### ISSUE TITLE
Dagit config editor string escaping

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1000]
Seems like I should be able to do this and escape a " character in a string:

![image](https://user-images.githubusercontent.com/609349/54858572-c7be1380-4cc2-11e9-921d-c956bb2f6c7a.png)

**Comment by schrockn** [comment]
@bengotow do you think another thing to add here would be an escape hatch to disable autocomplete and schema checking for unanticipated issues like this?
