### ISSUE TITLE
Dagit - supply filesystem path config types with autocompletion out of the box

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1001]
Presumably a common use case for config is supplying a local path "/foo/bar" - would be awesome to give automatic type-ahead path completion on these paths

**Comment by bengotow** [comment]
This would be really cool and I don't think it's terribly hard, but we'd need to create a route / query that essentially let you `ls` any directory on the filesystem - would that be acceptable? Doesn't seem harmful to me but it might be something we'd want to turn off in hosted Dagit. (cc @natekupp)

**Comment by catherinewu** [comment]
discussed w. nate that this “create a route / query that essentially let you ls any directory on the filesystem” isn't worth doing. closing issue
