### ISSUE TITLE
Load asset by  Materialize all with configurable resources

### ISSUE THREAD

**Issue by lilinxi** [dagster-io/dagster#10027]
### Dagster version

1.0.12

### What's the issue?

I am using the 1.0.12 dagit but it seems that I meet this issue #8677 again, when I trigger the Materialize all button, it tells me that there is a resource config miss but do not have place to add them.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@lilinxi - any chance you have you have a code sample we'd be able to reproduce this with?

**Comment by sryza** [comment]
I'm going to close this because haven't heard back, but feel free to reopen.
