### ISSUE TITLE
Cannot pass dictionary config to partitioned asset job

### ISSUE THREAD

**Issue by erinov1** [dagster-io/dagster#10041]
### Dagster version

1.0.13

### What's the issue?

If I define a partitioned asset job using `define_asset_job`, then I cannot pass in a static dictionary as config (only a `PartitionedConfig`). For example:

```python
daily_partitions_def = DailyPartitionsDefinition(
    start_date="2022-10-13",
)

@op(config_schema={"my_config": str})
def my_op(context):
    return None

my_asset = AssetsDefinition.from_op(op_def=my_op, partitions_def=daily_partitions_def)

my_asset_job = define_asset_job(
    name="my_asset_job",
    selection=AssetSelection.assets(my_asset),
    config={
        "ops": {"my_op": {"config": {"my_config": "Hello!"}}},
    },
    partitions_def=daily_partitions_def
)
```

Executing this job raises ```dagster._check.CheckError: Invariant failed. Description: Can't supply a ConfigMapping for 'config' when 'partitions_def' is supplied.``` When the job is not partitioned this works fine.

### What did you expect to happen?

Users should be able to pass static config that will apply to all partitions.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @erinov1 . This should fix it: https://github.com/dagster-io/dagster/pull/10057.
