### ISSUE TITLE
Partitions don't display properly for schedules

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#10060]
The schedule page has a column for "partition set", which claims to provide information about the execution status of each partition with regards to that schedule. This seems to be blank for jobs. 
Repro: run dagit on toys; check out the schedule page for `longitudinal_schedule` (the corresponding job has partitioned config). You'll notice that the partition set column is blank.

Additionally, the terminology "partition set" is out of date (we don't actually expose the name partition set anywhere anymore). We should change this to just refer to "partitions"

**Comment by sryza** [comment]
Arguably, we should get rid of this column. Post-CRAG, schedules don't themselves have partitions - the jobs that they point to do.

**Comment by dpeng817** [comment]
> Arguably, we should get rid of this column. Post-CRAG, schedules don't themselves have partitions - the jobs that they point to do.

That's right, but it could still be useful to, from the schedules tab, see which partitions are materialized (given that run requests have a partition key attached).

**Comment by hellendag** [comment]
This column will not be included in the new virtualized version of the Schedules table.

**Comment by hellendag** [comment]
> That's right, but it could still be useful to, from the schedules tab, see which partitions are materialized (given that run requests have a partition key attached).

Can you provide a screenshot of what you mean?

**Comment by dpeng817** [comment]
I think it would be hard to produce a screenshot, but essentially since only a single job can be triggered by a schedule, being able to view into which partitions have / have not run could be nice.

**Comment by sryza** [comment]
> I think it would be hard to produce a screenshot, but essentially since only a single job can be triggered by a schedule, being able to view into which partitions have / have not run could be nice.

FWIW, you can get there nowadays by clicking on the job and looking at the partitions tab.

**Comment by sryza** [comment]
> I think it would be hard to produce a screenshot, but essentially since only a single job can be triggered by a schedule, being able to view into which partitions have / have not run could be nice.

FWIW, you can get there nowadays by clicking on the job and looking at the partitions tab.

**Comment by sryza** [comment]
> I think it would be hard to produce a screenshot, but essentially since only a single job can be triggered by a schedule, being able to view into which partitions have / have not run could be nice.

FWIW, you can get there nowadays by clicking on the job and looking at the partitions tab.
