### ISSUE TITLE
in built-in object IO managers, handle loading objects for multiple partitions

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#10120]
If a daily asset depends on an hourly asset, then each partition of the daily asset will correspond to 24 partitions of the hourly asset.

When materializing the daily asset and `load_input` is called to load the contents of the hourly asset, we should return the contents of those 24 partitions.

For the Pandas type handler of the Snowflake IO manager, we handle this by returning a single dataframe that contains the concatenated contents of all the hourly partitions.

For the built-in object store IO managers, we could just return a list of the pickled objects. Or potentially a dictionary keyed by partition?

What we've heard:
- 2022-10-20: https://dagster.slack.com/archives/C01U954MEER/p1666175125167899

Here's a start on the implementation:
```python
from dagster import io_manager, IOManager, AssetKey


@io_manager
def my_io_manager():
    return MyIOManager()


class MyIOManager(IOManager):
    def handle_output(self, context, obj):
        ...

    def _load(self, asset_key: AssetKey):
        ...

    def _load_partition(self, asset_key: AssetKey, partition_key: str):
        ...

    def load_input(self, context):
        if context.has_asset_partitions:
            partition_key_range = context.asset_partition_key_range
            if partition_key_range.start == partition_key_range.end:
                return self._load_partition(context.asset_key, partition_key_range.start)
            else:
                return [
                    self._load_partition(context.asset_key, partition_key)
                    for partition_key in context.asset_partition_keys
                ]
        else:
            return self._load(context.asset_key)
```

**Comment by andrewgryan** [comment]
@sryza would a generator make more sense? I'm leaning towards key, value pairs to be most general. E.g.

```python
    # inside load_input() method
    yield partition_key, self._load_partition(...)
```

For example, when each hourly partition fits in RAM but all 24 partitions loaded together exceed available memory. It might be more useful to allow a consuming asset to process one partition at a time. It may also allow the consuming code to decide what container is best for their situation.

Also, I'm happy to take this on as a PR, if the sketched out code above is a good approach. Also, I'll need to read up on the contributor guidelines and the dagster machinery for processing the return value of `load_input`

**Comment by andrewgryan** [comment]
Actually, this is a bit harder than I first thought. Testing it using `materialize_to_memory` is proving tricky since all assets need to share the same `partitions_def`.

Example, TDD attempt to capture the problem.

```python
from dagster import (
    asset,
    materialize_to_memory,
    DailyPartitionsDefinition,
    HourlyPartitionsDefinition,
)
from pytest import fixture
import datetime


@fixture
def start():
    return datetime.datetime(2022, 1, 1)


@fixture
def hourly(start):
    return HourlyPartitionsDefinition(start_date=f"{start:%Y-%m-%d-%H:%M}")


@fixture
def daily(start):
    return DailyPartitionsDefinition(start_date=f"{start:%Y-%m-%d}")


def test_partitioned_io_manager(hourly, daily):
    @asset(partitions_def=hourly)
    def hourly_asset():
        return 42

    @asset(partitions_def=daily)
    def daily_asset(hourly_asset):
        return hourly_asset

    result = materialize_to_memory([hourly_asset, daily_asset], partition_key="2022-01-01")
    assert result.output_for_node("daily_asset") == 42
```

`dagster._core.definitions.asset_job` has a check to make sure all assets have the same partitions_def. Which is a very sensible check to reduce the complexity of supporting mix/match partition_keys.

**Comment by sryza** [comment]
> @sryza would a generator make more sense?

Interesting - this isn't a pattern that we've used before with IO managers, but I think it makes sense.

> Testing it using materialize_to_memory is proving tricky since all assets need to share the same partitions_def.

You could do something like this:

```
materialize([*hourly_asset.to_source_assets(), daily_asset], partition_key="2022-01-01")
```

That will run `load_input` for `daily_asset` without trying to materialize `hourly_asset` in the same run.

**Comment by andrewgryan** [comment]
Thanks for the tips for writing tests, it is working as expected and the io_manager development is matching your pseudo-code nicely.

**Comment by andrewgryan** [comment]
@sryza I've submitted a PR that addresses the issues discussed so far, I have a few design concerns of my own but I will wait and see what you think of this attempt at solving the problem.

**Comment by andrewgryan** [comment]
I also think a syntax to be more specific for higher frequency asset dependencies would be useful, but out of scope for this ticket. In some cases not all overlapping partitions are required, it would be nice to specify e.g. `hourly_asset['-3H']` or something similar

**Comment by sryza** [comment]
> I also think a syntax to be more specific for higher frequency asset dependencies would be useful, but out of scope for this ticket. In some cases not all overlapping partitions are required, it would be nice to specify e.g. hourly_asset['-3H'] or something similar

You might already be aware of this, but you could define a custom `PartitionMapping` to express this
