### ISSUE TITLE
I/O manager InputContext.dagster_type is incorrect with input assets

### ISSUE THREAD

**Issue by peay** [dagster-io/dagster#10126]
### Dagster version

dagster, version 1.0.13

### What's the issue?

When an asset takes as input another asset that has a `dagster_type` defined, this type is not correctly made available to the I/O manager in `load_input` via `InputContext`.

In the example below, when materializing `test2_spark_df`, in the I/O manager when reading the `test_spark_df` input, `input_context.dagster_type` is `pyspark.sql.dataframe.DataFrame`, and the  underlying `StepInput` object is:

```py
StepInput(
  name='test_spark_df',
  dagster_type_key='_TypeHintInferred[pyspark.sql.dataframe.DataFrame]'
)
```

### What did you expect to happen?

`input_context.dagster_type` should be the Dagster type of the input asset -- i.e., in the example below, it should be `TestSparkDF`

### How to reproduce?

```py
from dagster import IOManager, InputContext, io_manager
from dagster import OpExecutionContext, DagsterType, asset
from pyspark.sql import DataFrame

TestSparkDF = DagsterType(name="TestSparkDF", type_check_fn=lambda _, v: True)
Test2SparkDF = DagsterType(name="Test2SparkDF", type_check_fn=lambda _, v: True)

class _CheckInputTypeIOManager(IOManager):
    def load_input(self, input_context: InputContext) -> DataFrame:
        if input_context.dagster_type != TestSparkDF:
            raise RuntimeError(f"Input Dagster type was {input_context.dagster_type}")
            
        return spark.range(10)  # Dummy impl. to reproduce

    def handle_output(self, context, obj):
        pass


@io_manager
def check_input_type_io_manager():
    return _CheckInputTypeIOManager()


@asset(
    dagster_type=TestSparkDF,
    required_resource_keys={"pyspark"},
    io_manager_def=check_input_type_io_manager
)
def test_spark_df(context: OpExecutionContext) -> DataFrame:
    spark = context.resources.pyspark.spark_session
    return spark.range(10)


@asset(
    dagster_type=Test2SparkDF,
    required_resource_keys={"pyspark"},
    io_manager_def=check_input_type_io_manager,

    # Materializing this asset will fail. However, it works if we add:
    # ins={"test_spark_df": AssetIn(test_spark_df.asset_key, dagster_type=TestSparkDF)}
)
def test2_spark_df(test_spark_df: DataFrame) -> DataFrame:
    return test_spark_df
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by peay** [comment]
I'd like to fix this one but I am not sure about the best course of action.

One option would be to update `build_assets_job`: [after resolving asset dependencies](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/assets_job.py#L153), we should have the correct Dagster types for all of the assets involved. When building the graph right after, we'd do:

```py
    graph = GraphDefinition(
        name=name,
        node_defs=[resolve_missing_dagster_types(asset.node_def for asset in assets) for asset in assets],   # <---
        dependencies=deps,
        description=description,
        input_mappings=None,
        output_mappings=None,
        config=None,
    )
```

where `resolve_missing_dagster_types` would go over all the `In`s of the `node_def`, and try to replace any type set to `NoValueSentinel` by looking up the right type.

Does that plan make sense?

**Comment by sryza** [comment]
Hey @peay - I believe this is the expected behavior - Dagster types don't propagate to from the upstream output to the downstream input.  Changing that behavior at this point would be a breaking change for users who are relying on the previous behavior.

However, I would expect this to work:
```python
    def load_input(self, input_context: InputContext) -> DataFrame:
        if input_context.upstream_output.dagster_type != TestSparkDF:
            raise RuntimeError(f"Input Dagster type was {input_context.dagster_type}")
            
        return spark.range(10)  # Dummy impl. to reproduce
```

(Note the  `upstream_output`)

**Comment by peay** [comment]
Thanks @sryza, I gave it a try but `input_context.upstream_output.dagster_type` doesn't seem to work, it raises:

> dagster._core.errors.DagsterInvariantViolationError: Attempting to access dagster_type, but it was not provided when constructing the OutputContext

`input_context.upstream_output.asset_info` is set, but `AssetOutputInfo` has no property about the Dagster type. 

Would it make sense to either add an `asset_info.dagster_type` property (to avoid changing the behavior on either `input_context.upstream_output.dagster_type` or `input_context.dagster_type`), or to make sure `input_context.upstream_output.dagster_type` is populated instead?

**Comment by sryza** [comment]
I see what's going on here: if the upstream asset isn't part of a run, then we represent it as a `SourceAsset` within the `AssetLayer` for the run. But `SourceAsset` doesn't have a `dagster_type` field, so the information gets lost.

So I think the most straightforward thing to do here would be to add a `dagster_type` field to `SourceAsset` and thread it through.

That said, the concept of a dagster type is arguably a little undefined for a source asset. A dagster type basically represents a "check" function that gets run on the Python value corresponding to the function argument or return value that the type is attached to, but source assets aren't associated with functions.

Curious: did you consider including this information on the asset's `metadata` instead of its dagster type? Did that present any downsides?

**Comment by peay** [comment]
I had tried using `input_context.metadata`, and it suffered from the same problem: the metadata set in the asset definition was not being propagated (although it was when passing the metadata directly via `AssetIn`). Is this also the expected behavior?

However, based on your suggestion, I just checked `input_context.upstream_output.metadata` and the asset metadata does seem to be propagated there, so I think this would be good enough!

If that's useful, I could prepare a small doc PR to clarify the docstrings for `InputContext.dagster_type` and `InputContext.metadata`, to reflect that these may not be set even though the corresponding asset has the properties, and mostly correspond to information set explicitly in `In` or `AssetIn`.

**Comment by sryza** [comment]
> I had tried using input_context.metadata, and it suffered from the same problem: the metadata set in the asset definition was not being propagated (although it was when passing the metadata directly via AssetIn). Is this also the expected behavior?

That is the expected behavior

> However, based on your suggestion, I just checked input_context.upstream_output.metadata and the asset metadata does seem to be propagated there, so I think this would be good enough!

Glad there's something that works for you!

> If that's useful, I could prepare a small doc PR to clarify the docstrings for InputContext.dagster_type and InputContext.metadata, to reflect that these may not be set even though the corresponding asset has the properties, and mostly correspond to information set explicitly in In or AssetIn.

That would definitely be useful!
