### ISSUE TITLE
Dagit: Clearer visual indicators of solid type

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1014]
In Airflow, one thing that's really helpful when scanning a DAG is differently colored operator instances to indicate whether something is a Spark job, or a SQL query, or whatever it might be, something like the below (fill color is operator type, border color is execution state):

![image](https://user-images.githubusercontent.com/609349/54942933-6af27100-4eed-11e9-97dd-a2408e3c477e.png)

Would be awesome if `dagit` had configurable `Solid` colors, so that when looking at a zoomed-out DAG of hundreds of solids you can quickly identify what's what.

@bengotow would love your thoughts on this one!

**Comment by alangenfeld** [comment]
I think the `kind` tags that generate different colored boxes in the corners covers this.
