### ISSUE TITLE
Dagit YAML editor behavior on Ctrl+A

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1015]
When editing a string config in dagit, I often hit <kbd>CTRL</kbd>+<kbd>A</kbd> to skip to the beginning of the line. In the screenshot below, I'd expect that to jump the cursor to right before the "s" in "spark_config"; instead, it goes to the beginning of the line and opens the auto-complete, which isn't what I want. I find myself repeatedly having to hit Esc and then manually edit my selection.

![image](https://user-images.githubusercontent.com/609349/54943307-3af79d80-4eee-11e9-85d7-0528b2e81713.png)

**Comment by natekupp** [comment]
https://dagster.phacility.com/D3366

**Comment by bengotow** [comment]
This is /mostly/ resolved by https://dagster.phacility.com/D5630 (it now goes to the start of the line AFTER whitespace), but I was unable to stop the autocompletion (for the same reason you noticed in D3366). We could add some state tracking, but it appears there isn't enough data within onKeyUp to filter out this case.
