### ISSUE TITLE
upstream changed indicator on the assets view has false negative cases

### ISSUE THREAD

**Issue by aroig** [dagster-io/dagster#10160]
### Dagster version

commit ca87aa3c95204c7941e675318f714d24a4990132

### What's the issue?

The "upstream changed" tag for assets, is based on materialization time comparison between an asset and its dependencies. This is subject to a race condition.

Let's say we have asset_1, that materializes in 1 second. asset_2 that materializes in 10. Then trigger a materialization of asset_2 only. When the run has started, trigger a materialization of asset_1. Most probably asset_1 will materialize before asset_2, yet asset_2 used stale data, because it started running before asset_1 materialization started.

The timeline is something like this. It is allowed because two separate runs can execute concurrently, and no dependency check is done across runs.
```
asset_1                        *---------*
asset_2                *--------------------------*
```

### What did you expect to happen?

I would expect that upstream_changed has no false negatives, meaning a case where it says nothing, but data for asset 1 has actually changed after asset_2 materialization started. So, in the situation explained above, I would expect an "upstream changed" tag.

False positives are ok, I think, i.e. saying upstream changed when data can potentially have changed, even if it has not in reality.

### How to reproduce?

On the following code

```python
import random
import time
import dagster


@dagster.asset(
    group_name="all"
)
def asset_1(context):
    time.sleep(1)
    x = random.randint(0, 1000000000)
    return dagster.Output(x, metadata={"lucky_number": x})

@dagster.asset(
    group_name="all"
)
def asset_2(asset_1: int):
    time.sleep(10)
    return dagster.Output(asset_1, metadata={"lucky_number": asset_1})

job_all = dagster.define_asset_job(
    name="all",
    selection=dagster.AssetSelection.groups("all")
)

@dagster.repository
def my_repository():
    return [
        asset_1,
        asset_2,
        job_all,
    ]
```

* Materialize both assets in a single run. Observe that both have the same value for "lucky_number" in the materialization metadata. No "upstream changed" tag is shown.
* Materialize asset_2 only. Wait 5 seconds, and then materialize asset_1. Observe that no "upstream changed" tag is shown, yet both assets have a different value for the "lucky_number" metadata.

### Additional information

One way to do the "upstream changed" check that seems more reliable than using times (which are subject to how runs are scheduled) would be by tracking the run_id  that materialized the dependencies of an asset, on the materialization events. If for any dependency of asset_2, the current last run_id that touched the dep, is different from the run_id that asset_2 tracked in its own materialization, then flag as "upstream changed".

A mechanism like this, could be extended in different ways:
- track also a user-provided version number for the code that produces the asset on materialization. If the version of the code is bumped, mark the asset as "upstream changed".
- Here the run_id of the dependencies, serves as "data version". If instead of tracking run_id that produced the deps, we tracked a hash of the actual data, it would reduce false positives: if asset_1 is materialized after asset_2, but the data is the same, we would not show "upstream changed". 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I agree that this is problematic behavior that we should fix.

> track also a user-provided version number for the code that produces the asset on materialization. If the version of the code is bumped, mark the asset as "upstream changed".
> Here the run_id of the dependencies, serves as "data version". If instead of tracking run_id that produced the deps, we tracked a hash of the actual data, it would reduce false positives: if asset_1 is materialized after asset_2, but the data is the same, we would not show "upstream changed".

@smackesey is actually implementing something exactly along these lines. @smackesey - mind linking to the relevant PRs to provide context?  Up to this point, we had been thinking about it as only something we would use if users explicitly supply a code version, but, as you point out, it might make sense to use for calculating Upstream Changed in general.

**Comment by aroig** [comment]
Thanks! I've seen the stream of PRs on #10167 I am looking forward to this!

**Comment by aroig** [comment]
After the asset versioning changes in version 1.1.2, I think this issue can be closed. As far as I understand old "upstream changed" is no longer exposed, isn't it?

**Comment by sryza** [comment]
@aroig - yup! The new "Stale" indicator should no longer have these negatives.
