### ISSUE TITLE
Dagit: make whitespace rendering configurable

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1016]
In dagit, whitespace is rendered as dots - would love to be able to toggle this off, it's not how I usually configure my editor :)

**Comment by mgasner** [comment]
cc @bengotow

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by mgasner** [comment]
This is going to be tricky to turn on and off because of how it's implemented: https://github.com/dagster-io/dagster/pull/354/files

**Comment by natekupp** [comment]
hm can we just toggle the CSS class based on a checkbox or something?
