### ISSUE TITLE
Deprecate legacy asset keys

### ISSUE THREAD

**Issue by clairelin135** [dagster-io/dagster#10240]
We've been using the new asset key version since `0.9.19`. We should deprecate the legacy asset keys in the next major release to reduce compute time for our event log queries

**Comment by plaflamme** [comment]
This is particularly painful on relatively large `event_log` tables (3.1M rows). Here's an example of the latency difference it can cause for a query that is executed thousands of times per hour under normal operation for my instance (I'm not sure what triggers this query, but it's quite frequent during backfilling):

```
EXPLAIN ANALYZE SELECT event_logs.id, event_logs.event 
FROM event_logs 
WHERE event_logs.dagster_event_type = 'ASSET_MATERIALIZATION' AND (event_logs.asset_key = '["not", "the "real" "key"]' OR event_logs.asset_key = 'not.the.real.key') ORDER BY event_logs.id DESC 
 LIMIT 1;
                                                                      QUERY PLAN                                                                       
-------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.43..280.12 rows=1 width=831) (actual time=246.699..246.701 rows=1 loops=1)
   ->  Index Scan Backward using idx_event_type on event_logs  (cost=0.43..129776.03 rows=464 width=831) (actual time=246.698..246.699 rows=1 loops=1)
         Index Cond: (dagster_event_type = 'ASSET_MATERIALIZATION'::text)
         Filter: ((asset_key = '["not", "the "real" "key"]'::text) OR (asset_key = 'not.the.real.key'::text))
         Rows Removed by Filter: 21649
 Planning Time: 0.151 ms
 Execution Time: 246.728 ms
(7 rows)
```

vs

```
EXPLAIN ANALYZE SELECT event_logs.id, event_logs.event 
FROM event_logs 
WHERE event_logs.dagster_event_type = 'ASSET_MATERIALIZATION' AND (event_logs.asset_key = '["not", "the "real" "key"]') ORDER BY event_logs.id DESC 
 LIMIT 1;
                                                                     QUERY PLAN                                                                      
-----------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.55..1.59 rows=1 width=831) (actual time=1.655..1.657 rows=1 loops=1)
   ->  Index Scan Backward using idx_events_by_asset on event_logs  (cost=0.55..481.68 rows=462 width=831) (actual time=1.654..1.655 rows=1 loops=1)
         Index Cond: ((asset_key = '["not", "the "real" "key"]'::text) AND (dagster_event_type = 'ASSET_MATERIALIZATION'::text))
 Planning Time: 0.255 ms
 Execution Time: 1.688 ms
(5 rows)
```

This is ~150 times faster.

Sometimes, we get lucky and the planner uses a different version using two index scans for both keys and then merges the result, but it's still ~2x slower than the query with a single key.

The first version of dagster I used was 1.1.10. It's unfortunate that I have to pay this cost for compatibility I don't need.

**Comment by prha** [comment]
It should be safe to remove the legacy check in `1.2.0`.  The data migration shouldn't take long to write but will defer to you about the weight of keeping it around... We did not have that many users using assets pre `0.10.0`.

**Comment by plaflamme** [comment]
In the meantime, for anyone else impacted by this and that do not require compatibility, [here's a commit](https://github.com/plaflamme/dagster/commit/2e344fc458c897dabb335424d727da651e96a341) you can apply on top `1.1.19` to "fix" this.
