### ISSUE TITLE
Metadata defined via AssetsDefinition.from_graph not accessible in IO Manager

### ISSUE THREAD

**Issue by PascalStehling** [dagster-io/dagster#10243]
### Dagster version

dagster, version 1.0.15

### What's the issue?

When defining metadata in the `AssetsDefinition.from_graph` function via the `metadata_by_output_name` parameter, its not accessible in the IO Manager OutputContext parameter from the `handle_output` function. But the Metadata is shown via in the Dagit UI for the Asset.

### What did you expect to happen?

The Metadata defiend via the `metadata_by_output_name` parameter of the `AssetsDefinition.from_graph` should accessible via OutputContext.metadata in the IO Manager.

### How to reproduce?

To reproduce use the following Code snippet with `dagit -f test.py`. 

If you Materialize the `hello_world_asset` Asset the same metadata that is shown for the Asset metadata is logged in the info field.

But when Materializing the `hello_world_graph` Asset, the metadata defined for the graph is not availible.

What should happen is, that with both Methods, using the OutputContext.metadata, the defined metadat should be ruturned.

```py
from typing import Any
from dagster import AssetsDefinition, IOManager, InputContext, Out, OutputContext, asset, graph, io_manager, op, repository


class MyIoManager(IOManager):

    def handle_output(self, context: OutputContext, obj: Any) -> None:
        context.log.info(context.metadata)
        context.log.info(obj)

    def load_input(self, context: InputContext) -> Any:
        return ""


@io_manager
def my_io_manager() -> MyIoManager:
    return MyIoManager()


@asset(metadata={"key": "asset op"}, io_manager_def=my_io_manager)
def hello_world_asset() -> str:
    return "Hello World"


@op
def hello() -> str:
    return "Hello"


@op(out=Out(io_manager_key="io_man"))
def world(inp: str) -> str:
    return inp + " World"


@graph
def hello_world_graph() -> str:
    h = hello()
    return world(h)


hello_world_graph_asset = AssetsDefinition.from_graph(
    hello_world_graph,
    metadata_by_output_name={"result": {
        "key": "metadata in graph"
    }},
    resource_defs={"io_man": my_io_manager})


@repository
def repo() -> list:
    return [hello_world_asset, hello_world_graph_asset]

```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @PascalStehling.  I agree that this is a bug.

It looks like the root there's some inconsistency in how we handle metadata for different ways of constructing assets:
- If using the `@asset` or `@multi_asset` decorator, we put the metadata on the `Out` of the `op` that we build and put inside the `AssetsDefinition` we construct.
- If using `AssetsDefinition.from_graph` or `AssetsDefinition.from_op`, we supply it to the `metadata_by_key` property of the `AssetsDefinition` we construct.

The most straightforward fix would be to change `get_output_context` in context/output.py to use the metadata from `AssetLayer.metadata_for_asset()`, if the `Out` has no metadata on it.

For consistency, we might also want to fill in `metadata_by_key` on the `AssetsDefinition` even when using `@asset` or `@multi_asset`.

**Comment by PascalStehling** [comment]
Hi @sryza, first thanks for acknowledging the Issue.

Second, Im not sure if I should make a new Issue for that, so I will post it here first. There is another inconsistency/problem with Assets defiend via "AssetsDefinition.from_graph".

The Description, which is shown for an Asset, is the one of the last OP in an Asset defiend via the AssetsDefinition.from_graph and not the Description of the Graph.

In the Example below, the Description of the Asset should be "Hello World Asset based on AssetsDefinition.from_graph" but it is "Op that appends 'World' to string".

To reproduce it, just run the following code via dagit and look at the descriptions of the Assets:
```py
from dagster import AssetsDefinition, asset, graph, op, repository


@asset
def hello_world_asset() -> str:
    "Hello World Asset based on @asset Decorator"
    return "Hello World"


@op
def hello() -> str:
    "Op that returns Hello"
    return "Hello"


@op
def world(inp: str) -> str:
    "Op that appends 'World' to string"
    return inp + " World"


@graph(description="SOme other description")
def hello_world_graph() -> str:
    "Hello World Asset based on AssetsDefinition.from_graph"
    h = hello()
    return world(h)


hello_world_graph_asset = AssetsDefinition.from_graph(hello_world_graph)


@repository
def repo() -> list:
    return [hello_world_asset, hello_world_graph_asset]
```

Have a great day and keep on the Good work :)
