### ISSUE TITLE
Dagit should probably be more permissive about solid-level config

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1025]
Specifically, when we are executing a subset of the DAG, it may not make sense to error when config is present for solids we don't happen to be selecting at a given moment, since we can just filter those out of the type check.

cc @schrockn

**Comment by mgasner** [comment]
cc @bengotow

**Comment by mgasner** [comment]
We could provide display cues, like greying out/striking through the config that is valid but does not apply to the selected subset

**Comment by bengotow** [comment]
Going to close this since we're going to rebuild scaffolding in #1139 and it's been temporarily removed from Dagit.
