### ISSUE TITLE
Strange errors in dagit

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1026]
![Screen Shot 2019-03-25 at 1 43 00 PM](https://user-images.githubusercontent.com/427016/54952809-13133480-4f04-11e9-81a3-7c0257ddbfea.png)

**Comment by schrockn** [comment]
@mgasner have you continued to see this? I believe they may have been resolved by @bengotow

**Comment by schrockn** [comment]
@mgasner I'm going to go ahead and close this for now as we haven't seen this in awhile. If it crops up again we can reopen with a more specific repro
