### ISSUE TITLE
[docs issue] trying "Fully Featured" project and getting error out of the box ("symbol not found in flat namespace (_CFRelease)")

### ISSUE THREAD

**Issue by sw-yx** [dagster-io/dagster#10262]
### What's the issue or suggestion?

i wanted to try https://docs.dagster.io/guides/dagster/example_project

made a new venv, and ran `pip install dagster dagit`.

Then ran 

```
dagster project from-example \
    --name my-dagster-project \
    --example project_fully_featured
```

got this

![image](https://user-images.githubusercontent.com/6764957/198864891-250be3cc-0fb3-468f-aad6-65dcf5ef8555.png)

### Additional information

requirements.txt

```
alembic==1.8.1
aniso8601==7.0.0
anyio==3.6.2
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.1.3
coloredlogs==14.0
croniter==1.3.7
dagit==1.0.15
dagster==1.0.15
dagster-graphql==1.0.15
docstring-parser==0.15
gql==2.0.0
graphene==2.1.9
graphql-core==2.3.2
graphql-relay==2.0.1
grpcio==1.47.2
grpcio-health-checking==1.43.0
h11==0.14.0
httptools==0.5.0
humanfriendly==10.0
idna==3.4
Jinja2==3.1.2
Mako==1.2.3
MarkupSafe==2.1.1
packaging==21.3
pendulum==2.1.2
promise==2.3
protobuf==3.20.3
pyparsing==3.0.9
python-dateutil==2.8.2
python-dotenv==0.21.0
pytz==2022.5
pytzdata==2020.1
PyYAML==6.0
requests==2.28.1
Rx==1.6.1
six==1.16.0
sniffio==1.3.0
SQLAlchemy==1.4.42
starlette==0.21.0
tabulate==0.9.0
toposort==1.7
tqdm==4.64.1
typing-compat==0.1.0
typing_extensions==4.4.0
urllib3==1.26.12
uvicorn==0.19.0
uvloop==0.17.0
watchdog==2.1.9
watchfiles==0.18.0
websockets==10.4

```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sw-yx** [comment]
for other people searching and only finding #9728 

```
Traceback (most recent call last):
  File "/Users/swyx/Desktop/Work/trydagster/env/bin/dagster", line 5, in <module>
    from dagster.cli import main
  File "/Users/swyx/Desktop/Work/trydagster/env/lib/python3.9/site-packages/dagster/__init__.py", line 440, in <module>
    from dagster._core.host_representation.selector import (
  File "/Users/swyx/Desktop/Work/trydagster/env/lib/python3.9/site-packages/dagster/_core/host_representation/__init__.py", line 51, in <module>
    from .repository_location import (
  File "/Users/swyx/Desktop/Work/trydagster/env/lib/python3.9/site-packages/dagster/_core/host_representation/repository_location.py", line 10, in <module>
    from dagster._api.list_repositories import sync_list_repositories_grpc
  File "/Users/swyx/Desktop/Work/trydagster/env/lib/python3.9/site-packages/dagster/_api/list_repositories.py", line 6, in <module>
    from dagster._grpc.types import ListRepositoriesResponse
  File "/Users/swyx/Desktop/Work/trydagster/env/lib/python3.9/site-packages/dagster/_grpc/__init__.py", line 11, in <module>
    from .client import DagsterGrpcClient, client_heartbeat_thread, ephemeral_grpc_api_client
  File "/Users/swyx/Desktop/Work/trydagster/env/lib/python3.9/site-packages/dagster/_grpc/client.py", line 8, in <module>
    import grpc
  File "/Users/swyx/Desktop/Work/trydagster/env/lib/python3.9/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/swyx/Desktop/Work/trydagster/env/lib/python3.9/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/swyx/Desktop/Work/trydagster/env/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (_CFRelease)
```

**Comment by smackesey** [comment]
Hi @sw-yx, the `grpcio` package has been causing headaches wit hvarious Python versions on M1 for some time (are you on M1).

We'll try to figure out how to constrain the `grpc` package to fix this, but in the meantime could you try reinstalling `grpcio` with `pip install --no-binary :all: grpcio==1.47.2 --ignore-installed` and see if that solves the issue?

**Comment by sw-yx** [comment]
yup am on m1... will try

**Comment by sw-yx** [comment]
![image](https://user-images.githubusercontent.com/6764957/199624294-8c18fbc8-9465-4760-8103-e372c2de1d6e.png)

unfortunately no success

**Comment by Taytay** [comment]
I fixed this by putting the following in my requirements.txt:
`grpcio==1.51.3`

**Comment by zaneselvans** [comment]
I'm having the same or a related issue.

Any version of `grpcio` that I install using `pip` has the `_CFRelease` symbol not found error. However, if I install `grpcio==1.51.1` using conda/mamba in the same conda environment, then dagster / dagit seems to work fine.  Unfortunately that version is in conflict with dagster 1.1.21 requirements for `grpcio<1.48.1,>=1.32.0`.

Installing `grpcio==1.46.1` using mamba/conda also seems to work, but not with pip.

```
System:
  OS: macOS 13.2.1
  CPU: arm64 Apple M1 Pro
  Memory: 32 GB

Dagster: 1.1.21
```

**Comment by gibsondan** [comment]
Hi @zaneselvans - glad you have something that’s working for now. We’re actively working with the gRPC team to get this pin removed - feel free to keep it at 1.51.1 if it’s not causing you any problems at that version.

**Comment by zaneselvans** [comment]
@gibsondan Well.... it's not really working. There's no version that works when it's installed using `pip`.  I can install 1.46.1 independent of the package in the conda environment that I'm personally working in, but if someone else were to install it using pip, or in the environment created by Tox I think it's still going to fail -- at least under whatever circumstances are affecting me: @bendnorman is also on an M1 mac and isn't having this problem, for reasons we don't understand.

**Comment by gibsondan** [comment]
Got it - do the instructions here about adding a —find-links flag so that it will try to use our wheel help? https://docs.dagster.io/getting-started/install#installing-dagster-into-an-existing-python-environment

**Comment by zaneselvans** [comment]
First I tried adding the `--find-links` to the `pip` section of my `environment.yml`:

```yaml
  - pip:
      - --find-links https://github.com/dagster-io/build-grpcio/wiki/Wheels
      - --editable ../[doc,test,dev,datasette]
```
I rebuilt the environment but I still got the `_CFRelease` error.

Then I uninstalled `dagster`, `dagit` and `grpcio` and reinstalled `dagster` & `dagit` directly using `pip`:

```bash
pip uninstall dagster dagit grpcio
pip install dagster dagit --find-links=https://github.com/dagster-io/build-grpcio/wiki/Wheels
```
but I still got the `_CFRelease` error.

Then I tried doing above, but with the `pip` cache disabled:
```
pip uninstall dagster dagit grpcio
pip install dagster dagit --no-cache-dir --find-links=https://github.com/dagster-io/build-grpcio/wiki/Wheels
```

but I still got the `_CFRelease` error.

In all of these cases, I ended up with `grpcio==1.47.5` installed.

**Comment by gibsondan** [comment]
I see - looks like we may need to get the grpcio pin removed after all. Last question - what version of Python are you using?

**Comment by zaneselvans** [comment]
I'm on Python 3.10.9.

**Comment by jmccartin** [comment]
Going to report in with my own findings surrounding this issue. I am on the very latest version of dagster (1.31), and I receive this error with a virtual environment created in Python 3.10.8. If I create the same environment with a Python 3.9.16 executable, then the error goes away. Forcing any version of `grpcio` using pip does not remedy the issue.

M1 Max, OS Ventura (13.3.1)
