### ISSUE TITLE
partitions page shows runs from multiple repositories

### ISSUE THREAD

**Issue by adam-bloom** [dagster-io/dagster#10276]
### Dagster version

1.0.13

### What's the issue?

When looking at per-step status on the partitions page (for an asset), selecting a partition brings up a "view runs" link. That runs link (and count displayed for the link) are showing runs across multiple repositories. There's likely a missing filter in this query.

![image](https://user-images.githubusercontent.com/3771193/199113371-e71e615f-6450-4c05-8d9c-63f55e869cfa.png)

### What did you expect to happen?

I expected to only see runs for this particular asset, not runs with the same partition/job name in another repository.

### How to reproduce?

Two repositories, asset backed partitioned job with the same name in both. Run both jobs for the same partition and then look at the partitions tab for both jobs.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Thanks @adam-bloom, we'll address this.
