### ISSUE TITLE
Add a volumes and volumeMounts key to the helm chart

### ISSUE THREAD

**Issue by tsungchih** [dagster-io/dagster#10282]
### What's the use case?

When deploying Dagster with an existing external Postgresql database using SSL, we need to configure Dagit and Dagster daemon to establish SSL connection to the target database. With the current version of dagster helm chart, we can have it done by configuring `postgresql.postgresqlParams` in the custimized values file. However, there has no entry for users to mount the required certificates in Dagit and Dagster daemon.

### Ideas of implementation

Add a volumes and volumeMounts key to the helm chart that would allow users to configure additional volumes and the corresponding volume mounts.

### Additional information

I have made modifications to templates and schema for adding additional volumes and volume mounts to Dagit and Dagster daemon. After that, Dagit and Dagster daemon are able to establish SSL connection to an existing external Postgresql database.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
This is in master now and will go live in the release later this week.
