### ISSUE TITLE
A weird backward slash is appearing in the asset description in the Global Lineage view

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#10331]
### Dagster version

1.0.15

### What's the issue?

![image](https://user-images.githubusercontent.com/49863538/199753034-f0cf4e32-815d-4044-b7a9-585fc4796685.png)

This slash isn't rendered in the Asset Details page. It doesn't exist in the asset definition code too, of course.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by danielgafni** [comment]
The same happens in 1.0.16

**Comment by smackesey** [comment]
cc @bengotow @hellendag

This also occurs in the `assets_pandas_type_metadata` example, where it occurs with an "&" in an asset description. Has something to do with the markdown processing of special characters in dagit.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1531373/200407639-21504242-3a85-4e4d-8734-d945ce01d229.png">
