### ISSUE TITLE
Add support for Permissive in the config editor

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1033]
In #1024 we added support for a permissive dictionary to the config type system, where the user can get away with bypassing the type system for certain configs. 

We should surface this in dagit somehow so that it's clear to the end-user what these are

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by catherinewu** [comment]
the current support in dagit for Permissive seems reasonable, going to close this issue
