### ISSUE TITLE
Dagit: UI shouldn't let me hit run again when a run is already in flight for the current run_id

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1037]
Maybe this button should be grayed out/locked while something is running? 

![image](https://user-images.githubusercontent.com/609349/55020503-2f6eaa00-4fb4-11e9-822b-4ceb62e9ed9f.png)

**Comment by bengotow** [comment]
Good catch - it looks like it actually is unclickable, but it certainly looks like you could click it again. Will see if we can change the color.

**Comment by mgasner** [comment]
This is fixed by #1043
