### ISSUE TITLE
Dagit: Float default value is 1, but the editor declares it invalid 

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1040]
See screenshot:

![image](https://user-images.githubusercontent.com/609349/55028639-744f0c80-4fc5-11e9-9b47-367ab40583f5.png)

**Comment by bengotow** [comment]
Hey! I think I've run in to this one elsewhere actually - the YAML implementation of "floats" requires the `.`: https://yaml.org/type/float.html, so I think that this error is technically correct unless the python validation allows `Float || Int`.

**Comment by mgasner** [comment]
probably the python config type should be implemented as a union of Float and Int and coerce to float() silently

**Comment by mgasner** [comment]
Also, we can enter 3.0 for Ints and it seems to just work

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by natekupp** [comment]
We don't auto-populate config anymore, so we can close this one
