### ISSUE TITLE
JobDefinition.execute_in_process not switching IO manager to mem_io_manager as per docs

### ISSUE THREAD

**Issue by northernSage** [dagster-io/dagster#10412]
### What's the issue or suggestion?

Dagster docs on https://docs.dagster.io/concepts/io-management/io-managers#built-in-io-managers state that:

> The default IO manager, [fs_io_manager](https://docs.dagster.io/_apidocs/io-managers#dagster.fs_io_manager), stores and retrieves values from pickle files in the local filesystem. If a job is invoked via [JobDefinition.execute_in_process](https://docs.dagster.io/_apidocs/jobs#dagster.JobDefinition.execute_in_process), **the default IO manager is switched to [mem_io_manager](https://docs.dagster.io/_apidocs/io-managers#dagster.mem_io_manager), which stores outputs in memory.**

However, this is not happening in practice and `fs_io_manager` is still being used with `execute_in_process`. We came across this issue after bumping dagster from 0.15.x to latest release, which caused one of our unit tests to blow up with the following:

```
test_regression_graph.py::test_download_and_train_no_time - TypeError: no default __reduce__ due to non-trivial __cinit__
...
pickle.dump(obj, write_obj, PICKLE_PROTOCOL)
File "stringsource", line 2, in _catboost._PoolBase.__reduce_cython__

```

The reason why pickling is breaking here is probably not relevant for this issue, but it happens when you try pickling a `Pool` object from `catboost` library (one can make it work by quantizing and using their provided `save` api). What's important here is that the `ops` in question is being executed with `execute_in_process` and it's clearly trying to pickle the object instead of storing it in memory.

To work around this, we had to:

```
       result: ExecuteInProcessResult = (
        train_and_save_traffic_shaping_server_classification_graph.execute_in_process(
            resources={
                "io_manager": mem_io_manager,   # added this line
                "clock": MockClock(),
            }
        )
    )
```
explicitly setting the `io_manager` to `mem_io_manager`

### Additional information

dagster version: latest
python release: 3.1
Execution environment: Debian latest

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@dpeng817 @johannkm mind taking a look?
