### ISSUE TITLE
Maybe guard against Graphene's bad habit of calling resolvers where `self` is not an instance of the class

### ISSUE THREAD

**Issue by bengotow** [dagster-io/dagster#1049]
Just ran in to a cryptic bug where this check was succeeding, but the object provided was not a pipeline run:

```
check.inst_param(pipeline_run, 'pipeline_run', PipelineRun)
```

It turns out that both of these are valid:
```
// passing the constructor
check.inst_param(PipelineRun, 'pipeline_run', PipelineRun)
// passing an instance
check.inst_param(PipelineRun( ... constructor args ...), 'pipeline_run', PipelineRun)
```

I think this is some magical python "the constructor and an instance are the same type" business, but it'd be really nice if check.inst_param could prevent this. It's easy to make this mistake in our codebase because we often dynamically retrieve constructors, like this:

```
graphene_info.schema.type_named('PipelineRun')(run) // don't forget to invoke!
```

cc @mgasner

**Comment by mgasner** [comment]
Yep, this is not true for ordinary classes but I think is true for classes on which graphene has done its metamagic

**Comment by mgasner** [comment]
http://docs.graphene-python.org/en/latest/types/objecttypes/#resolvers

**Comment by schrockn** [comment]
https://github.com/dagster-io/dagster/pull/1050

**Comment by mgasner** [comment]
I'm going to close this prospectively -- I think if we want to address this kind of thing (deep seated ergonomic issues with Graphene) we will probably end up doing it by writing a graphql layer in JS.

**Comment by mgasner** [comment]
Feel free to reopen if anyone feels strongly about this.
