### ISSUE TITLE
Make it more ergonomic to use partition mappings with non-argument deps

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#10508]
Here's currently the best way to do this:
```python
from dagster import Nothing

@asset(
    partitions_def=HourlyPartitionsDefinition(start_date="2023-01-01-00:00", timezone=DEFAULT_TIMEZONE),
    ins={
        "hourly_depends_on_past": AssetIn(
            dagster_type=Nothing,
            partition_mapping=TimeWindowPartitionMapping(start_offset=-1, end_offset=-1),
        )
    },
)
def hourly_depends_on_past(context):
    return 1
```

However, it's awkward that you need to deal with dagster types for this.

**Comment by marcinja** [comment]
Is this currently supported? Or is the currently recommended approach similar to what's described here: https://github.com/dagster-io/dagster/issues/11664#issuecomment-1380729209

i.e. `AssetIn` with `dagster_type=Nothing`

**Comment by sryza** [comment]
@marcinja it's currently supported using the approach described in that issue you linked. However, it's kind of awkward. I'm reopening this and framing it around making it more ergonomic.

**Comment by sryza** [comment]
`deps` and `AssetDep` address this issue
