### ISSUE TITLE
Allow ACL kwarg to be passed into S3 Computer Log Manager

### ISSUE THREAD

**Issue by DustyShap** [dagster-io/dagster#10507]
### What's the use case?

I am hoping to store the Compute Logs into S3 and display them in the Dagit UI. I would be doing this by way of the `computeLogManager` value in the Helm chart. In my case, though, I would require the ACL (access control list) kwarg to be passed into [the upload_fileobj method](https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-aws/dagster_aws/s3/compute_log_manager.py#L192)

### Ideas of implementation

In my case, it would require the Helm chart, specifically in the S3ComputeLogManager config, to get an ACL value passed to it.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
cc @prha

**Comment by DustyShap** [comment]
Thanks for attending to this issue @prha !  Deployed 1.1.8 and the logs are flowing to Dagit as well as AWS.

**Comment by prha** [comment]
Great!  Glad that's working for you
