### ISSUE TITLE
@repository doc block out-of-date

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#10505]
### What's the issue or suggestion?

The `@repository` decorator is out of date. It does not accurately say what definition types it accepts (no assets, mentioned for example) and also says it can accept RepositoryData instances, even though that is an abstract class.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
@schrockn I'm inclined to close this as we've moved to `Definitions` and `@repository` is no longer emphasized - 👍 ?

**Comment by schrockn** [comment]
sgtm
