### ISSUE TITLE
Missing description of `metadata_by_table_name` argument for `build_fivetran_assets ` in `dagster-fivetran`

### ISSUE THREAD

**Issue by mgierada** [dagster-io/dagster#10582]
### What's the issue or suggestion?

LInk to documentation: https://docs.dagster.io/_apidocs/libraries/dagster-fivetran

Part: 
![image](https://user-images.githubusercontent.com/23472449/202446904-e5664ba9-d37c-4e91-8570-0fa251567f42.png)

Version of `dagster_fivetran`
`__version__ = "0.16.17"` 

Issues: In a [source code](https://docs.dagster.io/_modules/dagster_fivetran/asset_defs#build_fivetran_assets) there is one more arg that can be passed `metadata_by_table_name` but its missing in documentation. I would love to see a description what it does and how to use it with some cool examples.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thoughts @benpankow ?
