### ISSUE TITLE
[Documentation Feedback] Problem on /tutorial/assets/non-argument-deps page

### ISSUE THREAD

**Issue by elementljarredc** [dagster-io/dagster#10580]
The intro makes it seem that we're going to deal with a different kind of asset type, because you don't know what kind of asset the op is going to materialize until it runs. 

Then we're talking about what assets are 

And their being bound to ops

and logging when assets are created. 

But we never really explain why assets might appear when we don't expect them to (or we don't know what they are ahead of time)

**Comment by sryza** [comment]
Closing because this page has been eliminated in the latest version of the tutorial
