### ISSUE TITLE
Allow to pass `group_name` as arg in `build_fivetran_assets` of `dagster_fivetran`

### ISSUE THREAD

**Issue by mgierada** [dagster-io/dagster#10583]
### What's the use case?

Currently (v.0.16.17) when using `build_fivetran_assets` method of `dagster_fivetran` it is not possible to set group name for assets. `default` is displayed all the time. It would be extremely useful to pass `group_name` as an argument, as it will allow for a better organisation and structure of a dagster assets.

As far as I am aware, the only way we can organise fivetran imported assets is by using `asset_key_prefix` which is okay for some cases but still we are missing a big picture how those assets interacts with each other. Also, the graph of global asset linage is less informative with all fivetran assets set to `default` group name.

### Ideas of implementation

Allow to pass additional argument `group_name` to `build_fivetran_assets` or add more generic one like `metadata`.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by carter293** [comment]
We have a multi-tenancy fivetran account. Doesn't make sense for us to sync all connectors for the account.

Workaround - Used the API to grab all connectors ids and names for a group and used that info to create dagster sync ops with an op factory.

**Comment by sryza** [comment]
Closing this as `build_fivetran_assets` now has a `group_name` parameter.
