### ISSUE TITLE
[Documentation Feedback] Problem on /dagster-cloud/getting-started/getting-started-with-serverless-deployment page

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#10657]
This page links a very old repo: https://github.com/dagster-io/dagster-cloud-template when it describes "Clone the Dagster Cloud starter project - This option clones the [dagster-cloud-template](https://github.com/dagster-io/dagster-cloud-template) repo, which already has Serverless Deployment and [Branch Deployments](https://docs.dagster.io/dagster-cloud/developing-testing/branch-deployments) configured."

I think it should link to https://github.com/dagster-io/dagster-cloud-serverless-quickstart?

**Comment by erinkcochran87** [comment]
You're correct @schrockn. I have a PR going that works on this + the Hybrid guide (#10429) - I'll make sure to include this in those changes.

**Comment by erinkcochran87** [comment]
This was addressed in #10429 - closing
