### ISSUE TITLE
Visual partition selector and asset health visualization on Materialize dialog not appearing after 1.1.2

### ISSUE THREAD

**Issue by aroig** [dagster-io/dagster#10650]
### Dagster version

1.1.2

### What's the issue?

When clicking Materialize on assets view, for a partitioned job, a partition selection dialog opens, with a textbox selector, checkboxes (Missing, Partial, Completed) but no partition status visualization. If I click "show per asset partition health" nothing appears.

![no-partition-bar](https://user-images.githubusercontent.com/1743143/202898547-e1aa2ec3-eafd-43df-97ca-47f98f1074bb.png)

### What did you expect to happen?

I would have expected to see the visual partition selector, showing partition state. I would also expect the "show per asset partition health" to open a drop-down showing state of individual assets and partitions.

![197407560-763a0b4b-8ac1-48b3-b3ec-076611afc343](https://user-images.githubusercontent.com/1743143/202898596-8b6e074a-e77a-46e1-89fd-76c1b852776e.png)

### How to reproduce?

With the following repository, go to assets view, and click the Materialize button

```python
import dagster

partitions = dagster.StaticPartitionsDefinition(["A", "B", "C"])

@dagster.asset(
    partitions_def=partitions,
    group_name="all"
)
def asset_1():
    return 1

@dagster.asset(
    partitions_def=partitions,
    group_name="all"
)
def asset_2(asset_1: int):
    return asset_1 + 1

job_all = dagster.define_asset_job(
    name="all",
    selection=dagster.AssetSelection.groups("all")
)

@dagster.repository
def my_repository():
    return [
        asset_1,
        asset_2,
        job_all,
    ]
```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@bengotow @braunjj - mind taking a look?

**Comment by bengotow** [comment]
Hey folks! Will take a look at this tomorrow. I think this is expected in the latest version of Dagit - we only show the time range selector for time based partitions. 

For non-timerange partitions, I think we can show a version of the UI that does not imply an ordered set. I think there's one place we show partition blocks with a hairline divider, and that'd probably be best here.
