### ISSUE TITLE
Trailing slash in GCSComputeLogManager leads to confusing log path

### ISSUE THREAD

**Issue by reidab** [dagster-io/dagster#10675]
### Dagster version

1.0.7

### What's the issue?

I had configured GCSComputeLogManager like this:

```yaml
compute_logs:
  module: dagster_gcp.gcs.compute_log_manager
  class: GCSComputeLogManager
  config:
    bucket: reidab-dagster-logs
    prefix: log/compute/
```

The trailing `/` on that prefix led to Dagster uploading everything to a path that looked like `gs://reidab-dagster-logs/log/compute//storage/[…]`.

The extra `/` created an extra level of hierarchy (a directory named `/`) and both the desktop and CLI clients I was using to view the GCS bucket didn’t know how to handle that information. (The desktop client showed `gs://reidab-dagster-logs/log/compute/` as an empty directory and the CLI tools required backslash escaping to drill into the `/` directory.

### What did you expect to happen?

I expected the prefix and log path to be concatenated using a path-aware method and for logs to appear in `gs://reidab-dagster-logs/log/compute/storage/[…]` without the extra `/` directory.

Documentation about the `prefix` configuration value is slim, so it's not clear what kind of value is expected/required here.

### How to reproduce?

Configure `GCSComputeLogManager` with a `prefix` that has a trailing slash. (Probably also consider this issue across other compute log managers.)

### Deployment type

Dagster Helm chart

### Additional information

This was spawned from a Slack discussion here: https://discuss.dagster.io/t/5089325/I-m-trying-to-debug-configuration-of-the-GCSComputeLogManage

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by prha** [comment]
Just landed a fix for this in https://github.com/dagster-io/dagster/pull/10671... should go out in the next release `1.1.3`
