### ISSUE TITLE
Dagit Schedules screen failed with Unexpected GraphQL Error

### ISSUE THREAD

**Issue by averell-ftx** [dagster-io/dagster#10688]
### Dagster version

1.1.2, 1.0.17, 1.0.16

### What's the issue?

Unexpected GraphQL Error when opening the Schedules screen on Dagit.

```
Operation name: SingleScheduleQuery

Message: (mysql.connector.errors.ProgrammingError) 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTERSECT SELECT run_tags.run_id 
FROM run_tags 
WHERE run_tags.`key` = '.dagste' at line 5
[SQL: SELECT runs.id, runs.run_body, runs.status, runs.create_timestamp, runs.update_timestamp, runs.start_time, runs.end_time 
FROM runs 
WHERE runs.run_id IN (SELECT run_tags.run_id 
FROM run_tags 
WHERE run_tags.`key` = %(key_1)s AND run_tags.value = %(value_1)s INTERSECT SELECT run_tags.run_id 
FROM run_tags 
WHERE run_tags.`key` = %(key_2)s AND run_tags.value = %(value_2)s) ORDER BY runs.id DESC 
 LIMIT %(param_1)s]
[parameters: {'key_1': 'dagster/schedule_name', 'value_1': 'segment_partial_schedule', 'key_2': '.dagster/repository', 'value_2': 'analytx_assets_repo@generic', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)

Path: ["scheduleOrError","scheduleState","runs"]

Locations: [{"line":16,"column":9}]
```

### What did you expect to happen?

Schedules are displayed correctly.

### How to reproduce?

Use MySQLScheduleStorage (tried with 8.0.30 and 8.0.23)

### Deployment type

Docker Compose

### Deployment details

Tried with local docker (MacOS with M1 chip), and AWS ECS

### Additional information

There's no issue if using MySQL 8.0.31.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@prha @hellendag - know what might be going on here?

**Comment by averell-ftx** [comment]
Thanks @sryza.
https://github.com/dagster-io/dagster/commit/389134a12e4ecf305e7718fc512d17c92b4d3fc5
There was a change to use `db.intersect` in this commit, which requires MySQL version 8.0.31. This new requirement about minimum version of MySQL should be documented somewhere.
