### ISSUE TITLE
Actually do proper fix for solid navigation bug

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1070]
I added some dubious JS in https://github.com/dagster-io/dagster/pull/1069

I figured it would be way more efficient for you to do correctly since it is fighting both the Router and TS

Issue is at https://github.com/dagster-io/dagster/pull/1069/files#diff-d1f08b414dfd43c4e3783bef46b5ad85R127

**Comment by mgasner** [comment]
Closing this because this part of the JS codebase has been thoroughly reworked.
