### ISSUE TITLE
Adjust `build_asset_reconciliation_sensor` to reconcile after source asset versions change

### ISSUE THREAD

**Issue by smackesey** [dagster-io/dagster#10727]
### What's the use case?

Users want to rematerialize their stale assets automatically.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OSadovy** [comment]
I found that reconciliation sensor does not detect that downstream asset is stale because of upstream source asset version changed. the UI shows the asset as stale however the sensor does not output a run. is this bug related to this issue? If yes, are there any workarounds?

**Comment by sryza** [comment]
@OSadovy - @OwenKephart just merged a fix for this that should make it into next week's release: https://github.com/dagster-io/dagster/pull/13163
