### ISSUE TITLE
Runs directory intermediates should be scoped by pipeline and solid.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1072]
One can inject run_ids so this is possible. You could construct a sequence of runs where pipelines and solids are run multiple times in which case values could be smashed. We should think about how to handle that.

**Comment by mgasner** [comment]
Can you clarify the issue here @schrockn? I am not sure if this is about multiple runs with the same run_id or if it's about nesting intermediates under corresponding step keys (which I think is implemented).

**Comment by mgasner** [comment]
This is made irrelevant by the new layout
