### ISSUE TITLE
Asset Job - unable to launch backfill when there is required asset/resource config

### ISSUE THREAD

**Issue by xWaita** [dagster-io/dagster#10733]
### Dagster version

1.1.1

### What's the issue?

When attempting to launch a backfill for an asset job that has asset/resource config that is marked as required, the `materialize all` button opens the `launchpad` UI instead of the `launch backfill` UI

### What did you expect to happen?

We expect this button to open the `launch backfill` UI instead of the `launchpad` UI.

Since 1.1.1, the Asset Job partition page's `launch backfill` button has been replaced with a `materialize all` button which uses logic for launching runs for assets
https://github.com/dagster-io/dagster/blob/release-1.1.2/js_modules/dagit/packages/core/src/partitions/AssetJobPartitionsView.tsx#L84

This logic contains two checks `anyAssetsHaveRequiredConfig` and `anyResourcesHaveRequiredConfig` which shows the launchpad UI if there is required asset/resource config, or shows the partition UI if there is no required asset/resource config.
https://github.com/dagster-io/dagster/blob/release-1.1.2/js_modules/dagit/packages/core/src/assets/LaunchAssetExecutionButton.tsx#L351

This check made sense previously when this button was only used for Assets, because asset/resource config could not be provided by other means, however doesn't make sense for asset jobs, which could have asset/resource config that is required, which is filled in via partitioned config.

### How to reproduce?

1. create an asset that has `resource_defs` with a config field that is marked as `required`, or a `config_schema` with a field marked as required. 
2. use this asset to create an asset job using `define_asset_job`
3. launch the UI, go to the job, and then to the partitions tab
4. press the `materialize all` button, and instead of the `launch backfill` UI, the `launchpad` UI is shown

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey folks! Thanks for the detailed write-up of this one @xWaita. I think you're correct - the Dagit UI tries to statically determine whether launching a backfill of multiple partitions without config is possible, and when it sees that there's required config it reverts to the launchpad, forcing you to specify config and launch runs one at a time.

I think there are a couple ways we can fix this - we could detect that job config is present (and completely satisfies the config requirement) and let you open the backfill modal or provide a way to override Dagit's "default behavior" and show the backfill modal even though it thinks runs might fail. 

Need to sync up with @braunjj and @sryza about this, but we'll see what we can do!

**Comment by sryza** [comment]
@xWaita was this working for you on earlier versions?

**Comment by xWaita** [comment]
Thanks guys! @sryza the last version that worked for us was 1.0.17

This is because in 1.0.17, the partitions page directly launched a backfill
https://github.com/dagster-io/dagster/blob/1.0.17/js_modules/dagit/packages/core/src/partitions/PartitionView.tsx#L188

however in 1.1.0 onwards, this was replaced with the following file, which uses the aforementioned `LaunchAssetExecutionButton` logic instead
https://github.com/dagster-io/dagster/blob/1.1.0/js_modules/dagit/packages/core/src/partitions/AssetJobPartitionsView.tsx#L84

**Comment by sryza** [comment]
Got it - that makes sense @xWaita .

@bengotow is working on this, and a fix will be included in Thursday's release.

**Comment by bengotow** [comment]
Hey folks! The fix for this merged in https://github.com/dagster-io/dagster/pull/10905. When a user-defined asset job has partitions, we always assume that the config will be provided (via job-level `PartitionedConfig`) and a backfill is possible (essentially the same as the old pre-1.1.0 behavior). 

This changes the button to show the partition range picker -- if you want to customize config and launch a single partition, you can hold shift when clicking Materialize.

Thanks for your patience @xWaita!
