### ISSUE TITLE
View backfill button broken

### ISSUE THREAD

**Issue by Nintorac** [dagster-io/dagster#10735]
### Dagster version

1.1.2

### What's the issue?

After launching a backfill a popup is displayed that says click to view backrun. It sends you to the daemon page instead

### What did you expect to happen?

expected to be directed to the back run

### How to reproduce?

launch a backrun, click the popup

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by chriscomeau79** [comment]
Saw the same on 1.1.3

**Comment by sryza** [comment]
@prha is this something you're familiar with?

**Comment by prha** [comment]
I think this is fixed by https://github.com/dagster-io/dagster/pull/10664, which went out in `1.1.4`.
