### ISSUE TITLE
Improve API and error checking for metadata on a solid

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1076]
It's very easy to screw this up right now. You must simply know magical keys. I accidentally passed the entire contents of a sql statement as the "kind" and that was not caught.

**Comment by natekupp** [comment]
Maybe worth revisiting what we want out of the metadata APIs vs. system tags?

**Comment by catherinewu** [comment]
going to close this issue as it's a bit underspecified, feel free to open with more details. 

here's the related issue for improving `kind` tags https://github.com/dagster-io/dagster/issues/3210
