### ISSUE TITLE
[Documentation Feedback] /deployment/run-monitoring is reachable by "Search the docs" but results in a 404 

### ISSUE THREAD

**Issue by millimat** [dagster-io/dagster#10785]
To reproduce:
1. Visit https://docs.dagster.io/getting-started
2. Click "Search the docs"
3. Enter "Run monitoring"
4. Click any of the links to pages titled "Run monitoring"
5. Reach 404 Not Found page

**Comment by erinkcochran87** [comment]
@millimat Thanks for the report! I re-deployed the docs site earlier and have confirmed this is now working.
