### ISSUE TITLE
Enable loading source assets, e.g. in Jupyter notebooks, using `load_asset_value`

### ISSUE THREAD

**Issue by DSamuylov** [dagster-io/dagster#10819]
### What's the use case?

Currently it is possible to load software-defined assets into Jupyter Notebooks as described [here](https://docs.dagster.io/concepts/assets/software-defined-assets#loading-asset-values-outside-of-dagster-runs). However, if we try to load source assets using the same approach, they are not available under `loader._assets_defs_by_key`.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@DSamuylov I agree that this would be beneficial. No pressure, but if you'd be up for submitting a PR, I'd be happy to review.

**Comment by sryza** [comment]
This has been addressed in a recent release
