### ISSUE TITLE
asset value loader doesn't correctly load partitioned assets

### ISSUE THREAD

**Issue by Nintorac** [dagster-io/dagster#10828]
### Dagster version

dagster, version 1.1.3

### What's the issue?

Partitioned assets cannot be loaded with the asset value loader

### How to reproduce?

run the script and notice it try to load from `storage/a` rather than `storage/a/a`

```
from dagster import AssetKey, StaticPartitionsDefinition, asset, repository


parts = StaticPartitionsDefinition(list('abcdefgh'))

@asset(
    partitions_def=parts
)
def a():

    pass


@repository
def repro():

    return [a]


if __name__=="__main__":
    message = repro.load_asset_value(
            AssetKey("a"), 
            partition_key='a'
    )
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
This should be fixed in tomorrow's release
