### ISSUE TITLE
Consider changing PipelineContextDefinition to take name as argument rather than rely on dictionary keys

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1085]
Another issue proposes changes everything to dictionaries, but I think it might be wise to go the opposite directions. As a do a round of improvements to our error messaging it is much easier to craft good error messages on construction when the names are readily available.

**Comment by schrockn** [comment]
We could also have the dictionary key variant be user-facing and then transform it to the version where the object contains the name

**Comment by mgasner** [comment]
cf #687

**Comment by mgasner** [comment]
closing this, since PipelineContextDefinition has been replaced by ModeDefinition (which follows the convention suggested here)
