### ISSUE TITLE
Enabling using assets as input for a job/graph

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#10874]
_Originally posted by @PascalStehling in https://github.com/dagster-io/dagster/discussions/10802_

Hi all,

is there a way to have Assets as input for a "normal" Job. I have some Assets and based on them I want to run a Job, which does not create a new Asset. For the job I want to reuse the already existing structure with the Asset and its IO Manager and not load the Data directly from the source DB. Is this possible? And if so, how? 

Below is an example of what i am thinking about. Its not working as the AssetIn's are directly passed as Input and not the loaded Asset values.

Thank you for your help and keep on the good work :)

```py
from dagster import asset, repository, job, op, OpExecutionContext, AssetIn, fs_io_manager


@asset(io_manager_def=fs_io_manager)
def get_five() -> int:
    return 5


@asset(io_manager_def=fs_io_manager)
def get_ten() -> int:
    return 10


@op
def do_something_special_op(context: OpExecutionContext, five: int,
                            ten: int) -> None:
    context.log.info(five + ten)


@job(resource_defs={"io_manager": fs_io_manager},
     input_values={
         "get_five": AssetIn("get_five", input_manager_key="io_manager"),
         "get_ten": AssetIn("get_ten", input_manager_key="io_manager"),
     })
def asset_based_job(get_five: int, get_ten: int) -> None:
    do_something_special_op(get_five, get_ten)


@repository
def repo() -> list:
    return [get_five, get_ten, asset_based_job]
```
    

References:
- https://discuss.dagster.io/t/8204501/does-calling-an-asset-function-from-a-job-cause-the-asset-to
- https://discuss.dagster.io/t/8609918/how-can-i-access-a-materialized-asset-in-a-job

**Comment by Bonnevie** [comment]
This is pretty under-documented, it seems like most places in the docs where this would naturally come up an ordinary python function is used to load some data from disk. But given that assets have internal ops, would it work to do
```python
do_something_special_op(get_five(), get_ten())
```
It's just not obvious to me that this would trigger the I/O manager given that it is an asset definition and not actually an op?

A related headache is if you can run jobs on an asset specified by configuration (i.e. asset key) - I assume the asset loader cannot be used inside a job? E.g. you might have a generic backup or observation routine.

**Comment by jzgrzebnicki** [comment]
What if the asset is partitioned? Does the job will need to have the same partition?

**Comment by sryza** [comment]
Potential API for this:

```python
@job(
     input_assets={
         "asset1": AssetKey("asset1"),
         "asset2": AssetKey("asset2"),
     }
)
def asset_based_job(asset1, asset2):
    do_something_special_op(asset1, asset2)
```

**Comment by PascalStehling** [comment]
I think the first option fits better to the general dagster configuration/workflow than the second one.

Maybe as a third potential API (but im not sure if this is even possible):

```
@job(
     input_values={
         "asset1": inputFromAsset(AssetKey("asset1")),
         "asset2": inputFromAsset(AssetKey("asset2")),
     }
)
def asset_based_job(asset1, asset2):
    do_something_special_op(asset1, asset2)
```

With this you would have all the input values for the Job (let it be an Asset or something else) at one place and not defined at different parameters.

**Comment by sryza** [comment]
I posted an RFC PR for this. I ended up going with an approach that's not identical to any of the proposals here.  I'm a bit negative on approaches like:

```python
@job(
     input_assets={
         "asset1": AssetKey("asset1"),
         "asset2": AssetKey("asset2"),
     }
)
def asset_based_job(asset1, asset2):
    do_something_special_op(asset1, asset2)
```

because of the large number of times that each asset name needs to be typed (four!). That said, I think the approaches aren't mutually exclusive, and we could actually allow both.
