### ISSUE TITLE
Add option to cancel Databricks job when the according op has been cancelled or failed

### ISSUE THREAD

**Issue by sinnfashen** [dagster-io/dagster#10928]
### What's the use case?

When we run a Databricks op with databricks_pyspark_step_launcher, it submits a Databricks job and polls its run_status/logs until it finishes. 
The issue with the current behavior is that when we manually cancel the dagster job run, or the local process somehow fails, it does not affect the remote Databricks job. This causes confusion as people may not realize that the job is still running, and also cause inconvenience as people will need to manually cancel the Databricks job in Databricks UI to really stop the job when they want to. It's especially annoying if we need to terminate multiple databricks jobs at once.
Therefore, it would be really great to have an option to be able to send out kill command to Databricks jobs once the according ops receives a user-triggered cancel or any other unexpected error.

### Ideas of implementation

The job killing command should be no much different from the job submitting command.
It's possible that we won't be able to capture some kinds of error as they may cause the op to die immediately or so. Still, I think we should try to capture "cancel", and beyond that we can try to capture as much errors as we can.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
We had a similar PR for dbt Cloud: https://github.com/dagster-io/dagster/pull/10723. Essentially, we always cancel the job in the `finally:` step.

**Comment by sinnfashen** [comment]
Thanks @rexledesma! Didn't see that earlier but that sounds pretty much the thing we are looking for. Gonna try the latest version and close this request after verifying the behavior is desired.

**Comment by rexledesma** [comment]
> Thanks @rexledesma! Didn't see that earlier but that sounds pretty much the thing we are looking for. Gonna try the latest version and close this request after verifying the behavior is desired.

@sinnfashen the solution for our Databricks integration to address your concern is not implemented yet. I was just mentioning a potential solution that worked in another one of our libraries.

**Comment by sinnfashen** [comment]
@rexledesma Oh sorry I misunderstood that. In that case I guess I should keep this open. Do we have any timeline for this yet?

**Comment by sinnfashen** [comment]
Hi @rexledesma, just want to check-in again to see if we have any plan for that already. I can also try to just replicate that logic in the PR you mentioned if not.

**Comment by rexledesma** [comment]
yeah, feel free to send in a PR - we are not actively working on this issue at the moment.
