### ISSUE TITLE
Freshness policies for integration assets (dbt)

### ISSUE THREAD

**Issue by slopp** [dagster-io/dagster#10924]
### What's the use case?

Freshness policies enable a very useful approach to scheduling, but today they can only be set on assets created explicitly within dagster, e.g. with the `asset` decorator.  It would be equally useful to be able to set freshness policies on assets that are loaded from other integrations such as dbt models.

### Ideas of implementation

Perhaps ot would be useful to set a freshness policy on one or more assets via a selection. 

```
dbt_assets = load_assets_from_dbt_project(DBT_PROJECT_DIR)

build_freshness_policy(
    freshness_policy = FreshnessPolicy(maximum_lag_minutes = 5), 
    asset_selection = AssetSelection.keys("dbt_model_a")
)

build_freshness_policy(
    freshness_policy = FreshnessPolicy(maximum_lag_minutes = 10), 
    asset_selection = AssetSelection.keys("dbt_model_b")
)
```

Another approach would be some sort of mapping function as an argument to the load statement, but that introduces complexity for each integration and a new concept for users.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
@slopp I'm mostly on board w/ the idea of porting in dbt's concept of freshness. It might be a bit confusing for users as it doesn't really map 1-1 with the concept of freshness in dbt-land, but I think that's ok. I'm guessing we should ingest the "warn-after" value (rather than the "error-after").

I think the most flexible implementation would follow along the lines of our other parameters, where we have a `node_info_to_freshness_policy_fn` parameter, which has a default implementation of trying to create a freshness policy from the freshness defined on the node, but can be overridden to base the policy off of tags, model name, or whatever.

This should be a pretty easy win imo.

**Comment by sryza** [comment]
My instinct would be to try to separate it from the dbt notion of freshness. While they've got similar goals at a high-level, I think the specifics just end up too different.  I.e. there's no concept in Dagster that maps to dbt's `loaded_at_field` and no concept in dbt that maps to Dagster's concept of upstream data time.

**Comment by slopp** [comment]
fwiw after reading more into dbt freshness I also agree that its mostly a different thing, specifically because freshness is only associated with source data, whereas in dagster-dbt we are talking about the desired freshness of the transformed data

But I think the fact that they are distinct concepts, IMO, is an argument for defining dagster freshness policies in dagster, not in dbt tags that are implicitly turned into dagster policies.  But maybe I am missing the motivation for keeping all dbt adjacent stuff strictly in dbt?

**Comment by sryza** [comment]
> But maybe I am missing the motivation for keeping all dbt adjacent stuff strictly in dbt?

My understanding is that usually the people who will be making the decisions about how fresh assets need to be will be analytics engineers who work entirely in dbt. In many cases, those people will work in a git repository that hosts the dbt project, which is separate from the git repository that hosts the Dagster code.

**Comment by slopp** [comment]
Just in case anyone finds this issue - this is now experimentally implemented for dbt, in the `load_assets_` functions use `node_info_to_freshness_policy_fn` which also accepts this default:

https://docs.dagster.io/_apidocs/libraries/dagster-dbt#assets-dbt-core 

```
{{
        config(
                dagster_freshness_policy={"maximum_lag_minutes": 60, "cron_schedule": "0 9 * * *"}
        )
}}

select
        order_date,
        n_orders as num_orders
from {{ ref("order_stats") }}
```

**Comment by jonathanneo** [comment]
@slopp Do you have the link to the PR that has this implemented? I don't see it released yet in the latest version (version 1.1.7) of dagster.

**Comment by jonathanneo** [comment]
All good, I found the PR: https://github.com/dagster-io/dagster/pull/11103 

And it is part of the 1.1.7 release. 

Adding `dagster_freshness_policy` to the config line to my dbt model works.

**Comment by arniwesth** [comment]
In our case, we need the dbt freshness test to test and warn of source data staleness. This differs from how Dagster thinks about freshness, as mentioned above. What is currently the best way to orchestrate a run of 

```dbt source freshness```

in Dagster?
