### ISSUE TITLE
Airline-demo config query instigates heavy startup cost

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1094]
Querying the config type system causing a heavy weight startup process. 1) It probably shouldn't do this and 2) It causes some bad behavior in dagit.

Investigate this and fix or file follow up tasks as needed

**Comment by mgasner** [comment]
cf #816

**Comment by mgasner** [comment]
I'm having trouble reproducing this from dagit. Do you know what query produced this behavior?

**Comment by schrockn** [comment]
The exact case when this occurs is when you have a pipeline with an expensive resource creation process and you're config is not valid. Then make it valid and it is going to try to create the execution plan to render the execution plan. I, for example, the airline demo case, it actually does the heavyweight spark context initialization and while it is in that state the UI is in a weird state where you don't know if you can press start execution or not.

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
ah, i see, i need to rebuild dagit. apologies

**Comment by mgasner** [comment]
I think it makes sense to be able to query the execution plan without having to init resources (which in many other cases will change global state! -- e.g., creating S3 buckets). I encounter this same issue when, e.g., compiling an execution plan to Airflow operators.
