### ISSUE TITLE
Dagit: tab auto-completion doesn't behave nicely

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1095]
I don't really want it to do this:

![image](https://user-images.githubusercontent.com/609349/55354003-7d365700-5479-11e9-969e-f1e5c7f1e41e.png)

![image](https://user-images.githubusercontent.com/609349/55354015-81627480-5479-11e9-9bc9-d8a5de978cdc.png)

**Comment by schrockn** [comment]
Another repro in the airline demo:

![Screenshot 2019-04-01 13 40 34](https://user-images.githubusercontent.com/28738937/55358261-cd1a1b80-5483-11e9-9296-17b6242045f9.png)

**Comment by natekupp** [comment]
More on dagit autocompletion from @Eronarn's notes:

> I tried using the auto completion features here, rather than just pasting in the YAML dictionary. This worked fine, except in the case where I was entering a new dict and hadn't typed anything yet. I would've expected a way to see the available fields for that dict without having to first type a character (like popping up automatically before I hit tab).

**Comment by mgasner** [comment]
I'm going to move @Eronarn's comment to a new issue -- this comment really concerns some form of hint to tell people to hit option-space for autocomplete.
