### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1098]
Getting this error in dagit for the airline demo:

![image](https://user-images.githubusercontent.com/609349/55365682-458bd700-549a-11e9-939d-b0fafe2a537c.png)

The real issue is further up in the logs, an S3 access denied exception:

![image](https://user-images.githubusercontent.com/609349/55365687-53415c80-549a-11e9-9c9e-2839e92bec4c.png)

cc @mgasner

**Comment by mgasner** [comment]
Duplicate of #1079
