### ISSUE TITLE
The `input_manager` receives `InputContext` which doesn't have the `.instance` attribute

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#11004]
### Dagster version

1.1.5

### What's the issue?

Consider this code for an `IOManager`: 

```python
@io_manager(config_schema={"base_path": Field(str, is_required=False)})
def local_parquet_io_manager(init_context: InitResourceContext) -> ParquetIOManager:
    assert init_context.instance is not None
    base_path = UPath(init_context.resource_config.get("base_path", init_context.instance.storage_directory()))
    return ParquetIOManager(base_path=base_path)
```

Here we have access to `InitResourceContext` and thus can get the `init_context.instance.storage_directory()` as the default storage location. 

This behavior can't be replicated for an `InputManger`, because it instead receives an `InputContext`. Why is that? 

### What did you expect to happen?

I expected to access the `.instance` attribute from the `input_manager` decorator.

### How to reproduce?

```python
@input_manager(
    config_schema={"base_path": Field(str, is_required=False)}
)
def local_raw_upath_parquet_input_manager(context: InputContext) -> RawUPathParquetInputManager:
   context.instance  # will raise an error
```

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by danielgafni** [comment]
Thanks!

**Comment by sryza** [comment]
I do think it would be nice to have an `instance` property on InputContext. I filed https://github.com/dagster-io/dagster/issues/11016 for this.
