### ISSUE TITLE
Select all by default in backfill modal

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#11093]
It's confusing that you have to manually make a selection in order to launch a backfill. we should always just select all by default and then let users change it if they'd like to.
![image](https://user-images.githubusercontent.com/2798333/207450167-967e3a2e-5603-45bb-b46d-81e21bd26ad1.png)

The screenshot above shows 0 missing partitions.... even though you can see that there are missing ones in the bar chart.

Slack convo:
https://elementl-workspace.slack.com/archives/C03CCE471E0/p1670967462873999

**Comment by bengotow** [comment]
Hey gang! This has been fixed 🙌 I think this convo was about a previous release
