### ISSUE TITLE
Allow RetryPolicy to trigger retries for k8s pod failures (ex: OOMKilled)

### ISSUE THREAD

**Issue by markfickett** [dagster-io/dagster#11221]
### What's the use case?

I'm running a pipeline on a hybrid Dagster Cloud using Kubernetes. Occasionally I've seen a pod OOMKilled but been able to complete successfully on retry. We have a couple ops in our DAG that are consistently the highest RAM users. So, it could be nice if a [RetryPolicy](https://docs.dagster.io/concepts/ops-jobs-graphs/op-retries) could retry on k8s pod failure, as well as user code exceptions.

More broadly, the goal of a retry within this context is so that the overall pipeline can succeed even if one pod hits an OOM. If there were a way to allow this one op to fail (it's part of a dynamic output fan-out) but still run the rest of the pipeline, that would be nice as well.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by liveandletbri** [comment]
I'll jump in here and say I'd love this too, but with a different use case. I've got an op that has to read CSVs into memory and write them to Snowflake. Unfortunately Pandas has a memory leak that I can't seem to get around. This op can upload a handful of CSVs before it runs out of memory. It is idempotent, so when it restarts, it will pick up on a new file that hasn't yet been loaded. I'd love to set a retry policy on this to let it continue to load files until they're all uploaded to Snowflake.

**Comment by gibsondan** [comment]
This is (finally!) going live in the release later this week - see the linked issue
