### ISSUE TITLE
Bring back code location configuration details on code locations page

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#11240]
(This info is currently only available by clicking on "view configuration" in the context menu)
 
- Display the `image` value under the code location name 
- Display either the `module_name`, `package_name`, or `file_name` value
- Add the `commit_hash` under the git repository link

Mockup
![image](https://user-images.githubusercontent.com/2798333/208527109-4d3b42d8-236f-4f0e-a62a-0b6ffbd98e97.png)

**Comment by hellendag** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/11281 for OSS and a similar PR for Cloud.
