### ISSUE TITLE
Dagit zoom is reversed on trackpads

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1126]
@Aylr reports that zoom on dagit is reversed in trackpads.

**Comment by mgasner** [comment]
#297

**Comment by schrockn** [comment]
What is the least surprising behavior here? I honestly have no mental model for how trackpad is supposed to work anyways so for every app I just try things.

**Comment by bengotow** [comment]
Hey! So I took a look at this and I think we were in fact doing it backwards. On my trackpad, swiping DOWN zooms IN on Google Maps, and it was going out in Dagit. I've reversed the swipe handling in #1137.

I think that there's a chance this will still be backward if you've turned off "natural scrolling" on the Mac, but I believe it'd still be consistent with Google Maps.

**Comment by schrockn** [comment]
well there we go

**Comment by bengotow** [comment]
Going to close this with the merge of #1137. I /think/ this addresses the issue - if not, we'll need to take a more detailed look at how the pinch-to-zoom gesture arrives in JS.
