### ISSUE TITLE
@asset key_prefix kwarg docs lacks final Asset name explanation

### ISSUE THREAD

**Issue by airton-neto** [dagster-io/dagster#11341]
### What's the issue or suggestion?

Hi there,

There is some coding which I expected to run

```py
from dagster import asset, materialize_to_memory

@asset(
    name='simple',
    key_prefix='prefix'
)
def simple() -> str:
    return "simple"

result = materialize_to_memory(
    [simple]
)

simple_res = result.output_for_node(simple.key)
```

There is two concerns here:
1) AssetKey is a list. In this case `['prefix', 'simple']`. Wouldn't it be better for AssetKey to be based on final str names?
2) output_for_node() expects final op name, which is `prefix__simple`, with two underscores

I think adding some explanation to @asset docs could solve (2).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
> AssetKey is a list. In this case ['prefix', 'simple']. Wouldn't it be better for AssetKey to be based on final str names?

I'm not exactly following what you mean. Mind expanding on this a little?

> I think adding some explanation to @asset docs could solve (2).

I think you are right. I'll see if I can find time to take a stab at this.

btw, I think we should also provide a method on the execution result that lets you get the values by asset key, not just the node name

**Comment by airton-neto** [comment]
Hi there,

The thing I don't undesrtand is why Keys are defined by strings and, at the same time, as lists.
The issue I had was to discover that ['a', 'b'] is parsed to 'a__b'.

One theoretical problem is that this process of list -> str is not always reversible. 
Users must not include __ in asset names, am I right?

**Comment by sryza** [comment]
> The thing I don't undesrtand is why Keys are defined by strings and, at the same time, as lists.

Asset keys are always lists. However, op names are strings.  When we auto-generate an op name from an asset key, we need some scheme for converting one to the other.

As you point out, an unfortunate side-effect of this is that if you had two assets, one with `AssetKey(["a", "b"])` and one with `AssetKey(["a__b"])`, they would end up with the same op name, which would cause an error.

**Comment by airton-neto** [comment]
Ok then, thanks for replying me back!

**Comment by sryza** [comment]
I'm going to close this now that the `ExecuteInProcessResult.asset_value` change is merged.
