### ISSUE TITLE
psycopg in a code location causes a conflict with dagster-postgres preventing a run from starting

### ISSUE THREAD

**Issue by dmosesson** [dagster-io/dagster#11353]
### Dagster version

1.1.3

### What's the issue?

When a code location is using psycopg (and probably psycopg2 as well), dagit fails to start a run if dagster-postgres is installed.

I believe at least part of the issue is here: https://github.com/psycopg/psycopg2/issues/1360 and it should probably be possible to mitigate by using psycopg-binary as well.

The other bug is that dagit does record what the postgres connection error was, it just gives a generic "Tried too many times" error.

### What did you expect to happen?

I expected that the dependancies in the .venv for a code location would have no impact on the process of launching a job

### How to reproduce?

I'm not at work to test this just yet but:
* In one env install dagit, dagster postgres, and set up the dagster.yaml to connect to postgres. Postgres must require SCRAM (default behavior in 15)
* In another env, create a python package, install psycopg (not binary) and a repository that uses it
* Load that python package and point to the .venv in the workspace.yaml
* Try and launch a job from that repository

### Deployment type

Local

### Deployment details

host: dagit version 1.0.17, dagster-postgres version 0.16.17
code location: dagster 1.1.3

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dmosesson** [comment]
Following up on this:

- The root cause of the bug is that `psycopg2` is not present in the `venv` of the code location in a way that dagster can find.

It is surprising to me that dagit requires all code locations to be able to do `import dagster_postgres.run_storage` if `dagit` is set up to use postgres.

I confirmed that manual install of `psycopg2-binary` fixes the problem so this is probably not a high priority, but just an interesting quirk of the way that pipelines are launched

**Comment by sryza** [comment]
Hi @dmosesson - for better or worse, this is a result of the Dagster OSS deployment architecture - the code inside a code location will directly read/write to the instance database in certain circumstances - e.g. if a sensor is running inside the code location that queries the instance. One advantage is that this avoids the Dagit web server as a bottleneck.

**Comment by kevinschaich** [comment]
@dmosesson @sryza  unfortunately I'm still hitting this on Docker. 

I'm using the following Dockerfile:

```
FROM python:3.10-slim

RUN pip install dagster dagster-graphql dagit dagster-postgres dagster-docker psycopg2-binary==2.9.5

ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
```

And in my repo's `__init__.py` file, I import `dagster_postgres` as Daniel mentioned in his Slack post. Building succeeds but running gives me:

```
2023-02-22 22:34:08 WARNING:root:Retrying failed database connection: (psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above
```
