### ISSUE TITLE
Implement config scaffolding with a single, consolidated python implementation that makes sense

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1139]

**Comment by schrockn** [comment]
Initial python implementing by yours truly followed by handoff to @bengotow

**Comment by mgasner** [comment]
#692

**Comment by mgasner** [comment]
@schrockn this is probably going to be easier after your config changes land

**Comment by schrockn** [comment]
Not sure of the value of this feature actualy

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
I'm going to close this issue pending renewed user interest in the feature.
