### ISSUE TITLE
dagster databricks raises unexpected error for empty HTTPErrors when fetching logs

### ISSUE THREAD

**Issue by rzsquirrel** [dagster-io/dagster#11413]
### Dagster version

1.0.17

### What's the issue?

While using dagster databricks, we've been sporadically hitting this error during job runs:

> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "/opt/conda/envs/akuna/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_plan.py", line 251, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/opt/conda/envs/akuna/lib/python3.8/site-packages/dagster_databricks/databricks_pyspark_step_launcher.py", line 205, in launch_step
    yield from self.step_events_iterator(step_context, step_key, databricks_run_id)
  File "/opt/conda/envs/akuna/lib/python3.8/site-packages/dagster_databricks/databricks_pyspark_step_launcher.py", line 269, in step_events_iterator
    all_events = self.get_step_events(
  File "/opt/conda/envs/akuna/lib/python3.8/site-packages/dagster_databricks/databricks_pyspark_step_launcher.py", line 303, in get_step_events
    if e.response.json().get("error_code") == "RESOURCE_DOES_NOT_EXIST":
  File "/opt/conda/envs/akuna/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

The databricks job itself starts and completes successfully, but dagster raises this error. Looking at the [source](https://github.com/dagster-io/dagster/blob/471d7e047a98f760bfc1aa172b7a2807fc7d4a53/python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py#L316-L330), my guess is that we hit an HTTPError with an empty response, which causes the unexpected JSONDecodeError that we're seeing.

Given the databricks job is fine, is this something we can retry on?

### What did you expect to happen?

I expect that we retry after a backoff period or raise a different error.

### How to reproduce?

Get an empty HTTPError from databricks

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
hi @rzsquirrel ! are you able to confirm what version of dagster-databricks you're running on your databricks cluster? You note that your dagster version is on 1.0.17, which should correspond to a dagster-databricks library version of `0.16.17`. A change was made somewhere around the 0.15.x era that made it much less likely for errors of this type to occur, so that might be at least part of the issue.

regardless, I think your diagnosis is correct, and we should be safeguarding against empty responses, so I threw up a PR to fix that: https://github.com/dagster-io/dagster/pull/11430

**Comment by rzsquirrel** [comment]
I can confirm that our databricks cluster has dagster-databricks at 0.16.17. Thanks for the PR!
