### ISSUE TITLE
Support end-dates for time-partitioned assets

### ISSUE THREAD

**Issue by mjclarke94** [dagster-io/dagster#11428]
### What's the use case?

Let's say we are attempting to collate the data used by a number of mobile devices. Alice has had her phone since Jan 1st 2022, Bob had his old device since Feb 1st 2022, and he replaced it in Dec 2022.

One approach would be to set up the following:
```
@asset(
    partitions_def=MultiPartitionsDefinition(
        {
            "date": DailyPartitionsDefinition(start_date="2022-01-01"),
            "device": StaticPartitionsDefinition(["alice", "bob_old", "bob_new"]),
        }
    )
)
def fetch_consumed_data(context) -> pd.Dataframe:
    ...
    return bar
```

This will work so long as the asset is written to handle missing data, but has a few issues.

Firstly, any partitions which are correspond to dates before the asset came online (pre Feb 2022 for `bob_old`, pre Dec 2022 for `bob_new`) will always return None, and we know this at definition time, so running these is redundant.

We then have the issue that when `bob_new` comes online, `bob_old` will never return data again, but every day a job will be launched to confirm this. Not a major issue each day, but pretty expensive when it comes to backfills.

This is probably two feature requests in one (happy to split the issue if needed), but:
- It would be useful to add an `end_date` parameter to `TimeWindowPartitionsDefinition`
- Being able to have multi-dimensional partitions have certain key pairs be excluded at definition time, with emphasis on allowing each static partition key have its own start (and end) date.

### Ideas of implementation

For consistency, adding an `end_date` parameter which was then used for `get_last_partition_key` etc in `TimeWindowPartitionDefinition` when `end_date < dt.today()`.

Then for the multi-dimensional definitions issue, a first thought at syntax might be allowing time-partitions to be passed in as a dict, where each key in the StaticPartition must have a TimeWindowPartition defined.
```
MultiPartitionsDefinition(
        {   
            "device": StaticPartitionsDefinition(["alice", "bob_old", "bob_new"]),
            "date": {
                "alice": DailyPartitionsDefinition(start_date="2022-01-01"), 
                "bob_old": DailyPartitionsDefinition(start_date="2022-02-01", end_date="2022-11-30"),
                "bob_new": DailyPartitionsDefinition(start_date="2022-12-01"),
                }
        }
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by Jack-Kingdom** [comment]
@mjclarke94 check `FreshnessPolicy` in source code. It's an asset arguments that can help you achieve this.

**Comment by mjclarke94** [comment]
@Jack-Kingdom Possibly it's just me not fully grasping the feature, but my understanding is that a `FreshnessPolicy` on an asset allows you to ensure that when upstream assets change, the downstream asset is then updated to incorporate the new information in a given timeframe.

This would allow you to avoid running downstream assets as the upstream asset wouldn't be changing, but it wouldn't prevent the upstream asset from being unnecessarily polled in the first place (which could potentially be an expensive operation), nor would it handle the issue of a backfill growing larger over time.

Here, the idea would be to allow a time-partitioned asset to transition from growing indefinitely, to becoming a pseudo-static asset. The benefit of this over converting it to a static asset once it is no longer growing is you preserve the time-partitioning and thus can use it in downstream time-partitioned assets up to the point it expires.

Say for example in the case of the mobile data I mentioned above, we had a downstream asset which was a monthly summary table. It would still be polling expired upstream assets only to receive `None/0/NaN` as inputs. If you have thousands of short-lived assets, it makes sense to allow them to expire and thus cease to be a dependency for downstream assets.

**Comment by adam-bloom** [comment]
Another use case where a similar feature would be useful:
System A produces assets. System A is scheduled for shutdown and replacement with System B. System B has assets that replace those from System A, but they are distinct dagster assets (different methods of loading, names, etc). After System A is shutdown, we need to retain its assets for historical analysis. We could remove the asset job after the shutdown, but if we needed to do a backfill in the future for some reason, that becomes more complicated. It'd be useful to specify an end date of system A in the partitions definition, which would automatically stop schedules/downstream jobs.

**Comment by sryza** [comment]
I think end dates on time-partitioned assets would be a very reasonable addition. I can't promise that we'll be able to get to this soon, but I'd be happy to review a pull request if anyone has the bandwidth to submit one.

**Comment by spenczar** [comment]
I have another use case for this. I'm working on large-scale scientific data (astronomical surveys). The data are very, very large, so we need to process them in partitions. A natural partitioning is the week that the observations were recorded. This has a finite range, often a few years, like from 2008 to 2012.

Some of the surveys are running today, so we want to sense new observations come in. But eventually the surveys end.

Even without a flow of new data coming in, there are often new ways to analyze old data which might require reprocessing all the way back from the source science data. So the partitioning remains useful, but I'd really like to specify an end date.

**Comment by akoumjian** [comment]
Our current workarounds for this are not very pretty. Maybe we could have time to submit a PR if we knew some guidelines ahead of time and increase the likelihood of it getting accepted.

Here is a bit more background on our use case and workaround:
For our astronomical datasets that have already ended, we use a `StaticPartitionsDefinition`, one that has to be sourced as a daily partition due to its size (and upstream flakiness). Downstream, we transform this data and need to roll these up into monthly partitions so it can be consumed correctly by our end node in the graph. Since the partitions def is based on `Static`, mapping is not supported and we have to jump through a few steps to do the daily -> monthly rollup.

To get the `Daily` to roll up to `Monthly`, we have to send it into an `@op` through a `@job` which has to emit the `AssetMaterializations` manually. This also requires doing the I/O manually outside of an `io_manager`. Lastly, we have to declare the downstream asset as a `SourceAsset` so we can properly feed it into the end of the asset graph.

The `end_date` would allow us to fit everything neatly into regular `@asset`s and allows us to build a proper dependency graph, use `IOManager`, etc.

**Comment by renzhe-brian** [comment]
Hi guys, I made a PR here https://github.com/dagster-io/dagster/pull/14155 to support the `end_date` in `TimeWindowPartitionsDefinition`.

We plan to implement this in our environment and we're still testing (in version 1.2.4 ). I will update our status.

**Comment by sryza** [comment]
I merged @renzhe-brian's PR this afternoon, so this will be resolved in next week's release.
