### ISSUE TITLE
partition_mapping defined in AssetIn is ignored

### ISSUE THREAD

**Issue by ynotzort** [dagster-io/dagster#11420]
### Dagster version

dagster, version 1.1.7

### What's the issue?

When an asset has upsteam dependencies on multiple partitions, then I would expect to be able to define them via the partition_mapping parameter of AssetIn as described in the documentation (https://docs.dagster.io/_apidocs/assets#dagster.AssetIn.partition_mapping): "Defines what partitions to depend on in the upstream asset".

My concrete usecase is that I have an asset A (partitioned by time) that depends on an other asset B (also partitioned by time) but requires as input the current and previous days of asset B. This should be achievable by simply passing TimeWindowPartitionMapping(start_offset=-1, end_offset=0) into the partition_mapping parameter of AssetIn. 

As far as I can tell however this parameter is ignored and instead : 
`partition_mapping = assets_def.infer_partition_mapping(upstream_asset_key)`
is called...

### What did you expect to happen?

I expected the partition_mapping parameter of AssetIn to be taken into account.

### How to reproduce?

```python

# example from https://docs.dagster.io/concepts/partitions-schedules-sensors/partitions#partitioned-assets-with-partitioned-io-managers
import pandas as pd

from dagster import DailyPartitionsDefinition, asset, TimeWindowPartitionMapping, AssetIn


@asset(partitions_def=DailyPartitionsDefinition(start_date="2022-01-01"))
def my_daily_partitioned_asset(context) -> pd.DataFrame:
    partition_date_str = context.asset_partition_key_for_output()
    return pd.read_csv(f"coolweatherwebsite.com/weather_obs&date={partition_date_str}")

# the issue is here: partition_mapping defined in AssetIn is ignored!
@asset(
  partitions_def=DailyPartitionsDefinition(start_date="2022-01-02"),
  ins=dict(
    my_daily_partitioned_asset=AssetIn(
        partition_mapping=TimeWindowPartitionMapping(start_offset=-1, end_offset=0)
    )
  ),
)
def problematic_asset(my_daily_partitioned_asset: pd.DataFrame) -> pd.DataFrame:
  # here I would assume we get 2 partitions:
  # the one from the current day and one from the previous day
  return my_daily_partitioned_asset

```

### Deployment type

None

### Deployment details

Same issue on local and k8s deployments

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I just tried out a slightly simplified version of your example:
```python
from dagster import DailyPartitionsDefinition, asset, TimeWindowPartitionMapping, AssetIn


@asset(partitions_def=DailyPartitionsDefinition(start_date="2022-01-01"))
def my_daily_partitioned_asset(context):
    partition_date_str = context.asset_partition_key_for_output()
    return partition_date_str


@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2022-01-02"),
    ins=dict(
        my_daily_partitioned_asset=AssetIn(
            partition_mapping=TimeWindowPartitionMapping(start_offset=-1, end_offset=0)
        )
    ),
)
def problematic_asset(context, my_daily_partitioned_asset):
    context.log.info(my_daily_partitioned_asset)
    return my_daily_partitioned_asset
```

I launched individual materializations of 2022-01-01 and 2022-01-02 for the first asset. Then I tried to launch 2022-01-02 of the second asset. I encountered this:
```
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/plan/execute_plan.py", line 266, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/plan/execute_step.py", line 350, in core_dagster_event_sequence_for_step
    for event_or_input_value in ensure_gen(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/plan/inputs.py", line 185, in load_input_object
    load_input_context = step_context.for_input_manager(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/context/system.py", line 614, in for_input_manager
    self.asset_partitions_subset_for_input(name)
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/context/system.py", line 927, in asset_partitions_subset_for_input
    return partition_mapping.get_upstream_partitions_for_partitions(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py", line 82, in get_upstream_partitions_for_partitions
    return self._map_partitions(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py", line 126, in _map_partitions
    check.invariant(from_partitions_def == to_partitions_def)
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_check/__init__.py", line 1629, in invariant
    raise CheckError("Invariant failed.")
```

Is that what you encountered? I'm going to post a PR to relax this constraint that the two PartitionsDefinitions need to be identical. They just need the same schedule type (daily, hourly, etc.).

I then tried changing the partitions_def of the second asset to `DailyPartitionsDefinition(start_date="2022-01-01")`, and I the message I expected was logged when the second asset ran:
```
{'2022-01-01': '2022-01-01', '2022-01-02': '2022-01-02'}
```

**Comment by sryza** [comment]
Here's the PR: https://github.com/dagster-io/dagster/pull/11422

**Comment by ynotzort** [comment]
Thanks a lot! Yes what you mentioned is part of the issue, but there is another one, it took me a bit to isolate the issue:

Version A
```python

@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2022-12-01"),
    key_prefix=["staging"],
)
def my_daily_partitioned_asset(context):
    partition_date_str = context.asset_partition_key_for_output()
    return partition_date_str

@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2022-12-01"),
    key_prefix=["staging"],
    ins=dict(
        my_daily_partitioned_asset=AssetIn(
            key="my_daily_partitioned_asset",
            partition_mapping=TimeWindowPartitionMapping(start_offset=-1, end_offset=0)
        )
    ),
)
def problematic_asset(context, my_daily_partitioned_asset):
    context.log.info(my_daily_partitioned_asset)
    return my_daily_partitioned_asset
```

Version B
```python

@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2022-12-01"),
    key_prefix=["staging"],
)
def my_daily_partitioned_asset(context):
    partition_date_str = context.asset_partition_key_for_output()
    return partition_date_str

@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2022-12-01"),
    key_prefix=["staging"],
    ins=dict(
        my_daily_partitioned_asset=AssetIn(
            key=["staging", "my_daily_partitioned_asset"],  # <- this changed!
            partition_mapping=TimeWindowPartitionMapping(start_offset=-1, end_offset=0)
        )
    ),
)
def problematic_asset(context, my_daily_partitioned_asset):
    context.log.info(my_daily_partitioned_asset)
    return my_daily_partitioned_asset
```

The change is in the key of the problematic asset. If I try to materialize "2022-12-02" then I get:
- for Version A:  "2022-12-02"
- for Version B: {'2022-12-01': '2022-12-01', '2022-12-02': '2022-12-02'} (this is the expected behavior)

so apparently I had a pretty specific configuration that troubled me, but you helped me find a solution, so thanks!
Anyways even if Version A is not how AssetIn should be used, maybe throwing a warning would be helpful...

**Comment by sryza** [comment]
@ynotzort I was able to reproduce this.

Based on some initial code-spelunking, it must be some problem with how the dependencies are getting resolved in `StepExecutionContext.has_asset_partitions_for_input`.

**Comment by sryza** [comment]
Here's a fix: https://github.com/dagster-io/dagster/pull/11483
