### ISSUE TITLE
dagit: "maximum recursion depth exceeded" for asset that depends on earlier partitions of itself

### ISSUE THREAD

**Issue by ynotzort** [dagster-io/dagster#11440]
### Dagster version

dagster, version 1.1.7

### What's the issue?

When trying to use an asset that depends on earlier partitions of itself, dagit shows the following error message when viewing the Global Asset Lineage.

```
Operation name: AssetGraphLiveQuery

Message: maximum recursion depth exceeded

Path: ["assetNodes",13,"projectedLogicalVersion"]

Locations: [{"line":44,"column":3}]
```

Materializing the assets works as expected.

Also got this one once, but can't currently reproduce: `Message: maximum recursion depth exceeded while getting the str of an object` (it had `Path: ["assetNodes",16,"projectedLogicalVersion"]`)

### How to reproduce?

small example to reproduce the issue

```python
@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2022-12-01"),
    key_prefix=["staging"],
)
def my_daily_partitioned_asset(context):
    partition_date_str = context.asset_partition_key_for_output()
    return partition_date_str

@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2022-12-01"),
    key_prefix=["staging"],
    ins=dict(
        my_daily_partitioned_asset=AssetIn(
            key=["staging", "my_daily_partitioned_asset"],  # <- this changed!
            partition_mapping=TimeWindowPartitionMapping(start_offset=-1, end_offset=0)
        ),
        problematic_asset_prev=AssetIn(
            key=["staging", "problematic_asset"],  # <- this changed!
            partition_mapping=TimeWindowPartitionMapping(start_offset=-1, end_offset=-1)
        ),
    ),
)
def problematic_asset(context, my_daily_partitioned_asset, problematic_asset_prev):
    context.log.info(my_daily_partitioned_asset)
    context.log.info(problematic_asset_prev)
    return my_daily_partitioned_asset

```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I observed this too. I believe it's fixed by this PR: https://github.com/dagster-io/dagster/pull/11204, which will be included in this week's release.
