### ISSUE TITLE
Running backfill for partitioned assets fail because of not providing configuration defined in other asset

### ISSUE THREAD

**Issue by jzgrzebnicki** [dagster-io/dagster#11462]
### Dagster version

1.1.3

### What's the issue?

Hi, I have one asset defined with configuration that need config to be run and second with partitions where no config is required. When I'm running materialization for second asset of one partition at a time it works fine, but when trying to run set of partition I'm getting:
An exception was thrown during execution that is likely a framework error, rather than an error in user code.
dagster._core.errors.DagsterInvalidConfigError: Error in config for job
Error 1: Missing required config entry "ops" at the root. Sample config for missing entry: {'ops': {'op1': {'config': {'in_file_name': '...', 'in_sheet_name': '...'}}, 'op2': {'config': {'in_file_name': '...', 'in_sheet_name': '...'}}}}
It seems that somehow first asset interfere with the second one even if they are not connected

### What did you expect to happen?

I expect backfill to generate jobs correctly

### How to reproduce?

generate some asset job with defined config and second asset group without, then try to run backfill for more than one partition for asset from group without config:
```
power_plans_assets_job = define_asset_job(
    f'{ASSET_GROUP}_group_materialize',
    AssetSelection.groups(ASSET_GROUP),
    config=config_from_files(
        [file_relative_path(__file__, "config/config.yml")]
    ),
    description=f"Job for materializing assets from group {ASSET_GROUP}",
)
```
and here are assets from completely different group:
```
from dagster import DailyPartitionsDefinition, MonthlyPartitionsDefinition, asset, OpExecutionContext, define_asset_job
from datetime import datetime

dayli = DailyPartitionsDefinition(datetime(2022, 12, 1))
monthly = MonthlyPartitionsDefinition(datetime(2022, 12, 1))

@asset(partitions_def=dayli, group_name='partitioned')
def assetdaily(context: OpExecutionContext):
    context.log.info(context.partition_key)
    return context.partition_key

@asset(partitions_def=monthly, group_name='partitioned')
def assetmonthly(context: OpExecutionContext, assetdaily):
    context.log.info(context.partition_key)
    context.log.info(assetdaily)
```

### Deployment type

Local

### Deployment details

running local with:
dagit -m dagster_repo -a repo_local
dagster-daemon run -m dagster_repo -a repo_local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jzgrzebnicki** [comment]
Additionally it seems that generated runs don't have step_selecion defined:
![Screenshot from 2023-01-02 09-44-46](https://user-images.githubusercontent.com/104764118/210213828-01bb3b47-cc40-4c09-961e-2df9cdbf6d5f.png)

**Comment by jzgrzebnicki** [comment]
Seems that it's fixed in newer version... on 1.1.7 I don't have such problem ;)

**Comment by sryza** [comment]
Awesome
