### ISSUE TITLE
Dagit Repository Navbar UI elements flickering & unnecessarily truncated

### ISSUE THREAD

**Issue by ssingh13-rms** [dagster-io/dagster#11489]
### Dagster version

1.1.7

### What's the issue?

There is an issue with Dagit UI that affects Firefox (108.0.1).
1. Some Repository/Definitions navbar on the left get unnecessarily truncated. This appears to be completely random. Some longer names do not get truncated whereas names shorter than them do.
2. Some Repository/Definition names flicker in the navbar

These issues do not seem to exist when loading Dagit UI in Chrome.

### What did you expect to happen?

1.  Repository/Definitions names on the navbar to get truncated appropriately 
2. No flickering of UI elements

### How to reproduce?

Not sure if this is specific to our instance but I can try to put together a sample Dagster project that can demonstrate the issue

### Deployment type

Other Docker-based deployment

### Deployment details

Running the latest version of Dagster via Docker

### Additional information

--

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
This is fixed in master, and will be in the next release. https://github.com/dagster-io/dagster/pull/11203

Sorry about this. Thanks for the report!
