### ISSUE TITLE
environment variable not working in venv

### ISSUE THREAD

**Issue by avnav88** [dagster-io/dagster#11482]
### Dagster version

1.1.7

### What's the issue?

I am working out of pycharm in windows environment, with python 3.10.  I have a virtual environment set.

I have tried setting the `DAGSTER_HOME` variable three different ways:

1. through the pycharm config
2. with `set DAGSTER_HOME="L:\work\Dagster\volumes"` in the terminal
3. and by adding `os.environ['DAGSTER_HOME'] = r'L:\work\Dagster\volumes'` to the `__init__.py` file

when i run `pip install -d ".[dev]"  and then `dagit`, a temp file gets created to house the dagit data instead of going to my chosen directory.

### What did you expect to happen?

i expect the dagit data to persist in my volumes directory.

instead i get:

```
(venv_dagster) PS L:\work\Dagster\Resources\resources_test> dagit
Using temporary directory L:\work\Dagster\Resources\resources_test\tmpwx5j142i for storage. This will be removed when dagit exits.
To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to use.
```

### How to reproduce?

create a pycharm project and try to run the dagit server out of a virtual environment

### Deployment type

Local

### Deployment details

this is done on a local desktop, trying to get to local:3000

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by avnav88** [comment]
i've now tried the `python-dotenv` method also

**Comment by ei-grad** [comment]
Did you check that it is set in the current shell session before running dagit?

**Comment by avnav88** [comment]
i believe you are right there's something wrong maybe with the indexing on pycharm -- shoulda double checked!
