### ISSUE TITLE
Dagster stack traces should print important error messages together at the bottom

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1148]
See:

![image](https://user-images.githubusercontent.com/609349/55665405-d395f380-57f3-11e9-90e7-1a4a0164639b.png)

maybe we can group the important messages together in the footer of this message/log spew?

**Comment by mgasner** [comment]
this is probably possible with a little bit of traceback surgery

**Comment by natekupp** [comment]
I feel like this has considerably improved. I haven't seen any cryptic errors like this in a long time. Let's re-open if we see more of these
