### ISSUE TITLE
cannot run "pytest dagster-framework" from python_modules even though the dagster-framework folder exists

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1149]
This breaks:

![Screenshot 2019-04-06 06 55 25](https://user-images.githubusercontent.com/28738937/55670437-15955880-5839-11e9-97cf-195bdba98d16.png)

This works:

![Screenshot 2019-04-06 06 56 40](https://user-images.githubusercontent.com/28738937/55670444-25ad3800-5839-11e9-9c2e-864575dea67a.png)

**Comment by mgasner** [comment]
This is sort of by design since dagster_framework is not a module, but we can probably make the experience better by deviating a little from python packaging norms

**Comment by schrockn** [comment]
Sorry to be clear this is when the you are targeting the "dagster-framework" folder, which should still work

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
We've reorganized to libraries/
