### ISSUE TITLE
On backfills overview page, fill out "Backfill target" column for pure asset backfills

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#11515]
We could list the assets that were targeted by the backfill:
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/654855/210673989-e1295e1d-4803-42cb-ae30-4543535b7f02.png">

**Comment by bengotow** [comment]
I think this should be working - here's what the UI looks like for me with a few tweaks applied (https://github.com/dagster-io/dagster/pull/11693). I'd be curious if the asset selection is not set on these backfills for some reason, or if the target is not in a loaded repo?

edit: It looks like in that PR I have one case where there was no context provided, I'll see how that happened. Maybe it's asset-related

**Comment by bengotow** [comment]
Hmm it looks like there is one case we're missing support for. Backfills that specify an asset selection and contain partitionNames, but have no partition set name or partition set linked.

I'm going to update #11693 to support this case, but I wonder if this is a bug? It seems odd the backfill would have partition keys but not be linked to a job partition set.

![image](https://user-images.githubusercontent.com/1037212/212373636-53915885-f719-4351-ba3f-d291c47e13f2.png)

**Comment by sryza** [comment]
> I'm going to update https://github.com/dagster-io/dagster/pull/11693 to support this case, but I wonder if this is a bug? It seems odd the backfill would have partition keys but not be linked to a job partition set.

This is now possible with the new pure asset backfills, which can handle backfills across assets that live in different base asset jobs.
