### ISSUE TITLE
Better formatting for config schema errors

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1152]
Set up a bad config for a Spark solid, get this:

![image](https://user-images.githubusercontent.com/609349/55678663-70b76180-58b2-11e9-957a-d1d102749d7c.png)

**Comment by natekupp** [comment]
and this

![image](https://user-images.githubusercontent.com/609349/55678668-89c01280-58b2-11e9-926f-adc937c87fc8.png)

**Comment by mgasner** [comment]
Just to make it easier to reproduce, do you happen to know which pipeline this is from or which pipeline we can use to get a similar experience?

**Comment by mgasner** [comment]
cc @helloworld

**Comment by natekupp** [comment]
In particular, this is really tough to read w/ very large config schemas like Spark—should possibly pretty print?

**Comment by catherinewu** [comment]
the current formatting (error in bottom left corner) seems nicer now, going to close. feel free to re-open with repro steps
