### ISSUE TITLE
Mysterious runtime type error

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1156]
{"data": null, "errors": [{"locations": [{"column": 3, "line": 33}], "message": "Runtime Object type \"PythonError\" is not a possible type for \"ExecutePlanResult\"."}]}

Steps to reproduce:
- Check out 6b06af3b236050473b18ec56a79588668b7242ee
- cd dagster/python_modules/dagster-airflow
- pytest -vv -k TestExecuteDag

**Comment by schrockn** [comment]
So this is likely happening if you are attempting to load a repository or pipeline and the code errors out. 

The question is what is the ideal behavior when this happens. Should this be in the application domain (i.e. the graphql type system) or should the query fail and be reported in the graphql['errors']. There's an argument either way.

**Comment by mgasner** [comment]
I don't feel strongly except that I'd like us not to swallow the underlying Python error -- right now the user doesn't know what to do next. I was able to debug this a little in the GraphQL explorer, where I get a different & more informative error than from dagit -q (I suspect the issue is with AWS credentials) -- we should unify the error path:

```{
  "errors": [
    {
      "message": "Unable to locate credentials",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "executePlan"
      ]
    }
  ],
  "data": null
}```

**Comment by mgasner** [comment]
Query is ```mutation(
  $config: PipelineConfig = {
  context: {
    default: {
      config: {
        log_level: "DEBUG"
      }
    }
  },
  solids: {
    multiply_the_word: {
      config: {
        factor: 2
      },
      inputs: {
        word: {
          value: "bar"
        }
      }
    }
  },
  storage: {
    s3: {
      s3_bucket: "dagster-airflow-scratch"
    }
  }
},
  $pipelineName: String = "demo_pipeline",
  $runId: String = "fa0d1215-5f38-4842-9139-95c71ba694bd",
  $stepKeys: [String!] = ["multiply_the_word.word.input_thunk", "multiply_the_word.transform"]
) {
  executePlan(
    config: $config,
    executionMetadata: {
      runId: $runId
    },
    pipelineName: $pipelineName,
    stepKeys: $stepKeys,
  ) {
    __typename
    ... on PipelineConfigValidationInvalid {
      pipeline {
        name
      }
      errors {
        __typename
        message
        path
        reason
      }
    }
    ... on PipelineNotFoundError {
        message
        stack
        pipelineName
    }
    ... on ExecutePlanSuccess {
      pipeline {
        name
      }
      hasFailures
      stepEvents {
        step {
          key
          solid {
            name
          }
          kind
        }
        __typename
        ... on ExecutionStepOutputEvent {
          outputName
          valueRepr
        }
        ... on ExecutionStepFailureEvent {
          error {
              message
          }
        }
      }
    }
  }
}
```

**Comment by mgasner** [comment]
Seems broader. I'm getting the same
