### ISSUE TITLE
Eliminate Repository Container

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1157]
Now that we do not do live reloading, the RepositoryContainer should go away. It is a poor abstraction that has unfortunately spread throughout the codebase. I believe we should do a much more functional approach where you clearly separate out the cases where you have a constructed repository versus a repository_target_info which is a serializable object that has enough information to reconstruct a repository. It, in essence, contains the arguments passed in our CLI tools that are sufficient to reconstruct a repository.

I attempted to do this but hit a blocker in our airflow integration where an emphemeral repository is constructed, which I think is problematic.

**Comment by natekupp** [comment]
Fixed in https://dagster.phacility.com/D81
