### ISSUE TITLE
Adding tags to backfill runs from Dagit UI

### ISSUE THREAD

**Issue by Beaglefoot** [dagster-io/dagster#11585]
### What's the use case?

Adding tags allows to manage concurrency, restrict resources and lower priority of backfill runs.

### Ideas of implementation

It's already available with cli:
```
dagster job backfill --tags awesome_tag
```
So it's probably possible to copy/paste [Edit Tags UI from Launchpad](https://docs.dagster.io/concepts/ops-jobs-graphs/metadata-tags#specifying-tags) and somehow reuse API from the code snippet above.

### Additional information

I have a vague idea that this was available at some point in time previously.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@bengotow mind taking a look at this one?

**Comment by sryza** [comment]
Just came across another request for this one. @bengotow - would we be able to get this done in time for the next release?

**Comment by bengotow** [comment]
Hey gang, yep there's a pull request up for this actually just forgot to tag it: https://github.com/dagster-io/dagster/pull/11656
