### ISSUE TITLE
Figure out future for dagster-sqlalchemy

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1159]
Right now we are in a bit of weird spot because SC has a repo that actually relies on the *internals* of dagster-sqlalchemy. I would propose that we actually full move over a copy of the current dagster-sqlalchemy into the SC repository, allowing us to "control our destiny" in terms of our sqlalchemy, which needs a lot of work. SC would then be free to fork, evolve, etc what is there now. Then once dagster-sa is improved, they could start to use it again; or they could migrate to DBT obviating the need for it.

**Comment by schrockn** [comment]
Obviously this needs to be done in concert with SC but I'd like to figure out a plan by EOW.

**Comment by dmsfabiano** [comment]
Is there any documentation on how to properly handle sql-alchemy session's specially around concurrent `ops`?

**Comment by mjmare** [comment]
That would be a useful example, even in the era of assets
