### ISSUE TITLE
Maximum recursion depth exceeded when non partitioned asset depends on asset with self dependency

### ISSUE THREAD

**Issue by tha23rd** [dagster-io/dagster#11600]
### Dagster version

1.1.9

### What's the issue?

The following asset setup:

```py
@asset(
    partitions_def=HourlyPartitionsDefinition(start_date="2023-01-01-00:00"),
    ins={
        "hourly_depends_on_past": AssetIn(
            partition_mapping=TimeWindowPartitionMapping(start_offset=-1, end_offset=-1)
        )
    }
       )
def hourly_depends_on_past(hourly_depends_on_past):
    time.sleep(3)
    return 1

@asset
def non_partitioned(hourly_depends_on_past):
    time.sleep(30)
    return 1
```
   
   Produces the following error message in the dagit UI when loaded:
```
   Operation name: AssetGraphLiveQuery

Message: maximum recursion depth exceeded

Path: ["assetNodes",1,"projectedLogicalVersion"]

Locations: [{"line":41,"column":3}]
```

### What did you expect to happen?

Expected the two assets to be able to not produce an error when viewing in Dagit

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I was able to reproduce this. I've asked @smackesey to look into it.

**Comment by tha23rd** [comment]
@sryza Wondering if ya'll were able to find the cause of this?

**Comment by sryza** [comment]
@smackesey - are we able to get a fix out for this this week?

**Comment by smackesey** [comment]
>are we able to get a fix out for this this week?

Yes, I just up a diff that fixes it.
