### ISSUE TITLE
support variables in DBT declarative scheduling 

### ISSUE THREAD

**Issue by geoHeil** [dagster-io/dagster#11613]
### What's the use case?

https://dagster.slack.com/archives/C04CW71AGBW/p1673368975821419 support DBT variables in DBT configuration

### Ideas of implementation

parse the variables

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@OwenKephart does this match your expectation?

**Comment by OwenKephart** [comment]
Are you using `load_assets_from_dbt_project` or `load_assets_from_dbt_manifest`? With the latter, assuming the manifest you're using was compiled with the relevant variables supplied, I'd expect this to work (dbt should render the variables into the config automatically).

Do you mind providing a sample of the config that you provided?

**Comment by geoHeil** [comment]
Exactly. I am using `load_assets_from_dbt_project`

**Comment by rexledesma** [comment]
[`@dbt_assets`](https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.dbt_assets) supports using `--vars` with `DbtCliResource`, so I'm closing this issue.
