### ISSUE TITLE
Automatic asset reconciliation fails for imported DBT project with sources

### ISSUE THREAD

**Issue by marvin-roesch** [dagster-io/dagster#11627]
### Dagster version

1.1.8

### What's the issue?

We want to use Dagster for scheduling (incremental) DBT model updates. To this end, we import our DBT project into dagster with `load_assets_from_dbt_project`. This generates a single `AssetsDefinition` for all our models, but also includes dependencies on external sources used by models that are not known to Dagster. These are displayed correctly as source assets in the dependency graph in Dagit.

However, when trying to use the built-in asset reconciliation sensor (via `build_asset_reconciliation_sensor`), it fails as the `AssetGraph` does not recognize the asset keys of the source assets. In particular, `get_non_source_roots` and its callees treat the source asset keys as regular assets.

`load_assets_from_dbt_project` should probably return `SourceAssets` for these keys rather than only having them implicitly defined as part of dependencies in the `AssetsDefinition`.

### Deployment type

Local

### Additional information

A quick and easy workaround for this issue is to use a `source_key_prefix` such as `['sources']` for all the DBT sources and then manually create assets for them like so:

```python
source_asset_keys = set()
for asset_def in dbt_assets:
    for deps in asset_def.asset_deps.values():
        for dep in deps:
            if dep.path[0] == 'sources':
                source_asset_keys.add(dep)

source_assets = [
    SourceAsset(key=key) for key in source_asset_keys
]
```

It would be preferable if the library would already (optionally) generate these assets for us, however.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@OwenKephart is this something you just fixed?

**Comment by OwenKephart** [comment]
> @OwenKephart is this something you just fixed?

yep! thanks for the report, a fix has been merged in and will go out with tomorrow's release.
