### ISSUE TITLE
Dagster Run Hangs on ECS/Fargate

### ISSUE THREAD

**Issue by ustulation** [dagster-io/dagster#11628]
### Dagster version

1.1.1

### What's the issue?

Every once in a while when we trigger some jobs from dagit, the dagit UI shows that the `run` is stuck in `Starting` for a long time. The only output in these cases is:
```
RUN_ENQUEUED
RUN_DEQUEUED
RUN_STARTING

ENGINE_EVENT:
[EcsRunLauncher] Launching run in ECS task
ECS Task ARN
arn:aws:ecs:us-east-1:<account-num>:task/<rest-of-arn>
ECS Cluster
arn:aws:ecs:us-east-1:<account-num>:cluster/<rest-of-arn>
Run ID
8642713a-06f6-42b0-842c-c0d171d3c57f
```

And nothing else. I suppose it happens if the task container got destroyed before it could do anything (internally by `AWS`) etc but I'm not sure.

In any case it would be nice to have:
1. Dagster detect this and error out (or respawn the task)
2. Have a job-timeout configuration such that if it doesn't complete in a given time-frame it errors out and halts. This could help alert us when launching hangs in such a manner as above.

We use a simple `define_asset_job()` with not much configuration. The launcher is the `ECSRunLauncher`.

Is this a know issue and are there any solutions? Do we have a job-level timeout in dagster?

### What did you expect to happen?

RunLauncher to detect that the launch is taking excessive time and fail.

### How to reproduce?

Using `ECSRunLauncher` for `AWS Fargate`.

### Deployment type

Other

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ustulation** [comment]
[Maybe related to this in the docs](https://docs.dagster.io/deployment/run-monitoring), but there's nothing about `ECSRunLauncher` there unfortunately. Could that be it? And is there any ETA for `ECSRunLauncher` being able terminate hung jobs?

**Comment by gibsondan** [comment]
Hi @ustulation - we'll get those docs updated, we actually do support the EcsRunLauncher for the "stuck in starting" feature mentioned there.

**Comment by gibsondan** [comment]
i.e. you can configure start_timeout_seconds and any runs that are stuck in STARTING will be terminated, regardless of the run launcher that you're using.

**Comment by ustulation** [comment]
Oh I see, thanks!
