### ISSUE TITLE
Jobs API doc doesn't document `compose_fn` arg

### ISSUE THREAD

**Issue by laserson** [dagster-io/dagster#11637]
### What's the issue or suggestion?

The [API reference](https://docs.dagster.io/_apidocs/jobs) for `dagster.job` lists `compose_fn` as the first arg of the function but doesn't mention it further in the docs. In particular, what are the constraints on this function that I write, and what args can it take? For example, can it take `context` as a first arg? (I think so? Seems like this ends up wrapping a graph object.)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I just merged [a change](https://github.com/dagster-io/dagster/pull/11655) that adds some additional documentation there. Feel free to reopen if you think more is required. Graph and job do not accepts a context argument - context is available to the ops without it being explicitly passed through.
