### ISSUE TITLE
If you can't load pipelines (e.g due to syntax error) and press execute dagit gets borked

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1172]
Repro:

Load a pipeline.
Execute it.
Change code to be invalid.
Execute it. You get in the following state.

![Screenshot 2019-04-08 15 16 20](https://user-images.githubusercontent.com/28738937/55760579-53e57000-5a11-11e9-8d28-546c5f7d69c4.png)

**Comment by mgasner** [comment]
This is also resolved by https://dagster.phacility.com/D626
