### ISSUE TITLE
[dagster-dbt] Emit Outputs/AssetMaterialization events as the dbt command executes, rather than waiting for run_results.json

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#11752]
### What's the use case?

Currently, we wait for the run_results.json file to become available before we emit any outputs. For very large dbt projects, this has two issues:

1. Large dbt projects (generally) take a while to run, meaning tables may be materialized well before their materialization event is created.
2. Each output requires three events to be emitted (OUTPUT, ASSET_MATERIALIZATION, STEP_OUTPUT). If the time it takes to write each event is high, then writing the (potentially thousands) of events at the end of dbt execution can take a non-negligible amount of time.

### Ideas of implementation

We'd need to add a new method, akin to `execute_cli`, that executes a given command/arguments in a streaming manner. We'd then consume from that stream within the body of the op. By default, dbt will provide us logs in a JSON format, so it likely would be possible to parse this json output to detect when models are materialized (or fail to be materialized).

This behavior should be made optional, as it would preclude us from being able to attach certain types of metadata (that only becomes available at the end of execution) to the outputs.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by NiallRees** [comment]
Hi @OwenKephart, hope you don't mind me asking a question on this issue but it seemed the most appropriate place. We're now using this feature, and I'm wondering if it's possible to view each model's materialization in the overall run timing chart, even though it's technically a single dbt op. So rather than a single dbt bar per the screenshot, we'd see a separate bar for each model. dbt Cloud does this and it makes it really easy to identify bottlenecks in the DAG.

What we currently see
<img width="836" alt="image" src="https://github.com/dagster-io/dagster/assets/23722609/bdb64286-4cf3-4c8d-83f2-49a3b98b29d2">

What would be nice to see
![image](https://github.com/dagster-io/dagster/assets/23722609/b3d7b95e-9e1a-4d84-8e3b-29ba73073536)

**Comment by sryza** [comment]
@NiallRees @karakanb - I filed an issue to track this request: https://github.com/dagster-io/dagster/issues/14559

**Comment by NiallRees** [comment]
Thank you @sryza !

**Comment by egeyumlu-cl** [comment]
Hey community, I have been working on a dagster-dbt project. I have ADF pipelines, which ingest the data into an SQL server for DBT to use. The execution of the dbt assets, still waits for ALL the ADF pipelines to execute fully. They don't start executing after all their dependencies are done. This leads to a lot of time wasted as all the dbt assets wait for the last ADF pipeline ( which takes really long and only one dbt model is dependent on it). 

I saw in the issue number #12070 that a similar idea was discussed with this as the solution. Nevertheless, I still don't see paralelism on my side. Can someone verify the versioning required for this change and how to identify if it is working properly?

I see that the dbt run (all the dbt assets wait for the last ADF execution)

**Comment by OwenKephart** [comment]
Hi @egeyumlu-cl -- the issue here is that all dbt commands for a single `@dbt_assets` are executed within a single step, and so in order for that step to start, all upstreams of that step must be ready, regardless of if some subset of the dbt models could start earlier.

One workaround is to break your dbt assets up into multiple smaller steps, for example, you could segment that last dbt model which is dependent on the slow ADF pipeline into its own definition:

```python
@dbt_assets(..., exclude="slow_model")
def dbt_assets_without_slow_model(): ...

@dbt_assets(..., select="slow_model")
def dbt_assets_slow_model(): ...

```

This would allow the slow model to execute independently of the other models.
