### ISSUE TITLE
Error when calling `run_request_for_partition` from multiple partitioned job sensor

### ISSUE THREAD

**Issue by grafael** [dagster-io/dagster#11766]
### Dagster version

1.1.9

### What's the issue?

When using `run_request_for_partition` function from a multiple job sensor it does return the following error:
<img width="1707" alt="error" src="https://user-images.githubusercontent.com/7319476/213243530-be6abd29-8841-4f2a-8e80-2cf643b5edc8.png">

I cannot use `RunRequest` because it does not allow partitions

Slack discussion: https://dagster.slack.com/archives/C01U954MEER/p1673958486850079

### What did you expect to happen?

Return a Request without error

### How to reproduce?

Create a code similar to this:

```python
my_job = define_asset_job(
    name="my_job",
    selection=AssetSelection.groups("my_groups"),
    partitions_def=my_partitions,
)

my_second_job = define_asset_job(
    name="my_second_job",
    selection=AssetSelection.groups("my_second_groups"),
    partitions_def=my_second_partitions,
)


@sensor(
    jobs=[my_job, my_second_job],
    default_status=DefaultSensorStatus.RUNNING,
    minimum_interval_seconds=30,
)
def my_sensor():

    for key in partitions:
        request =  my_job.run_request_for_partition(
            partition_key=key, run_key=key
        )

        yield request

    for key in second_partitions:
        second_request =  my_second_job.run_request_for_partition(
            partition_key=key, run_key=key
        )

        yield second_request
```

### Deployment type

Local

### Deployment details

No customization 

### Additional information

It does work if I do use a single-partitioned job

```python
@sensor(
    job=my_job,
    default_status=DefaultSensorStatus.RUNNING,
    minimum_interval_seconds=30,
)
def my_sensor():
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this. This should fix: https://github.com/dagster-io/dagster/pull/11780.
