### ISSUE TITLE
Page for monitoring an asset / non-job backfill

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#11779]
If you launch a backfill from a job page, Dagit has a place for your to monitor the backfill: a filtered version of the job's partition page.

However, you can also launch backfills from the asset graph, and in that case we just send you to the list of all runs with that backfill tag. This isn't very useful for understanding the progress of the backfill.

It would be helpful to provide a page with a similar UI to the job partitions page for monitoring pure asset backfills.

**Comment by braunjj** [comment]
@sryza Let's chat about this one in our weekly sync
