### ISSUE TITLE
When there are no inputs or outputs highlight box looks off center

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1178]
<img width="673" alt="Screenshot 2019-04-08 19 34 26" src="https://user-images.githubusercontent.com/28738937/55769366-6a052780-5a35-11e9-9f14-9d922bd909a1.png">

**Comment by mgasner** [comment]
This is resolved[
<img width="462" alt="Screen Shot 2019-07-17 at 2 31 03 PM" src="https://user-images.githubusercontent.com/427016/61413120-8b30ac00-a89f-11e9-8e83-1b30728ffb10.png">
](url)
