### ISSUE TITLE
Microsoft Teams Integration

### ISSUE THREAD

**Issue by gu-xie** [dagster-io/dagster#11783]
### What's the use case?

As an Enterprise customer, we leverage Microsoft Teams for our communication in the organization.

Would be great to have Alerts in Dagster Cloud integrate to Microsoft Teams via their `WebhookURL` so we can get notifications of Job Failures instead of relying on Email notifications.

### Ideas of implementation

It's a very similar integration with Slack, except Microsoft Teams tend to be more restrictive to a particular `WebhookURL`, that is tied to a singular channel. 

I'd recommend starting with a simple integration via the `WebhookURL` method, then expanding to a bot later on.

### Additional information

Highly recommend using Microsoft Team's Adaptive Card method too.
https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/design-effective-cards?tabs=design

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
Hey! This is a super reasonable request - we use issues primarily for stuff for the OSS project, not the cloud product, so going to close this, but I'm making sure this request is represented in our feature request tracking for cloud. Thanks!
