### ISSUE TITLE
Add a scaffold default config button

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#11828]
For cases where you want to provide config in the launchpad, but you've provided all default values, in order to change config values away from the default, you have to manually type everything. Would be a lot more straightforward to just have a button that scaffolded defaults for you so that you could easily change the values you care about.

This kind of works already if you use jobs, (we auto-fill default config for jobs) but only if you provide a top level config argument.

From slack thread: https://dagster.slack.com/archives/C01U954MEER/p1674109975914069

**Comment by C0DK** [comment]
potentially not simply scaffold the whole thing, but maybe by clicking on entries to the right, it will scaffold/add exactly that. because I might not want/need to scaffold logging etc, but specific parts might make sense.
