### ISSUE TITLE
Asset tags keys are being capitalized in Dagit metadata view

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#11823]
### Dagster version

1.1.11

### What's the issue?

Asset tags keys are being capitalized in Dagit metadata view. 

For example, I have 

```python
@asset(op_tags={"train": "catboost"})
def my_asset():
    ...
```

It's being shown as
![image](https://user-images.githubusercontent.com/49863538/213751680-641cceff-2be2-44e4-93fa-c0689843b834.png)

### What did you expect to happen?

I expect the key in Dagit to match the code exactly

### How to reproduce?

Define an asset with tags and open it's page in Dagit

### Deployment type

Docker Compose

**Comment by hellendag** [comment]
Thanks for the report! Can you post a larger screenshot of the page, so that we can get a better idea of the context?

**Comment by danielgafni** [comment]
![image](https://user-images.githubusercontent.com/49863538/216646574-792b9f2e-f270-4880-9815-c6b04e8b9a71.png)
Here is the page. It's the Asset Catalog, I've clicked the "View Metadata" button on the left.

**Comment by bengotow** [comment]
This will be fixed in the next release!
