### ISSUE TITLE
Consider running a local pypi accessible to Buildkite to speed up pip installs

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1183]

**Comment by mgasner** [comment]
cc @alangenfeld

**Comment by mgasner** [comment]
The state of the art has moved here: https://github.com/pypa/bandersnatch

**Comment by mgasner** [comment]
Previously, maybe still: https://devpi.net/docs/devpi/devpi/stable/+d/index.html#

**Comment by natekupp** [comment]
@mgasner I don't think we need this in the current infrastructure, as the vast majority of our python deps are cached in the buildkite images - can we close this?

**Comment by mgasner** [comment]
closing this until it becomes the low-hanging fruit in our test setup
