### ISSUE TITLE
Description at the top of the asset details panel

### ISSUE THREAD

**Issue by nicolasgallandpro** [dagster-io/dagster#11834]
### What's the use case?

When onboarding new people on dagster, they sometimes miss the description that is at the bottom of panel, and without the description they are a bit lost. And the first impression is not as good as it should be.

For people used to dagster it's quite handy to have the metadata first, but the clarity for new people is more important for me.

### Ideas of implementation

The description would be at the top of the panel, above the "Materialization in last run"

### Additional information

Discussed here : https://dagster.slack.com/archives/C01U5LFUZJS/p1674128317503089

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey folks! I think this is referring to the fact that the description appears too far down the sidebar here?

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/1037212/215884612-70af6c53-d04f-491a-aeb3-8fda34eed106.png">

**Comment by hellendag** [comment]
New designs are in the works for the Asset sidebar.

**Comment by braunjj** [comment]
Moved this back to `untriaged` @hellendag . I think we can make a quick change here while we still work on a larger sidebar redesign. Lets discuss on Tuesday.

**Comment by salazarm** [comment]
Is there an example in the toys repo I can use of a job that has assets in it?

**Comment by sryza** [comment]
@salazarm I just wrote one up: https://github.com/dagster-io/dagster/pull/12972.
