### ISSUE TITLE
Airbyte assets with '/' in stream name produce an illegal asset name

### ISSUE THREAD

**Issue by wagnermarkd** [dagster-io/dagster#11861]
### Dagster version

dagster, version 1.1.13

### What's the issue?

My environment:
* Airtable is a source in Airbyte. The streams from Airtable look like 'my-base-name/table-name'
* Using the dagster-airbyte extension and `load_assets_from_airbyte_instance` to define assets from Airbyte

When the assets for Airtable (via Airbyte) are created, an exception is thrown saying that e.g. 'my_base_name/table_name' is an invalid asset name.

### What did you expect to happen?

The assets should be loaded successfully.

### How to reproduce?

Following the [Airbyte + Dagster doc](https://docs.dagster.io/integrations/airbyte#loading-airbyte-asset-definitions-from-an-airbyte-instance), but with a stream that includes a '/' in its name.

### Deployment type

Local

### Additional information

Though I haven't tested it, I believe dashes in names are okay because Dagster is converting them to underscores in asset_decorator.py

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by chollinger93** [comment]
I can confirm this problem when writing data to any file system, where the prefix + `/` is very useful (if not to say, mandatory).

I don't think your assessment regarding the `asset_dectorator.py` logic is 100% correct. Trying that yields `KeyError: 'e2e-data'` while trying to get `metadata_by_key` in the decorator, which feeds off `outputs` in `assets_def.py` in `dagster_airbyte`. Different error with the same outcome (no assets for us :-) ).

I've created a PR for this here: https://github.com/dagster-io/dagster/pull/15902
