### ISSUE TITLE
Got an error sqlalchemy.exc.ArgumentError when tried to materialize asset

### ISSUE THREAD

**Issue by Adiyansjah** [dagster-io/dagster#11880]
### Dagster version

1.1.13

### What's the issue?

Hallo guys, i recently got this error

```
sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got [Column('run_body', Text(), table=<runs>), Column('status', String(length=63), table=<runs>)]. Did you mean to say select(Column('run_body', Text(), table=<runs>), Column('status', String(length=63), table=<runs>))
```
I am using postgres to store the data and using k8s to run the pipeline. i'm pretty sure the code run well yesterday and no error. Now i am unable to materialize the asset.

### Deployment type

Helm Chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by Adiyansjah** [comment]
Fixed by doing `pip install --force-reinstall 'sqlalchemy<2.0.0'`

**Comment by simplylizz** [comment]
Actually it's a bug. Stumbled upon the same, the version should be pinned properly.

**Comment by simplylizz** [comment]
@Adiyansjah could you please re-open?

**Comment by Adiyansjah** [comment]
Hi @simplylizz , Dagster version 1.1.14 was released and it fixed my problem.

**Comment by simplylizz** [comment]
Oh, ok.

**Comment by Partysun** [comment]
Hi @Adiyansjah, I have the same problem, my version is 1.1.14. But it doesn't help. Did you do anything else to fix it?

**Comment by simplylizz** [comment]
@Partysun if you're also installing it via helm, ensure that your "user deployments" image are also using dagster 1.1.14 (or just add to your requirements file an explicit constraint - "SQLAlchemy<2.0.0").

https://github.com/dagster-io/dagster/blob/664c2e425708f34a2033c7213307a8fc7995ad69/python_modules/dagster/setup.py#L92 - the constraint is in 1.1.14 release. It should work.

**Comment by pietercusters** [comment]
> Hi @Adiyansjah, I have the same problem, my version is 1.1.14. But it doesn't help. Did you do anything else to fix it?

Make sure to upgrade both system and user code
