### ISSUE TITLE
Remove apache-airflow 2.5.1 pin in tests

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#11889]
### What's the use case?

Verify that dagster works with apache-airflow 2.5.1 and remove the pin in our test suite

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by Ramshackle-Jamathon** [comment]
closed by https://github.com/dagster-io/dagster/pull/12776
