### ISSUE TITLE
Support composite types with specialized storage requirements

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1190]
see #1057

**Comment by mgasner** [comment]
https://dagster.slack.com/archives/CCCR6P2UR/p1588787341455600

**Comment by mgasner** [comment]
Couple ideas after talking this over with @sryza.

One thing we could do is add a `TypeStoragePlugin` on the container types that implements a scheme like serializing `List[X]` into N+1 files, with, say, `/foo/bar` being a pointer and the individual items of type X serialized at `/foo/bar/0...n`. It maybe feels tenuous to use the type storage plugin machinery for something so core.

Another thing we could do is adapt `SerializationStrategy.serialize_to_file` and `.deserialize_from_file` (or perhaps implement this on `PickleSerializationStrategy`) to special case the composite types and serialize their members to bytes, then serialize lists (or perhaps only lists of types with custom serialization strategies) as List[bytes].

We will need to walk the composite types somehow also.

**Comment by natekupp** [comment]
Moving to Assets lane FYI @sryza

**Comment by yuhan** [comment]
Closing it as we've moved away from type-based serialization
