### ISSUE TITLE
New makefile pylint command no longer takes advantage of parallelism

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1192]
Does for loop over folders. Much slower.

**Comment by schrockn** [comment]
Could also try something like https://github.com/sk-/git-lint

**Comment by mgasner** [comment]
This is improved by https://github.com/dagster-io/dagster/commit/f85583543efda25fbca7d18c1d9ed14804be0263#diff-b67911656ef5d18c4ae36cb6741b7965
