### ISSUE TITLE
Add keyboard shortcuts for scrolling dag view in dagit

### ISSUE THREAD

**Issue by Aylr** [dagster-io/dagster#1196]
It would be very handy for keyboard focused types to scroll the dag view (especially in zoomed in view) with the arrow keys.

**Comment by mgasner** [comment]
Related : more ticks for zoom. 

See: SVGViewport.autocenter, SVGViewport.onZoomAndCenter

**Comment by mgasner** [comment]
https://dagster.slack.com/archives/GJVRJ5VLZ/p1564697287015700

**Comment by mgasner** [comment]
More zoom ticks certainly helps here; closing this for now
