### ISSUE TITLE
Decision to make: Should we enforce that first argument is named "context" in a solid?

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1198]

**Comment by mgasner** [comment]
Yes, I think

**Comment by schrockn** [comment]
We will close this as resolved and readdress if user feedback demands more flexibilty. My only concern is masking a context module or similar. I'm going to add the ability to do context_ to handle those cases.

**Comment by schrockn** [comment]
Actually it already allows this. Closing
