### ISSUE TITLE
Support `working-directory` for `dagster dev` 

### ISSUE THREAD

**Issue by rob-pomelo** [dagster-io/dagster#11989]
### What's the use case?

`dagster dev` is great! We currently use the `--working-directory` flag with dagit locally (because of our use of bazel). It would be great if we could set that for `dagster dev`.

### Additional information

Could potentially take a stab at a PR if need be!

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
hey @gibsondan - if you have a minute can you take a look at this?

**Comment by gibsondan** [comment]
Fixed in https://github.com/dagster-io/dagster/pull/12026 - thanks for the report!
