### ISSUE TITLE
Asset graph truncation is causing linked assets to be indistinguishable

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#12028]
We recently added the middle truncation to the linked asset nodes in the asset graph but they now are so short that many assets become indistinguishable from each other. You have to click into each one to know what itis.

 **I think we should** :
- expand that character count a bit
- add a tooltip on hover to show the full name

Reported in slack [here](https://dagster.slack.com/archives/C01U954MEER/p1675175971059919)
**EXAMPLE:**
![image](https://user-images.githubusercontent.com/2798333/216168400-4ea8c161-41b2-48ea-a848-5ed7db2d2a55.png)

**Comment by sryza** [comment]
I think that showing the first N characters of the last segment of the asset key would likely be more informative in most situations than what we do now (first N/2 characters and the last N/2 characters or similar)

**Comment by brianjstroh** [comment]
This may be a whole separate issue, but would it be possible for the characters displayed for asset names in the lineage graph to be configured by the user? I agree that expanding the default character count a bit and showing a tooltip on hover would be very helpful too.

**Comment by bengotow** [comment]
Hey folks! I do think making the truncation configurable might be the right move... I like the idea of showing the first N characters of the last segment and that may be worth a shot before we go full-configurable. Will see what we can do and add the tooltip for this week's release.

I feel like doing a nice automatic job of this might require looking at the whole set of your asset keys and evaluating which strategy generates a more "unique" label.
