### ISSUE TITLE
Can't test time windowed partitioned asset that uses `asset_partitions_time_window_for_output`

### ISSUE THREAD

**Issue by MathieuLaksh** [dagster-io/dagster#12039]
### Dagster version

1.1.7

### What's the issue?

```
@asset(
    partitions_def=DailyPartitionsDefinition(start_date=datetime(2023, 1, 1)),
)
def partitioned_asset(context):
    start, end = context.asset_partitions_time_window_for_output()
    ...
```

Called in the test:
```
context = build_op_context(
      partition_key="2023-02-02",
  )
partitioned_asset(context)
```

Fails with 
```

self = <dagster._core.execution.context.invocation.BoundOpExecutionContext object at 0x40327af540>
output_name = 'result'

    @public
    def asset_partitions_time_window_for_output(self, output_name: str = "result") -> TimeWindow:
        """The time window for the partitions of the output asset.
    
        Raises an error if either of the following are true:
        - The output asset has no partitioning.
        - The output asset is not partitioned with a TimeWindowPartitionsDefinition.
        """
>       return self._step_execution_context.asset_partitions_time_window_for_output(output_name)
E       AttributeError: 'BoundOpExecutionContext' object has no attribute '_step_execution_context'. Did you mean: 'get_step_execution_context'?

/venv/lib/python3.10/site-packages/dagster/_core/execution/context/compute.py:392: AttributeError
```

This seems related to https://github.com/dagster-io/dagster/issues/10586, but maybe I'm missing something when using `build_op_context()`

### How to reproduce?

Create a partitioned asset that attempts to access the partition time window e.g. `start, end = context. asset_partitions_time_window_for_output()`
Attempt to call the asset function with a context created with `build_op_context`

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by prha** [comment]
@MathieuLaksh thanks for the report!  We'll take a look and get back to you.

**Comment by MathieuLaksh** [comment]
Hi! Any updates on this?

**Comment by clairelin135** [comment]
Hi Mathieu. I have a fix in progress for this: https://github.com/dagster-io/dagster/pull/13088

**Comment by MathieuLaksh** [comment]
Thanks a lot!
