### ISSUE TITLE
[Documentation Feedback] Problem on /concepts/assets/software-defined-assets page

### ISSUE THREAD

**Issue by bosmat-elementl** [dagster-io/dagster#12050]
Page links to itself instead of the next page ("Asset Materialization") at the bottom of the page

**Comment by jamiedemaria** [comment]
thanks for the catch! cc @erinkcochran87

**Comment by sryza** [comment]
I'm having trouble finding this link - it might be gone now? Closing this, but please reopen if I missed it.
