### ISSUE TITLE
`TableSchema` metadata should be collapsible in Dagit

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#12075]
### Dagster version

1.1.15

### What's the issue?

The `TableSchema` metadata takes too much screen space as it's not collapsible. I have tables with hundreds of columns and it breaks the asset metadata view.

### What did you expect to happen?

Collapse long TableSchemas in Dagit

### How to reproduce?

Log a `TableSchema` with a lot of columns

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
Thanks for the request! the UI team has been tagged and they'll take a look
