### ISSUE TITLE
Dynamic numerical based partitions

### ISSUE THREAD

**Issue by kevinschaich** [dagster-io/dagster#12076]
### What's the issue or suggestion?

I saw in https://github.com/dagster-io/dagster/pull/5764 the introduction of `DynamicPartitionsDefinition` but I can't find it anywhere in the docs.

Is there a way to do dynamic, numerical partition keys? e.g. I am pulling data from a web API that is paginated, and I want my first request to be keyed as `my_data_page1`, the next one as `my_data_page2`, but I don't know how many pages there will be in total prior to fetching?

cc: @sryza 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yuhan** [comment]
cc @sryza could it be yet another scenario for https://github.com/dagster-io/dagster/issues/7943?

**Comment by kevinschaich** [comment]
Going to post my thoughts in that thread, thanks for linking @yuhan 🙏
