### ISSUE TITLE
dagster-snowflake `execute_queries` appends results to a DataFrame instead of a list when `use_pandas_result` is True

### ISSUE THREAD

**Issue by clayheaton** [dagster-io/dagster#12084]
### Dagster version

1.1.15

### What's the issue?

[`execute_queries()` includes this code](https://docs.dagster.io/_modules/dagster_snowflake/resources#SnowflakeConnection.execute_queries):

```
        if use_pandas_result:
            import pandas as pd

            results = pd.DataFrame()
        else:
            results = []
        with self.get_connection() as conn:
            with closing(conn.cursor()) as cursor:
                for sql in sql_queries:
                    if sys.version_info[0] < 3:
                        sql = sql.encode("utf-8")
                    self.log.info("Executing query: " + sql)
                    parameters = dict(parameters) if isinstance(parameters, Mapping) else parameters
                    cursor.execute(sql, parameters)
                    if fetch_results:
                        if use_pandas_result:
                            results = results.append(cursor.fetch_pandas_all())  # type: ignore
                        else:
                            results.append(cursor.fetchall())  # type: ignore

        return results if fetch_results else None
```

If `use_pandas_result` is `True`, then each queries is retrieved with `cursor.fetch_pandas_all()`, which returns a DataFrame. However, at the top of the code block, you'll see that `results` is initialized as a DataFrame. What this means is that the code attempts to append each query's results to the `results` DataFrame. This causes failure when the queries return significantly different results. 

### What did you expect to happen?

I expect that `execute_queries()` will return a list of DataFrames when the `use_pandas_result` flag is True. This would fix it:

```
        if use_pandas_result:
            import pandas as pd

        results = []

        with self.get_connection() as conn:
            with closing(conn.cursor()) as cursor:
                for sql in sql_queries:
                    if sys.version_info[0] < 3:
                        sql = sql.encode("utf-8")
                    self.log.info("Executing query: " + sql)
                    parameters = dict(parameters) if isinstance(parameters, Mapping) else parameters
                    cursor.execute(sql, parameters)
                    if fetch_results:
                        if use_pandas_result:
                            results = results.append(cursor.fetch_pandas_all())  # type: ignore
                        else:
                            results.append(cursor.fetchall())  # type: ignore

        return results if fetch_results else None
```

### How to reproduce?

```
queries = [
    "USE SECONDARY ROLES ALL",
    "SELECT * FROM SOME_TABLE_WITH_MANY_COLUMNS LIMIT 5"
]

results = context.resources.snowflake.execute_queries(
    sql_queries=queries,
    fetch_results=True,
    use_pandas_result=True
)
```

### Deployment type

Docker Compose

### Deployment details

Deployment is not relevant to this problem

### Additional information

pandas.DataFrame.append is deprecated anyhow: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.append.html

Also note that the code example for `execute_queries()` contains an error. The first parameter is `sql_queries` and not `sql` as shown in the example.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clayheaton** [comment]
Hey @jamiedemaria - It seems like `execute_query` (singular) does not return a pandas DataFrame if `use_pandas_result=True` - perhaps because the method doesn't import pandas like `execute_queries` does? This is in a situation where I have yet to use pandas before calling `execute_query`. Anyhow, I thought I would point out the discrepancy between the two methods.

**Comment by jamiedemaria** [comment]
thanks for bringing this up! i'll look into it

**Comment by jamiedemaria** [comment]
hey so i think the issue with the second code snippet is that `fetch_results` and `use_pandas_result` are mutually exclusive. So if you just do `use_pandas_result` it should work. That there isn't an error when both parameters are True is very odd to me. I'll put up a PR to fix that in addition to the changes to `execute_queries`

**Comment by clayheaton** [comment]
> hey so i think the issue with the second code snippet is that `fetch_results` and `use_pandas_result` are mutually exclusive. So if you just do `use_pandas_result` it should work. That there isn't an error when both parameters are True is very odd to me. I'll put up a PR to fix that in addition to the changes to `execute_queries`

Thanks! If you notice, `execute_queries()` requires both parameters to be `True` to return results, which is probably why I was assuming that was the case for `execute_query()`.

**Comment by jamiedemaria** [comment]
yeah i noticed at as well. i'll also make it consistent between the two methods
