### ISSUE TITLE
When loading an observable source asset for a first time, the UI claims it is "observed" when it is not.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#12119]
### Dagster version

master

### What's the issue?

When loading an observable source asset for a first time, the UI claims it is "observed" when it is not.

![Screen Shot 2023-02-05 at 1 17 10 PM](https://user-images.githubusercontent.com/28738937/216837467-dee27d71-e16a-4d19-a6ac-abed5dd8c510.png)

![Screen Shot 2023-02-05 at 1 17 15 PM](https://user-images.githubusercontent.com/28738937/216837468-1b87ae52-77c2-4690-9ca3-282fd8f10d4e.png)

### What did you expect to happen?

It should say "unobserved" or something.

### How to reproduce?

Write an `@observable_source_asset` and load in dagit.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
@bengotow Might this be related to recent front-end changes? I think this is new and, while it's possible #11951 might somehow be responsible, I think its unlikely.

**Comment by bengotow** [comment]
Hey gang this current UI is intentional - here are all the states.

I will sync with Josh and we will find a better way to present this. I believe the problem is that "Observed" is just a label and the "-" indicates it has never been observed.

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/1037212/217095325-a32a92e7-fafc-4e74-a5fb-1d0ffff23cec.png">

**Comment by braunjj** [comment]
Maybe we should say "Latest observation" instead of "Observed" too?

**Comment by bengotow** [comment]
Talked with Josh and I know we're talking about changing Never Materialized => Missing, but adding a "Never Observed" state like this seems like a good route:

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/1037212/217101889-e691d11a-5f44-49eb-9324-fdc750059eae.png">
