### ISSUE TITLE
Make all asset materialization tags viewable in the asset page in the asset catalog

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#12133]
### What's the use case?

We want to be able to view all tags, specifically so we can display logical versioning information for observability, useful for debugging issues in production and tutorials.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@schrockn Would this be a more accurate name for this issue: "Make all asset versions viewable in the asset page in the asset catalog"

**Comment by schrockn** [comment]
Yes much more accurate. My bad.

**Comment by schrockn** [comment]
@bengotow from slack chatter looks like you are picking this up?

**Comment by bengotow** [comment]
I believe this has been completed - we show asset materialization tags (which include asset versions) on the asset materialization detail page.
