### ISSUE TITLE
Confusing `repository_name` change from `@repository` to `Definitions` pertaining to GraphQL 

### ISSUE THREAD

**Issue by ssingh13-rms** [dagster-io/dagster#12157]
### Dagster version

1.1.17

### What's the issue?

When a `Repository` is created with the new `Definitions` type, there does not appear to be a way to pass repository name to the constructor, instead a default value of `__repository__` is used. This created some confusion when I was trying to kickoff a Job remotely via a GraphQL request.

This can potentially break a lot of workflows that are using GraphQL to trigger jobs remotely, when they make the change to `Definitions`.

### What did you expect to happen?

Expected the GraphQL request to kick off the job

### How to reproduce?

Try to execute a Job defined using the new Definitions via a GraphQL request

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thoughts on this @schrockn @yuhan ?

**Comment by schrockn** [comment]
@ssingh13-rms if you want to use the new Definitions-style API but also retain the ability to name repository I think the best option is to use the `create_repository_using_definitions_args` function that we export.

**Comment by ssingh13-rms** [comment]
@schrockn can you help me find some documentation on how to use it? I searched the Dagster docs page but couldn't find anything relevant

**Comment by schrockn** [comment]
Ah this did not have a public API entry. I'll put up a PR so that goes out this week.

In the meantime this is an example:

```python
        named_repo = create_repository_using_definitions_args(
            name="a_repo",
            assets=[asset_one, asset_two],
            schedules=[a_schedule],
            sensors=[a_sensor],
            jobs=[a_job],
            resources={
                "a_resource": some_resource,
            }
        )
 ```

**Comment by ssingh13-rms** [comment]
Many thanks @schrockn!
