### ISSUE TITLE
UPathIOManager truncates paths when partition key has a "." in it

### ISSUE THREAD

**Issue by spenczar** [dagster-io/dagster#12173]
### Dagster version

dagster, version 1.1.17

### What's the issue?

I'm using a custom PartitionsDefinition which uses static decimal partitioning keys, which happen to make sense for my data. It provides partition keys which include a "." character. For example, `0.94-to-0.95` is a partition key I use.

I also use a UPathIOManager - specifically, one that works with Google Cloud Storage.

The IO manager is storing `asset` outputs in paths like `"gs://redacted/redacted/redacted/0.94-to-0"`

### What did you expect to happen?

I would expect the UPathIOManager's generated paths to be unique per partition key, but since they truncate the partition key if it has a "." character, this is not the case. Data gets overwritten.

### How to reproduce?

Make a static partition definition using keys ["0.0", "1.0"]. Make assets using that partition definition, and use a UPathIOManager. Observe the paths where the assets are stored.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Thanks for the report, we'll fix this ASAP.
