### ISSUE TITLE
Collapse "Nothing" type Inputs in DAG view

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#1218]
#1175 added a Nothing type. If a step has multiple inputs of this type, it's probably safe to collapse down in the DAG view to in some way. This would be helpful for SC folks as they have these fan in steps that don't communicate values and clutter the UI.

**Comment by bengotow** [comment]
Hey @alangenfeld I think #1263 should address this for now, but we can also see about merging them in to a single input box soon.
