### ISSUE TITLE
InstanceBackfillsQuery: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by spenczar** [dagster-io/dagster#12188]
### Dagster version

dagster, version 1.1.17

### What's the issue?

I was on the Assets page for a particular asset with many, many partitions - 10,000 partitions. I clicked "materialize asset" and selected about 350 partitions. I started the backfill job, and clicked the button which navigates me to `/overview/backfills`. I got the following error:

<img width="1640" alt="Screen Shot 2023-02-08 at 11 39 05 AM" src="https://user-images.githubusercontent.com/880413/217634137-1d42e2c5-c6df-4015-b144-9b07917aa163.png">

```
Operation name: InstanceBackfillsQuery

Message: 'NoneType' object is not iterable

Path: ["partitionBackfillsOrError","results",3,"numPartitions"]

Locations: [{"line":7,"column":9},{"line":62,"column":3}]
```

Every several seconds, "Unexpected GraphQL error" reappears on the top right.

### What did you expect to happen?

I expected to see the backfills.

### How to reproduce?

I don't know.

### Deployment type

Dagster Helm chart

### Deployment details

This dagit instance is running on a Kubernetes cluster, and I am using `kubectl port-forward` to be able to view it at a localhost address.

### Additional information

When I refresh the page, I still see the same error every time.

When I go to `/runs`, I see all 353 runs are in progress.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @spenczar - any chance there's a stack trace in your Dagit logs that correspond to this error?

**Comment by spenczar** [comment]
Sorry to say there's nothing in the logs. I'm still able to reproduce this at will, though. Any time I go to /overview/backfills I get this error. If you'd like me to `kubectl exec` into the dagit container and do anything to poke around, I can.

**Comment by sryza** [comment]
We think we've been able to reproduce this internally. @clairelin135 is investigating a fix.
