### ISSUE TITLE
[dagit] add info to Runs page

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#1222]
hashes aren't a joy for human users

total execution time
time run occurred
etc.

**Comment by alangenfeld** [comment]
i know we talked about this recently, but I couldn't find an existing issue. Please merge if dupe.

**Comment by mgasner** [comment]
pipeline name, links to config, subset info

**Comment by mgasner** [comment]
summary green # of steps that succeeded red # failed yellow? # cancelled/skipped grey # deselected

**Comment by schrockn** [comment]
https://github.com/dagster-io/dagster/pull/1257
