### ISSUE TITLE
`dagster-airflow>=1.1` CLI points to non-existent `dagster_airflow.cli`

### ISSUE THREAD

**Issue by bollwyvl** [dagster-io/dagster#12249]
### Dagster version

1.1.17-1.1.18

### What's the issue?

`dagster-airflow`'s [setup.py](https://github.com/dagster-io/dagster/blob/1.1.18/python_modules/libraries/dagster-airflow/setup.py#L71) points to `dagster_airflow.cli` that last existed in [1.1.15](https://github.com/dagster-io/dagster/blob/1.1.15/python_modules/libraries/dagster-airflow/dagster_airflow/cli.py).

```
+ dagster-airflow --help
Traceback (most recent call last):
  File "~/env/bin/dagster-airflow", line 7, in <module>
    from dagster_airflow.cli import main
ModuleNotFoundError: No module named 'dagster_airflow.cli'
```

### What did you expect to happen?

One of:
- [ ] remove the entry
- [ ] restore the module

### How to reproduce?

```bash
pip install "dagster-airflow>=1.1.17"
dagster-airflow 
```

### Deployment type

Other

### Deployment details

Downstream repackaging:
- PR on [conda-forge](https://github.com/conda-forge/dagster-feedstock/pull/245)
- build on [Azure Pipelines](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=656487&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=11773)

### Additional information

As always, thanks for dagster!

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by benpankow** [comment]
Thanks for the report! cc @Ramshackle-Jamathon

**Comment by bollwyvl** [comment]
If that `entry_point` is going to be removed, i can just patch it out on conda-forge and ship 1.1.18.

**Comment by Ramshackle-Jamathon** [comment]
@bollwyvl yep the dagster-airflow cli was removed as part of the `1.x.x` bump, so we'll be dropping `entry_point`. thanks for the report!
