### ISSUE TITLE
staleness-based versioning for partitioned assets

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12314]

**Comment by sryza** [comment]
From @spenczar:

> It would be nice if I could write a function that returns a map of partition-key -> logical version value.

**Comment by tha23rd** [comment]
This would be huge

**Comment by smackesey** [comment]
Closed by #14265

**Comment by sryza** [comment]
Closing this because we now track this data. https://github.com/dagster-io/dagster/issues/9374 tracks displaying it in more places.
