### ISSUE TITLE
Unit testing Asset Sensor requires Dagster Instance

### ISSUE THREAD

**Issue by will-holley** [dagster-io/dagster#12324]
### Dagster version

1.1.14

### What's the issue?

`build_sensor_context` declares its `instance` arg as `Optional[DagsterInstance] = None`.  It should _not_ be optional when building context for an Asset Sensor.  For example:

```python
from dagster import asset_sensor, AssetKey, SkipReason, build_sensor_context

@asset_sensor(name="foo_sensor", asset_key=AssetKey("foo"))
def my_asset_sensor(context):
    return SkipReason("Testing")


def test_my_asset_sensor():
    context = build_sensor_context(cursor="0")
    for run_request in my_asset_sensor(context):
        pass
```

will result in the following error when executed with PyTest:

```
________________________________________________________________________ test_my_asset_sensor ________________________________________________________________________
source__test__.py:26: in test_my_asset_sensor
    for run_request in my_asset_sensor(context):
dagster/_core/definitions/asset_sensor_definition.py:76: in _fn
    event_records = context.instance.get_event_records(
dagster/_core/definitions/sensor_definition.py:133: in instance
    raise DagsterInvariantViolationError(
E   dagster._core.errors.DagsterInvariantViolationError: Attempted to initialize dagster instance, but no instance reference was provided.
```

### What did you expect to happen?

I believe that the methodology for testing Sensors, as detailed [here](https://docs.dagster.io/concepts/partitions-schedules-sensors/sensors#testing-sensors) should not differ from that of testing Asset Sensors.

### How to reproduce?

The example above should suffice.

### Deployment type

Other Docker-based deployment

### Deployment details

Running in local development environment.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by will-holley** [comment]
While debugging this, I encountered another unexpected behavior worth noting:

If no event records are present, `dagster sensor preview` will skip evaluation and log `skipping: Sensor function returned an empty result` rather than evaluating the sensor (see `asset_sensor_definition.py:97`) and returning a more meaningful message or an exception.

Having spent the better part of the last 2 hours tracking this one down, increased verbosity or an outright exception detailing the event records length prerequisite would be very welcome.

**Comment by OwenKephart** [comment]
Hi @will-holley! For the original issue, it's a bit tricky to come up with a smooth solution here, as in many cases where you'd want to use `build_sensor_context`, it's unnecessary to provide an instance argument, so that parameter really should be optional. However, for cases where it is necessary (such as when providing it to an asset sensor) it'd be nice if the validation step could happen earlier in the callstack, rather than spitting out what you experienced.

For your second issue, I totally agree, and I just opened a PR to address that issue.

**Comment by will-holley** [comment]
Hey, again, @OwenKephart — thanks for the expedient response! 

Re: optionality, is there an alternative suggested way to test asset sensors? I couldn’t find anything in the docs on mocking `DagsterInstance` (but admittedly did not exhaustively check the source code), which would be ideal. As it stands, I’m not sure how to unit test this.

**Comment by OwenKephart** [comment]
ah fair enough, that should definitely be covered in the docs. I just created a how-to discussion on this topic to make the answer easier for others to find: https://github.com/dagster-io/dagster/discussions/12346.
