### ISSUE TITLE
Snowflake IO Manager should not require type hints when set up to handle only one type

### ISSUE THREAD

**Issue by clayheaton** [dagster-io/dagster#12328]
### What's the use case?

When opening a connection to Snowflake, it is possible to use `cursor.fetch_pandas.all()` to create a DataFrame without using type hints. However, when that DataFrame is passed to another asset as a parameter, the Snowflake IO Manager requires type hints to be able to read the Snowflake table into a DataFrame. This is inconvenient when working exclusively with Pandas or Spark. 

For instance, if I create an asset like this with the Snowflake IO Manager:

```
@asset
def my_asset(context) -> pd.DataFrame:
    with context.resources.snowflake.get_connection() as conn:
            with closing(conn.cursor()) as cursor:
                q2 = "SELECT * FROM SANDBOX.MY_SCHEMA.MY_TABLE"
                cursor.execute(q2)
                df = cursor.fetch_pandas_all()
                return df
```

I get an error if I try to load the same df in the next asset:

```
@asset
def my_next_asset(context, my_asset) -> pd.DataFrame:
    stuff...
```

The error is:

`dagster._check.CheckError: SnowflakeIOManager does not have a handler for type 'typing.Any'. Has handlers for types '<class 'pandas.core.frame.DataFrame'>'. Please add <class 'pandas.core.frame.DataFrame'> type hints to your assets and ops.`

### Ideas of implementation

@jamiedemaria says

> So the snowflake io manager can be set up to handle different types at once. for example you could make a snowflake io manager that can handle both pandas and pyspark dataframes. In that case we require the typing hints to know which type to load the input as. However, in the case when the io manager is only set up to handle one type, we should default to using that type if there are no hints. I’ve been mentally tracking this issue, but haven’t had a chance to fix it yet. if you want to open a github issue with your code sample and assign it to me we can officially track it

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I actually wrote a relevant PR here: https://github.com/dagster-io/dagster/pull/9373, but didn't merge it yet
