### ISSUE TITLE
No way to cancel/delete in progress and requested backfills

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#12334]
Requested in [slack](https://dagster.slack.com/archives/C01U5LFUZJS/p1676390707265019)

There is currently no way to cancel a backfill from the UI.

**Comment by hellendag** [comment]
This might be specific to these being asset backfills, and some limitation on cancelability as defined in Python.

**Comment by sryza** [comment]
Closing this as a duplicate of https://github.com/dagster-io/dagster/issues/11530
