### ISSUE TITLE
sidebar on asset graph shows outdated number of partitions

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12422]
E.g. here, where the asset node indicates that 3 partitions are filled, but the bar only shows that two are filled:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/654855/219717872-d635c732-fb8b-4cb3-a305-76dfbd5a0f0c.png">

This happens immediately after a manual asset partition materialization. Refreshing the page or closing and then reopening the sidebar fixes the issue.

**Comment by bengotow** [comment]
Merging this into https://github.com/dagster-io/dagster/issues/13023 - the issue here is that `usePartitionHealthData` is pulling the full health data from separate GraphQL queries and doesn't know to refetch when the live query on the asset graph sees the count change.
