### ISSUE TITLE
asset graph view takes a long time to register that asset has materialized

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12421]
I have a (dynamically) partitioned asset. I kicked off a run to materialize a partition. The spinner showed up immediately, and the run completed in a couple seconds, but the asset node wasn't updated to get rid of the spinner until the end of the 30-second countdown.

**Comment by bengotow** [comment]
This should have been immediate, investigating how this happened.

**Comment by bengotow** [comment]
Hmm, this seems to be working for me actually - I was able to test with a dynamically partitioned asset and I still get the correct behavior. Is there anything else I could try to narrow it down?

This feature works by subscribing to all "inProgressRunIds" and "unstartedRunIds" seen in the live asset response and watching them for materialization / observation / step failure, so it could break if some part of the pure asset backfill engine breaks those, but I haven't spotted anything like that yet. It also limits to watching 3 runs at a time for performance reasons, so it could break if you had 4+ concurrent runs going.

**Comment by sryza** [comment]
Hmm I just tried this again and it worked fine. Closing and will reopen if it returns.
