### ISSUE TITLE
ShouldShowNux permission denied graphql error in dagit (1.1.19) deployed through helm

### ISSUE THREAD

**Issue by manthena-aravind** [dagster-io/dagster#12439]
### Dagster version

1.1.19

### What's the issue?

I have upgraded dagster to 1.1.19 using helm chart and am getting below error in dagit while loading user code repositories.

"
Operation name: ShouldShowNux
Message: [Errno 13] Permission denied: '/opt/dagster/dagster_home/.nux'
Path: ["shouldShowNux"]
Locations: [{"line":2,"column":3}]
"

![image](https://user-images.githubusercontent.com/125947502/220254707-44f34b1d-14b3-45ee-81c6-87fc9393a2a6.png)

### How to reproduce?

go to dagster user code definitions in dagit and try to reload any user code repo.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by peay** [comment]
@OwenKephart would it make sense to set `nux: false` in the YAML configuration deployed by the Helm chart? The popup is not to be displayed outside of `localhost` anyway. I can send a PR if that makes sense.

**Comment by Ramshackle-Jamathon** [comment]
👍 @peay yes OSS dagit shouldn't be querying for NUX information

**Comment by Ramshackle-Jamathon** [comment]
this was fixed by https://github.com/dagster-io/dagster/pull/12477 and released in `1.1.20`
