### ISSUE TITLE
Dagster crash if you have to many partitions configured

### ISSUE THREAD

**Issue by marcilj** [dagster-io/dagster#12441]
### Dagster version

dagster, version 1.1.18

### What's the issue?

If an asset is configured with too many partitions, Dagster will stop responding.

This issue originated from a `MultiPartitionsDefinition` that created ~90k partitions.
But the same thing happens if we only use `HourlyPartitionsDefinition` with a start date that is old enough to create a lot of partitions.

When using `MultiPartitionsDefinition` that contains an `HourlyPartitionsDefinition` and `StaticPartitionsDefinition`.

If the number of total partitions is too high `HourlyPartitionsDefinition` * `StaticPartitionsDefinition`, Dagster will fail with the error:

> Unable to reach the user code server for schedule X. Schedule will resume execution once the server is available.

> User code server request timed out due to taking longer than 60 seconds to complete.

As @clairelin135 describes in [this thread](https://dagster.slack.com/archives/C01U954MEER/p1676648056525889), the error happens because of the way `run_request_for_partition` iterate over all the partitions.

>  The source of the error is that run_request_for_partition iterates through all the multipartitions to find the desired partition, which becomes expensive given that you have 90K partitions.

### What did you expect to happen?

I expect Dagster to run normally without any type of lag.

I would expect Dagster to store metadata on all partition's status so It knows the min, max of all complete and incomplete ranges, and don't have to query over each partition to return the missing ones in the UI.

### How to reproduce?

Option 1: Define an hourly partition asset that starts "way back" in the past.
Example: `HourlyPartitionsDefinition(start_date=datetime(2000, 12, 1))`
Then click on the `Materialize all` button.
Since the number of partitions is really high (~195K), Dagster will stop responding before you can run any jobs.
![image](https://user-images.githubusercontent.com/89793010/220375086-4f57c09c-2a6f-4e42-88eb-e6a525be5369.png)

Option 2: Define a MultiPartitionDefinitions that creates at least 90k partitions.
Example:
```
MultiPartitionsDefinition(
    {
        "hour": HourlyPartitionsDefinition(start_date=datetime(2022, 12, 1)),
        "asset": StaticPartitionsDefinition(
            ["DA3YOMC", "DA6YYNS", "DASK8KY", "DAHBT5U", "DAYT16A", "DAFB0MN", "DAU04PV", "DA05GWG", "DAY5UHJ", "DA8UISY", "DAAD2D6", "DAYK7R2", "DAEK979", "DA2Z102", "DAXVC4R", "DA14ISM", "DAYKXMG", "DAYGTPQ", "DAMFI9C", "DAD20TB", "DAEF133", "DAUY6W1", "DAMSTS2", "DAWWDPT", "DAWDCO9", "DARMN8J", "DAAFG27", "DAWPX23", "DAVTY3L", "DAWK4FA", "DA2DANE", "DAAWP08", "DARUEIM", "DAL5A0K", "DAFV08S", "DAPG1UA", "DA803TS", "DAIYNV8", "DALYJ9J", "DA4QZR7", "DAFAYJB", "DA22JZ7", "DAPV839", "DAEMBTU", "DAN0CMH", "DAWNJ9I", "DAHWGXP"],
        ),
    }
)
```

### Deployment type

Local

### Deployment details

This happens when I run Dagster Locally in a Docker container or Locally on my MacBook Pro.

### Additional information

Slack Thread: https://dagster.slack.com/archives/C01U954MEER/p1676648056525889

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Thanks @marcilj for the detailed bug report. https://github.com/dagster-io/dagster/pull/12431 should fix the issue with the sensor evaluation timing out.

The UI not loading 180K partitions is a different known issue that we'll likely take on at a separate time.
