### ISSUE TITLE
Dagster compatbility with older versions of mysql for storing runs

### ISSUE THREAD

**Issue by jcauserjt** [dagster-io/dagster#12447]
### Dagster version

1.1.19

### What's the issue?

I am trying to migrate my storage to mysql. One issue I have is that my mysql instance requires a primary key to be defined at the time of creating every table but the sql statement it's running to create table `daemon_heartbeats` does not have a primary key (despite it having a unique column. Is there any way to tweak the storage config in `dagster.yaml` to resolve this?

The issue is that a primary key is not specified in some of the metadata tables. Mainly:
`daemon_heartbeats`  and `instance_info` tables in `dagster._core.storage.runs.schema`
The recommended settings for a mysql implementation is for every table to have a primary key. Even if it is an auto increment identity column. I think this would be an incremental benefit to the library.

### What did you expect to happen?

All metadata tables to have a primary key so that initializing tables in older versions of mysql works.

### How to reproduce?

Need mysql version 8.0.21 or earlier

Afaik, this is fixed in 8.0.30 because it auto-creates missing primary keys

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by prha** [comment]
@jcauserjt Can you provide any more info on this?  I was just able to run our run storage test suite on a mysql server running `8.0.21`.

**Comment by prha** [comment]
This should be resolved with the `1.2.0` release.
