### ISSUE TITLE
Dagit timeline tick visual bug

### ISSUE THREAD

**Issue by nehz** [dagster-io/dagster#12465]
### Dagster version

1.1.19

### What's the issue?

![image](https://user-images.githubusercontent.com/151358/220624730-815a91c6-ddd7-4524-a399-9785989d1082.png)

Both system timezone and dagit timezone set to AWST
Logs show there are successful runs between 2pm and 8pm, but nothing shows on UI
I think it is likely related to timezones

### What did you expect to happen?

Successful runs going to "now"

### Deployment type

Local

### Deployment details

Dagster 1.1.19
Running on MySQL

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
cc @hellendag

**Comment by hellendag** [comment]
Closing this as stale, and because my hunch is that this issue has probably gone away in newer versions. Please feel free to reopen if you're still seeing it!
