### ISSUE TITLE
Bug when opening metadata dropdown menu in Schedule

### ISSUE THREAD

**Issue by marcilj** [dagster-io/dagster#12532]
### Dagster version

dagster, version 1.1.18

### What's the issue?

When you are on the Schedule page, the metadata dropdown always return an error since it's looking for future partition that doesn't exist yet. (Since they are schedule in the future)
![image](https://user-images.githubusercontent.com/89793010/221262830-99497f53-d187-4ade-a2cc-735a85822950.png)

![image](https://user-images.githubusercontent.com/89793010/221262903-28ce0bc0-0995-4293-8671-753c43f54145.png)

### What did you expect to happen?

I don't know what's supposed to be shown there, but clearly not an error, if the partition will be created when the schedule starts.

### How to reproduce?

Create an asset with hourly partitions.
Configure the partition to start in the past without any end time.
Example `hourly_partitions = HourlyPartitionsDefinition(start_date=datetime(2022, 12, 1))`
Schedule that asset to be materialized every hour.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
This looks like a problem with config generation on the backend. The OSS issues project is full...I'm going to move it to the SDA project.

**Comment by sryza** [comment]
Here's a fix: https://github.com/dagster-io/dagster/pull/12601
