### ISSUE TITLE
show partition status counts while partitioned asset is materializing

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12574]
If you launch a backfill to materialize a partitioned asset, the entire status area gets covered by the "Materializing" as long as any run is targeting a partition of the asset. This makes it difficult to understand how the backfill is progressing.

**Comment by sryza** [comment]
@braunjj @bengotow @johannkm  - something to think about while you're thinking about displaying the failed partitions count: we might also want to display the "materializing" partitions count.

**Comment by johannkm** [comment]
yep, that's easy to calculate with the same query

**Comment by bengotow** [comment]
Hmm that sounds interesting, If the numbers do not sum to 100% otherwise, I'd vote for showing it. (eg: If I have 10 partitions and it currently shows "1 success, 3 failed, 5 missing", let's also show "1 materializing")

**Comment by sryza** [comment]
I think that a partition could technically be considered both "missing/failed/successful" and "materializing", however, I think that the "materializing" status should probably override those other statuses in the display.
