### ISSUE TITLE
explore system for environment variable fallback/defaults in configs

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#1259]
Using `default_value` to do environment variable look ups created problematic scenarios since your pipeline construction is now environment dependent. I moved the early use of this pattern for spark_home in #1258.

This is still a useful concept, so it's worth exploring how we could provide a better system for it.

**Comment by mgasner** [comment]
I presume this is solved by config mapping?

**Comment by mgasner** [comment]
and SourceString?
