### ISSUE TITLE
`Reload All` definitions button

### ISSUE THREAD

**Issue by catalyst17** [dagster-io/dagster#12592]
### Dagster version

dagster, version 1.1.19

### What's the issue?

I am running Dagster locally for now and am testing creation of new code locations and loading its' definitions without restarting the process. What I've noticed is:
- when I'm adding, say, _**3rd**_ code location to my `workspace.yaml` it's sufficient to just press **Reload All** button in Deployment tab to have all the new definitions present, even sensors start to run automatically then
- but if I only had _**1**_ code location and am adding the _**2nd**_ one, then Dagit doesn't even have this **_Reload All_** button and there is no way the new definitions can start to take an effect w/o the restart

### Deployment type

Local

### Additional information

I was able to reload the workspace by using GraphQL API with `DagitMutation.reloadWorkspace` as suggested in [this](https://dagster.slack.com/archives/C01U954MEER/p1677603998569879) Slack thread.

So it is basically just a UI/UX issue. 
![image](https://user-images.githubusercontent.com/37663786/221940015-503d9fc7-1628-4f29-80d7-ea47415bddcf.png)
![image](https://user-images.githubusercontent.com/37663786/221940126-aba5545c-bf08-451e-9378-2f8dc9a68405.png)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/12588.
