### ISSUE TITLE
FutureWarning in dagster_snowflake_pandas

### ISSUE THREAD

**Issue by sethkimmel3** [dagster-io/dagster#12604]
### Dagster version

1.1.20

### What's the issue?

Small warning from [this line](https://github.com/dagster-io/dagster/blob/116ec378b77a195182b9b89f3d44ac9e59e54505/python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas/snowflake_pandas_type_handler.py#L80):

`FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.`

### What did you expect to happen?

Should probably be replaced.

### How to reproduce?

Run the code!

### Deployment type

Local

### Additional information

Happy to submit a PR, would love to see how Dagster tests changes.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
> Happy to submit a PR, would love to see how Dagster tests changes.

If you'd be up for submitting a PR, that would be great. Before changing this, we should figure out if this will break compatibility with earlier versions of Pandas that users might still be relying on.

**Comment by sethkimmel3** [comment]
Done! See https://github.com/dagster-io/dagster/pull/12629
