### ISSUE TITLE
[docs] - document how to report row count or other metadata from DBT run

### ISSUE THREAD

**Issue by geoHeil** [dagster-io/dagster#12612]
### What's the issue or suggestion?

https://dagster.slack.com/archives/C01U954MEER/p1677239804545109

How can I include custom asset observations i.e. row count into DBT-backed assets? Are there any configuration options I am overlooking?

hmm... our api docs do have a simple example, but it currently isn't displaying correctly: https://docs.dagster.io/_apidocs/io-managers#dagster.OutputContext.log_event
Here it is copy pasted:
            from dagster import IOManager, AssetMaterialization

            class MyIOManager(IOManager):
                def handle_output(self, context, obj):
                    context.log_event(AssetMaterialization("foo"))
I agree that this pattern would be helpful to document in the docs though. We also have a similar utility that attaches observations via the load_input method of an IO manager. I'd recommend filing an issue so that we can track adding this to our documentation

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
We give an example of customizing asset materialization metadata in our API docs: https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.DbtCliResource.cli.
