### ISSUE TITLE
Way to cancel all the runs submitted for a backfill

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12634]
It's currently possible to cancel a job-based backfill, but this only stops the daemon from submitting more runs on behalf of the backfill. It does not cancel any runs that are already submitted.

It would be useful to offer a way to cancel all the runs that have already been submitted.

Requests:
- https://dagster.slack.com/archives/C04KC6XRU8N/p1681828190922769 - Someone kicked off a bunch of rather massive backfills and I'm not able to terminate them, looks like they're stuck in the "requested" state. Is there another way we can kill these? I also see a bunch of queued up runs from them, so not sure if "requested" is accurate here as well

**Comment by clairelin135** [comment]
I tested with the UI and it seems like it's already possible to do this with a job-based backfill:
- cancel a backfill, preventing more runs from being queued
- cancel the unfinished runs in the backfill
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/29110579/236266389-3e350517-6ee8-47b2-8353-f5f140f8e368.png">

**Comment by clairelin135** [comment]
Closing as completed. https://github.com/dagster-io/dagster/issues/11530 will bring asset backfills up to parity with job backfills by:
- enabling canceling backfills
- enabling terminating unfinished runs

**Comment by mvanaltvorst** [comment]
Hi, I have a quick question about this: why does cancelling a backfill take so long? My backfill can be in the "canceling" state for over 10 minutes where it is busy canceling approximately 500 queued jobs. Why does canceling 500 jobs take 10 minutes?

**Comment by clairelin135** [comment]
@mvanaltvorst Is your backfill running on a selection of assets? Or is it across partitions of a job?

In the asset selection case case, the daemon cancels up to 50 runs per iteration, and iterations are 30s apart. This is to avoid throttling the daemon since canceling runs incurs some cost.
