### ISSUE TITLE
Allow providing config to @graph_asset decorator

### ISSUE THREAD

**Issue by simonvanderveldt** [dagster-io/dagster#12647]
### What's the use case?

`@graph_asset` (added in https://github.com/dagster-io/dagster/pull/10152) is missing the `config` attribute that allows one to pass/define config for Ops that are part of the graph/graph backed Asset.

The `@graph` annotation does support this
https://github.com/dagster-io/dagster/blob/fe8ed527ee9c4acae0568a6c3466346be544973f/python_modules/dagster/dagster/_core/definitions/decorators/graph_decorator.py#L135
as does the `GraphDefinition` class
https://github.com/dagster-io/dagster/blob/fe8ed527ee9c4acae0568a6c3466346be544973f/python_modules/dagster/dagster/_core/definitions/graph_definition.py#L205
so I'd expect that the `@graph_asset` should also be able to take a `config` argument and pass this on to the graph it creates for the Asset.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@simonvanderveldt would you mind elaborating a little bit more on what you'd like to use this for?

`@asset` doesn't currently have a `config` attribute, but we've been discussing adding one. Arguably, `@graph_asset` and `@asset` should be consistent on this.

cc @benpankow

**Comment by simonvanderveldt** [comment]
@sryza Apologies for the delay. I think the use-case can be summarized as "Reusable Ops that require config being used as part of a graph backed asset and the config is defined in code (so not provided at run-time)".

A bit more detail:
We have a set of re-usable ops that require config. We compose these ops into graphs that materialize an asset (i.e. graph backed assets). This graph backed asset thus needs config so the ops it contains can do their thing. Note that all of this is in code, not at runtime. `@graph()` does have a `config` argument, but `@graph_asset()` doesn't so we can't provide this in code.
We've worked around this for now by passing the config to `define_asset_job()`.

Regarding `@asset` I'm not sure it would make sense for that to have a `config` argument, since AFAIK there's no way for `@asset` to re-use an op. And for a configurable asset (so `@asset(config_schema=<some schema>)`) it also wouldn't really make sense I think? Defaults can already be defined as part of the config schema, apart from that I can't think of a use-case for it.

**Comment by sryza** [comment]
This is not necessarily the most ergonomic solution, but have you considered using `configured` for this use case?

E.g.

```python
@op(config_schema={"config_key": str})
def my_reusable_op():
    ...

@graph_asset
def asset_x():
    x_op = my_reusable_op.configured({"config_key": "x"}, "x_op")
    return x_op()

@graph_asset
def asset_y():
    y_op = my_reusable_op.configured({"config_key": "y"}, "y_op")
    return y_op()
```

**Comment by PascalStehling** [comment]
@sryza your solution is only possible if you have an hardcoded config. As soon you need a dynamic config, your only other option is to use the Pythonic config, which is not working with graph_assets (see #13880) at the moment. So either there needs to be a `config` attribute (like suggested) or the pythonic config needs to be working to migrate graph assets created with `AssetsDefinition.from_graph`.

**Comment by dpeng817** [comment]
Just wanted to note that if the graph-backed asset is provided as part of a job a-la `define_asset_job` - the underlying ops can be configured using the `config` parameter of the job, or using the launchpad in the UI. The launchpad can also provide config in the non-job case - IE materializing a group of assets. I think the only thing not served here is providing config at the graph level specifically.
