### ISSUE TITLE
Allow re-using Ops whilst being able to override some of their attributes?

### ISSUE THREAD

**Issue by simonvanderveldt** [dagster-io/dagster#12649]
### What's the use case?

We like the idea of re-usable Ops and would like to make use of them to be able to re-use code as well as see where these Ops/pieces of codes are used (via the Ops view of each code location).

Unfortunately though because there is no (or there doesn't appear to be a) distinction between Op definitions and instances of these Op definitions, it's currently not possible to set/override any of the attributes of an Op when including a re-usable Op in a Job or Graph/Graph backed asset.

Examples of this would be:
- An Op that uses data from 1 to n Assets. This would require the (amount of) `ins` to be overridden when using it in a Job/Graph
- An Op that gets included more than 1 time in a Job/Graph. Being able to override it's name/give it a more explicit name helps with making clear what it's being used for.

We have several of these use-cases and for now we're just creating Ops specific to each Asset/Graph/Job for this, but this clutters the Ops view a lot and means we can't use the Ops view to see which Assets/Graphs/Jobs are using a certain Op basically nullifying the point of having a centralized Ops list where one can see where these Ops are being used.

I hope this makes some sense. If anything is unclear please let me know so I can try to clarify :)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
> An Op that uses data from 1 to n Assets. This would require the (amount of) ins to be overridden when using it in a Job/Graph

Would fan-in work for this? I.e. you can pass a list of outputs into a single input. Here's the docs for this: https://docs.dagster.io/concepts/ops-jobs-graphs/graphs#with-a-fixed-fan-in.

> An Op that gets included more than 1 time in a Job/Graph. Being able to override it's name/give it a more explicit name helps with making clear what it's being used for.

Does `.alias` work for this? Here's the docs: https://docs.dagster.io/concepts/ops-jobs-graphs/graphs#that-re-use-ops.

**Comment by simonvanderveldt** [comment]
> Does `.alias` work for this? Here's the docs: https://docs.dagster.io/concepts/ops-jobs-graphs/graphs#that-re-use-ops.

Ugh, I searched quiet a bit for way to do this but somehow this didn't come up in my searches. Might be me though, I mostly searched for things like "reusable Ops", "reuse Ops", etc.

Anyway, thanks for the pointer, this does indeed work perfectly for this use-case :+1: 

One small thing I noticed that when using the same Op multiple times in a single Graph only one of them is shown in the code location's Op listing (under "All invocations").
I expected all instances of the Op to be listed there but not sure if that's expected or not. If not, shall I create a new issue for this?

> Would fan-in work for this? I.e. you can pass a list of outputs into a single input. Here's the docs for this: https://docs.dagster.io/concepts/ops-jobs-graphs/graphs#with-a-fixed-fan-in.

Thanks for this pointer as well, I tried some of this before but it didn't entirely work, but I'll give it another try and report back.

**Comment by sryza** [comment]
> Ugh, I searched quiet a bit for way to do this but somehow this didn't come up in my searches. Might be me though, I mostly searched for things like "reusable Ops", "reuse Ops", etc.

I'll add this to my hit-list of docs search results that I want to improve:

<img width="937" alt="image" src="https://user-images.githubusercontent.com/654855/222819381-c30a4a41-a749-4718-b50f-a23161ba87a1.png">


> I expected all instances of the Op to be listed there but not sure if that's expected or not. If not, shall I create a new issue for this?

A new issue for this would be helpful

**Comment by simonvanderveldt** [comment]
> Would fan-in work for this? I.e. you can pass a list of outputs into a single input. Here's the docs for this: https://docs.dagster.io/concepts/ops-jobs-graphs/graphs#with-a-fixed-fan-in.

Tried this, but I think this doesn't work for us because we're using Dagster just as a scheduler. Because of this all our input and output types are `Nothing`, but `Nothing` can not be wrapped in a List, I get the following message when trying to do this
```
Error loading repository location repository.py:dagster._core.errors.DagsterInvalidDefinitionError: Type Nothing can not be wrapped in List or Optional
```

**Comment by sryza** [comment]
I was able to get this to work:

```python
from dagster import op, Nothing, In, graph


@op
def op1() -> None:
    ...


@op
def op2() -> None:
    ...


@op(ins={"after": In(Nothing)})
def op3():
    ...


@graph
def graph1():
    op3(after=[op1(), op2()])
```

Would this work for you?

**Comment by simonvanderveldt** [comment]
@sryza Thanks for the pointer, wasn't aware one could pass in more than 1 object/lists for `Nothing` types. Tested this and it does indeed work.

> > I expected all instances of the Op to be listed there but not sure if that's expected or not. If not, shall I create a new issue for this?
> 
> A new issue for this would be helpful

I'm having a hard time creating a example case that shows this behavior. A simple example using Definitions works fine but the setup we run in production does exhibit this behavior. We're using repository though because we generate multiple repositories programmatically, so maybe something's happening there, will need to dig a bit deeper. If I can replicate it I'll create a new issue for this.

Anyway, the original two issues are addressed, so I'll close this issue. Thanks again for the help, much appreciated!
