### ISSUE TITLE
Make all dbt CLI flags/options/arguments available in CLI resource config

### ISSUE THREAD

**Issue by jayhale** [dagster-io/dagster#12684]
### What's the use case?

Only a subset of CLI flags and options are accessible when configuring the dbt CLI resource from `dagster-dbt`.  E.g., `--debug` is not exposed (see [Slack conversation](https://dagster.slack.com/archives/C01U954MEER/p1675710009301629?thread_ts=1675305604.334819&cid=C01U954MEER)).

When developing, or in some implementation situations, a user likely wants access to some of the more esoteric CLI flags, options, and/or arguments.

### Ideas of implementation

Update the config definition in `dagster-dbt` to include all dbt CLI flags/options/arguments.

https://github.com/dagster-io/dagster/blob/df53d31886fd75d86bfa35dd7c9a74e0633e19a8/python_modules/libraries/dagster-dbt/dagster_dbt/cli/constants.py#L13

https://github.com/dagster-io/dagster/blob/df53d31886fd75d86bfa35dd7c9a74e0633e19a8/python_modules/libraries/dagster-dbt/dagster_dbt/cli/constants.py#L60

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@rexledesma - thoughts on this one?

**Comment by rexledesma** [comment]
I believe this is already supported.

- `dbt_cli_resource` takes a `Permissive` schema. Meaning that it can take in more configuration than what it is explicitly configured for.
- So, although we define `CLI_COMMON_FLAGS_CONFIG_SCHEMA` and `CLI_COMMON_OPTIONS_CONFIG_SCHEMA`, we still allow options that are not predefined to be passed through (e.g. `--debug`). 
- So, you can add something like `{"debug": None}` to add the debug flag to your run.

**Comment by jayhale** [comment]
@rexledesma @sryza that doesn't appear to add the flag.

This config:
```
all_assets = with_resources(
    definitions=load_assets_from_dbt_project(
        project_dir=DBT_PROJECT_DIR,
        profiles_dir=DBT_PROJECT_DIR,
        node_info_to_asset_key=get_asset_key_for_node,
        source_key_prefix=["bronze"],
        use_build_command=True,
    ),
    resource_defs={
        "dbt": dbt_cli_resource.configured(
            {
                "project_dir": DBT_PROJECT_DIR,
                "profiles_dir": DBT_PROJECT_DIR,
                "debug": None,
            }
        )
    },
)
```

Results in this command:
```
Executing command: dbt --no-use-color --log-format json build --project-dir /opt/dagster/app/dbt --profiles-dir /opt/dagster/app/dbt --select *
```

**Comment by rexledesma** [comment]
@jayhale sorry - could you try `{"debug": True}`?

**Comment by jayhale** [comment]
@rexledesma 

Just did.  That fails due to unexpected ordering of the flags.  `--debug` needs to be attached to the `dbt` command, not the `build` subcommand:

```
Executing command: dbt --no-use-color --log-format json build --project-dir /opt/dagster/app/dbt --profiles-dir /opt/dagster/app/dbt --debug --select *
...
dbt: error: unrecognized arguments: --debug
```

**Comment by rexledesma** [comment]
Ah I see, you're right. I had assumed that `--debug` was part of the subcommand.

We will need to add a similar mechanism that allows passthrough of command line flags for the main `dbt` command.

**Comment by jayhale** [comment]
Given the current dbt CLI is implemented with Click, all of the options can be taken from the command objects themselves, instead of needing to shadow them here.

Additionally, programmatic invocation would probably make passing flags/options/arguments much more straightforward, instead of using a subprocess.

Is there a reason this integration chose to use `process.Popen` instead of just using the command objects directly?

**Comment by rexledesma** [comment]
>

> Is there a reason this integration chose to use `process.Popen` instead of just using the command objects directly?

`dbt-core`'s API is their CLI, which is why we invoke the CLI instead of the underlying implementation. If the underlying implementation of the CLI changed (as it did when it changed from `argparse` to `click`), and we were using the internal programmatic interface, we would have had to change our implementation as well, as this would have broken us.

> Given the current dbt CLI is implemented with Click, all of the options can be taken from the command objects themselves, instead of needing to shadow them here.
> 
> Additionally, programmatic invocation would make passing flags/options/arguments much more straightforward, instead of using a subprocess.

This is a neat suggestion, but I would argue that pairing the Dagster config system with `dbt`'s command line arguments was not a good choice, as it added some needless indirection when specifying custom options to steps like `dbt run`/`dbt build` when materializing software-defined assets. For that reason, I don't think we should be actively promoting/investing in more configuration for the `dbt_cli_resource`.

However, given the current system and its extensive use of Dagster config, adding a pass-through should be sufficient to accomplish the initial use case that you have requested in this issue.

---

As an aside, we are actively re-considering how the `dagster-dbt` integration is fundamentally structured as custom use cases like adding a simple `--debug` flag to your command should be easy. Again, I apologize that your journey has not been straightforward.

**Comment by jayhale** [comment]
@rexledesma what's the ETA for the integration rework?  The immediate issue for us is being able to diagnose the delays between queries when running on Dagster - we need access to `--debug` asap.

**Comment by rexledesma** [comment]
For the moment, we will support your use case with https://github.com/dagster-io/dagster/pull/12722.

But as noted in the PR, the correct way forward with this is to natively support [dbt's existing precedence hierarchy with global config](https://docs.getdbt.com/reference/global-configs).

This way, Dagster will not need to unnecessarily intermediate between translating dbt config to Dagster config: you can configure everything in your dbt project and Dagster will simply just run it.

**Comment by rexledesma** [comment]
This is supported using `DbtCli`, in our new APIs. See https://github.com/dagster-io/dagster/discussions/14477 for more details.
