### ISSUE TITLE
Enable resource_class on CircleCI

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1268]
https://circleci.com/docs/2.0/configuration-reference/#resource_class

**Comment by schrockn** [comment]
This is enabled, or so the circleci person told me

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
Turns out that switching to resource_class: xlarge doesn't really save much time at all when linting (22 sec. on 1:53 for the actual pylint step) -- most of the time is spent installing packages. #631
