### ISSUE TITLE
Ctrl+K for search in Dagit

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#12688]
### What's the use case?

Very simple, I'd like `ctrl`+`k` to open the search in dagit (as an alternative to `/`). 

This is the behavior in the dagster API docs, just want the same in the dagit ui.

### Ideas of implementation

Same as the dagster documentation.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
https://github.com/dagster-io/dagster/pull/10449 should have addressed this in `1.0.17`. What version are you on?

**Comment by mkleinbort-ic** [comment]
1.1.21

**Comment by mkleinbort-ic** [comment]
I'm on windows, so the hotkey is `ctrl+k` not `command+k` - maybe that's the issue?
