### ISSUE TITLE
Loosen dependencies (esp. airflow)

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1273]

**Comment by mgasner** [comment]
airflow - I think we can go back as far as 1.10.0 without having to rewrite anything. Further than that, we may need a conditional implementation of the containerized operator. N.b., only 1.10.3 will work with py37. I will make a tracking task to relax this dependency.

**Comment by schrockn** [comment]
Closed in favor of https://github.com/dagster-io/dagster/issues/1497
