### ISSUE TITLE
Please support the basic UI customization and authorization based on jobs, assets and workflows access. Currently everyone can view all the jobs, assets and workflows.

### ISSUE THREAD

**Issue by krishnakko** [dagster-io/dagster#12730]
### What's the use case?

We are implementing job and queue-related tasks through Dagster. Currently, we are not able to change the basic UI. Mainly with authorization, we are facing issues like we want to give access to particular jobs to particular users only when they are using our product. Currently, we are not able to implement that.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @krishnakko - I'm merging this into https://github.com/dagster-io/dagster/issues/2219 since it matches the description of that issue.
