### ISSUE TITLE
for failed partitions on asset details page, include link to failed run

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12750]
after we make this change, I think we should remove 
![image](https://user-images.githubusercontent.com/654855/223235985-27e65e8a-417d-4d0d-9dc1-295f6c7c30c3.png)
from the top of the page

**Comment by salazarm** [comment]
@bengotow Are there any existing events or subscriptions I could use to accomplish this? Or do we need some new backend support to do it?

**Comment by sryza** [comment]
@johannkm or @clairelin135 might know

**Comment by johannkm** [comment]
Yes I added https://github.com/dagster-io/dagster/pull/12845 for this

**Comment by bengotow** [comment]
This has been completed! d37b0085
