### ISSUE TITLE
Possible to simplify/clean up the .ipynb boilerplate/programming model?

### ISSUE THREAD

**Issue by breathe** [dagster-io/dagster#1275]
Hi -- just learning about dagster and trying to figure out if its something I want to play with and/or start using on some python data science workflows.

Sorry for a drive-by comment (with an unfortunate self-promotional flare!!) -- but I was noticing the ability to [invoke .ipynb's as dagster solid's](https://dagster.readthedocs.io/en/0.4.0/sections/learn/tutorial/dagstermill.html) -- it seems to me the boilerplate around this might be a little strange/annoying/higher friction than necessary?  In particular the parameters cell strikes me as odd and the need to manually call dm.yield_result to serialize the outputs of the notebook.  Small things but simplifying that boilerplate might help reduce the bug surface area.

I made a library recently for programmatically running code from jupyter notebooks and it occurred to me this might actually be a more easy dependency to use for integrating notebook's into the dagster workflow ...  Its a more simplistic codebase and simpler api than papermill -- but I thought I would comment here in case it might fit or might fit your use case with a little work ... https://github.com/breathe/NotebookScripter.  

NotebookScripter exposes three methods -- `run_notebook`, `run_notebook_in_subprocess` and `run_notebook_in_jupyter` -- they are just function calls which keyword parameters and will execute either .ipynb or .py files with provided parameters injected into the notebook execution context.  `run_notebook_in_jupyter` can render output notebooks.  Parameter's are received within the notebook by calling `receive_parameter(some_default="foo")` which returns 'foo' unless some_default parameter was injected into the execution context.  Personally I like this api more than relying on a tagged parameter cell.

It seems to me like with maybe a little ability to customize the `run_notebook_in_jupyter` input/output serialization strategy could allow getting rid of some of the boilerplate needed to turn notebook's into Solid's?

Also -- I don't understand the need to include the need to call register_repository() within the notebook -- if nothing else -- this issue can maybe stand as a minor doc bug -- I at least, don't understand this comment:

```
dm.register_repository() takes a repository definition (define_example_repository() in this case) and lets the notebook know how to find the repository that contains the corresponding notebook-driven solid.
```

Looking at the airline examples -- my guess is that we need to register_repository() within the notebook in order for dm.get_context() to return an appropriate value when run as a standalone jupyter notebook?

Apologize if this issue feels mostly like noise!!  Interesting library -- I've found myself building things like this before and curious to see and learn more.

**Comment by schrockn** [comment]
Thanks for the questions!

1) The parameters cell is definitely necessary. The system has to known where to place the data that has been produced by previous solids. This is also inherited from the the papermill library upon which is it based. https://github.com/nteract/papermill. It's a similar amount of decoration as the NotebookScripter library IMO.

2) Definitely do *not* need the registory_repository call unless you need to use advanced features. We need to upgrade our docs to reflect that! Thanks a bunch.

3) In terms of custom serialization, we do this within our type system. Each type can configure its own serialization/deserialization formats, and it would be straightforward to make this configurable.

4) dm.yield_result() is only necessary if you are outputting a value for use downstream, or want to be  able to use our config system to materialize that result to arbitrary locations.

**Comment by schrockn** [comment]
Closing this in favor of https://github.com/dagster-io/dagster/issues/1471
