### ISSUE TITLE
Dagster assets, resources, for code location are not being displayed properly in Dagit

### ISSUE THREAD

**Issue by kevinschaich** [dagster-io/dagster#12793]
### Dagster version

1.1.21

### What's the issue?

My assets are all loading & displaying properly in the "Assets" tab and the lineage graph, but if I click on Deployments > Code Locations > pipelines (the code location it's loading from) nothing displays, and I get the following message:

```
No matching jobs
assets
was not found in any repositories in this workspace.
```

The same thing happens when I open the sidebar and try to view an asset group or a resource. Video attached.

https://user-images.githubusercontent.com/9244728/223612133-4af21499-98b8-4691-95fe-64990c6333bb.mp4

### What did you expect to happen?

Assets, asset groups, and resources should display properly

### Deployment type

Docker Compose

### Additional information

I'm using the new Definitions API to define my assets, resources, etc.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by kevinschaich** [comment]
@dpeng817 I'm using software-defined assets pretty much everywhere, so adding those + resources in `<my repo>/__init__.py`:

```python
...

defs = Definitions(
    assets=load_assets_from_modules([module_a, module_b, ...]),
    resources=resources_by_env["local"],
    executor=dagster_docker.docker_executor,
)
```

and then defining asset groups with the @asset decorator:

```python
@asset(
    group_name="unified",
    required_resource_keys={"spark", "env"},
)
def my_asset():
    ...
```

**Comment by hellendag** [comment]
We think this is a routing issue due to the code location being named `pipelines`. I'll take a look.

**Comment by hellendag** [comment]
Yeah, that's basically what's breaking here. We use location-less `/pipelines/[name]` and `/jobs/[name]` paths to try to redirect the user to any pipeline/job that matches `[name]`, if a match exists in the available code locations.

This is mostly to resolve issues where a (presumably old) Run object might not have its code location information attached to it. I'm not entirely sure we can remove these routes at this point -- @bengotow and I will need to discuss it a bit further.

@kevinschaich In the meantime, the workaround here is to rename your code location to something other than "pipelines" or "jobs". Sorry about that!
