### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by pacesetterplus** [dagster-io/dagster#12796]
### What's the issue or suggestion?

This [url](https://docs.dagster.io/concepts/code-locations#definitions-versus-repositories) is broken

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
Doesn't seem broken for me at the moment - is this still persisting for you?

**Comment by pacesetterplus** [comment]
Not anymore.
