### ISSUE TITLE
Enable AssetValueLoader to load SourceAssets

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#12806]
The mechanism by which `AssetValueLoader` works should reasonably be extensible to `SourceAsset` as well - we should add this ability.

**Comment by Bonnevie** [comment]
@sryza I tried digging around a bit in the source, and it seems that the `Definitions` class to the untrained eye is a wrapper around a repository and in line 355 of `repository_definition.py` an asset value loader is instantiated with `AssetValueLoader(self._assets_defs_by_key, instance=instance)`. But the `_assets_defs_by_key` only contains a mapping to all proper assets,  whereas there is a separate `get_source_assets_by_key`.
Empirically I just observed my source assets were not present in that dictionary mapping.

**Comment by sryza** [comment]
@Bonnevie you are right that this isn't supported. Here's a PR to add support for it: https://github.com/dagster-io/dagster/pull/12859
