### ISSUE TITLE
Attempt to `create schema if not exists ...` crashes flow when connector role lacks permissions to create schemas in the database

### ISSUE THREAD

**Issue by clayheaton** [dagster-io/dagster#12801]
### Dagster version

1.1.21

### What's the issue?

The snowflake connector tries `create schema if not exists ...` prior to materializing a DataFrame as a Snowflake table. This causes flows to crash when the Snowflake role assigned to the connector lacks privileges to create schemas in the database. 

It is related to this pull request:

https://github.com/dagster-io/dagster/pull/11764

### What did you expect to happen?

Check whether a schema exists before trying to create it, but do so in a way that will not return an error from Snowflake when the connector's role lacks privileges to create schemas.

### How to reproduce?

Use a role with access to a schema but that lacks privileges to create a new schema.

### Deployment type

Docker Compose

### Additional information

This is a dagster-breaking bug for me and I will not be able to upgrade to a new version until it is addressed. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@jamiedemaria - mind taking a look?
