### ISSUE TITLE
Resources not picked up from Definitions resources in jobs

### ISSUE THREAD

**Issue by Daniel-Vetter-Coverwhale** [dagster-io/dagster#12800]
### Dagster version

dagster, version 1.1.21

### What's the issue?

I am having to specify the same resources in the Definitions and every job that needs to use them. 

```
/Users/daniel.vetter/src/dagster/test-new-resources/.venv/lib/python3.11/site-packages/dagster/_core/workspace/context.py:602: UserWarning: Error loading repository location test.py:dagster._core.errors.DagsterInvalidDefinitionError: resource with key 'test_resource' required by op 'test_new_resources' was not provided. Please provide a <class 'dagster._core.definitions.resource_definition.ResourceDefinition'> to key 'test_resource', or change the required key to one of the following keys which points to an <class 'dagster._core.definitions.resource_definition.ResourceDefinition'>: ['io_manager']
```

### What did you expect to happen?

I believe I should only have to specify the in Definitions from what I'm seeing in the docs. 

### How to reproduce?

import dagster
import dagster._config.structured_config as sc

class TestResource(sc.ConfigurableResource):
    secret_id: str

    def test_this_thing(self):
        print(self.secret_id)

@dagster.op
def test_new_resources(context: dagster.OpExecutionContext,
                       test_resource: TestResource):
    test_resource.test_this_thing()

@dagster.job
def test_job():
    test_new_resources()

defs = dagster.Definitions(
    jobs=[test_job],
    resources={
        "test_resource": TestResource.configure_at_launch()
    }
)

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by benpankow** [comment]
Hi Daniel, I've created an issue to track this on our end: https://github.com/dagster-io/dagster/issues/12824
