### ISSUE TITLE
on the asset details page, partition bar doesn't refresh after materialization fails

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12819]
To reproduce:
- go to asset details page on a time-partitioned asset
- kick off a materialization
- it fails
- "Run X has failed to materialize" banner shows up
- bar does not update

**Comment by sryza** [comment]
@bengotow maybe this is already fixed on master? I tested this on the release branch, which doesn't have your recent refresh fix.

**Comment by bengotow** [comment]
Yep this was fixed in https://github.com/dagster-io/dagster/pull/12798!
