### ISSUE TITLE
Obfuscate secrets in the config editor

### ISSUE THREAD

**Issue by bengotow** [dagster-io/dagster#1290]
The plan is to use the new `isSecret` field to identify secret YAML keys, pre-process the config text given to codemirror to replace these values with **** , extend hinting to add some sort of hover-to-reveal pattern for them, and then re-inject / smoosh the hidden values back into the config before saving it.

Follows #1289

**Comment by mgasner** [comment]
#1246

**Comment by mgasner** [comment]
This is still very much an issue because GraphQL queries leak secrets.

**Comment by natekupp** [comment]
closing this out, we now have `StringSource` for secrets; can reopen a new issue if we want to do something more
