### ISSUE TITLE
Databricks Pyspark Launcher raises error when passed custom tags

### ISSUE THREAD

**Issue by PadenZach** [dagster-io/dagster#12922]
### Dagster version

1.1.21

### What's the issue?

Passing the `custom_tags` config to the dagster_databricks pyspark step launcher results in a runtime error:

```
  File "/Users/zpaden/Workspace/company-dagster/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_plan.py", line 269, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/zpaden/Workspace/company-dagster/.venv/lib/python3.9/site-packages/dagster_databricks/databricks_pyspark_step_launcher.py", line 248, in launch_step
    databricks_run_id = self.databricks_runner.submit_run(self.run_config, task)
  File "/Users/zpaden/Workspace/company-dagster/.venv/lib/python3.9/site-packages/dagster_databricks/databricks.py", line 260, in submit_run
    tags.append({"key": "__dagster_version", "value": dagster.__version__})
  File "/Users/zpaden/Workspace/company-dagster/.venv/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 247, in __readonly__
    raise RuntimeError("Cannot modify ReadOnlyList")
```

This is an issue that I've known about for a while, but just now was able to set aside some time to write up a bug issue 🤓 

### What did you expect to happen?

The cluster and job to be launched, with my custom tag attached to the cluster.

### How to reproduce?

Slightly modified version of the dagster_test_databricks test that should surface the issue.
```py
NEW_CLUSTER = {
    "size": {"num_workers": 1},
    "spark_version": "6.5.x-scala2.11",
    "nodes": {"node_types": {"node_type_id": "Standard_DS3_v2"}},
    "custom_tags": [{"key":"custom_tags"}, "value":"donotwork"}],
}
databricks_run_config["cluster"] = {"new": NEW_CLUSTER}

task = databricks_run_config.pop("task")
runner.submit_run(databricks_run_config, task)
```

### Deployment type

Dagster Cloud

### Additional information

This seems to be an issue with merging the dagster provided tags (dagster version) and the provided tags, lines 259-261:

```py
tags = new_cluster.get("custom_tags", [])
tags.append({"key": "__dagster_version", "value": dagster.__version__})
new_cluster["custom_tags"] = tags
```

I should be able to put a fix in for this, since it's quite simple. I assume other than editing the test to catch this sort of error, I'd just be tweaking the few lines posted above in a PR.

Thanks.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by zyd14** [comment]
I think this ticket can probably get closed, it looks like custom tags are working now (at least as of v0.19.3 / dagster v1.3.13)
