### ISSUE TITLE
Icon off center in dagit execution plan view

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1293]
<img width="682" alt="Screenshot 2019-04-24 08 55 26" src="https://user-images.githubusercontent.com/28738937/56674377-ca6baa00-666e-11e9-95eb-9842d80d00ec.png">

**Comment by mgasner** [comment]
Can't reproduce (dagit 0.5.2.post3 / Chrome Version 75.0.3770.142 (Official Build) (64-bit)) -- also not an issue in Firefox.
