### ISSUE TITLE
Community Slack Link Expired

### ISSUE THREAD

**Issue by TimoVink** [dagster-io/dagster#12939]
### What's the issue or suggestion?

I was hoping to join the community Slack, but the `Join us on Slack` link on dagster.io unfortunately appears to be expired:

![image](https://user-images.githubusercontent.com/694180/225073577-fad6271d-ba71-4fa4-90a6-aa6ca6ebda8c.png)

### Additional information

I've tried all of the following, in case it matters:
 * Signup link in header (next to sign-in button)
 * Signup link in footer (above newsletter)
 * Signup link on [Community page] (https://dagster.io/community)

All of them seem to go to the same "this link is no longer active" page.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Hello! Thank you for bringing this to our attention! I just updated the link and it should take you to the a proper invite page now!

**Comment by TimoVink** [comment]
Can confirm it works now. Thanks for the fast turnaround!
