### ISSUE TITLE
on asset details page, show the latest date-partition first

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12934]
here, we're showing the earliest one first:

![image](https://user-images.githubusercontent.com/654855/224891729-02ef63bd-ca87-4917-a9d9-9016ef8fc79d.png)

**Comment by hellendag** [comment]
We might be able to do what we did for the config editor partition picker in Launchpad, and show a button to sort and reverse-sort.

I can't find any examples in our existing code locations, I think they all got turned into assets. But here's where the code is: https://github.com/dagster-io/dagster/blob/cb775d43c59fd841b54aadbedb9972ade23d1b99/js_modules/dagit/packages/core/src/launchpad/ConfigEditorConfigPicker.tsx#L206

If you're able to find a job with partitions, you should be able to go to the Launchpad, choose a partition set, and choose a partition. The sort button should appear there.
