### ISSUE TITLE
Update deploy_ecs example to support Definitions

### ISSUE THREAD

**Issue by migsk** [dagster-io/dagster#12956]
### What's the issue or suggestion?

While working on this example: https://github.com/dagster-io/dagster/tree/1.2.1/examples/deploy_ecs, I noticed that it still uses repo.py instead of Definitions. Could this example be updated?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rokity** [comment]
I can do it
