### ISSUE TITLE
Make context.log available to resource contexts

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1298]
Right now we provision `context.log` in the solid context, but AFAICT we don't for resource contexts - would be nice to be able to log things during resource initialization / usage

**Comment by schrockn** [comment]
Max should be able to do this as part of the logging work

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
definitely
