### ISSUE TITLE
Make specifying solid resource dependencies more explicit

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1299]
Right now, something like this:

https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-slack/dagster_slack_tests/test_resources.py#L25

won't fail until runtime if we've neglected to provision a slack resource instance in the pipeline context definitions.

**Comment by mgasner** [comment]
This should be resolved by https://github.com/dagster-io/dagster/commit/2f31f212dab8145ffa25a1f31aafd9e432d98ca6 et seq., right?

**Comment by natekupp** [comment]
well, if you neglect to declare that your solid requires a particular resource, the system won't catch the issue until runtime—right now we only catch the case where you've explicitly declared your resource requirements

**Comment by mgasner** [comment]
aside from introspecting the AST of the solid compute function, i'm not sure how we can catch that

**Comment by mgasner** [comment]
Closing this as intractable / requiring a very different programming model, required_resource_keys gets us a lot
