### ISSUE TITLE
Table metadata type is not being displayed

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#13005]
### Dagster version

1.2.2

### What's the issue?

I logged a `TableMetadataValue`, but it's empty in Dagit. 
It has bothed `TableRecord`s and a `TableSchema`. 
![image](https://user-images.githubusercontent.com/49863538/225954345-42aacde5-2b84-4b09-961c-6b6596d4ef4a.png)

### What did you expect to happen?

Expected to see a table

### How to reproduce?

log a `TableMetadataValue`

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Hey hey! Thanks for reporting this! I've attached to a GitHub project so the right people are aware of it.
