### ISSUE TITLE
Integrations: tracking list of library operators/resources to build

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1302]
This issue serves as a running list of integrations that we have vs. what we still need to build. 

### Hadoop
🚫 Presto
🚫 Hive
🚫 distcp, also better S3 / GCS support
🚫 Sqoop
🚫 Pig

### AWS
✅ EMR
✅ S3
🚧 Move Redshift from `airline_demo` to `dagster_aws` (#1371)
🚫 Sagemaker

### GCP
✅ BigQuery
✅ Cloud Dataproc
🚫 Cloud Bigtable
🚫 Cloud Dataflow
🚫 Cloud Datastore

### Azure
🚫 TBD?

### Miscellaneous
🚫 Bash
🚫 Generic JDBC
🚫 FTP / SFTP
🚫 MongoDB
🚫 Segment
🚫 MySQL
🚫 Postgres (think about the overlap w/ redshift here?)
🚫 Druid / Pinot
🚫 Sendgrid
🚫 Twilio
🚫 Discord
🚫 Papertrail (should be modeled as part of @mgasner's logging work instead?)
🚫 Loggly

**Comment by natekupp** [comment]
Loggly

**Comment by natekupp** [comment]
Moving this to the wiki

**Comment by bruth** [comment]
Clicking on the wiki it appears there are no pages (it redirects back to the main repo page)? I was curious of the integration with Presto in particular from the list. Another idea/need are running Kubernetes jobs.
