### ISSUE TITLE
Add option to pass a PartitionMapping to an asset built with dbt

### ISSUE THREAD

**Issue by mmutso-boku** [dagster-io/dagster#13053]
### What's the use case?

I have an asset A with hourly partition going back 2+ years. Asset B is unpartitioned and is downstream of asset A.
I tried to use the asset reconciliation sensor to materialize asset B, but the sensor tick times out.

As far as I can understand, this is because the default logic is that for unpartitioned asset all upstream partitons must be materialized before the asset reconciliation sensor will materialize the unpartitioned asset, and so it tries to look through the 8000 partitions every tick.

Usually this could be changed with defining a PartitionMapping in @asset "ins" parameter, but for an asset built with `load_assets_from_dbt_project` , there seems to be no way to pass the "ins" parameter to the creation of AssetsDefinition.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @mmutso-boku ! I see two separate issues here:

First is the behavior one, where you would like `B` to be materialized regardless of the historical missing partitions of `A`. I think you're on the right track here with customizing the `PartitionMapping`. We're in the process of making it much easier to customize the dbt assets that are generated from a given manifest, so this seems like something we could do along those lines. What would be the most ergonomic way for you to set this up? Something in dbt config, or something purely in the python API?

For now, one way to hack around this would (unfortunately) be something like:

```python
my_dbt_assets = load_assets_from...(...)[0]
my_dbt_assets._partition_mappings[AssetKey('A')] = LastPartitionMapping()
```

The second issue is a performance one -- regardless of the current behavior, this tick shouldn't time out. To look into that, a few bits of information would be helpful:

What version of `dagster` are you on?

How many assets are targeted by the reconciliation sensor beyond `A` and `B`?

**Comment by mmutso-boku** [comment]
Hi @OwenKephart 

> What would be the most ergonomic way for you to set this up? Something in dbt config, or something purely in the python API? 

For me, it doesn't really matter much. Perhaps in the python API, but on the other hand there is already some configuration which is defined on the dbt side (I can't recall what it was at the moment), so I'd think whichever is more intuitive/"standardized".

> For now, one way to hack around this would (unfortunately) be something like:

I did try to hack it this way, but it did not work - maybe I had a mistake somewhere, but if I recall correctly, I got an exception about using the AssetKey as an index.

> What version of dagster are you on?

1.2.2. Will soon bump to 1.2.3 and at some point will try again to see if this improves things.

> How many assets are targeted by the reconciliation sensor beyond A and B?

1 or at most 2

**Comment by mmutso-boku** [comment]
I now tried with 1.2.4 also. Same thing. Sensor tick times out.
For more information, this happens on the helm-kubernetes deployment but works in local with dagster dev.

**Comment by OwenKephart** [comment]
hi @mmutso-boku , thanks for the report! I was able to replicate this issue and have a PR out to fix it.

**Comment by rexledesma** [comment]
We added support for this in `dagster-dbt==0.21.6`. 

To see how to configure `PartitionMapping`'s on dbt SDAs in the new API, check out our discussion: https://github.com/dagster-io/dagster/discussions/17722.
