### ISSUE TITLE
AllPartitionMapping is not a PartitionMapping?

### ISSUE THREAD

**Issue by DrawnWren** [dagster-io/dagster#13058]
### Dagster version

1.2.2

### What's the issue?

I'm getting a type error when using `AllPartitionMapping` with an asset that has no partition of its own.
```
dagster._check.ParameterCheckError: Param "partition_mapping" is not a PartitionMapping. Got <class 'dagster._core.definitions.partition_mapping.AllPartitionMapping'> which is type <class 'abc.ABCMeta'>.
```
The relevant code in the asset is:

### What did you expect to happen?

I expected AllPartitionMapping to have the type PartitionMapping

### How to reproduce?

```
@asset(
    required_resource_keys={"duckdb"},
    ins={
        "asset1": AssetIn(partition_mapping=AllPartitionMapping),
        "asset2": AssetIn(partition_mapping=AllPartitionMapping),
    },
)
```

### Deployment type

Local

### Deployment details

local.

### Additional information

none.

**Comment by sryza** [comment]
Try adding parentheses after `AllPartitionMapping`
