### ISSUE TITLE
Improvement opportunities for asset event component in Asset Details page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#13068]
When trying to understand the information that this component was trying to  communicate to me, I encountered a few confusions.

![image](https://user-images.githubusercontent.com/654855/226754116-c11224da-2f03-4ae8-98d6-79e6ae341895.png)

- In the case that a materialization is involved, replace "Latest event" with "Latest materialization". Otherwise, say "Latest observation". "Latest event" is inaccurate in the case that asset observations came after the materialization time being shown.
- Replace "2 events" with "2 prior events", to clarify that this is referring to the events that are _not_ included in what's being shown.
- Replace "👁️ logins in <run_id> (a few seconds later)" with "Observed in run <run_id> (a few seconds later)"
- If multiple events include the same metadata value for the same metadata key, just show that metadata entry once. (maybe this is a controversial suggestion. it means displaying slightly less data, but I think makes the UI a lot prettier in a lot of common cases).

**Comment by bengotow** [comment]
Hey @sryza this all sounds good! One small q: right now "👁️ logins in <run_id> (a few seconds later)" notes which step key the observation was created in (logins) and we're removing that context. I think that's ok -- "Observed in logins in run <run_id> (a few seconds later)" would be pretty verbose?
