### ISSUE TITLE
`context.partition_time_window` when MultiPartitionsDefinition

### ISSUE THREAD

**Issue by rubenbriones** [dagster-io/dagster#13077]
### Dagster version

1.2.1

### What's the issue?

The property `context.partition_time_window` is not working when `MultiPartitionsDefinition` is used, even though one of the partitions is of type `DailyPartitionsDefinition`.

### What did you expect to happen?

I would expect that the properties `partition_time_window.start` and `partition_time_window.end` can be accessed for the Daily partition.

It would be great if dagster is able to automatically recognize the date partition, and return its _time_window_. Or if not, that something like that could be done: `context.get_partition_by_key('date').partition_time_window`

### How to reproduce?

```py
@asset(
    partitions_def=MultiPartitionsDefinition(
        {
            "country": StaticPartitionsDefinition(["USA", "ESP"]),
            "date": DailyPartitionsDefinition(start_date="20230317", fmt='%Y%m%d'),
        }
    ),
)
def foo(context):
    date_requested = context.partition_time_window.start.strftime("%Y%m%d")
    print(date_requested)
```

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
thanks for the report! @clairelin135  would you or sandy be the right person to take a look at this?

**Comment by clairelin135** [comment]
I'll take a look at this
