### ISSUE TITLE
[Documentation Feedback] Problem on /integrations/dbt/using-dbt-with-dagster/part-one page

### ISSUE THREAD

**Issue by cnstlungu** [dagster-io/dagster#13079]
**Context:**

Was following along the [tutorial on Using Dagster with dbt](https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/part-one)

**Feedback:**

Step 2.2 (adding code to the profile.yml file) was not required, as that code was already there.

![image](https://user-images.githubusercontent.com/10930578/226929939-bed85e48-32f6-40be-9403-7b913b3884e6.png)

![image](https://user-images.githubusercontent.com/10930578/226929834-e5bda0c3-f99f-459e-84e2-60cbda9766ca.png)

**Comment by jamiedemaria** [comment]
@erinkcochran87  do you think we should remove the code from the template file or remove the step from the documentation?
