### ISSUE TITLE
Sensors job monitoring is selecting the wrong jobs

### ISSUE THREAD

**Issue by aaaaahaaaaa** [dagster-io/dagster#13076]
### Dagster version

1.2.2

### What's the issue?

When deploying code locations via the helm chart (`dagster-user-deployments`), the job monitoring selection for sensors has an unexpected behaviour:

- when NOT specifying the `monitored_jobs` param, sensors are triggered **for all jobs across all deployments**.
- when specifying the `monitored_jobs`, if several jobs have the same name (e.g. `daily`) across different deployments, then the sensor will be triggered for all of those jobs.

The sensors are defined using `@run_status_sensor`, and `monitor_all_repositories` is NOT set (default is `False`).

### What did you expect to happen?

- if `monitored_jobs` is not set, I would expect the sensor to only be triggered for the jobs of that specific `deployment`.
- if `monitored_jobs` is set and jobs share the same name across `deployments`, i would expect each sensor to only be triggered for the job of their respective `deployment`.

### How to reproduce?

1. Deploy the Helm chart with multiple `user-deployments`.
2. Each deployment has a job with the same name.
3. Each deployment has a sensor defined with `@run_status_sensor` for that job (with or without `monitored_jobs` parameters).
4. Run a job.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
hey @aaaaahaaaaa  are you also seeing this behavior in a local deployment? like if you just run `dagster dev` locally rather than a full helm deployment?

**Comment by aaaaahaaaaa** [comment]
@jamiedemaria The local deployment doesn't create multiple code locations. I couldn't test that.

**Comment by aaaaahaaaaa** [comment]
@jamiedemaria We're still experiencing this bug (now `1.4`). It seems that sensors are triggered only based on job names and do not consider code locations.

The screenshot below shows that 2 sensors were triggered during the execution of a single run. Those 2 sensors belong to 2 different code locations, each targeting 2 different jobs which but which have the same name.

![image](https://github.com/dagster-io/dagster/assets/2808155/311badaf-0046-487c-861d-9673ec982be7)

**Comment by ignaski** [comment]
I am explicitly defining the CodeLocationSelector, but the job names are the same in different locations and the sensor is being triggered even for the location which is not in the selector

**Comment by ion-elgreco** [comment]
I am still seeing this behavior in version 1.6.10 @jamiedemaria

**Comment by jamiedemaria** [comment]
Hey @ion-elgreco  I believe i found the source for the bug. wIll try to work on a fix this week

**Comment by ion-elgreco** [comment]
@jamiedemaria awesome! Thanks Jamie
