### ISSUE TITLE
bigquery_io_manager does not support daily partition with a date field

### ISSUE THREAD

**Issue by hamza-digitl** [dagster-io/dagster#13147]
### Dagster version

dagster, version 1.2.3

### What's the issue?

I am attempting to run a single asset pipeline using a daily partition on a field in "date" format. To accomplish this, I am using the bigquery_pandas_io_manager from the gcp_pandas module. Here is a snippet of my asset code:
```
partition_def = DailyPartitionsDefinition(
    start_date=os.environ["START_DATE"],
    timezone="Europe/Berlin",
)
@asset(
    key_prefix=["dataset_name"],
    compute_kind="API",
    partitions_def=partition_def,
    metadata={
        "partition_expr": "date",
    },
)
def report(context: OpExecutionContext) -> pd.DataFrame:
    date = context.asset_partition_key_for_output()
    # Do some transformations
    df = ......
    # Adding the date field as a date format
    df.insert(0, "date", pd.Timestamp(date).date())
    return df
```
The first partition corresponding to the date "2023-03-18" ran successfully without any issues. However, since the partition field format is a date, the second partition related to the day after  "2023-03-19" throws the error :
> dagster._core.errors.DagsterExecutionHandleOutputError: Error occurred while handling output "result" of step "XXXXX":: google.api_core.exceptions.BadRequest: 400 Could not cast literal "2023-03-19 00:00:00" to type DATE at [2:9]

![image](https://user-images.githubusercontent.com/126671212/227566746-e1799c4e-8f91-4b00-b1cc-f09ca6e1ff2d.png)

The problem is located in the delete_table_slice method in the BigQueryClient Class. 
This method attempts to execute the following query : 
```
DELETE FROM `dataset_name.report` WHERE
date >= '2023-03-19 00:00:00' AND date < '2023-03-20 00:00:00'
```
Resulting in the bigquery error :

>Could not cast literal "2023-03-19 00:00:00" to type DATE
The is due to the "Date" type of the date field. 

The workaround here is to transform my date field type to a "DateTime". However, this is not desirable.

### What did you expect to happen?

The delete_table_slice method should execute a BigQuery Query respecting the partition field format which can also be a Date format.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
@hamza-digitl  `partition_expr` can contain more complex sql to convert data in the partition column to match the timestamp format used by dagster in the query. So for example you could set your partition expr to this 
```
CAST(date AS TIMESTAMP)
```

and then the query would be 
```
DELETE FROM `dataset_name.report` WHERE
CAST(date AS TIMESTAMP) >= '2023-03-19 00:00:00' AND CAST(date AS TIMESTAMP) < '2023-03-20 00:00:00'
```

there's more information on this here https://docs.dagster.io/integrations/bigquery/reference#storing-time-partitioned-assets

**Comment by hamza-digitl** [comment]
@jamiedemaria, thank you very much for your input. Do you have any idea how to add this partition_expr metadata to downstream dbt assets using the load_assets_from_dbt_project method?

**Comment by jamiedemaria** [comment]
Looks like `load_assets_from_dbt_project` has a parameter `node_info_to_definition_metadata_fn` that according to the docs is 
```
– A function that takes a dictionary of dbt node info and optionally returns a dictionary of metadata to be attached to the corresponding definition. This is added to the default metadata assigned to the node, which consists of the node’s schema (if present).
```

you could implement a function that takes this dbt info dictionary and returns the `{"partition_expr": ...}` metadata
