### ISSUE TITLE
"RuntimeError: generator raised StopIteration" when backfilling assets with partitions or cross code location dependency

### ISSUE THREAD

**Issue by boenshao** [dagster-io/dagster#13174]
### Dagster version

1.2.3

### What's the issue?

"RuntimeError: generator raised StopIteration" when backfilling assets with cross code location dependency.

When I use "Materialize All" to backfill assets that have cross code location dependency.
![image](https://user-images.githubusercontent.com/65853605/227904328-2ecfa46f-74a3-4337-aea0-09c51bf4c8d8.png)
![image](https://user-images.githubusercontent.com/65853605/227904203-6e9a0887-11cf-4a47-b99c-6f98b100cc1e.png)

Below error occured.
![image](https://user-images.githubusercontent.com/65853605/227903335-0ba8d15c-36b5-4daf-ada6-e7623317cb65.png)

### How to reproduce?

You can find the minimal reproducible example here

- https://bitbucket.org/berry-ai/dagster-asset-backfill-error-report/src/master/

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
@clairelin135 @sryza is this a known issue?

**Comment by boenshao** [comment]
I just found out that backfilling an asset with multiple partitions can also trigger the same error.

![image](https://user-images.githubusercontent.com/65853605/228729601-275170ec-d876-47e9-bdf8-3805839cb232.png)

The steps to reproduce the issue have been added to the repo below:
- https://bitbucket.org/berry-ai/dagster-asset-backfill-error-report/src/master/

I'll update the issue's title to reflect this finding.

**Comment by sryza** [comment]
@boenshao thanks for reporting this and for the detailed reproduction steps. I was able to reproduce this.

Here's a PR that fixes the issue: https://github.com/dagster-io/dagster/pull/13275.
