### ISSUE TITLE
In the materialize modal view, I cannot modify a partition date after clicking latest

### ISSUE THREAD

**Issue by fridiculous** [dagster-io/dagster#13183]
### Dagster version

1.1.18

### What's the issue?

As a user, I can't actually change the value of the partition field after pressing latest.  Please see the video below of me attempting to backspace.

https://user-images.githubusercontent.com/1227514/228055015-4bc962a6-1523-4b5b-a427-329fb0154119.mov

### What did you expect to happen?

I expect I'd be able to modify the input text box.

### How to reproduce?

1. click on a large asset DAG from the hamburger menu on the left
2. add * in the textbox underneath the lineage tab
3. click Materialize all
4. click latest after the modal appears
5. try to backspace 

### Deployment type

Local

### Deployment details

I've attempted this on a range of versions from 1.1.18 to 1.2.3.  This also appears to be an issue on k8s as well local (M2).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @salazarm

**Comment by salazarm** [comment]
I took a look at this and I don't see any issue except it might be confusing that you have to hit "Enter" for your change to actually apply.
