### ISSUE TITLE
Divergence in aws test behavior btwn buildkite and circleci

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1319]
See https://github.com/dagster-io/dagster/pull/1317

**Comment by natekupp** [comment]
Looking at the buildkite failure:

```
...
E                   raise NoRegionError()
E               NoRegionError: You must specify a region.
```
I think this is because we set `AWS_DEFAULT_REGION` in CircleCI and not in buildkite

**Comment by natekupp** [comment]
See https://circleci.com/gh/dagster-io/dagster/edit#env-vars

**Comment by alangenfeld** [comment]
addressing in https://dagster.phacility.com/D8
