### ISSUE TITLE
Testing sensors is not compatible with Definitions

### ISSUE THREAD

**Issue by spenczar** [dagster-io/dagster#13207]
### Dagster version

1.2.3

### What's the issue?

I am writing tests of a multi-asset sensor. I need to give it a context. [The docs](https://docs.dagster.io/concepts/partitions-schedules-sensors/asset-sensors#multi-asset-sensors) tell me to use [build_multi_asset_sensor_context](https://docs.dagster.io/_apidocs/schedules-sensors#dagster.build_multi_asset_sensor_context).

That function has a required argument of 'repository_def: RepositoryDefinition`. So to use it, I *must* provide a repository_def.

But I don't have a repository definition, since I'm using Definitions. A different page in the docs (the [one for Repositories](https://docs.dagster.io/concepts/repositories-workspaces/repositories#repositories)) has an admonition on the top:
> In 1.1.6, we introduced [Definitions](https://docs.dagster.io/_apidocs/definitions#dagster.Definitions), which replaces repositories. While repositories will continue to work, we recommend migrating to Definitions

If Definitions are preferred, I think build_multi_asset_sensor_context should accept them.

### What did you expect to happen?

Maybe the docs should be consistent in their recommendation, or explain how to work with either system by providing conversion tools, or maybe the build_multi_asset_sensor_context function should accept a Definitions.

### How to reproduce?

n/a

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by spenczar** [comment]
This seems to be more generally true of `build_sensor_context` as well, so I'll update the title.

**Comment by smackesey** [comment]
Thanks @spenczar, I'll take this on. Expect a fix next week.
