### ISSUE TITLE
Dagster Airflow CI issues

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#1323]
Getting the graphql response from docker cli via stdout when we are using DagsterDockerOperator is flakey and we get intermittent failures on buildkite.

**Comment by alangenfeld** [comment]
examples: 
https://buildkite.com/dagster/dagster/builds/243
https://buildkite.com/dagster/dagster/builds/233
https://buildkite.com/dagster/dagster/builds/232

**Comment by alangenfeld** [comment]
https://buildkite.com/dagster/dagster/builds/246

**Comment by mgasner** [comment]
https://dagster.phacility.com/D72
