### ISSUE TITLE
Revisit ExecutionContext and PipelineContextDefinition

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1324]
Right now we support both:

```
PipelineContextDefinition(resources=...)
```
and
```
PipelineContextDefinition(context_fn=<some thing that returns an ExecutionContext>)
```

Arguably given our conversations re: resources yesterday, we can do away with the latter entirely. So instead of permitting user-created contexts, we'd only allow user-defined resources and loggers, and any custom user business logic would need to be defined within a resource.

**Comment by mgasner** [comment]
+1

**Comment by schrockn** [comment]
I think it should be a goal to do this, however I want this to play out just a *little* bit. I think it is a good escape hatch in case there are some sort of bugs in the logging or resources system to be able to directly override them, in the short term.

However in the short term I think we should bury this in the documentation.
