### ISSUE TITLE
Easier lineage navigation in the Dagit UI

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#13251]
### What's the use case?

We rely heavily on the "groups" functionality for structuring our pipelines. However, it is cumbersome to look at the lineage (upstream/downstream) for groups. 

I propose two buttons next to each group (here):

![image](https://user-images.githubusercontent.com/112868935/228831714-6c033a08-5288-4b5e-b736-3a75c856aba6.png)

Clicking on one would be the equivalent of searching `*"{grop_name}"` in the global asset linage
The other would be `"{grop_name}"*` 

You might want them as toggles - no strong opinion on this.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Thanks for providing a screenshot like this, @mkleinbort-ic, very helpful. We'll consider it!
