### ISSUE TITLE
Error when naming code location `pipelines` due to legacy URL analysis.

### ISSUE THREAD

**Issue by LouisAuneau** [dagster-io/dagster#13258]
### Dagster version
1.2.4

### What's the issue?

When having a code location called `pipelines`, Dagit is unable to show some pages of the UI and instead shows:
```
No matching jobs
**jobs**
was not found in any repository in this workspace
```

The issue is due to the fact that URLs are formatted as follows:
```
http://127.0.0.1:3000/locations/<code_location_name>/jobs/<job_name>
```
But when the code location is called `pipelines`, this front-end code tries to fetch a pipeline named `jobs` which obviously doesn't exists.

### What did you expect to happen?

Deprecate the usage of the legacy keyword `pipelines` in URL reading to avoid this issue as pipelines no longer exist.

### How to reproduce?

Creating a project using the following command:
```
dagster project scaffold --name pipelines
```
### Deployment type

Local is sufficient to reproduce.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Thanks for the report @LouisAuneau. cc @hellendag

**Comment by sryza** [comment]
Related to https://github.com/dagster-io/dagster/issues/12793
