### ISSUE TITLE
s3_pickle_io_manager does not support inputs with multiple partitions

### ISSUE THREAD

**Issue by TimoVink** [dagster-io/dagster#13290]
### Dagster version

1.2.4

### What's the issue?

Hi all. New to dagster, having a good time so far -- very exciting stuff!

Unfortunately I ran into the following issue: When using the `s3_pickle_io_manager` with an asset that takes in a partitioned asset as input, we get the following error:
```
dagster._check.CheckError: Failure condition: Tried to access partition key for asset 'AssetKey(['my_asset'])', but the number of input partitions != 1
```

Upon inspection, comparing `s3_pickle_io_manager` with `fs_io_manager`, we see that the S3 IO manager inherits from `MemoizableIOManager` directly, while the FS IO manager inherits indirectly via `UPathIOManager`. It seems `UPathIOManager` is what contains the logic for handling partitioned assets -- so that's missing from the S3 IO manager.

### What did you expect to happen?

_Ideally_ it'd be nice if all first-party IO managers, like this S3 one, supported the full range of dagster functionality (barring limitations of the underlying IO system).

However, if that is impracticable, perhaps at least it'd be nice to:
 * Add a note in the `dagster-aws` docs that partitions are not supported for this IO manager (apologies if this is already mentioned somewhere -- I couldn't find it)
 * Throw a better error if we do try to load a partitioned asset:
    ```
    # Is it as simple as adding this in PickledObjectS3IOManager.load_input?
    if context.has_asset_partitions:
        raise SomeBetterException("Partitioned assets are not currently supported by the PickledObjectS3IOManager")
    ```

### How to reproduce?

Try to materialize `unique_top_stories` in this example with `s3_pickle_io_manager`:

```
partitions_def = DynamicPartitionsDefinition(name='top_stories')

@asset(partitions_def=partitions_def)
def top_stories(context):
    # omitted

@asset
def unique_top_stories(top_stories):
    # omitted
```

### Deployment type

Dagster Helm chart

### Additional information

Went forth and back on whether this is a "bug" or a "feature request". Ended up tossing it on the `bug` side of the fence because:
 * Partitions are a core dagster feature
 * The AWS S3 IO manager is managed by dagster themselves (not a community-maintained library I believe?)
 * There is no documentation on this limitation (that I could find)

Of course feel free to reclassify as you see fit :)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by TimoVink** [comment]
This issue is related to https://github.com/dagster-io/dagster/issues/10908, though smaller in scope and therefore perhaps more actionable?

**Comment by adjit** [comment]
For further context, the error is thrown from the s3 IO Manager to `get_asset_identifier` https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-aws/dagster_aws/s3/io_manager.py#L32. This will cause an error to be thrown here for `self.asset_partition_key` https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/execution/context/input.py#L459, where the error is ultimately thrown from here - https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/execution/context/input.py#L332. The IO Manager needs to handle the other types of assets.

**Comment by smackesey** [comment]
Thanks for the report @TimoVink, as there are two related issues here that have been around a while I'll take a look.

**Comment by sryza** [comment]
Heads up – I updated the title to reflect my understanding of what's going on here: I believe this is specific to the case where an input corresponds to multiple partitions.  E.g. in the case of your example @TimoVink , a non-partitioned asset is depending on a partitioned asset, so the input of the non-partitioned asset corresponds to every partition of the partitioned asset.

**Comment by adjit** [comment]
@smackesey is there any update on the progress of this? Trying to come up with a custom IO manager to handle this, but running into some issues
