### ISSUE TITLE
[1.2.4] Dynamic Partitions broken with remote grpc

### ISSUE THREAD

**Issue by planvin** [dagster-io/dagster#13309]
### Dagster version

1.2.4

### What's the issue?

with the removal of PartitionSetDefinition #13145 , a side effect is that we are unable to launch a dynamically partitionned asset materialization (at least from dagit).

### What did you expect to happen?

the job should launch normally

### How to reproduce?

create a simple asset with a dynamic partition a `main.py`script for example:

```python
from dagster import asset, Definitions, DynamicPartitionsDefinition

dynamic_partitions = DynamicPartitionsDefinition(name="testpartition")


@asset(partitions_def=dynamic_partitions)
def myasset(context):
    return 1


defs = Definitions(
    assets=[myasset],
)

```

launch a grpc server : `dagster api grpc -f main.py -h localhost -p 3030`

create a remote code location with a `workspace.yml`file : 

```yaml
load_from:
  - grpc_server:
      host: localhost
      port: 3030
      location_name: brokenpartitions
```

launch dagit : `dagit -w workspace.yml`

try to materialize the asset in dagit (create a partition if needed)

get the error message : 

![image](https://user-images.githubusercontent.com/917377/229274093-f3aa6793-90d4-4391-91e4-4eb394ebe75a.png)

### Deployment type

Dagster Helm chart

### Deployment details

should fail as long as the code location is a grpc server

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Thanks for the report and PR, we'll get this fixed this week.

**Comment by smackesey** [comment]
@clairelin135 Looks like my `PartitionSet` PR broke something (easily fixed, thx @planvin) related to materializing dynamically partitioned assets. This indicates there is a gap in test coverage here, would you mind adding a test?

**Comment by clairelin135** [comment]
Ah yeah, I also realized this was broken. I have a fix PR that includes a test (looks almost the same as the other PR) , I'm happy to merge the PR after @planvin's is merged

https://github.com/dagster-io/dagster/pull/13334/files

**Comment by PedroMTQ** [comment]
I'm getting this error as well. 
Is this broken again?

# partition definition
PARTITIONS = DynamicPartitionsDefinition(name='my_partitions')

# call that is raising the error
context.instance.add_dynamic_partitions(dynamic_partitions_definition_name='my_partitions', partition_keys=new_partitions)

#error
dagster_shared.check.functions.CheckError: Failure condition: The instance is not available to load partitions. You may be seeing this error when using dynamic partitions with a version of dagster-webserver or dagster-cloud that is older than 1.1.18. The other possibility is that an internal framework error where a dynamic partitions store was not properly threaded down a call stack.
