### ISSUE TITLE
Quick access to current run compute logs from the Dagit UI asset sidebar

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#13325]
### What's the use case?

I have some long running asset materialization, and it'd be good to see the logs within the asset lineage page. 

So, my feature request is:

"As someone monitoring asset materializations, I'd like to be able to have quick access to an asset materialization's compute logs from within the asset lineage view so that I can quickly see the progress of my assets"

### Ideas of implementation

I envision this as adding these views:

![image](https://user-images.githubusercontent.com/112868935/229468439-f7c5f307-bd4f-4ea0-b4c4-5cdd0ff13e99.png)

From the current run to the side panel of that opens when you click on an asset in the Dagit Global Asset Lineage.

This should point to the current run's logs or the latest run's logs. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for the idea @mkleinbort-ic - I'm forwarding this to the Dagster UI team.
