### ISSUE TITLE
Update integration libs for compatibility with pandas 2.0

### ISSUE THREAD

**Issue by smackesey** [dagster-io/dagster#13339]
### What's the use case?

Pandas 2.0 was released on 4/3/2023, the following libs exampled have been pinned at `pandas<2` and need to be updated for compatibility:

- assets-pandas-type-metadata
- assets-pandas-pyspark
- dagster-duckdb-pandas
- dagster-duckdb-pyspark
- dagster-gcp-pandas

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by pzarabadip** [comment]
On a related note to PR #14172 , I've tried to resolving this issue for `dagster-duckdb-pyspark` as well.
It requires further investigation as the incompatibility raises from not passing time units (`FAILED python_modules/libraries/dagster-duckdb-pyspark/dagster_duckdb_pyspark_tests/test_type_handler.py::test_partitioned_asset - TypeError: Casting to unit-less dtype 'datetime64' is not supported. Pass e.g. 'datetime64[ns]' instead.`
