### ISSUE TITLE
Re-execute button on runs page should reuse asset selection

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#13370]
We got a report from a user that when they kicked off a re-execution of a run that was originally launched as part of a pure asset backfill, it attempted to re-materialize all the assets in the code location.

This button:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/654855/229932380-f1dd8a58-a23e-42f4-a59b-b1a2a4d9e0ca.png">

**Comment by salazarm** [comment]
@sryza Do you have repro steps for this? I've been trying to figure out how this happened but from looking at the logic it seems to depend on which runs are "checked". Could it be that they had "Selected all"

**Comment by sryza** [comment]
I just tried to reproduce this, but could not.

When addressing a different issue, @johannkm made a change that fixed asset selection retries for non-job asset.  I wonder if that fixed this as a side effect.

I'm going to close this.

**Comment by johannkm** [comment]
I don't think I fixed it, my change was limited to runs from the retry daemon. Maybe something else
