### ISSUE TITLE
Asset reconciliation sensor is triggering all partition of MultiPartitionsDefinition asset instead on only the latest

### ISSUE THREAD

**Issue by mgierada** [dagster-io/dagster#13382]
### What's the use case?

My asset uses  `MultiPartitionsDefinition` partitions. I noticed that **all** of them are triggered by `asset_reconciliation_sensor` My understanding was it should behave similarly to `DailyPartitionsDefinition` so only the latest partition triggered. Is it a bug or a feature? Is there a way to setup `asset_reconciliation_sensor` to trigger only latest partitions of `MultiPartitionsDefinition` asset?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
As mentioned on Slack, @clairelin135 is going to look into this when she has the chance
