### ISSUE TITLE
Syntax Errors during pipeline loads are rough

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1341]
dagit error

![Screenshot 2019-05-09 10 48 13](https://user-images.githubusercontent.com/28738937/57474863-fcbd0000-7247-11e9-8f86-2c9a506239e9.png)

actual error:

![Screenshot 2019-05-09 10 48 24](https://user-images.githubusercontent.com/28738937/57474875-03e40e00-7248-11e9-89dd-ff38d146c654.png)

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by mgasner** [comment]
This is resolved by https://dagster.phacility.com/D626
