### ISSUE TITLE
Figure out how to safely expose config in Airflow DAGs

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1342]
https://dagster.phacility.com/D66

cf. #681, #1246, #1289

**Comment by natekupp** [comment]
I was hoping to stash this in the Airflow dag_details pane, but it is unfortunately not pluggable at all: https://github.com/apache/airflow/blob/1.10.3/airflow/www/templates/airflow/dag_details.html

**Comment by natekupp** [comment]
it's really unfortunate, as this is a very natural place to stash this. and for the record, Jinja templates escape things, so we can't cheat with injection trickery like

`'owner': 'airflow</td></tr><tr><th>injected new thing</td><td></td></tr>',`

**Comment by natekupp** [comment]
WIP here https://dagster.phacility.com/D421

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by natekupp** [comment]
No longer need this, as using StringSource to pull config from the environment solves this issue.
