### ISSUE TITLE
Tags are not defined/missing when executing scheduled partition jobs

### ISSUE THREAD

**Issue by mgierada** [dagster-io/dagster#13504]
### Dagster version

1.2.6

### What's the issue?

Let's say I have an asset partitioned by `MultiPartitionDefinition`. I want to create a schedule that will target specific partitions. Let's say I want to target all latest partition for a finished day (so it would be yesterday). I also want to have a custom crone for that.

Dagster throws an error every time it tries to execute that scheduled job saying:

![image](https://user-images.githubusercontent.com/23472449/231122571-b2256247-6adb-4e1e-af5d-47992ae1cab0.png)

I debug into that a bit and it seems that tags are not present in the scheduled run. Tags are also not visible if I strictly add them like that.

```python
@schedule(cron_schedule="* * * * *", job=job, execution_timezone="US/Eastern")
def my_schedule():
    for partition_key in get_latest_partitions():
        request = job.run_request_for_partition(
            partition_key=partition_key,
            run_key=partition_key, 
            tags={"dagster/partition": "2023-04-08|id1"},

        )
        yield request
```

### What did you expect to happen?

- Scheduled jobs are running requested partitions without any error.
- [Documentation](https://docs.dagster.io/concepts/partitions-schedules-sensors/partitions#creating-schedules-from-partitioned-jobs) is more up-to-date

### How to reproduce?

Code:

``` python
from datetime import date, timedelta

from dagster import (
    AssetSelection,
    define_asset_job,
    schedule,
)

from .const import HISTORY_START_CURRENT
from .partitions import (
    make_static_figi_and_date_multi_partition,
)


history_start = HISTORY_START_CURRENT.strftime("%Y-%m-%d")
partition = make_static_figi_and_date_multi_partition(history_start)

job = define_asset_job(
    name="my_custom_schedule",
    selection=AssetSelection.keys(["public", "some_asset"]),
    partitions_def=partition,
)


def get_latest_partitions():
    partition_keys = partition.get_partition_keys()
    yesterday = (date.today() - timedelta(days=1)).strftime("%Y-%m-%d")
    return [
        partition_key for partition_key in partition_keys if partition_key.startswith(yesterday)
    ]

@schedule(cron_schedule="* * * * *", job=job, execution_timezone="US/Eastern")
def my_schedule():
    for partition_key in get_latest_partitions():
        request = job.run_request_for_partition(
            partition_key=partition_key, run_key=partition_key
        )
        yield request
```

`make_static_figi_and_date_multi_partition` looks like this:

```python
from dagster import StaticPartitionsDefinition, DailyPartitionsDefinition, MultiPartitionsDefinition

def make_static_figi_and_date_multi_partition(start_date: str) -> MultiPartitionsDefinition:
    return MultiPartitionsDefinition(
        {
            "date": DailyPartitionsDefinition(start_date=start_date),
            "figi": StaticPartitionsDefinition(["id1", "id2"]),
        }
    )
```

### Deployment type

Local

### Deployment details

The same for docker version and Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Followed up within Slack, but you could try 
```
yield RunRequest(partition_key=partition_key, run_key=partition_key)
```
instead of
```
request = job.run_request_for_partition(
    partition_key=partition_key, run_key=partition_key
)
yield request
```

**Comment by sryza** [comment]
Closing this based on this message from Slack:

> Hi team, I found the root cause and solution. I was removing tags while marking all schedules as off for localhost. I refactored my logic and schedule works well. Thanks for explanation and hard push on that.
