### ISSUE TITLE
Add `partition_time_window_to_vars_fn` arg to `load_assets_from_dbt_project`

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#13530]
This would allow single-run range backfills over dbt assets

**Comment by yusufshalaby** [comment]
This would be very helpful. Something like

(partition_start: Any, partition_end: Any) -> Dict[str, Any]

Where partition_start and partition_end are defined using context.asset_partitions_time_window

**Comment by rexledesma** [comment]
This can be done using `DbtCli` and `@dbt_assets`, since the user has full control over the compute function. 

See https://github.com/dagster-io/dagster/discussions/14477 for more details.
