### ISSUE TITLE
Support asset-level backfill configuration

### ISSUE THREAD

**Issue by tha23rd** [dagster-io/dagster#13565]
### What's the use case?

We are running into several headaches related to backfills due to:
1. Concurrency limitations in BigQuery
2. Hourly tables having an absolute crap load of partitions

We would love to take advantage of the partition range backfilling feature, but:

Typically backfills for us:
- Encompass a subset of the entire DAG
- Encompasses 1 or more assets that must build one window per query, and thus cannot handle ranges
- Encompasses assets that can handle different "ranges". I.e asset A might be huge and can only load ~15 partitions per query without timing out, whereas asset B is simpler and can handle ~365 partitions

Hence, being able to specify a policy per asset (just like the proposed auto materialization policy) is greatly needed for us to be able to make use of it

### Ideas of implementation

I was looking at the proposal for the reconciliation sensor, specifically the AutoMaterializationPolicy - and I think this is a pattern that would supply a good interface for configuring how an asset is backfilled as well. In its simplest form, it could be:
```py
AssetBackfillPolicy {
    can_coalesce: bool # whether or not an asset can be materialized in chunks
    coalesce_chunk_size: int # the max size of partitions that can be materialized at once for an asset
}
```
Having this kind of control on a per-asset basis would provide a lot of flexibility and alleviate some of the pain that is endured from backfilling per-partition (especially for hourly assets)
Ideally we can then launch a backfill across a large swath of assets, and the backfilling daemon would take these policies into account when kicking off/coordinating runs

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @tha23rd - I've thought that it could make sense to add an API like this as well.x

**Comment by sryza** [comment]
Here's a proposal: https://github.com/dagster-io/dagster/discussions/14829

**Comment by sryza** [comment]
Closing this now that we have `BackfillPolicy`s!
