### ISSUE TITLE
Pointing dagit at a repository.yml that references a missing module should warn or error

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1359]
e.g. if repository.yml says:
```
repository:
  module: foobar
  fn: define_repo
```
dagit silently passes and displays an empty repo

**Comment by natekupp** [comment]
Good catch - might be good to add a few more test cases exercising things like this in the tests for the `ExecutionTargetHandle` object that I just landed

**Comment by mgasner** [comment]
cf #1104

**Comment by mgasner** [comment]
the `ExecutionTargetHandle` actually raises a ModuleNotFound error as we might expect -- https://dagster.phacility.com/D235 will kill the parent process

**Comment by schrockn** [comment]
Confirmed in https://dagster.phacility.com/D241
