### ISSUE TITLE
allow setting AutoMaterializePolicys when using load_assets_from_dbt_project and similar

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#13627]
Similar to freshness policies, it could be useful to be able to set this on individual dbt models via dbt config.

Though you probably also want it to be easy to set on all your models at once.

**Comment by OwenKephart** [comment]
closed! https://github.com/dagster-io/dagster/pull/13794

**Comment by askvinni** [comment]
Hah didn't even realize there was an open issue for this. Sorry for stealing your work @johannkm :D
