### ISSUE TITLE
Show full asset name when zoomed in on asset graph

### ISSUE THREAD

**Issue by clayheaton** [dagster-io/dagster#13670]
### What's the use case?

Some assets have names long enough that they do not completely appear when zoomed in on the asset graph. For example:

![zoomed_in](https://user-images.githubusercontent.com/205364/232224296-4921fd0b-98ee-45df-96dd-cc2cef6e900a.png)

However, when zooming out, there's a tooltip that shows the entire name:

![zoomed_out](https://user-images.githubusercontent.com/205364/232224352-cc847f9d-670f-4647-bf71-a3b282c414b5.png)

The use case is that I need to be able to see the full name of the asset when zoomed in and viewing the graph.

### Ideas of implementation

An _ideal_ solution would be that the full name is visible without a tooltip.

An acceptable easier short-term solution would be to show the tooltip with the full name of the asset when zoomed in on the asset graph.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
> An acceptable easier short-term solution would be to show the tooltip with the full name of the asset when zoomed in on the asset graph.

This is reasonable, let's make sure these are tooltip'd.
