### ISSUE TITLE
Wrap Query object in a DagsterQuery or equivalent with better/minimal error handling

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1369]
Right now we are throwing error info away everywhere -- we should at least log to console. E.g., App.tsx:58 (only look at queryResult.data), ConfigEditorPresetsPicket.tsx:35 (throw error away completely). cc @alangenfeld

**Comment by mgasner** [comment]
This is an issue when dagit needs to be rebuilt and we end up with endlessly spinning interfaces with no error feedback in console, UI, or on dagit command line

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by mgasner** [comment]
Closing this as the most egregious cases are mitigated by PythonErrorInfo
