### ISSUE TITLE
on backfill page, include targeted assets that are not partitioned

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#13702]
Currently, if you launch a backfill that includes some partitioned assets and some non-partitioned assets, only the partitioned assets will be shown on the backfill page

The value in the "Partitions targeted" column these assets should be "-"

**Comment by clairelin135** [comment]
@salazarm I have a PR out to update the gql queries to also return unpartitioned assets, do you think you could add the front end changes to display rows for these assets?

PR: https://github.com/dagster-io/dagster/pull/13853
