### ISSUE TITLE
Partition selector modal broken

### ISSUE THREAD

**Issue by psarka** [dagster-io/dagster#13798]
### Dagster version

dagster, version 1.3.0

### What's the issue?

The partition selector modal does not scroll and does not display partitions. See the gif attached. What you don't see in the gif is me trying to scroll down to see more partitions and scrolling down does nothing. Also in real view the partitions flicker at high frequency
![broken_selector](https://user-images.githubusercontent.com/1212244/233410337-7d93b726-b9ed-45e5-aef1-4820249c38c1.gif)

### How to reproduce?

Link: https://github.com/psarka/repro/tree/failing-ui

Otherwise, it should be very easy to trigger, just create any asset with many partitions. My example uses 1000, probably a lower number will do too, have not tried to find the lowest.

### Deployment type

Local

### Deployment details

Edition	Windows 10 Pro
Version	22H2
Installed on	‎2023-‎01-‎09
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

Microsoft Edge Version 112.0.1722.48 (Official build) (64-bit)

Python 3.11.2

### Additional information

I have noticed this since 1.2.2 and was waiting for it to be fixed, but maybe it only triggers on specific OS / browser?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Hi! Thank you for reporting this.

@salazarm , are you the right person to give a heads-up about this?

**Comment by psarka** [comment]
Broken on Ubuntu + Firefox as well

![image](https://user-images.githubusercontent.com/1212244/233546255-d341ab48-d58d-445a-bdb5-b5b292e1419c.png)

**Comment by salazarm** [comment]
I have a potential fix slated for the release next week but I haven't been able to test it on my windows machine due to various WSL 2 issues :\

**Comment by psarka** [comment]
If you need help testing your fix and you have instructions, I could give it a shot.

**Comment by salazarm** [comment]
Yeah if you could try running off the master branch to see if the issue is fixed I would appreciate you a ton!

**Comment by psarka** [comment]
Unfortunately I can't get it to build :(

```
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
```

If the potential fix is on master already, does it mean that it will get released with 1.3.3? If so, I'll take a look then. I have checked 1.3.2, it is still broken there.

**Comment by psarka** [comment]
I get the same error on Ubuntu, do you guys still use `make dev_install`?

**Comment by psarka** [comment]
I changed the title, as this does not seem to be limited to one OS. It is broken on Windows + edge, Ubuntu + firefox, Ubuntu + chrome and Mac (not sure which browser).

**Comment by psarka** [comment]
@salazarm Could you please indicate if you are able to replicate this on your side and if you have plans to have it fixed by 1.3.4 or 1.3.5? This is just for us to plan if we should wait for a bit more, or to migrate now and find a way around the issue (we are still on 1.1.21, which was the last working release).

Thanks! :)

**Comment by salazarm** [comment]
hi @psarka Yes we have plans to address the issue. Can you clarify what exactly broke after 1.1.21? Is it more than just the issue you reported here that broke?

**Comment by salazarm** [comment]
Hi @psarka Is it possible you have multiple partitions with the same name somehow? Or maybe the difference is just whitespace?

**Comment by salazarm** [comment]
@psarka Have you tested this on OSX?

**Comment by salazarm** [comment]
Could you try with the above PR: https://github.com/dagster-io/dagster/pull/14238

**Comment by psarka** [comment]
It did indeed fix my repro case :tada: Thanks!
