### ISSUE TITLE
negative number of requested runs on backfill page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#13791]
Notice the value under "Requested" for daily_asset:

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/654855/233227122-b0798cdf-97d5-4d93-968f-e063a87be90b.png">

How I got here:
* Launched `dagster dev` from the repo root
* Launched a backfill of daily_asset, hourly_asset1, and hourly_asset2, with this selection: "2023-03-24-04:00...2023-03-26-13:00"
* Waited

**Comment by clairelin135** [comment]
Was able to repro this--looks like negative counts are only displaying when certain partitions fail.

Looking into this and will put out a fix
