### ISSUE TITLE
API audit: startPipelineExecution and executePlan

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1379]
These APIs are totally gross at this point and have too many parameters. I also suspect some of them aren't needed as they aren't all used.

**Comment by natekupp** [comment]
Per discussion on https://dagster.phacility.com/D137 it'd be nice to consolidate these into a single API with appropriate hooks to grab events for testing contexts

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by mgasner** [comment]
Resolved in https://dagster.phacility.com/D198
