### ISSUE TITLE
DagsterEvent.is_step_success should change

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1380]
Per morning conversation with @alangenfeld, this is currently:
```
    @property
    def is_step_success(self):
        return not self.is_step_failure
```
but seems like it should be:
```
    @property
    def is_step_success(self):
        return self.event_type == DagsterEventType.STEP_SUCCESS
```
however, we need to make sure we have test coverage on this before changing, in particular cases where we might skip part of a pipeline. For example, in this pipeline:

```
  B
 / 
A  
 \ 
  C
```
if `B` depends on an output of `A` but `C` depends on an optional output and is skipped, the pipeline still should be marked successful.

**Comment by alangenfeld** [comment]
Heres the code I was concerned about 

https://dagster.phacility.com/source/dagster/browse/master/python_modules/dagster/dagster/core/execution/results.py$51-54

so i think the change should be safe to make. We should still add the test.
