### ISSUE TITLE
Compact display for DisplayEvents that have only one key/value pair

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1381]
See feedback on https://dagster.phacility.com/D171

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by mgasner** [comment]
I think we can close this in favor of the structured log viewer (we will be deprecating right-hand panel display of these events).

**Comment by schrockn** [comment]
yup agreed

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
