### ISSUE TITLE
QUERY_TEMPLATE in dagster-airflow should use variables not default values

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1383]
QUERY_TEMPLATE currently works by interpolating values as *default* values for variables to the mutation and then executing it with no variables. We should instead not use defaults and use traditional variable parameterization

**Comment by natekupp** [comment]
I do this in https://dagster.phacility.com/D137#change-Egeio6YaCQH4 which was based off of the `dagster-airflow` code; should be fairly easy to implement this change
