### ISSUE TITLE
enable auto-materializing historical time partitions

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#13848]
Currently, if you set an `AutoMaterializePolicy` on a time-partitioned asset, then only the most recent partition will be eligible for auto-materializing.

We should make it possible to allow historical partitions to be auto-materialized.

**Comment by sryza** [comment]
One way of looking at this that I have recently found appealing is in terms of a rate limit.

Our current rule is that only the most recent partition is eligible for auto-materializing. The main reason we put this rule in place was that, without it, enormous amounts of work could get accidentally kicked off at once.

Examples of situations where you wouldn't want this all to get kicked off at once:
- You backfill an upstream asset, but that backfill doesn't actually require backfilling the downstream asset. E.g. maybe the change to the upstream asset only affects a kind of row that gets filtered out by the downstream asset.
- You want to save the backfill for the evening, when it's less likely to interfere with peoples' ad-hoc queries.
- You accidentally bump the code version of the upstream asset when you didn't mean to.
- The historical partitions of the downstream asset are already materialized, but you haven't had a chance to tell Dagster about this yet.

In these situations, the consequence of (re)materializing a few partitions of the downstream asset every hour are low, but the consequences of materializing all of them are high.

An advantage of this rate-limiting approach is that it would also help avoid large accidental backfills in the case of static and dynamic partitions.

**Comment by sryza** [comment]
Another potential option in a totally different direction: allow hardcoding a particular datetime cutoff as part of the `AutoMaterializePolicy`. Partitions earlier than that cutoff are not eligible for auto-materializing.

**Comment by sryza** [comment]
> Otherwise, I found that setting the time_window_partition_scope_minutes to a value equal to the start partition enables the functionality you are talking about here

Right now, we consider this parameter effectively internal, because of some issues we've noticed with it. For example, it can have unintuitive behavior at daylight savings time boundaries. We may choose to keep it, but we're also considering options like replacing it with a historical vs. non-historical boolean.

Any thoughts on what kinds of knobs you think would be helpful here are welcome.

**Comment by tha23rd** [comment]
In that case - certainly in favor of having the "historical" boolean option! Will think more on what other knobs might be useful here

**Comment by sryza** [comment]
@OwenKephart @johannkm is our current plan here basically the following?
1. Make cold-start performance good enough that we can remove `time_window_partition_scope_minutes`
2. Remove `time_window_partition_scope_minutes`
3. Users can set `max_materializations_per_minute` to enable auto-materializing historical time partitions

**Comment by OwenKephart** [comment]
@sryza correct!

**Comment by tha23rd** [comment]
Want to confirm that with the removal of `time_window_partition_scope_minutes` we can still prevent the auto materializer from "backfilling" brand new assets? @sryza @OwenKephart
