### ISSUE TITLE
Custom name for Op created by load_assets_from_dbt_* methods

### ISSUE THREAD

**Issue by wkeifenheim** [dagster-io/dagster#13873]
### What's the use case?

Some patterns of using `dbt` fail to load in Dagster due to non-unique Op names generated by the `dagster_dbt` library.

I have many different `dbt` profiles, each targeting a distinct client domain (i.e., database) to run the _same_ model code for each client. When supplying configuration to invocations of `load_assets_from_dbt_*` method, all result in the same underlying Op name _unless_ you are applying a select/exclude filter that differs between each.

![image](https://user-images.githubusercontent.com/639361/234098651-874eb55f-c2bd-4d68-8429-ed9867632391.png)

These Op names are [auto-generated](https://github.com/dagster-io/dagster/blob/1.3.1/python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py#L382-L385) using a hash of the `select` and `exclude` filters, but not `target` or `profile`.

My runs/builds of `dbt` primarily differ in which `target` is selected, and these fail to load because we cannot have non-unique Op names in a `Definitions` object.

The current suggestion is to pre-compile all the needed `dbt manifests` and load using `load_assets_from_dbt_manifest`, however we still need a way to make each Op (generated from each manifest) always have a unique name.

### Ideas of implementation

Two options, not necessarily mutually exclusive and both may have enough value to pursue.

1. Add a `name` parameter to the `load_assets_from_dbt_*` methods. This would allow a user to create Op names with more semantic value (i.e. "run_dbt_for_some_target" vs. "run_dbt_ab15d").
2. Include additional CLI parameter fields [`profile`, `target`, `vars`] in the `load_assets_from_dbt_*` methods and include it in the hash method that auto-generates the Op name.

### Additional information

This request stems from a conversation I had with @OwenKephart in Slack.

I am working from a modified version of the `assets_dbt_python` example, happy to share that code if it's helpful.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Resolved with https://github.com/dagster-io/dagster/pull/14190
