### ISSUE TITLE
Latest version of dagster-dbt (v1.3.1) incompatible with dbt v1.5

### ISSUE THREAD

**Issue by mikals0ft** [dagster-io/dagster#13898]
### Dagster version

1.3.1

### What's the issue?

We tried upgrading to a pre-release version of dbt-core v1.5 (specifically 1.5.0rc1), and I ran into the following error when trying to run Dagster locally. Looks to be some incompatibility between the new DBT version and dagster-dbt.

![Screen Shot 2023-04-25 at 2 26 04 PM](https://user-images.githubusercontent.com/11432805/234413186-3baf2dc3-b7a3-405a-ad85-c12138a63fba.png)

### What did you expect to happen?

I expected our Dagster repository to load properly, along with all our assets.

### How to reproduce?

Use dagster v1.3.1 along with dbt-core v1.5.0rc1

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@rexledesma @OwenKephart - mind taking a look?
