### ISSUE TITLE
Cannot define resources in RunConfig

### ISSUE THREAD

**Issue by Magniko** [dagster-io/dagster#13915]
### Dagster version

1.3.1

### What's the issue?

Trying to define the resources under the *resources* parameter of RunConfig only yields problems.
Instead, I need to define it separately outside the RunConfig constructor in eg. the **job()** decorator or in the  **.execute_in_process()** method, and I have to also remove the resource argument from the RunConfig instance I passing in the two aforementioned functions.

### What did you expect to happen?

I expected RunConfig to be able to handle the defined resources alone so that I would only need to provide one argument when running the jobs

### How to reproduce?

So from a template like this:
```python
from dagster import job, op, resource, RunConfig

@op(required_resource_keys={"my_resource"})
def my_ops():
    return sum([1,2,3])

@resource
def my_resource():
    return [3, 2, 1]


resources = {"my_resource": my_resource}

config_execution = {"config": {"multiprocess": {"max_concurrent": 4}}}

run_config = RunConfig(execution=config_execution)

@job
def my_job():
    my_ops()




def test_pipeline():
    result = my_job.execute_in_process()
    assert result.success
```

...I will demonstrate the different cases where this issue happens.

### Does not work
Defining the resources in the RunConfig constructor and passing it in the decorator
```python
run_config = RunConfig(execution=config_execution, resources=resources)

@job(config=run_config)
def my_job():
    my_ops()
```
#### Raises
```
E   dagster._core.errors.DagsterInvalidConfigError: Invalid default_value for Field.
E       Error 1: Received unexpected config entry "my_resource" at the root. Expected: "{ io_manager?: { config?: Any } }".
```

### Does not work
Same as above but also defining the resources in the decorator
```python
run_config = RunConfig(execution=config_execution, resources=resources)

@job(config=run_config, resource_defs=resources)
def my_job():
    my_ops()
```

#### Raises
```
E   TypeError: Object of type ResourceDefinition is not JSON serializable
```

### Works
Removing the resource definition from the RunConfig constructor and defining it solely in the decorator
```python
run_config = RunConfig(execution=config_execution)

@job(config=run_config, resource_defs=resources)
def my_job():
    my_ops()
```

## With the execute_in_process() method
This is almost the same as above

### Does not work
Defining the resources in the RunConfig constructor and passing it in the method
```python
run_config = RunConfig(execution=config_execution, resources=resources)

def test_pipeline():
    result = my_job.execute_in_process(run_config=run_config)
    assert result.success
```
#### Raises
```
E               dagster._core.errors.DagsterInvalidDefinitionError: resource with key 'my_resource' required by op 'my_ops' was not provided. Please provide a <class 'dagster._core.definitions.resource_definition.ResourceDefinition'> to key 'my_resource', or change the required key to one of the following keys which points to an <class 'dagster._core.definitions.resource_definition.ResourceDefinition'>: ['io_manager']
```

### Does not work
Same as above but also defining the resources in the method
```python
run_config = RunConfig(execution=config_execution, resources=resources)

def test_pipeline():
    result = my_job.execute_in_process(run_config=run_config, resources=resources)
    assert result.success
```

#### Raises
```
E       TypeError: Object of type ResourceDefinition is not JSON serializable
```

### Works
Removing the resource definition from the RunConfig constructor and defining it solely in the method
```python
run_config = RunConfig(execution=config_execution)

def test_pipeline():
    result = my_job.execute_in_process(run_config=run_config, resources=resources)
    assert result.success
```

### Deployment type

Other

### Deployment details

I am simply running test functions to ensure that the ops and jobs are running properly after having ported them. 
So I am using the **.execute_in_process()** method.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
legacy-style resources cannot be provided to the `RunConfig` object in this way - if you want to be able to provide resources directly to the RunConfig object, you need to use [configurable resources](https://docs.dagster.io/concepts/resources#using-ops-and-jobs).

**Comment by Magniko** [comment]
> legacy-style resources cannot be provided to the `RunConfig` object in this way - if you want to be able to provide resources directly to the RunConfig object, you need to use [configurable resources](https://docs.dagster.io/concepts/resources#using-ops-and-jobs).

Hi, a bit late reply on this as I thought it was resolved. Either way, I have tried to migrate to Pythonic resources and even following the examples above yield errors when using any resources in *RunConfig*  that does not have the key **io_manager**.

```from dagster import job, op, ConfigurableResource, RunConfig
import requests
from requests import Response

class MyConnectionResource(ConfigurableResource):
    username: str

    def request(self, endpoint: str) -> Response:
        # return requests.get(
        #     f"https://my-api.com/{endpoint}",
        #     headers={"user-agent": "dagster"},
        # )
        return endpoint

config_test  = RunConfig(
	resources={"my_conn": MyConnectionResource(username="my_user")},
)


@op
def update_service(context):
    context.resources.my_conn.request("/update")

@job(config=config_test)
def update_service_job():
    update_service()
```

This code raises the following error
`DagsterInvalidConfigError: Invalid default_value for Field.
    Error 1: Received unexpected config entry "my_conn" at the root. Expected: "{ io_manager?: { config?: Any } }".`
