### ISSUE TITLE
dagster-datadog and dagster-bigquery don't appear to run in ci/cd

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1392]

**Comment by schrockn** [comment]
I noticed this because cargo-culting their includes for "mock" did not work for py27.

**Comment by natekupp** [comment]
WIP in [D217](https://dagster.phacility.com/D217) - everything done except for `dagster-gcp`, which needs a credentials JSON file provisioned into its environment and the `GOOGLE_APPLICATION_CREDENTIALS` env var set. Will discuss w/ @alangenfeld on Tuesday

**Comment by natekupp** [comment]
Landed D217
