### ISSUE TITLE
Run a dry run publish.py in buildkite

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1396]
Per conversation with @alangenfeld  - also should check state of filesystem similar to what D217 does for `pipeline.py`

**Comment by natekupp** [comment]
Another vote for `--dry-run`; I just published nightlies on my local machine when testing whether the code worked. Would be nice to be able to test everything up to actually pushing to remote

**Comment by mgasner** [comment]
we now have a --dry-run and a releasability test in buildkite
