### ISSUE TITLE
Auto materialize keeps retrying failed run

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#13985]
if a materialization fails it shouldn't retry

**Comment by schrockn** [comment]
@johannkm shouldn't retry at all? What about abiding by the `RetryPolicy` on the asset?

**Comment by johannkm** [comment]
We have two retry systems already- `RetryPolicy` and auto run retries. These work with runs created by auto materialize. What shouldn't happen is that the auto materialize daemon keeps firing off runs if the prior failed, which is happening currently

**Comment by schrockn** [comment]
Cool makes sense
