### ISSUE TITLE
Missing materialization tags in asset_event

### ISSUE THREAD

**Issue by jzgrzebnicki** [dagster-io/dagster#13980]
### Dagster version

dagster, version 1.3.1

### What's the issue?

In previus versions `@asset_sensor` asset_event contains asset_event.dagster_event.logging_tags['pipeline_tags'] field where you can check tags that where uses during materialization. I new version it's misssing

### What did you expect to happen?

 asset_event to have information about tags used during materialization. I need to check if materialization was run adhock or by schedule

### How to reproduce?

Create asset sensor and try to access asset_event.dagster_event.logging_tags['pipeline_tags']

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
Not a bug - has been renamed to "job_tags".
