### ISSUE TITLE
Slackclient incompatibilities 

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1400]
bin/requirements.txt specifies slackclient==2.0.0 and and dagster-slack requires slackclient==1.3.1

![Screenshot 2019-05-29 11 30 26](https://user-images.githubusercontent.com/28738937/58581797-38266b00-8205-11e9-94ff-2a96a389291b.png)

**Comment by alangenfeld** [comment]
I tried to fix this last week, slackclient 2.0 doesn't support python 2

**Comment by schrockn** [comment]
Doesn't seem to be an obvious solution other than porting bin/publish.py ( http://bin/publish.py ) to 1.3.1 then eh

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
