### ISSUE TITLE
ui mark partitions as already processed

### ISSUE THREAD

**Issue by geoHeil** [dagster-io/dagster#14017]
### What's the use case?

How can I tell dagit that some partitions were already materialized (with a backfill operation outside of dagster)?

https://dagster.slack.com/archives/C02LJ7G0LAZ/p1682765312317029

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
This is currently tracked here: https://github.com/dagster-io/dagster/issues/8795. If you upvote that issue, it will help us with prioritization.
