### ISSUE TITLE
[Dagster Guide] Deployment, Airflow, Dask, etc.

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1402]

**Comment by natekupp** [comment]
Per discussion today, punting from 0.5.0 until we have hammered on the core shim layer, etc. more to gain confidence that the fundamentals are solid

**Comment by mgasner** [comment]
I'd like to close this given https://dagster.phacility.com/D663

**Comment by natekupp** [comment]
yes, closing
