### ISSUE TITLE
Include partition_expr in DuckDB documentation

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#14036]
From https://github.com/pybokeh/dagster-partitioning-av:
> Furthermore, I was using duckdb IO manager, but I soon learned dagster's documentation for duckdb integration isn't as complete as their Snowflake documenation. It was not until I looked at their Snowflake's [documenation](https://docs.dagster.io/integrations/snowflake/reference#storing-partitioned-assets) did I learn that I need to add the metadata= parameter to add the partition_expr key and it's value.

**Comment by jamiedemaria** [comment]
yup! totally hear this. I've been meaning to make a Duckdb integration guide a la Snowflake and BigQuery, but haven't had the time. I could also include example snippets in the api docs for partitions
