### ISSUE TITLE
Failed runs are green in the backfill page

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#14054]
### Dagster version

1.3.2

### What's the issue?

![image](https://user-images.githubusercontent.com/49863538/235774473-18a17e36-986d-4e46-bc7c-d73ff0f4d324.png)

### What did you expect to happen?

They should be red

### How to reproduce?

Run a backfill with failed runs

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Hey @danielgafni, I believe this will be fixed by https://github.com/dagster-io/dagster/pull/13846 which will be in this week's release. Let me know if it's not, and I'll take a second look.
