### ISSUE TITLE
User-facing errors during execution plan construction cause graphql errors

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1406]
Repro: 

1) Inject an error into execution plan construction. e.g.:

![Screenshot 2019-05-30 11 20 16](https://user-images.githubusercontent.com/28738937/58654513-ec3ef900-82cc-11e9-878d-85c2ceea02e1.png)

2) Run in dagit.

3) See this

<img width="683" alt="Screenshot 2019-05-30 11 21 03" src="https://user-images.githubusercontent.com/28738937/58654582-10023f00-82cd-11e9-8cf2-2f629acf5e60.png">

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D751
