### ISSUE TITLE
GraphQL Error: Operation name: RunsRootQuery

### ISSUE THREAD

**Issue by kcatalsakal-ic** [dagster-io/dagster#14085]
### Dagster version

1.2.4

### What's the issue?

When I view the `Runs` page, I am getting this error notification

```
Operation name: RunsRootQuery

Message: Cannot return null for non-nullable field Run.mode.

Path: ["pipelineRunsOrError","results",0,"mode"]

Locations: [{"line":29,"column":3}]

Stack Trace:
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 541, in execute_field
    return_type, field_nodes, info, path, result
  File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 621, in complete_value
    "Cannot return null for non-nullable field"
```

I use dagster_dbt==0.19.2 and this error popped up after having a failed dbt asset materialization

### Deployment type

Local dagit

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @kcatalsakal-ic , does this problem go away if you upgrade your `dagit` version to 1.3.2 as well? This looks like a problem that we fixed in that version.
