### ISSUE TITLE
graphql error 

### ISSUE THREAD

**Issue by saravananravi08** [dagster-io/dagster#14082]
### Dagster version

dagster, version 1.1.18

### What's the issue?

Operation name: InstanceWarningQuery

Message: Cannot query field 'backfillId' on type 'PartitionBackfill'.

Path: 

Locations: [{"line":10,"column":9}]

### How to reproduce?

i created a schedule and started it and when i opened the scheduled job's tab in the website it throwed this error on reloading it went away

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Hi @saravananravi08. Would you mind checking what your dagster/dagit versions are? I think there might be a mismatch, it's possible that the dagit version is less than the dagster version, which is causing this error
