### ISSUE TITLE
Proposal: In re-execution workflow we should only display the execution steps we are reexecuting

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1410]
See here: 

I am re-executing a single step in a large pipeline. When I do this multiple times I end up hunting around for the single step I want to re-execute. There is only one step that is relevant so we should probably only display that.

![Screenshot 2019-05-31 10 29 46](https://user-images.githubusercontent.com/28738937/58723483-07723d00-838f-11e9-8dbb-800d3764d41e.png)

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by mgasner** [comment]
https://github.com/dagster-io/dagster/pull/1465

**Comment by natekupp** [comment]
Now at https://dagster.phacility.com/D556

**Comment by helloworld** [comment]
Implemented at: https://dagster.phacility.com/D568
