### ISSUE TITLE
Specify the name of dbt ops that it created using the dbt asset

### ISSUE THREAD

**Issue by juliusngcmc** [dagster-io/dagster#14110]
### What's the use case?

The issue relates to this [slack question](https://dagster.slack.com/archives/C01U954MEER/p1680511176828349)
Can we specify the name of dbt ops that it created using the dbt asset? Like in this example, the dbt run name "run_dbt_3a4be". Can we config this name? 
![image (3)](https://user-images.githubusercontent.com/110522861/236406914-fdc245f3-75c7-46bc-ac57-46b4abc53607.png)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yuhan** [comment]
@rexledesma getting this on your radar in case there's a more ergonomic way to configure things like this.

**Comment by rexledesma** [comment]
This is temporarily resolved by https://github.com/dagster-io/dagster/pull/14190, but with the new incoming `@dbt_multi_asset` decorator, you will be able to specify the name on the decorated function.
