### ISSUE TITLE
ability to do AssetSelection.key_prefix(..)

### ISSUE THREAD

**Issue by C0DK** [dagster-io/dagster#14151]
### What's the use case?

We generally structure our key prefixes similar to catalogs and schemas on the underlying data structure and by source systems. Rather than having to create a job from a mixture of groups, for instance, it would be neat to have something like 

```python

   ingress_job = define_asset_job(
        name="ingress_finance_from_dw",
        selection=AssetSelection.key_prefix(["old_datawarehouse", "finance"]),
    )
  ```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
@C0DK I've opened a PR for this: https://github.com/dagster-io/dagster/pull/14163

**Comment by C0DK** [comment]
Thank you! From feature request to implementation and integration in under 24 hours is very impressive.

You guys rock.
