### ISSUE TITLE
issue running command 'dbt build --select *'

### ISSUE THREAD

**Issue by blackdigitaldotnet** [dagster-io/dagster#14169]
### Dagster version

1.3.3

### What's the issue?

The materialize all command issues from Dagit is issuing a dbt command that is not supported. The build or run command has a '--select *' suffix which results in the following warnings in dbt

23:20:21 The selection criterion 'analyses' does not match any nodes  
23:20:21 The selection criterion 'dbt_packages' does not match any nodes  
23:20:21 The selection criterion 'dbt_project.yml' does not match any nodes  
23:20:21 The selection criterion 'logs' does not match any nodes  
23:20:21 The selection criterion 'macros' does not match any nodes  
23:20:21 The selection criterion 'models' does not match any nodes  
23:20:21 The selection criterion 'packages.yml' does not match any nodes  
23:20:21 The selection criterion 'profiles.yml' does not match any nodes  
23:20:21 The selection criterion 'README.md' does not match any nodes  
23:20:21 The selection criterion 'seeds' does not match any nodes  
23:20:21 The selection criterion 'snapshots' does not match any nodes  
23:20:21 The selection criterion 'target' does not match any nodes  
23:20:21 The selection criterion 'tests' does not match any nodes  
23:20:21  
23:20:21 Nothing to do. Try checking your model configs and model specification args

### What did you expect to happen?

I was expecting my entire dbt DAG to be materialized.

### How to reproduce?

On a windows 11 machine

Install dbt-core==1.5.0 with the associated postgres adapter.

initialise a new dbt project.

Setup a fake profile.yml file. You dont need to create an actual postgres database, but you need to provide some fake mandatory profile parameters so that it believes there is a database it can connect to.

Run 'dbt build --select *'

### Deployment type

Local

### Additional information

Issue was raised with DBT and their response suggests it's a bug with the way Dagster is invoking DBT when trying to run 'materilize all'

https://github.com/dbt-labs/dbt-core/issues/7541

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @OwenKephart

**Comment by OwenKephart** [comment]
After some digging, it seems like this is caused by an inconsistency in how the `click` library handles globs (`*`) in arguments between windows and unix systems. In Unix systems, these characters are handled literally (just pass the `*` into the underlying command), whereas on Windows, the `click` library will automatically expand the `*` in some cases: https://github.com/pallets/click/pull/1830

I believe we should be able to fix this issue by ensuring that we wrap the select argument in quotes before invoking the dbt cli
