### ISSUE TITLE
Enable collapsing asset groups in the asset graph UI

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#14182]
### What's the use case?

We are encountering issues scaling Dagster to more assets while preserving visibility of asset dependencies.

Beyond a few hundred assets the DAG looks uninteligible - which is to be expected.

A major mitigation to this would be the ability to have "sub-groups" and possibly collapsable groups in the Dagit UI.

Kedro has a good implementation (this is a GIF). Here you can see the "group" _Data Processing_ as a single node when zoomed-out, but it can also be expanded.

![image](https://docs.kedro.org/en/0.18.0/_images/collapsible.gif)

### Ideas of implementation

I think this would require a modification to the group_name parameter to accept a list, then one could collapse based on the entries in the list.

In this idea, an asset would be declared as 

```python
@asset(group_name=['data_processing'])
def foo():
    ...

@asset(group_name=['data_processing'])
def bar():
    ...

```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mkleinbort-ic** [comment]
Here is a link to a Kedro interactive demo that shows the functionality.

https://demo.kedro.org/

And here is some documentation on how they've approached dag layout (they seem to have put a lot of thought into it)

https://github.com/kedro-org/kedro-viz/blob/main/LAYOUT_ENGINE.md

**Comment by smackesey** [comment]
cc @bengotow

**Comment by mkleinbort-ic** [comment]
On reflection, this issue could be approached in two phases:

Phase 1: Collapsible Groups 
Phase 2: Nested Groups

### Phase 1: Collapsible Groups 
The first phase would be a UI toggle in the corner of the group bounding box. Here is a proposal:

![image](https://github.com/dagster-io/dagster/assets/112868935/f12c993f-2dc2-436c-b5af-faf79c567afa)

Clicking on the `[ - ]` would collapse the group into a single node with a single input & output point for all edges incoming/outgoing from the assets in the group:

![image](https://github.com/dagster-io/dagster/assets/112868935/0b5ceab4-7b6f-469e-8844-ebad3b6905db)

### Phase 2: Nested Groups
This would allow one do define groups within groups. Hopefully the collapsible groups feature can be extended without too much effort.

**Comment by bengotow** [comment]
This looks great! We've played around a version of the DAG visualization that does more of a "graph with a box, which reveals another graph when you zoom in", but I think a simple collapsing behavior might be best. 

One challenge we've had with this is that groups in asset graphs can get super large, and collapsing them reflows the rest of the graph so much that it's hard to tell what happened. "eg: I hide this huge box, and everything animates all over the place." Maybe we can find a way to mitigate that -- if we restricted the types of reflow allowed after collapsing a box to just sliding other nodes into the empty space, it might be easy enough to follow.

**Comment by mkleinbort-ic** [comment]
I'm also very ok with a full re-flow of the dag. 

In many ways I want to collapse a group to help me think through my DAG in a new way - say "Forgetting that my _data extraction_ group is 100 separate assets - what stuff depends on it, and what stuff does it depend on"?

A re-flow would be helpful in this context.

**Comment by mkleinbort-ic** [comment]
Hi @sryza 
Just want to emphasize how amazing this feature would be! It's definitely the #1 feature I'm looking forward to in Dagster. 

Is it currently in the Dagit backlog? I could not find it here: https://github.com/dagster-io/dagster/projects/8

**Comment by sryza** [comment]
Hey @mkleinbort-ic - I just added it to the Dagit backlog. @braunjj - I think you've seen this already, but just in case you haven't, pinging you.

**Comment by mkleinbort-ic** [comment]
Any updates on this?

**Comment by mkleinbort-ic** [comment]
Hey @hellendag - is this in the roadmap? Will hack something on my end if not.

**Comment by mkleinbort-ic** [comment]
It's a cool feature to navegate the graph. I'm using it at the moment. 

But just to note that it's a different feature to what I'm looking for. In my deployments this pattern is quite common:

![image](https://github.com/dagster-io/dagster/assets/112868935/3eda909e-3a91-41bf-9136-bee1baac2c05)

Usually when computing multiple metrics for an asset, or when extracting data from multiple API endpoints.

I find these "super wide" sections make the DAG quite hard to visualize and reason about, so it'd be nice to collapse them to show the data lineage from source asset to final asset without these distractions.

**Comment by salazarm** [comment]
@mkleinbort-ic @bengotow is currently prototyping this feature.

**Comment by mkleinbort-ic** [comment]
This can be closed as per the recent feature update (👏👏👏👏)
I am moving the conversation about nested groups to https://github.com/dagster-io/dagster/issues/14530
