### ISSUE TITLE
Negative missing partitions appear in the asset card in Dagit

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#14227]
### Dagster version

1.3.3

### What's the issue?

![image](https://github.com/dagster-io/dagster/assets/49863538/e6ad27c9-f269-49b1-acf6-fcad861daa27)

I think this happened after I've switched either the `PartitionsDefinition` or the `PartitionMapping` for the asset.

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @salazarm

**Comment by sryza** [comment]
also cc @clairelin135

**Comment by clairelin135** [comment]
@danielgafni thanks for reporting. If you don't mind, would you be able to check if the counts for materialized and failed partitions are correct? This will help us isolate the source of error.

Also, do you happen to know what the partitions definition was before and after you changed it? Wondering if there's some sort of caching bug.

**Comment by danielgafni** [comment]
Hey, the negative numbers disappeared :( I'll try to capture more info if they ever return.

**Comment by sryza** [comment]
Going to close this for now. Please reopen if it reappears.
