### ISSUE TITLE
Clean up AWS resources and permissions used for test

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1424]
Move everything to pulumi, be explicit about IAM config

**Comment by natekupp** [comment]
FWIW Pulumi doesn't yet support "adoption" of existing resources:

https://github.com/pulumi/pulumi/issues/1662

So we might need to rebuild our BuildKite CloudFormation stacks in Pulumi when we do this.

**Comment by natekupp** [comment]
everything is now under pulumi AFAIK
