### ISSUE TITLE
launchPartitionBackfill for a selection of assets with `allPartitions:true` param not launching backfill for all assets 

### ISSUE THREAD

**Issue by ruizh22** [dagster-io/dagster#14255]
### Dagster version

1.3.2

### What's the issue?

When launching a backfill for a selection of assets with `allPartitions: true` through GraphQL API launchPartitionBackfill, not all the assets are included. 

It works fine when we mix hourly and daily partitioned assets, however, if we mix in any unpartitioned assets, they will not be targeted for backfill and they will not show up on the backfill overview page. 

 It seems to be a problem with unpartitioned assets specifically. 

### What did you expect to happen?

Unpartitioned assets are also included for backfill if we pass them in as part of the asset selection for backfill. 

### How to reproduce?

Execute a launchPartitionBackfill mutation with an asset selection including partitioned and unpartitioned assets, and also pass in `allPartitions:true` in the parameter. 

Go to backfill overview page, and the unpartitioned asset is not being targeted for backfill and not showing up on the UI there.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @clairelin135

**Comment by clairelin135** [comment]
Hi @ruizh22 @tha23rd sorry about the late response!

I believe that starting 1.3.2 we enabled selecting `allPartitions`, but the asset backfill page did not display unpartitioned assets until 1.3.4. So I think that the unpartitioned assets are being targeted in 1.3.2, but are just not being displayed in the UI. 

I think upgrading to 1.3.4 should display these assets.

**Comment by ruizh22** [comment]
No worries at all! 
That's awesome, we will upgrade to 1.3.4 as soon as possible. Thank you so much!
