### ISSUE TITLE
Intermittent failures in SQLite-based logging machinery tests

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1425]
https://buildkite.com/dagster/dagster/builds/1541#cd170120-6822-4f2d-90c9-9d8128de38a4

**Comment by schrockn** [comment]
https://buildkite.com/dagster/dagster/builds/1904#af4df4cb-6831-4cf1-9ace-552ca1e40a6e

**Comment by schrockn** [comment]
https://buildkite.com/dagster/dagster/builds/1979#54604585-78ae-493b-9595-e2ae0c678eca

**Comment by natekupp** [comment]
Punting from 0.5.0 - @mgasner lmk if you think it should stay for any reason

**Comment by mgasner** [comment]
These appear to have gone away. I am going to close this task until we start seeing this again.
