### ISSUE TITLE
UI not displaying custom skip_message of SkipReason when sensor has both yield and return

### ISSUE THREAD

**Issue by ruizh22** [dagster-io/dagster#14271]
### Dagster version

1.3.2

### What's the issue?

UI is displaying a generic message "Sensor function returned an empty result" when the code actually specified a custom skip_message like `SkipReason(skip_message='No assets to backfill')`.

![image](https://github.com/dagster-io/dagster/assets/109117963/5a6a8cbc-3e2e-44c9-8692-d23520c266f8)
![image](https://github.com/dagster-io/dagster/assets/109117963/68a73f39-e178-48c0-b457-3c620eaf85c7)

### What did you expect to happen?

UI to display the custom skip message when hovering over the "Skipped" status and also reflect the same message on the "test sensor" result page.

### How to reproduce?

Define a sensor to return a SkipReason with custom skip_message, the custom skip_message will not show up on UI or anywhere in the log. 

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @ruizh22 - do you have a code example that reproduces this?

I just gave this a shot with this code example

```python
from dagster import sensor, SkipReason, Definitions


@sensor()
def sensor1():
    return SkipReason("hello")


defs = Definitions(sensors=[sensor1])
```

and got the expected behavior:

<img width="106" alt="image" src="https://github.com/dagster-io/dagster/assets/654855/a6033460-b547-401d-b470-fc8c31a79c6f">

-

<img width="220" alt="image" src="https://github.com/dagster-io/dagster/assets/654855/d946eb94-1ca7-4f5e-b558-4d3c656199e2">

**Comment by ruizh22** [comment]
hi @sryza , we are doing something like this:

```
@sensor(name='a_sensor', job_name='a_job')
    def code_versions_sensor(context: SensorEvaluationContext) -> Union[RunRequest, SkipReason]:
        ...
        assets_to_backfill = {...}
        if len(backfill_asset_versions) == 0:
            skip_message: str = 'No assets to backfill'
            context.log.info(skip_message)
            return SkipReason(skip_message=skip_message)
        yield backfill_run_request(assets_to_backfill)
        context.update_cursor(...)
```

**Comment by sryza** [comment]
Can you verify that you're making it to the inside of that `if` statement? E.g. by raising an exception there and seeing if it shows up? Or writing out to a file that you can inspect?

**Comment by ruizh22** [comment]
Yes, it definitely reached into the inside of if block since the sensor eval was short-circuited and returned SkipReason. Otherwise, it will actually launch a RunRequest.

**Comment by sryza** [comment]
Are you able to try out that example I posted and see what happens for you?

**Comment by Lyle-on-Git** [comment]
I'm not sure if this is still the case but in an earlier version of Dagster I found that if I _returned_ a SkipReason in a Sensor from inside an if statement, I encountered this situation (my message did not appear in Dagit), but if I _yielded_ a SkipReason it worked as expected. I did not verify without the if statement as @sryza did in his simplified example.

**Comment by emirkmo** [comment]
I can replicate this, and I can verify the if statements are reached. The problem seems to be returning `SkipReason` with custom message from inside an `if` statement when there is (further down) `yield` statements in the same sensor (for yielding a set of RunRequest).

See minimal example:

```Python
sqs_messages = []
@sensor(<some_job>)
def test_sensor(context):
if len(sqs_messages) == 0:
        context.log.info("This will show up in the logs")
        return SkipReason("There is no data, trying again later.") # this correctly Skip but will not show message.
for message in sqs_messages:
    yield RunRequest(<parsed message>) 
    # correctly shows when message queue has messages:
    context.log.info(f"Messages in SQS queue: {[message.body for message in sqs_messages]}") 
```

Dagit UI shows no reason for the skip.

**Comment by sryza** [comment]
I was able to reproduce this. Here's a fix: https://github.com/dagster-io/dagster/pull/14558.

**Comment by ruizh22** [comment]
@sryza  apologize for the delay and thanks for the fix :)
