### ISSUE TITLE
Graphql endpoint always returns null `metadataEntries { description }`

### ISSUE THREAD

**Issue by DrawnWren** [dagster-io/dagster#14288]
### Dagster version

1.3.3

### What's the issue?

Inside my `io-manager`, I attach metadata to the materialization (inside `handle_output`) with: 
`context.add_output_metadata({"uri": url})`

Dagster correctly displays the metadata inside dagit's frontend. 

However, when I query the `/graphql` endpoint with this query:
```
query RepositoriesQuery {
  repositoriesOrError {
    ... on RepositoryConnection {
      nodes {
          assetMaterializations {
              timestamp
              metadataEntries {
                label
                description
              }
```

The `assetMaterializations` come back with `description: null` instead of the value that I see in `dagit`. 

```
"assetMaterializations": [
                {
                  "timestamp": "1684156958695",
                  "metadataEntries": [
                    {
                      "label": "uri",
                      "description": null
                    }
                  ],
                  "partition": null
                },
```

### What did you expect to happen?

I expect `"description":` to be the same value in the `dagit` frontend for the graphql response. 

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
cc @hellendag can you take a look at this or pass it along to someone more familiar with our graphql endpoints?
