### ISSUE TITLE
Support multi-line docstrings for asset descriptions

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#14293]
Better support for multi-line docstrings. This request makes a ton of sense to me - we should at least do better to support the first line of a description in the asset node. Maybe we always render the first line, and add a "Show more" button to expand it in other views?

**Reported in Slack [here](https://dagster.slack.com/archives/C01U5LFUZJS/p1684071307688029)**

> Any plans to support multi-line docstrings for assets? (summary line, followed by empty line, followed by detailed description). At the moment Dagit drops all the newlines and displays the entire docstring as one long line in the description. I'd expect it to just use the first line of the docstring so it appears neatly in the UI. And maybe expose the rest somewhere else in the UI. Or at least not drop all the newlines! :slightly_smiling_face:

**Comment by sim-dt** [comment]
For reference: [PEP 257 – Docstring Conventions – Multi-line docstrings](https://peps.python.org/pep-0257/#multi-line-docstrings)

**Comment by bengotow** [comment]
Hey folks! It turned out this was a problem specifically with the first double-newline and was caused by some of our code, so we were able to get it fixed. The behavior should be correct in the next release. Thanks!

**Comment by sim-dt** [comment]
Yay! :)
