### ISSUE TITLE
Partitioned observable source assets

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#14290]
### What’s a partitioned observable source asset?

A partitioned observable source asset is a source asset for which it’s possible to make statements like “this partition is present” or “this is the version of this partition”.

Examples include:

- **DailyPartitionsDefinition with files** - every day, at an unpredictable time, an external data provider drops a file corresponding to that day into a directory. Soon after it arrives, we want an AssetObservation in the event log for the asset partition corresponding to that day.
- **DailyPartitionsDefinition with table** - every day, at an unpredictable time, an external data provider adds records corresponding to that day to a table. Soon after it arrives, we want an AssetObservation in the event log for the asset partition corresponding to that day.
- **DynamicPartitionsDefinition** - at unpredictable intervals, new files land in a directory. Soon after it arrives, we want a new dynamic partition corresponding to that day, and an  AssetObservation in the event log for that asset partition.

### Why care about partitioned observable source assets?

Users want to trigger materializations of downstream assets and asset partitions based on changes in partitioned observable source assets.

The most common kind of change is the arrival of a partition that was previously missing.

### Potential API

```python
@observable_source_asset(partitions_def=fruits)
def partitioned_observable():
    return Observation(
        data_version=DataVersionByPartition({"apple": "version1", "banana": "version2"}),
        metadata=MetadataByPartition({"apple": {"num_records": 5}, "banana": ...}),
    )
```

### What we've heard
- https://elementl-workspace.slack.com/archives/C03C3E81TNE/p1684164626829299
  - struggling a little more with observable source assets conceptually - we have sensors currently that monitor date-partitioned bigquery tables that aren't represented as assets and yield run requests for specific partitions when needed. how do i translate this to a paradigm where those bigquery tables are represented as source assets? does the observe_fn for a source asset have any awareness of partitions?

**Comment by chriscomeau79** [comment]
I've been doing something similar myself, without using Dagster's Partition or DataVersion yet. 

If it helps, I call these manifests - term I've seen used in Iceberg + Delta Lake for similar concepts.

Query source, get a row count and max row version timestamp (row modify date), optionally grouped by partition key: source manifest / upstream DataVersion.
Run same query against staged replica (this is in ELT workflow): target manifest / downstream DataVersion.
If reconciliation needed, re-stage affected partitions (or whole table).

That behaviour's all in a single @asset op for my current approach.

**Comment by sryza** [comment]
This week's release includes an experimental change that allows an observable source asset to return per-partition observations: https://github.com/dagster-io/dagster/pull/14354.

@mjclarke94 - not every partition needs to be observed on every invocation of the asset observation.

**Comment by sryza** [comment]
Closing this because of the aforementioned change
