### ISSUE TITLE
Filter Asset Catalog by partition status

### ISSUE THREAD

**Issue by cbini** [dagster-io/dagster#14318]
### What's the use case?

Often times, a partition materialization will fail, and I will have to manually run the materialization after correcting any issues. It would be great if we could filter the asset catalog to show only assets that contain missing or failed partitions so that I can more easily identify what needs to be run.

### Ideas of implementation

Something similar to the filters on the asset details page would be perfect:

![image](https://github.com/dagster-io/dagster/assets/5003326/5ef3b841-a89e-4acc-9409-75f7d0172b98)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
cc @clairelin135  and @salazarm

**Comment by salazarm** [comment]
cc @braunjj

**Comment by salazarm** [comment]
@cbini Have you see our experiemental assets overview page? It splits up the assets by their status so you could for example easily see all of the assets with failed partitions in an asset group:

<img width="483" alt="Screen Shot 2023-06-02 at 2 31 32 PM" src="https://github.com/dagster-io/dagster/assets/2286579/22ad0a2e-8188-4def-9c85-da875bcb8407">

<img width="2050" alt="Screen Shot 2023-06-02 at 2 31 29 PM" src="https://github.com/dagster-io/dagster/assets/2286579/78d0bbde-dfe5-4abc-b49d-d95a9dc1a560">
<img width="216" alt="Screen Shot 2023-06-02 at 2 31 27 PM" src="https://github.com/dagster-io/dagster/assets/2286579/d080cd20-9b0e-47c7-ad37-7a97f254f0ef">
<img width="631" alt="Screen Shot 2023-06-02 at 2 32 53 PM" src="https://github.com/dagster-io/dagster/assets/2286579/eb71592a-5dcb-4e05-8ce7-244427ba8f32">

**Comment by hellendag** [comment]
Closing since this has shipped. :)
