### ISSUE TITLE
Debug test_run_emr_job

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1431]

**Comment by natekupp** [comment]
https://buildkite.com/dagster/dagster/builds/1593#5f7713fa-984d-4ae2-9142-5a6f4d0a5482

**Comment by natekupp** [comment]
See:
https://github.com/spulec/moto/issues/2118
https://github.com/spulec/moto/issues/1815

**Comment by natekupp** [comment]
Experimenting here https://dagster.phacility.com/D350

**Comment by natekupp** [comment]
Well, I tried a number of permutations - I don't think we're going to be able to fix this until moto addresses the underlying issues w/ newer versions of boto. Let's leave the test marked skipped for now and we can revisit when moto updates

**Comment by natekupp** [comment]
This is now fixed w/ recent moto
