### ISSUE TITLE
--path-prefix regression no longer working in 1.3.4

### ISSUE THREAD

**Issue by mpicard** [dagster-io/dagster#14310]
### Dagster version

1.3.4

### What's the issue?

`dagit --path-prefix PATH` is no longer working in 1.3.4

### What did you expect to happen?

This option worked in 1.3.3, the dagit UI worked on paths with a prefix.

### How to reproduce?

`dagit --path-prefix /dagit` and see the client side errors due to 404s

### Deployment type

Dagster Helm chart

### Deployment details

Using helm chart but the issue seems to be with the binary probably, as I can see that the container command does indeed include the --path-prefix.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
thanks for filing this issue! @gibsondan  mind taking a look or passing on to someone else?

**Comment by tfederman** [comment]
Also ran into this and have worked around #5678 in the past. Using the path-prefix is super useful.

**Comment by hellendag** [comment]
Fixed by https://github.com/dagster-io/dagster/pull/14421, which will be in the 1.3.6 release.
