### ISSUE TITLE
AutoMaterializePolicy.eager should wait for upstream asset runs to complete, optionally

### ISSUE THREAD

**Issue by joel-olazagasti** [dagster-io/dagster#14327]
### What's the use case?

Currently, an eager automaterialization policy will happily kick off asset materialization runs of downstream assets when their upstream ancestors are being materialized by another job. I've only had this happen when my team has merged changes that unblock a broken scheduled job, so the fixed job is run automatically, and the automaterialize policy triggers on code versions. But I can imagine a scenario where this might happen if a team staggers their schedules such that they retrigger cascading automaterializations while another dependent asset is materializing. I can imagine that might be a viable use case for some teams, where they want to always keep downstream assets up to date, even in the case of incoming new upstream data. With high enough sync frequencies that's probably the case, but otherwise it's a waste of compute and resources.

### Ideas of implementation

Either a parameter on `AutoMaterializePolicy.eager()` or a third option for an AM policy that does not trigger materializations of assets while an upstream dependency is currently being materialized.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey Joel - thanks for the input. We'll digest this. I wonder if this should even be the default behavior.

**Comment by joel-olazagasti** [comment]
There's probably a good case to be made for that. I imagine *most* users would rather not run consecutive jobs because assets are updating too early. Having cascading, blocking updates, that are staggered in such a way that downstream assets are never free to auto-materialize requires some fairly specific circumstances. And teams that want their downstream models updated for each upstream update, regardless of overlap, are likely the more mature data teams better equipped to handle their custom requirements.

**Comment by OwenKephart** [comment]
Hi! Checking back in on this issue after awhile, but one option here is to use the new [skip_on_not_all_parents_updated](https://docs.dagster.io/_apidocs/assets#dagster.AutoMaterializeRule.skip_on_not_all_parents_updated) AutoMaterializeRule: 

```python
from dagster import AutoMaterializePolicy, AutoMaterializeRule

my_policy = AutoMaterializePolicy.eager().with_rules(
    AutoMaterializeRule.skip_on_all_parents_not_updated(),
)
```

This definitely does not have the exact same semantics as your proposal, but achieves a similar goal of "wait for all my parents to complete". Would that work for your usecase?

**Comment by joel-olazagasti** [comment]
@OwenKephart That would work for me! Just waiting on an Airbyte integration bugfix, then I can upgrade and implement that.

**Comment by OwenKephart** [comment]
Got it! Closing this issue for now.
