### ISSUE TITLE
Pythonic resource sharing between schedule and job fails

### ISSUE THREAD

**Issue by alexknorr** [dagster-io/dagster#14333]
### Dagster version

1.3.4

### What's the issue?

When a pythonic resource is used in both schedule and job op, loading fails if the schedule is bound to a job definition instead of the job name:

> dagster._check.ParameterCheckError: Invariant violation for parameter Cannot specify resource requirements in both @sensor decorator and as arguments to the decorated function.

There was a similar issue with sensors in 1.3.2. that got fixed in 1.3.3.

### What did you expect to happen?

Pythonic resources in schedules to work the same way as in sensor definitions.

### How to reproduce?

```python
from dagster import (
    ConfigurableResource,
    Definitions,
    OpExecutionContext,
    RunRequest,
    ScheduleEvaluationContext,
    job,
    op,
    schedule
)


class Resource(ConfigurableResource):
    value: str

    def log(self, logger):
        logger.info(f'my value is {self.value}')


@op
def op_requires_resource(context: OpExecutionContext, resource: Resource):
    resource.log(context.log)


@job
def a_job():
    op_requires_resource()


# @schedule(job_name=a_job.name, cron_schedule='* * * * *')
@schedule(job=a_job, cron_schedule='* * * * *')
def a_schedule(context: ScheduleEvaluationContext, resource: Resource):
    resource.log(context.log)
    return RunRequest()


defs = Definitions(jobs=[a_job],
                   schedules=[a_schedule],
                   resources={'resource': Resource(value='valuable')})

```

It works when @schedule(job_name=a_job.name, cron_schedule='* * * * *') is used insted.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
cc @benpankow  mind taking a look when you get back?
