### ISSUE TITLE
dagster-dbt source key prefix include refs

### ISSUE THREAD

**Issue by bmarcj** [dagster-io/dagster#14336]
### What's the issue or suggestion?

The [documentation](https://docs.dagster.io/integrations/dbt/reference#adding-a-prefix-to-asset-keys) says:

> Note: The key_prefix argument only applies to models. If you want to apply a prefix to the source keys that Dagster generates, pass in a source_key_prefix argument:

This seems to not just matter for source keys, but also for any refs that are not loaded as models (by include/exclude flags on the dbt loading). Either the documentation should change to mention this fact, or all models (not just those included in the loading) need to have the key appended. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
cc @OwenKephart  or @rexledesma  mind taking a look?

**Comment by OwenKephart** [comment]
Hi @bmarcj ! Thanks for pointing this out. The behavior works as you're expecting (refs will get the key prefix as well), it's the documentation that's wrong. Just created a PR to address this!

**Comment by OwenKephart** [comment]
@bmarcj sorry about that -- you're totally correct (mistyped in the above answer, just edited)
