### ISSUE TITLE
Need a sensible subset selection story for composites

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1434]
Composites aren't expandable here, so we should find another way to visually indicate that the solid is a composite:

![image](https://user-images.githubusercontent.com/609349/58914677-036a5600-86d4-11e9-917e-9861750304ef.png)

**Comment by mgasner** [comment]
@themissinghlink can you record the issues you've been having with subset selection of composites here

**Comment by mgasner** [comment]
See: https://dagster.phacility.com/D2879. We are going to merge this for 0.8.1, but first do some work to change all config for composite solids to use the dotted solid handle syntax rather than nesting under `composite_a.config.solids.solid_a.config` etc

**Comment by hellendag** [comment]
Workaround is now to use the DSL in solid selection view.

**Comment by mgasner** [comment]
Why was this closed?

**Comment by sryza** [comment]
@mgasner - I filed a separate issue (https://github.com/dagster-io/dagster/issues/3557), because it seems like this issue has taken on a different meaning (selecting full top-level composites inside Dagit?)
