### ISSUE TITLE
[Dagit] Better keyboard shortcut zoom-in/zoom-out in graph view using scroll wheel

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#14351]
### What's the use case?

The recent 1.3.4 release made the scroll wheel pan the dagit graph up/down (vs. the previous zoom-in/zoom-out)

I can still zoom-in/zoom-out with `windows key` + `scroll wheel`, but this opens the start menu on windows.

I much preferred the zoom-in/zoom-out default, but if that's not coming back can we change the shortcut to `ctrl`+`scroll wheel` or `alt`+`scroll wheel`, or `shift`+`scroll wheel`? the use of the `windows key` is not great.

### Ideas of implementation

Change the zoom-in/zoom-out shortcut to `ctrl`+`scroll wheel` or `alt`+`scroll wheel`, or `shift`+`scroll wheel`

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
cc @braunjj  and @bengotow  mind taking a look?

**Comment by bengotow** [comment]
Hey folks! This should be updated in v1.3.5, which we're shipping this week. Stay tuned! We added CTRL-wheel as well as a new tooltip explaining it. Shift-wheel will also scroll horizontally on Linux and other platforms that do not support it at the OS-level.

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/14314!
