### ISSUE TITLE
Tags in run tables no longer expand on hover

### ISSUE THREAD

**Issue by adam-bloom** [dagster-io/dagster#14355]
### Dagster version

1.3.4

### What's the issue?

Sometime between 1.2.3 and 1.3.4, tags stopped expanding when hovered over in the runs table. As an example, the k8s tag below used to expand so the full value was visible when hovering over. Now, you need to copy the value to see it.
![image](https://github.com/dagster-io/dagster/assets/3771193/42320d9c-e0f9-46b5-905c-712c0f8b6ddc)

### What did you expect to happen?

I expect a way to see the full value within the table.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
cc @salazarm  or @hellendag  mind taking a look?

**Comment by hellendag** [comment]
@salazarm I believe this is because the tag `label` is no longer a string, but is instead now a `ValueWrapper` child. https://github.com/dagster-io/dagster/blob/5b857046844323f1d62c3079a166ad44afdd72bf/js_modules/dagit/packages/ui/src/components/BaseTag.tsx#L44
