### ISSUE TITLE
dagster-dbt no longer logs output of dbt commands

### ISSUE THREAD

**Issue by adam-bloom** [dagster-io/dagster#14374]
### Dagster version

1.3.4

### What's the issue?

dagster-dbt 0.18.3 emitted logs for dbt output. As an example:

```
Executing command: dbt --no-use-color --log-format json run ...
Running with dbt=1.4.6
Unable to do partial parsing because config vars, config profile, or config target have changed
Unable to do partial parsing because env vars used in profiles.yml have changed
Found 167 models, 718 tests, 0 snapshots, 0 analyses, 594 macros, 0 operations, 0 seed files, 57 sources, 0 exposures, 0 metrics
```
Followed by individual logs as models or tests were run.

In dagster-dbt 0.19.4, these logs are no longer emitted. I get the following, without any of the intermediate output

```
Executing command: dbt --no-use-colors --log-format json run ...
dbt exited with return code 0
```

### What did you expect to happen?

I expect to still get the logs as dbt runs, or at least an option to enable them.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
cc @benpankow  and @rexledesma  closing the loop on the related slack thread
