### ISSUE TITLE
Multi-cursor select doesn't work in Dagit launchpad

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#14409]
### Dagster version

1.3.5

### What's the issue?

if you CMD-click to select multiple cursors in the Dagit launchpad, the cursors disappear once you type a single character.

User says this used to work until a couple of weeks ago in Dagster Cloud

### What did you expect to happen?

Able to type multiple characters with multi-select enabled

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Revert to React 17 made this go away. We'll still need to figure this out in order to get React 18 turned back on.
