### ISSUE TITLE
dagster_slack Hook URL is wrong

### ISSUE THREAD

**Issue by ruotianwang** [dagster-io/dagster#14413]
### Dagster version

1.3.1

### What's the issue?

Our team recently upgrade from 0.15.8 to 1.3.1 and found dagster_slack failure notification link is broken. After some research, I think the issue is dagster_slack hook URL.

Here is the `runs` URL between 0.15.8 and 1.3.1
* 0.15.8: https://github.com/dagster-io/dagster/blob/0.15.8/js_modules/dagit/packages/core/src/app/AppTopNav.tsx#L39
* 1.3.1: https://github.com/dagster-io/dagster/blob/1.3.1/js_modules/dagit/packages/core/src/app/AppTopNav.tsx#L56

Inside 1.3.1, runs URL removed `instance` inside URL path.

However, the latest dagster_slack hook still contains `instance`: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-slack/dagster_slack/hooks.py#L65

### What did you expect to happen?

Fix dagster_slack hook URL format.

### How to reproduce?

Really easy to reproduce..

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @ruotianwang ! Thanks for the report and doing the digging here. I've created a PR that will resolve this issue (and related ones!) here: https://github.com/dagster-io/dagster/pull/14435
