### ISSUE TITLE
Airline demo tutorial needs to be rewritten and folded into docs

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1445]

**Comment by natekupp** [comment]
We should also make sure to rewrite the readme, it still references the previous repo layout

**Comment by natekupp** [comment]
See https://github.com/dagster-io/dagster/tree/master/examples/dagster_examples/airline_demo

**Comment by natekupp** [comment]
See https://dagster.phacility.com/D552

**Comment by mgasner** [comment]
This is done in https://dagster.phacility.com/D755
