### ISSUE TITLE
UI: automatically open the error log when an asset materialized manually fails

### ISSUE THREAD

**Issue by maxcorbeau** [dagster-io/dagster#14487]
### What's the use case?

When I click `materialize selected` on an asset via the Dagit UI and that run fails:
 - I have to click on the run link
 - I then have to click `"View full message"` on the `STEP_FAILURE` to understand why it failed
 - I then have to click `"OK"`
 - Finally I have to go back to the previous page to see the asset diagram again

That's a lot of manual steps which could be avoided

### Ideas of implementation

When I click `materialize selected` on an asset via the Dagit UI and that run fails:
 - Automatically display the full error message in a popup over the diagram view

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Hi! Thanks for requesting this! I'll triage it over to the UI team.

**Comment by hellendag** [comment]
Let's track this in https://github.com/dagster-io/dagster/issues/13325.
