### ISSUE TITLE
Consider not opening pipeline executions in new popups

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1450]
From conversation with @Eronarn:

> I tried executing a pipeline a few times in dagit before I realized that Chrome was blocking a popup. Without the popup, and having missed the blocking notification, there was no feedback about whether it was working.

**Comment by mgasner** [comment]
I'm not sure what we can do about this short of implementing a very complex scheme to communicate to the server that the popup successfully opened.

**Comment by mgasner** [comment]
@schrockn can you make a call on this and close it if we won't implement

**Comment by schrockn** [comment]
I think we could address with the proposed build/run group feature. I.e a new window per build

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by natekupp** [comment]
Given that new runs in the same run group will pop-up in the same window (and redesign of Dagit) - do we still think this is a good idea? cc @schrockn

**Comment by schrockn** [comment]
given run group work i think we should close this

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
