### ISSUE TITLE
Auto-materializing daemon does not work in 1.3.6 (core) / 0.19.6 (libraries) for dbt assets

### ISSUE THREAD

**Issue by mgierada** [dagster-io/dagster#14506]
### Dagster version

dagster, version 1.3.6

### What's the issue?

There seem to be a bug in the latest release of dagster. For some unknown reasons all `dbt` imported assets that implement `AutoMaterializePolicy` and `eager` strategy are not automatically materialised by auto-materializing daemon when upstream changes take place. Instead, dagit shows that those assets have some upstream changes that could be incorporated. However, the API never picks or schedule those assets. I waited several hours but all affected dbt assets were never automatically triggered.

Example screenshot 

<img width="1150" alt="image" src="https://github.com/dagster-io/dagster/assets/23472449/f18eb833-a1fc-45f9-8059-910767532629">

That forced me to revert by PR back to 1.3.5 (core) / 0.19.5 (libraries) which work great by the way

The root cause might be related with the recent changes in `AutoMaterializePolicy` or in `dagster-dbt`.

`Auto-materializing daemon` throw this kind of error:
<img width="1125" alt="image" src="https://github.com/dagster-io/dagster/assets/23472449/803f03ea-3ac4-4b6f-a6cb-baa691567539">

After clicking `materialize all` buttons, the following popup error is presented: 
<img width="1077" alt="image" src="https://github.com/dagster-io/dagster/assets/23472449/866497ec-5a52-46fc-83b8-e16c9f96cb74">

It is also likely that this bug might be broader and not only limited to `dbt` imported assets.

### What did you expect to happen?

All dbt assets that implement `AutoMaterializePolicy` and `eager` strategy  are automatically materialised by auto-materializing daemon when upstream changes take place.

It works in the 1.3.5 (core) / 0.19.5 (libraries)

### How to reproduce?

1. Import any dbt asset using `dagster-dbt`.
2. Make sure this asset has `AutoMaterializePolicy` and `eager` strategy.
3. Add some upstream dependencies to that asset. For the sake of simplicity, it could be a simple software-defined asset.
4. Materialised upstream dependencies
5. Observe that dbt asset is not materialized

I hava a custom wrapper to load dbt assets
```python
def load_dbt_assets(
    io_manager_key: t.Optional[str] = None, selection: t.Optional[str] = None
) -> t.Sequence[AssetsDefinition]:
    """Load dbt assets depending on the environment. If we're running locally, load directly
    from the project. If we're deployed, use the manifest.json generated in the build process.

    We do this because in general we don't want to rebuild the entire manifest.json each time
    we start up a job. Instead, we should be able to build it once and use it going forward.

    The big watch-out-for here is that if we are using the dbt manifest, it will need to be
    regenerated each time we make a change to the dbt models.

    The default behavior can be overridden by setting the USE_DBT_MANIFEST environment variable
    to 1. In that case, we will use the existing manifest even if you are running this locally.

    Args:
        io_manager_key: Resource name corresponding to the IO manager we want to use for outputs.
        selection: Sub-selection of assets in dbt.

    Returns:
        Sequence of defined assets.
    """
    if deployment_description.is_local and not os.getenv("USE_DBT_MANIFEST") == "1":
        return load_assets_from_dbt_project(
            project_dir=get_dbt_path(),
            node_info_to_group_fn=get_dbt_node_group_name,
            node_info_to_auto_materialize_policy_fn=get_auto_materialize_policy_from_dbt_node,
            io_manager_key=io_manager_key,
            select=selection,
        )
    else:
        manifest_location = Path(get_dbt_path()) / "target" / "manifest.json"
        with open(manifest_location, "r") as f:
            return load_assets_from_dbt_manifest(
                manifest_json=json.load(f),
                node_info_to_group_fn=get_dbt_node_group_name,
                node_info_to_auto_materialize_policy_fn=get_auto_materialize_policy_from_dbt_node,
                io_manager_key=io_manager_key,
                select=selection,
            )
```

and a `get_auto_materialize_policy_from_dbt_node` helper function

```python
def get_auto_materialize_policy_from_dbt_node(
    node_info: t.Mapping[str, t.Any]
) -> t.Optional[AutoMaterializePolicy]:
    """Return the auto materialize policy as specified in a dbt model.

    There are only two types of policies: eager and lazy. If the policy is not specified,
    we default to eager. If it is other then eager or lazy, we return None.

    Args:
        node_info (t.Mapping[str, t.Any]): Node details extracted from dbt.

    Returns:
        t.Optional[AutoMaterializePolicy]: Auto materialize policy for the node.
    """
    if auto_materialize_policy := node_info["config"].get("dagster_auto_materialize_policy"):
        if auto_materialize_policy.get("type") == "eager":
            return AutoMaterializePolicy.eager(max_materializations_per_minute=None)
        elif auto_materialize_policy.get("type") == "lazy":
            return AutoMaterializePolicy.lazy(max_materializations_per_minute=None)
        return None
    return AutoMaterializePolicy.eager(max_materializations_per_minute=None)
```

I load all my dbt assets with the following:

```python
cool_dbt_assets = load_dbt_assets(
    io_manager_key="our_warehouse",
    selection="super_dbt*",
)
```

All dbt assets have `eager` `AutoMaterializePolicy`.

### Deployment type

Dagster Cloud

### Deployment details

All packages are using latest versions

### Additional information

It does not work in Dagster Cloud nor localhost through dagster dev.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mgierada** [comment]
Fix coming: https://github.com/dagster-io/dagster/pull/14531

**Comment by rexledesma** [comment]
@OwenKephart I believe this was resolved by https://github.com/dagster-io/dagster/pull/14531?
