### ISSUE TITLE
graph_asset and graph_multi_asset are missing compute_kind argument

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#14513]
### Dagster version

1.3.5

### What's the issue?

The title

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Thanks for reporting @danielgafni, we'll track this in our backlog and fix it when we get the chance.

**Comment by gustavom95** [comment]
Also affected by this issue, are there any workarounds?

**Comment by danielgafni** [comment]
I believe this has been fixed here: https://github.com/dagster-io/dagster/pull/25227

Should be out either in `1.8.13` or in `1.9.0` (our next release)
