### ISSUE TITLE
Add more machine learning compute_kinds (op tags)

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#14511]
### What's the use case?

 From the top of my head:
 - parquet (not ML but is missing)
 - deltalake (same)
 - pytorch-lightning
 - catboost
 - lightgbm
 - xgboost
 - pyboost
 - optuna
 - JAX
 - Ray

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by danielgafni** [comment]
@braunjj hey, tagging you since you helped me out with `polars` last time :)

**Comment by braunjj** [comment]
Thanks for the suggestions @danielgafni! We'll get these added soon.
