### ISSUE TITLE
Refactor unit testing docs section

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1451]
> This section needs work. There's a statement of "So let’s do that. Follow along in the comments:" that doesn't actually lead to any comments. Also, this section isn't written similarly to real-world unit test code. I feel like it would be better to demonstrate this with something like `@pytest.mark.parametrize` to show a more useful test case.

**Comment by schrockn** [comment]
I'm working on testing so I can do this

**Comment by mgasner** [comment]
These docs have been rewritten since this issue was opened.
