### ISSUE TITLE
Preinstall dagster integration images in an AMI for buildkite

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1453]
This would speed up our builds by 45s - 1m on fresh machines.

**Comment by mgasner** [comment]
https://www.packer.io/intro/getting-started/build-image.html

**Comment by mgasner** [comment]
https://programmaticponderings.com/2017/03/06/baking-aws-ami-with-new-docker-ce-using-packer/

**Comment by natekupp** [comment]
https://dagster.phacility.com/D417

**Comment by natekupp** [comment]
Done!

**Comment by natekupp** [comment]
Got ahead of myself here. What I've learned so far:

The legacy buildkite queue is configured to use AMI `ami-0be8cf5e4f1fe0fb1` which was built using the scripts in D417. The AMI is working fine, however we need to remove `"always-pull": True` from the buildkite config; still, getting this from builds despite having pulled the images in the AMI creation:

`Unable to find image 'dagster/buildkite-integration:py3.7.3-v4' locally`

**Comment by natekupp** [comment]
See https://buildkite.com/dagster/dagster/builds/2327#3497dcc3-24cc-4205-a5ca-9db7dac5b182

**Comment by natekupp** [comment]
I did this a while ago, it doesn't speed things up materially - let's look at other options for speeding up tests.
