### ISSUE TITLE
Update to Census Management API results in buggy ops that run syncs

### ISSUE THREAD

**Issue by ldnicolasmay** [dagster-io/dagster#14542]
### Dagster version

1.2.7

### What's the issue?

The Census integration no longer works as expected because Census recently changed its "Management API".

[Here](https://docs.getcensus.com/basics/developers/api/sync-runs#get-sync_runs-id) are the docs where you can see that, in the response `data.status` field, there's a new possible value `"preparing"`.

### What did you expect to happen?

When a Census sync is run, Dagster should poll throughout the `"preparing"` _**and**_ `"working"` status.

However, this new value `"preparing"` is now always returned before the `"working"` value when the API is called. So, the Dagster integration code currently treats it as a finished status and breaks the `while` loop [here](https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-census/dagster_census/resources.py#L151-L176) in the `CensusResource` class's `poll_sync_run` method.

### How to reproduce?

Run any op that starts a valid Census sync run.

### Deployment type

Docker Compose

### Deployment details

N/A

### Additional information

N/A

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Responded on the PR, thanks for adding a fix!
