### ISSUE TITLE
Run failure sensors don't inject pythonic resources

### ISSUE THREAD

**Issue by eavonius** [dagster-io/dagster#14556]
### Dagster version

1.3.6

### What's the issue?

When creating a sensor, I can declare constructor parameters to have pythonic resources injected when that sensor runs.

However when creating a run failure sensor, I get an error trying to do the same.

For example, I have a pythonic resource class called ```DbConnection```.

If I declare this run failure sensor:

```python
@run_failure_sensor(
    name="project_processing_failed_sensor"
)
def project_processing_failed_sensor(
    context: RunFailureSensorContext,
    db_connection: DbConnectionResource):
```

I can enable the sensor, however when a job fails and initiates it - I get this error:

_TypeError: project_processing_failed_sensor() missing 1 required positional argument: 'db_connection_

### What did you expect to happen?

I would expect a run failure sensor to support pythonic resources in the constructor.

### How to reproduce?

1. Create any job that will throw an error and fail when started.
1. Create a pythonic resource class.
1. Create a run failure sensor that takes that pythonic resource class as a parameter.
1. Start dagster (I was testing in dev though my prod environment is on k8).
1. Start the new run failure sensor in the "sensors" area of the UI so it is enabled.
1. Start the job that will fail and wait for it to fail.
1. You should see an error in the logs: 

_TypeError: project_processing_failed_sensor() missing 1 required positional argument: [name of your pythonic resource variable]_

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
@benpankow would you mind taking a look at this?
