### ISSUE TITLE
Option to have auto-materialize policy ignore upstream partition being materialized after downstream partition

### ISSUE THREAD

**Issue by mmutso-boku** [dagster-io/dagster#14550]
### What's the use case?

Hello,

Consider a simplified scenario:

Partitioned Asset A (hourly) -> Partitioned Asset B (hourly) -> Partitioned Asset C (weekly)
Asset A is materialized by a sensor, Asset B and C are in the asset reconciliation sensor

Time goes by, partitions get materialized.

I now need to modify the asset graph so it looks as follow:

Partitioned Asset A (hourly) -> Partitioned Asset D (hourly) -> Partitioned Asset B (daily) -> Partitioned Asset C (weekly)
Asset D is also in the asset reconciliation sensor.

Assets A, B and C have their partitions materialized, but D has no partitions materialized, so we mark the partitions in the past as materialized using a custom job that uses context.log_event(AssetMaterialization(...)). We don't want to actually materialize all the past assets because in the database table the asset represents, they actually exist.

Since Asset D has partitions materialized more recently than B, asset C won't get materialized by the asset reconciliation sensor. It seems like it is expected that everything downstream of Asset D need to be re-materialized after Asset D-s materialization.

It would be very nice to have the option to ignore the "parent has been materialized more recently than child".

### Additional information

Current Dagster version is 1.3.1

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
> It would be very nice to have the option to ignore the "parent has been materialized more recently than child".

Is this a one-time thing? I.e. if partitions of D were later to be re-materialized, would you want the corresponding partitions of B to be auto-materialized after?

**Comment by OwenKephart** [comment]
Hi! Closing this as resolved, as you can now accomplish this with the following:

```python
from dagster import AutoMaterializePolicy, AutoMaterializeRule

my_new_policy = AutoMaterializePolicy.eager().without_rules(
    AutoMaterializeRule.skip_on_parent_outdated(),
)
```

This will disable the check that you're describing.
