### ISSUE TITLE
Implement cp_object in S3ObjectStore

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1455]

**Comment by schrockn** [comment]
we should just implement this... probably not hard https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.copy_object -- @natekupp

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D1259
