### ISSUE TITLE
Importing annotations from __future__ breaks Config

### ISSUE THREAD

**Issue by mjclarke94** [dagster-io/dagster#14571]
### Dagster version

1.3.6

### What's the issue?

We are attempting to create classes which define their own Config structure internally. As such, the model needs to be able to self-reference, which requires that we use `from __future__ import annotations`, but dagster is very much not happy about this!

### What did you expect to happen?

It should be possible to enable forward references (which work fine with Pydantic models) and have them work with `dagster.Config`.

### How to reproduce?

Consider the following:
```
from pydantic import BaseModel
from __future__ import annotations

class Foo(BaseModel):
    num: int
    config: Foo.ModelConfig
    
    class ModelConfig(BaseModel):
        mult: int

    def calculate(self):
        return self.num * self.config.mult
```

This is a valid Pydantic model, where we include the code required to configure the model `Foo` within the definition for Foo. Ideally we'd be able to use the `Foo.BaseModel` as a config directly (maybe a feature request needed!) so external libraries don't need Dagster as a dependency, but we'll adjust accordingly:

```
from dagster import Config, asset
from pydantic import BaseModel
from __future__ import annotations


class Foo(BaseModel):
    num: int
    config: Foo.ModelConfig
    
    class ModelConfig(Config):
        mult: int

    def calculate(self, config):
        return self.num * config.mult
```

Again, all good so far. However when we use this in an asset, we get an error.

```
from dagster import Config, asset
from pydantic import BaseModel
from __future__ import annotations


class Foo(BaseModel):
    num: int
    config: Foo.ModelConfig
    
    class ModelConfig(Config):
        mult: int

    def calculate(self, config):
        return self.num * config.mult
    
@asset
def my_asset(config: Foo.ModelConfig) -> int:
    foo = Foo()
    return foo.calculate(config = config)

___

DagsterInvalidPythonicConfigDefinitionError: 
Error defining Dagster config class.
Unable to resolve config type 'Foo.ModelConfig' to a supported Dagster config type.
```

Ok, let's strip it back to this:

```
from dagster import Config, asset

class ModelConfig(Config):
    mult: int

@asset
def my_asset(config: ModelConfig) -> int:
    foo = Foo()
    return foo.calculate(config = config)
```

This works, but once we enable annotations, we get the same error as before:

```
from dagster import Config, asset
from __future__ import annotations


class ModelConfig(Config):
    mult: int

@asset
def my_asset(config: ModelConfig) -> int:
    foo = Foo()
    return foo.calculate(config = config)

___

DagsterInvalidPythonicConfigDefinitionError: 
Error defining Dagster config class.
Unable to resolve config type 'Foo.ModelConfig' to a supported Dagster config type.

```

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mjclarke94** [comment]
A note on this, I think if you limit the scope of the annotations import to a file where you aren't using Dagster it works. 

I'm not sure if we're asking for bugs by using multiple inheritance to get around not having `dagster` and `__future__.annotations` being imported in the same scope...assuming someone can confirm that this isn't a major anti-pattern then here's a workaround in the interim!

_test.py_
```
from __future__ import annotations
from pydantic import BaseModel, Field

class Test(BaseModel):
    class ModelConfig(BaseModel):
        foo: str = "bar"

    a: int = 1
    b: Test.ModelConfig = Field(default_factory = lambda: ModelConfig())
```
_main.py_
```
from test import Test
from dagster import asset, Config

class DagConf(Test.ModelConfig, Config): pass

@asset
def foo(config: DagConf): pass
```

**Comment by smackesey** [comment]
cc @benpankow this is the same issue I discovered independently and DMed you about

**Comment by smackesey** [comment]
@mjclarke94 thanks for the report, I have a PR that should fix this. If you want to understand what is going on I recommend reading the full OP for #14675 (you already commented but I since updated the OP with an explanation).
