### ISSUE TITLE
Launchpad for non-partitioned asset shows dynamic partition

### ISSUE THREAD

**Issue by slopp** [dagster-io/dagster#14579]
### Dagster version

1.3.7

### What's the issue?

If you "shift+click" materialize on an asset that does not have any partitions, and your asset graph also has a dynamic partitioned asset, then the launchpad shows partitions for the dynamic partitioned asset:

To reproduce:

1. On the hooli global asset graph select any non-partitioned asset: https://hooli.dagster.cloud/data-eng-prod/asset-groups/ANALYTICS%2Fcompany_perf
2. Shift click Materialize for that asset
3. Note the incorrect partitions

![Screen Shot 2023-06-01 at 2 32 54 PM](https://github.com/dagster-io/dagster/assets/15901072/3c2a0dbe-9f6a-4f04-8dbb-c4be606b9d26)

A few other things to note:

 - I had enabled "automatically scaffold default config"
 - The default config button is still available, which is odd
 - The remove config button is not available?
 - The scaffolded config is for all ops, even though my asset selection only requires one op. I would have expected just the one op's config to be shown

The partitions shown are for the op keep product deep dive

If, instead, I select a time partitioned asset, the correct partition option is shown

### What did you expect to happen?

The launchpad should show the config for the op associated with the selected asset and should show the partitions for the selected asset. If the selected asset is not partitioned, then no partitions should be available to select.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jeanineharb** [comment]
Any updates on this? Encountering the same problem: when attempting to materialize non-partitioned assets, the launchpad asks for the partitioning scheme coming from a different asset group...

**Comment by theelderbeever** [comment]
Still an issue on Dagster 1.6.8. Is progress being made on this?

**Comment by salazarm** [comment]
Fix will go out in the release this week. Sorry for the long wait!
