### ISSUE TITLE
Add `compute_kind` to AssetOut

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#14595]
### What's the use case?

This would allow specifying the compute kind for `multi_asset`s. Right now it's only possible to provide it to `multi_asset` itself. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by danielgafni** [comment]
Yes. For example, I might have a multi_asset which creates a trained model (PyTorch) and fitted scalers/encoders (scikit-learn).

**Comment by sryza** [comment]
Now that we have `kinds` on `AssetSpec`, I think we can close this.
