### ISSUE TITLE
Write up coherent summary of pipeline init process.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1461]
It's complicated. Worth writing up

**Comment by mgasner** [comment]
cc @catherinewu

**Comment by catherinewu** [comment]
fyi @yuhan to get on your radar

**Comment by alangenfeld** [comment]
this is in flux while we work towards being able to orchestrate runs from a host process

**Comment by erinkcochran87** [comment]
@schrockn @alangenfeld Is this guy worth keeping open?
