### ISSUE TITLE
Dagstermill missing page in documentation

### ISSUE THREAD

**Issue by EtienneT** [dagster-io/dagster#14611]
### What's the issue or suggestion?

The tutorial for dagstermill is not found: https://docs.dagster.io/integrations/dagstermill/using-notebooks-with-dagster

### Additional information

It was working in earlier versions.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@yuhan @erinkcochran87 – this looks like one of those situations where a docs page mysteriously 404s.

**Comment by erinkcochran87** [comment]
Thanks @sryza!

Thanks for the report @EtienneT - I found the issue and opened a PR for it (#14639). This will be fixed in this week's release.
