### ISSUE TITLE
Selector for strings without nesting

### ISSUE THREAD

**Issue by balavins** [dagster-io/dagster#14629]
### What's the use case?

I would like the Launchpad UI to be able to have Selectors but without having to be nested.
For example
```
config: {
  "Mode": Selector("Local","Distributed")
}
```
Current Selector API is 
dagster.Selector(fields, description=None)[[source]](https://docs.dagster.io/_modules/dagster/_config/field_utils#Selector)[¶](https://docs.dagster.io/_apidocs/config#dagster.Selector)
Where fields is (Dict[str, [Field](https://docs.dagster.io/_apidocs/config#dagster.Field)])
I would like Selector to be just choosing between strings

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @balavins - you can use an enum for this: https://docs.dagster.io/_apidocs/config#dagster.Enum.

Feel free to reopen if I'm misunderstanding what you're looking for.
