### ISSUE TITLE
Rethink & untangle example dependencies

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1463]
dagster-aws, dagster-spark, and dagster-snowflake shouldn't be requirements
for running dagit in the examples folder -- this is too heavy

**Comment by natekupp** [comment]
Maybe the easiest solution is to make any integration deps optional and use square-bracket syntax to install?

**Comment by mgasner** [comment]
Was: Running dagit for the examples repository requires too many dependencies

**Comment by mgasner** [comment]
https://dagster.phacility.com/D2215#inline-13362

**Comment by catherinewu** [comment]
closing since examples folder has separate dependencies per example now
