### ISSUE TITLE
Cancelled backfill runs cannot be re-run from the backfill page

### ISSUE THREAD

**Issue by nathan-calandra-simplisafe** [dagster-io/dagster#14646]
### Dagster version

dagster, version 1.3.7

### What's the issue?

If a pending backfill run was cancelled, it can no longer be resubmitted from the backfill page.  In the example below, I should be able to submit 4 runs, but the UI only let's me submit one.  The difference is that the one run failed and the others were cancelled.

#### Backfill Page
![image](https://github.com/dagster-io/dagster/assets/121573154/cc1ecd05-3196-46b7-af70-872bfb4cbd50)

#### Jobs from the cancelled backfill
![image](https://github.com/dagster-io/dagster/assets/121573154/e670d27e-205e-4978-a25f-37b5cb6ebe84)

### What did you expect to happen?

I should be able to submit backfills for cancelled jobs.  Either with a separate checkbox or as part of the "Failed" group.

### How to reproduce?

1. Setup a simple partitioned job
2. Start a backfill, but cancel the runs it before they all complete
3. Try to backfill again, but notice that the cancelled jobs cannot be selected

### Deployment type

Dagster Helm chart

### Deployment details

I've seen this in local development as well as deployed via a Helm chart on EKS.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @nathan-calandra-simplisafe - did the partitions that had canceled runs have prior successful runs?  If so, those partitions are considered "Completed".  If you check the "Completed" box, then they'll be included in the backfill.

**Comment by nathan-calandra-simplisafe** [comment]
@sryza In this case they did, but it still doesn't work.  If I check the "completed" box it submits 5/30 and 6/4.  I am unable to submit 6/1 -> 6/3

**Comment by sryza** [comment]
Got it - that does sound like a bug

**Comment by bengotow** [comment]
Hey folks, I was able to reproduce this today and will get a PR up with a fix. I think ideally a cancelled run would  "not count" for the purposes of the health bars and checkboxes on this page, and we'd show the status from the run previous to that one (missing, failed or completed).

<img width="937" alt="image" src="https://github.com/dagster-io/dagster/assets/1037212/348903e6-3188-410a-963f-c4b3ba923cf5">
