### ISSUE TITLE
Display all provenance information. Do not hide behind "and N more..."

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#14654]
### What's the use case?

We have useful provenance information but we hide it sometimes in the UI, with no way of viewing it.

Here's an example from our own system:

![Screen Shot 2023-06-06 at 3 53 24 PM](https://github.com/dagster-io/dagster/assets/28738937/6b781141-cd31-49ba-839b-61401bc49b73)

This is frustrating because it is often that missing piece of information that is necessary for debugging and understandability. Furthermore there is no way to expand this.

We should display all this information somewhere if someone needs it.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by schrockn** [comment]
Folks at Enigma explicitly asked for this as well.

**Comment by bengotow** [comment]
Hmm @braunjj I wonder if we could switch this from a tooltip to a modal-on-click. I think this makes sense but I've also seen it show a lot of data, might need to scroll to show them all.

**Comment by bengotow** [comment]
We discussed this in our sync and I'm putting together a fix that will use this component, which keeps the popover but allows you to scroll within it, viewing a potentially long list of provenance items. PR incoming!

![image](https://github.com/dagster-io/dagster/assets/1037212/e08fdc84-4c67-4e92-9b41-08d4020ab14d)
