### ISSUE TITLE
Snapshot Id out of sync error when backfilling asset

### ISSUE THREAD

**Issue by gustavo-delfosim** [dagster-io/dagster#14663]
### Dagster version

1.3.7

### What's the issue?

I received an error when backfilling an asset in Dagit. The error was:
```
dagster._check.CheckError: Invariant failed. Description: Parent pipeline snapshot id out of sync with passed parent pipeline snapshot
```
I suspect the error is related to having a `dict[int,int]` in the asset's `metadata`, i.e.:
```py
@asset(
    ...,
    metadata={
        "my_problematic_metadata": {
            1: 10,
            2: 20
        },
    }
)
```

The error started happening after I swapped keys and values in my `dict[int, int]`.

### What did you expect to happen?

I expected the backfill to run normally.

### How to reproduce?

I could not isolate and reproduce it.
The problematic `asset` is defined as follows:
```py
    # Example Data, I can share the actual data if needed
    pontoId_mapping = {
        1: 10,
        2: 20,
    }
  
    ...
    
    @asset(
        name="Way2_ETL",
        description=description or "Way2 ETL",
        partitions_def=partitions_def, 
        compute_kind="Way2 API",
        key_prefix=key_prefix,
        required_resource_keys={
            way2_api_connector_key,
            sqlalchemy_engine_key,
        },
        metadata={
            "scada_id": scada_id,
            "pontoId_mapping": {str(k): v for k, v in pontoId_mapping.items()},
            # "pontoId_mapping": pontoId_mapping,
            "grandezas_mapping": grandezas_mapping,
            "resource_key_mapping": {
                "way2_api_connector_key": way2_api_connector_key,
                "sqlalchemy_engine_key": sqlalchemy_engine_key,
            },
        },
    )
    def way2_etl(context: OpExecutionContext):
        ...
        
   # partition_def is a MultiPartitionsDefinition, 
   # combining a TimeWindowPartitionsDefinition and a StaticPartitionsDefinition
```
The code above works well. However, if I comment the `pontoId_mapping` key on the `metadata` dict  whose value is being parsed to a `dict[str, int]` for the unparsed one, I get the error.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yeetfield** [comment]
Hi @alangenfeld, it seems like your link isn't working.

**Comment by gutswright** [comment]
What has solved this issue for me is going to the hosted dagster instance under 'Deployment' > 'Code Locations' Click on 'Reload' (or 'Reload all') to pull from the most recent Docker image and this enables me to materialize multiple times manually from different devices.
