### ISSUE TITLE
"Upstream materializations missing" when downstream of partitioned source asset

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#14662]
> I have a daily partitioned observable source asset with a snowflake io manager, and downstream of that I have a self-dependent asset events_table with the partition mapping described above. When I go to materialise the events_table, it warns me that some upstream materialisations are missing

https://dagster.slack.com/archives/C04EKVBA69Y/p1686092525315599?thread_ts=1685986923.128199&cid=C04EKVBA69Y

**Comment by bengotow** [comment]
Hmm I believe this was fixed, but I still have the repro case locally. Will investigate and see what's up.

**Comment by mjclarke94** [comment]
Also, I just actually read the PR code and now see the distinction between source and observable source wasn't relevant. Apologies!

**Comment by sryza** [comment]
@mjclarke94 we've actually got a separate issue already to track the self-dependency problem: https://github.com/dagster-io/dagster/issues/13896

**Comment by mjclarke94** [comment]
@sryza Ah, right you are. Apologies for the cross-talk!
