### ISSUE TITLE
`parameters` tag for the injected cell is too general, use something less likely to collide

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1468]

**Comment by mgasner** [comment]
There are a number of other possible collisions. We `import json`, which could mess up notebooks using, e.g., mujson

**Comment by natekupp** [comment]
Punting from 0.5.0 - @mgasner please shout if it should stay

**Comment by catherinewu** [comment]
@mgasner could you add more details here or should we close this issue?

**Comment by schrockn** [comment]
This is a constraint of papermill, not us, so I think we should close. See https://papermill.readthedocs.io/en/latest/usage-parameterize.html

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by catherinewu** [comment]
closing issue per nick's suggestion
