### ISSUE TITLE
Relax Constraints on Alembic Pin

### ISSUE THREAD

**Issue by cwe5590** [dagster-io/dagster#14708]
### What's the use case?

It would be helpful to relax the constraints on Alembic to reduce dependency conflicts.

A dependency conflict I'm running into: 

```
    meltano 2.19.1 depends on alembic<2.0.0 and >=1.11.1
    dagster 1.3.8 depends on alembic!=1.6.3, !=1.7.0, <1.11.0 and >=1.2.1
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@jmsanders I saw you did the latest pin. Seeing that Meltano depends on >= 1.11.1 makes me think that maybe 1.11.0 had bugs that are fixed in later versions. Thoughts?

**Comment by prha** [comment]
Yeah, this was resolved here: https://alembic.sqlalchemy.org/en/latest/changelog.html#change-1.11.1

**Comment by prha** [comment]
This went out in `1.3.10`
