### ISSUE TITLE
Intersection of partitioned assets?

### ISSUE THREAD

**Issue by DrawnWren** [dagster-io/dagster#14730]
### What's the use case?

I frequently have different `TimeWindowPartition`ed assets which share the same partition except for their start date. Would it be possible to add a feature to run on i.e. the intersection of these time windows for a simple job?

i.e.: 
```
asset_1 : Daily, starting 2021-09-24 Etc/UTC. End offsetted by -1 partitions.
asset_2 : Daily, starting 2019-09-10 Etc/UTC. End offsetted by -1 partitions.
asset_3 : Daily, starting 2019-04-30 Etc/UTC. End offsetted by -1 partitions.
```
and the feature request would allow me to schedule a job which selects only daily, starting 2021-09-24.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
This looks related to https://github.com/dagster-io/dagster/issues/12298

**Comment by DrawnWren** [comment]
Yep, it's the same issue. Should I close this one?

**Comment by sryza** [comment]
@DrawnWren got it - I'm going to close this one and link it from there.
