### ISSUE TITLE
AutoMaterializePolicy.lazy should wait for Freshness policy trigger for assets that are missing materialization

### ISSUE THREAD

**Issue by nixent** [dagster-io/dagster#14744]
### What's the use case?

When Auto-materialize daemon starts for assets with lazy policy, it picks missing assets and starts materialization. For Prod environment it results in full load of all assets initiated in same time, while in normal operations materializations would be spread in time according to their Freshness policies. In Dev/Test environments developers often need to test handful of models and don't need full set of models, deferring missing assets materialization until their Freshness policy would allow tests based on Freshness policy without having materializations for all missing assets.

It is possible to define custom `AutoMaterializationPolicy` with `on_missing = false`, however for dbt scenario, it would be nice to control it in the dbt config, which supports two types: lazy and eager

### Ideas of implementation

Freshness policy evaluation can be based on Daemon start time. If asset is not materialized yet, Daemon start time is the reference point for calculation of the asset freshness.
Example:
DAG: A->B->C
Asset A is materialized manually, B and C are missing. C has freshness policy of 1h.
When daemon starts it should wait for 1h and trigger materializations of A->B->C

Maybe making additional "super-lazy" type for dagster-dbt with `on_missing = false` is the easiest way to achieve it

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
If I understand correctly, the request is to be able to have dbt assets with lazy auto-materialize policies and avoid materializing missing assets?

It sounds like there are a couple gaps here in what we have:
- In Python, we don't have a blessed way of setting `on_missing=False`. You can do it with the `AutoMaterializePolicy` constructor, but we currently discourage the use of that constructor.
  - So we should probably just add it as a parameter to the `lazy` and `eager` methods.
- In dbt, we don't have an easy way of setting `on_missing=False`. You can do it with the `node_info_to_auto_materialize_policy_fn` on `load_assets_from_dbt_manifest`, but that's a pain.
  - We should probably have a way of specifying it in dbt config that uses the same terms (e.g. "on_missing") that are used with the Python API.

cc @OwenKephart

**Comment by nixent** [comment]
It boils down to definition of "**lazy**" AutoMaterializationPolicy, my understanding of "lazy" is "do as little as possible, do nothing until it is really necessary", with `on_missing=True`, that is not the case.
`lazy()` is defined as 
```
AutoMaterializePolicy(
            on_missing=True,
            on_new_parent_data=False,
            for_freshness=True,
```
Providing parameters to control each of the constructor parameters makes it more flexible but adds complexity. I'd propose to change definition of "lazy" policy to:
```
AutoMaterializePolicy(
            on_missing=False,
            on_new_parent_data=False,
            for_freshness=True
```

effectively making it replacement for freshness sensor. For scenarios with `on_missing=True`  `eager` policy fits much better.
For cases where missing assets should be materialized right away, I'd suggest to introduce another policy type, something like "determined" to replace current definition of lazy policy.

**Comment by sryza** [comment]
I would expect a lazy auto-materialize policy to materialize a missing asset or missing partition in the case that a materialization of the asset or partition is needed in order to satisfy a freshness policy.

@nixent - would you agree?

@nixent - if I understand what you're saying, a lazy auto-materialize policy will materialize a missing asset even if it's not needed to satisfy a freshness policy?

**Comment by nixent** [comment]
> I would expect a lazy auto-materialize policy to materialize a missing asset or missing partition in the case that a materialization of the asset or partition is needed in order to satisfy a freshness policy.
> 
> @nixent - would you agree?
> 
Yes

> @nixent - if I understand what you're saying, a lazy auto-materialize policy will materialize a missing asset even if it's not needed to satisfy a freshness policy?
>
Yes. In the current implementation of freshness calculation, missing asset is considered to be infinitely out of date. I'd suggest using Auto-materialize daemon start time as reference point for freshness calculation.

Please check this [Slack discussion](https://dagster.slack.com/archives/C04CW71AGBW/p1686047768337559) about this issue.

**Comment by sryza** [comment]
> Yes. In the current implementation of freshness calculation, missing asset is considered to be infinitely out of date. I'd suggest using Auto-materialize daemon start time as reference point for freshness calculation.

The way we've been looking at it is that, for an asset to be fresh, all its upstream assets need to be materialized. So no matter when the auto-materialize daemon was started, if an upstream asset isn't materialized, then the downstream asset will be overdue, which the asset daemon aims to address.

We've tried to avoid including the daemon start time as part of the auto-materialize behavior, because it makes the behavior more path-dependent and adds a variable that needs to be incorporated whenever someone is reasoning about auto-materialize.

**Comment by nixent** [comment]
The logic with materializing upstream assets to meet freshness policy for downstream assets makes total sense to me. The question is what should be used as a starting point for freshness calculation in case of missing assets that don't have policy attached to them or their downstream assets?

Both, `lazy` and `eager` policies have ```on_missing=True```. What was the reason for having parameter to control missing assets?

**Comment by sryza** [comment]
I just merged in a change that sets `on_missing` to `False` for lazy assets.

**Comment by sryza** [comment]
(which this thread has convinced me is the correct behavior)
