### ISSUE TITLE
ConfigurableResource does not work with sensor since version 1.3.8

### ISSUE THREAD

**Issue by mqq-marek** [dagster-io/dagster#14753]
### Dagster version

1.3.8

### What's the issue?

Does not accept ConfigurableResource parameter in sensor. like:

         class MongoResource(ConfigurableResource):
                pass

          @sensor(job=simple_job)
          def is_job_created(
              context: SensorEvaluationContext,
              mongo: MongoResource,
          )

### What did you expect to happen?

Expected behavior: sensor definition accpets ConfigurableResource parameter and work like in earlier Dagster version

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@benpankow recently merged a fix for this, which will be included in our next release
