### ISSUE TITLE
[Docs] GCSComputeLogManager docs show example of AzureBlobComputeLogManager usage

### ISSUE THREAD

**Issue by seanabraham** [dagster-io/dagster#14765]
### What's the issue or suggestion?

I think this is just a simple oversight — the docs for the usage of GCSComputeLogManager are actually a copy-pasta of the section above on AzureBlobComputeLogManager, so there are no examples of how to configure GCSComputeLogManager.

### Additional information

Incorrect docs can be seen here: https://github.com/dagster-io/dagster/blob/c24a16aac0c5b64d4cc96bb6665fb1eb6cf3f46a/docs/content/deployment/dagster-instance.mdx?plain=1#L617-L650

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
Hey @seanabraham! Thanks for pointing this out. It was addressed in https://github.com/dagster-io/dagster/pull/15803, so I'm gonna close this out.
