### ISSUE TITLE
`AssetSelection.from_coercible` accepts a Sequence but fails check for non-list sequence

### ISSUE THREAD

**Issue by ndellosa95** [dagster-io/dagster#14772]
### Dagster version

1.3.9

### What's the issue?

Type alias `CoercibleToAssetSelection` takes either a string or a Sequence of various things it can coerce to assets. However, the check [here](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/asset_selection.py#L273-L301) only actually passes for lists. 

### What did you expect to happen?

Either add a check for non-list sequences or change the type hint to only accept lists.

### How to reproduce?

Try passing a tuple to `AssetSelection.from_coercible`.

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @ndellosa95 ! Thanks for the report -- just merged in a fix
