### ISSUE TITLE
Auto-materializing assets works incorrectly with dbt assets

### ISSUE THREAD

**Issue by pufffikk** [dagster-io/dagster#14809]
### Dagster version

dagster, version 1.3.9 

### What's the issue?

I am trying to use Auto-Materializing with dbt models, but it works very strange. It runs the same asset materialization many times every 30 seconds and I have a lot of the same runs in the same time. The same behavior if used build_asset_reconciliation_sensor. [ Slack thread](https://dagster.slack.com/archives/C01U954MEER/p1686677002506089)
where I provide screenshots how it looks like. In version 1.2.2 there are no such problems with build_asset_reconciliation_sensor, probably with Auto-Materializing too.

### What did you expect to happen?

Expect that Auto-Materialization will run only by cron_schedule.

### How to reproduce?

**dbt_project.yaml**- part with configuration models
```yaml
models:
  project:
    mmm:
      +materialized: view
      +view_security: invoker
      +dagster_auto_materialize_policy:
        type: eager
```

**mmm_non_media_metrics.sql - config part**
```
{{ config(
    materialized='incremental',
    unique_key=['date'],
    properties={
        "partitioned_by": "ARRAY['date']",
    },
    dagster_freshness_policy={
        "maximum_lag_minutes": 195,
        "cron_schedule": "15 5 * * *"
    }
) }}

-- set default min_date
{% set min_date = '2019-01-01' %}

{% if is_incremental() %}
  -- overwrite default min_date
  {% set min_date = run_query('SELECT max(date) - INTERVAL \'7\' DAY FROM ' ~ this).columns[0].values()[0] %}
{% endif %}

{% set date_filer = 'date >= DATE(\'' ~ min_date ~ '\') - INTERVAL \'1\' DAY' %}
```

**repo.py**
```python
dbt_project = os.getenv("DBT_PROJECT")
dbt_profiles = os.getenv("DBT_PROFILES")


def make_slack():
    return WebClient(os.getenv('ALERT_SLACK_TOKEN'))


slack = ResourceDefinition(make_slack)
resources = {
    "dbt": dbt_cli_resource.configured(
        {
            "project_dir": dbt_project,
            "profiles_dir": dbt_profiles,
        }
    ),
    "slack": slack
}

def build_runtime_metadata(_, node_info):
    return dict(affected_table=node_info["relation_name"])


dbt_assets = load_assets_from_dbt_project(
    project_dir=dbt_project,
    profiles_dir=dbt_profiles,
    key_prefix=["project"],
    source_key_prefix=["sources"],
    runtime_metadata_fn=build_runtime_metadata,
    use_build_command=True,
)

defs = Definitions(
    assets=dbt_assets,
    resources=resources)
```

requirements.txt
```
dagster==1.3.9
dagster-dbt
dagster-postgres
dagster-k8s
dagster-slack
dagster-graphql
dbt-core==1.4.0
dbt-trino
acryl-datahub==0.9.6.2
acryl-datahub[dbt]==0.9.6.2
sqlalchemy<2.0.0
pylint==2.15.5
```

### Deployment type

Other Docker-based deployment

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Thanks for the report! Looking into this behavior.

**Comment by pufffikk** [comment]
@OwenKephart we tried with the newest version of dagster 1.3.11 and dbt 1.5.2, but the behavior still the same.

**Comment by OwenKephart** [comment]
@pufffikk Hi, sorry for the delay on this, I've been failing to replicate this behavior and it's somewhat hard to imagine what might be going on here.

Some extra info that might help:

- With AutoMaterializePolicies, you should be able to go to the Asset Details page of the asset that's getting rematerialized and see the reasons that the system decided to materialize it (this will be under the Auto-materialize history tab). What do you see here?
- Do you have many other runs executing at the same time? Or is it mostly just the ones for this asset?
- In your screenshot, what type of assets are upstream of `mmm_web_purchases/sessions`? Are they more dbt models, or are they dbt sources?
