### ISSUE TITLE
UI Bug: Wrong linkage of Ops in waterfall view when retry is triggered

### ISSUE THREAD

**Issue by karzuo** [dagster-io/dagster#14827]
### Dagster version

1.3.9

### What's the issue?

Dagster is showing a wrong and misleading view of the data lineage in waterfall view when a retry has been triggered in the Ops.

This is the correct view for Flat view:
![image](https://github.com/dagster-io/dagster/assets/2015748/e9587a21-cd1c-4399-940c-6071e2606841)

This is what is shown for waterfall view:
![image](https://github.com/dagster-io/dagster/assets/2015748/20cfe43b-6ffd-4d43-bcf2-5f9850ba07c2)

### What did you expect to happen?

For the example pipeline above, `load_data` happens only after `extract_delta` runs successfully. While the flat view shows this sequence correctly, the waterfall view gave a false alarm that the pipeline sequence was screwed up. The pipeline execution order was correct (extract_delta (failure 1), extract_delta (failure 2), extract_delta (success), load_data).

### How to reproduce?

1. Create a job with 2 ops that depend on each other. i.e Op A must run first before Op B.
2. Add retry mechanism.
3. Run the pipeline with Op A failing first time and run successfully upon retry.

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by salazarm** [comment]
@bengotow Correct me if I'm wrong but I believe you fixed this recently?

**Comment by bengotow** [comment]
I was able to reproduce this against latest `main` using the following graph:

```
@op(retry_policy=RetryPolicy(max_retries=3, delay=5))
def aop():
    if random() > 0.5:
        raise 'fail!'
    return 2

@op()
def bop(aop):
    return aop * 2

@job
def test_job():
    part = aop()
    bop(part)
```

Will investigate! Thanks for reporting this @karzuo.

<img width="703" alt="image" src="https://github.com/dagster-io/dagster/assets/1037212/0e85003d-4519-45b1-a371-162cdfdf9f58">
