### ISSUE TITLE
When materializing an asset from the global view, the implicit asset job will be used instead of a defined one

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#14820]
### Dagster version

1.3.9

### What's the issue?

```python
from dagster import (
    AssetSelection,
    DailyPartitionsDefinition,
    Definitions,
    asset,
    define_asset_job,
)

pda = DailyPartitionsDefinition(start_date="2023-05-01")
pdb = DailyPartitionsDefinition(start_date="2023-05-02")


@asset(partitions_def=pda)
def a():
    return 1


@asset(partitions_def=pdb)
def b():
    return 1


@asset(partitions_def=pda)
def aa():
    pass


@asset(partitions_def=pdb)
def bb():
    pass


defs = Definitions(
    assets=[a, b, aa, bb],
    jobs=[define_asset_job("aaa", selection=AssetSelection.assets(a, aa), tags={"foo": "bar"})],
)

```

Take the above repo and go to the global lineage view in dagit. Launch a run for "a" or "aa" (or both).

Expectation: a run of the job "aaa" will be kicked off.

Reality: a run of the implicit asset job "__ASSET_JOB" will be kicked off.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
This is the expected behavior, no?

**Comment by OwenKephart** [comment]
Turns out this is how things have always been
