### ISSUE TITLE
Support Dagster sensors that take longer than 60 seconds to execute

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#14830]
### What's the issue or suggestion?

Today dagster sensors time out if the sensor execution function takes more than 60 seconds to run. It's not uncommon for sensors that need to iterate over large quantities of data or slower APIs to hit into the limit, and the recommended workaround of breaking work up into chunks using cursors is not always feasible.

In the short term, we could increase the default timeout to something higher. In the longer term, we could investigate ways to make sensors that can run continually with no limit.

Doing either will likely require resolving https://github.com/dagster-io/dagster/issues/14523.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ssingh13-rms** [comment]
This will be an amazing addition!

**Comment by astronautas** [comment]
Up! 🙏
