### ISSUE TITLE
When sensor targets `asset_selection`, don't show `__ASSET_JOB` in UI

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#14844]
Here's a sensor that targets an `asset_selection`:

```python
from dagster import sensor, AssetSelection, Definitions, asset


@sensor(asset_selection=AssetSelection.keys("asset1"))
def sensor1():
    ...


@asset
def asset1():
    ...


defs = Definitions(sensors=[sensor1], assets=[asset1])
```

When you look at this in the UI, you see:

<img width="604" alt="image" src="https://github.com/dagster-io/dagster/assets/654855/da4fc709-d23d-446d-a757-4c30c2fa79d6">

and

<img width="373" alt="image" src="https://github.com/dagster-io/dagster/assets/654855/3bccb8f2-38f5-4ac2-95c1-341bbda0b037">

We would ideally show the selection in the UI. If that information isn't available to the frontend, just showing the text "selection of assets" would be an improvement over the status quo.

**Comment by sryza** [comment]
@yuhan - FYI, because you're currently working on extending this to schedules.

**Comment by bengotow** [comment]
Hmm, I was thinking we might be able to do something about this because Sensors have a `metadata.assetKeys`, and we render that in the UI already if it's present (as `Monitored assets`),  but it looks like that's for a separate asset sensor feature where the assets are under observation and not the sensor target. This may not be something we can tackle in the UI/UX bucket until @yuhan has taken a pass at it!

**Comment by sryza** [comment]
@yuhan - is this something that you think you might get to soon?

If not, then I think it would still be an improvement to say "A selection of assets", instead of the current obtuse `__ASSET_JOB`

**Comment by danielgafni** [comment]
It would be great to get rid of `__ASSET_JOB` in general. 
I wonder if we could have unique job names based on the asset selection or something like this.

**Comment by yuhan** [comment]
hey sorry totally missed the pings. here's the pr for the schedule implementation: https://github.com/dagster-io/dagster/pull/15348

**Comment by yuhan** [comment]
hey sorry totally missed the pings. here's the pr for the schedule implementation: https://github.com/dagster-io/dagster/pull/15348 @bengotow @sryza - are tracking the schedule UI changes separately?
