### ISSUE TITLE
make it easier to specify a dbt asset as an upstream dependency of a non-dbt asset

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#14846]
Having a non-dbt asset depend on a dbt asset can be finicky. You have to make sure that the asset key included on the downstream asset matches the asset key that's generated for the dbt model when you load it into Dagster.

We could make it possible to just reference the model directly, which removes this finnicky-ness:

```python
manifest = DbtManifest(...)

@dbt_assets(manifest=manifest)
def my_dbt_assets():
    ...

@asset(non_argument_deps={manifest.get_asset_key_for_model(model_name="orders")})
def downstream_python_asset():
    ...
```

**Comment by rexledesma** [comment]
@clairelin135 resolved this by implementing https://github.com/dagster-io/dagster/pull/14933 and https://github.com/dagster-io/dagster/pull/14932, and we're tracking https://github.com/dagster-io/dagster/discussions/14964 for feedback on these APIs.
