### ISSUE TITLE
Include option to not log shell command in execute_shell_command fn

### ISSUE THREAD

**Issue by yusufshalaby** [dagster-io/dagster#14854]
### What's the use case?

Currently the `execute_shell_command` function in `dagster-shell` logs the the command itself. I have a use case where I am running a command that uses secrets to connect to an API. It would be great if I had an option to toggle this log or to somehow indicate parts of the command that should be hidden.

### Ideas of implementation

Parameter in the `execute_shell_command` to log the command or not.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by JoeNaso** [comment]
+1 to this. I just noticed in issue in a project I am working on - inadvertently logging credentials

**Comment by PedramNavid** [comment]
Thanks @JoeNaso and @yusufshalaby, created #18139 to resolve this.
