### ISSUE TITLE
Introduce `AssetExecutionContext`

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#14871]
### What's the use case?

Currently, the context object on assets is typed as `OpExecutionContext` which exposes unnecessary implementation details. So, we'd like to introduce an `AssetExecutionContext` which likely would be a subtype to `OpExecutionContext` and expose only the fields that make sense to asset land.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yuhan** [comment]
created this issue for tracking.

relevant prs:
- https://github.com/dagster-io/dagster/pull/14792
- https://github.com/dagster-io/dagster/pull/14822

**Comment by alangenfeld** [comment]
likely need to add `build_asset_context`

**Comment by sryza** [comment]
Are we ready to close this as completed?
