### ISSUE TITLE
[UI] Steps are misaligned for running job

### ISSUE THREAD

**Issue by salazarm** [dagster-io/dagster#14898]
In the "Timed view" of a running job, all the DynamicOuts are left-aligned together, even though some of them start/finish execution later. Also the black start/end brackets for the selected step aren't aligned with the actual selected step.

![image](https://github.com/dagster-io/dagster/assets/2286579/495177f5-5701-4392-adf8-e3fa67df9c46)

**Comment by bengotow** [comment]
Followed up with the user in the Dagster support slack here: https://dagster.slack.com/archives/C01U954MEER/p1686763220313229, haven't been able to track this down yet but I think my repro case may be insufficient in some way.
