### ISSUE TITLE
make auto-materialize respect data versions on materializable assets

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#14893]
There are some cases where auto-materialize will materialize an asset even if the UI does not list it as having new upstream data: a parent asset was materialized with a data version that's the same as the data version of the materialization used by the latest materialization of the child asset.

This can happen when:
- The user provides the same runtime data version for both materializations of the parent asset
- The code version and the upstream data have not changed between materializations of the parent asset

**Comment by OwenKephart** [comment]
As of now, whenever an upstream asset/partition is materialized for an asset with an AutoMaterializePolicy.eager(), we will launch a run of the downstream, regardless of if that upstream asset/partition has a new data version or not. We do however take into account versioning information for observable source assets.

The fact that we don't always take versioning into account is surprising, as we have the tools necessary to determine that no new run is necessary, but do not use them. This has historically been for performance reasons, but this may be less of a concern as of recently.

We should remove this limitation as soon as practical.

**Comment by tha23rd** [comment]
@OwenKephart Any thoughts on when this one might get picked up?

**Comment by OwenKephart** [comment]
@tha23rd Currently investigating the work that would be required to make this work. On the auto-materialize side, there's essentially nothing to be done, but when we store asset materialization events from partitioned assets, we don't actually store the versioning information that we need (essentially, the versions of all the input assets) at the moment. Hopefully, this will be a small lift.

**Comment by tha23rd** [comment]
@OwenKephart got it!

For my own knowledge, when I navigate to the "events" tab of an asset, I see that each event includes versioning information under "system tags". Is what you're describing separate from that?

**Comment by OwenKephart** [comment]
@tha23rd Ah so all AssetMaterialization events do have versioning information written into the system tags, but this is not actually an accurate version in some cases (as we calculate it in a way that does not take into account partition mappings between assets). So in the presence of PartitionsDefinitions, we cannot currently rely on the versions that are written into storage.

However, we're actively working on a fix for that, and once merged, I believe it will be safe to start using this versioning information in the AutoMaterialize logic. I don't have an exact timeline (as I want to account for any expected weirdness that may crop up), but if things go smoothly then this could be done in ~2 weeks.

**Comment by sryza** [comment]
@OwenKephart @smackesey is this close-able?
