### ISSUE TITLE
Search (CTRL+K) does not work with --path-prefix

### ISSUE THREAD

**Issue by alexknorr** [dagster-io/dagster#14894]
### Dagster version

1.3.10

### What's the issue?

When dagit is started with a --path-prefix, clicking on search or typing CTRL-K leads to an JS import-error. Typing in the popup input does not find anything.

It seems to load some js-scripts from the root, ignoring the prefix-path.

Browser log shows the following error:
`
importScripts chunk loading:28  Refused to execute script from 'https://my.company.com/static/js/984.5a2e0916.chunk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
n.f.i @ importScripts chunk loading:28
(anonymous) @ ensure chunk:6
n.e @ ensure chunk:5
n.x @ startup chunk dependencies:3
(anonymous) @ startup:2
(anonymous) @ 833.c37a676f.chunk.js:1
importScripts chunk loading:28  Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://my.company.com/static/js/984.5a2e0916.chunk.js' failed to load.
    at n.f.i (https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6312)
    at https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6085
    at Array.reduce (<anonymous>)
    at n.e (https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6050)
    at n.x (https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6616)
    at https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6637
    at https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6641
n.f.i @ importScripts chunk loading:28
(anonymous) @ ensure chunk:6
n.e @ ensure chunk:5
n.x @ startup chunk dependencies:3
(anonymous) @ startup:2
(anonymous) @ 833.c37a676f.chunk.js:1
importScripts chunk loading:28  Refused to execute script from 'https://my.company.com/static/js/984.5a2e0916.chunk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
n.f.i @ importScripts chunk loading:28
(anonymous) @ ensure chunk:6
n.e @ ensure chunk:5
n.x @ startup chunk dependencies:3
(anonymous) @ startup:2
(anonymous) @ 833.c37a676f.chunk.js:1
importScripts chunk loading:28  Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://my.company.com/static/js/984.5a2e0916.chunk.js' failed to load.
    at n.f.i (https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6312)
    at https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6085
    at Array.reduce (<anonymous>)
    at n.e (https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6050)
    at n.x (https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6616)
    at https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6637
    at https://my.company.com/prefix-path/static/js/833.c37a676f.chunk.js:1:6641
`

### What did you expect to happen?

That searching is possible with --path-prefix being set.

### Deployment type

Other

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Just triaged it over to our UI team. Thanks for reporting this!

**Comment by hellendag** [comment]
Sorry it's taken so long to get to this. I've got a repro and am putting together a fix.

**Comment by alexknorr** [comment]
don´t worry and thanks a lot on taking this on!
