### ISSUE TITLE
Introduce automaterialize policy(s) that materialize only when all upstream assets are updated

### ISSUE THREAD

**Issue by leozqin** [dagster-io/dagster#14950]
### What's the use case?

The existing eager and lazy auto-materialize policies work well when an asset can safely incorporate data of differing vintages from each of its input assets.

However, some assets cannot safely do this, or doing so is inordinately expensive. For these use cases, an automaterialize policy that triggers a run only when all upstream assets have newer data than the asset for which the policy is set would satisfy the use case.

### Ideas of implementation

One way of implementing this feature would be to replace the input to the `on_new_parent_data` argument to `AutoMaterializePolicy` with enum values of `ALL_PARENTS` or `ANY_PARENT`, and expose a new prebuilt policy that implements this argument.

However, I can also see that as we expose more arguments to `AutoMaterializePolicy` the number of policy permutations will increase, so it is also worth considering how to make it safer/stable for users to define their own policies instead of using prebuilt ones.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @leozqin ! Appreciate the feedback here, and allowing for more flexibility here is definitely on our minds. To add some color here, I'm interested in learning a bit more about how you determine a given asset's "data vintage" (to borrow your phrasing).

In particular, it seems like the most natural way to define "only update when all upstream assets are updated" would be to keep track of the data version of each of the upstreams when the asset was last materialized, then only materialize the downstream asset again if every single one of those versions is now different.

However, this doesn't quite capture the concept of "data vintages" if I'm understanding correctly. Imagine you have two input assets, `A` and `B`. Assuming I've just turned on this new AutoMaterialize policy, how do I know if it's ok to materialize this asset right now (assuming both `A` and `B` have been materialized many times)? Couldn't it be the case that, at the time the policy is started, `A` is of "vintage" `N` and `B` is of "vintage" `N+1`?

In essence, are there only specific combinations of upstream versions that you should start this process on, and if so, how do you know which combinations those are?

**Comment by leozqin** [comment]
Oh - i think we can treat "vintage" simply to mean "last materialization time". If there's a better term for that, let me know!

The situation we usually encounter is something like:

1. Source 1 -> Asset A -> Asset C
2. Source 2 -> Asset B -> Asset C
3. Source 1 and 2 both update daily
4. Source 1 update several hours before Source 2
5. If we compute Asset C using today's data from Asset A and yesterday's Asset B we might get semantically incoherent results, or a failure.

Furthermore, while Asset C can and should be written in such a way that it is tolerant to the data being mixed temporally, what if Asset C is computationally expensive? 

Furthermore, sometimes Source 2 (or Source n...) can be updated on an irregular basis.

Cold starts aside, the plain-english desired behavior would be "materialize Asset C only when all of its inputs have been updated at least once since the last time that Asset C was materialized", or "min(last materialized time of inputs) > last materialized time of asset"

**Comment by OwenKephart** [comment]
To be more specific about my concern, following your example, imagine a timeline of:

1. Source 1 / Asset A are updated
2. Someone manually executes Asset C before Source 2 / Asset B is updated

At this point, if C waits for _both_ of its parents to be updated, when Asset B is updated then `C` will not be executed (as `C` already consumed the latest version of `A`). Instead, it'll wait until tomorrow, when Source 1 updates, resulting in the asset being permanently off-cycle, at least until someone manually intervenes again.

This could just be an acceptable sacrifice, but what I'm trying to figure out is if there's some important aspect of these sources that's not currently being modeled, and if it were modeled, would result in the desired behavior. For example, it sounds like these sources might actually be day-partitioned (we expect them to be materialized daily).

Another angle of this might be making the lazy automaterialize behavior more intuitive (it's quite challenging at the moment). But would a way to say "once a parent has been materialized, you may wait up to three hours to pull in those changes" or something along those lines also work?

That's not to say this `AND` behavior is not worth pursuing, just trying to expand the space of options.

**Comment by leozqin** [comment]
Yes, i think that, if the policy explains that all inputs must update before a materialization is happens, then that behavior in your example can be reconciled as valid. We definitely only use manual materializations when something has started to go down the unhappy path.

Another benefit of this approach is that it avoids treating the freshness policy like a pseudo-schedule. There truly is no preference as to WHEN materialization happens (which is when you'd use a freshness policy cron), just that it happens asap after all the pieces are in place. 

It occurs to me that what's great about eager materialization is that it only cares about the state of the graph, not the timing of when the graph updates. I think that this approach is the same, but gives us a lever to introduce a degree of conservatism (maybe... conservative auto-materialize policy??)

**Comment by OwenKephart** [comment]
Some more slack conversations:
- https://dagster.slack.com/archives/C01U954MEER/p1692112529750479
- https://dagster.slack.com/archives/C04CW71AGBW/p1692211120857789?thread_ts=1692203865.737849&cid=C04CW71AGBW

**Comment by OwenKephart** [comment]
Closed by: https://github.com/dagster-io/dagster/pull/16052

To enable this behavior:

```python
wait_for_all_parents_policy = AutoMaterializePolicy.eager().with_rules(
    AutoMaterializeRule.skip_on_not_all_parents_updated()
)
```
