### ISSUE TITLE
pyspark getting downloaded in airline-demo tox command

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1496]
Unclear why this is happening exactly but it potentially is a considerable slowdown for airline demo test. pyspark 2.4.0 should be on the integration image which is the base image in question (AFAIK)

See logs here for this repro:

https://buildkite.com/dagster/dagster/builds/2244#0e1056ea-2b80-42d4-bd30-56a26d516548

**Comment by mgasner** [comment]
I think this is probably when we build the docker container. See also #1453 #1183

**Comment by mgasner** [comment]
this is resolved by our snapshot system
