### ISSUE TITLE
Support custom naming format for partition keys

### ISSUE THREAD

**Issue by giovannipcarvalho** [dagster-io/dagster#14971]
### What's the use case?

I want to be able to distinguish at a glance that `asset_a/2023-06-04.pkl` is a partitioned asset that encompasses more than a single day, e.g. 2023-06-04 to 2023-06-10.  Currently, if I'm looking only at the persisted data (local disk or S3), it's not immediately obvious that it's not a plain daily-partitioned asset.

While I understand that the asset could be named as to indicate that its partitioning scheme (e.g. `my_weekly_asset`) I believe something like `asset_a/2023-06-04_2023-06-10.pkl` is clearer.

### Ideas of implementation

Since strftime has no concept of start and end dates, I think it would be simpler to accept a `partition_key_fmt` function that translates `(start_date, end_date) -> str` and let the user handle the logic, rather than extending `%`-identifiers.

Also, there's always a possibility that the specified function creates collisions for different time ranges, which is a problem to keep in mind.

### Additional information

I'm aware this can be implemented as a custom io-manager, but in most cases just providing a custom naming format would be much simpler.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @sryza, do you know off the top of your head if we rely on being able to parse time partition keys? If not, then this seems like it wouldn't be too tough.

**Comment by sryza** [comment]
`PartitionsDefinition` objects can't have attributes that are user-provided functions, because they need to be usable in host-processes like the web server, where user code isn't available.

However, the code that's actually writing the files – either in the `@asset`-decorated function or in the IO manager – has access to the partition time window and can choose the file name based on that.

**Comment by smackesey** [comment]
@giovannipcarvalho Based on @sryza's comment, it looks like it's not possible to support a user-provided function. In theory we could add some extra static args and interpret them to generate the custom key, but I don't believe the added complexity to be worth it in this case, when it is already possible to generate whatever path you want using IO manager logic. Thanks for taking the time to write this up!
