### ISSUE TITLE
Wrangle dependency madness

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1497]
So we need to figure out a short term dependency strategy for our 0.5.0 release.

I suggest a few principles

1) Our setup.py dependencies should *as loose* as possible
2) Our dev environment should be *as strict* as possible.

This means we should have separate snapshot requirements.txt files that act as our lockfiles for local dev and test runs. This would prevent redownloading the world with our integration images. However we want to be permissive with our user base and not incur dep hell on *them*.

https://github.com/dagster-io/dagster/issues/1273

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by natekupp** [comment]
Marking as dupe, let's use 1295 as the primary issue for this
