### ISSUE TITLE
Allow use of type signature-derived solid definitions on library solids

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1498]
Prototyped approach @ https://dagster.phacility.com/D411

**Comment by natekupp** [comment]
can you expand on this? @schrockn

**Comment by schrockn** [comment]
This was an idea to have a generic facility to allow for type signatures on specialized solid decorators (e.g. specific to a library). I don't think we need this for now. May be interesting to explore during lakehouse work.
