### ISSUE TITLE
DynamicPartitions via pyspark_step_launcher - Nonexistent partition keys (DagsterInvalidInvocationError)

### ISSUE THREAD

**Issue by weberdavid** [dagster-io/dagster#14987]
### Dagster version

1.3.10

### What's the issue?

We discussed this issue in detail in Slack: https://dagster.slack.com/archives/C01U954MEER/p1687185900524019

Here is a summary:

1. We use file partitions based on DynamicPartitionsDefinition
2. Asset1: Is executed locally, uses the partitions via the `partitions_def` in the `@asset` decorator
3. Asset2: Executed in Databricks using the `pyspark_step_launcher`, also using `partitions_def` in the `@asset` decorator; this asset depends on asset1, by having it as an input parameter in the function.

This is the exact error message:
```
dagster._core.errors.DagsterInvalidInvocationError: Partition range <our_partition_key> to <our_partition_key> is
                not a valid range. Nonexistent partition keys:
                [<our_partition_key>]
```

Apparently, dagster on Databricks is not aware of the partition that we are passing to asset2.

### What did you expect to happen?

The error message is unexpected, as I expected Dagster on Databricks to have access to the DynamicPartition that is used throughout a job.

Here is a potential solution on how to fix it, suggested by @OwenKephart (thanks!):

1. StepRunRef contains all of the information that is sent to the external instance, but doesnt include dynamic partitions
2. Updating [run_step_from_ref](https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/_core/execution/plan/external_step.py?L237) would be a lightweight solution, to add a partition to the external Databricks instance.
3. First there should be a check, whether we are dealing with a DynamicPartitionsDef

I am currently testing @OwenKephart suggestion in our setup and will have a PR available soon.

### How to reproduce?

Here is a minimal code example that reproduces the issue (thanks @loerinczy):
```
from pathlib import Path
from dagster import (
    asset, 
    sensor, 
    SensorResult, 
    RunRequest,
    DynamicPartitionsDefinition,
    Definitions,
    AssetSelection,
    define_asset_job
)
from dagster_databricks import databricks_pyspark_step_launcher

partition = DynamicPartitionsDefinition(name='test_partition')

@asset(
    partitions_def=partition,
    required_resource_keys={'pyspark_step_launcher'}
)
def test_asset():
    return 1

test_job = define_asset_job(name='test_job', selection=AssetSelection.keys('test_asset'))

@sensor(
    name='test_sensor',
    job=test_job
)
def test_sensor():
    return SensorResult(
        run_requests=[RunRequest(partition_key='new_partition')],
        dynamic_partitions_requests=[
            partition.build_add_request(['new_partition'])
        ]
    )

defs = Definitions(
    assets=[test_asset],
    sensors=[test_sensor],
    jobs=[test_job],
    resources={
        "pyspark_step_launcher": databricks_pyspark_step_launcher.configured(
            {
                "run_config": {
                    "run_name": "test dagster",
                    "cluster": {
                        "existing": "<our_cluster>" # from the Databricks URL
                    },
                    # "libraries": [
                    #     {"pypi": { "package": "dagster==1.3.2"} },
                    # ]
                },
                'secrets_to_env_variables': [],
                "databricks_host": "<dbx_url>",
                "databricks_token": {
                    "env": "DATABRICKS_TOKEN" # It has to be available in the Databricks env as well
                },
                "local_pipeline_package_path": str(Path(__file__).parent.parent)
            }
        ),
    }
)
```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @OwenKephart

**Comment by weberdavid** [comment]
PR: #15000
