### ISSUE TITLE
Ability to query current status of any partition of an asset

### ISSUE THREAD

**Issue by renzhe-brian** [dagster-io/dagster#14988]
### What's the use case?

In our case, when current partition starts running, we need to check if the previous partition(s) is materilized or not. If the current status of previous partition(s) is not successfully materilized, then we need to cancel the current run.

We are using an op to do the check. As a work around, we use the following code to get the materilization event, but if the previous partition is re-materilizing, this doesn't work.
```python
event_records = context.instance.get_event_records(
        EventRecordsFilter(
            event_type=DagsterEventType.ASSET_MATERIALIZATION,
            asset_key=config.asset_key,
            asset_partitions=[prev_partition_key],
        )
    )
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @clairelin135 @johannkm thoughts on exposing the partition status cache used for GQL with a public `DagsterInstance` method?

**Comment by sryza** [comment]
@smackesey if the request is to look at the status of a single partition, then I think it might be more performant to do something like what @renzhe-brian included in his example above. Either way, I do think that a `DagsterInstance` method would be useful.

@renzhe-brian - if you had any bandwidth to work on this, we could give you pointers?

**Comment by renzhe-brian** [comment]
Hi @smackesey , @sryza , at this moment, the request is to  look at the current status of a single partition. 
@sryza , I'd love to try it out. Please show me some pointers.

**Comment by clairelin135** [comment]
@renzhe-brian here's a description of what the changes could look like:

Some background:
- We have an object called the [asset status cache value](https://github.com/dagster-io/dagster/blob/dfedb1bdfd6ffc7f29473297973754b9fd70ddad/python_modules/dagster/dagster/_core/storage/partition_status_cache.py#L58-L70) that stores a serialized representation of the materialized, failed, and in progress partitions. It contains functions that accept the partitions def to deserialize the failed/materialized/in progress partitions.
- [`get_and_update_asset_status_cache_value` is a function](https://github.com/dagster-io/dagster/blob/dfedb1bdfd6ffc7f29473297973754b9fd70ddad/python_modules/dagster/dagster/_core/storage/partition_status_cache.py#L562-L579) that updates the asset status cache value with the current events in storage.

The steps you can take to add the instance method:
1. Make the `get_and_update_asset_status_cache_value` function to be an instance method. This ensures that when you fetch the cache value from the instance, it is updated with the current state.
- Add some instance method that fetches the status of a partition key, and potentially create some status object representing partition status
```
def get_partition_status(self, asset_key, partitions_def, partition_key):
     cached_value = self.get_and_update_asset_status_cache_value(...)
     materialized_partitions = cached_value.deserialize_materialized_partition_subsets(...)
     failed_partitions = ...
     in_progress = ...

     if partition_key in in_progress:
           return PartitionStatus.IN_PROGRESS
     elif partition_key in failed:
           return PartitionStatus.FAILED
     elif partition_key in materialized:
           return PartitionStatus.MATERIALIZED
     else:
           return PartitionStatus.UNMATERIALIZED
```

**Comment by renzhe-brian** [comment]
Hi @clairelin135 , thank you very much. This is very clear.
