### ISSUE TITLE
when time_window_partitions_scope=None, root asset partitions are requested after being discarded

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#14984]
On each tick, the Auto-materialize history tab will say that partitions were discarded, but each tick will also request a run.

```python
from dagster import asset, DailyPartitionsDefinition, AutoMaterializePolicy

@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2020-01-01")
    auto_materialize_policy=AutoMaterializePolicy(
        on_missing=True,
        on_new_parent_data=True,
        for_freshness=True,
        time_window_partition_scope_minutes=None,
        max_materializations_per_minute=1,
    )
)
def asset1():
    ...
```

**Comment by sryza** [comment]
@OwenKephart is this on your radar already?

**Comment by OwenKephart** [comment]
@sryza Yep on the radar -- the reason is that we don't currently merge the discarded partitions back into the materialized_or_requested_root_asset_partitions bit of the cursor. should be a simple change
