### ISSUE TITLE
Testing with asset partition ranges

### ISSUE THREAD

**Issue by bmarcj** [dagster-io/dagster#14990]
### What's the use case?

Currently we can test a software defined asset that makes use of partition ranges, by creating an op context:

`context = dagster.build_op_context(partition_key="2023-01-05")`

And then we can do `time_window = context.asset_partitions_time_window_for_output()` and it will work for the single day (because we can derive a time window from the key).

However, there are some issues:
- `asset_partitions_time_window_for_output()` is marked as deprecated on `OpExecutionContext` (but not `AssetExecutionContext`) - possibly related to https://github.com/dagster-io/dagster/issues/14871 and a missing `build_asset_context` function?
- testing like this does not work with `context.partition_time_window` (` AttributeError: 'BoundOpExecutionContext' object has no attribute '_step_execution_context'. Did you mean: 'get_step_execution_context'?`) 
- Most importantly, we cannot test multiple days with this approach

### Ideas of implementation

Being able to specify a date/time range in the `build_op_context` would be ideal.  This might even need to be part of the upcoming `build_asset_context` (see  https://github.com/dagster-io/dagster/issues/14871 again).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Thanks for filing @bmarcj.
