### ISSUE TITLE
Manage Dynamic Partitions in Dagit UI

### ISSUE THREAD

**Issue by TimoVink** [dagster-io/dagster#15012]
### What's the use case?

When working with dynamic partitions sometimes we run into situations where it would be really nice to be able to manually intervene and create/delete partitions using dagit. 

For example:
 * Maybe you normally create new partitions on a schedule but you need to insert an "off-schedule run" 
 * Maybe you created some bad partitions due to a bug, and want to get rid of them

While there is limited functionality in dagit to *add* partitions, I don't believe there is a way to *delete* partitions from the UI. It would be great if this was added as the dynamic partitions feature matures.

### Ideas of implementation

Beautiful mockup:
![image](https://github.com/dagster-io/dagster/assets/694180/3999c243-518a-47da-9241-d60a1dbfeb17)

**Note:** partition IDs look like timestamps in the screenshot, but this is in fact a dynamic partition.

### Additional information

Our current workaround for manually managing partitions is to write one-off `@job`s to perform the actions using the `context.instance.delete_dynamic_partition` API. This works, but is just a bit cumbersome.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by TimoVink** [comment]
Side note: While creating this ticket I noticed the "add a partition" button in the screenshot isn't working for me right now (dagit v1.3.11). Clicking on the button does nothing. No JS console warnings either.

The "add a partition" button in the launchpad _does_ work for me.

**Comment by ian-whitestone** [comment]
Ran into this issue today, would be great to add!

**Comment by sryza** [comment]
Here's an earlier issue for tracking deleting dynamic partitions: https://github.com/dagster-io/dagster/issues/14026.  I agree that this would be helpful functionality to add.

I'm going to close this issue as a duplicate. Let me know if you think there's missing functionality that's not represented in that other issue, and maybe we can file a targeted issue for adding that functionality.
