### ISSUE TITLE
dagster project from-example does not create a folder

### ISSUE THREAD

**Issue by Gilad-Carmel** [dagster-io/dagster#15024]
### Dagster version

dagster, version 1.3.12

### What's the issue?

When running this command from the [tutorial in the docs](https://docs.dagster.io/tutorial/setup)

`dagster project from-example --example tutorial --name my-tutorial-project`

I get the following output
```
Downloading example 'tutorial'. This may take a while.

Success! Created my-tutorial-project at <folder-location>
```

but no folder is created at the location specified

### What did you expect to happen?

i expected the folder to be created at the locations specified

### How to reproduce?

run `dagster project from-example --example tutorial --name my-tutorial-project`

### Deployment type

Local

### Deployment details

Working on a VM with Ubuntu 22.04.2 LTS
Python 3.10.6

### Additional information

I tried doing this with other examples and it still does not work

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Thanks @Gilad-Carmel for the report.

cc @tacastillo another user with this problem

**Comment by smackesey** [comment]
I have replicated the issue inside the python:3.7-slim docker image, it's probably linux-specific

**Comment by tacastillo** [comment]
Hi! Thanks for bug report. We've found the regression and are rolling out a fix in a bit.
