### ISSUE TITLE
Add input and output labels to invocations panel in dagit

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1503]
I tried do it, but it was a bit of a rush job that I reverted here: https://dagster.phacility.com/D428

**Comment by bengotow** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/1037212/69887825-839dfc80-12ae-11ea-851b-de1a987179dc.png">

addressed in https://dagster.phacility.com/D1513

**Comment by natekupp** [comment]
Closing, looks like this was fixed by #1503
