### ISSUE TITLE
AutoMaterializePolicies should interact with the data versioning system

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#15037]
### What's the use case?

As of now, whenever an upstream asset/partition is materialized for an asset with an `AutoMaterializePolicy.eager()`, we will launch a run of the downstream, regardless of if that upstream asset/partition has a new data version or not. We do however take into account versioning information for observable source assets.

The fact that we don't always take versioning into account is surprising, as we have the tools necessary to determine that no new run is necessary, but do not use them. This has historically been for performance reasons, but this may be less of a concern as of recently.

We should remove this limitation as soon as practical.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I think this might be a duplicate of https://github.com/dagster-io/dagster/issues/14893?

**Comment by OwenKephart** [comment]
whoops missed that, closing this and copy/pasting the info there
