### ISSUE TITLE
[dagit] composite layout bug

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#1504]
seems like there is some lifecycle issue where we are trying to render something when it doesnt have a valid layout? couldnt quite figure it out.

**Comment by mgasner** [comment]
Do we have any further description of this or steps to reproduce?

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/source/dagster/browse/master/js_modules/dagit/src/graph/ExternalConnectionNode.tsx$43

**Comment by alangenfeld** [comment]
i think i bumped in to it when viewing the composition toy pipeline bouncing in and out of the composite layers

**Comment by mgasner** [comment]
Can't reproduce -- this whole layout has changed substantially.
