### ISSUE TITLE
visualize freshness policies in the UI

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#15073]
An asset is considered overdue when it's derived from data that's older than the required time for it to be fresh. An asset's data time is based on materialization times of the ancestor materializations of its latest materialization.

All of this information is currently opaque to the user, which makes it difficult to understand the semantics of freshness.  We should expose it.  I.e. you should be able to click or hover or something over a freshness policy and see:
- Its "data time", i.e. how old Dagster thinks its data is
- What its data time needs to be for it not to be considered overdue
- How its data time was computed

One fancy way to represent how its data time was computed would be a DAG of the materializations that the asset is based on.  Each materialization would show its data time, and materializations with data times prior to the expected data time would be colored red.

This materialization lineage graph might also be generally useful for debugging, even when no freshness policy is set.

This would help to resolve confusion like this: https://github.com/dagster-io/internal/discussions/5928#discussioncomment-6328060.

**Comment by bengotow** [comment]
Hey @sryza  - this seems like a great idea. I believe we /sorta/ have a way to inspect this already, in the form of this "Source Data"  rendering that pulls from `AssetNode.assetMaterializationUsedData(timestamp)`:

<img width="1041" alt="image" src="https://github.com/dagster-io/dagster/assets/1037212/096543cf-0c46-4a13-9bfc-9c79500a7fd0">

Right now we collapse it (only showing the furthest ancestors) and the times are relative and not absolute, but I think the data it's fetching is the data we want for this.

I'll take a stab at presenting this in an overlay that you can open from the "Late" tag and colorizing it to highlight the source of lateness.

**Comment by sryza** [comment]
@bengotow awesome - excited to see what you come up with. Let me know if it would be helpful to bounce around ideas.
