### ISSUE TITLE
Tags require 'str' value in RunRequest but 'Any' in the JobDefinition

### ISSUE THREAD

**Issue by yuvalgimmunai** [dagster-io/dagster#15080]
### Dagster version

1.2.6

### What's the issue?

In order to define k8s specs we have to give the run a tag with a Dict value.
This goes fine in the JobDefinition because the validation there is: 
`tags = check.opt_mapping_param(tags, "tags", key_type=str)`

But when we try to set it in a RunRequest we fail with this error:
`dagster._check.CheckError: Value in Mapping mismatches expected type for key dagster-k8s/config. Expected value of type <class 'str'>. Got value {'container_config': {'resources': {'limits': {'cpu': '42', 'memory': '243G'}, 'requests': {'cpu': '42', 'memory': '243G'}}}} of type <class 'dict'>.`

Becuase the validation is of such:
`tags=check.opt_mapping_param(tags, "tags", key_type=str, value_type=str),`

### What did you expect to happen?

I expected to be able to give a tag that does not have a 'str' as a value to be able to set k8s specs for my run.

### How to reproduce?

Create a RunRequest with a String: Dict in the tags

### Deployment type

Dagster Helm chart

### Deployment details

irrelevant

### Additional information

-

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by lior-ness** [comment]
Thanks @yuvalgimmunai
