### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [dagster-io/dagster#1508]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/dagster-io/dagster/blob/master/js_modules/dagit/package.json#L69

See https://nodejs.org/api/fs.html

You might want to remove it using `yarn remove fs`.

**Comment by schrockn** [comment]
Thanks for the report! We'll look into this

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D442
