### ISSUE TITLE
Can't view runs in Dagit

### ISSUE THREAD

**Issue by hymanoide** [dagster-io/dagster#15087]
### Dagster version

1.0.12

### What's the issue?

When clicked in "Runs" -> Queued or Running It throws this GraphQL exception: 

Operation name: RunsRootQuery
Message: Cannot return null for non-nullable field Run.mode.
Path: ["pipelineRunsOrError","results",0,"mode"]
Locations: [{"line":26,"column":3}]

### What did you expect to happen?

I expected to see running or queued jobs as normally.

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hymanoide** [comment]
I upgraded to last version 1.3.13 and solved the issue.

**Comment by peterbaccaro** [comment]
What was the root cause of this issue?  Has the Run.mode become optional?
