### ISSUE TITLE
pydantic.errors.PydanticImportError: `pydantic:ConstrainedFloat` has been removed in V2

### ISSUE THREAD

**Issue by TemaDobryyR** [dagster-io/dagster#15085]
### Dagster version

1.3.2

### What's the issue?

I have a dagster deployed in a kuber. Once again I updated the user deployment and got the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/dagster", line 5, in <module>
    from dagster.cli import main
  File "/usr/local/lib/python3.8/site-packages/dagster/__init__.py", line 95, in <module>
    from dagster._config.pythonic_config import (
  File "/usr/local/lib/python3.8/site-packages/dagster/_config/pythonic_config/__init__.py", line 21, in <module>
    from pydantic import ConstrainedFloat, ConstrainedInt, ConstrainedStr
  File "/usr/local/lib/python3.8/site-packages/pydantic/__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
  File "/usr/local/lib/python3.8/site-packages/pydantic/_migration.py", line 285, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:ConstrainedFloat` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.0/u/import-error
```
Dont understand why this error occurred, because I just rebuilt the user deployments image

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sim-dt** [comment]
Looks like pydantic made a major release over the weekend which has broken something.

We're working around this today by pinning `pydantic == 1.10.10`.

**Comment by TemaDobryyR** [comment]
yep, i have deployed dagster locally with deploy_docker from examples, and container with dagit (dagster version 1.3.1, 1.3.2) falls with the same error.
With the latest version of the dagster it works without errors

**Comment by tacastillo** [comment]
Hi! We added a pin to `Pydantic<2` in a recent patch release, in anticipation of Pydantic V2's release. If you update your Dagster version to a more recent release (ex. 1.3.13), you can downgrade to a Pydantic 1.X version while we work on adding support for Pydantic>2.

**Comment by rexledesma** [comment]
Consolidating in favor of https://github.com/dagster-io/dagster/issues/15162.
