### ISSUE TITLE
Preset loading has surprising behavior

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1509]
Since we reprocess YAML file contents to do a merge, we end up with things like this:

![image](https://user-images.githubusercontent.com/609349/59887287-a202e200-9377-11e9-8afb-7fe275b97294.png)

**Comment by natekupp** [comment]
also the merge meant that it reordered all the keys from my YAML file, which my initial gut reaction to is "wait, what happened? Ctrl+Z!" because of an anxiety that it screwed up my config

**Comment by natekupp** [comment]
Also, we should support Cmd-Z - it's disconcerting to not be able to undo loading a preset since it replaces everything in the editor

**Comment by mgasner** [comment]
See #1821

**Comment by natekupp** [comment]
yeah I think the undo is the main thing that's important here. we still load

```
filesystem:
  storage:
```
as the screenshot above (inserting null) but I don't think that's a big deal / worth keeping this open for.

**Comment by natekupp** [comment]
repro steps:

1. Create two YAML files, e.g. on `error_monster` add a second config file `storage.yaml`, then update `environment_files=[file_relative_path(__file__, 'environments/error.yaml'), file_relative_path(__file__, 'environments/storage.yaml')],` where `storage.yaml` has the contents:

```yaml
storage:
  filesystem:
```

2. Load `passing` preset in dagit
3. Dagit shows

```yaml
<< other config>>
storage:
  filesystem: null
```

**Comment by hellendag** [comment]
Could potentially pop the merged config into a new tab.

**Comment by catherinewu** [comment]
going to close since environment_files is deprecated afaict
