### ISSUE TITLE
In project scaffold, put definitions into a definitions.py, instead of __init__.py

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#15112]
From @slopp:

> I still think its mysterious for some users to see Definitions in init.py. I tend to create a definitions.py and then have a one line reference to the defs object in init.

**Comment by sryza** [comment]
After we do this, we can update the load-dbt-models tutorial step to link to https://docs.dagster.io/getting-started/project-file-reference. Right now, it doesn't make sense to do that because the dbt scaffold uses definitions.py instead of `__init__.py`.

**Comment by rexledesma** [comment]
This seems to be resolved.

**Comment by sryza** [comment]
@rexledesma is this just resolved in the dagster-dbt scaffold or also in the non-dbt scaffold?

**Comment by rexledesma** [comment]
Ah, I misinterpreted this to be related to `dagster-dbt`. Reopening.

**Comment by rexledesma** [comment]
https://github.com/dagster-io/dagster/pull/20771
