### ISSUE TITLE
Managing `DynamicPartitions` from Dagit

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#15127]
### What's the use case?

The [blog post](https://dagster.io/blog/dynamic-partitioning) on Dynamic Partitioning has this line: 

>  For these assets, partitions can be added and removed dynamically, via code or the UI.

However, I don't think it's currently possible to do it from Dagit (at least I didn't find a way). 

This would be really useful, as right now a special job/sensor is needed to do it. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
hey @danielgafni  when i have a dynamically partitioned asset I can add a partition in the UI. If i go to the asset graph and click materialize, the pop up window has an `add partition` option 

![Screenshot 2023-07-06 at 11 52 29 AM](https://github.com/dagster-io/dagster/assets/19783112/39a7193e-6a07-47d0-839b-79000254c0b9)

![Screenshot 2023-07-06 at 11 50 57 AM](https://github.com/dagster-io/dagster/assets/19783112/1b79f097-5c68-40b5-ac35-a53bf8869f8c)

is that not showing for you?

**Comment by sryza** [comment]
Here's an earlier issue for tracking deleting dynamic partitions: https://github.com/dagster-io/dagster/issues/14026.  I agree that this would be helpful functionality to add.

I'm going to close this issue as a duplicate. Let me know if you think there's missing functionality that's not represented in that other issue, and maybe we can file a targeted issue for adding that functionality.
