### ISSUE TITLE
Add support for pydantic 2

### ISSUE THREAD

**Issue by jamiedemaria** [dagster-io/dagster#15162]
### What's the use case?

update the resources and config system to support pydantic 2

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by lainiwa** [comment]
Pydantic v2 also contains v1 functionality, so likely Dagster could be updated to be v2-compatible just by editing imports: [pydantic v2 docs](https://docs.pydantic.dev/dev-v2/migration/#continue-using-pydantic-v1-features).

**Comment by mjclarke94** [comment]
Is there any update on this? @lainiwa 's suggestion might be a nice intermediate approach whilst resources/config are updated to make use of the new features. 

We have an interfaces library which is decoupled from dagster, but aren't able to bump that to pydantic 2 whilst some environments need both dagster and our interfaces tool.

**Comment by zaneselvans** [comment]
There's also the helpful little utility https://github.com/pydantic/bump-pydantic which can make many of the changes required to migrate from v1 to v2 automatically.

**Comment by emanueledomingo** [comment]
Hi guys, do you have an ETA for this?

**Comment by benpankow** [comment]
Hi all, just wanted to let you know that this is is something we're actively taking a look at - it's a bit too early to provide an ETA, but we will keep you updated as this proceeds. Since we rely on some of Pydantic's internals, it means we unfortunately can't rely solely on the compatibility layer.

**Comment by aeturrell** [comment]
I've run into this as an issue, great to know it's under active consideration.

**Comment by ttamg** [comment]
Any update on this move to pydantic v2 please?

**Comment by benpankow** [comment]
The relevant compat layer will be shipping with Dagster `1.5.5` on October 26
