### ISSUE TITLE
@config_mapping decorator

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1516]
we should consider adding another decorator for this
```
@config_mapping(config=...)
def event_proc_config_mapping(cfg):
   return ...

@composite(config_mapping=event_proc_config_mapping)
```

https://dagster.phacility.com/D289

**Comment by sryza** [comment]
I think `configured` satisfies a need that's pretty close to this, so I'm going to close this.  @natekupp, let me know if you think I'm misunderstanding.
