### ISSUE TITLE
Fix ordering issue with input mapping in DSL dep construction

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1518]
We can get into a state where inputs are pass in the incorrect order to solids when multiple inputs passed into a solid with *args rather than **kwargs.

The fix will look something like https://dagster.phacility.com/D462 but have to reconstruct in a test case etc.

For the particular test failure we can just switch to using only kwargs a la: https://dagster.phacility.com/D461

**Comment by schrockn** [comment]
Failure only occurred when landed in master https://buildkite.com/dagster/dagster/builds/2468#80607904-4b72-47a3-868c-b8a9d54bdf2d

**Comment by schrockn** [comment]
This is the revert that fixed it. Note removal of two input mappings deteremined via dsl: https://dagster.phacility.com/D463

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D464
