### ISSUE TITLE
dagster-airflow: first DAG run always fails

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1519]
The first scheduled DAG run for a `make_airflow_dag()` DAG always fails w/ error message:

```
[2019-06-25 17:12:06,825] {__init__.py:1580} ERROR - Executor reports task instance <TaskInstance: gcp_pipeline.dataproc_solid 2019-06-23 00:00:00+00:00 [queued]> finished (failed) although the task says its queued. Was the task killed externally?
```
Potentially related links:

https://stackoverflow.com/questions/56119107/apache-airflow-1-10-3-executor-reports-task-instance-finished-failed-alth
https://airflow.apache.org/cli.html#backfill

maybe a pickle issue?

**Comment by natekupp** [comment]
So far can only repro this on the celery executor, the sqlite/local seems to be unaffected

**Comment by mgasner** [comment]
I can't repro this on sqlite/local. Do we have a working celery executor setup?

**Comment by natekupp** [comment]
@catherinewu have you ever seen anything like this? if not, feel free to close this

**Comment by catherinewu** [comment]
@natekupp I haven't seen this error before. Closing for now..
