### ISSUE TITLE
Allow group_name to span over code locations in dagit UI

### ISSUE THREAD

**Issue by stefkauff** [dagster-io/dagster#15231]
### What's the use case?

I have 1 group name, distributed over 2 code locations. Currently in dagit in the lineage graph, these are shown as 2 separate blocks.

### Ideas of implementation

It would be nice if they are displayed as 1 group.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for submitting this @stefkauff . I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/14322.
