### ISSUE TITLE
Can't understand why eager AMP is not triggering materializations

### ISSUE THREAD

**Issue by tacastillo** [dagster-io/dagster#15246]
### Dagster version

1.3.11

### What's the issue?

Reposting from Slack. This is from a user who has been trying to solve this. Posting an GH issue to help track this for them.

### What did you expect to happen?

Whenever a partition of `up_a` is materialized, followed by a materialization of `up_b`, `multi_partitions_asset` should materialize a partition derived from both of those. This should be consistent as more partitions of its upstreams are materialized.

### How to reproduce?

```python
from dagster import (
    DailyPartitionsDefinition,
    MultiPartitionsDefinition,
    StaticPartitionsDefinition,
    asset, define_asset_job,
    Definitions, AutoMaterializePolicy, AssetSelection, in_process_executor,
)

datep = DailyPartitionsDefinition(start_date="2023-06-23")
colorp = StaticPartitionsDefinition(["red", "yellow", "blue", "green", "black", "white", "orange"])
shapesp = StaticPartitionsDefinition(["square", "round"])
multip = MultiPartitionsDefinition({"up_a": datep, "up_b": colorp})

@asset(partitions_def=datep)
def up_a():
    return [1, 2, 3]

@asset(partitions_def=colorp)
def up_b():
    return ['a', 'b']

@asset(
    partitions_def=multip,
    auto_materialize_policy=AutoMaterializePolicy.eager(),
)
def multi_partitions_asset(context, up_a, up_b):
    return up_a + up_b


myjob = define_asset_job('test_job',
    selection=AssetSelection.assets(multi_partitions_asset),
    #partitions_def=multip,
    executor_def=in_process_executor,
)

defs = Definitions(
    jobs=[myjob],
    assets=[up_a, up_b, multi_partitions_asset],
)
```

Sequence of steps:
1. materialize a partition of up_a and up_b. works great
2. materialize another partition of up_b, also works
3. materialize a partition of up_a,. I assumed that this would kick a run off with 2 partitions of multi_partitions_asset, since there are now two possible permutations that haven't been materialized.
Any subsequent materializations of up_a doesn't trigger anything, but a materialization of up_b leads to a single materialization with that first partition of up_a.

### Deployment type

None

### Deployment details

Local. Ran this a couple weeks back on 1.3.11.

### Additional information

![image](https://github.com/dagster-io/dagster/assets/10715711/7e9ba093-0276-41d5-aea8-eaea9fc3827d)
![image](https://github.com/dagster-io/dagster/assets/10715711/c0e2ce1f-0ad8-42e5-83d3-5b26f6c572be)
![image](https://github.com/dagster-io/dagster/assets/10715711/7ef02a3c-f6b8-4dec-946a-8687456f3576)
![image](https://github.com/dagster-io/dagster/assets/10715711/fa3bd360-a9a3-4784-aad9-f2ee55a206cd)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by someaveragepunter** [comment]
However I am now encountering a new bug. Perhaps close this issue and respond on new issue below?
https://github.com/dagster-io/dagster/issues/15383
