### ISSUE TITLE
Final API cleanup

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1526]
inputs --> input_defs
outputs --> output_defs
mode_definitions -> mode_defs
renamed ExpectationDefinition
resources -> resource_defs
 
in all public APIs

ResouceRequirements or some other name instead of just a set of raw string for required resources. This is will make additions to this subsystem potentially non-breaking. The set of strings is very inflexible.

**Comment by schrockn** [comment]
Assigning to our codemod master

**Comment by schrockn** [comment]
{input,output}{_selector,}_schema -> *_config_schema

**Comment by natekupp** [comment]
@alangenfeld closing, I think you got all of these
