### ISSUE TITLE
Search by run id in job history

### ISSUE THREAD

**Issue by pang-wu** [dagster-io/dagster#15260]
### What's the use case?

In many cases we get run id from logging system and want to locate the run, but in the new Dagster UI it doesn't seem to have a(intuitive) way to search:
![example](https://github.com/dagster-io/dagster/assets/104795337/20985e65-5a32-41f4-bab6-a1d79cc7957d)

### Ideas of implementation

Maybe add an extra menu item "Run Id"?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thoughts on this one @braunjj ?

**Comment by braunjj** [comment]
Agree that we should support this. @marcosmarxm is this something you could look into?
