### ISSUE TITLE
observable asset doesn't materialize linked asset

### ISSUE THREAD

**Issue by PierreDubrulle** [dagster-io/dagster#15262]
### Dagster version

dagster, version 1.3.13

### What's the issue?

I followed the instructions in the https://docs.dagster.io/concepts/assets/asset-auto-execution#auto-materialize-policies doc in the Auto-materialize policies and data versions chapter.
Although the observabla_asset works well, the asset linked to it is not materialised. 

![image](https://github.com/dagster-io/dagster/assets/114570596/63cfa312-97a7-49f6-b063-d4f42aed4332)

### What did you expect to happen?

I expect that if the observable_asset is launched for the first time, the asset linked to it will be materialised.

### Deployment type

Local

### Deployment details

Deployement local or via okteto

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @PierreDubrulle - if you go to the asset catalog page for clients_table and click the "Auto-materialize history" tab, what do you see?

**Comment by PierreDubrulle** [comment]
> Oh actually - I just noticed on your screenshot - auto-materialize is off. You can click that yellow button to get to a page to turn it on.

Thanks, I hadn't noticed that you needed to activate it. Is there a way to activate it by default?

**Comment by sryza** [comment]
I don't believe so, unless @johannkm knows otherwise.

You only need to turn it on once per deployment, not for every asset.

If you're interested in that functionality, mind filing a separate issue for it?

**Comment by johannkm** [comment]
Correct, we don't have a way to enable it by default

**Comment by PierreDubrulle** [comment]
@sryza @johannkm 
I've just noticed that activating auto-materialize launches the materialisation of the asset every 30 seconds. But what I want is for the asset to materialise only if one of the observable_source_assets is modified.

**Comment by johannkm** [comment]
@PierreDubrulle would you mind making a separate issue for this and providing your code?
