### ISSUE TITLE
On localhost:3000/runs page, no runs are displayed, error: Unexepected GraphQL error

### ISSUE THREAD

**Issue by ericruleman** [dagster-io/dagster#15271]
### Dagster version

dagster, version 1.3.12

### What's the issue?

I can't see any runs on my localhost. I see the following error:

<img width="863" alt="Screen Shot 2023-07-13 at 12 27 04 PM" src="https://github.com/dagster-io/dagster/assets/41025600/dd55476d-fada-441e-a386-2ca98091c01a">

```
Operation name: RunsRootQuery

Message: Cannot return null for non-nullable field Run.mode.

Path: ["pipelineRunsOrError","results",0,"mode"]

Locations: [{"line":29,"column":3}]

Stack Trace:
  File "/Users/ericruleman/Library/Caches/pypoetry/virtualenvs/gauntlet-dev-dJ8eWozF-py3.9/lib/python3.9/site-packages/graphql/execution/execute.py", line 540, in execute_field
    completed = self.complete_value(
  File "/Users/ericruleman/Library/Caches/pypoetry/virtualenvs/gauntlet-dev-dJ8eWozF-py3.9/lib/python3.9/site-packages/graphql/execution/execute.py", line 620, in complete_value
    raise TypeError(
```

### What did you expect to happen?

I expected to see a list of runs that I had done locally.

### How to reproduce?

I didn't do anything weird — just ran dagster locally & navigated to Runs page.

### Deployment type

Local

### Deployment details

Running locally.

### Additional information

None.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
Hey - this looks related to our removal of the mode schema - wondering if your dagit installation is out of sync?

**Comment by ericruleman** [comment]
I solved my problem by killing zombie python processes. I'll close this issue.
