### ISSUE TITLE
Failed expectations show as passed in the run list

### ISSUE THREAD

**Issue by olhmr** [dagster-io/dagster#15291]
### Dagster version

dagster, version 1.3.13

### What's the issue?

When yielding `ExpectationResult(success=False)`, the `/runs` page in dagit shows it as a passed exception.

Relevant portion of run logs:
```
...
STEP_START - Started execution of step "failed_expectation".
STEP_EXPECTATION_RESULT - Expectation result failed
STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
...
```

UI shows expectations passed:
![image](https://github.com/dagster-io/dagster/assets/45567442/6a59f076-0004-4fd0-8093-67805bf42fcf)

### What did you expect to happen?

The run list should report the expectation as having failed.

### How to reproduce?

Minimal example:
```
from dagster import op, job, ExpectationResult, Output, Definitions


@op
def failed_expectation():
    yield ExpectationResult(success=False)
    yield Output(0)


@job
def failed_expectation_job():
    failed_expectation()


defs = Definitions(
    jobs=[failed_expectation_job],
)
```

Run the job, note the `STEP_EXPECTATION_RESULT - Expectation result failed` event in the logs.

Go the the `/runs` page in dagit and hover over the success. Note that it says `1 expectations passed`.

### Deployment type

Local

### Deployment details

This happens when running locally with `dagster dev` in a freshly created project - no other tools involved except poetry.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @olhmr , thanks for the report. Looks like we're just counting the number of STEP_EXPECTATION_RESULT events when we generate that message, so I put up a PR to fix this wording.

**Comment by Lyle-on-Git** [comment]
@OwenKephart would it be reasonable to report the number of expectations that passed and failed, separately (like how steps passed/failed are shown in UI)? Not sure if this should be opened as a separate issue/request.

**Comment by OwenKephart** [comment]
Hi @Lyle-on-Git -- definitely a reasonable request, although not quite as quick a change as the above, and I will say we're doing some work internally to revamp the way we allow users to express expectations and the like so that may supersede any specific changes in this UI
