### ISSUE TITLE
airline_demo_warehouse_pipeline does not execute in dagit

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1532]

**Comment by schrockn** [comment]
![Screenshot 2019-07-05 16 22 12](https://user-images.githubusercontent.com/28738937/60748282-1ffee580-9f41-11e9-8440-b6e7325924b3.png)
![Screenshot 2019-07-05 16 22 18](https://user-images.githubusercontent.com/28738937/60748283-1ffee580-9f41-11e9-87a8-27eff3b0912e.png)

**Comment by schrockn** [comment]
https://dagster.phacility.com/D549

**Comment by mgasner** [comment]
Resolved in https://dagster.phacility.com/D555
