### ISSUE TITLE
UI error after dagster update

### ISSUE THREAD

**Issue by daglob** [dagster-io/dagster#15353]
### Dagster version

dagster, version 1.3.14

### What's the issue?

When opening jobs with a lot of ops, rendering freezes and an error occurs in the chrome console.
![image](https://github.com/dagster-io/dagster/assets/1770923/5106372d-6887-4bb5-bd1e-a398d948919d)

![image](https://github.com/dagster-io/dagster/assets/1770923/f1b6d339-10f3-4bb1-bbd9-441b8b70ed03)

![image](https://github.com/dagster-io/dagster/assets/1770923/2864b505-2c2b-4720-bfa8-b116a2beac06)

### Deployment type

Local

### Deployment details

dagit==1.3.14
dagster==1.3.14

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey @daglob  thanks for reporting this -- does this happen repeatedly if you reload the page? Because of the way Dagster uses web workers, it's possible that this was a transient error caused by updating dagster. Trying to reproduce it now.
