### ISSUE TITLE
Configuration parsing error when reusing an input in a composite solid.

### ISSUE THREAD

**Issue by jack-pace** [dagster-io/dagster#1540]
If I have understood composite solids correctly, then I would expect to be able to run the following example where I reuse the `arg` to `calculate_result` in two of the inner `solids`. However, I get an error:
> dagster.core.errors.DagsterInvalidConfigError: Pipeline "my_pipeline" config errors:
>     Error 1: Missing required field "calculate_result" at path root:solids Available Fields: "['calculate_result', 'noop']".

```python
from dagster import execute_pipeline, pipeline, lambda_solid, composite_solid


@lambda_solid
def noop(arg):
    return arg


@lambda_solid
def add_one(arg):
    return arg + 1


@lambda_solid
def adder(first, second):
    return first + second


@composite_solid
def calculate_result(arg):
    left = add_one.alias('add_one_left')(arg)
    right = add_one.alias('add_one_right')(arg)
    return adder(left, right)


@pipeline
def my_pipeline():
    return calculate_result(noop())


if __name__ == '__main__':
    execute_pipeline(
        my_pipeline,
        environment_dict={
            'solids': {
                'noop': {'inputs': {'arg': {'value': 1}}},
                # 'calculate_result': {'solids': {'add_one_left': {'inputs': {'arg': {'value': 10}}}}},
            }
        }
    )
```

If I uncomment the line in the `environment_dict` to fill the value for one of the solids inside, then the pipeline will run.
Alternatively, if I change `calculate_sum` and `my_pipeline` so that I pass the same argument twice to `calculate_sum` then the pipeline will run:
```python
@composite_solid
def calculate_result(arg1, arg2):
    left = add_one.alias('add_one_left')(arg1)
    right = add_one.alias('add_one_right')(arg2)
    return adder(left, right)


@pipeline
def my_pipeline():
    a = noop()
    return calculate_result(a, a)
```

**Comment by jack-pace** [comment]
Further, on the graph view on dagit, only one of the two `add_one_...` nodes above seems to be linked to the input.

**Comment by alangenfeld** [comment]
Thanks for another excellent bug report! I'll take a stab at fixing this this afternoon.

**Comment by schrockn** [comment]
@jack-pace also curious: is this just from playing around or driven by a more real-world use case?

The bug is that we don't support mapping a composite input to multiple inner inputs at the moment. 

A temporary workaround (until alex gets to this) while we resolve this would be to intro a sort of "dummy" solid whose sole purpose is to ingest the single input and then just return it. Then your two solids could depend on that single output.

**Comment by jack-pace** [comment]
Thanks, and yes, this is another real-world use case :smile:

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D584
