### ISSUE TITLE
[Runs Page UI] Show "auto-materialize policy" tag on runs that auto-observe source assets

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#15413]
When auto-materialization kicks of a run that only observes a source asset it appears to be manually launched in the Runs table. We should show the "Auto-materialze policy" tag here instead.
![image](https://github.com/dagster-io/dagster/assets/2798333/45775f29-3458-4528-832f-16babbfd9543)

[Context](https://elementl-workspace.slack.com/archives/C03CCE471E0/p1689802369266859) from Slack

Feedback on the newer auto_observe_interval_minutes :
- These observation runs show up in the runs UI with the tag "Manually Launched" which is mis-leading. I don't know if "Auto-materialization policy" is exactly correct, but a tag that indicates that the daemon is launching these would be good
- The Target asset (in this example, raw_asset) is not visually distinguished as a source asset
- The result of these two things is that if I just look at the runs UI it looks like I'm doing a whole bunch of runs !!! :grimacing:  when in reality it is a bunch of runs, but its just observing a source. It'd be great to visually distinguish that, or maybe even present these asset observations somewhere else altogether

<img width="333" alt="image" src="https://github.com/dagster-io/dagster/assets/2798333/8bcb30fa-498a-4d37-a6ee-f126236aa89a">

**Comment by sryza** [comment]
Would it make sense to say something about "Auto-observe" instead of "Auto-materialize"?

**Comment by hellendag** [comment]
@braunjj Would this ideally show the same popover information as https://github.com/dagster-io/dagster/issues/15225?

**Comment by johannkm** [comment]
> @braunjj Would this ideally show the same popover information as https://github.com/dagster-io/dagster/issues/15225?

It can't because we don't currently have a UI for auto observations

**Comment by braunjj** [comment]
Is an auto-observe policy different than an auto-materialize policy? I think we should make this tag match whatever policy name is.
If we go with "Auto-observe" we need to allow users to filter by that as well. We currently allow you to filter runs that were launched by the auto-materialize policy.

**Comment by sryza** [comment]
> Is an auto-observe policy different than an auto-materialize policy? I think we should make this tag match whatever policy name is.

We don't have something called an "auto-observe policy". We just allow you to provide a number of minutes on an observable source asset, and your observable source asset will be auto-observed every \<that many minutes\>.

I would definitely say this is different than an auto-materialize policy.
