### ISSUE TITLE
No browser history entry created when showing latest materialisations from banner on historic view

### ISSUE THREAD

**Issue by PeterJCLaw** [dagster-io/dagster#15410]
### Dagster version

1.3.14

### What's the issue?

When looking at an older materialisation there's a warning shown that the materialisation is old and what appears to be a link to the latest values:

![image](https://github.com/dagster-io/dagster/assets/336212/66d3bf33-92e9-4ada-9908-b86923d43f14)

However that link appears to instead be implemented as a `<button>` and despite updating the url of the page (from e.g: `/assets/items?asOf=1689862000173` to `/assets/items?time=1689862000173`) no browser history entry is created. This means that the user cannot easily return to the previous view -- pressing "Back" takes the user to the previous view, from where they must remember which link they had clicked to get to the historic materialisation view.

### What did you expect to happen?

Clicking a link should act like a link and create a browser history entry. Ideally changes in url should be implemented using anchor elements so that the browser does this natively (along with all the accessibility and power-user benefits from using browser-native behaviours rather than trying to reimplement them).

I also couldn't actually see any differences in the content of the page after having clicked the link, though that may be due to there having been few differences between my runs.

### How to reproduce?

Clicking the `[View Asset]` link on a historic run of an asset will take the user to a view which has the relevant message overlay.
My asset was a partitioned asset, though I'm not expecting that to be important.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Thanks for the report!
