### ISSUE TITLE
Cannot yield events from lambda_solid

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#1544]
Currently we can only return from a `lambda_solid` and can't `yield` events such as `ExpectationResult` or `Materialization`. 

We want to be able to do this:
```
@lambda_solid(
    input_defs=[InputDefinition('num', Int)], 
    output_def=OutputDefinition(Int)),
def add_one(num):
    yield ExpectationResult(label="some_expectation", success=True)
    yield Materialization.file('/path/to/nowhere')
    return num + 1
````

But get the error:
```
dagster.core.errors.DagsterTypeCheckError: In solid "add_one" the output "result" received value <generator object add_one at 0x10d78f048> of Python type <class 'generator'> which does not pass the typecheck for Dagster type Int. Step add_one.compute.
```

Few things to check here:
- Should only allow yielding one `Output`, and throw an error if more than one is yielded
- Shouldn't allow yielding an `Output` and returning a value
- Allow non-`Output` events to be yielded even after an `Output` is yielded

**Comment by alangenfeld** [comment]
This is by design as the system stands today - when you need to do something more complicated you "upgrade" to using `@solid` which allows for the cases you listed. 

That said it is worth considering if we want to stand behind this design decision.
