### ISSUE TITLE
Dagster-pandas dataframes cannot have dates in columns

### ISSUE THREAD

**Issue by jack-pace** [dagster-io/dagster#1545]
You cannot type check a pandas dataframe using `dagster_pandas` if it has dates in the columns. Or more generally, the columns must be json serialisable.
> TypeError: Object of type 'date' is not JSON serializable
> 
> The above exception was the direct cause of the following exception:
>
> dagster.core.errors.DagsterTypeCheckError: In solid "dataframe_constant" the output "result" received value    2019-01-01
0           0 of Python type <class 'pandas.core.frame.DataFrame'> which does not pass the typecheck for Dagster type PandasDataFrame. Step dataframe_constant.compute.

MWE:
```python
import datetime

from dagster import execute_pipeline, lambda_solid, pipeline
import dagster_pandas as dagster_pd
import pandas as pd


@lambda_solid
def dataframe_constant() -> dagster_pd.DataFrame:
    return pd.DataFrame([{datetime.date(2019, 1, 1): 0}])


@pipeline
def my_pipeline():
    dataframe_constant()


if __name__ == '__main__':
    execute_pipeline(my_pipeline)
```

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D586

**Comment by alangenfeld** [comment]
thanks for another excellent bug report  😄
