### ISSUE TITLE
Support for `DbtCliResource` commands to stream logs to UI rather than raw compute logs

### ISSUE THREAD

**Issue by stkbailey** [dagster-io/dagster#15479]
### What's the use case?

In the new version of the dbt resource (dagster-dbt==0.20.2), compute logs for the CLI command are pushed to the raw compute logs interface, rather than the structured event logs (which used to be the default).

This is problematic for our setup:

1. In our hybrid EKS deployment, the compute logs are not streamed back to Dagster Cloud until completion of the job. This means, during the execution of our run, there is no visibility into its progress apart from the AssetMaterialization events.
2. Users have to do extra digging to find the logs they expect to see. Few know that the compute logs exist.

While there are some nice formatting improvements, I would prefer for this behavior to be controllable by the user, because it makes a big difference in a user's ability to oversee an ongoing dbt operation ("is it running the right models?").

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by stkbailey** [comment]
Update: It looks like we can do:

```
for raw_event in dbt.cli(["run"]).stream_raw_events():
    context.log.info(raw_event)
    for dagster_event in raw_event.to_default_asset_events(manifest=DBT_MANIFEST):
        if isinstance(dagster_event, Output):
            # manually log asset materialization stuff
            ...
```

That is a satisfactory workaround for now, although it would still be great for the stream method to support this.

```
yield from dbt.cli(["run"]).stream(log_raw_events=True)
```

**Comment by srggrs** [comment]
We have the same workflow, so I would be interested in the solution as well

**Comment by rexledesma** [comment]
Considering there is a workaround posted, and that we made improvements on compute log discoverability, I'm closing this issue.

**Comment by weberdavid** [comment]
@stkbailey Would you mind showing a bit further what exactly you do in the last part of your code, under "manually log asset materialization stuff"? We have troubles implementing it correctly.
