### ISSUE TITLE
Assets using `SpecificPartitionsPartitionMapping` fail when using asset reconciliation sensor

### ISSUE THREAD

**Issue by rob-apella** [dagster-io/dagster#15485]
### Dagster version

1.3.11

### What's the issue?

Using `SpecificPartitionMapping` in a downstream partitioned asset for a specific upstream partition throws [this](https://github.com/dagster-io/dagster/blob/f090a1e9ba72438722cc7749907fd2437c6ec4e8/python_modules/dagster/dagster/_core/definitions/partition_mapping.py#L283) error, when using `build_asset_reconciliation_sensor(asset_selection=AssetSelection.all())`

Very simple [gist](https://gist.github.com/rob-apella/44968d12051743154b6a0ad96acc4b98
) that reproduces

And Slack [thread](https://dagster.slack.com/archives/C01U954MEER/p1689960887082959 
) leading to this issue here

### What did you expect to happen?

I expect the reconciliation sensor to work as expected. It should understand the state of the requested upstream partition in order to kick off the downstream or wait for that specific partition in the upstream.

### How to reproduce?

Very simple [gist](https://gist.github.com/rob-apella/44968d12051743154b6a0ad96acc4b98
) that reproduces

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @rob-apella - I suspect this is fixed in more recent versions of Dagster, because `get_downstream_partitions_for_partitions` is implemented. If you upgrade and still run into this, would you mind reopening this?
