### ISSUE TITLE
Project: Containerization

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#155]
Work on a containerization standard. Interact with the container via a GraphQL interface. This is a block for integration into other workflow engines.

**Comment by mgasner** [comment]
#556

**Comment by mgasner** [comment]
I'm going to close this given that we now have a working draft of a spec in https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-airflow#containerizing-your-repository / API support with `dagit -q`. Probably will eventually want to break this out of dagster-airflow (for AWS batch, k8s, etc.), and provide support tools, but we can cross those bridges when we get to them and track incremental work items or changes to the working spec independently.
