### ISSUE TITLE
Outdated / wrong information in tutorial content

### ISSUE THREAD

**Issue by lydialimsetel** [dagster-io/dagster#15501]
Hi this is my first time opening issue in the project, as I'm just a newbie exploring the tool via the [tutorial](https://docs.dagster.io/tutorial/connecting-to-external-services)! 

Referring to this line in the tutorial docs: (v1.4.2)

https://github.com/dagster-io/dagster/blob/359e313f21706df6b9b069a5a0499f9699074218/docs/content/tutorial/connecting-to-external-services.mdx#L40C176-L40C192

I don't see a resources.py file being created within the resources folder, which supposedly exposes the  DataGeneratorResource? Hence I'm unable to reference it further down the steps (`from .resources import DataGeneratorResource`)

Might be I'm not understanding the instructions correctly, in which case kindly advise and consider the issue closed.

**Comment by sryza** [comment]
Thanks for the feedback @lydialimsetel.

@tacastillo @erinkcochran87 – are you able to take a look?

**Comment by lydialimsetel** [comment]
Yup, using

`from .resources.data_generator import DataGeneratorResource
`

worked for me! Thanks!
