### ISSUE TITLE
Make pipeline subselection easier

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1552]
Right now solid subselection is a bit awkward. In the UI you have to manually select solids which can get awkward with large solids. And the python API involves building a subpipeline with the awkward def build_sub_pipeline() method on PipelineDefinition.

I believe we should do something akin to dbt's model selection syntax. See https://docs.getdbt.com/docs/model-selection-syntax

This would be both in the python API, as a command line flag, and in dagit.

**Comment by mgasner** [comment]
#1367

**Comment by mgasner** [comment]
Hooray!

**Comment by mgasner** [comment]
I guess leaving this open as still to implement in the Python API and in the CLI tools

**Comment by asingh16** [comment]
I volunteer as tribute to take a crack at this when I am done with bay bikes!

**Comment by yuhan** [comment]
Python API done: #2131 https://dagster.phacility.com/D3113

**Comment by yuhan** [comment]
1. CLI: `dagster pipeline execute` and `dagster pipelien launch` now accept queries in "solid-selection". for example:

```
$ dagster pipeline execute -f many_events.py -n many_events --solid-selection "raw_file_group_admins+, raw_file_users"
```

2. solid_selection (previously called solid_subset) in preset, partition, schedule also allows selection queries
