### ISSUE TITLE
Show all user-provided tags on the runs page

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#15535]
A few months ago we released an update to the runs page that introduced new filtering and a updated table layout that hid most tags under a click in order to make this table more dense. Some users have reported that this is frustrating to have to click into the tags modal for each run.

I want to revisit this design and try to find a better balance. I think we should make a few tweaks:
- always show all user-provided tags, and display them in blue
- change the order of the tag list. We should always start with the `backfill` and `partition` system tags, then any user-provided tags (in blue) and end with a `View all {n} tags` Tags should wrap to a second line if we run out of space for all of them
- add an icon to the partition tag so it matches the backfill tag
- We should continue to hide the default system-provided tags like `image` and `agent_id`
- Allow users to pin or unpin tags from the list. We can introduce the "pin"/"unpin" action in the hover state. This configuration should be storage in localstorage so each user can configure it independently. 

**Here's a mock up:**
![image](https://github.com/dagster-io/dagster/assets/2798333/f5f086b3-0f50-4864-81ea-09d200df54ab)

**Comment by joscha** [comment]
Is this still live? I currently see a screen where it is impossible to distiguish runs of different partitions:

<img width="1418" alt="Image" src="https://github.com/user-attachments/assets/9a3e2574-5650-4a30-9029-b28a8c61c2f2" />

and it's quite inconvenient to use.

**Comment by salazarm** [comment]
@joscha 

1. Partitions should show up in the target field when used properly
<img width="928" alt="Image" src="https://github.com/user-attachments/assets/5b1a5754-6caa-4b0b-917d-4cb4118f7755" />

2. When you click on "View all tags", if you hover over the tag you want to make always visible you can click on "Show tag in table" to have it always visible.

**Comment by joscha** [comment]
@salazarm I can see now, it doesn't seem to work with `partition`: 

<img width="548" alt="Image" src="https://github.com/user-attachments/assets/ffa0a8ea-6525-4620-b01d-956a2a960ea6" />

It's there for the other standard tags. As a workaround I can possibly add a tag to the run that equals the partition, but I think it would be nice if it worked out of the box for it.

Update: I am just seeing in your screenshot that the partition shows up in `Target` for you. That is not the case for me either.

**Comment by joscha** [comment]
<img width="2112" alt="Image" src="https://github.com/user-attachments/assets/dbe58b93-1500-458b-b1b9-d0fdad9d52fb" />

manual launches of the same asset show the partition nicely. I think it might have something to do with the way this partitioned asset is launched dynamically from a sensor
