### ISSUE TITLE
Auto-Materialize if the direct upstream Asset is materialized and higher ones not

### ISSUE THREAD

**Issue by PascalStehling** [dagster-io/dagster#15536]
### What's the use case?

You have three Assets, depending on each other in a row: A->B->C. None of them is yet materialized. If B is then (manual) materialized, C should also automatically be materialized, as it does not need any direct Data from A.

As a real world example, imagine A having a Schedule, downloading data once a month and storing it in S3. B having a sensor, checking if there is new Data in S3 and processing it, if there is some. And C takes this processed data. If this setup is started and there is already data in the S3, B will run with this data (because the sensor is starting it), but C will wait for A to run (in worst case) in a month, even if it could just process the data.

### Ideas of implementation

Maybe this could be implemented with a setting/flag in the `AutoMaterializePolicy`, which indicates, that it should only look at direct connections to the asset and not further, eg: `AutoMaterializePolicy.eager(only_direct=True)`.

This same approach could also be used for Issue #15057 to materialize if only on a subset needs to be monitored to decide if to run or not eg: `AutoMaterializePolicy.eager(only_monitor=[AssetKey(), AssetKey()])`.

### Additional information

The decision, if the data is materialized, should then only depend on the AutoMaterializePolicy settings, and should not be based on how the materialization was started, either manually or by some sensor/schedule/AutoMaterialization

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @PascalStehling ! Thanks for filing this, this is high priority for us to fix in a generalized way. In addition to the issue you note, there are cases in which some asset far upstream is out of date (imagine A -> B -> ... -> C -> D, then A and C are materialized, then the logic would refuse to materialize D until the changes from A were propagated all the way down to C).

**Comment by OwenKephart** [comment]
hi! I'm closing this issue as completed, due to the reasons outlined here: https://github.com/dagster-io/dagster/issues/14628#issuecomment-1716131664
