### ISSUE TITLE
Be able to drive alternative execution engines from dagit

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1554]
It would be very nice to do multiprocess and dask execution from dagit. This would not make sense for airflow since it does not support adhoc execution.e

I would suggest we do this via the configuration system. We could allow plugins to modify the config schema in order to add an entry under the "execution" key.

**Comment by schrockn** [comment]
Re-assigning this to alex as this can live under the "instance" mandate"

**Comment by mgasner** [comment]
What is left to do here? Are you thinking about dagit UI support for this vs. config-level switching?

**Comment by schrockn** [comment]
Essentially the full story of support here once the instance refactor is complete and in concert with the hosted version. Milestone here would be hosted dagit instigating compute into a dask cluster.

**Comment by mgasner** [comment]
Closing this since we can now target any engine from dagit.
