### ISSUE TITLE
SDF support

### ISSUE THREAD

**Issue by geoHeil** [dagster-io/dagster#15569]
### What's the use case?

Besideds DBT für SQL assets also support  SDF
https://blog.sdf.com/p/introducing-sdf-the-semantic-data

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
The initial scaffold is here: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-sdf. We'll have more documentation about this soon.
