### ISSUE TITLE
docker-compose.yaml is out of date.

### ISSUE THREAD

**Issue by meyergin** [dagster-io/dagster#15586]
### Dagster version

1.4.2

### What's the issue?

When I tried to run the docker-compose project, dagit seems have been out of date(replaced by dagster-webserver).
BTW, there is no docker example of the project_fully_featured, as I cannot find a tutorial how to start a docker container user_code by grpc to sync assets' project with multi-files instead of a single file.  When i materialize a asset of the project at WebUI, the docker container daemon returns error cannot found module named "example_project". But in the cotainer user_code, it can be imported well.

### Deployment type

Docker Compose

### Deployment details
Dockerfile_dagster and workspace.yaml is the same as example

Dockerfile_use_code
```
FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

# Add repository code

WORKDIR /opt/dagster/app

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY example_project /opt/dagster/app/example_project

# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "example_project"]
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
@meyergin we'll update the compose file.

Re: the example project, it looks like you'd need to do a `pip install -e /opt/dagster/app/example_project` so that the server can find the module `example_project`.

If that doesn't work, would you mind creating a separate issue for it just so we can track the rename issue separately

**Comment by meyergin** [comment]
> @meyergin we'll update the compose file.
> 
> Re: the example project, it looks like you'd need to do a `pip install -e /opt/dagster/app/example_project` so that the server can find the module `example_project`.
> 
> If that doesn't work, would you mind creating a separate issue for it just so we can track the rename issue separately

Thanks for your reply.
after adding a dependent setup.py file in the example_project folder and execute
```
RUN pip install -e /opt/dagster/app/example_project 
```
it works now
