### ISSUE TITLE
in dbt scaffold, awkwardness with DAGSTER_DBT_PARSE_PROJECT_ON_LOAD value

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#15605]
we recommend setting `DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1`. this would lead me to believe that `DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=0` would have the opposite behavior, but it actually has the same behavior.

also, "true" might be easier to understand than "1", because users without a CS background are less likely to be familiar with binary.

**Comment by rexledesma** [comment]
- I don't think this is an issue. No users have reported encountering trouble with this.
- We have docs to explain this setup to them: https://docs.dagster.io/integrations/dbt/reference#loading-dbt-models-from-a-dbt-project
