### ISSUE TITLE
Audit uses of @pipeline and execute_solid_within_pipeline and port to execute_solid

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1561]
Find all uses like in https://dagster.phacility.com/D592 and migrate

We should be able to remove many call sites of execute_solid_within_pipeline in favor of execute_solid. I don't believe we really use execute_solids_within_pipeline to any real effect, we need something like it for solid subset execution so let's keep it around.

**Comment by helloworld** [comment]
https://dagster.phacility.com/D614
