### ISSUE TITLE
Audit type system handling of basic/built-in types and composites

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1562]
```
from dagster import Field, List, String, solid, pipeline


@solid(config={'baz': Field(List[String])})
def foo(_):
    return 'bar'
```

**Comment by schrockn** [comment]
This seems reasonable to me. What is the problem and the alternate proposal?

**Comment by mgasner** [comment]
it's very reasonable for a user to write `Field(List(String))`

**Comment by mgasner** [comment]
cf. as_dagster_type(numpy.ndarray)

**Comment by mgasner** [comment]
Tuple[Tuple[np.ndarray]]

**Comment by mgasner** [comment]
this is much improved, see: https://dagster.phacility.com/D1273

**Comment by mgasner** [comment]
https://dagster.phacility.com/D1339

**Comment by mgasner** [comment]
would also like to get Set and Tuple importable from dagster

**Comment by mgasner** [comment]
https://dagster.phacility.com/D1346

**Comment by mgasner** [comment]
Closing this after D1346.
