### ISSUE TITLE
Warn when we return items from a @pipeline that aren't on the stack

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1563]
consider:
```
@lambda_solid
def single_input_solid():
    return

@pipeline
def single_input_solid_pipeline():
    return [single_input_solid.alias('foo'), single_input_solid.alias('bar')]
```

this is wrong (it should be `return [single_input_solid.alias('foo')(), single_input_solid.alias('bar')()]`), but silently passes yielding an empty pipeline

**Comment by mgasner** [comment]
cc @alangenfeld

**Comment by dpeng817** [comment]
Closed by https://dagster.phacility.com/D4322
