### ISSUE TITLE
Cannot define Pythonic resources in RunConfig()

### ISSUE THREAD

**Issue by Magniko** [dagster-io/dagster#15656]
### Dagster version

1.4.2

### What's the issue?

This is a continuation of https://github.com/dagster-io/dagster/issues/13915
It took a while for me to migrate to the Pythonic resource configuration as it wasn't really necessary back then, but after updating to a newer Dagster version in which I would need to define Pythonic configurations, I thought it would be best to do the same to resources, rather than having them defined as a simple dictionary.
Upon doing so, I assumed that I could now include them in the *RunConfig* objects to make configuration of job runs easier.

However, the exact same error is raised. At first  I thought I might have done something wrong with the resource class, but I have even followed examples in the docs(see code below), and starting Dagster yields errors when using any resources in *RunConfig* that does not have the key **io_manager**.

### What did you expect to happen?

I expected the new Pythonic resources to integrate fine with RunConfig so that I would not have to pass them separately in the job decorator parameters, thus allowing all job configs to be made in a separate file.

### How to reproduce?

The code below is taken from https://docs.dagster.io/concepts/resources#using-ops-and-jobs

```
from dagster import job, op, ConfigurableResource, RunConfig

class MyConnectionResource(ConfigurableResource):
    username: str

    def request(self, endpoint: str) -> str:
        return endpoint			# just making it simple

config_test  = RunConfig(
	resources={"my_conn": MyConnectionResource(username="my_user")},
)


@op
def update_service(context):
    context.resources.my_conn.request("/update")

# this is how our team have been executing jobs and ops(previously pipelines and solids) since we began using Dagster
@job(config=config_test)
def update_service_job():
    update_service()
```

### Deployment type

Local

### Deployment details

Just executing this code as a script. It happens when the config is pre-loaded.

**Comment by OwenKephart** [comment]
Hi @Magniko -- this is reasonable feedback, and we've seen other users with similar confusions in this area. RunConfig is intended to be something that can be flattened into a regular string-based dictionary (as it is also possible to pass run configuration via other interfaces (such as the UI), which would be a challenge in implementing this approach.

For now, the intended usage is to pass resources into the job decorator directly, e.g. `resource_defs={"my_conn": MyConnectionResource(username="my_user")}`.
