### ISSUE TITLE
Dagster Cloud does not accept underscore as part of a deployment name

### ISSUE THREAD

**Issue by pengw0048** [dagster-io/dagster#15665]
### Dagster version

1.4.2

### What's the issue?

On Dagster Cloud UI https://<my_org>.dagster.cloud/prod/cloud-settings/deployments, I cannot create a deployment with an underscore in its name, though the error prompt includes underscore as a valid character.

<img width="506" alt="image" src="https://github.com/dagster-io/dagster/assets/81975673/00c0a454-3822-4581-b051-1e714a7502bd">

### What did you expect to happen?

I expect to be able to create a deployment named `a_b`.

At the moment, the UI won't allow me to.

### How to reproduce?

Go to deployments settings, create a deployment, input `a_b` in the name text box.

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Hi @pengw0048, this error message needs to be corrected. Thanks for surfacing. This should be fixed in our next cloud release. We recommend that you use a hyphen instead of an underscore.
