### ISSUE TITLE
Python dependency toolchain

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1567]
We are quickly losing control of managing our dependencies. Adding modules is hard. Very easy to screw up things.

Namely we should have a canonical location of our dependency mappings, and then manage artifacts like setup.py, requirements.txt, tox files, our dev install scripts, and so forth.

- Our setup.py's should be as permissive as possible. We want to minimize our versioning requirements.
- We should be able to generate and manage multiple environment snapshots. This could be in the form of requirements.txt. Or we can think about using pipenv to get lock files. But we will be undoubtedly be interested in running ci/cd on a variety of environments, in addition to multiple python version.
- It is really easy to do local dev installs (i.e. pip install -e module) in the wrong order, which results in downloading the public version of a module instead of the local install. This can cause very difficult-to-catch bugs.
- A scaffolding script would also be nice to do module setup.

Here is a (almost certainly non-exhaustive list) of what you need to do when you add a module. https://dagster.phacility.com/w/module-checklist/

**Comment by mgasner** [comment]
cf https://github.com/Kwpolska/python-project-template
