### ISSUE TITLE
Maintain consistency between str and pathlib.Path in dagster-dbt

### ISSUE THREAD

**Issue by mjkanji** [dagster-io/dagster#15689]
### Dagster version

1.4.3

### What's the issue?

In `dagster-dbt` after the v1.4 API update, the `@dbt_assets` decorator expects `manifest` to be of type `pathlib.Path` but `DbtCliResource`, for example, expects `project_dir` to be a string.

`dbt_manifest` above is the only example I've come across recently which uses `pathlib` anywhere. And while I'd love improved `Path` support, I think consistency is more important. The project seems to have generally used `str` paths everywhere, so I'd recommend changing `dbt_manifest` here to also expect a `str` -- unless there are project-wide plans to adopt `pathlib` at large (which would be a much appreciated feature).

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@rexledesma mind taking a look at this one? Any objection to accepting strings for the manifest argument?
