### ISSUE TITLE
Downstream tests for universal_pathlib

### ISSUE THREAD

**Issue by ap--** [dagster-io/dagster#15726]
Hello dagster team,

dagster is one of the larger dependents of universal_pathlib, and I would like to ensure that future releases of universal_pathlib won't accidentally break dagsters use cases.

1. Could you provide me with a minimal set of tests that I can add to the third party test suite of universal_pathlib, to detect breaking changes early?

2. dagster is currently using private attributes in UPath to access storage_options for filesystems. The new bugfix release of UPath restores this private API for local paths: see fsspec/universal_pathlib#131

3. I created an issue fsspec/universal_pathlib#129 to address how access to storage_options could be provided and would appreciate feedback. I just want to avoid a XY problem.

(additional cross-reference: dagster-io/dagster#15017)

Cheers,
Andreas 😃

**Comment by sryza** [comment]
@danielgafni this might be already covered by the discussion on the other issue, but do you have thoughts on this?

**Comment by danielgafni** [comment]
I don't think Dagster is doing anything special with `universal-pathlib`, now that #15732 is merged we are only using the public API.

**Comment by sryza** [comment]
awesome - I'm going to close this. @ap-- feel free to reopen if you think there's outstanding stuff to do.
