### ISSUE TITLE
Structured log viewer experience rough on a small screen

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1573]
No dividers between columns. No column resizing.  All this makes for a rough initial experience when you kick off a job. This on my 15" macbook

<img width="1423" alt="Screenshot 2019-07-16 17 13 08" src="https://user-images.githubusercontent.com/28738937/61343033-38081c00-a801-11e9-99ad-e516ac7d91af.png">

**Comment by mgasner** [comment]
Added dividers and resizing
