### ISSUE TITLE
Add a hint to point users to autocomplete in config editor

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1576]
@Eronarn

 I tried using the auto completion features here, rather than just pasting in the YAML dictionary. This worked fine, except in the case where I was entering a new dict and hadn't typed anything yet. I would've expected a way to see the available fields for that dict without having to first type a character (like popping up automatically before I hit tab).

**Comment by bengotow** [comment]
Addressed in https://dagster.phacility.com/D1509!

**Comment by bengotow** [comment]
Resolved by D1509
