### ISSUE TITLE
Organize config editor buttons

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1577]
Right now we have buttons all over the UI - here:

![image](https://user-images.githubusercontent.com/609349/61414021-c7fda280-a8a1-11e9-8055-177205b5124d.png)

Here:

![image](https://user-images.githubusercontent.com/609349/61414028-cc29c000-a8a1-11e9-91ae-f7e8321fc02c.png)

and here:

![image](https://user-images.githubusercontent.com/609349/61414033-d0ee7400-a8a1-11e9-8819-efb3d165dbd6.png)

It seems like it'd be nice to consolidate these in one place (and potentially make their relationships clearer; e.g. the presets button uses the same icon as the modes icon but doesn't have a label)

**Comment by mgasner** [comment]
It is also really unclear what a bunch of these buttons do as they don't have labels
