### ISSUE TITLE
Clarify how to access numeric EnvVars via EnvVar.int(str)

### ISSUE THREAD

**Issue by hbruch** [dagster-io/dagster#15787]
### Dagster version

dagster, version 1.4.3

### What's the issue?

I want to configure a database port as environment variable. [IntEnvVar](https://github.com/dagster-io/dagster/blob/56cb48057db2361d54e64477e436f5ce679ee669/python_modules/dagster/dagster/_config/field_utils.py#L477) seems to be intended for such a use case, though neither the documentation does not include any example for numeric EnvVars, not is it published in `dagster\__init__.py` in addition to [`EnvVar`](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/__init__.py#L92).

### What did you expect to happen?

~~ I wonder if `IntEnvVar` should not be public? ~~ _Edited:_ Configuring numeric EnvVars should be documented better, see below

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hbruch** [comment]
Oh, got it. `EnvVar.int('ENV_VAR_NAME')` should do it. I suggest documenting this e.g. in the [using-environment-variables-and-secret section](https://docs.dagster.io/guides/dagster/using-environment-variables-and-secrets#from-dagster-configuration), e.g. providing an example for numeric env vars.

This issue should be tagged `documentation` instead of `bug` then.

**Comment by MeganBeckett** [comment]
Just came across this and I specifically stopped using `EnvVar` because it didn't work for ints (ie. database port as mentioned above). So, adding this to the documentation would be great for reference.
