### ISSUE TITLE
The disorderliness of the integrations bar picture really bothers me

### ISSUE THREAD

**Issue by Jimsparkle** [dagster-io/dagster#15781]
### What's the issue or suggestion?

Why do you do this to us...

![integrations-bar-for-readme](https://github.com/dagster-io/dagster/assets/25099425/32538811-943c-49e7-87be-3630f36303e8)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @Jimsparkle are you able to provide a link to where you're seeing this?

**Comment by frasermarlow** [comment]
Thanks @Jimsparkle  - I located it (in the README.md file!) and will replace it shortly.

**Comment by schrockn** [comment]
Top candidate for my favorite issue! Thanks @Jimsparkle can't unsee it now and glad we are getting it fixed. 🙏🏻🙏🏻🙏🏻

**Comment by rexledesma** [comment]
Resolved with https://github.com/dagster-io/dagster/pull/15783.
