### ISSUE TITLE
Make CLI and Unit Test log experience reasonable post all logging changes

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1578]
This is an issued related to our two log channels. We eliminate the free text logs corresponding to outputs here https://dagster.phacility.com/D661 which improves dagit, but these no longer log to the standard log stream. We should come up for a story around this.

**Comment by mgasner** [comment]
yep, we need either to collapse the two log streams or more sharply distinguish them

**Comment by schrockn** [comment]
This is a fairly broad mandate, but in addition to having great logging in dagit for the 0.6.0 launch, we should also have a good CLI and unit-testing experience.

**Comment by prha** [comment]
I think this is done...
