### ISSUE TITLE
`dagster.execute_job` frequently hangs after completion in `watch_orphans`

### ISSUE THREAD

**Issue by markfickett** [dagster-io/dagster#15791]
### Dagster version

dagster, version 1.3.6

### What's the issue?

For local execution, we run the pipeline via a command-line wrapper that uses `dagster.execute_job`. Fairly often (1 in 10 or more?), after the last op has printed its final output, the program hangs. If I wait a minute or two and then hit `^C` I get this stack trace:

```
Traceback (most recent call last):
  File "/home/me/project/.direnv/python-3.10.11/lib/python3.10/site-packages/dagster/_core/execution/watch_orphans.py", line 42, in <module>
  File "/home/me/project/.direnv/python-3.10.11/lib/python3.10/site-packages/dagster/_core/execution/watch_orphans.py", line 42, in <module>
    watch(sys.argv[1:])
  File "/home/me/project/.direnv/python-3.10.11/lib/python3.10/site-packages/dagster/_core/execution/watch_orphans.py", line 38, in watch
    watch(sys.argv[1:])
  File "/home/me/project/.direnv/python-3.10.11/lib/python3.10/site-packages/dagster/_core/execution/watch_orphans.py", line 38, in watch
    time.sleep(1)
KeyboardInterrupt
    time.sleep(1)
KeyboardInterrupt
```

### What did you expect to happen?

I expect the program to exit normally within a second or two of the last op finishing.

### Deployment type

Local

### Deployment details

We use a hybrid deployment on EKS, but this issue surfaces during local execution.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
what OS and python version? 

> For local execution, we run the pipeline via a command-line wrapper that uses dagster.execute_job

Can you include some more details about how this command-line wrapper is set-up? Since I don't believe we have seen other reports of this issue, there may be relevant details to how the process / subprocesses are managed.

**Comment by markfickett** [comment]
Versions:
```
$ python --version
Python 3.10.11
$ uname -a
Linux thinkpad-ubuntu 5.14.0-1029-oem #32-Ubuntu SMP Fri Mar 18
```

Here's what the wrapper script looks like (trimming out some other resource configs).

```py
    run_config = {
        "execution": {
            "config": {
                "multiprocess": {
                    "max_concurrent": 36,
                },
            },
        },
    }
    run_config["execution"]["config"]["multiprocess"]["start_method"] = {
        "forkserver": {
            "preload_modules": [
                # Preload our main application entry point for Dagster,
                # which avoids repeating all the expensive imports.
                "orchestration.main.local",
            ],
        },
    }
    result = execute_job(
        reconstructable(define_battery_data_job_local),
        run_config=run_config,
        instance=DagsterInstance.get(),
    )
    if not result.success:
        raise RuntimeError(
            "Pipeline execution failed: non-success result from Dagster execute_job."
        )
```

Thanks for checking on this. I'll see if I can [use py-spy](https://github.com/benfred/py-spy#dump) to get a stack sample next time it's hanging. I'm assuming the `watch_orphans` stack from when I `^C` to kill it is not that useful.

**Comment by markfickett** [comment]
I think this was actually just due to an `@op` that I thought had its output connected, but its output was not included in the list of outputs returned from a subgraph. It happened to be an `@op` that didn't print anything so I thought the program was idle.

I [made a suggestion for a UI change](https://dagster.slack.com/archives/C01U5LFUZJS/p1693509508492999) to make it easier to notice cases like this.

It could also be handy if, when you ^C Dagster in a situation like this, it tells you that there was still a subgraph's `@op` executing.

But, closing this ticket since I don't think Dagster was erroneously hanging. Thanks again for checking out the ticket!
