### ISSUE TITLE
Clarify single-run backfill context method usage

### ISSUE THREAD

**Issue by clairelin135** [dagster-io/dagster#15804]
### What's the issue or suggestion?

Reported by a user (Spencer Nelson):

> The backfill docs say this about backfill runs that work on multiple partitions in one run:
> > If your code uses any of the partition_key, asset_partition_key, asset_partition_key_for_output, or asset_partition_key_for_input context methods or properties, you'll need to update it to use methods or properties like asset_partitions_time_window, asset_partition_key_range, asset_partition_keys, asset_partitions_time_window_for_output, asset_partition_key_range_output, asset_partitions_time_window_for_input, or asset_partition_key_range_for_input instead.

> That’s a lot of methods and properties. I am not sure which I need to check. What are the scenarios for when they are used? Are there others that aren’t listed? The vague language (“methods or properties like…”) is pretty ominous.

It would be helpful to simplify this language and describe the use cases for when people might be using these context methods. Something like the following:

> Assuming that you've previously structured your code with the assumption that each run targets only one partition, you're probably using `context.partition_key` to get the currently executing partition. Similarly, the `context.asset_partition_key` / `context.asset_partition_key_for_output` methods assume your run is executing on a single partition.
> 
> If you instead want to enable executing a run across multiple partitions, you'll need to replace `context.partition_key` with `context.asset_partition_key_range` to fetch all of the executing partitions. There are convenience methods similar to `context.asset_partition_key_range` that provide the partition keys in a different format: `asset_partitions_time_window`, `asset_partition_keys`.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
This will be addressed by https://github.com/dagster-io/dagster/pull/16710
