### ISSUE TITLE
Add automaterialize_policy to graph_multi_asset

### ISSUE THREAD

**Issue by smackesey** [dagster-io/dagster#15837]
@OwenKephart @johannkm is there any reason we don't currently have this or is it just an oversight?

**Comment by Milias** [comment]
Same question here!

Also [`multi_asset`](https://docs.dagster.io/_apidocs/assets#dagster.multi_asset) doesn't seem to support it either?

**Comment by OwenKephart** [comment]
Hi @Milias ! There is an `automation_condition` argument to `AssetSpec`, which is now the recommended way of constructing `multi_assets`, i.e.:

```python
from dagster import multi_asset, AssetSpec, AutomationCondition

@multi_asset(specs=[AssetSpec("a", automation_condition=AutomationCondition.eager()), ...])
def my_multi_asset(): ...
```

(There is also an `auto_materialize_policy` argument, but the `AutomationCondition` APIs are replacing these concepts as of the 1.8 release: https://github.com/dagster-io/dagster/discussions/22811)

**Comment by Milias** [comment]
Thanks a lot @OwenKephart! I will look into that documentation.
