### ISSUE TITLE
Misleading "Process starting..." log pane loading indicator when reviewing past runs in dagit

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1584]
<img width="1440" alt="Screen Shot 2019-07-19 at 10 33 01 AM" src="https://user-images.githubusercontent.com/427016/61553971-a53dcc00-aa10-11e9-8418-16f41d34f10e.png">

**Comment by mgasner** [comment]
Punting this

**Comment by bengotow** [comment]
https://dagster.phacility.com/D726
