### ISSUE TITLE
Website navbar bug

### ISSUE THREAD

**Issue by moghadas76** [dagster-io/dagster#15853]
### Dagster version

Website

### What's the issue?

When you hover on the "sign in" button, the navbar height will be changed!!
![Screenshot from 2023-08-15 16-37-28](https://github.com/dagster-io/dagster/assets/23231913/3d7a1d27-59c0-4317-a6c0-56e2d37feaa9)

### What did you expect to happen?

the navbar height will not be changed!! 

### How to reproduce?

Just visit the website

### Deployment type

Other

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Thanks for the report!

**Comment by hellendag** [comment]
Fix is live in prod.
