### ISSUE TITLE
Enable external URL navigation from event log messaging

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#15862]
### What's the use case?

When logging messages containing URLs using `context.log`, would be helpful to enable highlight clicking to navigate to the external URL

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by eifuentes** [comment]
thanks @prha, just to add some additional context, I currently use the `context.log` path to log helpful AWS resource URLs for quick debugging and sanity checks. A great example is logging a Sagemaker training job that was kicked off as part of a dagster op.
