### ISSUE TITLE
Confusing concepts

### ISSUE THREAD

**Issue by moghadas76** [dagster-io/dagster#15890]
### What's the issue or suggestion?

Over-engineer architecture design makes confusing how to encompass our requirements with your library. Please write a clear documentation 0-100.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Hi! Sorry to hear about your confusion. We're always actively working on reducing the mental load and improving the narrative of applying Dagster concepts. Notably, this is one of our priorities this year and we're working on making this cleaner and clearer!

**Comment by sryza** [comment]
I'm going to close this for now because it's not specific enough to be directly actionable.

@moghadas76 if you have more specific feedback, we would love to hear it and could either place it in this issue or a separate.

**Comment by moghadas76** [comment]
As a suggestion, Please implement sample object recognition project. It is
vague when to use asset and when to use op, job, graph backend and etc. .
Our team got confused and believe that learning curve is high. As a former
project manager, I can offer you to contribute your document structure
if you explain the detailed architecture.
