### ISSUE TITLE
Support dbt style `--defer` natively in the Dagster framework

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#15911]
### What's the use case?

From [dbt's docs](https://docs.getdbt.com/reference/node-selection/defer):

> Defer is a powerful feature that makes it possible to run a subset of models or tests in a [sandbox environment](https://docs.getdbt.com/docs/environments-in-dbt) without having to first build their upstream parents. This can save time and computational resources when you want to test a small number of models in a large project.

With Dagster's asset graph, can we generalize this feature to support a data sandbox for any data asset. This will essentially supercharge our existing capabilities [with Dagster Cloud Branch Deployments](https://docs.dagster.io/dagster-cloud/managing-deployments/branch-deployments).

### Ideas of implementation

From https://dagster.io/blog/dagster-master-plan:

> We can build a “forkable” version of the asset graph (like “git branch” for data assets). When combined with [Dagster's branch deployments](https://docs.dagster.io/dagster-cloud/managing-deployments/branch-deployments) and branchable storage layers like [Snowflake’s zero-copy clones](https://thinketl.com/snowflake-zero-copy-cloning/) or [LakeFS](https://lakefs.io/), this will allow data engineers to create "copy on write" staging environments for every pull request that read from production and write to staging. This will massively improve developer velocity, especially for ML model development

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@rexledesma I wonder if there's a low budget version of this where we give guidelines on how to write a job that records a bunch of `AssetMaterialization` events that have the data from the prod deployment?

**Comment by alangenfeld** [comment]
Focused on the testing changes in branch deployments context called out in the "whats the use case" section, work was done to support `--defer` in that context.

* [`DbtProject`](https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.DbtProject)  has a `state_path` argument for where to expect a state artifacts.  
* [`DbtCliResource`](https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.DbtCliResource) has `get_defer_args` (and `get_state_args`) which allow conditionally including cli flags if the `state_path` contains a `manifest.json`.  You can see this demonstrated in [this test](https://github.com/dagster-io/dagster/blob/138ce7e2069119ad4764e89faa71e3c5a1654afd/python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py#L453-L484)
* `dagster-cloud ci dagster-dbt project manage-state` can be used by for Dagster+ users to handle automatically uploading state from production and downloading it in branch deployments. Shown in github action [here](https://github.com/dagster-io/dagster-cloud-action/blob/2206ffeb07694390e7eef2ed01d7f6c816778a1b/github/serverless/dbt/deploy.yml#L72C13-L72C112).

`--defer` is used for other dbt features as well, so I encourage folks who had a different interpretation of what native support looks like to file issues that call out specifically what you are looking for.
