### ISSUE TITLE
Consolidate dagster_event_from_dict with event logging path

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1592]
fyi @natekupp unless there's a strong reason I'd rather not have this alternate event stream pathway just or dask

**Comment by mgasner** [comment]
Should be doubly unnecessary now that we have the instance

**Comment by natekupp** [comment]
dagster_graphql.client should be replaced by new CLI

**Comment by natekupp** [comment]
@alangenfeld is fixing right now
