### ISSUE TITLE
build_schedule_from_dbt_selection() doesn't filter based on provided assets

### ISSUE THREAD

**Issue by marcilj** [dagster-io/dagster#15936]
### Dagster version

dagster, version 1.4.5

### What's the issue?

When we use the function `build_schedule_from_dbt_selection()` the provided `dbt_assets=[]` have no impact on the list of assets that will be in the schedule. It load all the available assets in the manifest.

### What did you expect to happen?

I expect that the assets loaded with `@dbt_asset` decorator and provided to the function would be the only one that would get select even if the default configuration for `dbt_select` is `dbt_select: str = "fqn:*"`.

For example if we take this code

```python
@dbt_assets(
    manifest=dbt_manifest_path,
    select="a b",
)
def a_b_dbt_assets(context: OpExecutionContext, dbt: DbtCliResource):
    yield from dbt.cli(["build"], context=context).stream()

@dbt_assets(
    manifest=dbt_manifest_path,
    select="c",
)
def c_dbt_assets(context: OpExecutionContext, dbt: DbtCliResource):
    yield from dbt.cli(["build"], context=context).stream()

dbt_c_schedule = build_schedule_from_dbt_selection(
    dbt_assets=[c_dbt_assets],
    job_name="should_only_run_c_dbt_model_job",
    cron_schedule="0 * * * *",
)
```

I would except that `dbt_c_schedule` create a schedule only for the dbt model `c` since I provided a list of `prefiltered` models to the `build_schedule_from_dbt_selection()` function and the `dbt_select: str = "fqn:*"` should be applied to the filtered set of models. 

### How to reproduce?

```python
@dbt_assets(
    manifest=dbt_manifest_path,
    select="tag:hourly",
)
def hourly_dbt_assets(context: OpExecutionContext, dbt: DbtCliResource):
    yield from dbt.cli(["build"], context=context).stream()


@dbt_assets(
    manifest=dbt_manifest_path,
    select="tag:daily",
)
def daily_dbt_assets(context: OpExecutionContext, dbt: DbtCliResource):
    yield from dbt.cli(["build"], context=context).stream()

dbt_daily_schedule = build_schedule_from_dbt_selection(
    dbt_assets=[daily_dbt_assets],
    job_name="dbt_daily_job",
    cron_schedule="0 * * * *", 
)

dbt_hourly_schedule = build_schedule_from_dbt_selection(
    dbt_assets=[hourly_dbt_assets],
    job_name="dbt_hourly_job",
    cron_schedule="0 * * * *",
)

```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @rexledesma
