### ISSUE TITLE
Omitted outputs should probably be a structured event

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1594]
https://github.com/dagster-io/dagster/blob/50385acd935b7414de232e142051409e868cee94/python_modules/dagster/dagster/core/execution/plan/compute.py#L85

instead of just unstructured `'Solid {solid} did not fire outputs {outputs}'`

**Comment by natekupp** [comment]
Looks like this has been fixed?

**Comment by sryza** [comment]
Closing this as part of housekeeping. Feel free to reopen if you think it would be helpful.
