### ISSUE TITLE
``op_tags`` not being added to partitioned asset runs

### ISSUE THREAD

**Issue by rubenbriones** [dagster-io/dagster#15945]
### Dagster version

1.4.7

### What's the issue?

When adding ``op_tags`` to a partitioned asset with an AutoMaterializePolicy, like the next example:

````py
@asset(
    deps=[create_partitions],
    partitions_def=symbols_partitions_def,
    auto_materialize_policy=AutoMaterializePolicy.eager(
        max_materializations_per_minute=10000
    ),
    op_tags={"2_run_per_value": "firstrate_forex_prices"},
)
def load_symbol(context) -> None:
    context.log.info(f"Loading data for: {context.partition_key}")
````

The ``op_tags`` are not being added to the Runs generated,

### What did you expect to happen?

I would expect that the tags set in ``op_tags`` where attached to each partition Run of the asset.

Before dagster 1.4, instead of using `AutoMaterializePolicy `I was using a `build_asset_reconciliation_sensor`, like the next one:

````py
sensor= build_asset_reconciliation_sensor(
    name="load_symbol_sensor",
    asset_selection=AssetSelection.assets(load_symbol),
    run_tags={"2_run_per_value": "load_symbol"},
)
````

And the `run_tags` were correctly attached to each partition Run generated by the sensor. But now, without the `build_asset_reconciliation_sensor` I don't know hoe to do it.

Thank you so much in advance for your help.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
thanks for bringing this to our attention! @johannkm  can you take a look?

**Comment by mmutso-boku** [comment]
`op_tags` on a partitioned asset still does not work. Version 1.4.12.

**Comment by johannkm** [comment]
op_tags don't get applied to the runs, they apply to the underlying steps in a run. This can be used for things like custom resources with the k8s_job_executor.

We're tracking the feature of tagging runs based on asset tags here: https://github.com/dagster-io/dagster/issues/8979
