### ISSUE TITLE
Solid subset selection button not appearing in dagit

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1596]

**Comment by schrockn** [comment]
<img width="1254" alt="Screenshot 2019-07-23 18 22 21" src="https://user-images.githubusercontent.com/28738937/61757772-d30b7380-ad76-11e9-8dcc-bac00bd7cab2.png">

o brother where art thou

**Comment by mgasner** [comment]
Can reproduce in Chrome, working in Firefox
