### ISSUE TITLE
Ability to set dagster/dagit options using environment variables

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#1597]
I'm running dagit in a Docker container. It would be handier to be able to set CLI options like `--host` and `--port` using environment variables. Since dagster and dagit both use Click for CLI handling, I'd like to request that they specify a value for `auto_envvar_prefix` on the root command context, which will automatically read options from environment variables.

For example, if dagit specified `auto_envvar_prefix='DAGIT'`, it'd be possible to set the host option with an environment variable like `DAGIT_HOST=0.0.0.0`, in addition to a CLI argument like `--host 0.0.0.0`.

[Click API Documentation — Context](https://click.palletsprojects.com/en/7.x/api/#context)

**Comment by mgasner** [comment]
This is a great suggestion, we'll implement later this week.

**Comment by alangenfeld** [comment]
dagit - https://dagster.phacility.com/D699
