### ISSUE TITLE
Strange layout issues in log viewer

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1599]
<img width="1265" alt="Screenshot 2019-07-24 14 29 03" src="https://user-images.githubusercontent.com/28738937/61830222-757f3180-ae1f-11e9-89ee-d41678e6c638.png">

This happens when full-screen with 125% zoom on my laptop (macbook pro 15")

100%

<img width="1277" alt="Screenshot 2019-07-24 14 30 42" src="https://user-images.githubusercontent.com/28738937/61830294-a0698580-ae1f-11e9-9e6e-997b861dd023.png">

**Comment by mgasner** [comment]
Can't reproduce after https://dagster.phacility.com/D690 on Chrome or Firefox
