### ISSUE TITLE
Unify environment file handling between dagster and dagster-airflow

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1601]
For the dagster-airflow scaffold command we have different features for specifying config files than vanilla dagster. Dagster-airflow takes the option "-c" and also cannot handle multiple instances of it (which is necessary when you want to capture files that cannot be capture by a single glob)

**Comment by natekupp** [comment]
Done, `dagster-airflow scaffold` now uses the same CLI as Dagster https://dagster.phacility.com/D743

**Comment by mgasner** [comment]
🙌
