### ISSUE TITLE
code smell principle

### ISSUE THREAD

**Issue by moghadas76** [dagster-io/dagster#16028]
### Dagster version

1.4.5

### What's the issue?

When defining asset as a function, the name violate python clean code
`
@asset
def asset_name():
    ....
`
while python clean_code supposed to be:
`
@asset
def get_asset_name():
    ....
`

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
hi @moghadas76 - you are free to call your asset functions whatever you like. If you'd like to name the function something other than what appears in the UI, you can also use the `name` parameter to `@asset`

```python
@asset(
   name="asset_name"
)
def get_asset_name():
    ...
```
