### ISSUE TITLE
Validate resource type when using Pythonic resources

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#16035]
### Dagster version

latest

### What's the issue?

The following is valid, when it should not be:

```
@dbt_assets(...)
def my_dbt_assets(context: OpExecutionContext, dbt: DbtCliResource):
    yield from dbt.cli(["run"], context=context)
    
defs = Definitions(
    assets=[my_dbt_assets],
    resources={
        "dbt": NotDbtCliResource(...)
    },
)
```

The annotation does not match the actual resource passed to the definition. We should not rely on duck typing here.

### What did you expect to happen?

A `isinstance` check or equivalent for resources passed into ops/assets should occur before execution.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by benpankow** [comment]
It's definitely frustrating that users can accidentally end up in this position. That being said, hard erroring might not be desirable for cases where a user is mocking their resources etc.

A reasonable compromise might be to log some sort of warning that could help a user figure out why their code doesn't work, without explicitly preventing cases where the user does want the duck type behavior.

**Comment by sryza** [comment]
> That being said, hard erroring might not be desirable for cases where a user is mocking their resources etc.

Like with `MagicMock`? Could they just use the `spec` argument?
