### ISSUE TITLE
Need to port additional black options to arc version

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1604]
In particular translate the -S and -N options (included in the Makefile version of this) to the config that arc expects

**Comment by schrockn** [comment]
Arc automatically applying the following changes:

![Screenshot 2019-07-25 10 53 01](https://user-images.githubusercontent.com/28738937/61896723-64d7c580-aeca-11e9-9cf5-527e3a07683a.png)

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D702
