### ISSUE TITLE
Support versioned dbt models

### ISSUE THREAD

**Issue by kirkhansen** [dagster-io/dagster#16046]
### Dagster version

dagster, version 1.4.7

### What's the issue?

When using versioning, dagster-dbt doesn't correctly resolve selected models, and the code location won't load.

```
Invariant failed. Description: The set of asset keys with dependencies specified in the asset_deps argument must equal the set of asset keys produced by this AssetsDefinition. 
asset_deps keys: {AssetKey(['seed', 'dbt', 'silver_seed', 'crop_d_v2']), AssetKey(['seed', 'dbt', 'silver_seed', 'breeding_zone_d_v1']), AssetKey(['seed', 'dbt', 'silver_seed', 'crop_d_v1'])} 
 expected keys: {AssetKey(['seed', 'dbt', 'silver_seed', 'crop_d_v2']), AssetKey(['seed', 'dbt', 'silver_seed', 'breeding_zone_d_v1'])}
```

In this case, The deps were correct, but the expected_keys dropped the v1 version for some reason.

### What did you expect to happen?

I expected the code location to load with a job that would materialize all the assets under the specified schema.

### How to reproduce?

Create two dbt models. Make one with 2 versions, and have the second version depend, `ref`, the first. Make another dbt model that depends on the latest version of the first table. Try to `load_assets_from_dbt_manifest` and you'll get an error where dagster expects less keys than it should.

### Deployment type

None

### Additional information

FWIW, if you do a "poor man's" versioning and split each of these into separate model files and use the same dagster asset loading code, dagster gets it right.

This may also be related to #16005: I was able to get around this for now by adding a custom dbt translator with a get_asset_key like

```python
from dagster import AssetKey
from dagster_dbt import DagsterDbtTranslator
from typing import Any, Mapping

class CustomDagsterDbtTranslator(DagsterDbtTranslator):
    def get_asset_key(self, dbt_resource_props: Mapping[str, Any]) -> AssetKey:
        base_key = super().get_asset_key(dbt_resource_props)
        version = dbt_resource_props.get("version")
        
        if not version:
            return base_key
        else:
            # version should be the last element in the unique_id
            path = base_key.path
            path[-1] = f"{path[-1]}_v{version}"
            return AssetKey(path)
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by Kamal-Klm** [comment]
It would be great if dagster could just follow how dbt's `ref("model")` macro resolves model versions. Dagster can pick only the version which `ref` resolves.
