### ISSUE TITLE
Please update DagsterGraphQLClient docs with Dagster Cloud example

### ISSUE THREAD

**Issue by markfickett** [dagster-io/dagster#16068]
### What's the issue or suggestion?

The docs on the Python GraphQL client: https://docs.dagster.io/_apidocs/libraries/dagster-graphql#graphql-dagster-graphql do not explain how to use it with Dagster Cloud or do auth.

It would be great to incorporate the instructions from here: https://github.com/dagster-io/dagster/discussions/7772 and copied below:

```py
from dagster_graphql import DagsterGraphQLClient
from gql.transport.requests import RequestsHTTPTransport
url = "https://yourorg.dagster.cloud/prod"
token = "your_token_here" # a User Token generated from the Cloud Settings page in Dagster Cloud. Note: User Token, not Agent Token
client = DagsterGraphQLClient(url, transport=RequestsHTTPTransport(url=url+"/graphql", headers={"Dagster-Cloud-Api-Token": token}))
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Resolved with https://github.com/dagster-io/dagster/pull/15974.
