### ISSUE TITLE
Better error message when config field is empty

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1606]
Right now we just emit `dagster.check.CheckError: Invariant failed. Description: Cannot specify empty config for ConfigMapping` - this should be a clearer error message.

![image](https://user-images.githubusercontent.com/609349/61907490-6f9e5480-aee2-11e9-9d44-ea6ef977ab93.png)

**Comment by mgasner** [comment]
Actually, I think it should be possible to have an empty config here. If the config mapping function for a composite solid doesn't itself need any config to set all the config values for the child solids (i.e., if you're using a composite solid to reify a set of config values, as in this example), then it should be ok.

**Comment by mgasner** [comment]
cc @kinghuang

**Comment by mgasner** [comment]
https://dagster.phacility.com/D1368
