### ISSUE TITLE
Unhandled TypeError can occur getting a solid's config

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#1607]
I declared a composite solid with an optional config named `foo` (relates to #1606). Then, I used it in a pipeline, and didn't specify a `config` key under the solid in the environment because I didn't need to override the config's default value for `foo`.

```
@composite_solid(
    config_fn=lambda _, cfg: {
        'prefix_value': {'config': {'prefix': '_id_'}},
    },
    config={
        'foo': Field(str, is_optional=True, default_value='')
    }
)
def prefix_id(id):
    return prefix_value(id)
```

```
solids:
  prefix_id:
    inputs:
      id:
        value: "12345"
```

This results in the exception `TypeError: 'NoneType' object is not iterable` in [_evaluate_composite_solid_config()](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/types/evaluator/evaluation.py#L252) because a frozendict is being created from the config which is evaluating to None.

```
mapped_config_value = solid_def.config_mapping.config_fn(
	ConfigMappingContext(run_config=context.run_config),
	# ensure we don't mutate the source environment dict
	frozendict(context.config_value.get('config')),
)
```

Putting in an empty config in the environment works.

```
solids:
  prefix_id:
    config: {}
    inputs:
      id:
        value: "12345"
```

Perhaps `config` should default to an empty dictionary instead of None.

```
mapped_config_value = solid_def.config_mapping.config_fn(
	ConfigMappingContext(run_config=context.run_config),
	# ensure we don't mutate the source environment dict
	frozendict(context.config_value.get('config', {})),
)
```

**Comment by helloworld** [comment]
https://dagster.phacility.com/D753
