### ISSUE TITLE
Failure to load a graph with multiple partition definitions and observable source assets

### ISSUE THREAD

**Issue by aroig** [dagster-io/dagster#16088]
### Dagster version

1.4.8

### What's the issue?

The piece of dagster code below combining observable source assets with multiple partition definitions fails to load, with a an error about unconnected inputs:

```
Traceback (most recent call last):
  File "/home/abdo/opt/tmp/dagster-bug/test.py", line 40, in <module>
    defs = dg.Definitions(
           ^^^^^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/definitions_class.py", line 422, in __init__
    self._created_pending_or_normal_repo = _create_repository_using_definitions_args(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/definitions_class.py", line 292, in _create_repository_using_definitions_args
    @repository(
     ^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/decorators/repository_decorator.py", line 161, in __call__
    else CachingRepositoryData.from_list(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/repository_definition/repository_data.py", line 346, in from_list
    return build_caching_repository_data_from_list(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/repository_definition/repository_data_builder.py", line 191, in build_caching_repository_data_from_list
    for job_def in get_base_asset_jobs(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/assets_job.py", line 98, in get_base_asset_jobs
    build_assets_job(
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/assets_job.py", line 233, in build_assets_job
    return graph.to_job(
           ^^^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/graph_definition.py", line 641, in to_job
    return JobDefinition.dagster_internal_init(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/job_definition.py", line 278, in dagster_internal_init
    return JobDefinition(
           ^^^^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/decorator_utils.py", line 195, in wrapped_with_pre_call_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/job_definition.py", line 154, in __init__
    self._graph_def.get_inputs_must_be_resolved_top_level(self._asset_layer)
  File "/home/abdo/opt/tmp/dagster-bug/.venv/lib/python3.11/site-packages/dagster/_core/definitions/graph_definition.py", line 277, in get_inputs_must_be_resolved_top_level
    raise DagsterInvalidDefinitionError(
dagster._core.errors.DagsterInvalidDefinitionError: Input 'asset_b' of op 'AssetX' has no way of being resolved. Must provide a resolution to this input via another op/graph, or via a direct input value mapped from the top-level graph. To learn more, see the docs for unconnected inputs: https://docs.dagster.io/concepts/io-management/unconnected-inputs#unconnected-inputs.
```

### What did you expect to happen?

I'd expect the reproducer code below to load without error.

### How to reproduce?

This is a reproducer, as minimal as I could make it.

```python
import dagster as dg
import warnings

warnings.filterwarnings("ignore", category=dg.ExperimentalWarning)

class B:
    pass

class X:
    pass

part_a = dg.StaticPartitionsDefinition(["a1", "a2"])
@dg.observable_source_asset(
    name="AssetA",
    partitions_def=part_a,
)
def asset_a():
    pass

part_b = dg.StaticPartitionsDefinition(["b1", "b2"])

@dg.observable_source_asset(
    name="AssetB",
    partitions_def=part_b,
)
def asset_b():
    pass


@dg.asset(
    name="AssetX",
    partitions_def=part_b,
    ins={
        "asset_b": dg.AssetIn("AssetB"),
    },
)
def asset_x(asset_b: B) -> X:
    return X()

defs = dg.Definitions(
    assets=[asset_a, asset_b, asset_x],
)
```

In order to trigger the error, `python reproducer.py`.

### Deployment type

Local

### Additional information

I've spent some time trying to track this problem down. I don't have a complete picture, but it looks like the following happens:

- `build_asset_job` [here](https://github.com/dagster-io/dagster/blob/044c2cb1729a8dbc27fdfc37a0543be69b9b4742/python_modules/dagster/dagster/_core/definitions/assets_job.py#L101) runs twice, for partitions_def's `part_a` and `part_b`.  The crash happens for the `part_a` case, where `assets=[]` and `source_assets = [asset_a, asset_b, asset_x]`.
- Then, while constructing the job, we reach [here](https://github.com/dagster-io/dagster/blob/044c2cb1729a8dbc27fdfc37a0543be69b9b4742/python_modules/dagster/dagster/_core/definitions/job_definition.py#L154)
- Inside that test, `node.get_inputs_must_be_resolved_top_level` [here](https://github.com/dagster-io/dagster/blob/044c2cb1729a8dbc27fdfc37a0543be69b9b4742/python_modules/dagster/dagster/_core/definitions/graph_definition.py#L271) returns an input for the node associated to `asset_x`. However, for this input [this](https://github.com/dagster-io/dagster/blob/044c2cb1729a8dbc27fdfc37a0543be69b9b4742/python_modules/dagster/dagster/_core/definitions/graph_definition.py#L276) check fails, and triggers the exception.

It looks like the problem is that `node.get_inputs_must_be_resolved_top_level` should really not return any input, as we are passing all the assets as `source_assets`, even if `asset_x` is not a SourceAsset.

Maybe [this](https://github.com/dagster-io/dagster/blob/044c2cb1729a8dbc27fdfc37a0543be69b9b4742/python_modules/dagster/dagster/_core/definitions/assets_job.py#L213) should actually be using `resolved_source_assets`?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Have you tried using the `deps` argument, instead of the `ins` parameter?

The issue is `asset_b` as an observable source asset should be returning a data version, not an object of the data version, so it can't be "loaded" into `asset_x` through and IO Manager.

**Comment by aroig** [comment]
> Have you tried using the deps argument, instead of the ins parameter?

I had not thought of that. Just tested it, same error.

> The issue is asset_b as an observable source asset should be returning a data version, not an object of the data version, so it can't be "loaded" into asset_x through and IO Manager.

hmm... I don't understand this IOManager explanation. Even though the function `asset_b` in the observable source asset definition returns a version, as an asset I want it to be loadable via an IOManager. In fact, the following variation of the code

```python
import dagster as dg
import warnings

class B:
    pass

class X:
    pass

part_b = dg.StaticPartitionsDefinition(["b1", "b2"])

@dg.observable_source_asset(
    name="AssetB",
    partitions_def=part_b,
)
def asset_b():
    pass


@dg.asset(
    name="AssetX",
    partitions_def=part_b,
    ins={
        "asset_b": dg.AssetIn("AssetB"),
    },
)
def asset_x(asset_b: B) -> X:
    return X()

defs = dg.Definitions(
    assets=[asset_b, asset_x],
)
```
works exactly as expected, when supplied with an IOManager that can handle types B and X.

As I explained in the original message, the problem happens when Definitions tries to create an empty job for `part_a` partition definition. In that case, it passes all 3 assets as `source_asset` argument in `build_asset_job` [here](https://github.com/dagster-io/dagster/blob/044c2cb1729a8dbc27fdfc37a0543be69b9b4742/python_modules/dagster/dagster/_core/definitions/assets_job.py#L101). That call should reasonably construct an empty job, with only observations, yet it does fail with the unconnected input error. That looks like a bug.

**Comment by aroig** [comment]
> Maybe [this](https://github.com/dagster-io/dagster/blob/044c2cb1729a8dbc27fdfc37a0543be69b9b4742/python_modules/dagster/dagster/_core/definitions/assets_job.py#L213) should actually be using resolved_source_assets?

Also I forgot to mention that doing the change suggested above appears to solve the problem. Not sure if it is the right fix though.
```python
        node_defs = list(filter(None, [asset.node_def for asset in [*resolved_source_assets]]))
```

After this change, I can trigger an observation for `AssetA`. However, if then I try to trigger an observation for `AssetB`, it would fail with this

```
dagster._check.CheckError: Invariant failed. Description: Can't supply a PartitionedConfig for 'config' with a different PartitionsDefinition than supplied for 'partitions_def'.
```

That seems to be a separate problem.
