### ISSUE TITLE
Document storage requirements for Airflow & other non-local executors

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1610]

**Comment by mgasner** [comment]
incl bucket config requirements for Airflow / S3 intermediate store

**Comment by catherinewu** [comment]
this seems a bit vague and we do have https://docs.dagster.io/deploying/aws#using-s3-for-intermediates-storage and https://docs.dagster.io/overview/io-managers/io-managers docs now. cc @yuhan feel free to re-open
