### ISSUE TITLE
Refresh mode definition rendering in sidebar

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1611]
No specific feature requests here, but in general the mode side panel could be much more useful. Right now it is really hard to tell what is going on with the resources, since the resource type is not rendered, only the key and the config schema

**Comment by bengotow** [comment]
Hey! I was just digging in to this a bit and I'm not sure I follow. It looks like the only fields that exist on resources are being displayed - do we need to expose the resource type in GraphQL? 

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/1037212/62069738-94eed380-b1fe-11e9-9bbe-b1696e040da1.png">

**Comment by natekupp** [comment]
Closing - feel free to reopen if you think we still need this @schrockn
