### ISSUE TITLE
Enable oauth authentication flow for Databricks jobs launched with dagster-databricks

### ISSUE THREAD

**Issue by zyd14** [dagster-io/dagster#16126]
### What's the use case?

Databricks now has the ability to delegate permissions to a [service principal](https://docs.databricks.com/en/dev-tools/service-principals.html) for interacting with their REST APIs in an automated / programmatic fashion. When using a service principal it is possible to authenticate using an oauth client ID and secret. The `databricks-sdk` supports authentication with oauth credentials, and will automatically refresh the temporary token retrieved using the client ID and secret. 

The security and auditing benefits of using a service principal with temporary credentials via oauth are obvious, and in order to support secure best practices we should expose this as an optional way to authenticate with Databricks.

### Ideas of implementation

Oauth client ID and secret could be exposed at the same configuration level that exposes the API token configuration. A runtime check would ensure either the API token, or both oauth client ID and secret were provided by the user.

### Additional information

One blocker to implementing this is that the `DatabricksClient` class still maintains (deprecated) support for the `databricks-api` and databricks-cli` clients, which only take an API token. If the oauth configuration was exposed and used on the step launcher, the clients implemented from `databricks-api` and `databricks-cli` would not be able to be initialized, leaving public attributes of the step launcher in an unexpected state.

One solution would be to throw an exception if a user tries to access the `_api_client` or `_client` properties when the `DatabricksClient` has been initialized with oauth creds. This would maintain backwards compatibility for now for users still using tokens who may have a dependency on those attributes. Although in general I'd expect the number of users who might have a dependency on that in the first place to be pretty small.

If that feels too messy it could also just wait until the next minor release if the plan is to drop the `databricks-api` and `databricks-cli` clients. I'm happy to put in a PR for this, just let me know if the error-throwing solution is reasonable for now or if y'all would rather wait until the next minor release and implement it clean.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
> One solution would be to throw an exception if a user tries to access the _api_client or _client properties when the DatabricksClient has been initialized with oauth creds.

This seems reasonable to me.
