### ISSUE TITLE
Asset with optional output is not recognized by its `output_name`

### ISSUE THREAD

**Issue by jeanineharb** [dagster-io/dagster#16128]
### Dagster version

dagster, version 1.4.3

### What's the issue?

I have an asset with an optional output, and a multi-asset depending on that output's asset:

```python
@asset(output_required=False)
def my_asset(...):
    ...
    yield Output({"key": "value"}, output_name="asset_name")


@multi_asset(
    ins={"asset_name": AssetIn("my_asset")},
    outs={"multi_1": AssetOut(), "multi_2": AssetOut(), "multi_3": AssetOut()},
)
def my_multi_asset(context: OpExecutionContext, asset_name: dict):
   ...
```

Whenever I specify the `output_name`  for the first asset's optional output, I get the following error:
`dagster._core.errors.DagsterInvariantViolationError: Core compute for op "my_asset" returned an output "asset_name" that does not exist. The available outputs are ['result']`
When I remove the` output_name` , it all works perfectly.

It seems to me that the `output_name` is not taken into account when provided for optional outputs.

### What did you expect to happen?

I would expect to be able to name the optional output by providing an `output_name`, and reference it elsewhere with the same name.

### How to reproduce?

Follow this template to reproduce the bug:

```python
@asset(output_required=False)
def my_asset(...):
    ...
    yield Output({"key": "value"}, output_name="asset_name")


@multi_asset(
    ins={"asset_name": AssetIn("my_asset")},
    outs={"multi_1": AssetOut(), "multi_2": AssetOut(), "multi_3": AssetOut()},
)
def my_multi_asset(context: OpExecutionContext, asset_name: dict):
   ...
```

### Deployment type

Local

### Additional information

Another person is also impacted by this issue, cf. [Slack thread](https://dagster.slack.com/archives/C01U954MEER/p1691510276927449).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @jeanineharb - to get the behavior you're looking for, I believe this should work:

```python
@asset(output_required=False, name="asset_name")
def my_asset(...):
    ...
    yield Output({"key": "value"})
```

The `output_name` parameter of `Output` is for telling Dagster that the output you're yielding corresponds to a particular output that you've already defined (e.g. a key in the dictionary of `AssetOut`s that you pass to `@multi_asset`), not for associating a new name with the output.

**Comment by jeanineharb** [comment]
Thank you for the clear explanation @sryza!
