### ISSUE TITLE
Layout issues with long items in the metadata boxes

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1616]
![Screenshot 2019-07-27 17 39 46](https://user-images.githubusercontent.com/28738937/62000820-a4064200-b095-11e9-9791-1c943983242a.png)

**Comment by mgasner** [comment]
this is a consequence of the fix to https://github.com/dagster-io/dagster/issues/1603 - i am unsure how to use flexbox to get something that looks good for both cases (long keys and long values) but will play around a little bit. we might need to introduce some kind of manual linebreaking / hyphenation algo for long keys.
