### ISSUE TITLE
Incorrect rendering of input event in dagit

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1617]
Running the airline demo ingest pipeline. See erroneous "See Full Message" button here.

![Screenshot 2019-07-27 17 43 43](https://user-images.githubusercontent.com/28738937/62000835-22fb7a80-b096-11e9-8edb-2b7749397537.png)

And strange output here. 

![Screenshot 2019-07-27 17 43 48](https://user-images.githubusercontent.com/28738937/62000836-33135a00-b096-11e9-9fe4-d066f8ee2bd7.png)

**Comment by mgasner** [comment]
The erroneous Full Message button is appearing because the scrollHeight of the row (incl. the SolidColumn) is larger than the height of the row (i.e., it's overflowing) -- this happens when the content in the SolidColumn is taller than the content in the message field.

**Comment by mgasner** [comment]
https://dagster.phacility.com/D721
