### ISSUE TITLE
Add copy-paste button to error modal

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1619]
Copy and paste button to be able to grab entire error text could be nice.

![Uploading Screenshot 2019-07-27 19.02.08.png…]()

**Comment by schrockn** [comment]
![Screenshot 2019-07-27 19 02 08](https://user-images.githubusercontent.com/28738937/62001239-1e888f00-b0a1-11e9-9b74-60904c4f6bc2.png)

**Comment by mgasner** [comment]
https://dagster.phacility.com/D720
