### ISSUE TITLE
DuckDBPandasIOManager is not thread safe and is prone to SQL injection

### ISSUE THREAD

**Issue by mvanaltvorst** [dagster-io/dagster#16248]
### Dagster version

1.4.11

### What's the issue?

I tried to do a backfill with approx 3.5k hourly partitions using the DuckDBPandasIOManager as an IO manager. Halfway through, all my jobs started failing because of the following error:

```duckdb.IOException: IO Error: Could not set lock on file "<snip>.db": Resource temporarily unavailable```

### What did you expect to happen?

I suspect DuckDBPandasIOManager does not take into account that it can happen that two jobs want to write (and read) data to the same file simultaneously, which can corrupt data. 

### How to reproduce?

Run many jobs which write dataframes to the same parquet file and backfill with a high `max_concurrent_runs`.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mvanaltvorst** [comment]
Is there a thread safe alternative IO manager I could use? Or do I have to write my own one to interact with e.g. a hosted PostgreSQL server?

**Comment by sryza** [comment]
Hi @mvanaltvorst - unfortunately this is a limitation of DuckDB that I don't believe we have the ability to impact on our own. The workaround, as you mentioned, is to limit the max concurrency.

Regarding SQL injection, the security model we operate under is that people defining assets have permission to mutate them in any way.  I.e. if you could write:

```python
@asset(metadata={"columns": [sneaky_injection_that_does_x]})
def table2(table1):
    ...
```

you could also just write

```python
@asset
def table2(table1):
    execute_sql(sql_that_does_x)
    ...
```

**Comment by mvanaltvorst** [comment]
Thank you @sryza. Do you know if Dagster provides any thread-safe IO managers? Additionally, I think it might be worthwhile to mention in the docs that the DuckDB IO manager can corrupt your data.

**Comment by sryza** [comment]
BigQuery and Snowflake support high concurrency, so they shouldn't experience the same issues.

**Comment by sryza** [comment]
Another option would be to do a single-run backfill: https://docs.dagster.io/concepts/partitions-schedules-sensors/backfills#single-run-backfills

**Comment by mvanaltvorst** [comment]
Additionally, the fact that the IO manager has full access to execute SQL queries isn't the issue per se. The issue is that column names are not correctly sanitised. If you use a column name which contains "--", and you use string formatting to put this into a SQL query, DuckDB is going to think that the rest of the query is a comment and your runs fail. I do not think that is desirable and it is easy to avoid by correctly sanitising your inputs.

**Comment by mvanaltvorst** [comment]
I think this issue highlights the importance of the following issue: https://github.com/dagster-io/dagster/issues/14080. It would be the only thread-safe local IO manager Dagster has.
