### ISSUE TITLE
Cursor jumping around when hitting "enter" key in Launchpad in Firefox (Dagster Cloud)

### ISSUE THREAD

**Issue by zyd14** [dagster-io/dagster#16244]
### Dagster version

1.4.10

### What's the issue?

There's still some unfortunate bugs in the UI when using Firefox. In the Launchpad, when I hit enter at the end of a line which is the first line in a nested block, it variously de-indents or indents the current line and creates a newline, while keeping the cursor at the same line. Sometimes it indents the current line when hitting enter at the end of the line.

If the cursor is at the beginning of the line, the text following the cursor on the same line will drop down a line to the left rule, while the cursor stays at the same line and is dedented one or many times.

Before hitting the enter key, my launchpad looks like this:
![Screenshot 2023-08-31 at 10 04 14 AM](https://github.com/dagster-io/dagster/assets/1015576/53d51817-d13a-4af2-96bc-4d2abfe0da61)
After hitting the enter key, the line the cursor is on is indented, and the cursor stays on the same line. A newline is also created:
![Screenshot 2023-08-31 at 10 04 33 AM](https://github.com/dagster-io/dagster/assets/1015576/d14e94e2-9df1-4432-a79e-e7c887c7b707)
Hitting enter a second time (after the indent and newline) seems to work as expected.

### How to reproduce?

Open a launchpad with existing configuration and try adding a newline with the cursor at the end of a line.

### Deployment type

Dagster Cloud

### Additional information

I can't reproduce the issue with a local Dagster deployment, it only seems to occur in Dagster Cloud launchpad views.

My Firefox version is: 116.0.3 (64-bit). This is on a Mac M1.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Getting this in front of our UI folks

**Comment by hellendag** [comment]
Confirmed repro, looks broken in Chrome too. Thanks for the report.

**Comment by hellendag** [comment]
Working on a fix for this now. The change should also take care of https://github.com/dagster-io/dagster/issues/14409.
