### ISSUE TITLE
Better message for object store operations

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1626]
<img width="932" alt="Screenshot 2019-07-28 19 25 39" src="https://user-images.githubusercontent.com/28738937/62017966-8b695b00-b16d-11e9-8afa-ef539910520e.png">

This message could be a lot better. Like "stored interemediate at location {blah}" or something

**Comment by mgasner** [comment]
hmm, this feels like a regression

**Comment by schrockn** [comment]
Ok! Let's discuss in person today or tmrw

**Comment by mgasner** [comment]
i mean, i think it was working and now isn't. i think i have a fix.

**Comment by mgasner** [comment]
https://dagster.phacility.com/D727
