### ISSUE TITLE
View Full Message not responding to click in airline demo

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1628]
![Screenshot 2019-07-28 19 40 40](https://user-images.githubusercontent.com/28738937/62018453-a0df8480-b16f-11e9-9643-47622eab2155.png)

**Comment by schrockn** [comment]
Click on "View Full Message" and nothing happens

**Comment by bengotow** [comment]
Hmm, I'm able to reproduce this if I click the 7px on the very right edge of the button (which is under the drag handle for the column), but in that case the button doesn't highlight either so I think something else may be going on.

**Comment by mgasner** [comment]
Can't reproduce
