### ISSUE TITLE
Undefined name 'query' in resources.py

### ISSUE THREAD

**Issue by cclauss** [dagster-io/dagster#1636]
[flake8](http://flake8.pycqa.org) testing of https://github.com/dagster-io/dagster on Python 3.7.1 @natekupp

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py:58:29: F821 undefined name 'query'
                    query = query.encode('utf-8')
                            ^
./python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py:77:29: F821 undefined name 'query'
                    query = query.encode('utf-8')
                            ^
2     F821 undefined name 'query'
2
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by cclauss** [comment]
From the context, it looks like these lines should both read: __sql = sql..encode('utf-8')__

**Comment by mgasner** [comment]
Thanks very much!

**Comment by mgasner** [comment]
https://dagster.phacility.com/D750
