### ISSUE TITLE
Allow for fine grained rules/configurations in auto materialization policies

### ISSUE THREAD

**Issue by tha23rd** [dagster-io/dagster#16361]
### What's the use case?

Two use cases I'd like to address:
1. Backfills triggering auto materializations
2. Waiting to materialize until ALL upstreams have updated

### Ideas of implementation

I am proposing two enhancements to the current auto materialization policies which would significantly improve the robustness and accuracy of our data pipelines.

**Selective Ignoring of Backfill Runs for Auto Materialization**: In our specific use-case, we do not require a materialization triggered by a backfill run to instigate an auto materialization on downstream assets. Consequently, it would be highly beneficial if there was an option like IgnoreBackfillRuns that could be applied to an asset's policy. This would prevent the asset from auto materializing when an upstream asset has been materialized by a run tagged as backfill or ranged. This feature would provide us with greater control over the materialization process, ensuring that downstream assets are not unnecessarily materialized during backfill operations.

**Delaying Materialization Until All Upstream Assets Have Updated**: At present, an asset can be materialized as soon as any of its upstream assets have been updated. This can occasionally result in a non-partitioned table being in a transient state, containing incomplete or incorrect data. This poses a significant issue for dashboards built on these tables, as they may report inaccurate information until the asset has been fully updated (i.e., all of its upstream assets have completed their updates). To circumvent this, it would be desirable if the auto materialization policy could include a detailed provision to specify which assets (or all) must be fully updated before initiating a new materialization run. This would ensure that the materialized data is always consistent and accurate, thereby improving the reliability of our data pipelines and the reports generated from them.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @tha23rd ! For (1), this is actually newly possible with:

```python
from dagster import AutoMaterializePolicy, AutoMaterializeRule

my_policy = AutoMaterializePolicy.eager().with_rules(
    AutoMaterializeRule.skip_on_all_parents_not_updated(),
)
```

In other words, it adds a new potential reason that materialization should be skipped (some of its parents have not been updated since the last materialization).

For (2), one thing I'm curious about in that vein though is what the future looks like for the assets downstream of the backfilled assets. Are these generally unpartitioned assets (and therefore will just get fully up to date whenever they're next materialized), or are they partitioned assets which will remain in an unbackfilled state for a (potentially) long time? I do understand the immediate goal of having a backfill be a more isolated entity which doesn't trigger follow-on work, but I'm just trying to get a better sense of the desired end state.

**Comment by tha23rd** [comment]
Hey Owen, just confirming:

Did you mean (2) is currently possible with the code snippet you shared?

To explain more about 1:
We have two types of backfills that will typically be triggered:
- Those that are completely automated and will encompass the entire DAG of the table or tables changed. These are triggered anytime a dbt model is modified/created
- One off backfills of a single asset, or even a single partition within a single asset

For the first type of backfill, since we encompass the entire DAG, we don't really need to worry about any downstream assets being in an unpartitioned state.

For the second type of backfill, we want to provide the flexibility to our Data Engineers to decide when data should propagate downstream. Here this rule would provide the benefit of leaving that decision totally up to our DEs.
----
Separately - we'd like to be able to bump up our "materialization requests per minute" parameter so that our pipeline can self heal, without fear of a rogue backfill kicking off a bunch of runs.

**Comment by OwenKephart** [comment]
@tha23rd Ah yep, reversed the order of those in my head somehow, and thanks for the extra context!

re: "we want to provide the flexibility to our Data Engineers...", do you have a sense of the scope of what situations they'd want to have their downstreams update under?

Would it just be "always update in response to a backfill" or "never update in response to a backfill" (and the DE will handle manually running things when necessary)? One fairly straightforward solution might be to just add a new skip rule ("skip on parent was backfilled" or something along those lines), just want to evaluate if that truly captures all the behaviors you might want.

Another similar thing along those lines would involve the response to manual runs in general (i.e. someone kicks off an ad-hoc materialization of an asset). Seems like similar arguments could be made for the value of that behavior, so perhaps a more general "skip on parent materialization type" rule could be useful.

**Comment by tha23rd** [comment]
"do you have a sense of the scope of what situations they'd want to have their downstreams update under" - only when manually specified in the backfill they're kicking off

One interesting solution here could be to make it tag based? "never update in response to a backfill" _unless_ it has some tag attached.

I am a bit worried that "skip on parent materialization type" might be tough to dial in

**Comment by OwenKephart** [comment]
Agree that a tag-based solution makes sense here (in reality, the "parent materialization type" such as sensor, schedule, AMP, backfill is just an amalgamation of some system tags). As a rough pass, something like:

```python
AutoMaterializeRule.materialize_on_parent_updated(
    blacklist_run_tags={"dagster/backfill", "dagster/user"},
    whitelist_run_tags={"my_amp_override"},
)
```

could do the trick. Does that align with what you were imagining?

The main addition to this is that we'd probably want to also allow users to specify the _values_ of those tags that they want to filter on, similar to: https://docs.dagster.io/guides/limiting-concurrency-in-data-pipelines#configuring-run-level-concurrency

**Comment by OwenKephart** [comment]
Closing this issue in favor of a more targeted: https://github.com/dagster-io/dagster/issues/16691
