### ISSUE TITLE
ImportError: cannot import name 'ExternalPipeline' from 'dagster._core.host_representation' 

### ISSUE THREAD

**Issue by Minivolk02** [dagster-io/dagster#16384]
### Dagster version

latest

### What's the issue?

ImportError: cannot import name 'ExternalPipeline' from 'dagster._core.host_representation' 

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Hi @Minivolk02, how are you running into this issue? I believe `ExternalPipeline` was renamed to `ExternalJob` in 1.3.3
