### ISSUE TITLE
Dagster Cloud slack alert template

### ISSUE THREAD

**Issue by caio-eiq** [dagster-io/dagster#16393]
### Dagster version

1.21.1

### What's the issue?

There was a template update for the Dagster Cloud slack alerts which is displaying the color red for both success and failures.

![image](https://github.com/dagster-io/dagster/assets/111778420/249cea59-4e3b-4405-b665-87e82dca8d47)
 

### What did you expect to happen?

Successful jobs should be in the color green
Failed jobs should be in the color red

### How to reproduce?

- Create a "catch all" Dagster Cloud alert policy
- Run a job to completion and check the slack alert notification. It will be displayed in a red color.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Hi @caio-eiq -- thanks for reporting, we'll add this issue to our backlog and fix it when we get the chance

**Comment by jasonicarter** [comment]
I'd like to add a formatting issue as well. The previous version was more condense with 2 columns which I personally prefer. 

**Old version**
<img width="1058" alt="image" src="https://github.com/dagster-io/dagster/assets/5205478/7b372fba-fd81-4ab2-91f7-154474bbc9cf">

**Current version**
<img width="1055" alt="image" src="https://github.com/dagster-io/dagster/assets/5205478/3d83c6e6-0e30-4342-9504-fb0e03c21c7d">

**Comment by bmarcj** [comment]
I agree about the two columns. The additional information - particularly duration - I prefer though.

**Comment by dpeng817** [comment]
Hey folks - the original issue here is fixed regarding red/green not displaying properly for failures. Slack formatting will likely be changing further, and this will be taken into account - thanks for the feedback.

**Comment by caio-eiq** [comment]
Can confirm the red/green template is not being rendered correctly, thanks for the quick fix.

**Comment by dpeng817** [comment]
Going to close this now as the original issue is resolved; feel free to open new issues for the other formatting concerns regarding information density.
