### ISSUE TITLE
Support interrupting execution

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1639]
Airflow operators can provide an `on_kill` method (here’s theirs for the bash operator):

```
    def on_kill(self):
        self.log.info('Sending SIGTERM signal to bash process group')
        os.killpg(os.getpgid(self.sub_process.pid), signal.SIGTERM)
```

It would be nice for our library solids, resources, and other integrations to support this kind of interrupt behavior. For example, EMR has APIs to kill an in-flight job, we should support those directly

**Comment by mgasner** [comment]
#830

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D1118 I think its just missing GraphQL & Dagit

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D1189 you can do it from the run history page

**Comment by schrockn** [comment]
yeah we just need to add it to the main run page

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
