### ISSUE TITLE
Census Management API sync run response statuses have changed

### ISSUE THREAD

**Issue by ldnicolasmay** [dagster-io/dagster#16428]
### Dagster version

1.4.10

### What's the issue?

Census has changed it's Management API again, changing the sync run API response's `status` values. The sync run status `"preparing"` has been deprecated for `"queued"`. See the table under the Request/Response JSON examples here: [https://docs.getcensus.com/basics/developers/api/sync-runs#get-sync_runs-id](https://docs.getcensus.com/basics/developers/api/sync-runs#get-sync_runs-id)

Currently the dagster-census integration is expecting a sync run status of `"preparing"`, but is now getting a `"queued"`. Since `"queued"` isn't a status that's expected in the integration's [`resources.py`](https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-census/dagster_census/resources.py), the sync run state falls to default `"completed"` status ([here](https://github.com/dagster-io/dagster/blob/8997056b4e2d6937878c1a1a6c276d3d76671da1/python_modules/libraries/dagster-census/dagster_census/resources.py#L177C13-L177C18)), and downstream assets are triggered before the Census sync run asset completes.

I've included snapshots that shows how this now runs unexpectedly. You can see most of the asset observation metadata is `null`.

<img width="1394" alt="Screenshot 2023-09-11 at 13 04 17" src="https://github.com/dagster-io/dagster/assets/36526433/1a8759bd-b889-46a6-a975-cb7616b0a507">

<img width="935" alt="Screenshot 2023-09-11 at 13 19 08" src="https://github.com/dagster-io/dagster/assets/36526433/0c31c652-c94d-4b96-8c50-68a7af20c028">

### What did you expect to happen?

The Census sync run should capture the new `"queued"` sync run status, instead of the deprecated `"preparing"` status, and then poll the sync run until it's completed.

### How to reproduce?

Unfortunately, you need to have a Census account to reproduce this. If you do, you can easily reproduce this by triggering any Census sync run.

### Deployment type

Docker Compose

### Deployment details

Deployment details aren't very relevant here since this is an integration bug.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Thanks for putting up the fix! Closing this out now
