### ISSUE TITLE
Use the Python logging API instead of our custom context loggers

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1643]
- surface (some of) the Python LogRecord stuff in the dagit UI

**Comment by sk4la** [comment]
Just a quick note from the Slack thread:

> [...] as a user I’d prefer to have a logging implementation that strives not to stray too much from the reference implementation (aka. the `logging` module). The main benefit I see (based on my own experience) is the ability to “catch” the logger from ouside of Dagster without the need to pass around the context object.

So yes, 👍 for this!

**Comment by mgasner** [comment]
hmm, if you just want to be able to do `logging.getLogger("dagster")`, that should be fairly easy for us to support. the initial impetus behind having a separate explicit logging path is that `import logging; logging.info(...)` is pretty magical and hard to reason about

**Comment by krisuj** [comment]
I'm looking around for a solution to this. I have dagster solids/pipelines wrapping around my functions that is currently using python native logging. i.e. logger=logging.getLogger(__name__), and logging.info("bla bla bla...") statements in my modules. Is it possible to display/view these log messages within dagit/dagster in general?

**Comment by sryza** [comment]
I wrote up a discussion topic with a set of proposals on how to evolve Dagster's logging to address some of the issues that have come up on this GH issue: https://github.com/dagster-io/dagster/discussions/4195.

Community members who have upvoted this issue - @krisuj @fj-sanchez @netcitizenrus @balazsdukai @j-hulbert - I would love to hear your opinions on which is the best direction to take.

I think the fundamental question here is: is it a fool's errand to try to route all logs to Dagster's structured log?  Even if we build an adapter for Python logging, what if someone depends on code that logs to stdout or executes a subprocess that's not in Python?  Would it be preferable to just make it the norm to yield plaintext logs?

**Comment by sryza** [comment]
Recent changes enable Python logging without the custom context loggers. This is documented here: https://docs.dagster.io/concepts/logging/python-logging.
