### ISSUE TITLE
Improve raw logs UI

### ISSUE THREAD

**Issue by leahpadgett** [dagster-io/dagster#16452]
<img width="1284" alt="Untitled" src="https://github.com/dagster-io/dagster/assets/11398699/a201a2ff-2c49-4983-ab28-eb61e9a6aba9">

- Many people don’t realize that `stdout` and  `stderr` exist
- Have to click on Raw Compute logs icon, then filter to an op

Design: https://www.figma.com/file/OnaH8ynIsPg3yh7BpwyDQX/Logging-Improvements?type=design&node-id=11%3A19&mode=design&t=jRhpOutHNvg8RG0T-1

Related: https://www.notion.so/Make-stderr-more-discoverable-in-the-UI-d2619dc5bfcf4a0ab4969d952d838765

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/16471.
