### ISSUE TITLE
AMP ignores partition mapping when mapping from dynamic partitions to unpartitioned

### ISSUE THREAD

**Issue by dmsfabiano** [dagster-io/dagster#16450]
### What's the use case?

The use case of the feature is to be able to auto-materialize assets **only** when the specific upstream dependency is updated.

Pre-requisite:
- I have asset A which is a dynamically partitioned asset
- I have asset B which has an upstream dependency with a `SpecificPartitionsPartitionMapping` of asset A say (`partition_a`)

Current behavior:
- if asset A generates a new partition, say `partition_b`, then; 
- asset b would auto materialize again, even though that it has as an upstream dependency only `partition_a`

This causes wasted time and resources when an asset should not be partitioning

### Ideas of implementation

Ideally, we would be able to have a parameter to let dagster know to auto-materialize the asset only with the Specific mapping is updated

### Additional information
discussed on #16392 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @dmsfabiano ! This looks like a bug where we're ignoring the partition mapping on the asset when mapping from DynamicPartitionsDefinitions to unpartitioned assets. Should be a quick fix so we can get this into next week's release.

**Comment by dmsfabiano** [comment]
@OwenKephart Would it be possible for the UI to show a different graph path when a specific partition is selected?

I find that the UI at the moment doesn't really show the dependency to one specifically selected partition

**Comment by OwenKephart** [comment]
Hi @dmsfabiano -- closing this as resolved. This repro is currently working as expected (after adding partitions "a", "b", "c", and "d", materializing c or d has no effect, and materializing a or b results in the unpartitioned asset being materialized):

```python
from dagster import (
    SpecificPartitionsPartitionMapping,
    DynamicPartitionsDefinition,
    AutoMaterializePolicy,
    asset,
    AssetIn,
    Nothing,
)


@asset(partitions_def=DynamicPartitionsDefinition(name="hoo"))
def foo():
    pass


@asset(
    ins={
        "foo": AssetIn(
            dagster_type=Nothing,
            partition_mapping=SpecificPartitionsPartitionMapping(partition_keys=["a", "b"]),
        )
    },
    auto_materialize_policy=AutoMaterializePolicy.eager(),
)
def bar():
    pass

```

Let us know if you have any further issues here! Re: your question around the UI, that is being tracked here: https://github.com/dagster-io/dagster/issues/15720. Definitely something that would be useful, although not particularly simple to implement
