### ISSUE TITLE
dagster-webserver metadata plots do not respect user's timezone preference

### ISSUE THREAD

**Issue by giovannipcarvalho** [dagster-io/dagster#16499]
### Dagster version

dagster, version 1.4.12

### What's the issue?

Changing the `User settings > Timezone` preference does not affect the time-axis in metadata plots.
The plots seem to always follow the browser-reported timezone.  Other parts of the UI seem to respect
the settings, such as last materialization date, the activity overview timeline, etc.

### What did you expect to happen?

Changing user settings > timezone in the UI (dagster-webserver) should affect the time-axis in metadata plots.

### How to reproduce?

Modify the timezone preference and observe that the time-axis for metadata plots are not affected accordingly.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Is this still broken for you?

**Comment by giovannipcarvalho** [comment]
I just checked and it seems to be working correctly on the latest version (1.7.15).
