### ISSUE TITLE
Misconfigured multiprocessor pipeline (without persistence storage) gives poor user experience

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1653]
If one tries to run a pipeline with multiprocessing config without specifying an intermediate storage that persists, the error is an unlabeled log message:

<img width="1298" alt="Screenshot 2019-08-09 06 56 50" src="https://user-images.githubusercontent.com/28738937/62784310-10f4e100-ba73-11e9-8cb6-5ee1bcfbc303.png">

Couple layers to this:

1) The error should be surfaced as an error in this view. I would suspect that this error is not being caught as part of an error boundary or something.

2) It would be very cool to catch this before execution somehow, although that might be quite difficult to pull off.

**Comment by mgasner** [comment]
for 2) i think we would need to either have some pieces of the config get evaluated at validation time, or we would need a way to specify dependencies between config sections

**Comment by mgasner** [comment]
#1610

**Comment by mgasner** [comment]
per @alangenfeld at lunch today, we may want to add a key to `filesystem` storage so that users can explicitly specify it will work over the network

**Comment by natekupp** [comment]
This error message has improved now, closing
