### ISSUE TITLE
Create markdown metadata entry and allow in-dagit rendering

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1655]
Similar to our json metadata entry (constructed with `EventMetadataEntry.json(..)`) it would be good to have a markdown one and then support rendering markdown (`EventMetadataEntry.md(...)`) within a model within dagit

**Comment by Aylr** [comment]
I cannot wait to use this.

**Comment by schrockn** [comment]
https://github.com/dagster-io/dagster/commit/6c78175afd317d5943596ef78caef932f376cbce
