### ISSUE TITLE
pyyaml dependency issue.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1657]
Reported in slack:

<img width="594" alt="Screenshot 2019-08-12 06 13 40" src="https://user-images.githubusercontent.com/28738937/62867536-58c07600-bcc8-11e9-9f01-c12efdcc1838.png">

According to dagster/setup.py this is because of an incompatibility with docker-compose:
```
            # pyyaml pinned for compatibility with docker-compose
            # https://github.com/docker/compose/blob/master/setup.py#L35
            'PyYAML>=3.10,<5',
```

And as of this writing that constraint is still in place: https://github.com/docker/compose/blob/master/setup.py

Ideally dagster itself would have a permissive variant and we would only impose the hard constraint in our environments that require use of docker-compose

**Comment by mgasner** [comment]
this is relaxed on master to >=3.10,<5
