### ISSUE TITLE
Filter historical materializations by static partition

### ISSUE THREAD

**Issue by christeefy** [dagster-io/dagster#16601]
### What's the use case?

Hi team! 

I am using Dagster to support multiple customer implementations. Currently, one graph / job is created per customer even though they all have the same workflow. The plan is to use static partitions (specifically with SDAs) to simplify the codebase. 

Unlike un-partitioned jobs, the UI for static partitions w/ SDAs doesn't allow me to view the historical materializations for a given customer. See below:
<img src="https://github.com/dagster-io/dagster/assets/8013575/a875408f-341f-4fbf-ba49-01cdae75b719" height="700" />

This is only blocker to migrating to partitioned assets for my team, as we need to at least be able to view historical materializations by customer (static partition). 

Thanks in advance for looking into this! 😊 

### Ideas of implementation

I do not have experience in frontend, but the simplest workaround I know of is to provide an option in the webserver UI to filter by a given static partition. 

We could take inspiration from the partitioned jobs UI:
<img width="566" alt="image" src="https://github.com/dagster-io/dagster/assets/8013575/0eaf0b40-96c6-484f-8ae0-746378280620">

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey @christeefy,

Sorry for the delay -- I think that Dagster may have the view you're looking for, but it's somewhat hidden (and I'll see if we can fix that!) If you go to the `Partitions` tab for this asset and select one of your customer partitions (ie: customer3), the right portion of the UI shows the latest materialization of that partition but you can view them all by clicking the "X prior events" link.

![Image](https://github.com/dagster-io/dagster/assets/1037212/1df9fb0d-b46e-4696-baed-98f9292b8bdf)

Separately I'll see if we can implement #17060 which may take care of part of this ask!

**Comment by christeefy** [comment]
Hi @bengotow, thanks for the reply here. I found the link after searching for a bit (agree that it is rather hidden). Looking forward to #17060 as a more explicit and intuitive way to filter for partitions!
