### ISSUE TITLE
Asset job "Open in launchpad" takes you to the playground page with no way to specify asset selection

### ISSUE THREAD

**Issue by bengotow** [dagster-io/dagster#16639]
### Dagster version

1.4.14

### What's the issue?

While investigating #16613, I was able to reach the old playground page for an asset job without an asset selection by clicking the Open in Launchpad button on an existing asset job run.  This option is also in a dropdown menu on the list page. This:

1) opens the /playground launchpad without the op/asset/check selection of the current run. You can use the query selector syntax to specify an op selection but not an asset or check selection.

2) goes to the /playground page which isn't supposed to exist for asset jobs

This button /might/ be ok for custom asset jobs but should definitely not exist in it's current form for __ASSET_JOB_0. The button doesn't copy the current run's config or tags or anything at all, so it really offers nothing that going to asset graph page and clicking "Materialize" doesn't offer.

### What did you expect to happen?

I expected that clicking Open in Launchpad from a run would take me to the exact launchpad view that I saw before I launched that run. I think we should try to make it do that if we can, but I'm not sure to what extent we can pass in all the original context.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Proposal: "Open in asset graph" instead of "Open in Launchpad"
