### ISSUE TITLE
dagster cli should print out structured events

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1666]
Right now we are not printing out structured events to the console when you run dagster from the CLI. Terrible user experience.

**Comment by mgasner** [comment]
These print out when log level is DEBUG -- should we change them to INFO?

**Comment by schrockn** [comment]
Yeah I would propose that. We just need to make sure it doesn't double print in dagit.

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by schrockn** [comment]
![Screenshot 2019-08-15 05 45 52](https://user-images.githubusercontent.com/28738937/63095404-04173800-bf20-11e9-8bfc-f340050442e2.png)
