### ISSUE TITLE
Allow for the creation of runs which do not trigger downstream AMPs

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#16691]
### What's the use case?

Sometimes, it's useful to execute a manual run or backfill which does not cause knock-on effects (i.e. triggering downstream eager AMPs).

This could take the form of a checkbox in the UI, or some tag that's added to runs (or both). In particular, this would impact the `AutoMaterializeRule.materialize_on_parent_updated()`, and could result in that rule not getting fired when such an "invisible" materialization is emitted.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@OwenKephart and I chatted about this yesterday, and ended up learning towards `skip_on_latest_materialization_run_tags` rule.

E.g.
```python
AutoMaterializePolicy.eager().with_rules([
    AutoMaterializeRule.skip_on_latest_materialization_run_tag(has_tag_key="backfill")
])
```

**Comment by sryza** [comment]
This is now possible with 
```python
AutoMaterializePolicy.materialize_on_parent_updated(
    updated_parent_filter=AutoMaterializeAssetPartitionsFilter(latest_run_required_tags=...)
)
```

**Comment by cbini** [comment]
@sryza should this work with `op_tags`? Trying to find a way to auto-materialize a dbt asset only if one specific upstream model has materialized and not every other upstream model it depends on.

**Comment by OwenKephart** [comment]
Hi @cbini -- the general track of solving that specific issue (only listening to updates from a specific upstream model) aligns with the new Declarative Automation framework discussed in [this post](https://github.com/dagster-io/dagster/discussions/22811). This allows you to target conditions at specific sets of parents, e.g.:

```python
AutomationCondition.any_deps_match(
    AutomationCondition.newly_updated(),
).allow(AssetSelection.assets("foo"))
```

so, you'd be able to craft a condition that is basically a copy of the built-in AutomationCondition.eager(), but with that `allow()` tacked on in the appropriate place
