### ISSUE TITLE
Create release pipeline

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1671]
Right now, the pipenv test will fail on any new release commit (since the commit will hit GitHub before the packages are available on PyPI). We really should formalize the release process in CI/CD, and add explicit post-release tests for installability, etc., of which this would be one.

Include:
* post release smoke tests #1818
* (optional) support for non-prod pypi #1958
* Test/validate K8s release deliverables #3179

**Comment by natekupp** [comment]
Pulling in note here from #2634: 

We could even automatically publish updates to CHANGES.md to Github via https://developer.github.com/v3/repos/releases/#create-a-release and Slack.

**Comment by natekupp** [comment]
Per discussion, this could be a Dagster pipeline instead
