### ISSUE TITLE
Enable checks to depend on secondary assets

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#16725]
Example use case: ensure that table X is joinable with table Y. Table X is the primary asset, and the success / failure of the check will reflect on table X's status.  However, table Y is also used as input data to the check's evaluation function.  If X, Y, and the check are all include in the same run, we should wait for both X and Y to materialize before executing the check.

### What we've heard
- https://github.com/dagster-io/dagster/discussions/15880#discussioncomment-7113911
- https://dagster.slack.com/archives/C05N0ELQA93/p1697463800916059 - "is there no way to reference multiple assets with one check? is something like this not possible? @asset_check(assets=[asset1, asset2, asset3]"

**Comment by sryza** [comment]
@johannkm @dsto - heads up, issue to track one of the pieces we talked about today.

**Comment by rob-apella** [comment]
@sryza what is the idea behind primary/secondary assets? why is the hierarchy needed?

**Comment by sryza** [comment]
@rob-apella - our current thinking is that the the primary asset is that asset whose status is affected by the result of the check.

E.g. imagine you've got some stable core table and then you have some table downstream of it with some fancy logic, and ultimately the downstream table should have a row for every row in the core table.  You want to write a check to verify this.  If the check fails, it's probably a problem with the downstream table, and you don't want the core table to have a big red check mark saying "failed its check". In this case the downstream table would be primary and the upstream core table is secondary.

Does this resonate? Do you have examples where you'd want both assets to get the red check mark if the check fails?

**Comment by johannkm** [comment]
This is supported now with

```python
@asset_check(
  asset=main_asset,
  additional_ins=[other_asset_1, ...],
  additional_deps=[other_asset_2,...],
)
def my_check():
  ...
```

https://docs.dagster.io/_apidocs/asset-checks#dagster.asset_check
