### ISSUE TITLE
Dagster should not depend on dagster-ext-process

### ISSUE THREAD

**Issue by psarka** [dagster-io/dagster#16753]
### Dagster version

1.4.16

### What's the issue?

There is a circular dependency:

`dagster-ext-process` depends on `dagster`
`dagster` depends on `dagster-ext-process`

Is it temporary? Can't the code be separated out properly?

### What did you expect to happen?

I would expect dagster to not depend on the dagster-ext-process, like it is the case for dagster-graphql, dagster-webserver, and all the other extensions.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
cc @smackesey  probably due to the `dagster` requirement in the `test` extra https://github.com/dagster-io/dagster/blob/master/python_modules/dagster-ext/setup.py#L37C5-L37C29

**Comment by smackesey** [comment]
@psarka How did this manifest for you? Plain `dagster-ext-process` does _not_ depend on `dagster`-- only `dagster-ext-process[test]`, which shouldn't affect users. Did this impact you somehow?

**Comment by psarka** [comment]
Sorry, my bad, did not inspect dagster-ext-process setup.py carefully enough. I hit this when executing `make dev_install` on my fork and got a pip error, not a very interesting case, so I'll deal with it.

Filing an issue I assumed that dagster could be made independent of it's extension dagster-ext-process, but now I see that it is the other way around.

**Comment by smackesey** [comment]
@psarka Well in any case we moved the test suite into core so now even the `dagster[test]` dependency is gone.
