### ISSUE TITLE
Navigation shortcuts

### ISSUE THREAD

**Issue by medghaim** [dagster-io/dagster#16763]
### What's the use case?

Slack has a CTRL+K hotkey which lets you search names, jump to channels, dms, etc.

A similar feature for Dagster would be amazing, especially for those with lots of jobs. Being able to jump directly to the job would be a minute, but very welcomed time save.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Hi! Did you know that pressing `/` is a shortcut that will pull up the search bar? From here, you can search all assets, schedules, jobs, etc.
