### ISSUE TITLE
Allow passing config to `dagster asset materialize` CLI

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#16802]
### What's the use case?

Providing non-default config values . 

It should be possible to both pass a path to `config.yaml` and provide the config in the CLI itself. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Seems like this would be useful, will add this issue to our backlog

**Comment by parthasdey2304** [comment]
i would love to work on this! Would you please assign this to me!

**Comment by sryza** [comment]
Hi @parthasdey2304 - assigned

**Comment by danielgafni** [comment]
I feel like ideally the CLI should be able to read values from both .yaml files and command line arguments, but we can probably start with just reading .yaml files, right?

**Comment by sryza** [comment]
Yeah, it should function the same as the `-c` argument on the `dagster job execute` command.

**Comment by sam-goodwin** [comment]
What's the status of this? It would be very helpful.

**Comment by 0x26res** [comment]
It looks like work on this has stalled sadly.

It would be good if we'd be able to provide a configuration for `dagster asset materialize`, but also `dagster jobs backfill`. I don't understand why only `dagster job execute` has got a config argument. 

It means (AFAIK) it's impossible to run a partitioned job with a custom configuration.

**Comment by DruidNx** [comment]
Hi I'm facing the same issue. It looks like the CLI is incomplete at this stage. 

| Dagster CLI command   | Can pass partition | Can pass config |
| ----------------- | --------- | ------ |
| job backfill      | yes       | no     |
| asset materialize | yes       | no     |
| job execute       | no        | yes    |

Could someone share a workaround of how to launch a partitioned job with a config or a partitioned asset with a config from the CLI.

**Comment by cmpadden** [comment]
I am also interested in this functionality--having accidentally created a duplicate issue https://github.com/dagster-io/dagster/issues/26217.

If there's anything I can do to assist on this functionality, please let me know!

**Comment by cmpadden** [comment]
`--json-config` has been implemented for `asset materialize` in #26578.
