### ISSUE TITLE
We do not appear to respect log level config

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1681]
I'm in branch right now and trying to suppress log spew.

Running a pipeline with: 

```
    result = execute_pipeline(
        construct_level_pipeline('low_numbers', levels=2, fanout=2),
        environment_dict={'loggers': {'console': {'config': {'log_level': 'ERROR'}}}},
    )
```

Still has debug printing

![Screenshot 2019-08-20 11 14 49](https://user-images.githubusercontent.com/28738937/63372811-bcd3e180-c33b-11e9-8388-b671039c2969.png)

**Comment by schrockn** [comment]
Max feel free to reassign (with additional context) to someone else if you can't get to this before you take off

**Comment by prha** [comment]
@schrockn I can't repro this...  can you?

**Comment by prha** [comment]
closing until repro
