### ISSUE TITLE
Rethink dagit watch

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1684]
Proposal: We should effectively kill or turn off the dagit watch system. A few things to note:

1) It continues to be a source of nasty bugs. (See https://github.com/dagster-io/dagster/issues/1682)
2) For use cases where you are only editing the body of the computation and not changing metadata at all, it actually detracts from the development experience. The re-execute button gets greyed out and the individual step reexecute button silently gets delayed with no feedback. In this case it is *not* necessary since the pipeline launch launches a new process *anyways*.
3) When you do update metadata, the user has to do a manual refresh anyway in order to see updated metadata in the UI.

What I believe we should instead is have a reload button within the UI that kills the web server process, which should be automatically reloaded by a wrapper script. The user would do this in lieu of pressing browser refresh. The only downside I can think of is that currently the process eagerly reloads whereas in this proposed scheme that would only occur when the user presses the button. So there's some increase in latency there. But upside is pretty high.

**Comment by mgasner** [comment]
This is also the source of #1678 afaict

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D1075
