### ISSUE TITLE
 Partition selection resets when typing in launchpad config

### ISSUE THREAD

**Issue by elementl-devtools** [dagster-io/dagster#16840]
https://dagsterlabs.slack.com/archives/C03CCE471E0/p1695825169112009?thread_ts=1695825107.250509&cid=C03CCE471E0

**Comment by salazarm** [comment]
Fixed in 1.5.3

**Comment by soichih** [comment]
I am not 100% if this is the same issue, but I am having a similar issue with Dagster 1.7.10. Everytime I try to enter my partition, I have to "fight" with the partition dialog which keeps resetting to the default value for about 10-20 seconds which is extremely annoying. Is there a work around to this? What causes this issue?

**Comment by garethbrickman** [comment]
@soichih I recall that problem as well but can't find a specific issue for it. Could you try upgrade your Dagster version, I suspect it's been fixed.
