### ISSUE TITLE
Dbt assets display nonsense metadata

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#16851]
### Dagster version

latest

### What's the issue?

Dagster dbt display nonsense metadata. These metadata entires are used for internal implementation details.

![Screenshot 2023-09-27 at 3 23 20 PM](https://github.com/dagster-io/dagster/assets/28738937/ba0c54d0-c516-44e5-bf11-824de732d6be)

### What did you expect to happen?

Should not see it.

### How to reproduce?

Click on asset in dbt project

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by slopp** [comment]
Important to note that Nick's screenshot shows the _definition_ metadata, of which we probably want to keep  `partition_expr` which is user defined but discard the rest.

We also show non-sensical _run_ metadata if you click 'View metadata' and should instead give preference to the asset materialization metadata, eg 

<img width="1711" alt="Screen Shot 2023-10-24 at 1 16 55 PM" src="https://github.com/dagster-io/dagster/assets/15901072/6aae7dc4-da8c-49df-b289-dcb05aa4f014">
<img width="1407" alt="Screen Shot 2023-10-24 at 1 16 36 PM" src="https://github.com/dagster-io/dagster/assets/15901072/8cca44dc-02d4-402a-b6d9-51b01f791e83">
