### ISSUE TITLE
dbt-dagster - need extra args when creating manifest.json invoking "parse" function from DbtCliResource 

### ISSUE THREAD

**Issue by MarioPerales** [dagster-io/dagster#16855]
### What's the issue or suggestion?

The [current documentation](https://docs.dagster.io/integrations/dbt/reference#loading-dbt-models-from-a-dbt-project) in the dagster-dbt tutorial suggests creating the dbt `manifest.json` via the following code:

```
dbt_project_dir = Path(__file__).joinpath("..", "..", "..").resolve()
dbt = DbtCliResource(project_dir=os.fspath(dbt_project_dir))

# If DAGSTER_DBT_PARSE_PROJECT_ON_LOAD is set, a manifest will be created at runtime.
# Otherwise, we expect a manifest to be present in the project's target directory.
if os.getenv("DAGSTER_DBT_PARSE_PROJECT_ON_LOAD"):
    dbt_parse_invocation = dbt.cli(["parse"], manifest={}).wait()
    dbt_manifest_path = dbt_parse_invocation.target_path.joinpath("manifest.json")
else:
    dbt_manifest_path = dbt_project_dir.joinpath("target", "manifest.json")
```

However, the `parse` function in dbt will not create the `manifest.json` file automatically. Therefore an error will occur at runtime as there will be no `manifest.json` file to reference. An additional argument, `--write-manifest`, is needed for the `manifest.json` to be created.

### Additional information

This issue is also found in the [example code](https://github.com/dagster-io/dagster/blob/f71cf74da3cb27cb3965562bff6c89de5f26fa38/examples/assets_dbt_python/assets_dbt_python/assets/dbt/__init__.py#L13C1-L13C13).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment]
Hi! As of dbt 1.5, `dbt parse` will do the `--write-manifest` behavior by default.

Thank you for highlighting this, though! We could specify that the flag is needed if you're using an older version of dbt.
