### ISSUE TITLE
Can't import Selectors, NamedSelectors and input_selector_schema

### ISSUE THREAD

**Issue by MrwanBaghdad** [dagster-io/dagster#1685]
Reading through the [user defined type in the docs](https://dagster.readthedocs.io/en/0.5.6/sections/learn/tutorial/types.html)

Trying to importing `Selector` `NamedSelector` or `input_selector_schema` results in an import_error. 

**Steps to replicate the error.**

* Install dagster using pip 
* run 
```python
from dagster import Selector
``` 

--- 
This error seems to be specific to the dagster which is installed through pip. 
Installing dagster with `setup.py` this error isn't shown and these modules are available to be imported through dagster's top module.

**Comment by alangenfeld** [comment]
Thanks for the report!

We had decided to drop those from the top level API to reduce the user facing complexity of the system and failed to update that section of the docs.

We are working on deciding between simplifying the tutorial and keeping those out of the top level API (https://dagster.phacility.com/D861) or going back on our decision.

**Comment by mgasner** [comment]
Closing this as resolved by D861.
