### ISSUE TITLE
 Double check that there isn't a buggy path that causes the right sidebar to be hidden

### ISSUE THREAD

**Issue by elementl-devtools** [dagster-io/dagster#16850]
https://dagsterlabs.slack.com/archives/C03CCE471E0/p1695840527544069?thread_ts=1695840345.321699&cid=C03CCE471E0

Maybe we can add a button/toggle to make it show up again if we detect it's hidden all the way

**Comment by hellendag** [comment]
I think this should be fixed now that the individual split panel containers have their own identifiers.
