### ISSUE TITLE
Config and partition key cannot both be provided via launchpad

### ISSUE THREAD

**Issue by clairelin135** [dagster-io/dagster#16863]
### Dagster version

1.4.17

### What's the issue?

Created a graph asset with static partitions and config. When I select a partition any configuration in the launchpad disappears, and when I enter any config in the launchpad the partition key disappears.

Reported by a user: https://dagster.slack.com/archives/C01U954MEER/p1695835525426889

**Comment by clairelin135** [comment]
Seems like a front end issue -- was able to successfully provide both a partition key and config to an asset in code:
```
class MyConfig(Config):
    config_int: int


@op
def my_op(context, config: MyConfig):
    context.log.info(context.partition_key)
    context.log.info(config.config_int)
    return 1


@graph_asset(partitions_def=StaticPartitionsDefinition(["a"]))
def my_graph_asset():
    return my_op()


materialize(
    [my_graph_asset],
    partition_key="a",
    run_config={"ops": {"my_graph_asset": {"ops": {"my_op": {"config": {"config_int": 1}}}}}},
)
```

**Comment by globmont** [comment]
I'm also encountering this. Seems like it may be related to this commit on the frontend in case that helps anyone more familiar with the frontend codebase here.

[#9eabe0e101a4e2efd071040844c44710d186e0cc](https://github.com/dagster-io/dagster/commit/9eabe0e101a4e2efd071040844c44710d186e0cc)
