### ISSUE TITLE
Direct invocation does not work for MaterializeResult

### ISSUE THREAD

**Issue by jamiedemaria** [dagster-io/dagster#16921]
### Dagster version

1.5.0+

### What's the issue?

Doing direct invocation when an asset returns a `MaterializationResult` 

```python
    @asset
    def my_asset() -> MaterializeResult:
        return MaterializeResult(metadata={"foo": "bar"})

    my_asset()
```
causes
```
AttributeError: 'MaterializeResult' object has no attribute 'output_name'
```
because the function `op_invocation.py:_type_check_function_output` is trying to get the output name associated with the MaterializationResult object (which does not have an output name)

You also get different errors when `MaterializationResult` is yielded
```python
    @asset
    def generator_asset() -> Generator[MaterializeResult, None, None]:
        yield MaterializeResult(metadata={"foo": "bar"})

    list(generator_asset())
```
causes 
```
 dagster._core.errors.DagsterInvariantViolationError: When yielding outputs from a op generator, they should be wrapped in an `Output` object.
```

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
@alangenfeld did direct invocation get fixed for `MaterializeResult` with these PRs? https://github.com/dagster-io/dagster/pull/16958 https://github.com/dagster-io/dagster/pull/16949 or is there still work to be done?

**Comment by jamiedemaria** [comment]
@archy-bold  I made a new issue for `AssetCheckResult` [here](https://github.com/dagster-io/dagster/issues/17454), please feel free to add any additional information

**Comment by alangenfeld** [comment]
yep the repros from the original issue are fixed
