### ISSUE TITLE
Wrong Using dbt with Dagster tutorial command

### ISSUE THREAD

**Issue by nick-vas** [dagster-io/dagster#16945]
### What's the issue or suggestion?

The second command of Step 2 within https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/load-dbt-models should be just dagster dev

### Additional information

NaN

**Comment by sryza** [comment]
@nick-vas are you able to explain your thinking on this one? The section below explains why to use `DAGSTER_DBT_PARSE_PROJECT_ON_LOAD`.

**Comment by rexledesma** [comment]
Closing this, as `DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1 dagster dev` is currently required, as per explanation in the tutorial.

**Comment by tintamarre** [comment]
I wanted to mention that I encountered this issue as well. I used `DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=0` for several months in my production .env file.
