### ISSUE TITLE
Documentation doesnt order version correctly

### ISSUE THREAD

**Issue by C0DK** [dagster-io/dagster#16956]
### Dagster version

1.4.17

### What's the issue?

1.4.17 should probably be ordered as "newer" than 1.4.9, however due to it being a string it's ordering it "1.4.9" > "1.4.17" > "1.4.1"...  :D 

![image](https://github.com/dagster-io/dagster/assets/9048078/ee5cefe9-bdeb-41d9-ae9f-5a70dc16e17c)

I assume the ordering is based on string ordering. It doesn't work when you have multi-digit semantic versioning, though ;) 

### What did you expect to happen?

The ordering to be related to newest release, to make it easier to find the prior version, if you are not fully up to date.

### How to reproduce?

see docs: https://docs.dagster.io/getting-started

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yuhan** [comment]
Thanks for catching! Will get it fixed soon!

**Comment by C0DK** [comment]
I think you fixed it.
