### ISSUE TITLE
backfill stalls when includes grandchild, but not child

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#16952]
Imagine an A -> B -> C asset graph.

You kick off a backfill that targets A and C, but not B.

Currently, we kick off runs to backfill A, but never kick off runs to backfill C, so the backfill remains in an in-progress state forever.

We should kick off runs to backfill both A and C at the same time.

**Comment by ruizh22** [comment]
Hi @sryza @clairelin135 , have we started working on this by any chance?

**Comment by clairelin135** [comment]
@ruizh22 Not yet, though I am hoping to take a stab at this this week or next week

**Comment by ruizh22** [comment]
> @ruizh22 Not yet, though I am hoping to take a stab at this this week or next week

Sounds good! Please keep us posted.
