### ISSUE TITLE
Audit Metadata for Toggle of Schedules and Sensors

### ISSUE THREAD

**Issue by NaturalFractals** [dagster-io/dagster#16963]
### What's the use case?

We have a cloud deployment of Dagster and would like to have an audit trail of who has toggled sensors and/or schedules. You can imagine a scenario where a developer (hopefully accidentally) toggles off a critical schedule or sensor for the source nodes of a particular DAG. This accident results in the miss of SLO/SLA for a number of data pipelines. It would be good to have an audit of who has toggled off the sensors and schedules through the UI for a given code location.

RBAC access controls for a given code location should already narrow down the list of folks who would even have access to do this, but a more definitive userID would be even better.

### Ideas of implementation

This data could be appended to the StopSchedule and StartSchedule mutation queries and persisted in the backend. In our use case they don't necessarily need to be exposed through the Dagster UI, but as long as we could access this information through the GraphQL APIs - that would be sufficient. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
This is now available in Dagster Cloud in our `1.6.2` release! Sensor and schedule mutations should now be tracked in the audit log: https://github.com/dagster-io/dagster/releases/tag/1.6.2
