### ISSUE TITLE
issue with build_airbyte_assets using airbyte cloud

### ISSUE THREAD

**Issue by marcNY** [dagster-io/dagster#16974]
### Dagster version

1.5.0

### What's the issue?

When implementing the code to load airbyte asset from the cloud I get the following error:

```
dagster._check.CheckError: Member of iterable mismatches type. Expected (<class 'dagster._core.definitions.assets.AssetsDefinition'>, <class 'dagster._core.definitions.source_asset.SourceAsset'>, <class 'dagster._core.definitions.cacheable_assets.CacheableAssetsDefinition'>). Got [<dagster._core.definitions.assets.AssetsDefinition object at 0x7fc695b2f670>] of type <class 'list'>.
```

Here is my code:

```

airbyte_instance=AirbyteCloudResource(api_key=EnvVar("AIRBYTE_API_KEY"),)
airbyte_assets = build_airbyte_assets(
    connection_id="58c7b793-6661-4670-xxxxxxx",
    destination_tables=[ "deals", "deals_archived", "engagements", "owners", "owners_archived"]

)

defs = Definitions(
    assets=[
        airbyte_assets
        ],
    resources={
        "airbyte": airbyte_instance
    },
)

```

### What did you expect to happen?

I epected the code to run

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yuhan** [comment]
Same question answered in slack [here](https://dagster.slack.com/archives/C047VPGQUTV/p1696322533492079). Closing as the question is resolved.

**Comment by selimrbd** [comment]
> Same question answered in slack [here](https://dagster.slack.com/archives/C047VPGQUTV/p1696322533492079). Closing as the question is resolved.

@yuhan the slack message being older tahn 90 days, it's not possible to access it (Dagster slack seems to be working on the free version)

Any other place where I could find this answer ?

**Comment by yuhan** [comment]
here's the persistent version: https://discuss.dagster.io/t/15886705/hello-all-i-am-trying-to-use-dagster-wiith-airbyte-cloud-usi
