### ISSUE TITLE
Improved display of multidimensional partitions

### ISSUE THREAD

**Issue by FlightOfStairs** [dagster-io/dagster#16999]
### What's the use case?

The current catalog is awkward to use for multi-partitioned assets with high cardinality or long names. We have partitions by company and date.

Our company partition is made up of `<slug>:<uuid>`, e.g., `mutiny-hq:c528a915-3339-4734-886d-ac3a03f65e22`. The slug is a human-readable name, while uuid is required for the op. These are dynamic partitions, so we can’t easily create a static mapping from slug to ID, as new companies will be automatically added.

![image](https://github.com/dagster-io/dagster/assets/1462903/bcab6feb-adfa-40e8-b1b6-34beefdd06a0)

### Ideas of implementation

Any of these would greatly help us:
* Make “human readable label” a top-level thing, so the UUID doesn’t need to appear in the UI.
* Improve column rendering - either dynamic height, or setting `white-space: nowrap;`.
* Allow searching. Looks like we can filter by date, but not by company.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
@sryza Thoughts on these suggestions?

**Comment by sryza** [comment]
> Make “human readable label” a top-level thing, so the UUID doesn’t need to appear in the UI.

I wouldn't rule this out in the long term, but this change would have big implications so would like to punt on it for now.

- Improve column rendering - either dynamic height, or setting white-space: nowrap;.

This seems like a good idea to me.

> Allow searching. Looks like we can filter by date, but not by company.

This also seems like a good idea to me.

**Comment by hellendag** [comment]
I'll take a look at adding some search inputs on there. It sounds like some of @salazarm's recent work may resolve the truncation and line wrapping.

**Comment by ztessler** [comment]
Just to note, many of these usability issues also apply in the case of singly-partitioned assets. We have several thousand dynamic partitions, with moderately long keys that tend to differ at the end of the string. It's quite difficult to find a single partition. Filtering/searching partition keys would be ideal, and the ability to increase the width of the partition key column to see the full key would also be great. Thanks!

**Comment by hellendag** [comment]
@FlightOfStairs @ztessler Are you still seeing the wrapping issue? We have middle truncation in place as of https://github.com/dagster-io/dagster/pull/16961, so ideally that should be working correctly now.

**Comment by ztessler** [comment]
@hellendag yes, seeing middle truncation now on 1.5.6, much more usable, thanks!
