### ISSUE TITLE
Observable Source Assets invoke an IO Manager

### ISSUE THREAD

**Issue by FlightOfStairs** [dagster-io/dagster#17030]
### Dagster version

dagster, version 1.4.17

### What's the issue?

It seems strange to me that Observable Source Assets invoke an IO Manager. We have a few that produce partitioned asset observations to trigger automaterialization of downstream jobs when datasources are ready. We have `athena_ready`, `elasticsearch_ready`, `graphql_ready`.

```python
@observable_source_asset(partitions_def=daily_company_partitions(), auto_observe_interval_minutes=60)
def athena_ready(context: OpExecutionContext) -> DataVersionsByPartition:
    ...
    return DataVersionsByPartition(
        {key: "1" for key in generate_date_range_rows(...)}
    )
```

We use our own IO Manager to persist datasets as Parquet in S3. We wish to assert that all assets produce pandas DataFrames, as we know how to turn these into Parquet. We’ve seen that these Observable Source Assets are invoking `S3ParquetIOManager.handle_output(<context>, None)`, which makes this assertion pretty ugly and potentially leaky:

```python
class S3ParquetIOManager(ConfigurableIOManager):
    ...

    def handle_output(self, context: OutputContext, obj: Any) -> None:
        # Weirdly, Observable Source assets invoke handle_output with None. We don't want to blindly allow None, and we
        # can't read tags or metadata from the asset. The IOManager is invoked with no asset key in these cases.
        if not context.has_asset_key and obj is None:
            return

        if not isinstance(obj, pd.DataFrame):
            raise Exception(f"Outputs of type {type(obj)} not supported.")

        ...
```

This behaviour is pretty surprising - can it be improved? I’m aware that this is touching on experimental features. 

### What did you expect to happen?

`IOManager.handle_output()` to have not been invoked, as there is no meaningful output to be persisted.

If there is some reason why the IOManager should be invoked, it should be easy to identify that this is from an observable source asset.

### How to reproduce?

```python
# reproduce_issue.py

from typing import Any

from dagster import StaticPartitionsDefinition, DataVersionsByPartition, ConfigurableIOManager, \
    OutputContext, Definitions, observable_source_asset, InputContext

# Our use-case is partitioned; I expect this occurs when not partitioned too.
color_partitions_def = StaticPartitionsDefinition(["red", "blue"])


@observable_source_asset(partitions_def=color_partitions_def)
def my_source_asset() -> DataVersionsByPartition:
    return DataVersionsByPartition(
        {
            "red": "1",
            "blue": "1"
        }
    )


class NotNoneIOManager(ConfigurableIOManager):
    def handle_output(self, context: OutputContext, obj: Any) -> None:
        if obj is None:
            raise Exception("Assets should not produce None")

    def load_input(self, context: "InputContext") -> Any:
        raise NotImplementedError()


defs = Definitions(
    assets=[my_source_asset],
    resources={"io_manager": NotNoneIOManager()},
    sensors=[],
    schedules=[],
)
```

`dagster dev -f src/reproducing_issue.py`

Observing this source asset in the UI will cause:
```
[...] - STEP_FAILURE - Execution of step "my_source_asset" failed.

dagster._core.errors.DagsterExecutionHandleOutputError: Error occurred while handling output "result" of step "my_source_asset"::

Exception: Assets should not produce None
```

### Deployment type

Dagster Cloud

### Deployment details

Deployment not relevant - occurs in local dev and Dagster Cloud.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @FlightOfStairs - agree that this is strange! I have a PR in progress to fix this.
