### ISSUE TITLE
Unify the Target column actions on the Runs page

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#17035]
We now have Three different types of targets. Jobs, Assets, and Asset Checks but they all behave differently when you hover and click on them.

- Jobs aren't clickable and have a separate action to click.
- Assets are clickable, and have a tooltip with two options.
- Asset checks are also clickable and have a tooltip and show an underline when you hover.

![Image](https://github.com/dagster-io/dagster/assets/2798333/690f2197-4b6f-4ce1-9546-eca21673e9e8)

**Comment by bengotow** [comment]
Hey @braunjj any preference how we unify these? I feel like the asset version (link styling with a tooltip menu) might be a nice one to converge. Maybe for starters removing the job version with a separate link icon would be good?

**Comment by braunjj** [comment]
yep that's what i had in mind too. Unifying all of these around the asset experience

**Comment by hellendag** [comment]
@bengotow Assigning to you since it looks like you've already started thinking about it. We can move it around if needed.
