### ISSUE TITLE
All modals from runs view do not work

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1704]
Click on "view configuration" here

<img width="1188" alt="Screenshot 2019-08-29 13 10 48" src="https://user-images.githubusercontent.com/28738937/63972873-762e6780-ca5e-11e9-9e8a-c133871ff0a9.png">

Get blank screen

<img width="1263" alt="Screenshot 2019-08-29 13 10 54" src="https://user-images.githubusercontent.com/28738937/63972874-762e6780-ca5e-11e9-9d04-0be8e3b2e1fa.png">

**Comment by prha** [comment]
actually, i'm not sure how setting react nodes as state ever worked?  @bengotow ?

**Comment by schrockn** [comment]
The "show metadata" button also does not work

**Comment by bengotow** [comment]
Hey! Will take a look at this right now—It looks like I used a regexp to update usages of this to the new one that takes a React Node and it may not have worked properly.

**Comment by schrockn** [comment]
fixed
