### ISSUE TITLE
Global Asset Lineage bugs

### ISSUE THREAD

**Issue by JensvandeZande** [dagster-io/dagster#17089]
### Dagster version

dagster, version 1.5.1

### What's the issue?

Hi all,

There are several bugs in the UI:

1. Groups are not shown on the global asset lineage page while they are present in the asset list page. I specify groups using the `load_assets_from_package_module` function.
2. When renaming assets and hitting "Reload definitions" button, the lineage page does not render properly and the name does not change while it does change in the asset list page. I changed the name from "brnz_jessiedong" to "jessiedong".
3. Also the bottom right asset's shape is off. It is not rectangular like the others.

![image](https://github.com/dagster-io/dagster/assets/49940005/2d01c926-7aba-4b93-8d1e-bed30b2548e3)
![image](https://github.com/dagster-io/dagster/assets/49940005/7b37c28d-a51b-4a90-838c-1908b08d4cdb)

### What did you expect to happen?

To render properly.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by salazarm** [comment]
@JensvandeZande If you go to user-settings and check the box "Disable asset graph caching" setting then reload the page does the issue go away? If so I believe the PR linked above will address this issue.
<img width="497" alt="Screenshot 2023-10-09 at 10 39 10 AM" src="https://github.com/dagster-io/dagster/assets/2286579/cc58e17b-69fd-4349-9f1f-a3d6de45b38e">

**Comment by JensvandeZande** [comment]
@salazarm, Points 1 and 3 are resolved. Point 2, the renaming, still exists.

**Comment by JensvandeZande** [comment]
@salazarm, The renaming, point 2, gets fixed once I reload the window but not right after I click Reload definitions.

**Comment by salazarm** [comment]
@JensvandeZande Gotcha, yeah these will all be fixed once we release the above PR

**Comment by salazarm** [comment]
Closing since the above PR was released in 1.5.3
