### ISSUE TITLE
`dagster_ssh` should include a ConfigureableResource version of `SSHResource`

### ISSUE THREAD

**Issue by slopp** [dagster-io/dagster#17087]
### What's the use case?

Wanting to nest `SSHResource` within other configurable resources

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by DanteOz** [comment]
This PR seems similar to https://github.com/dagster-io/dagster/issues/15108 which has an existing PR to add the ConfigurableResource version of SSHResource https://github.com/dagster-io/dagster/pull/15180.
