### ISSUE TITLE
 Update backfill dialog to reflect backfill will launch a single run when `BackfillPolicy.single_run` is set

### ISSUE THREAD

**Issue by elementl-devtools** [dagster-io/dagster#17095]
https://dagsterlabs.slack.com/archives/C03CCE471E0/p1696874285658849?thread_ts=1696874175.284329&cid=C03CCE471E0

**Comment by braunjj** [comment]
@leahpadgett Let's chat about this one

**Comment by sryza** [comment]
Closing as duplicate of https://github.com/dagster-io/dagster/issues/17201
