### ISSUE TITLE
Enable setting a default op-level concurrency limit

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#17145]
Imagine a deployment where there are many assets, new assets are added frequently, and most assets have concurrency limits.

Needing to execute `dagster instance concurrency set <concurrency_key> <limit>` every time you add/remove an asset makes it easy for the concurrency keys that the deployment knows about to get out of sync with the concurrency keys in the asset definitions.  It's also inconvenient and adds time to deploys.

One solution would be making it possible to configure a default deployment-wide limit that applies to any asset that has a concurrency key.

### What we've heard
- https://dagsterlabs.slack.com/archives/C03AC5P8Z1T/p1699318215947149?thread_ts=1699318010.338509&cid=C03AC5P8Z1T

**Comment by jPinhao-Rover** [comment]
👍 I'd say this really should be following the same concurrency control config used for job-level concurrency, with the ability to control asset materialisation with custom labels and options to set `applyLimitPerUniqueValue: true` as described in  https://github.com/dagster-io/dagster/discussions/12251

**Comment by sryza** [comment]
This has been addressed:

```yaml
concurrency:
  default_op_concurrency_limit: 1
```
