### ISSUE TITLE
Pylint complains about missing arguments when using the solid DSL to define pipelines

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1720]
e.g.:
```
from dagster import pipeline, solid


@solid
def hello_world(_):
    return 'hello'

@pipeline
def hello_world_pipeline():
    hello_world()
```

gives the pylint error: `No value for argument '_' in function callpylint(no-value-for-parameter)`

This is probably something we can fix with an astroid "brain hint". See: https://stackoverflow.com/questions/38087760/pylint-coroutines-decorators-and-type-inferencing. Docs are lacking, we would have to work from examples in https://github.com/PyCQA/astroid/tree/master/astroid/brain. Something like (this code doesn't work):

```
import astroid

def _is_decorated_solid(node):
    if not node.decorators:
        return False
    return 'dagster.core.definitions.decorators.solid' in node.decoratornames()

@astroid.inference_tip
def _infer_decorated_solid(node, context=None):
    _args = node.args
    _args.defaults = [astroid.nodes.Const(None) for arg in _args]
    node.args = _args
    return node


astroid.MANAGER.register_transform(
    astroid.FunctionDef,
    _infer_decorated_solid,
    _is_decorated_solid
)
```

**Comment by mgasner** [comment]
The pylint error is thrown at https://github.com/PyCQA/pylint/blob/master/pylint/checkers/typecheck.py#L1290

**Comment by mgasner** [comment]
Lol, or, just wait for https://github.com/PyCQA/pylint/pull/2926/files to merge

**Comment by schrockn** [comment]
yeah i wonder what they are waiting for. still no response to my comment

**Comment by schrockn** [comment]
would love to get this resolved though

**Comment by mgasner** [comment]
the brain hint is more invasive in one sense, but also easier in another in that it doesn't require our users to edit their pylint settings

**Comment by schrockn** [comment]
would definitely be open to prototyping this. the ergonomics are rough.

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by natekupp** [comment]
@mgasner this is resolved now right?
