### ISSUE TITLE
Job Partitions UI shows 0 partitions when asset count > 100

### ISSUE THREAD

**Issue by peter-lim-yello** [dagster-io/dagster#17206]
### Dagster version

1.4.10

### What's the issue?

When an asset job is created via `define_asset_job` on dbt_assets, and asset count is greater than 100, the partitions page fails to show partitions or last run status in the page.

Example of high asset count:
![image (1)](https://github.com/dagster-io/dagster/assets/110631348/7b996785-b40a-44b9-b5a9-c700972c9e21)

Main DAG page of job with high asset count:
![image](https://github.com/dagster-io/dagster/assets/110631348/2bbdfe9c-c02b-45bc-b542-31abe9524edb)

Example of lower asset count, each partition shows up:
![image (2)](https://github.com/dagster-io/dagster/assets/110631348/a5f007f9-e75f-4701-878f-828e24ee420e)

Example code of both jobs:
```
@partitioned_config(partitions_def=dynamic_client_etl_partitions_def)
def dbt_client_full_load_config(partition_key: str):

    return {
        "resources": {
            "dbt_run_resource": {
                "config": {
                    "client": partition_key,
                    "full_refresh": True,
                }
            }
        }
    }
```
Job:
```
run_ods_full_load_job = define_asset_job("run_ods_full_load_job",
                               config=dbt_client_full_load_config,
                               partitions_def=dynamic_client_etl_partitions_def,
                               selection=AssetSelection.assets(
                                   dbt_client_files,
                                   dbt_client_ods_full_load,
                                   dbt_client_ods
                               ))
```

Assets:
```
@dbt_assets(manifest=DBT_MANIFEST_PATH, partitions_def=dynamic_client_etl_partitions_def, select="ods.full_load")
def dbt_client_ods_full_load(context: OpExecutionContext, dbt_run_resource: DbtRunResource, dbt: DbtCliResource):

    dbt_run_args = dbt_resource_to_args("run", dbt_run_resource)

    yield from dbt.cli(dbt_run_args, context=context).stream()
```

### What did you expect to happen?

Partitions page should show the correct partition count even when asset count > 100. It would also be nice if we can choose to see materializations by selection/group so that the partitions UI page is not so cluttered when plenty of assets are present.

Example of expected partitions UI
![image (2)](https://github.com/dagster-io/dagster/assets/110631348/2f113aaf-3448-4970-8ef6-55847ad2202d)

### How to reproduce?

1. Create a dbt project with more than 100 table/view materializations
2. Declare those assets in dagster with the dbt_assets decorator
3. Create resources config for job, dynamic partitions, job with `define_asset_job `
4. Add dynamic partitions and see if they show up in the UI. The UI shows 0 if asset count in that job is > 100.

### Deployment type

Dagster Helm chart

### Deployment details

Deployed on Helm and Local, same behavior.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I was able to reproduce this with this smaller example:

```python
from dagster import (
    multi_asset,
    define_asset_job,
    AssetSpec,
    Definitions,
    StaticPartitionsDefinition,
)


@multi_asset(
    specs=[AssetSpec(f"asset_{i}") for i in range(200)],
    partitions_def=StaticPartitionsDefinition([f"partition_{i}" for i in range(100)]),
)
def foo():
    ...


job1 = define_asset_job("job1")


defs = Definitions(assets=[foo], jobs=[job1])
```
