### ISSUE TITLE
Make build_pyspark_zip exclude more extensible

### ISSUE THREAD

**Issue by aimran-adroll** [dagster-io/dagster#17219]
### What's the use case?

In the current [implementation](https://github.com/dagster-io/dagster/blob/12210a86a89511caa006177b96eb8ca0a8f175dc/python_modules/libraries/dagster-pyspark/dagster_pyspark/utils.py#L7), the `build_pyspark_zip` function is hardcoded to exclude various artifacts it finds in the local directory (e.g pytest and __pycache__ folders). It might be helpful if we can open up the exclusion list. 

In my case, I would like to exclude the `.venv` folder -- it took me a few tries to realize why the upload step was taking so long 😅 

### Ideas of implementation

Either make the function take optional argument for further filtering of folders. Alternately, some kinda `.ignorefile` support would be more extensible (same way .dockerignore knows to skip certain artifacts)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Good suggestion, I put up a PR that allows you to set `exclude`.

**Comment by aimran-adroll** [comment]
Thanks @smackesey
