### ISSUE TITLE
Internal Error when launching a job with nested graph while only selecting one graph

### ISSUE THREAD

**Issue by zyd14** [dagster-io/dagster#17216]
### Dagster version

1.5.0

### What's the issue?

When launching a job from the Dagster Cloud launchpad on a job containing two nested graphs, if I select the first graph in the job using the op selection text box, the following error is presented when I hit the Launch button:

`Internal Server Error (Trace ID: 2344929809736008173)`

Removing the selected graph from the op selection text box allows the job to be launched, but with all ops selected

### What did you expect to happen?

I expected the job to launch while only running the ops included in the graph specified in the op selection text box.

### How to reproduce?

Create a job with two graphs, one providing input into the other. Then try to launch the job while selecting only the first graph in the op selection text box.

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
We've identified the source of the problem here and are in the process of rolling out a fix for this issue to Dagster Cloud now.

**Comment by gibsondan** [comment]
The fix for this is now live - let us know if you're seeing any additional issues with op selection runs, and apologies for the disruption.
