### ISSUE TITLE
Execute Job on Start

### ISSUE THREAD

**Issue by jeremytanjianle** [dagster-io/dagster#17222]
### What's the use case?

An asset may require a parent asset to materialize. 
This parent asset should always be ready and should be the first thing to materialize.

Would it be possible to execute jobs / materialize assets on start of an instance? 
e.g. on `dagster dev -m src`, dagster spins up and immediately runs a selection of jobs.
(Sorry if this has already been raised, I've looked around but could not find a similar issue)

Edit:
I've read the Auto-materialize policy, particularly the `materialize_on_missing` rule.
After testing, it looks like it could be used, but is warned as experimental and requires a human hand to turn on. 
I wonder if there is an explicit method to materialize which assets first upon starting dagster?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Hi Jeremy, Thanks for the request-- however, we are going to keep materialization of assets and launching of the instance logically separate. If you want to materialize assets on start, then I would recommend:

- Writing a script that starts up the instance and then uses the [CLI](https://docs.dagster.io/_apidocs/cli#dagster-cli) or [GQL client](https://docs.dagster.io/concepts/webserver/graphql-client#graphql-python-client) to materialize target assets.
- Use auto-materialization (as you independently discovered)
