### ISSUE TITLE
Failed Asset Check still kicks off downstream flow

### ISSUE THREAD

**Issue by HuyNguyenNeyuData** [dagster-io/dagster#17251]
### Dagster version

dagster, version 1.5.3

### What's the issue?

I made a simple flow 

```
from dagster import asset, asset_check, AssetCheckResult

@asset
def extract_asset() -> int:
    return 3

@asset
def load_asset(extract_asset) -> None:
    return None

@asset_check(asset=extract_asset, description="Check that my asset has enough rows")
def my_asset_has_enough_rows(extract_asset: int) -> AssetCheckResult:
    return AssetCheckResult(passed=False, metadata={"num_rows": extract_asset})
```
The check failed, but checkmark is green, and downstream asset is still allowed to materialize
![image](https://github.com/dagster-io/dagster/assets/134916473/fa56e410-22c1-447c-aa11-5bac48320626)

### What did you expect to happen?

The Asset Check job should be red (indicated failed job), and downstream asset must be prevented from being further materialized

### How to reproduce?

clean install of dagster

in `assets.py`
```
from dagster import asset, asset_check, AssetCheckResult


@asset
def extract_asset() -> int:
    return 3


@asset
def load_asset(extract_asset) -> None:
    return None


@asset_check(asset=extract_asset, description="Check that my asset has enough rows")
def my_asset_has_enough_rows(extract_asset: int) -> AssetCheckResult:
    return AssetCheckResult(passed=False, metadata={"num_rows": extract_asset})
```

in `__init__.py`
```
from dagster import Definitions, load_assets_from_modules

from . import assets

all_assets = load_assets_from_modules([assets])
all_checks = []

defs = Definitions(assets=all_assets, asset_checks=[assets.my_asset_has_enough_rows])
```
then initiate "Materialize All" from UI

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
You've found this already, but for others:

By default checks won't block downstream assets. https://github.com/dagster-io/dagster/discussions/16569 discusses options for blocking checks using graph backed assets. There's also a new `build_asset_with_blocking_check` utility function to make this easy.
