### ISSUE TITLE
 "Attempting to show unified asset health for assets with dimension of different lengths"

### ISSUE THREAD

**Issue by elementl-devtools** [dagster-io/dagster#17305]
https://dagsterlabs.slack.com/archives/C03KE7K92TT/p1697731737565609?thread_ts=1697577747.120779&cid=C03KE7K92TT

https://app.datadoghq.com/rum/error-tracking?query=%40application.id%3A7edc09bb-51d0-4555-90cd-b19ca483d1fe&amp;issueId=747546da-5c4e-11ee-8843-da7ad0900002&amp;refresh_mode=sliding&amp;view=spans&amp;from_ts=1696972829701&amp;to_ts=1697577629701&amp;live=true

**Comment by bengotow** [comment]
Merging this in to #17380

**Comment by will-holley** [comment]
I've encountered this in 1.6.3 with two `StaticPartitionsDefinition` of lengths 1 and 2 composing a `MultiPartitionsDefinition`.
