### ISSUE TITLE
build_sling_asset doesn't use other SlingMode other than the default FULL_REFRESH

### ISSUE THREAD

**Issue by dduong1603** [dagster-io/dagster#17301]
### Dagster version

1.5.3

### What's the issue?

<img width="656" alt="Screenshot 2023-10-19 at 9 34 45 AM" src="https://github.com/dagster-io/dagster/assets/29114884/ec4439dc-8848-4895-b369-a1c456840853">

I believe the `_sync` method doesn't currently pass the `mode` to the `config` variable so `build_sling_asset` always use the default SlingMode

### What did you expect to happen?

`mode` to be passed to `_sync` method

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
cc @PedramNavid

**Comment by PedramNavid** [comment]
@dduong1603 thanks for catching this! Created #17310 to fix this to ship with the next release after its merged.
