### ISSUE TITLE
errors when using eternal assets examples

### ISSUE THREAD

**Issue by tomasz-maj-bp** [dagster-io/dagster#17325]
### What's the issue or suggestion?

Hey,
I've tried both examples from https://docs.dagster.io/concepts/assets/external-assets
But both of them return error during starting code location server. I'm using `dagster dev` to run it. I tried both 1.5.1 and 1.5.4 but errors were exactly same.
In first example:
```
defs = Definitions(assets=[external_asset_from_spec(AssetSpec("file_in_s3"))])
```
there's a typo in method name, it should be `external_assets_from_specs`, as well as the method produces list already, so wrapping it in another doesn't help.
So when running
```
defs = Definitions(assets=external_assets_from_specs(AssetSpec("file_in_s3")))
```
the error is
```
AttributeError: 'AssetKey' object has no attribute 'auto_materialize_policy'
```
which seems absurd, given in beginning of external asset method there's a validation:
```
check.invariant(
    spec.auto_materialize_policy is None,
    "auto_materialize_policy must be None since it is ignored",
)
```

The second example:
```
raw_logs = AssetSpec("raw_logs")
processed_logs = AssetSpec("processed_logs", deps=[raw_logs])

defs = Definitions(assets=external_assets_from_specs([raw_logs, processed_logs]))
```
Throws:
```
Invalid dependencies: node "_external_assets_def_2" does not have output "raw_logs". Listed as dependency for node "_external_assets_def input "raw_logs"
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
### First example

>there's a typo in method name, it should be external_assets_from_specs, as well as the method produces list already, so wrapping it in another doesn't help.

`dagster` also defines `external_asset_from_spec`, you just need to import it-- so there's no error here.

You can also use `external_assets_from_specs`, but in that case the argument needs to be a list:

```
defs = Definitions(assets=external_assets_from_specs([AssetSpec("file_in_s3")]))
```

### Second example

I'm unable to repro the error. I did this:

```
### test_external_assets.py
from dagster import AssetSpec, Definitions, external_assets_from_specs

raw_logs = AssetSpec("raw_logs")
processed_logs = AssetSpec("processed_logs", deps=[raw_logs])

defs = Definitions(assets=external_assets_from_specs([raw_logs, processed_logs]))
```

```
dagster dev -f test_external_assets.py
```

And it loaded fine (1.5.4). Can you try again?

**Comment by tomasz-maj-bp** [comment]
Hey, thanks for the response (and sorry for the delay).
Even with your examples I had same issues, but one of my colleagues verified that as well and it looks it's just something broken on my machine.

Thank you once more for your attention to this issue.
