### ISSUE TITLE
dagster_embedded_elt: Field mode is ignored

### ISSUE THREAD

**Issue by erudyk** [dagster-io/dagster#17349]
### Dagster version

dagster, version 1.5.4

### What's the issue?

The field `mode` in dagster_embedded_elt package (version 0.21.4) is ignored and not transferred to Sling package, causing Sling to default to full-refresh mode. 
![image](https://github.com/dagster-io/dagster/assets/17247650/d8a95bba-470b-4ece-92b6-8c5033db4553)

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by PedramNavid** [comment]
Hi @erudyk, this is a dupe of #17301 and has been resolved in #17310. Thanks for reporting this!
