### ISSUE TITLE
Come up with dangling runs strategy

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1735]
It's quite easy to get our runs db in a bad state. Start a long running job. Kill dagit. Restart dagit. Even though it is not executing it is in the "Started" state.

![Screenshot 2019-09-09 16 38 45](https://user-images.githubusercontent.com/28738937/64573483-4dd91f80-d320-11e9-968b-198bc073fc23.png)

This is the airline demo

**Comment by mgasner** [comment]
Just hit this too

**Comment by alangenfeld** [comment]
solution likely connected to #3613
