### ISSUE TITLE
dbt asset checks select based on tags

### ISSUE THREAD

**Issue by geoHeil** [dagster-io/dagster#17372]
### What's the use case?

Can I target an asset check selection based on DBT tags?

https://dagster.slack.com/archives/C05N0ELQA93/p1697465538407749

### Ideas of implementation

when will the asset checks DBT integration will support running the tests on their own cadence?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
@geoHeil, are you looking to select dbt tests based on tags on the tests themselves, or on the models?

**Comment by johannkm** [comment]
Cool, both should work once this goes out
