### ISSUE TITLE
Add ability to override asset_key[-2] as schema in DbIOManager

### ISSUE THREAD

**Issue by jrstats** [dagster-io/dagster#17389]
### What's the use case?

There is currently no way to set the database schema on a per-asset basis.
So if you have asset: `data_sources/source1/my_asset`, you do not have the option to store the asset in the `data_sources` schema.
In my database, I would like to store the asset in `data_sources`, but in dagster, it would be cool to not have to restrict the asset key to `data_sources/asset_name`.

It would be really useful to be able to connect to a database IO manager (e.g. bigquery) and specify the schema on a per-asset basis, and separately from the asset key.

### Ideas of implementation

similar to the op implementation.

> [For ops, the dataset can be specified by including a `schema` entry in output metadata. If ``schema`` is not provided via config or on the asset/op, ``public`` will be used for the dataset.](https://docs.dagster.io/_modules/dagster_gcp/bigquery/io_manager)

e.g.

definition

``` python
from dagster import asset

@asset(
    key_prefix=["data_sources", "source1"],
    metadata={"schema": "data_sources"}
)
def my_asset():
    ...
```
implementation

``` python
class DbIOManager(IOManager):
    ...
    def _get_table_slice(
            self, context: Union[OutputContext, InputContext], output_context: OutputContext
        ):
        ...
        ## NEW
        if output_context_metadata.get("schema"):
            schema = cast(str, output_context_metadata["schema"])
            
        ## END NEW
        elif len(asset_key_path) > 1 and self._schema:
            raise DagsterInvalidDefinitionError(
                f"Asset {asset_key_path} specifies a schema with "
                f"its key prefixes {asset_key_path[:-1]}, but schema  "
                f"{self._schema} was also provided via run config. "
                "Schema can only be specified one way."
            )
        elif len(asset_key_path) > 1:
            schema = asset_key_path[-2]
        elif self._schema:
            schema = self._schema
        else:
            schema = "public"
        ...
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
hey @jrstats thanks for bringing this up, it's a good idea! I'll get it on my backlog, but just want to let you know i've got some other priorities atm so I may not get to it for a bit. The DB IO manager isn't under active development so if you wanted to copy paste the code for it and make the update you mentioned, I don't foresee you needing to make many other changes due to updates in the source code. 

Alternately if you want to submit a PR, I'm happy to review!

**Comment by jrstats** [comment]
Thank you @jamiedemaria , I will submit a PR for this today, hopefully.
