### ISSUE TITLE
Point of discussion: Language around stopping schedules should be "stop" rather than "end"

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1740]
"End" generally indicates "destruction with finality" when used as a transitive verb. E.g. "I will end you" "And thus his watched has ended". By contrast "Stop" means a cessation that can in turn be restarted. Imagine if we re-named "stop signs" "end signs".

So when I typed "dagster schedule end foo" I actually translate to "delete" in my mind. 

"dagster schedule stop foo" is more clear that this is a cessation and not a deletion.

**Comment by mgasner** [comment]
“Suspend”

**Comment by helloworld** [comment]
Currently, the behavior is destructive as you described. We should, however, support stopping schedules to later resume them. Tracking here: https://github.com/dagster-io/dagster/issues/1743
