### ISSUE TITLE
Allow code version changes to trigger AMP

### ISSUE THREAD

**Issue by mjclarke94** [dagster-io/dagster#17411]
### What's the use case?

Currently when using AMPs as the primary means of scheduling asset materialisation, it will refresh assets in response to an upstream asset having returned different data, but not if the code which generated that data has changed. 

### Ideas of implementation

Add a new materialisation condition for when a code version has changed.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Hi @mjclarke94. Agree that it would be very useful to allow code version changes to trigger AMP. There is an existing issue that you can track, so I'll mark this one as a duplicate: https://github.com/dagster-io/dagster/issues/15686
