### ISSUE TITLE
Clicking Materialize Times out in >1.5

### ISSUE THREAD

**Issue by fridiculous** [dagster-io/dagster#17427]
### Dagster version

1.5.5

### What's the issue?

I click on a job and click `Materialize all...` it times out.  I've given ample database resources, but it may never return.  This is true wether i click `Materialize all` or `Open Launchpad`

There are over 700 assets in this job, but it unclear if it's size dependent. 

https://github.com/dagster-io/dagster/assets/1227514/d8b2286c-ccf7-47db-a441-6480863c4893

### What did you expect to happen?

To load the modal within a few seconds.

### How to reproduce?

Attempt on 1.5.5 with a large dag?

### Deployment type

Dagster Helm chart

### Deployment details

Cloud SQL configuration is as follows:
<img width="605" alt="image" src="https://github.com/dagster-io/dagster/assets/1227514/bf7db303-b180-4f62-a4c3-ecc11fcd945c">

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by fridiculous** [comment]
For more context, the timeout occurs with `LaunchAssetLoaderQuery` has 

```QueuePool limit of size 1 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)```

**Comment by sryza** [comment]
Hi @fridiculous - was this working for you pre-1.5? Are you able to use py-spy or similar to see what the web server process is doing while it's waiting? Does this happen every time or just occasionally? Are you able to reproduce it locally?

**Comment by fridiculous** [comment]
@sryza it was working in 1.3.9, but that was updated entirely.  I haven't tried to do py-spy yet.  It's happening everytime.

**Comment by fridiculous** [comment]
@sryza - i believe this bug was resolved in the upgrade from 1.5.5 to 1.5.6

**Comment by sryza** [comment]
@fridiculous that's great. Let us know if it re-surfaces.
