### ISSUE TITLE
Emphasize natural language instead of cron string

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1742]
Right now the cron string is always displayed and the english summation is only a tooltip. I think we should lead with the natural text. "Every minute" is in tool tip and the cron string leads:

<img width="917" alt="Screenshot 2019-09-10 19 54 18" src="https://user-images.githubusercontent.com/28738937/64664796-2c059880-d405-11e9-9650-0b874d190224.png">

And in this case I'm not sure what the 12:00 am signifies even though that is hourly. This could be an unrelated bug.

<img width="947" alt="Screenshot 2019-09-10 19 56 49" src="https://user-images.githubusercontent.com/28738937/64664810-3d4ea500-d405-11e9-8c93-6fe20068c6e8.png">

**Comment by helloworld** [comment]
https://dagster.phacility.com/D1008
