### ISSUE TITLE
Error DagsterInvariantViolationError: yielding AssetCheckResult from Asset

### ISSUE THREAD

**Issue by archy-bold** [dagster-io/dagster#17437]
### Dagster version

1.5.4

### What's the issue?

When unit-testing an asset with asset checks alongside the materliasation, I get the following error:

```
E               dagster._core.errors.DagsterInvariantViolationError: When yielding outputs from a op generator, they should be wrapped in an `Output` object.

.venv/lib/python3.10/site-packages/dagster/_core/definitions/op_invocation.py:368: DagsterInvariantViolationError
```

### What did you expect to happen?

I would expect to not be shown an error that I cannot yield an `AssetChcekResult` from an asset.

### How to reproduce?

Here's a minimal example:

```python
from dagster import (
    AssetCheckResult,
    Output,
    asset,
)

@asset
def an_asset():
    yield Output(value="hello")
    yield AssetCheckResult(
        passed=False,
    )

def test_an_asset():
    res = an_asset()
    assert next(res).value == "hello"
    assert next(res).passed == False
```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
Hi @archy-bold, you'll need to declare the asset check on the asset with `check_specs=`. See https://docs.dagster.io/concepts/assets/asset-checks#checks-that-execute-in-the-same-op-that-materializes-the-asset

**Comment by sryza** [comment]
@johannkm I think we could improve the error that's raised here

**Comment by archy-bold** [comment]
I'm 90% sure I've declared `asset_specs` correctly (I'm not in a position to check right now). It works through `materialize_to_memory` without issue, just has this error when executing the asset directly. I missed it from `asset_specs` the minimum reproduction however.

**Comment by johannkm** [comment]
@archy-bold you're right, I saw it missing from the repro and jumped to conclusions. We currently break on directly invoking an asset with a check spec. I've filed https://github.com/dagster-io/dagster/issues/17453 to track fixing this. In the meantime you can use `materialize`:

```python
from dagster import AssetCheckResult, Output, asset, AssetCheckSpec, materialize


@asset(check_specs=[AssetCheckSpec(name="an_asset", asset="an_asset")])
def an_asset():
    yield Output(value="hello")
    yield AssetCheckResult(
        passed=False,
    )


def test_an_asset():
    result = materialize([an_asset])
    assert result.asset_value("an_asset") == "hello"

    check_evals = result.get_asset_check_evaluations()
    assert len(check_evals) == 1
    assert not check_evals[0].passed
```

**Comment by archy-bold** [comment]
@johannkm Heh, for a minute I thought I'd wasted everyone's time, especially mine.
