### ISSUE TITLE
dagster job status doesn't change though ecs task instance was killed because of memory issue

### ISSUE THREAD

**Issue by schapala-hm** [dagster-io/dagster#17448]
### Dagster version

1.5.5

### What's the issue?

We recently changed our run launcher config from default to ECS Run Launcher.
Observed that dagster job run status shows **started** even though the respective ecs task (ECS Task ARN) was killed because of memory issue.

**Note**: This behaviour is observed only when the container failed with memory issue. 
Didn't see the issue happening if the job failed with user code error or when it is successful.

### What did you expect to happen?

The dagster job run should fail and let the user know that the container is killed

### How to reproduce?

Have a job reading 2 GB pandas dataframe and run the job using ecs run launcher using the task definition with 1 GB memory config.

### Deployment type

Other

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
https://docs.dagster.io/deployment/run-monitoring#run-monitoring

**Comment by schapala-hm** [comment]
@alangenfeld Run monitoring config helped me with the issue above.
