### ISSUE TITLE
StaticPartitionsDefinition can not be used in a ScheduleDefinition

### ISSUE THREAD

**Issue by azngeek** [dagster-io/dagster#17442]
### Dagster version

1.5.5

### What's the issue?

When trying to schedule a job with a ScheduledDefinition, it will raise an error.

```
category_jobs = define_asset_job(
    name="category_jobs",
    selection=AssetSelection.groups("meilisearch"),
    partitions_def=StaticPartitionsDefinition(['de', 'at'])
)

category_jobs_schedule = ScheduleDefinition(job=category_jobs, cron_schedule="* * * * *")
```

There is no error when the assets are loaded but when the job is executed:

`dagster._core.errors.DagsterInvariantViolationError: Cannot access partition_key for a non-partitioned run`

### What did you expect to happen?

I expect that jobs with StaticPartitionsDefinition can be run via ScheduleDefinitions.

### How to reproduce?

- Create a asset with a StaticPartitionsDefinition
- Create a job scheduler for this asset.
- Try to run the job via the scheduler

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by craustin** [comment]
We're affected by this too. Is there any way to schedule the run of all partitions of a statically-partitioned asset? Both leaving `define_asset_job()`'s `partitions_def=` unset and setting it to the assets `StaticPartitionsDefinition` (i.e. the repro above) yield:
> DagsterInvariantViolationError: Cannot access partition_key for a non-partitioned run

**Comment by craustin** [comment]
Mentioning @clairelin135 since they did some related work w/ multi-partitioned assets a few months ago. I filed PR https://github.com/dagster-io/dagster/pull/19485 to make schedules work w/ statically partitioned asset jobs. Let me know if you suggest a different approach.
