### ISSUE TITLE
materialize raises dagster._check.CheckError: Failure condition: The instance is not available to load partitions

### ISSUE THREAD

**Issue by pedrovgp** [dagster-io/dagster#17456]
### Dagster version

1.5.5

### What's the issue?

I have a very simple asset
```python
run_day_partitions_def = DynamicPartitionsDefinition(name="run_day")

@asset(partitions_def=run_day_partitions_def)
def run_day_partitions(context):
    """Dynamic partitions for run_day"""
    this_partition_key = context.partition_key
    return this_partition_key
```
which I try running in the script with
```python
DATE = "2023-10-01"
materialize(assets=[run_day_partitions], partition_key=DATE)
```
but I get

> Exception has occurred: CheckError
> Failure condition: The instance is not available to load partitions. You may be seeing this error when using dynamic partitions with a version of dagster-webserver or dagster-cloud that is older than 1.1.18.
> dagster._check.CheckError: Failure condition: The instance is not available to load partitions. You may be seeing this error when using dynamic partitions with a version of dagster-webserver or dagster-cloud that is older than 1.1.18.

### What did you expect to happen?

I expected the asset to be materialized with the same value as the DATE I passed.

### How to reproduce?

The code I provided, when run, reproduces the issue.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
@pedrovgp thanks for reporting -- the dynamic partitions store object likely isn't being passed through somewhere. I will try to fix for the next release

**Comment by clairelin135** [comment]
Ah actually, looks like you just need to pass the instance argument into `materialize` -- the instance is required to load dynamic partitions:
```python
materialize(assets=[run_day_partitions], partition_key=DATE, instance=DagsterInstance.get())
```

**Comment by pedrovgp** [comment]
In deed, it worked, thanks!

**Comment by sryza** [comment]
Other aspects of `materialize` assume a default instance.  I.e. `materialize` writes to an event log, and invocations of `context.instance` methods in user code are expected to work. So it's good that there's an easy workaround, but it's strange  for us to be erroring in this way here.

**Comment by clairelin135** [comment]
`materialize` currently executes with a ephemeral instance if one isn't provided, so in this case the partition key would never exist unless if `DagsterInstance.get()` is passed in

IMO the ideal behavior in this case is some error like 
```
Provided partition key x does not exist. An instance was not provided to materialize(...), so an ephemeral instance is being used. This can be resolved by:
(1) Passing your default instance to materialize via DagsterInstance.get()
(2) Creating an ephemeral instance via instance_for_test(), adding a dynamic partition, and passing this instance to materialize
```

**Comment by clairelin135** [comment]
https://github.com/dagster-io/dagster/pull/17477
