### ISSUE TITLE
[Documentation Feedback] Problem on /getting-started/hello-dagster page

### ISSUE THREAD

**Issue by malavikabala** [dagster-io/dagster#17462]
It looks like distutils was deprecated in Python 3.12 so I am unable to install Dagster now and run this command. I get an error: No module named 'distutils'

**Comment by yuhan** [comment]
Thanks for raising the issue. We haven't officially supported Python 3.12 yet. Here's a tracking issue for that: https://github.com/dagster-io/dagster/issues/17350 - closing this one as dup
