### ISSUE TITLE
Cannot see logs from multi-asset sensors

### ISSUE THREAD

**Issue by Beaglefoot** [dagster-io/dagster#17461]
### Dagster version

1.5.5

### What's the issue?

Not sure if it's bug or was never implemented. I cannot see log messages in web UI from multi-asset sensors, but I can see them in terminal.

### What did you expect to happen?

I expect the same behavior as with simple sensors and asset sensors where you have "View Logs" link on sensor page after enabling "Experimental schedule/sensor logging view" in settings.

### How to reproduce?

Just scaffold a new dagster project, then paste into `__init__.py` the following:

```py
from dagster import (
    Definitions,
    MultiAssetSensorEvaluationContext,
    SensorEvaluationContext,
    SkipReason,
    asset,
    asset_sensor,
    job,
    multi_asset_sensor,
    sensor,
)


@asset
def dummy_asset():
    ...


@job
def dummy_job():
    ...


@sensor()
def dummy_sensor(context: SensorEvaluationContext):
    context.log.info("Test sensor logging")
    return SkipReason()


@asset_sensor(
    asset_key=dummy_asset.key,
    job=dummy_job,
)
def dummy_asset_sensor(context: MultiAssetSensorEvaluationContext):
    context.log.info("Test asset sensor logging")
    return SkipReason()


@multi_asset_sensor(
    monitored_assets=[dummy_asset.key],
    job=dummy_job,
)
def dummy_multi_asset_sensor(context: MultiAssetSensorEvaluationContext):
    context.log.info("Test multi-asset sensor logging")
    return SkipReason()


defs = Definitions(
    assets=[dummy_asset],
    sensors=[dummy_sensor, dummy_asset_sensor, dummy_multi_asset_sensor],
)
```
Materializing asset produces logs to `dummy_asset_sensor`, while `dummy_multi_asset_sensor` still has no logs in UI.

### Deployment type

Local

### Additional information

I had to install gql = "3.4.1" manually otherwise running webserver doesn't work.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by kristianeschenburg** [comment]
I'm also having this same issue.  I'm recording events in the sensor using `context.log.info(some_message)` -- these logs are printed out in the terminal window, but are not shown in the Dagster sensor UI.

**Comment by selene-eiq** [comment]
Also running into this issue. Is a fix being worked on?
