### ISSUE TITLE
add test for "remote" instance requirements for dask/celery when using cluster

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#1748]

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D1121

**Comment by mgasner** [comment]
what was this intended to be? is this a dask-based run launcher?

**Comment by alangenfeld** [comment]
retitled - we should have a test like the one that was deleted in D1121. We have the functionality that the original task title was speaking to.

**Comment by natekupp** [comment]
@alangenfeld can you explain more what this test was about?

**Comment by alangenfeld** [comment]
uh I believe just testing that we catch and error early if you are not going to be able to see the results of a "remote" execution. Using local file system instance storage with an executor like dask, celery, or k8s. 

I think this should be addressed with a broader re-visit to the instance storage semantics - the discussion from https://dagster.phacility.com/D2834 is relevant. The tasks tracked there might be more meaningful than this one at this point.

**Comment by catherinewu** [comment]
closing based on @alangenfeld's comment. feel free to re-open with more details
