### ISSUE TITLE
Pipeline and execution plan metadata should be stored with logs, not recomputed on the fly

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1749]
Pipelines and engines may change, but logs will persist, and we will want to view them against the old execution plan, steps, etc.

**Comment by mgasner** [comment]
Not clear what the right way to persist this is -- we could store the graphql response but as @schrockn notes, this is the opposite of the versioning problem graphql is designed to solve.

**Comment by mgasner** [comment]
@schrockn is this good to close?

**Comment by schrockn** [comment]
Yup!
