### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by steffyd** [dagster-io/dagster#17511]
### Dagster version

1.4.3

### What's the issue?

Updating our resources to use the new pythonic config method. In one of our resources, we take in a separate ConfigurableResource that contains a dictionary as part of the configuration process. This appears to cause a recursion depth issue.

Here is our code:
```python
class FlushResourceFactory(ConfigurableResource):
    flush_resources_dictionary: dict

    def get_flush_resource(self, resource_label):
        return self.flush_resources_dictionary[resource_label]

class SqlServerRoundRobin(ConfigurableResource):
    flush_resource_factory: FlushResourceFactory

    @contextmanager
    def get_next_server(self,context, scoring_pipe_label):
        try:
            cnxn = get_scoring_server(context, scoring_pipe_label, self.flush_resource_factory)
            yield cnxn[1]
        finally:
            cleanup_dispatch(cnxn[0], self.flush_resource_factory)

flush_resource_factory = FlushResourceFactory(flush_resources_dictionary=FLUSH_RESOURCES)
sql_server_selector = SqlServerRoundRobin(flush_resource_factory=flush_resource_factory),
 ```
 
 Here is the error we receive on initialization:
[_dagster_cluster_dagster_code.1.gkhmcijshf8w83ybiv21oxuax_logs.txt](https://github.com/dagster-io/dagster/files/13217979/_dagster_cluster_dagster_code.1.gkhmcijshf8w83ybiv21oxuax_logs.txt)

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by benpankow** [comment]
Hi @steffyd, what is the type of `FLUSH_RESOURCES` in this case? I can't replicate this error on 1.5.3, at least with a basic dictionary

**Comment by steffyd** [comment]
`FLUSH_RESOURCES` is a dictionary of type <string, ConfigurableResource>

**Comment by benpankow** [comment]
I see -  in general Dagster doesn't support resource dependencies more complex than direct resource/resource deps, right now there's not a way to supply e.g. a list of resource deps or a dict.

That being said, you might be able to get this specific scenario to work by annotating `flush-resource_dictionary` as a `ResourceDependency`. This means it won't be introspected by our config machinery:

```python
class FlushResourceFactory(ConfigurableResource):
    flush_resources_dictionary: ResourceDependency[Dict[str, Any]]

    def get_flush_resource(self, resource_label):
        return self.flush_resources_dictionary[resource_label]
```

This might lead to unexpected behavior, though - in particular any of the nested resources in the dictionary may not be initialized as you'd expect.

**Comment by steffyd** [comment]
Unfortunately that doesn't seem to fix this issue, the error seems to persist in the SQLServerRoundRobin initialization... We have a large number of databases and we connect to an initial metadata database to get the connection information. The thought is that we would generate ConfigurableResources for each database and then have more complicated and specialized ConfigurableResources built on top of that. But if we can't have a dictionary or list of ConfigurableResources, is there a different methodology you would recommend for our use case?

**Comment by benpankow** [comment]
One option here might be to represent each database configuration as a `Config` subclass, e.g.

```python
from dagster import ConfigurableResource, Config, EnvVar
from typing import Dict, Any


class MyDbConfiguration(Config):
    username: str
    password: str

    def query(self, query_text: str) -> Any:
        ...


class MyComplexDbResource(ConfigurableResource):
    db_config_dictionary: Dict[str, MyDbConfiguration]

    def query(self, db_name, query_text:str) -> Any:
        return self.db_config_dictionary[db_name].query(query_text)


DB_CONFIG = {
    "my_db_1": MyDbConfiguration(username="foo", password=EnvVar("BAR")),
    "my_db_2": MyDbConfiguration(username="bar", password=EnvVar("BAR")),
}

my_complex_db = MyComplexDbResource(db_config_dictionary=DB_CONFIG)

```

There's no problem nesting these, and you can define methods on the config classes as well.

**Comment by steffyd** [comment]
Hm, even changing the DbResources to configs doesn't seem to fix the issue... This is our full hierarchy - we first generate a SQLCredentialConfig that is a Config. We then generate DbConfigs that have a method called `get_engine`, and these are all in a dictionary. We then pass that dictionary of Configs into a FlushResourceFactory, which is a ConfigurableResource. We then pass that factory to another ConfigurableResource called `SqlServerRoundRobin`, which is the one it apparently is failing on according to the error message. What could be continuing to cause this issue? That we're passing in a ConfigurableResource to another ConfigurableResource?

**Comment by benpankow** [comment]
Nesting should be OK - as long as the nested resource is typed properly as a resource in the wrapper class, e.g. the following works fine

```python
from dagster import ConfigurableResource, Config, EnvVar, Definitions, asset
from typing import Dict, Any


class MyDbConfiguration(Config):
    username: str
    password: str

    def query(self, query_text: str) -> Any:
        ...


class MyComplexDbResource(ConfigurableResource):
    db_config_dictionary: Dict[str, MyDbConfiguration]

    def query(self, db_name, query_text:str) -> Any:
        return self.db_config_dictionary[db_name].query(query_text)


class MyWrapperResource(ConfigurableResource):
    my_db: MyComplexDbResource

    def query(self, db_name, query_text: str) -> Any:
        return self.my_db.query(db_name, query_text)

DB_CONFIG = {
    "my_db_1": MyDbConfiguration(username="foo", password=EnvVar("BAR")),
    "my_db_2": MyDbConfiguration(username="bar", password=EnvVar("BAR")),
}

my_complex_db = MyComplexDbResource(db_config_dictionary=DB_CONFIG)
my_wrapped_db = MyWrapperResource(my_db=my_complex_db)


@asset
def my_asset(my_wrapped_db: MyWrapperResource):
    pass

defs = Definitions(
    assets=[my_asset],
    resources={
        "my_wrapped_db": my_wrapped_db
    }
)
```

**Comment by steffyd** [comment]
This ended up working, thanks for the work around!
