### ISSUE TITLE
Add default_status in the build_schedule_from_dbt_selection helper method

### ISSUE THREAD

**Issue by julien-bovet-unnest** [dagster-io/dagster#17512]
### What's the use case?

We're running dagster on a VM that is on only 1 hour per day.
We want the schedules to be on by default.
We can't add that parameter on our schedule since we use the build_schedule_from_dbt_selection helper method and the parameter is not supported right now.

### Ideas of implementation

Just add the default_status parameter in the build_schedule_from_dbt_selection helper method.

### Additional information

Loving dagster so far 👍

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tmastny** [comment]
@rexledesma I understand there is a workaround, but what you suggest is just a slight recreation of `build_schedule_from_dbt_selection`. Here's the source for comparison: https://docs.dagster.io/_modules/dagster_dbt/asset_utils#build_schedule_from_dbt_selection

I think it would be really helpful to expose that field, and doing so would make `build_schedule_from_dbt_selection` consistent with other `build_schedule_*` functions.

For example: 
* [build_schedule_from_partitioned_job](https://docs.dagster.io/_apidocs/schedules-sensors#dagster.build_schedule_from_partitioned_job) has a `default_status` parameter

**Comment by rexledesma** [comment]
@tmastny I put up a quick PR for this: https://github.com/dagster-io/dagster/pull/19518. It will make next week's release on 2024-02-08.
