### ISSUE TITLE
AMPs causing duplicate runs of partitioned asset

### ISSUE THREAD

**Issue by mjkanji** [dagster-io/dagster#17519]
### Dagster version

version 1.5.5

### What's the issue?

I have a relatively simple setup with three assets, where
- A is time-partitioned. The corresponding job takes 2 minutes (via a forced sleep).
- B is not partitioned and depends on the last partition of A
- C is not partitioned and depends on B

I'm using intervals of 5 minutes for testing purposes, but these would normally be a single day. I'm using auto-materialization for all of them. The code is shown below:

<details>

```python
import time
from datetime import datetime, timedelta
from textwrap import indent

from dagster import (
    AssetExecutionContext,
    AssetIn,
    AutoMaterializePolicy,
    Definitions,
    FreshnessPolicy,
    LastPartitionMapping,
    TimeWindowPartitionsDefinition,
    asset,
)

@asset(
    io_manager_key="io_manager",
    partitions_def=TimeWindowPartitionsDefinition(
        start=datetime.now() - timedelta(minutes=10),
        cron_schedule="*/5 * * * *",
        fmt="%Y-%m-%d %H:%M:%S",
        timezone="Asia/Karachi", # Use your own timezone here.
    ),
    auto_materialize_policy=AutoMaterializePolicy.eager(
        max_materializations_per_minute=1
    ),
)
def A(context: AssetExecutionContext) -> str:
    time.sleep(120)
    out = f"I'm A. My partition key is: {context.partition_key}"
    context.log.info(out)
    return out


@asset(
    io_manager_key="io_manager",
    auto_materialize_policy=AutoMaterializePolicy.lazy(),
    freshness_policy=FreshnessPolicy(
        maximum_lag_minutes=5, cron_schedule="*/5 * * * *"
    ),
    ins={"A": AssetIn(partition_mapping=LastPartitionMapping())},
)
def B(context: AssetExecutionContext, A: str) -> str:
    out = f"I'm, B. I depend on:\n{indent(A, '    ')}"
    context.log.info(out)
    return out


@asset(
    io_manager_key="io_manager",
    auto_materialize_policy=AutoMaterializePolicy.lazy(),
    freshness_policy=FreshnessPolicy(
        maximum_lag_minutes=5, cron_schedule="*/5 * * * *"
    ),
)
def C(context: AssetExecutionContext, B: str) -> str:
    out = f"I'm, C. I depend on:\n{indent(B, '    ')}"
    context.log.info(out)
    return out

defs = Definitions(
    assets=[A, B, C]
)
```
</details>

The issue is that A is being materialized twice, with two runs running simultaneously (because of the "long" processing time for the corresponding job), I assume once because of its own eager materialization policy and once because of the "pull" from B and C's materialization policy. Setting a `max_materializations_per_minute=1` in A only causes the second run to be delayed to the next minute, but does not avoid it.

This also results in the following side effect:
- the first run for A finished about a minute before the second run
- the first run triggers a combined job for B and C, which finishes in less than a minute
- the second run for A finished _**after**_ the job for B and C.
- B & C show a warning that there is "new" upstream data because the second run for A finished after their materialization

### What did you expect to happen?

Having two runs triggered for the same partition at the same time is a waste of resources. There should be a way for Dagster to reconcile "overlapping" AMP triggers and recognize that the asset is already being materialized without trigger a duplicate at the same time.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mjkanji** [comment]
Update: It seems that the duplicate runs don't _always_ happen. Here's a screenshot of the Runs tab, where you can see duplicate runs for the 20:10 partition but not the 20:15 and 20:20 partitions:

<details>

![image](https://github.com/dagster-io/dagster/assets/52061313/d0938d42-3912-4767-b728-e6443e87c1d4)

</details>

**Comment by OwenKephart** [comment]
Hi @mjkanji ! Thanks for the report. I looked into this, and I believe this is happening due to the `start` parameter of your partitions definition being variable (i.e. always starting 10 minutes before the current time). Are you able to confirm if this issue persists if you set that to a static value?

From my end, I was able to replicate the issue as described with your provided code, but setting `start="2023-10-31 00:00:00"` appears to resolve the issue.

The issue at play here (I believe) is that the system internally keeps track of partition keys that it has already materialized for the reason of "this partition is missing", to avoid kicking these off repeatedly. However, this storage gets invalidated when the partitions definition changes, which is happening on a regular basis in the provided code (basically any time the code location gets automatically reloaded, the underlying partitions definition will change, invalidating that storage, and making the daemon "forget" that a given partition has already been materialized).

Certainly arguable that these caches should be a bit more stable to this sort of update to the underlying definition, and we do have some planned work in that area, but we definitely don't recommend having a partitions definition that changes constantly as this will cause oddities in other parts of the system as well (as any individual loader of the user code will have a slightly different perception of when the start date of the partitions def is).

**Comment by mjkanji** [comment]
Hi @OwenKephart, thank you for looking into this so quickly! I was using the dynamic `start` mostly for testing purposes -- I didn't want to rewrite a hard-coded value every single time or have a massive backlog of partitions. I was working under the assumption that the definition would be based on when I first ran `dagster dev`, but I suppose that assumption was inaccurate.

Hard-coding the `start` does fix the issue, as you noted, and I didn't see any duplicate runs in a 30-minute window (i.e., 6 partition "boundaries").

However, if the code location being reloaded resets the partition definition each time, then this perhaps reveals a bug in the UI, because when using my original code, the UI shows all the partitions for the given asset based on when I first ran `dagster dev`, without any change based on the code location being reloaded. In other words, after 30 minutes, the UI shows 8 partitions, and not 2, based on the fact that `start=datetime.now() - timedelta(minutes=10)` and `cron_schedule="*/5 * * * *"` should only allow for 2 partitions at a time if the definition is always updating.

**Comment by OwenKephart** [comment]
@mjkanji no problem!

There are several processes in play when you run `dagster dev`, with some relevant ones being:
- the daemon which executes the auto-materialize logic
- the webserver which renders information about your project
- the subprocesses that your assets execute in

The daemon reloads its representation of your project on a somewhat regular basis (every few minutes I believe), the webserver does not reload its representation automatically (there's a button in the UI to manually do so), and the subprocesses always start up with a fresh representation. This is one of the reasons that having code locations with dynamic aspects (i.e. things that can change without the code itself changing) is discouraged -- there's no way of ensuring that all of these representations will remain in sync with each other.

I think this would explain the behavior your seeing, so I'll close this issue for now.
