### ISSUE TITLE
Sort order is ambiguous in the absence of a created_at timestamp for PipelineRun

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1752]
And dependent on implementation details of the underlying RunStorage.

**Comment by mgasner** [comment]
@alangenfeld how do you feel about adding a timestamp

**Comment by alangenfeld** [comment]
no reservations that i can think of

**Comment by hellendag** [comment]
@mgasner Do you have more context on this?

**Comment by catherinewu** [comment]
since we have `create_timestamp` on runs table, going to close this issue
