### ISSUE TITLE
Partitioned config doesn't get populated in launchpad

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#17522]
If a job has partitioned config, and a partition is selected, the config for that partition should show up in the launchpad. However, this does not appear to be happening. Instead, we just scaffold basic config.

I reproduced with this code snippet:

```python
from dagster import job, op, static_partitioned_config


@static_partitioned_config(["a", "b", "c"])
def partconf(partition):
    return {"ops": {"op1": {"letter": partition}}}


@op(config_schema={"letter": str})
def op1():
    ...


@job(config=partconf)
def job1():
    op1()
```

<img width="605" alt="image" src="https://github.com/dagster-io/dagster/assets/654855/ae7a52ba-6710-4e9b-8ee8-14f50dbdb362">

I confirmed that the config-generation function is being called on the backend.

**Comment by nathan-calandra-simplisafe** [comment]
Didn't see this before I opened an issue myself: https://github.com/dagster-io/dagster/issues/17569
