### ISSUE TITLE
Consolidate LoaderEntrypoints

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#1755]
We have two classes, `SchedulerLoaderEntrypoint` and `LoaderEntrypoint`, which have very similar implementations. 

`LoaderEntrypoint` is used to load a function that returns a `PipelineDefinition`, and  `SchedulerLoaderEntrypoint` is used to load a function that returns a `ScheduleDefinition`. 

We should figure out a way to consolidate these two implementations.

**Comment by natekupp** [comment]
@helloworld @alangenfeld - thoughts on this issue given recent refactors?

**Comment by alangenfeld** [comment]
no longer relevant
