### ISSUE TITLE
Weird border (or blank scrollbar) having in config editor popever

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1756]
<img width="867" alt="Screenshot 2019-09-19 10 46 21" src="https://user-images.githubusercontent.com/28738937/65267889-d13a0400-daca-11e9-8a99-9fe3ef92db6c.png">

**Comment by mgasner** [comment]
what browser?

**Comment by schrockn** [comment]
Chrome

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by bengotow** [comment]
Oh gawd you've got a mouse huh. Taking a look at this.

**Comment by bengotow** [comment]
Addressed in https://dagster.phacility.com/D1139
