### ISSUE TITLE
WorkspaceLocationStatusEntries does not report states of repositories that failed to load

### ISSUE THREAD

**Issue by kwmlodozeniec** [dagster-io/dagster#17571]
### Dagster version

1.4.11

### What's the issue?

Because of the issue https://github.com/dagster-io/dagster/issues/17319 we need to actively monitor the state of the code locations on our dagit instances. In order to achieve that we are trying to use the `CodeLocationStatusQuery` query but that does report locations that failed to load as `LOADED` as shown in the example below.
![Screenshot from 2023-11-01 14-34-18](https://github.com/dagster-io/dagster/assets/1453791/1ab7f409-3a5c-4b7c-9158-283c9a3cbb94)

### What did you expect to happen?

I would expect any location that failed to load to be described as such.

### How to reproduce?

Load a code location that you know will fail to load, for example import something in code that you know does not exists.
Observe the dagit UI and then also run this query
```
query CodeLocationStatusQuery {
  locationStatusesOrError {
    ... on WorkspaceLocationStatusEntries  {
      entries {
        name
        loadStatus
      }
    }
  }
}
```

### Deployment type

Other Docker-based deployment

### Deployment details

We use a kubernetes deployment.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
The below query may workaround this issue:

```gql
query LocationStatusesQuery {
  workspaceOrError {
	  ... on Workspace{
      locationEntries {
        ... on WorkspaceLocationEntry {
          loadStatus
          locationOrLoadError {
            __typename
          }
        }
      }
    }
  }
}
```

- `loadStatus` will be LOADING or LOADED. 
- You can use that additional `locationOrLoadError` field to distinguish between error and not. If the typename is `PythonError`, it loaded with an error state. If it's a `RepositoryLocation` it loaded in a working state.

(Worth noting that alerting when code locations fail to load due to an error is a native feature available in [Dagster+ Alerts](https://docs.dagster.io/dagster-plus/managing-deployments/alerts).)

**Comment by kwmlodozeniec** [comment]
Thanks for the suggestion.
We have since stopped using dagster so this is no longer a problem for us.

**Comment by nullmaxwell** [comment]
> The below query may workaround this issue:
> 
> ```graphql
> query LocationStatusesQuery {
>   workspaceOrError {
> 	  ... on Workspace{
>       locationEntries {
>         ... on WorkspaceLocationEntry {
>           loadStatus
>           locationOrLoadError {
>             __typename
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> * `loadStatus` will be LOADING or LOADED.
> * You can use that additional `locationOrLoadError` field to distinguish between error and not. If the typename is `PythonError`, it loaded with an error state. If it's a `RepositoryLocation` it loaded in a working state.
> 
> (Worth noting that alerting when code locations fail to load due to an error is a native feature available in [Dagster+ Alerts](https://docs.dagster.io/dagster-plus/managing-deployments/alerts).)



For those that stumble upon this issue looking for something similar heres what the output of @garethbrickman's workaround looks like when querying a deployment with 3 repos where 1 repo has not loaded correctly:
```
{'data': {'workspaceOrError': {'locationEntries': [{'loadStatus': 'LOADED',
                                                    'locationOrLoadError': {'__typename': 'RepositoryLocation'}},
                                                   {'loadStatus': 'LOADED',
                                                    'locationOrLoadError': {'__typename': 'RepositoryLocation'}},
                                                   {'loadStatus': 'LOADED',
                                                    'locationOrLoadError': {'__typename': 'PythonError'}}]}}}
```


As an additional note including `id` within the query made the result more legible for my use case:
```
query LocationStatusesQuery {
  workspaceOrError {
	  ... on Workspace{
      locationEntries {
        ... on WorkspaceLocationEntry {
          id
          loadStatus
          locationOrLoadError {
            __typename
          }
        }
      }
    }
  }
}
```
returns:
```
{'data': {'workspaceOrError': {'locationEntries': [{'id': 'code-server-1',
                                                    'loadStatus': 'LOADED',
                                                    'locationOrLoadError': {'__typename': 'RepositoryLocation'}},
                                                   {'id': 'code-server-2',
                                                    'loadStatus': 'LOADED',
                                                    'locationOrLoadError': {'__typename': 'RepositoryLocation'}},
                                                   {'id': 'code-server-3',
                                                    'loadStatus': 'LOADED',
                                                    'locationOrLoadError': {'__typename': 'PythonError'}}]}}}
```
