### ISSUE TITLE
[ui] Remove random tag color background for unknown tags.

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#17570]
### What's the use case?

Currently Dagster assigns a (horrible) random color to unrecognized compute tags.

![image](https://github.com/dagster-io/dagster/assets/112868935/a1a2fb16-87ae-439d-91b6-bc7f62ab34eb)
![image](https://github.com/dagster-io/dagster/assets/112868935/9c74a0b7-e7e6-4148-b246-486b6ce8ecf1)
![image](https://github.com/dagster-io/dagster/assets/112868935/a6a0cf45-5714-43f8-aba8-8c466b4f9611)
![image](https://github.com/dagster-io/dagster/assets/112868935/0c0e9fb6-eeeb-41e3-a16d-c437406527b4)
![image](https://github.com/dagster-io/dagster/assets/112868935/432f55c6-f9e3-41c5-91ce-52cc220c8b1c)
![image](https://github.com/dagster-io/dagster/assets/112868935/55355059-8098-40c1-a6f5-9a133d8eacee)

(Note that we use these to know what the asset does at a glance - API call, Deprecated, Sends Email, Etc..)

I think this comes from your `colorHash` function, but I'm not 100% sure:

https://github.com/dagster-io/dagster/blob/6893b5a73ec1a08273a25e05317ee93115cb4c6a/js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx#L235C1-L247C2

```javascript
export function colorHash(str: string) {
  let seed = 0;
  for (let i = 0; i < str.length; i++) {
    seed = ((seed << 5) - seed + str.charCodeAt(i)) | 0;
  }


  const random255 = (x: number) => {
    const value = Math.sin(x) * 10000;
    return 255 * (value - Math.floor(value));
  };


  return `rgb(${random255(seed++)}, ${random255(seed++)}, ${random255(seed++)})`;
}
```

### Ideas of implementation

To me this is pretty bad. Could you please disable this? Or at least make it pick from a sensible color pallet. 

To me a hard-coded `compute_kind background color` for unknown tags would be preferable to the current implementation.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dduong1603** [comment]
I think it would be nice to have the ability to customize this color and other things as requested in #14967

**Comment by mkleinbort** [comment]
Customization would be great (eg. A ComputeTag object that can be initialized with all the nice properties that define a tag). But for now I feel removing the random background colour for some default gray background would be a big improvement.
