### ISSUE TITLE
Ability to see historical runs of the partitions

### ISSUE THREAD

**Issue by dongchris** [dagster-io/dagster#17586]
### What's the use case?

Currently you can see the latest materialization for each partition. However, would like to see every run executed for every partition as well. This will make debugging more robust because there are many cases where we would want to see past runs as well
![image](https://github.com/dagster-io/dagster/assets/86695140/c0a202ff-73f9-4c66-b092-b0adfceff238)

### Ideas of implementation

A few ways to do this:

- Can display multiple runs right below and indicate the time that it was ran
- Can add a way to filter for prior runs too (either with date picker or dropdown, etc)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey folks! I think this is currently supported (though without date picker filtering, which would be nice). From the partitions page in the screenshot, if you click a partition that has been materialized a small "prior events" link appears next to the most recent run:


![Image](https://github.com/dagster-io/dagster/assets/1037212/7b9fb8a7-7f01-45f7-bc6c-32d7e96febac)


Clicking that opens a modal showing the previous runs that materialized that partition, and you can expand them to see the metadata that was included with the materialization event.

I think we can probably clarify the UI around this and make this feature more prominent. I think it's confusing that it appears in the first column and not in the second column (for the current Run). I think the reason for that is that the event history can include both observation and materialization events. (cc @braunjj)

**Comment by bengotow** [comment]
I think this also came up in [#16601](https://github.com/dagster-io/dagster/issues/16601)
