### ISSUE TITLE
Display run status and link in backfill page

### ISSUE THREAD

**Issue by dongchris** [dagster-io/dagster#17582]
### What's the use case?

Under the Backfills tab, run status is all empty. Would like this to be populated and show the active run. Currently need to click “View backfill runs” and find the run I am looking for. OR I need to use the experimental feature under Deployment→Concurrency limits to find the active run
![image](https://github.com/dagster-io/dagster/assets/86695140/e51e14dc-8c4a-4c16-8954-65c715ef1901)

### Ideas of implementation

This is already available under Concurrency limits, copying it over would be sufficient
![image](https://github.com/dagster-io/dagster/assets/86695140/6583aa71-dece-456f-b5d5-916b4843cdf8)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey @clairelin135! For this one, I think it'd be ideal to make a version of the `assetBackfillData` that flattens the `assetBackfillStatuses` per-asset data into a single set of statuses, and then show that here? Is that something you could help with on the backend side?

**Comment by clairelin135** [comment]
Yup, I can add backend for this next week

**Comment by sryza** [comment]
A backfill could involve thousands of runs - what exactly are we imagining displaying here?

**Comment by clairelin135** [comment]
I personally was imagining something similar to the partition status counts displayed on asset nodes.

I.e. the backend returns back the # of partitions in each of the following states: not started, in progress, materialized, failed.

Then the UI will display counts for each status (with anything > 1000 displayed as 999+)

**Comment by sryza** [comment]
@dongchris does that match what you're looking for?

**Comment by dongchris** [comment]
Hmm can I reframe the request to somehow display what runs are active on the asset page instead of backfill? Most common use case is im monitoring a backfill but it's tedious to find the current active run

**Comment by sryza** [comment]
From the asset page, you should be able to see what partitions have active runs by using the checkboxes to filter for "Materializing" partitions. If you click on a partition, you can then see the active run working on it.

Note that there's currently a bug with this that can make it sometimes not work when the partitions are being materialized by a backfill that targets multiple partitions in each run. @clairelin135 has a fix out for this.

After that's fixed, would that work for you?

<img width="1162" alt="image" src="https://github.com/dagster-io/dagster/assets/654855/02273ce7-e3cf-4695-9cbd-fd0330422e32">

**Comment by sryza** [comment]
Going to close this based on @clairelin135 's fix, but please reopen (or file a new issue) if there's still functionality missing.
