### ISSUE TITLE
Schedule broken for multi-partitioned assets

### ISSUE THREAD

**Issue by brunobbaraujo** [dagster-io/dagster#17592]
### Dagster version

1.5.5

### What's the issue?

A strange bug occurs when creating a scheduler from a job linked to a multi-partitioned asset.

I created a repo showing how to reproduce the issue and proposing a solution.

### What did you expect to happen?

I expected the schedule to run successfully and yield RunRequests.

### How to reproduce?

https://github.com/brunobbaraujo/mwe-issue-dagster

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by brunobbaraujo** [comment]
I noticed that when I pass "partitions_def" parameter explicitly `in define_asset_job`, it works.
Maybe there needs to be a better message for this kind of error

**Comment by sryza** [comment]
@brunobbaraujo thanks for reporting this. Here's a fix: https://github.com/dagster-io/dagster/pull/17700.

**Comment by brunobbaraujo** [comment]
@sryza thanks for fixing this!
