### ISSUE TITLE
Add color syntax highlighting in docs

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#17611]
### What's the use case?

It would be nice if the docs site had syntax coloring rather than sad monocolor highlighting:

In docs site:

![Screenshot 2023-11-01 at 4 52 02 PM](https://github.com/dagster-io/dagster/assets/28738937/6776995d-f376-45bb-937d-ef118b10473c)

Compare to with color.

```python
class WriterResource(ConfigurableResource):
    str: prefix

    def create_resource(self, context: InitResourceContext) -> Writer:
        # Writer is pre-existing class defined else
        return Writer(self.prefix)

@asset
def use_preexisting_writer_as_resource(writer: ResourceParam[Writer]):
    writer.output("text")

defs = Definitions(
    assets=[use_preexisting_writer_as_resource],
    resources={"writer": WriterResource(prefix="a_prefix")},
)
```

With color sparks joy.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
This would be a huge improvement
