### ISSUE TITLE
Initial parameter to pipeline

### ISSUE THREAD

**Issue by eamag** [dagster-io/dagster#1761]
My pipeline: once a day check external db, get updated fields, calculate features if needed and insert or update features in other database (a. should I do the last step in some solid function or return results back to python wrapper?). I want to setup dag and call it from python once a day, but (b.) cannot find where I should pass parameter "date after which download updated fields". (c.) I also can't join slack because the link is now broken. Thanks

**Comment by eamag** [comment]
I also want to get database connection from environment (I use python's os.environ) and all other params from yaml file, how should I pass this to pipeline decorator? I cannot find combination of PresetDefinition and PresetDefinition.from_files

**Comment by natekupp** [comment]
Hey @eamag, some quick thoughts below, but happy to discuss further:

a.) If I understand your question correctly, I think having the last solid function in your pipeline do this update step should work well.
b.) we'll be adding more explicitly support for this "unit of work" or partition time in the future; for now, the best way for you to accomplish this is to (1) create a date config field for your solid, and then consume that configuration in your solid function definition, and (2) provide a specific date in your config YAML when you invoke the pipeline. You can see some of the documentation for this [here](https://dagster.readthedocs.io/en/0.5.9/sections/learn/tutorial/configuration_schemas.html) but please feel free to ask questions if you need help!
c.) Thanks a ton for flagging the broken Slack link—I just fixed it. Please try again, would love to discuss your use case there
d.) When you say that you get the database connection from the environment, what exactly do you mean? Do you mean the configuration parameters (URI, username, password, etc.) for creating a database connection?

**Comment by eamag** [comment]
Thanks a lot!
b.) That's what I do now, so no other way than changing the config file with template engine like jinja2, right?
d.) I want to wrap the dagster pipeline into the docker and have some configuration parameters (URI, username, password, etc.) in the docker env vars.

**Comment by natekupp** [comment]
b.) correct, no templating support, but I'll keep you posted on when we land something for explicit date partition support
d.) got it - one way you could do this is to specify an optional config value and provide a default that pulls from the environment:

```
@solid(
    config={'db_uri': Field(str, is_optional=True, default=os.environ.get('DB_URI'))
)
```
would that work?
