### ISSUE TITLE
Invalid time zone specified: Etc/Unknown

### ISSUE THREAD

**Issue by jaceksan** [dagster-io/dagster#17623]
### Dagster version

1.5.0

### What's the issue?

After traveling from EU to US west and back, when I start dagster, the error from title appears on some pages in the UI.

- Runs
- Deployment/Daemons
- 

Full error message:
```
Sorry, page can't be displayed.
Please report this error to the Dagster team via GitHub or Slack. Refresh the page to try again.
Loading chunk 713 failed.
(error: http://127.0.0.1:3001/_next/static/chunks/713.f981b85f36d1482f.js)

ChunkLoadError: Loading chunk 713 failed.
(error: http://127.0.0.1:3001/_next/static/chunks/713.f981b85f36d1482f.js)
    at p.f.j (http://127.0.0.1:3001/_next/static/chunks/webpack-4f9fcddb9e2602c5.js:1:5446)
    at http://127.0.0.1:3001/_next/static/chunks/webpack-4f9fcddb9e2602c5.js:1:1433
    at Array.reduce (<anonymous>)
    at p.e (http://127.0.0.1:3001/_next/static/chunks/webpack-4f9fcddb9e2602c5.js:1:1399)
    at http://127.0.0.1:3001/_next/static/chunks/317.a42fc99bc5c06af5.js:1:204251
    at T (http://127.0.0.1:3001/_next/static/chunks/framework-1db12f6a8a2cfbf2.js:25:3197)
    at i (http://127.0.0.1:3001/_next/static/chunks/framework-1db12f6a8a2cfbf2.js:9:119881)
    at oO (http://127.0.0.1:3001/_next/static/chunks/framework-1db12f6a8a2cfbf2.js:9:99058)
    at http://127.0.0.1:3001/_next/static/chunks/framework-1db12f6a8a2cfbf2.js:9:98925
    at oF (http://127.0.0.1:3001/_next/static/chunks/framework-1db12f6a8a2cfbf2.js:9:98932)
```

### What did you expect to happen?

The correct page content is displayed instead of the error message.

### How to reproduce?

Not sure. Does it relate to my traveling and changing time zones on my laptop? 

Also, meanwhile, the time shift happened in the EU (1-hour shift).

### Deployment type

Local

### Deployment details

Local deployment. I bootstrapped Dagster based on the onboarding guide in your DOC and then I filled it with integration with dbt and Meltano manually, based on examples in the corresponding documentations.

### Additional information

n/a

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for filing @jaceksan - triaging this to our UI team.

**Comment by salazarm** [comment]
This occurs when you upgrade dagster versions without restarting the webserver

**Comment by sryza** [comment]
@salazarm would it make sense for us to indicate that in the error message?

**Comment by salazarm** [comment]
Yeah I have a TODO to do something like this for cloud, I will make sure we have something similar for OSS

**Comment by jaceksan** [comment]
Thanks for the quick answer!

However, I am still not sure how to fix it in my project. Can you help me? I am a newbie...
