### ISSUE TITLE
Not capturing all logs in dagit log viewer

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1764]
If you run a simple pipeline like the pandas_hello_world pipeline. Only a couple log messages appear within the dagit UI:

![Screenshot 2019-09-25 10 52 01](https://user-images.githubusercontent.com/28738937/65626587-844ea580-df82-11e9-8221-c9effe634b82.png)

However there are a couple issues.

1) There are some step-level events that are not captured for some reason:

![Screenshot 2019-09-25 10 52 30](https://user-images.githubusercontent.com/28738937/65626641-9e888380-df82-11e9-97ec-3c2bb3b450ac.png)

2) And there is no spot to view log messages on "master" that aren't associated with a step.

**Comment by mgasner** [comment]
Hopefully this will be resolved by https://dagster.phacility.com/D1061 / we shouldn't try to fix until that diff lands

**Comment by prha** [comment]
336e3714 resolves 1.  Not sure about the best way to address 2...

**Comment by prha** [comment]
Closing this in favor of #1830 1830
