### ISSUE TITLE
Pressing enter undoes filter in runs typeahead.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1766]
Start with a mix of runs:

![Screenshot 2019-09-26 07 08 53](https://user-images.githubusercontent.com/28738937/65695498-840ae480-e02c-11e9-9326-0e7e4c94802d.png)

Filter down to particular one:

![Screenshot 2019-09-26 07 09 33](https://user-images.githubusercontent.com/28738937/65695566-9dac2c00-e02c-11e9-8e73-3d6d0acf0cf9.png)

Now keep the cursor in the search bar and press enter. The filtering is undone:

![Screenshot 2019-09-26 07 09 43](https://user-images.githubusercontent.com/28738937/65695605-ac92de80-e02c-11e9-9e69-83fe483559e6.png)

**Comment by schrockn** [comment]
On chrome and master as of 9707e2b446e30af60c3694812a613ef5ab78bc34

**Comment by bengotow** [comment]
Addressed in https://dagster.phacility.com/D1139
