### ISSUE TITLE
Dangling/Zombie tail processes

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1767]
![Screenshot 2019-09-26 07 26 16](https://user-images.githubusercontent.com/28738937/65696970-072d3a00-e02f-11e9-8955-0285e1d72e9f.png)

Looks like we are leaving lots of tail processes around. I assume this is related to the logging ish.

**Comment by prha** [comment]
are these recent?  I think this all gets addressed in https://github.com/dagster-io/dagster/commit/fbf1e2d0bd9bffd38444ee8dd0568b4ec70e88e3

**Comment by schrockn** [comment]
i'll restart my comp and see if they start accumulating again

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by prha** [comment]
Okay, closing for now... reopen if you see anything?

**Comment by schrockn** [comment]
Still seeing this

**Comment by schrockn** [comment]
![Screenshot 2019-09-28 06 18 44](https://user-images.githubusercontent.com/28738937/65817079-f0feb580-e1b7-11e9-80fb-c47e8fe9e1d8.png)

**Comment by prha** [comment]
resolved in 414df8099e035992baeb1a0351396326bfd1c23c.

it's a good thing you were working on cancellation and caught this, @schrockn
