### ISSUE TITLE
Dynamic partitioned assets fail materialisation when backfill policy set

### ISSUE THREAD

**Issue by bmarcj** [dagster-io/dagster#17693]
### Dagster version

1.5.6

### What's the issue?

When an asset is partitioned with dynamic partitions, and any backfill policy is explicitly set, the asset fails to materialise, instead failing with an error:

```
Backfill failed for nnloghpj: dagster._check.CheckError: Failure condition: The instance is not available to load partitions. You may be seeing this error when using dynamic partitions with a version of dagster-webserver or dagster-cloud that is older than 1.1.18.
```

### What did you expect to happen?

The materialisation should succeed.

### How to reproduce?

Create a dynamically partitioned asset. Explicitly set the backfill policy (`single_run()` or `multi_run(...)`) Attempt to materialise a partition in the ui.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks fro reporting this @bmarcj. Here's a fix: https://github.com/dagster-io/dagster/pull/17698.

**Comment by somiandras** [comment]
@sryza I'm running into this issue on 1.6.1. Is this possible or I'm missing something? 

I have one asset partitioned by a dynamic partition with `backfill_policy=BackfillPolicy.single_run()`. My backfills fail with the error above (`Failure condition: The instance is not available to load partitions ...`).

**Comment by sryza** [comment]
@somiandras - do you have a short code snippet I can run that reproduces your issue?

**Comment by somiandras** [comment]
@sryza Even the simplest example fails for me.

```python
@asset(
    name="test",
    partitions_def=my_partition_def,
    backfill_policy=BackfillPolicy.single_run(),
)
def test_asset():
    pass
```

`my_partition_def` is defined as:

```python
from dagster import DynamicPartitionsDefinition

my_partition_def = DynamicPartitionsDefinition(name="my_partition_def")
```

Starting a backfill from the Materialize UI results in this error:
<img width="1183" alt="image" src="https://github.com/dagster-io/dagster/assets/12885402/fc36bef6-a560-4ffc-80de-d42621b62569">

After removing `backfill_policy=BackfillPolicy.single_run()`  I can do a one run per partition backfill on the asset. I double checked, I'm on 1.6.1.

**Comment by wintersrd** [comment]
@sryza I can confirm the same issue with all dynamic partitions on single run backfill. The issue seems to stem from an issue in the logging, specifically this line:
https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/instance/__init__.py#L1586

Removing that line allows dynamic partitions to backfill in single_run. Tested by modifying the code locally with 
```
        try:
            if execution_plan_snapshot:
                self._log_asset_planned_events(
                    dagster_run, execution_plan_snapshot, asset_job_partitions_def
                )
        except Exception:
            sys.stderr.write("_log_asset_planned_events is broken with dynamic partitions")
```

**Comment by sryza** [comment]
Thanks for bearing with us on this one.  I think this got rebroken when we started logging per-partition materialization events.  Here's a fix: https://github.com/dagster-io/dagster/pull/19622.

**Comment by ElPincheTopo** [comment]
I think that this is still broken when using `context.partition_keys` instead of `context.partition_key_range`.
I'm getting the exact same error on version 1.10.6 when using dynamic partitions with `BackfillPolicy.single_run()` only difference is that I'm using `context.partition_keys` instead of `context.partition_key_range`.
