### ISSUE TITLE
Feature Request: Ability to Manually Mark a Failed Asset as Successful

### ISSUE THREAD

**Issue by jadenhpark** [dagster-io/dagster#17728]
### What's the use case?

Motivation

During our operations, we occasionally encounter failures in asset materialization due to external factors. Although these can be rectified manually (for example, by addressing issues directly in the database or file system), Dagster's asset tracking system still shows these assets as failed. The lack of an option to update the asset state without rerunning the pipeline poses a challenge, as it can be resource-intensive and sometimes unnecessary.

Use Case

An illustrative scenario is when dealing with data merges in our Data Catalog. If a task fails due to a transient error, such as a temporary network disruption, we can fix the issue manually using our internal tools. However, we need a way to reflect this resolution in Dagster without re-executing the entire pipeline, which is not always a practical solution.

### Ideas of implementation

We propose adding functionality that allows users to manually override the status of an asset to "successful." This could be implemented via a UI action for failed assets and extended to the Dagster API for programmatic access. This feature would significantly improve the handling of exceptions and reduce unnecessary computational work.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by petartonchev** [comment]
Hey, @jadenhpark, I how is this feature request different than the "Report materialization event" functionality that's discussed here https://github.com/dagster-io/dagster/issues/8795#issuecomment-1761945315 ?

**Comment by jadenhpark** [comment]
@petartonchev Yes, it does. Thanks for pointing out. I'll close this ticket.
