### ISSUE TITLE
Nested resource dependencies do not work when create_resource method is overridden

### ISSUE THREAD

**Issue by dwallace0723** [dagster-io/dagster#17727]
### Dagster version

1.4.10

### What's the issue?

The [docs](https://github.com/dagster-io/dagster/pull/17613/files#diff-0209b713906e6e525c3a69001ece16af00e59e7c246084047b5c113c9d129760R680-R707) for `ConfigurableResource` mention that users should override the `create_resource` method when they would like to vend an object of a different type at runtime. The [docs](https://docs.dagster.io/concepts/resources#resources-that-depend-on-other-resources) also mention that nested resource dependencies can be specified by marking a resource as an attribute on a downstream resource. 

Leveraging nested resource dependencies on their own appears to work just fine. For example, the following code executes successfully:

```python
class MyOtherResource(ConfigurableResource): ...

class MyResource(ConfigurableResource):
    other_resource: MyOtherResource
    
@op
def one_plus_one(resource: MyResource) -> int:
    return 1 + 1

@job
def dummy_job():
    one_plus_one()

defs = Definitions(
    jobs=[dummy_job],
    resources={"resource": MyResource(other_resource=MyOtherResource())},
)
```

However, when attempting to override the `create_resource` methods in addition to leveraging nested resources, you get surprising results:

```python
class MyOtherObject: ...
        
class MyObject: ...

class MyOtherResource(ConfigurableResource[MyOtherObject]):
    def create_resource(self, context: InitResourceContext) -> MyOtherObject:
        return MyOtherObject()

class MyResource(ConfigurableResource[MyObject]):
    other_resource: MyOtherResource

    def create_resource(self, context: InitResourceContext) -> MyObject:
        return MyObject()
    
@op
def one_plus_one(resource: ResourceParam[MyObject]) -> int:
    return 1 + 1

@job
def dummy_job():
    one_plus_one()

defs = Definitions(
    jobs=[dummy_job],
    resources={"resource": MyResource(other_resource=MyOtherResource())},
)
```

```
pydantic.error_wrappers.ValidationError: 2 validation errors for MyResource
other_resource
  value is not a valid dict (type=type_error.dict)
other_resource
  value is not a valid dict (type=type_error.dict)

  File "/opt/venv/lib/python3.10/site-packages/dagster/_core/errors.py", line 286, in user_code_error_boundary
    yield
  File "/opt/venv/lib/python3.10/site-packages/dagster/_core/execution/resources_init.py", line 324, in single_resource_event_generator
    resource_def.resource_fn(context)
  File "/opt/venv/lib/python3.10/site-packages/dagster/_config/pythonic_config/__init__.py", line 556, in setup_context_resources_and_call
    return self._resource.resource_fn(context_with_key_mapping)
  File "/opt/venv/lib/python3.10/site-packages/dagster/_config/pythonic_config/__init__.py", line 949, in _initialize_and_run
    with self._resolve_and_update_nested_resources(context) as has_nested_resource:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/venv/lib/python3.10/site-packages/dagster/_config/pythonic_config/__init__.py", line 926, in _resolve_and_update_nested_resources
    yield self._with_updated_values(to_update)
  File "/opt/venv/lib/python3.10/site-packages/dagster/_config/pythonic_config/__init__.py", line 879, in _with_updated_values
    out = self.__class__(**{**self._get_non_none_public_field_values(), **values})
  File "/opt/venv/lib/python3.10/site-packages/dagster/_config/pythonic_config/__init__.py", line 772, in __init__
    Config.__init__(self, **{**data_without_resources, **resource_pointers})
  File "/opt/venv/lib/python3.10/site-packages/dagster/_config/pythonic_config/__init__.py", line 243, in __init__
    super().__init__(**modified_data)
  File "/opt/venv/lib/python3.10/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
```

It appears as if it is a pydantic validation error when validating the nested resource attribute. I imagine this could be resolved by updating the data type of the attribute representing the nested resource to be the actual data type instead of the _resource_ type (e.g. `MyOtherObject` instead of `MyOtherResource`) but I'm not sure how that would mess up the Dagster resource dependency graph internally.

### What did you expect to happen?

I would expect to be able to use these two pieces of functionality together.

### How to reproduce?

Code to reproduce included in description.

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by samoor64** [comment]
+ 1

**Comment by jamiedemaria** [comment]
thanks for raising this issue! @benpankow  you're probably in the best position to address this or figure out who should address it

**Comment by jzgrzebnicki** [comment]
Same problem here: I have resources that previously were function resources (as provided in docs override create_resource method) and now can't migrate to new pythonic resource system as the same type of error occur

**Comment by benpankow** [comment]
Looking into why this is occurring - for now, I think that manually marking the resource as a `ResourceDependency` should allow this pattern to work:

```pythonfrom dagster import ConfigurableResource, InitResourceContext, job, op, ResourceParam, Definitions, ResourceDependency

class MyOtherObject: ...
        
class MyObject(): ...

class MyOtherResource(ConfigurableResource[MyOtherObject]):
    def create_resource(self, context: InitResourceContext) -> MyOtherObject:
        return MyOtherObject()

class MyResource(ConfigurableResource[MyObject]):
    other_resource: ResourceDependency[MyOtherObject]

    def create_resource(self, context: InitResourceContext) -> MyObject:
        assert isinstance(self.other_resource, MyOtherObject)
        return MyObject()
    
@op
def one_plus_one(resource: ResourceParam[MyObject]) -> int:
    assert isinstance(resource, MyObject)
    return 1 + 1

@job
def dummy_job():
    one_plus_one()

defs = Definitions(
    jobs=[dummy_job],
    resources={"resource": MyResource(other_resource=MyOtherResource())},
)
```

**Comment by jzgrzebnicki** [comment]
In my case using ResourceDependency solve the problem. But to be honest It should be better documented.

**Comment by emirkmo** [comment]
`ResourceDependency` is missing. It is required and the docs now mention it. @dwallace0723  if adding this solves your issue, can you close it? It is solved afaik.
