### ISSUE TITLE
reconsider the user-facing requirement that types be wrapped in Field for config

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1777]

**Comment by schrockn** [comment]
Can you go over this one a bit? We could add another top-level argument in addition to `config` and `config_field` to be `config_type` that allows this, but i think there is a cost to adding more surface area to API

**Comment by mgasner** [comment]
I suppose the question I have in mind here is, anywhere we expect to see `Field`, why we can't also accept a naked config type and automatically wrap it in `Field` -- just to reduce boilerplate. I grant the value of being explicit, but we could do this translation, e.g., only in `@solid`. I have a hunch that people are often going to write `{'foo': ConfigType}` as they spin up on the system, see some errors, write `{'foo': Field(ConfigType)}`, not quite knowing why, maybe put the `Field()` wrapper in the wrong place, etc., etc.

**Comment by schrockn** [comment]
I just generally find that type of type coercion quite distasteful. It feels pretty terrible in graphene as an example and I think this same thing applies here.

**Comment by mgasner** [comment]
Closing this as a dupe of #1908
