### ISSUE TITLE
DBT backfills are broken because single-runs are executed as separate runs

### ISSUE THREAD

**Issue by qgab-flowdesk** [dagster-io/dagster#17778]
### Dagster version

dagster, version 1.5.5

### What's the issue?

Since the removal of `single run` execution mode of partitioned assets in the UI, it is not possible to run backfill `dbt` partitioned jobs in a single run. 

Because `dbt` creates temporary tables that does not have unique IDs, running several jobs concurrently on the same table will have side effects (tmp table is unaccessible by run partition B because it's just been deleted by partition A c). This can't be bypassed otherwise than by grouping the data within the `dbt` models with a `group by partition` and running the backfill as a single run. Since single run are not available anymore, it's not possible to do backfill neither. 

### What did you expect to happen?

Single run executing as single runs rather than separate runs. 

### How to reproduce?

- [ ] Set-up a job following [building-incremental-models-using-partitions](https://docs.dagster.io/integrations/dbt/reference#building-incremental-models-using-partitions) guide
- [ ] Define an asset with N partitions, with BackfillPolicy.single_run()
- [ ] Open the backfill dialog for that asset
- [ ] Notice that the button to launch the backfill says "Launch N-run backfill"

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
`@dbt_assets` takes in a `backfill_policy` parameter to configure this. See our [API docs](https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.dbt_assets) and our [`1.5.3` release notes](https://github.com/dagster-io/dagster/releases/tag/1.5.3).

Have you configured these parameters to accomplish your use case?

**Comment by bmarcj** [comment]
If this really is broken with multi-run, what's the case to ever allow anything but single-run? It seems both incremental and fully partitioned dbt models are better suited to the latter.

It could at least be the default.

**Comment by qgab-flowdesk** [comment]
@rexledesma nop I tried the `backfill_policy=BackfillPolicy.single_run()`, yet N runs are triggered. 
@bmarj for `dbt` I think I agree with you, I think this is a problem that will occur with most backend except `trino`

**Comment by rexledesma** [comment]
> Notice that the button to launch the backfill says "Launch N-run backfill"

@qgab-flowdesk This is a UI bug. When you launch the backfill, only a single run will be created. This was fixed in `dagster==1.5.6`: https://github.com/dagster-io/dagster/pull/17540.

Could you try upgrading and seeing if the issue persists?

> If this really is broken with multi-run, what's the case to ever allow dbt to operate in anything but single-run mode?

@bmarcj With time window partitions, this is correct. But if the user chooses to partition their dbt assets statically, a single-run may not be feasible.

But your comment is taken. For most cases, single-run mode should be chosen. For example, it should be chosen with [the partition guidance we give in our docs](https://docs.dagster.io/integrations/dbt/reference#building-incremental-models-using-partitions). 

To address this, we can make a change to change the default `backfill_policy` depending on whether the `partition_def` is static or a time window.

**Comment by rexledesma** [comment]
Once https://github.com/dagster-io/dagster/pull/17822, we should provide a sensible default.

I will close this issue when @qgab-flowdesk confirms that `dagster==1.5.6` fixed your problem.

**Comment by qgab-flowdesk** [comment]
@rexledesma 
I updated all my environments to 1.5.6 and yet the issue remains. The local dagster logs where is specified the warning about experimental backfill_policy:
<img width="1477" alt="Screenshot 2023-11-09 at 14 48 33" src="https://github.com/dagster-io/dagster/assets/138511470/f575d774-16c4-4233-b1e9-6ea3ecd65fd4">

The 2 runs that are triggered despite the `backfill_policy=BackfillPolicy.single_run()`:
<img width="1964" alt="Screenshot 2023-11-09 at 12 36 21" src="https://github.com/dagster-io/dagster/assets/138511470/85f7d935-9299-4313-8a78-a45df1dbe935">

**Comment by rexledesma** [comment]
@qgab-flowdesk I misunderstood you. You expect that the `backfill_policy` is respected on the asset job. 

Your issue is more along the lines of https://github.com/dagster-io/dagster/issues/17665:

> asset job backfills don't respect backfill policies.

Could you follow up on that issue instead? Thanks. I'm closing this issue to consolidate.
