### ISSUE TITLE
consider whether it is possible to support destructuring syntax in the pipeline definition DSL

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1778]

**Comment by schrockn** [comment]
this is a bit unclear imo

**Comment by mgasner** [comment]
e.g., if i have a solid with multiple outputs:

```
@pipeline
def my_pipeline():
    a, b = multiple_output_solid()
    some_other_solid(a, b)
```

**Comment by catherinewu** [comment]
based on the [tutorial]( https://docs.dagster.io/tutorial/basics_solids#multiple-and-conditional-outputs), sounds like this exists so will close..
