### ISSUE TITLE
Fully incremental reexecution with memoized intermediate results

### ISSUE THREAD

**Issue by stratospark** [dagster-io/dagster#1784]
What is the mechanism, if any, to prevent subtasks/solids from being repeated if already run? In a system like Luigi, this is based on if an output file, as a result of a task, exists. Ideally, I would like to use the outputs of existing solids to serve as the precomputed inputs for multiple pipelines of solids that may be defined at a later point in time.

**Comment by prha** [comment]
Hey @stratospark... great question!

We'd like to build in similar functionality into the execution engine itself, but we're still figuring out the details of exactly how that would work.

Right now, the best way to handle this would be with a custom memoization solid, that stores the output somewhere (filesystem, database) and potentially checks on re-execution if it should load and reuse that output or recompute.

**Comment by mgasner** [comment]
You can also use pipeline subset selection to execute only parts of a pipeline.

**Comment by catherinewu** [comment]
cc @sryza

**Comment by catherinewu** [comment]
@stratospark here is our current implementation of memoized compute: https://docs.dagster.io/examples/memoized_development#main we would love to hear your feedback if you try it out!
