### ISSUE TITLE
Dagster AWS spinup round up

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1785]
Just went through the aws spinup. Pretty magical. Using this issue as a tracking issue. We may want to break out individual tasks:

1. "Select a VPC [default: vpc-a6d3fdc1]": Can you make it more clear this is using an existing VPC rather than creating one for you?
2. "Do you want to install Dagster / Dagit from Github? (default: use stable from PyPI) [y/N]" I think this would feel a lot of better if we forced the user to have a requirements.txt file (we could autogenerate it). That way we could pin the dagster/dagit install to a specific hash of master which would be much better for reproducability etc.
3. Spit out URL of hosted instance: Once the instance is created and dagit spun up print out the URL where you can navigate to dagit.
4. Got this error when I shelled in: "bash: line 0: cd: /opt/dagster: No such file or directory"
5. A `dagster-aws info` command might be good which would just print out all the information about a node. It's also not clear to me how this will work if we spin up multiple dagit instances.
6. When I tried to "clear" (I would consider delete btw) I was unable to delete the security group. Is this because it was reusing a different security group spun up by someone else using dagster-aws? That was all a little unclear to me.

**Comment by natekupp** [comment]
Awesome, thanks for running through this!

1. Agree https://dagster.phacility.com/D1157
2. We support providing a `requirements.txt` during `dagster-aws up`; this is just to drive the initialization of the VM. I could move this to that location, but it feels like we should be able to get all the dagster/dagit stuff in place _before_ installing a user's requirements for their particular application. Thoughts?
3. Yes, we pop open a browser on `dagster-aws up` but also agree we should print it - see https://dagster.phacility.com/D1158
4. This is a consequence of the AWS boto3 library reporting an instance as "ready" after it has booted, but before the init script has completed. I haven't yet found a way to hook on init script completion, will look some more today
5. Yes, this is a great idea - will add this today
6. Yeah I guess "clear" got added in the "nuke" removal, I think "delete" would be better here. As you guessed, I have been re-using a single security group for all `dagster-aws` instances, but I think I'll transition to just having 1 SG per instance—it's much less confusing that way, particularly in this cleanup phase

**Comment by natekupp** [comment]
Found a solution to (4) https://dagster.phacility.com/D1159 - it definitely takes a couple of minutes longer, but at least now you get an instance in a known-good state.
