### ISSUE TITLE
Attach debugger to dev instance of dagster

### ISSUE THREAD

**Issue by EtienneT** [dagster-io/dagster#17859]
### What's the use case?

You are coding a new asset, a new sensor, anything in dagster and you need to debug the code to be able to inspect variables and understand what is going on.  It would be awesome to be able to attach the debugger of a tool like vscode to debug things in our dagster project.  The debugger would attach to the dev instance of dagster, you could set breakpoints in an asset for example and as soon as you materialize this asset in the UI, it would trigger your breakpoint.

Same thing for sensors or job.  As soon as it runs in dagster, if your debugger is attached your breakpoints hit and you can inspect all variables.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
Hi @EtienneT  the `context` in `ops

**Comment by EtienneT** [comment]
Hey @jamiedemaria, thanks for your response.  Do you have a tutorial on how to leverage the context pdb?

Using a unit test is ok, but sometimes you have real world data you want to test with.  Something that would take a lot of time to reproduce in a unit test.  Being able to test with the real data inside dagster would be really helpful.

Another example is testing sensors.  Right now you save your code inside vscode, the executing sensor in dagster does not refresh automatically, you have to reload the location manually several times and it finally pickup the new code.  You have to debug with context.log.info to get any meaningful info.  I could have tested using unit tests, but sometimes the relevant information I want to test with is inside the data of my dagster instance.

The dream would be to be able to attach the debugger to a live instance of dagster dev directly from visual studio.  Put breakpoints in anything and it would hit.

Also when saving a python file like an asset, sensor, schedule etc, when running in dev, the code location needs to reload immediately.

Those two changes would bring the developer experience to a completely different level.

**Comment by EtienneT** [comment]
This works!  Thanks a lot!  I think this should be front and center in some of your quick starts.  Really useful.

**Comment by Rupin817** [comment]
@jamiedemaria do we have similar thing in pycharm?

**Comment by emod02** [comment]
@Rupin817 you can create in PyCharm a similar Run/Debug Configuration. 

Create a new Python Config, in topic "Run" set the right interpreter and swtich to "module" (defeault is "script") and set the corresponding textfield to "dagster". As "script parameters" set "dev".
In your `run.xml` there should be these options:
```
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="your name here" type="PythonConfigurationType" factoryName="Python">
    ....
    <option name="SCRIPT_NAME" value="dagster" />
    <option name="PARAMETERS" value="dev" />
    <option name="MODULE_MODE" value="true" />
    ....
  </configuration>
</component>
```

**Comment by don1uppa** [comment]
> @Rupin817 you can create in PyCharm a similar Run/Debug Configuration.
> 
> Create a new Python Config, in topic "Run" set the right interpreter and swtich to "module" (defeault is "script") and set the corresponding textfield to "dagster". As "script parameters" set "dev". In your `run.xml` there should be these options:
> 
> ```
> <component name="ProjectRunConfigurationManager">
>   <configuration default="false" name="your name here" type="PythonConfigurationType" factoryName="Python">
>     ....
>     <option name="SCRIPT_NAME" value="dagster" />
>     <option name="PARAMETERS" value="dev" />
>     <option name="MODULE_MODE" value="true" />
>     ....
>   </configuration>
> </component>
> ```

There must be some detail you are leaving out.

**Comment by idiked** [comment]
@don1uppa are you using Python 3.11 or 3.12?
PyCharm has issues with debugging subprocesses in these versions: https://youtrack.jetbrains.com/issue/PY-61217/Cannot-attach-to-subprocess-when-debugging-with-Python-3.11-3.12
Switching to Python 3.10 has helped me

**Comment by emod02** [comment]
> > @Rupin817 you can create in PyCharm a similar Run/Debug Configuration.
> > Create a new Python Config, in topic "Run" set the right interpreter and swtich to "module" (defeault is "script") and set the corresponding textfield to "dagster". As "script parameters" set "dev". In your `run.xml` there should be these options:
> > ```
> > <component name="ProjectRunConfigurationManager">
> >   <configuration default="false" name="your name here" type="PythonConfigurationType" factoryName="Python">
> >     ....
> >     <option name="SCRIPT_NAME" value="dagster" />
> >     <option name="PARAMETERS" value="dev" />
> >     <option name="MODULE_MODE" value="true" />
> >     ....
> >   </configuration>
> > </component>
> > ```
> 
> There must be some detail you are leaving out. Here is what I get: /Users/donaldiuppa/dagster/.venv/bin/python -X pycache_prefix=/Users/donaldiuppa/Library/Caches/JetBrains/PyCharm2023.3/cpython-cache /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --module --multiprocess --qt-support=auto --client 127.0.0.1 --port 57278 --file dagster dev Connected to pydev debugger (build 233.13763.11) Usage: python -m dagster dev [OPTIONS] Try 'python -m dagster dev --help' for help.
> 
> Error: No arguments given and no [tool.dagster] block in pyproject.toml found. When I add: dev -m mindoula_dagster as the arguments it runs but ignores my breakpoints

Mhh the python call seems correct to me (nothing else for me):
`...\venv\Scripts\python.exe -X pycache_prefix=...\AppData\Local\JetBrains\IntelliJIdea2024.1\cpython-cache ".../AppData(Roaming)/JetBrains/IntelliJIdea2024.1/plugins/python/helpers/pydev/pydevd.py" --module --multiprocess --qt-support=auto --client 127.0.0.1 --port 57584 --file dagster dev`
So I guess, the problem is maybe not the run config? I'm using Python 3.11 and IntelliJ 2024.1.1 with Python Plugin on a Windows machine, maybe there is the "problem".

**Comment by idiked** [comment]
@emod02 PyCharm has problems with debugging subprocesses in Python 3.11, 3.12: https://youtrack.jetbrains.com/issue/PY-61217/Cannot-attach-to-subprocess-when-debugging-with-Python-3.11-3.12

Try to use 3.9 or 3.10. And disable `python.debug.asyncio.repl` in PyCharm Registry (by default, double shift and search "Registry")

**Comment by HynekBlaha** [comment]
For those affected by the same bug: I am able to run debugger with Python 3.12 on PyCharm Professional Edition 2024.2.

**Comment by jakubczaplicki** [comment]
> For those affected by the same bug: I am able to run debugger with Python 3.12 on PyCharm Professional Edition 2024.2.

@HynekBlaha : Could you please provide more details on how you accomplished this?

**Comment by HynekBlaha** [comment]
@jakubczaplicki I am not aware of any extra setup. It just started working after PyCharm update.

**Comment by finalgrrrl** [comment]
@jamiedemaria [this](https://github.com/dagster-io/dagster/issues/17859#issuecomment-1805916514) almost works for me. the problem is that after i attach to the debug process and hit my trace/breakpoint, the logs from other threads continue to stream in the terminal making it difficult to actually get much useful information from the debugging console.

any thoughts/ideas?

**Comment by jamiedemaria** [comment]
hey @finalgrrrl. I haven't run into this specific issue before. Other threads will still log messages to the terminal, but I've found i can still run commands, see the values of variables, etc in the `Debugging console` tab and `Variables` and `Watch` sidebars. Maybe some other folks in the thread will have advice!
