### ISSUE TITLE
Support dbt's log-format flag in dagster-dbt integration

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1786]
See:

https://github.com/fishtown-analytics/dbt/issues/1237
https://github.com/fishtown-analytics/dbt/pull/1791/files

**Comment by rexledesma** [comment]
I believe this is already supported since our dbt cli resource can be permissively configured. Users can pass `{"log-format": true}` when configuring the resource. 

See https://docs.dagster.io/integrations/dbt#cli-examples.
