### ISSUE TITLE
Code locations page scrambled

### ISSUE THREAD

**Issue by alexknorr** [dagster-io/dagster#17892]
### Dagster version

1.5.7

### What's the issue?

Updated from 1.4.16 to 1.5.7 and found that the Code locations page layout is a bit scrambled now.
The locations table height is very small hiding some bottom parts (showing a vertical scroll-bar where it is not needed) and the row-columns are not in line with the header-columns.
I could make an screenshot but don´t know how to post it here.

### What did you expect to happen?

Sound page table-layout.

### Deployment type

Other

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mmutso-boku** [comment]
I can second this. Upgraded from 1.5.4 to 1.5.7, and the code locations CSS is now a bit messed up - the last code location (out of total 4) is partly hidden and there is an unnecessary scrollbar for that table.

**Comment by hellendag** [comment]
@mmutso-boku What browser are you using?

**Comment by mmutso-boku** [comment]
> @mmutso-boku What browser are you using?

Chrome 119.0.6045.105
