### ISSUE TITLE
Clicking "+XX More" Button in Scheduler goes to blank page

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1789]

**Comment by schrockn** [comment]
![Screenshot 2019-10-02 09 55 36](https://user-images.githubusercontent.com/28738937/66064747-db142c00-e4fa-11e9-957d-2bf734c86ff2.png)

Click on +71 more

Goes back to blank home page.

![Screenshot 2019-10-02 09 56 42](https://user-images.githubusercontent.com/28738937/66064795-f41cdd00-e4fa-11e9-9fa1-f783c1f73fb3.png)

**Comment by helloworld** [comment]
https://dagster.phacility.com/D1170
