### ISSUE TITLE
Be able to load a scheduled job into execution console

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1790]
Would be nice to be able to take a scheduled job and load up the config and execute it in an ad-hoc way.

![Screenshot 2019-10-02 10 05 02](https://user-images.githubusercontent.com/28738937/66065388-1d8a3880-e4fc-11e9-9b08-695aae83fc00.png)

So this menu:

![Screenshot 2019-10-02 10 05 42](https://user-images.githubusercontent.com/28738937/66065438-3d216100-e4fc-11e9-8224-105b718571d1.png)

Should have this button:

![Screenshot 2019-10-02 10 05 26](https://user-images.githubusercontent.com/28738937/66065422-32ff6280-e4fc-11e9-9a82-90d4215a2c76.png)

**Comment by helloworld** [comment]
https://dagster.phacility.com/D1171
