### ISSUE TITLE
Allow Optional types when using allow_nonexistent_upstream_partitions

### ISSUE THREAD

**Issue by EtienneT** [dagster-io/dagster#17910]
### Dagster version

1.5.5

### What's the issue?

When you specify an asset that can have missing dependencies, we have to be able to specify Optional in our typings:

```
@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2017-01-01", end_offset=1, timezone="US/Eastern"),
    ins={
        "price_archive": AssetIn(partition_mapping=TimeWindowPartitionMapping(allow_nonexistent_upstream_partitions=True)),
        "price_recent": AssetIn(partition_mapping=TimeWindowPartitionMapping(allow_nonexistent_upstream_partitions=True))
    },
    io_manager_key="duckdb",materialize this asset
    backfill_policy=BackfillPolicy.single_run(),
    metadata={"partition_expr": "Time"}
)
def price_daily(context: AssetExecutionContext, price_archive: Optional[dict[str, pd.DataFrame]], price_recent: Optional[dict[str, pd.DataFrame]]) -> pd.DataFrame:
    ...
```
where price_archive and price_recent are also partitionned daily.

Then when I run a single run backfill where price_archive doesn't have any partition, I get the following error:

```
dagster._check.CheckError: Failure condition: Loading an input that corresponds to multiple partitions, but the type annotation on the op input is not a dict, Dict, Mapping, or Any: is 'typing.Optional[typing.Dict[str, pandas.core.frame.DataFrame]]'.
```

### What did you expect to happen?

I expected to be able to make those fields Optional.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
hey @EtienneT  thanks for bringing this up. I'll take a look when I can carve out some time this week

**Comment by jamiedemaria** [comment]
One odd thing is that the error you're seeing 
```
dagster._check.CheckError: Failure condition: Loading an input that corresponds to multiple partitions, but the type annotation on the op input is not a dict, Dict, Mapping, or Any: is 'typing.Optional[typing.Dict[str, pandas.core.frame.DataFrame]]'.
``` 

isn't raised by the duckdb io manager. It is raised by any io manager inheriting from the `UPathIOManager` though. That would be filesystem based io managers like the default io manager, S3 io manager, GCS io manager, etc. Can you double check that your assets are using the io manager you expect?

**Comment by EtienneT** [comment]
You are right!  I tested it again and it is now working.  I must have forgotten to specify my iomanager before testing.  Sorry about that.
