### ISSUE TITLE
dagster-mysql schema data type for Asset_keys.last_materialization and event_logs.event

### ISSUE THREAD

**Issue by zee-mel-2022** [dagster-io/dagster#17982]
### Dagster version

1.5.7

### What's the issue?

Hey, Dagster team can you please fix the bug for dagster-mysql schema data type. I tried to make a line graph using matplotlib, but it was not saved as md content but the bar graph was saved due to it being small in size as compared to a line graph. I highly suggest that you change the data type Asset_keys.last_materialization and event_logs.event from text to LongText which supports very high sizes. Also attached is a Jupiter output of my code for the multi-line graph.

The failure is coming from dagster MySQL db that it’s too long. Please check the main thread photo attached. In Postgres the text size is unlimited where as MySQL text size is fixed. This can be fixed by changing the data type of the column that support highest size of the table and save asset md content in MySQ

### What did you expect to happen?

Save the multiline graph as md content in Dagster's MySql DB
![image (11)](https://github.com/dagster-io/dagster/assets/143694545/aa9bcdfa-30f8-47c2-b6b0-d6f1f1b4940a)
![image (11)](https://github.com/da
![image (13)](https://github.com/dagster-io/dagster/assets/143694545/26fa7bab-8f3a-48c7-b6c2-7b3886e247a0)
gster-io/dagster/assets/143694545/8a35309d-220e-412a-81ff-85f5eea16eb3)
![image (12)](https://github.com/dagster-io/dagster/assets/143694545/a4362c35-93a2-403e-81db-97c99014382e)

### How to reproduce?

Using matplotlib make complex multi line and store it as asset metadata. 

`
      import base64
      import datetime
      import io
      import math
      from datetime import timedelta
      import matplotlib.pyplot as plt
      import pandas as pd

      def multi_plot_line_for_accuracy(df: pd.DataFrame(), start_date: str, end_date: str) -> str:
          us = df.loc[df['country_x'] == 'US', 'Hourly_FA'].astype(float).values.tolist()
          jp = df.loc[df['country_x'] == 'JP', 'Hourly_FA'].astype(float).values.tolist()
          au = df.loc[df['country_x'] == 'AU', 'Hourly_FA'].astype(float).values.tolist()
          india = df.loc[df['country_x'] == 'IN', 'Hourly_FA'].astype(float).values.tolist()
      
          x = df.loc[df['country_x'] == 'US', 'ds']
      
          plt.subplot(2, 1, 1)
          plt.plot(x, us, '.-', color='green')
          plt.title("US Hourly Accuracy")
          plt.xticks(rotation=45, ha="right")
          plt.subplot(2, 1, 2)
          plt.plot(x, jp, '.-', color='red')
          plt.title("JP Hourly Accuracy")
          plt.xticks(rotation=45, ha="right")
          plt.xlabel("Dates")
          plt.ylabel("Hourly Accuracy")
          plt.suptitle(f'US - JP Hourly Accuracy between:{start_date} - {end_date},', fontsize=10)
          plt.tight_layout()
      
          img = io.BytesIO()
          plt.savefig(img, format="png")
          image_data = base64.b64encode(img.getvalue())
      
          # Convert the image to Markdown to preview it within Dagster
          md_content = f"![img](data:image/png;base64,{image_data.decode()})"
          print(f" length of md content {len(md_content)} \n")`
          return md_content
      df = pd.DataFrame({"country_x": ['US', 'JP'], "Hourly_FA": [0.95, 0.30], "ds": [datetime.datetime.now(),datetime.datetime.now() ] })
      md = multi_plot_line_for_accuracy(df, "test", "test2")
`

### Deployment type

Docker Compose

### Additional information

https://dagster.slack.com/archives/C01U954MEER/p1698361753707969

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
Yes, it is a blocker for us.

**Comment by prha** [comment]
Hi @zee-mel-2022 ... thanks for flagging this!

I have put up [a PR](https://github.com/dagster-io/dagster/pull/18120) that should change the stated schema of the MySQL event cols to be longtext, but as it currently stands will only affect new MySQL storages.  You can alter the column types of the `event_logs.event` and the `asset_keys.last_materialization` column manually to migrate your existing instance.

**Comment by prha** [comment]
I've posted this discussion to document this: https://github.com/dagster-io/dagster/discussions/18313.  Let me know if you're unable to resolve.
