### ISSUE TITLE
Auto-materialize daemon can no longer see some partitions have materialized in upstream

### ISSUE THREAD

**Issue by mmutso-boku** [dagster-io/dagster#18024]
### Dagster version

1.5.7

### What's the issue?

After upgrading from 1.5.4 to 1.5.7, something has broken regarding auto-materialize, and upstream assets having negative end_offset. Auto-materialize daemon skips partitions giving the reason that "Required parent partitions do not exist", however they do exist when looking at the upstream asset partitions. This only seems to happen when upstream asset partitionsdefinition has negative end_offset. 
It also seems that the "Required parent partitions do not exist" affected partitions list starts from the day the version upgrade was done, so it is "cumulative".

### What did you expect to happen?

I expect auto-materialize daemon to find these upstream partitions, as it did in version 1.5.4

### How to reproduce?

Haven't tried to reproduce it in local, but the affected scenarios for me are:

Asset A - Hourly, end_offset=-4 (or -6)
Asset B - Daily, Downstream of Asset A (and other assets which do not have end_offset), eager automaterialize

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mmutso-boku** [comment]
From my own testing and observations, it seems that partitions materialized pre-upgrade are somehow different from partitions materialized after upgrade.

One changelog note stood out to me from 1.5.5:
> Dramatically improved the performance of partition-mapping, for basic hourly and daily partitions definitions

**Comment by OwenKephart** [comment]
Hi @mmutso-boku -- a fix for this behavior has been merged in and will go out in the next release.
