### ISSUE TITLE
failed partitions single-run backfills don't show up in asset nodes or on details page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#18020]
### To reproduce

Launch a single-run backfill of a couple partitions of this asset:

```python
@asset(
    partitions_def=DailyPartitionsDefinition(start_date="2023-10-10"),
    backfill_policy=BackfillPolicy.single_run(),
)
def asset1() -> None:
    raise RuntimeError()
```

Notice that:
- A failed run shows up on the Runs page
- The asset node does not show any failed partitions
  <img width="282" alt="image" src="https://github.com/dagster-io/dagster/assets/654855/50df9525-0a31-47a6-9622-ed1f15a98ed9">
- The asset details page does not show any failed partitions

**Comment by clairelin135** [comment]
Will be resolved by:
- https://github.com/dagster-io/dagster/pull/18305
- https://github.com/dagster-io/internal/pull/7615

**Comment by ion-elgreco** [comment]
@clairelin135 shouldn't this be closed by now then?

**Comment by clairelin135** [comment]
We were able to land the fixes on cloud, but OSS requires additional database schema changes in order to support this.

Closing for now.
