### ISSUE TITLE
Auto-materialize doesn't trigger with eager

### ISSUE THREAD

**Issue by marcilj** [dagster-io/dagster#18042]
### Dagster version

dagster, version 1.5.8

### What's the issue?

I've setup a `fully-featured-project`  where I've modified the `CustomDagsterDbtTranslator` to set an `eager` auto-materialize policy on all dbt models with a freshness policy.

```python
class CustomDagsterDbtTranslator(DagsterDbtTranslator):
    @classmethod
    def get_asset_key(cls, dbt_resource_props: Mapping[str, Any]) -> AssetKey:
        return super().get_asset_key(dbt_resource_props).with_prefix("snowflake")

    def get_auto_materialize_policy(
        self, dbt_resource_props: Mapping[str, Any]
    ) -> Optional[AutoMaterializePolicy]:
        return AutoMaterializePolicy.eager(max_materializations_per_minute=1)

    def get_freshness_policy(
        self, dbt_resource_props: Mapping[str, Any]
    ) -> Optional[FreshnessPolicy]:
        return FreshnessPolicy(maximum_lag_minutes=60)
```

The problem is that even if I build a partition for all the `core` models.

<img width="517" alt="image" src="https://github.com/dagster-io/dagster/assets/89793010/a8b10070-9861-44fb-998e-505319212ad1">

Dagster is not seeing the data as updated, so it won't trigger a run for the downstream models
<img width="620" alt="image" src="https://github.com/dagster-io/dagster/assets/89793010/4d65f15e-f416-4b7a-82ff-3b97660b0571">

even if they are overdue, and if the conditions should all be met
<img width="339" alt="image" src="https://github.com/dagster-io/dagster/assets/89793010/779bdade-eadd-44e9-9b1b-e89d5b0eca96">

If we looked at the Auto-Materialization History, we can see that Dagster was about to start a run, but the upstream model were not finished to be updated so it stopped. The problem is that all the other checks doesn't consider the parent as updated.
<img width="1168" alt="image" src="https://github.com/dagster-io/dagster/assets/89793010/edc1bef2-4ea4-482a-acbe-3050c9caac1a">

### What did you expect to happen?

I expect `comment_daily_stats` to get built once upstream data is updated.

### How to reproduce?

Create a fully-featured-project using the command like `dagster project from-example --example project_fully_featured`

Change the `CustomDagsterDbtTranslator` to this

```python
class CustomDagsterDbtTranslator(DagsterDbtTranslator):
    @classmethod
    def get_asset_key(cls, dbt_resource_props: Mapping[str, Any]) -> AssetKey:
        return super().get_asset_key(dbt_resource_props).with_prefix("snowflake")

    def get_auto_materialize_policy(
        self, dbt_resource_props: Mapping[str, Any]
    ) -> Optional[AutoMaterializePolicy]:
        return AutoMaterializePolicy.eager(max_materializations_per_minute=1)

    def get_freshness_policy(
        self, dbt_resource_props: Mapping[str, Any]
    ) -> Optional[FreshnessPolicy]:
        return FreshnessPolicy(maximum_lag_minutes=60)
```

And add the  missing imports
```python
from dagster import (
    AssetExecutionContext,
    FreshnessPolicy,
    AutoMaterializePolicy,
)
```

Then build the `core` job manually.

Once the core job is done, dagster should start a job to build downstream `eager` models, but it doesn't.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for the detailed screenshots. Based on them, my understanding of what's going on here:
- The `comments` asset has 25k+ partitions
- One of those partitions is present, but the rest are missing
- The `comment_daily_stats` asset is downstream of the `comments` asset, but is no auto-materialized because it's "Waiting on upstream data to be present", i.e. for those other partitions to no longer be missing

In your case, would you like `comment_daily_stats` to be materialized even though some of the upstream partitions it depends on are missing?

**Comment by sryza** [comment]
@marcilj that makes total sense. @gibsondan merged a change last week (not yet released yet) that should help with this confusion: https://github.com/dagster-io/dagster/pull/17915.
