### ISSUE TITLE
switching storage configs has potentially unpredictable/inconsistent behavior

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#1805]
If we switch the compute log manager from `LocalComputeLogManager` to `S3ComputeLogManager`, the compute log manager looks for historical runs (where logs were stored locally) on S3.

We should consider whether we need to store extra metadata about the state of the instance config for stored runs to have a better user experience.

A minimal solution might just be to audit whether or not we have good fallback error handling on a per-graphql endpoint basis.

**Comment by schrockn** [comment]
I think with a change of instance configuration all bets are off really.

**Comment by prha** [comment]
yeah, I think that's true... but maybe we'll get a lot of pushback / confusion, so wanted to jot down a placeholder issue

**Comment by fj-sanchez** [comment]
I just hit the this issue and it was driving my crazy... It would be good to at least have a warning message or similar. I think many people will likely find this issue when they are starting, as this is when you are changing configurations and running things to experiment.

**Comment by catherinewu** [comment]
Added the documentation label since we should probably warn about this in the tutorial / docs

**Comment by catherinewu** [comment]
cc @yuhan putting this on your radar

**Comment by erinkcochran87** [comment]
@prha is this issue still relevant?

**Comment by sryza** [comment]
Closing this as part of housekeeping because I don't think it's turned out to be a big deal. Feel free to reopen if you believe otherwise.
