### ISSUE TITLE
Multiple asset checks that execute in a single op

### ISSUE THREAD

**Issue by jrstats** [dagster-io/dagster#18068]
### What's the use case?

As documented in #15880

Specifically needed to create factories ([example from the docs](https://docs.dagster.io/concepts/assets/asset-checks#asset-check-factories)) with multiple checks as these cannot be done in each individual asset and where multiple checks require the same inputs.

> Multiple asset checks that execute in a single op
Sometimes, you want to define multiple checks that are executed within the same function. For example, this is useful in situations where loading the data that you want to check is time-consuming.
``` python
@multi_asset_check(
    check_specs=[
        AssetCheckSpec("orders_id_has_no_nulls", asset=orders),
        AssetCheckSpec("orders_id_is_unique", asset=orders),
    ]
)
def orders_checks():
    orders_df = pd.read_csv("orders.csv")
    num_null_order_ids = orders_df["order_id"].isna().sum()

    return [
        AssetCheckResult(
	    check_name="orders_id_has_no_nulls",
            asset_key="orders",
            success=(num_null_order_ids == 0),
            metadata={"num_null_order_ids": num_null_order_ids},
        ),
        AssetCheckResult(
            check_name="orders_id_is_unique",
            asset_key="orders",
            success=orders_df["order_id"].is_unique,
        )
    ]		
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
Thoughts on the name `@asset_multi_check`? My concern with `@multi_asset_check` is that it sounds like a check on a `@multi_asset`

**Comment by jrstats** [comment]
happy with asset_multi_check :)
