### ISSUE TITLE
Pipeline not building correctly when using inputs of composite_solids multiple times

### ISSUE THREAD

**Issue by PhilGru** [dagster-io/dagster#1808]
I want to build a composite_solid that takes inputs from two other solids. The following code runs without problems:

```python
from dagster import pipeline, lambda_solid, composite_solid

@lambda_solid
def return_one():
    return 1

@lambda_solid
def return_two():
    return 2

@lambda_solid
def add(n, m):
    return n + m

@lambda_solid
def multiply(n, m):
    return n * m

@composite_solid
def calculate(one, two):
    #added = add(one, two)
    multiplied = multiply(one, two)

@pipeline
def calculate_pipeline():
    one = return_one()
    two = return_two()
    calculate(one, two)
```

The pipeline will be built like this:

![image](https://user-images.githubusercontent.com/56165214/66217107-fd5aa500-e6c6-11e9-8a5f-d905487d2a8e.png)

However, if i want to use the inputs to the composite_solid a second time by uncommenting the `added = add(one, two)` line, the pipeline will be built like this:

![image](https://user-images.githubusercontent.com/56165214/66217293-532f4d00-e6c7-11e9-8125-d8ca1cc7db87.png)

So this seems to be a bug. I am using dagster 0.5.9.

**Comment by PhilGru** [comment]
This seems to be related: https://github.com/dagster-io/dagster/issues/1540

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D1214
