### ISSUE TITLE
[UI] Add subtle background color to the box enclosing an expanded asset group

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#18104]
### What's the use case?

Love the collapsible assets groups (honest, 10/10 job!)

That said, it is hard to reason at a glance about what assets are in what group now that the box enclosing the expanded asset group is background-less.

### Ideas of implementation

Can you please re-instate some background:

![image](https://github.com/dagster-io/dagster/assets/112868935/c1e5ca9b-918b-445c-b5f8-500dfb9f2b76)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by braunjj** [comment]
This should be improved once we roll out the new light and dark mode themes @hellendag. They both have a subtle background added.

**Comment by bengotow** [comment]
Marking this as fixed!
