### ISSUE TITLE
dagster images latest tag is wrong

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1814]
Flagging this to dig into later, but noticed this earlier today....

`dagster/dagster-py37:latest` seems to package 0.5.7 whereas the tag `dagster/dagster-py37:2019-10-05` is correctly on `0.6.0.post0`

**Comment by newturok** [comment]
Also there is no `--no-watch` option in `dagit-cli`
[https://dagster.readthedocs.io/en/0.6.0.post0/sections/deploying/dagit.html#containerized-execution-in-docker](https://dagster.readthedocs.io/en/0.6.0.post0/sections/deploying/dagit.html#containerized-execution-in-docker)
![image](https://user-images.githubusercontent.com/5757827/66264861-58021700-e815-11e9-9af3-9e3683cd670e.png)

**Comment by natekupp** [comment]
Good catch, thanks!! Will be fixed by https://dagster.phacility.com/D1229

**Comment by newturok** [comment]
Сontinuing about deploying with docker, it looks like `dagster/dagster-py37` doesn't have `cron` installed:
![image](https://user-images.githubusercontent.com/5757827/66264960-183c2f00-e817-11e9-9afc-f565256c8352.png)
![image](https://user-images.githubusercontent.com/5757827/66264974-4d488180-e817-11e9-9db6-77074c4c70aa.png)

**Comment by natekupp** [comment]
https://dagster.phacility.com/D1230 will fix the public images issue here, as well as the missing cron mentioned in https://github.com/dagster-io/dagster/issues/1812

**Comment by natekupp** [comment]
Landed these
