### ISSUE TITLE
Asset dependency paths not visible on Safari

### ISSUE THREAD

**Issue by DanteOz** [dagster-io/dagster#18143]
### Dagster version

dagster, version 1.5.9

### What's the issue?

Intra group asset dependency graphs are not visible in Safari when using the `Experimental asset graph experience`.

## Safari
<img width="664" alt="Screenshot 2023-11-19 at 10 22 26 PM" src="https://github.com/dagster-io/dagster/assets/72047001/6418a424-c6d4-4a05-9b00-10ee73435552">

## Firefox
<img width="763" alt="Screenshot 2023-11-19 at 10 23 06 PM" src="https://github.com/dagster-io/dagster/assets/72047001/5ff666be-74bf-4943-bc7c-52b3528d6824">

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by salazarm** [comment]
@braunjj

**Comment by DanteOz** [comment]
Error no longer present in Dagster 1.5.10.
