### ISSUE TITLE
`sensor` with multiple jobs only attempts to run one the jobs despite using the ignored jobs `RunRequest`

### ISSUE THREAD

**Issue by hello-world-bfree** [dagster-io/dagster#18146]
### Dagster version

1.5.9 (also did the same on 1.5.8)

### What's the issue?

Depending on an external event - matching hashes in my case - I'm attempting to either run job "a" or job "b". Both jobs materialize asset a but only job b materializes asset b. 

Using a sensor with multiple target jobs configured, I'm always submitting a `RunRequest` - one for job "a" if the hashes do not match, and one for job "b" if they do. Despite having a clear binary path, job "a" is always selected for running when using the 'Test Sensor' feature, even when all the logs and control flow show that the job "b" `RunRequest` is what was called. It's as if the provided `job_name` is overridden. The additional config is still present providing further evidence that it's using the correct `RunRequest`, it's just trying to run the wrong job.

This continues to happen even when I change the code to submit both `RunRequests` - I'll just get two instances of job "a" instead of one.

The only way I can get job "b" is if I use `job` instead of `jobs` in the `sensor` decorator. Then it'll return job "b" and it'll be chosen to run as it should. OR, if I make the name of job "b" be alphabetically before job "a", then it'll swap. It just seems to be selecting the job based on its alphabetical order.

```
@sensor(
    jobs=[
        job_a,
        job_b
    ]
)
def demo_sensor(context):
    hash_a = get_hash("a")
    hash_b = get_hash("b")

    run_requests = [
        RunRequest(
            run_key=_run_key,
            job_name="job_a",
            run_config=RunConfig(
                ops={
                    "asset_a": AssetAConfig()
                }
            ),
        )
    ]

    if hash_a == hash_b:

        run_requests = [
            RunRequest(
                job_name="job_b",
                run_config=RunConfig(
                    ops={
                        "asset_a": AssetAConfig(),
                        "asset_b": AssetBConfig(),
                    }
                ),
            )
        ]

    return SensorResult(run_requests=run_requests)
```

### What did you expect to happen?

The `RunRequest.job_name` property should tell Dagster which target job(s) to attempt to run. Depending on which job names are specified in the run requests submitted in the `SensorResult` only that subset of jobs should be ran.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by salazarm** [comment]
Hi @BFreeNashville trying to understand the root issue here. It seems that the behavior is correct when it actually runs but when trying to use the test sensor feature it reports the wrong job, correct?

**Comment by BFreeNashville** [comment]
Hey @salazarm thanks for the response! I haven't ran it outside of the `Test Sensor` feature. Even there, everything seems to be correct **_except_** for the job it attempts to run. 

It's as if the `job_name` I supply to `RunRequest` is ignored and it selects the first target job defined in the `sensor` decorator `jobs` arg by alphabetical order instead.
