### ISSUE TITLE
Green circles in Schedule Tab is one run late from Runs Tab

### ISSUE THREAD

**Issue by newturok** [dagster-io/dagster#1815]
First run is not sown in Schedule Tab overall
![image](https://user-images.githubusercontent.com/5757827/66266688-f780d300-e830-11e9-8a0a-8e6c37e1ac09.png)

After two runs only one is shown in Schedule Tab
![image](https://user-images.githubusercontent.com/5757827/66266676-d7511400-e830-11e9-89b4-44247527320e.png)

Last run is correct

**Comment by schrockn** [comment]
@newturok thank you for these high quality issues! keep 'em coming. and feel free to hop in our slack :-)

**Comment by helloworld** [comment]
Thanks for catching this! Fixed by: https://dagster.phacility.com/D1234. We'll send out a release today with this fix.
