### ISSUE TITLE
Dagster asset names and prefixes are aggressively shortened in Firefox

### ISSUE THREAD

**Issue by brennan-wall-fgp** [dagster-io/dagster#18173]
### Dagster version

dagster, version 1.5.9

### What's the issue?

In Firefox, the asset names are shortened in both the folder and list view.
### Firefox

![image](https://github.com/dagster-io/dagster/assets/143037450/edfb3dfd-0bbc-4e24-b8fc-6a830f07e527)

![image](https://github.com/dagster-io/dagster/assets/143037450/bd60c0cb-3975-4fb4-b6b9-577fb19fd376)

### What did you expect to happen?

In Chrome it doesn't shorten asset names aggressively:
### Chrome
![image](https://github.com/dagster-io/dagster/assets/143037450/90155790-fd3c-441b-b30f-704c427d0130)

### How to reproduce?

View your asset list in Firefox with an asset prefix longer than ~8 characters.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
This is fixed by #18240!
