### ISSUE TITLE
Examples: need an example with local Spark

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1819]
We should have an example that uses local Spark

**Comment by mgasner** [comment]
#966

**Comment by natekupp** [comment]
cc @sryza

**Comment by sryza** [comment]
The simple_pyspark_example that I added to test the emr_pyspark_step_launcher has a mode that uses local Spark, so I'm going to close this.  @natekupp let me know if I'm misunderstanding what this issue refers to.
