### ISSUE TITLE
Using Ray distributed computing as an Executor

### ISSUE THREAD

**Issue by aeroaks** [dagster-io/dagster#18213]
### What's the use case?

We use [Ray](https://docs.ray.io/en/latest/) in our setup to distribute computing. Having seen a [Dagster-dask](https://docs.dagster.io/deployment/guides/dask) Executor. I was wondering what and how can we support a cluster, like Ray, as an executor.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mkleinbort** [comment]
Hey, keen to see a ray executor. I came across this project https://github.com/danielgafni/dagster-ray but it looks to be in its very early stages.

Any plans or guidance to support ray executors?

**Comment by garethbrickman** [comment]
cc @danielgafni for your awareness!

**Comment by danielgafni** [comment]
Hey everyone!

I added a KubeRayCluster resource to dagster-ray. 

While it's not an Executor, it also allows executing Ray code in an auto-provisioned RayCluster. 

It works in minikube, but I would like to test it in a real cluster. Currently I don't have one. 

Please reach out to me if you want to try it out. 

Should be as easy as: 

The idea is:

1. Have KubeRay Operator installed in k8s cluster 
2. Configure the Resource according to your needs (e.g. max_nodes, pod resources) 
3. Request the Resource in an asset: 

'''python
@asset
def my_asset(ray_cluster: KubeRayCluster): 
    # write ray code here 
'''

**Comment by danielgafni** [comment]
Another update: I've added [RayJob](https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/rayjob-quick-start.html) support to [dagster-ray](https://github.com/danielgafni/dagster-ray) via [Dagster Pipes](https://docs.dagster.io/concepts/dagster-pipes).

---

In Dagster code:

```python
from dagster import AssetExecutionContext, Definitions, asset

from dagster_ray.kuberay import PipesRayJobClient


@asset
def my_asset(context: AssetExecutionContext, pipes_rayjob_client: PipesRayJobClient):
    pipes_rayjob_client.run(
        context=context,
        ray_job={
            # RayJob kubernetes manifest goes here
            # .metadata.name is not required and will be generated if not provided
            # *.container.image is not required and will be set to the current `dagster/image` tag if not provided
            # full reference: https://ray-project.github.io/kuberay/reference/api/#rayjob
            ...
        },
        extra={"foo": "bar"},
    )


definitions = Definitions(
    resources={"pipes_rayjob_client": PipesRayJobClient()}, assets=[my_asset]
)
``` 

In the job entrypoint script: 

```python
from dagster_pipes import open_dagster_pipes


with open_dagster_pipes() as pipes:
    pipes.log.info("Hello from Ray Pipes!")
    pipes.report_asset_materialization(
        metadata={"some_metric": {"raw_value": 0, "type": "int"}},
        data_version="alpha",
    )
```

A convenient way to provide `dagster-pipes` to the Ray job is with the `runtimeEnvYaml` field:

```python
import yaml

ray_job = {"spec": {"runtimeEnvYaml": yaml.safe_dump({"pip": ["dagster-pipes"]})}}
```
---

Please reach out to me if you want to try it out.

**Comment by danielgafni** [comment]
I've [added](https://github.com/danielgafni/dagster-ray/releases/tag/v0.0.4) `RayRunLauncher` and `ray_executor` to `dagster-ray`. 

I'll close this issue, feature requests can be created in https://github.com/danielgafni/dagster-ray.
