### ISSUE TITLE
D1216/ef23ea3c3aa8b89adb0c92e7bbf1fd3d9684d8e6 broke runs page

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1822]
I have a revert out.  https://dagster.phacility.com/D1248

Getting this error on the runs page.

![Screenshot 2019-10-08 20 50 52](https://user-images.githubusercontent.com/28738937/66450480-88aca100-ea0d-11e9-8143-8245a94286e9.png)

**Comment by mgasner** [comment]
Closing this in favor of #1824
