### ISSUE TITLE
Redo https://dagster.phacility.com/D1232 with scheduler fix

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1824]
Had to revert in https://dagster.phacility.com/D1249

**Comment by schrockn** [comment]
Repro:

- `dagit -p 3333` in dagster_examples
- `make` in js_modules/dagit
- navigate to schedules tag
- see:
![Screenshot 2019-10-09 13 44 36](https://user-images.githubusercontent.com/28738937/66518858-05399100-ea9b-11e9-88aa-18543e5a77a4.png)

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D1256
