### ISSUE TITLE
AutoMaterialize not working for Airbyte integration

### ISSUE THREAD

**Issue by benpankow** [dagster-io/dagster#18266]
### Discussed in https://github.com/dagster-io/dagster/discussions/18212

<div type='discussions-op-text'>

<sup>Originally posted by **jonathanneo** November 21, 2023</sup>
I am defining my airbyte_assets as follows: 

```python
airbyte_assets = load_assets_from_airbyte_instance(
    airbyte=airbyte_instance, 
    connection_to_asset_key_fn=lambda metadata, table_name: AssetKey([metadata.name, "raw", table_name]), 
    connection_to_auto_materialize_policy_fn=lambda _: AutoMaterializePolicy.lazy(),
)
```

However, the automaterialization policy is not being defined: 
![Screenshot 2023-11-22 at 1 57 40 pm](https://github.com/dagster-io/dagster/assets/16749633/22cac9ba-2a79-4be6-ba05-99483ea9fef4)</div>

**Comment by thiagoazcampos** [comment]
Facing the same issue here. I could set the Freshness Policy and other attributes, but not the Auto Materialize Policy.

**Comment by jonathanneo** [comment]
Any updates on this? @benpankow

**Comment by hellendag** [comment]
This doesn't look UI-specific.

**Comment by jonathanneo** [comment]
Hi team, just following up on this issue. Is anyone looking into this?
