### ISSUE TITLE
Make sure pipeline level events can be captured and persisted somewhere in `compute_logs`

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#1830]
This is required for a consolidated compute log cli tool that tails logs.

**Comment by mgasner** [comment]
@prha are we good to close this?

**Comment by prha** [comment]
This is still open, but not a hi-pri issue.  Will probably need to bump for 0.7.0 to keep track of remote execution logs though.

**Comment by alangenfeld** [comment]
closing since this making the pipeline driving possible to do from a host process changes things so much
