### ISSUE TITLE
support for views

### ISSUE THREAD

**Issue by geoHeil** [dagster-io/dagster#18318]
### What's the use case?

Enhance the DBT integration to better support views

Currently, dagster is only aware of tables and does not know that a view does not require to be re-materialized if the underlying table is updated.

However, when setting up a job or changing the definition of the view the view needs to be re-materialized

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Duplicate of https://github.com/dagster-io/dagster/issues/6474.
