### ISSUE TITLE
Historical runs display "Process (PID undefined)" in log viewer

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1832]
This occurs when you view a historical run. The PID is no longer displayed, which is fine. But it should indicate that the process no longer exists.

See at the top of this UI:

![Screenshot 2019-10-11 16 33 41](https://user-images.githubusercontent.com/28738937/66690479-10302500-ec45-11e9-81ed-2c89b14f2dab.png)

**Comment by xinbinhuang** [comment]
I wanna take up on this. 
To make sure I understand correctly: we want the UI to display something more informative rather than `undefined` correct?

**Comment by alangenfeld** [comment]
sorry @xinbinhuang  - this task isn't relevant anymore since the UI has changed drastically since
