### ISSUE TITLE
Invocations not listed for composite solid definitions when clicked into an instance

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1836]
So, when one has a composite solid selected from a parent solid, the invocations are listed fine:

![Screenshot 2019-10-12 12 45 05](https://user-images.githubusercontent.com/28738937/66706926-280fb380-ecee-11e9-835e-d9d7c9f71c1f.png)

But click on expand and they are nowhere to be found

![Screenshot 2019-10-12 12 45 13](https://user-images.githubusercontent.com/28738937/66706928-2a720d80-ecee-11e9-8e76-72a198fa023a.png)

**Comment by alangenfeld** [comment]
I took a look at this and its kinda tricky due to how we handle an expanded composite using `""` in the `path`. @bengotow leaving this one for you.

**Comment by bengotow** [comment]
Ahh yeah this one was complicated a bit by some odd `prop` choices we made early on - fixed this up in https://dagster.phacility.com/D1510!

**Comment by bengotow** [comment]
Resolved by D1510
