### ISSUE TITLE
Can sensor submitted job not appear as ad_hoc materializations

### ISSUE THREAD

**Issue by salazarm** [dagster-io/dagster#18377]
### Discussed in https://github.com/dagster-io/dagster/discussions/18376

<div type='discussions-op-text'>

<sup>Originally posted by **dagsir[bot]** November 29, 2023</sup>
is there a way to make sensor submitted jobs *NOT* appear as ad_hoc materializations

---

*The question was originally asked in [Dagster Slack](https://dagster.slack.com/archives/C01U954MEER/p1701280731200739?thread_ts=1701280731.200739&cid=C01U954MEER).*</div>

**Comment by hellendag** [comment]
This should hopefully be resolved in the near future with our new timeline UI.
