### ISSUE TITLE
`pip install -e .` inadequate for examples

### ISSUE THREAD

**Issue by zkurtz** [dagster-io/dagster#1837]
Working through the [airline example](https://dagster.readthedocs.io/en/latest/sections/learn/airline_demo.html) starting from a fresh virtual environment, `dagit` fails to run due to the absence of several dependencies which are all listed in the [setup.py](https://github.com/dagster-io/dagster/blob/master/examples/setup.py) under `extras_require`. I have not tested it but [this answer](https://stackoverflow.com/a/30239714/2232265) suggests that replacing `pip install -e .` with something like `pip install -e .[extra]` might work for most users.

**Comment by alangenfeld** [comment]
Good catch, the documentation should definitely refer to doing a `pip install -e .[full]`. Will send out a diff soon, thanks!

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D1280
