### ISSUE TITLE
[Documentation Feedback] Problem on /integrations/airflow?_gl=1*1tesl5x*_ga*Mzg5Njg1NDE3LjE3MDEyNjg2NTg.*_ga_84VRQZG7TV*MTcwMTY4NjE2Mi4yLjEuMTcwMTY4NjcxMC41NC4wLjA.*_gcl_au*NjA3MDM1NTg0LjE3MDE2ODQxOTg. page

### ISSUE THREAD

**Issue by pricemg** [dagster-io/dagster#18464]
the link to `partitioning` in this line is broken

https://docs.dagster.io/integrations/airflow?_gl=1*1tesl5x*_ga*Mzg5Njg1NDE3LjE3MDEyNjg2NTg.*_ga_84VRQZG7TV*MTcwMTY4NjE2Mi4yLjEuMTcwMTY4NjcxMC41NC4wLjA.*_gcl_au*NjA3MDM1NTg0LjE3MDE2ODQxOTg.#:~:text=Datasets,like%20partitioning.

Datasets | [Software-defined Assets (SDAs)](https://docs.dagster.io/concepts/assets/software-defined-assets) | SDAs are more powerful and mature than datasets and include support for things like [partitioning](https://docs.dagster.io/concepts/partitions-schedules-sensors).
-- | -- | --

**Comment by erinkcochran87** [comment]
Hey @pricemg - thanks for reporting this! Just waiting for tests to run on the PR that fixes this, and then I'll merge it in.
