### ISSUE TITLE
Dagster cloud cannot launch Databricks compute resources

### ISSUE THREAD

**Issue by ayephillip** [dagster-io/dagster#18471]
### Dagster version

1.4.3 and 1.5.10

### What's the issue?

Dagster cloud cannot spin up a databricks compute resource, this started Friday Dec 1. This does not impact local dev using a databricks compute resource and our code / databricks cluster haven't changed

`RESOURCE_INIT_START ` doesn't trigger compute to spin up (I can also see this on the databricks' compute tab that the cluster doesn't attempt to spin up) and instead I now get:

```
dagster._core.errors.DagsterSubprocessError: During multiprocess execution errors occurred in child processes:
In process 16: dagster._core.errors.DagsterResourceFunctionError: Error executing resource_fn on ResourceDefinition pyspark
```

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by phoebe-dt** [comment]
This has been an issue for almost a week now, hope dagster responds soon
