### ISSUE TITLE
In backfills and auto-materialize, queue runs in order of partitions

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#18563]
### What we've heard
- https://dagsterlabs.slack.com/archives/C0417S941U0/p1701965695650459
- https://dagsterlabs.slack.com/archives/C05HE0RG8SU/p1701390768905049
  - I'm ok with parallel instantiations, but if the system is going to instantiate N parallel runs, it seems preferable to start with the prefix of the data if possible (prefix here defined to be by date)

**Comment by littleK0i** [comment]
Yes, that would be fantastic!

**Comment by ignaski** [comment]
@sryza any plans to continue on this?
