### ISSUE TITLE
Docs introducing the GraphQL API

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1856]

**Comment by mgasner** [comment]
https://github.com/2fd/graphdoc

**Comment by mgasner** [comment]
https://www.npmjs.com/package/graphql-docs

**Comment by mgasner** [comment]
consider against a live endpoint: https://pypi.org/project/sphinx-graphiql/

**Comment by helloworld** [comment]
Preliminary docs here: https://docs.dagster.io/overview/graphql-api#using-the-graphql-playground
