### ISSUE TITLE
persist representation of a pipeline to a file using CLI command

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#1860]
If users are encountering bugs running their pipelines, it would be useful to point them to a CLI command that would generate a data representation of their pipeline that they could then send over to use to help with debugging.  

We could stub out the compute and just generate the shape of their pipeline.

**Comment by natekupp** [comment]
@helloworld this exists now right?

**Comment by schrockn** [comment]
So we persist snapshost now but we don't have an easy way to report it. Going to punt this to 0.9.0 as part of broarder instance management/ops support workstream

**Comment by alangenfeld** [comment]
`dagster debug export` + "download debug file"
