### ISSUE TITLE
Doc : build_input_context : asset_partition_key_range type hint should be Optional[PartitionKeyRange] not Optional[str]

### ISSUE THREAD

**Issue by ShootingStarD** [dagster-io/dagster#18624]
### What's the issue or suggestion?

The documentation in the website for build_input_context() says that the asset_partition_key_range attribute is Optional[str] while in the code of the last version, it is Optional[PartitionKeyRange]
It should be updated I suppose.
Here is the link of the website page : https://docs.dagster.io/_apidocs/io-managers#dagster.build_input_context

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @ShootingStarD. Here's a PR to fix: https://github.com/dagster-io/dagster/pull/18636.

**Comment by ShootingStarD** [comment]
Hi @sryza I just checked the dagster api doc and it is not yet updated with the new docstring 

![Picture From API doc](https://github.com/dagster-io/dagster/assets/55139877/5c178c92-52b2-4e2a-9152-e63b49861859)
![The Source code](https://github.com/dagster-io/dagster/assets/55139877/15abec14-5fa3-44cf-b983-e59baa27b8ee)

**Comment by sryza** [comment]
@yuhan this apidocs change [made it into last week's release](https://www.notion.so/dagster/1-5-13-Changelog-7c29bda472bc40aaaa044a8bc5d35e8d?pvs=4#a1bd41c252c146c2bfee362c5144580e), but doesn't seem to be reflected in the docs: https://docs.dagster.io/_apidocs/io-managers#dagster.build_input_context.

Do you know if I missed a step here?

**Comment by sryza** [comment]
@yuhan this apidocs change [made it into last week's release](https://www.notion.so/dagster/1-5-13-Changelog-7c29bda472bc40aaaa044a8bc5d35e8d?pvs=4#a1bd41c252c146c2bfee362c5144580e), but doesn't seem to be reflected in the docs: https://docs.dagster.io/_apidocs/io-managers#dagster.build_input_context.

Do you know if I missed a step here?

**Comment by ShootingStarD** [comment]
seems to still be missing, should we remove the closed tag of the issue?

**Comment by garethbrickman** [comment]
@ShootingStarD I am seeing `Optional[PartitionKeyRange]` [in the docs now](https://docs.dagster.io/_apidocs/io-managers#dagster.build_input_context)
![Screenshot 2024-02-16 at 13 25 02](https://github.com/dagster-io/dagster/assets/50636644/5da51202-3b04-40cf-a03b-2105b31bd372)

**Comment by ShootingStarD** [comment]
@garethbrickman Indeed, it is displayed properly now, sorry I might have looked too fast
