### ISSUE TITLE
Display longer external asset names in Asset Groups

### ISSUE THREAD

**Issue by maxcorbeau** [dagster-io/dagster#18622]
## Current situation
When in **Asset Group lineage**,  **non-group assets** (i.e. assets which don't belong to group) have their **name truncated to 9 characters**, making the **lineage graph harder to understand** as one needs to hover non-group assets to see their full name, in below graph `trial_xps_to_exclude` is truncated to `trial_xps...`.

![image](https://github.com/dagster-io/dagster/assets/24207660/7f5176c5-3c3d-466d-87d9-350564054268)

## Requested change
Allow displaying longer non-group asset names

### Ideas of implementation

- Make the **display limit** a **configurable option** inside `dagster.yaml`
- Let Dagster users customize as per their needs (e.g. maybe for 1 user the cutoff should be 15, another 20...)
- That way we don't go into endless debates about UI limits

### Additional information

I see various related UI issues such as ones below. **Since UI is something more personal/subjective, I think a customizable approach via `dagaster.yaml` would be more sustainable than making arbitrary decisions for the Dagster community as a whole:
 - https://github.com/dagster-io/dagster/issues/14182
 - https://github.com/dagster-io/dagster/issues/13670

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey folks, just a heads up that we've doubled the number of characters shown on these external labels. Thanks for filing this!
