### ISSUE TITLE
Investigate reported issue in medium post

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1863]
![Screenshot 2019-10-23 06 30 19](https://user-images.githubusercontent.com/28738937/67397853-a9710c80-f55e-11e9-84ce-ed210f9a3b26.png)

**Comment by helloworld** [comment]
Landed checks for this in this diff: https://dagster.phacility.com/D1300

**Comment by schrockn** [comment]
great!

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
