### ISSUE TITLE
Explicitly document destructuring for multiple outputs in @pipeline

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1864]

**Comment by sryza** [comment]
Does this mean that https://github.com/dagster-io/dagster/issues/1778 is done?  Or this would be in case we do it?

**Comment by catherinewu** [comment]
given this discussion about outputs and the code sample `hot_cereals, cold_cereals = split_cereals(read_csv())` in the [docs](https://docs.dagster.io/tutorial/basics_solids#multiple-and-conditional-outputs), can we close this? or were you thinking of adding more explanation / are there are destructuring methods to be discussed?

**Comment by sryza** [comment]
IMO it would be worth adding an example for this.  I recently was trying to figure out how to do this, and didn't think to look in the tutorial (ended up giving up)
