### ISSUE TITLE
Can't send Slack Alerts to Groups via Dagster

### ISSUE THREAD

**Issue by WorksWellWithOthers** [dagster-io/dagster#18643]
### Dagster version

Dagster 1.3.12

### What's the issue?

I can alert individuals with Dagster-slack but I'm unable to alert groups.
For example,
I can set up an alert to message @JohnSmith but I can't send messages to @group-name
Is there a different function call to try and send a message to a group vs an individual via Slack from Dagster?

### What did you expect to happen?

I can send alerts to Slack groups.
EX: @group-name

### How to reproduce?

Attempt to send a message to a group in Slack via Dagster.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @WorksWellWithOthers - can you share a code snippet of what you're trying to do?

**Comment by WorksWellWithOthers** [comment]
This works:
```
import os

from dagster import EnvVar, job, op
from dagster_slack import SlackResource


@op
def slack_op(slack: SlackResource):
    slack.get_client().chat_postMessage(channel='#noise', text=':wave: **@sryza** hey there!')

@job
def slack_job():
    slack_op()

defs = Definitions(
    jobs=[slack_job],
    resources={
        "slack": SlackResource(token=EnvVar("MY_SLACK_TOKEN")),
    },
)
```

This does not:
```
import os

from dagster import EnvVar, job, op
from dagster_slack import SlackResource


@op
def slack_op(slack: SlackResource):
    slack.get_client().chat_postMessage(channel='#noise', text=':wave: `@group-with-sryza-and-me` hey there!')

@job
def slack_job():
    slack_op()

defs = Definitions(
    jobs=[slack_job],
    resources={
        "slack": SlackResource(token=EnvVar("MY_SLACK_TOKEN")),
    },
)
```
