### ISSUE TITLE
Extend autoaliasing

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1866]
would be nice to be able to write:
```
sort_hot_cereals = sort_cereals_by_calories
```
instead of:
```
sort_hot_cereals = sort_cereals_by_calories.alias('sort_hot_cereals')
```

**Comment by xinbinhuang** [comment]
Do you have a recommended path for this? 

I poked around a bit, but the only way I can think of to retrieve `sort_hot_cereals` is by calling `locals()` to replace the `CallableSolidNode.given_alias` automatically before calling `sort_hot_cereals()`.  I can not quite think of a possible way to do it.

**Comment by sryza** [comment]
Going to close this as stale
