### ISSUE TITLE
Global search returns deleted assets

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#18669]
**What's happening:**
- User has 3 assets, materializes all three (`source_a/my_asset`, `source_b/my_asset`, `source_c/my_asset`
- User then removes the definition for 2 of those assets
- User does a search for "my_asset"
- All three assets appear in search results even though two were deleted

I _think_ the issue here is that we're returning all assets with materializations even if the definition was removed.

User report:
<img width="352" alt="image" src="https://github.com/dagster-io/dagster/assets/2798333/688c1cc7-846a-4041-a02d-9cf9519eaa66">

**Comment by hellendag** [comment]
Let's see about removing non-SDAs from global search.

**Comment by lcendoya** [comment]
@hellendag how is this solved? I am using version 1.11.2 and I experience the issue. How can I have the asset removed from the UI?

**Comment by salazarm** [comment]
@lcendoya Hey I think it is a regression due to some recent performance changes. I'll file an issue to fix it.

**Comment by salazarm** [comment]
https://github.com/dagster-io/dagster/pull/31399
