### ISSUE TITLE
Add an autoaliasing example

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1867]

**Comment by catherinewu** [comment]
adding some context: dagster/python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_autoalias.py

`def test_pipeline_autoalias():
    @pipeline
    def autopipe():
        echo(echo(echo(hello())))

    result = execute_pipeline(autopipe)
    assert result.success == True
    assert result.result_for_handle("echo_3").output_value() == "hello"
    assert result.result_for_handle("echo_2").output_value() == "hello"
    assert result.result_for_handle("echo").output_value() == "hello"
    assert result.result_for_handle("hello").output_value() == "hello"
`

**Comment by yuhan** [comment]
http://localhost:3001/concepts/solids-pipelines/pipelines#solid-aliases
