### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by psmoros** [dagster-io/dagster#18690]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@dmandefy) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by jmsanders** [comment]
Thanks for the suggestion - I think our https://dagster.io/security page serves a sufficiently similar purpose and will have the information you're looking for. We'll look into adding a link to that page in the git repo as well.
