### ISSUE TITLE
master tests broken

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1870]
Azure pipelines. python 35

https://github.com/dagster-io/dagster/runs/269903300

**Comment by schrockn** [comment]
https://dev.azure.com/elementl/dagster/_build/results?buildId=5267&view=logs&jobId=57dfcc29-cc66-52d6-4ba8-9c2c5ee0c676

**Comment by schrockn** [comment]
might blame to me but doesn't seem to be related

**Comment by alangenfeld** [comment]
D1326
