### ISSUE TITLE
"DagsterInvariantViolationError: Provided resource is a generator...", but it is not...

### ISSUE THREAD

**Issue by LPauzies** [dagster-io/dagster#18757]
### Dagster version

1.4.3

### What's the issue?

I am writing some tests to cover some dagster assets that are using a resource to connect to an instance of a SGBD, and for the first time I'm getting this error :

```
self = <dagster._core.execution.context.invocation.UnboundOpExecutionContext object at 0x7f4fff672d90>

    @property
    def resources(self) -> Resources:
        if self._resources_contain_cm and not self._cm_scope_entered:
>           raise DagsterInvariantViolationError(
                "At least one provided resource is a generator, but attempting to access "
                "resources outside of context manager scope. You can use the following syntax to "
                "open a context manager: `with build_solid_context(...) as context:`"
            )
E           dagster._core.errors.DagsterInvariantViolationError: At least one provided resource is a generator, but attempting to access resources outside of context manager scope. You can use the following syntax to open a context manager: `with build_solid_context(...) as context:`
```

Here is the code of my test, pretty simple :

```Python
@pytest.fixture(scope="module")
def ch_resource():
    # ClickhouseResource inherit from ConfigurableResource
    return ClickhouseResource(dsn="MY-DSN")

def test_query_in_asset(ch_resource):
    with build_asset_context(
        resources={"clickhouse": ch_resource},
    ) as context:
        result = asset(context=context)
        # Assert stuff on 'result'
```

Here is the code of my asset :

```Python
@asset(
    key_prefix=["key"],
    name="asset",
    description="description",
    compute_kind="CH",
    group_name="asset_group",
    io_manager_key="my_io_manager",
)
def asset(
    context: AssetExecutionContext,
    clickhouse: ClickhouseResource,
) -> List[str]:
    dataframe = clickhouse.client.query(
        """
        select
            toString(info) as info_id
        from
            db.table;
        """.strip()
    )
    info_ids = list(dataframe["info_id"])
    context.log.info(f"info_ids: {info_ids}")
    return info_ids
```

### What did you expect to happen?

I'm expecting to push a custom resource designed for testing to my context, and pass this context into my asset (as the doc say) to perform a Clickhouse query against my testing tools.

I should have a result inside `result` variable.

### How to reproduce?

Install dagster==1.4.3

Create a file with an asset that query something external from a given custom resource that inherit from ConfigurableResource.

Write the associated test injecting a resource with the same structure but not the same configuration and execute it through pytest

### Deployment type

Local

### Deployment details

I'm launching my dagster in local using : `dagster dev`

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
Hey @LPauzies  The error message indicates that the resource is a generator (yielded from a function) and that you haven't done a `with build_asset_context`. But you have set your code up that way so I think there's something else going on 

I think i'm going to need a bit more information from you. Can you share the full stack trace? Additionally, I put this small replication case together but was unable to reproduce the error. Can you try running this code and see if it works for you? 

```python
    class MyResource(ConfigurableResource):
        some_config: str

        def get_some_config(self):
            return self.some_config

    @asset
    def my_asset(context, my_resource: MyResource):
        context.log.info(my_resource.get_some_config())

    with build_asset_context(resources={"my_resource": MyResource(some_config="foo")}) as context:
        my_asset(context)
```

**Comment by LPauzies** [comment]
For some reason, it worked by bumping dagster to 1.5+
