### ISSUE TITLE
pendulum 3.0.0 not handled in dagster._seven.compat.pendulum

### ISSUE THREAD

**Issue by kopok2** [dagster-io/dagster#18781]
### Dagster version

1.5.13

### What's the issue?

With a release of the newest `pendulum` 3.0.0 on 2023-12-16 the Pendulum module versions handling in:
https://github.com/dagster-io/dagster/blob/bff47ea791581beb39c939f7b4444452fbd9f9da/python_modules/dagster/dagster/_seven/compat/pendulum.py#L50

is no longer working properly. Dagster module expects all non-2.x.x `pendulum `versions to expose `pendulum.Pendulum` interface which no longer is a case.

Suggested solutions could include:
1) Replacing `_IS_PENDULUM_2` with `_IS_PENDULUM_1` and negating relevant boolean expressions
2) Expanding the `_IS_PENDULUM_2` to cover 3.x.x versions -> `_IS_PENDULUM_2_OR_3`
3) Enforcing `pendulum` versions to be strictly lesser than `3.x.x`

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi, dagster currently is pinned to pendulum<3 : https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/setup.py#L89 - so I believe we are already doing Option 3 in your list.

**Comment by kopok2** [comment]
You're right!
