### ISSUE TITLE
Make cancel button visually less aggressive

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1879]
Don't know about everyone else, but it is really the thing that my eyes go to when loading the screen, which is not what we want IMO. May just be a fiddling-with-the-color-palette thing.

**Comment by schrockn** [comment]
<img width="851" alt="Screenshot 2019-10-29 11 25 39" src="https://user-images.githubusercontent.com/28738937/67797466-ff522280-fa3e-11e9-9631-b3c0c23b20f1.png">

**Comment by helloworld** [comment]
Also, maybe `Cancel` should be `Stop` or `Stop Execution`

**Comment by bengotow** [comment]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/1037212/69821384-16fd0200-11c9-11ea-8278-dbfb8e8549c3.png">


<img width="465" alt="image" src="https://user-images.githubusercontent.com/1037212/69821390-1b291f80-11c9-11ea-9fd2-ad5f8184c33e.png">


It looks like this has been nicely addressed on `master`. Going to close this as housekeeping but let me know if other changes should be made here!
