### ISSUE TITLE
Schedules UI grinds to a halt when thousands of runs have been scheduled

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1880]
I ran into this during a demo. I run `dagster schedule wipe` to resolve. I had had an minutely job running for days so I would esimate on the order of 5000-25000 runs attached to a single schedule. It was effectively infinitely loading.

**Comment by helloworld** [comment]
We have this diff https://dagster.phacility.com/D1276#inline-6690 but it's blocked a larger `RunStorage` refactor that consolidates all these query methods that have accumulated on `RunStorage`.  It might be worth to get this out before the refactor so that the schedules UI can load quickly.

**Comment by helloworld** [comment]
Fixed by https://dagster.phacility.com/D1276
