### ISSUE TITLE
[BUG] - Dagit input type preview incorrect.

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#1885]
I have the following solids:

```
@solid
def unzip_csv_files(_, file_names: List[str], source_dir: str, target_dir: str):
    for file_name in file_names:
        _unzip_csv(os.path.join(source_dir, file_name), target_dir)
```

However, dagit is showing me the following. Notice that the preview pane is saying `value: String` when the value really should be List[str] and just continues to stay red.

![Screen Shot 2019-10-30 at 4 33 00 PM](https://user-images.githubusercontent.com/4219809/67906794-f6db1400-fb32-11e9-9dda-bedab4bbc55c.png)

**Comment by alangenfeld** [comment]
The each string in the list is a `Selector` based input hydration - what the system is asking for in an admittedly subtle way is:
```
file_names:
  - value: hello
  - value: my
  - value: name
```

**Comment by asingh16** [comment]
ah that makes sense! It was also resolved, gonna close for posterity! Thanks Alex!
