### ISSUE TITLE
We should have a "bells and whistles" complete version of the tutorial pipeline

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1891]
Not sure what the right version of the pipeline that should be in there but something should be there.

**Comment by mgasner** [comment]
@catherinewu had a clever idea about how to put the behemoth copy-paste final pipeline under test to control drift, by checking bytecode compatibility with the source files

**Comment by mgasner** [comment]
This would exercise all of the features demonstrated in the tutorial

**Comment by sryza** [comment]
We now offer the hacker news demo jobs, which is where I believe we want to point people who are looking for a bells-and-whistles understanding of Dagster.

I think it's possible to imagine combining these two somehow, but I'm going to close this for now, and we can add a new issue if we want to track that.
