### ISSUE TITLE
Windows CI/CD

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1896]
Looks like https://dagster.phacility.com/D1371 broken windows master tests

**Comment by mgasner** [comment]
#1733 #1420

**Comment by mgasner** [comment]
@prha are we good to close this and the two associated issues?

**Comment by prha** [comment]
This issue can be closed (the underlying breakage), but I didn't merge https://dagster.phacility.com/D1423 because I hadn't figured out the perf piece yet.  I think that's the blocker for #1733 ...
