### ISSUE TITLE
Show asset docstring on the asset page

### ISSUE THREAD

**Issue by EtienneT** [dagster-io/dagster#18964]
### What's the use case?

It would be nice to be able to add documentation to a software defined asset and display it inside the asset page.  Right now it displays in the asset list, but it is truncated.  It would be nice to be able to add links or even markdown to show in a documentation tab of the asset.  You could define documentation for your fellow team members directly in the code and it would show directly in the dagster UI too for quick reference.

### Ideas of implementation

Same thing as the asset list showing the docstring, but inside a tab in the asset showing everything as markdown.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @EtienneT  - the description shows up near the top of the "Definition" tab of the Asset Details page. Is that what you're looking for?

**Comment by EtienneT** [comment]
@sryza exactly what I was looking for thanks!
