### ISSUE TITLE
Scheduler documentation incomplete in 0.6.3

### ISSUE THREAD

**Issue by mikeyk** [dagster-io/dagster#1897]
While working on implementing something with dagster & cron, I noticed the 0.6.3 docs are missing the content below the `@schedules` decorator. It was ok as of 0.6.1 (https://dagster.readthedocs.io/en/0.6.1/sections/learn/tutorial/scheduler.html)

I also couldn't find the `ScheduleDefinition` docs in the API section.

**Comment by mikeyk** [comment]
(I'm happy to take a stab at both of these)

**Comment by helloworld** [comment]
Thanks for catching this! Fixed the line numbers and added both the `@schedules` decorator and `ScheduleDefinition` to the API section. 

The diff is here: https://dagster.phacility.com/D1395, and we'll ship this out next Tuesday with our release.
