### ISSUE TITLE
Fix postgres docker container flakiness

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1898]
A disturbingly high portion of our jobs fail on some postgres container failure. 

(I had a repro but the build was retried so not seeing it anymore)

**Comment by alangenfeld** [comment]
example failure: https://dagster.phacility.com/P25
history for agent that got in to bad state: https://buildkite.com/organizations/dagster/agents/31a1ad5f-9a86-4178-aabf-acbd75e91014/jobs

It seems like the docker-compose invocations we have should be cleaning up / removing these containers but they're not.

**Comment by alangenfeld** [comment]
https://buildkite.com/organizations/dagster/agents/fafd6269-79f7-47d6-b554-77ba8bae8019/jobs

**Comment by schrockn** [comment]
From buildkite support:

Hi Nick,

Thanks for reaching out.

Sorry to hear you are having trouble with the docker resources hanging around. We do sometimes see issues with docker resources not being cleaned up, normally with any docker builds we recommend that you run clean up task using docker system prune.

Let me know how you go.

Cheers,

Jason

**Comment by mgasner** [comment]
I think we are no longer seeing these?

**Comment by alangenfeld** [comment]
ya this is resolved with the pre-exit hook
