### ISSUE TITLE
Failed to execute 'importScripts' on 'WorkerGlobalScope', Fetch through target failed: Unsupported URL scheme

### ISSUE THREAD

**Issue by CamronBorealis** [dagster-io/dagster#18986]
### Dagster version

dagster, version 1.5.13

### What's the issue?

Graph will not load after reaching 30 or so items, error from console is:

`Could not load content for webpack://_N_E/webpack/after-startup (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)`

### What did you expect to happen?

Graph would load accurately

### How to reproduce?

- Add dagster-dbt to project
- Add dbt-core=1.4.9 to project
- Create 50 models
- Run `dagster dev`
- Navigate to asset view for that group

### Deployment type

Local

### Deployment details

- Running locally
- dagster-dbt
- dbt-core=1.4.9
- dbt-sqlserver=latest
- Chrome 120

### Additional information

Disabling or enabling the experimental UI and/or websockets does not affect this

I did find this, which would align with the issue I'm having: https://stackoverflow.com/questions/24349175/uncaught-networkerror-failed-to-execute-importscripts-on-workerglobalscope

Thank you for a great product!!

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Hi @CamronBorealis, does this reproduce reliably for you? If you try this in 0.5.12 or previous versions, does anything similar occur?

**Comment by CamronBorealis** [comment]
@hellendag Yes, this is consistent. Once I pass a threshold of assets, the graph stops working every time. Downgrading to 1.5.12 does not solve it.

I also noticed I am receiving other errors as well:

`Refused to execute script from 'http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js' because its MIME type ('text/plain') is not executable.`

WebSockets also do not work with the message:

`WebSocket is closed before the connection is established.`
