### ISSUE TITLE
Investigate pex and shiv

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1899]
The idea here is that for some environments where we can't easily containerize, or perhaps as a standard for container build, we would use a zipapp instead.

https://github.com/pantsbuild/pex/
https://github.com/linkedin/shiv

**Comment by mgasner** [comment]
https://github.com/indygreg/PyOxidizer

**Comment by mgasner** [comment]
https://github.com/facebookincubator/xar/

**Comment by alangenfeld** [comment]
going to close this issue - we can come at these technologies from a more specific problem statement
