### ISSUE TITLE
Support DSL in solid subset selection for execution

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1901]
Right now the solid viewer supports wildcards. So should solid subset selection for execution. (This should also be supported in the python API and command line, but we can track that in a different task)

**Comment by mgasner** [comment]
#1552

**Comment by mgasner** [comment]
this will be done for the python api in D3112 and D3113

**Comment by mgasner** [comment]
closing in favor of #1552 -- we will track the remaining work there
