### ISSUE TITLE
test harness for kubernetized airflow dags

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1904]

**Comment by mgasner** [comment]
@natekupp are we currently testing a dag that actually uses the k8s pod operator?

**Comment by natekupp** [comment]
Yes, we have both a test DAG and a test fixture for the k8s pod operator now! 🎉

**Comment by natekupp** [comment]
https://github.com/dagster-io/dagster/blob/master/python_modules/dagster-airflow/dagster_airflow/test_fixtures.py#L128-L160

**Comment by natekupp** [comment]
and

https://github.com/dagster-io/dagster/blob/master/python_modules/dagster-airflow/dagster_airflow_tests/test_factory.py#L147-L161
