### ISSUE TITLE
speculative: dagstermill for Excel spreadsheets

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1909]
not clear how to do this on os x / unix -- perhaps openoffice only on those platforms with no interop -- but might be as simple as building on top of xlwings and limiting to osx/windows:

```Workaround: in essence, xlwings is just a smart wrapper around pywin32 on Windows and appscript on Mac. You can access the underlying objects by calling the api property```

https://docs.xlwings.org/en/stable/quickstart.html

but nb that none of our executors are os/sys-aware yet

possible approaches include win32 apis (on nt):
https://stackoverflow.com/questions/37560346/is-there-any-way-i-can-call-excel-vba-function-through-python
https://stackoverflow.com/questions/19616205/running-an-excel-macro-via-python

perhaps just substituting the cell:
https://openpyxl.readthedocs.io/en/stable/

perhaps launching windows containers (requires a windows docker server)

inside the spreadsheet, we could write a dagstermill-alike in VBA, or perhaps in pyxll (https://www.pyxll.com/) or with xlwings calling RunPython

https://www.pyxll.com/blog/tools-for-working-with-excel-and-python/

**Comment by sryza** [comment]
Closing this as part of housekeeping because it hasn't gotten much traction. Feel free to reopen if you think we should focus on this.
