### ISSUE TITLE
When you change config schema runs page does not load

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1910]
It appears that we are compiling the execute plan when loading the runs page. If you have changed config schema historically this breaks everything.

<img width="1283" alt="Screenshot 2019-11-14 16 33 22" src="https://user-images.githubusercontent.com/28738937/68907426-9932f400-06fc-11ea-8c7c-7d2c5542d22a.png">

**Comment by mgasner** [comment]
https://github.com/dagster-io/dagster/issues/1749

**Comment by bengotow** [comment]
Hmm this may be an issue with the GraphQL interface not necessarily with Dagit. For each run in the runs history view, we load the following:

```
      fragment RunTableRunFragment on PipelineRun {
        runId
        status
        stepKeysToExecute
        canCancel
        mode
        environmentConfigYaml
        pipeline {
          ... on PipelineReference {
            name
          }
          ... on Pipeline {
            solids {
              name
            }
          }
        }
        stats {
          stepsSucceeded
          stepsFailed
          startTime
          endTime
          expectations
          materializations
        }
        tags {
          key
          value
        }
      }

```

My guess is that asking for `environmentConfigYaml` is causing this? Also worth noting that we /could/ hotfix this by not requesting that until you click to Re-execute or "View Configuration". It is only used in conjunction with actions.

**Comment by mgasner** [comment]
see also #2249

**Comment by mgasner** [comment]
@schrockn I assume this is a dead letter with the snapshotting work -- if so can you close it?
