### ISSUE TITLE
First-time user modal is hard to read in dark mode

### ISSUE THREAD

**Issue by tacastillo** [dagster-io/dagster#19166]
### Dagster version

1.5.14

### What's the issue?

With dark mode, that modal comes up when you go to the UI for the first time is hard to read because some of the text is white and matches the modal background.

![image](https://github.com/dagster-io/dagster/assets/10715711/2b47aec5-c92d-450b-8a85-49ff7705ca6a)

### What did you expect to happen?

I can read it in dark mode.

### How to reproduce?

Does a cookie track when to present the modal? I can't recall reproducing this by deleting $DAGSTER_HOME, but I might be wrong.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Thanks for reporting this! We've fixed this in https://github.com/dagster-io/dagster/pull/19086 and it should be out in the next release.
