### ISSUE TITLE
Dagster Cloud Agent: FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/memory/memory.limit_in_bytes'

### ISSUE THREAD

**Issue by cbini** [dagster-io/dagster#19195]
### Dagster version

1.6.0

### What's the issue?

After upgrading the agent, we started getting this error:
```
 Traceback (most recent call last):
  File "/dagster/dagster/_utils/container.py", line 116, in _retrieve_containerized_memory_limit
    with open(memory_limit_path()) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/memory/memory.limit_in_bytes' 
```

There are a few similar errors getting logged as well, but `_retrieve_containerized_memory_limit()` doesn't appear to be catching it properly:
- Failed to retrieve CPU time from cgroup: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpuacct/cpuacct.usage'
- Failed to retrieve memory usage from cgroup: [Errno 2] No such file or directory: '/sys/fs/cgroup/memory/memory.usage_in_bytes'
- Failed to retrieve memory limit from cgroup

### What did you expect to happen?

At the very least, it should fail without raising the exception if this isn't a critical process.

### Deployment type

Dagster Cloud

### Deployment details

Hybrid agent using GKE, installed via Helm

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
Hey there - `_retrieve_containerized_memory_limit` logs an exception when the error happens, but does correctly pass through. Definitely understandable that the exception is kind of a spooky log, but in this case it should be harmless. Going forward we'll be disabling this metrics retrieval by default so that this log spew doesn't affect you.

**Comment by cbini** [comment]
confirmed it goes away after upgrading to 1.6.1
