### ISSUE TITLE
Figure out dagster's credentials story

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#1919]
User Story: As a user of dagster, I would like to have an opinionated and documented approach for managing my credentials for my resources and solids.

Context: I needed to make an API call and did not want to store my keys in an input preset for dagit to use. As a result, I originally went the route of having a config for my solid which stored the environment variable. However, because our configs has no concept of "hydration" it meant that I needed to shoehorn my credentials as an input to my solid. This is weird because credentials are globally known to be configuration and not data flowing through a system. Finally, I went and just built a SolidCredentialsVault resource (https://dagster.phacility.com/D1452). 

However, it seems odd that I am throwing credentials I need for solids into a global credentials vault resource and at the same time am using the resource schema configuration system to have each resource manage its own cred story. Is there a better way to do this? Can we build first class support for this by writing/documenting a resource which makes this easy for our users because this gonna be a pain point for a lot of people once we hit live systems.

**Comment by mgasner** [comment]
#1289 #1246  #681

**Comment by mgasner** [comment]
#1290

**Comment by catherinewu** [comment]
going to close this issue as 1) max's linked issues are resolved and 2) the issue is a bit broad. we can create new issues as user requests come in
