### ISSUE TITLE
Tag display in run history is cramped and visually intrusive

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1921]
<img width="1680" alt="Screen Shot 2019-11-19 at 10 25 21 AM" src="https://user-images.githubusercontent.com/427016/69174616-022cba00-0ab7-11ea-85c9-e66ca5405eb5.png">

**Comment by schrockn** [comment]
This gets worse with multiple tags. I imagine we will start to jam more tags into this. Separately we should be able to add tags from the execution console.

**Comment by helloworld** [comment]
+1 to adding tags from the execution console. This is important for running partitioned-based runs and testing scheduled-runs from the console.

**Comment by prha** [comment]
Split off https://github.com/dagster-io/dagster/issues/2053 as a separate issue
