### ISSUE TITLE
Getting into invalid subselection state where you can't recover

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1924]
See bottom left:

![Screenshot 2019-11-20 07 34 46](https://user-images.githubusercontent.com/28738937/69252869-8b4ff980-0b68-11ea-8bb2-ee3375085728.png)

If you click you can select nothing

![Screenshot 2019-11-20 07 34 52](https://user-images.githubusercontent.com/28738937/69252884-90ad4400-0b68-11ea-9a91-a36be6b7fec1.png)

Here's the state of local storage

![Screenshot 2019-11-20 07 36 07](https://user-images.githubusercontent.com/28738937/69252907-96a32500-0b68-11ea-836d-b8f64abf5c80.png)

**Comment by bengotow** [comment]
Fixed in https://dagster.phacility.com/D1508!

**Comment by bengotow** [comment]
Resolved by D1508
