### ISSUE TITLE
`Definitions` dropdown on ops and graphs unreadable in dark mode

### ISSUE THREAD

**Issue by jacobkaf** [dagster-io/dagster#19259]
### Dagster version

1.6.0

### What's the issue?

Trying out new dark mode and when clicking around on jobs, I noticed the text in the `Definition` dropdown for ops and graphs is borderline unreadable. 

Graph of graphs:
<img width="350" alt="Screenshot 2024-01-17 at 11 46 19 AM" src="https://github.com/dagster-io/dagster/assets/111370778/35634438-76b5-4a8e-8cc6-f879c6f9b002">

Graph of ops:
<img width="342" alt="Screenshot 2024-01-17 at 11 48 39 AM" src="https://github.com/dagster-io/dagster/assets/111370778/24a14da1-0c14-44b5-a5d4-e27638b8281b">

### What did you expect to happen?

I'm guessing the font color here was supposed to be white to match the rest of dark mode

### How to reproduce?

Click on any job in the UI, then select one of the nodes of the job graph and click the `Definitions` tab on the sidebar (if it doesn't open by default)

### Deployment type

Other

### Deployment details

I'm not sure deployment type applies here because it's a UI issue, but we use the Helm chart + kubernetes and AWS

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Fixed with [https://github.com/dagster-io/dagster/pull/19265](https://github.com/dagster-io/dagster/pull/19265).
