### ISSUE TITLE
Images in Dagster reference guide are broken

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1928]
https://dagster.readthedocs.io/en/0.6.4/sections/reference/reference.html currently shows images extremely large and with a 1px border. @mgasner is this related to any of our recent docs changes?

<img width="938" alt="image" src="https://user-images.githubusercontent.com/609349/69385195-6a27ff80-0c73-11ea-83d5-0059ec315740.png">

**Comment by mgasner** [comment]
Hmm, is this broken? I switched these to be thumbnails, we can revert.

**Comment by natekupp** [comment]
yeah sorry s/broken/oversized/
