### ISSUE TITLE
Redocument/rework @dagster_type and as_dagster_type APIs

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#1929]
**Observation:**

I defined a TripDataFrame dagster type in the following way because I read the reference [code](https://dagster.readthedocs.io/en/latest/sections/reference/reference.html#dagster-types) which said: `Types also allow for custom materialization, and are typically defined using the @dagster_type decorator or the as_dagster_type API. It is also possible to inherit from RuntimeType directly.`

This made me believe that as_dagster_type was a convenience function. So when I did:

```
TripDataFrame = as_dagster_type(
    name='TripDataFrame',
    existing_type=DataFrame,
    description='A consolidated view of all bay bike trips in 2018/2019',
    type_check=validate_trip_dataframe,
)
```

All DataFrames started to get casted as TripDataFrame's which was super confusing when I defined my solid as:

```
@solid(required_resource_keys={'transporter', 'volume'})
def download_csv_from_bucket_and_return_dataframe(
    context, key: str, path_to_file: str
) -> DataFrame:
    target_csv_location = os.path.join(context.resources.volume, path_to_file)
    context.resources.transporter.download_file_from_bucket(key, target_csv_location)
    return read_csv(target_csv_location)
```

and got the following image in dagit:

![Screen Shot 2019-11-21 at 3 48 18 PM](https://user-images.githubusercontent.com/4219809/69386888-c9d4d980-0c78-11ea-8683-96575c2e8cce.png)

**Solution:**

After talking with @mgasner, it turns out that `as_dagster_type` converts everything to the custom datatype wheras `@dagster_type` just converts a specific instance to that dagster type when you do `TripDataFrame(<object of type DataFrame>)`. We ought to make this clear in the docs:

https://dagster.readthedocs.io/en/latest/sections/reference/reference.html#dagster-types

AND

https://dagster.readthedocs.io/en/latest/sections/learn/tutorial/types.html#user-defined-types

**Comment by schrockn** [comment]
Removing good first issue because I think this is a core abstraction problem as opposed to a documentation problem

**Comment by mgasner** [comment]
team seems to agree that `as_dagster_type` (perhaps renamed to be more transparent, e.g., `register_dagster_type`) is a better API to point new users at than `@dagster_type`

**Comment by schrockn** [comment]
0.7.0 type system changes resolve this
