### ISSUE TITLE
How does dagster compare and contrast to kedro?

### ISSUE THREAD

**Issue by karhohs** [dagster-io/dagster#1931]
Hello,

I have experience with Airflow and am intrigued by the additional layer of abstraction provided by Dagster to create more generalized, reproducible workflows that can scale from the inception of a project to production. At least, that’s the promise I perceive when reading the docs. However, I would like to know more about what sets Dagster apart from another project that seems to share many of the design goals of Dagster: Kedro. Unfortunately, I don’t have enough experience to recognize the differences.

Would someone please compare these two projects to help me decide if Dagster is the right tool for me? Are these projects solving the same problem? What about Dagster sets it apart from Kedro? I know this is an opinionated forum to ask such a question, but I have a feeling I’m not the only one facing this confusion.

Thanks in advance for any help!

**Comment by flowersw** [comment]
Having completed the tutorials for several tools (some of them related, some not), including Dagster and Kedro, I wrote a blog post documenting my initial experience of them. It could be a starting point for what you're looking for: https://medium.com/@will_flwrs/python-data-engineering-tools-the-next-generation-354e00f2f060

**Comment by natekupp** [comment]
I'm going to close this issue in favor of #1593 so that we have one issue tracking this—thanks!
