### ISSUE TITLE
Reconcile nullable and optional verbiage in the config and runtime type systems

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1933]
Right now we are not consistent at all

**Comment by mgasner** [comment]
@schrockn i think this is done?

**Comment by schrockn** [comment]
No I wouldn't call this done yet

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by schrockn** [comment]
only last vestigial element here is in our graphql interface, but i'll call that an implementation detail of the the system
