### ISSUE TITLE
Unexpected GraphQL error in Development-default-Lineage view

### ISSUE THREAD

**Issue by craigchoi** [dagster-io/dagster#19337]
### Dagster version

1.6.1

### What's the issue?

When load screen, there are Unexpected GraphQL error. Has shown doulble times on right side of top with red warning.
Error Message:
Operation name: AssetGroupMetadataQuery
Message: Fragment 'SensorSwitchFragment' is never used.
Path: 
Locations: [{"line":11,"column":1}]

### How to reproduce?

Every time it happened

### Deployment type

None

### Additional information

Didn't use SensorSwitchFragment anywhere

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by CamronBorealis** [comment]
I am also getting this

**Comment by jmarciloamo** [comment]
I am also getting this

**Comment by hainenber** [comment]
I think this is fixed by #19293. Probably landed in a next minor release :D

**Comment by craigchoi** [comment]
> I think this is fixed by #19293. Probably landed in a next minor release :D

Great. Thanks for let me know.

**Comment by craigchoi** [comment]
Solved since 1.6.2
