### ISSUE TITLE
Graph view does not show branching correctly

### ISSUE THREAD

**Issue by hoopes** [dagster-io/dagster#19331]
### Dagster version

not sure, i think latest

### What's the issue?

When looking at the graph view, branches do not render correctly:

<img width="1025" alt="Screenshot 2024-01-19 at 6 43 12 PM" src="https://github.com/dagster-io/dagster/assets/565716/17718f18-3bb9-4256-bd4f-f5a37058b9e6">
<img width="1216" alt="Screenshot 2024-01-19 at 6 43 34 PM" src="https://github.com/dagster-io/dagster/assets/565716/d2d4cce4-4a02-4a81-8e76-e530f3c1113b">

The tree structure appears correct, but in the graph view, the branching nature of the dag is not obvious.

### What did you expect to happen?

It should be obvious that a decision is being made in the op that branches, and there are two (or more, i suppose) potential destinations for the next step.

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hoopes** [comment]
https://reactflow.dev/

This appears to be a very nice drop-in react component for drawing dags.

**Comment by bengotow** [comment]
Thanks for filing this 👋  We unfortunately can't easily swap in a different rendering library for this (the Gantt view is rendered with a time axis in some scenarios, there are a lot of annotations that can appear when more exotic Dagster features are in use, and the layout algorithm has to be simple enough to render performantly for 10,000+ nodes) 

That said this looks awful and I think we can render the lines differently to do a better job!  I put up a small PR addressing this by moving the vertical portion of the lines to the whitespace between the nodes and we'll see how that looks. Thanks for reporting!

**Comment by hoopes** [comment]
The screenshots in that PR definitely look a lot better. I don't suppose it's easily possible to also expand the box size to show the entire name of the op? I'm clearly not in the 10k node world, so "no" is a fine answer. Thanks so much for taking a look at this!

**Comment by bengotow** [comment]
You bet! The nodes are actually getting wider in the next release as well - there was a separate request for that here :-) https://github.com/dagster-io/dagster/pull/20976. Cheers!
