### ISSUE TITLE
Solid Selection borked in master

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1934]
Ben I know you are reworking this (and I would just fix this in your new design) but the solid subselection stuff is borked in master.

![Screenshot 2019-11-23 09 59 12](https://user-images.githubusercontent.com/28738937/69483091-f7846480-0dd7-11ea-9983-cd1a5a885cf3.png)

**Comment by schrockn** [comment]
This may be a false positive. I cleared browser state. Will see if that resolved. I swore I did that before.

**Comment by mgasner** [comment]
Can't reproduce
