### ISSUE TITLE
Unexpected GraphQL Error

### ISSUE THREAD

**Issue by ngurahyudi** [dagster-io/dagster#19364]
### Dagster version

dagster, version 1.6.1

### What's the issue?

<img width="1207" alt="image" src="https://github.com/dagster-io/dagster/assets/16011522/5ae33319-e026-433a-8809-6a3e77556525">

### How to reproduce?

run `dagster dev` command and reload asset in dagster web UI

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by craigchoi** [comment]
You have the same issue that I have. Refer to this, #19337. It may fix in the next minor release.

**Comment by craigchoi** [comment]
After installing 1.6.2, Check it? Should be gone.

**Comment by yuhan** [comment]
dup of https://github.com/dagster-io/dagster/issues/19488 - this was fixed in 1.6.2
