### ISSUE TITLE
Add dagster_event_type,timestamp index to postgres event log alembic migration

### ISSUE THREAD

**Issue by kirkhansen** [dagster-io/dagster#19390]
### What's the use case?

We're using dagster's event log (backed by dagster postgres) to emit openlineage events. The query we use via the `DagsterInstance.get_event_records` ends up being something like:

```sql
SELECT event_logs.id, event_logs.event 
FROM event_logs 
WHERE event_logs.dagster_event_type = 'STEP_START' 
AND event_logs.timestamp < '2024-01-24T16:08:58.145735'::timestamp 
AND event_logs.timestamp > '2024-01-24T16:03:51.618856'::timestamp 
ORDER BY event_logs.id ASC;
```

This was causing a ton of IO use due to there not being an index on dagster_event_type and timestamp.

I manually created an index on the db with

```sql
CREATE INDEX idx_events_by_timestamp ON public.event_logs USING btree (dagster_event_type, timestamp);
```
and saw several orders of magnitude performance improvement with this query. This would allow a downsize in required AWS RDS instance type size to save some money since we no longer need as many IOPS.

Was leaving the timestamp column unindexed intentional? Is there an appetite for accepting a PR creating that index?

### Ideas of implementation

The alembic migration for postgres receives an update to create an index on dagster_event_type and timestamp column.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rileymcdowell** [comment]
Hi all. I work with @kirkhansen and was also affected by this issue. In case it's not immediately obvious, the [EventRecordsFilter](https://docs.dagster.io/_apidocs/internals#dagster.EventRecordsFilter) accepts `after_timestamp` and `before_timestamp` fields, which are the ones we were using. Those fields don't have a corresponding index, so a dagster instance with a sufficient number of events stored will take significant execution time if those fields are used.

**Comment by alangenfeld** [comment]
> The query we use via the DagsterInstance.get_event_records ends up being something like

Our current `get_event_records` API is very open ended and allows you to create lots of different queries that can perform poorly without the right index. Adding this timestamp index for your specific `get_event_records` call is definitely a good move. A slightly more optimal index index could be `(dagster_event_type, timestamp, id)` since its ordered by `id`. If you only care about specific `dagster_event_type` you could consider a partial index / using a `where` clause on the index.

Since this is a custom query that doesn't occur naturally in the core product, its unclear that we should add this as a default index.

**Comment by kirkhansen** [comment]
I opened this as an enhancement request precisely because I thought you might be leaving this index off because dagster core wasn't using it. Thank you for confirming, and for developing dagster.

Is there a recommended path for adding custom indices? Perhaps another approach is to document the way to add custom indices to the event log storage and add a note that any queries using the `after_timestamp` and `before_timestamp` filters will very likely cause performance issues and link to the docs for adding custom indices.

If all is a no go, feel free to close the issue. Thanks!

**Comment by alangenfeld** [comment]
> Is there a recommended path for adding custom indices?

Adding them directly to the DB manually is practical and I believe a reasonable solution. 

> is to document the way

A lightweight way to do this is to start a Q&A discussion that you submit an answer for with the approach you took here. If you do a good job with the title / question then other users who search should hit that Q&A discussion. Here is a tangentially related example https://github.com/dagster-io/dagster/discussions/12047. If you would be willing to do that it would be greatly appreciated.

**Comment by kirkhansen** [comment]
> If you would be willing to do that it would be greatly appreciated.

Certainly! It may take me a few days to get around to it, but I'm willing to do that.

**Comment by kirkhansen** [comment]
I didn't notice that linking too the issue in the discussion did not mention that discussion

https://github.com/dagster-io/dagster/discussions/19493

I'll close this issue
