### ISSUE TITLE
Unable to set up on Dagster cloud

### ISSUE THREAD

**Issue by juraurai** [dagster-io/dagster#19415]
I have the same problem.

Could you do the same reset for me?

### Discussed in https://github.com/dagster-io/dagster/discussions/17750

<div type='discussions-op-text'>

<sup>Originally posted by **MZF404** November  7, 2023</sup>
Hi, I just started a serverless dagster cloud trial yesterday, and while setting up a sample project, I hit an unexpected critical error (sorry, didn't manage to get a screenshot).

Following that, the setup tabs have disappeared and I'm left with a perpetual spinning icon on my UI. I'm unable to set up with dagster cloud as a result. Is there any fix for this? Thank you!
</div>

**Comment by prha** [comment]
Hi, I just reset the setup state for you.  Feel free to reopen an issueif you run into this again.
