### ISSUE TITLE
Dark Mode Breaks Slack Modal Styles

### ISSUE THREAD

**Issue by ryandstoughton** [dagster-io/dagster#19411]
### Dagster version

dagster, version 1.6.1

### What's the issue?

Using dark mode, this modal shows up like

<img width="735" alt="Screenshot 2024-01-25 at 9 44 07 AM" src="https://github.com/dagster-io/dagster/assets/46951044/0fa29c5e-d93b-44e4-ba4b-789b46dfb8b6">

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey @ryandstoughton thanks for filing this! We've actually fixed this (in f107e18e) and it's pending release. Stay tuned!
