### ISSUE TITLE
Core compute for solid returned an output multiple times

### ISSUE THREAD

**Issue by mnm-tbk** [dagster-io/dagster#1943]
Hi, I started experimenting with Dasgter and it has been very interesting experience, however I think I am missing something important about the design of the tool. 

How would one go about yielding unknown number of Outputs from the solid?

What I have tried:

```
@solid(output_defs=[OutputDefinition(Tuple, 'classification_data')])
def extract_classification_from_file(context, xml_path: String) -> Tuple:
    context.log.info(f"start")
    root = ET.parse(xml_path).getroot()
    for code_node in root.findall('definition-item'):
        context.log.info(f"{code_node.find('classification-symbol').text} {code_node.find('definition-title').text}")
        yield Output((code_node.find('classification-symbol').text, code_node.find('definition-title').text), 'classification_data')


@solid()
def load_classification(context, classification_data):
    cls = CPCClassification.objects.create(code=classification_data[0], description=classification_data[1]).save()

@pipeline
def define_classification_pipeline():
    load_classification(extract_classification_from_file())
```

What i recieved:
```
dagster.core.errors.DagsterInvariantViolationError: Core compute for solid "extract_classification_from_file" returned an output "classification_data" multiple times
```

Is there any way to parse xml file in Dagster other than returning a list of values?

**Comment by mgasner** [comment]
Hi @mnm-tbk, right now there is no way to yield Outputs that are only defined at runtime. Can you provide a little more context about what you're trying to accomplish here? Depending on the size of your data, it may make sense for you to just work with a List[Tuple].

**Comment by mgasner** [comment]
#462

**Comment by mnm-tbk** [comment]
I was basically just curios, returning List[Tuple] is sufficient for now.
