### ISSUE TITLE
Show name of asset instead of showing it under `Ad hoc materializations` in the Overview tab

### ISSUE THREAD

**Issue by chrishiste** [dagster-io/dagster#19477]
### What's the use case?

We've been leaning more towards auto materializing rather than traditional jobs lately. In the user interface, these are all grouped under 'Ad hoc materializations'. It'd be really helpful if they showed up each one separately, categorized either by their asset group or specific names.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by chrishiste** [comment]
![ScreenShot 2024-01-30 at 14 43 04@2x](https://github.com/dagster-io/dagster/assets/24848602/5830ab43-7c23-4fbd-8899-7984f943fcf7)

Similarly would be nice to have the name propagate to Slack as well instead fo `__ASSET_JOB_X`

**Comment by salazarm** [comment]
We have something in the works for this https://github.com/dagster-io/dagster/pull/19431

**Comment by chrishiste** [comment]
@salazarm Very nice, should I open another issue for `__ASSET_JOB_X`?

**Comment by chrishiste** [comment]
@salazarm hi, this is still an issue for us, what's the best course of action?

**Comment by garethbrickman** [comment]
Duplicates https://github.com/dagster-io/dagster/issues/15423

@chrishiste Please follow and comment in that issue, it is on our UI team's radar 👍
