### ISSUE TITLE
Dynamic steps skipped in job retry after run is terminated unexpectedly

### ISSUE THREAD

**Issue by OrenLederman** [dagster-io/dagster#19490]
### Dagster version

1.6.2

### What's the issue?

We are encountering an issue in our Dagster pipeline where dynamic steps are being skipped during the retry of a job after an unexpected run termination when the job is set to resume from failure. In particular, we see that the instances of the dynamic step that were running at the time of termination are just ignored in the retry+resume attempt.

We first encountered the project in a Kubernetes environment where pod failures, such as Out Of Memory (OOM) errors or node terminations, lead to the abrupt ending of a run. When the job resumed, some parts of the dynamic step where skipped, leading to data loss.

I was able to replicate the issue in a local environment as well. In the example below, I created a job with a dynamic step, and a collector step that fails if the number of dynamic inputs it receives is incorrect. I killed the process while one of the dynamic step instances was running. you can see it in gray color here:
<img width="448" alt="Screenshot 2024-01-30 at 9 55 11 AM" src="https://github.com/dagster-io/dagster/assets/365577/1f588110-5315-4143-b9ac-a461e8a1e416">

When the job retried, only the collector step attempted to run, but it failed because it only got 2 inputs instead of 3. Note that the assertion error is raised by an assertion I put in there, not Dagster's code.
<img width="447" alt="Screenshot 2024-01-30 at 9 55 22 AM" src="https://github.com/dagster-io/dagster/assets/365577/c73b6f87-0735-400c-87eb-a17b379743c6">

<img width="439" alt="Screenshot 2024-01-30 at 9 55 31 AM" src="https://github.com/dagster-io/dagster/assets/365577/bd4ebb98-2d51-426b-9d84-3f6565e8b493">

### What did you expect to happen?

I expect Dagster to run the instances of the dynamic step that failed or were executing (but did not complete). In the example above, i'd expect it to run `process number` for the key `2` again. Or at least throw an error. Ignoring these failures lead to silent data loss.

### How to reproduce?

I used the following code to create a dynamic job. I enabled retries and set the event_log_storage in the dagster.yaml file.

One of the instances of the dynamic step goes into an infinite loop so I have time to terminate the process with `kill -9`.

To reproduce the issue, kick off a run, look for the PID of the run, and kill it with `kill -9` while the dynamic step is running.

```
NUMBERS = [0, 1, 2]

@op(out=DynamicOut())
def emit_numbers():
    for i in NUMBERS:
        yield DynamicOutput(value=i, mapping_key=str(i))

@op
def process_number(context, number):
    context.log.info(f"Processing number: {number}")
    if number == 2:
        context.log.info(f"Entering an infinite loop for: {number}")
        while True:
            pass
    return number

@op
def collector(context, numbers: List[int]):
    context.log.info(f"Collected numbers: {numbers}")
    assert len(numbers) == (NUMBERS)

@job(
    tags={"dagster/max_retries": 3, "dagster/retry_strategy": "FROM_FAILURE"},
    executor_def=multiprocess_executor,
)
def dynamic_job():
    numbers = emit_numbers()
    process_results = numbers.map(process_number)
    collector(process_results.collect())

defs = Definitions(
    jobs=[dynamic_job],
)
```

### Deployment type

Local

### Deployment details

This happens in a local python environment where I enabled retries and set the event_log_storage in the dagster.yaml file.
It also happens when running self-hosted dagster in k8s (GKE 1.28)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OrenLederman** [comment]
Note - this is related to an older issue I create a while back (https://github.com/dagster-io/dagster/issues/15259). I created a new ticket because I narrowed down the actual problem and found an easier way to recreate it locally.

**Comment by alangenfeld** [comment]
Thanks for taking the time to put together a solid repro, this made it easy to track down the problem.

**Comment by OrenLederman** [comment]
Great, thanks for the quick fix!
