### ISSUE TITLE
optional bigint migration breaks auto-increment fields for mysql storage

### ISSUE THREAD

**Issue by paralyzah** [dagster-io/dagster#19510]
### Dagster version

1.4.15 or above

### What's the issue?

https://github.com/dagster-io/dagster/pull/16057/files#diff-dbae0cc9739a50d3c92215d45e24691c45bb7fdfd32e4bde4a34a1e4a7d7fd0bR49
erases AUTO_INCREMENT property
ALTER TABLE MODIFY requires an explicit column properties declaration, more information about MODIFY behaviour described here:
https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

### What did you expect to happen?

All columns after migration should remain AUTO_INCREMENT property, if they had AUTO_INCREMENT property before optional migration

### How to reproduce?

1. boostrap fresh instance with version before optional migration implementation, for instance 1.4.14
2. check output ```select * from sys.schema_auto_increment_columns```
3. update to 1.4.15
4. apply ```dagster instance migrate```
5. apply ```dagster instance migrate --bigint-migration```
6. check output ```select * from sys.schema_auto_increment_columns```

### Deployment type

Other

**Comment by prha** [comment]
@paralyzah thanks for the report.  I just put up https://github.com/dagster-io/dagster/pull/19582 which should address the issue and go out in the next release.

In the meantime, you can manually alter the id cols to autoincrement.
