### ISSUE TITLE
[dagster-airflow] transient GraphQL errors

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1955]
seems like we might be getting transient graphql errors occasionally: 

https://buildkite.com/dagster/dagster/builds/7644#82e81793-0a65-4f60-97c4-ad49da58ca4a

filing an issue for now (cc: @alangenfeld) - we can dig in more if this comes up again

**Comment by alangenfeld** [comment]
another: https://buildkite.com/dagster/dagster/builds/7653#a7a7ed3c-01af-4ffd-bc36-708bd4654765

**Comment by alangenfeld** [comment]
https://buildkite.com/dagster/dagster/builds/7674#c9dd987b-163e-4a07-a09f-0ac2dad945af

**Comment by alangenfeld** [comment]
https://buildkite.com/dagster/dagster/builds/7855#d0bb8c65-c138-4d31-8894-d642e6a5c46f

**Comment by mgasner** [comment]
let's close this until it recurs
