### ISSUE TITLE
Display full name somehow in typeahead

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1956]
Right now it just totally clips the name which is not the best.

<img width="187" alt="Screenshot 2019-12-05 19 29 49" src="https://user-images.githubusercontent.com/28738937/70293633-b572ff80-1795-11ea-8cef-75d1f6f0000b.png">

**Comment by bengotow** [comment]
This is slightly a problem (with solids) in the new UI, but I've addressed this quite a bit via a new custom tooltip implementation in #2421. It now does this when you hover over an item in the sidebar that is truncated:

![image](https://user-images.githubusercontent.com/1037212/83569251-ceacfc80-a4e9-11ea-8edd-03ef87817dd7.png)
