### ISSUE TITLE
self._conn_str not used in LocalSQLiteWarehouse

### ISSUE THREAD

**Issue by mpatek** [dagster-io/dagster#1957]
Hi, nice project!

I was just running through the tutorial yesterday. In the [resources section](https://dagster.readthedocs.io/en/stable/sections/learn/tutorial/resources.html) of the tutorial, when you use the SQLite warehouse, it doesn't look like the `conn_str` parameter is being used. The db connection is done [like this](https://github.com/dagster-io/dagster/blob/50467ed7f7aedab3d009d1bbb8492a10ccf3ec47/examples/dagster_examples/intro_tutorial/resources.py#L23):

```Python
        conn = sqlite3.connect('example.db')
```

but I think it should be:

```Python
        conn = sqlite3.connect(self._conn_str)
```

**Comment by schrockn** [comment]
Great catch! Thanks for the report

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D1553
