### ISSUE TITLE
DBT ephemeral models fail due to absence in the asset graph

### ISSUE THREAD

**Issue by Pr0p1k** [dagster-io/dagster#19619]
### Dagster version

1.5.14

### What's the issue?

We have few ephemeral DBT models. 
They are represented in Dagster asset graph as sources, which is fine.

The problem arises after execution:
dagster._core.errors.DagsterInvariantViolationError: Core compute for op "run_dbt_da74d" returned an output "eph_***_dbt" that does not exist. The available outputs are [...]

The status in Dagster is "failed", but the models work successfully in our database.

So it seems, the ephemeral model is reported by dbt as successful, but Dagster can't find it, since it's not included in the graph.

There might be a potential issue that we have two dirs with models: "core" and "core_rel", and the missing comes from "core". But anyway table materialized models are shown from both dirs, and both dirs ephemeral models are missing in the available outputs.

### What did you expect to happen?

Suppress the error as there's no way to display ephemeral models in Dagster

### How to reproduce?

Create any upstream ephemeral model and run "Materialize all" 

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
I can't reproduce this using `@dbt_assets`. If you have a minimal reproduction exhibits your exact problem, please share it and re-open the issue.
