### ISSUE TITLE
Tutorial: Scheduling section should include requirements

### ISSUE THREAD

**Issue by mpatek** [dagster-io/dagster#1961]
In the [scheduling section](https://dagster.readthedocs.io/en/latest/sections/learn/tutorial/scheduler.html#scheduling-pipeline-runs) of the tutorial, the code includes the `dagster_cron` library, which requires a  `pip install dagster-cron`. There should probably be some indication of that, similar to what's done in the [Airflow section](https://dagster.readthedocs.io/en/latest/sections/learn/tutorial/intro_airflow.html#requirements).

**Comment by zzztimbo** [comment]
Hi @mpatek I've updated the documentation.
