### ISSUE TITLE
We ought to swap out Dagster types for native python types in the solid configs for our examples

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#1963]
We ought to swap out Dagster types for native python types in the solid configs for our examples

**Comment by asingh16** [comment]
Currently, our solids in the airline demo and other examples are using DagsterTypes in the config fields. Changes have been made so that native python types are preferred so we should switch to that for all of our examples!

**Comment by mgasner** [comment]
assigning this to @schrockn for disposition

**Comment by mgasner** [comment]
going to close this -- the type system has moved quite a bit since 12/19
