### ISSUE TITLE
Renable test_interrupt_multiproc

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1970]
Flaky test.

**Comment by schrockn** [comment]
(Just assigning to max because he can reliably repro)

**Comment by schrockn** [comment]
Still seeing this unfortunately

**Comment by schrockn** [comment]
https://buildkite.com/dagster/dagster-diffs/builds/3043#c05884ac-8a18-4bdf-807b-a613c04cc533

**Comment by natekupp** [comment]
This has been fixed by @gibsondan
