### ISSUE TITLE
Assets web page memory leak

### ISSUE THREAD

**Issue by EtienneT** [dagster-io/dagster#19726]
### Dagster version

1.6.4

### What's the issue?

Keep the /assets page in chrome opened for a while.  Open dev tools and you will see the memory steadily increasing.  After a while, the tab in chrome crash with an out of memory exception.  This can take several hours.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment]
Thanks for bringing this to our attention, @EtienneT -- I've confirmed that I experience the memory leak as well.

When using the _Task Manager_ in Chrome, you can clearly see the number rise.

<img width="256" alt="image" src="https://github.com/dagster-io/dagster/assets/5807118/10a4ff21-e11c-4d4f-b5be-15b91a1433de">

And using the Memory profiler in the developer tools, we can compare the object allocation between two heap snapshots and see in more detail where things are being allocated.

<img width="1307" alt="image" src="https://github.com/dagster-io/dagster/assets/5807118/1bdbea1c-cfd0-4ed7-ace9-a66c7bbe8e45">

We'll dig into this further - thanks.

**Comment by salazarm** [comment]
Thanks for the report, the fix will go out in our release this week
