### ISSUE TITLE
Write humane error message for nested errors in a config structure

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1976]
Right now it will give you no path information, which is rough. This will require keeping track of a stack during the processing pass that converts dicts and types to Fields

**Comment by natekupp** [comment]
@schrockn is this still an issue post-config system refactor?

**Comment by schrockn** [comment]
Yup. Our error messages definitely need a refresh.

**Comment by natekupp** [comment]
This has been improved recently, please re-open if still an issue cc @alangenfeld
