### ISSUE TITLE
Update documentation for config system

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1977]

**Comment by schrockn** [comment]
https://dagster.phacility.com/D1614

**Comment by mgasner** [comment]
#2139

**Comment by yuhan** [comment]
is https://docs.dagster.io/_apidocs/config good enough to close this issue?

**Comment by yuhan** [comment]
Im gonna close this issue as we have relatively complete documentation for the config system:
- concept explanation: https://docs.dagster.io/concepts/configuration/config-schema
- complete api docs: https://docs.dagster.io/_apidocs/config#dagster.ConfigSchema

As for more comprehensive descriptions/explanations like the config system's motivation or good patterns, please open new issues with concrete content asks
