### ISSUE TITLE
Inconsistent behaviour for `context.asset_key_for_input` when using `deps` with `key_prefix`

### ISSUE THREAD

**Issue by A-Stangeland** [dagster-io/dagster#19790]
### Dagster version

1.6.4

### What's the issue?

I am trying to get the key and partition key of an upstream asset depencency specified with the `deps` parameter in the `@asset` decorator. This works if the key of the upstream asset key only has a single part, e.g., `AssetKey(['upstream'])` like in this example:
```python
@asset(partitions_def=my_partition_def)
def upstream() -> None:
    pass

@asset(deps=[upstream], partitions_def=my_partition_def)
def downstream(context: AssetExecutionContext) -> None:
    print(context.asset_key_for_input("upstream"))
    print(context.asset_partition_key_for_input("upstream"))
```
However, if I specify a `key_prefix` for the upstream asset this no longer works:

```python
@asset(partitions_def=my_partition_def, key_prefix="prefix")
def upstream() -> None:
    pass

@asset(deps=[upstream], partitions_def=my_partition_def)
def downstream(context: AssetExecutionContext) -> None:
    print(context.asset_key_for_input("upstream"))
    print(context.asset_partition_key_for_input("upstream"))
```
This raises an error when materializing the downstream asset: 
```
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "downstream"::

dagster._check.CheckError: Failure condition: Input 'upstream' has no asset
```

### What did you expect to happen?

I expected `AssetExecutionContext.asset_key_for_input` and `AssetExecutionContext.asset_ partition_key_for_input` to behave the same way regardless if the upstream asset key has a single or multiple parts.

### How to reproduce?

This code should reproduce the error: 
```python
from dagster import (
    asset,
    Definitions,
    AssetExecutionContext,
    StaticPartitionsDefinition,
)

my_partition_def = StaticPartitionsDefinition(["A", "B"])


@asset(partitions_def=my_partition_def, key_prefix="prefix")
def upstream() -> None:
    pass


@asset(deps=[upstream], partitions_def=my_partition_def)
def downstream(context: AssetExecutionContext) -> None:
    print(context.asset_key_for_input("upstream"))
    print(context.asset_partition_key_for_input("upstream"))


defs = Definitions(assets=[upstream, downstream])
```

### Deployment type

Local

### Additional information

More generally, I am looking for a consistent way to manage the storage paths of assets regardless if they use an IO manager or not. As IO managers inheriting from `UPathIOManager` use the asset key to construct the path, I want to be able to construct the paths in the same way for assets where using an IO manager is not practical.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by maximearmstrong** [comment]
Hey @A-Stangeland - when a prefix is added, it changes the key of the asset. See full documentation [here](https://docs.dagster.io/_apidocs/assets#software-defined-assets). It is done [here](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py#L923-L924) in the code.

> key_prefix (Optional[Union[str, Sequence[str]]]) – If provided, the asset’s key is the concatenation of the key_prefix and the asset’s name, which defaults to the name of the decorated function. Each item in key_prefix must be a valid name in dagster (ie only contains letters, numbers, and _) and may not contain python reserved keywords.

I just tested your code updated with "prefix_upstream" instead of "upstream" and it worked:

```
from dagster import (
    asset,
    Definitions,
    AssetExecutionContext,
    StaticPartitionsDefinition,
)

my_partition_def = StaticPartitionsDefinition(["A", "B"])


@asset(partitions_def=my_partition_def, key_prefix="prefix")
def upstream() -> None:
    pass


@asset(deps=[upstream], partitions_def=my_partition_def)
def downstream(context: AssetExecutionContext) -> None:
    print(context.asset_key_for_input("prefix_upstream"))
    print(context.asset_partition_key_for_input("prefix_upstream"))


defs = Definitions(assets=[upstream, downstream])
```

**Comment by A-Stangeland** [comment]
Than you for the help @maximearmstrong! I thought I had tried this, but I must have missed it.

I guess what I am really looking for is for dagster to auto-resolve the asset key when using `deps`, like what happens when using an IO manager and passing the upstream dependency as a parameter to the downstream asset.
