### ISSUE TITLE
Allow for flattened view of nested solids in pipeline 

### ISSUE THREAD

**Issue by tseader** [dagster-io/dagster#1979]
Presently when creating composite_solids, you can only view the content of a single composite-solid at a time.  It would be wonderful to have the functionality to not lose visibility on the rest of the pipeline solids when viewing content of a composite solid.  Along the same lines, it would be great to expand out multiple composite_solids.

This is an example of the view I'm referring to where I can't view contents of a composite-solid without losing my view on the rest of the pipeline.  When a pipeline gets large, this could prove to be quite cumbersome and could dissuade users from wanting to use composite_solids since using them compromises the high-level (but still detailed) visual view of a pipeline
![image](https://user-images.githubusercontent.com/19822395/70627762-66d9c100-1bec-11ea-953e-bb02c3f03179.png)

**Comment by schrockn** [comment]
This is a great suggestion.

Are you in our slack?

**Comment by tseader** [comment]
Not yet

**Comment by bengotow** [comment]
This should be at least partially addressed by https://dagster.phacility.com/D1860!
