### ISSUE TITLE
[Documentation Feedback] Problem on /getting-started/hello-dagster page

### ISSUE THREAD

**Issue by pomkos** [dagster-io/dagster#19805]
404: Not Found
The page you are looking for does not exist.
If it should, please use theShare Feedback button at the top of this page to let us know

**Comment by garethbrickman** [comment]
hey @pomkos, thanks for alerting us to this! A fix is in [#19713](https://github.com/dagster-io/dagster/pull/19713), and it should be resolved in the next deployment of Dagster this week. 

In the meantime, the page is available when looking at the prior version 1.6.3 docs [here](https://release-1-6-3.dagster.dagster-docs.io/getting-started/hello-dagster)
