### ISSUE TITLE
[Documentation Feedback] Problem on /getting-started/hello-dagster page

### ISSUE THREAD

**Issue by dschafer** [dagster-io/dagster#19810]
This page is 404ing for me when I load it at https://docs.dagster.io/getting-started/hello-dagster, as linked from the left sidebar there. https://release-1-6-3.dagster.dagster-docs.io/getting-started/hello-dagster does not have the same issue.

(reported from the "Share feedback" on the right sidebar -- let me know if additional information is helpful)

**Comment by alangenfeld** [comment]
believe this is resolved by https://github.com/dagster-io/dagster/pull/19713
