### ISSUE TITLE
pyspark DataFrame Dagster type hardcodes resource name

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1983]
This will be problematic when we have a pipeline that interacts with multiple spark clusters (and hence resources with different names) - perhaps a use case for `resource_mapping_fn`?

https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-pyspark/dagster_pyspark/__init__.py#L143

**Comment by natekupp** [comment]
This is now at https://github.com/dagster-io/dagster/blob/f4d54382ec87cb1c69ea4d8c74522b5bb862edb6/python_modules/libraries/dagster-pyspark/dagster_pyspark/__init__.py#L29

**Comment by sryza** [comment]
This will be addressed by @dpeng817 's resource remapping work, so I'm going to close this.
