### ISSUE TITLE
Figure out alembic programming model mismatch

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1985]
alembic has a concept of a single revision per database -- in order to use alembic for smooth upgrades with postgres, we will probably have to enforce that postgres storages use separate databases for event log and run storage

**Comment by natekupp** [comment]
ouch that's rough. how does airflow handle this? they also use alembic and get away with one DB

**Comment by mgasner** [comment]
i have a plan -- basically am going to write the alembic revisions in a much more conditional style than is typical, and keep them in a single place rather than one per storage. will throw a diff up next week
