### ISSUE TITLE
feat: Support multi-line string in run_config

### ISSUE THREAD

**Issue by yevgenypats** [dagster-io/dagster#19882]
### What's the use case?

Im trying to pass a multiline string to an asset config and the UI shows the following:

<img width="1134" alt="image" src="https://github.com/dagster-io/dagster/assets/16490766/6a2f277a-6ca0-403b-9c56-ec8379604300">

In the code Im using the following to initialize the asset with a default configuration:

```
DEFAULT_CQ_HN_SPEC = """
kind: source
spec:
  name: "hackernews"
  path: "cloudquery/hackernews"
  registry: "cloudquery"
  version: "v3.0.22"
  tables: ["*"]
  destinations:
    - "sqlite"
  spec:
    item_concurrency: 100
    start_time: "2024-02-02T00:00:00Z"
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  registry: cloudquery
  version: "v2.7.0"
  spec:
    connection_string: ./db.sql
"""

class CloudQueryConfig(Config):
    spec: Optional[str] = None


@asset
def ingest_hn(context: AssetExecutionContext, config: CloudQueryConfig) -> None:
  execute_shell_command("cloudquery sync --log-console /Users/yevgenyp/dagstertutorial/cq-dagster-embedded/config", output_logging="STREAM", log=context.log)

hackernews_job = define_asset_job(
  "hackernews_job",
  selection=AssetSelection.all(),
  config=RunConfig(ops={"ingest_hn": assets.CloudQueryConfig(spec=DEFAULT_CQ_HN_SPEC)}))
```

Note: this is a partial snippet but if it's not enough I can provide full reproduction. 

### Ideas of implementation

I know the UI using the YAML editor so maybe using one of the multi-line annotators supported in yaml - https://yaml-multiline.info/ 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hi @yevgenypats thanks for reporting this! YAML is a bit odd in the way it handles long strings, I think the syntax you're looking for is this:

```yaml
ops:
  example:
    config: |
      hello\nworld this is interesting:\n\n
      a newline just wraps the input, there is no newline before a.
```

The `|` at the beginning tells it to handle the entire indented block as a single string. The newlines in the block don't translate to newlines in the string data, only the `\n` ones are actual newlines.

Hope that helps! I think we use a library similar to https://onlineyamltools.com/convert-yaml-to-json for parsing the configuration, so you could reference that and see if your YAML input produces the desired string value when it's converted to JSON.
