### ISSUE TITLE
Can't import DuckDBPolarsIOManager

### ISSUE THREAD

**Issue by arghaffari** [dagster-io/dagster#19896]
### Dagster version

1.6.5

### What's the issue?

DuckDBPandasIOManager can be imported but DuckDBPandasIOManager is not shown and can't be imported.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ion-elgreco** [comment]
Did you install dagster-duckdb-polars?

**Comment by arghaffari** [comment]
No after a while I noticed this but I forgot to close the issue, sorry, since I thought that it's a build-in package like pandas. thanks
