### ISSUE TITLE
Auto-materialize wrong multi-partition

### ISSUE THREAD

**Issue by chrisflesher** [dagster-io/dagster#19942]
### Dagster version

1.6.5

### What's the issue?

I have noticed that auto-materialize can generate the wrong partition when using a multi-partition.

### What did you expect to happen?

I have combined two partitions, (sensor name, location id number) into a multi-partition. I noticed auto-materialize sometimes attempts to generate downstream assets for the wrong sensor partition.

### How to reproduce?

I don't have a great way to reproduce right now, maybe could try to come up with a simplified example if it would be worth the effort?

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
Hey @chrisflesher - a replication case would certainly be useful for this

**Comment by chrisflesher** [comment]
Hmm... well I tried reproducing this and haven't been successful so far... closing this.
