### ISSUE TITLE
Nightly builds still failing

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1994]
@mgasner https://buildkite.com/dagster/dagster-nightly/builds/172#8eb4ee19-cb29-4df0-9c06-74c8ec7c6ab2 - my hypothesis is that this is because the nightly branch sticks around after a failed build, and so the nightly branch is pointing to the stale version that doesn't include `ac269e98f`

**Comment by schrockn** [comment]
Closing this for now with Nate's https://dagster.phacility.com/D1760
