### ISSUE TITLE
Dagstermill local output I/O Manager .write()

### ISSUE THREAD

**Issue by WCONFR** [dagster-io/dagster#20001]
### Dagster version

version 1.6.5

### What's the issue?

I am trying to generate an `op` which executes and stores a Jupyter Notebook. The op successfully executes but issues a warning that it failed to materialize the notebook and defaults to "local" which stores the executed notebook in a tmp folder. As a result I can't display the executed Notebook in Dagster UI.

The warning message:
```
Error when attempting to materialize executed notebook using file manager: AttributeError: 'LocalOutputNotebookIOManager' object has no attribute 'write'

Stack Trace:
  File "/usr/local/lib/python3.11/site-packages/dagstermill/factory.py", line 308, in _t_fn
    executed_notebook_file_handle = op_context.resources.file_manager.write(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Now falling back to local: notebook execution was temporarily materialized at /tmp/tmpima7ldo6/749ea425-9909-417d-bda4-475eea9ec279-out.ipynb
If you have supplied a file manager and expect to use it for materializing the notebook, please include "file_manager" in the `required_resource_keys` argument to `define_dagstermill_op`
```

### What did you expect to happen?

The executed notebook to be stored using the configured directory and having the possibility to display the executed notebook in Dagster UI.

### How to reproduce?

Create an `op` which executes a Notebook and try to visualize the the executed notebook.

``` jobs.py
from dagster import job, file_relative_path
from dagstermill import define_dagstermill_op
from dagstermill.io_managers import local_output_notebook_io_manager

nb_silae_dossiers = define_dagstermill_op(
    name='silae_dossiers',
    notebook_path=file_relative_path(__file__, 'notebooks/dossiers.ipynb'),
    required_resource_keys=set(['file_manager'])
)

resource_defs={
    'file_manager': local_output_notebook_io_manager
    # 'output_notebook_io_manager': local_output_notebook_io_manager,
    # 'file_manager': FilesystemIOManager(base_dir='/io')
}

@job(resource_defs=resource_defs)
def nb_execute_macro_job():
    nb_silae_dossiers()
```

``` repo.py
defs = Definitions(
    jobs=[nb_execute_macro_job]
    resources={
        # IO Managers
        'output_notebook_io_manager': ConfigurableLocalOutputNotebookIOManager(base_dir='/io/notebooks')
    }
)
```

Based on the warning I feel like Dagster correctly uses the LocalOutputNotebookIOManager but the code tries to use a unavailable method .write().

### Deployment type

I have dagster running in Docker containers with Python 3.11

### Deployment details

```
dagster==1.6.5
dagster-webserver==1.6.5
dagster-postgres==0.22.5
dagster-docker==0.22.5
dagstermill==0.22.5
ipykernel
jupyter
notebook==7.1.0
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yuhan** [comment]
```python
from dagster import job, file_relative_path
from dagstermill import define_dagstermill_op
from dagstermill.io_managers import local_output_notebook_io_manager

nb_silae_dossiers = define_dagstermill_op(
    name='silae_dossiers',
    notebook_path=file_relative_path(__file__, 'notebooks/dossiers.ipynb'),
)

@job
def nb_execute_macro_job():
    nb_silae_dossiers()
```
would it work if you remove the job-level resources which specifies a file manager?

**Comment by WCONFR** [comment]
We decided to put in the effort to migrate the notebook towards actual Assets and Ops which is ultimately a better solution. Therefore I didn't pursue the above.

I do think that there is still a problem running notebook **Ops** and displaying the executed notebook in the Web UI. However, I closed the ticket as I do no longer have the need to get this to work.
