### ISSUE TITLE
Execution plan rendering color scheme is messed up

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2000]
Some styling got messed up:

**Comment by schrockn** [comment]
![Screenshot 2019-12-16 14 38 31](https://user-images.githubusercontent.com/28738937/70949117-d9de9f80-2011-11ea-8453-f8bae12d28a0.png)

**Comment by bengotow** [comment]
Also found and will fix this 
<img width="214" alt="image" src="https://user-images.githubusercontent.com/1037212/71024058-b70fc200-20c9-11ea-9c4f-1906f1c4657e.png">

**Comment by bengotow** [comment]
https://dagster.phacility.com/D1691
