### ISSUE TITLE
Periodic Errors in SQLlite during multiprocessing

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2003]
![Screenshot 2019-12-17 08 55 38](https://user-images.githubusercontent.com/28738937/71018954-4f984900-20ae-11ea-881e-2e49be9d5014.png)
![Screenshot 2019-12-17 08 55 33](https://user-images.githubusercontent.com/28738937/71018955-4f984900-20ae-11ea-9a08-442b3c467905.png)

**Comment by schrockn** [comment]
![Screenshot 2019-12-17 09 19 45](https://user-images.githubusercontent.com/28738937/71018987-6048bf00-20ae-11ea-9697-bcc45e23eb45.png)

**Comment by mgasner** [comment]
see #2013 -- this was a regression
