### ISSUE TITLE
Long text in the "SCHEDULE" column in the Schedules tab gets cut off

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2008]
![Screenshot 2019-12-18 19 37 35](https://user-images.githubusercontent.com/28738937/71142999-e1e33e80-21cd-11ea-80dc-4f737fedf321.png)

See screenshot. There's no way to resize or click on it to see the full text

**Comment by helloworld** [comment]
Fixed by https://dagster.phacility.com/differential/revision/edit/1905/
