### ISSUE TITLE
Add filter by run id in runs page

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2010]

**Comment by helloworld** [comment]
@schrockn I think we already have this? Are you thinking of something other than this:

![image](https://user-images.githubusercontent.com/3893054/71700129-e17fa180-2d90-11ea-9209-35392fa0c058.png)

![image](https://user-images.githubusercontent.com/3893054/71700133-ea707300-2d90-11ea-8edd-8d66d90bbf8e.png)

**Comment by prha** [comment]
I think we can close this out... @schrockn feel free to reopen if you think the current state is ambiguous.
