### ISSUE TITLE
RunConfig cannot be used in PartitionedConfig and cannot contain Configs for IO managers

### ISSUE THREAD

**Issue by kaylimekay** [dagster-io/dagster#20117]
### Dagster version

1.6.5

### What's the issue?

`dagster._core.definitions.run_config.convert_config_input` handles the conversion from `RunConfig` to config dicts. In `RunRequest`, if a config is provided at construction, it is wrapped by `convert_config_input` and a `RunConfig` will be converted to a config dict as necessary. Later if the `with_resolved_tags_and_config` method is called, we have the following bit of code:
```
        return self.with_replaced_attrs(
            run_config=(
                self.run_config
                if self.run_config
                else partitioned_config.get_run_config_for_partition_key(self.partition_key)
            ),
            tags=tags,
        )
```
If `self.run_config` was already populated, it is used, and this will be the dict that may have been produced from a `RunConfig`. But if we are using a `PartitionedConfig` then a config is retrieved, and in this case it doesn't get wrapped by `convert_config_input`. A similar pattern occurs in other places as well. So we are not allowed to use `RunConfig` in `PartitionedConfig`. But I don't see any reason for this limitation and suspect it might just be an oversight.

Another related issue is that `convert_config_input` works by applying the `_convert_config_classes_inner` helper function recursively on the dicts inside the `RunConfig` until it finds a pythonic `Config` instance inside. These are rendered as a dict with a single key: `{"config": v._convert_to_config_dictionary()}`. The issue is that in some cases, there actually need to be other entries inside this dict, like `"input"` and `"output"`, and those entries may have other `Config`s inside them, so this simple structure isn't sufficient. (This is related to my other issue #20053.) If those keys are present, the resulting dict has the wrong structure and will cause errors later.

### What did you expect to happen?

A `PartitionedConfig` should be allowed to return a `RunConfig` like anywhere else in the code. 

Currently I am handling this by slapping the following decorator onto my function that generates configs from partition keys, under/before the `@partitioned_config` decorator.
```
def convert_run_config(config_fn):
    def wrapped_config_fn(partition_key):
        return _collapse_config_dict(convert_config_input(config_fn(partition_key)))

    return wrapped_config_fn
```
but this is a bit ugly and would be better handled inside dagster as it is in other cases.

The `_collapse_config_dict` relates to the second issue above. It is
```
def _collapse_config_dict(input):
    output = {}
    for key, value in input.items():
        if not isinstance(value, dict):
            output[key] = value
        elif len(value) == 1 and "config" in value:
            output[key] = value["config"]
        else:
            output[key] = _collapse_config_dict(value)
    return output
```
This fixes the resulting config dict structure, but again is pretty ugly and could be better handled internally. At any rate, I've verified that everything works as hoped after these modifications.

### How to reproduce?

Return a `RunConfig` from a `PartitionedConfig`, and/or try to give pythonic config for IO managers in a `RunConfig`.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by kriskringles** [comment]
Have there been any updates to this issue?
