### ISSUE TITLE
Seeing many cron processes on my machine

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2015]
<img width="711" alt="Screenshot 2019-12-19 09 02 10" src="https://user-images.githubusercontent.com/28738937/71193252-a765ba00-223e-11ea-93ca-eb095625f68d.png">

**Comment by mgasner** [comment]
hooray @helloworld

**Comment by natekupp** [comment]
@helloworld fixed this recently - it is a Catalina issue
