### ISSUE TITLE
AMP waiting on already updated parent

### ISSUE THREAD

**Issue by mjkanji** [dagster-io/dagster#20177]
### Dagster version

version 1.5.14

### What's the issue?

I am orchestrating my DBT project using the following AMP:

```python
class DailyDagsterDbtTranslator(CustomDagsterDbtTranslator):
    def get_auto_materialize_policy(
        self, dbt_resource_props: Mapping[str, Any]
    ) -> AutoMaterializePolicy:
        return AutoMaterializePolicy.lazy().with_rules(
            AutoMaterializeRule.skip_on_not_all_parents_updated(),
            AutoMaterializeRule.materialize_on_cron(cron_schedule="0 1 * * *"),
        )
```

Most of my DBT DAG is behaving correctly, but I noticed that one branch has not orchestrated correctly since February 28. See the following:

![image](https://github.com/dagster-io/dagster/assets/52061313/84fa0946-a5eb-4721-8d9e-1e1b20a2b7a6)

`chargify_customer_summary` is an external asset made using `external_assets_from_specs` and is materialized daily using a job that does `context.log_event(AssetMaterialization(asset_key=...))`.

This job is correctly logging materialization events for `chargify_customer_summary`. However, its children are not materializing and the `Automation` page shows they are waiting for `chargify_customer_summary` to be updated.

See the Automation page for one of its children (`customer_sub_history`):

![customer_sub_history_automation](https://github.com/dagster-io/dagster/assets/52061313/7b0d6080-775c-4e39-be4a-47fc994d82d1)

Note the times. `chargify_customer_summary` was materialized at 5 AM (see the DAG screenshot above) but at 6 AM, `customer_sub_history` says it's still waiting for the parent to be updated.

Looking at the events for `customer_sub_history` shows successful materializations every day until February 28th:

![customer_sub_history_events](https://github.com/dagster-io/dagster/assets/52061313/cb381bea-352e-43e8-a856-898a05c19743)

Based on those dates, I'm wondering if this is somehow a leap-year bug?

### What did you expect to happen?

That `customer_sub_history` would successfully materialize daily.

### Deployment type

Dagster Cloud

### Deployment details

Dagster Cloud Serverless.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cbini** [comment]
Just noticed this myself. Looks like the last time it worked was around 5 PM ET on 2/28.

**Comment by OwenKephart** [comment]
Hi @mjkanji thanks for the report. We've identified the issue here and a fix has been rolled out to Dagster Cloud.

For OSS users, the same fix will be available in next week's `1.6.9` release, or reverting to `1.6.6` will also avoid this issue.

**Comment by mjkanji** [comment]
Hi @OwenKephart, could you please clarify how the fix takes effect? I'm on Dagster Cloud Serverless and even after running my DBT DAG manually earlier in the day, the assets downstream of my external assets are not triggering at their AMP cron tick. The Automation page continues to say they're waiting for their (external asset) parents, which have already been updated.

Is the fix applied automatically for Cloud users or do I need to wait for the `1.6.9` release? I am on version `1.5.14` for your reference.

**Comment by OwenKephart** [comment]
Hi @mjkanji apologies for the confusion here -- there was a secondary fix that needed to happen on the cloud end to fully solve this issue, which has now been rolled out (as of this morning). No action is required on your end if you are a cloud user.

**Comment by mjkanji** [comment]
> Hi @mjkanji apologies for the confusion here -- there was a secondary fix that needed to happen on the cloud end to fully solve this issue, which has now been rolled out (as of this morning). No action is required on your end if you are a cloud user.

Awesome, thanks! I was also able to confirm that my DAGs are running as expected.
