### ISSUE TITLE
Unexpected errors in type checks do not behave properly

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2018]
When raise_on_error is true, I believe we should be letting those errors escape up the stack for testing etc. Currently raise_on_error is not respect and this is reported as just a vanilla type check failure, which is hard. We created check_dagster_type to compensate for this but I think the real fix was just to respect raise_on_error

**Comment by asingh16** [comment]
PR for posterity: https://dagster.phacility.com/D1943
