### ISSUE TITLE
`run_retries/max_retries` should not trigger on manually terminated jobs

### ISSUE THREAD

**Issue by mjkanji** [dagster-io/dagster#20217]
### What's the use case?

I have the following deployment settings:

```
run_retries:
  max_retries: 1
  retry_on_asset_or_op_failure: true
```

This currently starts a retry for jobs that were manually terminated. Retries should either be restricted to automated failures in the op logic by default or there should be an option to make this the default behaviour.

If a user is terminating a job manually, they probably have a good reason to do so, and it doesn't make sense for a retry to automatically trigger and alter the state of their data pipelines without the user's knowledge.

### Ideas of implementation

If a job is terminated manually, ignore the `max_retries` setting or provide an option to ignore it.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
@mjkanji the intended behavior here is that run retries should only trigger for runs that failed (status "Failure" in the UI: 
<img width="150" alt="image" src="https://github.com/dagster-io/dagster/assets/8451211/bedf7baf-11e5-410b-a93e-40da22d4346d">) not runs that were manually terminated from the Dagster UI or using the GraphQL API (status "Canceled" in the UI: 
<img width="130" alt="image" src="https://github.com/dagster-io/dagster/assets/8451211/fcbeeb4b-9547-41e1-9c88-5a9f67072e17">)

It sounds like this is different than what you're experiencing though - can you provide debug information for a run where this happened on a manually terminated run using the "Download debug information" dropdown on the runs page? 
<img width="409" alt="image" src="https://github.com/dagster-io/dagster/assets/8451211/6f61aaa6-1b33-4386-8a60-fb2c599dfac6">
Or if it's a run in Dagster Cloud you could also email support@dagsterlabs.com with a link to the run.

**Comment by gibsondan** [comment]
We identified the issue here (the pod not getting terminated cleanly in time before the process was killed, then our monitoring functionality incorrectly moving it into a failure state instead of a cancelled state, triggering a retry) - and rolled out a fix for this in the most recent cloud release. No upgrade to anything required if you're using cloud. Thanks for the report!

**Comment by tristan-ki** [comment]
@gibsondan is there a solution to this problem in OSS?

**Comment by gibsondan** [comment]
This should not be a problem on either OSS or Dagster+ - if you are seeing a problem can you file a new issue with the details of what you’re seeing?
