### ISSUE TITLE
JS errors on Google Chrome when displaying large number of assets in global lineage view.

### ISSUE THREAD

**Issue by maxfirman** [dagster-io/dagster#20284]
### Dagster version

1.6.3

### What's the issue?

In Google Chrome (Version 122.0.6261.94), displaying a large number of assets in the global lineage view hangs indefinitely with: "Rendering a large number of assets, please wait…".

Opening up Chrome Dev Tools reveals the following error [127.0.0.1-1709718868998.log](https://github.com/dagster-io/dagster/files/14508229/127.0.0.1-1709718868998.log):

`_async_to_generator.js:6 Uncaught (in promise) DOMException: Internal error opening backing store for indexedDB.open.`

Firefox does not exhibit the same error, and loads the full asset graph correctly.

The error in Chrome will go away if I reduce the number of assets to be displayed by filtering down the graph by code location / asset group / compute kind. There appears to be a maximum number of assets that can displayed without triggering the error. Going beyond this number always results in the error, irrespective of the set of assets that happen to be included by the filter selections.

### What did you expect to happen?

Asset graph should load without errors

### How to reproduce?

Try to render a large asset graph in Chrome. 

Admittedly I have only encountered this error on our project, so it is possible there is something specific to our project that causes the issue. 

If needs be, I can create a simple example project that reproduces the problem and upload it to my Github.

### Deployment type

Local

### Deployment details

The issue exists both locally and deployed via Helm.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by salazarm** [comment]
@maxfirman >If needs be, I can create a simple example project that reproduces the problem and upload it to my Github. 

Could you do this pretty please :). It will make my life much easier since I don't have a repro atm.

**Comment by salazarm** [comment]
Another question: Are you accessing the page using `http` or `https`?

**Comment by maxfirman** [comment]
@salazarm, strangely enough the issue seems to have resolved itself! My Chrome version has been updated to Version 122.0.6261.111 so I'm wondering if it was a bug in Chrome that got fixed.  Please feel free to close the issue, I can re-open if the problem recurs.
