### ISSUE TITLE
Code location versioning

### ISSUE THREAD

**Issue by nzlysenko** [dagster-io/dagster#20324]
### What's the use case?

It would be great to have a feature to provide some versioning information e.g. project version, build version for code location and show it somewhere in the Dagster UI. It allows see the current release state of the code location. At the moment we're using the dummy job definition to put the version number in it like on the screen below.
![image](https://github.com/dagster-io/dagster/assets/30044742/67f19f99-1c3b-4b46-8a9d-c3427aa14b2e)

### Ideas of implementation

We could have the property like version in the Definitions class or some environment variable which could be used during starting the code location. The version could be displayed somewhere near the code location name.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Effectively duplicates #15090

**Comment by ei-grad** [comment]
For anyone who lands here (or on #15090) and wants a stop‑gap way to attach a version string to a code location, we’ve been using a small hack based on the internal `DagsterLibraryRegistry`.

The idea is:

- Treat your code location as a Python package.
- Resolve its version via `importlib.metadata`.
- Manually register that package + version with `DagsterLibraryRegistry` when building `Definitions`.

That gives Dagster a notion of “this code location is version X.Y.Z”, even though there isn’t yet a first‑class `Definitions(version=...)` or code‑location metadata field.

**1. Package `__init__.py` – resolve the version**

```python
# my_dagster_app/__init__.py
from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("my-dagster-app")
except PackageNotFoundError:
    # Fallback for editable installs / unknown version
    __version__ = "0.0.0"
```

**2. `defs.py` – register in the Dagster library registry**

```python
# my_dagster_app/defs.py
import dagster as dg
from dagster._core.libraries import DagsterLibraryRegistry  # internal API

from my_dagster_app import __version__

# Hacky workaround for code location versioning (see #20324, #15090):
# register this app as a Dagster “library” with its version.
DagsterLibraryRegistry.register(
    "my-dagster-app",  # name to show up in the registry
    __version__,
    is_dagster_package=False,  # it's our app, not a core dagster package
)

defs = dg.Definitions(
    # ... assets / jobs / schedules / resources ...
)
```

This obviously relies on an internal API and doesn’t give you the nice UI columns requested in #15090, but it at least lets Dagster track “which version of this code location is currently loaded” in a single place until there’s a proper, supported way to attach version/metadata to code locations.
