### ISSUE TITLE
dagstermill Python 3.5 tests are intermittently failing

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2034]
I've seen this failure a few times: https://buildkite.com/dagster/dagster/builds/8777#d22d0692-565f-4be6-bb50-492d63a270cc

**Comment by natekupp** [comment]
Another example: https://buildkite.com/dagster/dagster/builds/8866#afe9b111-410b-4764-98ce-78ae43c77423

**Comment by schrockn** [comment]
https://dagster.phacility.com/D1758

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
closing this as we drop testing for 3.5
