### ISSUE TITLE
Multipartitions with more than two dimensions

### ISSUE THREAD

**Issue by clement-uspace** [dagster-io/dagster#20356]
### What's the use case?

Sometimes a natural partition of an asset would involve more than two dimensions. Having this capability in the MultiPartition would avoid having to create separate assets manually for the other levels.

### Ideas of implementation

A similar interface to the existing one, but not limited to two dimensions. However I'm not sure of the consequences e.g. in the UI.

### Additional information

This feature request comes from [this discussion](https://github.com/dagster-io/dagster/discussions/20283).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
I think this may fall under the ambit of this issue: #14228 it's worth documenting your use case in its comments to collate!

**Comment by clement-uspace** [comment]
yes it does seem that it would be a good fit. I'll answer there.
