### ISSUE TITLE
[UI] Keyboard shortcut or permanent button to reload code location

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#20357]
### What's the use case?

I find it cumbersome to navegate to the deployment page or the global asset dag just to reload the code.

For example, I'm looking at the dag for one of my jobs - I change the code - and I'd like to have a quick way to see the changes. 

### Ideas of implementation

Keyboard shortcut, button, or option somewhere to reload code location

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
When viewing the job, next to the job name in the header, you should see a tag with the name of the code location. There should be a reload button in that tag, which will reload that job's code location. Does that work?

<img width="682" alt="Screenshot 2024-03-12 at 14 12 19" src="https://github.com/dagster-io/dagster/assets/2823852/1945a0ad-ebfd-40e8-8077-ae95c8a9d772">

**Comment by mkleinbort-ic** [comment]
Ok, that's fine - I think there could be a bit more consistency:

Currently the "reload definitions" is: 

-> On the top right when on the asset dag
-> On the top middle when on a job's dag
-> Implicit when running "re-execute" on a run page

But it does address my ask
