### ISSUE TITLE
Improve graphql error reporting

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2037]
Right now we get error reports like this:

<img width="418" alt="Screenshot 2019-12-28 08 51 23" src="https://user-images.githubusercontent.com/28738937/71546864-45e4d000-294f-11ea-9bfd-a26f10c22a23.png">

Not sufficient for remote debugging.

**Comment by mgasner** [comment]
We should now be getting more in the console log

**Comment by schrockn** [comment]
We don't in this instance. We let the exception escape through resolve_environmentConfigYaml and there is no console logging or useful error information
