### ISSUE TITLE
Auto-Materialization is not working for a Dagster-native asset that depends on an external asset in Dagster >= 1.6.7

### ISSUE THREAD

**Issue by chximn** [dagster-io/dagster#20396]
### Dagster version

1.6.7

### What's the issue?

When using versions `>=1.6.7` of Dagster, auto-materialization doesn't seem to function as expected, or at least, as it was functioning before version `1.6.7`. Dagster-native assets are not materialized automatically when the upstream external asset is updated, i.e. an external materialization event was reported.

In the screenshot below, Dagster picks up the upstream asset materialization event and marks the downstream asset as "not fresh"; however, it doesn't auto-materialize it.
![Screenshot Dagster 1.6.7](https://github.com/dagster-io/dagster/assets/35144548/2f586eaa-0880-4c33-a1d8-ab23dfbf79f6)

This was not the case for versions previous to `1.6.7`, which does trigger auto-materialization of the downstream asset.
![Screenshot 2024-03-11 090848](https://github.com/dagster-io/dagster/assets/35144548/a728f1a8-5ab0-4ef6-a8f7-3e312118a99c)

Additionally, the external asset looks different in the UI (dashed borders in `>=1.6.7`), similar to "Source Assets".

### What did you expect to happen?

The auto-materialization policy would trigger the materialization of the downstream Dagster-native asset when Dagster receives a materialization report for the upstream external asset.

### How to reproduce?

1. Create a Dagster-native asset with an external asset dependency, similar to the following code
```python
external_upstream_asset = external_asset_from_spec(AssetSpec("external_upstream_asset"))

@asset(
    deps=[external_upstream_asset],
    auto_materialize_policy=AutoMaterializePolicy.eager()
)
def downstream_asset():
    ...
```
2. Make sure auto-materialization is enabled
3. Report materialization event externally using the REST API: [https://docs.dagster.io/concepts/assets/external-assets#dagster-oss-1](https://docs.dagster.io/concepts/assets/external-assets#dagster-oss-1)

### Deployment type

Docker Compose

### Additional information

I have tested this on versions: `1.6.6`, `1.6.7`, and `1.6.9`

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ammerzon** [comment]
@garethbrickman, do you know if this behavior is a bug or an intentional change in the newer Dagster versions?

**Comment by garethbrickman** [comment]
@ammerzon This does seem like a regression bug, however [External Assets are an experimental API](https://docs.dagster.io/concepts/assets/external-assets#external-assets-experimental) so breaking changes between versions are explicitly possible.

**Comment by ammerzon** [comment]
> @ammerzon This does seem like a regression bug, however [External AssetsI](https://docs.dagster.io/concepts/assets/external-assets#external-assets-experimental) and [Auto-Materialization](https://docs.dagster.io/concepts/assets/asset-auto-execution#auto-materializing-assets-) are Experimental APIs so breaking changes between versions are explicitly possible.

@garethbrickman Thank you for the quick clarification. It's already good to know that this is instead a bug rather than a conscious decision not to support this anymore. If you need more information, please just reach out 😁

**Comment by ammerzon** [comment]
Even though they are using source assets I think this is related to https://github.com/dagster-io/dagster/issues/19207

**Comment by chximn** [comment]
This should now work fine with Automation Conditions.
