### ISSUE TITLE
dagster_airflow_docker_operator_pipeline image is now hardcoded; reevaluate test structure

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2041]
I changed dagster_airflow_docker_operator_pipeline to use get_dagster_docker_image for all images rather than have image be parameterized on the Test class in https://dagster.phacility.com/D1756.

I find this pattern of class-based fixtures and eagerly evaluating all variables at import time to be pretty problematic. It makes it harder to isolate tests from eachother. In this case, I was unable to run a purely local airflow unit test without running all the tests that require the context that BK spins up.

**Comment by natekupp** [comment]
hey @catherinewu assigning to you since you're already looking at Airflow test stuff

**Comment by mgasner** [comment]
these tests have been substantially cleaned up
