### ISSUE TITLE
Invocations list reports different usage list based on context

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2043]
This may be a product decision rather than a bug. Worth discussing. However this doesn't seem intuitive.

For example same solid definition, different invocation list. When selecting the solid within the context of a composite solid, it only shows the invocations within the composite solid

![Screenshot 2019-12-31 09 26 04](https://user-images.githubusercontent.com/28738937/71628996-cefa4200-2baf-11ea-83d4-50667583ed53.png)

However in the solid viewer it shows all invocations

![Screenshot 2019-12-31 09 25 54](https://user-images.githubusercontent.com/28738937/71629009-e0434e80-2baf-11ea-9558-1ac115b3a390.png)

Broadly I think that we should be showing the same information in both cases.

**Comment by mgasner** [comment]
yikes

**Comment by hellendag** [comment]
This looks okay to me now.
