### ISSUE TITLE
Incorrect Status of paritioned Assets with upstream Asset modified

### ISSUE THREAD

**Issue by anotine10** [dagster-io/dagster#20442]
### Dagster version

dagster, version 1.6.8

### What's the issue?

**Context**:
I have a sequential of 4 dependent assets (with static partition) which I all materialised correctly once.

**Actions:**
- Then I manually re-materialized the 2nd asset with some new configuration values. The Data version and Code version has changed correctly

**Results:**
- However in the UI, i do not see any changes in the status of the 3rd  neither 4rth asset. I would have expected a change in Status as up-stream asset has changed! 
- If i select (click)  all these 4 assets, and click on the option "materialize all changed and missing assets", the popup says "All assets are up to date" which is not true
- If i click on the 2rd asset, the green circle stays. AT this level, it does not give information about the the fact that this asset need to be updated
- If i click on the partition, it adds a new orange icon "upstream data", which is correct but i would have expected this information earlier in the flow.

### What did you expect to happen?

If i changed one partition of the asset, i would expect some change in status in the downstream asset being visible, (not only when i select one partition). Is it the expected behaviour? 
The most undesired behaviour is the following: Surely, i would expect that clicking on the "materialize changed and missing", it notifies the partition to update, and update it.

### How to reproduce?

- Create 2 assets: A and B. B depends on A. A has some configuration. Both Asset are Static partitioned. Use one value in the partition
- materialize correctly the 2 assets
- Change one value from the configuration of A, and materialize it (i have done it with launchpad UI)
- Observe the status of B

I have created a toy example showing the difference between how it shows for 2 assets with partition and 2 assets without partition. The one without partition works good
![Screenshot 2024-03-13 at 00 52 16](https://github.com/dagster-io/dagster/assets/5657376/300afe9a-71a7-41ff-80b1-d02d731ff131)

```

class TestConfig(Config):
    num: int
@asset
def testA(config: TestConfig):
    print(config.num)

@asset
def testB(testA):
    print("TestB")

raw_test_partition = StaticPartitionsDefinition(
    ["test"]
)

@asset(partitions_def=raw_test_partition)
def testA_partitioned(config: TestConfig):
    print(config.num)
    return 1

@asset(partitions_def=raw_test_partition)
def testB_partitioned(testA_partitioned):
    print("TestB partitioned")
```
### Deployment type

Local

### Deployment details

Not much customisation

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
I believe this duplicates #9374

**Comment by anotine10** [comment]
Oh, you re right! 
  Also, as an the user ([mkleinbort-ic](https://github.com/mkleinbort-ic))  have just added into the ticket,  it is not just about the UI, but also that the button "materialize stale or missing" does not catch these partitions change!

**Comment by garethbrickman** [comment]
Gotcha, please add your feedback into #9374 and I'll raise it internally for re-review 👍
