### ISSUE TITLE
[dagster-k8s] test instability

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2045]

**Comment by alangenfeld** [comment]
https://buildkite.com/dagster/dagster/builds/8957#c7a9092e-e54f-414b-8a36-9a418a17f16a

**Comment by prha** [comment]
Also, saw https://buildkite.com/dagster/dagster/builds/8964#f638abbc-220a-4e72-b160-b4bc964aa9e4 over the weekend, so not limited to py27

**Comment by natekupp** [comment]
I think this is likely caused by https://dagster.phacility.com/D1762 due to kind needing to pull much larger images

**Comment by schrockn** [comment]
i agree. i just sent this up for the airflow tests

https://dagster.phacility.com/D1786

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by schrockn** [comment]
In my view the correct fix is to have airflow tests and like not pull the integration image at all. Instead they should testing trivial hello world pipelines with minimal dependencies

**Comment by schrockn** [comment]
I did not fix this in K8sRunLauncher as I do not know the API to change without using the kubernetes module's  PodLauncher. D1786 only fixes in the airflow tests
