### ISSUE TITLE
Ability to use other S3 compatible object storage

### ISSUE THREAD

**Issue by yamrzou** [dagster-io/dagster#2047]
We use our own S3 compatible private cloud setup (we are using https://www.openio.io/). 
To be able to use it as a storage, we need to specify a `region` and and `endpoint` for the s3 resource.

**Comment by schrockn** [comment]
Your PR definitely works and thank you!

You actually may want to consider a different solution. If you don't want to have to specify the same config everywhere (or you will need further custom behavior) you may want to consider creating your own custom resource fo openio.io

```
@resource
def open_io_s3_resource(_):
   return S3Resource(create_s3_session_your_way())
```

In which case you will have total control over your s3 session creation and you won't be dependent on upstream PRs to move forward.

If you are in our slack please say hi! We would love to hear more about how you are using the system.

**Comment by yamrzou** [comment]
Thanks, I haven't thought of that !

I'm just starting to look around to see if this can be a fit for our use case. 
It looks promising and I love the the abstractions being created to ease the the development.

Will definitely connect via slack in the near future.
