### ISSUE TITLE
Auto materialize triggers different assets groups in the same run

### ISSUE THREAD

**Issue by chrishiste** [dagster-io/dagster#20507]
### Dagster version

1.6.8

### What's the issue?

Hello, I ran into a snag with our auto materialize setup. When several assets trigger at the same time, they all get chucked into one big run. It's a bit of a mess to sift through in the UI since everything's jumbled together, and it also messes with how we manage our run's concurrency—it's all or nothing right now.

**TL;DR**: Would be super helpful to have a way to split these simultaneous triggers into their own runs based on asset groups. It'd make our lives easier for monitoring and managing resources.

Could we add a config option to make this happen? It'd clear up the dashboard and let us fine-tune the concurrency for better efficiency.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @chrishiste  - you can use `AutoMaterializeSensorDefinition`s to execute them independently:

```python
from dagster import AutoMaterializeSensorDefinition

group1_auto_materialize_sensor = AutoMaterializeSensorDefinition(
    "group1_sensor", asset_selection=AssetSelection.groups("group1")
)

group2_auto_materialize_sensor = AutoMaterializeSensorDefinition(
    "group1_sensor", asset_selection=AssetSelection.groups("group1")
)

defs = Definitions(sensors=[group1_auto_materialize_sensor, group2_auto_materialize_sensor])
```

cc @gibsondan to correct me if I got any of this wrong

**Comment by gibsondan** [comment]
That is correct, but I would recommend upgrading to 1.6.9 or later before using AutoMaterializeSensorDefinition as there were some fixes related to them in that release.

**Comment by chrishiste** [comment]
@sryza awesome :)

Currently I don't have anything setup for auto materialization, I just turned it on globally. How will a dedicated sensor cohabit with the global auto materialization? Do I need to turn that off and create specific sensors for all my groups?

**Comment by gibsondan** [comment]
@chrishiste We should have mentioned that you enable this feature via your dagster.yaml as well:

```
auto_materialize:
  use_sensors: true
```

or if you're using the Dagster helm chart:
```
additionalInstanceConfig:
  auto_materialize:
    use_sensors: true
```

Docs for all of this coming soon!

**Comment by chrishiste** [comment]
@gibsondan that makes sense. I will wait for the docs to implement thanks.
