### ISSUE TITLE
Animate the recent attempt bubbles to more information dense

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#2057]
**Observation**

Currently, the bubbles under "recent attempt" are not great at conveying information change in our pipeline runs. This makes it hard for me to know if a queued up run actually ran or not, and it's unclear what side the "most recent run" is on (left most side or right most side). 

**Proposal**

It would be really nice if we could have more animated coloring to signify the enqueuing of a pipeline, the execution of the pipeline, and the success/failure of the pipeline run. 

Currently, things get lost in a sea of green/red, and the hover over for recent just shows a pipeline run uuid which is not very useful.

**Comment by helloworld** [comment]
This is a great point - I'll try to brainstorm a better view for this and pass ideas by you
