### ISSUE TITLE
Filter /assets based on code location

### ISSUE THREAD

**Issue by dsgibbons** [dagster-io/dagster#20580]
### What's the use case?

We have many code servers running in a single Dagster deployment. Under `/overview` in the UI, we can filter jobs, schedules etc. based on code locations. However, this functionality is not present in the list view under `/assets` (it is available however when "View global asset lineage" is clicked). 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mattfysh** [comment]
@garethbrickman I just checked the UI and this looks to be completed, so you might be able to close this issue? I also wanted to ask - can we add a link to the Deployment page to open the Lineage view with a code location filter applied? Currently you need to "View global asset lineage" first, then apply the filter. Global assets might be in the thousands, so the step prior to filtering can cause the UI to become sluggish

**Comment by garethbrickman** [comment]
Thanks @mattfysh! Please open a new issue for your request and I'll get it to our UI team 👍

**Comment by mattfysh** [comment]
opened https://github.com/dagster-io/dagster/issues/24732
