### ISSUE TITLE
No longer support for non-english characters in asset names

### ISSUE THREAD

**Issue by C0DK** [dagster-io/dagster#20586]
### Dagster version

1.6.11

### What's the issue?

Previously we have utilized `æ` in our asset names, (which is a Danish letter) - this has never been a problem before. 

Today when upgrading from `1.6.4` to `1.6.11` this is no longer the case, and we get a:

```
kredslob_dagster:dagster._core.errors.DagsterInvalidDefinitionError: "anlægsnummer" is not a valid name in Dagster. Names must be in regex ^[A-Za-z0-9_]+$.
```

In theory one could argue 'why don't you just rename your asset' - but we've current set up our IOManager to utilize the asset name as a way of resolving the underlying data, and this is a third-party source asset, so we cannot trivially rename that; our best bet would be to create a hacky solution (utilizing metadata) that enables resolution of an asset name in this case. 

### What did you expect to happen?

it to work as it used to

### How to reproduce?

```python
my_asset = SourceAsset(key=["en", "fæst"])
```

Above would probably raise the error

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @C0DK - I believe we've had this limitation in non-source assets for quite a long time, and allowing these characters in source assets was unfortunately an accidental miss. Have you been able to use these characters in materializable assets?

**Comment by C0DK** [comment]
Probably not now that you mention it. In the meantime I did find an alternative solution (an optional metadata field that takes precedence). In that case this bug can probably be closed. 😅

**Comment by sryza** [comment]
Glad you were able to work something out!
