### ISSUE TITLE
Sensor tick delay

### ISSUE THREAD

**Issue by gasgallo** [dagster-io/dagster#20618]
### Dagster version

1.5.12

### What's the issue?

After k8s maintenance recreated some of my node pools, dagster sensor ticks don't respect their configured interval anymore. The ticks are delayed and kind of random, most of the times they happen with a delay between 8-10 minutes.

For example:
- my sensor that is supposed to evaluate every 30s is, instead, evaluated every 8-10mins
- my sensor that is supposed to evaluate every 10min is, instead, evaluated every 18-20mins

### What did you expect to happen?

Sensor ticks are evaluated accordingly to configured interval.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gasgallo** [comment]
I found out that the issue was caused by a lack of CPU resources. Once I freed up some CPU, all the sensors went back to evaluating their ticks with the expected frequency.

I'm not sure if this is the expected behaviour. In case that it is, feel free to close.

**Comment by mlarose** [comment]
Hi @gasgallo, 

cpu starvation on the code location pod will indeed cause this type of issues. I will close for now, but if you have new information feel free to reopen!
