### ISSUE TITLE
Dagit playground rendering issues due to yaml.dump

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2063]
The built-in `yaml.dump` method inserts line breaks into long string values. For example

```
➜  python
Python 3.6.8 (default, Jul  8 2019, 11:53:15)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.dump({"key": "this is a really long value value that will have a line break in the resulting yaml one two three four five six seven"})
'{key: this is a really long value value that will have a line break in the resulting\n    yaml one two three four five six seven}\n'
```

Notice the extra line break after the word `resulting`. This causes a rendering issue in Dagit, where a value will be split across two lines. 

For example, if we have the pipeline:

```
@solid(config={"key": str})
def hello_world(context):
    context.log.info('Hello, world!')


@pipeline(
    preset_defs=[
        PresetDefinition(
            "test",
            {
                'solids': {
                    "hello_world": {
                        "config": {
                            "key": "this is a really long value value that will have a line break in the resulting yaml one two three four five six seven"
                        }
                    }
                }
            },
        )
    ]
)
def hello_world_pipeline():
    hello_world()
```

It will look like this in Dagit:

![image](https://user-images.githubusercontent.com/3893054/72466362-98b2ea00-378d-11ea-94f4-7ef860adae1f.png)

We should consider passing a `width` parameter to `yaml.dump` to prevent the newlines.

**Comment by helloworld** [comment]
As @prha mentioned, you can argue that we shouldn't mess with the default line-width of yaml documents produced by `yaml.dump` and that users might expect this wrapping. However, it was confusing to me when I saw line breaks in long s3 paths or cli commands.

**Comment by catherinewu** [comment]
closing issue as it does not seem actionable. feel free to re-open if there's a proposed fix?
