### ISSUE TITLE
Incorrect rendering of `Nothing` typed dependencies in dagit when using kwargs

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2065]
When we use kwargs in solid calls in pipeline definitions, we get an incorrect rendering of data dependencies in dagit. 

Given the following set of solids:

```
@solid
def order_1(_):
    pass


@solid
def order_2(_):
    pass


@solid
def one(_):
    return 1


@solid(
    input_defs=[
        InputDefinition("num", Int),
        InputDefinition("order_dependency_1", Nothing),
        InputDefinition("order_dependency_2", Nothing),
    ]
)
def process(_, num):
    pass
```

### ✅ Not using kwargs:

```
@pipeline
def simple_pipeline():
    A = order_1()
    B = order_2()
    process(one(), A, B)
```

Renders as:

![image](https://user-images.githubusercontent.com/3893054/72489269-670b4480-37c8-11ea-820a-261214a37ace.png)

### ❌ Using kwargs:

```
@pipeline
def simple_pipeline():
    A = order_1()
    B = order_2()
    process(A, B, num=one())
```

Renders as:

![image](https://user-images.githubusercontent.com/3893054/72489305-80ac8c00-37c8-11ea-9c7b-3571d3845bb0.png)

### ✅ Not using kwargs but wrapping `Nothing` in list:

```
@solid(
    input_defs=[InputDefinition("num", Int), InputDefinition("order_dependencies", Nothing),]
)
def process(_, num):
    pass


@pipeline
def simple_pipeline():
    A = order_1()
    B = order_2()
    process(one(), [A, B])
```

![image](https://user-images.githubusercontent.com/3893054/72489466-f9abe380-37c8-11ea-824b-99d1d718266c.png)

### ❌ Using kwargs but wrap `Nothing` inputs in list:

```
@solid(
    input_defs=[InputDefinition("num", Int), InputDefinition("order_dependencies", Nothing),]
)
def process(_, num):
    pass


@pipeline
def simple_pipeline():
    A = order_1()
    B = order_2()
    process([A, B], num=one())
```

![image](https://user-images.githubusercontent.com/3893054/72489393-c79a8180-37c8-11ea-8757-6785e947ee52.png)

**Comment by alangenfeld** [comment]
D1853 resolves this assuming we go this direction
