### ISSUE TITLE
Try to open global asset lineage results in TypeError: Cannot read properties of undefined (reading 'height')

### ISSUE THREAD

**Issue by ajohnson5** [dagster-io/dagster#20655]
### Dagster version

1.6.9

### What's the issue?

I am unable to view the global asset lineage - This is for our cloud deployment and also when I try run dagster locally. Other people are able to view the global asset lineage. I am using a Windows machine. Note that I am able to look at the asset lineage of specific groups.

![image](https://github.com/dagster-io/dagster/assets/99501368/9b67436a-1fe0-4d30-8e34-d794ac742bd6)

I have set up a different project locally with a smaller dag which I am able to view so the dag size maybe impacting it but that does not explain why other people in my team can still view the lineage.

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by salazarm** [comment]
Hello, we've added a fix in 1.7.1

**Comment by ajohnson5** [comment]
> Hello, we've added a fix in 1.7.1

Thanks, I appreciate the quick turn around!
