### ISSUE TITLE
DagsterDbtTranslator.get_asset_key / get_group_name should be non-static

### ISSUE THREAD

**Issue by alex-statsig** [dagster-io/dagster#20670]
### What's the issue or suggestion?

`DagsterDbtTranslator.get_asset_key` and `DagsterDbtTranslator.get_group_name` are both marked as `@classmethod`, but every callsite seems to invoke them non-statically. This is preventing a safe non-classmethod version of these functions in a custom subclass.

### Additional information

Noticed `DagsterDbtTranslator.get_asset_key` and `DagsterDbtTranslator.get_group_name` are both marked as `@classmethod`, which makes sense since the current implementations dont use any instance properties. However, every callsite seems to invoke them non-statically.

In particular, the problem is that my usage currently involves using instance properties on a custom translator to easily make variants of it (with different key_prefix which affects get_asset_key). However, I currently can't know for sure whether dagster will add a static invocation of this method or if I can assume it will still be called on an instance.

Also there are probably other cases of this, these were just the ones we noted as we added better typechecking to our usage and realized this possible error.

Wasn't sure where to file this typing issue (not really a bug or documentation issue, but this felt closest to right). Happy to contribute a PR to address this if its agreed that the change should be made.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Makes sense. https://github.com/dagster-io/dagster/pull/20683 will resolve.
