### ISSUE TITLE
Unhelpful type hinting in config editor

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2068]
<img width="655" alt="Screen Shot 2020-01-16 at 10 56 27 AM" src="https://user-images.githubusercontent.com/427016/72554130-f0fdf080-384e-11ea-9546-b511ebd7b3ba.png">

@schrockn I think this might be a consequence of recent type system changes

**Comment by mgasner** [comment]
<img width="669" alt="Screen Shot 2020-01-16 at 10 57 44 AM" src="https://user-images.githubusercontent.com/427016/72554192-0bd06500-384f-11ea-9ef0-e3249617a009.png">

**Comment by schrockn** [comment]
Is this on master? I believe https://dagster.phacility.com/D1828 should have resolved this.

Also what pipeline is this?

**Comment by mgasner** [comment]
this is resolved on master
