### ISSUE TITLE
azureBlobComputeLogManager not working

### ISSUE THREAD

**Issue by sverbruggen** [dagster-io/dagster#20706]
### Dagster version

1.6.10

### What's the issue?

The azureBlobComputeLogManager is not working, either with a DefaultAzureCredential (e.g. with service principal credentials) configuration or with a secretKey configuration. Both give a graphql error when trying to see stderr/stdout from the dagster UI. The logs do get uploaded to the storage account in both (DefaultAzureCredential and secretKey) cases. They are just not visible from the UI.

### What did you expect to happen?

I expected to see the logs

### How to reproduce?

create an azure storage account, configure the dagster helm chart to use an azureBlobComputeLogManager. Attach the 3 environment variables that the DefaultAzureCredential requires to the webserver, dagster daemon and job pods. Deploy it to k8s, run any task and try to see its stderr/stdout output.

### Deployment type

Dagster Helm chart

### Deployment details

Azure k8s, azure storage account, azure service principal

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sverbruggen** [comment]
![Stack Trace](https://github.com/dagster-io/dagster/assets/27513235/096f62f0-24bc-4d20-bf80-06e96afbf300)

**Comment by HynekBlaha** [comment]
I have similar issue on 1.7.0 (trying to set it up for the first time).

```
computeLogManager:
  type: AzureBlobComputeLogManager
  config:
    azureBlobComputeLogManager:
      storageAccount: <REDACTED>
      container: dagster-logs
      defaultAzureCredential:
        exclude_environment_credential: true
      localDir: "/tmp/dagster_compute_logs"
      uploadInterval: 30
```

I also had to comment this section:
```
{{/*  secret_key: {{ include "stringSource" $azureBlobComputeLogManagerConfig.secretKey }}*/}}
```
in dagster/templates/helpers/instance _compute-log-manager.tpl, otherwise I would get this error when while starting a job.
<img width="1413" alt="Screenshot 2024-04-11 at 20 34 34" src="https://github.com/dagster-io/dagster/assets/26007903/57c949de-5888-43c4-b0e3-56864f2067cb">

I confirm, the log files are being stored to AzureBlob Container, in my case I get different error when trying to load the stdout/stderr.

<img width="1415" alt="Screenshot 2024-04-11 at 20 26 59" src="https://github.com/dagster-io/dagster/assets/26007903/36c7da02-f2c1-4bcd-a39b-2a1ee8eb18a5">

**Comment by ion-elgreco** [comment]
@HynekBlaha yes you are running into the issue that the log manager implicitly assumes an account key.

**Comment by bvallier** [comment]
Running into something similar on my end trying to interact with Azure Storage Account:

```
dagster._core.errors.DagsterSubprocessError: During multiprocess execution errors occurred in child processes:
In process 28980: dagster._core.errors.DagsterInvalidConfigError: Errors whilst loading configuration for {'storage_account': <dagster._config.source.StringSourceType object at 
0x000001810EA8E160>, 'container': <dagster._config.source.StringSourceType object at 0x000001810EA8E160>, 'secret_key': Field(<dagster._config.source.StringSourceType object at 
0x000001810EA8E160>, default=@, is_required=False), 'default_azure_credential': Field(<dagster._config.config_type.Noneable object at 0x000001812A1AEFA0>, default=None, is_required=False), 'local_dir': Field(<dagster._config.source.StringSourceType object at 0x000001810EA8E160>, default=@, is_required=False), 'prefix': Field(<dagster._config.source.StringSourceType object at 0x000001810EA8E160>, default=dagster, is_required=False), 'upload_interval': Field(<dagster._config.config_type.Noneable object at 0x000001812A1AE280>, default=None, is_required=False)}.
    Error 1: Received unexpected config entry "credential" at the root. Expected: "{ container: (String | { env: String }) default_azure_credential?: { }? local_dir?: (String | 
{ env: String }) prefix?: (String | { env: String }) secret_key?: (String | { env: String }) storage_account: (String | { env: String }) upload_interval?: Int? }".
 
Stack Trace:
  File "C:\Users\e0416319\AppData\Roaming\Python\Python39\site-packages\dagster\_core\executor\child_process_executor.py", line 78, in _execute_command_in_child_process
    for step_event in command.execute():
  File "C:\Users\e0416319\AppData\Roaming\Python\Python39\site-packages\dagster\_core\executor\multiprocess.py", line 97, in execute
    yield from execute_plan_iterator(
  File "C:\Users\e0416319\AppData\Roaming\Python\Python39\site-packages\dagster\_core\execution\api.py", line 874, in __iter__
    yield from self.iterator(
  File "C:\Users\e0416319\AppData\Roaming\Python\Python39\site-packages\dagster\_core\execution\plan\execute_plan.py", line 39, in inner_plan_execution_iterator
    compute_log_manager = job_context.instance.compute_log_manager
  File "C:\Users\e0416319\AppData\Roaming\Python\Python39\site-packages\dagster\_core\instance\__init__.py", line 817, in compute_log_manager
    compute_log_manager = cast(InstanceRef, self._ref).compute_log_manager
  File "C:\Users\e0416319\AppData\Roaming\Python\Python39\site-packages\dagster\_core\instance\ref.py", line 533, in compute_log_manager
    return self.compute_logs_data.rehydrate(as_type=ComputeLogManager)
  File "C:\Users\e0416319\AppData\Roaming\Python\Python39\site-packages\dagster\_serdes\config_class.py", line 125, in rehydrate
    raise DagsterInvalidConfigError(
 
Stack Trace:
  File "C:\Users\e0416319\AppData\Roaming\Python\Python39\site-packages\dagster\_core\execution\api.py", line 760, in job_execution_iterator
    for event in job_context.executor.execute(job_context, execution_plan):
  File "C:\Users\e0416319\AppData\Roaming\Python\Python39\site-packages\dagster\_core\executor\multiprocess.py", line 311, in execute
    raise DagsterSubprocessError(
```

I have something like this in my dagster.yaml file:

```
compute_logs:
  module: dagster_azure.blob.compute_log_manager
  class: AzureBlobComputeLogManager
  config:
    storage_account: my-storage-account
    container: my-container
    credential: sas-token-or-secret-key
    default_azure_credential:
      exclude_environment_credential: true
    prefix: "dagster-test-"
    local_dir: "/tmp/cool"
    upload_interval: 30
```

per docs: https://docs.dagster.io/_apidocs/libraries/dagster-azure

I then just specify the io_manager_key in the asset decorator for the asset i'm trying to materialize with the context from the adls2_io_manager

**Comment by ion-elgreco** [comment]
I've resolved it by overriding some methods in azureBlobComputeLogManager class

**Comment by bvallier** [comment]
did you manage to submit a PR?
