### ISSUE TITLE
Consider using Gitpod

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2071]
This is an unbelievably slick service: https://github.com/marketplace/gitpod-io

> It launches a complete dev environment for any GitHub project, by simply prefixing the GitHub URL with gitpod.io/#.

It launches a full VSCode dev environment in the browser with the repository code checked out. 

What we could do is package up our hello cereal tutorial into it's own repository with a Dockerfile that installs dagster + dagit. 

Then, we could link `gitpod.io/#the_cereal_tutorial_repo` in our docs, giving users an instant and free way to try out dagster and dagit. It even supports connecting to open ports through the URL it gives you, so we can actually open dagit as well.

**Comment by helloworld** [comment]
Also, it's completely free

**Comment by natekupp** [comment]
@helloworld we're using gitpod now, right? can we close?
