### ISSUE TITLE
Handling of job timeout error

### ISSUE THREAD

**Issue by Auric-Manteo** [dagster-io/dagster#20729]
### Dagster version

1.6.8

### What's the issue?

When enabling run monitoring and a job times out it fails silently instead of triggering the failure hook.
The timeout is set on the job level:
    
    @job(tags={"dagster/max_runtime": 10})
    def my_job(): ...

### What did you expect to happen?

That an exception is triggered that I can handle to report job failures triggered by timeouts to Slack.

### How to reproduce?

Set up run monitoring and a job with a short timeout and a failure hook that logs something to the console. 
The poll cycle for run monitoring needs to be short as well.
Then use a sleep statement or similar inside of the job to wait until it fails.

### Deployment type

Docker Compose

### Additional information

Slack conversation: https://dagster.slack.com/archives/C01U954MEER/p1711094275857849

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
Hi @Auric-Manteo  the issue here is that hooks are applied to each op in a job, not the job itself. And the timeout monitoring sends a job level event, not an op level event. From the [docs](https://docs.dagster.io/concepts/ops-jobs-graphs/op-hooks#-job-level-hooks):

```
When you add a hook to a job, the hook will be added to every op in the job individually. The hook does not track job-scoped events and only tracks op-level success or failure events.
```

You could set up a run failure sensor to catch these job level events https://docs.dagster.io/concepts/partitions-schedules-sensors/sensors#run-failure-sensor

**Comment by Auric-Manteo** [comment]
Hi @jamiedemaria,
Thanks for your answer!
I tried set up a job monitor according to your suggestion but it does not catch the timeout errors.
It works fine for normal exceptions, but when I let my job timeout or `raise DagsterExecutionInterruptedError('foobar')` the sensor is not triggered. I started a new thread here to make sure I am not doing anything obvious wrong:
https://dagster.slack.com/archives/C01U954MEER/p1712155587091169

**Comment by Auric-Manteo** [comment]
Hi @jamiedemaria,
I must have made a mistake afterall since using the failure sensor works now.
I think a reference to a complete example in the docs would have helped a lot.
In retrospect it seems obvious, but I didn't see any of the examples registering the sensor with a `Definition` plus I needed to add paranthesis to the sensor decorators, which you don't need to do for the ops decorators.
Thanks!
