### ISSUE TITLE
Consider using Pulumi for helm charts

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2072]
Pulumi has a resource provider for k8s. We could write our helm chart in Pulumi and generate the resulting yaml on push, letting us write Typescript with extremely helpful autocomplete and type checking instead of raw YAML. 

https://github.com/pulumi/pulumi-kubernetes

**Comment by alangenfeld** [comment]
For the helm chart we author to be useful - it needs to be in a template form so that users can override various values for their specific deployment. It's not clear to me how we could use pulumi to generate template yaml

**Comment by mgasner** [comment]
I think this is a nonstarter for the reason @alangenfeld gives above.
