### ISSUE TITLE
Resource key for io_manager not found, despite being defined in resources

### ISSUE THREAD

**Issue by mattfysh** [dagster-io/dagster#20728]
### Dagster version

dagster, version 1.6.13

### What's the issue?

I receive this error:

```
dagster._core.errors.DagsterInvalidDefinitionError: io manager with key 'xyz' 
required by output 'result' of op 'iris_dataset'' was not provided. 
Please provide a IOManagerDefinition to key 'xyz', 
or change the required key to one of the following keys 
which points to an IOManagerDefinition: ['io_manager']
```

### What did you expect to happen?

I expected the asset to find the defined io_manager resource by matching the resource key, however it was unable to do so

The only current workaround I have for now is to instead define the io_manager inline using `@asset(io_manager_def=DeltaLakePandasIOManager(...))`

### How to reproduce?

```
import pandas as pd
from dagster_deltalake import LocalConfig
from dagster_deltalake_pandas import DeltaLakePandasIOManager

from dagster import Definitions, asset


@asset(io_manager_key="xyz")
def iris_dataset() -> pd.DataFrame:
    return pd.DataFrame()


defs = Definitions(
    assets=[iris_dataset],
    resources={
        "xyz": DeltaLakePandasIOManager(
            root_uri="/Users/matt/deltalake",
            storage_options=LocalConfig(),
            schema="IRIS",
        )
    },
)
```

### Deployment type

Local

### Deployment details

im new so I just followed the getting started guide to scaffold the `my-dagster-project` layout

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
hey @mattfysh how are you materializing your asset (via the UI, CLI, some other way)? I was able to successfully run this code snippet form the UI so I suspect there is something with how the asset is being materialized that is the issue

**Comment by mattfysh** [comment]
hi @jamiedemaria thanks for replying

this is the bare minimum isolation: https://github.com/mattfysh/dagbug

but you can also reproduce the issue using the assets.py file from the deltalake tutorial: https://docs.dagster.io/integrations/deltalake/using-deltalake-with-dagster#completed-code-example

**Comment by mattfysh** [comment]
my bad, I thought the code from the linked tutorial was meant to go into assets.py when in fact it should have been in __init__.py - 🙏 sorry for the trouble, I'll close this
