### ISSUE TITLE
Event metadata cards do not handle long strings

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2074]
probably just wrap text?

**Comment by schrockn** [comment]
<img width="1639" alt="Screenshot 2020-01-21 17 33 28" src="https://user-images.githubusercontent.com/28738937/72824414-106b9380-3c2a-11ea-888a-b3041e00e49f.png">

screenshot for context

**Comment by yuhan** [comment]
Can't repo -- it may have been fixed as we moved to the new layout. Plz reopen if you hit it again
