### ISSUE TITLE
load_asset_checks_from_package_module() seems to be broken after ugrading

### ISSUE THREAD

**Issue by somiandras** [dagster-io/dagster#20752]
### Dagster version

1.6.13

### What's the issue?

After upgrading to 1.6.13 from 1.6.9 our user code container fails to start up with `dagster._core.errors.DagsterInvalidDefinitionError: Duplicate asset check key` error. 

We were just getting started with Asset Checks, so the code location contains only 3 of them, all with obviously unique name. I tried removing the asset checks one by one from the code, but it keeps failing even with a single available asset check.

We define asset checks in the same files as the related asset and we load them to our definitions via `load_asset_checks_from_package_module()`. Importing the checks directly from their module works.

### What did you expect to happen?

Asset checks keep working after upgrading with `load_asset_checks_from_package_module()`

### How to reproduce?

The only thing we changed is upgrading to 1.6.13 from 1.6.9.

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
Yeah understandable that it's hard. We don't have more logging at this point but I'm looking at adding some to help track this down.

I'm curious on your side- I assume you're using `load_assets_from_package_module` along with `load_asset_checks_from_package_module`? Does the error remain if you remove `load_assets_from_package_module` so that you're only putting checks in the `Definitions`?

Also, could you share the (censored) code for your `defs = Definitions(...)`

**Comment by somiandras** [comment]
@johannkm Looks like the change happened in 1.6.12. I climbed the ladder from 1.6.9 to 1.6.13 and if I add a simple `print(load_asset_checks_from_package_module(assets))` to `main.py`, right before `deps = Definitions(...)`, it will correctly print a list of 3 objects from 1.6.9 to 1.6.11 (and things will generally work), but on 1.6.12 it prints 12 items, counting every check four times.

Here's the extract of my Definitions (looks pretty standard to me):

*main.py*
```
defs = Definitions(
    assets=load_assets_from_package_module(assets),
    asset_checks=load_asset_checks_from_package_module(assets),
    sensors=[
        ...
    ],
    jobs=[
        ...
    ],
    schedules=[
        ...
    ],
    resources=resource_defs,
)
```

where `assets` looks like this (obviously with real unique names):

```
assets
├── __init__.py
├── analytics
│   ├── __init__.py
│   ├── folder1
│   │   ├── __init__.py
│   │   └── some_assets.py
│   └── folder2
│       ├── __init__.py
│       └── some_assets.py
└── universe
    ├── __init__.py
    ├── folder1
    │   ├── __init__.py
    │   └── some_assets.py
    ├── folder2
    │   ├── __init__.py
    │   └── some_assets.py
    ├── ...
```

I tried removing `assets=load_assets_from_package_module(assets)` from the Definitions and only keep the asset check part, but the same error came up.

**Comment by johannkm** [comment]
Found a repro, working on a fix. Thanks for the report!

**Comment by johannkm** [comment]
https://github.com/dagster-io/dagster/pull/21063 will go out in release 1.7.1 this week, which is expected to fix this.
