### ISSUE TITLE
[dagster-dbt] `dagster.log_column_level_metadata()` post-hook causes CI failure

### ISSUE THREAD

**Issue by cbini** [dagster-io/dagster#20798]
### Dagster version

1.6.13

### What's the issue?

I'm testing out the dbt column metadata feature, but the `dbt build --select state:modified+` command running on our dbt Cloud deployment CI pipeline throws an error: `Syntax error: Unexpected end of statement at [4:1]`

It appears that this macro returns a blank query if it's executed there. Here's the text of the query that was executed against our warehouse:
```
/* {"app": "dbt", "dbt_version": "1.7.10", "profile_name": "user", "target_name": "default", "node_id": "model.kipptaf.stg_schoolmint_grow__observations"} */

        -- This macro should only be run in the context of a `dagster-dbt` invocation.
      
```

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Thanks for trying out the feature early! We'll be marking it ready for public consumption once we release 1.7, so there are fixes that haven't been released since we released `1.6.13`.

https://github.com/dagster-io/dagster/pull/20896 will solve your issue.
