### ISSUE TITLE
Re-enable python2 pipenv test

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2079]
We had to turn this off as we were getting strange errors. Pipenv was insisting on putting nbformat 5.0.3 in the lockfile, even though it actually installed 4.4.0 in the virtual environment. When python two tried to install from the lock file, it could not find 5.0.3. About 45 minutes of investigation did not reveal an obvious fix at all.

This is likely correlated with the release of nbformat 5.0.4 somehow.

**Comment by mgasner** [comment]
cf https://github.com/jupyter/nbformat/issues/162

**Comment by MSeal** [comment]
Yes that was my bad -- the release left a .tar.gz file that python 2 thought was usable for nbformat 5.0.3. We had to remove the 5.0.3 tar.gz file form PyPI which we knew would break pip locks for python 2 -- but the code was failing in python 2 so we thought it better to make it break than cause issues with returning invalid notebook objects. Your python 2 lock files should only have nbformat 4.4.0 now. 5.x releases are python 3 only going forward.

**Comment by MSeal** [comment]
You're likely to see this same issue crop up in other libraries when locking with python 2 moving forward, to the point that you may want to consider soft-locking all dependencies for python 2 builds form here-on.

**Comment by natekupp** [comment]
we can turn this back on after #2502

**Comment by catherinewu** [comment]
closing since we removed python2 support
