### ISSUE TITLE
Allow user to select another pipeline when pipeline not found

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2080]
![Screenshot 2020-01-23 15 22 01](https://user-images.githubusercontent.com/28738937/73032523-317fe000-3df4-11ea-87a2-51c670fd1a9e.png)

**Comment by natekupp** [comment]
@bengotow this won't be an issue in the new UI, right?

**Comment by bengotow** [comment]
![image](https://user-images.githubusercontent.com/1037212/83548497-7d8d1080-a4c9-11ea-8cdd-3aa7f471cae3.png)

Yep this shouldn't be a problem anymore with the new UI!
