### ISSUE TITLE
Explore a mypy plugin for dagster types

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2088]
https://github.com/python/mypy/blob/master/mypy/plugin.py

**Comment by mgasner** [comment]
https://mypy.readthedocs.io/en/latest/extending_mypy.html

**Comment by mgasner** [comment]
solids that yield multiple values but use our type annotation syntax for their output value types will hit the following mypy error in the status quo:

```
elementl_data/pipelines/survey_demo.py:51: error: The return type of a generator function should be "Generator" or one of its supertypes
```

**Comment by schrockn** [comment]
sure do. need to use `OutputDefinition` in that case

**Comment by sryza** [comment]
what's our type annotation syntax for multiple outputs? `-> Tuple[TypeA, TypeB]`?

**Comment by schrockn** [comment]
We don't support type annotation syntax for multiple outputs. You have to have `OutputDefinition`
