### ISSUE TITLE
incomplete auto-materialize after multiple upstream asset materializations

### ISSUE THREAD

**Issue by razafinl** [dagster-io/dagster#20924]
### Dagster version

dagster, version 1.6.14

### What's the issue?

When materializing several (10+ or 100+) asset partitions, I notice that downstream asset partitions are not all auto-materialized despite enable Eager auto-materialize.

The issue seems to occur when several downstream materializations are completed in very short period (within a few seconds).

When 20 upstream partitions are materialized, only 3 or 5 (out of the expected 20) downstream partitions are (re)materialized from automaterialize daemon.

### What did you expect to happen?

Auto-materialize should be triggered for all downstream assets

### How to reproduce?

- Implement short/quick to be completed upstream assets

```python
from dagster import (
    AutoMaterializePolicy,
    asset,
    Definitions,
    load_assets_from_current_module,
    HourlyPartitionsDefinition,
    AssetExecutionContext,
)

partition_defs=HourlyPartitionsDefinition("2024-03-30-00:00")

@asset(partitions_def=partition_defs)
def parent_asset(context: AssetExecutionContext) -> str:
    return context.asset_partitions_time_window_for_output().start.strftime("%Y-%m-%dT%H")

@asset(partitions_def=partition_defs)
def child_asset(context: AssetExecutionContext, parent_asset: str) -> str:
    return parent_asset

defs = Definitions(load_assets_from_current_module(auto_materialize_policy = AutoMaterializePolicy.eager()))
```

- Launch backfill of 10+ upstream asset partitions
- Wait for automaterialize daemon to detect and trigger downstream materializations (several downstream assets will remain late/unmaterialized)

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mst** [comment]
Is this maybe due to `max_materializations_per_minute` (https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py#L112)?
```
    Lastly, the `max_materializations_per_minute` parameter, which is set to 1 by default,
    rate-limits the number of auto-materializations that can occur for a particular asset within
    a short time interval. This mainly matters for partitioned assets. Its purpose is to provide a
    safeguard against "surprise backfills", where user-error causes auto-materialize to be
    accidentally triggered for large numbers of partitions at once.
```

Have you tried this?

```
defs = Definitions(load_assets_from_current_module(auto_materialize_policy = AutoMaterializePolicy.eager(max_materializations_per_minute=None)))
```

**Comment by razafinl** [comment]
> Is this maybe due to `max_materializations_per_minute` (https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py#L112)?
> 
> ```
>     Lastly, the `max_materializations_per_minute` parameter, which is set to 1 by default,
>     rate-limits the number of auto-materializations that can occur for a particular asset within
>     a short time interval. This mainly matters for partitioned assets. Its purpose is to provide a
>     safeguard against "surprise backfills", where user-error causes auto-materialize to be
>     accidentally triggered for large numbers of partitions at once.
> ```
> 
> Have you tried this?
> 
> ```
> defs = Definitions(load_assets_from_current_module(auto_materialize_policy = AutoMaterializePolicy.eager(max_materializations_per_minute=None)))
> ```

It seems to have solved my issue. I wasn't aware about this parameter.

Thank you!
