### ISSUE TITLE
Errors in schedule decorators are being swallowed

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#2093]
I had the following error:

```
@daily_schedule(
    pipeline_name='extract_daily_weather_data_pipeline',
    start_date=datetime(year=2019, month=1, day=1),
    execution_time=(now + timedelta(minutes=1)).time(),
    mode='development',
    environment_vars={'DARK_SKY_API_KEY': os.environ.get('DARK_SKY_API_KEY')},
)
```

This should have errored because env_vars should have returned None which ought to be a string according to a check at the decorator level. However, dagit runs fine, but doesn't actually run the job.

**Comment by helloworld** [comment]
Thanks for catching this! I don't think the errors are being swallowed by dagit (for ex, it would run fine if we used the dagit cli too), but there's definitely something weird going on.
