### ISSUE TITLE
reliable test for sqlite event log concurrency

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2098]
previous flakey test marked as skip - grep for issue number

**Comment by alangenfeld** [comment]
https://buildkite.com/dagster/dagster/builds/9767#5d8c77fd-74c0-4203-bf69-427b66b73c5c

**Comment by alangenfeld** [comment]
https://buildkite.com/dagster/dagster/builds/9738#0fed0a3b-7bde-477f-bb95-a016dea36653

**Comment by alangenfeld** [comment]
https://buildkite.com/dagster/dagster/builds/9772#3c9e511f-2c36-47d7-81ec-1a67864a6a68

https://buildkite.com/dagster/dagster/builds/9772#fc00ce05-d456-4f20-a45b-82eb3e32f104

**Comment by mgasner** [comment]
done in #2100

**Comment by mgasner** [comment]
i mean, in https://dagster.phacility.com/D1921
