### ISSUE TITLE
How to fix issue with stdout streaming to Dagster UI (on Window OS)

### ISSUE THREAD

**Issue by Zeulni** [dagster-io/dagster#20992]
### What's the issue or suggestion?

In our project we had the problem that DBT logs were written to stdout/stderr but did not appear in the Dagster UI run-logs (under the tabs "stdout"/"stderr"). After some troubleshooting we found out in the corresponding Dagster Python module that for Windows systems the environment variable "PYTHONLEGACYWINDOWSSTDIO" must be set to "1" to enable IO streaming.

To help others who have the same problem to resolve this issue more quickly, it would be beneficial to include this in the documentation.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Should be resolved by https://github.com/dagster-io/dagster/pull/20996. We'll just add that environment variable since that setting only affects Windows users anyways.
