### ISSUE TITLE
Consider conditionally enabling wal2 in sqlite storages

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2101]
https://www.sqlite.org/cgi/src/timeline?r=wal2

**Comment by schrockn** [comment]
What problem will this solve?

**Comment by catherinewu** [comment]
From https://www.sqlite.org/cgi/src/doc/wal2/doc/wal2.md, it seems like the biggest difference is that "In wal2 mode, wal files do not grow indefinitely even if the checkpointer never has a chance to finish uninterrupted."

One downside is the migration: "It is not possible to change a database directly from "wal" mode to "wal2" mode. Instead, it must first be changed to rollback mode."

**Comment by catherinewu** [comment]
given that sqlite should not be used in production situations, it's likely not worth investing in this change
