### ISSUE TITLE
dlt: source assets not inheriting the specified group

### ISSUE THREAD

**Issue by gofford** [dagster-io/dagster#21049]
### Dagster version

1.7

### What's the issue?

When using the new `dlt` integration in `dagster-embedded-elt` the source assets generated by `get_deps_asset_keys` in the translator always appear in the `default` dagster group regardless of what the `group_name` is set to when defining the `dlt_assets`.

cc: @cmpadden 

<details>
<summary>Code</summary>

```
@dlt_assets(
    dlt_source=activeants(),
    dlt_pipeline=pipeline(
        pipeline_name="activeants",
        dataset_name="activeants",
        destination=ingest_destination,
    ),
    name="activeants",
    group_name="operations",
    dlt_dagster_translator=ActiveantsDagsterDltTranslator(),
)
def activeants_assets(context: AssetExecutionContext, dlt: DagsterDltResource):
    yield from dlt.run(context=context)
```

</details>

<img width="687" alt="Screenshot 2024-04-05 at 13 54 13" src="https://github.com/dagster-io/dagster/assets/32452466/64de89fb-0d2b-47fb-859b-ace477315d6a">

### What did you expect to happen?

As user I expected all assets created via `dlt_assets` would appear in the same group. I would like to be able to configure this behaviour. 

### How to reproduce?

Create `dlt_assets()` using the default translator. 

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment]
Hi @gofford , after speaking with the team I've come to the conclusion that this is expected behavior. It looks like the best practice here would be to define the assets for the sources you want outside of your `@dlt_assets`, and then point to those assets from your translator `get_deps_assets_keys` method.

You can find a relevant discussion of the same thing for the dbt integration here:

- https://github.com/dagster-io/dagster/discussions/16470#discussioncomment-7754624

Let me know if you have any questions!

**Comment by cmpadden** [comment]
Here is one example of how it might be done. I'm pointing all of the thinkific pipeline resource assets to a single source asset. Alternatively, they could have their own individual source assets -- either way!

```
thinkific_upstream_asset = SourceAsset("thinkific_api", group_name="education")

class ThinkificDltDagsterTranslator(DltDagsterTranslator):
    def get_deps_asset_keys(self, resource: DltResource) -> Iterable[AssetKey]:
        return [AssetKey("thinkific_api")]

@dlt_assets(
    dlt_source=thinkific(),
    dlt_pipeline=pipeline(
        pipeline_name="thinkific",
        dataset_name="thinkific",
        destination="snowflake",
    ),
    name="thinkific",
    group_name="education",
    dlt_dagster_translator=ThinkificDltDagsterTranslator(),
)
def thinkific_assets(context: AssetExecutionContext, dlt: DltDagsterResource):
    yield from dlt.run(context=context)
```
<img width="688" alt="image" src="https://github.com/dagster-io/dagster/assets/5807118/1feb03db-eaf7-4405-b3f5-eb2241bc0b85">

**Comment by gofford** [comment]
Yeah, cool - thanks @cmpadden. This is what I ended up doing, and to be fair the explicit SourceAsset is better in my opinion. Thanks for looking into it!

**Comment by cmpadden** [comment]
I know this was closed a while back, but I wanted to show how to define the `SourceAssets` for all of the deps, since we just updated our code to do that.

```
thinkific_source_assets = [SourceAsset(key, group_name="thinkific") for key in thinkific_assets.dependency_keys]
```

This demonstrates how to set the `group_name` for those same Thinkific assets above.

![image](https://github.com/dagster-io/dagster/assets/5807118/0ff6788c-d41f-44cd-9aa9-52182c74222d)

Cheers!

**Comment by travbp** [comment]
> I know this was closed a while back, but I wanted to show how to define the `SourceAssets` for all of the deps, since we just updated our code to do that.
> 
> ```
> thinkific_source_assets = [SourceAsset(key, group_name="thinkific") for key in thinkific_assets.dependency_keys]
> ```
> 
> This demonstrates how to set the `group_name` for those same Thinkific assets above.
> 
> ![image](https://private-user-images.githubusercontent.com/5807118/327583040-0ff6788c-d41f-44cd-9aa9-52182c74222d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NDQxMDAsIm5iZiI6MTcxODc0MzgwMCwicGF0aCI6Ii81ODA3MTE4LzMyNzU4MzA0MC0wZmY2Nzg4Yy1kNDFmLTQ0Y2QtOWFhOS01MjE4MmM3NDIyMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMjA1MDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE5Nzk2YTM1OTA1Yzc4MjJhMTk0OTIyZjNkZGQ0NjExNDhmYjU1MDNlZjNlMzcwYWYyMzljZGI1ODkwOGUxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yjbW077kWTF-Rp8PAYjpQjleLRlYWr4cVqH8uHRJnBY)
> 
> Cheers!

@cmpadden would you be able to show where to put this code? I'm trying to emulate this in my project

**Comment by cmpadden** [comment]
> @cmpadden would you be able to show where to put this code in your original example? I'm trying to emulate this in my project

hi @travbp you can find a full example in our `dagster-open-platform` project here:

https://github.com/dagster-io/dagster-open-platform/blob/821d8ab56c9d9821d50bb04728ee10de9705eddb/dagster_open_platform/dlt/assets.py#L45-L47

Which are being registered in our Definitions object using `load_assets_from_modules([assets])` here:

https://github.com/dagster-io/dagster-open-platform/blob/main/dagster_open_platform/dlt/definitions.py#L26

**Comment by travbp** [comment]
@cmpadden this got me on the right track, thanks!!
