### ISSUE TITLE
Materialize unsynced assets incorrectly includes `source assets`

### ISSUE THREAD

**Issue by ion-elgreco** [dagster-io/dagster#21040]
### Dagster version

1.7.0

### What's the issue?

The new materialize unsynced assets is a great improvement, since it now includes also partitioned assets, however the list also includes source assets which can not be executed together. 

It should only show normal assets since those can be materialized.

### How to reproduce?

Click on materialize unsynced assets in an asset group that contains source assets and normal assets.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Thanks for filing this @ion-elgreco  - it looks like this may be specifically source assets that have partitions? Will see if we can get this fixed.

**Comment by ion-elgreco** [comment]
> Thanks for filing this @ion-elgreco  - it looks like this may be specifically source assets that have partitions? Will see if we can get this fixed.

Yess the source assets has partitions

**Comment by johannkm** [comment]
closed by the above
