### ISSUE TITLE
Seeing periodic windows-only failures in test_seperate_sub_dags

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2105]
https://dev.azure.com/elementl/dagster/_build/results?buildId=6171&view=logs&j=6d18a791-2503-588f-401e-deb910661c62&t=e1a0008d-2827-5047-ff23-b9afccb00ba9

**Comment by natekupp** [comment]
Let's fix after #1923

**Comment by catherinewu** [comment]
Seems resolved now, closing
