### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by aakash1274** [dagster-io/dagster#21061]
### Dagster version

https://github.com/dagster-io

### What's the issue?

integration: embedded -elt

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
hey @aakash1274 you didn't specify any details for this

**Comment by rexledesma** [comment]
Closing due to lack of details.
