### ISSUE TITLE
Link to Built-In IOManagers is self-referential and does not contain named data.

### ISSUE THREAD

**Issue by easontm** [dagster-io/dagster#21074]
### What's the issue or suggestion?

If you go to
https://docs.dagster.io/concepts/io-management/io-managers#built-in-io-managers
it says:
> For a full list of Dagster-provided I/O managers, refer to the [built-in I/O managers list](https://docs.dagster.io/concepts/io-management/io-managers#built-in-io-managers).

Which is just a link to that very section and does not contain the list.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
Thanks for reporting this! Fixed it in #21095.
