### ISSUE TITLE
are config fields accessible from jupyter notebook? 

### ISSUE THREAD

**Issue by zzztimbo** [dagster-io/dagster#2111]
```
foo_products_to_google_sheet = dm.define_dagstermill_solid(
    "foo_products_to_google_sheet",
    script_relative_path("products_to_google_sheet.ipynb"),
    config_field=Field(
        Dict(
            fields={
                "google_sheets_service_account_json": Field(
                    String, is_optional=False, description="The Google Service Account to use to access Google Sheets."
                )
            }
        )
    ),
)
```

How do I access config fields from my notebook? I'm assuming I can't. Is the only route to pass in the path to my service account from an upstream solid?

**Comment by zzztimbo** [comment]
Ok. I figured everything out. 

https://github.com/dagster-io/dagster/blob/master/python_modules/dagstermill/dagstermill/examples/notebooks/hello_world_config.ipynb

It's a simple case of RTFM. `In our notebook, we’ll stub the context as follows (in the parameters cell)` from https://dagster.readthedocs.io/en/0.6.9/sections/learn/guides/data_science/data_science.html

It took me a while to figure out that the `parameters` cell in the notebook gets replaced with the injected values from dagstermill.

**Comment by alangenfeld** [comment]
Do you think there is a way we could have surfaced this that would make it more clear?

**Comment by zzztimbo** [comment]
Perhaps explicitly instructing the user to look at the rendered notebooks or placing screenshots of the rendered notebook in the documentation?
