### ISSUE TITLE
Airflow scheduler hangs when loading pipeline

### ISSUE THREAD

**Issue by casassg** [dagster-io/dagster#2113]
Wrote my first dagster pipeline yesterday and wanted to run it on Airflow. However it was not showing up on Airflow as the scheduler process in charge of processing the DAG seemed to disappear. 

After some manual debugging, found the cause was [PDB instance](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/utils/__init__.py#L302) on the `dagster.utils` module that was being imported when trying to load the Airflow DAG. 

Seems the code was added [here](https://github.com/dagster-io/dagster/commit/40dfab63e0dc50f2d4b9f87ed338aa56ac14cc8e) but I haven't been able to find any reference to the PDB so I'm wondering if that instance could be hidden behind a conditional flag to avoid Scheduler hangs on Airflow.

Great product btw!

**Comment by schrockn** [comment]
Thanks for the kind words! Handing off to @prha and @helloworld who this blames to

**Comment by schrockn** [comment]
Thanks for digging in, this sounds like it was tricky to debug

**Comment by mgasner** [comment]
i wonder if the `if __name__.startswith('unusual_prefix')` guard will work here, or only in DAG definition files

**Comment by mgasner** [comment]
probably we should just put this in `dagster.utils.pdb` or somewhere else it won't be wantonly imported

**Comment by helloworld** [comment]
@casassg just landed a fix in master so that `ForkedPdb` won't be imported automatically. 

Our next release will be on Tuesday, so if you need the fix now I'd recommend simply deleting the import in `dagster/python_modules/dagster/dagster/utils/__init__.py` or doing an editable install of the master branch.

**Comment by casassg** [comment]
Appreciate the fast fix. I actually commented it out on my machine and was able to run the DAG successfully. Thanks for the support 👍
