### ISSUE TITLE
Stop using PipelineDefinition for sub selection

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2115]
Using instances of PipelineDefinition for executing solid subsets is pretty confusing and almost certainly has some broken corner cases. A good solution to this problem is likely introducing a new abstraction for what is to be executed and potentially how to load it - ie its target handle.

>... the need for some sort of "ExecutionScope" that is separate from PipelineDefinition in my view which could cover executing a solid in isolation, pipeline subsets, composite solids in isolation, etc.

From https://dagster.phacility.com/D1940

**Comment by mgasner** [comment]
#1982 #812

**Comment by yuhan** [comment]
considering pick this back up as part of https://github.com/dagster-io/dagster/issues/4489

**Comment by sryza** [comment]
Closing because PipelineDefinition no longer exists and selections have been working fine under the current scheme for a long time
