### ISSUE TITLE
Side panel is missing with new settings page enabled on 1.7.1

### ISSUE THREAD

**Issue by somiandras** [dagster-io/dagster#21184]
### Dagster version

1.7.1

### What's the issue?

After upgrading to 1.7.1 the side panel and the hamburger menu icon disappeared. When I turn the new settings page off in the User settings everything goes back to normal.

<img width="1505" alt="image" src="https://github.com/dagster-io/dagster/assets/12885402/fcc40e53-7b9d-49f1-b16e-560db2f3c873">

### What did you expect to happen?

I didn't expect elements of the UI to be missing.

### How to reproduce?

Upgrade to 1.7.1, turn on the new user settings.

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ion-elgreco** [comment]
I can confirm, side menu is gone when you enable new settings page, this wasn't an issue in 1.7.0

**Comment by garethbrickman** [comment]
Thanks for reporting this! A fix has been merged in #21187
