### ISSUE TITLE
transient failure in sqlite storage concurrency test

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2124]
E           AssertionError: [IntegrityError('(sqlite3.IntegrityError) UNIQUE constraint failed: alembic_version.version_num')]
E           assert not [IntegrityError('(sqlite3.IntegrityError) UNIQUE constraint failed: alembic_version.version_num')]

**Comment by alangenfeld** [comment]
https://buildkite.com/dagster/dagster/builds/10108#c60d8785-2a10-49df-95e0-b8939f14a1e8
