### ISSUE TITLE
[Documentation Feedback] Problem on /dagster-cloud/deployment/agents/amazon-ecs/creating-ecs-agent-existing-vpc page

### ISSUE THREAD

**Issue by aimran-adroll** [dagster-io/dagster#21291]
Did we lose ability to deploy agents on existing vpc? The page disappeared

**Comment by garethbrickman** [comment]
Nope we just had a bug resolving that URL, sorry about that! You can find that docs page here: https://docs.dagster.io/dagster-plus/deployment/agents/amazon-ecs/creating-ecs-agent-existing-vpc
