### ISSUE TITLE
Upgrade K8sRunLauncher k8s definitions to allow 1.29 fiels

### ISSUE THREAD

**Issue by dbullerwell** [dagster-io/dagster#21312]
### Dagster version

1.7.1

### What's the issue?

My company runs a k8s hosted implementation of dagster in a GKE cluster, using Cloud SQL Postgres as the Dagster db store. Because of a few Cloud SQL quirks it requires us to add a cloud-sql-proxy sidecar to all jobs to allow them to connect to our database and properly update job status and logs for Dagster.

This implementation leads to a situation where jobs stick around forever as sidecars don't shut down properly when the main process exits. As a workaround today we use a [k8s-controller](https://github.com/otherguy/k8s-controller-sidecars) to shutdown sidecars when the main process stops. This implementation works reasonably most of the time, however in k8s 1.28 [native sidecars](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) were introduced in alpha, and graduated to beta in 1.29, which finally resolves this issue natively in Kubernetes.

Attempting to use this feature on a 1.29 k8s cluster with the K8sRunLauncher caused all jobs to fail to start with the error below.

```
Exception: Unexpected keys in model class V1Container: {'restart'}
  File "/usr/local/lib/python3.10/site-packages/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py", line 379, in _dequeue_run
    instance.run_launcher.launch_run(LaunchRunContext(dagster_run=run, workspace=workspace))
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/launcher.py", line 296, in launch_run
    self._launch_k8s_job_with_args(job_name, args, run)
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/launcher.py", line 219, in _launch_k8s_job_with_args
    container_context = self.get_container_context_for_run(run)
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/launcher.py", line 214, in get_container_context_for_run
    return K8sContainerContext.create_for_run(dagster_run, self, include_run_tags=True)
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/container_context.py", line 444, in create_for_run
    run_k8s_config=UserDefinedDagsterK8sConfig.from_dict(
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/job.py", line 168, in from_dict
    return UserDefinedDagsterK8sConfig(
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/job.py", line 131, in __new__
    pod_spec_config = k8s_snake_case_dict(kubernetes.client.V1PodSpec, pod_spec_config)
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/models.py", line 133, in k8s_snake_case_dict
    final_dict[key] = _k8s_snake_case_value(val, attr_type, key)
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/models.py", line 79, in _k8s_snake_case_value
    return [
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/models.py", line 80, in <listcomp>
    _k8s_snake_case_value(list_value, sub_kls, f"{attr_name}[{index}]")
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/models.py", line 100, in _k8s_snake_case_value
    return k8s_snake_case_dict(klass, val)
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/models.py", line 128, in k8s_snake_case_dict
    snake_case_dict = k8s_snake_case_keys(model_class, model_dict)
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/models.py", line 122, in k8s_snake_case_keys
    raise Exception(f"Unexpected keys in model class {model_class.__name__}: {invalid_keys}")
```

### What did you expect to happen?

Dagster would generate the job using the defined native sidecar container.

### How to reproduce?

Here's a small sample of our runLauncher configuration that injects the cloud-sql-proxy as a native sidecar, but fails to start with the error noted above.

```
dagster:
  runLauncher:
    type: K8sRunLauncher
    config:
      k8sRunLauncher:
        runK8sConfig:
          podSpecConfig:
            # Injecting the cloud sql proxy for every job that's spun up
            initContainers:
              - name: cloud-sql-proxy
                image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
                args:
                  - '--exit-zero-on-sigterm'
                  - '--structured-logs'
                  - '--port=5432'
                  - '--private-ip'
                  - 'SQL_INSTANCE_NAME'
                securityContext:
                  runAsNonRoot: true
                # The offending line
                restart: Always
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    memory: 128Mi
```

### Deployment type

Dagster Helm chart

### Deployment details

Helm chart version: 1.7.1
Kubernetes version: 1.29

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @dbullerwell - thanks for reporting this. The code snippet that you posted has to do with the Helm chart schema, which I would not expect to come into play with the stack trace you posted. 

We're pulling these fields from the kubernetes python client models: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-k8s/dagster_k8s/models.py#L7

That dependency should be unpinned in dagster-k8s, so I wonder if fixing this is just a matter of ensuring that our helm chart is deploying the latest version of that Python package?

**Comment by gibsondan** [comment]
hmmmm, I just checked and we are running the latest released version of `kubernetes` so it's not that..

```
dagster % docker run docker.io/dagster/dagster-celery-k8s:1.7.1 /bin/bash
dagster % pip freeze | grep kubernetes
dask-kubernetes==2022.9.0
kubernetes==29.0.0
kubernetes-asyncio==28.2.1

**Comment by gibsondan** [comment]
oh! Is it possible it needs to be `restart_policy` not `restart`? As per https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Container.md

**Comment by gibsondan** [comment]
(or restartPolicy - both should work)
