### ISSUE TITLE
Implement reasonable public python API for executing pipeline subselections and document it

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2131]
From slack, got a perfect reasonable question and was able to give only an unsatisfying answer.

```
aqm Today at 1:11 AM
Hi all.  I'm trying to understand how, through the python api, I can execute a subset of pipeline solids.  I can use execute_solids_within_pipeline(), but this returns a list of SolidExecutionResults.  Ideally, what I want is a PipelineExecutionResult, which has a run_id and a context I can inspect.  Is there a way to do this?
```

```
schrockn  < 1 minute ago
Hey aqm this is definitely way more awkward and less documented than it should be right now.
For now call build_sub_pipeline on the original pipeline and the pass that to execute_pipeline. e.g.:
execute_pipeline(original_pipeline.build_sub_pipeline(['solid_a', 'solid_b']))
```

**Comment by mgasner** [comment]
see also #1552

**Comment by mgasner** [comment]
see also #1434

**Comment by yuhan** [comment]
`solid_subset` arg in the following python APIs now accept DSL syntax queries:
- `execute_pipeline(foo_pipeline, solid_subset=['*some_solid', 'other_solid_a', 'other_solid_b+'])`
- `execute_pipeline_iterator(foo_pipeline, solid_subset=['*some_solid', 'other_solid_a', 'other_solid_b+'])`

More examples documented in the api's [docstring](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/execution/api.py#L264-L271)
