### ISSUE TITLE
explore systemic solutions to "custom" config types

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2133]
We have a few "custom" config types that don't quite fit the mold of how the others operate:
* `StringSource` on dagster instance config
* `Table` & `Dataset` in dagster-gcp

We need to figure out how we want to deal with these config types that have `post_process`ing and need to not conflict with our current `key` based identity approach.

**Comment by natekupp** [comment]
@alangenfeld @schrockn do you think there's anything else we want to do here?

**Comment by schrockn** [comment]
I actually think we ended up in a good place on this, using post_process to implement these custom types. I think we can close.

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
