### ISSUE TITLE
Pydantic V2 warning about config keys

### ISSUE THREAD

**Issue by neerajprad** [dagster-io/dagster#21355]
### Dagster version

dagster, version 1.7.2

### What's the issue?

When running dagster, I see the following warning:
```
...site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'keep_untouched' has been renamed to 'ignored_types'
```

I see that there are a [couple](https://github.com/search?q=repo%3Adagster-io%2Fdagster%20keep_untouched&type=code) of places in the code which use `keep_untouched`.

This can be fixed by changing the argument name to `ignored_types`.

### What did you expect to happen?

No warnings.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by neerajprad** [comment]
In the meantime, if there's a way to silence these warnings, that'll be greatly appreciated.

**Comment by eknowles** [comment]
> In the meantime, if there's a way to silence these warnings, that'll be greatly appreciated.

I also have this issue, only way I've found is to turn off all warnings with the following `export PYTHONWARNINGS=ignore`. The `warnings` library wouldn't work when trying to target this warning for me.

**Comment by sryza** [comment]
A fix for this will be landing in tomorrow's release: https://github.com/dagster-io/dagster/pull/21274

**Comment by ggurjar333** [comment]
Fix it in PyCharm or you can fix in Environment variables of your windows machine.
![Screenshot 2024-04-29 071718](https://github.com/dagster-io/dagster/assets/8761197/ee39a871-c64c-412d-9071-450b52ed30c4)
