### ISSUE TITLE
Dagit Runs Page should provide a run summary view

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#2136]
When I run a backfill job with let's say 300 runs. I search for the backfill job id tag but I just see a huge list of jobs that say "starting" and I don't have a great idea of how my jobs are going. To solve this I have to click the next page button all the way to the end to see if my jobs are succeeding or failing.

**Comment by bengotow** [comment]
We could change the sort order on the dagit view to show the running jobs at the top maybe, but it sounds like the best fix for this would be some sort of grouped run view with a summary (eg: `8 / 300 in progress`)?

**Comment by sryza** [comment]
With the new partitions UI, we now show a runs summary after starting a backfill.  I believe that should address this requirement.
