### ISSUE TITLE
copy (but not paste) in the config editor / dagit playground seems to be broken

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2138]

**Comment by mgasner** [comment]
this is on Mac -- command-C causes UX changes but nothing ends up on the clipboard

**Comment by schrockn** [comment]
Works for me. Mac and Chrome

**Comment by mgasner** [comment]
Hm, I'm on firefox

**Comment by mgasner** [comment]
When I hit command-C, this is the state of the UI, and nothing is copied to the clipboard
<img width="1780" alt="Screen Shot 2020-02-12 at 9 35 45 AM" src="https://user-images.githubusercontent.com/427016/74361072-16611a00-4d7b-11ea-9a7e-c5403260a74b.png">

**Comment by bengotow** [comment]
Can confirm, copying doesn't work in FF. Will see if I can fix this.

**Comment by bengotow** [comment]
https://dagster.phacility.com/D2120
