### ISSUE TITLE
Configure buildkite to be less resource intensive.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2142]
We generally are over capacity in our BK cluster. This is getting to be non-trivial cost. I suspect we can rejigger the settings to prevent overprovisioning and then contract more quickly. In particular I think there's a chance that our behavior became more pathological once our test build times went over 10 mins.

**Comment by natekupp** [comment]
@schrockn I'll close this and we can open new issue when this comes up again

**Comment by schrockn** [comment]
👍🏻

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
