### ISSUE TITLE
opening compute logs broken against remote run

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2144]
When we have for example a run launched in to kubernetes the compute logs wont work in there current form. When you open them in dagit you get an endless spinner. We handle this more gracefully.

**Comment by bengotow** [comment]
Hey @alangenfeld do you think we should handle this by detecting that the job is remote and not showing the "Show Compute Logs" UI, or should we show the button, let you click it, get a 400/404 from the API and show a "Sorry no logs available" screen? I feel like the former would be a bit nicer but I'm not sure how easy it is to determine that no logs will be available.

**Comment by alangenfeld** [comment]
I think this was fixed in https://dagster.phacility.com/D2024 actually
