### ISSUE TITLE
launch button stuck in loading state on error

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2145]

**Comment by bengotow** [comment]
This one should be fairly easy to fix. Right now we await completion of the Start button's click handler (ExecutionStartButton.tsx:66) and then transition it back out of the loading state. My bet is that certain kinds of errors cause that handler to never complete, or it might be throwing an exception there. Gonna flag this one as a good first issue!

**Comment by natekupp** [comment]
@bengotow is this fixed?

**Comment by natekupp** [comment]
@prha FYI as you're reworking this button

**Comment by prha** [comment]
I think this is fixed... transport errors would have caused the async handler to not complete.  We're now catching those.
