### ISSUE TITLE
DynamicOut downstream op using PolarsParquetIOManager fails with  ComputeError: RecursionError

### ISSUE THREAD

**Issue by CrispyCrafter** [dagster-io/dagster#21451]
### Dagster version

dagster, version 1.7.2

### What's the issue?

When creating a `job` that uses `PolarsParquetIOManager` with a `DynamicOutput` op, polars fails to read upstream parquet files due to the presence of square brackets in the file path. 

![image](https://github.com/dagster-io/dagster/assets/29259177/2c6f65fa-a4bd-4ba5-ab5a-327ffe833ba2)

Investigating further it appears that this is a long-standing bug that showed up using partitioned filesystems.

https://github.com/pola-rs/polars/issues/12589
and internally in dagster:
https://github.com/dagster-io/dagster/issues/11123

I have taken the liberty to update the polars issue with the core of the underlying issue.

Fundamentally what this comes down to is that `UPath` objects in `DynamicOutput` ops are tracked using square brackets in the mapping key name:

https://github.com/dagster-io/dagster/blob/638a4d40df6fae2355e70b97db2e1027d9d983a7/python_modules/dagster/dagster/_core/definitions/events.py#L152

This breaks the polars downstream read operations leading to the observed error

    

### What did you expect to happen?

Serialise and deserialise inter-op parquet polars dataframes.

### How to reproduce?

Here is a simple example to replicate the bug:

```python
import os    
import polars as pl
from dagster_polars import PolarsParquetIOManager
from dagster import Out, DynamicOut, DynamicOutput, op, job

base_path = 'some_path'

polars_parquet_io = PolarsParquetIOManager(
    base_path=base_path
)

@op(out=DynamicOut(str))
def files_in_directory(context):
    path = base_path + '/inputs'
    dirname, _, filenames = next(os.walk(path))
    for file in filenames:
        yield DynamicOutput(os.path.join(dirname, file), mapping_key=file.split(".")[0])

@op(
    out={
        'df': Out(
            dagster_type=pl.DataFrame,
            io_manager_key='polars_parquet_io'
        )
    }
)
def read_file(path) -> pl.DataFrame:
    return pl.read_parquet(path)

@op(required_resource_keys=['polars_parquet_io'])
def summarize_directory(context, dfs):
    context.log.info("Running")
    return pl.concat(dfs)

@job(resource_defs={'polars_parquet_io': polars_parquet_io})
def process_files():
    files = files_in_directory()
    file_results = files.map(read_file)
    summarize_directory(file_results.collect())
```

When running this job the following error is raised:
`polars.exceptions.ComputeError: ComputeError`

### Deployment type

Local

### Deployment details

local

### Additional information

See:
https://github.com/pola-rs/polars/issues/12589
https://github.com/dagster-io/dagster/issues/11123

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by CrispyCrafter** [comment]
It seems that polars is interpreting square brackets `[ ]` as valid shell-glob syntax.
I would recommend that this syntax is not used for `DynamicOutput` persistent object paths as it is inevitable that a third party package that uses glob would fail. 

This is from the blog man page:

```
       Character classes

       An expression "[...]" where the first character after the leading
       '[' is not an '!' matches a single character, namely any of the
       characters enclosed by the brackets.  The string enclosed by the
       brackets cannot be empty; therefore ']' can be allowed between
       the brackets, provided that it is the first character.  (Thus,
       "[][!]" matches the three characters '[', ']', and '!'.)

       Ranges

       There is one special convention: two characters separated by '-'
       denote a range.  (Thus, "[A-Fa-f0-9]" is equivalent to
       "[ABCDEFabcdef0123456789]".)  One may include '-' in its literal
       meaning by making it the first or last character between the
       brackets.  (Thus, "[]-]" matches just the two characters ']' and
       '-', and "[--0]" matches the three characters '-', '.', and '0',
       since '/' cannot be matched.)
````
https://man7.org/linux/man-pages/man7/glob.7.html


Here is the core bug being tracked in `polars`

https://github.com/pola-rs/polars/issues/12876

**Comment by ritchie46** [comment]
I just see this now. I will ensure we will have a `glob` flag upstream in Polars which users can toggle off.

**Comment by CrispyCrafter** [comment]
> I just see this now. I will ensure we will have a `glob` flag upstream in Polars which users can toggle off.
@ritchie46 

Although I agree that a `glob` flag would be useful in polars, it seems that in the case of `Dagster`, the convention of using square brackets is really the key issue here.

For instance, say an operation created as set out partitioned outputs with the pattern:
`output/[partition_A]/[partition_B]/*.parquet` one would like the ability to read all files in lowest folder root. 

Perhaps it should be considered invalid syntax to write files containing square brackets and reserve `[]` to act as correct glob functionality for reads

**Comment by CrispyCrafter** [comment]
Compiled and tested against polars master branch. Can confirm the issue has been fixed.
It should be resolved with the latest polars release

**Comment by CrispyCrafter** [comment]
Scrap that latest got released two hours ago.
