### ISSUE TITLE
Allow creating an "email asset owners" alert even if not all assets have owners

### ISSUE THREAD

**Issue by polivbr** [dagster-io/dagster#21464]
### What's the use case?

We would like to have an alert to email asset owners on failures but haven't added owners to all of our existing assets. While we could create alerts for all of the assets groups and keys which do have owners, this is a maintenance headache.

### Ideas of implementation

The alert could simply not apply to assets without owners. A warning could be displayed, but it shouldn't prevent the alert from being created.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
@polivbr This makes sense. I've raised awareness with the team and they will triage and decide on prioritization 👍

**Comment by garethbrickman** [comment]
We've added an input for a default email address to handle assets that don't have owners explicitly set for them:

![Screenshot 2024-10-18 at 09 11 50](https://github.com/user-attachments/assets/2c60e4a0-7995-410f-b39a-dd0a824da45d)
