### ISSUE TITLE
host our Helm chart

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2146]
Maybe self hosting:
https://medium.com/containerum/how-to-make-and-share-your-own-helm-package-50ae40f6c221

Maybe Helm Hub:
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by rlancer** [comment]
Without a hosted Helm repository we can't plug Dagster into our infrastructure as code workflow, we use https://github.com/roboll/helmfile to manage our Helm deployments

**Comment by natekupp** [comment]
Fixed in https://dagster.phacility.com/D3945 - Dagster Helm chart can now be installed via:

```shell
helm repo add dagster https://dagster-io.github.io/helm
helm install dagster dagster/dagster
```
