### ISSUE TITLE
Tracking Issue for Odd Layout Bug in Gaant Viewer

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2149]
Have been unable to repro locally so far but we have seen odd layout issues when selecting execution subsets in the Gaant Viewer

**Comment by bengotow** [comment]
Havent' been able to repro this exact problem but I did locate another scenario where a small downward line exists and shouldn't:

<img width="204" alt="image" src="https://user-images.githubusercontent.com/1037212/74387577-8b097800-4dbe-11ea-9fa3-6bae518f5848.png">

Digging in to what's going on but may miss 4pm.

**Comment by schrockn** [comment]
no worries this shouldn't block release but we should get it out in next dot release (which would be latest late next week)

**Comment by bengotow** [comment]
Should be fixed by https://dagster.phacility.com/D2118!
