### ISSUE TITLE
1.6.12 introduced a bug preventing asset checks to be available in a code location using dagster-dbt

### ISSUE THREAD

**Issue by derHeinzer** [dagster-io/dagster#21516]
### Dagster version

1.6.12

### What's the issue?

I encountered strange errors with asset checks in combination with the dbt integration lately. I tried to use the new multi_asset_check decorator to implement multiple checks on a dagster dbt asset, that I dont want to implement as dbt tests. In this case the configured Checks are correctly attached to the respective asset in the webgui, but when I try to execute the checks I am encountering the error:
![image](https://github.com/dagster-io/dagster/assets/43210452/b85d693a-6d21-42a4-95ba-d6c7482717c3)

This is strange, since the AssetKey MUST be supplied by the definition, otherwise I would not be able to try to execute a check on the respective asset.

Afterward I tried to implement a working minimal example to further examine the error and encountered that even the provided example by the dagster docs would not work.

The orders_id_has_no_nulls example at https://docs.dagster.io/concepts/assets/asset-checks/define-execute-asset-checks#defining-checks-and-assets-together does not work in our setup anymore. The check does not show up in the gui and is not being executed when materializing the asset. I tried it in different dagster versions. The bug seems to have been introduced in 1.6.12, since everything works in 1.6.11 but not in 1.6.12.

The latter error seems to be connected with dagster dbt and does occur in special constellations. There must be an additional asset in the code location like the following

```
@asset(
    deps=["size_distribution_regular"],
    check_specs=[
        AssetCheckSpec(
            asset="check_asset_regular_size_distribution",
            name="correctness",
        ),
    ],
)
def check_asset_regular_size_distribution():
    yield AssetCheckResult(
        check_name="correctness",
        passed=True,
    )
```

size_distribution_regular must be a dagster dbt asset and additionally check_asset_regular_size_distribution must have a downstream dagster dbt asset with a model like for exammple
```
-- depends_on: {{ source('dagster_checks', 'check_asset_regular_size_distribution') }}
SELECT 1
```
and a sources.yml
```
version: 2

sources:
  - name: dagster_checks
    tables:
      - name: check_asset_regular_size_distribution
        meta:
          dagster:
            asset_key: ["check_asset_regular_size_distribution"]
```

Suprisingly the existence of this constellation prevents the asset check orders_id_has_no_nulls to be displayed in the webserver.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @derHeinzer - thanks for the report. We believe that this issue will be fixed in https://github.com/dagster-io/dagster/pull/21488 which is planned to go out in our 1.7.4 release later this week.

**Comment by derHeinzer** [comment]
Hi @gibsondan great to hear that. I will be testing. Thank you very much!

**Comment by derHeinzer** [comment]
works like charm with 1.7.4 thanks again! @gibsondan

**Comment by rexledesma** [comment]
Fixed with https://github.com/dagster-io/dagster/pull/21488.
