### ISSUE TITLE
DagsterInvalidSubsetError for dbt cloud assets when defining an asset job with them 

### ISSUE THREAD

**Issue by ndellosa95** [dagster-io/dagster#21522]
### Dagster version

1.6.2, but don't know the exact version where this cropped up

### What's the issue?

If you follow the dbt cloud assets example in the documentation, you will get this error with dagster v1.6.2:

```
dagster._core.errors.DagsterInvalidSubsetError: AssetKey(s) {AssetKey(['all materializable assets'])} were selected, but no AssetsDefinition objects supply these keys. Make sure all keys are spelled correctly, and all AssetsDefinitions are correctly added to the `Definitions`.
```

However, if you remove the schedule/asset job it will work as expected, so it seems it just can't find the asset keys correctly. 

### How to reproduce?

I am seeing this with the [example here](https://docs.dagster.io/integrations/dbt-cloud#step-3-schedule-dbt-cloud-job-runs).

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Duplicates [https://github.com/dagster-io/dagster/issues/21152](https://github.com/dagster-io/dagster/issues/21152)
