### ISSUE TITLE
run_failure_sensor and run_status_sensor for DagsterRunStatus.FAILURE not working on 1.7.3

### ISSUE THREAD

**Issue by marcilj** [dagster-io/dagster#21526]
### Dagster version

dagster, version 1.7.3

### What's the issue?

Trying to upgrade from 1.6.1 to 1.7.3, and while testing Dagster before upgrading, I found out that the failure sensor where not getting triggered in 1.7.3.

I think the process is able to find the failed jobs but doesn't yield runs.

When I look in the sensor evaluation history I can see that the `record_timestamp` change from `null` to the `current_timestamp` when I have a run that fails, but not run request are triggered.

See picture 
![image](https://github.com/dagster-io/dagster/assets/89793010/47591367-1625-43c3-85c6-b7e25a302c90)

![image](https://github.com/dagster-io/dagster/assets/89793010/29f82b26-38d9-4643-93fa-fb4f31465d85)

Same thing happen when I use run_status_sensor directly instead of `run_failure_sensor`
![image](https://github.com/dagster-io/dagster/assets/89793010/c8dd43a2-b9c2-49e0-83fe-e5c5699e988e)

### What did you expect to happen?

A run request to be started, because I return a run request in my run_failure_sensor.

### How to reproduce?

Create a job that fails
```
@op
def fails():
    raise Exception("failure!")


@job
def my_job_fails():
    fails()
```

And a `run_failure_sensor` that return a `RunRequest`

```
@run_failure_sensor(request_job=my_job)
def my_failure_sensor(context: RunFailureSensorContext):
    return RunRequest(job_name="my_job")
```

### Deployment type

None

### Additional information

I've been tested this by installing 1.6.1, running it and then installing 1.7.3 and doing the same steps.

On 1.6.1 (Without any code change) it runs but not on 1.7.3

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
@marcilj I tried loading this file based on your example:

```
from dagster import (
    DefaultSensorStatus,
    Definitions,
    RunFailureSensorContext,
    RunRequest,
    job,
    op,
    run_failure_sensor,
)


@op
def fails():
    raise Exception("failure!")


@job
def my_job_fails():
    fails()


@run_failure_sensor(
    request_job=my_job_fails, minimum_interval_seconds=5, default_status=DefaultSensorStatus.RUNNING
)
def my_failure_sensor(context: RunFailureSensorContext):
    return RunRequest(job_name="my_job_fails")


defs = Definitions(sensors=[my_failure_sensor], jobs=[my_job_fails])
```

- ran dagster dev
- Launched the job, saw it fail, and viewed the sensor timeline

I can see the run being launched as expected in 1.7.3: 
<img width="1240" alt="image" src="https://github.com/dagster-io/dagster/assets/8451211/ea8faa71-97f3-40bf-bd2a-6461597bb521">

It sounds like that is different than what you are seeing - if you run those same steps do you get different results? Any other details or differences that might be helpful for us to reproduce what you're seeing?

**Comment by marcilj** [comment]
Oh damm... you are totally right.

Tried it with that basic code, and ended up with a working sensor.


Ok, so found the issue, and this might be a feature. I was testing my sensor on a failed job from another Code Location.
What throw me off was that the `record_timestamp` was getting refreshed, but nothing else was happening.

Can you please tell me why would the `record_timestamp` get updated if the sensors technically shouldn't look at failed jobs from another code location?

Adding `monitor_all_code_locations=True` in `@run_failure_sensor(
    request_job=send_event_to_datadog_job, monitor_all_code_locations=True
)` fixed the issue.

Thank for the quick reply.

**Comment by gibsondan** [comment]
No problem - record_timestamp gets updated because the sensor is tailing the full event stream and filtering out invalid events.
