### ISSUE TITLE
Getting invalid CSS rule error for gantt view

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#2152]
![Screen Shot 2020-02-12 at 2 19 50 PM](https://user-images.githubusercontent.com/1040172/74383103-6f44a880-4da3-11ea-8385-0c1f9ba1a7e8.png)

**Comment by bengotow** [comment]
Oh good catch, will fix this ASAP

**Comment by bengotow** [comment]
Resolved by https://dagster.phacility.com/D2030!
