### ISSUE TITLE
Unpin papermill

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2154]
https://dagster.phacility.com/D2000

**Comment by natekupp** [comment]
Started https://dagster.phacility.com/D2054 but probably not trivial to get this to support both pre/post 2.0.0

**Comment by mgasner** [comment]
We are also going to need to deal with nbformat dropping python 2 support in v5

**Comment by mgasner** [comment]
https://nbformat.readthedocs.io/en/latest/changelog.html#id6

**Comment by mingfang** [comment]
any update on this?
papermill<2.0.0 is now ancient and is causing compatibility problems for me

**Comment by mgasner** [comment]
i think we can move forwards on this since we have also dropped support for py2

**Comment by mingfang** [comment]
is there any hope of bumping this up?
I'm blocked by this.

**Comment by mgasner** [comment]
I took a look at this today and I have a clear path to unpinning papermill. I anticipate this should merge tomorrow and go out in Thursday's release

**Comment by mgasner** [comment]
Well, a week late, but https://dagster.phacility.com/D7970 just merged and this will be in tomorrow's release. Thank you for your patience @mingfang

**Comment by mingfang** [comment]
@mgasner 
thank you very very much!
