### ISSUE TITLE
enable materializing ranges of partitions using the asset CLI

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#21560]
perhaps
```shell
dagster asset materialize --partition-range-start 2024-02-02 --partition-range-end 2024-03-04 ...
```

**Comment by Gw1p** [comment]
Isn't this already available via "partition_range"?

**Comment by cmpadden** [comment]
> Isn't this already available via "partition_range"?

Hi @Gw1p , that looks to be correct. @briantu implemented `--partition-range` in September after this issue was created.
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/46f68393-5979-4e32-a881-465ebb6ad6dc" />
