### ISSUE TITLE
Issue with docs rendering times new roman font.

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#2158]
All code snippets look like this on my browser (chrome) Version 79.0.3945.130 (Official Build) (64-bit). It seems the font is not rendering correctly. No errors are being thrown on the console log.

![Screen Shot 2020-02-13 at 3 34 43 PM](https://user-images.githubusercontent.com/4219809/74489093-0d567280-4e79-11ea-9a3a-c763359ea49f.png)

**Comment by mgasner** [comment]
https://dagster.phacility.com/D2046
