### ISSUE TITLE
is_optional should be deprecated for OutputDefinition? 

### ISSUE THREAD

**Issue by zzztimbo** [dagster-io/dagster#2162]
When I was refactoring my code to upgrade to 0.7.0, I saw a bunch of warnings: ```"is_optional" deprecated in 0.7.0 and will be removed in 0.8.0.```. I globally replaced `is_optional=False` with `is_required=True` and that broke things. OutputDefinition still has an `is_optional` field. 

Should this:

https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/definitions/output.py#L29-L33

be refactored to have a similar migration to `is_required` as this:

https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/config/field.py#L213-L220

**Comment by alangenfeld** [comment]
@schrockn - thoughts?

**Comment by schrockn** [comment]
Seems like a great idea @zzztimbo. Thanks for suggestion!

**Comment by catherinewu** [comment]
Just landed a [fix](https://dagster.phacility.com/D2122) for this, will go out in the release tomorrow
