### ISSUE TITLE
dagster schedule commands throw UserWarning

### ISSUE THREAD

**Issue by zzztimbo** [dagster-io/dagster#2164]
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/4597/74577299-4e1abe00-4f43-11ea-8290-ce8fd41bfc27.png">

Seems like a similar issue that was happening in the runs storage. 

https://github.com/dagster-io/dagster/blob/6d117bd43e87a8f7d434436e73d0cf024db0dead/python_modules/dagster/dagster/core/storage/runs/sqlite/sqlite_run_storage.py#L40-L45

`check_alembic_revision` expects a connection, not an engine.

https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/storage/schedules/sqlite/sqlite_schedule_storage.py#L39-L43

**Comment by mgasner** [comment]
https://dagster.phacility.com/D2057

**Comment by prha** [comment]
Thanks for the report... fix will go out with the next release next week
