### ISSUE TITLE
DagsterInvalidConfigError not return in the UI

### ISSUE THREAD

**Issue by alvarogomezuria** [dagster-io/dagster#21654]
### Dagster version

1.7.4

### What's the issue?

Issue started after upgrading to the latest version ([1.7.4](https://github.com/dagster-io/dagster/releases/tag/1.7.4)).

When trying to run a job that needs an Env Var set (use ), it loads forever without returning any failure pop up. In the past, we used to receive an immediate popup pointed that the Env Var XXXX is not set.

Currently, the only way to figure out what is going on is by inspecting the graphQL API call in the Chrome dev tool. I found the following error message:

`"dagster._core.errors.DagsterInvalidConfigError: Error in config for job YYYY\n    Error 1: Post processing at path root:resources:instagram_insights:config:access_token of original value {'env': 'XXXXXXX'} failed:\ndagster._config.errors.PostProcessingError: You have attempted to fetch the environment variable \"XXXXXXX\" which is not set. In order for this execution to succeed it must be set in this environment.\n\nStack Trace:\n  File \"/usr/local/lib/python3.10/site-packages/dagster/_config/post_process.py\", line 79, in _post_process\n    new_value = context.config_type.post_process(config_value)\n  File \"/usr/local/lib/python3.10/site-packages/dagster/_config/source.py\", line 40, in post_process\n    return str(_ensure_env_variable(cfg))\n  File \"/usr/local/lib/python3.10/site-packages/dagster/_config/source.py\", line 16, in _ensure_env_variable\n    raise PostProcessingError(\n\n"`

### What did you expect to happen?

To receive a popup with the proper error message as it was before.

### How to reproduce?

You just need to have an invalid config of your job and try to execute it from the UI.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by salazarm** [comment]
This will be fixed in the release next week. Sorry for the confusion!
