### ISSUE TITLE
[dagster-graphql] Add method for terminating job runs to DagsterGraphQLClient

### ISSUE THREAD

**Issue by garethbrickman** [dagster-io/dagster#21695]
### What's the use case?

The GraphQL API itself has a `​terminateRun`​ mutation ­[documented here](https://docs.dagster.io/concepts/webserver/graphql#terminate-an-in-progress-run) as well as a `terminateRuns` mutation that can take multiple Run IDs. 

Both of these should be supported[ in the GraphQL Python Client](https://docs.dagster.io/concepts/webserver/graphql-client#graphql-python-client).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by baumann-t** [comment]
Hello @garethbrickman

Just to clarify the required enhancements: The function terminate_run already exists in the client, as seen here: [terminate_run function](https://github.com/dagster-io/dagster/blob/cebe7938f02a8751a039d2e5736c9f0f2be0c855/python_modules/dagster-graphql/dagster_graphql/client/client.py#L377).

Would you like to add a terminate_runs function to the client that can handle multiple Run IDs simultaneously, similar to the terminateRuns mutation in the GraphQL API? If so, I'm ready to start working on this feature. Please let me know if you have any specific requirements or suggestions!

Thank you!

**Comment by garethbrickman** [comment]
@baumann-t Thanks for pointing that out! I'll make a PR to update [the docs](https://docs.dagster.io/concepts/webserver/graphql-client#overview) to show that function is indeed available.

Would be great to work on a `terminate_runs` function with you! 👍

**Comment by baumann-t** [comment]
Good morning @garethbrickman, I just opened a PR for the `terminate_runs` function, including the unit tests: https://github.com/dagster-io/dagster/pull/21775 

Let me know what you think!

**Comment by garethbrickman** [comment]
@baumann-t Amazing thank you! Will block some time to review this next week. I'll keep you posted in the PR 👍
