### ISSUE TITLE
Auto-materialize daemon caught an error: KeyError for an old non-existent asset

### ISSUE THREAD

**Issue by jlloyd-widen** [dagster-io/dagster#21692]
### Dagster version

1.7.4

### What's the issue?

I'm getting the following error in the daemon:
```
2024-05-07 16:49:43 +0000 - dagster.daemon.AssetDaemon - ERROR - Auto-materialize daemon caught an error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/dagster/_daemon/asset_daemon.py", line 731, in _process_auto_materialize_tick_generator
    stored_cursor = _get_pre_sensor_auto_materialize_cursor(instance, asset_graph)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_daemon/asset_daemon.py", line 137, in _get_pre_sensor_auto_materialize_cursor
    backcompat_deserialize_asset_daemon_cursor_str(
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/definitions/asset_daemon_cursor.py", line 224, in backcompat_deserialize_asset_daemon_cursor_str
    partitions_def = asset_graph.get(key).partitions_def if asset_graph else None
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/definitions/base_asset_graph.py", line 184, in get
    return self._asset_nodes_by_key[asset_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: AssetKey(['salesforce', 'salesforce_orders'])
```

The asset key mentioned is an old dbt asset that no longer exists. I even went into the backend postgres database and deleted any rows in any tables that had `asset_key = '['salesforce', 'salesforce_orders']'`. I rebooted the daemon pod and even pushed a new image but this error still persists. I have no idea where it's even getting the idea to search for this asset. It doesn't appear that automaterialization will work at all with this happening at every tick.

### What did you expect to happen?

I expect it to run without error and probably produce some run requests.

### How to reproduce?

I'm not sure how reproducible this is. It seems like a case of things getting into a funky state.

### Deployment type

Dagster Helm chart

### Deployment details

Deployed in a kubernetes cluster and a postgres backend. I'm on a FIPS enabled system, though I doubt that's related. Python version 3.11.5.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @jlloyd-widen, thanks for flagging this. The solution you arrived at is reasonable and won't cause you any issues going forward. This issue will be addressed more completely via: https://github.com/dagster-io/dagster/pull/21714
