### ISSUE TITLE
Design interactions between Dagster retries and retries in lower-level systems

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2169]

**Comment by catherinewu** [comment]
This was something we ran into with celery k8s, where we were a bit lucky that since k8s enforces unique job ids this meant that only retries instigated from the dagster system would succeed.

**Comment by alangenfeld** [comment]
It's not clear to me how to act on this issue, I guess I'm skeptical that there is a broad or overarching policy that we can apply. I expect us to more so handle this in specific interactions as they come up.

I'm not certain of that stance so will leave open.

**Comment by johannkm** [comment]
Cancelling, the status-quo is that we'll offer dagster retries on top of the system, but not support native retries since the complexity it brings
