### ISSUE TITLE
"dagster code-server start" and "dagster api grpc" do _not_ take the same arguments

### ISSUE THREAD

**Issue by leejlFG** [dagster-io/dagster#21698]
### What's the issue or suggestion?

Title basically explains it all - auto-reloading the code location via GraphQL in OSS deployments requires the `code-server start` command in lieu of the `api grpc` command, but the arguments are not the same as written [here](https://github.com/dagster-io/dagster/blob/23f1ab75325f9be98de2ae748eaf820ab3592327/helm/dagster/values.yaml#L311) and [here](https://github.com/dagster-io/dagster/blob/23f1ab75325f9be98de2ae748eaf820ab3592327/helm/dagster/charts/dagster-user-deployments/values.yaml#L42). The good solution is to make them actually match, but the easy solution is to just not say that they do.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by philiporlando** [comment]
@skittlejohn, would you mind sharing more about your OSS deployment? Is there a repo you can point to?

I know hot reloading Docker Compose deployments is something that several other devs (including myself) are actively trying to solve for in #30824.

**Edit:** it looks like hot reloading is [not supported with docker compose deployments](https://github.com/dagster-io/dagster/discussions/14709#discussioncomment-12010661). I'm going to explore using devcontainers with a single Dockerfile that runs the `dagster dev` command for my development environment, and use a separate docker compose deployment for production.
