### ISSUE TITLE
Remove deltalake upper version bound in dagster-polars!

### ISSUE THREAD

**Issue by ion-elgreco** [dagster-io/dagster#21759]
### Dagster version

1.7.5

### What's the issue?

The upper bound of deltalake in dagster-polars needs to be removed.

That one failing test simply needs to be skipped. The issue only happens in edge cases, which I've already fixed in deltalake and will be released in next bugfix release.

It's bad practice, to upper limit a package for such a small bug. For that 0.0001% you might run into an issue, now all environments can't upgrade deltalake if you use dagster-polars...

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
@ion-elgreco Could you let us know when the deltalake bugfix is released? Can then put in a PR for unpinning the version and see how that test goes 👍

**Comment by ion-elgreco** [comment]
@garethbrickman I pushed a new release
