### ISSUE TITLE
Support dbt-core 1.8+

### ISSUE THREAD

**Issue by cbini** [dagster-io/dagster#21774]
`dbt-core` just released version 1.8: https://github.com/dbt-labs/dbt-core/releases/tag/v1.8.0

It would be great if we could get this vetted and supported in an upcoming release.

https://github.com/dagster-io/dagster/blob/b1a12e0873d19cb9f81587d7e725d83df0edcb3b/python_modules/libraries/dagster-dbt/setup.py#L40

**Comment by rbaker1** [comment]
I can take this

**Comment by robele-dooly** [comment]
I can take this

**Comment by lydialimlh** [comment]
Would anyone be able to provide an ETA, for compatibility with dbt-core 1.8?

**Comment by robele-dooly** [comment]
> Would anyone be able to provide an ETA, for compatibility with dbt-core 1.8?

I'm hoping to submit PR in a few hours. I'm not sure if someone else has joined yet

**Comment by robele-dooly** [comment]
PR Draft - https://github.com/dagster-io/dagster/pull/21831

**Comment by rexledesma** [comment]
I'll handle this in the next week or two. Supporting `dbt-core==1.8.*` requires some surgery in the framework since some internal methods from `dbt-core` moved around, so this change isn't as simple as relaxing the pin.

**Comment by rexledesma** [comment]
Resolved in https://github.com/dagster-io/dagster/pull/21908. Support for `dbt-core==1.8.*` will come out in `dagster==1.7.7` and `dagster-dbt==0.23.7`!

**Comment by cbini** [comment]
nice! any chance of an off-cycle release for this?

**Comment by rexledesma** [comment]
We're not planning on an off-cycle release for this, since there's a workaround for users (pinning `dbt-core<1.8`). It will come out next Thursday (5/23).
