### ISSUE TITLE
maybe consolidate S3FileHandle and S3Coordinate 

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2178]

**Comment by sryza** [comment]
@mgasner any opinion on which should stick around and which should go?

**Comment by schrockn** [comment]
They are two distinct concepts. One if just the bucket, key pair (S3Coordinate). One is tied to semantics of the FileManager. S3FileHandle should *contain* an S3Coordinate. Assigning to sandy who is looking at integrations.

**Comment by catherinewu** [comment]
given nick's comment, going to close issue fyi @sryza
