### ISSUE TITLE
Test Schedule "Open in Launchpad" not working

### ISSUE THREAD

**Issue by moleary-gsa** [dagster-io/dagster#21804]
### Dagster version

dagster, version 1.7.5

### What's the issue?

When testing a schedule the "Open in Launchpad" button opens a new tab and redirects to the job overview for the job associated with the schedule. 

This is happening on every schedule and all ticks I test the schedule on. 

I haven't made any changes to the config to cause this and the schedules submit runs successfully under normal operation.

Just to note this behavior had happened  before intermittently and got better with recent releases but has stopped working completely since latest release.

I am completely in the dark as to why this might be happening, no errors are shown and the schedule evaluation shows green when testing. If there are rules in the background governing whether it is possible or not to open a launchpad view then it should be clear to me why my config / setup isn't allowing it.

I also can't seem to access the launchpad via entering the playground url for any job for some reason which may be related.

### What did you expect to happen?

I expected the new tab to open in a launchpad with the config generated by the schedule evaluation pre-populated.

### How to reproduce?

Attempt what I suggested in the problem description.

### Deployment type

None

### Deployment details

Local deployment and docker compose deployment

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by salazarm** [comment]
This will be fixed in this weeks release.
