### ISSUE TITLE
dagster/max_runtime tag does not seem to work

### ISSUE THREAD

**Issue by cwe5590** [dagster-io/dagster#21813]
### Dagster version

dagster, version 1.7.5

### What's the issue?

I am not able to get the max_runtime feature to work properly in my production deploy in k8s nor with a contrived example (see below). I'm not sure this still works, but I'm likely missing something obvious.

```
@op
def my_op():
    time.sleep(30)

@job(tags={"dagster/max_runtime": 10})
def my_job():
    my_op()
```

https://docs.dagster.io/deployment/run-monitoring#general-run-timeouts

### What did you expect to happen?

I would expect the above contrived example to fail due to timeout

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Did you enable  `run_monitoring` in your `dagster.yaml` file?

```# Opt in to run monitoring
run_monitoring:
  enabled: true
```

**Comment by cwe5590** [comment]
I have not enabled that so that explains it. Thanks @garethbrickman
