### ISSUE TITLE
GraphQl error on launching and fetching data from Dagster

### ISSUE THREAD

**Issue by achintamiri** [dagster-io/dagster#2186]
Actual Result : On running dagit-cli ,GUI is throwing graphql error as show in the attched screenshot.

Expected Result : GUI should create and run Dagster Pipeline 

![image](https://user-images.githubusercontent.com/48036519/74977948-9a726c00-5423-11ea-8a73-ee342b5369c1.png)

**Comment by schrockn** [comment]
Fixed in https://dagster.phacility.com/D2084 which should be going out today with 0.7.1

**Comment by schrockn** [comment]
will let @alangenfeld once it is confirmed out
