### ISSUE TITLE
Cannot execute Docker runs 

### ISSUE THREAD

**Issue by nrsmac** [dagster-io/dagster#21990]
### Dagster version

1.7.3

### What's the issue?
docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker

Not sure what happened, but as of today I cannot materialize any assets. Everything mounted properly and docker compose stands up the instance just fine. Probably something to do with Docker 24.0.5?
![image](https://github.com/dagster-io/dagster/assets/8288816/e0c0f41e-1268-4e4d-8764-679ce86f4a3b)

### Deployment type

None

### Deployment details

Multi-container deployment:
![image](https://github.com/dagster-io/dagster/assets/8288816/15760bd5-7f1b-4115-982d-cfecb7a320a6)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Combining with https://github.com/dagster-io/dagster/discussions/21987 which includes instructions for how to resolve this upstream issue with the Docker python client.
