### ISSUE TITLE
Change library solids to use StringSource instead of String in config

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#2200]
In order to read config values from environment variables, consider doing a comprehensive audit of all of our library solids and convert appropriately.

See the following for reference:
https://dagster.phacility.com/D1956
https://dagster.phacility.com/D2103

**Comment by natekupp** [comment]
We should also handle non-string values from the environment, e.g. for port specification https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-postgres/dagster_postgres/utils.py#L25

**Comment by jbrambleDC** [comment]
I've handled StringSource in the places that I thought make sense. Should we do the same with IntSource?

**Comment by jbrambleDC** [comment]
Since we've merged this: 
https://dagster.phacility.com/D3268

I am marking this as complete!
