### ISSUE TITLE
Solid Selector Search not strict filtering

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#2201]
If you load `dagit/dagit_tests/stress/megadags.py` and type `1000_nodes_solid_2`, instead of searching from the dependencies of _2, it will also grab the relations for _20, _21, _22, etc. This looks like the following and is not a great experience:

![Screen Shot 2020-02-24 at 4 07 34 PM](https://user-images.githubusercontent.com/4219809/75202470-318b3c80-5720-11ea-9bad-21c9e09e59e0.png)

**Comment by bengotow** [comment]
Ahh yeah this is an interesting case. Right now the query input box auto-completes to full solid names, but if a solid name is a subset of another solid name it's effectively autocompleting to a partial match string, leading to the behavior above.

I think that one solution to this would be to require explicit wildcards if you want to fuzzy-match. Eg: `1000_nodes_solid_2%` (Would be kind of nice to use * but that's taken 😅 ) We could also remove fuzzy matching altogether, but I'd defer to @schrockn  on that one. It does seem somewhat helpful to be able to query for `redshift_` and see a bunch of things, but that may be better implemented via tags.

**Comment by mgasner** [comment]
another thing we could do is have `sub,` filter only for `sub` but `sub` filter for `sub` and `subset`

**Comment by schrockn** [comment]
I think this is just a function of substring matching and the way it works. I think the behavior is fine given other tradeoffs at play
