### ISSUE TITLE
Hovering over version in Dagit flashes rapidly instead of showing instance info

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2205]
![captured](https://user-images.githubusercontent.com/609349/75278934-98abfe00-57bf-11ea-810d-1362c3901b69.gif)

**Comment by bengotow** [comment]
Oof. It looks like this happens specifically when the browser window is too short to show the contents of the popover without it being pushed down. The popover opens, covers the mouseover target, causes the popover to close, which then reveals the mouseover target, etc.

I think the best solution might be to make that popover two columns / better formatted / link to a full page of information. It's 800px tall on my machine and seems like it will continue getting more info.

**Comment by natekupp** [comment]
+1 for better formatting / link to a full page.

I think this info is going to be super important for debugging when our users hit issues so would be great to make it easily accessible (maybe even a direct link/URL?) 

A click-to-copy button might also be good to have here.

**Comment by natekupp** [comment]
yeah, hit this again today :| makes debugging instance issues tough

**Comment by natekupp** [comment]
No longer an issue w/ new Dagit UI
