### ISSUE TITLE
Missing env var causes silent failure of materialization from UI

### ISSUE THREAD

**Issue by somiandras** [dagster-io/dagster#22145]
### Dagster version

1.7.4

### What's the issue?

I created a new configurable resource that relies on an environment variable in the definition, like `MyNewResource(api_token=EnvVar("MY_API_KEY"))`, but forgot to actually set the env var in my user code container. When I tried to materialize my assets that used this resource from the UI, clicking the Materialize button did nothing, no runs launched, no error toasts, just the spinner on the button. The browser console did show some 500 apollo error, but other than that the whole thing failed silently. Setting the env var immediately solved it.

### What did you expect to happen?

I think this error should not be swallowed, I should have received some clear indication that an env var is missing.

### How to reproduce?

See above.

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
This should be fixed by upgrading to >1.7.5 https://github.com/dagster-io/dagster/issues/21654
