### ISSUE TITLE
Launchpad on asset shows all resources instead of the required ones

### ISSUE THREAD

**Issue by ion-elgreco** [dagster-io/dagster#22142]
### Dagster version

1.7.7

### What's the issue?

When opening  the launchpad for an asset materialization, it will show all resources. In our case that's 30+, even though 1-3 might be required.

The launchpad of an asset job actually does only the required resources. So there must be a difference in the implementation there, perhaps the asset materialization is not properly filtering to the required resources config.

### What did you expect to happen?

Only show required resources like in the job launchpad.

### How to reproduce?

Add a bunch of resources in definitions, add 1 resource to your asset and open launchpad of that asset. It will show all the resources instead of that 1 resource.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
I think this may duplicate https://github.com/dagster-io/dagster/issues/21308 ?

**Comment by ion-elgreco** [comment]
Ah missed that one, I couldn't find a similar issue before! @garethbrickman
