### ISSUE TITLE
Evaluate approaches to cross-pipeline dependencies and implement

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2217]
Title is a placeholder, since we've discussed this many times. Probably don't want to just blindly implement this (external task sensors in Airflow are super problematic). Ideally we design something from first principles that fits with our current abstractions (solid/composite/pipeline/repository) in a natural way.

The use case: consider an organization that has a core set of data pipelines written by a central data team and ingested hourly, with many other downstream daily pipelines written and owned by various product teams, each of which is scheduled daily.

Effectively we should support the state where most of an organization's data processing tasks are _somehow_ connected, but authored and maintained by different teams/individuals and scheduled on different intervals.

**Comment by schrockn** [comment]
Suspect this will be roped into project "instigation policy" work at some point

**Comment by catherinewu** [comment]
Going to close this thanks to release of sensors. I think there's still more work to do wrt to visualizing the data dependencies introduced via sensors in dagit, but those can probably be filed in specific separate issues
