### ISSUE TITLE
Add option to execute backfills serially

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2218]
Backfills currently run according to run launcher behavior. We should implement a way to explicitly set serial vs parallel backfill behavior in the backfill cli

**Comment by natekupp** [comment]
and tbh more generally backfill strategy, e.g. newest-to-oldest vs. oldest-to-newest

**Comment by natekupp** [comment]
Should be fixed by https://dagster.phacility.com/D2244 and https://dagster.phacility.com/D2328
