### ISSUE TITLE
Rename all runtime_type properties on all definitions to dagster_type

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2220]
Missed this in our rename. We should eliminate all references to runtime type in the codebase.

**Comment by yuhan** [comment]
Renamed runtime_type properties and relevant functions in core.definitions.* in 0.7.3
The rest are (1) in StepInputData and StepOutputData in core.execution.* and (2) call sites in examples

**Comment by yuhan** [comment]
followup issue to do the deprecation cleanup in next major release: https://github.com/dagster-io/dagster/issues/2246
