### ISSUE TITLE
Adding DBT Unit Tests Break Dagster Repo

### ISSUE THREAD

**Issue by cwe5590** [dagster-io/dagster#22216]
### Dagster version

dagster, version 1.7.7

### What's the issue?

Adding unit tests to my DBT project breaks my Dagster project. This seems to be occurring because the unit_tests are omitted  when the manifest is de-serialized into <class 'dbt.contracts.graph.manifest.Manifest'>. FWIW, I pass the manifest as a json string into dbt_assets decorator. I can confirm that the manifest has unit tests at manifest.unit_tests.

Manifest.unit_test returns an empty dictionary/set and thus this logic doesn't capture the unit test unique ids in the handler below in the dbt.graph.selector._is_graph_member function

```
elif unique_id in self.manifest.unit_tests:
    return True
```

Error

```
The above exception was caused by the following exception:
KeyError: 'unit_test.business_intelligence.[OBFUSCATED].test_value'

  File "/Users/chris/.pyenv/versions/3.12.3/envs/dagster-bi/lib/python3.12/site-packages/dbt/graph/selector.py", line 186, in _is_graph_member
    node = self.manifest.nodes[unique_id]
```

### What did you expect to happen?

Unit tests to be correctly loaded

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by wmairinger-bsci** [comment]
Hello. We are seeing the same error with unit tests.
