### ISSUE TITLE
Partition definition for pipelines

### ISSUE THREAD

**Issue by mnguyen-daparto** [dagster-io/dagster#2222]
Hi everyone,

I think about switching to Dagster and so far enjoying its easy to use API.
I read the guide for partitioning and scheduling for solids. Is it possible to use partitioning for whole pipelines?

Currently I iterate over a set of countries and pull data from our application databases and Google Analytics into a table. It would be handy if I could just iterate over my country set and run the pipeline for each country and day.

It might be possible, I don't know cause I'm pretty new to Dagster.
Thanks. :)

**Comment by helloworld** [comment]
Hey @mnguyen-daparto,

> Is it possible to use partitioning for whole pipelines?

Could you clarify what you mean by this? Currently, partition sets are tied to pipelines, and you can generate config for a partition however you'd like. 

> It would be handy if I could just iterate over my country set and run the pipeline for each country and day.

I believe you're alluding to 2-D partition sets, with one axis being time and the other being a fixed-length set (in your case countries). This is something we don't currently have but definitely want to support as a first-class feature. 

For now, what you can do is have a date-partitioned schedule, like the one defined in the guide [here],(https://dagster.readthedocs.io/en/stable/sections/learn/guides/partitioning/schedule_partitions.html) and just iterate over every country within your solid. 

```python
@solid
def process_analytics(context):
    date = context.solid_config['date']
    for country in ['US', 'CA', 'MX', ...]:
        # Do analysis here

@pipeline
def data_pipeline():
   process_analytics()

@daily_schedule(
    pipeline_name='data_pipeline', start_date=datetime.datetime(2020, 1, 1),
)
def daily_data_pipeline(date):
    return {
        'solids': {
            'process_analytics': {  'config': { 'date': date.strftime("%Y-%m-%d") } }
        }
    }
```

**Comment by mnguyen-daparto** [comment]
Hi,

I might missunderstood the documentation. I think I'll try it the way you described.
Thanks for that! Just another question. If let's say my process_analysis step fails for country 'MX' and I have to restart the pipeline it will start all over again right? Like it would start  with 'US' then 'CA' and 'MX' right?

**Comment by helloworld** [comment]
Sorry for the delayed response to this – I missed your reply. 

In the example I constructed above, you are correct – since we're just using a for-loop to go through the countries in `process_analysis`, retrying the pipeline run means we would iterate through all the countries again when we run the `process_analysis` step. If you need to be able to retry a pipeline run such that only the steps for failed countries are re-executed, I can help walk you through constructing a pipeline that enabled that. 

As for passing the country and date to several solids by only defining it once in the root config, you can use a [composite_solid](https://docs.dagster.io/latest/api/apidocs/solids/#composing-solids) and it's `config_fn`.

**Comment by mnguyen-daparto** [comment]
No problem dude. Happens sometimes. :)
Okay yeah I see.

Sounds great tbh. If there is a tutorial or guide for this just send me the link. Don't want to bother you with that stuff. Cheers mate!

**Comment by mnguyen-daparto** [comment]
No problem!

I tried to understand the PipelineDefinition class but I think it would be great if you could provide an example of how to use PipelineDefinition and composite_solid in my case.
Only thing I need is to pass a date and a country to a couple of solids.

**Comment by catherinewu** [comment]
Since this is a stale issue, going to close for now. Feel free to reach out to us on slack and we'd be happy to clarify follow ups + provide example code: https://dagster-slackin.herokuapp.com/
