### ISSUE TITLE
Tags missing from Multi Graph Asset

### ISSUE THREAD

**Issue by CamFromStar** [dagster-io/dagster#22239]
### Dagster version

1.7.7

### What's the issue?

When defining a multi graph asset and assigning each output with tags, the tags do not register. They cannot be found in the asset catalog using the UI.  Nor will they be found when using the AssetSelection.tag() method.

### What did you expect to happen?

Multi graph assets should have tags assigned to them when defined in their decorator.

### How to reproduce?

Create a multi graph asset:
```python
@graph_multi_asset(
    outs={
        'asset_1':AssetOut(tags={'tag_a':'true'}),
        'asset_2':AssetOut(tags={'tag_a':'true'}),
    },
)
def multi_asset_1():
    #do something
```
Add asset to definitions.
Open asset_1 or asset_2's asset catalog in the UI.  Notice the tags are missing.

### Deployment type

Docker Compose

### Deployment details

Tested using docker compose, but also just with running dagster dev.  The issue happens either way.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
thanks for the report - i believe #22289 should resolve this
