### ISSUE TITLE
DBT asset causes `All assets in a job must share the same BackfillPolicy` error

### ISSUE THREAD

**Issue by aaaaahaaaaa** [dagster-io/dagster#22254]
### Dagster version

1.7.6

### What's the issue?

Since `dagster 1.7.6` and `dagster-dbt 0.23.6`, DBT assets are raising the following error when loading:
```
UserWarning: Error loading repository location <NAME>:dagster._core.errors.DagsterInvalidDefinitionError: Asset job <JOB_NAME> materializes assets with varying BackfillPolicies. All assets in a job must share the same BackfillPolicy.
```

When debugging where the exception is raised [here](https://github.com/dagster-io/dagster/blob/8b8d61abe654bcbd71147b52eedf747faac2452b/python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py#L190), it's clear that the DBT asset is the one causing the issue. It's the only asset with a different value for the backfill policy:
```
> [n.backfill_policy for n in executable_nodes if n.is_partitioned]
00: None
01: None
...
24: None
25: None
26: BackfillPolicy(max_partitions_per_run=None)    <--- That's the DBT asset
27: None
```

* We're not setting the `backfill_policy` anywhere for any of our assets. Normal asset nor DBT assets.
* Our project has always been functional prior to `1.7.6` and `0.23.6`.
* The project loads successfully when rolling back to `1.7.5` and `0.23.5`.

### What did you expect to happen?

Project and assets to load successfully.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by the4thamigo-uk** [comment]
I encountered this also. https://github.com/dagster-io/dagster/pull/21259#issuecomment-2145642687

**Comment by mgierada** [comment]
@aaaaahaaaaa @the4thamigo-uk  Yeah I kind of resolve that issue for my dbt assets just by being explicit and setting the same backfill policy - in your case  `BackfillPolicy(max_partitions_per_run=None)` for all dbt assets. In my case the partitioned ones ware causing some headaches.

**Comment by mgierada** [comment]
This is kind of related to this feature request I raised here 
- https://github.com/dagster-io/dagster/issues/22356

**Comment by the4thamigo-uk** [comment]
@mgierada That would be fine except for the fact that I have a job that executes unpartitioned dbt assets and partitioned ones. My dbt project is split into two separate `@dbt_asset` multi assets. One contains the unpartitioned dbt models, and the other contains the partitioned dbt models. Unfortunately, dagster-dbt forces me to have to specify `BackfillPolicy::single_run()` for the unpartitioned `@dbt_asset`.

**Comment by mgierada** [comment]
@the4thamigo-uk I feel you. I am facing the same issue in my project. I raised a feature request #22356 that would be a workaround or permanent fix, depending on the context.

**Comment by the4thamigo-uk** [comment]
I think the best thing to do is to revert to 1.7.5 and wait for a proper fix.

**Comment by the4thamigo-uk** [comment]
New release seems to fix the issue: https://github.com/dagster-io/dagster/releases/tag/1.7.10
