### ISSUE TITLE
Test to catch dagit crash looping 

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2227]
See https://dagster.phacility.com/D2167 for context - right now dagit could be totally broken in our k8s deployment and our tests would not cover that case.

If we changed to

```success, _ = wait_for_pod('dagit', wait_for_readiness=True)```

In the k8s test suite, we could ensure dagit is in a good state; however, this would mean the test image would need to include a `make rebuild_dagit` so that dagit is actually up. Unfortunately, that adds 2-3+ mins to the critical path of our test suite, so not really a good option, and we should find some other way to get coverage here.

**Comment by alangenfeld** [comment]
hmm - we don't need to do the js build for the health check endpoint to work. There might be a way forward if we setup dagit to degrade gracefully when the js build didn't happen in a dev build

**Comment by natekupp** [comment]
oh that's a good idea. Might want that to be something we explicitly opt into w/ a CLI flag, since by default we presumably *do* want health checks to fail if the js build didn't happen

**Comment by catherinewu** [comment]
im not sure i follow how "health checks to fail if the js build didn't happen" would work? another possibility is to use a separate bk ModuleBuildSpec that only runs `make rebuild_dagit` and checks that dagit pod is healthy so as to not add any time on the critical path

**Comment by johannkm** [comment]
Solved with @gibsondan 's conversion of integration tests to use gql
