### ISSUE TITLE
Dagit playground solid sub-selection solid explorer view doesn't expand composite solids

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#2231]
When I am using the dagit playground. I am trying to figure out what solids to sub-select, however, when I use the provided solid explorer I cannot expand composite solids.

![Screen Recording 2020-03-02 at 4 04 18 PM](https://user-images.githubusercontent.com/4219809/75729865-fd73c680-5c9f-11ea-8800-aacd9c6a75be.gif)

**Comment by hellendag** [comment]
Can use the solid selection DSL to accomplish this.
