### ISSUE TITLE
No way to reach into composite solids and select solids via the dagit solid selector

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#2237]
If a user has a mega-pipeline which composes of composite solids that contain more composites, I am unable to select those depth 2 composite solids via the solid selection syntax. I am pretty sure I chose to ignore this when originally building it but this dis-incentivizes mega pipelines because it's hard for me to explore/debug and run small parts of my pipeline via dagit. 

![Screen-Recording-2020-03-03-at-9 35 44-AM](https://user-images.githubusercontent.com/4219809/75803121-be428580-5d32-11ea-91cd-4c461487ac1c.gif)

**Comment by mgasner** [comment]
#1552 #1434

**Comment by schrockn** [comment]
Closing in favor of https://github.com/dagster-io/dagster/issues/1434
