### ISSUE TITLE
Explode composites shows the composite solid name instead of the sub solid names

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#2238]
Clicking explode composites in the pipeline explorer ends up showing a ton of solids with the composite solids under their name. However, when you click on them, the right name shows up in the sidebar. I don't think this was intended behavior. 

![Screen-Recording-2020-03-03-at-9 42 22-AM](https://user-images.githubusercontent.com/4219809/75803846-eda5c200-5d33-11ea-83b2-fc571cb81da0.gif)

**Comment by hellendag** [comment]
> However, when you click on them, the right name shows up in the sidebar. I don't think this was intended behavior.

@asingh16 Can you clarify what you mean? In the gif it does not look like you clicked on any solids, so I'm not sure I follow where the bug is. Thanks!
