### ISSUE TITLE
confusing for an analyst to see celery executor configs on the UI

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2240]
"btw if I specify something in the celery configmap, do I also have to add those values in the presets? because I think it can be confusing for example for an analyst if he/she sees the celery executor configs on the UI, plus it will be more error prone since our hero will be able to modify these configs"

**Comment by schrockn** [comment]
this should be part of entire instance management workstream that we anticipate this summer

**Comment by sryza** [comment]
`configured` should most solve this, except in places where configured doesn't work (e.g. in places where the run launcher counts on being able to extract config (celery-k8s)), but that's tracked elsewhere
