### ISSUE TITLE
improve UnknownPipeline handling

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2241]
Improve the experience of looking at a run from an `UnknownPipeline`. `UnknownPipeline` most commonly surface from doing different runs from different repos in the same instance .

**Comment by alangenfeld** [comment]
post D2186 state
![Screen Shot 2020-03-03 at 2 28 35 PM](https://user-images.githubusercontent.com/202219/75825984-52c0de00-5d5b-11ea-9176-467c5e9f73bf.png)

* nothing at all shown up top in timeline view
* step keys are not shown (since they are fetched from `step.key` which is not present if we cant build the execution plan, fixing this involve schema changes)

**Comment by schrockn** [comment]
Calling resolved with all the snapshots being persisted etc
