### ISSUE TITLE
Fix parameter name in Schedules API docs example

### ISSUE THREAD

**Issue by mnguyen-daparto** [dagster-io/dagster#2243]
Schedules API docs page shows in the @dagster.schedules example a wrong parameter name "cron_string" but it should be "cron_schedule" according to ScheduleDefinition.
I know it's a small one but it could be misleading.

https://dagster.readthedocs.io/en/stable/sections/api/apidocs/schedules.html#dagster.schedules

**Comment by alangenfeld** [comment]
Thanks! Fixed in a28c5dc
