### ISSUE TITLE
[UI] In Asset Graph, asset cards with checks extend past the group border

### ISSUE THREAD

**Issue by askvinni** [dagster-io/dagster#22457]
### Dagster version

1.7.8

### What's the issue?

When assets include checks, the asset group border doesn't seem to scale with the new size of the asset card, this becomes especially apparent when a `compute_kind` is also defined. See screenshot.
<img width="281" alt="Screenshot 2024-06-01 at 15 11 41" src="https://github.com/dagster-io/dagster/assets/53345119/f0c26e2d-0f58-434d-9553-c5c460101438">

### What did you expect to happen?

Asset Group to scale up vertically.

### How to reproduce?

```python
from dagster import AssetCheckResult, Definitions, asset, asset_check

@asset(group_name="raw", compute_kind="pandas")
def my_asset(): ...

@asset_check(asset=my_asset)
def my_check():
    return AssetCheckResult(passed=True)

defs = Definitions(assets=[my_asset], asset_checks=[my_check])
```

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment]
Should be fixed by https://github.com/dagster-io/dagster/pull/22692
