### ISSUE TITLE
[Documentation Feedback] Problem on /dagster-plus/developing-testing/code-locations page

### ISSUE THREAD

**Issue by sowla** [dagster-io/dagster#22463]
I got redirected to this document from Dagster Cloud UI:
<img width="828" alt="Screenshot 2024-06-11 at 17 02 13" src="https://github.com/dagster-io/dagster/assets/19764028/b2e916ff-39d5-4d16-a81a-b7d77fdc5fcd">

and got "404: Not Found" for version "1.7.9 / 0.23.9 (libs)latest" ("1.7.7 / 0.23.7 (libs)" works)

**Comment by garethbrickman** [comment]
Thanks for letting us know, pushing a fix for that! The correct link you can use is: https://docs.dagster.io/dagster-plus/managing-deployments/code-locations
