### ISSUE TITLE
Dagit will not load if non-existent mode is in run storage

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2249]
If a user creates a run with a given mode, and then deletes that mode and tries to re-run dagit, dagit will fail with the following error:

```
dagster.check.CheckError: Failure condition: Could not find mode <MODE_NAME> in pipeline <PIPELINE_NAME> 
```

For example, if we create a run for the following pipeline:

```
@pipeline(
    mode_defs=[ModeDefinition(name="dev")]
)
def my_pipeline():
   ...
```

Then change the pipeline definition to:

```
@pipeline(
    mode_defs=[ModeDefinition(name="prod")]
)
def my_pipeline():
   ...
```

We won't be able to load dagit.

**Comment by helloworld** [comment]
This error specifically happens when you have the page open for a specific run, and therefore the `pipelineRunLogs` subscription running.

**Comment by helloworld** [comment]
Duplicate of https://github.com/dagster-io/dagster/issues/1689

**Comment by schrockn** [comment]
This is resolved will all the snapshot changes. Historical runs always load now
