### ISSUE TITLE
When saving intermediates to disk, execution continues even if dependency is broken.

### ISSUE THREAD

**Issue by maxbarkhausen** [dagster-io/dagster#2251]
When there are intermediates from a previous run and intermediates are saved to and loaded from disk, execution of the graph continues at a node even when a parent node did not exectute. If there are no intermediates from previous runs, it will halt. I would argue that the desired behavior is to always stop executing a pipeline at a node when any of the parents did not execute on the same run.

**Comment by alangenfeld** [comment]
Can you provide some more context on which API you are exercising how and what your expected behavior is? The apis involving `previous_run_id` are not yet set up well for user consumption and are currently focused on resume / retry semantics as opposed to general memoization.

**Comment by maxbarkhausen** [comment]
Apologies, I don't know dagster well enough to know what APIs you're referring to. The behavior occurs when executing a pipeline using Dagit and saving intermediates to disk. What seems unintuitive (and error-prone) to me is that downstream steps in the pipeline will execute if intermediates from a previous have been saved to the base directory, even if their dependencies are broken.

**Comment by prha** [comment]
Hi!

How are you executing a pipeline with previous runs.... are you using the `Resume / Retry` button?

**Comment by prha** [comment]
@maxbarkhausen can you reopen if you're still running into this issue?

Screen caps would be really useful to get a handle on what you're seeing.
