### ISSUE TITLE
DAGSTER_HOME points to wrong directory for `dagster-aws` init script in `dagster-aws` cli environments

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#2253]
See https://dagster.slack.com/archives/CCCR6P2UR/p1583792672247800 for context.

$INSTALL_PATH is not getting interpolated correctly into the `dagster_home.sh` script

**Comment by mgasner** [comment]
reproduced -- on a fresh `dagster-aws init` and then `dagster-aws shell`, we have the following:

```
ubuntu@ip-172-31-27-111:/opt/dagster$ cat /etc/profile.d/dagster_home.sh 
export DAGSTER_HOME=$INSTALL_PATH/dagster_home
ubuntu@ip-172-31-27-111:/opt/dagster$ env | grep DAGSTER
DAGSTER_HOME=/dagster_home
```
