### ISSUE TITLE
Cannot configure partitioned job on the launchpad.

### ISSUE THREAD

**Issue by kriskim8937** [dagster-io/dagster#22552]
### Dagster version

1.7.6

### What's the issue?

We recently updated 1.4.5 to 1.7.6.
After the update, even if I select the partition on the launchpad, it doesn't show up on launchpad properly like the one below and causes error
<img width="572" alt="wrong_partition" src="https://github.com/dagster-io/dagster/assets/40317107/99ca41e2-da5f-4eb9-877b-43adf921ccac">
Error 
<img width="254" alt="partition_error" src="https://github.com/dagster-io/dagster/assets/40317107/2a2eef2d-fa5a-4d5c-80d2-cf2d4fecf0ae">

### What did you expect to happen?

Partition should be added on the launchpad correctly like below
<img width="507" alt="correct_partiton" src="https://github.com/dagster-io/dagster/assets/40317107/3b840840-d201-40dc-b503-8e5774051674">

### How to reproduce?

Update dagster to 1.7.6 and add partition on launchpad

### Deployment type

Dagster Helm chart

### Deployment details

You can reproduce it in local (dagster dev) and helm deployment.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by salazarm** [comment]
Hello @kriskim8937, I haven't been able to reproduce this issue. Is this still happening on 1.7.10? Are there any errors in the terminal running dagster or in the browser console?

**Comment by bengotow** [comment]
I re-tested this in Dagster 1.9 today and I'm not able to reproduce the issue either - I think it's possible that this could happen if your config provider is throwing an exception and failing to return config for the partition that was selected, but we might need more detail to verify that case. Going to close for now.
