### ISSUE TITLE
Something is wrong with float handling in the config editor

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2257]
<img width="697" alt="Screen Shot 2020-03-10 at 5 36 25 PM" src="https://user-images.githubusercontent.com/427016/76370924-b7e57800-62f5-11ea-8cfa-edabfd8b16d1.png">

**Comment by yuhan** [comment]
Can't repo. it seems fine now 
![image](https://user-images.githubusercontent.com/4531914/84093354-d4558700-a9ae-11ea-890b-5c2cd09df9e4.png)

Reopen if you hit it again
