### ISSUE TITLE
Dagster Cloud UI not showing logs for job runs

### ISSUE THREAD

**Issue by misa-nogly-aleksic** [dagster-io/dagster#22605]
### Dagster version

1.7.10

### What's the issue?

Since recently, perhaps a week now, the Dagster Cloud UI hasn't been showing logs for our jobs. For us, this seems to be happening across all recent job executions, even older jobs where we've definitely seen logs in the past.

When I inspect the network traffic, it seems to say the GraphQL queries are coming back slower than expected/desired, and the requests just keep appearing, but no logs are displayed.

<img width="1728" alt="image" src="https://github.com/dagster-io/dagster/assets/102963991/0ae27adc-8884-45db-b183-31d4f1376222">

**Workaround for now** if anyone else is impacted:
![image](https://github.com/dagster-io/dagster/assets/102963991/ff34d105-472d-499d-918a-2c15e32180f0)

### What did you expect to happen?

The logs are shown.

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @misa-nogly-aleksic - if you click on that button that says “Levels (0)” in your screenshot and select some checkboxes, do logs appear? I’m wondering if you have it set so that no logs should be shown. If so, we can make that clearer in the UI that that’s the case.

**Comment by misa-nogly-aleksic** [comment]
OMG 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️  😅

**Comment by misa-nogly-aleksic** [comment]
Yes, that worked. I'm now going to go live in a cave somewhere away from human eyes 😅 . Thanks @gibsondan
