### ISSUE TITLE
add @weekly_schedule

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2263]
requested by a user

**Comment by asingh16** [comment]
@alangenfeld For posterity, did somebody request this? Could you add it to the description? Or is this just because?

**Comment by alangenfeld** [comment]
updated - ya this came up in a call with a user

**Comment by asingh16** [comment]
revision: https://dagster.phacility.com/D2245

**Comment by asingh16** [comment]
landed! Should go out in the next revision!
