### ISSUE TITLE
Make StringSource docs discoverable via search

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2267]
I don't think we document this anywhere yet

**Comment by alangenfeld** [comment]
https://docs.dagster.io/latest/api/apidocs/config/#dagster.StringSource

**Comment by natekupp** [comment]
Hmm maybe this is really a critique of our search, which didn't turn up that page: 

<img width="968" alt="image" src="https://user-images.githubusercontent.com/609349/76780433-43359200-676a-11ea-81d4-b489eee5d294.png">

**Comment by natekupp** [comment]
@alangenfeld I'm going to re-open to track fixing this in search - @mgasner FYI this issue

**Comment by schrockn** [comment]
resolved in new docs site

**Comment by natekupp** [comment]
actually I don’t think this is resolved, @helloworld is planning some search fixes—but maybe we should track a more general “fix docs search” issue. will let @helloworld chime in

**Comment by schrockn** [comment]
Worked fine for me

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )
