### ISSUE TITLE
[exploration] support async solid defs in appropriate python versions

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2268]
should we support `asyncio.run` ing solids ?

```
@solid(...)
async def fancy():
  x = await do_stuff()
  return x
```

should we support async generators in python 3.6+ ?

```
@solid(...)
async def fancy():
  x = await do_stuff()
  yield Output(x)
```

should we have an in process engine that gathers over multiple async solids ?

**Comment by JBrVJxsc** [comment]
Do we have an update on this :) ?

**Comment by JBrVJxsc** [comment]
Or do we have a plan to add an official multi-threading executor?

**Comment by alangenfeld** [comment]
Basic support for handling async and async generator functions to work as solids should land soonish https://dagster.phacility.com/D6017

Proper executor support for in process cooperative multitasking or an official multi-threaded executor will take more work. How we monitor solid execution for example with the `ComputeLogManager` is not currently set up to handle concurrent solids in the same process and will require some substantial rethinking for that context.

**Comment by yuhan** [comment]
closing as `@solid` can now decorate async def functions since 0.11.4. will track work about the proper executor support in a separate issue https://github.com/dagster-io/dagster/issues/4041

**Comment by JBrVJxsc** [comment]
AWESOME!!! THANK YOU!!!
