### ISSUE TITLE
Reorder tests in buildkite so that all we have optimal ordering for debugging via BK and minimum testing time

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2269]
E.g. I think we should frontload more tests that depend on test images that are buillt that are slow (e.g. dagster-k8s) while still keeping lint, black, and dagster/dagster-graphql near the front of the queue for getting fast feedback while developing.

**Comment by FishmanL** [comment]
followup to this issue is 'figuring out how to mark changes as not relevant to all of BK' so that if you update something in an external library you don't nec. have to do full rebuilds?  not sure if this is possible though

**Comment by schrockn** [comment]
I actually think this was a bit of a silly idea on my part. Let's close it.
