### ISSUE TITLE
Regression (v1.7.8) - Increased Time Required to start a dbt Project

### ISSUE THREAD

**Issue by tomsej** [dagster-io/dagster#22709]
### Dagster version

1.7.8

### What's the issue?

I have a quite big dbt project (~2500 models). Prior to the 1.7.8 update, the startup process for local development was relatively swift, taking around 20 seconds. However, post-update, the same process now exceeds 1.5 minutes. Issue persists even without custom code (see below), suggesting the slowdown is linked to version 1.7.8:

**Definition:**
```
from unittest.mock import MagicMock

from dagster import (
    Definitions,
    load_assets_from_package_module,
)

from pipelines.locations.dbt_snowflake import assets

# Definitions
defs = Definitions(
    assets=load_assets_from_package_module(assets),
    resources={
        "dbt": MagicMock(),
    },
)
```

dbt_snowflake.py
```
from pathlib import Path

from dagster import AssetExecutionContext
from dagster_dbt import DbtCliResource, dbt_assets


@dbt_assets(manifest=Path.cwd() / "dbt_snowflake" / "target" / "manifest.json")
def jaffle_shop_dbt_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    yield from dbt.cli(["build"], context=context).stream()
```

I attempted to execute Dagster with the DEBUG log level using the following command: `dagster dev --python-file pipelines/locations/dbt_snowflake/dbt_snowflake_definition.py --code-server-log-level debug --log-level debug`, but it failed to yield additional information regarding the cause of the delay. Could you advise on alternative methods to diagnose the source of this performance issue?

The issue with prolonged startup times is not limited to `dev`; it also occurs in the Linux staging environment, where each step experiences substantial delays.

## Flamegraphs
**1.7.7.**:
![1 7 7](https://github.com/dagster-io/dagster/assets/6624716/eb37b839-8c10-4bf9-8c93-90e13ed76c95)

**1.7.10**:
![1 7 10](https://github.com/dagster-io/dagster/assets/6624716/cf6d5c0b-ccfc-4275-95ce-88474fd7b16b)

## Pyinstruments
**1.7.7.**:
![CleanShot 2024-06-26 at 11 28 25@2x](https://github.com/dagster-io/dagster/assets/6624716/eab5cf78-cdc7-4bb7-9a0f-86230ef46e5d)

**1.7.10**:
![CleanShot 2024-06-26 at 11 26 07@2x](https://github.com/dagster-io/dagster/assets/6624716/a6757fbd-d9eb-4530-bcbe-fefa615c144c)

### What did you expect to happen?

Performance between versions is the same.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jonathanneo** [comment]
Experiencing significant slowdowns too (~7000 dbt models) after upgrading dbt from `1.7.2` to `1.7.12`.

**Comment by rexledesma** [comment]
@tomsej @jonathanneo If you could link your `pyspy` profiles in a speedscope compatible format, that would help our investigation. On our end, we'll investigate and try to reproduce the problem and see if any offending commits landed in `1.7.8`.

**Comment by gibsondan** [comment]
@tomsej if possible could you also run `py-spy` on the following command instead of the "dagster dev" command?

`dagster api grpc -p 4000 --python-file <same file argument you are passing to dagster dev>`

Your definitions are being loaded using that command in a subprocess - that will help us fully understand what the bottleneck is.

Adding `-f speedscope` to the py-spy command will create a JSON file that we can get more detailed information from.

**Comment by sryza** [comment]
Hey @tomsej - thanks for reporting this and for all the detail you included. Based on your pyinstrument output, I suspect I've found the source of the problem: https://github.com/dagster-io/dagster/pull/22874.

**Comment by tomsej** [comment]
@gibsondan Sure, here are json files you requested:

- **1.7.3**: [dagster-1.7.3-2024-07-08T19:20:54+02:00.json](https://github.com/user-attachments/files/16132532/dagster-1.7.3-2024-07-08T19.20.54%2B02.00.json)
- **1.7.12**: [dagster-1.7.12-2024-07-08T19:22:49+02:00.json](https://github.com/user-attachments/files/16132541/dagster-1.7.12-2024-07-08T19.22.49%2B02.00.json)

Let me know if you need something else.

@sryza thanks a lot! Should I test the branch?

**Comment by sryza** [comment]
If you're able to test the branch that would be awesome!

**Comment by tomsej** [comment]
I apologize, unfortunately, I wasn't by my computer. I have tested that branch and it is way better!! Seems even faster then in version 1.7.3!

**Comment by sryza** [comment]
Awesome. That change will be included in this week's release.
