### ISSUE TITLE
Missing imports in `Refactoring assets to use resources` in Dagster Essentials

### ISSUE THREAD

**Issue by kornerc** [dagster-io/dagster#22765]
### What's the issue or suggestion?

In the lesson `Practice: Refactoring assets to use resources` of Dagster Essentials the suggested imports are not complete.

It is stated to update the imports in `assets/metrics.py` to the following:
```python
import requests
from dagster_duckdb import DuckDBResource
from . import constants
from dagster import asset
```

However, the import of `requests` is not needed and the import of `geopandas` and other libraries is missing.

It should instead look similar to that:
```python
from datetime import datetime, timedelta

from dagster import asset
from dagster_duckdb import DuckDBResource
import geopandas as gpd
import pandas as pd

# import plotly.express as px
# import plotly.io as pio

from . import constants
```

(the commented imports are needed for  the asset `manhattan_map`)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment]
@kornerc thank you for your attention to detail, I've opened this pull request to fix the imports as you suggested: https://github.com/dagster-io/dagster/pull/22774.
