### ISSUE TITLE
Upstream_output.definition_metadata doesn't contain the metadata since 1.7.11 for observable Source Assets [REGRESSION]

### ISSUE THREAD

**Issue by ion-elgreco** [dagster-io/dagster#22789]
### Dagster version

1.7.11

### What's the issue?

Since v1.7.11 the `InputContext.upstream_output.definition_metadata` doesn't contain the metadata anymore of the input asset. This is quite problematic since we have IO managers that rely on this metadata of an asset.

with v1.7.11
![image](https://github.com/dagster-io/dagster/assets/15728914/b8a7cb10-56c1-4d91-8b10-e8ae9a8bcdf6)
with v1.7.10
![image](https://github.com/dagster-io/dagster/assets/15728914/f6f6cd67-1a23-4057-aa55-e1fbb57676ed)

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ion-elgreco** [comment]
@garethbrickman Can someone look into this? This breaks all IO managers implementations for source assets

**Comment by sverbruggen** [comment]
@garethbrickman Would really appreciate if if you could make some time for this, seems like a relatively major issue.

**Comment by OwenKephart** [comment]
Hi @sverbruggen @ion-elgreco , are either of you able to create a minimal reproduction of this issue? My attempts haven't been successful here, generally trying things along these lines:

```python
def test_input_manager_with_source_assets() -> None:
    fancy_metadata = {"foo": "bar", "baz": 1.23}

    upstream = SourceAsset("upstream", metadata=fancy_metadata)

    @asset(ins={"upstream": AssetIn(input_manager_key="special_io_manager")})
    def downstream(upstream) -> int:
        return upstream + 1

    class MyIOManager(IOManager):
        def load_input(self, context) -> int:
            assert context.upstream_output is not None
            assert context.upstream_output.asset_key == AssetKey(["upstream"])
            assert context.upstream_output.definition_metadata == fancy_metadata

            return 2

        def handle_output(self, context, obj) -> None: ...

    defs = Definitions(
        assets=[upstream, downstream],
        resources={"special_io_manager": IOManagerDefinition.hardcoded_io_manager(MyIOManager())},
    )
    job = defs.get_implicit_job_def_for_assets([downstream.key])
    assert job is not None
    output = job.execute_in_process()

    assert output._get_output_for_handle("downstream", "result") == 3  # noqa: SLF001
    assert False
```

There _was_ a change which resulted in those system-generated metadata keys (e.g. `dagster/asset_execution_type`) no longer appearing, but that wouldn't impact the user-provided metadata as you're experiencing.

**Comment by ion-elgreco** [comment]
@OwenKephart I have an MRE in my code base, will share it when I arrive back home tonight!

**Comment by OwenKephart** [comment]
Thank you!

**Comment by ion-elgreco** [comment]
@OwenKephart found a way to reproduce it with a slight modification of your example:

```python
from dagster import (
    AssetIn,
    AssetKey,
    ConfigurableIOManager,  # noqa
    DataVersion,
    IOManager,  # noqa
    asset,
    materialize,
    observable_source_asset,
)


def test_input_manager_with_source_assets() -> None:
    fancy_metadata = {"foo": "bar", "baz": 1.23}

    @observable_source_asset(metadata=fancy_metadata)
    def upstream():
        return DataVersion('1')
    # upstream = SourceAsset("upstream", metadata=fancy_metadata)

    @asset(ins={"upstream": AssetIn(input_manager_key="special_io_manager")})
    def downstream(upstream) -> int:
        return upstream + 1

    class MyIOManager(IOManager):
        def load_input(self, context) -> int:
            assert context.upstream_output is not None
            assert context.upstream_output.asset_key == AssetKey(["upstream"])
            assert context.upstream_output.definition_metadata == fancy_metadata
            return 2

        def handle_output(self, context, obj) -> None: ...

    materialize(assets=[upstream,downstream], resources={"special_io_manager": MyIOManager()})
```

```python
AssertionError: assert {'dagster/io_... 'io_manager'} == {'baz': 1.23, 'foo': 'bar'}
  Left contains 1 more item:
  {'dagster/io_manager_key': 'io_manager'}
  Right contains 2 more items:
  {'baz': 1.23, 'foo': 'bar'}
  Use -v to get more diff
```

**Comment by OwenKephart** [comment]
@ion-elgreco thanks for the reproduction, we should be able to get a fix in for next week's release

**Comment by ion-elgreco** [comment]
@OwenKephart thanks!! Much appreciated for the quick fix
