### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by monika-3115** [dagster-io/dagster#22800]
### Dagster version

version 1.7.10

### What's the issue?

Operation name: CapturedLogsSubscription

Message: 'utf-8' codec can't decode byte 0x92 in position 5960: invalid start byte

Path: 

Locations: 

### What did you expect to happen?

materialize

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Duplicates https://github.com/dagster-io/dagster/issues/18755

It's likely your code is outputting non-UTF-8 characters into logs
