### ISSUE TITLE
Refactor our storage APIs

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2282]
This felt much messier than it should to implement: https://dagster.phacility.com/D2259

In particular:

- It feels sketchy to have slightly different, duplicative paths for reading/writing between `FileManager` and `ObjectStore`.
- `FileManager` has the path prefix computed externally and passed in; `IntermediateStore` has `root_for_run_id`.
- The line between IntermediateStore and ObjectStore used to be cleaner; these two objects have bled functionality into each other

We should also unify our testing for storages, similar to how we have this for schedule storage:

https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/utils/test/schedule_storage.py

since our file system / S3 / GCS / and now HDFS would all share the same testing setup

**Comment by mgasner** [comment]
cf. https://arrow.apache.org/docs/python/filesystems.html https://arrow.apache.org/docs/python/generated/pyarrow.fs.FileSystem.html#pyarrow.fs.FileSystem

**Comment by mgasner** [comment]
probably would be good to get the file manager subclasses as thin as the intermediates managers -- could include helpers to make writing these easier for library authors

**Comment by sryza** [comment]
@dpeng817 made significant progress on this.  I'm going to close this and we can open issues for any particular issues.
