### ISSUE TITLE
Dagster 1.6.3 and later import pytest (when available)

### ISSUE THREAD

**Issue by RMHogervorst** [dagster-io/dagster#22830]
### Dagster version

1.6.3

### What's the issue?

I use a sys.modules check to see if pytest is active, if it is certain resource behavior is changed (this is not ideal, but worked wonderfully so far). 
When I upgraded dagster from 1.6.1 to 1.7.9 test resources became active.

I manually checked every dagster version between those to see when this changed. It changed between dagster 1.6.2 and 1.6.3. 

### What did you expect to happen?

I would not expect dagster to load pytest in memory (sys.modules) even if it is installed.

I would only expect pytest to be manually called. as an `import pytest` statement in the tests. 

### How to reproduce?

```bash
rm -fR venv2
python -m venv venv2
source venv2/bin/activate
pip install pytest
pip install dagster==1.6.2 # 1.6.3
python check_imports.py
```

check_imports.py:
```python
import sys
import dagster
if 'pytest' in sys.modules:
    print('pytest found')
```

### Deployment type

Dagster Helm chart

### Deployment details

i believe this is not relevant

### Additional information

This problem occurs only locally because I split the dev dependencies (including pytest) and in production pytest is not installed. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @RMHogervorst - if you pin the pendulum dependency to version 2 instead of version 3 does this go away?

**Comment by RMHogervorst** [comment]
Is there any way I could have figured this out on my own?

**Comment by RMHogervorst** [comment]
relates to https://github.com/sdispater/pendulum/issues/808

**Comment by gibsondan** [comment]
Yeah, that's the one - we are planning to remove our pendulum dependency in dagster 1.8, at which point this should no longer be an issue.
