### ISSUE TITLE
`AutomationCondition.eager` triggers downstream materializations even when source asset data version didn't change

### ISSUE THREAD

**Issue by ion-elgreco** [dagster-io/dagster#22850]
### Dagster version

1.7.12

### What's the issue?

We use extensively observable source assets that return a data version, which sometimes might be the same version between a tick, so they didn't change. Currently the AutomationCondition.eager() will still cause rematerializations for downstream assets, see below. It marks it has updated since tick, but the updated since tick should check whether the previous tick DataVersion has changed with current DataVersion.

![image](https://github.com/dagster-io/dagster/assets/15728914/a3149d97-12f6-4c9e-99ea-9e3fa2b29455)

![image](https://github.com/dagster-io/dagster/assets/15728914/ddc90128-cd8c-4fdd-8143-a5d10c11e295)

Below you can see the reproducible example

### How to reproduce?

```python
from dagster import AutomationCondition, DataVersion, Definitions, asset, observable_source_asset

@observable_source_asset(auto_observe_interval_minutes=2)
def source_asset():
    return DataVersion('1')

@asset(deps=['source_asset'], auto_materialize_policy=AutomationCondition.eager().as_auto_materialize_policy())
def downstream_asset():
    return {"hello":"world"}

defs = Definitions(assets=[source_asset, downstream_asset])

```

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ion-elgreco** [comment]
@OwenKephart can you take a look at this?

**Comment by danielgafni** [comment]
This is still an issue for me. I also have `auto_materialize.respect_materialization_data_versions=true` in my `dagster.yaml`. Very surprising behavior! Just had my entire asset graph re-materialized because of this :(

**Comment by ion-elgreco** [comment]
> This is still an issue for me. I also have `auto_materialize.respect_materialization_data_versions=true` in my `dagster.yaml`. Very surprising behavior! Just had my entire asset graph re-materialized because of this :( 

That must have been a regression because I remember this worked after the fix

**Comment by OwenKephart** [comment]
@danielgafni What dagster version are you on and are you just using the standard `AutomationCondition.eager()`? And are you using an automation condition to kick off the observations or are those being automated via some other method?

**Comment by danielgafni** [comment]
I'm on Dagster Cloud. Using `AutomationCondition.eager()` in all my assets. 
I had to recalculate an upstream asset which in fact produced the same data versions for it's partitions, but it still kicked off downstream runs.

**Comment by ion-elgreco** [comment]
> I'm on Dagster Cloud. Using `AutomationCondition.eager()` in all my assets. I had to recalculate an upstream asset which in fact produced the same data versions for it's partitions, but it still triggered downstream runs.
> 
> I just added `~AutomationCondition.data_version_changed()` to all my assets.

Is that a source asset though? In this old bug it was when the observation was the same version

**Comment by danielgafni** [comment]
No, just a normal asset

**Comment by OwenKephart** [comment]
@danielgafni ah I see -- the `auto_materialize.respect_materialization_data_versions=true` does not have any effect on DA, so the way to configure `AutomationCondition.eager()` to ignore upstream _materializations_ that do not change the data version is with `~AutomationCondition.data_version_changed()` as you have done. I'll make sure that gets added to the docs.

The original issue here is in relation to asset observations (which should respect data versions regardless of that setting).

The reason that materializations are treated differently here is that there are common patterns users can fall into in which data versions will _not_ change even though the underlying data is changing (this often happens when using the dbt integration, for example). So to optimize for the more common case, we take a more relaxed view on data updates for the default automation conditions.

**Comment by danielgafni** [comment]
@OwenKephart it looks like actually this is the condition I'm looking for? 

```py
(
    dg.AutomationCondition.eager() & dg.AutomationCondition.data_version_changed()
) | dg.AutomationCondition.code_version_changed()
```

Not sure why were we talking about  `& dg.AutomationCondition.data_version_changed()`. It should be just `dg.AutomationCondition.data_version_changed()`. The former triggers materializations when the data version *does not change*.

**Comment by danielgafni** [comment]
From the [relevant docs](https://docs.dagster.io/guides/automate/declarative-automation/customizing-automation-conditions/customizing-eager-condition#respecting-data-versioning): 

```py
import dagster as dg

condition = dg.AutomationCondition.eager().replace(
    "newly_updated", dg.AutomationCondition.data_version_changed()
)
```
