### ISSUE TITLE
full run id is not displayed anywhere

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2286]
<img width="1969" alt="Screen Shot 2020-03-16 at 4 01 43 PM" src="https://user-images.githubusercontent.com/427016/76806736-7e05ed00-679f-11ea-8924-38a593eefb87.png">

**Comment by catherinewu** [comment]
i believe this is intentional as the run_id does not have inherent meaning and is easily accessed via clicking the truncated id
