### ISSUE TITLE
Create a dev-dependencies.txt file for docs dependencies

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2290]
Some docs dependencies are not captured in dependencies installed by `make dev_install`, such as `sphinxcontrib-images`. We should have a separate `dev-dependencies.txt` for the docs folder that will let contributors install what they need to build the docs.

**Comment by mgasner** [comment]
these are in `.read-the-docs-requirements.txt`

**Comment by natekupp** [comment]
@helloworld is `.read-the-docs-requirements.txt` good enough for you? might want to rename that file given we're moving away from RTD, but otherwise going to close this unless you think a different approach is warranted

**Comment by helloworld** [comment]
Yeah it was - we also have a PR to add installing pandoc to the installation process.
