### ISSUE TITLE
Option to add asset code as metadata for software defined assets

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#22966]
### What's the use case?

In some cases it'd be great to offer the users of dagster a way to peep at the definition of the software defined assets. 

This is inspired by Kedro where selecting a node offers the code used to define that computation:

![image](https://github.com/dagster-io/dagster/assets/112868935/1b2ebe2d-8d1a-47ad-b3fd-84cb3dcc89c5)

### Ideas of implementation

Not sure what's the cleanest solution - but some form of introspecting the function wrapped by @asset and exposing this within the metadata is my rough idea. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Duplicates https://github.com/dagster-io/dagster/issues/8939
