### ISSUE TITLE
ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#22985]
This failure occurs on python `3.12.4` and we missed it since we test on a lower version of `3.12`

**Comment by cbini** [comment]
thanks @alangenfeld is there a workaround for this too?

**Comment by tenhaus** [comment]
> thanks @alangenfeld is there a workaround for this too?

It's ok in `3.12.3`. I'm sure they'll get it updated soon. dagster team seems super active.

**Comment by alangenfeld** [comment]
(or use python 3.12.3 i guess but I assume pinning dagster is easier)
