### ISSUE TITLE
Be able to rerun a solid if all surrounding execution is successfully

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2303]
See discussion

<img width="692" alt="Screenshot 2020-03-21 18 14 02" src="https://user-images.githubusercontent.com/28738937/77240141-c22e2e80-6b9f-11ea-911d-f7d98e5d2061.png">

@mgasner @yuhan assigning to you because it's adjacent to run grouping stuff

**Comment by schrockn** [comment]
<img width="779" alt="Screenshot 2020-03-21 18 23 48" src="https://user-images.githubusercontent.com/28738937/77240257-230a3680-6ba1-11ea-85a7-67654e70b0e5.png">

Another suggestion is to enable this flow from the command line.

**Comment by mgasner** [comment]
this is now possible from dagit
