### ISSUE TITLE
Implement PipesCloudWatchMessageReader

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#23056]
### What's the use case?

The CloudWatch MessageReader would be pretty useful as many AWS services already produce CloudWatch logs.
With it being implemented users won't have to use "external" message channels such as S3. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by divyanshu-in** [comment]
@danielgafni are you still working on it, I'm interested in this particular issue, let me know if that's the case.
CC: @garethbrickman

**Comment by danielgafni** [comment]
Hey @divyanshu-in, CloudWatch reader has just been merged to master. 

Should be part of the next release.
