### ISSUE TITLE
Config field descriptions not loading from attribute docstrings

### ISSUE THREAD

**Issue by butterlyn** [dagster-io/dagster#23075]
### Dagster version

1.7.13

### What's the issue?

`Config` attribute docstrings (defined in [PEP 257](https://peps.python.org/pep-0257/#what-is-a-docstring) and [PEP 258](https://peps.python.org/pep-0258/#attribute-docstrings)) are not loaded into Dagster as field descriptions.

### How to reproduce?

```Python
from pydantic import Field
from dagster import Config

class MyAssetConfig(Config):
    my_boolean_field: bool = Field(default=False)
    """Description of my boolean field."""
```

Which should load the description into Dagster identically to:

```Python
from pydantic import Field
from dagster import Config

class MyAssetConfig(Config):
    my_boolean_field: bool = Field(
        default=False,
        description="Description of my boolean field.",
    )
```

### Deployment type

None

### Additional information

This functionality is already supported for asset descriptions being loaded from function docstrings.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
`PEP 258` is not an accepted specification, so we don't support this syntax to configure `Config` description.

**Comment by butterlyn** [comment]
@rexledesma PEP 257 is an active PEP that applies to docstring style (PEP 258 is referenced in PEP 257 as an example only). I can assure you that it applies

**Comment by butterlyn** [comment]
Quote from PEP 257 that applies:

![image](https://github.com/user-attachments/assets/2082e103-402c-40a5-b2fc-420bf5d9e766)
