### ISSUE TITLE
Rough error when you pass an uninvoked solid during composition

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2308]
See this conversation

![Screenshot 2020-03-22 14 28 59](https://user-images.githubusercontent.com/28738937/77261135-8ea7de80-6c49-11ea-8a4d-11b6cc3677ce.png)

Just an additional error text indicating that one *might* have done this would be useful? Any way we can do better than what is happening now.

**Comment by natekupp** [comment]
Fixed by https://dagster.phacility.com/D2451
