### ISSUE TITLE
Enabling dbt to fetch row count data causes job failures to go unreported.

### ISSUE THREAD

**Issue by LuanVCL** [dagster-io/dagster#23109]
### Dagster version

1.7.13

### What's the issue?

After enabling the experimental feature:
https://docs.dagster.io/integrations/dbt/reference#fetching-row-count-data
All dbt jobs are reported as being sucessful even if some models failed to materialize.

### What did you expect to happen?

dbt job to be marked as failed.

### How to reproduce?

Enable the feature:

https://docs.dagster.io/integrations/dbt/reference#fetching-row-count-data

### Deployment type

Dagster Helm chart

### Deployment details

This is a minor issue with a experimental feature.

This happened with dagster using helm and local dev with dagster dev.
All relevant python modules are up to date (dagster and dbt ones).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by benpankow** [comment]
Thanks for the report! #23115 should address this issue
