### ISSUE TITLE
Execution plan errors hidden on small screens

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2312]
Now that we do a horizontal split - error message content which is displayed in the bottom of the bottom pane can be missing. Need to update some visual indicator that an error is present that appears on the top of that bottom pane where the preview is.

**Comment by hellendag** [comment]
Do you have a screenshot of this?

**Comment by catherinewu** [comment]
going to close for now. please feel free to re-open with a repro or screenshot
