### ISSUE TITLE
Extend code references git_url to include self-hosted GitLab 

### ISSUE THREAD

**Issue by cooperellidge** [dagster-io/dagster#23135]
### What's the use case?

Currently the git [code reference](https://docs.dagster.io/guides/dagster/code-references#in-any-dagster-environment) feature only works for URLs containing "gitlab.com" and "github.com". This doesn't work with self-hosted GitLab because the string "gitlab.com" is not in "gitlab.self-hosted.xyz".

### Ideas of implementation

Relax the git URL check in [link_code_references_to_git(...)](https://github.com/dagster-io/dagster/blob/df4872ee0a9e30ca8aab2e0ad2b552cf4ecda056/python_modules/dagster/dagster/_core/definitions/metadata/source_code.py#L316) condition to:

```python
if "gitlab" in git_url:
        git_url = _build_gitlab_url(git_url, git_branch)
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
@cooperellidge This seems like a one-liner change that's pretty straight forward. If you put in a PR for it I'll get it reviewed 👍
