### ISSUE TITLE
clean up implicit dependency on dagster-celery in backfill CLI machinery

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2313]
<img width="1258" alt="Screen Shot 2020-03-23 at 2 47 27 PM" src="https://user-images.githubusercontent.com/427016/77366463-4ce46a00-6d15-11ea-8d2b-4296ed129dc0.png">

cc @alangenfeld

**Comment by natekupp** [comment]
@mgasner still real?

**Comment by prha** [comment]
this is done
