### ISSUE TITLE
Explore ways to represent parent-child runs relations

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#2314]

**Comment by natekupp** [comment]
@bengotow @yuhan is this now done?

**Comment by yuhan** [comment]
we have made the following decisions
- infra/data side is done by #2320 and #2296 -- run relations (root, parent, child) stored
- use facing is done by https://dagster.phacility.com/D3174 -- the relations are represented in a separate section in Dagit's Run's viewer and it allows users to easily switch between related runs
