### ISSUE TITLE
Consider supporting default values in InputDefinitions

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2316]
See discussion:

![Screenshot 2020-03-24 09 27 15](https://user-images.githubusercontent.com/28738937/77451259-a9956280-6db1-11ea-88d3-b238135798a0.png)

**Comment by dwallace0723** [comment]
We are running up against a case right now where it's completely acceptable for one of the solid inputs to be `None`. This `InputDefinition` is supplied via an optional `OutputDefinition` of the upstream solid. Currently, it's awkward to represent this using the `InputDefinition` API. I'd love to see the `InputDefinition` API support something like a `default_value` parameter that essentially lets you define a default value to fall back on if the upstream Output is not supplied.

**Comment by natekupp** [comment]
Fixed by https://dagster.phacility.com/D2339
