### ISSUE TITLE
Clarify in deployment docs that Postgres/MySQL storage must be in the UTC timezone

### ISSUE THREAD

**Issue by axellpadilla** [dagster-io/dagster#23173]
### Dagster version

1.7.14

### What's the issue?

On both the UIs (classic and experimental), the timezone is buggy, jobs runs missing from overview and also, the run time on runs is applied the timezone twice (for example, I have -6, so it says 3 instead of 10 for a 16 UTC).

Time is correct on overview (but jobs run missing)

### What did you expect to happen?

Correct times

### How to reproduce?

While exact steps I'm not sure, because it just is a it is, this is a problem on time zone CST and don't know others, checking the code that handles the conversion for just that part could show the problem.

### Deployment type

Local

### Deployment details

Just plain local on an ubuntu latests LTS version machine with already configured timezone

### Additional information

Could be related to #16499 (or that should be closed)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Could you share full page screenshots of specifically where in the UI you're seeing discrepancies with the timezone in timestamps?

Please also let us know what web browser and version you're viewing Dagster in.

**Comment by axellpadilla** [comment]
Edge, but no difference with other browsers:
runs:
![image](https://github.com/user-attachments/assets/fee420c1-8b03-4cc7-8ac5-0f80e07f521b)

overview with correct time but missing runs:
![image](https://github.com/user-attachments/assets/89345943-232a-4149-9452-ed1bf1ba07d5)

**Comment by hellendag** [comment]
Just so I'm sure I understand, are the timestamps incorrect on the Runs page (first screenshot) and correct on the timeline view (second screenshot)?

Would you mind sharing a screenshot of your User Settings dialog, including the timezone and hour cycle selections?

**Comment by kptres** [comment]
Similar issue for BST
![image](https://github.com/user-attachments/assets/7e709147-9c2f-4a6e-a5f6-f5b21f2d22ae)
The jobs highlighted in red ran at 8.02 but is appearing at 7.02 on the ui. "Now" is correct.

User settings
![image](https://github.com/user-attachments/assets/02016929-025c-4359-8198-8f0f57a7532c)

The runs page is displaying the _incorrect_ time as well.

Dagster code server, webserver, daemon is set to timezone BST and in the database all timestamps are in  BST as well.

Postgres timezone is UTC, Changing it to local time has no effect

**Comment by axellpadilla** [comment]
Hi @hellendag 

Do you need help finding the problem? If you can provide the files to check or have anything to help understand the code structure related to this functionality let me know!

**Comment by gibsondan** [comment]
@axellpadilla is there any chance you are able to test this on 1.7.12? I am wondering if https://github.com/dagster-io/dagster/pull/22818 that went out in 1.7.13 could have somehow caused this.

**Comment by gibsondan** [comment]
Can you also describe what type of storage you are using (SQLite vs Postgres)? From the description here it sounds like runs may be going into the DB with non-UTC timestamps which may be the source of the problem - the expectation is that they are in UTC (with no time zone) but it’s possible that’s not happening the way it is supposed to for some storage types.

**Comment by gibsondan** [comment]
One thing to double check is that your database is running in the UTC timezone? I can reproduce something like this if I spin up a local postgres database and set the "TZ" env var on it to "America/New_York" instead of the default of "UTC" - I create a run and the creation time is off by 4 hours. I know at least one person on this thread said that their postgres DB was in UTC though, so there may be something else going on here besides that.

**Comment by kptres** [comment]
changing the timezone in postgresql.conf to UTC  and running ALTER DATABASE xxx SET timezone TO 'UTC';
resolved the issue

**Comment by edwinvehmaanpera** [comment]
Yes, changing the timezone seems to have solved the issue. You can also set an environmental variable `PGTZ=UTC` on the Dagster instances if you cannot change the database timezone.

However, there still seems to be an opportunity to improve the docs (is the UTC requirement stated anywhere explicitly?) and Dagster could warn or fail if the DB is in the wrong timezone.

**Comment by gibsondan** [comment]
Absolutely - filed this as a docs improvement.

**Comment by axellpadilla** [comment]
Hi guys, setting ALTER DATABASE xxx SET timezone TO 'UTC' alone fixed this issue, I understand the database isn't timezone aware because performance improvement over large datasets, so it should be definitely documented (not "fixed")

**Comment by sqkkyzx** [comment]
> 嗨，伙计们，将 ALTER DATABASE xxx SET timezone TO 'UTC' 单独解决了这个问题，我知道数据库无法识别时区，因为大型数据集的性能有所提高，因此应该明确记录（而不是“修复”）。
> 
> PD：在加载时检查数据库时区对于显示警告非常有用

PostgreSQL seems to not support configuring a time zone for a specific database; it can only be changed globally through `postgresql.conf`.

So, I decided to try changing it at the session level:

1. By `ALTER ROLE dagster_user SET timezone TO 'UTC';` to require all sessions of the user `dagster_user` to use UTC as the time zone.
2. Add a time zone configuration at the end of `PG_DB_CONN_STRING`: `postgresql://dagster_user:password@host.docker.internal:5432/dagster?options=-c%20timezone=UTC`

I fixed the problem(#24764) by using both methods together, but I did not test which one is effective separately.

**Comment by axellpadilla** [comment]
@sqkkyzx Postgresql do support it, but [Docs](https://www.postgresql.org/docs/current/config-setting.html) explain it better :
- The [ALTER DATABASE](https://www.postgresql.org/docs/current/sql-alterdatabase.html) command allows global settings to be overridden on a per-database basis.
- The [ALTER ROLE](https://www.postgresql.org/docs/current/sql-alterrole.html) command allows both global and per-database settings to be overridden with user-specific values.

In your case, posibly, the user had a previously defined timezone
