### ISSUE TITLE
ignore/handle excess config when subsetting a pipelline

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2322]
If you load a preset for a full pipeline but want to execute just a subset - you have to manually delete the excess config for the solids you have removed.

This an issue in both dagit and if you are using subsetting in the python API for testing

**Comment by natekupp** [comment]
yeah: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-aws/dagster_aws/emr/utils.py#L10-L17

**Comment by natekupp** [comment]
Closing this, since we have filtering now

**Comment by tfoldi** [comment]
How can I use this filtering? I'd like to use the same run config for my jobs, but if I select subset of ops it runs to an error
