### ISSUE TITLE
Terminating tasks with Celery as executor and databricks_pyspark_step_launcher doesn't work

### ISSUE THREAD

**Issue by cristian-marisescu** [dagster-io/dagster#23222]
### Dagster version

dagster, version 1.7.14

### What's the issue?

I'm running a lot of databricks steps with databricks launcher.

Setup looks roughly like this:

```python

def databricks_launcher() -> ResourceDefinition:
    """Return pyspark_step_launcher."""
    return databricks_pyspark_step_launcher.configured(
        {
            "run_config": {
                "run_name": "dagster_runner",
                "install_default_libraries": False,
                "cluster": {
                    "existing": os.getenv("DATABRICKS_CLUSTER_ID"),
                },
            },
            "poll_interval_sec": 30,
            "permissions": {},
            "databricks_host": os.getenv("DATABRICKS_HOST"),
            "databricks_token": os.getenv("DATABRICKS_TOKEN"),
            "secrets_to_env_variables": secrets_to_env_variables(
                [
                    "databricks-host",
                    "databricks-token",
                    "databricks-cluster-id",
                    "app-user",
                    "app-user-secret",
                ],
            ),
            "local_pipeline_package_path": "nothing_because_we_use_the_installed_wheel_on_cluster",
        },
    )
```

And in my definition i have:

```python

defs = Definitions(
    assets=get_all_assets(),
    jobs=[overnight_and_midday_refresh_job, night_job],
    resources={
        "databricks_launcher": databricks_launcher(),
        "databricks_io_manager": DatabricksIOManager(),
    },
    executor=celery_executor,
)
```

and my assets have the 
```
 "required_resource_keys": {"databricks_launcher"},
```

### What did you expect to happen?

I expected that, after starting a run, to be able to terminate it from the Dagster UI with the "Terminate" button. The celery worker never stopped.

### How to reproduce?

1. Create a simple databricks_pyspark_step_launcher and build one asset with it.
2. Run it with multiprocess or in memory executor 
3. Terminate the task right after this was started. Termination is done gracefully, sending command to databricks to stop the job.

4. Change the execution mode to celery_executor
5. Start another run
6. Terminate the task right after. The task will never terminate, the celery worker will keep processing the task.

### Deployment type

Local

### Deployment details

I was running the setup with ```dagster dev```, rabbitmq through docker and celery worker with ```❯ dagster-celery worker start -A dagster_celery.app```, using the pattern from official docs:https://docs.dagster.io/deployment/guides/celery, but using an asset with databricks_pyspark_launcher instead of a job.

### Additional information

Image after I canceled
![image](https://github.com/user-attachments/assets/2e90ad4b-15c0-48d5-a66b-a262f32d26b9)

Image after I forcibly canceled, on same run:
![image](https://github.com/user-attachments/assets/72e1cb4c-f8a4-411a-aeb8-ee7fd07a4d3c)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by divyanshu-in** [comment]
@garethbrickman I'd like to work on this issue!
