### ISSUE TITLE
Errors when turning schedules on and off appear as GraphQL errors

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2325]
This feels a little off, esp. for the case where the schedule is toggled off but is already off.
<img width="1477" alt="Screen Shot 2020-03-27 at 3 49 49 PM" src="https://user-images.githubusercontent.com/427016/77806724-c399a400-7042-11ea-85dd-ba322baa7fd7.png">
<img width="1466" alt="Screen Shot 2020-03-27 at 3 50 01 PM" src="https://user-images.githubusercontent.com/427016/77806727-c6949480-7042-11ea-9e35-13e07efc5b82.png">

**Comment by mgasner** [comment]
I also believe that it may be possible to get the cron scheduler into a bad state where it believes a schedule is running but it is not in fact running.

**Comment by catherinewu** [comment]
@gibsondan going to close this given the daemon scheduler's improved error handling? feel free to re-open if that's incorrect
