### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by LucasGabrielB** [dagster-io/dagster#23309]
### What's the issue or suggestion?

![image](https://github.com/user-attachments/assets/29d445a2-6553-416a-bbfb-117fa7f63766)

Link: https://docs.dagster.io/concepts/automation

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment]
Yikes! Good catch.
