### ISSUE TITLE
Improve rendering of tick errors that are UserFacingGraphQLError

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2332]
Currently looks like: 

![image](https://user-images.githubusercontent.com/3893054/77876783-eafa9780-7221-11ea-8e38-747b20fe4992.png)

There's not enough information here to debug the error.

**Comment by mgasner** [comment]
I don't really understand why this should be displayed to the user as a raw traceback -- we should expect this kind of failure and have an appropriate rich representation of it in the schedule storage/frontend -- I feel like we have everything we need for this in the config editor code
