### ISSUE TITLE
Potential memory leak in Celery workers

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2334]
@alangenfeld @mgasner adding this issue to track

**Comment by alangenfeld** [comment]
from my exploration so far it appears that this is just the memory taken up by the loaded code which stays in memory between executions

https://gist.github.com/alangenfeld/f247a510e46734a6681a8f5c09ce1423

have not yet been able to attribute memory amounts to specific libraries

**Comment by natekupp** [comment]
Closing, we haven't seen anything concerning here in a while—can open a new issue if this comes up
