### ISSUE TITLE
Dagit UI Activity Timeline 'Now' timestamp is incorrect for 30 minute timezone offsets

### ISSUE THREAD

**Issue by milliekr** [dagster-io/dagster#23342]
### Dagster version

Dagit UI

### What's the issue?

The `Now` timestamp appears be only the hour offset for timezones that are a XX:30 or XX:45 offset. E.g. for +09:30 timezone, the `Now` line is showing 30 minutes behind, at +09:00.
![image](https://github.com/user-attachments/assets/d6496206-c087-49e6-8d52-38774ca34a89)
![image](https://github.com/user-attachments/assets/68b2d172-9175-44bd-9373-b05a834ee3ec)

### What did you expect to happen?

Expect the `Now` timestamp to be correctly set by the selected timezone.

### How to reproduce?

Set the Timezone value to a +09:30 selection in the User settings and observe the `Now` timestamp is at UTC +09:00.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Thanks for the report!
