### ISSUE TITLE
Confusing documentation on run monitoring 

### ISSUE THREAD

**Issue by ssingh13-rms** [dagster-io/dagster#23359]
### What's the issue or suggestion?

While trying to use the run monitoring feature in Dagster to set a limit for an Asset run time, like so, `tags={"dagster/max_runtime": 600}`, I run into the following error `dagster._core.errors.DagsterInvalidDefinitionError: Tag values must be strings`. 
Does this mean the documentation is out of sync? The docs are using integers.

Additionally, the documentation is not clear on if the feature works on Jobs _and_ Assets. 

Update:
After some further testing, I can confirm that it's integer for Jobs and string for Assets.

### Additional information
This bug has been encountered on Dagster 1.7.15

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
[An asset's tags must be strings](https://docs.dagster.io/_apidocs/assets#dagster.asset). The `dagster/max_runtime` tag for Run Monitoring applies only to Jobs, [as per the example in the documentation](https://docs.dagster.io/deployment/run-monitoring#general-run-timeouts).
