### ISSUE TITLE
Need better error messages for config validation failures on scheduled runs

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2335]
![Uploading Screen Shot 2020-03-30 at 2.49.26 PM.png…]()

Without understanding the internals, it isn't straightforward even to see that this is a config validation error, let alone know what to do next.

**Comment by schrockn** [comment]
i think you submitted this before the image was done uploading

**Comment by mgasner** [comment]
dupe of #2332

**Comment by mgasner** [comment]
<img width="997" alt="Screen Shot 2020-03-30 at 2 49 26 PM" src="https://user-images.githubusercontent.com/427016/77965879-da383900-7296-11ea-9578-3b514d8bfa47.png">
