### ISSUE TITLE
Tasks created for runs on ECS deployments are not associated with a service

### ISSUE THREAD

**Issue by jonathanunderwood** [dagster-io/dagster#23366]
### Dagster version

1.7.14

### What's the issue?

We have a deployment of Dagster (open source) on AWS ECS. We have separate ECS services for the webserver, daemon and a user code grpc server. What runs are created we are seeing ECS tasks created as expected. However, those tasks are not associated with any service, which makes metric generation and observability awkward with AWS CloudWatch etc. Is this a bug or working as intended? If working as intended, is there any configuration we can change to ensure asset tasks are mapped to ECS services (e.g. one service per asset materialization run).

### What did you expect to happen?

The tasks created for an asset materialization run might be expected to be created as part of the same ECS service for the corresponding grpc server. Or, perhaps a service per run, with a task per asset partition.

### How to reproduce?

- Deploy Dagster to ECS following the recommended approach and with a code server (grpc server) hosting the relevant code
- Initiate a backfill run
- ECS tasks are created but not attached to any ECS service.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jmsanders** [comment]
This is working as intended.

We think of [services as long-lived](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html) (like a webserver) and want to take advantage of ECS's ability to run replicas and remain fault-tolerant across disruptions.

We think of [tasks as ephemeral](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/standalone-tasks.html) (like a run). If the run fails, we don't want a new one to stand up in its place - Dagster has its own abstractions for retrying runs. When the run succeeds, we also don't want a new task representing the same run to launch again.

**Comment by jonathanunderwood** [comment]
@jmsanders thanks for the response, and confirming this is intended behavior.
