### ISSUE TITLE
Heartbeat between Dagit and Celery workers

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2336]
Right now, when we invoke a run via the k8s job launcher, if the celery queue is not being drained / assigned, the job will stick around forever and never terminate. We should consider all the ways job masters could be orphaned like this, but especially the case when the celery queue is accepting work but workers are unavailable

**Comment by natekupp** [comment]
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/609349/78099134-d7703d80-7395-11ea-88bd-6871b9416231.png">

Seeing this just go on with nothing happening

**Comment by mgasner** [comment]
I think we've determined this is not what was happening? Can we comment accordingly and close?

**Comment by natekupp** [comment]
hmmm I think this would still happen in any case with custom queues, the master job won't ever time out or terminate if you're sending steps to be executed in queues that don't exist—right? or do we have timeouts somewhere to catch that case?

**Comment by mgasner** [comment]
That seems fine?

**Comment by catherinewu** [comment]
i think it could be good to have an instance level run manager that can clean up cases like this

**Comment by johannkm** [comment]
> if the celery queue is not being drained / assigned

I think what we want here is probably some type of heartbeat between dagit and the celery workers? Or more generally, whatever is handling runs (we'll need similar heartbeats to the run queue process).

**Comment by johannkm** [comment]
We don't surface this exact situation, but it can be handled with run start timeouts.
