### ISSUE TITLE
GraphQL Playground auto-complete and type boxes don't disappear in the UI when using Chrome browser

### ISSUE THREAD

**Issue by garethbrickman** [dagster-io/dagster#23390]
### Dagster version

1.7

### What's the issue?

GraphQL Playground auto-complete and type boxes don't disappear in the UI:

<img width="577" alt="Screenshot 2024-08-02 at 18 27 45" src="https://github.com/user-attachments/assets/65a7aeb4-d96d-4f72-8b1f-255f775ad28f">

This only happens in Google Chrome browser above version 127. Using Firefox or Edge browsers are confirmed to work as alternatives. 

It is root caused by this bug in graphql-playground: https://github.com/graphql/graphql-playground/issues/1429

**Comment by hellendag** [comment]
Replaced GraphQL Playground with GraphiQL. 🎉
