### ISSUE TITLE
A CLI command that can check/validate definitions without loading the Dagster services/UI

### ISSUE THREAD

**Issue by imporoutco586** [dagster-io/dagster#23498]
### What's the use case?

I noticed that after dagster instance is started, the webserver ui checks the assets in the repository and gives error feedback. Is there any way to check the assets before dagster instance is started?
​
Is there a way to check the newly written asset from the command line to see if it is correct? The asset check in the documentation seems to be written specifically for certain assets, and I want the default generic error feedback, just like the ui feedback.

### Ideas of implementation

Maybe the cli like `dagster asset check --select your_asset` is what we were hoping for.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
https://github.com/dagster-io/dagster/pull/23692
