### ISSUE TITLE
Consolidate implementations of dictionary merge

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2350]
We have two: `dagster.utils.merger.dict_merge` and `dagster.utils.merge_dicts`. The latter is in more widespread use but former seems preferable.

**Comment by sryza** [comment]
@natekupp what looks preferable to you about `dict_merge`?  It seems to have a more complicated implementation.

**Comment by schrockn** [comment]
These functions have different semantics and have different purposes.  One is shallow and the other is deep copy. dict_merge is meant to merge config documents recursively. Other the other is meant to be shallow and mimic dictionary comprehensions. This is a naming issue.

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by natekupp** [comment]
Fixed by https://dagster.phacility.com/D2458
