### ISSUE TITLE
Re-execution incorrectly reports steps in a preparing state

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2352]
Execute a pipeline

![Screenshot 2020-04-07 11 23 12](https://user-images.githubusercontent.com/28738937/78705400-41bb3d80-78c2-11ea-9a63-e584135e01f7.png)

Re-execute

![Screenshot 2020-04-07 11 23 27](https://user-images.githubusercontent.com/28738937/78705416-497ae200-78c2-11ea-946b-31eb99f55119.png)

read_csv is permanently put in a "preparing" state

![Screenshot 2020-04-07 11 23 39](https://user-images.githubusercontent.com/28738937/78705445-55ff3a80-78c2-11ea-963f-2cc1d75df91f.png)

**Comment by prha** [comment]
I can't repro this, @schrockn .... this is on master?

**Comment by schrockn** [comment]
Looks like @yuhan was able to repro! https://dagster.phacility.com/D2472

**Comment by prha** [comment]
ah, it's single-step reexecution... k, thanks
