### ISSUE TITLE
Dagit Execution continues the timeline when the solid does not have a return value

### ISSUE THREAD

**Issue by canimus** [dagster-io/dagster#2355]
I am executing `pyspark_solid` 's and after launching the solid from the playground, the execution timeline animation does not stop, if the solid does not explicitly returns a value.
I am using 

dagster
dagit
dagster-spark
`0.7.6`

**Comment by natekupp** [comment]
Hey @canimus, thanks for raising this—is this only happening with `@pyspark_solid` or with other solids as well? Can you provide a bit more context or a code example that causes this?

**Comment by canimus** [comment]
Issue is only reproducible when running dagit from withon the command line terminal integrated in Visual Studio Code. For some reason the signal for completion of the pipeline execution is not captured in the browser, and as a consequence, even when the pipeline in the console reported as executed successfully, the browser's animation on the execution continues.

When running outside of the context of VS-Code, the execution finishes gracefully in both console, and browser.

Sorry for the early spam. 
Regards!
