### ISSUE TITLE
Unexpected GraphQL Error. Error when activate/deactivate schedule via Dagster Web UI

### ISSUE THREAD

**Issue by ngurahyudi** [dagster-io/dagster#23576]
### Dagster version

1.8.0

### What's the issue?

<img width="1449" alt="Screenshot 2024-08-12 at 17 32 27" src="https://github.com/user-attachments/assets/a9350f0e-f89f-4f99-a0c8-3aa93eb5cbe7">

### Deployment type

Local

### Deployment details

PostgreSQL

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Duplicates https://github.com/dagster-io/dagster/issues/23567

A fix will be included in the upcoming 1.8.1 release this week.

**Comment by ngurahyudi** [comment]
thank you!
