### ISSUE TITLE
Hard to select errors text in playground tab

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#2358]
I tried selecting the text in the "Errors" section at the bottom right of the playground tab, so that I could copy/paste to send to someone.  I tried clicking in a few different way, but the text immediately unselected.

**Comment by schrockn** [comment]
@sryza could you provide any more context on this? screenshot?

**Comment by sryza** [comment]
I'm referring to this pane:
![image](https://user-images.githubusercontent.com/654855/83551461-3b5dd200-a4bd-11ea-9243-1dde7a1feb78.png)

**Comment by yuhan** [comment]
@sryza if you click "View All", there will be a modal with a "Copy" button that allows you to copy the entire error 
![image](https://user-images.githubusercontent.com/4531914/84085409-67d08d00-a99a-11ea-8850-abc51e6a4f04.png)
