### ISSUE TITLE
horizontal scrollbar in error popout is inside vertical scroll pane

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#2359]
When I click on an error from an execution event and the log lines exceed the width of the viewport, I can't see the horizontal scroll bar until I scroll all the way down to the end of the vertical scroll.

This makes it difficult to see the ends of long log lines that aren't at the bottom of the log. 

![image](https://user-images.githubusercontent.com/654855/78822165-7648fb00-798f-11ea-8f90-57bb58f7589e.png)

![image](https://user-images.githubusercontent.com/654855/78822185-7d700900-798f-11ea-953f-eb63355b15ce.png)

**Comment by bengotow** [comment]
Ahh man thanks for reporting this, definitely strange behavior we've got going on here. I'll tackle this one.
