### ISSUE TITLE
Incompatible with polars >= 1.4.0

### ISSUE THREAD

**Issue by aebrahim** [dagster-io/dagster#23594]
### Dagster version

1.8.0

### What's the issue?

We have a version conflict due to a dagster version pin added for `1.3.0` in #23301.

Please support `1.4.0` and remove the pin.

Thank you!

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by DanteOz** [comment]
Also being blocked on upgrading to dagster 1.8 on this issue.

**Comment by garethbrickman** [comment]
cc @danielgafni as it relates to your Polars issue https://github.com/pola-rs/polars/issues/17933

**Comment by danielgafni** [comment]
I think the bug which I reported was fixed. The pin can be removed now.

**Comment by garethbrickman** [comment]
@danielgafni Oh actually the pin is removed in master branch, from https://github.com/dagster-io/dagster/pull/23708

**Comment by DanteOz** [comment]
@garethbrickman do you know if https://github.com/dagster-io/dagster/pull/23708 will it make it into this week's release?

**Comment by garethbrickman** [comment]
@DanteOz Yes it comes out this week in 1.8.2
