### ISSUE TITLE
`AutomationCondition` support for `dbt_assets`

### ISSUE THREAD

**Issue by cbini** [dagster-io/dagster#23656]
### What's the use case?

dbt assets currently cannot support the new `AutomationCondition` API. Even a drop-in replacement like `.eager()` fails with `AttributeError: 'AndAutomationCondition' object has no attribute 'to_automation_condition'`

### Ideas of implementation

- `build_dbt_multi_asset_args` needs to be updated to accept the new parameter when constructing `AssetOut` objects.
- `DagsterDbtTranslator` needs a `get_automation_condition` method or `get_auto_materialize_policy` needs to be retrofit to allow `AutomationCondition` output

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
https://docs.dagster.io/integrations/dbt/reference#customizing-automation-conditions
