### ISSUE TITLE
When using StringSource and environment variables, errors should be better

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2367]
Right now the experience in the config editor is rough when you try to specify an environment variable that does not exist.

![Screenshot 2020-04-12 17 11 51](https://user-images.githubusercontent.com/28738937/79083109-dc5fb600-7ce0-11ea-95ab-66aaf49cedbf.png)

The most likely solution is that there should be a properly formatted config error for errors that occur in the post process step

**Comment by alangenfeld** [comment]
this was improved
