### ISSUE TITLE
Unclear on `pipeline_dict` vs `pipeline_defs`

### ISSUE THREAD

**Issue by xinbinhuang** [dagster-io/dagster#2368]
Hi team,

In the tutorial `repos.py`. It is said that using `pipeline_dict` can pipeline instantiating lazily. 

https://github.com/dagster-io/dagster/blob/c40307d9a960cd287b302d86a09870d9668f5a27/examples/dagster_examples/intro_tutorial/repos.py#L21

But in the example given, I don't see how it's different from using `pipeline_defs=[hello_cereal_pipeline]` because `hello_cereal_pipeline` is already an instance of `PipelineDefinition`.

Would you be kind to provide a non-trivial example that shows the benefit of `pipeline_dict`?

Thanks
Bin

**Comment by schrockn** [comment]
Closing as resolved with new @repository API
