### ISSUE TITLE
Mark deleted instead of actually deleting records

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2369]

**Comment by schrockn** [comment]
Punting this one to 0.9.0. I anticipate that this may be part of larger work stream to may rows in the runs table wholly a mutable and instead of a row represent a state at a point in time for a run.

**Comment by catherinewu** [comment]
Hey @mgasner, was wondering if you could clarify which 'records' the title refers to?

**Comment by alangenfeld** [comment]
I think actual deletes is right for now - can re-open more specific issues
