### ISSUE TITLE
Resolve various pipeline run representation formats.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2370]
Right now pipeline run information is necessary for a few use cases. 

1) When the user executes a pipeline, they want to specify things like a pipeline run id, etc. 
2) https://dagster.phacility.com/D2514 introduces/introduced a separate class PipelineRunCreationData that is used internally to create runs at the DagsterInstance layer. We don't want class like this in the public API.
3) We need class to serve as the serialization format that is encoded in the db. Currently this is the PipelineRun object.

**Comment by mgasner** [comment]
i think this has been sorted

**Comment by mgasner** [comment]
we should open new issues for the double-encoding of info in execution plan, etc
