### ISSUE TITLE
[dagster-polars] Upstream partitionned Polars assets cannot be optional

### ISSUE THREAD

**Issue by razafinl** [dagster-io/dagster#23711]
### Dagster version

1.8.1

### What's the issue?

Using `dagster-polars` library, we are trying to build downstream asset based on partitonned upstream. As the library is implemented, whether the upstream asset is "optional" is determined by the Python type hint provided in downstream function.

Using expected Python type for the upstream asset (`dict[str, Optional[pl.DataFrame]]`) does not currently work and is throwing the following error:

> NotImplementedError: Can't load object for type annotation typing.Dict[str, typing.Optional[polars.lazyframe.frame.LazyFrame]]

### What did you expect to happen?

Given the following downstream asset based on a partitionned upstream asset with `dagster-polars` IOManager (subclass of BasePolarsUPathIOManager)

```python
@asset
def downstream(upstream: dict[str, Optional[pl.DataFrame]]) -> DataFrame:
  return concat(upstream.values())
```

I'm expecting all missing partition from upstream asset to be skipped/ignored and materialize downstream with only the materialized upstream partition without error.

### How to reproduce?

```python
from dagster import (
    AssetExecutionContext,
    DailyPartitionsDefinition,
    Definitions,
    asset,
    load_assets_from_current_module,
)
from os import path, getcwd
from polars import DataFrame, LazyFrame, concat
from dagster_polars import PolarsParquetIOManager

partition_def = DailyPartitionsDefinition("2024-08-10")

@asset(partitions_def=partition_def)
def upstream(context: AssetExecutionContext) -> DataFrame:
    return DataFrame({"date":[context.partition_time_window.start]})

@asset
def downstream(upstream: dict[str, LazyFrame|None]) -> DataFrame:
    return concat(upstream.values()).collect(streaming=True)

definitions = Definitions(
    assets    = load_assets_from_current_module (),
    resources = dict(io_manager=PolarsParquetIOManager(base_dir=path.join(getcwd(),"output")))
)
```

When attempting to materialize, we are facing the error.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by razafinl** [comment]
When trying to debug, it seems like despite providing `dict` as Python type for my downstream asset, the IOManager is getting the type `typing.Dict` which means the Python type I'm trying to use is not one of `POLARS_EAGER_FRAME_ANNOTATIONS` or `POLARS_LAZY_FRAME_ANNOTATIONS`:

https://github.com/dagster-io/dagster/blob/ac170b307d28e69807cbfef72654a2b557e3ca22/python_modules/libraries/dagster-polars/dagster_polars/io_managers/base.py#L78-L83

The first issue is that the received `typing.Dict[str, Optional[pl.LazyFrame]]` is not `dict[str, Optional[pl.LazyFrame]]`. Adding `typing.Dict` variants to both `POLARS_EAGER_FRAME_ANNOTATIONS` or `POLARS_LAZY_FRAME_ANNOTATIONS` seems to fix the `NotImplementedError`.

Furthermore, `typing.Dict[str, Optional[pl.LazyFrame]]` is not currently considered "optional" by [annotation_is_typing_optional](https://github.com/dagster-io/dagster/blob/ac170b307d28e69807cbfef72654a2b557e3ca22/python_modules/libraries/dagster-polars/dagster_polars/io_managers/base.py#L86C5-L87) method. A quick workaround that I tested locally is

```python
def annotation_is_typing_optional(annotation) -> bool:
    if get_origin(annotation) in (dict, Dict):
        return annotation_is_typing_optional(get_args(annotation)[1])
    else:
        return get_origin(annotation) == Union and type(None) in get_args(annotation)
```

**Comment by danielgafni** [comment]
I think this isn't an issue with `dagster-polars`. Duplicating my comment from the PR here for visibility: 

To be able to do this, you need to set "allow_missing_partitions": True in the input metadata. This feature comes from the default `UPathIOManager`, it's not something unique to `dagster-polars`. Otherwise the IOManager will raise an error when trying to load a missing partition.

```python
def test_polars_upath_io_manager_input_dict_optional_eager(
    io_manager_and_df: Tuple[BasePolarsUPathIOManager, pl.DataFrame],
):
    manager, df = io_manager_and_df
    partition_keys = ["a", "b", "missing"]

    if isinstance(manager, PolarsDeltaIOManager):
        pytest.skip("PolarsDeltaIOManager does not read partitions as dictionaries")

    @asset(io_manager_def=manager, partitions_def=StaticPartitionsDefinition(partition_keys))
    def upstream(context: AssetExecutionContext) -> Optional[pl.DataFrame]:
        return (
            None
            if context.partition_key == "missing"
            else df.with_columns(pl.lit(context.partition_key).alias("partition"))
        )

    @asset(
        io_manager_def=manager,
        ins={
            "upstream": AssetIn(
                metadata={
                    "allow_missing_partitions": True,
                }
            )
        }
    )
    def downstream(upstream: Dict[str, pl.DataFrame]) -> pl.DataFrame:
        dfs = []
        for df in upstream.values():
            assert isinstance(df, pl.DataFrame)
            dfs.append(df)
        return pl.concat(dfs)

    for partition_key in partition_keys:
        materialize(
            [upstream],
            partition_key=partition_key,
        )

    materialize(
        [upstream.to_source_asset(), downstream],
    )
```

**Comment by razafinl** [comment]
Hello Daniel,
Yes it does solve this issue. Thank you!
