### ISSUE TITLE
Terminology: Composite Solid vs Composite Pipeline

### ISSUE THREAD

**Issue by AdamDorwart** [dagster-io/dagster#2374]
Pretty simple question, what's the reasoning for the name Composite Solid?

Based on the way that `Composite Solids` act and are written they seem to behave more like `Pipelines` (`Composite Pipelines`?) than `Solids`. I realize this is a pretty basic nit to create an issue for so I get it if this gets rejected (especially if there's a good reason I'm not seeing) . It was unintuitive as a new user that the body of a `solid` is a typical python function but the body of a `composite_solid` is more like a pipeline definition and has limitations on what's allowable syntax. 

I think the difference between solid (Python) syntax vs pipeline (DAG building) syntax is a common early pitfall. Changing the name might help make composite's a bit easier for new users to grasp.

**Comment by natekupp** [comment]
Thanks for flagging! At minimum, we should definitely have better/clearer documentation around the constraints of pipelines and composite solids.

**Comment by schrockn** [comment]
This sin shall be exorcised by fire: https://github.com/dagster-io/dagster/discussions/2902

**Comment by mgasner** [comment]
can we close this in favor of #2902 @alangenfeld
