### ISSUE TITLE
[dagit subscriptions] Errno 35 Resource temporarily unavailable

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2376]
It appears this can happen on OSX when resource contention is high

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "...truncated.../python3.8/site-packages/gevent/_socket3.py", line 504, in send
    return self._sock.send(data, flags)
BlockingIOError: [Errno 35] Resource temporarily unavailable
```
full stack trace https://gist.github.com/alangenfeld/5f27b58694b5be4781ea62606d8292a3

It doesn't seem like we have much control over timeouts or anything happening in the `graphql-ws` our subscriptions are currently built upon

**Comment by sryza** [comment]
I'm going to boldly close this issued that appears to have really been making the rounds between projects. We can reopen if we run into this again.
