### ISSUE TITLE
Migrating a remote instance

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2378]
We should have some way to migrate a remote database; this might be quite difficult if there's no direct CLI networking access to the database.

Ran into this w/ our k8s deployment; had to kubectl exec bash and run `dagster instance migrate` in a running pod, which may not be an option for real/prod deployments.

**Comment by helloworld** [comment]
For 0.10.0, we should probably at least write a guide about how to do this using a custom job so that people aren't blocked from upgrading

**Comment by gibsondan** [comment]
I think we should mark this as urgent until we have some official recommendation written down somewhere for users

**Comment by gibsondan** [comment]
One method right now: https://gist.github.com/alangenfeld/b16d6d867d262d401b2ba5b07095c84a
