### ISSUE TITLE
Provide some way to disable Dagit restart button

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2379]
This is useful locally, but bad to have in a prod context—you definitely don't want to have the Dagit pod die and be cycled out by k8s every time a curious user clicks this button to see what it does

![image](https://user-images.githubusercontent.com/609349/79298116-04901600-7e95-11ea-8d9c-3753816bc206.png)

**Comment by alangenfeld** [comment]
This shouldn't cause the pod to die though, the parent process (`dagit`) is still alive as the inner process (`dagit-cli`) restarts. Did you see different?

The button is already gated, so if you launch `dagit-cli` directly its not shown.

**Comment by natekupp** [comment]
Ah yes you're right, closing
