### ISSUE TITLE
Celery on dagster-k8s should use installation-specific default queue name

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2381]
Right now we always default to the queue name "dagster". 

We should change to defaulting to a install-specific name, otherwise you can't safely install two copies of the Helm chart on one cluster—they share a queue, and the two sets of Celery workers will contend for pulling tasks off that queue, even if they're not able to correctly execute those tasks.

**Comment by alangenfeld** [comment]
This problem also manifests if you want to try to use both `dagster_celery_docker` and regular `dagster_celery` executors in the same deployment.

**Comment by catherinewu** [comment]
this is resolved
