### ISSUE TITLE
How to migrate from using SourceAsset to AssetSpec

### ISSUE THREAD

**Issue by ShootingStarD** [dagster-io/dagster#23849]
### What's the issue or suggestion?

Hi, in the release of dagster 1.8 it is said that SourceAsset are being deprecated and we should use AssetSpec instead. My question is : how to migrate from one to the other?
Currently I face the problem that I have hyperparameter for an ML model that should depend on whether I am in a test environment, an environment with GPU or without GPU. I thought of having a json as an Asset that could be different for each environment. With a source asset it is very easy, I define my json io manager and I can easily load this json file that can be different for each environment
However I get the feeling that with AssetSpec, we cannot really load the "Asset" into another asset (as we cannot define an IO manager)
Therefore how should we migrate from SourceAsset to AssetSpec if AssetSpec have less functionalities than SourceAsset?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ShootingStarD** [comment]
I have another example where I don't really see how to solve it. We have a machine learning model that must be read in memory using our xgboost io manager. The model is made manually in jupyter notebooks because we could change the hyperparameter, the features etc. With a source Asset , we can specify the io manager to use to load the model, but I do not see how to load the model in another asset using the AssetSpec

**Comment by HynekBlaha** [comment]
Hello @ShootingStarD, have you tried steps mentioned in [migration docs](https://docs.dagster.io/migration)?
```python
# before
from dagster import SourceAsset
my_asset = SourceAsset("my_asset", io_manager_key="abc")

# after
from dagster import AssetSpec
my_asset = AssetSpec("my_asset", metadata={"dagster/io_manager_key": "abc"})
```
