### ISSUE TITLE
1.8.2 - ImportError: cannot import name 'runtime_version' from 'google.protobuf'

### ISSUE THREAD

**Issue by rossserven** [dagster-io/dagster#23854]
### Dagster version

1.8.2

### What's the issue?

The 'Prepare DBT project for deployment' Github Action step is failing with

`  
File "/home/runner/.local/lib/python3.8/site-packages/grpc_health/v1/health_pb2.py", line 9, in <module>
    from google.protobuf import runtime_version as _runtime_version
ImportError: cannot import name 'runtime_version' from 'google.protobuf' (/home/runner/.local/lib/python3.8/site-packages/google/protobuf/__init__.py)
Error: Process completed with exit code 1.
`

I am not seeing the same error under 1.8.1
`
    install_requires=[
        "dagster<1.8.2",
        "dagster-cloud<1.8.2",
        "dagster-dbt<1.8.2",
...
    ],
`

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @rossserven - thanks for reporting this, we're fixing the action in https://github.com/dagster-io/dagster-cloud-action/pull/195. You can apply that same change to your github repo and it should work (specifically, replacing `pip install pip --upgrade` with `python -m pip install pip --upgrade` in the two action YAML files).

**Comment by gibsondan** [comment]
This is now fixed for new users going through the flow. If the github action has already been scaffolded in a github repo, applying the change above will fix it.

**Comment by gibsondan** [comment]
Hold that thought actually - we temporarily rolled back the fix, but it should be live soon. The above workaround should still work in the meantime.

**Comment by cyclonstep** [comment]
@gibsondan hello, I also found this problem lately and it really locks me for getting the newest version. Is this actually still in the broken state  now or can I just re-scaffold it?

**Comment by gibsondan** [comment]
This is fixed now if you re-scaffold, sorry for not updating this task. Or you can apply that change above to the action yaml if you have already scaffolded.

**Comment by cyclonstep** [comment]
@gibsondan thank you very much 👍 
If I don't need to re-scaffold the project, do I just need to update the action yaml like this? 
https://github.com/dagster-io/dagster-cloud-action/pull/195/files#diff-050229b268df6169d016a0f0c43b5f7ab7280b21541d86bb3412a08a8c579ae4

**Comment by gibsondan** [comment]
That’s all you should need to do to make it work, yes
