### ISSUE TITLE
Error when running Dagster U tutorial, first run / materialization of first asset

### ISSUE THREAD

**Issue by fdjonmc** [dagster-io/dagster#23957]
### Dagster version

1.8.2

### What's the issue?

Operation name: {PipelineRunLogsSubscription}

Message: FSEventsObserver.schedule() takes 3 positional arguments but 4 were given

Path: 

Locations: 

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment]
Hi @fdjonmc - I'm unable to reproduce this one.

Would you be able to share the version of Python you're using, your operating system, and also the version of `dagster-webserver`?

**Comment by abedzantout** [comment]
Faced the same issue today, seems a problem with the new watchdog 5.0.0 release. Downgrading to watchdog 4.x.x solves this

**Comment by cmpadden** [comment]
> Faced the same issue today, seems a problem with the new watchdog 5.0.0 release. Downgrading to watchdog 4.x.x solves this

Thanks for pointing this out @abedzantout, we'll be setting a pin on watchdog in the next release.

For the time being I'll inform users that they must downgrade like you've outlined.

**Comment by garethbrickman** [comment]
The 1.8.4 release with the fix for this is out now! https://github.com/dagster-io/dagster/releases/tag/1.8.4

**Comment by l1uzz3** [comment]
I downgraded watchdog into the terminal `pip install watchdog==0.10.4 then it worked`

**Comment by cmpadden** [comment]
Thanks for reporting this @fdjonmc .

We've updated Dagster University courses to run on Dagster v1.9.* which should resolve this issue. If you've already scaffolded your project, you'll have to update the dependency manually, otherwise new projects should be good-to-go.

Thanks!
