### ISSUE TITLE
OutputContext' object has no attribute 'asset_info'

### ISSUE THREAD

**Issue by dridk** [dagster-io/dagster#23951]
### Dagster version

dagster, version 1.8.2

### What's the issue?

Hi, 

From last version 1.8, it looks like "asset_info" has been removed.  I get the following error : "OutputContext' object has no attribute 'asset_info'". It was working before. 

I can no longer access to : 
- context.asset_info.code_version
- context.asset_info.key
- context.asset_info.partition_def

### What did you expect to happen?

OutputContext.asset_info or alternative

### How to reproduce?

Create an asset with a code_version. 
Try to access the code_version from an IOManager using the OutputContext 

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dridk** [comment]
Seems close to https://github.com/dagster-io/dagster/issues/23951

**Comment by dridk** [comment]
I can confirm this bug has been introduction with dagster 1.7.11

**Comment by dridk** [comment]
I think it comes from from this commit :
https://github.com/dagster-io/dagster/commit/41036fe77be58c64ac579498c2c431f395c8719f

**Comment by dridk** [comment]
I solved it by replacing the code for accessing code_version by the following line

```
code_version = context.op_defs.outs["result"].code_version
```

**Comment by sryza** [comment]
Hi @dridk - `asset_info` was not a public attribute of `OutputContext`, so we removed it as part of a larger cleanup. I've filed an issue to track exposing some of these properties on `OutputContext` in more stable ways: https://github.com/dagster-io/dagster/issues/23965.  I'm glad you were able to find a short-term workaround.
