### ISSUE TITLE
Dagster GrapgQL launch run problem

### ISSUE THREAD

**Issue by Vinicius999** [dagster-io/dagster#24033]
### Dagster version

dagster, version 1.8.2

### What's the issue?

When running the job manually via the schedule or by running the job directly, the UI shows the following error:

![image_01](https://github.com/user-attachments/assets/8fd4861b-39b0-4020-b9e3-901e2813f5b0)

![image_02](https://github.com/user-attachments/assets/079b3471-9027-4b26-a9ad-7c10b68c2f50)

The UI does not refresh showing the execution of the job, even though the job runs normally behind the scenes, and it is possible to view the execution in the “runs” tab.

### What did you expect to happen?

I don't know what's causing the error because the execution occurs normally behind the scenes.

### How to reproduce?

I don't know what's causing the error because the execution occurs normally behind the scenes.

### Deployment type

Local

### Deployment details

It's the local test before deployment.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Duplicates https://github.com/dagster-io/dagster/issues/23957

Fixed in this week's forthcoming release of 1.8.4
