### ISSUE TITLE
Unknown type "StartPipelineExecutionSuccess" after #2395

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#2408]
```
dagit -f examples/dagster_examples/intro_tutorial/materializations.py -n materialization_pipeline
```
![image](https://user-images.githubusercontent.com/4531914/80266113-26388c80-864f-11ea-8a20-2845a18e85fd.png)

**Comment by helloworld** [comment]
run `make dev_webapp`

**Comment by catherinewu** [comment]
I think I encountered this by somehow having a prod install of dagster-graphql.`pip install --upgrade pip` then `make install_dev_python_modules` worked for me.
