### ISSUE TITLE
Improve syntax highlighting for strings in Dagit playground

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2409]
The syntax highlighting is a bit broken when you have strings with a `:` (colon) in them. 

For example:

![image](https://user-images.githubusercontent.com/3893054/80399697-a0535600-8887-11ea-929b-5c90457779f5.png)

We should either manually fix the syntax highlighting here, or just wrap each string in quotes. The latter solution might actually provide a better experience – it's more obvious that the value is a string:

![image](https://user-images.githubusercontent.com/3893054/80399794-c4af3280-8887-11ea-9ccf-d42290c67d26.png)

**Comment by bengotow** [comment]
I am somewhat impressed that this is valid YAML actually, but I'll see what we can do 😎

**Comment by bengotow** [comment]
Addressed in https://dagster.phacility.com/D3232
