### ISSUE TITLE
it's hard to know where to start in the dagit playground

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2410]
<img width="1792" alt="Screen Shot 2020-04-27 at 3 27 26 PM" src="https://user-images.githubusercontent.com/427016/80426966-af440380-889b-11ea-9699-219834701f85.png">

especially if i have "errors only" checked
<img width="1784" alt="Screen Shot 2020-04-27 at 3 28 35 PM" src="https://user-images.githubusercontent.com/427016/80427020-c8e54b00-889b-11ea-9f91-72eb338f811b.png">

**Comment by hellendag** [comment]
Perhaps this will be made better by https://github.com/dagster-io/dagster/issues/3118? What do you think @mgasner?

**Comment by catherinewu** [comment]
going to close
