### ISSUE TITLE
Visual hints for shortcut keys in Dagit should have some delay before appearing

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2411]
Otherwise all of our Dagit screenshots have shortcut key hints 

![image](https://user-images.githubusercontent.com/609349/80433750-9d1e9100-88ac-11ea-9db8-24771da43e26.png)

**Comment by bengotow** [comment]
Will fix this, agreed it's annoying. I've started putting another window in the foreground and then using macOS window screenshot capture (Ctrl-Cmd-Shift-4 and then press the spacebar and select the window) to capture it behind the other window so it's not receiving keyboard events, but that's quite the hack.
