### ISSUE TITLE
Remove all calls to `get_or_create_run` from dagster-airflow

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2412]

**Comment by catherinewu** [comment]
After talking to some folks about their airflow workflows, it appears to be a common pattern to pick up a job from a failed task (which can be downstream of the root task). Thus, we need the ability for arbitrary tasks to be able to create runs, so I think we should keep get_or_create_run() and add use https://dagster.phacility.com/D2719 for the race

**Comment by catherinewu** [comment]
Decided to keep get_or_create_run, with some added robustness, testing, and documentation in https://dagster.phacility.com/D2719
