### ISSUE TITLE
dagster-dbt model "Unexpected graphql error"

### ISSUE THREAD

**Issue by MYFSUHAIL-ORKA** [dagster-io/dagster#24135]
### Dagster version

1.7.16

### What's the issue?

I am running dbt dagster model in local development using docker container. Sometimes I am getting this error on the localhost webpage.

UNEXPECTED GRAPHQL ERROR:
Operation name: {CapturedLogsSubscription}
Message: PollingObserver.__init__() takes 1 positional argument but 2 were given
Path: 
Locations: 

The job is completeing fine. But this pop up is coming in the webserver page everytime.

### What did you expect to happen?

I dont want the popup window to come !

### Deployment type

Docker Compose

### Deployment details

Using docker and dbt with duckdb

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tobiplay** [comment]
Can you try bumping your Dagster version to the latest release (1.8.4) temporarily (incl. the libraries to their respective current releases)?

If you're using deprecated features (check the changelogs), disable them temporarily as well.

You can also try disabling the WebSockets from the UI's user settings. That helped me suppress a similar error prior to version 1.8.4.

**Comment by dargmuesli** [comment]
I think it's resolved in Dagster's most recent version.

**Comment by tobiplay** [comment]
This issue can most likely be closed now, as it was addressed in a previous update.
