### ISSUE TITLE
feature request: button in the runs page to terminate all started pipelines

### ISSUE THREAD

**Issue by cjroth** [dagster-io/dagster#2413]
I'm actually not sure if it should just terminate *all* started pipelines - there might be a better way to implement this - needs more thought - but I think it would be really nice to have a way to kill off old/stuck pipelines that get stuck in the "started" state.

To add more to this idea, the real problem is actually that there are stuck pipelines in the first place. I would love it if there was a solid-level and/or pipeline-level configuration option to for a maximum execution time that would cause the pipeline or solid to fail after a certain amount of time.

To be fair, this is not hard to implement in the solids themselves using basic Python... but how nice would it be to just throw a parameter in there?

Anyways... that's the idea :) Love Dagster and very much enjoying using it.

**Comment by hellendag** [comment]
This should be doable in the Runs page, by filtering to `status: STARTED` and using the checkboxes to select and cancel the desired runs.
