### ISSUE TITLE
Save the current Config used

### ISSUE THREAD

**Issue by naidu-rohit** [dagster-io/dagster#2414]
I am tring to use config yaml files as a way to record ML experiments. However, I am not able to save the current config being used. I can copy the yaml files to an experiments folder, but if any changes are made in dagit i cannot store it. Is there a way to save the config as a yaml file?

**Comment by natekupp** [comment]
Hi @naidu-rohit, Dagit doesn't directly support writing config YAML to disk.

However, I would suggest using `PresetDefinition`: https://docs.dagster.io/latest/tutorial/presets/ 

This will let you bundle up your pre-defined YAML files and load them into Dagit. You'll then need to manually update your YAML files outside of Dagit when you want to save the configuration changes, but you'll easily be able to pull configuration presets into Dagit for ad-hoc execution.

**Comment by natekupp** [comment]
@naidu-rohit I'm going to close this for now, but please let us know (and feel free to re-open) if you have further issues that Presets don't resolve for you here!
