### ISSUE TITLE
Support for boto3 == 1.10.*

### ISSUE THREAD

**Issue by lee335** [dagster-io/dagster#2418]
Hi, first of all thanks for the great tool that you are developing. We are currently building our data infrastructure using dagster at our company.

We encountered a dependency problem using dagster-aws with the newest versions of sagemaker (> 1.49.0) that support tensorflow 2.

sagemaker needs boto3>=1.10.32, but dagster-aws currently only supports boto3==1.9.*

When are you planning to update your boto3 dependency to 1.10.* ?

Unfortunately we cannot use an older sagemaker version, because we need tensorflow 2 support.

Until then, is it critical to use dagster-aws with boto3>=1.10.32?

**Comment by schrockn** [comment]
Thanks for reporting. This pinning appears totally unnecessary. See https://dagster.phacility.com/D2723

This fix should go out in today's release.

**Comment by lee335** [comment]
Thank you very much for the fast response! We are looking forward for today's release.

**Comment by schrockn** [comment]
Great! Please feel free to reach out to us on slack. Always interested to hear how folks are using th the project.
