### ISSUE TITLE
User settings icon not available after experimental features

### ISSUE THREAD

**Issue by sganis** [dagster-io/dagster#24203]
### Dagster version

dagster, version 1.8.4

### What's the issue?

After enabling experimental features, the user settings icon (gear) disappeared. I can't find a way to reset the settings to default. I deleted the virtual environment, the $DAGSTER_HOME folder, and I installed dagster again, but the issue persists.
The only way to get back the user settings is changing the port number.

### What did you expect to happen?

To see the gear icon for user settings

### Deployment type

Local

### Additional information

In Mac M2 Max, macOs Sonoma 14.6.1

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
@sganis Would you mind sharing full page screenshots of what you're encountering, including your browser's address bar?

**Comment by sganis** [comment]
it is fixed after clear the browsing data in chrome. I even tried the incognito window and the issue still persisted. I don't have the screen anymore, the url was http://localhost:3000. I will close this issue and re-open if I can reproduce it, thank you.
