### ISSUE TITLE
Import jaffle_shop_project in dbt tutorial and not dbt_project

### ISSUE THREAD

**Issue by cmpadden** [dagster-io/dagster#24221]
### What's the issue or suggestion?

<img width="607" alt="image" src="https://github.com/user-attachments/assets/f9d6395d-0f3c-4654-a111-8835123aa1c3">

Community member, Sebastian, has pointed out that the import should be `jaffle_shop_project` and not `dbt_project` in https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/upstream-assets.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sandertan** [comment]
@cmpadden this is not fixed yet.

**Comment by cmpadden** [comment]
@sandertan, the import should be `dbt_project`, as this is the name of the variable that has been created in the `project.py` file, see here:

https://github.com/dagster-io/dagster/blob/7de09127c3b9a88188301ca80aa79f71522b7674/examples/docs_snippets/docs_snippets/integrations/dbt/tutorial/upstream_assets/project.py#L6-L8
