### ISSUE TITLE
dlt assets should store metadata on the number of records that have been extracted/loaded per run

### ISSUE THREAD

**Issue by gnilrets** [dagster-io/dagster#24222]
### What's the use case?

I'd like to be able to quickly get an idea of how many records by asset are loaded via dlt.  Storing this metadata in dagster would be very helpful.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gnilrets** [comment]
I hadn't noticed the column metadata issue yet.  Thanks!

**Comment by kristianandre** [comment]
Solved with https://github.com/dagster-io/dagster/pull/24306.
