### ISSUE TITLE
Add to Docs: dynamic pipeline generation

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2423]
It is not clear to users that they are able to dynamically generate Pipeline Definitions. Along that vein, we should clearly articulate the current limitations of Dagster so that users can quickly parse and understand what is possible, what's not possible, and what will soon be possible (wip)

**Comment by terekete** [comment]
Is there an example of how to do this ?

**Comment by fj-sanchez** [comment]
I have been thinking about it also, I would be interested to know more.

**Comment by alangenfeld** [comment]
here is one example of pipeline generation 
https://github.com/dagster-io/dagster/tree/master/examples/dagster_examples/dep_dsl
