### ISSUE TITLE
Serverless deployments timing out and taking >10 minutes to sync to agent

### ISSUE THREAD

**Issue by jrstats** [dagster-io/dagster#24244]
### Dagster version

1.8.4

### What's the issue?

Most of our Github actions serverless deploys are failing, and those that are not are taking ~10 minutes to complete.

I am hesitant to split it into many separate code locations because of the helper libraries, shared resources and interconnection between the assets locations. There is also no documentation that I can find that can help manage a split of a code location, while managing these factors.

In any case, the code location is only moderately sized, and only takes 15 seconds to start up locally.
A month ago, the deployment was taking less than 90 seconds, and then overnight it starts timing out or taking ~10 minutes.

```
...
Still waiting for agent to sync changes to ... This can take a few minutes.
Still waiting for agent to sync changes to ... This can take a few minutes.
Still waiting for agent to sync changes to ... This can take a few minutes.
Still waiting for agent to sync changes to ... This can take a few minutes.
Still waiting for agent to sync changes to ... This can take a few minutes.
Error: Some locations failed to load after being synced by the agent:
Error loading ...:
Exception: Timed out after waiting 615s for server
...
2024-08-28 17:17:28 +0000 - dagster.code_server - INFO - Stopping server once all current RPC calls terminate or 60 seconds pass
{"time": "28/Aug/2024:17:14:34 +0000", "log": "_server - Exception calling application: Invariant failed. Description: Active server hit error:\ndagster._core.errors.DagsterUserCodeUnreachableError: Could not reach user code server. gRPC Error code: UNAVAILABLE

...

Most recent connection error: dagster._core.errors.DagsterUserCodeUnreachableError: User code server request timed out due to taking longer than 60 seconds to complete.

Stack Trace:
  File "/dagster-cloud/dagster_cloud/workspace/user_code_launcher/user_code_launcher.py", line 2032, in _wait_for_server_process
    client.ping("")
  File "/dagster/dagster/_grpc/client.py", line 206, in ping
    res = self._query("Ping", api_pb2.PingRequest, echo=echo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dagster/dagster/_grpc/client.py", line 173, in _query
    self._raise_grpc_exception(
  File "/dagster/dagster/_grpc/client.py", line 151, in _raise_grpc_exception
    raise DagsterUserCodeUnreachableError(
```

### What did you expect to happen?

The deployment to take ~90 seconds.

### Deployment type

Dagster Cloud

### Deployment details

Standard serverless deployment, but using a custom image (only difference is installing selenium).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Hey James, as this is impacting your Dagster+ Serverless deployment please could you open a support ticket from in the app and our Dagster+ support team can investigate and be in touch with you directly. Check out dagster.io/support for how to do that!
