### ISSUE TITLE
Cloudwatch logger breaks dagit pipeline view

### ISSUE THREAD

**Issue by asharov** [dagster-io/dagster#2424]
I'm trying to use the Cloudwatch logger from dagster_aws. I have this mode definition
```python
prod_mode = ModeDefinition(
  name="prod",
  resource_defs={ ... },
  logger_defs={"cloudwatch": cloudwatch_logger}
)
```
I have a YAML file with
```yaml
loggers:
  cloudwatch:
    config:
      log_level: ERROR
      log_group_name: ...
      log_stream_name: ...
```
I'm reading the YAML file with `PresetDefinition.from_files` and setting them in the `@pipeline` decorator
```python
@pipeline(preset_defs=presets, mode_defs=modes)
def pipeline():
...
```

With this setup, when I run dagit, I get a blank page. The Javascript console shows this stacktrace
```
TypeError: undefined is not an object (evaluating 'n.__typename')
e — ConfigTypeSchema.tsx:74
e — ConfigTypeSchema.tsx:133
(anonymous function) — ConfigTypeSchema.tsx:102
map
e — ConfigTypeSchema.tsx:91
value — ConfigTypeSchema.tsx:198
```

This only affects the Pipelines page in dagit. The other pages, Solids, Runs, Playground, and Schedules work. I am able to run the pipeline in the Playground and the logger works when the pipeline runs. It is only the Pipelines page that fails.

This is with Dagster 0.7.9.

**Comment by natekupp** [comment]
thanks for the bug report @asharov - we'll look into it. 

For future reference I was able to repro this on 0.7.9 by adding the following to the `toys.many_events` pipeline in examples:

```
    preset_defs=[
        PresetDefinition.from_files(
            'test_cw',
            environment_files=[file_relative_path(__file__, 'environments/many_events.yaml')],
        )
    ],
    mode_defs=[ModeDefinition('default', logger_defs={'cloudwatch': cloudwatch_logger})],
```

But it does not repro on master

**Comment by natekupp** [comment]
I think this may be resolved now, but we should confirm before 0.8.0 release

**Comment by asharov** [comment]
Hi @natekupp I tried my setup now with 0.7.15 and everything's working fine there.

**Comment by natekupp** [comment]
ok great! closing
