### ISSUE TITLE
Fix flyte version number

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2428]
It is out of sync with the rest of versions and it is failing nightlies.

https://buildkite.com/dagster/dagster-nightly/builds/289#9c0ee8a4-6f27-46ed-a194-f88ea806bf3e

We should add the same version sync'ing check to our unit tests too.

**Comment by jbrambleDC** [comment]
Fixed in 6ae6e72a7c71c699993b055ff4652f9b559939ed. Added a test in the CI pipeline that ensures version equality across all modules.
