### ISSUE TITLE
Execute apis needed from host processes (e.g. dagster-graphql)

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2430]
Just tracking these:

1) Execute pipeline without access to pipeline definition
2) Execution plan compilation
3) Get pipeline subset
4) Execute plan (Not it might be better to eliminate from graphql entirely and instead use the dagster-api)

**Comment by helloworld** [comment]
More notes:
- Create type signature for all possible JSON
- All JSON should come from object that is whitelisted for serdes
