### ISSUE TITLE
[dagster-polars] `PolarsParquetIOManager` cannot save DataFrames with `polars.Decimal` columns

### ISSUE THREAD

**Issue by butterlyn** [dagster-io/dagster#24343]
### Dagster version

1.8.1

### What's the issue?

When using `dagster-polars` `0.24`, DataFrames with `polars.Decimal` columns raise an error when used with `PolarsDeltaIOManager` or `PolarsParquetIOManager`.

@danielgafni

### How to reproduce?

With `dagster-polars` `0.24.1` installed, the following code snippet raises an error:

```python
from dagster_polars import PolarsParquetIOManager
from dagster import materialize, asset
import polars as pl

@asset(
    io_manager_def=PolarsParquetIOManager()
)
def my_asset() -> pl.DataFrame:
    return pl.DataFrame(
        data={
            "col_1": [1, 2, 3],
        },
        schema={"col_1": pl.Decimal}
    )

materialize(assets=[my_asset])
```
```
dagster._core.errors.DagsterExecutionHandleOutputError: Error occurred while handling output "result" of step "my_asset":

During handling of the above exception, another exception occurred:
dagster._check.functions.CheckError: Value in dict mismatches expected type for key col_1. Expected value of type (<class 'str'>, <class 'float'>, <class 'int'>, <class 'bool'>, <class 'NoneType'>). Got value 3 of type <class 'decimal.Decimal'>
```

### Deployment type

Local

### Additional information

This issue is arising more since Polars version 1 now [uses `polars.Decimal` by default when converting from Arrow decimal columns](https://docs.pola.rs/releases/upgrade/1/#support-decimal-types-by-default-when-converting-from-arrow) (instead of casting to float).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by butterlyn** [comment]
@danielgafni you absolute legend... resolved the bug in <20 minutes

**Comment by cmpadden** [comment]
A legend indeed, nice work @danielgafni !
