### ISSUE TITLE
dagster_k8s dependency in dagster_celery

### ISSUE THREAD

**Issue by mrdrprofuroboros** [dagster-io/dagster#2435]
In new 7.10 release there is an implicit import dependency to dagster_k8s
so when trying to import celery_executor I get

`File "/opt/dagster/app/pipelines/celery_pipe.py", line 1, in <module>
    from dagster_celery import celery_executor
  File "/usr/local/lib/python3.6/site-packages/dagster_celery/__init__.py", line 1, in <module>
    from .executor import celery_executor, celery_k8s_job_executor
  File "/usr/local/lib/python3.6/site-packages/dagster_celery/executor.py", line 135, in <module>
    @executor(name='celery-k8s', config=celery_k8s_config())
  File "/usr/local/lib/python3.6/site-packages/dagster_celery/executor.py", line 99, in celery_k8s_config
    from dagster_k8s.job import DagsterK8sJobConfig
ModuleNotFoundError: No module named 'dagster_k8s'`

you could add dagster_k8s to dagster_celery explicit dependencies or better do smth with lazy imports

**Comment by natekupp** [comment]
Yeah, it's this line: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-celery/dagster_celery/executor.py#L99

will get a fix together today

**Comment by natekupp** [comment]
Fixed by https://dagster.phacility.com/D2834
