### ISSUE TITLE
dagster-ui allows installation of insecure version of `loader-utils`

### ISSUE THREAD

**Issue by lamalex** [dagster-io/dagster#24363]
### Dagster version

1.8.5

### What's the issue?

the dagster ui has transitive dependencies on `loader-utils` < 2.0.3
Prototype pollution vulnerability in function parseQuery in parseQuery.js in webpack loader-utils via the name variable in parseQuery.js. This affects all versions prior to 1.4.1 and 2.0.3.

### What did you expect to happen?

dependencies updated for latest critical security issues

### Deployment type

Other Docker-based deployment

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
Can you provide some logs or information to indicate where you're seeing this? Packages in `dagster-ui` should already be on 2.0.4 and 3.3.1.

**Comment by hellendag** [comment]
Thanks. Elsewhere in the yarn lockfile, `loader-utils@^2.0.0` is set to resolve to `2.0.4` within `dagster-ui`:

https://github.com/dagster-io/dagster/blob/2356582c40cc4e6da5cc3f3556fa7ece433841da/js_modules/dagster-ui/yarn.lock#L16572

Upon installation of the dependencies, there should not be any installed version of `loader-utils` below `2.0.4`. I'm not sure whether this can be flagged to the wiz.io scanner.

To verify this, you can check out the repository, and from the `dagster-ui` directory, run `yarn install` and `yarn why loader-utils`:

```
$ yarn why loader-utils
├─ @pmmmwh/react-refresh-webpack-plugin@npm:0.5.11
│  └─ loader-utils@npm:2.0.4 (via npm:^2.0.4)
│
├─ @pmmmwh/react-refresh-webpack-plugin@npm:0.5.11 [9022c]
│  └─ loader-utils@npm:2.0.4 (via npm:^2.0.4)
│
├─ @storybook/nextjs@npm:8.2.7
│  └─ loader-utils@npm:3.3.1 (via npm:^3.2.1)
│
├─ @storybook/nextjs@npm:8.2.7 [1c483]
│  └─ loader-utils@npm:3.3.1 (via npm:^3.2.1)
│
├─ adjust-sourcemap-loader@npm:4.0.0
│  └─ loader-utils@npm:2.0.4 (via npm:^2.0.0)
│
├─ file-loader@npm:6.2.0
│  └─ loader-utils@npm:2.0.4 (via npm:^2.0.0)
│
├─ file-loader@npm:6.2.0 [f4a81]
│  └─ loader-utils@npm:2.0.4 (via npm:^2.0.0)
│
├─ resolve-url-loader@npm:5.0.0
│  └─ loader-utils@npm:2.0.4 (via npm:^2.0.0)
│
├─ worker-loader@npm:3.0.8
│  └─ loader-utils@npm:2.0.4 (via npm:^2.0.0)
│
└─ worker-loader@npm:3.0.8 [d6e99]
   └─ loader-utils@npm:2.0.4 (via npm:^2.0.0)
```
