### ISSUE TITLE
The asset_checks prduced by build_time_partition_freshness_checks do not respect offset_end

### ISSUE THREAD

**Issue by derHeinzer** [dagster-io/dagster#24394]
### Dagster version

1.8.5

### What's the issue?

The freshness checks generated by build_time_partition_freshness_checks do not respect DailyPartitionsDefinition's end_offset parameter. The standard PartitionDefinition in our project looks like 

```
DailyPartitionsDefinition(start_date="2024-01-01", end_offset=1)
```
which means the current partition is todays partition (not yesterdays as would be for end_offset=0).

Sadly feshness checks generated by e.g.

```
freshness_checks = build_time_partition_freshness_checks(
    assets=[asset_key_xyz],
    deadline_cron="0 7 * * *",
    timezone=EXECUTION_TIMEZONE,
    severity=AssetCheckSeverity.ERROR,
)
```

always check if the asset with partition key corresponding to yesterdays partition has been materialized before the defined deadline. However this check is pretty useless in our case

### What did you expect to happen?

The end_offset parameter should be respected when evaluating the partition that needs to be materialized for the check to pass.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Thanks for the report - the attached PR should fix this.
