### ISSUE TITLE
CLI run parts of a DAG

### ISSUE THREAD

**Issue by Aylr** [dagster-io/dagster#244]
It would be great to be able to run parts of a DAG via the CLI. Because only parts of a DAG may be runnable without prior inputs, I'm not sure how this would be made usable for a noob - so maybe it's a dangerous tool at first? I do have a use case where I wanted to quickly iterate on a part of a dag to see materialized output, and thought the CLI would be more fun than toggling blocks of comments in code.

**Comment by mgasner** [comment]
we could specify a DAG subset in config @schrockn
