### ISSUE TITLE
[docs] - dagster.yaml file per project

### ISSUE THREAD

**Issue by sephib** [dagster-io/dagster#2444]
Hi,
The current [documentation for dagster.yaml](https://docs.dagster.io/docs/deploying/instance) stats that: 
> Dagster checks whether the environment variable DAGSTER_HOME is set  

thus since `DAGSTER_HOME` is an `environment variable` that is set **per user**, how would you configure a different `dagster.yaml` per project?  
We are a small DS team that would like to use `dagster` for several projects, and since each project is from a different domain the storage of the outputs and intermediates would most likely be saved in different locations.  
What is the best practice for such workflow?

**Comment by catherinewu** [comment]
cc @yuhan to consider adding to "best practices" documentation

**Comment by sryza** [comment]
Outputs and intermediates are now configured via IO managers, which are independent from dagster.yaml, so closing this.
