### ISSUE TITLE
bay_bikes example is problematic since there is no option to receive darksky API

### ISSUE THREAD

**Issue by sephib** [dagster-io/dagster#2445]
Hi,
Since [darksky](https://darksky.net/dev) has been bought by Apple, there is no option to sign up to receive an API key for running the [bay_bikes](https://github.com/dagster-io/dagster/tree/master/examples/dagster_examples/bay_bikes) example.

**Comment by catherinewu** [comment]
["How to migrate from Dark Sky API to OpenWeather One Call API"](https://openweathermap.org/darksky-openweather). Using OpenWeather API seems like an option since it has a [very similar api](https://openweathermap.org/darksky-openweather#match) and is free up to 1,000 calls a day

**Comment by iKintosh** [comment]
Hi!
I'd like to work on this issue)
I need to change bay_bikes example so it works with OpenWeather API. Do I understand correctly? Is it necessary to write tests for the pipeline?

**Comment by iKintosh** [comment]
As I understand bay_bikes pipeline needs historical data, but OpenWeather only allows you to load 5 previous days. This means that this cannot be done.

> Then use the backfill API by running dagster pipeline backfill daily_weather_pipeline --mode=development which will run 31 daily partitions to populate the weather_etl table for Jan 2020

**Comment by iKintosh** [comment]
Here is the proof https://openweathermap.org/price and https://openweathermap.org/api

**Comment by helloworld** [comment]
Hey @iKintosh, sorry for the late reply. here. 

> I need to change bay_bikes example so it works with OpenWeather API. Do I understand correctly? Is it necessary to write tests for the pipeline?

Yup, that's exactly right. There are already a decent amount of tests for the pipeline that should cover this functionality. 

> OpenWeather only allows you to load 5 previous days

This API might not be the best fit then - we might have to do some exploration about a free API that lets you query historical data.

**Comment by catherinewu** [comment]
going to close as bay_bikes is now a legacy example
