### ISSUE TITLE
error when running black  on dagster root

### ISSUE THREAD

**Issue by sephib** [dagster-io/dagster#2446]
Hi,  
When running `black .` on the root of the project  there is an error:  
> AttributeError: 'int' object has no attribute 'lower'   

Apparently `click` is requesting a  string and not int for `skip-string-normalization` when running the `dagster/pyproject.toml` file.  
> skip-string-normalization = 1   

possibly this needs to be raised with `click`

**Comment by DavidKatz-il** [comment]
I have submitted an [issue ](https://github.com/pallets/click/issues/1553)on this bug at `click` repo

**Comment by DavidKatz-il** [comment]
Following  ['click' issue response](https://github.com/pallets/click/issues/1553#issuecomment-627973139)  
The solution can be by adding quotes    
`skip-string-normalization = '1'`

**Comment by DavidKatz-il** [comment]
It was fix on this [commit](https://github.com/dagster-io/dagster/commit/66015f3a38c8efc426051360f02b97ea6161684c)

**Comment by natekupp** [comment]
Going to close this issue given @mgasner's fix has landed - thanks for reporting!
