### ISSUE TITLE
Automation Condition should handle partitioned assets

### ISSUE THREAD

**Issue by brunobento-delfos** [dagster-io/dagster#24474]
### What's the use case?

The auto materialize policy API on version 1.7 of dagster handled partitions gracefully.

For example, imagine three assets A, B, C. The asset C is dependent on A and B, and they're all partitioned daily.

Before, if C had an auto-materialize policy and I ran my pipeline for any day, it would run C automatically.
Now that the API has changed to Automation Condition, it only runs C automatically if A and B run the last partition. Anything other than that and C doesn't run.

### Ideas of implementation

AutomationCondition should handle better dependencies between partitioned assets. If I run a single partition of all parents, I expect the children to update them too.

### Additional information

My use case is that I have a job who depends on an asset of another job. So I took out those assets with double dependency and put AutoMaterializePolicy on them.

Now, that logic is broken after Dagster 1.8

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @brunobento-delfos -- what you observed is the default behavior of `AutomationCondition.eager()`, which has an `AutomationCondition.in_latest_time_window()` filter on it.

This filter serves to (e.g.) prevent people from accidentally launching large backfills when they add a new asset to their asset graph, but is not an essential part of the system. You can create your own policy which is a copy of the [eager condition](https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py?L442) without this condition:

```python
def my_policy() -> AutomationCondition:
    return (
        (
            AutomationCondition.newly_missing() | AutomationCondition.any_deps_updated()
        ).since_last_handled()
        & ~AutomationCondition.any_deps_missing()
        & ~AutomationCondition.any_deps_in_progress()
        & ~AutomationCondition.in_progress()
    ).with_label("eager")
```

This will allow your older downstream partitions to update in response to their parents being updated.

We're also working on making this more ergonomic -- there is an open pr to allow you to simply write:

```python
AutomationCondition.eager().without(AutomationCondition.in_latest_time_window())
```

**Comment by brunobento-delfos** [comment]
Thanks for the fast reply @OwenKephart ! Glad to know there is a workaround :)
