### ISSUE TITLE
Consider dividing up airflow tests

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2449]
They are frequently the long poll now in testing, and require the test images before execution, leading to builds that approach 15 minutes

![Screenshot 2020-05-11 12 42 21](https://user-images.githubusercontent.com/28738937/81604544-e2e75900-9384-11ea-9cfb-cab308802aa8.png)

Dividing this in two could shave 3 mins off the critical path.

**Comment by catherinewu** [comment]
After https://dagster.phacility.com/D2927, the builds should be ~12.5-13 minutes https://buildkite.com/dagster/dagster-diffs/builds/2156. The long poll now seems to be "airline-demo tests" and "dagster-flyte build example"

<img width="677" alt="Screen Shot 2020-05-14 at 11 57 43 AM" src="https://user-images.githubusercontent.com/6024687/81975403-cdb83780-95db-11ea-99eb-cd1bd97a01ef.png">

**Comment by catherinewu** [comment]
https://dagster.phacility.com/D2927
