### ISSUE TITLE
Dagit Select a Solid does not show all 350+ solids

### ISSUE THREAD

**Issue by Aylr** [dagster-io/dagster#245]
...but should it?

# STR
1. Build a dag with hundreds of solids
2. `dagit`
3. Click the *Select a Solid* dropdown
4. Note only a few are shown

![dagit350](https://user-images.githubusercontent.com/928247/47400960-9681ed00-d6fc-11e8-9bfd-68ae3b70e784.gif)

**Comment by schrockn** [comment]
does the typeahead work?

**Comment by Aylr** [comment]
Why yes it does. Closing this issue.
