### ISSUE TITLE
Unable to Change Resources for Assets Created from Ops using with_resources method.

### ISSUE THREAD

**Issue by Nomow** [dagster-io/dagster#24501]
### Dagster version

dagster, version 1.7.3

### What's the issue?

I am trying to reuse the implementation of **Ops** and define assets using the `AssetsDefinition.from_op` method. My goal is to change the resource linked to the asset, but it seems the `from_op` method doesn't provide a direct way to modify the resources.

For example, I have an Op `my_op` that uses `resource1`. When I create `asset1` from `my_op`, it links to `resource1` as expected. However, when I try to create `asset2` from the same `my_op` but with `resource2` instead of `resource1`, I encounter an issue.

Based on my understanding, the `with_resources` method should allow me to link `asset2` with `resource2`, but I receive the following error:

`dagster._core.errors.DagsterInvalidInvocationError: AssetsDefinition with key ["asset2"] has conflicting resource definitions with provided resources for the following keys: resource1. Either remove the existing resources from the asset or change the resource keys so that they don't overlap.
`

Or is it possible to assign somehow using `define_asset_job`, different resources to assets/jobs?
### What did you expect to happen?

asset2 would use resource2.

### How to reproduce?

```
from dagster import resource, op, AssetsDefinition, AssetKey, Definitions, ConfigurableResource, with_resources

class Resource1(ConfigurableResource):
    name : str  = 'resource1'

class Resource2(ConfigurableResource):
    name : str  = 'resource2'


@op(required_resource_keys={"resource1"})
def my_op(context):
    return context.resources.resource1.name


asset1 = AssetsDefinition.from_op(my_op, 
    keys_by_output_name={"result": AssetKey(["asset1"])},
)

asset2 = with_resources([AssetsDefinition.from_op(my_op, 
    keys_by_output_name={"result": AssetKey(["asset2"])},
)],
    resource_defs={
        "resource1": Resource2
    },
)

defs = Definitions(
    assets=[asset1 ] + asset2,
    resources={"resource1": Resource1(), "resource2": Resource2()},
)

```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by maximearmstrong** [comment]
Hey @Nomow - the problem here is that the resources are passed to the Definitions object as well as in the `with_resources()` function. Since `"resource1"` is defined in two places, there is a conflict.

That said, you cannot have conflicting version of a resource for the same resource key. This means that even if the first error is fixed, you'll get another error mentioning that `resource1` cannot be of different resource types for different assets.

A fix for that would be to create one op per resource. All ops could then call the same function:

```python
from dagster import (
    AssetKey,
    AssetsDefinition,
    ConfigurableResource,
    Definitions,
    op,
)


class Resource1(ConfigurableResource):
    name: str = "resource1"


class Resource2(ConfigurableResource):
    name: str = "resource2"


@op
def my_op_with_resource1(resource1: Resource1):
    return _my_op(resource1)


@op
def my_op_with_resource2(resource2: Resource2):
    return _my_op(resource2)


def _my_op(resource):
    return resource.name


asset1 = AssetsDefinition.from_op(
    my_op_with_resource1,
    keys_by_output_name={"result": AssetKey(["asset1"])},
)


asset2 = AssetsDefinition.from_op(
    my_op_with_resource2,
    keys_by_output_name={"result": AssetKey(["asset2"])},
)

defs = Definitions(
    assets=[asset1, asset2],
    resources={"resource1": Resource1(), "resource2": Resource2()},
)
```
