### ISSUE TITLE
dbt full refresh global config does not work

### ISSUE THREAD

**Issue by bmarcj** [dagster-io/dagster#24500]
### Dagster version

1.8.7

### What's the issue?

Documentation on dbt global configs is found here:

https://docs.getdbt.com/reference/global-configs/about-global-configs

This includes the fairly critical `--full-refresh` flag.

Dagster documentation:
https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.DbtCliResource.global_config_flags

Global flags are supposed to be supported by this setting.

Unfortunately, the dagster implementation places global flags at the start of the command e.g.

`dbt --full-refresh build ...`

This causes an error with the dbt command line (it expects this to be at the *end* of the invocation).

### What did you expect to happen?

The flag should be in the correct place to work.

### How to reproduce?

Run a dbt asset with the global config set to ["--full-refresh"]

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Thanks for reporting, I'm adding a PR to fix: https://github.com/dagster-io/dagster/pull/24615

**Comment by bmarcj** [comment]
Thanks @clairelin135. That's a fine fix for this issue. Are there plans to support full refresh for dbt out of the box, or is this integration something users are expected to handle themselves?

**Comment by clairelin135** [comment]
@bmarcj it's come to my attention that `--full-refresh` actually isn't a valid global config flag, because it isn't accepted by all commands (i.e. `dbt parse`). So I'm actually adjusting that PR to clarify that the list of global config flags are the ones outputted by `dbt --help`.

> Are there plans to support full refresh for dbt out of the box, or is this feature integration something users are expected to handle themselves?

@rexledesma do you know the answer for this?
