### ISSUE TITLE
Support dbt YAML selectors

### ISSUE THREAD

**Issue by yche0326** [dagster-io/dagster#24515]
### What's the use case?

When using `dagster_dbt.build_dbt_asset_selection` or `dagster_dbt.DbtManifestAssetSelection`, it is only possible to specify `select` and `exclude` strings. This could work in the cases of relatively straightforward selection logic, but might get tricky & resulting in a very long selection/exclude string.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Duplicates https://github.com/dagster-io/dagster/issues/22252
