### ISSUE TITLE
[Feature Request] Make materializations that start with http(s) into links

### ISSUE THREAD

**Issue by cjroth** [dagster-io/dagster#2452]
We would love to be able to click on the materialization and have it go to the link as many of our materializations are S3 assets.

It would also be cool if clicking on the materializations could go to the new Assets tab when there is an `asset_key` defined.

**Comment by alangenfeld** [comment]
you can add a `EventMetadataEntry.url` on the `metadata_entries` of your `Materialization` to get a clickable link in dagit

**Comment by cjroth** [comment]
This solved the issue, thanks @alangenfeld!
