### ISSUE TITLE
You have defined two solid definitions named "bq_solid" in repository 

### ISSUE THREAD

**Issue by zzztimbo** [dagster-io/dagster#2459]
**given:** 

**in pipeline a:** 
```
a_df = bq_solid_for_queries(["select * from a"]).alias("a_df")
```

**in pipeline b:** 
```
b_df = bq_solid_for_queries(["select * from b"]).alias("b_df")
```

I'm seeing the following error on startup of the dagit ui. 

```
PythonError encountered when loading pipelines:
dagster.core.errors.DagsterInvalidDefinitionError: You have defined two solid definitions named "bq_solid" in repository "data_processing_workflow_repo". Solid definition names must be unique within a repository. The solid definition has been defined in pipeline "a_pipeline" and it has been defined again in pipeline "b_pipeline." 
```

Am I using `bq_solid_for_queries` improperly? 

I do see the solid being defined within the function `bq_solid_for_queries`.

https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/solids.py#L42-L64

**Comment by alangenfeld** [comment]
thats a bug - we need to be setting `name=` on `@solid` to ensure unique definition names

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D2942

**Comment by zzztimbo** [comment]
thanks @alangenfeld
