### ISSUE TITLE
Audit BigQuery Integration

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2461]
Bugs like this https://dagster.phacility.com/D2942 indicate that this library is both not that used and has some issues. Given how old it is and what we have learned about the system, it is worth re-examining this and figuring out what we want this to be.

**Comment by natekupp** [comment]
Some improvements for now in https://dagster.phacility.com/D3424, will do the rest in 0.9.0

**Comment by catherinewu** [comment]
Going to mark this as closed since we use BigQuery in dogfooding pipelines. Not sure how else we can audit BigQuery cc @natekupp
