### ISSUE TITLE
Warning Error after upgrading to Dagster 1.8.6 `ModuleNotFoundError No module named 'dbt.adapters.duckdb'`

### ISSUE THREAD

**Issue by kennycontreras** [dagster-io/dagster#24644]
### Dagster version

1.8.6

### What's the issue?

Running `dbt` commands with the latest version of Dagster throws a warning error even though `duckdb` adapter is not being used. 

```bash
pipelines-dagster  | Traceback (most recent call last):
pipelines-dagster  |   File "/usr/local/lib/python3.10/site-packages/dagster_dbt/core/resource.py", line 383, in _initialize_adapter
pipelines-dagster  |     from dbt.adapters.duckdb.credentials import DuckDBCredentials
pipelines-dagster  | ModuleNotFoundError: No module named 'dbt.adapters.duckdb'
```

![Screenshot 2024-09-22 at 19 30 26](https://github.com/user-attachments/assets/c39f5e7c-3170-44dd-b182-5740590d14b0)

### What did you expect to happen?

No warnings/errors since duckdb adapter is not being use. 

### How to reproduce?

Any `dbt` command executed from a dagster pipeline could show the warning error. 

### Deployment type

Docker Compose

### Additional information

My current deployment is using a dbt-impala adapter. dbt-core version 1.7.0

I found this issue that it's close https://github.com/dagster-io/dagster/issues/23952 but the error persist in newer versions too. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
This warning was fixed in the 1.8.7 release - upgrading the version used in your code will make it go away: https://docs.dagster.io/changelog#bugfixes-1
