### ISSUE TITLE
JobBackfillsQuery

### ISSUE THREAD

**Issue by ArtiNgqobe** [dagster-io/dagster#24649]
### Dagster version

1.8.8

### What's the issue?

Operation name: {JobBackfillsQuery}

Message: Enum 'BulkActionStatus' cannot represent value: 'COMPLETED_SUCCESS'

Path: ["partitionSetOrError","backfills",0,"status"]

Locations: [{"line":22,"column":3},{"line":90,"column":3},{"line":115,"column":3}]

Stack Trace:
  File "C:\ProgramData\anaconda3\envs\dasgter\Lib\site-packages\graphql\execution\execute.py", line 542, in execute_field
    completed = self.complete_value(
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\dasgter\Lib\site-packages\graphql\execution\execute.py", line 614, in complete_value
    completed = self.complete_value(
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\dasgter\Lib\site-packages\graphql\execution\execute.py", line 641, in complete_value
    return self.complete_leaf_value(cast(GraphQLLeafType, return_type), result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\dasgter\Lib\site-packages\graphql\execution\execute.py", line 776, in complete_leaf_value
    serialized_result = return_type.serialize(result)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\dasgter\Lib\site-packages\graphene\types\definitions.py", line 58, in serialize
    return super(GrapheneEnumType, self).serialize(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\dasgter\Lib\site-packages\graphql\type\definition.py", line 1247, in serialize
    raise GraphQLError(

### What did you expect to happen?

I am new dagster but i expected backfill infor

### How to reproduce?

When you have partitioned jobs and you run a backfill

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
For reproducing, could you please share the code for your job and any other relevant components?

**Comment by ArtiNgqobe** [comment]
@garethbrickman ; i use an asset sensor to trigger an asset from another job based on an asset materialization from one job; 

**asset sensor code**

@asset_sensor(
    asset_key=AssetKey(['project_align', 'fetch_api_data', 'update_product_table_asset']),
    job=pim_misalignment_job
)
def pim_data_validation_sensor(context, asset_event: EventLogEntry):
    # Ensure the event is an asset materialization event
    assert asset_event.dagster_event and asset_event.dagster_event.asset_key

    # Retrieve the materialization event
    materialization = asset_event.dagster_event.event_specific_data.materialization

    # Check if metadata is not empty
    if materialization.metadata:
        # Log the metadata for debugging
        context.log.info(f"Metadata: {materialization.metadata}")

        try:
            # Access the "all_lists" value from the materialization event
            all_lists = materialization.metadata.get("all_lists")  # Use metadata.get() to access "all_lists"

            if all_lists:
                context.log.info(f"Passing all_lists {all_lists} to the get_pim_updates asset")

                # Update run_config to reflect the correct structure
                run_config = {
                    "ops": {
                        "project_align__gather_misalignments__get_pim_updates": {
                            "config": {
                                "data": all_lists  # Pass the all_lists here as part of the config
                            }
                        }
                    }
                }

                context.log.info(f"Run config: {run_config}")

                return RunRequest(run_key=None, run_config=run_config)
            else:
                context.log.warning("No 'all_lists' found in metadata.")

        except KeyError as e:
            context.log.error(f"KeyError: {e}")
    else:
        context.log.warning("Materialization metadata is empty.")

**the asset being triggered**

@asset(
    group_name='Project_Align',
    key_prefix=['project_align', 'gather_misalignments'],
    output_required=False,
    compute_kind="sqlserver",
    description='Fetches updated data from PIM, checks alignment with DAM data, and logs discrepancies.',
    ins={"data": AssetIn(key=AssetKey(['project_align', 'fetch_api_data', 'update_product_table_asset']))}
)
def get_pim_updates(context, data: list[str]):
    context.log.info(f'here {data}')
    tags = context.run.tags
    context.log.info(f'Tags: {tags}')

    if 'dagster/sensor_name' in tags:
        updated_by = 'sensor'
        context.log.critical(f"Run launched by sensor: {tags['dagster/sensor_name']}")
        df, gtins_for_later = call_pim_api(api_key=api_config()["Silo1API"]["project_align_api_key"],
                                           url=api_config()["Silo1API"]["url"], gtins=data, context=context)

        yield Output(
            value=(df, gtins_for_later, updated_by),
            metadata={
                "Number of rows in DataFrame": len(df),
                "Data (Top 200)": MetadataValue.md(df.head(200).to_markdown())
            }
        )
    else:
        updated_by = 'schedule'
        context.log.critical(f"Run launched by schedule: {tags['dagster/schedule_name']}")
        df, gtins_for_later = call_pim_api(api_key=api_config()["Silo1API"]["project_align_api_key"],
                                           url=api_config()["Silo1API"]["url"],
                                           updated_after=today)
        # Yield Output with metadata and the two objects
        yield Output(
            value=(df, gtins_for_later, updated_by),
            metadata={
                "Number of rows in DataFrame": len(df),
                "Data (Top 200)": MetadataValue.md(df.head(200).to_markdown())
            }
        )

**Comment by ArtiNgqobe** [comment]
> What about `pim_misalignment_job`? Originally you said the error happened "When you have partitioned jobs and you run a backfill"

@garethbrickman  apologies, the initial error was resolved by upgrading dagster to newest version, should i close this issue? but its a different one and i have the latest version installed 1.8.10, when the second asset is ran and you view its run from the RUNS page you get this error, the job runs and prints events etc. but doesn't show the graph, happy to log a new issue and close this one, thanks; 
![image](https://github.com/user-attachments/assets/374ed1c6-68b8-46b1-8431-70dd9b388dca)

**Comment by ArtiNgqobe** [comment]
@garethbrickman 
![image](https://github.com/user-attachments/assets/9d515d33-f5e5-41df-b7b0-ca628c3df246)

**Comment by garethbrickman** [comment]
I think that is [this known bug ](https://github.com/dagster-io/dagster/discussions/24898#discussioncomment-10882915)with the new experimental Runs page so please post/follow that discussion about it. 

You can disable the experimental Runs page by going into User Settings:

![Screenshot 2024-10-09 at 09 23 50](https://github.com/user-attachments/assets/2fe68420-fa3b-40b3-a841-434c746197a4)

![Screenshot 2024-10-09 at 09 24 17](https://github.com/user-attachments/assets/bb3eb0db-a675-4ceb-89e7-cad41ed3475c)

**Comment by ArtiNgqobe** [comment]
@garethbrickman  thanks but i'm afraid it happens regardless of the change being on or not, I will perhaps log a new issue specifically for this as its being happening before i even upgraded to latest version, thanks
