### ISSUE TITLE
dagster dev not working inside conda env

### ISSUE THREAD

**Issue by nsteins** [dagster-io/dagster#24696]
### Dagster version

1.8.8

### What's the issue?

I am not able to run a webserver using the `dagster dev` command inside a conda env. Inside a fresh environment, running `dagster dev` yields the error:

> Usage: dagster dev [OPTIONS]
Try 'dagster dev --help' for help.
>
>Error: The dagster-webserver Python package must be installed in order to use the dagster dev command. If you're using pip, you can install the dagster-webserver package by running "pip install dagster-webserver" in your Python environment.

However `dagster-webserver` does run correctly as expected

### What did you expect to happen?

I expect `dagster dev` to launch a dagster webserver locally

### How to reproduce?

Tested from a fresh environment

```
conda create -n test_env python=3.10
conda activate test_env
pip install dagster-webserver
dagster dev
```

It appears that everything is installed and located correctly in the env:

`whereis pip dagster dagster-webserver`

> pip: /usr/local/Caskroom/miniconda/base/envs/test_env/bin/pip
> dagster: /usr/local/Caskroom/miniconda/base/envs/test_env/bin/dagster
> dagster-webserver: /usr/local/Caskroom/miniconda/base/envs/test_env/bin/dagster-webserver

`pip freeze`

> alembic==1.13.3
> aniso8601==9.0.1
> annotated-types==0.7.0
> anyio==4.6.0
> backoff==2.2.1
> certifi==2024.8.30
> charset-normalizer==3.3.2
> click==8.1.7
> coloredlogs==14.0
> croniter==3.0.3
> dagster==1.8.8
> dagster-graphql==1.8.8
> dagster-pipes==1.8.8
> dagster-webserver==1.8.8
> docstring_parser==0.16
> exceptiongroup==1.2.2
> filelock==3.16.1
> fsspec==2024.9.0
> gql==3.5.0
> graphene==3.3
> graphql-core==3.2.4
> graphql-relay==3.2.0
> greenlet==3.1.1
> grpcio==1.66.1
> grpcio-health-checking==1.62.3
> h11==0.14.0
> httptools==0.6.1
> humanfriendly==10.0
> idna==3.10
> Jinja2==3.1.4
> Mako==1.3.5
> markdown-it-py==3.0.0
> MarkupSafe==2.1.5
> mdurl==0.1.2
> multidict==6.1.0
> packaging==24.1
> protobuf==4.25.5
> pydantic==2.9.2
> pydantic_core==2.23.4
> Pygments==2.18.0
> python-dateutil==2.9.0.post0
> python-dotenv==1.0.1
> pytz==2024.2
> PyYAML==6.0.2
> requests==2.32.3
> requests-toolbelt==1.0.0
> rich==13.8.1
> six==1.16.0
> sniffio==1.3.1
> SQLAlchemy==2.0.35
> starlette==0.39.0
> structlog==24.4.0
> tabulate==0.9.0
> tomli==2.0.1
> toposort==1.10
> tqdm==4.66.5
> typing_extensions==4.12.2
> universal_pathlib==0.2.5
> urllib3==2.2.3
> uvicorn==0.30.6
> uvloop==0.20.0
> watchdog==5.0.2
> watchfiles==0.24.0
> websockets==13.1
> yarl==1.12.1

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
See the docs here for how to use `dagster dev` and locate your Dagster code for it: https://docs.dagster.io/guides/running-dagster-locally#locating-your-code

**Comment by nsteins** [comment]
The issue was not with locating the code, but the error claiming dagster-webserver was not installed, regardless of commands passed to the command.

However, I am no longer able to reproduce this error, which leads me to believe I had something misconfigured with my environment that has been fixed, so I am closing the issue.
