### ISSUE TITLE
Error installing Dagster

### ISSUE THREAD

**Issue by brandybobandyistaken** [dagster-io/dagster#24767]
### Dagster version

1.8.8

### What's the issue?

Tried to install dagster (no version specified) in a fresh venv on python 3.8.10, and for the following:

ERROR: grpcio-health-checking 1.66.1 has requirement protobuf<6.0dev,>=5.26.1, but you'll have protobuf 4.25.5 which is incompatible.

### What did you expect to happen?

Install correctly

### How to reproduce?

Install dagster on the above version of python 

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by brandybobandyistaken** [comment]
Here is the output of piip list:

Package                Version
---------------------- -----------
alembic                1.13.3
annotated-types        0.7.0
certifi                2024.8.30
charset-normalizer     3.3.2
click                  8.1.7
coloredlogs            14.0
croniter               3.0.3
dagster                1.8.8
dagster-pipes          1.8.8
docstring-parser       0.16
filelock               3.16.1
fsspec                 2024.9.0
greenlet               3.1.1
grpcio                 1.66.1
grpcio-health-checking 1.66.1
humanfriendly          10.0
idna                   3.10
importlib-metadata     8.5.0
importlib-resources    6.4.5
jinja2                 3.1.4
Mako                   1.3.5
markdown-it-py         3.0.0
MarkupSafe             2.1.5
mdurl                  0.1.2
packaging              24.1
pip                    20.0.2
pkg-resources          0.0.0
protobuf               4.25.5
pydantic               2.9.2
pydantic-core          2.23.4
pygments               2.18.0
python-dateutil        2.9.0.post0
python-dotenv          1.0.1
pytz                   2024.2
PyYAML                 6.0.2
requests               2.32.3
rich                   13.8.1
setuptools             44.0.0
six                    1.16.0
SQLAlchemy             2.0.35
structlog              24.4.0
tabulate               0.9.0
tomli                  2.0.1
toposort               1.10
tqdm                   4.66.5
typing-extensions      4.12.2
universal-pathlib      0.2.5
urllib3                2.2.3
watchdog               4.0.2
zipp                   3.20.2

**Comment by gibsondan** [comment]
Hi @brandybobandyistaken - can you try upgrading pip before installing? (with "pip install -U pip")

**Comment by brandybobandyistaken** [comment]
This fixed the issue thanks!
