### ISSUE TITLE
Unable to resume pipeline from solid where it was terminated

### ISSUE THREAD

**Issue by cjroth** [dagster-io/dagster#2480]
Possible Bug: I sometimes terminate solids that are taking a really long time so that I can debug what they are stuck on. When I try re-executing it lets me start from the "failure" (even though I terminated and there was no failure), but that just starts it from the beginning of the pipeline again.

**Comment by schrockn** [comment]
I believe this should be resolved by @mgasner and @yuhan's work on this. Reopen if not accurate.
