### ISSUE TITLE
Replacing config dict with python-box object or similar for attribute access

### ISSUE THREAD

**Issue by jdb78** [dagster-io/dagster#2481]
Dagster is really a great product. I think usability could be improved if the config object would be a frozen `Box` object (https://pypi.org/project/python-box/). What are your thoughts? Should be a rather trivial change and 100% backwards-compatible.

**Comment by schrockn** [comment]
Can you give us some more context on when you would want to be able to use this? In the body of solids?

**Comment by jdb78** [comment]
I think in solids, it would be great, if the `solid_config` would be a frozen `Box` object instead of a frozen dict.

**Comment by schrockn** [comment]
I don't think this is something we would add to our core, as it is quite a matter of personal preference and brings in another dependency. I think we would instance leave this to user choice and allow them pull this library into your project and wrap config dictionaries themselves.

**Comment by jdb78** [comment]
Maybe, what could be done, is prevent recasting the config when passing it as `environment_dict` to `execute_pipeline`. At the moment, the `Box` object is recasted and `solid_config` becomes a frozen dict.

I think this could be achieved by modifying line https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/utils/__init__.py#L148
As a `dict` is directly enforced. Maybe, better we can return just `self` instead of `dict(self)`. This would allow the user to use subclassed dictionaries.

**Comment by mgasner** [comment]
hm, in python 3 we could use a dataclass. cf #2545

**Comment by yuhan** [comment]
closing in favor of #2545
