### ISSUE TITLE
Cannot view Dagster 1.6.4 documentation

### ISSUE THREAD

**Issue by ryandstoughton** [dagster-io/dagster#24853]
### What's the issue or suggestion?

When navigating to the [Dagster 1.6.4 documentation](https://release-1-6-4.dagster.dagster-docs.io/getting-started), the URL changes, but the most current version of documentation is shown instead. Every other version works, including the surrounding versions 1.6.3 and 1.6.5.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Hey @ryandstoughton thanks for reporting this. Do you need to access the information for that version? We'll soon be migrating to a new docs platform.

**Comment by ryandstoughton** [comment]
I've since upgraded versions, but I appreciate it!
