### ISSUE TITLE
A failed scheduled pipeline didnt log properly

### ISSUE THREAD

**Issue by jtmiclat** [dagster-io/dagster#2488]
Versions of dagster
```
dagit==0.7.13             
dagster-cron==0.7.13     
dagster-gcp==0.7.13       
dagster-graphql==0.7.13  
dagster-pandas==0.7.13    
dagster-postgres==0.7.13  
dagster-slack==0.7.13    
```

Error message when examing logs using UI. 

![Screenshot from 2020-05-20 21-27-54](https://user-images.githubusercontent.com/30991698/82451643-ded3dd80-9ae0-11ea-8ed4-6feda32eca6d.png)

```
UnboundLocalError: local variable 'execution_plan_index' referenced before assignment
  File "/usr/local/lib/python3.7/site-packages/dagster_graphql/implementation/execution/scheduled_execution.py", line 123, in start_scheduled_execution
    run, result = _execute_schedule(graphene_info, external_pipeline, execution_params, errors)
  File "/usr/local/lib/python3.7/site-packages/dagster_graphql/implementation/execution/scheduled_execution.py", line 169, in _execute_schedule
    execution_plan_snapshot=execution_plan_index.execution_plan_snapshot,
```

Looking at the code, dagster is not catching the case when `validation_result.success` is falsy and therefore execution_plan_index is not defined. 

https://github.com/dagster-io/dagster/blob/5c6b8e662dc0cdf6e3e9912ddc48f5b10106908f/python_modules/dagster-graphql/dagster_graphql/implementation/execution/scheduled_execution.py#L150-L172

Having a hard time finding a way to reproduce this but I can close the issue if the code above is intended.

**Comment by schrockn** [comment]
Thank you for the report. Definitely a bug on our end and we should be able to push a fix in a release soon (probably tmrw).

The way to fix is in the short term is to fix the configuration errors in pipeline run that you are scheduling.

**Comment by jtmiclat** [comment]
Thanks! Seems like a we forgot add `storage` to the `resources` config.

**Comment by helloworld** [comment]
This has been fixed and will go out in the release tomorrow. Sorry you ran into this!
