### ISSUE TITLE
Deprecation warnings in dagster-graphql tests

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2491]
```
/Users/max/.virtualenvs/dagster/lib/python3.7/site-packages/graphql/backend/core.py:32: DeprecationWarning: The 'context' alias has been deprecated. Please use 'context_value' instead.
    return execute(schema, document_ast, *args, **kwargs)```

**Comment by mgasner** [comment]
`

/workdir/examples/.tox/py35/lib/python3.5/site-packages/graphql/backend/core.py:32: DeprecationWarning: The 'root' alias has been deprecated. Please use 'root_value' instead.
--


`

**Comment by danieldiamond** [comment]
Issue appears to be resolved [here](https://github.com/dagster-io/dagster/commit/88de30f5a439c187c1da7b48f7858d1e80f8e1d5)
