### ISSUE TITLE
[Documentation Feedback] Problem on /dagster-plus/developing-testing/code-locations#syncing-the-workspace page

### ISSUE THREAD

**Issue by namaste-supplyx** [dagster-io/dagster#24990]
Page seems to not work anymore (see title):

404: Not Found

The page you are looking for does not exist.

If it should, please use theShare Feedback button at the top of this page to let us know

**Comment by garethbrickman** [comment]
Hey @namaste-supplyx, where did you encounter the link to that page? It seems like it's deprecated. This is the current page for code locations in Dagster Plus: https://docs.dagster.io/dagster-plus/managing-deployments/code-locations

**Comment by namaste-supplyx** [comment]
Hey @garethbrickman, I'm currently setting up Dagter+ and if the dagster_cloud.yaml is missing in the root of the repository and you try to import a Dagster project via the dagster+ UI you get an error saying that the dagster_cloud.yaml is missing with a link to the deprecated page.
