### ISSUE TITLE
Time to rebuild integration images?

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2502]
I think they were updated last <3 months ago. Probably quite out-of-date with where the ecosystem is...

**Comment by natekupp** [comment]
Almost certainly; I'd be happy to guide someone else through the process this time, just to distribute the knowledge. 

It also might be a good exercise to set up the integration image build to run nightly.

FWIW the process is documented here: https://github.com/dagster-io/dagster/tree/master/.buildkite/images

**Comment by natekupp** [comment]
Some notes while I'm looking at https://github.com/dagster-io/dagster/blob/master/.buildkite/images/docker/snapshot-update.sh:

- sphinxcontrib-images - I don't think we need this anymore
- matplotlib: now available for py38 (can remove override)
- tensorflow: now available for py38 (can remove override)

The rest of the manual overrides here can go away once we drop 3.5.

**Comment by xinbinhuang** [comment]
Would this be suitable for someone who has not contributed to this project before - like me ;) ?
I think this would be a great opportunity for me to learn more about the ecosystem.

**Comment by natekupp** [comment]
hey @xinbinhuang thanks for asking! This one might be less ideal since it involves some of our internal tooling, credentials etc. as well—I will ping you on the Dagster Slack to follow up

**Comment by natekupp** [comment]
See also #2306

**Comment by natekupp** [comment]
Fixed by https://dagster.phacility.com/D3213
