### ISSUE TITLE
[Documentation Feedback] Problem on /concepts/automation/declarative-automation page

### ISSUE THREAD

**Issue by shivonchain** [dagster-io/dagster#25032]
Not sure why `AutomationCondition.on_cron()` is listed but `AutomationCondition.cron_tick_passed()` is not listed as a pre-built condition. It is unclear what the difference is between the two, especially as `cron_tick_passed()` is used as an example followed immediately by the example using `on_cron()`.

**Comment by garethbrickman** [comment]
`cron_tick_passed` is technically not a pre-built condition, but an [operand](https://docs.dagster.io/concepts/automation/declarative-automation/customizing-automation-conditions#operands) for use when making custom conditions.
