### ISSUE TITLE
k8s deploy error - Celery .Values.celery.image.repository is required

### ISSUE THREAD

**Issue by terekete** [dagster-io/dagster#2509]
Hi Dagster Community,
Attempting to use the dagster-k8's module and running into an error: 

Error: execution error at (dagster/templates/_helpers.tpl:36:3): Celery worker image repository .Values.celery.image.repository is required
helm.go:84: [debug] execution error at (dagster/templates/_helpers.tpl:36:3): Celery worker image repository .Values.celery.image.repository is required

I am just trying a dryrun: helm install dagster --dry-run --debug helm/dagster
Any help is appreciated.

Thanks,
M.

**Comment by catherinewu** [comment]
Hi M, could you share that snipped in your values.yaml file where .Values.celery.image.repository is defined?

**Comment by terekete** [comment]
Appears I missed configuring the values.yaml.

Would there be an example I can refer to. When I look at say the celery section I have no image specified and assuming I need to reference a image repo.  Is there any reference to images or Dockerfiles from which I can bootstrap ?

**Comment by catherinewu** [comment]
I'm going to close the issue since the original question was resolved. Celery deprecated their official image in docker hub (https://hub.docker.com/_/celery); in the reasoning, they link to this comment (https://github.com/docker-library/celery/issues/1#issuecomment-287655769) which recommends using the application image

**Comment by natekupp** [comment]
@terekete this is the celery Dockerfile we've been using for testing: https://gist.github.com/natekupp/0eb55aec885358dd89ad8572db32877f

You can likely do something similar, although you'll probably want to install from PyPI instead of using editable installs.

**Comment by terekete** [comment]
thanks both!
