### ISSUE TITLE
Add tests for pynotify in dagster-postgres

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2510]
This has poor test coverage and this finally block looks suspicious:

```
    finally:
        conn.close()
        for s in signals_to_handle or []:
            if s in original_handlers:
                signal_name = construct_signals(s).name
                signal.signal(s, original_handlers[s])
```

(`signal_name` is unused)

**Comment by mgasner** [comment]
see #2091

**Comment by sidkmenon** [comment]
Should be more or less closed via pynotify cleanup in https://github.com/dagster-io/dagster/commit/39897af913f1484b4d7c7d9d04ffb835b00f2eab; the listen/notify functionality is covered pretty well in the shared EventLog & PG-specific test suite, and the error handling cases are covered in test_pynotify.py.
