### ISSUE TITLE
Chop up dagster-graphql tests in the several CI runs

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2514]
With our new test matrix approach test times are increasing and we have to chop it up a bit. Luckily the new infra autoapplies marks to this should be straightforward

All runs get a graphql_context_test_suite mark, so one run should be NOT graphql_context_test_suite

Then divide the rest. A first attempt would be dividing the remainder between in_memory_instance and sqlite_instance and tags, but there are a bunch of ways to potentially divide it.

**Comment by natekupp** [comment]
Closing given the new tox-based test partitioning
