### ISSUE TITLE
Project: Make CliApiRunLauncher Resilient to Dagit Process Restarts

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2524]
Currently this component maintains a mapping between process id and run id in memory. This works fine as long as the dagit process is up and running. If the run processes terminate unexpectedly the pipeline runs state is correct maintained.

This breaks apart if that mapping is lost due to a process restart, leaving the pipeline runs potentially in an inconsistent state or unterminate-able state. 

We need to make it so that if one restarts the dagit server you can still terminate running runs and also correctly report their state if they unexpectedly crash.

**Comment by schrockn** [comment]
Likely will be bounced to 0.9.0, but this would be a good medium-sized task for an infra-minded eng on the front end of 0.9.0

**Comment by alangenfeld** [comment]
This is also key for being able to terminate runs from dagit that were launched from the scheduler.

**Comment by gibsondan** [comment]
GrpcRunLauncher has this property now, so if we move everybody to managed grpc servers and take CliApiRunLauncher out of the default path, we will get this for free

**Comment by natekupp** [comment]
This is resolved now cc @gibsondan
