### ISSUE TITLE
Exceptions in RunLauncher launch_run are swallowed

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2525]
I noticed this in passing when working on dagster-k8s + celery run launcher - just filing a bug so this doesn't get dropped. will try to put together a minimal repro

**Comment by mgasner** [comment]
should this be behind a user code error boundary

**Comment by schrockn** [comment]
I actually think this is mostly a frontend issue. We should have an error boundary but all errors become PythonErrors right now and the stack trace is not displayed

**Comment by helloworld** [comment]
https://dagster.phacility.com/D3568
