### ISSUE TITLE
We truncate solid names in the log pane which makes debugging hard

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2530]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/609349/83654740-5b030200-a572-11ea-94c6-fd96eef10cbe.png">

**Comment by yuhan** [comment]
seems have been addressed it in https://dagster.phacility.com/D3229
![image](https://user-images.githubusercontent.com/4531914/84093209-6dd06900-a9ae-11ea-816d-21ea9803d666.png)
