### ISSUE TITLE
Error loading repository location my-dagster-project; gRPC server exited with return code 0 while starting up with the command

### ISSUE THREAD

**Issue by joanafloresc** [dagster-io/dagster#25339]
### What's the issue?

I installed dagster and it was running perfectly. I used inside docker containers, as well as outside.
Today, the same projects started to not run in local dagster. I even used projects that are running well in my colleagues laptop.

### What did you expect to happen?

**This happens after inputing dagster dev --code-server-log-level debug**

2024-10-17 17:59:52 +0200 - dagster.code_server - INFO - Starting Dagster code server for module my-dagster-project  on port 54730 in process 25376
2024-10-17 17:59:52 +0200 - dagster.code_server - INFO - Started Dagster code server for module my-dagster-project  on port 54730 in process 25376
2024-10-17 17:59:53 +0200 - dagster.code_server - INFO - Starting Dagster code server for module my-dagster-project on port 54733 in process 25448
2024-10-17 17:59:53 +0200 - dagster.code_server - INFO - Started Dagster code server for module my-dagster-project on port 54733 in process 25448
2024-10-17 18:00:13 +0200 - dagster.code_server - INFO - Stopping server once all current RPC calls terminate or 60 seconds pass
2024-10-17 18:00:13 +0200 - dagster.code_server - INFO - Shutting down Dagster code server for module my-dagster-project on port 54730 in process 25376

C:\Users\username\projects_folder\my-dagster-project\venv\Lib\site-packages\dagster\_core\workspace\context.py:657: 
UserWarning: Error loading repository location my-dagster-project:
Exception: gRPC server exited with return code 0 while starting up with the command: 
"C:\Users\username\projects_folder\my-dagster-project\venv\Scripts\python.exe -m dagster api grpc --lazy-load-user-code --port 52892 --heartbeat --heartbeat-timeout 20 --fixed-server-id 0249ac84-9c1f-4eb8-bb0d-dd27507862f1 --log-level warning --inject-env-vars-from-instance --instance-ref 
{"__class__": "InstanceRef",
  "compute_logs_data": {
    "__class__": "ConfigurableClassData",
      "class_name": "LocalComputeLogManager",
        "config_yaml": "base_dir: C:\\Users\\user\\.data\\dagster\\storage\n",
          "module_name": "dagster.core.storage.local_compute_log_manager"}, 
          "custom_instance_class_data": null,
            "event_storage_data": {
              "__class__": "ConfigurableClassData",
              "class_name": "SqliteEventLogStorage",
              "config_yaml": "base_dir: C:\\Users\\user\\.data\\dagster\\history\\runs\\\n",
"module_name": "dagster.core.storage.event_log"
}, 
"local_artifact_storage_data": {
  "__class__": "ConfigurableClassData",
    "class_name": "LocalArtifactStorage",
      "config_yaml": "base_dir: C:\\Users\\user\\.data\\dagster\n",
        "module_name": "dagster.core.storage.root"
        }, 
        "run_coordinator_data": {
          "__class__": "ConfigurableClassData",
          "class_name": "DefaultRunCoordinator",
          "config_yaml": "{}\n",
          "module_name": "dagster.core.run_coordinator"
          },
          "run_launcher_data": {
            "__class__": "ConfigurableClassData",
            "class_name": "DefaultRunLauncher",
            "config_yaml": "{}\n",
            "module_name": "dagster"
            }, "run_storage_data": {
              "__class__": "ConfigurableClassData", 
              "class_name": "SqliteRunStorage", 
              "config_yaml": "base_dir: C:\\Users\\user\\.data\\dagster\\history\\\n",
              "module_name": "dagster.core.storage.runs"
              },
              "schedule_storage_data": {
                "__class__": "ConfigurableClassData",
                "class_name": "SqliteScheduleStorage",
                "config_yaml": "base_dir: C:\\Users\user\\.data\\dagster\\schedules\n",
                "module_name": "dagster.core.storage.schedules"
                },
                "scheduler_data": {
                  "__class__": "ConfigurableClassData",
                  "class_name": "DagsterDaemonScheduler",
                  "config_yaml": "{}\n",
                  "module_name": "dagster.core.scheduler"
                  },
                  "secrets_loader_data": null,
                  "settings": {},
                  "storage_data": {"__class__": "ConfigurableClassData", 
                  "class_name": "DagsterSqliteStorage",
                  "config_yaml": "base_dir: C:\\Users\\user\\.data\\dagster\n",
                  "module_name": "dagster.core.storage.sqlite_storage"}} 
--location-name my-dagster-project -m my-dagster-project -d C:\Users\user\projects_folder\my-dagster-project"

Stack Trace:
  File "C:\Users\user\projects_folder\my-dagster-project\venv\Lib\site-packages\dagster\_core\remote_representation\grpc_server_registry.py", line 184, in _get_grpc_endpoint
    server_process = GrpcServerProcess(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\projects_folder\my-dagster-project\venv\Lib\site-packages\dagster\_grpc\server.py", line 1471, in __init__
    server_process, self.port = _open_server_process_on_dynamic_port(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\projects_folder\my-dagster-project\venv\Lib\site-packages\dagster\_grpc\server.py", line 1417, in _open_server_process_on_dynamic_port
    server_process = open_server_process(port=port, socket=None, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\projects_folder\my-dagster-project\venv\Lib\site-packages\dagster\_grpc\server.py", line 1398, in open_server_process
    wait_for_grpc_server(server_process, client, subprocess_args, timeout=startup_timeout)
  File "C:\Users\user\projects_folder\my-dagster-project\venv\Lib\site-packages\dagster\_grpc\server.py", line 1318, in wait_for_grpc_server
    raise Exception(

  warnings.warn(f"Error loading repository location {location_name}:{error.to_string()}")

### How to reproduce?

This happened with empty dagster projects (`dagster project scaffold --name my-dagster-project`) as well as projects that my colleagues are working on and without having this error

`dagster api grpc -p 4000` works

### Dagster version

1.8.10

### Deployment type

Local

### Additional information

I added a DAGSTER_HOME environment, as well as the .data/dagster folder and an empty dagster.yaml file there.
The problem does not occur in containerized Dagster.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by garethbrickman** [comment]
If it's not occurring in containerized Dagster then there's probably some issue with your local environment. Did you try creating a fresh virtual environment and reinstalling Dagster and its dependencies in it?

**Comment by joanafloresc** [comment]
Hi @garethbrickman, yes, I did, the issue continues.

I had installed a programm to secure network and access to applications when Dagster started to show this error. At beginning, I thought it was not related, but now, one of my colleagues also installed it and started to have the same bug in Dagster, in projects that were running properly. Even uninstalling it doesn't work as I surely could not revert the settings to default. At the moment, we don't know how to work around this. Is there any workaround on Dagster?

**Comment by garethbrickman** [comment]
What was the program?

**Comment by joanafloresc** [comment]
Unfortunately, I cannot mention it. It is a commercial product to ensure safe network.

**Comment by garethbrickman** [comment]
Gotcha, I think you'll need to be in touch with that product's support to see what it could be doing to block or interrupt the Dagster processes. From those logs it looks like the Dagster code server is getting shut down within 20 seconds of starting.
