### ISSUE TITLE
Dagster PyIceberg IO manager

### ISSUE THREAD

**Issue by JasperHG90** [dagster-io/dagster#25338]
### What's the use case?

I'm developing a library so that users can use PyIceberg <https://github.com/apache/iceberg-python> as an IO manager with Dagster.

I'd like to submit it as a contribution to this repository. I saw that most (all?) of the dagster libraries are authored by your team. Is this a kind of contribution that you accept?

### Ideas of implementation

The library implementation follows the same implementation as `dagster-deltalake`.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Hey @JasperHG90 we're in the process of streamlining the way our community can submit their own Dagster integrations. While that's in flight, what you could do is host it in a standalone repo and then when the new process is up and running in the near future we can work with you to formally incorporate it.

**Comment by garethbrickman** [comment]
Hey @JasperHG90 thanks for your interest in contributing to Dagster! We're in the process of streamlining the way the Dagster community can submit their own Dagster integrations. While that's in flight, what you could do is host yours in a standalone repo like [these community-supported libraries](https://docs.dagster.io/integrations#community-supported-libraries). 

When the new process is up and running in the near future we can work with you to port it to that one 👍
