### ISSUE TITLE
Allow for protobuf 5.xx

### ISSUE THREAD

**Issue by 0x26res** [dagster-io/dagster#25398]
### What's the use case?

Following on https://github.com/dagster-io/dagster/issues/10627 I'd now like to be able to use the version 5.xx of the python protobuf library.

The switch from 4.xx to 5.xx in python corresponds to this release [v26.0](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0).

My experience is that the breaking changes are minor, unless using the option `always_print_primitive_fields` when printing json.

So in theory it's just a matter of changing the setup.py to allow of 5.xx.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by je-movers-market** [comment]
The latest dbt-core requires protobuf >=5.0 meaning this is actually causing a conflict, meaning current or newer releases of dbt-core are incompatible with Dagster as of right now.

So would surely be good to get this completed ASAP, as I assume the dbt integration is very popular.

**Comment by lydialimlh** [comment]
dbt-core 1.8.9 and above requires protobuf >=5.0 , please move the pin so that we can all greenkeep dbt-core.
