### ISSUE TITLE
Documentation for Click CLIs looks weird

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2541]
[Check on Firefox, maybe add some white background]

![image](https://user-images.githubusercontent.com/609349/83905143-05fff100-a716-11ea-8a35-642408ac6134.png)

**Comment by yuhan** [comment]
closing this as:
- we've removed the dagster-aws cli in https://dagster.phacility.com/D3619
- the Dagster CLI page looks good now https://docs.dagster.io/_apidocs/cli
