### ISSUE TITLE
Create separate "Library" section in API docs sidebar

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2542]
Something like this?

![image](https://user-images.githubusercontent.com/609349/83905304-495a5f80-a716-11ea-9096-b0f31fb53ff8.png)

**Comment by tinkerware** [comment]
It would be good to see `dagster-pandas` there; is the omission by choice?

**Comment by natekupp** [comment]
Page exists now https://docs.dagster.io/docs/apidocs/libraries/dagster_pandas actual docs coming soon :)
