### ISSUE TITLE
maybe support alternative config type definition using dataclasses/typed namedtuples (python 3 only)

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2545]
this is an interesting idea to reduce the impedance mismatch between the config type system and the host language and allow for smoother onboarding of less experienced users

**Comment by mgasner** [comment]
https://realpython.com/python-data-classes/

**Comment by FishmanL** [comment]
why not attrs instead?
https://www.attrs.org/en/latest/examples.html

**Comment by valentin-iris** [comment]
Hey! Is there any update on this? I would find this a fantastic new feature!

**Comment by ilkersigirci** [comment]
The recent trend in python for configuration management is using builtin [dataclass](https://docs.python.org/3/library/dataclasses.html). We can see this in projects such as [pydantic](https://docs.pydantic.dev/usage/dataclasses/), [omegaconf](https://omegaconf.readthedocs.io/en/2.1_branch/structured_config.html) etc. With type hints, dataclasses become really powerful and I think dagster should support them as config type definitions.

**Comment by ilkersigirci** [comment]
Any update on this?

**Comment by yuhan** [comment]
this is done with https://dagster.io/blog/pythonic-config-and-resources
