### ISSUE TITLE
When switching repository it should not try to navigate to a pipeline of the same name.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2554]
e.g.:
1)
![Screenshot 2020-06-08 14 53 20](https://user-images.githubusercontent.com/28738937/84084198-da8c3900-a997-11ea-9a40-4c22b2e209d1.png)
2)
![Screenshot 2020-06-08 14 53 30](https://user-images.githubusercontent.com/28738937/84084208-e1b34700-a997-11ea-83e1-bd488e69794f.png)

3)
![Screenshot 2020-06-08 14 53 38](https://user-images.githubusercontent.com/28738937/84084230-e841be80-a997-11ea-8349-ee1fdba59323.png)

**Comment by bengotow** [comment]
Should be addressed in the near term by https://dagster.phacility.com/D3369 and in the longer term by moving repo state to the URL
