### ISSUE TITLE
dagster/row_count metadata not visible in asset events view

### ISSUE THREAD

**Issue by dschafer** [dagster-io/dagster#25566]
### What's the issue?

In the `/assets/example?view=events` view of an asset, `dagster/row_count` is filtered out of the metadata, but it does not appear in another place in the UI.

### What did you expect to happen?

Either the row_count metadata shouldn’t be filtered in this view (easiest), or there should be a dedicated UI treatment for it in this view.

### How to reproduce?

With this test file, run with `dagster dev -f thisfile.py`

```py
from dagster import (
    Output,
    asset,
)


@asset()
def example():
    return Output(0, metadata={"dagster/row_count": 10, "someotherdata": 5})
```

Materialize the asset twice, then go to http://127.0.0.1:3000/assets/example. You can see the row count right underneath status (it's "promoted" to a dedicated UI treatment), and the someotherdata in the metadata section.

<img width="1054" alt="Screenshot 2024-10-26 at 15 49 21" src="https://github.com/user-attachments/assets/5c875a87-da46-4dd7-937b-2877d74bca84">

But if you go to http://127.0.0.1:3000/assets/example?view=events , you can still see `someotherdata` in metadata, but `dagster/row_count` neither appears in metadata nor in a dedicated treatment.

<img width="1512" alt="Screenshot 2024-10-26 at 15 48 58" src="https://github.com/user-attachments/assets/86517695-39aa-4ffe-97f0-25ab5bf6033d">

So if you're using this view to look back in time to see how row count has changed over materializations, there's no way to do so.

### Dagster version

dagster, version 1.8.9

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by dschafer** [comment]
Given that this is UI, guessing this is CC @hellendag

**Comment by dschafer** [comment]
Seems to be https://github.com/dagster-io/dagster/blob/dea8214e3787be1f720d00f741eeffdfdff7f181/js_modules/dagster-ui/packages/ui-core/src/assets/AssetEventMetadataEntriesTable.tsx#L337

**Comment by dschafer** [comment]
Might be related to #22324 – CC @rexledesma

**Comment by hellendag** [comment]
@bengotow is on it!

**Comment by garethbrickman** [comment]
Fixed by https://github.com/dagster-io/dagster/pull/25955 and https://github.com/dagster-io/dagster/pull/25956
