### ISSUE TITLE
Pin croniter<4.0.0

### ISSUE THREAD

**Issue by dinis-rodrigues** [dagster-io/dagster#25570]
### What's the issue?

A new release `4.0.0` of `croniter` introduces breaking changes in current dagster schedule definitions.

Version should be pinned to: `3.0.4`

### What did you expect to happen?

```python
@schedule(
    cron_schedule="0 10 * * 7", 
)
def some_schedule(context: ScheduleEvaluationContext):
``` 

The current cron string should work. Instead, we are getting the error:

```
dagster._core.errors.DagsterInvalidDefinitionError: Found invalid cron schedule '0 10 * * 7' for schedule 'some_schedule''. Dagster recognizes standard cron expressions consisting of 5 fields.
```

### Dagster version

dagster, version 1.8.13

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by gibsondan** [comment]
Hi @dinis-rodrigues - well look into a pin or a workaround, but in the meantime based on their release notes I think changing the “7” in the day of the week part of the cronstring to a “0” should resolve it as well, does that match what you’re seeing?

**Comment by dinis-rodrigues** [comment]
> Hi @dinis-rodrigues - we’ll look into a pin or a workaround, but in the meantime based on their release notes I think changing the “7” in the day of the week part of the cronstring to a “0” should resolve it as well, does that match what you’re seeing?

Yes changing the 7 to 0 seems to resolve the issue. Following the cron standards, indeed 7 should not be allowed.

**Comment by gibsondan** [comment]
Landed the pin to go out in our next release, thanks!

**Comment by lydialimlh** [comment]
Croniter updated to v5.0.1 and reinstated 7 as a DayOfWeek, all good now, maybe no need for this pin anymore.

See: https://github.com/kiorky/croniter/blob/5.0.1/CHANGELOG.rst

**Comment by joshuataylor** [comment]
Would be great to unpin, as Meltano requires:

```
The conflict is caused by:
    dagster 1.9.5 depends on croniter<4 and >=0.3.34
    meltano 3.6.0 depends on croniter<6.0.0 and >=5.0.1
```

**Comment by joshuataylor** [comment]
Made a PR here: https://github.com/dagster-io/dagster/pull/26515
