### ISSUE TITLE
Dagit - nicer rendering for unnamed environment

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2558]
From tutorial, run `dagit -f hello_cereal.py -a hello_cereal_pipeline` - shown as "<<unnamed>>"

<img width="276" alt="image" src="https://user-images.githubusercontent.com/609349/84223810-b744b500-aa8f-11ea-9a4b-8185712f57d4.png">

**Comment by natekupp** [comment]
<<unnamed>> seems to suggest I should be able to double-click the text and rename the environment

**Comment by schrockn** [comment]
Yeah we should change this today. Propose a naming convention ?

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by natekupp** [comment]
We could just not show an environment name there, and then gray out the environment selector and show a tooltip or text explaining the current state

**Comment by schrockn** [comment]
Could do. But I think in the short term we should just generate a credible name and see if we need to do anything more fancy later.
