### ISSUE TITLE
Migrate dagster-graphql off of legacy repository.yaml loading and figure out it's future.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2559]
Right now dagster-graphql users the legacy repository.yaml loading. We use it in a couple contexts:

1) "Host process" execution. E.g. dagster-airflow and the k8s run launcher. The likely end state of executePlan and executeRunInProcess invocation will the grpc api, in which case we can cut the dependency on graphql totally.

From brief code inspection it looks like the container must be configured such that a repository.yaml is available. We can't support multi-repo/location in k8s until that is resolved, so we may want to do it all in one shot.

2) Tooling: We use dagster-graphql to download mocks for our dagit test infrastructure. It may be worth keeping around for this purpose.

**Comment by schrockn** [comment]
This is aggressive to do for 0.8.0, but this will need to be resolved quickly.

**Comment by catherinewu** [comment]
https://dagster.phacility.com/D3422
