### ISSUE TITLE
File extension for SerializationStrategy

### ISSUE THREAD

**Issue by joostmeulenbeld** [dagster-io/dagster#2561]
When using the intermediate store, the generated files don't get an extension. When dealing with multiple binary serialization formats it quickly becomes unclear what type of file is stored when browsing through the generated filestore.

I reckon the most logical place for specifying the extension would be the SerializationStrategy constructor (i.e. an `extension='.hdf'` argument in the `__init__`)

**Comment by joostmeulenbeld** [comment]
For people stumbling upon this problem, we opted for an in-between class using the following. This overrides the `serialize_to_file` and `deserialize_from_file` from `SerializationStrategy`. This works for now but hopefully the internals of `SerializationStrategy` don't change too much :). I still think this could be worthwhile in the dagster library.
```python
class ExtensionSerializationStrategy(SerializationStrategy):
    def __init__(self, *args, extension: str = "", **kwargs):
        super().__init__(*args, **kwargs)
        if "." not in extension:
            extension = f".{extension}"
        self.extension = extension

    def serialize_to_file(self, value: Any, write_path: Union[Path, str]) -> Any:
        write_path = Path(write_path).with_suffix(self.extension)
        return super().serialize_to_file(value, str(write_path))

    def deserialize_from_file(self, read_path: Union[Path, str]) -> Any:
        read_path = Path(read_path).with_suffix(self.extension)
        return super().deserialize_from_file(str(read_path))
```

**Comment by sryza** [comment]
We're targeting a feature for our December release that will make it easier to directly control how outputs

Hey @joostmeulenbeld. For our next major release, we're revamping our intermediates system in a way that will allow users to directly control how outputs are stored.  I'm glad you were able to get something working - soon you should be able to control this without depending on the internals of SerializationStrategy.

**Comment by catherinewu** [comment]
@sryza is this good to close now that IOMangers have shipped?

**Comment by alangenfeld** [comment]
closing since IOManagers handle this
