### ISSUE TITLE
Catch Dagit port conflict

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2567]
Dagit warns if we are trying to serve on http://127.0.0.1:3000 and another process is already using that port.

However, we don't check if another process is serving on http://localhost:3000 (our docs were previously doing this with `yarn dev`, I'm fixing). 

We should catch this case and ask the user to choose a different port

**Comment by hellendag** [comment]
The CRA warns when something else is already running on the port, e.g. `Something is already running on port 3000.`. I think this is probably fine to close.
