### ISSUE TITLE
Incorrect warning on missing config section

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2568]
From tutorial, /docs/tutorial/basics_solids

We show both `read_csv` and `sort_by_calories` as requiring additional config, but this is incorrect—only `read_csv` requires config.

![image](https://user-images.githubusercontent.com/609349/84315660-d8081b80-ab1e-11ea-80b5-150a2f7c92cc.png)

Adding just `solids:` results in:

![image](https://user-images.githubusercontent.com/609349/84315874-1b628a00-ab1f-11ea-880f-fb3000be83ab.png)

Only after we have the config

```
solids:
  read_csv:
```

does the warning appear correctly on just `read_csv`:

![image](https://user-images.githubusercontent.com/609349/84316003-43ea8400-ab1f-11ea-8ed9-cd4f8e968a7c.png)

**Comment by bengotow** [comment]
https://dagster.phacility.com/D5630
