### ISSUE TITLE
Dagster University UI GraphQL Error

### ISSUE THREAD

**Issue by cobrienbeam** [dagster-io/dagster#25716]
### What's the issue?

Error
You hit an unexpected error while fetching data from Dagster.

If you have a minute, consider reporting this error either by filing a Github issue or by messaging in the Dagster slack. Use the "Copy" button below to include error information that is helpful for the core development team to diagnose what is happening and to improve Dagster in recovering from unexpected errors.
Operation name: {PipelineRunLogsSubscription}

Message: FSEventsObserver.schedule() takes 3 positional arguments but 4 were given

Path: 

Locations: 

### What did you expect to happen?

Not have the error occur in the UI

### How to reproduce?

Materialize an asset

### Dagster version

dagster~=1.7

### Deployment type

Local

### Deployment details

Running Dagster dev locally following Dagster university instructions

### Additional information

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/68ddbc12-cd9f-4d70-8197-6f6ca04ee1b7">

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by cobrienbeam** [comment]
Also receiving this error while trying to view the "stdout" logs for a run

<img width="1381" alt="image" src="https://github.com/user-attachments/assets/f5af94d5-b702-4126-b9d1-d7b508cd8102">

**Comment by garethbrickman** [comment]
Duplicates https://github.com/dagster-io/dagster/issues/23957

This a known issue with the ​​watchdog​​ dependency due to a breaking change the library introduced. It is fixed in dagster versions =>1.8.4.

Adding a ​​watchdog<5​​ pin would also fix it in earlier versions.
