### ISSUE TITLE
Docs unclear on setting up SlimCI for dbt from scratch

### ISSUE THREAD

**Issue by lydialimlh** [dagster-io/dagster#25724]
### What's the issue or suggestion?

Docs only say to use this line in our CI/CD files:

`dagster-cloud ci dagster-dbt project manage-state --file path/to/project.py
`

but did not mention that `--statedir` is a required field, or what the value should be. Upon filling in what I think the statedir should be, I run the command and get error message:

> Error: Unable to determine deployment state.

And from here on, it's difficult to understand what else I'm missing or how to debug and move forward.

### Additional information

I am running a hybrid deployment.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Could you share the link to the docs that's in?

**Comment by lydialimlh** [comment]
Hi @garethbrickman , here it is: https://docs.dagster.io/integrations/dbt/reference#leveraging-dbt-defer-with-branch-deployments

**Comment by maximearmstrong** [comment]
Hi @lydialimlh - It looks like the `DAGSTER_BUILD_STATEDIR` env var is not set in your CD/CD workflow.

The `dagster-cloud ci dagster-dbt project manage-state` uses the env var to set the `--state-dir` value. The env var is required - I recommend [this guide](https://docs.dagster.io/dagster-plus/getting-started#other-cicd-provider) about how to configure the CI/CD files.

That said, it looks like you are using the GitHub integration with a hybrid deployment. Are you deploying using GitHub?

If so, I would recommend using the [ci-init action](https://github.com/dagster-io/dagster-cloud-action/blob/v0.1.49/actions/utils/ci-init/action.yml) that initializes the CI state in the CI/CD workflow, and sets the `DAGSTER_BUILD_STATEDIR` env var for you. You can see [the action in a CI/CD file](https://github.com/dagster-io/hooli-data-eng-pipelines/blob/8c5909e17e89af22f51bf6d5bfccd8e1c4eb310a/.github/workflows/deploy-dagster-cloud.yml#L119-L126) in our hooli-data-eng-pipelines repo, which is a example of a Dagster project using hybrid deployment.

About the documentation for the `dagster-cloud ci dagster-dbt project manage-state` command, I'll update it to specify that the `DAGSTER_BUILD_STATEDIR` env var is required.

**Comment by lydialimlh** [comment]
Thanks @maximearmstrong, appreciate you taking the time for this! I promise I will give it another go when I have the time - while waiting, I had gone ahead with the solution from: https://medium.com/@raulsh/dagster-a-complete-replacement-for-dbt-cloud-automations-78a0613d632f
