### ISSUE TITLE
pipeline/solid typeahead should select on enter once it narrow down to 1 result

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2572]
Once we are down to 1 pipeline in the search I don't want to have to touch the mouse to bring this up

![Screenshot 2020-06-10 15 16 31](https://user-images.githubusercontent.com/28738937/84324327-61264f00-ab2d-11ea-920b-a738ff11cba3.png)

**Comment by bengotow** [comment]
Will be resolved by https://dagster.phacility.com/D3705!
