### ISSUE TITLE
dagster-gcp: Allow project specification as resource input

### ISSUE THREAD

**Issue by tmc** [dagster-io/dagster#2577]
If there isn't an explicit project in the service account key then initialization may fail. Accepting a project String/StringSource would likely be appropriate.

**Comment by natekupp** [comment]
Is this in the BigQuery resource? if so, this should be landing in 0.8.0 today - cc @jbrambleDC

**Comment by natekupp** [comment]
we need to enable configuring the storage account in constructing `storage.client.Client()` from GCSResource
