### ISSUE TITLE
latency between `step_worker_started` and `resource_init_started`

### ISSUE THREAD

**Issue by Tazoeur** [dagster-io/dagster#25780]
### What's the issue?

Hello,

I find that the time between the `step_worker_started` and the `resource_init_started` events is quite long, and I'd like to identify the problem.

![image](https://github.com/user-attachments/assets/cc7442f0-604e-41b1-8124-923b3ce2c5cc)

As you can see, I have a 20s delay between the moment I click the materialization button and the moment the io manager code is actually called.

To be honest, I did not care until now because when the automated workflows run in production, 20 seconds per job does not matter at all. 
But when I debug stuff and develop new assets, I find it bothersome to wait 20-30 more seconds between each iteration.

* Is it an issue that many users have?
* Is it on my side or on dagster side?
* How can I reduce this delay?

EDIT: I have the same behaviour if I launch the asset via the command line `dagster asset materialize -m my_module --select my_asset --partition my_partition`
 

### Dagster version

dagster, version 1.9.0

### Deployment type

Local

### Deployment details

I am using `dagster dev`.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by HynekBlaha** [comment]
Hello @Tazoeur,
How long does it to start up when running command `dagster dev`?
I can see that you are using multiprocess executor, which spawns new process for each step.
The new process goes trough importing all packages before executing your op/asset.

I recommend to try different executor: [in_process_executor](https://docs.dagster.io/deployment/executors#example-executors)
If it helps, you probably spend a long time on imports.
This is how you can profile it:
```
pip install tuna
PYTHONPROFILEIMPORTTIME=1 dagster dev 2> src/import.log
tuna src/import.log
```

**Comment by Tazoeur** [comment]
Hello @HynekBlaha,

> How long does it to start up when running command `dagster dev`?
~1 minute

Oh my, you're right, the imports take ~ 50s
![image](https://github.com/user-attachments/assets/4f4a1fb6-3c53-40f8-b815-19c27862265e)

I can see our packages take roughly 80% of the import time. I guess we'll have to refactor our configuration management design, which seems to have a huge impact.

So it's a me-problem, sorry for bothering the dagster team about this, and thank you again :)

**Comment by david-takacs** [comment]
Hi @Tazoeur, maybe you've already figured this out but one solution for this issue is to use `forkserver` with `preload_module`. The `forkserver` will be created in the first process spawned and then subsequent processes will be forked from the forkserver itself with the modules already loaded.
