### ISSUE TITLE
Add support for kinds tags to AssetOut for use by @multi_asset

### ISSUE THREAD

**Issue by garethbrickman** [dagster-io/dagster#25796]
### Discussed in https://github.com/dagster-io/dagster/discussions/25783

[AssetOut ](https://docs.dagster.io/_modules/dagster/_core/definitions/asset_out#AssetOut) currently has support for `tags` but not `kinds`

**Comment by benpankow** [comment]
This is now supported in  `1.9.2` as you're now able to [construct an `AssetOut` from a spec](https://docs.dagster.io/_apidocs/assets#dagster.AssetOut.from_spec) which gives you more control over properties like `kinds`:

```python
spec = AssetSpec(key="my_asset", kinds={"python"})

@graph_multi_asset(outs={"my_asset": AssetOut.from_spec(spec)})
def my_graph_multi_asset():
    ...
```
