### ISSUE TITLE
[UI] Incorrect version release descent

### ISSUE THREAD

**Issue by kennycontreras** [dagster-io/dagster#25801]
### What's the issue or suggestion?

I noticed the descent order in the docs for the released versions is incorrect. 
I wonder if this is how it's expected to look. If that's the case, then there's no bug at all.

![Screenshot 2024-11-08 at 08 27 25](https://github.com/user-attachments/assets/7f76bd2f-75a7-446c-8cdb-b304d4ab68b2)

### Additional information

Go to the docs and then click on the released drop down button
https://docs.dagster.io/getting-started

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Thanks for reporting this, Kenny. It's a known technical issue with our current docs system. We'll soon be moving to a new system, check out the preview here: https://docs-preview.dagster.io/
