### ISSUE TITLE
Reduce gratuitous snapshot fetching and snapshot id creation

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2587]
Profiling has revealed that we do a lot of unnecessary fetching of snapshots in dagit and unnecessary snapshot id generation. Given that snapshot's are immutable, snapshot id generation is deterministic, and that we have a long-running web process, we should be able to reduce this a lot with some caching at the right layers.

**Comment by natekupp** [comment]
@alangenfeld did some profiler-driven optimization and fixed the observed instances of this issue
