### ISSUE TITLE
[Webserver] Scrollbars always use light theme

### ISSUE THREAD

**Issue by rd-danny-fleer** [dagster-io/dagster#25897]
### What's the issue?

When choosing dark theme, scrollbars still use light theme (see the red boxes on the screenshot):

![image](https://github.com/user-attachments/assets/01811d55-2752-4b1d-be26-ba166255f52a)

I tested this with the following setup:
dagster 1.8.13
Chrome Version 130.0.6723.117 (Official Build) (arm64)
macOS 15.1

Quick guess: The CSS property [color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) is not correctly applied to the scrollbars.

### What did you expect to happen?

Scrollbars should respect the theme settings, i.e. being dark when theme is set to dark.

### How to reproduce?

- Set theme to use "dark"
- Open a run and verify the scrollbars use light theme

### Dagster version

dagster, version 1.8.13

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by hellendag** [comment]
I merged a fix earlier this week, and it will be in the next release. (https://github.com/dagster-io/dagster/pull/26033) Thanks for the report!
