### ISSUE TITLE
Update messaging in all the places prior to 0.8.blog

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2589]
- pypi module description
- elementl.com
- github page

**Comment by mgasner** [comment]
we should also make sure each project has a description on pypi

**Comment by mgasner** [comment]
<img width="1477" alt="Screen Shot 2020-06-11 at 4 09 29 PM" src="https://user-images.githubusercontent.com/427016/84447831-fb55c800-abfd-11ea-88a3-030833d5ffe5.png">

**Comment by natekupp** [comment]
I'm going to close this, please open a new task if anything still remains open here
