### ISSUE TITLE
`config` should be `config_schema` instead in `dagster_celery/executor.py`

### ISSUE THREAD

**Issue by alirazeen** [dagster-io/dagster#2592]
I am trying out v0.8 now and I happened to notice this line that looks like it's using a soon-to-be deprecated option in the `@executor` decorator: https://github.com/dagster-io/dagster/blob/9e10c83efe161478c836f3c0a883e99bf3e83ab4/python_modules/libraries/dagster-celery/dagster_celery/executor.py#L35 I thought I'd quickly point it out.

(P.S.: Dagster is great!)

**Comment by schrockn** [comment]
Great thanks for the report

**Comment by sryza** [comment]
https://dagster.phacility.com/D3476
