### ISSUE TITLE
dagster-celery has an undeclared dependency on dagster-k8s

### ISSUE THREAD

**Issue by alirazeen** [dagster-io/dagster#2593]
In v0.8, it looks like `dagster-celery` requires `dagster-k8s` because `engine.py` in `dagster-celery` has the import:

```
from dagster_k8s.job import get_k8s_resource_requirements
```

Unfortunately, this means using the celery executor at the moment results in a runtime error unless `dagster-k8s` is also installed. I'm working around this by installing `dagster-k8s` manually.

**Comment by natekupp** [comment]
Hi @alirazeen thanks for catching this! Fixed in https://dagster.phacility.com/D3479 which should go out in a release soon.
