### ISSUE TITLE
Tutorials and examples shouldn't use module loading from `dagster_examples`

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2595]
In our tutorial, we have snippets like:

```
load_from:
  - python_module: dagster_examples.intro_tutorial.repos
```

These tutorials should be written from the perspective of a user on their own filesystem without our repo checked out. For simplicity, we should probably use file-based loading. 

If we want to show module based loading, we should walk the user through the whole process of creating and installing a module. Otherwise, it's quite confusing.

**Comment by alangenfeld** [comment]
remaining references to this stuff are in `legacy_examples` so closing
