### ISSUE TITLE
UnboundLocalError in _launch_scheduled_execution() hides real error

### ISSUE THREAD

**Issue by alirazeen** [dagster-io/dagster#2599]
I ran into the following error when I was trying out a scheduled pipeline in v0.8 (and I think the error exists in v0.8.1 as well)

```
UnboundLocalError: local variable 'execution_plan_snapshot' referenced before assignment
  File "venv/lib/python3.6/site-packages/dagster/cli/api.py", line 464, in _schedule_tick_state
    yield holder
  File "venv/lib/python3.6/site-packages/dagster/cli/api.py", line 519, in launch_scheduled_execution
    _launch_scheduled_execution(instance, schedule_def, pipeline, tick, stream)
  File "venv/lib/python3.6/site-packages/dagster/cli/api.py", line 597, in _launch_scheduled_execution
    execution_plan_snapshot=execution_plan_snapshot,
```

In my case, the real error was that `create_execution_plan` in the following snippet failed before `snapshot_from_execution_plan` could run:

https://github.com/dagster-io/dagster/blob/d71543542ffd054859fa6b16920fb46df83ceaf6/python_modules/dagster/dagster/cli/api.py#L572-L582

I was able to figure out quickly why `create_execution_plan` was failing for me without getting the true error message (I neglected to export an environment variable in my `ScheduledDefinition`). But I might not be as lucky next time :)

It would be nice if errors from a failed `create_execution_plan` are shown instead of being obscured by an `UnboundLocalError`.

**Comment by schrockn** [comment]
Thank you for finding this bug and helping us pinpoint the error. We should be able to get this resolved quickly.
