### ISSUE TITLE
Runs by AutomationConditionSensor - Filtering

### ISSUE THREAD

**Issue by ArtiNgqobe** [dagster-io/dagster#26001]
### What's the use case?

I am loving the AutomationConditioning functionality with the AutomationConditionSensor - it means less schedules because i set my cron times for assets to run by themselves even without jobs but the issue i have is that once these assets run i cannot easily filter by a speicific asset ran by automationConditionSensor from the RUNS page, 

1. I use Tags currently to differentiate but this isn't specific enough as other assets would have this tags as well
2. Launch by as well isn't specific enough
3. I can't filter by job because by these assets do not have jobs by nature

### Ideas of implementation

The only thing i can think of is the filter by Target - the target should be unique to an asset, 

![image](https://github.com/user-attachments/assets/7eb4fe33-c0f9-446c-af1e-9f86d6aaa7c6)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Closing as duplicate: https://github.com/dagster-io/dagster/issues/17245
