### ISSUE TITLE
K8s job timeouts should be configurable on a per-solid basis

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2603]

**Comment by catherinewu** [comment]
@helloworld would your "support arbitrary k8s config" diff resolve this?

**Comment by helloworld** [comment]
I don't see any timeout setting here: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Job.md or here: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1JobSpec.md

@natekupp do you remember what you were referring to?
