### ISSUE TITLE
BaseObserver.schedule() takes 3 positional arguments but 4 were given [University Project Downgrades Dagster]

### ISSUE THREAD

**Issue by bgruey** [dagster-io/dagster#26081]
### What's the issue?

It seems the dagster university project uses an older version. Via pip I installed Dagster v1.9.2, but once I ran the following commands, I had Dagster v1.7.16:
```
cd dagster_university
cp .env.example .env
pip install -e ".[dev]"
```

When viewing the asset materialization run, I get the following popup error.

```
Operation name: {PipelineRunLogsSubscription}

Message: BaseObserver.schedule() takes 3 positional arguments but 4 were given

Path: 

Locations: 
```

### What did you expect to happen?

I expected no popup error.

### How to reproduce?

1. Follow the Dagster University course using version `dagster~=1.9` in a requirements.txt file.
2. Click on the "Materialize" button on step 3 of the `Asset materialization` topic of Lesson 3.
3. Click "view" on the purple popup box.
4. See error message.

### Dagster version

dagster, version 1.7.16

### Deployment type

None

### Deployment details

Local deployment to get acquainted with Dagster on a new Linux Mint installation from a couple days ago, on a Dell Inspiron 16+.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by garethbrickman** [comment]
Thanks for reporting this, it was due to the `setup.py` using `dagster==1.7.*` so when you ran `pip install -e ".[dev]"` it downgraded the version of Dagster in your environment to an older one affected by the bug that caused the error. 

We have fixed that so it uses `dagster==1.9.*` in this PR: https://github.com/dagster-io/dagster/commit/d9a79b8c0dda241cd89cd8a5c6e936ace1a133f9
