### ISSUE TITLE
replace executeRunInProcess with direct dagster api invocation

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2608]

**Comment by natekupp** [comment]
are there any of these left @johannkm ?

**Comment by johannkm** [comment]
Yep, I think only the k8s and celery-k8s run launchers used them

**Comment by alangenfeld** [comment]
this issue is still referenced from the code-base, reopening to track removal

**Comment by johannkm** [comment]
Closed thanks to @gibsondan
