### ISSUE TITLE
[Documentation Feedback] Redundance in the documentation

### ISSUE THREAD

**Issue by CelianInfo** [dagster-io/dagster#26084]
The 3 sections :

Selecting an asset's entire lineage
Selecting upstream dependencies
Selecting downstream dependencies

The only thing that change is the '*' used before and after the asset name. I don't think we need to create 3 section with examples. Only 1 section with 3 lines of selection would be better I think.

**Comment by garethbrickman** [comment]
Thanks for your feedback! In the near future we'll be migrating to a new version of our documentation site which will also have revamped and upgraded content, so we won't be doing major amendments to the structure of the existing docs. You can preview the new docs at: https://docs-preview.dagster.io/
