### ISSUE TITLE
Unexpected GraphQL error: "Operation name: {RunRootQuery}  Message: 'NoneType' object has no attribute 'lineage_snapshot'"

### ISSUE THREAD

**Issue by lokinnnnnn** [dagster-io/dagster#26095]
### What's the issue?

Dagster reported an Unexpected GraphQL error,I want to know if this issue is a bug or a problem with my dagster settings?

error info:
Operation name: {RunRootQuery}

Message: 'NoneType' object has no attribute 'lineage_snapshot'

Path: ["pipelineRunOrError","parentPipelineSnapshotId"]

Locations: [{"line":14,"column":3}]

Stack Trace:
  File "/usr/local/lib/python3.10/site-packages/graphql/execution/execute.py", line 523, in execute_field
    result = resolve_fn(source, info, **args)
  File "/usr/local/lib/python3.10/site-packages/dagster_graphql/schema/pipelines/pipeline.py", line 476, in resolve_parentPipelineSnapshotId
    if snapshot.lineage_snapshot is not None:

![Snipaste_2024-11-22_10-23-25](https://github.com/user-attachments/assets/c21e7507-c92f-43b4-8c56-349926ab2c32)

### Dagster version

1.8.7

### Deployment type

Docker Compose

### Deployment details

Package an image using Docker, upload it to AWS ECR, deploy grpc, daemon, and web server on AWS ECS, and use Fargate's startup type

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by garethbrickman** [comment]
Is this reproducible when running `dagster dev` locally? My first though is in your `setup.py` or `requirements.txt` is you should ensure you pin `dagster` and `dagster-webserver` to use the same versions. 

(If you don't explicitly pin all dagster dependencies to the same version, then there will be version mismatches that can cause incompatibilities).

**Comment by lokinnnnnn** [comment]
No, it is deployed and running on AWS, and the problem still exists. Additionally, there is a problem with my automatic scheduling, and it cannot start the scheduling task.

requirements.txt
dagster==1.8.7
dagster-aws
dagster_dbt==0.24.7
dagster_docker
dagster-webserver==1.8.7
dagster-postgres
dagster-mysql
dbt-core==1.7.18
dbt-mysql==1.7.0

pandas==2.2.3
pymysql==1.1.1
sqlalchemy==2.0.36

**Comment by garethbrickman** [comment]
Could you try explicitly pinning all the `dagster-{library}` dependencies to be the same version?

**Comment by garethbrickman** [comment]
Closing in lieu of https://github.com/dagster-io/dagster/issues/26124
