### ISSUE TITLE
error on $DAGSTER_HOME set to "."

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2609]
this doesn't fail in any intuitive way - a lot of things sort of work assuming you run most commands from one directory

**Comment by AndersonReyes** [comment]
@alangenfeld Thinking give this issue a trey as a new contributor but have some clarifying questions.

1. Can I get more context as to why it needs to error, which would explain your line `a lot of things sort of work assuming you run most commands from one directory` better
2. is this the right place to error out? https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/instance/__init__.py#L50

**Comment by alangenfeld** [comment]
> why it needs to error

We make assumptions in the system that we can evaluate `$DAGSTER_HOME` and resolve to a consistent location regardless of the current working directory. We want to have an absolute path after we expand user directory sigils like `~`.

The place that things will fail is when we are handing over control to a separate process that has a different working directory. One example of this is when our `cron` based scheduler attempts to do an execution. 

> is this the right place to error out?

Yep I believe so, we want to check `os.path.isabs` *after* we call `expanduser`.
