### ISSUE TITLE
Ensure we move Helm chart version forward in lockstep with release

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2610]
Right now we report that we support an ancient Dagster version, 0.6.9:

https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-k8s/helm/dagster/Chart.yaml#L7

**Comment by johann-dag** [comment]
closed by https://github.com/dagster-io/dagster/commit/7df9aaa6dce19ed15532810729c8b57d2dd1ff3c
