### ISSUE TITLE
emr_pyspark_step_launcher fails with packaged airflow dags

### ISSUE THREAD

**Issue by Benyuel** [dagster-io/dagster#2612]
When the [EmrPysparkStepLauncher](https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-aws/dagster_aws/emr/pyspark_step_launcher.py#L92)(`deploy_local_pipeline_package=True`) is used in conjunction with dagster-airflow where the dag is a [packaged dag](https://airflow.apache.org/docs/1.10.2/concepts.html?highlight=zip#packaged-dags) (i.e. in a zip file), `emr_pyspark_step_launcher` `post_artifacts` will zip up the already zipped dag.  

https://github.com/dagster-io/dagster/blob/439022652453b770e8f7ce92b6ab2d1c6766278b/python_modules/libraries/dagster-aws/dagster_aws/emr/pyspark_step_launcher.py#L179-L183

This results in an EMR artifact `code.zip` containing `{packaged_dag}.zip` which cannot be imported in pyspark EMR-land.  

The `step_run_ref` that gets pickled and executed from EMR also references an import of `{packaged_dag}.zip`.  

https://github.com/dagster-io/dagster/blob/439022652453b770e8f7ce92b6ab2d1c6766278b/python_modules/libraries/dagster-aws/dagster_aws/emr/pyspark_step_launcher.py#L188

The only resolution I see at the moment is to unzip the packaged dag prior to `post_artifacts`.

**Comment by sryza** [comment]
I suspect the right approach here is to avoid zipping if what's at `local_pipeline_package_path` is already a zip

**Comment by dpeng817** [comment]
When this occurs, how are you specifying {packaged_dag}.zip? Are you just passing the directory that contains it as local_pipeline_package_path, or are you additionally specifying the name of this file somehow?

**Comment by Benyuel** [comment]
My workaround for this was to monkey patch the `EmrPysparkStepLauncher` so that if the `local_pipeline_package_path` is a zipfile, it unzips it first to a temp directory, then the regular step launcher is fine to zip back up and the rest of the logic.  

> When this occurs, how are you specifying {packaged_dag}.zip?  Are you just passing the directory that contains it as local_pipeline_package_path, or are you additionally specifying the name of this file somehow?

In terms of Airflow, Airflow automatically detects the packaged dags if they are in a well known directory.  
In terms of the `EmrPysparkStepLauncher`, the `local_pipeline_package_path` ends up becoming `/local/path/to/{packaged_dag}.zip/my/dagster/dag/dir` and is generated programmatically based on the `__file__` and where the `{packaged_dag}.zip` is deployed.

**Comment by catherinewu** [comment]
bump @dpeng817?

**Comment by dpeng817** [comment]
Hey! Thanks @Benyuel for bringing this to our attention. We don't have the bandwidth to investigate a fix right now, but as we head into 0.12.0 planning in a month or so, will be happy to touch base and revisit if you are still running into this.
