### ISSUE TITLE
Avoid executing __init__.py of code location every ~60 seconds

### ISSUE THREAD

**Issue by Zeulni** [dagster-io/dagster#26159]
### What's the issue?

If we start our code via “dagster dev”, then the init.py is executed by Dagster every ~60 seconds. 
**The problem**: Since we use DBT assets and thus perform a “dbt parse” when running the init.py (at least locally, not on K8s), “dbt parse” is executed every ~60 seconds even though the code location has not been actively reloaded. Since our DBT project is quite large, this leads to performance issues.

### What did you expect to happen?

There should be a configuration to execute the init.py only once - when the code is started and not automatically every ~60 seconds thereafter. Alternatively, we would need access to an env variable, for example, which indicates whether a reload is currently taking place (e.g. when the “Reload” button is pressed). 

### How to reproduce?

Just starting a local dagster project with an init.py via "dagster dev" and having a print statement in there. The print statement will be executed every ~60 seconds.

### Dagster version

1.9.2

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by garethbrickman** [comment]
Duplicates https://github.com/dagster-io/dagster/issues/26010
