### ISSUE TITLE
dagster-postgres required in deployment examples

### ISSUE THREAD

**Issue by fj-sanchez** [dagster-io/dagster#2615]
I was following the documentation here https://docs.dagster.io/docs/deploying/local but the `Dockerfile` doesn't install `dagster-postgres`, which is then required according to the `dagster.yaml` used. ~~Also, that page is a bit outdated now that `repository.xml` is the preferred way of running dagit.~~ I got this bit wrong, it might be required to update it for 0.9.0 though.

I'm happy to submit a fix but I wanted to confirm that I'm right before doing anything.

**Comment by fj-sanchez** [comment]
It seems that also `dagster-cron` is required or it will fail, as by default it tries to enable the scheduling.

**Comment by catherinewu** [comment]
thanks @fj-sanchez for this issue report!

https://docs.dagster.io/docs/deploying/local is decoupled from the dagster.yaml/dockerfile now, so going to close. 

also deploying in docker now includes postgres deps https://docs.dagster.io/deploying/docker
