### ISSUE TITLE
Add option to provide run configuration to `dagster asset materialize` command

### ISSUE THREAD

**Issue by cmpadden** [dagster-io/dagster#26217]
### What's the use case?

When materializing an asset from the command-line, it is not currently possible to provide the configuration for that asset.

Current options include:
```
Options:
  -a, --attribute TEXT          Attribute that is either a 1) repository or job or 2) a function that returns a
                                repository or job
  --package-name TEXT           Specify Python package where repository or job function lives
  -m, --module-name TEXT        Specify module where dagster definitions reside as top-level symbols/variables and
                                load the module as a code location in the current python environment.
  -f, --python-file PATH        Specify python file where dagster definitions reside as top-level symbols/variables
                                and load the file as a code location in the current python environment.
  -d, --working-directory TEXT  Specify working directory to use when loading the repository or job
  --select TEXT                 Asset selection to target  [required]
  --partition TEXT              Asset partition to target
  --partition-range TEXT        Asset partition range to target i.e. <start>...<end>
  -h, --help                    Show this message and exit.
```

It would be nice to be able to provide a YAML file, or JSON blob from the command-line to test asset materialization.

This idea came when working [Dagster Neovim plugin](https://github.com/cmpadden/dagster.nvim).

### Ideas of implementation

Introduce `--run-config` option in which either a file or JSON blob can be provided.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by Ajay-Satish-01** [comment]
#16802 is solving a similar problem, right?

**Comment by cmpadden** [comment]
> #16802 is solving a similar problem, right?

Exactly! I will close this one as a duplicate - thank you.
