### ISSUE TITLE
AutomationCondition API migration guide

### ISSUE THREAD

**Issue by LPauzies** [dagster-io/dagster#26223]
### What's the issue?

I'm trying to migrate sensors from Dagster 1.7.4 to 1.9.2.
As asked by the framework some entities are deprecated, and it is the case of `@multi_asset_sensor`, saying that we should use `AutomationConditions` instead :
```Python
@deprecated(breaking_version="2.0.0", additional_warn_text="use `AutomationConditions` instead")
```

I don't find the documentation very clear and there is no migration guide (I think it should be a migration guide as the way we implement things change totally).

I would want to migrate the following code to the one using AutomationConditions API : 
```Python
from dagster import AssetKey, RunRequest, SensorEvaluationContext, multi_asset_sensor

from jobs import job_4, job_5

@multi_asset_sensor(
    name="dbt_and_native_implemented_assets_sensor",
    description="A sensor that refreshes DBT stuff and materialize given sensors.",
    monitored_assets=[
        AssetKey(path=["code_loc_1", "dbt", "asset_1_job_1"]),
        AssetKey(path=["code_loc_1", "dbt", "asset_2_job_1"]),
        AssetKey(path=["code_loc_1", "dbt", "asset_3_job_1"]),
        AssetKey(path=["code_loc_2", "python", "asset_1_job_2"]),
        AssetKey(path=["code_loc_2", "python", "asset_2_job_2"]),
        AssetKey(path=["code_loc_2", "python", "asset_3_job_2"]),
        AssetKey(path=["code_loc_2", "python", "asset_4_job_2"]),
        AssetKey(path=["code_loc_3", "dbt", "asset_1_job_3"]),
        AssetKey(path=["code_loc_3", "python", "asset_2_job_3"]),
    ],
    jobs=[
        job_4,
        job_5,
    ],
)
def dbt_and_native_implemented_assets_sensor(context: SensorEvaluationContext):
    asset_events = context.latest_materialization_records_by_key()
    if all(asset_events.values()):
        context.advance_all_cursors()
        yield RunRequest(job_name="job_4")
        yield RunRequest(job_name="job_5")
```
The documentation says here : https://docs.dagster.io/concepts/automation#selecting-a-method, that in the case above, we should choose https://docs.dagster.io/concepts/partitions-schedules-sensors/asset-sensors but the deprecation decorator shows that we should use AutomationConditions). Who is right and how to handle my use case if I have to use AutomationCondition ? How would you do ?

### What did you expect to happen?

I expect the documentation to be clearer with some examples showing how to migrate from `@multi_asset_sensor` to AutomationConditions API. Maybe with some example with DBT for example and how to work with job triggering using AutomationConditions if the deprecation message is true. Otherwise specify that we should use assets_sensors as above.

### Dagster version

dagster, version 1.9.2

### Deployment type

Other Docker-based deployment

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by lydialimlh** [comment]
I have the same question. I was previously using `@multi_asset_sensor` because the regular sensors weren't able to sense specific partitions and pass them on to the run requests. Maybe there is a better way now but I'm also puzzled by the recommendation to use AutomationConditions

**Comment by smackesey** [comment]
Thanks for reporting this. We've realized that, while automation conditions are a good replacement for the most common use case of `@multi_asset_sensor` in the past (triggering materializations of a target asset when upstream assets were materialized), automation conditions don't cover _all_ use cases-- for example, when launching jobs from the sensor, as in OP here. So we are going to roll back deprecation of `@multi_asset_sensor` as a whole and may emit deprecation warnings in more narrowly scoped circumstances.

There _is_ a [migration guide](https://github.com/dagster-io/dagster/discussions/23495) from auto-materialize policies to automation conditions, but it unfortunately doesn't cover multi-asset sensors.

**Comment by LPauzies** [comment]
Thanks for the the answer and the reactivity :pray:

**Comment by sugendran** [comment]
I just spent the best part of a day trying to work out what I was missing, and this was it. Could you update the docs to explain that this is not supported? Or at least the bot?

Also, is there something in the works that will have the declarative automation system support this?

**Comment by smackesey** [comment]
>I just spent the best part of a day trying to work out what I was missing, and this was it. Could you update the docs to explain that this is not supported? Or at least the bot?

Can you clarify? This issue was about the deprecation of multi-asset sensors, but we reversed their deprecation.

**Comment by luqmansen** [comment]
I was also really confused by the documentation, which suggests using `AutomationCondition` instead of `multi_asset_sensor`, but gives no example of how to translate the exact code.
https://docs.dagster.io/guides/automate/asset-sensors#monitoring-multiple-assets

If possible, can you also help to update the docs (or can I? I didn't see any contribute button on the docs page)

**Comment by jburnich** [comment]
Documentation to date indicates this.

<img width="524" height="182" alt="Image" src="https://github.com/user-attachments/assets/32525d48-a8af-462f-a32a-c8e60be7b097" />

In view of your comment
> This issue was about the deprecation of multi-asset sensors, but we reversed their deprecation.

Will they be removed from 2.0? Or kept in the code base?

**Comment by LPauzies** [comment]
I think Dagster team should find a solution, at the moment and from my knowledge, AutomationCondition does not cover the way to trigger a job when some assets have been materialized yet. For an orchestration tool, it is totally paradoxical.
