### ISSUE TITLE
Support retries for Celery K8s Executor

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2626]
CeleryK8sJobConfig allows user to configure retries, but that value is ignored in execute_plan

<img width="972" alt="Screen Shot 2020-06-18 at 12 22 11 AM" src="https://user-images.githubusercontent.com/6024687/85179483-f0221e00-b235-11ea-83ad-5de087499be7.png">

**Comment by alangenfeld** [comment]
I think the best bet is to fix this as part of moving from invoking `executePlan` via GraphQL to invoking a execute_plan CLI API call
