### ISSUE TITLE
Partition filter in UI for MultiPartitionsDefinition  filters on both sub partitions

### ISSUE THREAD

**Issue by the4thamigo-uk** [dagster-io/dagster#26267]
### What's the issue?

Typing a search string into the filter for one sub-partition filters the other one. 

https://github.com/user-attachments/assets/ecebeb25-b4c4-426a-8252-eea0ea1339aa

### What did you expect to happen?

They ought to be independent.

### How to reproduce?

See video

### Dagster version

1.9.2

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by hellendag** [comment]
Should be fixed by https://github.com/dagster-io/dagster/pull/26580, which should go out in the next release.
