### ISSUE TITLE
Cron schedules day and day of week filter do not work

### ISSUE THREAD

**Issue by tobiascadee** [dagster-io/dagster#26537]
### What's the issue?

When providing a schedule with a cron like this `0 10,12,14,16 3-20 * 1-5`. The hour selectors work properly but the day of week and day of month selectors do not work. This means the job also runs during the weekends and also on other days that I want it to run.

### Dagster version

1.9.4

### Deployment type

Dagster Cloud

### Deployment details

Hybrid deployment with Kubernetes agent.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by gibsondan** [comment]
Hey @tobiascadee - I initially thought this was a bug in the cron library that we use to determine schedules for cronstrings, but after investigating I think this might actually be what the official cron spec says should happen (For what it's worth, I find this confusing and would also expect it to work the way you did): https://pubs.opengroup.org/onlinepubs/007904975/utilities/crontab.html

"Finally, if either the month or day of month is specified as an element or list, and the day of week is also specified as an element or list, then any day matching either the month and day of month, or the day of week, shall be matched."

One way that you could work around this is to add logic to your schedule function that inspects the context.scheduled_execution_time and implements the logic that you actually want:


```
@schedule(cron_schedule="0 10,12,14,16 * * 1-5") # Left out the day of the month
def my_schedule(context):
  day_of_month = context.scheduled_execution_time.date().day
  if day_of_month < 3 or day_of_month > 20:
     return SkipReason(f"Wrong day of month {day_of_month}")

  return RunRequest()
```

**Comment by tobiascadee** [comment]
@gibsondan thanks so much for the quick reply! Should have found this myself sorry for not checking. Yeah I agree this is very confusing. I will edit my schedule accordingly.
