### ISSUE TITLE
dagit webserver rewrite

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2655]
possibly; possibly swapping out the `gevent-websockets` library. recording slack discussion here:

Looking at the code for Dagit, I'm curious if there has been any discussion around the use of gevent-websockets given that it hasn't seen any commits for the past 2 years. As a corollary to that, has there been any consideration of converting to one of the ASGI frameworks given the reliance on websockets?
5 replies

alex  28 minutes ago
ya its definitely a known source of risk using that stale websocket library. As we continue down this path of separating “host” processes from “user” processes, we’ve actually been discussing rewriting the dagit webserver in Javascript given the maturity of the GraphQL and. websocket libraries there.
Will have to look in to ASGI as well, thanks for the suggestion.

Tobias Macey  13 minutes ago
Some notable options on the ASGI side are FastAPI for a well-designed framework that would require a rewrite of Dagit, or Quart for a shorter migration path

Tobias Macey  13 minutes ago
https://pgjones.gitlab.io/quart/

Tobias Macey  13 minutes ago
https://fastapi.tiangolo.com/

fastapi.tiangolo.comfastapi.tiangolo.com
FastAPI
FastAPI framework, high performance, easy to learn, fast to code, ready for production

Tobias Macey  11 minutes ago
For GraphQL options you might also look at Ariadne https://ariadnegraphql.org/

ariadnegraphql.orgariadnegraphql.org
Ariadne · Python GraphQL Schema-first
A Python library for implementing GraphQL servers using schema-first approach.

**Comment by schrockn** [comment]
Big decision point whether or not to keep it in python or not:

- If we do python we could make dagit python 3 only and choose a fresh graphql stack/web stack
- Otherwise make the whole thing JS/TS top-to-bottom

**Comment by fj-sanchez** [comment]
If anyone picks dragster as a library it means that they already are committed to use python, that's why for me it makes more sense to keep everything in python. Otherwise the risk is that they decide to not use dagster because they would have to also support JavaScript for dagit.

**Comment by schrockn** [comment]
In the dagit-as-JS model, it would be packaged as a docker container (for deployment) or an Electron app (for the desktop). Users would not have to support it.

**Comment by fj-sanchez** [comment]
Well, that's not my view. When I propose to adopt a library or project in my company I expect that I will have to fix bugs on it and contribute features, I wouldn't like to put my team or myself in a situation where we have a component that we cannot fix or improve. Now, this means that my team would require JS/TS developers and python developers which I'm not saying is wrong, just something else to consider.

**Comment by schrockn** [comment]
That's fair. But also if you are contributing end-to-end features in dagit, you definitely have to be using JS/TS anyways in order to implement the in-browser features.

To be clear, dagster core and all integrations would still be in python. I.e. the vast majority of the system. So bug fixes in the core runtime and integrations would be all python as before.

This task *only* refers to the dagster-graphql module and the dagit web-server. In fact one of the advantages of this is that our frontend developers could add more features without having to touch python.

**Comment by fj-sanchez** [comment]
Thanks for the clarification. As I said, I'm not opposing to this change, I only wanted to raise this point to be considered as part of the decision.

**Comment by alangenfeld** [comment]
As of `0.14.0` :
* Dagit now uses starlette (the same ASGI framework as FastAPI) 
* More work to be done on `dagster-graphql` - this still has the pins we used for the `flask` & `gevent-websockets` setup

**Comment by bengotow** [comment]
Removing this from the Dagit UI/UX project since it seems to be strictly related to the graphQL layer 👋

**Comment by hellendag** [comment]
Closing in favor of newer or more granular issues as needed.
