### ISSUE TITLE
Add autodocs stub in bin/create_library.py

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2656]
We should automatically generate the API docs page for new libraries when they are added

**Comment by FishmanL** [comment]
it should just be a matter of getting library.__all__ and an autodoc template?

**Comment by erinkcochran87** [comment]
@yuhan Do you know if this has since been addressed? Or do docs for new libraries still need to be added manually?

**Comment by yuhan** [comment]
i dont think this has been addressed - it's still manual at the moment. 

do you think this is something we'd want to do? i'm inclined to mark it as "won't do" as imo it's pretty low maintenance (vs to automatically figure out if the new lib is ready to be included in the docs) and we can reopen the issue if we feel like doing.

**Comment by erinkcochran87** [comment]
I'm also inclined to say we can close this for now. If we were adding brand new libraries / integrations all the time I think this would be worth doing, but it feels like it's not necessary at the moment.
