### ISSUE TITLE
Broken Tutorial Links 

### ISSUE THREAD

**Issue by rlaabs** [dagster-io/dagster#2659]
On the tutorial page (https://docs.dagster.io/docs/tutorial)

The 'Basics of Pipelines' link incorrectly points to https://docs.dagster.io/docs/tutorial/basics_solids

**Comment by helloworld** [comment]
I just tried clicking the link and it seems to be going to the right page. Could you try again?

**Comment by rlaabs** [comment]
Sorry, I should have been more clear. The link in the left sidebar looks right. It's the link in the center of the page that looks like its pointing to the wrong place. That is assuming it is intended to be the same as the 'Basic of Pipelines' link in the sidebar.

Here's the source:

`
<a href="/docs/tutorial/basics_solids"><strong>Basics of Pipelines</strong></a> will teach you the basics of using
pipelines.
`

**Comment by helloworld** [comment]
This will be fixed in today's release - thanks again!
