### ISSUE TITLE
List[T] where T requires custom serialization currently not supported in the intermediates manager

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2667]
See https://dagster.slack.com/archives/CCCR6P2UR/p1593471935347400?thread_ts=1593298111.294200&cid=CCCR6P2UR for bug report in slack

**Comment by schrockn** [comment]
@mgasner I thought we had another issue tracking this but I'm not finding it

**Comment by catherinewu** [comment]
@sryza is this supported with the more flexible IOManager?

**Comment by sryza** [comment]
Yes - users should now be able to serialize however they want with IO managers.
