### ISSUE TITLE
returning multiple outputs in composite solids not documented / different from solids

### ISSUE THREAD

**Issue by filthysocks** [dagster-io/dagster#2669]
Hello,

I want to return multiple outputs from a composite solid. From the [documentation](https://docs.dagster.io/docs/tutorial/basics_solids#multiple-and-conditional-outputs) i would have assumed something like this:
``` python
@solid
def s_1(_) -> int:
    return 1

@solid
def s_2(_) -> int:
    return 2

@composite_solid(
    output_defs=[OutputDefinition(int, "a"), OutputDefinition(int, "b")]
)
def c():
    a = s_1()
    b = s_2()

    yield Output(a, "a")
    yield Output(b, "b")
```
this yields an error:
` dagster.core.errors.DagsterInvalidDefinitionError: @composite_solid c returned problematic value of type <class 'generator'>. Expected return value from invoked solid or dict mapping output name to return values from invoked solids
`

However, the following code works:
```python
@composite_solid(
    output_defs=[OutputDefinition(int, "a"), OutputDefinition(int, "b")]
)
def c():
    a = s_1()
    b = s_2()

    return {"a": a, "b": b}
```
I suggest to either document this or make the behavior for returning multiple outputs from composite solids and solids consistent.

BTW:
I think it would be really great if i could just write
``` python
from typing import Tuple


@composite_solid()
def c() -> Tuple[int, int]:
    a = s_1()
    b = s_2()

    return a,b
```

**Comment by yuhan** [comment]
https://docs.dagster.io/concepts/solids-pipelines/composite-solids#multiple-outputs
