### ISSUE TITLE
Eliminate schism between helm chart and tests

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2671]
Because of resource exhaustion issues in our buildkite we have to comment out:
```
# 'extraWorkerQueues': [{'name': 'extra-queue-1', 'replicaCount': 1},],
```
in helm.py. This is in our helm chart so having the schism is bad.

Here's an example build that exposed the issue: https://buildkite.com/dagster/dagster-diffs/builds/5072#97c97507-5a81-40dc-8a0b-2e3ea3f08e88

For more context on the error involved:

https://kind.sigs.k8s.io/docs/user/known-issues/#unable-to-pull-images

**Comment by natekupp** [comment]
Closing, this is resolved - @rexledesma to link the diff here
