### ISSUE TITLE
Merge `FileInDirectoryCodePointer` and `FileCodePointer`

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#2673]
FileInDirectoryCodePointer and FileCodePointer can be merged, but this would shift all the stored schedule_origin_ids.

To resolve, we would need to blow away schedule storage, which is pretty disruptive and should be paired with other storage changes / a more significant release.  Potentially for `0.9.0` or `0.10.0`.

**Comment by gibsondan** [comment]
Believe this is done, FileInDirectoryCodePointer no longer exists
