### ISSUE TITLE
Create an official python client to the GraphQL API

### ISSUE THREAD

**Issue by dbendelman** [dagster-io/dagster#2674]
Please consider adding an officially maintained and documented python client for the graphql endpoint, e.g.

```
from dagster_graphql import DagsterGraphQLClient

client = DagsterGraphQLClient(host='localhost', port=9000)
client.launch_pipeline('my_pipeline', config={})
```

There is already code in the `dagster_graphql` test suite that implements something akin to a client ([example](https://github.com/dagster-io/dagster/blob/d9ced0a4f17e4327cb856d89868c136058d118d6/python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_execute_pipeline.py#L20-L32)), but all this code is tightly coupled with fairly complex test scaffolding and of course it's not easily usable outside that test suite.

Such a client would be incredibly useful:
* Pipeline solids launching other pipelines (our particular use case, and a common one from what I see in dagster slack).
* Easily interact with a dagit server from steps in a CI/CD pipeline.
* Pave the way for third party control planes for dagit to be written.
* Simplify dagster's own tests.

**Comment by mgasner** [comment]
should have documented oauth support

**Comment by sidkmenon** [comment]
Should be closed with https://github.com/dagster-io/dagster/commit/e929746efd1c1ca76a6a85a11d874593ed93450c
