### ISSUE TITLE
Update pyspark 2.4.4 to pyspark 3.0.0

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2678]
We should upgrade to the newest spark version in our integration image and tests

**Comment by natekupp** [comment]
see also #1960 

noting here for whoever looks into this, IIRC spark 2/3 have  different Java and debian version requirements, so this may be a bit involved to fix.

**Comment by natekupp** [comment]
see http://spark.apache.org/docs/latest/

> Spark runs on Java 8/11, Scala 2.12, Python 2.7+/3.4+ and R 3.1+. Java 8 prior to version 8u92 support is deprecated as of Spark 3.0.0. Python 2 and Python 3 prior to version 3.6 support is deprecated as of Spark 3.0.0. R prior to version 3.4 support is deprecated as of Spark 3.0.0. For the Scala API, Spark 3.0.0 uses Scala 2.12. You will need to use a compatible Scala version (2.12.x).

**Comment by natekupp** [comment]
Fixed by https://dagster.phacility.com/D4091
