### ISSUE TITLE
make dev_install does not not work on python 2

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2680]
We have python-3-only modules now (e.g. great_expectations). IMO we should move to a world where our integrations are free to be py3-only but we will need to update our tooling to support that.

**Comment by kinghuang** [comment]
Perhaps it's time to drop support for Python 2? The final Python 2.7 reached end of life at the beginning of the year, and the final release happened in April.

**Comment by catherinewu** [comment]
closing bc py2 is deprecated
