### ISSUE TITLE
Dagit config editor help panel overlaps input text

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#2681]
In Dagit's Playground view, the help panel to the right of the config editor can overlap long config lines, making them hard to edit.

In the following screenshot, the long path strings end up under the help panel.

![Screen Shot 2020-07-05 at 2 16 45 PM](https://user-images.githubusercontent.com/27340/86541443-3039ff80-beca-11ea-852b-c635da72e8a2.png)

**Comment by bengotow** [comment]
This should be resolved by https://dagster.phacility.com/D3882!

**Comment by bengotow** [comment]
Hmm, so I'm not sure there's a perfect way to address this - it seems like we could hard wrap the text in the editor, but at that point it might be preferable to switch the sidebar from a floating panel to a split panel like this. Will push up a change with this and collect some feedback! Stay tuned—

![image](https://user-images.githubusercontent.com/1037212/87451584-aecb2700-c5c5-11ea-9186-f64049cd8758.png)

**Comment by hellendag** [comment]
This was fixed.
