### ISSUE TITLE
Doc navigation is confusing with small width

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#2682]
It's unclear that you need to click on the hamburger to get the overviews. We could specify that in the landing page, or maybe better would be if they could be listed on this page as well.

<img width="1017" alt="Screen Shot 2020-07-06 at 10 20 49 AM" src="https://user-images.githubusercontent.com/22018973/86603790-7ea2d900-bf72-11ea-9f87-764e7995ed1a.png">

**Comment by yuhan** [comment]
could get done with #2540
