### ISSUE TITLE
Links in API Docs index page should link to given version not latest

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#2685]
<img width="752" alt="Screen Shot 2020-07-06 at 3 16 27 PM" src="https://user-images.githubusercontent.com/4531914/86656664-7bbcde00-bf9c-11ea-933f-432ae0cd42fc.png">

sidebar items link to the given version, but the ones in red box don't

**Comment by adharshkamath** [comment]
Hello! I'd like to work on this issue. Can you please tell me how I can reproduce this?
I cloned this repository and built the docs site. But I get a 404 error when I try to open docs for versions < 0.8.7

**Comment by yuhan** [comment]
Hi @adharshkamath! Thanks for looking into this. This one is a bit involved -- it requires an extra sphinx build step to enable reproducing and testing it locally. We will handle this one. 

Feel free to pick up an issue labelled as "good first issue" [here](https://github.com/dagster-io/dagster/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) if you would like to contribute :)

**Comment by adharshkamath** [comment]
Will do. Thank you!

**Comment by yuhan** [comment]
@helloworld looks like the new _apidocs isnt working with versioning either.
https://docs.dagster.io/0.11.0/_apidocs:
<img width="605" alt="Screen Shot 2021-03-22 at 4 51 09 PM" src="https://user-images.githubusercontent.com/4531914/112072338-d9935500-8b2e-11eb-94aa-dd6497c9c3b3.png">

can you take a look?

**Comment by yuhan** [comment]
fixed
