### ISSUE TITLE
intermediates_storage and system_storage both have is_persistent properties that can disagree

### ISSUE THREAD

**Issue by FishmanL** [dagster-io/dagster#2686]
moreover, those properties  are confusing (why is mem_system_storage not persistent if its file system is?)
would probably be better if file_storage and intermediates_storage had their own persistence tags, and there wasn't a global tag

**Comment by sryza** [comment]
intermediate_storage and system_storage should be mutually exclusive, so I don't think them having the potential to disagree is a problem.  Gonna close this.
