### ISSUE TITLE
Implement single click re-executiobn in dagit run viewer

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2687]
Current we always require 2 clicks to instigate a re-execution. We should make this a one click operation with reasonable default behavior.

**Comment by bengotow** [comment]
This should be resolved by https://dagster.phacility.com/D3882! 

![image](https://user-images.githubusercontent.com/1037212/87446356-ce128600-c5be-11ea-8c3f-f7efb7b6aabf.png)
