### ISSUE TITLE
Documentation on "Data Science with Notebooks" needs updating

### ISSUE THREAD

**Issue by JeroenSchmidt** [dagster-io/dagster#2690]
I'm exploring dagsters functionality within the data science workflow and I've come across a few issues.

1) I can not reach this [guide]( https://docs.dagster.io/learn/guides/data_science/data_science) from your home page. I was only able to find it through a google search. In fact there appear to be a few guides under https://docs.dagster.io/learn/guides/ which appear very useful but I couldn't figure out how to reach them from your homepage. 

2) Within the data science guide, you import `dagster_examples` but I'm unable to find a way to install this package. Has this been depricated? If this is the case, where can I find a guide for using dagster with notebooks within a data science workflow?

**Comment by yuhan** [comment]
Hi @JeroenSchmidt, Thanks for reporting the issues! We're currently overhauling our guides and examples, as well as organizing our docs structure -- sorry for the inconvenience it caused, and it will be done by the end of this month.

1. We've moved the data science guide to https://docs.dagster.io/overview/packages/dagstermill. Besides, if you would like to read the older docs, you can go to our [versions' page](https://docs.dagster.io/versions) by clicking the version number on the top menu, and clicking "Documentation" will bring you to the docs of the given version.
2. You can find the data_science guide's example code here: https://github.com/dagster-io/dagster/tree/master/examples/docs_snippets/docs_snippets/legacy/data_science. I've pushed a doc change regarding some mismatch in the guide's content, which will be live by the end of this week.

Again, really appreciate your feedback! Please don't hesitate to reach out if you have any questions/feedback.

**Comment by yuhan** [comment]
moved to https://docs.dagster.io/overview/packages/dagstermill
