### ISSUE TITLE
RunGroupPanel showing non-local times, incorrect elapsed times

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#2695]
https://www.dropbox.com/s/4klnr15udo0a16r/Screen%20Recording%202020-07-08%20at%203.34.59%20PM.mov?dl=0

**Comment by hellendag** [comment]
Not a UI issue after all. The timestamps are handled correctly in JS, but are incorrect coming from the backend. It looks like the wrong timestamp is being applied to the events. Related to #3061.

**Comment by catherinewu** [comment]
closing as this does not seem to be an issue with RunGroupPanel and https://github.com/dagster-io/dagster/issues/3061 is tracked separately
