### ISSUE TITLE
View numeric data in Assets as table 

### ISSUE THREAD

**Issue by sephib** [dagster-io/dagster#2697]
Hi,
Currently the [Materialization](https://docs.dagster.io/_apidocs/solids#dagster.Materialization) displays numeric assets in a graph.  
It would be useful if that data can be viewed as a table (even better if the table could be filtered/sorted on the fly).   
Additionally adding to the graph tooltip the `RUN` ID could also assist in navigating between the chart and runs

**Comment by sryza** [comment]
@bengotow recently added this!
