### ISSUE TITLE
Hardcoded file paths in sources for Dagit

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2699]
When viewing the sources for Dagit, a hardcoded user path shows up with what seems to be stylesheets. The path corresponds to whoever did the last release. 

![image](https://user-images.githubusercontent.com/3893054/87169544-27687580-c29e-11ea-95b6-e60671e708fc.png)

**Comment by bengotow** [comment]
Hey folks! This appears to be resolved by the recent upgrade we did to react-scripts 4. After doing a `yarn build` of Dagit, the build folder doesn't contain any references to my system path (in the image above it looks like it was appearing in a .css.map file). If this crops up again let's re-open!
