### ISSUE TITLE
Unpin Airflow dependency and refresh Kubernetes integration

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2701]
Apache Airflow 1.10.11 introduces a substantial refactor of their Kubernetes APIs, which breaks dagster-airflow. We're pinning for now in [D3839](https://dagster.phacility.com/D3839) until we have time to address the compatibility issues.

**Comment by natekupp** [comment]
The work is started here - https://dagster.phacility.com/D3837

We should probably just vendor everything k8s-related from airflow so that we don't depend on their implementation and avoid this in the future

**Comment by sryza** [comment]
was unpinned from Airflow 1.0 some time ago
