### ISSUE TITLE
Extend partition set configs from preset configs

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#2704]
I've created a pipeline with preset configs, and would like to add partition definitions to it. I'm surprised to find that [PresetDefinition](https://docs.dagster.io/_apidocs/pipeline#dagster.PresetDefinition) and [PartitionSetDefinition](https://docs.dagster.io/_apidocs/partitions#dagster.PartitionSetDefinition) are independent concepts that do not work together.

For example, suppose I have two preset configs. One for local execution and one for remote execution. The are reading a partitioned Parquet dataset either from a local filesystem or a S3 bucket.

**local.yml**:

```yaml
solids:
  example:
    inputs:
      data:
      	read:
      	  parquet:
      	    path: /tables/supplier_catalog
```

**remote.yml**:

```yaml
solids:
  example:
    inputs:
      data:
      	read:
      	  parquet:
      	    path: s3://some_bucket/tables/supplier_catalog
```

The pipeline definition uses `preset_defs` to load these configs.

```python
@pipeline(
    name="example",
    preset_defs=[
        PresetDefinition.from_pkg_resources(
            name="local",
            mode="default",
            pkg_resource_defs=[
                ('sa_extract.info.presets', 'catalog_local.yaml'),
            ],
        ),
        PresetDefinition.from_pkg_resources(
            name="remote",
            mode="default",
            pkg_resource_defs=[
                ('sa_extract.info.presets', 'catalog_remote.yaml'),
            ],
        ),
    ],
)
```

The Parquet datasets have been stored with partitions by year. I want to add a filter parameter to the solid configs to read the data by partition. Using a PartitionSetDefinition, I wrote the following.

```python
def catalog_partition_run_config(partition):
    dt = partition.value

    return {
        "solids": {
            "example": {
                "inputs": {
                    "data": {
                        "read": {
                            "parquet": {
                                "filters": [["year", "=", str(dt.year)]]
                            }
                        }
                    }
                }
            }
        }
    }

catalog_partition_set = PartitionSetDefinition(
    name="catalog_partition_set",
    pipeline_name="example",
    partition_fn=date_partition_range(
        start=datetime.datetime(2001, 1, 1),
        end=datetime.datetime(2019, 1, 1),
        delta=relativedelta(years=1),
        inclusive=True,
    ),
    run_config_fn_for_partition=catalog_partition_run_config,
)
```

I was expecting the partition config to add on to the preset config. Instead, it replaces the preset config, Thus, the partition config as written is missing the `path` parameter from the presets.

In order to have `local` and `remote` configs along with partitions, two PartitionSetDefinitions would have to be created. For `n` presets and `m` partition schemes, `n × m` PartitionSetDefinitions would have to be created.

## Proposal

When generating a pipeline config, provide a way to merge a preset config (or an arbitrary base config) with a partition set config. So, rather than being two independent ways to generate a config, partition set configs should be an extension of a preset config.

Of the options presented below, I recommend option 2.

### Option 1: Dagster deep merges preset configs with partition set configs

Given a preset config and partition set config, Dagster would deep merge the partition set config into the preset config to generate a run config. For the examples above, the merged run config would be the following.

```yaml
solids:
  example:
    inputs:
      data:
      	read:
      	  parquet:
      	    path: /tables/supplier_catalog
            filters": [["year", "=", str(dt.year)]]
```

The idea here is equivalent to how Docker Compose files or GitLab CI/CD configs are merged together. However, common problems in those systems include the inability to merge lists and unassign dict keys. I do not recommend this option.

### Option 2: Provide the current config as an argument to run_config_fn_for_partition

Pass the preset config or the current playground config as an optional argument to the function specified for `run_config_fn_for_partition`. The function can then modify the config with partitioning details instead of generating a complete config.

```python
def catalog_partition_run_config(partition, config={}):
    dt = partition.value
    config["solids"]["example"]["inputs"]["data"]["read"]["parquet"]["filters"] = [["year", "=", str(dt.year)]]

    return config
```

This should preserve compatibility with existing functions, and allows full control over how the partition config is constructed.

## Further Details

With this change, Dagit should show presets and partition sets as two separate selections, instead of a single list of mutually exclusive options.

Along with this proposed change, I think partition set definitions should be part of pipeline definitions rather than top level repository objects. For example:

```python
@pipeline(
    name="example",
    preset_defs=[
        PresetDefinition.from_pkg_resources(
            name="local",
            mode="default",
            pkg_resource_defs=[
                ('sa_extract.info.presets', 'catalog_local.yaml'),
            ],
        ),
        PresetDefinition.from_pkg_resources(
            name="remote",
            mode="default",
            pkg_resource_defs=[
                ('sa_extract.info.presets', 'catalog_remote.yaml'),
            ],
        ),
    ],
    partition_set_defs=[
        PartitionSetDefinition(
            name="catalog_partition_set",
            partition_fn=date_partition_range(
                start=datetime.datetime(2001, 1, 1),
                end=datetime.datetime(2019, 1, 1),
                delta=relativedelta(years=1),
                inclusive=True,
            ),
            run_config_fn_for_partition=catalog_partition_run_config,
        ),
    ],
)
```

**Comment by prha** [comment]
With `0.12.0`, we've deprecated presets and put partitioned config on the job as opposed to the repository.
