### ISSUE TITLE
google.protobuf.descriptor has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by b0nj0m0n** [dagster-io/dagster#2707]
Getting `module 'google.protobuf.descriptor' has no attribute '_internal_create_key'` on a newly upgraded dagster when attempting to `import dagster`. Found a few closed issues but no resolution steps that I could send to our Linux team to follow. How does one resolve this issue?

**Comment by alangenfeld** [comment]
what version of `dagster`, `grpcio`, and `grpcio-tools` are you on?

**Comment by b0nj0m0n** [comment]
`dagster` is 0.87, was upgraded to the latest version last Friday
`grpcio` is 1.30.0
`grpcio-tools` is not installed - is this a requirement?

**Comment by alangenfeld** [comment]
looks like that is just a dev-requirement, how about `protobuf` ?

**Comment by b0nj0m0n** [comment]
`protobuf` is 3.11.3

**Comment by alangenfeld** [comment]
currently require protobuf to be `3.12.2` 
https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/setup.py#L80

**Comment by b0nj0m0n** [comment]
Thanks Alex - I'll have the admins upgrade protobuf. Appreciate your help!
