### ISSUE TITLE
hard protobuf version pin 

### ISSUE THREAD

**Issue by bollwyvl** [dagster-io/dagster#2708]
Congrats on the `0.8.7` release! Really looking forward to playing with it.

In this release, and the previous one, we've run into some issues over on [conda-forge](https://github.com/conda-forge/dagster-feedstock/pull/49) in supporting that _specific_ version of `protobuf`, as there were some complications with it (or rather, it's upstream) [building under windows](https://github.com/conda-forge/protobuf-feedstock/pull/87).

I'm not sure what lead to the decision (they can be hard) of doing the really tight pin, but it can sometimes make it much harder to satisfy for downstream packagers. `airflow` is a beast, for this reason.

Would it be possible to open up the pin, to something more permissive like `>=3.12.2,<3.13`? Or, introduce an `extra` like `[strict-protobuf]` that would allow for the tighter pin, if desired? 

The same probably goes for `grpcio`: I did get that version to build, finally, but the release cadence is fairly mysterious, and no doubt we might some time in the future basically not be able to build a full release for all our platforms for a _specific_ version, especially if there are upstream issues.

**Comment by bollwyvl** [comment]
Friendly reminder that @conda-forge/dagster-feedstock can't proceed with packaging these new releases for conda-forge against `3.12.2`.  conda-forge has already packaged `3.12.3`, but there are no releases for that version on pypi, which doesn't help my confusion.

I don't really know what the right play is, and don't have the fortitude to wade into windows land to get the broken libprotobuf build working. It seems like the _purpose_ of protobuf is to be backwards-and-forwards compatible, so downgrading the codegen build chain to `3.12.0` and setting the pin to `>=3.12.0,<3.13.0a0` _should_ work, but again, you folks made the call for a good (customer) reason, I'm sure. 

Looks like `4.0` is on the horizon... it looks like there are a fair amount of changes to the python _and_ c++ sides of the house, so who knows what fresh horrors await.

**Comment by alangenfeld** [comment]
Hey thanks for staying on our case about this. Looking in to how we can try to get back in to a good state for `0.9.0` .

**Comment by bollwyvl** [comment]
Awesome! Looking forward to it!
