### ISSUE TITLE
Missing Playground view in tutorial

### ISSUE THREAD

**Issue by animator** [dagster-io/dagster#2712]
In the page [Building Pipelines with Dagster](https://docs.dagster.io/tutorial/execute) > Executing Our First Pipeline > From a GUI, use the Dagit tool, 

It says `Click on the "Playground" tab and you'll see the view below.`, but the same image is repeated twice instead of the playground view. 

![dagit](https://user-images.githubusercontent.com/615622/87358501-989c7700-c583-11ea-8544-4dd90f2e330a.PNG)

**Comment by nancydyc** [comment]
Updated the screenshots by landing diff [D5225](https://dagster.phacility.com/D5225)
