### ISSUE TITLE
Pipeline concurrency control

### ISSUE THREAD

**Issue by dbendelman** [dagster-io/dagster#2716]
It would be nice if Dagster could allow controlling the max concurrent number of runs a pipeline can have. Something like:

```
@pipeline(max_concurrent_runs=3)
def my_pipeline():
```

We have a pipeline solid that ingests a feed of `Thing` items from a source and starts a child pipeline for each one. We need to do this because we want to visualize, control, and rate limit the processing of each `Thing` independently, but more importantly because we want to process each `Thing` as it's ingested as opposed to waiting until our solid collects them all and outputs them as a List. We therefore needed to find a way to "pause" our generator solid while it waits for some running pipelines to finish.

This feature might not be too hard to add because I've successfully implemented it in my client code:

```
def wait_for_run_slot(pipeline_name, max_runs=1):

    instance = DagsterInstance.get()

    def get_active_runs(pipeline_name):
        started_runs = len(instance.get_runs(PipelineRunsFilter(pipeline_name=pipeline_name, status=PipelineRunStatus.STARTED)))
        not_started_runs = len(instance.get_runs(PipelineRunsFilter(pipeline_name=pipeline_name, status=PipelineRunStatus.NOT_STARTED)))
        return started_runs + not_started_runs

    while get_active_runs(pipeline_name) >= max_runs:
        time.sleep(2)

@solid
def generator(context):
    batch_of_things = ...
    for thing in batch_of_things:
        wait_for_run_slot('process_thing')
        ...launch pipeline...
```

It would be great if this extra machinery could be avoided with a single argument to `@pipeline`. Also, the above code only prevents the generator solid from launching too many runs, but you can still override this limit by launching manually via the web UI. Whereas if the setting is configured into the pipeline definition via `@pipeline`, it could be enforced by dagster internally at a global level.

**Comment by dbendelman** [comment]
To benefit anyone reading this that needs to accomplish the above via graphql, you can make 2 queries like the one below, specifying `STARTED` and `NOT_STARTED` run states and then adding the result counts:

```
pipelineRunsOrError(filter: {
    pipelineName: {pipeline_name}
    status: {status}
  }) {
    ... on PipelineRuns {
      results {
        runId
      }
    }
  }
}
```

**Comment by natekupp** [comment]
@johannkm FYI I'm moving this to Scheduled Runs project board, feel free to dupe this one to a primary issue for run queuing if you have a different one

@dbendelman we're currently working on adding run queueing to Dagster which I think should help here; feel free to jump in our Slack and DM Johann if you have any questions!

**Comment by johannkm** [comment]
Hi @dbendelman, this will be included in our 0.10.0 release. We have the core pieces available to try now https://elementl.quip.com/zSYYAXAZqV1c/How-to-preview-the-QueuedRunCoordinator-Experimental, namely you can specify `max_concurrent_runs` across all pipelines in the system.

To add more specific contraints, we'll be allowing concurrency limits based on tags, which would at least make it possible to emulate something like `@pipeline(max_concurrent_runs=3)`. I'm hesitant to introduce that exact syntax because I believe it isn't usually a property of the pipeline, but of the deployment (the same pipeline might be deployed in two clusters, one with many more resources and therefore a higher possible concurrency limit). Curious to hear any thoughts!

**Comment by johannkm** [comment]
Tag-based concurrency limits are now on master. These will be documented for the 0.10.0 release, but for now they can be seen at https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/run_coordinator/queued_run_coordinator.py#L52-L64.

To achieve the functionality you have above, you can place a tag in the PipelineDefinition, then specify a limit for that tag on the Run Coordinator. I think that satisfies this feature request so I'm closing the issue. Feel free to re-open if that's not the case, or reach out for any questions/comments!

**Comment by dbendelman** [comment]
Thanks @johannkm, this sounds very promising! Unfortunately I'm stuck on 0.8.10 for now with an upgrade deep in the backlog :)

I hope to test this out as part of all the other goodies I'm looking forward to after upgrading. Thanks for the amazing work :1st_place_medal:
