### ISSUE TITLE
dagster.utils.frozenlist cannot be unpickled

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#2719]
## Summary

I have Dagster solids with configs that involve Dask computation. I pass some of the Dagster solid configs to Dask, which get pickled and then unpickled on workers. Config values that are lists are presented as `dagster.utils.frozenlist` objects, which don't seem to be un-pickleable. This is causing errors on Dask workers.

## Details

For example, here is an excerpt of a materialize config on the `refined` output.

```yaml
    outputs:
      - refined:
          to:
            parquet:
              path: /some/path/here
              partition_on:
                - year
                - month
```

The `partition_on` field is declared as a list of strings.

```python
Field([str], is_required=False, description="Construct directory-based partitioning by splitting on these fields’ values.")
```

In the materializer, the code is effectively passing the value of `partition_on` to Dask's [DataFrame.to_parquet](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.to_parquet). This value gets pickled on the client, which Dask workers have to unpickle. This causes a RunetimeError.

```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/distributed/protocol/core.py", line 130, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/usr/local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 302, in deserialize
    return loads(header, frames)
  File "/usr/local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 64, in pickle_loads
    return pickle.loads(x, buffers=buffers)
  File "/usr/local/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 67, in loads
    return pickle.loads(x)
  File "/usr/local/lib/python3.8/site-packages/dagster/utils/__init__.py", line 167, in __readonly__
    raise RuntimeError("Cannot modify ReadOnlyList")
RuntimeError: Cannot modify ReadOnlyList
```

## Steps to Reproduce

It appears the Dagster frozenlist cannot be unpickled. Here is a reproducible example.

```python
>>> import cloudpickle
>>> from dagster.utils import frozenlist
>>> l = frozenlist([1, 2, 3])
>>> data = cloudpickle.dumps(l)
>>> cloudpickle.loads(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/dagster/utils/__init__.py", line 167, in __readonly__
    raise RuntimeError("Cannot modify ReadOnlyList")
RuntimeError: Cannot modify ReadOnlyList
```

## What is the current *bug* behaviour?

`frozenlist` objects cannot be unpickled.

## What is the expected *correct* behaviour?

It should be possible to pickle and unpickle `frozenlist` objects.

## Other information

This problem doesn't seem to affect Dagster's `frozendict` type.

```python
>>> import cloudpickle
>>> from dagster.utils import frozendict
>>> d = frozendict({"a": 1, "b": 2})
>>> data = cloudpickle.dumps(d)
>>> cloudpickle.loads(data)
{'a': 1, 'b': 2}
```

**Comment by alangenfeld** [comment]
Wow this is an incredible bug report, thanks for taking the time to do such a thorough job.

This should be fixable in the same way that `frozendict` was https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/utils/__init__.py#L142-L150

**Comment by kinghuang** [comment]
Funny, I didn't even see that there in `frozendict`! Glad to hear that there may be an easy fix.
