### ISSUE TITLE
Have local state in the config editor keyed off of repo.pipeline, not just pipeline

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2720]
Running into this while building a demo. I'd like to have two repositories in a workspace with the same pipeline name and switch between them. However this clobbers local state in the config editor. It would be better if those two pipeline's didn't clobber each other's config editor state.

**Comment by schrockn** [comment]
Discovered on this code: https://dagster.phacility.com/D3840?id=18796

**Comment by bengotow** [comment]
Resolved in https://dagster.phacility.com/D3928
