### ISSUE TITLE
In multi repository location workspaces, the location gets reset when run is launched

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2722]
See:

![Screenshot 2020-07-14 20 00 48](https://user-images.githubusercontent.com/28738937/87498583-faed8a00-c60c-11ea-904c-caeeefc70275.png)

We are in the "Step four" repo

As you'll see in this zipped video the repository location in context switches to another one, and then we end up not being able to find the pipeline:

[Screen Recording 2020-07-14 at 8.01.22 PM.zip](https://github.com/dagster-io/dagster/files/4922613/Screen.Recording.2020-07-14.at.8.01.22.PM.zip)

see different repo location:

![Screenshot 2020-07-14 20 03 36](https://user-images.githubusercontent.com/28738937/87498640-21abc080-c60d-11ea-91d0-4c36d5d819b1.png)

and then we can't find pipeline

![Screenshot 2020-07-14 20 03 42](https://user-images.githubusercontent.com/28738937/87498647-283a3800-c60d-11ea-9d19-791e9cb213be.png)

**Comment by schrockn** [comment]
Code for exact repro is here: https://dagster.phacility.com/D3840?id=18796 but i would suspect it repros on other multi-location situations

**Comment by bengotow** [comment]
Resolved in https://dagster.phacility.com/D3928
