### ISSUE TITLE
Un-deprecate the config_field property on SolidDefinition

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2724]
I saw this:

```

    @property
    def compute_fn(self):
        return self._compute_fn

    @property
    def config_field(self):
        rename_warning('config_schema', 'config_field', '0.9.0')
        return self._config_schema
```

on SolidDefintion.

I actually do not think we should deprecate this. `config_field` is actually more accurate because once the `config_schema` is passed in it is canonicalized to be an instance of a Field. So config_schema is not really accurate anymore.

**Comment by natekupp** [comment]
@sryza @schrockn what's the latest here?
