### ISSUE TITLE
Add lint rule for errant print statements

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2726]
@prha has boldly led us into the world of custom linting (see https://dagster.phacility.com/D3893)

We recently pushed a bug where are an errant print statement broke a user. In the leave no trace/replace your divots/fix things systematically spirit, let us add a lint rule to catch future instances of this.

This would be we would force a pylint directive for any legitimate print statement, which I think is the right tradeoff.

**Comment by sryza** [comment]
This is a good idea

**Comment by sryza** [comment]
https://dagster.phacility.com/D3905
