### ISSUE TITLE
Catch error when defining @resource without a context argument earlier

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2727]
If one defines a resource without a context argument like so:

```
@resource
def fake_pandas_metastore():
    return FakePandasMetastore()
```

<img width="1213" alt="Screenshot 2020-07-15 09 56 40" src="https://user-images.githubusercontent.com/28738937/87573272-84d73a80-c681-11ea-9cef-0ffa400854e2.png">

It doesn't not detect the lack of required context argument until runtime. We should detect this earlier like we do with @solid.

**Comment by dpeng817** [comment]
Solved by https://dagster.phacility.com/D3961.
