### ISSUE TITLE
Pipeline re-execution not working in multi repository location contexts

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2728]
I haven't not had time to truly dig in to get a proper repo, but right now in local development with multiple repos in context I cannot re-execute a pipeline run:

<img width="1488" alt="Screenshot 2020-07-15 10 00 47" src="https://user-images.githubusercontent.com/28738937/87573642-1646ac80-c682-11ea-8897-7bcfaca2563f.png">

**Comment by natekupp** [comment]
@schrockn pretty sure this has been fixed, closing—please reopen if still valid
