### ISSUE TITLE
Default output "results" in UI are not distinguished

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#273]
Currently, when you drill down into a single node, you get information about its inputs (and thus its dependencies) in the sidebar:
<img width="355" alt="screen shot 2018-11-08 at 4 14 06 pm" src="https://user-images.githubusercontent.com/427016/48235109-67f94880-e371-11e8-8558-bd3ef53d5319.png">
The `result` here is generic, and not distinguished from the `result` of any other nodes -- every output is, by default, called `result`. It would be helpful if we changed this to indicate the node from which it originated, e.g. "Depends on `subsample_august_sfo_weather`:`result`".

Similarly, although `result` is hyperlinked in this display, clicking on it simply restores the sidebar to the generic view of the pipeline as follows:
<img width="360" alt="screen shot 2018-11-08 at 4 16 29 pm" src="https://user-images.githubusercontent.com/427016/48235169-ae4ea780-e371-11e8-83ed-4581fb95182e.png">

**Comment by mgasner** [comment]
I'm still seeing this issue in dagit

**Comment by schrockn** [comment]
This looks fixed to me
[image: Screenshot 2018-11-26 14.16.02.png]

**Comment by mgasner** [comment]
Steps to reproduce:
- From the airline_demo folder, run `dagit`
- Navigate to http://127.0.0.1:3000/airline_demo_spark_ingest_pipeline/load_q2_market_data
<img width="386" alt="screen shot 2018-11-27 at 3 29 27 pm" src="https://user-images.githubusercontent.com/427016/49109669-4fd26600-f259-11e8-83f5-659216799e66.png">
- Click on `result`
<img width="369" alt="screen shot 2018-11-27 at 3 30 26 pm" src="https://user-images.githubusercontent.com/427016/49109705-64aef980-f259-11e8-9a86-0f1b6ec31198.png">

**Comment by schrockn** [comment]
Need to yarn install && yarn build
