### ISSUE TITLE
Pull in dbt integration from goodeggs

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2730]
They are not going to have the bandwidth to upstream so someone on the core should just do it on their behalf. cc: @dwallace0723 just cc'ing you so you can stay up-to-date about what is going on

**Comment by wearpants** [comment]
link to upstream please?

**Comment by sryza** [comment]
this is complete! there's now a dagster_dbt package: https://pypi.org/project/dagster-dbt/

https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dbt
