### ISSUE TITLE
Add ability to filter pipeline Runs view by repository

### ISSUE THREAD

**Issue by bengotow** [dagster-io/dagster#2734]
In the case below, the top run was actually for a pipeline of this name in another repository:

![image](https://user-images.githubusercontent.com/1037212/87716927-35723680-c775-11ea-9970-7e1d0ff732af.png)

To fix this, we need to allow the pipelineRuns query to be filtered by a PipelineSelector, not just a pipeline name. (And Pipeline Run Storage needs to keep the repo location name and repo name to make this filter possible):

![image](https://user-images.githubusercontent.com/1037212/87717044-618db780-c775-11ea-8757-b023baab9b83.png)

**Comment by hellendag** [comment]
@gibsondan Is it possible to add a repository selector to this filter?

**Comment by gibsondan** [comment]
we can absolutely add repository name and repository location name to this - one thing that we will lose if we do that is pipelines created via direct execution of the PipelineDefinition itself separate from any repository - e.g. "dagster pipeline execute" or calling execute_pipeline programatically. Not sure if that's actually a problem or not.
