### ISSUE TITLE
Dagit shows green on step with assumed failure

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#2735]
`Step multiply_the_word.compute finished without success or failure event, assuming failure.`, but the box for the step execution is green.

**Comment by alangenfeld** [comment]
This means the event store DB writes worked successfully, but the executor did not receive the event from how ever it was consuming the event stream of the step execution. What executor was in use when you saw this?

**Comment by johannkm** [comment]
Interesting. It's celery k8s, so just the same issue I'm working on now
