### ISSUE TITLE
Schedules page in dagit could show time of the most recent run

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2737]
It would be nice to see the time of the most recent run of each schedule, and the time of a given run on hover. This ask was also brought up during a user call.

<img width="1536" alt="Screen Shot 2020-07-17 at 11 37 42 AM" src="https://user-images.githubusercontent.com/6024687/87804548-05cd3800-c822-11ea-97d7-bd9328c08633.png">

**Comment by hellendag** [comment]
Closing this since I think we have enough metadata in this table to satisfy needs related to timing.
