### ISSUE TITLE
Postgre DB connection leak introduced in 0.8.7

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#2739]
See https://dagster.slack.com/archives/CCCR6P2UR/p1595267143114900?thread_ts=1594934057.091600&cid=CCCR6P2UR for details and repro instructions.

Blames to https://github.com/dagster-io/dagster/commit/90d404169d60fea714bdcd09b827c6de74c8a261 - placing a reference to the DagsterInstance in the run launcher seems to be enough to keep it from cleaning up DB connections properly.

**Comment by alangenfeld** [comment]
2 issues:
* memory cycle created by blame rev preventing `DagsterInstance` object destruction 
* the fact that we create a `LISTEN` connection on init in `PostgresEventLogStorage`, should only do that if we are actively watching any `run_id`s

**Comment by gibsondan** [comment]
first fix landed, leaving open to track second Postgres-specific fix
