### ISSUE TITLE
Dagit does not seem to re-compute whether to show "Terminate" button

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2740]
On the Pipeline Run view, it seems like "Terminate" button is computed once on initial load and not computed again. Since a PipelineRun cannot be terminated until the run has been marked as STARTED in the db, this means that if Dagit loads before the pipeline run starts and the DB is updated, then the user will not see the "Terminate" button until they refresh the page.

**Comment by bengotow** [comment]
Hey! I broke a pipeline so that it would not start and also tried inserting a delay between the starting and started states and it looks like this has been resolved by @hellendag's recent improvements to the run view! Going to close for now.
