### ISSUE TITLE
PySpark client mode job instigation not working on k8s

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2748]
See https://dagster.slack.com/archives/G014KBQDJFK/p1595511384004500?thread_ts=1595320975.002700&channel=G014KBQDJFK&message_ts=1595511384.004500

https://dagster.slack.com/archives/G014KBQDJFK/p1591178328058800

**Comment by sryza** [comment]
The challenge here is:
* The spark executors need to know where the spark driver lives
* Where the spark driver lives is determined at job launch time (by the dagster run launcher + executor)
* Nobody tells the spark executors where that ends up being

To get this to work, we would need to either:
* Have the run launcher + executor launch the step with some sort of address that can be predictable referenced, maybe using a k8s service?
* Enable the pod that a step gets launched on to be passed to the configuration of another step

**Comment by catherinewu** [comment]
re: "Have the run launcher + executor launch the step with some sort of address that can be predictable referenced, maybe using a k8s service?" -- if im understanding correctly, i think it should be straightforward to encode the spark driver location in an env var "DAGSTER_SPARK_DRIVER_LOCATION" and inject that env var into the k8s pod (kinda like "DAGSTER_CURRENT_IMAGE")?

**Comment by sryza** [comment]
@catherinewu I'm not a kubernetes expert, but to add some more context on what make this complicated:
* it's the spark executors that need to know where the SparkSession is running
* the SparkSession is responsible for launching the executor pods
* spark executors typically learn where the SparkSession is through the spark.driver.host spark property, which can be passed as configuration when starting the session and the session then passes on to the executors when starting them

so the challenge is basically for the code that's constructing the SparkSession to know what host its running on and pass that in as config

**Comment by sspaeti** [comment]
Any updates on this? This is kind of a blocker for us, and I haven't found a workaround 😢. I tried `deployMode: cluster`, but then I get `Exception: Java gateway process exited before sending its port number` as explained [here](Exception: Java gateway process exited before sending its port number).

Any ideas how others work with spark and dagster to get over this? Thanks so much.

**Comment by johannkm** [comment]
Hi @sspaeti, thanks for bringing this up again, apologies for the wait. We'll be taking a look this week

**Comment by sspaeti** [comment]
I think the last missing piece is setting the container-pod-port inside the pipeline-tag with `container_config`.
Below example works for resources, but ports are not taken. 

One guess would be that it should be replaced [here](https://github.com/dagster-io/dagster/blob/262abbfc215a607f50bb2de65879e24bd9580551/python_modules/libraries/dagster-k8s/dagster_k8s/job.py#L155), same as resources? But even better would be, that all configs you specify with that, would be routed to Kubernetes.

Conversation on Slack for reference: https://dagster.slack.com/archives/C014N0PK37E/p1602754655005400

Config: 
```{
    "container_config": {
        "resources": {
            "requests": {
                "cpu": "1",
                "memory": "1Gi"
            },
            "limits": {
                "cpu": "2",
                "memory": "2Gi"
            },
        },
        "ports": [
            {
                "name": " grpc",
                "containerPort": 3030,
                "protocol": "TCP"
            },
            {
                "name": "spark-driver",
                "containerPort": "4040",
                "protocol": "TCP"
            },
        ]
    }
}```

**Comment by chenbobby** [comment]
As @sryza noted,
> the challenge is basically for the code that's constructing the SparkSession to know what host its running on and pass that in as config

This can be resolved by using a custom `pyspark_resource` that will set the `spark.driver.host` field in the spark_conf during initialization. An example of a custom `pyspark_resource` can be [found in this gist](https://gist.github.com/chenbobby/760b3026be866834e51d530d59ab453a), which is modeled after [the default `pyspark_resource`](https://github.com/dagster-io/dagster/blob/0.9.18/python_modules/libraries/dagster-pyspark/dagster_pyspark/resources.py#L30-L41).

---

And, regarding the comment from @sspaeti about setting the container ports on the k8s pod, I have a working example below that uses pipeline definition tags.

```python
@pipeline(
    ...,
    tags={
        "dagster-k8s/config": {
            "container_config": {
                "resources": {
                    "requests": {
                        "cpu": "1",
                        "memory": "1Gi"
                    },
                    "limits": {
                        "cpu": "2",
                        "memory": "2Gi"
                    },
                },
                "ports": [
                    {
                        "name": "grpc",
                        "containerPort": 3030,
                        "protocol": "TCP"
                    },
                    {
                        "name": "sparkdriver",
                        "containerPort": 4040,
                        "protocol": "TCP",
                    },
                ],
            }
        },
    },
)
def example_pipe():
	pass
```

_Some gotchas for setting k8s config_
- The config dictionary must be defined in the `tags` field with the key `dagster-k8s/config`.
- The Python client library for k8s seemed to have an problem with non-alphanumeric characters in the `name` field. So, `"name": "spark-driver"` needed to be changed to `"name": "sparkdriver"`
