### ISSUE TITLE
Add a dagster-scaffold option for creating a self-contained package.

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#2761]
The current way that `dagster-scaffold example` initializes the boilerplate can be problematic if wanting to add additional python files to the example. The additional files won't be recognized, and a workaround is necessary to add the workspace to the path. We should add an option in dagster-scaffold for initializing an example as a self-contained module to avoid these workarounds.

**Comment by catherinewu** [comment]
closing due to https://docs.dagster.io/_apidocs/cli#

**Comment by yuhan** [comment]
idle
