### ISSUE TITLE
A strange question : The order of importing python library

### ISSUE THREAD

**Issue by ProQianXiao** [dagster-io/dagster#2767]
Hi, I am new to Dagster and I meet a strange question. I have two simple python files, **_message.py_** and _**simple_task.py**_, the content is as follows：
message.py
![image](https://user-images.githubusercontent.com/25978988/88917334-2a052c00-d29a-11ea-8e91-4e72dcb3e413.png)
simple_task.py
![image](https://user-images.githubusercontent.com/25978988/88917488-6afd4080-d29a-11ea-9077-a2248ef2c4b4.png)
and I run the simple_task.py by the commond `dagit -f simple_task.py`, it failed and the error log is follows:

> (citics) E:\PythonProject\CITIC_Schedule\dagster_task>dagit -f simple_task.py
Loading repository...
Traceback (most recent call last):
  File "d:\anaconda\envs\citics\lib\site-packages\dagster\api\utils.py", line 11, in execute_command_in_subprocess
    subprocess.check_output(parts, stderr=subprocess.STDOUT)
  File "d:\anaconda\envs\citics\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "d:\anaconda\envs\citics\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['d:\\anaconda\\envs\\citics\\python.exe', '-m', 'dagster', 'api', 'repository', 'C:\\Users\\lo\\AppData\\Local\\Temp\\tmpt7d8w7d_', 'C:\\Users\\lo\\AppData\\Local\\Temp\\tmpv9bgrg0w']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "d:\anaconda\envs\citics\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\envs\citics\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\citics\Scripts\dagit.exe\__main__.py", line 7, in <module>
  File "d:\anaconda\envs\citics\lib\site-packages\dagit\cli.py", line 197, in main
    cli(auto_envvar_prefix='DAGIT')  # pylint:disable=E1120
  File "d:\anaconda\envs\citics\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda\envs\citics\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda\envs\citics\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda\envs\citics\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda\envs\citics\lib\site-packages\dagit\cli.py", line 91, in ui
    host_dagit_ui(host, port, path_prefix, storage_fallback, port_lookup, **kwargs)
  File "d:\anaconda\envs\citics\lib\site-packages\dagit\cli.py", line 102, in host_dagit_ui
    workspace, host, port, path_prefix, storage_fallback, port_lookup
  File "d:\anaconda\envs\citics\lib\site-packages\dagit\cli.py", line 124, in host_dagit_ui_with_workspace
    app = create_app_from_workspace(workspace, instance, path_prefix)
  File "d:\anaconda\envs\citics\lib\site-packages\dagit\app.py", line 235, in create_app_from_workspace
    locations.append(PythonEnvRepositoryLocation(repository_location_handle))
  File "d:\anaconda\envs\citics\lib\site-packages\dagster\core\host_representation\repository_location.py", line 457, in __init__
    repo_list = sync_get_external_repositories(self._handle)
  File "d:\anaconda\envs\citics\lib\site-packages\dagster\api\snapshot_repository.py", line 26, in sync_get_external_repositories
    RepositoryPythonOrigin(repository_location_handle.executable_path, pointer),
  File "d:\anaconda\envs\citics\lib\site-packages\dagster\api\utils.py", line 32, in execute_unary_api_cli_command
    execute_command_in_subprocess(parts)
  File "d:\anaconda\envs\citics\lib\site-packages\dagster\api\utils.py", line 14, in execute_command_in_subprocess
    "Error when executing API command {cmd}: {output}".format(cmd=e.cmd, output=e.output)
dagster.serdes.ipc.DagsterIPCProtocolError: Error when executing API command ['d:\\anaconda\\envs\\citics\\python.exe', '-m', 'dagster', 'api', 'repository', 'C:\\Users\\lo\\AppData\\Local\\Temp\\tmpt7d8w7d_', 'C:\\Users\\lo\\AppData\\Local\\Temp\\tmpv9bgrg0w']: b'Traceback (most recent call last):\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\core\\code_pointer.py", line 104, in load_python_file\r\n    module = import_module_from_path(module_name, python_file)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\seven\\__init__.py", line 100, in import_module_from_path\r\n    spec.loader.exec_module(module)\r\n  File "<frozen importlib._bootstrap_external>", line 678, in exec_module\r\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\r\n  File "simple_task.py", line 3, in <module>\r\n    import numpy as np\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\numpy\\__init__.py", line 140, in <module>\r\n    from . import core\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\numpy\\core\\__init__.py", line 72, in <module>\r\n    from . import numeric\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\numpy\\core\\numeric.py", line 23, in <module>\r\n    from . import shape_base\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\numpy\\core\\shape_base.py", line 9, in <module>\r\n    from . import numeric as _nx\r\nImportError: cannot import name \'numeric\'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "d:\\anaconda\\envs\\citics\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\__main__.py", line 3, in <module>\r\n    main()\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\cli\\__init__.py", line 38, in main\r\n    cli(obj={})  # pylint:disable=E1123\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\click\\core.py", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\click\\core.py", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\click\\core.py", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\click\\core.py", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\click\\core.py", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\click\\core.py", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\cli\\api.py", line 109, in command\r\n    output = check.inst(fn(args), output_cls)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\cli\\api.py", line 157, in repository_snapshot_command\r\n    return external_repository_data_from_def(recon_repo.get_definition())\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\core\\definitions\\reconstructable.py", line 35, in get_definition\r\n    return repository_def_from_pointer(self.pointer)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\core\\definitions\\reconstructable.py", line 321, in repository_def_from_pointer\r\n    target = def_from_pointer(pointer)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\core\\definitions\\reconstructable.py", line 284, in def_from_pointer\r\n    target = pointer.load_target()\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\core\\code_pointer.py", line 178, in load_target\r\n    module = load_python_file(self.python_file, None)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\core\\code_pointer.py", line 119, in load_python_file\r\n    raise error\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\core\\code_pointer.py", line 95, in load_python_file\r\n    module = import_module_from_path(module_name, python_file)\r\n  File "d:\\anaconda\\envs\\citics\\lib\\site-packages\\dagster\\seven\\__init__.py", line 100, in import_module_from_path\r\n    spec.loader.exec_module(module)\r\n  File "<frozen importlib._bootstrap_external>", line 678, in exec_module\r\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\r\n  File "simple_task.py", line 2, in <module>\r\n    from message import Message\r\nModuleNotFoundError: No module named \'message\'\r\n'

It seems that the module _**message**_ could not be found.

But the weird thing is, if I change the order of importing numpy (numpy is even not used) and I set the `import numpy as np` in front of `from message import Message`, it could work. Like this:
![image](https://user-images.githubusercontent.com/25978988/88918151-93d20580-d29b-11ea-9eb3-5083a2a9d01f.png)
And I run the command again, it succeeds:
![image](https://user-images.githubusercontent.com/25978988/88918216-b6fcb500-d29b-11ea-9ffe-b2e6e3443bd0.png)
![image](https://user-images.githubusercontent.com/25978988/88918265-c1b74a00-d29b-11ea-89de-542e3e23bfb3.png)

It really confused me,  any help is greatly appreciated.

**Comment by gibsondan** [comment]
resolved over Slack / in https://dagster.phacility.com/D4049 . Thanks again!
