### ISSUE TITLE
When a pipeline has failed, but STEP_FAILURE events are missing, the steps appear to spin forever in dagit

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2770]
This can occur with a segfault, and can be reproduced with the hard_failer pipeline. We should synthetically generate STEP_FAILURE events in this case, but dagit should be robust to this case. 
<img width="1842" alt="Screen Shot 2020-08-03 at 1 22 43 PM" src="https://user-images.githubusercontent.com/427016/89209567-9464e780-d58c-11ea-8db3-766406bb8d90.png">

**Comment by alangenfeld** [comment]
I think if we get a good tool tip message on the question mark explaining the unknown state it is in that this will be a substantial improvement over where we are now

**Comment by catherinewu** [comment]
added the tooltip: https://dagster.phacility.com/D4349
<img width="1536" alt="Screen Shot 2020-09-15 at 10 21 10 PM" src="https://user-images.githubusercontent.com/6024687/93296657-810c8500-f7a4-11ea-868d-094070cc202b.png">
