### ISSUE TITLE
dagit might wait a beat for run storage db to be available

### ISSUE THREAD

**Issue by mattgiles** [dagster-io/dagster#2771]
Working with a `docker-compose.yml` that runs dagit and postgresql for run storage, I am in the habit of doing:

```shell
docker-compose up -d storage
docker-compose up
```

This is because , if I jump straight to `docker-compose up`, dagit will exit when `PostgresRunStorage` can't connect to the db immediately. Which is ~100% of the time if you're re-booting postgresql with a docker volume to data from prior runs.

Would be cool if either dagit or dagster-postgres waited a beat for the db to initialize.

**Comment by natekupp** [comment]
Thanks @mattgiles, agree we should have this - more generally, Dagit should be tolerant of transient network issues w/ the database, and stay alive even if the connection is interrupted

**Comment by natekupp** [comment]
This should now be fixed, we have DB retries in place now
