### ISSUE TITLE
Make examples manageable for demo'ing and exploring

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2776]
While our new examples hierarchy is nicer organizationally it's been a substantial regression in terms of navigating around to different example pipelines. You end up having to kill and restart dagit with different workspaces all the time, which is a huge bummer.

I believe we need a new workspace.yaml that can merge together all the pipelines reasonably. However doing this naively may result in a a *ton* of repository locations which also has its downsides. But right now it is really hard to hop around the codebase (I struggled in vain to be able to load the longitidunal_pipeline without changing code).

**Comment by natekupp** [comment]
It might be worth having a separate repo w/ examples intended for live demos / presentations vs. examples intended to showcase the full surface area of our public APIs:

1. For demos/presentations, I assume the audience is new to Dagster, and the goals should be to elegantly and systematically demonstrate the capabilities of the system, starting from "hello, world" and building towards specific use cases—ETL on AWS, ML in dagstermill, etc.
2. For user examples, I assume the user is already reasonably familiar with the fundamentals of Dagster and is trying to solve a specific problem—so the examples can be highly targeted, MVP examples of "how can I do X with Dagster?"

Definitely overlapping use cases, but I wonder if we can have a more streamlined demo/preso experience by addressing it separately. Thoughts?

**Comment by yuhan** [comment]
#2451

**Comment by yuhan** [comment]
folding this into this an internal tracker.
