### ISSUE TITLE
K8S Resource Requirements tags not applying to solid-subsets

### ISSUE THREAD

**Issue by ikendoit** [dagster-io/dagster#2792]
_Context_
From this work: https://dagster.phacility.com/D3589, 
"K8S_RESOURCE_REQUIREMENTS_KEY" tag can be used in a pipeline to set its resource-requirements config for running Pods on K8S.

_Issue_
- For triggering a full pipeline end-to-end, the resource requirements config work.
- But if we trigger a subset of solids within that pipeline, the resource requirements is not applied.

_Reproduction_
![image](https://user-images.githubusercontent.com/26758925/89667456-04c37f80-d891-11ea-89d6-568a57cbd014.png)

**Comment by schrockn** [comment]
Thanks for the report!
