### ISSUE TITLE
Would be useful to be able to mark a solid as having failed in Dagit before re-executing pipeline "from failure"

### ISSUE THREAD

**Issue by mgiles-asp** [dagster-io/dagster#2796]
And I guess, on the flip side, maybe marking failed solids as having succeeded too.

**Comment by catherinewu** [comment]
hi @mgiles-asp, could you elaborate a bit more on your use case? I'm not sure I understand, but one option might be to cancel the pipeline run (which causes all executing solids to fail), and you can re-execute from that point?

**Comment by catherinewu** [comment]
we do support re-executing arbitrary subsets of solids (not just failed solids)

going to close
