### ISSUE TITLE
After a GraphQL error when reloading a repository location, the reload button spins forever

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2798]
![Image 8-9-20 at 1 58 PM](https://user-images.githubusercontent.com/427016/89738668-7691f980-da48-11ea-852f-1b3336f65c44.jpg)

This is unfortunate because, for instance, you get a GraphQL error if there is something wrong with the repository definition (e.g., you've accidentally included a solid def instead of a pipeline def) - this easily happens in dev and it would be better if dagit went into an invalid state and the button could be used to reload when the issue was fixed. (We probably should also type these errors and display a more helpful message than the red GraphQL error popup.)

Steps to reproduce:

Load the following repository.py

```
from dagster import solid, pipeline, repository

@solid
def a_solid(_):
    ...

@pipeline
def a_pipeline():
    a_solid()

@repository
def a_repository():
    return [a_pipeline]
```

now change it so that you have instead

```
@repository
def a_repository():
    return [a_pipeline, a_solid]
```

and hit the reload button in dagit.

**Comment by schrockn** [comment]
Dup (ish) of https://github.com/dagster-io/dagster/issues/2718. We should handle repositories and repository locations that are in an unloadable state

**Comment by mgasner** [comment]
closing as a dupe
