### ISSUE TITLE
Times like 14:21 PM don't make a lot of sense

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2801]
I'd expect, like, "14:21", "14:21 EDT", "14:21 UTC-5" or "2:21 PM", but "14:21 PM" is strange. Cf. #1750 #2695 #2188 if we want to make a push to rationalize times in dagit.

**Comment by catherinewu** [comment]
adding https://github.com/dagster-io/dagster/issues/2850 to the list

**Comment by hellendag** [comment]
Considering this done, please reopen specific issues if you spot any remaining timezone display bugs.
