### ISSUE TITLE
Dagit playground can't be edited after engine error

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#2804]
Can only reproduce before 0.9.1, since the subset bug somehow triggers it. After launching the faulty pipeline run, the playground becomes un-editable. 

![ezgif-7-2f29179bf7f3](https://user-images.githubusercontent.com/22018973/89790013-56694580-daef-11ea-9023-4d9c59382a59.gif)

**Comment by hellendag** [comment]
Hasn't come up again and not reproable in current versions, closing.
