### ISSUE TITLE
Add type loader for dagster-pyspark DataFrame

### ISSUE THREAD

**Issue by flvndh** [dagster-io/dagster#2806]
Hi team!

I read the `DataFrame` type definition of `dagster-pyspark` and noticed that there is no loader. Is it on purpose?

The module could provide selectors for both the file and the table API of Spark. Something like:

```python
@dagster_type_loader(
    Selector(
        {
            "file": Permissive(...),
            "table": Permissive(...),
        }
    ),
    required_resource_keys={"pyspark"},
)
def load_spark_data_frame(context, config):
    pass
```

What do you think ?

**Comment by DavidKatz-il** [comment]
https://github.com/dagster-io/dagster/pull/2790
