### ISSUE TITLE
K8SRunLauncher should allow passing arbitrary config to jobs/pods/containers 

### ISSUE THREAD

**Issue by ikendoit** [dagster-io/dagster#2812]
Currently, K8SRunLauncher does not allow passing in custom config when creating Job/Pod/Container Kubernetes Object.
This can cause problems when users want to pass in custom annotations[1], labels or any other config to their K8S Objects. 

Ideas are being considered to implement this but needs prioritization:
https://dagster.slack.com/archives/C014N0PK37E/p1597248672084000?thread_ts=1597019607.076100&cid=C014N0PK37E

[1]: sample annotation: `cluster-autoscaler.kubernetes.io/safe-to-evict": "false"`
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node
This annotation can be used to stop Cluster-Auto scaler from evicting running dagster-pipeline pods.

**Comment by ikendoit** [comment]
Additional use case from szalai1 on Slack: https://dagster.slack.com/archives/C014N0PK37E/p1597327142088800
Node-affinity to target the pipeline-runs on the nodes with GPU power.

**Comment by szalai1** [comment]
@helloworld I see you `self-assigned` this, does that mean you are working on it? if not I can allocate time to do this, as it's a blocker for us.

### My additional thoughts and  questions 
What's the right level/way of exposure of these configurations
**Annotations**:
* I want to use it for **kube2iam**, which is a "Dagster" level thing, I want all of the jobs to have these annotations that are started by Dagster.  (`mode`s??)

**Nodeselectors**:
*  If I have solid which requires GPU, I would like to "tag" only that one.
* Contrary I might want to run whole pipelines with the same node selector (e.g. specific autoscaling groups can belong to teams)

**Comment by helloworld** [comment]
Hey @szalai1, yes – I'm currently working on this! It should come out with this Thursday's release.

> If I have solid which requires GPU, I would like to "tag" only that one.
> Contrary I might want to run whole pipelines with the same node selector (e.g. specific autoscaling groups can belong to teams)

This is a great point and you've identified the need for configuration at both the solid and pipeline level, which I plan on introducing. Just to make sure, are you using the `CeleryK8sRunLauncher`? You will need to if you want solids to run in their own pods with a unique configuration. 

A question for you: What do you expect to happen if you specify node selectors at both the pipeline and solid level? More specifically, do you expect a merge? And if there's a conflict, which one should take precedence? 

> I want to use it for kube2iam, which is a "Dagster" level thing, I want all of the jobs to have these annotations that are started by Dagster. 

I'm not sure if we'll have a solution for this soon. Until we do, I'd recommend just adding this annotation at the pipeline level for each pipeline.

**Comment by szalai1** [comment]
hey @helloworld ,
> I'm currently working on this! 
Thank you very much.

> Are you using the CeleryK8sRunLauncher? 
Not at the moment, because without `kube2iam` tag, pods cannot access S3. (specific to our setup, but probably common).

>What do you expect to happen if you specify node selectors at both the pipeline and solid level? More specifically, do you expect a merge? And if there's a conflict, which one should take precedence?
Good question. Probably pipeline level should over-write the solid level. 
As solid write, I'm **advising** something with the tag, but the end-user who writes the pipeline should be able to overwrite it. IMO. 
e.g if there is no GPU machine in the cluster, then pipeline should overwrite the node selector with `{}` and whoever wrote the solid won't know about where and how the solid will be executed. 

> I'd recommend just adding this annotation at the pipeline level for each pipeline.
That's a totally doable workaround. Thanks.

**Comment by ikendoit** [comment]
Thanks @helloworld , the release of 0.9.3 worked for me. 
Annotations was added, users were made happy! 

I will close this issue tonight unless anyone wants to keep it open.

**Comment by helloworld** [comment]
Awesome! Glad it worked.

@szalai1 I just wanted to confirm that you were successfully able to specify node-affinities. If so, we can close this issue.
