### ISSUE TITLE
Tags on PipelineDefinitions don't mix well with Dagit's tag editing

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#2814]
The tags will show up when you load the pipeline in Dagit. You can delete them in the playground, but they’ll still appear on any runs

Dagit should probably show the tags as uneditable. Alternatively should tags in PipelineDefinitions be deprecated?

**Comment by hellendag** [comment]
Definition tags are no longer editable. This was fixed by https://dagster.phacility.com/D8118.
