### ISSUE TITLE
Kubernetes documentation link in README.md is broken

### ISSUE THREAD

**Issue by AntonFriberg** [dagster-io/dagster#2816]
Hi!

The link to the kubernetes documentation in the [README.md](https://github.com/dagster-io/dagster#dagster) file points to a broken link https://docs.dagster.io/deploying/k8s . 

See screenshot below.
![image](https://user-images.githubusercontent.com/14290517/90120009-96803080-dd5a-11ea-9561-827d21901ae0.png)

**Comment by catherinewu** [comment]
Sorry, that should link to docs.dagster.io/deploying/k8s_part1 instead! fixing: https://dagster.phacility.com/D4286
