### ISSUE TITLE
Runtime config vs environment config

### ISSUE THREAD

**Issue by thedmi** [dagster-io/dagster#2822]
I'm in the process of evaluating Dagster for a distributed production setup. For this, I've created an example that demonstrates a distributed Dagster / Celery setup, see https://github.com/thedmi/dagster-celery-docker-example. All services are dockerized.

One point I'm struggling with is configuration: At pipeline runtime (e.g. through Dagit -> Playground) I want to keep the required configuration to a minimum. This will be used by data analysts, and they shouldn't care about things such as Celery broker URLs or resource definitions. However, I wasn't able to find a way to provide fixed values for a specific environment. I understand that there is the concept of presets, but they still produce unwanted infrastructure configuration in the Playground window.

How can I provide parts of the runtime config so that pipeline users don't have to worry about them?

**Comment by alangenfeld** [comment]
https://docs.dagster.io/overview/configuration#configured

This is new, but is designed to solve exactly this problem.

**Comment by thedmi** [comment]
Thanks, looks good and works, except for the S3 intermediate storage. I've opened a separate issue for that: https://github.com/dagster-io/dagster/issues/2828
