### ISSUE TITLE
S3 intermediate storage does not work with configured() mechanism

### ISSUE THREAD

**Issue by thedmi** [dagster-io/dagster#2828]
```python
from dagster_aws.s3 import s3_intermediate_storage
intermediate_storage_configured = s3_intermediate_storage.configured({'s3': {'config': {'s3_bucket': 'dagster-intermediates'}}})
```

The snipped above shows the relevant lines. When trying to load this into dagit, I get the following error:

```
AttributeError: 'IntermediateStorageDefinition' object has no attribute 'configured'
```

The same approach worked in the same code-base for a resource and an executor, so I suspect that this is a bug in the S3 intermediate storage.

I'm on Dagster 0.9.2.

**Comment by ajnadel** [comment]
Hey @thedmi, sorry this is happening. I'm having trouble reproducing the issue locally. Can you paste the output of `$ pip freeze` so I can get a sense of what your dagster installation on pip looks like?
