### ISSUE TITLE
ERROR: running tox on windows

### ISSUE THREAD

**Issue by DavidKatz-il** [dagster-io/dagster#2831]
When running tox (e.g `tox -e py37` in 'dagster\python_modules\libraries\dagster-pyspark')
It failed with the following error
```
ERROR: InvocationError for command /bin/bash -c '! pip list --exclude-editable | grep -e dagster -e dagit' (exited with code 2)
```
After putting this line in a comment, it still failed with the following error
```
ERROR: InvocationError for command could not find executable echo
```
It's run successfully when putting those two lines in a comment
```
  !windows: /bin/bash -c '! pip list --exclude-editable | grep -e dagster -e dagit'
  echo -e "--- \033[0;32m:pytest: Running tox tests\033[0m"
```

**Comment by DavidKatz-il** [comment]
After adding this line into the tox.ini file, it runs successfully. (It's still showing the error)
```
[testenv]
ignore_errors = true
```

**Comment by sryza** [comment]
Closing as stale
