### ISSUE TITLE
Document how to trigger stuff via HTTP

### ISSUE THREAD

**Issue by hnykda** [dagster-io/dagster#2832]
Hi,

I really like dagster and dagit. What I am failing to find out is how it can be operated via something like HTTP (REST or graphql). Is it not possible to trigger workflows in some other way than from Dagit or via CLI? We would love to integrate Dagster with our inhouse pipeline tooling operated by non-technician, and therefore Dagit is an overkill for them, so this would be useful.

I know there is http://localhost:3000/graphql and its documentation - if that's supposed to be used, then maybe just a note _somewhere_ more prominently would be handy (I haven't found it). Anyway, when I try to go there and click on "Query Variables", docs nor schema loads for me:
![image](https://user-images.githubusercontent.com/2741256/90650184-d902ab00-e23b-11ea-8c1f-d2f7a21760b7.png)
am I doing something wrong? It seems that when accessing `/graphql` endpoint, the whole server freezes (as then not even the localhost:3000 loads which it does if I access it _before_ opening /graphql)

**Comment by alangenfeld** [comment]
Yeah agree it needs to get documented, and thanks for the bug report for graphql playground not loading.

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D4231
https://dagster.phacility.com/D4224
