### ISSUE TITLE
Re-executing subsets from dagit is a little counter-intuitive

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2848]
You need to select the subset again -- othewise, if you hit "re-execute whole pipeline" the entire pipeline will re-execute instead of the subset you just executed.

**Comment by yuhan** [comment]
related #2858
re-execution will always have the same solid_selection -- meaning when "re-execute full pipeline" where the root pipeline is a subset (solid) of a pipeline, the whole run group will run on the same *solid subset*

the selection query in the run group UI is the step query not solid query, which is confusing.
