### ISSUE TITLE
Confusing error message when default pickling for intermediate storage fails

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2855]
repro:

```
from dagster import (
    DagsterInstance,
    Output,
    Nothing,
    execute_pipeline,
    pipeline,
    reconstructable,
    solid,
)


@solid
def nothing_solid(_):
    yield Output(Nothing)


@pipeline
def repro():
    nothing_solid()


if __name__ == "__main__":
    execute_pipeline(
        reconstructable(repro),
        run_config={"execution": {"multiprocess": {}}, "storage": {"filesystem": {}}},
        instance=DagsterInstance.get(),
    )

```

**Comment by alangenfeld** [comment]
What's the context for this? Do you think we should try to have a better error for when some one uses a `DagsterType` in an `Output` ?

**Comment by alangenfeld** [comment]
for reference the issue is `AttributeError: Can't pickle local object 'NewType.<locals>.new_type'` . All of these will fail the same way https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/builtins.py#L7-L11

**Comment by mgasner** [comment]
i think we probably need better error messaging for these serialization failures with multiprocessing. it's very unclear to the user how to recover from this.

**Comment by alangenfeld** [comment]
Alright yep that makes sense. This is from intermediate storage being filesystem, not the multiproc executor, and will happen with all storages that are not just in-memory. 

Full stack trace for reference:
```
AttributeError: Can't pickle local object 'NewType.<locals>.new_type'

  File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/core/execution/plan/execute_plan.py", line 210, in _dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/core/execution/plan/execute_step.py", line 273, in core_dagster_event_sequence_for_step
    for evt in _create_step_events_for_output(step_context, user_event):
  File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/core/execution/plan/execute_step.py", line 303, in _create_step_events_for_output
    for evt in _set_intermediates(step_context, step_output, step_output_handle, output):
  File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/core/execution/plan/execute_step.py", line 311, in _set_intermediates
    res = step_context.intermediate_storage.set_intermediate(
  File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/core/storage/intermediate_storage.py", line 181, in set_intermediate
    return self.set_intermediate_object(dagster_type, step_output_handle, value)
  File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/core/storage/intermediate_storage.py", line 154, in set_intermediate_object
    return self.object_store.set_object(
  File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/core/storage/object_store.py", line 127, in set_object
    serialization_strategy.serialize_to_file(obj, key)
  File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/core/types/marshal.py", line 56, in serialize_to_file
    return self.serialize(value, write_obj)
  File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/core/types/marshal.py", line 70, in serialize
    pickle.dump(value, write_file_obj, PICKLE_PROTOCOL)
```

**Comment by sryza** [comment]
A couple things that might make sense to do here:
* Add an event called something like AssetStoreFailure, IntermediateStoreFailure, OutputStoreFailure, or SetAssetFailure to make it clear that this is happening while trying to store an asset, as well as indicating which step it is and what AssetStore is being used.  Users are likely to encounter this error because they used the wrong AssetStore.
* Maybe wrap the pickle call in a try/catch and re-raise with a more informative message like "Error while trying to pickle object".

Do you have any thoughts on this @yuhan ?

**Comment by yuhan** [comment]
Wrapping the pickle call sounds good and an easy fix to this problem. Option 1 could be a next step as we are consolidating asset store and object store (the ones intermediateStorage uses).

**Comment by catherinewu** [comment]
another user reported getting “OSError: [Errno 22] Invalid argument” from the same line as [above stack trace](https://github.com/dagster-io/dagster/issues/2855#issuecomment-679235075) since the user's output was several GB. It was not clear that the resolution was to configure a different intermediate storage

**Comment by yuhan** [comment]
Introduced a new error type `DagsterObjectStoreError` to capture errors during intermediate object store get and set.

updated the error message to show more details:
![image](https://user-images.githubusercontent.com/4531914/98611269-75ba6f00-22a6-11eb-9e62-4c1680adc54a.png)
