### ISSUE TITLE
Default to first provided storage option when it requires no config

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#2857]
## Problem Statement

Given an intermediate storage definition like so:
```python
@intermediate_storage(name='my_intermediate_storage', config_schema=None)
def my_intermediate_storage(_):
    # blah blah
@pipeline(mode_defs=[ModeDefinition(intermediate_storage_defs=[my_intermediate_storage])])
def my_pipeline()
    # blah blah
```

In order to get this pipeline to work, I will need to provide the following configuration:
```
intermediate_storage:
    my_intermediate_storage:
```
It is onerous to require this run configuration, as the user isn't providing any actual information. 

**In cases where storage options are provided that don't require run configurations, we shouldn't require run configuration.**

## Solution

To solve this, we can provide a mechanism for selecting a default storage option. Since the end goal is simplicity for users, we'll keep it to the simple strategy of choosing the first in the list of provided storage definitions. If the selected option does not require any additional configuration, the user will not have to provide any configuration for storage. 

Now, given the same intermediate storage definition as the earlier example, no configuration would be required. 

Note that if the selected intermediate storage definition has required configuration, the system will still require configuration for storage.

**Comment by schrockn** [comment]
Makes sense 👍🏻

**Comment by dpeng817** [comment]
Resolved by https://dagster.phacility.com/D4178
