### ISSUE TITLE
dagster 27-windows-core_tests frequently timing out

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#2859]
Sample failure run: https://dev.azure.com/elementl/dagster/_build/results?buildId=8992&view=logs&j=ece613e7-a587-5fb3-ffe3-c12a053c4e5c

No smoking guns in the test run, need to do a bit more investigation but it seems like everything is just overall slower

Weirdly, other test runs in master around the same time finish in less than half the time: https://dev.azure.com/elementl/dagster/_build/results?buildId=8994&view=results

**Comment by natekupp** [comment]
@gibsondan is this still an issue?

**Comment by catherinewu** [comment]
closing bc python2 is deprecated
