### ISSUE TITLE
@schedule vs. @daily_schedule naming is confusing wrt partitioning

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#2860]
`@schedule` accepts a cron expression.  When I see `@daily_schedule`, I expect that it's a convenience decorator over `@schedule` that makes it easy to make daily schedules if you don't know cron syntax.

In fact `@daily_schedule` creates an underlying partition set and passes the date partition to the decorated function, while `@schedule` is a simple cron schedule that executes whenever the cron string is satisfied.

One solution would be to rename `@daily_schedule` to `@daily_partitioned_schedule`.

**Comment by gibsondan** [comment]
https://dagster.phacility.com/D4788 deprecates @schedule (and replaces it with @cron_schedule which is cron-based but also partitions), that may partially address this?

**Comment by sryza** [comment]
@gibsondan does this mean that now all (non-deprecated) schedules are partitioned?

**Comment by gibsondan** [comment]
It does!

**Comment by sryza** [comment]
That strikes me as a little weird.  Maybe it's just the naming?  What does it mean to have a partitioned schedule if none of the underlying data is partitioned?  E.g. in the case where someone has a schedule that drops and recreates a table daily.

**Comment by gibsondan** [comment]
Yeah, it's a fair point - it's really defining the set of instigations that you want the scheduler and/or backfills to be able to run on (and for a table like the one you mention, the range of 'partitions' should really only be the most recent day I think?). Very relevant to our discussion about backfills and sensors on Friday.

**Comment by yuhan** [comment]
we moved daily_schedule to daily_partitioned_config. here's the migration guide: https://docs.dagster.io/guides/dagster/graph_job_op#partition-schedules
