### ISSUE TITLE
Verbosity of default stdout logger makes it tough to find relevant information

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#2862]
```
2020-08-19 11:54:23 - dagster - INFO - system - 3d7c3d83-d646-45ea-ac9a-00a5fcba83ec - Dependencies for step make_daily_temperature_highs.compute failed: ['make_weather_samples.compute']. Not executing.
               solid = "make_daily_temperature_highs"
    solid_definition = "make_daily_temperature_highs"
            step_key = "make_daily_temperature_highs.compute"
2020-08-19 11:54:23 - dagster - DEBUG - simple_pyspark_sfo_weather_pipeline - 3d7c3d83-d646-45ea-ac9a-00a5fcba83ec - STEP_SKIPPED - Skipped execution of step "make_daily_temperature_highs.compute".
                 pid = 18016
               solid = "make_daily_temperature_highs"
    solid_definition = "make_daily_temperature_highs"
            step_key = "make_daily_temperature_highs.compute"
```

Each log line results in 5 lines of output.  The step name is repeated 4 different times.

I've found that all this makes it tough to find relevant information when developing on the command line.

**Comment by catherinewu** [comment]
@sryza thoughts on controlling the verbosity via cli option like `dagster pipeline execute ... --verbose` or `dagster pipeline execute ... --terse` or are you thinking of something more sophisticated where you can filter for the types of events you want to see in stdout?

**Comment by sryza** [comment]
My thinking was that we would just change the default to be more terse - i.e. I suspect that we can find a level of verbosity that works well for most people.  If users complain, we could add a verbose mode.  Thoughts?

**Comment by natekupp** [comment]
This was fixed by https://dagster.phacility.com/D4484
