### ISSUE TITLE
Test coverage for Helm charts

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2863]
There are some areas of the helm chart that lack test coverage. For example, setting config source on the run launcher (https://dagster.phacility.com/D4027)

**Comment by catherinewu** [comment]
https://github.com/dagster-io/dagster/issues/2671

**Comment by catherinewu** [comment]
`add test coverage for "env_froms"` https://github.com/dagster-io/dagster/issues/2155

**Comment by catherinewu** [comment]
https://github.com/dagster-io/dagster/issues/3370

**Comment by alangenfeld** [comment]
@rexledesma

**Comment by rexledesma** [comment]
This is vague - given the introduction of pytest template testing in our Helm chart, we close this and open up more scoped issues if anything pops up.
