### ISSUE TITLE
Consider coercing to string in the loggers

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2864]
Does it really make sense for, e.g., `context.log.info(len([]))` to crash a pipeline?

**Comment by rexledesma** [comment]
Should be resolved by https://github.com/dagster-io/dagster/issues/4572, since `__str__` will automatically be called on these objects passed to our `logging` compliant logger. See https://docs.python.org/3/howto/logging.html#using-arbitrary-objects-as-messages for details.
