### ISSUE TITLE
Inappropriate Pipeline Snapshot switching

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2867]
For some reason when I am playing with the longitudinal pipeline and running backfills and schedules. When a run kicks off and you click on the pipeline, it claims that it is a snapshot, but it should be the same.

Zipped file uploaded

[Screen Recording 2020-08-27 at 9.52.11 PM.zip](https://github.com/dagster-io/dagster/files/5140055/Screen.Recording.2020-08-27.at.9.52.11.PM.zip)

**Comment by hellendag** [comment]
Fixed this the other day.
