### ISSUE TITLE
[dagit] make runs page able to load without querying event DB

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2870]
Currently we query the event DB to get the start time and and end time for what we display in the last column in the runs table. We should change either what we display or how we fetch the times to remove the dependence on the event DB for showing the run details.

**Comment by alangenfeld** [comment]
One potential solution is to add a `PersistedPipelineRun` object that wraps `PipelineRun` and includes the updated & created time columns we have in the DB and is returned from the get_runs methods we currently have.

**Comment by hellendag** [comment]
Moving to Core since this doesn't seem like something that can be fixed client-side.

**Comment by alangenfeld** [comment]
resolved with addition of `RunRecord` and FE changes to leverage
