### ISSUE TITLE
Versioned solids, resources, and loaders

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#2871]
## Motivation

If, when Dagster stores a result, it can store information to uniquely identify the computation that produced it, it can compare that information with similar information for unexecuted computations to determine whether execution would produce a new result.

### Intended Uses

**General memoized re-execution -** When I’m executing a pipeline, if a step would produce a result that’s identical to the result produced by a step in a previous run, I’d like to use the result from the step as the input to subsequent steps.

**Memoized development -** When I’m iterating on a pipeline in development, I want to avoid manually keeping track of which steps I need to re-run after I make a change.

**Version-based backfills -** When I update code, data, or configuration that an asset depends on, I want to automatically backfill the asset to reflect the change.

### Where might versions come from?

**Versioning definitions:**

* Have users explicitly assign versions to computations.
* Let users define a code organization scheme that determines which source files and directories each computation definition can depend on.  Then a hash all the contents of these files and directories forms a unique identifier for the computation.
* Have users serialize representations of their computation at definition time - e.g. SQL statements, PySpark logical plans, Numba llvmlite, TensorFlow saved models, or JAX HLOs.  Then hash those.

**Versioning external inputs:**

* Many filesystems and databases enable checking the last time that a table was modified.
* Many object stores enable checking the last time that a key was updated.
* Streaming systems like Kafka enable checking whether new data has arrived.
* Hash the object itself.

## Version relationships

* The version of an output comes from the step that generates it
* The version of a step comes from
    * The solid definition
    * The version of the solid’s processed run configuration
    * The version of all inputs
    * The version of all resources
* The version of a resource comes from
    * The resource definition
    * The resource’s processed run configuration
* The version of an input comes from
    * If it’s an externally loaded input, the version of data its loaded from
    * If its a step input, the version of the upstream step

### Solids: add a version attr SolidDefinition

Hardcoding a version for a solid definition:
```
@solid(version='5')
def my_solid(context):
    '''Do stuff'''
```
Writing a decorator to compute versions based on the SQL transform:
```
def versioned_sql_solid(sql_statement, **kwargs):
    version = hashlib.sha1(sql_statement.encode('utf-8')).hexdigest()
    @solid(**kwargs, version=version)
    def execute_sql_solid(context, **kwargs):
        context.resources.db_connection.execute(sql_statement)

my_sql_solid = versioned_sql_solid('create table the_table as select * from ...')
```
Setting a version based on the contents of relevant files:
```
def file_hash(file_path):
    with open(file_path, 'rb') as f:
        return hashlib.sha1(f.read())
        
def combine_hashes(*hash_list):
    return hashlib.sha1(''.join(hash_list))
    
@solid(version=combine_hashes(file_hash(__file__), file_hash('requirements.txt')))
def my_solid(context):
    '''Do stuff'''
```
### Resources: add a version attr to ResourceDefinition

Versioning a resource definition:
```
@resource(version='5')
def my_resource(init_context):
    '''Build the resource'''
```
Solid configuration: add a config_version next to config

In most cases, we can compute the version of a config subtree by hashing some normalized form of it - a simple way would be the string repr of a stably-sorted copy of the config dict.

In some rare cases, a user might need to hardcode the version of a config.  E.g. perhaps they removed a vestigial config property that was having no effect, and they want to avoid dirtying their pipelines.  They could do:

```
solids
  my_solid:
    config_version: 5
    config:
        ...
```

We probably shouldn’t spend time implementing this until someone requests it.

### Composite solids: no changes required

Composite solids don’t have versions.  Instead, the versions of solids in the flattened DAG are used.  When a composite solid involves a config-mapping function, it’s taken into account into the versioning of relevant steps by using its output as the processed run config for the step.

### Configured solids and resources: no changes required

Configured solids and resources don’t have versions.  Instead, versions of the inner definitions are used.  When a configured solid or resource involves a config-mapping function, the function is taken into account into the versioning of relevant objects by using its output as the processed run config for the object.

### Dagster type loaders: add version attr and an external_version_fn attr to DagsterTypeLoader

The version attr refers to the version of the loading code, and the external_version_fn refers to the version of the input that's being loaded.

For modeling the versions of external inputs to pipelines.  Unlike the static version attributes on definitions in the rest of the proposal, we use a function here to reflect that the versions of external inputs depend can depend on when we query them.

A risk worth noting is race conditions - we might ascertain the version of an external input, and then it might change before we have the chance to load it.  It’s tough to address this in the general case.

```
def version_from_last_update_time(context, config):
    file_path = config['file_path']
    return str(os.path.getmtime(file_path))
    

@dagster_type_loader(version='1.0', external_version_fn=version_from_last_update_time, config_schema={'file_path': str})
def my_loader(context, config):
    '''Load stuff'''
```

**Comment by alangenfeld** [comment]
I think this makes sense, tried to come up with some questions to flesh things out more:

Assuming that `version` is an optional argument on `SolidDefinition`, do I get any utility if I only have some solids marked with their version or is it all or nothing? How does a pipeline express what level of version-awareness it has?

Should this proposal include a related API on `PipelineDefinition` to enforce that everything has marked `version` that needs to in order to unlock the full memoization features?

If I am using some library solid definition that doesn't set version, what can I do?

**Comment by sryza** [comment]
@alangenfeld - thanks for the thoughts and questions.

> Assuming that version is an optional argument on SolidDefinition, do I get any utility if I only have some solids marked with their version or is it all or nothing? How does a pipeline express what level of version-awareness it has?

I think any unversioned solids ruin versioning for all downstream steps - that doesn't mean they necessarily need to ruin things for the whole pipeline.  Maybe a pipeline has a step at the end that sends a bunch of emails, and it doesn't make sense to version it because it's not even idempotent.  For someone making changes to the earlier part of the pipeline, it could still be useful to execute a versioned subselection of the pipeline and use the versioning to avoid re-executing steps with outputs from prior runs.  Thoughts?

> Should this proposal include a related API on PipelineDefinition to enforce that everything has marked version that needs to in order to unlock the full memoization features?

If what I wrote above holds true, my opinion would be that we don't need an API like that.  I do think we need to provide tools that make it easy for users to understand what subset of a pipeline they would be re-executing and why.

> If I am using some library solid definition that doesn't set version, what can I do?

I think something like the following would work.  We could maybe provide a utility to make it easier?
```
from some_library import not_versioned_solid
import some_library

my_versioned_solid = SolidDefinition(
  version=some_library.__version__,
  name=not_versioned_solid.name,
  compute_fn=not_versioned_solid.compute_fn,
  # and so on with all the solid attrs
```

**Comment by alangenfeld** [comment]
>  Maybe a pipeline has a step at the end that sends a bunch of emails, and it doesn't make sense to version it because it's not even idempotent. For someone making changes to the earlier part of the pipeline, it could still be useful to execute a versioned subselection of the pipeline and use the versioning to avoid re-executing steps with outputs from prior runs. Thoughts?

Ya I think thats a good argument against pipeline as the bounding for enforcement, but I still think it would be useful to be able to assert for some boundary that all the versioning information is present. If I become operationally dependent on the memoization behavior, I want to catch an error of a missing `version` attr as early in the process as possible.

**Comment by sryza** [comment]
Superseded by this discussion: https://github.com/dagster-io/dagster/discussions/2904
