### ISSUE TITLE
Remove deprecated root-level type options for loading/materializing Dask DataFrames

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#2872]
The root-level config options for specifying file types to load/materialize Dask DataFrames were deprecated in `0.9.x` in favour of the same keys under the `read`/`to` keys, respectively. This frees up the type configs for additional options.

### Affected Code Files

* python_modules/libraries/dagster-dask/dagster_dask/data_frame.py
* python_modules/libraries/dagster-dask/dagster_dask_tests/test_data_frame.py

**Comment by catherinewu** [comment]
Hi @kinghuang -- thanks for shipping #2821 ! Could we mark this issue as closed, or is there still outstanding items? Thanks again for your contributions 👍

**Comment by kinghuang** [comment]
Can this be targeted for 0.11?

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D6954
