### ISSUE TITLE
Verify that dagster deployments are all on compatible versions

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#2876]
GRPC calls and celery tasks could include the sender's dagster version, to be verified on the other side. It's easy for images to be out of sync and can be hard to diagnose.

**Comment by alangenfeld** [comment]
for grpc this could pair well with moving to a model where we hold the channel open instead of re-opening it for each request, that would allow us to not have to version handshake on each call but just on channel establishment

**Comment by johannkm** [comment]
@dpeng817 added backcompat testing
