### ISSUE TITLE
dagster-dbt missing license, attrs dependency

### ISSUE THREAD

**Issue by bollwyvl** [dagster-io/dagster#2881]
Congratulations on the release!

Over on conda-forge, I missed 0.9.4, and am catching up with 0.9.5. 

I noticed the once-and-future dagster-dbt is missing
- a LICENSE
- an `install_requires` for `attrs`

https://github.com/conda-forge/dagster-feedstock/pull/63

Will proceed with packaging the dagster license, but seems like good things to fix!

**Comment by bollwyvl** [comment]
Still appears to be an issue in subsequent releases, including 0.9.9...

**Comment by alangenfeld** [comment]
sorry about that, should be fixed for next release https://dagster.phacility.com/D4489

**Comment by bollwyvl** [comment]
Thanks!
