### ISSUE TITLE
Start the watcher thread in `PostgresEventWatcher` on-demand?

### ISSUE THREAD

**Issue by alirazeen** [dagster-io/dagster#2885]
Does it make sense to update the `PostgresEventWatcher` to start its watcher thread only when `PostgresEventWatcher.watch_run()` has been called at least once? 

From my understanding of the code (Dagster 0.8.2), it looks like any process started by the `CliApiRunLauncher` will eventually start the watcher thread if the dagster instance uses a `PostgresEventLogStorage`. Consequently, they end up opening a connection to the database to listen for events even though they don't actually use these events (because that process never calls `watch_run()`). Since this connection does not end until the pipeline eventually completes, it has the potential to become a bottleneck, especially in deployments where there are a lot of pipeline instances running concurrently, or when pipelines take a lot of time to complete, or when dagster is used in conjunction with connection poolers such as `pgbouncer`.

 From my experimentation and code grepping, it looks like the most relevant use of the event watcher is by the `PipelineRunLogsSubscription` GraphQL API. The process launched by the `CliApiRunLauncher` doesn't use that API. Assuming my claims are right, maybe there's an opportunity to mitigate the bottleneck by starting the watcher thread on demand?

**Comment by alangenfeld** [comment]
yep you are right, the DB connection should only be established on-demand
