### ISSUE TITLE
Dagit pipeline run view: Engine event of type function flashes on hover + click

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2892]
https://www.loom.com/share/41acf7e9e0224073b50266e89cf16aa8

**Comment by catherinewu** [comment]
https://www.loom.com/share/150556bf1721452db83399ef1d8599b3

**Comment by catherinewu** [comment]
This seems to fix it for the second video: https://github.com/palantir/blueprint/issues/4019

**Comment by hellendag** [comment]
@catherinewu does this still happen?

**Comment by hellendag** [comment]
I'm not aware of this still being an issue and I'm not sure of repro steps -- please reopen if it is still broken.
