### ISSUE TITLE
[grpc] termination issues

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2906]
I was attempting to terminate a solid that uses `time.sleep` in a loop and the termination failed to take effect until this happened:

> [DagsterApiServer] Pipeline execution process for 60fa9a14-b347-4770-9454-d5644787b55a killed after failing to terminate
> This pipeline run has been marked as failed from outside the execution context

I thought the scheme we were using would allow for the termination to work even in sleep. Either way, `can_terminate` should become false once the "killed after failing to terminate" timer is started.

**Comment by gibsondan** [comment]
Could you paste the exact solid?

**Comment by alangenfeld** [comment]
```

@solid(
    config_schema={
        "job_submit_config": [Permissive({"jobDefinition": str, "jobQueue": str, "jobName": str})],
        "reporting": get_reporting_config_schema(),
    },
    required_resource_keys={"aws_batch"},
    tags={"kind": "aws_batch"},
    input_defs=[InputDefinition("on_complete", Nothing)],
)
def aws_batch_solid(context):
    region = "us-west-1"  # should come from config
    submit_response = context.resources.aws_batch.submit_job(
        **context.solid_config["job_submit_config"][0]  # revisit this [0]
    )
    # context.log.info(str(submit_response))
    job_name = submit_response["jobName"]
    job_id = submit_response["jobId"]

    while True:
        time.sleep(10)  # config-ify
        status_response = context.resources.aws_batch.describe_jobs(jobs=[job_id])
        job = status_response["jobs"][-1]
        context.log.info("[aws batch] polling {} status: {}".format(job_id, job["status"]))
        if job["status"] == "SUCCEEDED":
            return
        elif job["status"] == "FAILED":
            raise Failure(
                "Job {} ({}) Failed!".format(job_name, job_id),
                metadata_entries=[
                    EventMetadataEntry.url(
                        url="https://console.aws.amazon.com/cloudwatch/home?region={region}#logEventViewer:group=/aws/batch/job;stream={log_stream_name}".format(
                            region=region, log_stream_name=job["container"]["logStreamName"]
                        ),
                        label="logs",
                    )
                ],
            )
```

**Comment by gibsondan** [comment]
A stack trace from dagit while this was going on would be super helpful (in particular, knowing the stack trace of the KeyboardInterrupt). I think if it actually threw in the sleep() it should have worked - are you able to consistently repro this?

My best guess right now is that https://github.com/dagster-io/dagster/issues/2919 would also cover this, but I'm not positive, that only would make sense if the interrupt was caught somewhere else that we don't handle well.

**Comment by gibsondan** [comment]
Oh, that's also super surprising if can_terminate was returning True after this happened.

The code removing it from the list that's checked in can_terminate is here: https://dagster.phacility.com/source/dagster/browse/master/python_modules/dagster/dagster/grpc/server.py$247-279

**Comment by gibsondan** [comment]
Oh, I see, you said after the timer started. Very fair point.
