### ISSUE TITLE
Dagster / K8s / Celery: Add debug cli tool

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2922]
We should add a debug cli tool that aggregates relevant logs from all services (celery worker, run master pod, step job pods, dagit, versioning info, etc) so that users can run a single command and share a dump of all their logs with us when users run into unexpected issues.

**Comment by helloworld** [comment]
Would this be a wrapper over kubectl?

**Comment by catherinewu** [comment]
i think it would use the kubernetes python client, which is a "wrapper" over kubectl

**Comment by natekupp** [comment]
rather than a separate tool, perhaps this could be built into the system? it'd be nice if there was a "download logs" button in Dagit that does this

**Comment by johannkm** [comment]
Alex's dagit-debug tool covers some of the use cases for this, but there's definitely cases where you might still want the raw logs, plus I don't think we get any versioning info.

**Comment by johannkm** [comment]
Run monitoring can expand to cover surfacing logs here (except celery worker logs)
