### ISSUE TITLE
[dagit] showing historical pipeline when snapshot id matches current live pipeline

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2923]
I believe we do not do a good job of realizing when we are looking at a "historical" run that it matches the snapshot id of a "live" pipeline definition.

Relatedly - we should probably show a context menu to disambiuate if you have multiple matches, such as loading the same pipeline in different repository locations (virtual envs / docker images)

**Comment by hellendag** [comment]
Closing this issue, since the snapshot banner should now only appear for snapshots. Opened the other issue to discuss the second point.
