### ISSUE TITLE
Intermittent s3 / botocore errors

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2926]
While running the "large_pipeline_celery" on k8s at a 5 minute frequency in a cluster with 10 nodes, I get "botocore.exceptions.NoCredentialsError: Unable to locate credentials" about 1 in every 10 pipelines. Retrying the pipeline does result in success. 

Screenshot:
<img width="1536" alt="Screen Shot 2020-09-17 at 7 39 25 PM" src="https://user-images.githubusercontent.com/6024687/93549161-92c56800-f91d-11ea-8f52-19abef284a5f.png">

Stack trace: 
dagster.core.errors.DagsterSubprocessError: During celery execution errors occurred in workers:
[outer.layer_0_node_1.layer_1_node_4.compute]: (DagsterK8sError) - dagster_k8s.client.DagsterK8sError: Encountered failed job pods with status: {'active': None,
'completion_time': None,
'conditions': [{'last_probe_time': datetime.datetime(2020, 9, 18, 1, 51, 5, tzinfo=tzlocal()),
'last_transition_time': datetime.datetime(2020, 9, 18, 1, 51, 5, tzinfo=tzlocal()),
'message': 'Job has reached the specified backoff limit',
'reason': 'BackoffLimitExceeded',
'status': 'True',
'type': 'Failed'}],
'failed': 1,
'start_time': datetime.datetime(2020, 9, 18, 1, 50, 55, tzinfo=tzlocal()),
'succeeded': None}, and logs: {'dagster-job-069561af113f1ca3dfb5d1b4a4ee9746-ztmdn': '/modules/dagster/dagster/core/definitions/mode.py:65: UserWarning: system_storage_defs are deprecated and will be removed in 0.10.0 and should be replaced with intermediate_storage_defs for intermediates and resource_defs for files\n "system_storage_defs are deprecated and will be removed in 0.10.0 "\n2020-09-18 01:51:01 - dagster - DEBUG - large_pipeline_celery - ffe08a60-d18c-45aa-bdeb-82cf4eb4cea0 - ENGINE_EVENT - Starting initialization of resources [s3].\ndagster/schedule_name = "frequent_large_grpc_pipe"\n event_specific_data = {"error": null, "marker_end": null, "marker_start": "resources", "metadata_entries": []}\n pid = 1\n solid = "layer_1_node_4"\n solid_definition = "leaf_node"\n step_key = "outer.layer_0_node_1.layer_1_node_4.compute"\n2020-09-18 01:51:03 - dagster - DEBUG - large_pipeline_celery - ffe08a60-d18c-45aa-bdeb-82cf4eb4cea0 - ENGINE_EVENT - Finished initialization of resources [s3].\ndagster/schedule_name = "frequent_large_grpc_pipe"\n event_specific_data = {"error": null, "marker_end": "resources", "marker_start": null, "metadata_entries": [["s3", "Initialized in 2.32s", ["botocore.client", "S3"]]]}\n pid = 1\n solid = "layer_1_node_4"\n solid_definition = "leaf_node"\n step_key = "outer.layer_0_node_1.layer_1_node_4.compute"\nTraceback (most recent call last):\n File "/usr/local/bin/dagster", line 33, in <module>\n sys.exit(load_entry_point(\'dagster\', \'console_scripts\', \'dagster\')())\n File "/modules/dagster/dagster/cli/__init__.py", line 38, in main\n cli(obj={}) # pylint:disable=E1123\n File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__\n return self.main(*args, **kwargs)\n File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main\n rv = self.invoke(ctx)\n File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke\n return _process_result(sub_ctx.command.invoke(sub_ctx))\n File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke\n return _process_result(sub_ctx.command.invoke(sub_ctx))\n File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke\n return ctx.invoke(self.callback, **ctx.params)\n File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke\n return callback(*args, **kwargs)\n File "/modules/dagster/dagster/cli/api.py", line 426, in execute_step_with_structured_logs_command\n execution_plan, pipeline_run, instance, run_config=args.run_config, retries=retries,\n File "/modules/dagster/dagster/core/execution/api.py", line 716, in __iter__\n for event in self.execution_context_manager.prepare_context():\n File "/modules/dagster/dagster/utils/__init__.py", line 416, in generate_setup_events\n obj = next(self.generator)\n File "/modules/dagster/dagster/core/execution/context_creation_pipeline.py", line 249, in event_generator\n context_creation_data, system_storage_data, scoped_resources_builder\n File "/modules/dagster/dagster/core/execution/context_creation_pipeline.py", line 421, in create_system_storage_data\n context_creation_data.system_storage_def.required_resource_keys,\n File "/modules/dagster/dagster/core/execution/context_creation_pipeline.py", line 46, in construct_system_storage_data\n return storage_init_context.system_storage_def.system_storage_creation_fn(storage_init_context)\n File "/modules/dagster-aws/dagster_aws/s3/system_storage.py", line 128, in s3_system_storage\n type_storage_plugin_registry=init_context.type_storage_plugin_registry,\n File "/modules/dagster-aws/dagster_aws/s3/intermediate_storage.py", line 21, in __init__\n object_store = S3ObjectStore(s3_bucket, s3_session=s3_session)\n File "/modules/dagster-aws/dagster_aws/s3/object_store.py", line 17, in __init__\n self.s3.head_bucket(Bucket=bucket)\n File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call\n return self._make_api_call(operation_name, kwargs)\n File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 622, in _make_api_call\n operation_model, request_dict, request_context)\n File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 641, in _make_request\n return self._endpoint.make_request(operation_model, request_dict)\n File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request\n return self._send_request(request_dict, operation_model)\n File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request\n request = self.create_request(request_dict, operation_model)\n File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request\n operation_name=operation_model.name)\n File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit\n return self._emitter.emit(aliased_event_name, **kwargs)\n File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit\n return self._emit(event_name, kwargs)\n File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit\n response = handler(**kwargs)\n File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler\n return self.sign(operation_name, request)\n File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 160, in sign\n auth.add_auth(request)\n File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 357, in add_auth\n raise NoCredentialsError\nbotocore.exceptions.NoCredentialsError: Unable to locate credentials\n'}

Stack Trace:
File "/modules/dagster-celery/dagster_celery/core_execution_loop.py", line 66, in core_celery_execution_loop
step_events = result.get()
File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 226, in get
self.maybe_throw(callback=callback)
File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 342, in maybe_throw
self.throw(value, self._to_remote_traceback(tb))
File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 335, in throw
self.on_ready.throw(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/vine/promises.py", line 244, in throw
reraise(type(exc), exc, tb)
File "/usr/local/lib/python3.7/site-packages/vine/five.py", line 195, in reraise
raise value

  File "/modules/dagster/dagster/cli/api.py", line 369, in _execute_run_command_body
    for event in execute_run_iterator(recon_pipeline, pipeline_run, instance):
  File "/modules/dagster/dagster/core/execution/api.py", line 723, in __iter__
    execution_plan=self.execution_plan, pipeline_context=self.pipeline_context,
  File "/modules/dagster/dagster/core/execution/api.py", line 676, in _pipeline_execution_iterator
    pipeline_context, execution_plan, steps_started, pipeline_success_ref
  File "/modules/dagster/dagster/core/execution/api.py", line 642, in _core_execution_iterator
    for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
  File "/modules/dagster-celery/dagster_celery/core_execution_loop.py", line 141, in core_celery_execution_loop
    subprocess_error_infos=list(step_errors.values()),

Similar issues: 
https://github.com/boto/botocore/issues/1965
https://stackoverflow.com/questions/58210314/boto-intermittent-unable-to-load-credentials-with-ec2-iam-roles/60199286#60199286

**Comment by natekupp** [comment]
we added retries to the boto client, closing for now—let's reopen if we hit this exception again

**Comment by bratiacharya** [comment]
I am getting this error very frequently. Any idea?

TASK [Ensure Application Exists in Beanstalk] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.NoCredentialsError: Unable to locate credentials
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1612176347.5235934-25105931528250/AnsiballZ_elasticbeanstalk_app.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1612176347.5235934-25105931528250/AnsiballZ_elasticbeanstalk_app.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1612176347.5235934-25105931528250/AnsiballZ_elasticbeanstalk_app.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/local/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/local/lib/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_elasticbeanstalk_app_payload_f9hju946/__main__.py\", line 206, in <module>\n  File \"/tmp/ansible_elasticbeanstalk_app_payload_f9hju946/__main__.py\", line 169, in main\n  File \"/tmp/ansible_elasticbeanstalk_app_payload_f9hju946/__main__.py\", line 104, in describe_app\n  File \"/tmp/ansible_elasticbeanstalk_app_payload_f9hju946/__main__.py\", line 110, in list_apps\n  File \"/usr/local/lib/python3.6/site-packages/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/client.py\", line 663, in _make_api_call\n    operation_model, request_dict, request_context)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/client.py\", line 682, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/endpoint.py\", line 132, in _send_request\n    request = self.create_request(request_dict, operation_model)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/endpoint.py\", line 116, in create_request\n    operation_name=operation_model.name)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/hooks.py\", line 356, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/hooks.py\", line 228, in emit\n    return self._emit(event_name, kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/hooks.py\", line 211, in _emit\n    response = handler(**kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/signers.py\", line 90, in handler\n    return self.sign(operation_name, request)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/signers.py\", line 162, in sign\n    auth.add_auth(request)\n  File \"/usr/local/lib/python3.6/site-packages/botocore/auth.py\", line 357, in add_auth\n    raise NoCredentialsError\nbotocore.exceptions.NoCredentialsError: Unable to locate credentials\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
