### ISSUE TITLE
[dagit] selected step re-execution disabled issue

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2927]
I think the `Wait for selected steps to finish` gating should be disabled once the pipeline enters a terminal state

original issue below:

The pipeline run has failed but I cannot execute the selected step subset due to "Wait for the selected steps to finish to re-execute it."

<img width="1536" alt="Screen Shot 2020-09-17 at 7 47 34 PM" src="https://user-images.githubusercontent.com/6024687/93549681-b4731f00-f91e-11ea-8958-203105b49061.png">

**Comment by catherinewu** [comment]
Events related to step: 
<img width="1536" alt="Screen Shot 2020-09-17 at 7 49 46 PM" src="https://user-images.githubusercontent.com/6024687/93549815-fdc36e80-f91e-11ea-9f4a-bdf369bc1155.png">

**Comment by catherinewu** [comment]
There also aren't any Step Start events for this step in the db

**Comment by sryza** [comment]
@catherinewu or @alangenfeld do you know whether this is something that we have steps to reproduce?  Or is it actionable in some other way?  If not, maybe we should close and see if it resurfaces?

**Comment by yuhan** [comment]
can't repro. but likely was fixed by recent re-execution bug fixes. please reopen if this is still an issue
