### ISSUE TITLE
Add scheduler based on APScheduler for better flexibility

### ISSUE THREAD

**Issue by blarghmatey** [dagster-io/dagster#2934]
In order to support more dynamic scheduling, and scheduling that doesn't rely on an implementation of Cron, it would be great to add an implementation of the scheduler interface built on top of the [APScheduler](https://apscheduler.readthedocs.io/en/latest/) library. This would allow for storing the schedule definitions in the database, in Redis, in memory, etc. It would also be possible to expose a UI through Dagit to create/read/update/delete schedule instances. In addition to all of that, it supports automatically executing missed schedules in the event that a system crash or maintenance prevents normal execution.

**Comment by catherinewu** [comment]
cc @gibsondan

**Comment by helloworld** [comment]
Hey @blarghmatey, this is a great suggestion! We're actually working on a new custom `Scheduler` implementation that doesn't reply on Cron and does all the things you suggested as well as support more advanced scheduling strategies. 

> This would allow for storing the schedule definitions in the database, in Redis, in memory, etc. It would also be possible to expose a UI through Dagit to create/read/update/delete schedule instances.

We already persist information about schedules in the Database, and use that information to track new and deleted `ScheduleDefinitions` within your repository. You can also use Dagit to turn schedules on and off. Are you asking for the ability to create entirely new schedules from Dagit?

**Comment by mgasner** [comment]
@blarghmatey do we know an APScheduler expert who might be interested in sketching this :)

**Comment by blarghmatey** [comment]
@helloworld being able to create schedules from the Dagit UI is definitely something I would be interested in, but also just having more flexibility around how to define schedules and being able to handle execution around missed scheduled runs.

@mgasner I'm certainly happy to help with designing and vetting the implementation. I might have time to work on doing at least a first pass but I can't make any promises.

Thanks to all for the quick feedback!

**Comment by sryza** [comment]
I'm going to close this because we have chosen to go with our own scheduler implementation and not make the scheduler interface a general extension point. I believe the current architecture gives us the ability to fill the gaps mentioned here, which were more difficult to fill when we had the cron scheduler.
