### ISSUE TITLE
Syntax Highlighting for Python in Blog

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2936]
I'm not sure if this is specific to @sryza's post or a generalized thing, but we should have syntax highlighting for code samples.

<img width="1121" alt="Screen Shot 2020-09-22 at 5 09 45 AM" src="https://user-images.githubusercontent.com/28738937/93875277-f0491400-fc91-11ea-90b2-862d06e3c7e4.png">

**Comment by helloworld** [comment]
cc @yuhan

**Comment by yuhan** [comment]
fixed
