### ISSUE TITLE
Dagit zoom seems to be backwards (using multitouch touchpad), hard to control

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#297]
On my MacBook, pinching zooms in and zooming zooms out. Also, it's quite difficult to stop the zoom where you want it.

An easy improvement would be to just add zoom in/zoom out icons for less fine-grained but more reliable control.

Not sure if this is the same as #95

**Comment by mgasner** [comment]
One other thing to note is that two-finger pan seems to be interpreted as zoom. This is, tbf, actually smoother and easier to control than the zoom/pinch gesture. Again, on a Mac.

**Comment by schrockn** [comment]
@mgasner the opinionated fix zoom level is a design decision we made so I'm going to go ahead and close this for now
