### ISSUE TITLE
provide access to step events in success and failure hook

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#2975]
we want to enable solid hook to provide events in a streaming fashion, i.e. users can get the event as it comes. 
so the user can send error messages to slack for example:
```
@failure_hook(required_resource_keys={"slack"})
def slack_on_failure(context, event_iterator):
    for event in event_iterator:
    	if event.is_step_failure:
            context.resources.slack.send_message(event.event_specific_data.error)
```

we currently have `event_list_hook` which provides the access to the entire list of events in a pipeline run, but because this isn't streaming, the user has to wait until the step finishes and then get all the events of the step at the end.

**Comment by nancydyc** [comment]
#3631 We have more users requested this feature.

**Comment by sryza** [comment]
A potential use case that we heard from a user: know when the step started and stopped to report on that.

**Comment by yuhan** [comment]
We introduced a new attribute `solid_exception` on `HookContext` in 0.11.7. It returns the original exception object. You can find more info at [Accessing failure information in a failure hook](https://docs.dagster.io/concepts/solids-pipelines/solid-hooks#accessing-failure-information-in-a-failure-hook).

As for accessing more event types in a "near-realtime" fashion, we recommend writing a Sensor where you can call [`context.instance.get_event_records`](https://docs.dagster.io/_apidocs/internals#dagster.DagsterInstance.get_event_records) to get events. See examples like [Asset sensors](https://docs.dagster.io/concepts/partitions-schedules-sensors/sensors#asset-sensors) and [Run status sensors](https://docs.dagster.io/concepts/partitions-schedules-sensors/sensors#run-status-sensors) for more information.

So we're closing this issue given the two mechanisms described above could address most use cases of this issue.
