### ISSUE TITLE
Output more metadata in Dask DataFrame type_check_fn

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#2984]
The `type_check_fn` for Dask DataFrame currently only outputs the dataframe columns as metadata. Unlike the Pandas equivalent, the number of rows is not output because that can be expensive to compute depending on the state of the Dask graph.

However, it would be really useful to output metadata that doesn't require computing a Dask graph like the number of partitions, indexes, whether divisions are known, etc.

**Comment by sryza** [comment]
Closing this, because we've moved away from integration-specific Dagster types
