### ISSUE TITLE
k8s-dagit image for 0.9.12 not pushed 

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#2986]
Hi! 

I'm just trying out Dagster on Kubernetes and I noticed that the 0.9.12 image was for k8s-dagit was not pushed. Instead, it looks like the 0.9.11 image was updated. See screenshot below

<img width="1279" alt="Screen Shot 2020-10-02 at 11 09 16" src="https://user-images.githubusercontent.com/1425877/94912555-bc46cd80-049f-11eb-9c57-1506cf0391a0.png">

**Comment by gibsondan** [comment]
Hi, thanks for reporting this! The images should be correct now, and we've changed our release process to keep this from happening again.
