### ISSUE TITLE
Partition backfill UI appears unstyled and cutoff

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2988]
<img width="1529" alt="Screen Shot 2020-10-02 at 6 59 40 AM" src="https://user-images.githubusercontent.com/28738937/94931829-14b8a380-047d-11eb-9a04-8a7c24814a88.png">

**Comment by schrockn** [comment]
words_pipeline has no margin and the partition key is cut off

**Comment by hellendag** [comment]
This has been fixed.
