### ISSUE TITLE
Tracking Issue: Have a "queued" run state. Display it logically during a backfill

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2991]
Running through a demo this morning doing backfill stuff the lack of a queued state for a run is quite painful. It is difficult to know what the system is doing. Adding this issue to track this particular feature, which is part of the broader queueing issue.

What I would like to be able to is to start a backfill, be able to click on the "created backfill job" toast (https://github.com/dagster-io/dagster/issues/2990), see all the runs, and then understand the state of what is going on. That is which ones are running and which ones are not.

**Comment by johannkm** [comment]
Still some UI improvements to be made, but this is now the case when using the QueuedRunCoordinator.
