### ISSUE TITLE
Partitions graphs and backfills should be viewable easily from the schedules screen

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2995]
![Screen Shot 2020-10-02 at 10 39 34 AM](https://user-images.githubusercontent.com/28738937/94952926-961f2e80-049b-11eb-97e5-d52b430dfdc3.png)

In order to get a graph for history of this schedule I have to know to click on "slack_digest_pipeline" and then the Partitions tab.

Only then do I get the hotness:

![Screen Shot 2020-10-02 at 10 40 19 AM](https://user-images.githubusercontent.com/28738937/94953009-b818b100-049b-11eb-9fb4-48cd454833a1.png)

This doesn't make much sense from the user perspective

**Comment by sryza** [comment]
Could also potentially link directly to the relevant partition set?

**Comment by prha** [comment]
This got resolved in `0.10.0`
