### ISSUE TITLE
Are spaces allowed in pipeline and solid names?

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#2996]
Dagster 0.9.12 outputs a warning for invalid solid and pipeline names. Our pipelines, solids, and other resources are named with human friendly values and have spaces in them (e.g., `Extract Item Info`). This hasn't been a problem with past Dagster versions. But, are spaces going to be considered out of spec going forward?

> /usr/local/lib/python3.8/site-packages/dagster/core/definitions/pipeline.py:159: UserWarning: You provided name "Extract Item Info" which is invalid. Name must pass regex "^[A-Za-z0-9_]+$" and cannot be a python keyword, primitive type, or some other common names. This will be an error starting in 0.9.13. Full list: {'str', 'global', 'if', 'continue', 'break', 'import', 'or', 'in', 'while', 'input', 'and', 'class', 'from', 'context', 'not', 'output_arg_dict', 'as', 'conf', 'except', 'dict', 'config', 'False', 'for', 'async', 'nonlocal', 'try', 'bool', 'await', 'arg_dict', 'pass', 'float', 'output', 'assert', 'yield', 'raise', 'input_arg_dict', 'with', 'lambda', 'type', 'def', 'True', 'None', 'finally', 'meta', 'int', 'else', 'is', 'del', 'elif', 'return'}.

**Comment by schrockn** [comment]
Hey @kinghuang thanks for opening up this issue.

The sad reality is that not doing this check on pipeline was always an oversight (we always disallowed these for solids) which we are just now correcting. 

The name field on these objects has come to be used for snapshots, indexes, and other programmatic access patterns that make us believe strict naming rules will save us from substantial number of problems over time. The name is also significant in terms of determining the identity of the object throughout the system.

However I do appreciate the desire for more human-friendly names, especially in the UI etc. And, perhaps, more importantly, the ability to change the display name of something while still retaining all the history around it. Having a display name concept would allow to alter the displayed name while not changing the underlying identity of the pipeline and destroying all history, for example. Thoughts?

**Comment by kinghuang** [comment]
Understood. So, the current `name` is more like a technical `id`. A new field like `display_name` for human-friendly values to be shown in the UI sounds good to me!
