### ISSUE TITLE
Add document titles in dagit

### ISSUE THREAD

**Issue by hellendag** [dagster-io/dagster#2998]
Individual pages in dagit currently don't have document titles, which means that all tabs and items in back/forward menus are just "Dagit", which is not useful. Let's make this better.

**Comment by kinghuang** [comment]
In addition to distinguishing the different pages, it'd be nice if there is a way to customize Dagit's name, so that I can tell the different between different environments. e.g., be able to change `Dagit` to `Dagit Staging`.

Relates to #2994 a bit.
