### ISSUE TITLE
dagster-celery tests failing due to misconfigured celery app fixture

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#2999]
Test fixture celery app creation code: https://dagster.phacility.com/source/dagster/browse/master/python_modules/libraries/dagster-celery/dagster_celery_tests/conftest.py$13-23

Real celery app creation code: https://dagster.phacility.com/source/dagster/browse/master/python_modules/libraries/dagster-celery/dagster_celery/app.py$9-11

Workers run using the former can't find the "execute_plan" module, causing all tests that use the fixture to fail.

**Comment by sryza** [comment]
Going to close this because I think we're no longer seeing this failure. Plz reopen if this is wrong.
