### ISSUE TITLE
Health check endpoint for Dagster API gRPC server

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3002]
Dagit servers expose a health check endpoint at `/dagit_info`. Is there an equivalent when running a Dagster API gRPC server?

**Comment by gibsondan** [comment]
There's a Ping API that the server exposes that could work for this, but we don't call it anywhere in Dagster or Dagit currently.

**Comment by kinghuang** [comment]
Hmm, I'm not aware of the ping API. What's its endpoint?

**Comment by gibsondan** [comment]
It doesn't have an endpoint - it's one of the gRPC methods exposed by the server though. Accessing it currently would require writing some custom code to connect to the server and calling this API on it (would require some knowledge of the implementation of the gRPC server - we should probably expose something more user-friendly that accomplishes this instead)

**Comment by schrockn** [comment]
Can you give us some more context on why you want this? Very interested in your exact use case.

**Comment by kinghuang** [comment]
I'm splitting out my Dagster repositories from Dagit using the gRPC functionality. For the Dagster gRPC server containers, I'm looking for something to use for the container health check to check that the gRPC server is up.

For Dagit, the `/dagit_info` endpoint works well for this purpose. The health check uses `curl` to do a GET request and check that the response contains the expected Dagit/Dagster version info.

**Comment by schrockn** [comment]
Makes sense!

**Comment by alangenfeld** [comment]
https://github.com/grpc-ecosystem/grpc-health-probe

**Comment by johannkm** [comment]
Hi @kinghuang, just to clarify, a health check over an http endpoint would be best for you?

**Comment by kinghuang** [comment]
An `http` endpoint would be the most convenient in terms of using existing tools like `wget` and `curl`. But, that `grpc_health_probe` tool @alangenfeld linked to looks totally fine, too. It appears to be built for health checking gRPC apps in K8s, which fits my use case.

**Comment by alangenfeld** [comment]
Heres a blog post that touches on why the health probe binary is recommended
https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/
its seems not trivial to host a regular http endpoint on the grpc server.

**Comment by awhillas** [comment]
@alangenfeld are you saying that the dagster grpc server conforms to the [RPC Health Checking Protocol v1](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) and one can run the [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe) as a sidecar container (it just seems to be a CLI tool, would it provide a http server that k8s or ECS could query?)

**Comment by alangenfeld** [comment]
> dagster grpc server conforms to the RPC Health Checking Protocol v1

Yep, we use https://pypi.org/project/grpcio-health-checking/

> one can run the [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe) as a sidecar container

you should be able to do that, though we have a cli entry point available as well. Example in our helm chart here: https://github.com/dagster-io/dagster/blame/master/helm/dagster/values.yaml#L350-L351

> would it provide a http server that k8s or ECS could query?

I don't believe so. K8s can run cli commands for checks as shown above, but a http server would have to be provided by some other means.
