### ISSUE TITLE
Support for sending messages to Microsoft Teams (Connector Cards)

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3003]
### Problem to solve

As a pipeline/solid author in an organization that uses Microsoft Teams (as opposed to Slack), I would like something that helps me send messages to Teams channels during pipeline execution, similar to the `dagster_slack` module.

### Intended users

* Pipeline Developer
* DevOps Engineer

### User experience goal

Pipeline developers should be able to create a Dagster resource that manages sends requests to Microsoft Teams Webhooks, and perhaps help create Connector Cards.

```python
@solid(required_resource_keys={"teams"})
def teams_solid(context):
    context.resources.teams.post_message(title="Dagster", text="Hello, from Dagster!")
``` 

DevOps engineers should be able to configure the resource with a webhook URL (or similar), and any other details needed to authorize/authenticate requests.

### Proposal

Create a `dagster_teams` module that provides a resource for working with Teams webhooks, mainly to post messages.

### Further details

See [Sending messages to connectors and webhooks](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#setting-up-a-custom-incoming-webhook) for some documentation.

**Comment by kst83** [comment]
Would also be interested in a teams module
