### ISSUE TITLE
Reloading repository metadata doesn't refresh pipelines list in Dagit

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3005]
### Summary

If I add or remove a pipeline from a repository's resources and then press the button to reload the repository's metadata in Dagit, the list of pipelines does not change. I have to refresh the browser window to see the change.

### Steps to reproduce

This example removes a pipeline, but it's the same idea for adding a pipeline.

1. Create a `RepositoryDefinition` with a couple of pipelines.
2. Run Dagit and load the repository. Select one of the pipelines.
3. Remove the selected pipeline from the repository definition.
4. Press the “Reload metadata from this repository location” button in Dagit.

### What is the current *bug* behaviour?

After reloading the metadata, Dagit still shows the pipeline in the pipelines left on the left. However, since the pipeline no longer exists, the main area now says “Pipeline Not Found” because it is still the active/selected pipeline.

### What is the expected *correct* behavior?

The pipelines list should be refreshed after reloading the metadata.

At the moment, to refresh the list, the browser window has to be reloaded in addition to reloading the metadata.

### Relevant logs and/or screenshots

**Starting state**:

![Screen Shot 2020-10-03 at 2 34 43 PM](https://user-images.githubusercontent.com/27340/95001275-9c89d500-0585-11eb-9696-d6bc8f497618.png)

**extract_invoice_detail removed and metadata refresh**:

Note that `extract_invoice_detail` still appears in the sidebar, but the pipeline is no longer found. And, as an aside, the tooltip for the reload button doesn't go away.

![Screen Shot 2020-10-03 at 2 36 02 PM](https://user-images.githubusercontent.com/27340/95001302-d529ae80-0585-11eb-9b96-e7ed3d21305f.png)

**Browser refreshed**:

The pipelines list is now matches the state in the refreshed metadata.

![Screen Shot 2020-10-03 at 2 37 20 PM](https://user-images.githubusercontent.com/27340/95001321-f68a9a80-0585-11eb-9580-3afc884e42ae.png)

### Versions

```
root@c1f4eb28eea8:/project# dagster --version
dagster, version 0.9.12
root@c1f4eb28eea8:/project# dagit --version
dagit, version 0.9.12
```

### Other Information

I think it's ok for Dagit to still have `extract_invoice_detail` as the selected pipeline, even though it's been removed. The user can explicitly select another pipeline, or add the missing pipeline back into the repository.

**Comment by hellendag** [comment]
This has been fixed.
