### ISSUE TITLE
Dagit Playground controls are still active while generating configuration

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3007]
### Summary

In the Dagit Playground, when a preset config or partition set config is selected, the editor area and UI controls like the `Partition Set` popup menu are greyed out to indicate inactive controls. But, they are still active and can be interacted with.

### Steps to reproduce

Given a pipeline with presets or partition sets.

1. Run Dagit, select the pipeline, and go to the Playground tab.
2. Choose a preset config or partition set. The main config editor area should be greyed out with a message saying "Generating configuration…".
3. While in the state described in step 2, click on a control like the partition menu.

### What is the current *bug* behaviour?

While the editor is greyed out, the UI controls are still active and respond to user interactions. For example, it is possible to click the partition menu and select another partition while the config for one is being generated. The new selection may be overridden when the previous selection is generated, though.

### What is the expected *correct* behaviour?

While the editor is greyed out, none of the greyed out UI controls should be active.

### Relevant logs and/or screenshots

I've selected a partition, and the editor area is greyed out. But, I am able to click on the partition menu and select another one.

![image](https://user-images.githubusercontent.com/27340/95021840-b9c7ad80-0630-11eb-9f27-70375c3da4ed.png)

### Versions

```
root@65b4a93cd00f:/project# dagster --version
dagster, version 0.9.12
groot@65b4a93cd00f:/project# dagit --version
dagit, version 0.9.12
```

**Comment by schrockn** [comment]
These are amazing reports! Thank you 🙏🏻🙏🏻🙏🏻
