### ISSUE TITLE
Visible versioning for dagit webapp

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#301]
cc @schrockn 

It would be nice if dagit visibly surfaced its version in the webapp interface, perhaps printing the version number and git commit hash in a bottom corner of the interface. This would help us more easily diagnose phantom issues like #273, where the actual cause was an out of date yarn build. This is likely to trip up many new developers on the project.

**Comment by bengotow** [comment]
I think this is a great idea - I think we could put this in the top right of the UI (or the bottom left, inside the graph). Will get this added.

**Comment by mgasner** [comment]
@bengotow are we good to close this issue?
