### ISSUE TITLE
Duplicate browser history when searching through docs

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3011]
## Issue 
More than one state is pushed to the browser history when navigating the docs.

**Browser history when starting at the homepage**
![image](https://user-images.githubusercontent.com/16431325/95123378-b6065a80-0706-11eb-94c6-d3040f691195.png)

**Browser history after navigating to some link (e.g. `Kubernetes (dagster_k8s)`)**
![image](https://user-images.githubusercontent.com/16431325/95123453-d7674680-0706-11eb-9e7a-909c89fd36c7.png)

Three states were pushed to the browser history:
- https://docs.dagster.io/_apidocs/libraries/dagster_k8s#kubernetes-dagster-k8s
- https://docs.dagster.io/_apidocs/libraries/dagster_k8s#
- https://docs.dagster.io/_apidocs/libraries/dagster_k8s#kubernetes-dagster-k8s (again)

As a result, to go back to the homepage, I have to click the back button on my browser three times.

## Expected Behavior
Only one state should be pushed to the browser history stack when navigating to another link in the documentation. When navigating to a search result from the Dagster docs, I should only have to navigate back once to go to the previous page.

**Comment by yuhan** [comment]
@helloworld do you happen to know what could be causing this behavior? would it be a nextjs thing?

**Comment by yuhan** [comment]
can't repro. please reopen if this still happens on the new site
