### ISSUE TITLE
Don't show shortcut tooltips in Dagit when taking a screenshot

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3012]
When I try to take a screenshot of Dagit, all of the tooltips showing shortcuts show up. I keep needing to disable the tooltips whenever I take screenshots, but ideally, the Mac OS screenshot shortcut and the tooltip preview shortcut shouldn't conflict. 

![image](https://user-images.githubusercontent.com/3893054/95137606-748da380-0736-11eb-96f1-d9e02a879ceb.png)

**Comment by helloworld** [comment]
cc @hellendag @bengotow

**Comment by kinghuang** [comment]
I've just been taking screenshots really, *really* fast before the tooltips show up. Took a bit of practice. 😂

**Comment by natekupp** [comment]
Slack has a ~2s delay before showing the tooltips, we could do that too

**Comment by bengotow** [comment]
I'd be up for a delay! That seems like a good approach. We could also add a "show help" button bound to `?` I think I've seen that in a few apps as well.

I've gotten in the habit of putting another window in the foreground and taking screenshots without the window having keyboard focus, which is definitely a hack 😅

**Comment by helloworld** [comment]
Slack also disables the tooltips as soon as you press "Shift", and the screenshot shortcut on MacOS is "Cmd-Shift-[Some number]". So it basically knows you're about to take a screenshot and hides them.

**Comment by sryza** [comment]
Oh yeah this has driven me crazy
