### ISSUE TITLE
[k8s] Helm chart to just deploy user code container

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3018]
User requested ability to deploy specific sets of user code containers with helm, without updating dagster services / deployments

**Comment by catherinewu** [comment]
likely will use helm subcharts: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

**Comment by rexledesma** [comment]
Resolved with a stack of commits: 648d1a596a4dd4af5a362cdf4415ac4ac4120ebf, 8fb71ca108a9cba7060b5a47aa8314576e57361c
