### ISSUE TITLE
Dagit pipeline run view, unexpected filtering behavior

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3024]
When viewing a pipeline run, there are options to filter for Debug / Info / Warning / Error / Critical / Event. By default, clicking on a filter _removes_ those events from the logs view. So, to view "Info" logs, one would have to click four buttons -- "Warning", "Error", "Critical" and "Event" ("Debug" is unselected by default) which can be a bit unwieldy and unexpected.

User expected that clicking a filter would filter _for_ the event and not _against_ it.

**Comment by alangenfeld** [comment]
Which version of dagit was this on? https://dagster.phacility.com/D4518 made this much better recently
