### ISSUE TITLE
Run config for solid subselection for partition

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3030]
Currently, dagster only allows user to specify one run config per partition. This means that when the user wants to run a solid subselection (for example due to the previous pipeline ending in an ambigious, non-failure / non-success state), then the user needs to manually construct the config of the root solids.

For users who have pre-defined configuration for each solid's inputs, we could explore exposing a "generate run config for solid subselection for partition" function

**Comment by sryza** [comment]
I suggested a solution to the user that I believe works for them.  There isn't a general solution to this for all cases, but in the case where a user has hardcoded inputs, they can do something like this:

```
    @solid()
    def solid1(_):
        return "public.table_1"

    @solid(input_defs=[InputDefinition(name="input_table", default_value="public.table_1")])
    def solid2(_, input_table):
        pass

    @pipeline
    def my_pipeline():
        solid2(solid1())

    execute_pipeline(my_pipeline)
    execute_pipeline(my_pipeline, solid_selection=["solid2"])
```

**Comment by schrockn** [comment]
@sryza why even have `solid1` here

**Comment by sryza** [comment]
> @sryza why even have solid1 here

I'm not sure I understand.  solid1 generates public.table_1.  Are you saying why not have solid1 emit a Nothing output?  If so, that could work too, but would be a bigger change for the user.
