### ISSUE TITLE
Should support backfilling partitions for which there was not a previous run

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3031]
Currently, dagster can only backfill partitions for which there was a previous run

**Comment by sryza** [comment]
Is this purely a problem with what backfills can be triggered in Dagit?  Or an issue with how backfills work more deeply?

**Comment by catherinewu** [comment]
cc @prha -- could you add the insight that you shared last month during the customer meeting?

**Comment by prha** [comment]
Any step subselection with a backfill that takes in inputs will need to copy intermediates from a previous run context.

For orgs that only use `Nothing` inputs, this is not an issue.  I think we're going to enable it via UI and just have errors for steps subselections that do take inputs.

**Comment by sryza** [comment]
It seems like Dagit actually does support backfilling partitions without a previous run.

The issue is with step subsets, which is tracked here: https://github.com/dagster-io/dagster/issues/3092.  I'm going to close this.
