### ISSUE TITLE
have inputs / outputs in the definition view to link to entries in the asset catalog

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3032]
Three ways we could implement this:
* Enable users to specify, in code, which assets their inputs / outputs are intended to mutate.
* Enable AssetMaterializations to track which output definition they correspond to.  List all assets that have prior materializations that correspond to that output definition.
* Track the correspondence at the solid level, not the input / output level.  List all assets that have prior materializations that correspond to that solid.

**Comment by sryza** [comment]
Closing this because software-defined assets essentially is this
