### ISSUE TITLE
[dagit] Accidentally clicking to pipeline definition view instead of pipeline run view

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3033]
Within the partitions page, many users click on pipeline name on run list items rather than the run hash and land on pipeline page accidentally

**Comment by alangenfeld** [comment]
This problem applies out side the partitions UI in all runs lists. I get burned by it all the time, definitely supportive of attempting to improve the experience here.

**Comment by sryza** [comment]
This has happened to me many times

**Comment by hellendag** [comment]
Hopefully resolved by https://github.com/dagster-io/dagster/commit/7a9aa5bff13cb1d7356a7b15a84a26eb48764b26.
