### ISSUE TITLE
apidocs deep links are broken

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3037]
This 404s: https://docs.dagster.io/_apidocs/sections/api/apidocs/solids#dagster.SolidDefinition

**Comment by yuhan** [comment]
@sryza do you recall what brought you to this broken link? it should have been captured by the docs broken link tests if it's an internal link

**Comment by sryza** [comment]
Hmm - now I don't remember :(.  Maybe search?  But that seems to work now.  We can probably close this.

**Comment by yuhan** [comment]
might be related to #2939
