### ISSUE TITLE
[k8s] make helm chart default to using the Dagster daemon

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3039]

**Comment by catherinewu** [comment]
https://dagster.phacility.com/D4778

**Comment by natekupp** [comment]
we need to ensure that the migration path doesn't leave stray K8s CronJob objects around

**Comment by natekupp** [comment]
This was done in https://dagster.phacility.com/D5642 - @gibsondan let's make sure to include release notes on implications for existing cron job users
