### ISSUE TITLE
Investigate performance of partitions graphs on the Schedules page in Dagit

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3041]
The partitions page in Dagit seems to be slow/unloadable when a schedule has a lot of executions. A user is running a pipeline on a schedule of every 5 minutes and is unable to load the partition graphs on the schedules page. The problem might be caused by a DB bottleneck, but we should investigate if we're making unnecessarily expensive queries or over fetching and also audit our pagination on that page.  

The user is using a t3.medium instance in RDS.

**Comment by nancydyc** [comment]
#3430 This is also a Dagit performance issue
