### ISSUE TITLE
API Docs link broken in small screen size 

### ISSUE THREAD

**Issue by nancydyc** [dagster-io/dagster#3054]
Docs cannot scroll down in small screen size as well. @yuhan @helloworld

**Comment by yuhan** [comment]
@nancydyc can you share a screenshot? i can't repro

**Comment by nancydyc** [comment]
Here's it.
<img width="493" alt="small screen problem" src="https://user-images.githubusercontent.com/59324923/95497296-f1976380-0956-11eb-8861-31857533f1a2.png">

The zip file contains the screen record. 
[small screen problem.mov.zip](https://github.com/dagster-io/dagster/files/5350535/small.screen.problem.mov.zip)

**Comment by yuhan** [comment]
fixed by rework the site's mobile view
