### ISSUE TITLE
Add json schema validation for helm values

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3057]
We should consider defining a [schema file for our `values.yaml`](https://helm.sh/docs/topics/charts/#schema-files). This will allow us to do requirement checks, type validation, range validation, and constraint validation on our chart's values [[1]](https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/). 

Note that this schema file can be created incrementally, so not all validation has to be added at once. 

We can also use the schema file to describe the fields in `values.yaml`, as well as surface concrete examples if validation fails [[2]](https://json-schema.org/understanding-json-schema/reference/generic.html#annotations).

**Comment by natekupp** [comment]
@rexledesma is this done?
