### ISSUE TITLE
dagster-slack should be rewritten for the new slack client/API

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3058]
We currently have a pin on `slackclient` in `dagster-slack` due to py2 support:

```
# Slack 2.x does not support Python 2
# https://github.com/slackapi/python-slackclient/wiki/Migrating-to-2.x#minimum-python-versions
"slackclient<2.0.0",
```

However, 2.0 was a complete rewrite: https://github.com/slackapi/python-slackclient/wiki/Migrating-to-2.x

Users will most likely want to use the 2.0 API, which is quite different from the 1.x API and contains many new features. It's pretty confusing to look at the [current slackclient documentation](https://github.com/slackapi/python-slackclient) and run into errors due to version mismatch. 

We should consider making `dagster-slack` python 3 only and update the resource to use slackclient 2.x

**Comment by schrockn** [comment]
Strongly in the support of this. I think we can just retitle this so upgrade dagster-slack to support slackclient>=2.0.0
