### ISSUE TITLE
dagit happily renders circular dependencies

### ISSUE THREAD

**Issue by Aylr** [dagster-io/dagster#306]
Dagit happily renders circular dependencies, even though upon execution dagster raises a `CircularDependencyError`

<img width="604" alt="screen shot 2018-11-27 at 9 18 29 pm" src="https://user-images.githubusercontent.com/928247/49128777-1e25c300-f28a-11e8-82fe-77944f72123b.png">

**Comment by mgasner** [comment]
This is fixed: we now get `[GraphQL error] @pipeline circular_reference_pipeline invoked the same solid (foo) twice without aliasing.`
