### ISSUE TITLE
dagster-aws.emr package requires dagster-spark

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3060]
It should be possible to use dagster-aws.emr without pulling in spark dependencies

**Comment by sryza** [comment]
A couple options:
* Split out the emr_pyspark_step_launcher into a separate top-level package, e.g. dagster-emr-pyspark
* Require users to import from `dagster_aws.emr.pyspark_step_launcher` instead of `dagster_aws.emr`

**Comment by sryza** [comment]
https://dagster.phacility.com/D4745

**Comment by sryza** [comment]
Short-term plan (for 0.9.17): make it so that `import dagster_aws.emr` doesn't transitively import any spark stuff.
* Duplicate spark_configs.py to the dagster-aws package
* Move all pyspark imports inside functions

Long term plan (aim for 0.10.0): add a dagster-aws-pyspark package and remove emr_pyspark_step_launcher from dagster-aws
* During the deprecation period, both dagster-aws and dagster-aws-pyspark will have versions of the emr_pyspark_step_launcher.  The dagster-aws-pyspark version will point to the internals in the dagster-aws package.
* The dagster-aws version will emit a deprecation warning.
* After the deprecation period, we'll migrate the internals to dagster-aws-pyspark.

https://github.com/dagster-io/dagster/issues/3163

**Comment by catherinewu** [comment]
Hi @sryza seeing as this issue was moved from `In progress` to `Done` on the Assets project board, I'm going to close this comment. If this was done in error, please feel free to re-open
