### ISSUE TITLE
tqdm / progressbar from solid

### ISSUE THREAD

**Issue by mrdrprofuroboros** [dagster-io/dagster#3070]
Some solids are quite a massive map-reduce tasks whose execution time heavily depends on the config. So I want to get an estimate of what to expect from them and the most natural way would be a progress bar. when I execute pipeline in dev mode via python API, I see tqdms running in my jupyter, but I would like to have it in dagit. the MVP here could be just tqdm plugin, yielding % messages in plain text, but of course UI is preferred

tqdm seems to be the core tool in data science, it makes computations faster :smile:

**Comment by mrdrprofuroboros** [comment]
it is highly customizable
https://github.com/tqdm/tqdm/blob/master/tqdm/contrib/telegram.py

**Comment by mrdrprofuroboros** [comment]
sorry, duplicated

**Comment by nancydyc** [comment]
No problem. Your comments are greatly appreciated!
