### ISSUE TITLE
proposal: use args not command for kubernetes

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#3081]
Hi, 

thanks for this great project :) 

I noticed that in a few places (helm chart, dagster-celery-k8s) pipeline pods are creating setting the `command` to `dagster`. 

There is a different meaning between `command` in k8s and in docker, because in kubernetes what is specified in `command` overrides the image entrypoint (see: [kubernetes docs](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes)). This might be a problem for docker images where the entrypoint is set (e.g. [to provide a conda environment](https://pythonspeed.com/articles/activate-conda-dockerfile/)).

Would it be possible to not set command and use args instead so that the entrypoint is preserved? In alternative, is it possible to let the user specify the command and args?

This is just a proposal, but if you are happy with it I can try opening a PR.

Thanks again 🙂

**Comment by helloworld** [comment]
Hey @amarrella, sorry for the late response here. I'm hoping to fix this for you today. 

Just to make sure I understand correctly, what do you plan on setting the entry point in your image to be? I'm assuming it would be something like:

```
ENTRYPOINT ["conda", "run", "-n", "myenv", "dagster"]
```

Also for your proposal:

> Would it be possible to not set command and use args instead so that the entry point is preserved? In the alternative, is it possible to let the user specify the command and args?

Which solution do you prefer?

**Comment by amarrella** [comment]
@helloworld no problem, thanks for getting back to me :) 

I actually have a shell script in my images that looks like this:
```sh
#exec_in_myenv.sh
#!/bin/bash
. /opt/conda/etc/profile.d/conda.sh
conda activate myenv
exec "$@"
```

and as entrypoint in the dockerfile I have
```
ENTRYPOINT [ "exec_in_myenv.sh" ]
```

but i believe what you quoted is more idiomatic and would work the same.

For my proposal the best case would be being able to specify both so that i have maximum flexibility (with a default to use dagster to support the most common use case).

Thanks again for working on this and let me know if I can be of any help :)

**Comment by helloworld** [comment]
Hey @amarrella, I put up https://dagster.phacility.com/D5452 that moves everything to the container arguments, so that you can specify your own entry point. I just wanted to pass it by you to check that this works for you.

**Comment by amarrella** [comment]
Hi @helloworld, thanks for this! 

I'll be testing it soon and let you know if there are any issues!

Thanks a lot!

**Comment by catherinewu** [comment]
Hi @amarrella fyi -- I think the change is only in master right now and is intended for the 0.10.0 release (~Jan 14). We can cherry-pick it for the 0.9.23 next week, if you would like it earlier!

**Comment by amarrella** [comment]
No rush! January is completely fine for me. Thanks again :)

**Comment by catherinewu** [comment]
Thank you for giving us so much great feedback 👍

**Comment by daviskirk** [comment]
The dagster kubernetes chart still uses the "command" in the user template deployment.
Is this on purpose or would the same logic apply there as well?

https://github.com/dagster-io/dagster/blob/a790cd3736eecccea0e63777e0853213b2eba507/helm/dagster/charts/dagster-user-deployments/templates/deployment-user.yaml#L44

**Comment by TimoFriedri** [comment]
I actually have the opposite problem. The run pod now ionly has args and no command in my case.

In combination with Azure ACI, I can now not start the ACI pods because they expect a command! They complain that there are only args!!!

**Comment by abkfenris** [comment]
> The dagster kubernetes chart still uses the "command" in the user template deployment. Is this on purpose or would the same logic apply there as well?
> 
> I'm running in to the same problem there trying to use dagster that's installed in a conda environment
> 
> https://github.com/dagster-io/dagster/blob/a790cd3736eecccea0e63777e0853213b2eba507/helm/dagster/charts/dagster-user-deployments/templates/deployment-user.yaml#L44

I'm running into this with user code deployments too, specifically using a [micromamba](https://github.com/mamba-org/micromamba-docker/) base image with conda environments.
