### ISSUE TITLE
YAML highlighting breaks with inline arrays \ dicts

### ISSUE THREAD

**Issue by mrdrprofuroboros** [dagster-io/dagster#3082]
YAML highlighting breaks when you use inline arrays or dicts. I personally like to use them a lot, they make it more compact\readable quite frequently. 

It breaks quite peculiar :smiley: highlighting a closing bracket + random following key as plain text

Normal:
![image](https://user-images.githubusercontent.com/21140507/95776843-c651a300-0ccd-11eb-9b69-5ffc6a5afc76.png)

Inline:
![image](https://user-images.githubusercontent.com/21140507/95776833-c05bc200-0ccd-11eb-93c2-7ee801b15c8a.png)

**Comment by bengotow** [comment]
Hey hey! Thanks for filing this - we made a bunch of improvements to the YAML syntax parser last week and I double checked that it's tagging literals in inline objects and arrays correctly now. Should be shipped in the next release!

<img width="542" alt="image" src="https://user-images.githubusercontent.com/1037212/102270423-94360a80-3ee3-11eb-98a4-ad3cbc8380d8.png">
