### ISSUE TITLE
loading asset page locks up dagit in certain conditions

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#3083]
On postgres, user with millions of event rows is seeing the `select distinct asset_key from event_logs` query lock up dagit for an extended period of time.

edit: database was not locked up - it was dagit and our current poor use of gevent

**Comment by alangenfeld** [comment]
current plan of attack
* add `statement_timeout` to our pg connections to prevent problematic queries from doing much damage
* create a dedicated `asset_keys` table

**Comment by sryza** [comment]
@prha is this work ongoing?

**Comment by prha** [comment]
the fix is out, but want to confirm that it resolves the issue.  will close out when i do.
