### ISSUE TITLE
Highlighting in config editor is wrong when solid config is missing (?)

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3086]
Steps to reproduce:

`arc patch D4753` then load `community_events_demo/base.py` with `dagit -f`

<img width="747" alt="Screen Shot 2020-10-13 at 9 24 48 AM" src="https://user-images.githubusercontent.com/427016/95873878-f16fdd00-0d35-11eb-937f-d82aed338810.png">

but

<img width="390" alt="Screen Shot 2020-10-13 at 9 25 57 AM" src="https://user-images.githubusercontent.com/427016/95874046-1c5a3100-0d36-11eb-9367-f3fc90c1c776.png">

if you type `solids:` in the config editor, all of the highlighting disappears (this feels wrong -- `query_stock_market_data` should still be missing)

<img width="595" alt="Screen Shot 2020-10-13 at 9 26 59 AM" src="https://user-images.githubusercontent.com/427016/95874178-3f84e080-0d36-11eb-88c8-9f8ba7c1bfb1.png">

but there is still an (uninformative) error

<img width="532" alt="Screen Shot 2020-10-13 at 9 26 44 AM" src="https://user-images.githubusercontent.com/427016/95874155-372ca580-0d36-11eb-8dda-f91adc4f4ab1.png">

**Comment by hellendag** [comment]
It looks like the validation is incorrect (or at least missing useful information) in the value coming from python.

```
{
  "__typename": "PipelineConfigValidationInvalid",
  "errors": [
    {
      "__typename": "RuntimeMismatchConfigError",
      "reason": "RUNTIME_TYPE_MISMATCH",
      "message": "Value at path root:solids must not be None.",
      "stack": {
        "entries": [
          {
            "__typename": "EvaluationStackPathEntry",
            "fieldName": "solids"
          }
        ],
        "__typename": "EvaluationStack"
      }
    }
  ]
}
```

If information should be added to highlight `query_stock_market_data` as being required, I'm thinking that should come from the validation step rather than being determined on the client.
