### ISSUE TITLE
Skipped solids in failed pipelines are incorrectly marked "preparing" in run viewer

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3087]
<img width="1590" alt="Screen Shot 2020-10-13 at 10 34 31 AM" src="https://user-images.githubusercontent.com/427016/95882830-c7bbb380-0d3f-11eb-931e-e70e74f690d1.png">

**Comment by alangenfeld** [comment]
We can change the label to `Not Executed` either always or just after the pipeline enters a finished state
