### ISSUE TITLE
Dagit shows “large DAG” message for an empty pipeline

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3094]
### Summary

I created several stub pipelines with no solids for some new development. In Dagit, a message appears indicating that the DAG is large and difficult to visualize. It should probably show a message saying that the DAG is empty, instead.

### Steps to reproduce

1. Create a pipeline with no solids.
2. View the pipeline's definition in Dagit.

```python
@pipeline
def empty_pipeline():
    pass
```

### What is the current *bug* behaviour?

Dagit shows the following message, suggesting that the pipeline DAG is large and difficult to visualize.

> This is a large DAG that may be difficult to visualize. Type * in the subset box below to render the entire thing, or type a solid name and use:

### What is the expected *correct* behaviour?

Dagit should show a message indicating that the pipeline is empty, or nothing at all.

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/27340/95920536-d2407200-0d6c-11eb-8e27-6e0b48808af6.png)

### Versions

```
root@0ce914363032:/project# dagster --version
dagster, version 0.9.13
root@0ce914363032:/project# dagit --version
dagit, version 0.9.13
```

**Comment by hellendag** [comment]
Thanks for the detailed report!
