### ISSUE TITLE
Non-BytesIO serialization strategy (e.g. for dask dataframes)

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#3110]
Hi, I'm trying to find a way to serialize intermediate dask dataframes without converting them to pandas via `.compute()`.

I think due to its distributed nature, dask doesn't offer the possibility to serialize a dataframe to BytesIO. Would it be possible to allow for a `Path` or a URI to be specified instead? I'm not sure what this would mean for memory storage, perhaps in that case default to pickle or let the user specify a separate serialize function for memory?

Thanks again :)

**Comment by amarrella** [comment]
Expanding to this, sometimes it would be nice to "serialize" to a db table as well (i guess in that case it would need a database resource).

**Comment by schrockn** [comment]
Hey @amarrella. For our next major release we are revamping our intermediates system to allow the user to take more control of persisting assets as they are passed between steps in the execution. This will solve a number of problems and will in the end be the "right" way to allow you to custom how your data frames are stored.

In the short-term, the way to take more fine-grained control over the serialization process would be to overwrite your own implementation of `IntermediateStorage`. However, this is quite advanced and will be deprecated in the next release.

**Comment by amarrella** [comment]
Hey @schrockn thanks for your reply! I'm looking forward to see the new way :) 

I'm not in a rush to overwrite the implementation, but good to know in case i need a "escape hatch"!

Thanks again :)

**Comment by alangenfeld** [comment]
https://docs.dagster.io/concepts/io-management/io-managers#io-managers
