### ISSUE TITLE
[graphQL error] Hitting an unexpected error while fetching data from Dagster

### ISSUE THREAD

**Issue by nancydyc** [dagster-io/dagster#3119]
I was running launch execution in Dagit but got error message like below:

<img width="1472" alt="Screen Shot 2020-10-16 at 4 00 44 PM" src="https://user-images.githubusercontent.com/59324923/96321028-f4cec700-0fc8-11eb-94a2-f5546c81229c.png">

**Comment by mgasner** [comment]
dagit out of sync
