### ISSUE TITLE
Improve documentation for the config system and types

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3120]
We unfortunately have very poor documentation coverage for our config system. Several config types have no documentation. For example:

![image](https://user-images.githubusercontent.com/3893054/96360203-e7106300-10e8-11eb-9473-ffdd1f01c463.png)

Our overview on "Configuration" doesn't do much to explain how to use the config system either: https://docs.dagster.io/overview/configuration/

The best (and only real) explanation of config schemas is in the tutorial, but it doesn't really explain the different types: https://docs.dagster.io/tutorial/basics_solids#parametrizing-solids-with-config

Understanding and using the config system is a crucial part of being productive while using Dagster. At the very least we should document the different types, and ideally we should have an in-depth guide about how to use the config system as a whole.

**Comment by rexledesma** [comment]
Addressed by https://github.com/dagster-io/dagster/commit/5218af84a0abb3dfd9e41d9aa421bcbe24375ed3!
