### ISSUE TITLE
attempted relative import with no known parent package

### ISSUE THREAD

**Issue by nuruladroady** [dagster-io/dagster#3122]
I have a file structure a.py and b.py and c.py is the result of a combination of two files a.py and b.py

c.py file has the following structure:

from .a import hello, good
from .b import hello1, good1
from dagster import repository
from dagster.utils import file_relative_path

@repository
def combined_repository ():
  return [hello, good, hello1, good1]

with the workspace.yaml configuration

load_from:
  - python_file: c.py

but got error attempted relative import with no known parent package, how to solve it?

**Comment by m50d** [comment]
How did you solve it?
