### ISSUE TITLE
More details in Docs on how to write testable pipelines

### ISSUE THREAD

**Issue by nancydyc** [dagster-io/dagster#3124]
We need to write more examples to demo how to use [pipelineExecutionResult](https://docs.dagster.io/_apidocs/execution#pipeline-and-solid-results). This is what we have right now [https://docs.dagster.io/examples/pipeline_unittesting](https://docs.dagster.io/examples/pipeline_unittesting)

**Comment by yuhan** [comment]
https://docs.dagster.io/concepts/testing#examples
