### ISSUE TITLE
Introduce selector in docs

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3125]
Could either be in the tutorial or in the config section

**Comment by helloworld** [comment]
Related: https://github.com/dagster-io/dagster/issues/3120

**Comment by yuhan** [comment]
as we are planning to make the tutorial less heavy, it'd make sense to introduce selector in the config overview and link api reference in the overview. so im categorizing it to "docs:content-how-to"

**Comment by yuhan** [comment]
is https://docs.dagster.io/_apidocs/config#dagster.Selector good enough to close this issue?
