### ISSUE TITLE
Outdated screenshots of Dagit UI

### ISSUE THREAD

**Issue by chenbobby** [dagster-io/dagster#3127]
## Problem
The Dagit UI gradually iterates, but screenshots in the documentation articles do not get updated. This might be confusing to newcomers who see something different on their `latest` Dagit UI.

PNG files can be found in this folder: [dagster/docs/next/public/assets/images/tutorial](https://github.com/dagster-io/dagster/tree/master/docs/next/public/assets/images/tutorial).

For example, [inputs_figure_one.png](https://github.com/dagster-io/dagster/blob/master/docs/next/public/assets/images/tutorial/inputs_figure_one.png) is using Dagit v0.7.2

![inputs_figure_one.png](https://raw.githubusercontent.com/dagster-io/dagster/master/docs/next/public/assets/images/tutorial/inputs_figure_one.png)

## Solutions
1. Ignore these issues until the Dagit UI is stabilized, then try solutions (2) or (3).
1. Update screenshots for now, and revisit screenshots in documentation every N releases.
1. Create a checklist of screenshots that need to be reviewed/recreated whenever the Dagit UI changes.
1. Reframe the screenshots to parts of the Dagit UI that are least likely to change.
1. ??? 🤷‍♀️

**Comment by mgasner** [comment]
There is a script to generate these screenshots that probably needs to be run as part of releases/kept up to date: https://github.com/dagster-io/dagster/blob/master/docs/generate_screenshots.test.js

**Comment by nancydyc** [comment]
https://dagster.phacility.com/D5225 will solve this problem

**Comment by nancydyc** [comment]
Landed diff [D5225](https://dagster.phacility.com/D5225)
