### ISSUE TITLE
Remove deprecated schedule/timezone functions just before 0.10.0 release

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3128]
Tracking these changes here:
- Make 'execution_timezone' a required argument on schedules
- Remove the 'delta' argument to date_partition_range
- Remove the 'schedule' decorator in favor of 'cron_schedule', which has partitions (?)
- Turn warning into an error when partitioned schedule start_dates aren't at the start of the period

**Comment by alangenfeld** [comment]
other 0.10.0 breaking change to consider: make `canTerminate` take pipeline_run instead of just id (since the resolver where its called already has the full run)

**Comment by alangenfeld** [comment]
assume this is resolved
