### ISSUE TITLE
Helm chart uses a mix of camel case and snake case

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3129]
Helm docs recommend camel case https://helm.sh/docs/chart_best_practices/values/#naming-conventions and most of our current helm chart is in camel case, so would recommend standardizing on camel.

**Comment by rexledesma** [comment]
We can enable [yamllint](https://github.com/adrienverge/yamllint) to remove some formatting problems. Unfortunately, there's no enforcement for camelCase so that will have to be enforced manually on the `values.yaml`

**Comment by natekupp** [comment]
Will be addressed by https://dagster.phacility.com/D5781 and released in 0.10.0
