### ISSUE TITLE
Dagit swallows DauphinInvalidStepError details

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3131]
After UserFacingGraphQLError(DauphinInvalidStepError(invalid_step_key=step_key)) is raised, dagit does not display the offending step key and instead displays the message below
  
<img width="570" alt="Screen Shot 2020-10-21 at 12 29 23 PM" src="https://user-images.githubusercontent.com/6024687/96749682-21079080-1399-11eb-88ec-f5a420501162.png">

**Comment by hellendag** [comment]
Do you have repro steps for this?

**Comment by hellendag** [comment]
@catherinewu Ping for repro steps. :)
