### ISSUE TITLE
Improve test coverage for postgres event log storage

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3137]
For run storage and schedule storage, we have a shared test suite in Dagster core that runs tests across both the sqlite and Postgres implementations of the run storages. 

This is not true for event log storage, so the Postgres event log storage is missing a bit of coverage. Also any new tests need to be manually added to the postgres test suite. 

These tests should be refactored similarly to the run storage and schedule storage tests.

**Comment by xinbinhuang** [comment]
@helloworld  I will take a look at this.

**Comment by helloworld** [comment]
It's all yours! I'll assign this to you

**Comment by xinbinhuang** [comment]
Sorry for the late update on this. I was occupied by other things in the last couple of weeks. Will try to start on this in the next couple of days

**Comment by helloworld** [comment]
Sounds great! Please let me know if you run into any issues.

**Comment by prha** [comment]
I think this is already done...
