### ISSUE TITLE
too much whitespace in integrated log viewer?

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3150]
![Screen Shot 2020-10-26 at 4 30 13 PM](https://user-images.githubusercontent.com/427016/97239334-9532a180-17a8-11eb-9ec5-2e34fac44472.png)

**Comment by hellendag** [comment]
@mgasner Which whitespace are you referring to? The whitespace caused by the left column wrapping?

**Comment by mgasner** [comment]
aha yeah i guess that's it

**Comment by hellendag** [comment]
Great! The columns are width-adjustable, so I think this can be closed.
