### ISSUE TITLE
timezone offsets have reversed signs in dagit dropdown

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3151]
![Screen Shot 2020-10-26 at 4 31 43 PM](https://user-images.githubusercontent.com/427016/97239402-c4e1a980-17a8-11eb-916d-683677835274.png)

**Comment by mgasner** [comment]
might be nice to have CET in here also

**Comment by mgasner** [comment]
![Screen Shot 2020-10-26 at 4 32 34 PM](https://user-images.githubusercontent.com/427016/97239430-dc209700-17a8-11eb-9311-eb937fe3f5f3.png)

**Comment by mgasner** [comment]
also weird ^^

**Comment by hellendag** [comment]
Looks like CET is already in the list.
