### ISSUE TITLE
Feedback input within Dagit

### ISSUE THREAD

**Issue by hellendag** [dagster-io/dagster#3152]
It would be useful to have a low-friction way for Dagit users to provide in-app feedback about bugs and feature requests, possibly with a file input to upload a screenshot of the relevant issue. This can be a really useful way to surface otherwise unknown issues to the team.

**Comment by natekupp** [comment]
This project will likely have a platform component as well—presumably we can just add an endpoint to the telemetry service to support this

**Comment by hellendag** [comment]
It would still be nice to have this, but I'm going to close it until we can actually devote some time to it.
