### ISSUE TITLE
Confusing error when run config validation fails

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3161]
Some of the config validation errors can be confusing for users who are not familiar with the error syntax. For example, user had a solid that expected only one input and the user accidentally both passed an input within the @pipeline fn and also from the run_config. User received error “Undefined field “inputs” at path root:solids:get_timers. Expected: “{ outputs?: [{ result?: { json: { path: String } pickle: { path: String } } }] }“.” which is less clear than ~"Solid expected 1 input(s) for input name X, but received 2 input(s)"

**Comment by catherinewu** [comment]
another report of confusing graphql error: https://github.com/dagster-io/dagster/issues/3186

**Comment by mgasner** [comment]
i don't think that #3186 has anything to do with this?

**Comment by catherinewu** [comment]
I think they're both examples of config errors that are hard for users unfamiliar with graphql to understand
