### ISSUE TITLE
Re-execution tooltip no longer explains why it is disabled

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3164]
Users may get confused about why re-execution is disabled and how to enable it. The re-execution buttons used to suggest configuring persistent storage in order to use re-execution but that seems to have been removed

<img width="1536" alt="Screen Shot 2020-10-29 at 3 29 33 PM" src="https://user-images.githubusercontent.com/6024687/97623158-a0314000-19fb-11eb-81bf-c7644166b597.png">

**Comment by hellendag** [comment]
The alt tag still has that information, but it should probably be consolidated into the tooltip.

**Comment by sryza** [comment]
Our current behavior is not to disable it, and rather to let the user experience an error when they kick off the reexecution, if their IO manager doesn't support it.  The error will come up almost immediately in most cases and can be made to be pretty informative.

In light of the above, I'm going to close this.

cc @alangenfeld who maybe knows more about this than me?
