### ISSUE TITLE
when backfilling a subselection, auto-filter to that subselection

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3173]
User feedback:
"I’m currently playing with a little subset of solids, backfilling them for a couple of days. What I experienced that after starting the backfill a green message will pop up with the backfill id and the search bar will be populated with that, so only the corresponding states would be shown. What would be great to add is the solid subset filter as well, so if we have 70 steps only those, rerun by the backfill would show up in the table."

**Comment by bengotow** [comment]
Addressed in https://dagster.phacility.com/D5346
