### ISSUE TITLE
How to make multiprocess execution fast for simple small pipelines?

### ISSUE THREAD

**Issue by manuelma** [dagster-io/dagster#3177]
I'm trying to use multiprocess execution to speed up the execution of simple pipelines, up to 20 solids. My assumption (maybe incorrect) is that multiprocess execution will parallelize the execution of different 'branches' in my pipeline and everything will be faster. However, that's not the case. I have built a simple example to illustrate my point:

```python
from dagster import (
    SolidDefinition,
    DependencyDefinition,
    InputDefinition,
    OutputDefinition,
    PipelineDefinition,
    Output,
    execute_pipeline,
    reconstructable,
    DagsterInstance,
)
import timeit


def sleeper_fn(context, inputs):
    units = inputs["units"]
    yield Output(value=units, output_name='total')


def giver_fn(context, inputs):
    yield Output(value=0, output_name='out_1')
    yield Output(value=1, output_name='out_2')
    yield Output(value=2, output_name='out_3')
    yield Output(value=3, output_name='out_4')


def total_fn(context, inputs):
    in_1 = inputs["in_1"]
    in_2 = inputs["in_2"]
    in_3 = inputs["in_3"]
    in_4 = inputs["in_4"]
    yield Output(value=in_1 + in_2 + in_3 + in_4)


def define_sleepy_pipeline():
    giver = SolidDefinition(
        name="giver",
        input_defs=[],
        compute_fn=giver_fn,
        output_defs=[
            OutputDefinition(name='out_1'),
            OutputDefinition(name='out_2'),
            OutputDefinition(name='out_3'),
            OutputDefinition(name='out_4'),
        ],
    )
    sleepers = [
        SolidDefinition(
            name="sleeper" + str(k),
            input_defs=[InputDefinition(name='units')],
            compute_fn=sleeper_fn,
            output_defs=[OutputDefinition(name='total')],
        )
        for k in range(1, 5)
    ]
    total = SolidDefinition(
        name="total",
        input_defs=[
            InputDefinition(name='in_1'),
            InputDefinition(name='in_2'),
            InputDefinition(name='in_3'),
            InputDefinition(name='in_4'),
        ],
        compute_fn=total_fn,
        output_defs=[OutputDefinition()],
    )
    return PipelineDefinition(
        name="sleepy",
        solid_defs=[giver] + sleepers + [total],
        dependencies={
            'giver': {},
            'sleeper1': {'units': DependencyDefinition('giver', 'out_1')},
            'sleeper2': {'units': DependencyDefinition('giver', 'out_2')},
            'sleeper3': {'units': DependencyDefinition('giver', 'out_3')},
            'sleeper4': {'units': DependencyDefinition('giver', 'out_4')},
            'total': {
                'in_1': DependencyDefinition('sleeper1', 'total'),
                'in_2': DependencyDefinition('sleeper2', 'total'),
                'in_3': DependencyDefinition('sleeper3', 'total'),
                'in_4': DependencyDefinition('sleeper4', 'total'),
            },
        },
    )


if __name__ == '__main__':
    instance = DagsterInstance.local_temp()
    reconstructable_pipeline = reconstructable(define_sleepy_pipeline)
    pipeline = define_sleepy_pipeline()
    run_config_multiprocess = {
        "execution": {"multiprocess": {}},
        "storage": {"filesystem": {}},
        "loggers": {"console": {"config": {"log_level": "CRITICAL"}}},
    }
    run_config_in_process = {
        "loggers": {"console": {"config": {"log_level": "CRITICAL"}}},
    }
    print(
        timeit.timeit(
            "execute_pipeline(reconstructable_pipeline, run_config=run_config_multiprocess, instance=instance)",
            globals=locals(),
            number=10,
        )
    )  # prints 31.894213319999835
    print(
        timeit.timeit("execute_pipeline(pipeline, run_config=run_config_in_process)", globals=locals(), number=10)
    )  # prints 0.38577169999916805
```

So in this example, multiprocess execution is about 100 times slower than 'normal' in-process execution.

Reading through the doc, I came to the conclusion (again, possibly wrong) that the overhead is due to using the filesystem as storage system. And then, the next conclusion is multiprocess execution is meant for something else than my type of example.

Anyways, am I making any sense here? What do I need to do to make multiprocess execution of these type of simple pipelines fast?

**Edit**: my dagster version is 0.9.15 (and python's 3.7.9)

**Comment by schrockn** [comment]
With the pipeline you've posted here a slowdown of this magnitude is totally expected. 

Each step in your pipeline will incur a process start overhead and the body of your compute functions do virtually no computation. Multiprocessing will only improve performance if the body of you solids are expensive enough to actually get benefit from the parallelism.

In this case process start overhead and filesystem operations dominate. If you inserted a call of `time.sleep(10)` in each solid body (to simulate, say, a large amount of processing on a dataframe) you would find there would be a performance increase.

**Comment by manuelma** [comment]
Thanks very much! That confirm my suspicions.

I was thinking about trying to implement a custom `SystemStorageDefinition` using `multiprocessing.Value` to share stuff across solids in shared memory. Do you think that could work in conjunction with the `MultiprocessExecutor`?

Another idea was to implement a custom `Executor` that uses `threading` instead of multiprocess, but I haven't checked how much work would it be.

**Comment by manuelma** [comment]
I went with a custom `Executor` that is a 'clone' of `MultiprocessExecutor` but uses python `threading` instead of `multiprocessing`. It works fantastic for my dumb pipelines. The thing is, for my use case, I typically have several solids that do very little and just pass a url for the next solid to do the heavy stuff. I am thinking that I would probably want to merge these 'dummy' solids into the ones that really do work, to avoid spawning too many threads. But for now I'm happy with what I'm getting.

**Comment by schrockn** [comment]
That's great! I'm glad the multithreaded executor wasn't too much trouble
