### ISSUE TITLE
Provide python example or API for launching a run over the GraphQL API (or using it more generally)

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3178]
Based on user feedback. Assigned to @yuhan for triage/cataloging

**Comment by helloworld** [comment]
I wrote this a while ago: https://docs.dagster.io/overview/graphql-api

Let me know if there's anything that's missing or we should elaborate on

**Comment by schrockn** [comment]
Oh did not see that! I think a code sample of invoking in from python using `requests` would round it out nicely

**Comment by helloworld** [comment]
Good call

**Comment by jwalker** [comment]
Documentation on invoking via python requests module would be awesome. Any eta on this or possible routes to take?

**Comment by schrockn** [comment]
While not a wholly satisfactory answer here is an example of invoking the GitHub graphql API with python requests. https://gist.github.com/gbaman/b3137e18c739e0cf98539bf4ec4366ad

What exactly are you trying to do? That could inform what example we provide.

**Comment by gibsondan** [comment]
@jwalker there's also an example in one of our unit tests that makes python requests against dagit: https://github.com/dagster-io/dagster/blob/master/examples/deploy_docker/tests/test_deploy_docker.py#L124

**Comment by echen805** [comment]
Hi Dagster team, appreciate the quick feedback and awesome product so far! I work with @jwalker so I can help to monitor this ticket. 

> What exactly are you trying to do? That could inform what example we provide.

What we're trying to accomplish is launch a pipeline via python requests. The links that you provided are super helpful, especially the examples in the unit tests. One thing I am curious on is if schedulers are always required when launching repositories? I noticed that the exposed API with GraphQL is LaunchPipelineExecution but it requires a scheduler each time. 

I can help to contribute, write up a working example that sends a requests to the LaunchPipelineExecution and returns back a status and result from the pipeline. That was essentially the issues I was facing, the documentation is good for individual parts but working on connecting an entire system was not as easy to figure out.

**Comment by gibsondan** [comment]
Hi @echen805 - I'm not sure what you mean by "schedulers are always required" - could you give an example? I don't see a scheduler arg in the launchPipelineExecution mutation.

**Comment by echen805** [comment]
Ah sorry about that, I misunderstood some parts. After rereading my code, this is the situation:

I'm trying to launch a pipeline in a docker container from using Postman (or Python requests from another project). This is just a basic test for me to better understand how Dagster can be incorporated and used in a system. 

The error message I got was with the repository needing a schedule but I realized that was because I didn't have a scheduler.yaml file. I think the docs make sense, just took a bit of finagling on my end since everything was detailed but in separate sections. 

One weird thing that I noticed was that when running on the Playground, I would hit an error about repositoryLocationName not valid but when I did the same in Postman, it ran successfully. This is the curl call that is copied from the Playground:
```
curl 'http://monad-task-mgr_monad-task-mgr_1:3000/graphql' \
            -H 'Accept-Encoding: gzip, deflate, br' \
            -H 'Content-Type: application/json' \
            -H 'Accept: application/json' \
            -H 'Connection: keep-alive' \
            -H 'DNT: 1' \
            -H 'Origin: http://localhost:3000' \
            -H 'pipelineName: hello_pipeline' \
            -H 'repositoryName: hello_repos' \
            -H 'repositoryLocationName: hello_dagster.py' \
            -H 'runConfigData: [object Object]' \
            -H 'mode: default' \
            --data-binary '{"query":"mutation ExecutePipeline(\n  $repositoryLocationName: String!\n  $repositoryName: String!\n  $pipelineName: String!\n  $runConfigData: RunConfigData!\n  $mode: String!\n) {\n  launchPipelineExecution(\n    executionParams: {\n      selector: {\n        repositoryLocationName: $repositoryLocationName\n        repositoryName: $repositoryName\n        pipelineName: $pipelineName\n      }\n      runConfigData: $runConfigData\n      mode: $mode\n    }\n  ) {\n    __typename\n    ... on LaunchPipelineRunSuccess {\n      run {\n        runId\n      }\n    }\n    ... on PipelineConfigValidationInvalid {\n      errors {\n        message\n        reason\n      }\n    }\n    ... on PythonError {\n      message\n    }\n  }\n}\n"}' --compressed

```

**Comment by echen805** [comment]
Ah sorry, I should have included that. This is the error message from playground unless there's more that I can get somewhere else?
```
{
  "error": {
    "errors": [
      {
        "message": "Variable \"$repositoryLocationName\" of required type \"String!\" was not provided.",
        "locations": [
          {
            "line": 1,
            "column": 26
          }
        ]
      }
    ]
  }
}
```

**Comment by nancydyc** [comment]
Hi @echen805 , I'm currently working on writing how to use python-gql to execute a pipeline. Hope it would be helpful to you. 
https://gist.github.com/nancydyc/6d6fef6cc9bb9aa73802a4e6c1f81cf5

Before run the script above (assume you've already install dagster dagit):

- `pip install --pre gql[all]` 
If it doesn't work, try `pip install --pre gql\[all\]` 
(This is a GraphQL client for Python 3.6+. [graphql-python documentation](https://github.com/graphql-python/gql))
- Create a pipeline repository. The link to the example repo above: https://gist.github.com/nancydyc/190f333f66b5bdc2bf20ee1f4dd1e980
- In your terminal, bring up Dagit, loading repo by file `dagit -f repo.py`
- Laster step, open another tab in your terminal, run `python trigger_pipeline_gql.py`

**Comment by gibsondan** [comment]
@echen805 sorry for the confusion, there are actually two different 'Playground" views in Dagster - my previous comment referred to the Playground tab in Dagit for a given pipeline, but I now see that you were clearly referring to the GraphQL Playground that lets you run GraphQL queries against the server.

From your description, this looks like an unintuitive property of the built-in GraphQL playground from the flask_graphql library. There are two tabs at the bottom - HTTP Headers and Query Variables. Confusingly, setting your variables in HTTP Headers only affects the "Copy Curl" command, but doesn't fill in the variables if you hit Play in the Playground. If you copy the same dict into the Query Variables tab, pressing Play should apply them to the resulting query.

If you do that does the Playground query work as expected?

**Comment by echen805** [comment]
D'oh! Sorry about that, that makes so much sense and explains why it worked in Postman too then. 

Appreciate the quick responses! And thank you everyone for all the examples!

**Comment by yuhan** [comment]
Most of the content discussed here has been document the GraphQL API usage [here](https://docs.dagster.io/concepts/dagit/graphql)
 
Closing this issue in favor of https://github.com/dagster-io/dagster/issues/3887 which will handle the remaining content gaps, e.g. using `requests` to make queries.
