### ISSUE TITLE
Test/validate K8s release deliverables

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#3179]
There have been several occurrences when the k8s parts of the release fail and go unnoticed for up to weeks, eventually getting caught by a user. We could consider adding these to the release validate command.

- k8s images (https://github.com/dagster-io/dagster/issues/3040)
- helm charts

Ideally there would also be an integration test using a latest helm install with the latest images

**Comment by rexledesma** [comment]
re: helm chart automation, could be worthwhile to implement https://github.com/helm/helm/issues/7197 real quick and use that for validation

**Comment by chainlink** [comment]
Running helm template and piping to https://github.com/instrumenta/kubeval is a cheap way to ensure valid manifests (e2e is best to catch all issues though) If there's interest I'm happy to look at PR'ing.

https://github.com/gruntwork-io/terratest is amazing for testing different code paths in a helm chart (but does require go)

**Comment by alangenfeld** [comment]
collapsing
