### ISSUE TITLE
Automatic retries for solids

### ISSUE THREAD

**Issue by liezl200** [dagster-io/dagster#3194]
Is there a way to configure an automatic retry for a solid? I don't want to fail the whole workflow and have to manually retry.

**Comment by helloworld** [comment]
Hey @liezl200, you can raise `RetryRequested` from a solid to control retry behavior from a solid. It looks like we're missing documentation coverage about this–I've made a separate issue to resolve that. 

For example:

```
@solid
def my_solid(_):
    try:
         do_something()
    except:
         raise RetryRequested(max_retries=3)
```

Does this work for you?

**Comment by liezl200** [comment]
Yes, thank you @helloworld for the quick reply! Will give it a shot and report back here if there are any issues.
