### ISSUE TITLE
S3ComputeLogManager is slow with minio 

### ISSUE THREAD

**Issue by mrdrprofuroboros** [dagster-io/dagster#3196]
I'm deploying dagster with self-hosted s3 storage
With zenko/cloudserver (https://hub.docker.com/r/zenko/cloudserver/) everything works predictably well, but minio (https://hub.docker.com/r/minio/minio/) is 11x slower when using S3ComputeLogManager. Intermediate storage works as well as zenko/cloudserver so the issue might be connected to the difference between  fileobj_upload (compute logs) and put_object (intermediates)

minio is a preferred s3 server because of its nice GUI

Here are the cProfile traces of both deployments, if it could be of any help
[minio.txt](https://github.com/dagster-io/dagster/files/5497619/minio.txt)
[zenko.txt](https://github.com/dagster-io/dagster/files/5497620/zenko.txt)
<img width="1292" alt="minio" src="https://user-images.githubusercontent.com/21140507/98300130-e40ee100-1fc9-11eb-885b-d0714fc0358c.png">
<img width="1287" alt="zenko" src="https://user-images.githubusercontent.com/21140507/98300156-ef620c80-1fc9-11eb-98d8-775e98580691.png">

**Comment by prha** [comment]
From a lot more debugging from dmitry: https://dagster.slack.com/archives/G015NFL26TU/p1623431529032200

**Comment by prha** [comment]
There's an interaction between minio / boto about uploading empty files.   We should try out a solution / option in the S3ComputeLogManager to refrain from uploading empty files.

**Comment by prha** [comment]
Just landed https://dagster.phacility.com/D8354, which should allow you to configure your S3ComputeLogManager with the config option `skip_empty_files`.  Confirmed with a local minio instance that the upload does not hang.  This should go out with the upcoming `0.11.14` release.
