### ISSUE TITLE
Dagster 0.9.18:  @pipeline 'pipeline' has unmapped output 'result'. (my return type is `-> None`)

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#3198]
Hi, 

I'm trying to update dagster to the latest version in my pipeline and I'm getting this error because my pipeline function is annotated with `-> None` as the return type.

The error disappears if I remove the return type, but that would make mypy unhappy (and `#type: ignore` doesn't work well with annotated functions). 

Should the error be raised if the return type is `None`? If yes is there any workaround you can suggest? I'd prefer not disabling mypy if possible.

**Comment by schrockn** [comment]
Could you provide more details about the error?

Based on the information given, I believe you are reporting an error that dagster is communicating that is separate from mypy.

In this case we've added an experimental capability for pipelines to have outputs and dagster is interpreting `-> None` to. indicate that the pipeline itself has an output.

If that is the case the workaround would be to set output defs to the empty array `@pipeline(output_defs=[])` in your decorator.

**Comment by amarrella** [comment]
Hi @schrockn, thanks!

> Could you provide more details about the error?

A reproducer would be
```python
@pipeline
def pipeline() -> None:
  example = my_solid()
```

mypy requires to keep the `-> None` on functions that don't return anything.

But when running the pipeline in dagster (e.g. with execute_pipeline in a unit test) this would throw the error above.

> In this case we've added an experimental capability for pipelines to have outputs and dagster is interpreting `-> None` to. indicate that the pipeline itself has an output.

> If that is the case the workaround would be to set output defs to the empty array `@pipeline(output_defs=[])` in your decorator.

Setting `output_defs` to the empty list worked, thanks!

**Comment by schrockn** [comment]
To be clear this is a pretty bad user experience, but I'm glad you are unblocked

**Comment by sryza** [comment]
I think it's worth keeping this issue open.  While there's a workaround, I think it's worth thinking about whether there's a way to provide an experience that doesn't require a workaround.

**Comment by sryza** [comment]
One approach would be to special-case None when inferring OutputDefinitions from mypy annotations.

**Comment by schrockn** [comment]
Alex fixed this pretty definitively: https://dagster.phacility.com/D5048

**Comment by sryza** [comment]
Oh perfect!

**Comment by amarrella** [comment]
Thanks! The speed at which you folks work is incredible!

**Comment by alangenfeld** [comment]
fix linked above will go out in the release today
