### ISSUE TITLE
Make the repository location name more obvious in Dagit

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3205]
Currently, the repository name and repository location name are just displayed next to each other in the Dagit repository picker. 

We should make it more obvious about which one is which. This would help expose the concept of repository locations to the user as well.

**Comment by gibsondan** [comment]
Agreed - this ties in nicely with work that @hellendag is currently doing on rewriting most of our permalinks, many of the new UIs and URLs include the location more prominently (not sure about "good first issue" as a result though)
