### ISSUE TITLE
'Open in playground' on schedule page doesn't set preset or mode

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#3206]
On the schedules page

![image](https://user-images.githubusercontent.com/22018973/98602461-7d7e1180-22ae-11eb-8583-6dd1b87e6390.png)

To me, `Open in Playground` conveys that I will see the same config as clicking `View Configuration`. Instead it just goes to the usual playground.

In place of actually opening the playground to the set preset and mode, it could be switched to `Open Pipeline in Playground`, which I think conveys better that it's the usual playground

**Comment by hellendag** [comment]
The config view and playground menu items have been removed in favor of just encouraging people to go directly to the pipeline.
