### ISSUE TITLE
[dagit] revisit "kind" tag and tags preview system 

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#3210]
We have this pretty basic system that got added a while ago where we show a little box in the bottom right of the solid in zoomed out view based on the `kind` tag. There is also some bespoke undocumented sibling tags to the kind, such as one that previews the SQL query for `kind: sql` solids that show up if you click on the little box.

This could use an update and some documentation

**Comment by schrockn** [comment]
And it is a high value feature. Strong endorse.

**Comment by catherinewu** [comment]
To add a bit: emerald shared that it would be useful to configure some elements (such as color, add icons, etc) of the dagit definition view in a more general way. For example, a solid's box could be a shade of red to signify it's high priority and with an emoji to signify it's also self-healing. More info in [3216](https://github.com/dagster-io/dagster/issues/3216).

**Comment by bengotow** [comment]
Hey folks! I'm going to untag Dagit for now. On the front-end, I think the existing system behind the "kind" tag is pretty nice - Ops can specify a "kind" metadata tag, which then allows plugin-like React components to use other op metadata key-values to do freeform things like render a SQL statement or preview an ipynb notebook from the op sidebar. 

It'd be cool to see more of our connector libraries use this feature and shouldn't require too many dagit changes unless we decide to re-architect things. This might be a fun hack day focus.

**Comment by sryza** [comment]
I'm going to close this as part of garbage collection because I don't think there's a clear proposal or problem statement. Feel free to disagree and reopen.
