### ISSUE TITLE
Enable users to configure CSS of solids in pipeline definition view

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3216]
## Use Case
The user would like to configure some visual elements of solid "boxes" in the pipeline definition view, such as the color of the box or adding icons/symbols. The current use case is to convey the priority of a solid (ie stuff related to payments would high priority) and to convey traits such as whether the solid is "self-healing" in the next run or needs to be manually recovered. 

## Ideas of Implementation
I hear there is a history of hacking stuff in the dagit UI by adding a `kind` field to solid `tags`...

**Comment by alangenfeld** [comment]
#3210

**Comment by hellendag** [comment]
Closing in favor of https://github.com/dagster-io/dagster/issues/3210.
