### ISSUE TITLE
[docs] - Document reserved words

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3219]
## Summary

Add documentation specifying reserved keywords. This documentation should include the error that is raised when a reserved keyword is used.

---

## Resources

- **Originating resource**: https://dagster.phacility.com/D4985
- [Partial (?) list in code](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/utils.py)
- [Error if reserved keyword is used](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/utils.py#L53)

**Comment by erinkcochran87** [comment]
General thoughts here:

- The documentation we produce here should include the error that's raised when a reserved keyword is used
- Can we automate pulling this into the docs? It'd be nice to dump this list in instead of creating/maintaining it manually - cc @yuhan

**Comment by erinkcochran87** [comment]
Tracking this in Notion - closing this.
