### ISSUE TITLE
Could dagit highlight connections?

### ISSUE THREAD

**Issue by Aylr** [dagster-io/dagster#322]
In many dag layouts (especially when there are solids with multiple inputs and outputs, it can be difficult to visually inspect solid wiring. The following screenshot illustrates this:
<img width="2032" alt="screen shot 2018-11-21 at 2 34 05 pm" src="https://user-images.githubusercontent.com/928247/49386707-65261500-f6dd-11e8-8078-c55214c6d76d.png">

## Ideas

1. What if individual inputs/outputs were clickable which could then cause the "patch cable" and "port/jack" to highlight. Something clean could also be displayed in the *info* tab.
<img width="1177" alt="screen shot 2018-12-03 at 9 29 06 am" src="https://user-images.githubusercontent.com/928247/49387117-48d6a800-f6de-11e8-85ca-910cf093636c.png">

2. What if the current Solid selection behavior remains the same, except that inputs (and maybe outputs?) to that solid highlight their upstream dependencies (and maybe downstream?)
<img width="1528" alt="screen shot 2018-12-03 at 9 35 38 am" src="https://user-images.githubusercontent.com/928247/49387399-f944ac00-f6de-11e8-9d7b-f539de7c0f84.png">

**Comment by schrockn** [comment]
[image: Screen Shot 2018-12-03 at 10.59.09 AM.png]
This is implemented in master
