### ISSUE TITLE
Add documentation for user-defined k8s config.

### ISSUE THREAD

**Issue by chenbobby** [dagster-io/dagster#3223]
# Feature Description
Users can pass k8s config to their k8s resources via pipeline definition tags or pipeline run tags. The tag key must be `dagster-k8s/config`.

An example usage can be seen in [issue #2748](https://github.com/dagster-io/dagster/issues/2748#issuecomment-709999339), where the user is defining container resource requests, limits, and ports.

# Documentation Requirements
- Config schema (or reference to a config schema) with all possible key-values
- Example usage with pipeline definition tags
- Example usage with pipeline run tags

# Proposed Location of New Docs
- [API docs for `dagster-k8s`](https://docs.dagster.io/_apidocs/libraries/dagster_k8s)
- [API docs for `dagster-celery-k8s`](https://docs.dagster.io/_apidocs/libraries/dagster_celery_k8s)

**Comment by yuhan** [comment]
believe it's included in /deploying/k8s#custom-kubernetes-configuration
reopen if it's not the case
