### ISSUE TITLE
Support MySQL

### ISSUE THREAD

**Issue by JBrVJxsc** [dagster-io/dagster#3227]
## Use Case
Currently, Dagster only supports Postgres. It would be nice to also support MySQL.

**Comment by nancydyc** [comment]
#3550

**Comment by sidkmenon** [comment]
Still a work in progress - current changes can be found in this diff: https://dagster.phacility.com/D6381. 

Have the skeleton of listen/notify done + schema changes & BK changes finished. 

I still do need to figure out how to idiomatically modify the `SELECT` query  st. a watcher thread gets only the newly updated events. also the alembic migrations logic still needs work, as well as testing (both of writing tests & performance testing).

**Comment by sidkmenon** [comment]
Update - https://dagster.phacility.com/D6412 shows a stack of diffs that have the polling working. Still working on testing & migrations logic before this is ready to land.

**Comment by sidkmenon** [comment]
Update - https://dagster.phacility.com/D6617 shows a stack of diffs with MySQL supported (test suite green). Still needs some refactoring wrt. the migrations logic, docs, & general cleanup. Thank you for your patience!

**Comment by JBrVJxsc** [comment]
Thank you for the updates! looking forward to it!

**Comment by sidkmenon** [comment]
Update - https://github.com/dagster-io/dagster/commit/7eff7a85a43691ad909275d936efb4d32d584b72 pushes `dagster-mysql` to master! But I'd hold off on using it, we're just going to do some performance testing to confirm that everything is working as expected. Thanks again for your patience - will update this ticket (ASAP) when the perf testing is completed!

**Comment by JBrVJxsc** [comment]
nice! thank you so much! @sidkmenon

**Comment by JBrVJxsc** [comment]
@sidkmenon may i ask how long would performance testing normally take?

**Comment by sidkmenon** [comment]
Hi @JBrVJxsc, thank you for your patience! I wrote a pipeline to stress-test the MySQL storage backend yesterday & things are looking okay. As far as I can tell from testing so far, everything seems comparable to performance when using Postgres.

Right now, I have a few tasks remaining:

1: Launching a backfill until there’s 10k runs
2: Checking that assets are correctly logged, etc.
3: Verify that sensors kick off a run when expected

In my estimation this shouldn’t take more than a day or so more. I will update at the EOD today with my progress. As long as there’s no glaring issues, MySQL storage should be able to be included in the release tomorrow.

**Comment by sidkmenon** [comment]
Hi @JBrVJxsc , things are looking ok with respect to performance testing! MySQL storage should be included in tomorrow's release & should be usable. Please let me know if there are any issues at all and I'll be very happy to assist.

**Comment by JBrVJxsc** [comment]
@sidkmenon thank you so much!!!!!! this is awesome!
