### ISSUE TITLE
Schedule should have a link to its associated partition set

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#3230]
here:
![image](https://user-images.githubusercontent.com/609349/99342079-ef6ed180-283f-11eb-8fbc-071d4d2e0929.png)

would be nice to be able to go directly to the partitions page; as-is, I have to click the pipeline name and then go to the partitions tab.

I know we're thinking about refactoring the sidebar anyway, so wanted to comment that it might be nice to have partitions more top-level rather than schedules: I'm probably going to set the schedule and never change it, whereas I'll likely be looking at the partitions page several times a week.

**Comment by schrockn** [comment]
💯

**Comment by schrockn** [comment]
definitely want to address this as part of the run scheduling UI work
