### ISSUE TITLE
[dagit] delete run improvements

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#3236]
Currently we only allow you to delete a run if its completed - or more specifically if you can not `terminate` it.

For the foreseeable future it's possible that the system will get in to a bad state where a user will want to delete a run that is stuck, but this prevents them.

We should introduce a way to delete a run even if we think you shouldn't, with an extra layer of friction to prevent doing it accidentally.

**Comment by hellendag** [comment]
Does the deletion already work on the back end, and we just need to allow it in Dagit?

**Comment by gibsondan** [comment]
Backend work is required for this as well

**Comment by alangenfeld** [comment]
deletion already works - I'm not sure what backend work @gibsondan is referring to 

https://github.com/dagster-io/dagster/blob/master/js_modules/dagit/src/runs/RunActionsMenu.tsx#L155-L156

**Comment by gibsondan** [comment]
to clarify - I was referring to marking these runs as failed, not deleting them. I think it's still useful to have these runs in run history.

**Comment by alangenfeld** [comment]
Alright to clarify this issue, the front end work that can be done now is:
* we should not gate the delete action on `canTerminate`
* we should throw up some more friction on the delete action always since it is destructive, especially if the run is not in a terminal state where a deletion will almost certainly put things in to a bad state if things are actually still running

I'll file a separate issue with backend work is to create a "mark as failed" command that is preferable to delete in most cases where people want deal with a run that got in to a whacked out state. Once we have that the three options of terminate, mark as failed, and delete could be presented together and as @gibsondan put it

> maybe its a dropdown and we just pick the default intelligently

**Comment by gibsondan** [comment]
https://github.com/dagster-io/dagster/issues/3239 is the related issue for mark-as-failed

**Comment by catherinewu** [comment]
Once [#3239](https://github.com/dagster-io/dagster/issues/3239) is resolved, I think we should only offer "terminate" and "mark as failed". It is hard for me to imagine a case where a user is opinionated about actually deleting the pipeline run from the runs db (although happy to be proven wrong). The only niche scenario that comes to mind is maybe someone writing secrets into run config? but not sure if solving this unlikely event is worth the risk of breaking "append only" guarantees

**Comment by catherinewu** [comment]
im actually pretty surprised that dagit offers the functionality to delete runs from the database and i think we shouldn't continue to support it unless there is a really compelling use case. "mark as failed" seems to be just as good at getting the system out of a bad state due to stuck runs.

**Comment by alangenfeld** [comment]
In my opinion we should offer delete for emergencies such as when someone accidentally puts sensitive information in plain text. I think it should be behind plenty of encouragement to use mark as failed or terminate instead, but be available in the expected place.

**Comment by hellendag** [comment]
We have now landed a bunch of changes here. All termination and deletion workflows should now use confirmation dialogs.

- Upon termination, allow the user to "force" termination, with an appropriate warning about the lack of cleanup.
- If the runs cannot be cleanly terminated (`!canTerminate`), show the warning but not the checkbox. Only "force-terminate" is available in this circumstance.
- Upon deletion, encourage the user to terminate instead. Open the termination dialog if they choose this option.
- Upon confirmation of either termination or deletion, show progress and confirmation/errors.
- Runs can now be in "canceling" or "canceled" states.
