### ISSUE TITLE
insufficient documentation when running a non-asset-aware storage

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3251]
You get this in Dagit:
![Screen Shot 2020-11-19 at 6 12 43 PM](https://user-images.githubusercontent.com/427016/99749226-e88bcd00-2a92-11eb-8982-43270fcc710d.png)
which links to https://docs.dagster.io/overview/instances/dagster-instance, which has nothing about asset-aware storage at all. (Also: what if I'm not running postgres or don't know how to locally? etc)

**Comment by sryza** [comment]
If I understand correctly, the missing documentation here is documentation on how to configure the instance-level event storage.  I.e. we'd like to have a page we can link to that says "Here's how you set up Postgres event storage?"  If that's the case, I think this issue should probably live inside the docs project or the platform project.

**Comment by nancydyc** [comment]
A link to the how-to guides [Asset Materialization](https://docs.dagster.io/examples/materializations#assets-in-dagit) in Examples which mentions `asset-aware storage` probably is more friendly to user than directly pointing to instance documentation.

**Comment by mgasner** [comment]
<img width="534" alt="Screen Shot 2021-01-06 at 2 13 18 PM" src="https://user-images.githubusercontent.com/427016/103824724-541d0000-5029-11eb-8229-6c11a9e83243.png">
yes that seems like the only place we even mention it -- we should have a dedicated doc for this i think though

**Comment by yuhan** [comment]
this seems to be a problem of insufficient instance config documentation. it could be addressed in https://github.com/dagster-io/dagster/issues/3314 where we could explain "asset-aware"

**Comment by sryza** [comment]
Our default storage is now asset aware, so I'm going to close this.
