### ISSUE TITLE
Cannot use asset store with celery k8s executor (or I'm doing something wrong)

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3252]
## Summary
I tried to run the "slack demo pipeline" (from master in Internal repo) with an asset store configured and encountered errors below in screenshot 1. Following the suggestion, I removed the s3 intermediate storage from the mode definition but then received "You have attempted to use an executor that uses multiple processes while using intermediate storage in_memory which does not persist intermediates." as seen in screenshot 2.

It seems like the fix might be to update _check_persistent_storage_requirement to accept asset store as well. 

screenshot 1:
<img width="1253" alt="Screen Shot 2020-11-19 at 9 54 17 PM" src="https://user-images.githubusercontent.com/6024687/99767060-3c101200-2ab7-11eb-869a-59e241410566.png">

screenshot 2:
<img width="1245" alt="Screen Shot 2020-11-19 at 10 31 11 PM" src="https://user-images.githubusercontent.com/6024687/99766995-197df900-2ab7-11eb-9081-b57a817b6b97.png">

## Reproduction

1. Configure asset store
2. Launch pipeline with celery k8s executor (likely also reproducible with multiprocessing executor)

**Comment by catherinewu** [comment]
Hmm, maybe this is intentionally not supported yet, not sure. I assumed it was supported because the internal demo seems to try to use it.

**Comment by yuhan** [comment]
i believe https://dagster.phacility.com/D5207 is fixing it
