### ISSUE TITLE
Multiple repositories playground pipeline trigger reset the selected repository and pipeline

### ISSUE THREAD

**Issue by szeleeteo** [dagster-io/dagster#3254]
## Summary

In a setup with multiple repositories, running any of the pipelines except from the first repository in playground reset dagit selected repository to the first repository in the list. Expected to see the selected repository that triggered the pipeline instead. 

Furthermore re-executing partial pipeline became not possible without re-switching to the original repository, and choosing the previous runs.

This happened in 0.9.19 and 0.9.20 but not earlier.

## Reproduction

repo_one/repo.py
```
from dagster import pipeline, repository, solid

@solid
def get_one(_):
    return 1

@solid(config_schema=int)
def multiply(context, number):
    result = context.solid_config * number

@pipeline
def one_pipeline():
    multiply(get_one())

@repository
def one_repo():
    return [one_pipeline]
```
repo_two/repo.py
```
from dagster import pipeline, repository, solid

@solid
def get_two(_):
    return 2

@solid(config_schema=int)
def multiply(context, number):
    result = context.solid_config * number

@pipeline
def two_pipeline():
    multiply(get_two())

@repository
def two_repo():
    return [two_pipeline]
```

workspace.yaml
```
load_from:
  - python_file:
      location_name: repo_one
      relative_path: repo_one/repo.py
  - python_file:
      location_name: repo_two
      relative_path: repo_two/repo.py
```

## Dagit UI/UX Issue Screenshots

Setting up to run two_pipeline from two_repo
![image](https://user-images.githubusercontent.com/31718589/99801056-58bc5080-2b70-11eb-9cdd-65f5374a459f.png)

Immediately after pipeline is triggered, dagit selected repo has been reset to one_repo, and re-execution is disabled.
![image](https://user-images.githubusercontent.com/31718589/99801152-886b5880-2b70-11eb-810e-1d3b00d9c3c6.png)

**Comment by hellendag** [comment]
Thanks for the report, taking a look.

**Comment by hellendag** [comment]
Two issues here:

- `localStorage` state is not being used correctly upon initialization, so a new browser tab will open to the *first* repository instead of the localStorage-tracked one. Fixing this now.
- Now that we no longer depend on the repository switcher context to load pipelines, we can start allowing execution of any pipeline in the current workspace from anywhere in Dagit. This is a newly possible feature. I'll try to get it working.
