### ISSUE TITLE
[algolia] searching "execute_solid" doesn't return corresponding api docs

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3256]
## Summary
I would expect [this](https://docs.dagster.io/_apidocs/execution#dagster.execute_solid) to be one of results when searching "execute_solid". Current results:

<img width="525" alt="Screen Shot 2020-11-20 at 9 48 58 AM" src="https://user-images.githubusercontent.com/6024687/99832714-ce470300-2b15-11eb-927d-952bb488f385.png">

**Comment by yuhan** [comment]
![image](https://user-images.githubusercontent.com/4531914/112071429-f6c72400-8b2c-11eb-981c-d5ec73b67685.png)

this is now the first result
