### ISSUE TITLE
Full view of AssetMaterialization in Dagit doesn't contain link to catalog

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3257]
Collapsed view:
![Screen Shot 2020-11-20 at 2 05 19 PM](https://user-images.githubusercontent.com/427016/99854308-6efaea00-2b39-11eb-9392-75ab9688c7df.png)

Full view:
![Screen Shot 2020-11-20 at 2 06 10 PM](https://user-images.githubusercontent.com/427016/99854367-8d60e580-2b39-11eb-9712-317dedfc4805.png)

**Comment by bengotow** [comment]
Hey folks! I dug in to this this evening and it looks like this problem has been resolved. I'm unable to reproduce on master (see screenshot, small window size makes "View Full Message" easy), and looking through the code it looks like the modal renders the identical React tree as the cell now.

![Screen Shot 2021-06-03 at 1 08 51 AM](https://user-images.githubusercontent.com/1037212/120595740-795f4000-c408-11eb-8e61-cb8680587e59.png)
![Screen Shot 2021-06-03 at 1 08 50 AM](https://user-images.githubusercontent.com/1037212/120595742-79f7d680-c408-11eb-9bb1-c4587c089054.png)
