### ISSUE TITLE
[Partition UI] Selecting "By Partition" shows materializations that do not contain a partition key

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3261]
## Summary
I expected selecting "By Partition" would only show Asset Materializations that contained a partition key. The leftmost materialization does not contain a partition key but is still shown and included in the graphs.

<img width="1536" alt="Screen Shot 2020-11-21 at 1 08 27 PM" src="https://user-images.githubusercontent.com/6024687/99887660-e9d80980-2bfa-11eb-932e-8d3db40f0cbb.png">

## Reproduction
Yield AssetMaterialization without partition; then, yield same AssetMaterialization with a partition.

**Comment by bengotow** [comment]
This has been fixed in https://dagster.phacility.com/D5298. It looks like we were just coercing the partition key to `''` instead of removing events not tied to a partition.
