### ISSUE TITLE
Smoother handling of pipeline "Failed to Start"

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3264]
## Summary
Somestimes a pipeline can fail to start; for example, this can happen if kubernetes doesn't have enough space to create the job. Opening a historical run of a pipeline that failed to start is confusing, since the page seems to try to load forever. 

Would be nice for dagit to point to a FAQ docs page explaining the reasons why a page might fail to load?

## Additional Info about Your Environment

https://www.loom.com/share/2da200c3fed44cea9fe539ecbabe10f9

**Comment by yuhan** [comment]
Pointing to FAQ docs sounds great and is def a great improvement for UX, which would be the end goal here. But prior to achieving that there's core, dagit, and docs work to do. Moving this issue to "Dagit UI/UX" lane as the most outstanding piece is error handling UX.

**Comment by bengotow** [comment]
Hey! I broke a pipeline so that it would not start and also tried inserting a delay between the starting and started states and it looks like this has been resolved by @hellendag's recent improvements to the run view! It doesn't look like you get the indefinite spinners anymore 🙌
