### ISSUE TITLE
[Pipeline run view] Selecting "Hide non matches" causes single match to be repeated infinitely

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3265]
## Summary
In the pipeline run view, I expected searching with "hide non matches" selected to show each match once. Instead, it showed one match many times (can tell it's the same match by the time stamp).

## Reproduction
See Loom

## Additional Info about Your Environment

https://www.loom.com/share/6494bc54039b40fcb84b132b64816c80

**Comment by catherinewu** [comment]
I can't reproduce this behavior, might have been a weird one-off..?

**Comment by hellendag** [comment]
We're also not able to repro -- reopen this if it happens again?
