### ISSUE TITLE
Easy to accidentally trigger "back" gesture when scrolling through horizontal modals

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3269]
## Use Case
When scrolling through the Asset UI's "Materializations over Time" Graphs view, it's easy for the user to "over-scroll" and trigger the "back" gesture (on a trackpad), causing the user to go to previous page. I think this is compounded by https://github.com/dagster-io/dagster/issues/3268 since users may expect more materializations than show up in the modal.

**Comment by hellendag** [comment]
I'll take a look.
