### ISSUE TITLE
[dagit] `--path-prefix` not considered for links in run logs

### ISSUE THREAD

**Issue by roeap** [dagster-io/dagster#3278]
## Summary
When running `dagit` under a path using the `--path-prefix` option, it seems, links within the logs displayed on the runs page do not consider the path prefix. The specific example we encounter is the clicking the `View Asset Dashboard` link. 

## Reproduction
Create a minimal pipeline that yields an `AssetMaterialization`, run dagit with `--path-prefix dagit`, and observe that the link under `View Asset Dashboard` does not include the path prefix.

**Comment by bengotow** [comment]
Resolved by https://dagster.phacility.com/D5292
