### ISSUE TITLE
remove "storage" entry in run_config

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3280]
we deprecated it in 0.10.0. will remove it in 0.11.0

**Comment by sryza** [comment]
There was some discussion on this in phabricator, right?  Did we decide to leave the storage entry there for as long as we have IntermediateStorage?

**Comment by yuhan** [comment]
Yes, we've deprecated the "storage". But as for removal, this issue will remain open until the deprecation cycle is done (0.11.0)
