### ISSUE TITLE
More actionable error message in dagit when a GraphQL request fails due to a local gRPC server being down

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3282]
## Use Case
right now if your (local, spun up by dagit) gRPC server fails in the middle of a dagit session, the error you get is very cryptic: https://dagster.phacility.com/P127

We should inform you more clearly that the repository can't be loaded anymore, and direct you to the most likely resolution here instead, which is to reload your repository location in the UI.

Some of the work @helloworld is doing for remote gRPC servers may be useful here as well - we could detect proactively that the server went down as well, rather than the next time you try to make a call out to the server.

**Comment by hellendag** [comment]
I'm pretty sure we're now surfacing these errors correctly. Please reopen if I'm overlooking anything.
