### ISSUE TITLE
Explain Celery when mentioned in docs

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3284]
## Summary
The docs assume that readers know what Celery is and what it is used for, but that's not a reasonable assumption. Many users have asked what is celery, what's the purpose of celery, how do they know if they need to use it, what will happen if they don't use it, etc.

**Comment by yuhan** [comment]
https://docs.dagster.io/deployment/custom-infra/celery
https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm-advanced#celery
