### ISSUE TITLE
[K8s run launchers x grpc user code images] Docker image is not stored in runs DB

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3285]
## Use Case
When users kick off a pipeline run with the K8sRunLauncher / CeleryK8sRunLauncher and user code deployments configured, the run launcher fetches the docker image + tag from the user code deployment but this image + tag is not saved anywhere in the events db or runs db. This is important for understanding what version of the code was running and re-producing the results. 

The easiest approach is perhaps to add this to the launch functions:
```
        self._instance.add_run_tags(
            run.run_id,
            {
                "job_image": job_image,
            }
        )
```
However, this is not super ergonomic for re-execution as (1) the tag is only visible on the Runs page but not when viewing a specific historical pipeline run and (2) lots of copy + pasting is required to actually re-execute the pipeline with that image

**Comment by rexledesma** [comment]
Looks to be resolved with https://github.com/dagster-io/dagster/commit/b55b46c2f38424a03ef8225c8326b944554b9283 cc @johannkm
