### ISSUE TITLE
[K8s run launchers x grpc user code] Unable to launch run with specific image

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3286]
## Use Case
Currently, if a user uses the K8sRunLauncher or CeleryK8sRunLauncher + GRPC user code deployments, then we do not allow users to specify a specific job image and force users to use the current image in the grpc user code deployment. 

This was originally intended to prevent users from accidentally passing in a job_image (via instance config / executor config) while expecting that the latest image within the user code server would be used. However, it seems that this is too strict as it completely blocks the ability to execute a run using a prior image tag. 

The easy fix is to remove the added validation code. We may want to add visual cues in the UX so that users are aware whether a user-specified image will be used or the grpc image.

**Comment by bengotow** [comment]
(Sorry meant to reference #3268 in the commit above, it is unrelated.)

**Comment by alangenfeld** [comment]
D5597
