### ISSUE TITLE
define_dagstermill_solid should allow users to pass in solid tags and description 

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3290]
## Summary
https://docs.dagster.io/_modules/dagstermill/solids#define_dagstermill_solid

For example, this is important for running dagstermill solids in kubernetes w/ resource constraints

**Comment by nancydyc** [comment]
When solid definition is returned, tags and description are defined by providing notebook_path. Is this what you look for?

**Comment by catherinewu** [comment]
I think users should also be allowed to pass in their own tags + description to define_dagstermill_solid

**Comment by sidkmenon** [comment]
Should be solved with https://github.com/dagster-io/dagster/commit/d6f67b2290750dede65d58720d28d6f5cc2988c4
