### ISSUE TITLE
[Docs] Introduce solid-level tags when introducing pipeline-level tags

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3291]
## Summary

It's not obvious that users can tag solids and pipelines. We should at least update [this example](https://docs.dagster.io/examples/pipeline_tags) to mention solid level tags or include a solid tag example

**Comment by sidkmenon** [comment]
Should be solved with https://github.com/dagster-io/dagster/commit/1790319f1b74751b07dce82b71b95f8b5f8a0770
