### ISSUE TITLE
[Dagit] CodeMirror area should change highlighting color and fix inconsistent auto-completion

### ISSUE THREAD

**Issue by nancydyc** [dagster-io/dagster#3292]
## Summary

1. The config editor highlight string value in red, which is distracting. My first thought was if there is anything wrong with my code.
2. Inputs is expected in this run_config, but there is no auto-completion for inputs and its value. See pic-2. This causes problem when doing auto-typing in [screenshot test](https://dagster.phacility.com/source/dagster/browse/master/docs/generate_screenshots.test.js$999). "\n" won't make inputs go to next line as expected. See messed up config in pic-3.

## Reproduction

1. Red highlighting: 
```cd examples/docs_snippets/docs_snippets/intro_tutorial/advanced/solids```
```dagit -f composite_solids.py -a composite_solids_pipeline```
Then, go to playground view.
2. Auto-completion:
Go to the composite solid test in [screenshot test](https://dagster.phacility.com/source/dagster/browse/master/docs/generate_screenshots.test.js$999) and `npm run screenshots`
``` 
    await page.type(
      ".CodeMirror textarea",
      "solids\n" +
      "load_cereals\n" +
      "solids\n" +
      "read_cereals\n" +
      "inputs\n" +
      "csv_path\n" +
      'value: "cereal.csv"\n'
    );
    await page.focus(".CodeMirror textarea");
    for (let i = 0; i < 2; i++) {
      await page.keyboard.press("Backspace");
    }
    await page.type(
      ".CodeMirror textarea",
      "read_manufacturers\n" +
      "config\n" +
      'delimiter: ","\n'
    );
    await page.focus(".CodeMirror textarea");
    for (let i = 0; i < 1; i++) {
      await page.keyboard.press("Backspace");
    }
    await page.type(
      ".CodeMirror textarea",
      "inputs\n" + "csv_path\n" + 'value: "manufacturers.csv"\n'
    );  
```

## Dagit UI/UX Issue Screenshots

![red highlight](https://user-images.githubusercontent.com/59324923/100267228-f95f9700-2f07-11eb-8f33-2a8663b92f18.png)
![no auto-completion](https://user-images.githubusercontent.com/59324923/100268042-498b2900-2f09-11eb-967c-9ec65cb4ab5b.png)
![messed up config editor](https://user-images.githubusercontent.com/59324923/100268639-2614ae00-2f0a-11eb-87c9-24bba2ef5af2.png)

**Comment by bengotow** [comment]
This is resolved by https://dagster.phacility.com/D5389!
