### ISSUE TITLE
Improve undo functionality in Dagit

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3294]
## Summary

When performing actions like selecting a preset, selecting a partition, deleting unnecessary config, or scaffolding config, the history of the playground editor is blown away. 

This is because externally changing the string value of the codemirror element causes it to clear it’s undo history here (after a componentDidUpdate sets hydrated = false): https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L460 

```
    this.mirror.clearHistory();
```

One fix, courtesy of @bengotow, is to run the following to make the change the preserve the history, but we need to build it into our wrapper:

```
 const lastLine = doc.lastLine();
    const lastChar = doc.getLine(doc.lastLine()).length;
    doc.replaceRange(value || '',
      {line: 0, ch: 0},
      {line: lastLine, ch: lastChar});
```

Another option is to make an internal copy of `react-codemirror2` and just delete the clearHistory line

**Comment by hellendag** [comment]
@helloworld What's the status of your proposed diff for this?

**Comment by helloworld** [comment]
This fell into my backlog. We discussed forking the package locally in https://dagster.phacility.com/D5304. I plan on getting to this next week.

**Comment by hellendag** [comment]
Closing as stale.
