### ISSUE TITLE
Tuple type checks intermix variadic and non-variadic typing, leading to inexpressible contraints

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3299]
## Summary

Right now in the check methods related to tuples (e.g. `is_tuple`, `tuple_param`) the implementation makes a decision to do variadic typing (undefined length but all items of the same type) versus non-variadic typing (defined length and defined type at each index) based on whether the `of_type` parameter is itself a tuple or not.

This was a mistake. It makes it impossible to express some perfectly sensible checks, e.g., if every member of a tuple is one of two types.

Type systems typically have different syntax to express these two use cases for this exact reason.

For example in python typing:

Variadic:

```Tuple[str, ...]```

Non-Variadic

```Tuple[str, str]``` 

There should be two separate methods for these two use cases. I suggest

```check.tuple_shape(tuple, tuple_types)```

for the non-variadic case

## Reproduction

```
def test_non_variadic_union_type_is_tuple():
    class Foo:
        pass

    class Bar:
        pass

    # this is the behavior of isinstance
    foo_tuple = (Foo(),)
    for item in foo_tuple:
        assert isinstance(item, (Foo, Bar))

    # This call fails:
    # This does not call isinstance on tuple member and instead does
    # non-variadic typing. It is impossible to check that each
    # member is Foo or Bar given current API design
    check.is_tuple(foo_tuple, of_type=(Foo, Bar))
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by schrockn** [comment]
Demonstration of inexpressable constraint: https://dagster.phacility.com/D5319

**Comment by mgasner** [comment]
we could also enforce that users write `check.is_tuple(foo_tuple, of_type=(str, ...))` rather than allowing `check.is_tuple(foo_tuple, of_type=str)`. the union case would then be either `check.is_tuple(foo_tuple, of_type=((Foo, Bar), ...))` or `check.is_tuple(foo_tuple, of_type=(Union[Foo, Bar], ...))`

**Comment by schrockn** [comment]
IMO I think the `of_type` behavior should behave identically for all collection types, including tuple
