### ISSUE TITLE
Resource context manager for outside execution context

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#3302]
Currently, resource initialization is tied to the initialization for an execution context. Enabling memoized re-execution, however, requires that resources be initialized before execution time. This is because the asset store (which is represented as a resource) is crucial in determining which steps need to re-execute. 

Once it is possible for resources to depend on one another, the initialization of an asset store could potentially require any number of other resources to also be initialized outside of execution. 

In order to enable this workflow, we should consolidate resource initialization into a single API that can be spun up both from within and without the execution context.

**Comment by schrockn** [comment]
I'm interested in how this turns out as it is related to the effort to model all our mode-dependent artifacts (such as executors) as resources

**Comment by dpeng817** [comment]
solved by the existence of `build_resource_context`
