### ISSUE TITLE
Docstring parsing throws errors at runtime for misformatted docstrings

### ISSUE THREAD

**Issue by k-visvanathan** [dagster-io/dagster#3306]
## Summary
Dagster uses [docstring-parser](https://github.com/rr-/docstring_parser) to inspect docstrings and obtain additional information about solid inputs and outputs. This results in a runtime error being thrown in instances where docstring format may deviate slightly from google-style guidelines. Docstring checking should at the very least be configurable and not throw runtime errors.

## Reproduction
Valid docstring:
```
Args:
    arg_name: description of the arg
```

Invalid docstring (contains hyphen instead of colon):
```
Args:    
    arg_name - description of arg 
```
The second example results in the following error when trying to run the solid the docstring is enclosed in:
```python
Traceback (most recent call last):
  File "dagster/core/definitions/decorators/solid.py", line 59, in __call__
    else infer_input_definitions_for_solid(self.name, fn)
  File "dagster/core/definitions/inference.py", line 132, in infer_input_definitions_for_solid
    descriptions = _infer_input_description_from_docstring(fn)
  File "dagster/core/definitions/inference.py", line 20, in _infer_input_description_from_docstring
    docstring = parse(fn.__doc__)
  File "docstring_parser/parser.py", line 20, in parse
    rets.append(parse_(text))
  File "docstring_parser/google.py", line 272, in parse
    return GoogleParser().parse(text)
  File "docstring_parser/google.py", line 262, in parse
    ret.meta.append(self._build_meta(part, title))
  File "docstring_parser/google.py", line 106, in _build_meta
    before, desc = text.split(":", 1)
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by catherinewu** [comment]
Hey @k-visvanathan thanks for the feedback! Agreed that this should not cause runtime errors. im not aware of better docstring parsers, but am happy to add a try/catch around this

**Comment by sryza** [comment]
https://dagster.phacility.com/D8170

**Comment by sryza** [comment]
The fix will be included in next week's release
