### ISSUE TITLE
[Dagit] config editor highlights a solid in red unexpectedly

### ISSUE THREAD

**Issue by nancydyc** [dagster-io/dagster#3317]
## Summary

There's no error for this run config, so the solid "sort_by_calories" should be blue instead of red. 

## Reproduction

`cd examples/docs_snippets/docs_snippets/intro_tutorial/basics/e02_solids/config.py`

`dagit -f config.py -a config_pipeline`

Then, manually type the run config like the picture below.

## Dagit UI/UX Issue Screenshots

![red solid](https://user-images.githubusercontent.com/59324923/100786372-e563db80-33c6-11eb-96be-1d8bdfa71aac.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by nancydyc** [comment]
#3292

**Comment by bengotow** [comment]
This is resolved by https://dagster.phacility.com/D5389!
