### ISSUE TITLE
test coverage for asset store and intermediate storage edge cases

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3320]
improve test coverage for cases involved in the intermediate storage deprecation

**Comment by sryza** [comment]
@yuhan - do you have a set of edge cases in mind that we can use to determine when this issue is complete?

**Comment by yuhan** [comment]
@sryza No not yet. I plan to test the matrix (asset store vs intermediate storage) you put together as part of the intermediate deprecation im working rn

**Comment by sryza** [comment]
That makes sense.
