### ISSUE TITLE
[Dagit] Enhancement of selecting subset by clicking on that solid

### ISSUE THREAD

**Issue by nancydyc** [dagster-io/dagster#3321]
## Use Case

For now, we can only choose the subset by typing the solid name. It's more natural for users to click on the solid they want to re-execute.

![click on solid to choose subset](https://user-images.githubusercontent.com/59324923/100803717-7c895d00-33e0-11eb-8286-101a7fd31f4b.png)

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by catherinewu** [comment]
@nancydyc this seems like a duplicate of 3027 which dish just closed issue so going to close. please feel free to re-open if this is not the case
