### ISSUE TITLE
Support Memoized Re-execution from all execution paths

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#3322]
Currently, memoized re-execution is only supported from the command line. The code path where it is decided which steps need to be re-run is accessible only to the CLI. 

At present, this is desirable because memoized execution is highly experimental. However, once memoized execution is in a more stable state, we should change the code path to support all possible execution paths.

**Comment by yuhan** [comment]
closing because this may not be super relevant as we're exploring a new path: https://docs.dagster.io/guides/dagster/asset-versioning-and-caching
