### ISSUE TITLE
[dagit] re-execute button clickable despite disabled ui state

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#3324]
![Screen Shot 2020-12-02 at 1 28 12 PM](https://user-images.githubusercontent.com/202219/100921579-5f1cc780-34a2-11eb-9520-24b58530c7cb.png)

this button is clickable and attempts to launch even though it looks disabled

**Comment by hellendag** [comment]
Is it clickable but (correctly) does nothing when clicked?

**Comment by alangenfeld** [comment]
no it takes the action too
