### ISSUE TITLE
[Dagit: Playground] Propogate solid subselection to text editor and solid list (bottom right corner) 

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3327]
## Use Case
User has many solids (100?) in the pipeline and a lot of config (10+ lines) for each solid. Also, the solids have similar names since the name is derived from directory strucutre. User often runs the pipeline with one or a few solids selected via the solid subselection field. 

It would be great if this solid subselection was propogated to the bottom right modal that contains a list of all the solids, such that only the selected solids are highlighted or the non-selected solids are hidden. Then, it will be easier for the user to find the relevant solids and click on those and get to the relevant run config within the text editor. 

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
Can you show a screenshot of exactly where you this to appear? I'm having a little trouble following from the description.
