### ISSUE TITLE
[Dagit] Hard to view run config + run tags + run date of an old pipeline run

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3328]
## Use Case
With the new asset + partitions views that make it easy to jump back to old pipeline runs, I realized that it seems hard to find more information about that pipeline run including run tags, run configuration, and run date.

I think this information does not exist in the pipeline run view. The date in particular was requested by a Jaakko [in slack](https://dagster.slack.com/archives/CCCR6P2UR/p1605689208279400). The run tag answers questions like was this run part of a schedule execution? Was it part of a backfill? The run config answers questions like what job_image was used?

One workaround is to go to the runs page and manually hit "previous page" until said run is visible. 

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Should hopefully be resolved by https://github.com/dagster-io/dagster/commit/89a7f25cf8c95a83a752313a2c092124c2e40afa.
