### ISSUE TITLE
Configure whether ExpectationResult is terminal

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3335]
## Use Case
From user: 
"Suppose I have a data verification step within a solid which should be treated as terminal or non-terminal, depending on the configuration of the pipeline (eg., maybe in dev mode, all failed expectations are terminal, whereas in production runs a failed expectation is only recorded).
I can obviously write code that either raises a Failure or yields an ExpectationResult based on the mode that pipeline is running in. Just wondering if there is already API for doing that that I'm overlooking?"

## Ideas of Implementation
yield ExpectationResult(
   ...,
   is_terminal=some_condition()
)

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Closing, because I think this will be subsumed by https://github.com/dagster-io/dagster/discussions/9543
