### ISSUE TITLE
[helm] Dagit should have more lenient timeouts

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3336]
## Summary
The dagit webserver is unfortunately currently serial, making it easy to overwhelm and cause k8s liveness probes to fail for low timeouts. Currently the default timeout is 1 second. While the webserver is serial, we should set the timeout to something more reasonable (from [user](https://dagster.slack.com/archives/CCCR6P2UR/p1603709661296400))

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by natekupp** [comment]
https://github.com/dagster-io/dagster/blob/master/helm/dagster/values.yaml#L60-L65

Currently this liveness probe hits TCP socket on :80. Potentially should use dagit /info endpoint

Make this timeout longer; 1s up to 10s

**Comment by chenbobby** [comment]
Resolved by [this diff D5587](https://dagster.phacility.com/D5587)
