### ISSUE TITLE
Playground renders comments in a difficult to discern color

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3343]
![Screen Shot 2020-12-04 at 3 42 48 PM](https://user-images.githubusercontent.com/427016/101225818-5d403900-3647-11eb-8d3e-92af83b0af4d.png)

Should probably be gray etc.

**Comment by mgasner** [comment]
oh, i see, it's actually orange -- this wasn't obvious to me until I saw the screenshot fragment

**Comment by bengotow** [comment]
https://dagster.phacility.com/D5630
