### ISSUE TITLE
Scheduler does inefficient queries of entire partition set

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3347]
For an hourly schedule that was started a long time ago, the scheduler will load thousands of partitions in memory on each tick and then discard all but one of them (eventually noticeably affecting performance). We should add the ability to range-query partition sets for certain partitions and use that functionality in the scheduler.

**Comment by alangenfeld** [comment]
I think we can let work like this fall out of profiler guided optimizations
