### ISSUE TITLE
create_dagster_pandas_dataframe_type should work with new managers API

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3354]
De/serialization support for passing pandas object between solids isn't good.

`create_dagster_pandas_dataframe_type` currently only takes loader/materializer. It should accept custom serialization_strategy. https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/libraries/dagster-pandas/dagster_pandas/data_frame.py#L153

Given serialization strategy is likely to be deprecated by 0.11.0, the new asset APIs should have a better support for this use case.

**Comment by schrockn** [comment]
I think we should definitely support this with new managers API and not in the serialization strategy (which will be gone in Q1 2021)

**Comment by sryza** [comment]
We now have a set of IO managers that handle Pandas types, so I'm going to close this
