### ISSUE TITLE
Different icons for dagit based on context

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3357]
## Use Case
It would be awesome to be able to have different icons and favicons for dagit for different contexts.

For example: on local host dagster with a laptop
Deployed to server: dagster nestled in a cloud

Could also make it configurable so users could customize.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Duplicate of #2994.
