### ISSUE TITLE
Long hang after pressing backfill "Launch"

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3358]
After kicking off a large backfill, it can take minutes for the button to stop spinning and relinquish control back to the user.

If I understand what's going on correctly, the button spins until the backend reports that is has launched all the jobs.

A couple potential solutions:
* Don't block on completion of all the launches.  This might require updating the graphql APIs to not block.  A drawback of this approach is that the user doesn't get confidence that all the runs they've requested will actually happen, and it's more difficult to surface errors that happen while launching runs.
* Add some sort of launch progress indicator.  E.g. "Submitted 130/200 runs".
* Add some text explaining what's happening.  E.g. "Waiting for all 200 runs to be submitted".

**Comment by nancydyc** [comment]
#3448
