### ISSUE TITLE
Schedule page gets busy on narrow windows

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#3362]
Ride side of page:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/22018973/101525037-c03c1380-3958-11eb-85d1-db026a6eb09f.png">

**Comment by johannkm** [comment]
This is 1/2 width on 16in mbp

**Comment by hellendag** [comment]
This should get better with a collapsible left nav.

**Comment by hellendag** [comment]
New Dagit design and collapsible left nav have made this better.
