### ISSUE TITLE
Incorrect SerializationStrategy referenced in events when using InProcess executor + no Intermediate storage

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3369]
## Summary
If user uses custom SerializationStrategy but does not configure storage:filesystem or intermediate storage, then the event stream incorrectly reports that my custom SerializationStrategy is used when in fact it is actually used. This is extremely misleading when locally iterating on serdes strategy. 

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
closing since we are moving to IOManagers handling this
