### ISSUE TITLE
Need a test for file managers with the output_notebook param

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3374]

**Comment by yuhan** [comment]
Here's the current behavior:


File Manager provided? | output_notebook? | Behavior
-- | -- | --
N | N | warning: Error when attempting to materialize executed notebook using file manager (falling back to local)
Y | N | successfully generate output notebook:- persist the output notebook in a temp file- yield AssetMaterialization
N | Y | error: dagster.core.errors.DagsterInvalidDefinitionError: Resource key "file_manager" is required by solid def plot_solid, but is not provided by mode "dev". In mode "dev", provide a resource for key "file_manager", or change "file_manager" to one of the provided resources keys: ['io_manager', 'warehouse_io_manager', 'warehouse_loader'].
Y | Y | successfully generate output notebook and an extra solid output:- persist the output notebook in a temp file- yield AssetMaterialization- yield Output(value=FileHandle(...), name=output_notebook)
