### ISSUE TITLE
Logs in run viewer rendering incorrectly with solid selections

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3375]
## Summary

Working on the dagster dbt demo I've been able to get the log viewer into a state where it appears that filtered out log messages are still consuming vertical space.

## Reproduction

Been occurring when using solid subselection in the run viewere

## Dagit UI/UX Issue Screenshots

![Screen Shot 2020-12-08 at 8 33 39 PM](https://user-images.githubusercontent.com/28738937/101584283-8c81dd80-399a-11eb-94e6-a8f1b1caabf2.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by schrockn** [comment]
cc: @mgasner

**Comment by mgasner** [comment]
Resizing the window (by any amount) seems to resolve

**Comment by hellendag** [comment]
Related to a bug I fixed the other day for an edge case. Revert has landed.
