### ISSUE TITLE
Dbt solids need to be factories in order to customize asset keys, metadata tags, etc

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3376]
## Use Case

The current library isn't flexible enough. For example the asset key scheme and the emitted metadata is not customizable.

## Additional Info

We should address this as part of the core API lane in 0.11.0

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
cc: @mgasner

**Comment by sryza** [comment]
@OwenKephart is this still the case?

**Comment by OwenKephart** [comment]
@sryza asset keys and metadata are customizable in SDA-land, although are not with the built-in ops. However, users have found success writing their own custom ops using the built-in resource, so I think we can count this as resolved.
