### ISSUE TITLE
Asset key collisions make it impossible to navigate to nested assets

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3377]
E.g., if you have an asset with the key `['a', 'b']` and an asset with the key `['a']`, you can only navigate to `a` in dagit, not to `a.b` (you need to use the typeahead or link directly)

**Comment by yuhan** [comment]
doesn't seem to be the issue anymore
![image](https://user-images.githubusercontent.com/4531914/114639441-bae23300-9c82-11eb-9293-2d7cc67eb83a.png)
