### ISSUE TITLE
Revert or normalize D5504 and D5505 post demo

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3380]

**Comment by catherinewu** [comment]
@mgasner could you add more clarification to this issue?

**Comment by mgasner** [comment]
This is the `asset_key_prefix` stuff, see https://dagster.phacility.com/D5504 and https://dagster.phacility.com/D5505. Really part of a broader "Figure out how to deal with output notebooks and materializations" chunk of work.

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/4490
