### ISSUE TITLE
Integrate with dbt cloud (API solids)

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3382]
notes:
https://app.swaggerhub.com/apis-docs/Sinter/api_v2/2.0.0a1

**Comment by remigabillet** [comment]
I just noticed that dbtCloud support was added in [this PR](https://github.com/dagster-io/dagster/pull/5524). 🥳

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/5524.
