### ISSUE TITLE
Dagster core/dagit does not load on Python 3.9

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3392]
This is split out to track the pressing issue from the parent #2777, which we'll leave open to track the trailing compatibility/dependency issues (pyarrow and tensorflow)

**Comment by mgasner** [comment]
Hmm, having trouble reproducing

**Comment by fire** [comment]
What is your OS?

What python version?

**Comment by mgasner** [comment]
I'm running a fresh install of dagster and dagit on 3.9.0, Mac OS X. Can I ask about your OS and python version, and do you have a traceback or any error output?

**Comment by mgasner** [comment]
I also can't reproduce in a fresh Debian container (`python:3.9.1-slim`)

**Comment by fire** [comment]
I'm not currently on Linux, but I was on fedora 33 and using pip3.

**Comment by mgasner** [comment]
Did installing dagit fail, or did it fail when you invoked it, or when running a pipeline?

**Comment by mgasner** [comment]
Also can't reproduce in a Fedora 33 container -- 

```docker run -it fedora:33 /bin/bash```

```python3 -m venv dagster
source dagster/bin/activate
pip install dagster dagit
dagit```

**Comment by fire** [comment]
I can't reproduce either. Something changed.

**Comment by mgasner** [comment]
Ok, hooray! We will prioritize getting testing up and running on 3.9 (#2777) for all the packages that don't have incompatible dependencies but going to close this issue for now.
