### ISSUE TITLE
Re-enable dagstermill tests: test_error_notebook, test_resources_notebook_with_exception

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3401]
## Summary

Starting with this [commit](https://github.com/dagster-io/dagster/commit/9f16d7dabdc5fc08a1178ac6e8a9c00936510f7b) that doesn't touch dagstermill code, we noticed that dagstermill_tests/test_basic_dagstermill_solids.py::test_error_notebook and dagstermill_tests/test_basic_dagstermill_solids.py::test_resources_notebook_with_exception started failing on master [BK](https://buildkite.com/dagster/dagster/builds/15596) and [on the release branch](https://github.com/dagster-io/dagster/commit/18ef90195294d89b04b1704e310b2fadb6477cf2) [BK](https://buildkite.com/dagster/dagster/builds/15597).

Root cause is unclear but seems to be happening within Papermill (based on stack trace in BK). Following up with Papermill here: https://github.com/nteract/papermill/issues/519

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
tests are re-enabled with a pin on ipykernel: https://dagster.phacility.com/D5731

We can close this once the pin is removed

**Comment by mgasner** [comment]
this should have been fixed by ipykernel 5.4.2, so going to try repinning to `ipykernel>=4.9.0,!=5.4.0,!=5.4.1`

**Comment by mgasner** [comment]
https://dagster.phacility.com/D6113

**Comment by rexledesma** [comment]
This issue resurfaced in `5.5.2`, pinning `ipykernel<5.5.2`
