### ISSUE TITLE
Asset keys with a / are not escaped correctly in the run log

### ISSUE THREAD

**Issue by coderanger** [dagster-io/dagster#3415]
## Summary

The run event log view for asset materialization events does not URL-escape asset keys when computing the link to the asset dashboard view for that event, leading to a 404 when clicked.

## Reproduction

Appears to happen on any asset key with a `/` in it, though in my specific case it was `["foo", "bar/baz"]`.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by nancydyc** [comment]
This is being resolved by [D5611](https://dagster.phacility.com/D5611) ^_^
