### ISSUE TITLE
Surround load_input and handle_output with a user_code_error_boundary

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3420]

**Comment by schrockn** [comment]
I ran into this. Just leaving here to indicate what state it leaves runs in: They are orphaned as "STARTING"

![Screen Shot 2020-12-17 at 10 58 11 AM](https://user-images.githubusercontent.com/28738937/102525324-5659f300-4057-11eb-95e0-5dd03c6133c6.png)

![Screen Shot 2020-12-17 at 10 59 02 AM](https://user-images.githubusercontent.com/28738937/102525384-67a2ff80-4057-11eb-9d05-5fcb702ab31f.png)

Not only should this be an error boundary but we should have more sensible fallback behavior to catch any framework errors.
