### ISSUE TITLE
Do performance profiling for Dagit loading historical pipeline runs

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3430]
## Summary

Users have shared screen recordings where Dagit takes a while to load historical runs. We should profile whether the backend is slow, whether some piece of the rendering is slow, etc

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Sounds like this is a webserver perf issue.

**Comment by alangenfeld** [comment]
@prha made some improvements since this was filed - will likely need to do this continually but closing this issue.
