### ISSUE TITLE
optional resource keys

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#3432]
Currently, many decorators in the core system ingest a set of `required_resource_keys`. However, this can be onerous in scenarios where we want to provide the option for a user to inject their own functionality, but can also operate without said injection.

A place where this is relevant is in the standard object managers. We want to provide the option for users to provide their own connection, but we should also be able to construct one implicitly if none is provided, with no input from the user.

**Comment by yuhan** [comment]
I/O managers (resources in general) can now depend on other resources
