### ISSUE TITLE
Persist logs when execution launched from dagit

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#344]
Instead of storing log messages in memory, we should persist them to disk. Code should be structured to be pluggable so we could use a different persistence/queuing mechanism (e.g. kafka) eventually.

**Comment by mgasner** [comment]
#714

**Comment by schrockn** [comment]
Resurfacing this one and assigning to 0.5.0 milestone as we are closer to having this given the infrastructure that @mgasner landed in https://dagster.phacility.com/D195 We should be able to use the persistence log storage there to store logs in dagit.

**Comment by natekupp** [comment]
Punting from 0.5.0

**Comment by mgasner** [comment]
This is gated behind a CLI flag until we have a good default for *where* to store the logs, but implemented and live.
