### ISSUE TITLE
Output and Input Manager required resource keys parameter

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#3442]
They don't currently have this parameter, but resource definition does.

**Comment by schrockn** [comment]
I ran into this too. I would suggest that solid's resource_required_keys automatically inherit all its input and output definition's manager keys

**Comment by schrockn** [comment]
More specifically, from the user perspective it should act like that

**Comment by sryza** [comment]
I ended up addressing this as part of the my fix for object manager definitions and configured: https://dagster.phacility.com/D5694
