### ISSUE TITLE
Suggest refresh of Playground cached config on repository reload

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3446]
## Use Case

When refreshing a repository, the run config in the Playground can get out-of-date (especially when users are actively developing on that pipeline) and we should add a visual reminder to refresh the config. 

The current work-around is for the user to remember to manually refresh the run config clicking in the partition and solid selection boxes) after they reload their repository which is hard to remember and really confusing when forgotten (the run fails, user looks for a bug in the code, can't find a bug, etc, etc, remembers that config was out-of-date)

Suggestion is to mark run configs in Playground view as out-of-date after the repository is refreshed, with a button that regenerates the config for that partition. 

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Closed with 1743a4ff05.
