### ISSUE TITLE
Be resilient to failures in the middle of backfill launches

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3449]
If the web server fails while in the middle of launching runs for a backfill, there's no checkpoint to start from when it comes back up or even record of what partitions we were trying to backfill.

**Comment by hellendag** [comment]
This is something that might be handled by having the backfill ID be mappable to the relevant partitions, right? Then we would be able to statically find out which partitions have had runs generated or have failed to do so.

**Comment by sryza** [comment]
@hellendag exactly

**Comment by prha** [comment]
This is done with the backfill daemon changes enabled in `0.10.7`
