### ISSUE TITLE
Link between config types and dagster types in docs

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#3458]
When searching for a config type that was the analogue to optional (ie searching `Optional config`) I received no search results that pointed me towards the solution (the `Noneable` config type). Being able to surface this information more readily from concepts that users are already familiar with would help improve the docs experience.

**Comment by yuhan** [comment]
@dpeng817 do you think https://docs.dagster.io/concepts/types#built-in-types would help? if not, how do you expect the linking to be like?

**Comment by sryza** [comment]
With our new guidance on Dagster types as runtime checks and preference for using Python type annotations when they're just Python types, we are de-emphasizing the built-in Dagster types in our docs, so I'm going to close this.x
