### ISSUE TITLE
Backfill modal takes a long time to load

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3459]
After pressing "Launch a partition backfill", it takes a long time to load the modal where the user can configure and launch the backfill.

From @catherinewu:

> Since we currently do a full table scan of the run_tags table for every valid partition key when we load the backfill partition modal, this is likely the root cause of slowness.

> In the short term, we can 1. add a secondary index to run_tags table to make the lookup more efficient 2. drop the look up entirely (which disables the ability to “re-execute from last run”/“re-execute from failure” from the backfill partitions ui).
From my reproduction, i launched 3000-4000 runs across 1000 partitions of a pipeline. At this point, loading the backfill modal took 16-18 seconds. After implementing (2), this dropped to 300-400ms. (1) did not produce a noticeable change in load times

> This is a (messy) diff that implements (2): https://dagster.phacility.com/D5654.

**Comment by sryza** [comment]
@catherinewu - do you still have the setup around that would allow you to measure how long it takes to load the backfill modal?  @prha recently merged his change that should speed this up considerably: https://dagster.phacility.com/D5727

**Comment by bengotow** [comment]
Hey folks! I took a look at this this afternoon and it seems like this has been largely resolved by Phil's switch over to `partitionStatusesOrError`. The performance is pretty good, though it does seem like it's still linear with the number of partitions. I think we should revisit this if we get more complaints, but this seems like a local maxima where more speed would take a lot more work  🙌

**Comment by sryza** [comment]
@bengotow that sounds right to me!

**Comment by deoqc** [comment]
This could be implemented in a generic way:
- context in job op could have access to load_asset_value, to get dependencies
- job could send multiple AssetMaterialization (multiple different assets, multiple different partitions)

It is a much more uncontrolled way, wouldn't be the primary way but an available optimization.
