### ISSUE TITLE
[dagit] evaluate websocket communication 

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#3460]
Currently we send all graphql traffic over websockets. We should evaluate changing this set up to send queries and mutations over as regular requests. A prototype, or a flag to toggle this behavior would be a good place to start.

**Comment by schrockn** [comment]
What is the current problem with using websockets?

**Comment by alangenfeld** [comment]
There are no known certain problems, but the way sockets are used has some effect on the properties of a deployed dagit webserver under simultaneous use. Having the ability to toggle this behavior will make measurement and analysis of that effect possible.
