### ISSUE TITLE
Launching a backfill triggers multiple runs per partition

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3461]
@dpeng817 encountered this.  Then I encountered it.

@catherinewu 's theory:
In the http protocol, there are some cases where the client will automatically retry such as “If an HTTP/1.1 client sends a request which includes a request body, but which does not include an Expect request-header field with the "100-continue" expectation, and if the client is not directly connected to an HTTP/1.1 origin server, and if the client sees the connection close before receiving any status from the server, the client SHOULD retry the request”
https://blogs.oracle.com/ravello/beware-http-requests-automatic-retries

**Comment by catherinewu** [comment]
@sryza do we have a repro for this behavior? if we don't have a precise repro, could you and @dpeng817 describe what you were doing when you encountered this? for example, were you launching x000 partitions / with or without the run coordinator?

**Comment by sryza** [comment]
After my initial reproduction, I have not been able to successfully repro this, either locally or in the dogfooding environment.  I am going to close this out for now and we can reopen if it resurfaces.

**Comment by sryza** [comment]
Reopening because @catherinewu recently hit this as well

**Comment by hellendag** [comment]
@sryza @catherinewu Do you have a repro for this?

**Comment by sryza** [comment]
@prha - do you have any idea what could be going on here?  One possible solution could be to make the backfill backend idempotent?  I.e., before submitting a run, check if there's a run with the same set of tags?
