### ISSUE TITLE
test_composite_basic_execution test very very slow. Versioning is likely culprit

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3463]
## Summary

I debugged the perf on this test once and it was related to lavishly re-constructing execution plans over and over again for the purposes of computing versioning information. Now that we are going to de-emphasize the versioning workstream I would like this looked at again. We shouldn't ship a major perf regression system-wide to support an experimental feature.

## Reproduction

pytest python_modules/dagster/dagster_tests/core_tests/test_composites.py -k test_composite_basic_execution

Takes about 35 seconds to run on my machine

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
https://dagster.phacility.com/D5712
