### ISSUE TITLE
Partitions drop-down should have most recent partition on top

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3465]
## Summary

Currently, date partitions are sorted from oldest to newest; this adds unnecessary steps to a dev loop because this forces users to unnecessarily scroll to the end of the partition list or click the reverse sort button each time

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Can you provide a screenshot? Is this on the playground? There is a "sort" button on the input that allows reversing the sort.

**Comment by hellendag** [comment]
![image](https://user-images.githubusercontent.com/2823852/102935043-f6a28400-446a-11eb-9b92-256ed4571201.png)

**Comment by hellendag** [comment]
This should be solved by the sort button, so I'm going to close this. Please reopen if there's anything I'm misunderstanding. :)
