### ISSUE TITLE
Solid selection search box: support fuzzy string match for surfacing suggested solids

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3466]
## Use Case

From user: In the solid selection, you have to know the entire solid name to select the solid. It would be nice to have some fuzzy search capabilities there (eg. I want to select the "x_y_z" job; if I type in "z”, it doesn’t show anything. Only if I type “x”, which is the first section, it shows the suggestion for "x_y_z")

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Pretty sure this kind of string matching works now. Seems okay when I try substrings.
