### ISSUE TITLE
Step-based views

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3467]
## Use Case

From user: When I add a new solid to a pipeline and want to monitor that particular solid (eg. how long did it take), it's not clear how to find it from the Runs section. I know it’s within the "X" pipeline, but it would be good to be able to find an individual step's logs, not the pipeline as a whole. 

Current workaround is to check step execution times via the Assets view. 

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by bengotow** [comment]
This is a pretty cool idea. We recently added a "Step Execution Time" graph to the Asset Details page, which shows the execution time over partitions for the step that emitted the asset materialization. There's no reason that graph is only shown for steps that emit an asset, and it seems like we could create a "Pipeline Step Page" that shows logs + execution time across runs to give you a home page to debug / inspect a step. Might be a good project for our observability track?

**Comment by sryza** [comment]
@bengotow I agree with everything you said.

**Comment by bengotow** [comment]
I think this is largely addressed now that we show the last 10 runs of a step (with links to the step logs) and the graph of recent step execution time on the op graph sidebar.
