### ISSUE TITLE
Ability to link to a pipeline run with filters applied

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3468]
## Use Case

From user:
Would love to be able to share `http://some_real_domain.com/instance/runs/ce53f1ef-ac7c-4e93-93c2-13ba6e2cb1b4?filters=step:branch_1_0` (for screenshot below) to send a step execution to colleagues

<img width="1536" alt="Screen Shot 2020-12-21 at 12 17 41 PM" src="https://user-images.githubusercontent.com/6024687/102818467-87ebfa80-4386-11eb-8794-74c0866e4998.png">

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
"Copy URL" button provides this. :)
