### ISSUE TITLE
[helm] add compute log manager setting

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#3470]
## Summary

Hi, I'm not entirely sure if I would define this as a "bug", but I'm unable to see console logs when I run a pipeline using dagster_celery_k8s. The logs don't appear in the "View Raw Step Output" in dagit, nor in the Kubernetes pod logs (I can only see dagster logs in there). If I run the same pipeline locally the logs appear.

## Reproduction

Just `print` or  use`logging.info` in a solid. Running locally prints the log, running on dagster_celery_k8s the log is lost.

## Additional Info about Your Environment

dagster 0.9.22 on Kubernetes 

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
Are you using the default `Compute Log Manager`? If you use `S3ComputeLogManager` or `GCSComputeLogManager` it should allow the "View Raw Step Output" feature to work.

https://docs.dagster.io/overview/instances/dagster-instance#instance-configuration-yaml

We could do a much much better job at communicating this stuff in the product / API

**Comment by natekupp** [comment]
will be addressed by https://dagster.phacility.com/D5745 and https://dagster.phacility.com/D5748

**Comment by amarrella** [comment]
Nice, thank you! 🙇

**Comment by rexledesma** [comment]
Resolved with 3a829808 and dab191ce. @amarrella let me know if you encounter problems when using this!
