### ISSUE TITLE
Daemon heartbeat error on dev site

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3471]
## Summary

![Screen Shot 2020-12-22 at 12 41 14 PM](https://user-images.githubusercontent.com/28738937/102926890-129a2b80-4453-11eb-87ff-0315d244fc8e.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by johannkm** [comment]
Resolved by https://github.com/dagster-io/dagster/commit/768f74150d26ea19b98029710e25c150ab45c308
