### ISSUE TITLE
Clicking on partition set from schedule does not persist selection to partitions page

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3473]
## Summary

video: https://www.loom.com/share/d13e0c45dbe74f12b374b1c4683efc05

In the video, we are viewing some schedule called "x_every_six_hours_export" that runs on the "many_events" pipeline. When we click "x_every_six_hours_export_partitions", then we are brought to the partitions view. However "many_events_minutely" partition set is displayed instead of the clicked "x_every_six_hours_export_partitions"

I guess another bug is that on the hourly schedule page, the partition names are cut off

## Reproduction

Add the following in python_modules/dagster-test/dagster_test/toys/schedules.py
```
@hourly_schedule(
    name="x_every_six_hours_export",
    pipeline_name="many_events",
    mode='default',
    should_execute=lambda dt: dt.hour % 6 == 0,
    start_date=datetime.datetime(2020, 11, 30)
)
def x_every_six_hours_export(date)
    return {}

def get_toys_schedules():
    from dagster import ScheduleDefinition, file_relative_path

    return [
        x_every_six_hours_export,
        backfill_test_schedule(),
        longitudinal_schedule(),
        materialization_schedule(),
        ScheduleDefinition(
            name="many_events_every_min",
            cron_schedule="* * * * *",
            pipeline_name="many_events",
            run_config_fn=lambda _: {"intermediate_storage": {"filesystem": {}}},
            execution_timezone=_toys_tz_info(),
        ),
    ]
```

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
This appears to have been fixed.
