### ISSUE TITLE
Add CLI option to `dagster api grpc` to enable/control logging

### ISSUE THREAD

**Issue by coderanger** [dagster-io/dagster#3482]
## Use Case

The upstream `gprcio` library uses Python's `logging` module however because this is never initialized, this output is never shown. When debugging weird issues, it would be nice to be able to turn this logging on (or maybe just have it on by default at an info or warning level).

## Ideas of Implementation

Adding a `--log-level` option which calls `logging.basicConfig` or similar would accomplish this.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/5897.
