### ISSUE TITLE
Flaky test: dagster_celery_tests/test_priority.py::test_run_priority_pipeline

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3493]
## Summary

https://buildkite.com/dagster/dagster/builds/15788#5a046de7-e026-4a32-95ef-3dade88695fd

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Closing because this is an old flaky test that hasn't come up recently
