### ISSUE TITLE
Next Tick should be localized to timezone in dagit?

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3499]
## Summary

Given how it displays timezones explicitly this might be a deliberate product decision, but I was surprised when all the "tick" timezones were displayed in the schedule's timezone rather than in the timezone of the dagit viewer.

![Screen Shot 2021-01-05 at 8 11 09 PM](https://user-images.githubusercontent.com/28738937/103724786-6d26a200-4f92-11eb-91dd-67c6b8d3f379.png)

See here how my dagit display is in MST but the schedule is in PST. I was surprised by this.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
This was deliberate - hovering over the clock icon shows it in your local time. We could swap them? Or just always show it in local time.

**Comment by schrockn** [comment]
Gotcha. I don't feel super strongly about this but I'd be curious about what others think.

However this does get worse:

![Screen Shot 2021-01-05 at 8 38 52 PM](https://user-images.githubusercontent.com/28738937/103726594-87fb1580-4f96-11eb-854f-01c9faf9b9b5.png)

Notice now there are *three* timezones in context. Schedule (Pacific). Tick History (Mountain). Runs (UTC)

**Comment by schrockn** [comment]
This is arguably just a bug in the tick history. But I still think even with that fixed the inconsistency between the runs list "timing" column and the tick times will be confusing

**Comment by hellendag** [comment]
This is now flipped: the tick shows the user's timezone, and the tooltip shows the execution timezone.
