### ISSUE TITLE
Flaky test: retry_multi_input_early_terminate_pipeline

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3500]
## Summary

Test suite: dagster-graphql-postgres-postgres_instance_managed_grpc_env tests (py38)
Test: dagster_graphql_tests/graphql/test_retry_execution.py::TestRetryExecutionAsyncOnlyBehavior::test_retry_early_terminate[postgres_with_default_run_launcher_managed_grpc_env]
BK: https://buildkite.com/dagster/dagster/builds/15814#1659bf02-705e-4d83-bb0d-f6b7c43e3707

It seems like "c970f6cb-b43b-47a7-a9d3-941e721fe7a7" is the initial run and "02a7cbfe-9d6c-40e9-8304-82d6e5db811b" is the subsequent retry. From reading the logged stderr, "c970f6cb-b43b-47a7-a9d3-941e721fe7a7" does not have a pipeline success or failure event and notably, we do not assert that "graphql_context.instance.run_launcher.terminate(run_id)" on L852 is successful.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Closing because this is an old flaky test that hasn't come up recently
