### ISSUE TITLE
Remove check for secondary index SECONDARY_INDEX_ASSET_KEY for asset key reads

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#3507]
## Use Case

We are conditionally reading from the AssetKeyTable, depending on whether SECONDARY_INDEX_ASSET_KEY row is set.  This is because we only want to read from the AssetKeyTable when it has the full set of asset keys that exist in the event log storage.

Without forcing users to run an event_log migration, we cannot guarantee that this will happen.  However, https://dagster.phacility.com/D5823 does lazily migrate on reads from the asset catalog, and we have been double-writing to the event log and the asset key table since https://dagster.phacility.com/D4764.

After some time (post-0.11.0?), it should be safe to remove the conditional check.  This will cause the asset catalog to only report asset keys that have been written using post-`0.9.16` code, and only if the asset page has not been loaded in dagit (post-`0.10.0`).

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
believe this was resolved
