### ISSUE TITLE
Helm chart's default probes are not overwritten when using `tcpSocket` or `httpGet`

### ISSUE THREAD

**Issue by chenbobby** [dagster-io/dagster#3513]
## Summary
For k8s probes, only one of `exec`,`tcpSocket`, and `httpGet` can be defined. Currently, if a user wishes to override the default probes for `userDeployment` or `celery` in their `values.yaml` using `tcpSocket` or `httpGet`, then the Helm chart will ignore this and use the default `exec` command.

The following sections of the Helm chart are affected, due to having a default probe in the `templates` YAML:
* celery
* userDeployment

## Reproduction
1. Modify `dagster/helm/dagster/values.yaml` by adding the following as a user-deployment (or celery) `livenessProbe`:
```
userDeployments:
  enabled: true
  ...
  livenessProbe:
    tcpSocket:
      port: 3030
```
2. Run `helm install my-release dagster/helm/dagster -f dagster/helm/dagster/values.yaml --dry-run`.
3. Observe in the output YAML that the livenessProbe still uses the `exec` probing method.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
These probes have been removed by default as of https://github.com/dagster-io/dagster/pull/6553.
