### ISSUE TITLE
Add Dagster helm chart to ArtifactHub.io

### ISSUE THREAD

**Issue by chenbobby** [dagster-io/dagster#3515]
## Use Case
Currently, the documentation for the Dagster helm chart is limited to source code in `dagster/helm` and the [Deploying on K8s](https://docs.dagster.io/deploying/k8s_part1#helm-chart
) guide in our documentation.

I would argue that there is room for improvement in terms of discoverability and documentation for the Dagster helm chart.

According to the [GitHub collection of Helm charts](https://github.com/helm/charts#helm-charts), "The canonical source for Helm charts is the [Artifact Hub](https://artifacthub.io/), an aggregator for distributed chart repos."

The ArtifactHub seems to have a nice way to present a `helm install` guide as well as documentation of the chart's `values.yaml` schema.

See examples:
* [Redis](https://artifacthub.io/packages/helm/bitnami/redis)
* [Nginx Ingress Controller](https://artifacthub.io/packages/helm/bitnami/nginx-ingress-controller)

## Ideas of Implementation
Add the Dagster helm chart to [Artifact Hub](https://artifacthub.io/).

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
This probably entails separating out our helm chart to a separate repository as well.

**Comment by rexledesma** [comment]
https://artifacthub.io/packages/helm/dagster/dagster
