### ISSUE TITLE
Repository location with error doesn't show up in dropdown

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3520]
## Summary
Clicking the dropdown to display all repositories, I would assume that even the repositories with errors would be displayed. From the dropdown itself, clicking on the errored repository should cause it to reload, without needing to navigate to `/instance/health#repository-locations`.

## Dagit UI/UX Issue Screenshots
All repositories:
![image](https://user-images.githubusercontent.com/16431325/104108383-131b2a80-5279-11eb-85f1-b08ac9a5946b.png)

Errored repository does not show up in this dropdown:
![image](https://user-images.githubusercontent.com/16431325/104108376-faab1000-5278-11eb-9008-28b5423b3b1c.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
A challenge with this is that if the repository location can't be loaded, the repositories inside it likely can't be either - so we would need to mix repository locations in with repositories, which might be confusing?

An underlying problem may be that we're not clearly exposing the concept of a repository location in the UI (and mashing all the repositories together, losing the fact that they're grouped inside repository locations)

**Comment by hellendag** [comment]
I think we probably just need to rethink how repo locations and repos are surfaced in the navigation, and we're intending to do so for 0.11. In the meantime, it probably doesn't work to include failed repo locations at the same level as repos in the switcher, as dgibson notes.
