### ISSUE TITLE
Search bar for repository locations

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3521]
## Use Case
Similar to the existing search bar for `Pipelines & Solids:`, a search bar could exist to find a repository location quickly, rather than relying on the dropdown menu.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
This is a good idea. I've got some ideas for search within Dagit, and am aiming to work on this in the coming month or two. I'll probably end up consolidating this into a larger issue for that. Backlogging for now.

**Comment by alangenfeld** [comment]
we have universal search now
