### ISSUE TITLE
Asset Store still mentioned in event logs

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3524]
## Summary
Mentions of `Asset Store` [still remains in the event logs](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/events/__init__.py#L842-L877)? Unsure if this is intended. Feel free to close if so.

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/16431325/104114149-0537ca80-52b6-11eb-92d2-bb3a137de325.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
@yuhan - you're working on some changes already that will get rid of this, right?

**Comment by yuhan** [comment]
Yes it’s tracked here https://github.com/dagster-io/dagster/issues/3509
