### ISSUE TITLE
Docs outline doesn't scroll

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#3527]
There's more content here on the right (this is from D5537) but I can't scroll down further in the outline to see it:

![image](https://user-images.githubusercontent.com/609349/104265472-87ed9080-5442-11eb-97b2-e14c785a0ccb.png)

cc @catherinewu

**Comment by catherinewu** [comment]
Also, "Database" has the wrong indent level even though it's formatted the same as the above components

**Comment by alangenfeld** [comment]
new docs site
