### ISSUE TITLE
Handle local managed gRPC server crashes better in dagit

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3528]
## Summary
If a gRPC server crashes (e.g. running out of memory), we don't surface that information or display it anywhere in dagit (or tell you the best way to fix it, which is to reload your repository location).

**Comment by hellendag** [comment]
@helloworld didn't we surface these before, with your earlier changes?

**Comment by helloworld** [comment]
Somehow missed this notification and just seeing this tag. We surfaced these errors for remote locations, but not local, managed locations. I'll take this issue

**Comment by hellendag** [comment]
Closing as wontfix.
