### ISSUE TITLE
Inconsistent Partition Status with schedule Partition set

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3532]
## Summary
When cross checking the `Partition Status` on `/instance/schedules` with a specific schedule's `Partition set`, the `Missing: XXX` numbers are not matching. 

## Reproduction
https://user-images.githubusercontent.com/16431325/104362155-47385a80-54c8-11eb-9815-a11f02f275e7.mov

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Taking a look.

**Comment by hellendag** [comment]
It's an Apollo caching bug related to IDs on `PartitionStatus` that need to be made more unique. Great catch, thanks for reporting it. @prha has a fix coming.

**Comment by hellendag** [comment]
Fixed by https://github.com/dagster-io/dagster/commit/9c4843f7da1c66668e8e5fb85f8d1697e7d856eb.
