### ISSUE TITLE
Deserialization Error with historical runs

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3533]
## Summary

https://demo.elementl.show/instance/runs/e21c0721-f0b0-4d9b-9383-e25ca1b5e583?timestamp=1610064053320

## Reproduction

![Screen Shot 2021-01-12 at 12 37 38 PM](https://user-images.githubusercontent.com/28738937/104363944-245f7380-54d3-11eb-919c-e463b9f188ec.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment]
this was fixed in https://dagster.phacility.com/D5863 and AssetStoreOperationType will be gone after https://dagster.phacility.com/D5474 is landed
shall we consider backcompat and guard it for historical runs?

**Comment by schrockn** [comment]
Even discarding it would be reasonable. demo.elementl.show just broke when I was showing someone on a call

**Comment by yuhan** [comment]
Did you mean deleting the historical runs? or do a data migration to cleanup that event from the event log db?

**Comment by schrockn** [comment]
I was thinking discarding any event which fails this in particular. But if the solution is to delete runs on demo.elementl.show that works too. It's just in any unfortunate state right now

**Comment by yuhan** [comment]
deleted the affected 3 runs just now. will rerun the slack_digest_pipeline with the latest io manager changes later today to make sure things show up in the asset catalog

**Comment by yuhan** [comment]
cleaned up the affected historical runs. reran slack_digest_pipeline to make sure the latest changes work.
please reopen this issue if it happens again, then we might want to do a data migration to clean up the logs systematically
