### ISSUE TITLE
[dagster-website] Add "subscribe to newsletter" modal in Footer

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3538]
## Use Case

In the footer of dagster.io, we can add a more discoverable + searchable "subscribe" modal compared to the current email icon. 

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
moving to https://github.com/dagster-io/dagster-website/issues/67
