### ISSUE TITLE
[Tracking] Improve docs tests

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3540]
it should capture
- broken links for broken API reference (via PyObject) like:
![image](https://user-images.githubusercontent.com/4531914/104679738-31cb5800-56a3-11eb-9c4b-a2703f61f13a.png)
- broken anchors like https://github.com/dagster-io/dagster/pull/5424
- broken links inside components
- https://github.com/dagster-io/dagster/issues/2939

**Comment by erinkcochran87** [comment]
Closing this in favor of more granular task tracking in Notion.
