### ISSUE TITLE
PyObject is causing line break/link rendering issues in docs

### ISSUE THREAD

**Issue by jmsanders** [dagster-io/dagster#3548]
https://docs.dagster.io/deploying/k8s#run-launcher has some wacky stuff going on with line breaks/link rendering. I think it's related to the use of the PyObject component:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/10291790/104945054-bf49c900-597d-11eb-9c96-203cafaf0283.png">

**Comment by catherinewu** [comment]
https://dagster.phacility.com/D6051

**Comment by catherinewu** [comment]
@yuhan @helloworld should we look into this issue further or will this likely be fixed with the new docs infra?

**Comment by yuhan** [comment]
yes we should! closing in favor of https://github.com/dagster-io/dagster/issues/3568
