### ISSUE TITLE
Enable selecting subsets of solids inside composites

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3557]
From Richard Fisher in general:

Hi, how can I use the solid selection syntax to query for a solid inside a composite? I’ve tried composite_name.solid_name, but this doesn’t seem to work. I’m trying this through the Dagit playground, but I’d like it to run through execute_pipeline

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
https://dagster.phacility.com/D2879

**Comment by dpeng817** [comment]
As of 0.14.0 - nested op selection is now possible via a `.` syntax: `my_graph.my_op`
