### ISSUE TITLE
dagster-dbt example is truncated

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3558]
## Summary

https://docs.dagster.io/examples/dbt_example

The docs go through the setup for the example, but the rest of the tutorial (narrative about what this example does, code snippets, dagster screenshots, etc) appears entirely missing?

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment]
refreshed the example page in https://dagster.phacility.com/D6171

@chenbobby it'd be great if you could revamp the api docs https://docs.dagster.io/_apidocs/libraries/dagster_dbt to be more precise about what each of method is doing (e.g. `dbt_cli_run` yields AssetMaterialization events to log dbt cli log), so the users don't have to read the source code to understand what is happening
