### ISSUE TITLE
Link to code in Examples section of Docs does not appear clickable

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3559]
## Summary

The link to the code ("Github" in the below screenshot) does not appear clickable. This likely resulted from a diff I committed that removed the semi-bold text format for links.

<img width="913" alt="Screen Shot 2021-01-19 at 6 49 12 PM" src="https://user-images.githubusercontent.com/6024687/105120431-1091af80-5a87-11eb-93a2-2384b3c0636c.png">

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
new docs site
