### ISSUE TITLE
Dep DSL example is missing content?

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3560]
## Summary

https://docs.dagster.io/examples/dep_dsl

Dep DSL example seems to be missing some narrative description about how the yaml is being converted into a pipeline?

Chatted with a user today who was asking for said feature and ended up linking to the code in Github instead of the docs

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
this is better in current docs
