### ISSUE TITLE
deploy docker example doesn't have title or description in examples.json, meaning it doesn't get displayed in the sidebar.

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#3561]
## Summary
The deploy docker example has no title or description:
(from dagster/docs/next/src/pages/examples/examples.json)
```
  {
    "name": "deploy_docker",
    "title": "",
    "description": ""
  }
```

**Comment by nancydyc** [comment]
I include this fix in my diff of [a new example](https://dagster.phacility.com/D5949)
