### ISSUE TITLE
Debug logs are written in stderr

### ISSUE THREAD

**Issue by amillette** [dagster-io/dagster#3566]
## Summary
The logs for debug are written in stderr instead of stdout.

## Dagit UI/UX Issue Screenshots
![localhost_3000_instance_runs_60c88d1f-ab63-4dd2-ab1e-329af886d4e7](https://user-images.githubusercontent.com/12679869/105249277-df2be900-5b45-11eb-8826-0b66274c5762.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by prha** [comment]
I think we should do this... but it will be a breaking change so we should probably hold off until `0.12.0`.  Need to resurrect  https://dagster.phacility.com/D4538, which made this change but got abandoned.

**Comment by sryza** [comment]
Some believe that stderr is the right place for all logs:
* https://stackoverflow.com/questions/4919093/should-i-log-messages-to-stderr-or-stdout#:~:text=2%20Answers&text=Regular%20output%20(the%20actual%20result,warning%2C%20error)%20on%20stderr%20.&text=You%20could%20argue%20that%20the,that%20should%20go%20to%20stdout%20.
* https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout

I tried to think of frameworks that emit logs, and the first that came to mind were Spark and Flask.  They both appear to log to stderr:
* https://stackoverflow.com/questions/24571922/apache-spark-stderr-and-stdout.
* https://stackoverflow.com/questions/56905756/how-to-make-flask-log-to-stdout-instead-of-stderr.

I don't have a horse in this race, but, given that there are seemingly valid opinions in both directions, and that at least some popular Python libraries log to stdout, I'd tend to believe that we should stick with the current behavior to minimize disruption to users who are accustomed to it.

**Comment by sryza** [comment]
https://www.devdungeon.com/content/python-logging-tutorial also claims that the Python `logging` library defaults to stderr.

**Comment by hellendag** [comment]
Sounds like this is a wontfix, at least at this point.
