### ISSUE TITLE
make it easy to link to dagit run page in hooks

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3576]
## Use Case

When someone gets a notification of a pipeline failure, they typically want to investigate the cause of the failure, which normally starts at the run page in Dagit.

Right now, if they want to offer this, they need to write code to construct the URL - not an easy out-of-the-box experience.

## Ideas of Implementation

Maybe a helper function that would enable something like:
```
@failure_hook(required_resource_keys={"slack"})
def slack_on_failure(context: HookContext):
    run_page_url = run_page_url(base="demo.mywebsite.dev", run_id=context.run_id)
    message = f"Pipeline {context.pipeline_def.name} failed.  More info: {run_page_url}"
    context.resources.slack.chat.post_message(channel="#foo", text=message)
```

Bonus points for linking to step-level failure filters like we do from the partitions page.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
Believe https://dagster.phacility.com/D6140 addressed part of it. Users now can configure `dagit_base_url` on the new `pagerduty_on_failure/success` and `slack_on_failure/success`. cc @OwenKephart

**Comment by yuhan** [comment]
closing this as we have the `dagit_base_url` param on the pagerduty and slack solid hooks
