### ISSUE TITLE
Refresh airline demo

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3577]
Updates the airline-demo to be in line with current thinking and best practices 

Ideas from older issues:
* Update airline demo to use dagster-aws Redshift resource

**Comment by yuhan** [comment]
https://github.com/dagster-io/dagster/issues/1975
https://github.com/dagster-io/dagster/issues/1622
https://github.com/dagster-io/dagster/issues/1371
https://github.com/dagster-io/dagster/issues/2451

**Comment by catherinewu** [comment]
https://github.com/dagster-io/dagster/issues/1945

**Comment by alangenfeld** [comment]
#3724

**Comment by yuhan** [comment]
recent discussion: https://dagster.phacility.com/D7384
