### ISSUE TITLE
Executors page is hard to find

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3578]
## Use Case

Two users have asked me whether multiprocessing / executing solids in parallel with dagster is possible. I'm not sure how to make this more obvious or discoverable. 

One contributing factor might be:

Executors page (https://docs.dagster.io/overview/pipeline-runs/executor#main) is almost impossible to discover, as it is nested under Overviews -> Pipeline Runs. Seemingly only way to discover is knowing to search "Executors" and then picking the right result:

<img width="568" alt="Screen Shot 2021-01-22 at 2 43 13 PM" src="https://user-images.githubusercontent.com/6024687/105557063-348c0580-5cc0-11eb-9043-1e3c0a2918a7.png">
 

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
I faced the same problem with run coordinators

**Comment by yuhan** [comment]
executors and run coordinators should be easily discovered with the new docs structure and the improved search:
![image](https://user-images.githubusercontent.com/4531914/112069489-25db9680-8b29-11eb-9c0c-8fac1b792565.png)
![image](https://user-images.githubusercontent.com/4531914/112069499-2c6a0e00-8b29-11eb-9ac0-00fe75643908.png)
