### ISSUE TITLE
Nit: ticks view shouldn't zoom in so far

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#3580]
![image](https://user-images.githubusercontent.com/609349/105559008-e7f6f900-5cc4-11eb-88b4-1a0775834531.png)

I think it'll be fairly rare for ticks to be more frequent than once a minute, stopping at something like this is probably sufficient:

![image](https://user-images.githubusercontent.com/609349/105559092-1ffe3c00-5cc5-11eb-89e5-e561f404712a.png)

**Comment by prha** [comment]
This landed with 6c6119f66
