### ISSUE TITLE
Retry sensor that returns RunRequest w/ invalid run config

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3583]
## Summary

I set up a sensor and it returned a run request with an invalid run_config (failed schema check). To recover in production or to iterate faster locally, it would be nice to be able to fix my sensor, reload the repo, and then "re-execute" the sensor for that run_key. 

<img width="1536" alt="Screen Shot 2021-01-22 at 10 50 20 PM" src="https://user-images.githubusercontent.com/6024687/105571369-41cae380-5d04-11eb-8eed-2079634cb4c8.png">

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
We'll make this a tick failure when the config is bad and the run can't be launched, rather than creating a failed run that can't be retried.

The point about being able to retry sensor ticks will still be valid even after that though

**Comment by yuhan** [comment]
Hi @mingfang at the moment a tick only represents operations inside the sensor machinery, while a failure of a requested run is executed outside the sensor daemon and could be attributed to many other causes (other than the sensor machinery error), so we don't currently consider failed runs as a tick failure.

**Comment by sryza** [comment]
I'm going to close this because I don't think we should offer this functionality. Feel free to reopen if you disagree.
