### ISSUE TITLE
[docs] - Dynamic dagster setup example

### ISSUE THREAD

**Issue by xyzy-web** [dagster-io/dagster#3585]
## Use Case
I think it would be great to have an example that shows how to do a really dynamic dagster setup.
What I mean by dynamic is that it can run either locally via command line using cli, dagit or .py, via local docker compose and maybe even using the kubernetes helm chart. All in one repo, using the same definitions (which should all be in a subdirectory).

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
This is a fantastic idea!

**Comment by kstadler** [comment]
Happy you like it :-).

Basically this could be seen as a three phase development:
- write code locally using cli, dagit, .py
- once it is stable deploy it to local docker compose for a final QA and seeing stuff that is not available on sqlite backends like assets
- finally deploy everything to kubernetes/helm

**Comment by kstadler** [comment]
I've started an example project that tries to setup both local dagster as well as docker compose (based on the example in the official dagster repo) in the context of retrieving exchange rates.
I'm still troubled with setting up the grpc server to support the module directory, as posted in this StackOverflow questions:
https://stackoverflow.com/questions/65860584/how-to-start-the-grpc-server-when-definitions-are-in-a-module

The current version of this project is available at https://github.com/kstadler/dagster-exchangerates, please feel free to reuse anything for an official example if you find it usable.

**Comment by kstadler** [comment]
The grpc error has bee fixed, just to get another error.
I've posted an issue here: https://github.com/dagster-io/dagster/issues/3589

**Comment by kstadler** [comment]
The error is fixed.
I've started looking at the kubernetes setup, but the process for building the user code image is unclear.
I've opened a ticket asking for extending the documentation on this: https://github.com/dagster-io/dagster/issues/3590

**Comment by kstadler** [comment]
Figured out how to do it and included it in the example at https://github.com/kstadler/dagster-exchangerates

**Comment by kstadler** [comment]
I wonder what's the best approach for keeping versions consistent within a release...
In the example project I've statically pinned everything to the current dagster release 0.10.1 and gave the usercode image the same tag.
Currently the following places define their own version numbers:
- Pipfile (for local run)
- docker-compose.yml (for local Docker)
- values.yaml (Helm chart)
- versions file (for building and uploading the Kubernetes user code image)

Thanks to PyCharm I can change the version in one or two minutes, but I'd still prefer to define the version number in a single place.
Any ideas on how to do this?

**Comment by yuhan** [comment]
Hi @kstadler, really appreciate your feedback! Re: dynamic dagster setup example, this is a great idea and it _is_ something we currently have in mind as part of our documentation revamping effort. Will keep you posted once we have a better idea how to showcase this.

**Comment by AntonFriberg** [comment]
Hi! I also lacked more examples of a complete folder structure with easy setup using e.g. Docker-Compose in combination with local Python setup.

My current example is available here. https://github.com/AntonFriberg/dagster-project-example

**Comment by sryza** [comment]
`dagster project scaffold` now produces a project with a lot of this, and this issue has been here for a while, so I'm going to close this. Feel free to reopen and/or file a more specific issue if you think there's still missing functionality.
