### ISSUE TITLE
Add user-facing description field to sensors and schedules

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3587]
## Use Case

It would be good to have a user-facing description field for schedules and sensors. I would like to be able to look at sensor especially and see what are the conditions that it fires without having to examples code.

## Ideas of Implementation

Add description field and render in dagit

## Additional Info

For example here:

![Screen Shot 2021-01-23 at 11 55 40 AM](https://user-images.githubusercontent.com/28738937/105611367-0d8e0c00-5d72-11eb-8d4d-ac85eef268b5.png)

It would be great if there was a description field that said "Monitors the directory at $DAGSTER_TOY_SENSOR_DIRECTORY and fires whenever a new file appears in that directory"

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
This will need backend work, I would expect the UI part to be fairly trivial.

**Comment by prha** [comment]
Resolved in 252ea65fd
