### ISSUE TITLE
Increase UI polling rate for individual sensor and schedules pages or move to real-time subscriptions

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3588]
## Use Case

Right now our UI polls. Normally this isn't the worst but it is a bit brutal on a sensor or a schedule with fast ticks. One is having to deal with the reconciliation loop in the daemon as well the front UI loop, leading to counterintuitive behavior in the UI. If the timing is off, it can appear that the reconciliation loop is going much slower or out-of-date. Compounding the real-time left-to-right scroll promises a level of real-time we don't deliver.

## Ideas of Implementation

Assuming the polls are not particularly expensive, we could just ratchet up the frequency to mitigate the issue. Other option would be proper subscriptions.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
cc: @catherinewu who has been running into this while preparing demo

**Comment by schrockn** [comment]
While we're at it how set are we on the 15 second polling interval for a sensor? The faster this is the better. Why not every second?

**Comment by schrockn** [comment]
cc: @gibsondan as well

**Comment by hellendag** [comment]
@schrockn IMO not set on that 15 seconds at all, it was based on our existing poll intervals elsewhere in Dagit. I'm not sure what the backend considerations are for speeding up the polling (will defer to @gibsondan) but no objections from me on the frontend part.

**Comment by schrockn** [comment]
Cat already did this.

https://dagster.phacility.com/D6134

The question is is it actually a good idea? This would presumably worsen perf problems on problematic instances. Is this always going to be super cheap query?

**Comment by prha** [comment]
Yes, this will worsen perf problems... I have a diff stack to make this cheaper, by adding time-range based queries for ticks, and shortening the default window (e.g. view the last 7 days of ticks).

Maybe it's a good idea to implement subscriptions for ticks.  I can take a crack at it in the next couple days.

**Comment by prha** [comment]
I changed the query scheme to fetch by time window, setting a very aggressive poll interval (every second) for just the live sensor timeline view.  I think this already feels pretty good, doesn't overfetch too much data, and doesn't have some of the UI jitter that refetching all of the page data has.

Planning on punting on tick subscriptions unless this becomes a problem again.
