### ISSUE TITLE
Extended documentation for k8s / Build Docker image for User Code

### ISSUE THREAD

**Issue by xyzy-web** [dagster-io/dagster#3590]
## Use Case
The documentation at https://docs.dagster.io/deploying/k8s for building a user code docker image is pretty much non-existing.
The Dockerfile mentioned doesn't directly include the user code, instead this is somehow handled in the undocumented docker automation tools and seems to be targeted to the included examples only.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by kstadler** [comment]
I've figured out how to do it and included it on my example project at https://github.com/kstadler/dagster-exchangerates, in case anyone wants to take a look at it.

**Comment by yuhan** [comment]
Thanks @kstadler! We will take a look soon! cc @rexledesma @catherinewu
