### ISSUE TITLE
Better validation on docker image names in DockerRunLauncher

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3591]
## Summary
Invalid docker image names (e.g. starting with an underscore) give an unhelpful error in DagsterDockerLauncher: docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("invalid reference format")\n'

**Comment by fj-sanchez** [comment]
I have seen exactly the same issue, the problem is that the provided docker-example uses `DAGSTER_CURRENT_IMAGE: "${COMPOSE_PROJECT_NAME}_docker_example_pipelines"`, so if you don't have `COMPOSE_PROJECT_NAME` set it will produce an invalid image name.

**Comment by gibsondan** [comment]
Yeah, that's the most likely way to hit this right now - there's a .env file included in the example that's supposed to provide a default COMPOSE_PROJECT_NAME, but it's easy to miss (and the resulting error is very unclear).
