### ISSUE TITLE
Unable to build execution plan for historical run OR bad experience if there is a config error in queued run

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3593]
## Summary

Seeing this error: https://demo.elementl.show/instance/runs/c6836525-f035-4c9c-aa91-01ecfb66c078

This shouldn't be able to happen anymore since historical runs are loaded from the snapshot.

The other possibility is that the execution plan never built because config was invalid and it was queued. In that case is a pretty rough experience, especially the "Invariant". If this is the case here we should provide a clear error and leave the run is some known state

## Dagit UI/UX Issue Screenshots

![Screen Shot 2021-01-23 at 10 15 15 PM](https://user-images.githubusercontent.com/28738937/105621822-f0385c80-5dc8-11eb-92c2-d1410d53f73e.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by catherinewu** [comment]
related: https://github.com/dagster-io/dagster/issues/3583

**Comment by gibsondan** [comment]
We'll make this a tick failure rather than creating a failed run that can't be retried.
