### ISSUE TITLE
When run is in the STARTING state we should list something reasonable in the "Timing" column

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3595]
## Summary

We have some runs stuck in the STARTING state on elementl.show

https://demo.elementl.show/instance/runs?q=status%3ASTARTED%2Cstatus%3ASTARTING%2Cstatus%3ACANCELING

Right now you can't know when they were started without clicking through to the actual runs.

<img width="1084" alt="Screen Shot 2021-01-24 at 7 30 35 AM" src="https://user-images.githubusercontent.com/28738937/105633514-41227200-5e16-11eb-810e-33308a71275c.png">

We should have some sort of meaningful timestamp in there (like when the transition to STARTING happened"

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by johannkm** [comment]
Thought this was a UI change but it actually needs new info from the stats endpoint. Taking back over

**Comment by johannkm** [comment]
Added timing info for queued and starting runs
https://dagster.phacility.com/D6194
