### ISSUE TITLE
Four spinners in the runs view is a lot

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3596]
## Summary

When you initially load runs in the runs viewer you get four spinners. This is pretty rough/stressful and is worse with longer load times:

<img width="878" alt="Screen Shot 2021-01-24 at 7 40 39 AM" src="https://user-images.githubusercontent.com/28738937/105633774-ceb29180-5e17-11eb-9972-5ff037e02716.png">

With ongoing reloads there are three spinners.

<img width="669" alt="Screen Shot 2021-01-24 at 7 41 12 AM" src="https://user-images.githubusercontent.com/28738937/105633784-dbcf8080-5e17-11eb-98e6-0adcccb1dfdb.png">

So

1) I think we should chill this out on the UI side at a minimum
2) @catherinewu was able to get this UI and instance in a state with a large backfill that was borderline unusable. This page + load/backed up queries does not feel great. This might be a separate issue around generalized performance

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Yeah, we can strip out a few of these spinners. Also ugh that loading bar, we need to do something about that, everywhere.

@catherinewu Do you have reliable repro steps for the perf issue described above?

**Comment by hellendag** [comment]
Excess spinners have been reduced. Still need some details on the perf issue when you have a moment.
