### ISSUE TITLE
Unlabeled columns in runs view can cause confusion.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3597]
## Use Case

I think it is a bit confusing to list the snapshot hash only as the pipeline definition.

<img width="1072" alt="Screen Shot 2021-01-24 at 9 13 05 AM" src="https://user-images.githubusercontent.com/28738937/105636192-78981b00-5e24-11eb-8eba-38847a2825ad.png">

There are two cases to consider.

1) When it is the "live" pipeline
2) When it is a historical snapshot but the pipeline of that name is in the repo
3) When it is a historical snapshot but the pipeline is not in the repo

Seems like in case 1 and 2 at a minimum we should display the pipeline name in some form.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
Eh the pipeline name is over the tags i see. Maybe that is fine. But it certainly confused me for a bit. My eye found "pipeline" and then I didn't see a name. Given my intimate knowledge of the system I would suspect this would confuse users with less knowledge as well.

I probably should have looked more carefully but a a few points of confusion remain. Perhaps the left three columns do not have headers. I think we should list "run id", "status", "pipeline". The third column is the least clear since it contains pipeline name + tags.

**Comment by hellendag** [comment]
Cool, we can add some headers on those columns.

The pipeline name is intentionally not linked, since people were consistently clicking on that text when trying to view the run itself.
