### ISSUE TITLE
Tag filter UI in runs viewer can get in bad state with X does not work, and some X buttons actually duplicate tags

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3598]
## Summary

See video here: https://www.dropbox.com/s/cuhjvac6lvkakx8/Screen%20Recording%202021-01-24%20at%209.23.38%20AM.mov?dl=0

<img width="956" alt="Screen Shot 2021-01-24 at 9 27 41 AM" src="https://user-images.githubusercontent.com/28738937/105636661-6e771c00-5e26-11eb-833b-a638e1ca5261.png">

Link to repro:

https://demo.elementl.show/instance/snapshots/github_pipeline@942817168882333f486192056dc463f89200fccc/runs?q=snapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc%2CsnapshotId%3A942817168882333f486192056dc463f89200fccc

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
- We should not show the `X` on the snapshot ID and pipeline name tags, as in this view it is correct for them to be removable. (The view here is Runs for a specific snapshot ID)
- Hitting backspace while the pipeline name tag is focused appears to do the duplication bit. That's a lolzy bug, will fix.
