### ISSUE TITLE
Autocomplete for dagster CLI commands

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3599]
## Use Case
Implement shell autocomplete for CLI commands used in local development.

## Ideas of Implementation
https://click.palletsprojects.com/en/7.x/bashcomplete/

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by TrushaT** [comment]
Hello I am new here and would like your guidance to work on this issue

**Comment by sryza** [comment]
Hi @TrushaT - I or someone on our team would be happy to review a PR for this issue.  Do you have any questions?

**Comment by TrushaT** [comment]
Hi @sryza! Thanks a lot. Rn, I am working on setting up the project and referring to the link provided as a reference for implementation. When I do I will be sure to reach out. Just would take a bit of time since I am new to this repo.

**Comment by rexledesma** [comment]
Closing issue due to staleness.
