### ISSUE TITLE
Documentation on what Helm Chart version to use with what Dagster version

### ISSUE THREAD

**Issue by xyzy-web** [dagster-io/dagster#3600]
## Use Case
Please correct me if I'm wrong, but I'm assuming that using Helm the way it is described in the documentation only works with the Dagster release that is the most recent one.
It would be great if there would be documentation on which Dagster version uses which Helm Chart version and how to install using that version.

Use case would be e.g. when you  need to upgrade to an intermediate version before upgrading to the newest Dagster version.
Or when you can't migrate the user code to the newest version yet and need to setup a new cluster.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Great suggestion.

The Dagster version and Helm Chart version should have a 1:1 correspondence. In Helm, can be specified by passing a `--version` flag to commands (e.g. `helm show values --version $DAGSTER_VERSION`, as an example, see the [Helm docs on this](https://helm.sh/docs/helm/helm_show_values/)).

To show all the versions of the helm chart:
```bash
helm repo add dagster https://dagster-io.github.io/helm
helm search repo dagster/dagster --versions
```

And you can see our documentation for each Dagster version here: https://docs.dagster.io/versions

**Comment by kst83** [comment]
Great to see the Chart is already versioned with the same version numbers as Dagster :).
What I meant regarding the documentation is that there is no example in the Dagster documentation on how to setup older versions of Dagster using the corresponding Helm Chart version.
