### ISSUE TITLE
dagit's "Latest runs" and "Runs" page showing time as UTC+11, instead of local time (EST) (ver 0.10.1)

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#3604]
Hello,
In the dagit UI, the "Latest Tick" and the tick in the "Tick History" chart shows the correct local time of 06:30PM EST, but the "Latest runs" section, it is showing time as 10:30AM or I guess UTC+11 time zone.  In the bottom left of dagit, "Automatic (EST)" was selected as default option.  In my schedule definitions, I have `execution_timezone="US/Eastern"` set in my `@schedule` decorator.

![image](https://user-images.githubusercontent.com/3989299/105779799-1e3ead80-5f3d-11eb-9b97-2af497bb33d8.png)

**The "Runs" page is also showing my runs in UTC+11 also:**

![image](https://user-images.githubusercontent.com/3989299/105780424-6ca07c00-5f3e-11eb-934a-83db4e168438.png)

Is this to be expected or why are the Latest Runs and Runs page showing times in UTC+11?

My setup:
- Running local dagster instance and daemon
- Windows 10
- dagster/dagit version 0.10.1
- On-prem Postgresql 11.5

**Comment by nancydyc** [comment]
Hi @pybokeh, we're looking into this issue. The timestamp itself is wrong. I assume it’s writing the wrong timestamp to the db when the run kicks off or something similar to this. The log viewer for a given run looks like it has correct timestamps.

**Comment by pybokeh** [comment]
@nancydyc Thanks for  the update!  FWIW, when I switch to the default, local sqlite, I don't have this problem.  It shows the correct timestamp.  But, then when I switch to our on-prem Postgres, have this problem again.  I issued the `show timezone;` statement on the PostgreSQL server and it then returns `America/New_York`.   I am using `dagster-postgres==0.10.1`.

**Comment by nancydyc** [comment]
It might not be the Dagit UI issue. I would like to triage this to another group. @gibsondan do you need more details for this issue?

@pybokeh it would be helpful we can reproduce on our end.
