### ISSUE TITLE
[Internal] Fix "rebase on behalf of contributor" workflow

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3607]
## Summary

Context in the PR comments:
https://github.com/dagster-io/dagster/pull/3547

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Remote + upstream should be properly configured if you use `gh pr checkout PULL_REQUEST_NUM` for a contributor's branch. The command can be copypasted from the top right of the PR on web.
