### ISSUE TITLE
Configure sensor poll interval

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#3614]
Currently sensors evaluate at a 30s interval. Feature request for changing this interval either at the daemon level, or even per-sensor.

**Comment by johannkm** [comment]
@prha where would you think to place config for this? The queue daemon reads it from config on `QueuedRunCoordinator` on the instance, but since we don't have a sensor class on the instance it seems like there's not a great spot for an overall interval setting. Per sensor config probably makes more sense anyway, but is a bit harder to implement

**Comment by prha** [comment]
I think you could still probably add the config on the instance, there just wouldn't be a configurable class associated with it.

The daemon controller would fetch the value from the instance itself.

As for individual sensors, an interval that is a multiple of 30 seconds seems easier than doing something less than 30 seconds.  I could easily see us wanting to configure an S3 sensor of checking every 10 minutes, as opposed to every 30 seconds.

**Comment by prha** [comment]
This is done as of `0.10.6`
