### ISSUE TITLE
s3_resource exposes a boto3 client instead of resource

### ISSUE THREAD

**Issue by cgalliva** [dagster-io/dagster#3615]
## Summary

This is just a minor issue but the docs/docstring says that s3_resource provides access to `boto3.resource('s3')` but calling `context.resources.s3.Object()` results in: `AttributeError: 'S3' object has no attribute 'Object'` because it actually exposes the boto3 client. 

Looking at the source [here](https://github.com/dagster-io/dagster/blob/7a0477bed17468be3f9271e872c73b0582c7e74c/python_modules/libraries/dagster-aws/dagster_aws/s3/utils.py#L39) it creates the boto3.resource but then just returns the .meta.client which has it's own functionality. 

## Reproduction

type(context.resources.s3) yields <class 'botocore.client.S3'>

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @cgalliva.  This should help a little bit: https://dagster.phacility.com/D6222.

**Comment by markfickett** [comment]
I think I'm seeing the same issue in the docs for `dagster_aws` at https://docs.dagster.io/_apidocs/libraries/dagster-aws#s3 .

It lists this example:

```py
from dagster import job, op, Definitions
from dagster_aws.s3 import S3Resource

@op
def example_s3_op(s3: S3Resource):
    return s3.get_client().list_objects_v2(
        Bucket='my-bucket',
        Prefix='some-key'
    )

@job
def example_job():
    example_s3_op()

defs = Definitions(
    jobs=[example_job],
    resources={'s3': S3Resource(region_name='us-west-1')}
)
```

But that doesn't work for me until I remove the `get_client()` call.
