### ISSUE TITLE
[Content Gap] Re-execution Guide

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3624]
## What content is missing

From user: I know this was asked before, but one question — when re-running a pipeline containing heavy computations, are there mechanisms for avoiding re-computation of parts whose inputs haven’t changed? Let’s say the solids’ inputs [outputs] are results read from [dumped to] files Essentially some type of caching/invalidation mechanism.
 
## Type of the content
 
Dagster Guide: "How to do re-execution in Dagster" https://docs.dagster.io/guides

## (Optional) Anything in particular you want the docs to cover

walk users through an example which demonstrates the re-execution feature and covers different ways to re-execute a pipeline:
- Dagit https://docs.dagster.io/concepts/dagit/dagit#re-executing-a-run
- `reexecute_pipeline` Python API https://github.com/dagster-io/dagster/issues/3912 

original feature announcement: https://dagster.slack.com/archives/CCCR6P2UR/p1591917737019900

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
python api too: https://github.com/dagster-io/dagster/issues/3912

**Comment by yuhan** [comment]
https://docs.dagster.io/guides/dagster/re-execution

**Comment by yuhan** [comment]
https://docs.dagster.io/guides/dagster/re-execution
