### ISSUE TITLE
(Ver 0.10.2) dagit's "Tick History" chart no longer works, just shows constant spinning circle

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#3626]
Actually, the spinning circle is running even before turning on the schedule.  In other words, when viewing the page for the first time, the spinning circle animation is already running.

![image](https://user-images.githubusercontent.com/3989299/106232448-0deb3480-61c2-11eb-950b-ccbb93241b0e.png)

**My setup:**
- Windows 10
- Local dagit and daemon instance
- On-prem Postgresql ver 11.5
- dagster_postgres ver 0.10.2
- Chrome ver 87

I will report back using default sqlite db and see if the problem persists.

**Comment by pybokeh** [comment]
Switched to sqlite db and even waited for 2 runs to finish.  The constant spinning circle remained:

![image](https://user-images.githubusercontent.com/3989299/106233483-a682b400-61c4-11eb-947f-5119ac320aed.png)

**Comment by prha** [comment]
I can't repro this locally... Is there an error in the JavaScript console?  

Feel free to ping me (prha) in the elementl slack to help debug...

**Comment by pybokeh** [comment]
I switched to personal Ubuntu. running a toy pipeline, everything local with default sqlite db, and using Firefox browser ver 84.0.2

Sorry, I have little JS dev knowledge.  So I'm assuming you're wanting to see output from Firefox's web console.  Initially I am getting no output in Firefox's web console:

![image](https://user-images.githubusercontent.com/3989299/106278602-ff743b80-6208-11eb-8c5e-28764351133e.png)

Then I happen to look at the web console again and this showed up:

![image](https://user-images.githubusercontent.com/3989299/106278742-3e09f600-6209-11eb-9768-622b351f7c5e.png)

Zoomed in:

![image](https://user-images.githubusercontent.com/3989299/106278785-537f2000-6209-11eb-8153-0d2f2483d757.png)

**Comment by alangenfeld** [comment]
`

**Comment by prha** [comment]
This was very helpful, thanks!

This hit a bug when there's no tick history and the schedule has never been turned on.   I'll also get a reasonable message surfaced and push that out in `0.10.3`.

**Comment by prha** [comment]
Ah, I'll keep this open until `0.10.3` is released next Thursday

**Comment by pybokeh** [comment]
@prha Thanks!  I look forward to the 0.10.3 release today or whenever it is ready.

**Comment by pybokeh** [comment]
I've upgraded, but the problem still remains.

On the first schedule run, I did get an error:
```
An error occurred while resolving field DaemonHealth.allDaemonStatuses
Traceback (most recent call last):
  File "d:\python38\envs\dagster_dev\lib\site-packages\graphql\execution\executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "d:\python38\envs\dagster_dev\lib\site-packages\graphql\execution\executors\sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster_graphql\schema\instance.py", line 93, in resolve_allDaemonStatuses
    return [
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster_graphql\schema\instance.py", line 94, in <listcomp>
    GrapheneDaemonStatus(daemon_status) for daemon_status in self._daemon_statuses.values()
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster_graphql\schema\instance.py", line 56, in __init__
    lastHeartbeatErrors=[
TypeError: 'NoneType' object is not iterable
```

I was curious if the existing data in the Postgres was maybe causing problems, so I deleted all the dagster-related tables, re-ran the schedule.  Still no change, but no longer getting that error above.

No errors showing up in the web console either or in the dagit terminal or the daemon terminal:

![image](https://user-images.githubusercontent.com/3989299/106968725-687f1600-6717-11eb-8f95-5b4e446d1e52.png)

**Comment by pybokeh** [comment]
Looks like some time between the 2nd and 3rd run, got something in the web console:

![image](https://user-images.githubusercontent.com/3989299/106969317-9add4300-6718-11eb-92aa-7bb8a4c4182f.png)

**Comment by prha** [comment]
Sorry about that.  I'm going to run a patch release to pick up the fix for this (unrelated to the original error).  I think if you start the daemon using `dagster-daemon run` or run `dagster-daemon wipe`, this problem should go away.

**Comment by pybokeh** [comment]
Upgraded personal 'nix machine with all sqlite dbs removed, problem still remains with no output in web console after 2 runs:

![image](https://user-images.githubusercontent.com/3989299/106971291-9a46ab80-671c-11eb-9b4e-06703549f9b2.png)

Also did not get the `TypeError: 'NoneType' object is not iterable` error at any point.

**Comment by johannkm** [comment]
Hi @pybokeh, this is a new error from the latest release. Thanks for raising this- will get a fix out asap

**Comment by pybokeh** [comment]
@prha No worries!  I am amazed at what dagit does or what it is able to do with so much going on underneath the hood.  Just to clarify, which problem should go away?  The `TypeError` problem or the constantly spinning circle?  I just did `dagster-daemon wipe` then did `dagster-daemon run`, spinning circle still remains.  FYI, like before, the spinning circle was already animating when the schedule's page was first rendered.

**Comment by johannkm** [comment]
I have a [fix](https://dagster.phacility.com/D6317) ready for the `TypeError: 'NoneType' object is not iterable` issue, but I don't have any update on the spinner issue unfortunately.

**Comment by prha** [comment]
Hmm, curious why you're still getting the spinner.  And I guess you're not getting any errors in the console?  Would love to set up a time to dig into it with you.

**Comment by pybokeh** [comment]
@prha I just checked, after 17 runs, no output in the web console on my person machine.

![image](https://user-images.githubusercontent.com/3989299/106976994-763c9780-6727-11eb-8ea6-8f0e476e3dfd.png)

I can be free after 4pm EST.  You can hit me up on dagster's Slack (Daniel Kim).  Yes it is strange.  The tick history was working fine for me with 0.10.0 and 0.10.1.  I am puzzled that this problem can not be duplicated I'm assuming.

**Comment by prha** [comment]
Reopening until this is out in the release, but the main underlying issue was around fetching ticks for schedules added to the repo using the lazy repository dictionary.

Short-term work around would be to use the list-based repository definition.

Fixing rev is here:
https://dagster.phacility.com/D6359
