### ISSUE TITLE
partitions scrollbar missing in launch backfill modal

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3638]
## Summary

![image](https://user-images.githubusercontent.com/654855/106524873-fea50900-6497-11eb-8543-97a64cd960e1.png)

## Reproduction

* Open up the partitions page for the longitudinal pipeline
* Hit "Launch backfill"

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey folks! It looks like the scrollbar is hidden if you're using a mac with a trackpad and have the macOS standard "Show scroll bars when scrolling" setting on, but appears correctly if you're using a wired mouse or turn that feature off. I think that we could technically create a custom HTML scrollbar here, so it's less confusing though. Will investigate doing that!

![image](https://user-images.githubusercontent.com/1037212/107975038-1773eb00-6f7d-11eb-8baf-b8538134127d.png)
