### ISSUE TITLE
Swiggly for value mismatch should overlay on the value, not the key

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#364]
![screenshot 2018-12-07 07 28 32](https://user-images.githubusercontent.com/28738937/49656279-c9a0e700-f9f1-11e8-8290-e27e992d9418.png)

"3432" should be swiggled.

**Comment by mgasner** [comment]
I think this is resolved? @schrockn can you confirm and close?

**Comment by schrockn** [comment]
<img width="391" alt="screenshot 2018-12-17 16 55 18" src="https://user-images.githubusercontent.com/28738937/50125196-998ceb80-021c-11e9-93a7-77cb7eec774d.png">

nope still same thing

**Comment by schrockn** [comment]
I say we press forward with this for now but if we really feel strongly we could return a special error for "I expected a scalar and you gave me a dictionary/list" and other similar more specialized error conditions. I think scalar type mismatch will be more common, but who knows.
