### ISSUE TITLE
With long queue times run viewer is effectively useless

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3654]
## Summary

For example https://demo.elementl.show/instance/runs/cee1dab3-1b5a-443f-86f7-2406e7e51904

The header shows the execution takes 6.582 seconds but the gantt viewer includes the queueing.

As the screenshot shows, this makes the view fairly useless.

Seems like we can just change the gantt viewer to only proceed once it is started, rather than queued.

## Reproduction

https://demo.elementl.show/instance/runs/cee1dab3-1b5a-443f-86f7-2406e7e51904

## Dagit UI/UX Issue Screenshots

![Screen Shot 2021-02-05 at 11 08 33 AM](https://user-images.githubusercontent.com/28738937/107071838-9198b880-67a2-11eb-98d4-421883eff2d7.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by johannkm** [comment]
@hellendag I think this is something you had fixed for 0.10.0 right? I can look at what might have caused a regression

**Comment by bengotow** [comment]
Hmm this is interesting - it looks like it's using the run's createdAt date and not the pipeline "started" transition date to do the Gannt chart? We may have changed this so that things look like they're moving while the pipeline is starting but we should probably change it back...

**Comment by johannkm** [comment]
There's a `PIPELINE_STARTING` event that I corresponds to launch time- similar to the createdAt time when not using the queue. The time is surfaced in graphql run stats `launch-time`

**Comment by hellendag** [comment]
I had made a change here that prevented the Gantt from starting while the run was queued, but it's possible that I either missed something or there's a regression.
