### ISSUE TITLE
Dagster version mismatch on UI when enabling simplified dagit

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3659]
## Summary
The Dagster version changes when enabling simplified Dagit in `/settings`.

## Reproduction
Before:
<img width="538" alt="Screen Shot 2021-02-08 at 3 05 05 PM" src="https://user-images.githubusercontent.com/16431325/107274916-12fc7f00-6a1f-11eb-9394-b25101b07ab2.png">

After:
<img width="502" alt="Screen Shot 2021-02-08 at 3 05 10 PM" src="https://user-images.githubusercontent.com/16431325/107274904-0c6e0780-6a1f-11eb-8f50-0ecf220c4f51.png">

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
This is on my todo list.
