### ISSUE TITLE
sqlite event log watch problems on ephemeral instance

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#3665]
We have seen some reports of watching a pipeline run not working. 

This seems mostly to happen when a newer user is trying `dagit` out and has not yet set up `DAGSTER_HOME`, meaning they are on the "ephemeral" instance with a sqlite db in a `tempfile.TemporaryDirectory`. 

The hypothesis is that this is a problem at the intersection of `Watchdog` filesystem subscriptions and the temporary directory.

**Comment by gibsondan** [comment]
This could be related to why local tests related to the event log sometimes fail? See the comment above test_event_log_storage_watch for example.

**Comment by alangenfeld** [comment]
We should could use the polling observer that @sidkmenon added

**Comment by mrdavidlaing** [comment]
By setting TMPDIR to a location in my `~/homefolder` I was able to preserve the "ephemeral" dagit setup I find useful for local development AND have the Gantt/Logs view stream info during a pipeline run.

eg:

```
TMPDIR="~/tmp" dagit -w dagster_workspace.yaml
```
