### ISSUE TITLE
Investigate profiling of Kubernetes pods

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3669]
## Use Case
We should know if there are parts of our system that could serve to be optimized.

## Ideas of Implementation
https://cloud.google.com/profiler/docs/profiling-python#gke

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
this is pretty vague, @rexledesma want to make this more specific / actionable or close?

**Comment by rexledesma** [comment]
Closing since this is an Elementl issue and not a Dagster issue.
