### ISSUE TITLE
Support dbt JSON output schemas across multiple versions

### ISSUE THREAD

**Issue by chenbobby** [dagster-io/dagster#3673]
## Use Case
Currently, the library `dagster-dbt` has solids that will turn [dbt JSON output](https://docs.getdbt.com/reference/artifacts/dbt-artifacts) into Dagster `Output`s and `AssetMaterialization`s.

```
dbt JSON -> Python dict -> Python namedtuple -> Output / AssetMaterialization
```

Unfortunately, the parsing of dbt JSON output is based on an unofficial schema. In issue #3616, we found that dbt 0.19.0 broke some solids in `dagster-dbt` due to incorrect schema assumptions.

Ideally, `dagster-dbt` should be able to support dbt JSON output from versions 0.X.0 to 0.19.0 and beyond. I would argue for supporting dbt>=0.17.0 as a starting point.

### Option 1: Parse dbt output based on the user's version of dbt

1. Check the dbt version (e.g. running a shell command `dbt --version`).
2. Determine the JSON schema based on the dbt version from step 1.
2. Parse the dbt JSON output based on the JSON schema from step 2.
3. Use the parsed dbt output as a Dagster `Output` and `AssetMaterialization`.

**Pros**
- dbt version can be included in the `Output` and `AssetMaterialization`.

**Cons**
- Unknown future maintenance. Need to think more about this / create a prototype.

### Option 2: Parse any dbt output

1. Parse the dbt output as an arbitrary JSON object / Python dict.
2. Use the parsed dbt output as a Dagster `Output` and `AssetMaterialization`.

**Pros**
- Least likely to break when dbt releases a new schema version for dbt JSON output

**Cons**
- There will be many `Optional` and `None` values in the parsed dbt output.
- Unknown future maintenance. Need to think more about this / create a prototype.

## Additional Info

Starting with dbt 0.19.0, the dbt JSON output will have an officially documented JSON schema. [See docs on dbt Artifacts for details.](https://docs.getdbt.com/reference/artifacts/dbt-artifacts)

dbt 0.19.0 is the v1 JSON schema. They also provide a v0 JSON schema, which is the schema for dbt 0.18.1. For dbt<0.18.1, no JSON schema is available (but they should be relatively similar to v0).

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by chenbobby** [comment]
> Option 1: Parse dbt output based on the user's version of dbt

For dbt>=0.19.0, any JSON output should have a `metadata.dbt_version` and `metadata.dbt_schema_version` to assist with detecting the appropriate JSON schema to use.

However, for dbt<0.19.0, these `metadata.*` fields are not available, and the dbt version must be determined in another way (e.g. running a shell command `dbt --version`).

[See dbt docs for details on `metadata` fields](https://docs.getdbt.com/reference/artifacts/dbt-artifacts/#common-metadata)

**Comment by rexledesma** [comment]
dbt<1.0 is not supported anymore, so we can effectively rely on the contract that is provided by dbt now.
