### ISSUE TITLE
Automatic version detection for memoization

### ISSUE THREAD

**Issue by xyzy-web** [dagster-io/dagster#3680]
## Use Case
Right now you need to pass the version to the solid if you want to use memoization.
It would be great if the version would default to the hash of the file it is defined in.

## Ideas of Implementation
Maybe the method mentioned in https://stackoverflow.com/a/60297932/15066096 could be used?
Didn't test it though...

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
Hey Klaus thanks for the issue.

In general, we've been very hesitant to provide behavior like this since it could cause misleading behavior if applied generally. Two examples would be 1) a file you depend on changes or 2) a version of one of your dependencies changes, but of which would not alter the file of the code but could change behavior.

**Comment by kstadler** [comment]
I see, these cases really sound problematic.
How about adding this information to the memoization documentation page?
The current example is based around the method of using the file hash after all.

**Comment by schrockn** [comment]
Will let @sryza and @dpeng817 comment further as they directly worked on this!

**Comment by dpeng817** [comment]
Hey @kstadler thanks for trying out memoization! I think the way forward here is de-emphasizing the code versioning aspect of the memoization doc. 
- We can explain in more detail how memoization works, to make it clear that memoization will still work if a user sets code versions to some fixed value, but that Dagster will then only take into account changes in inputs/outputs/config.
- Generally de-emphasize the file hashing portion of the doc, explain that it is one way forward if someone wants to take code versions into account, but also explain the pitfalls of this approach.

**Comment by dpeng817** [comment]
I think this has been resolved by the addition of the SourceHashVersionStrategy, which provides an easy default.
