### ISSUE TITLE
Re-execution + step launchers doesn't work correctly

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#3682]
Logging this since I hit it while developing the dataproc step launcher; didn't have a chance to investigate further.

To repro, launch a step launcher execution that fails for some reason. Change code, kick off re-execution in Dagit. Get failure w/ stack trace below.

```
### gcs_dir_key='dagster-steplauncher/b5f8ac0a-6109-4f0d-a5dc-fb3d3dfc8d36/hello/step_run_ref.pkl'
### step_run_ref=StepRunRef(run_config={'resources': {'dataproc_cluster_client': {'config': {'region': 'us-central1'}}, 'dataproc_job_client': {'config': {'region': 'us-central1'}}, 'dataproc_step_launcher': {'config': {'project_id': 'elementl-dev', 'region': 'us-central1'}}}}, pipeline_run=PipelineRun(pipeline_name='my_pipeline', run_id='b5f8ac0a-6109-4f0d-a5dc-fb3d3dfc8d36', run_config={'resources': {'dataproc_cluster_client': {'config': {'region': 'us-central1'}}, 'dataproc_job_client': {'config': {'region': 'us-central1'}}, 'dataproc_step_launcher': {'config': {'project_id': 'elementl-dev', 'region': 'us-central1'}}}}, mode='dev', solid_selection=None, solids_to_execute=None, step_keys_to_execute=None, status=<PipelineRunStatus.STARTING: 'STARTING'>, tags={'.dagster/grpc_info': '{"host": "localhost", "socket": "/var/folders/kp/8t3lgkhx0g7gcsngly7r34dw0000gn/T/tmp1ehcje93"}', 'dagster/parent_run_id': '1c130195-ba9b-4e85-9f8b-3c0f5027c958', 'dagster/root_run_id': '588f80c7-6a67-422a-a980-38a1bfa6acd1', 'dagster/solid_selection': '*'}, root_run_id='588f80c7-6a67-422a-a980-38a1bfa6acd1', parent_run_id='1c130195-ba9b-4e85-9f8b-3c0f5027c958', pipeline_snapshot_id='19991491854a901451846ba5c4e1ef56962b2c10', execution_plan_snapshot_id='e4e5aaddc906c8aa7f90680b6a734c61724b3d4d', external_pipeline_origin=ExternalPipelineOrigin(external_repository_origin=ExternalRepositoryOrigin(repository_location_origin=ManagedGrpcPythonEnvRepositoryLocationOrigin(loadable_target_origin=LoadableTargetOrigin(executable_path='/Users/nate/.pyenv/versions/3.8.5/envs/dagster38/bin/python3.8', python_file=None, module_name=None, working_directory=None, attribute=None, package_name='hacker_news'), location_name='hacker_news'), repository_name='my_repository'), pipeline_name='my_pipeline')), run_id='b5f8ac0a-6109-4f0d-a5dc-fb3d3dfc8d36', retries=<dagster.core.execution.retries.Retries object at 0x7fa25bb68c70>, step_key='hello', recon_pipeline=ReconstructablePipeline(repository=ReconstructableRepository(pointer=PackageCodePointer(module='hacker_news', attribute='my_repository'), container_image=None), pipeline_name='my_pipeline', solid_selection_str=None, solids_to_execute=None), prior_attempts_count=0)
2021-02-14 04:25:49 - dagster - DEBUG - my_pipeline - b5f8ac0a-6109-4f0d-a5dc-fb3d3dfc8d36 - 9280 - hello - ENGINE_EVENT - Starting initialization of resources [dataproc_cluster_client, dataproc_job_client, dataproc_step_launcher, gcs_client, io_manager].
2021-02-14 04:25:49 - dagster - DEBUG - my_pipeline - b5f8ac0a-6109-4f0d-a5dc-fb3d3dfc8d36 - 9280 - hello - ENGINE_EVENT - Finished initialization of resources [dataproc_cluster_client, dataproc_job_client, dataproc_step_launcher, gcs_client, io_manager].
Traceback (most recent call last):
  File "/tmp/510d94ee-949f-4347-93eb-892789e2defd/dataproc_step_main.py", line 92, in <module>
    main(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/tmp/510d94ee-949f-4347-93eb-892789e2defd/dataproc_step_main.py", line 50, in main
    for event in run_step_from_ref(step_run_ref, instance):
  File "/opt/conda/default/lib/python3.8/site-packages/dagster/core/execution/plan/external_step.py", line 180, in run_step_from_ref
    step_context = step_run_ref_to_step_context(step_run_ref, instance)
  File "/opt/conda/default/lib/python3.8/site-packages/dagster/core/execution/plan/external_step.py", line 169, in step_run_ref_to_step_context
    for _ in initialization_manager.prepare_context():
  File "/opt/conda/default/lib/python3.8/site-packages/dagster/utils/__init__.py", line 411, in generate_setup_events
    obj = next(self.generator)
  File "/opt/conda/default/lib/python3.8/site-packages/dagster/core/execution/context_creation_pipeline.py", line 253, in event_generator
    raise dagster_error
  File "/opt/conda/default/lib/python3.8/site-packages/dagster/core/execution/context_creation_pipeline.py", line 227, in event_generator
    _validate_plan_with_context(execution_context, execution_plan)
  File "/opt/conda/default/lib/python3.8/site-packages/dagster/core/execution/context_creation_pipeline.py", line 341, in _validate_plan_with_context
    validate_reexecution_memoization(pipeline_context, execution_plan)
  File "/opt/conda/default/lib/python3.8/site-packages/dagster/core/execution/memoization.py", line 18, in validate_reexecution_memoization
    raise DagsterRunNotFoundError(
dagster.core.errors.DagsterRunNotFoundError: Run id 1c130195-ba9b-4e85-9f8b-3c0f5027c958 set as parent run id was not found in instance
```

**Comment by alangenfeld** [comment]
Are we using an ephemeral instance on the receiving end of the step launch? If yes we could case against that in `validate_reexecution_memoization`

**Comment by Sourabh-dot** [comment]
When is this issue getting resolved? at the moment The following code raises the exception and does not re-execute the pipeline
from random import random

f```
rom dagster import ModeDefinition, fs_io_manager, pipeline, solid, reexecute_pipeline, execute_pipeline, \
    DagsterInstance


@solid()
def unreliable_start(_):
    print("1")
    return 1


@solid()
def unreliable(_, num):
    failure_rate = 0.5
    print("2")
    if random() < failure_rate:
        raise Exception("blah")


@solid()
def unreliable_end(_, num):
    print("3")
    return


@pipeline(mode_defs=[ModeDefinition(resource_defs={"io_manager": fs_io_manager})])
def unreliable_pipeline():
    unreliable_end(unreliable(unreliable_start()))


def reexecution():
    instance = DagsterInstance.ephemeral()

    # Initial execution
    pipeline_result_full = execute_pipeline(unreliable_pipeline, instance=instance)
    print(pipeline_result_full.result_for_solid("unreliable_end"))

    if not pipeline_result_full.success:
        # Re-execution: Entire pipeline
        reexecution_result_full = reexecute_pipeline(
            unreliable_pipeline,
            parent_run_id=pipeline_result_full.run_id,
            instance=instance,
        )
        return reexecution_result_full


if __name__ == '__main__':
    reexecution()
```

**Comment by Sourabh-dot** [comment]
When is this issue getting resolved? The following code raises the exception in the second solid but does not re-execute the pipeline. This code is from the Dagster documentation.

from random import random

from dagster import ModeDefinition, fs_io_manager, pipeline, solid, reexecute_pipeline, execute_pipeline, \
    DagsterInstance


@solid()
def unreliable_start(_):
    print("1")
    return 1


@solid()
def unreliable(_, num):
    failure_rate = 0.5
    print("2")
    if random() < failure_rate:
        raise Exception("blah")


@solid()
def unreliable_end(_, num):
    print("3")
    return


@pipeline(mode_defs=[ModeDefinition(resource_defs={"io_manager": fs_io_manager})])
def unreliable_pipeline():
    unreliable_end(unreliable(unreliable_start()))


def reexecution():
    instance = DagsterInstance.ephemeral()

    # Initial execution
    pipeline_result_full = execute_pipeline(unreliable_pipeline, instance=instance)
    print(pipeline_result_full.result_for_solid("unreliable_end"))

    if not pipeline_result_full.success:
        # Re-execution: Entire pipeline
        reexecution_result_full = reexecute_pipeline(
            unreliable_pipeline,
            parent_run_id=pipeline_result_full.run_id,
            instance=instance,
        )
        return reexecution_result_full


if __name__ == '__main__':
    reexecution()

**Comment by OwenKephart** [comment]
What's happening here is a legitimate error that doesn't have a super easy fix (as far as I can tell). Loading inputs from upstream steps during re-execution hits the dagster event log database if that output was not produced during the current run (as can happen if you're re-executing a subset of your job).

I think this is the offending bit of code: https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/core/execution/context/system.py?L496:9

Step launchers don't have access to the events database (nor can they in most circumstances), so it is genuinely impossible for them to load the output without us sending them some more information. Seems possible, but it might be a bit tricky to figure out the exact set of events we want to send over.

We could probably do something hacky where we call this function when creating a StepRunRef and somehow inject this information into the ephemeral instance, but I don't have a super clear view of how that would work.

**Comment by OwenKephart** [comment]
resolving this: https://github.com/dagster-io/dagster/issues/3511

should resolve the step launcher issue as well

**Comment by OwenKephart** [comment]
As long as a step launcher is implemented using external_instance_from_step_run_ref(), re-execution will work
