### ISSUE TITLE
Add overview page for cron based schedules

### ISSUE THREAD

**Issue by xyzy-web** [dagster-io/dagster#3683]
## Use Case
Currently there is only an overview page for partition based schedules (the partitions page of each pipeline).

It would be great if either cron based schedules could be integrated here or there would be a similar page without backfilling options for cron based schedules.

That way you could see success rates and execution times for cron based schedules too.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Going to close this because it's now possible to build partitioned schedules from a cron expression, which allows accessing this behavior.
