### ISSUE TITLE
IndexError when every step in the pipeline is memoized

### ISSUE THREAD

**Issue by ravwojdyla** [dagster-io/dagster#3687]
## Summary
Getting:
```python
    for step in self.get_steps_to_execute_by_level()[0]:
IndexError: list index out of range
```
when all steps in the pipeline are memoized.

## Reproduction
Example code: https://gist.github.com/ravwojdyla/6a546e3fa65459b17413aac10c643f25

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by ravwojdyla** [comment]
FYI @dpeng817 and thanks for your help on slack!

**Comment by alangenfeld** [comment]
believe this got fixed
