### ISSUE TITLE
MemoizableIOManager doesn't handle "duplicated" run instances

### ISSUE THREAD

**Issue by ravwojdyla** [dagster-io/dagster#3693]
## Summary
This might be more of a design bug or request for feature. But afaiu memoization/`MemoizableIOManager` depends on solid's version and config, and should resolve if there is already output based on that local information. And afaiu dagster currently supports multiple instances of dagit, or even running the same pipeline by two separate VMs (or developers). This means that there might be a case when there is more than 1 instance of the same memoized solid running potentially creating conflict at "write"/materialisation time of the output.

In other systems these problems are resolved by having "global coordinator", afaiu:
 * Airflow has global dag bag
 * Luigi you have the "global scheduler" process to resolve this conflict
 * Prefect requires registration to global scheduler

To reproduce you can write a pipeline that uses `MemoizableIOManager` and writes results to global location, like object store, and have two developers start it at the same time with the same config.

I would also suggest that this limitation should be well documented in the memoization documentation.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by ravwojdyla** [comment]
FYI @dpeng817

**Comment by ravwojdyla** [comment]
👋 @dpeng817 anything I could help with in regards to the context of this issue?

**Comment by sryza** [comment]
Hi @ravwojdyla apologies for the delay here. What would be your desired behavior? If two people kick off memoizable solids that would end up writing to the same object, ideally would you like only one of the solids to execute and the other solid to wait until the first one has completed?

**Comment by sryza** [comment]
Dagster contains "global" state inside an "instance".  An instance includes a database of runs and events, and multiple Dagit web servers can run against the same instance.  Here's Dagster's instance documentation: https://docs.dagster.io/deployment/dagster-instance.

For "advanced" usage, Dagster provides access to a Python object that can read data from the instance via 
 `context.system_context.instance`.

To achieve the behavior I asked about above, it would likely require some ability to take out a lock on an instance-level object that corresponds to the memoized version ID.  We don't currently have that kind of object or the ability to take out locks in that way.

**Comment by ravwojdyla** [comment]
👋  @sryza Sorry for the delay on my end!

> What would be your desired behavior? If two people kick off memoizable solids that would end up writing to the same object, ideally would you like only one of the solids to execute and the other solid to wait until the first one has completed?

Ideally, I would like one solid to execute, and another to wait **or** fail with "concurrent execution error", I can see reasons for either way, and also either is better than potentially corrupted data.

> It would likely require some ability to take out a lock on an instance-level object that corresponds to the memoized version ID. We don't currently have that kind of object or the ability to take out locks in that way.

Yes, in my mind it's very similar to how Luigi works with it's global "scheduler", which essentially acts as a global lock.

@sryza how would you like to proceed with this issue?

**Comment by sryza** [comment]
Got it - that request makes sense. It’s outside the scope of what our current memoization strives to do, but I can imagine that it could be a useful addition in the future.

Is there Luigi documentation you’d be able to point me to that could be useful as inspiration?

**Comment by ravwojdyla** [comment]
@sryza see the high level doc here: https://luigi.readthedocs.io/en/stable/central_scheduler.html. Luigi itself is a relatively small amount of code, so the code itself might actually be the best documentation, see: https://github.com/spotify/luigi/blob/master/luigi/scheduler.py. Hope this is helpful.

**Comment by sryza** [comment]
Thank @ravwojdyla

**Comment by sryza** [comment]
MemoizableIOManager is now deprecated in favor of the asset versioning system, so closing this.
