### ISSUE TITLE
Surface config errors, python errors from the backfill launch flow in dagit

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#3695]
## Summary

We should display an error dialog for error conditions from launching the backfill (show a dialog, prompt to open in playground, etc).

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey folks! I took another look at this today and it looks like we're surfacing errors correctly now. I think this may have been fixed with the addition of the dagster-daemon? I needed to run migrations and launch the daemon locally and the error was displayed nicely. 👍
