### ISSUE TITLE
Renaming a running schedule crashes the daemon

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3703]
## Summary

![image](https://user-images.githubusercontent.com/16431325/108300767-ece98400-716e-11eb-9cf4-ca99d46aae03.png)

The previously named schedule becomes an unloadable schedule when viewing the schedules page. The issue is resolved by turning the unloadable schedule off.

## Reproduction
Add a schedule, turn it on, then rename the schedule.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
This is happening inside a try/catch loop so I'd be surprised if it was causing a crash? Other schedules should still be running even.

either way we should definitely improve the error language here no matter what (both in the error itself and in Dagit - "restarting the daemon" isn't applicable if I'm right and it isn't crashing)

**Comment by schrockn** [comment]
Yeah that all makes sense. I didn't do much investigation aside from seeing CrashLoopBackoff in k9s happening a lot while I was seeing this issue and https://github.com/dagster-io/dagster/issues/3701. There might be some other stuff going on in the deployment though. I'm seeing some pretty aggressive resource consumption that I can't explain. See below:

<img width="1403" alt="Screen Shot 2021-02-17 at 9 01 14 PM" src="https://user-images.githubusercontent.com/28738937/108303568-65e2de80-7163-11eb-86e4-459907df812f.png">

So the crash could potentially be an unrelated issue.
