### ISSUE TITLE
Errors in compute log uploading result in "framework error"

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3708]
![Screen Shot 2021-02-18 at 10 03 38 PM](https://user-images.githubusercontent.com/28738937/108460118-38666580-7235-11eb-97b9-ed16df447b3d.png)

![Screen Shot 2021-02-18 at 10 03 42 PM](https://user-images.githubusercontent.com/28738937/108460134-41efcd80-7235-11eb-844c-58b7e23956b7.png)

An error in this case was thrown in `on_watch_finish` and the exception escaped to a top-level pipeline failure.

Scary error since it involves uploading logs but probably should have an error boundary in this stack somewhere.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment]
this seems to be related to dagster instance set up as the compute log manager is configured at the instance level, and it seems only apply to cloud use cases. @catherinewu  can you take a look?
