### ISSUE TITLE
dagit grpc error

### ISSUE THREAD

**Issue by nickfielding** [dagster-io/dagster#3709]
## Summary
Dagit has a grpc metadata leak which causes dagit to fail (error messages below).  The javascript elements of dagit will work (i.e. the run page will update with new jobs) but it is not possible to do a full page refresh or navigate to other pages.

Requires a full restart of dagit.  This was often accompanied by a "python.exe" error which would cause the schedule daemon to pause also.

## Reproduction
```
E0219 06:12:18.808000000  8756 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:12:18.810000000  8756 src/core/lib/transport/metadata.cc:260] mdelem ':authority' = 'localhost:62589'
E0219 06:12:18.817000000  8756 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:12:18.824000000  8756 src/core/lib/transport/metadata.cc:260] mdelem ':authority' = 'localhost:62501'
E0219 06:12:18.986000000  8756 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:12:18.996000000  8756 src/core/lib/transport/metadata.cc:260] mdelem 'user-agent' = 'grpc-python/1.35.0 grpc-c/14.0.0 (windows; chttp2)'
E0219 06:12:19.086000000  8756 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:12:19.092000000  8756 src/core/lib/transport/metadata.cc:260] mdelem ':authority' = 'localhost:62668'
E0219 06:12:19.167000000  8756 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:12:19.250000000  8756 src/core/lib/transport/metadata.cc:260] mdelem 'grpc-message' = ''
E0219 06:34:12.115000000  7472 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:34:12.117000000  7472 src/core/lib/transport/metadata.cc:260] mdelem 'user-agent' = 'grpc-python/1.35.0 grpc-c/14.0.0 (windows; chttp2)'
E0219 06:34:12.119000000  7472 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:34:12.124000000  7472 src/core/lib/transport/metadata.cc:260] mdelem 'grpc-message' = ''
E0219 06:34:12.296000000  7472 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:34:12.297000000  7472 src/core/lib/transport/metadata.cc:260] mdelem ':authority' = 'localhost:62668'
E0219 06:34:12.298000000  7472 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:34:12.300000000  7472 src/core/lib/transport/metadata.cc:260] mdelem ':authority' = 'localhost:62559'
E0219 06:34:39.054000000  7332 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:35:43.620000000  7332 src/core/lib/transport/metadata.cc:260] mdelem 'grpc-message' = ''
E0219 06:36:08.700000000  7332 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:36:31.611000000  7332 src/core/lib/transport/metadata.cc:260] mdelem 'user-agent' = 'grpc-python/1.35.0 grpc-c/14.0.0 (windows; chttp2)'
E0219 06:37:14.627000000  7332 src/core/lib/transport/metadata.cc:253] WARNING: 1 metadata elements were leaked
E0219 06:38:33.069000000  7332 src/core/lib/transport/metadata.cc:260] mdelem ':authority' = 'localhost:62518'
```

## Additional Info about Your Environment
Windows Server 2016.  Python 3.8

**Comment by gibsondan** [comment]
Hi @nickfielding - I haven’t seen this before, a few follow up questions to help us get to the bottom of it:

If it’s happening on a specific pipeline and it’s possible to share the code that would be very helpful. 

Is it possible to share the full output of the logs from dagit and/or the daemon? I’m wondering if there’s any output from earlier that could explain more about what’s going on.

Finally, which version of Dagster are you using?

**Comment by nickfielding** [comment]
Hi,

I haven't been able to isolate it to a particular pipeline (it tends to happen in the morning when we have a lot of pipelines running and I can't find out if it is a specific one).

Since exclusively using the scheduler the errors happen, but it isn't killing Dagit.  So maybe it was something about how I was triggering the pipelines from the command line.

What is the best way of exporting the logs?

Latest version of Dagster - 0.10.6

**Comment by gibsondan** [comment]
This sounds like it could be hitting some kind of resource limit on your machine (e.g. an out-of-memory issue). Having the logs would help diagnose, but if there's a way to monitor the CPU and memory usage of your machine or deployment that could give some useful clues as well. 

The way to get the logs depends on your deployment setup - if your dagit and dagster-daemon process are all on a single machine, you can pipe the commands to a file (dagit | tee ~/dagitlogs.txt) and then send us the contents of that file.

If it's specifically happening when many pipelines are running at once, one thing that might help is limiting the number of runs using the techniques here: https://docs.dagster.io/overview/pipeline-runs/limiting-run-concurrency

Finally since you mentioned the scheduler  -there are some performance improvements landing in this week's release that should make the daemon use fewer resources when running several schedules or sensors from the same repository, those could also help.

**Comment by sryza** [comment]
Closing because haven't heard back on this for a while. Feel free to reopen if it's still something you're encountering.
