### ISSUE TITLE
Partition Set out of sync with mode in Playground

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3711]
## Summary

When selecting a partition set in the playground UI it does not switch to the correct mode in the UI.

For example with this partition set:

![Screen Shot 2021-02-19 at 7 43 51 AM](https://user-images.githubusercontent.com/28738937/108519328-c28aea00-7286-11eb-994a-88a2fe6d5e13.png)

We get this behavior in playground.

![Screen Shot 2021-02-19 at 7 43 41 AM](https://user-images.githubusercontent.com/28738937/108519372-cae32500-7286-11eb-8a9b-6ee2f2e0db46.png)

It should match the mode. It appears that the run has the correct mode when instantiated.

![Screen Shot 2021-02-19 at 7 48 32 AM](https://user-images.githubusercontent.com/28738937/108519480-e64e3000-7286-11eb-87b1-7c57ff081df4.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Was able to reproduce this just now - it looks like the UI is only out of sync briefly (the mode updates to the mode defined by the partition set once you choose a partition), but it seems like something we should be able to fix easily.
