### ISSUE TITLE
Confusing terminal output when you start dagit without DAGSTER_HOME set

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3717]
if DAGSTER_HOME is not set, dagit creates a temporary folder for instance information and then complains about it not having a dagster.yaml file. This is confusing.

Is there a reason not to have dagit require DAGSTER_HOME to be set?

Sample output:

(dagster-3.8.3) dgibson@Daniels-MacBook-Pro dagster % unset DAGSTER_HOME
(dagster-3.8.3) dgibson@Daniels-MacBook-Pro dagster % dagit
/Users/dgibson/dagster/python_modules/dagster/dagster/core/instance/config.py:22: UserWarning: The dagster instance configuration file (dagster.yaml) is not present at /var/folders/nr/y4m1jv5d7836kpcw4x2lb9rh0000gn/T/tmph4hthekm. Dagster uses this file to know where and how to store local artifacts, information about past runs, and structured events.

**Comment by alangenfeld** [comment]
> Is there a reason not to have dagit require DAGSTER_HOME to be set?

I think its nice for initial trial / spin up that you don't have to set an environment variable, but we should print out a message communicating clearly the state and definitely not that current warning message.

**Comment by mingfang** [comment]
simple solution would be to default DEFAULT_HOME to the current directory in case it is not set
