### ISSUE TITLE
Asset Materializations during development / testing / debugging

### ISSUE THREAD

**Issue by davidz-1** [dagster-io/dagster#3725]
## Use Case
During fitting of ML models we want to track certrain key figures like the models accuracy. 
For tracking we use the asset materializations, but during development / testing / debugging any materalizations should be avoided.
How do we make sure that those materializations only happen while using a productive pipeline preset / mode?

## Ideas of Implementation
Add a flag to the ModeDefinition, which avoids any materializations if set.

## Additional Info
Please let me know if a soluton for this  problem already exist. I've saw the usage of materializatons in IOManagers which could be switched as resources with using another mode, but most of our materializations are part of solids not IOManagers.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @davidz-1 - what do you think about doing the following?
```
@solid
def my_solid(context):
    ...
    if context.mode_def.name == "prod":
        yield AssetMaterialization(...)
    ...
```

**Comment by davidz-1** [comment]
@sryza thanks for the quick answer, that should do for us. During unittesting of a solid the `mode_def` could be set with `execute_solid` as far as I understood.

**Comment by yuhan** [comment]
@davidz-1 glad to hear that this works for you - going to close this. Feel free to reopen if you have any more questions/problems on this issue
