### ISSUE TITLE
Some mismatches and odd names with new type: filteres

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3728]
## Summary

See the mismatch between STEP_MATERIALIZATION and AssetMaterialization here.

![Screen Shot 2021-02-23 at 4 21 00 PM](https://user-images.githubusercontent.com/28738937/108921235-49c3bf00-75f3-11eb-9aa0-8c0a3faaecca.png)

All the other steps have exact matching strings here.

ASSET_MATERIALIZATION is a much better name. In the short term I would consider mapping this at the GraphQL layer rather than a migration of any sort.

It would also be useful to filter out known enum entries that are deprecated. For example type:ASSET_STORE_OPERATION is a legacy artifact.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by schrockn** [comment]
This would be very nice to fix before Thursday, as this is the only event type I actually search for in my demos.

I added @alangenfeld who will have more historical context on deprecated event types.

**Comment by hellendag** [comment]
cc @yuhan since we noticed this yesterday too. Will put together a fix.

**Comment by hellendag** [comment]
The `step` filter options now match the rendered tags. Seems like `STEP_MATERIALIZATION` should still be renamed or remapped to `ASSET_MATERIALIZATION`, and I'm not entirely sure of the cleanest way to do that.

**Comment by hellendag** [comment]
I think this counts as done.
