### ISSUE TITLE
Difficult to find somewhat recent sensor ticks

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3729]
## Use Case

Right now in the sensor UI there are "Recent" ticks. 

![Screen Shot 2021-02-23 at 4 47 12 PM](https://user-images.githubusercontent.com/28738937/108923872-d1f79380-75f6-11eb-95e5-ae2a9244760c.png)

And then "7 days" ticks

![Screen Shot 2021-02-23 at 4 47 52 PM](https://user-images.githubusercontent.com/28738937/108923926-ea67ae00-75f6-11eb-92e9-00bc3181c139.png)

This makes it somewhat difficult to find a tick that happened within the last few hours, which is a common use case.

## Ideas of Implementation

Two ideas here:

1) Have a "last 24 hour" window
2) I think 1 is mitigating. I think this UI is missing just a simple "list" view of ticks. The scrolling timeline is impressive and useful in certain contexts, but I believe we are missing out on some core utility by not a list of ticks UI somewhere. This is especially true when "skip reason" contains useful information. Right now you have to mouseover individual runs.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
I'll add a 24h view and pass this along to the Scheduled Runs project.

**Comment by hellendag** [comment]
Landed "1 day" view. Passing to Scheduled Runs for list view.

**Comment by yuhan** [comment]
@hellendag is whats missing here a backend api which returns a list of recent ticks to support the list view? if so, @prha is it easy to support

**Comment by prha** [comment]
We already have the graphql API to fetch ticks.  That's what powers the timeline view.

**Comment by sryza** [comment]
Now that we have tick history as a table, it's easy to find sensor ticks of any age, so closing this
