### ISSUE TITLE
Track which user manually kicked off a pipeline run

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3732]
## Use Case

There are many reasons you'd want to know who kicked off a run:
- There is an active backfill of X00 jobs that is blocking a high priority pipeline from running. You'd want to know who to ping to see if the backfill is safe to be paused, and ask owner to add a concurrency limit
- Disambiguate whether a run was manually triggered or kicked off by the scheduler / sensor
- You notice that two people both kicked off a re-execution for a single failed run, but you don't know who these two people are and the simultaneous re-execution can produce undesirable effects by stepping on each others' toes
- Birds-eye view of dagster system usage, want to understand which users are using dagster the most and for what use cases

@alangenfeld had the suggestion of enforcing "required tags" for manual executions (or just backfills), so that users remember to add their name as a tag on executions (or just backfills). 

Another suggestion is to allow user to set their name somewhere within dagit (can be saved to local storage) and add the tag automatically 

Related: https://github.com/dagster-io/dagster/issues/2219

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
This involves broader questions of integrating identity into the product, and we probably shouldn't try to do anything superficial within Dagit to hack it into place. Passing to Core.

**Comment by rexledesma** [comment]
This is supported by default in Dagster Cloud. In open-source, we have an example for run attribution: as achieved from https://github.com/dagster-io/dagster/commit/400c3c573f265e6439dd83c2740808dfb51e00cb. See https://docs.dagster.io/guides/dagster/run-attribution.

**Comment by leonardovff** [comment]
https://github.com/dagster-io/dagster/actions/runs/6867528915/job/18676077839

**Comment by leonardovff** [comment]
If yes, is there another option how implement/have it?
