### ISSUE TITLE
asset page small issues

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3733]
Created this issue to collect a set of small thoughts I had about the asset page.  We can jettison any of these into their own issues if convenient:
* Somewhere, we should display the name of the pipeline that generated the asset.  We should also probably include the mode name, if it's not "default".
* Somewhere, we should display the name of the step that generated the asset.
* When graphing values by partition, the latest data point for each partition should be displayed, not the maximum.  This is because the latest run will typically overwrite previous values for that partition, so they're way less relevant.
* We should consider automatically rendering markdown inline instead of requiring a click to pop it out.  E.g. if someone wants to use markdown to structure metadata about the columns in their table, this is important enough information that it should show up without an extra click.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
Adding to this. Right now you have to click through a bunch of things to get to pipeline definition that produced the asset. 

Asset Catalog -> Run -> Pipeline Snapshot --> Pipeline

It's very rough.

Should be able to go from Asset Catalog --> Pipeline in a single click

This issue might be important enough to warrant its own issue

**Comment by sryza** [comment]
Ah yes I have experienced difficulty with that as well

**Comment by bengotow** [comment]
Hey folks! I think we should definitely show the pipeline + step alongside the "latest run" hash, but I'm a little worried about making assets look like they're coupled to a specific pipeline. (Though in practice maybe that's almost always the case...)  Technically these asset pages might show run ID hashes from several pipelines as you look through the materialization grid / list.

**Comment by bengotow** [comment]
Asset page => pipeline linking and also mode display has been addressed in https://dagster.phacility.com/D6824

**Comment by bengotow** [comment]
This should resolve the remaining issues - https://dagster.phacility.com/D6825

The header area was starting to look a little strange with a separate table row for run / step name / pipeline / mode / timestamp, etc so I unified a few of them into "Latest source", which I think looks a bit better, but I'm open to thoughts on the diff!

![image](https://user-images.githubusercontent.com/1037212/110360587-8389c200-8004-11eb-9e0e-c009e1c0a11b.png)

**Comment by sryza** [comment]
Thanks for fixing all these @bengotow !
