### ISSUE TITLE
`dagster-dbt` tests fail to cover dbt's configuration space.

### ISSUE THREAD

**Issue by chenbobby** [dagster-io/dagster#3739]
## Problem
Dagster can bring a lot of advantages to existing dbt projects, and `dagster-dbt` is the official entrypoint for an integration. However, the tests for solids in `dagster-dbt` have shallow coverage over dbt's configuration space.

It is inevitable that updates in dbt may cause breakages to `dagster-dbt`, so we should at least catch the most common breakages in our tests. Currently, this is not the case.

## Ideas of Implementation
Along the lines of [this example test](https://github.com/dagster-io/dagster/blob/a07fc28ae6878235aeada88e3584c6dea01f845b/python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_solids.py#L39), we should add more testing for different permutations of dbt config.

Ideally, we should also cover failure scenarios and ensure that `dagster-dbt` provides adequate error messages for users to fix failures.

**Comment by mgasner** [comment]
i think we need snapshots of real output from dbt to test against, and we need to use those snapshots as the mocks
