### ISSUE TITLE
Dagster/Dagstermill - Rendered Notebook Missing

### ISSUE THREAD

**Issue by prinapatel** [dagster-io/dagster#3743]
## Summary
I am trying to use some existing notebooks I have and turn them into Dagster solids as outlined in the [docs](https://docs.dagster.io/0.10.0/overview/packages/dagstermill). I have run the notebooks in Jupyter and they run, and they also execute fine in Dagster but rendered output is not at the location that the logs give me. 

I get a warning about the ```file_manager``` which I assume is the issue but I cannot find a resolution to this - also this is the very basic example that I've used from the docs (the only difference from the example given is the notebook I've used, I get the same behaviour with the iris-kmeans.ipynb notebook.)

The warning I get is:
```
Error when attempting to materialize executed notebook using file manager (falling back to local): SerializableErrorInfo(message='dagster.core.errors.DagsterUnknownResourceError: Unknown resource `file_manager`. Specify `file_manager` as a required resource on the compute / config function that accessed it.\n', stack=['  File "/Users/prinapatel/opt/anaconda3/envs/py37/lib/python3.7/site-packages/dagstermill/solids.py", line 229, in _t_fn\n    executed_notebook_file_handle = compute_context.resources.file_manager.write(\n', '  File "/Users/prinapatel/opt/anaconda3/envs/py37/lib/python3.7/site-packages/dagster/core/definitions/resource.py", line 264, in __getattr__\n    raise DagsterUnknownResourceError(attr)\n'], cls_name='DagsterUnknownResourceError', cause=None)
```
Any help on this issue would be appreciated!

Thanks,

Prina

## Reproduction
```
from dagster import pipeline,ModeDefinition,fs_io_manager,local_file_manager
import dagstermill as dm
from dagster.utils import script_relative_path

env_notebook=dm.define_dagstermill_solid('env_notebook',script_relative_path('notebooks/environment.ipynb'))

@pipeline(
    mode_defs=[
        ModeDefinition(
            name='local_test',
            resource_defs={'io_manager':fs_io_manager,'file_manager':local_file_manager}
        )
    ]
)
def env_pipeline():
    env_notebook()
```

## Dagit UI/UX Issue Screenshots
![Screenshot 2021-02-26 at 16 27 51](https://user-images.githubusercontent.com/6458085/109327707-8b9d7100-7850-11eb-8123-4ad43cdec918.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by nancydyc** [comment]
Hi @prinapatel , did you have `required_resource_keys={"file_manager"}` specified on the solid requires this resource?

**Comment by mgasner** [comment]
The dagstermill solid factory *should* be specifying that required resource key for you... can I ask which version of dagstermill you are running?

**Comment by prinapatel** [comment]
HI @nancydyc, @mgasner 

Thanks for your responses. Apologies, I should have included the versions in my posting: I am using dagster and dagstermill version 0.10.7.

As @nancydyc suggested I put the ```required_resource_keys={'file_manager'}``` to the definition of the notebook solid and this created the rendered notebook as expected in ```$DAGSTER_HOME```.

Thanks,

Prina
