### ISSUE TITLE
reddish outline for solid selection makes me feel like there's something wrong

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3746]
Small aesthetics thing: the reddish outline when you click on a solid in the pipeline overview makes me think there's a problem with that solid.

![image](https://user-images.githubusercontent.com/654855/109334579-c2a26100-7815-11eb-8d37-4ceaddeb0167.png)

## Ideas of Implementation

Purple?

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Colors seem a little better for this now.
