### ISSUE TITLE
Dagit incorrectly says "The sensor daemon is not running" if the sensor daemon yielded an error.

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3749]
Just because a tick yielded an error doesn't mean the daemon isn't running. There's a version of this check we can make that will only return True if the daemon is not running at all.

**Comment by alangenfeld** [comment]
i think this may have been resolved? cc @johannkm

**Comment by sryza** [comment]
@gibsondan do you know whether this is still an issue? Are there steps to reproduce?

**Comment by yuhan** [comment]
im gonna close this bc i can't repro it and it seems have been resolved. plz reopen if still valid
