### ISSUE TITLE
Flask server configuration improvements to better support multiple people hitting dagit at once

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3750]
Today in an unintentional Dagit load test, we managed to make dagit very sluggish without really trying. Alex has suggestions for how to improve this on the flask server side.

**Comment by alangenfeld** [comment]
https://github.com/dagster-io/dagster/issues/2655

https://github.com/dagster-io/dagster/issues/3417

**Comment by natekupp** [comment]
ahead of any code changes, a quick band-aid for now on k8s - we can increase the number of replicas from 1 to 3 and add mem/cpu to the dagit pod, and see if any of that helps

**Comment by mgasner** [comment]
are we also considering putting dagit behind a real webserver such as uwsgi

**Comment by alangenfeld** [comment]
collapse in to #2655
