### ISSUE TITLE
pipeline tags without preset/partition

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#3755]
It seems we do not show the pipeline level tags in the playground until you select preset / partition - even though they will show up on the run if you hit execute.

**Comment by bengotow** [comment]
Relevant docs: https://docs.dagster.io/concepts/solids-pipelines/pipelines#pipeline-tags

It looks like we should probably display these (and make them un-removable). We may need to check that there's a GraphQL field for retrieving them.
