### ISSUE TITLE
[Content Gap] Dynamic Orchestration

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3760]
## What content is missing
Explain "Dynamic Orchestration" with some code examples

## Type of the content
[Main Concept]: "What is X in Dagster" where X is a Dagster concept.
Can possibly be a pattern (or an example) for the Pipeline concept, see https://dagster.vercel.app/concepts/solids-pipelines/pipelines#patterns

## (Optional) Target Date
03/15 - would love to give it in for 0.11.0

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/11-docs/docs)
- Templates to follow: `/concepts/template` or [here](https://dagster.vercel.app/concepts/template)
- Examples for reference: https://dagster.vercel.app/concepts/solids-pipelines/pipelines#patterns

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by helloworld** [comment]
I'll take the first pass on this to migrate what we already have onto the docs site.

**Comment by schrockn** [comment]
make sure to coordinate with @alangenfeld still as he is going to do a section in the blog post about it

**Comment by yuhan** [comment]
https://docs.dagster.io/concepts/solids-pipelines/pipelines#dynamic-mapping--collect
