### ISSUE TITLE
[docs] - Example/guide for type-based IO manager

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3762]
## What content is missing
how to load inputs and outputs based on type

## Type of the content
[Best Practices Guide](https://dagster.vercel.app/guides): "How to do X in Dagster" where X is usually a use case and can be addressed by incorporating multiple Dagster concepts at a time.

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/11-docs/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
@sryza wonder if it'd make sense to convert https://dagster.phacility.com/D6400 to a how-to guide, as opposed to a framework-provided api?

**Comment by sryza** [comment]
@yuhan that was actually my original intention, but I discovered that the amount of code that the user would be required to write would be too enormous for me to recommend with a straight face.

**Comment by erinkcochran87** [comment]
@sryza @yuhan Is this still relevant?

**Comment by sryza** [comment]
I think we can get rid of this
