### ISSUE TITLE
[docs] - Dagster with GCS Guide

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3764]
## What content is missing
A hands-on guide to walk through uses of `dagster_gcp.GCS`, e.g. gcs_resource , gcs_pickle_io_manager, GCSComputeLogManager

## Type of the content
[Integration Guide](https://dagster.vercel.app/guides): "How to use X in Dagster" where X is a 3rd-party package/tool, e.g. dbt, Spark, etc

## (Optional) Anything in particular you want the docs to cover
1. Demonstrate how to set up modes to use with GCS resources (test, dev, staging, prod)
- A mocked version of X
- Write tests against test mode
2. Include an example of how to use gcs_pickle_io_manager as IO managers in the "Advanced Use Cases" section. 

## (Optional) Target Date
03/15 - would love to give it in for 0.11.0

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/11-docs/docs)
- Templates to follow: see `/guides/integrations/template` or [here](https://dagster.vercel.app/guides/integrations/template)
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
Closing - tracking in Notion.
