### ISSUE TITLE
[Content Gap] Deploying Dagster to Kubernetes

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3765]
## What content is missing
Migrate the content in https://docs.dagster.io/deploying/kubernetes to use the new deployment guide template.

## Type of the content
[Deployment Guide](https://dagster.vercel.app/deployment): "How to deploy Dagster to X", e.g. Docker, K8S, GCP, etc

## (Optional) Target Date
03/15 - would love to get in 0.11.0

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/11-docs/docs)
- Templates to follow: quip doc
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Resolved with 09578d3dd0a07beec669d905060cf7453870795f
