### ISSUE TITLE
[Content Gap] Re-visit Dagster Pandas integration guide

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3766]
## What content is missing

How-to guide to explain the uses of `dagster_pandas`
Existing content: https://docs.dagster.io/overview/packages/dagster_pandas

## Type of the content
[Integration Guide](https://dagster.vercel.app/guides): "How to use X in Dagster" where X is a 3rd-party package/tool, e.g. dbt, Spark, etc

## (Optional) Target Date
03/15 - would love to give it in for 0.11.0

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/11-docs/docs)
- Templates to follow: see `/guides/integrations/template` or [here](https://dagster.vercel.app/guides/integrations/template)
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
@yuhan Would you like to keep this open, or does the existing guide (https://docs.dagster.io/integrations/pandas) cover what you had in mind?

If it doesn't, could you add some info to the issue description that details what you'd like us to change/add/update?

**Comment by yuhan** [comment]
closing because this has been updated with op/job/graph and the content is in an ok state.
