### ISSUE TITLE
[docs] - Dagster with Slack Guide

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3768]
## What content is missing
A hands-on guide to walk through uses of the Slack resources, e.g. how to use slack resource, how to write a slack hooks

## Type of the content
[Integration Guide](https://dagster.vercel.app/guides): "How to use X in Dagster" where X is a 3rd-party package/tool, e.g. dbt, Spark, etc

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/11-docs/docs)
- Templates to follow: see `/guides/integrations/template` or [here](https://dagster.vercel.app/guides/integrations/template)
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
Closing - tracking this in Notion
