### ISSUE TITLE
Schedules broken on certain docker images due to outdated pendulum

### ISSUE THREAD

**Issue by syk0saje** [dagster-io/dagster#3770]
## Summary

Clicking "View configuration" from a schedule page in the web UI displays the following error:

```
dagster.core.errors.ScheduleExecutionError: Error occurred during the execution of run_config_fn for schedule extract_multi_schedule
  File "/root/.local/lib/python3.8/site-packages/dagster/grpc/impl.py", line 244, in get_external_schedule_execution
    run_config = schedule_def.get_run_config(schedule_context)
...
The above exception was caused by the following exception:
RuntimeError: Can not find any timezone configuration
...
  File "/root/.local/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 169, in get_tz_name_for_unix
    raise RuntimeError('Can not find any timezone configuration')
```

This is because calls to `pendulum.now()` are causing errors similar to [this issue](https://github.com/miracle2k/k8s-snapshots/issues/83).

The root of the problem is that `pendulum==1.4.4` fails to get the local timezone for certain custom images (in our case, based on [ubuntu:focal-20210119](https://hub.docker.com/layers/ubuntu/library/ubuntu/focal-20210119/images/sha256-62ff67e3aabbe2d7ea4580207da06644eaba606ecc9cb347e184b7aeb15bc374?context=explore). The same problem does not exist in `pendulum==2.1.2`.

## Reproduction

- Run the dagster UI on `ubuntu:focal-20210119`
- Click "View configuration" from any schedule page

For a demonstration of the underlying issue with `pendulum==1.4.4`:

Run `bash` from inside the specific image:
```
docker run -it --rm ubuntu:focal-20210119 bash
```

Once inside, run the following:

```
apt-get -y update && apt-get -y upgrade
apt-get install -y python3-pip
ln -s /usr/bin/python3 /usr/bin/python
ln -s /usr/bin/pip3 /usr/bin/pip

# By now you should have python 3.8.5
pip install pendulum==1.4.4
```

Then, still inside the container, run the following inside `python`:

```
import pendulum
pendulum.now()
```

This will cause the error while using `pendulum==2.1.2` does not.

## Additional Info about Your Environment

We also witnessed calls to `dagster api launch_scheduled_execution` fail silently without spawning execution pods. This problem disappeared once we introduced a `TZ` environment variable to our container, preventing calls to `pendulum.now()` from failing.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Thanks for the report! As luck would have it we just unpinned pendulum recently, so installing with pendulum 2 should work to resolve this if you upgrade to the latest version of dagster. 

I'm hesitant to pin pendulum to a later version, because we'd like dagster to still be compatible with older versions of Airflow that are pinned to 1.4.4. 

Other than recommending that users install the latest version of pendulum when using dagster in alpine, is there anything else we need to do to resolve this?

**Comment by syk0saje** [comment]
Thanks for the response @gibsondan ! Could you point me to the earliest release where `pendulum` is unpinned? Will try it out with the latest (`0.10.7`) but if I can get an earlier one, that might be better.

Also I'm not sure about the current state of `launch_scheduled_execution` but that was kind of blocking us when it just ended without any logs indicating any sort of failure. Hopefully it can be more verbose or at least have the option for verbosity to enable any future troubleshooting :)

**Comment by gibsondan** [comment]
It was fairly recent - maybe 0.10.5? So yeah, an upgrade may be required.

Re: launch_scheduled_execution, we have a much clearer debugging workflow for schedules using our new native scheduler, described here: https://docs.dagster.io/overview/schedules-sensors/schedules#running-your-schedule . There are also some troubleshooting steps here: https://docs.dagster.io/troubleshooting/schedules . I'm optimistic that you'll have a much better debugging experience if you upgrade and try out the new scheduler.

I'll close this out for now, but absolutely reach our here or on Slack if any more questions come up!
