### ISSUE TITLE
Environment var substitution does not work in config files

### ISSUE THREAD

**Issue by andgineer** [dagster-io/dagster#3775]
## Summary
I use `{"env": "ENV_VAR"}` as value for string in resources and get error
`Invalid scalar at path root:resources:spark:config:spark_conf:spark:master. Value "{'env': 'SPARK_MASTER_URL'}" of type "<class 'dict'>" is not valid for expected type "String".`

## Reproduction
resources.yml
```
    resources:
      spark:
        config:
          spark_conf:
            spark:
              master:
                env: SPARK_MASTER_URL
```

pipeline.py
```
    from dagster import ModeDefinition, SolidExecutionContext, pipeline, solid
    from dagster_pyspark import pyspark_resource
    
    @solid(
        required_resource_keys={"spark"},
    )
    def health_check(context: SolidExecutionContext):
        pass
    
    @pipeline(
        mode_defs=[
            ModeDefinition(
                resource_defs={
                    "spark": pyspark_resource,
                },
            )
        ],
    )
    def test_pipeline():
        health_check()
```

CLI
`dagster pipeline execute -f pipeline.py -c resources.yml`

## Dagit UI/UX Issue Screenshots
N/A

## Additional Info about Your Environment
Anaconda inside Docker container build on `debian:stretch`

    - dagit==0.10.4
    - dagster==0.10.4
    - dagster-spark==0.10.4
    - dagster-pyspark==0.10.4
    
---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by andgineer** [comment]
The docs:
https://docs.dagster.io/overview/instances/dagster-instance
"Dagster supports retrieving instance YAML values from environment variables, using env: instead of a string literal."

**Comment by alangenfeld** [comment]
The issue is that we have two different config types `String` which only accepts the scalar and `StringSource` which takes the scalar or the environment variable to load. 

I put up https://dagster.phacility.com/D6786 to move the generated spark config over to the Source types.

**Comment by alangenfeld** [comment]
expected it to go out in the release today
