### ISSUE TITLE
test_pipeline_run_observable_subscribe_with_polling flakey

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#3776]
https://buildkite.com/dagster/dagster/builds/16577#64c282c8-0b34-45a7-a419-319be5165587

**Comment by sidkmenon** [comment]
Should be resolved with https://dagster.phacility.com/D6783

**Comment by sidkmenon** [comment]
Solved w/ https://github.com/dagster-io/dagster/commit/768f2fe9c01c1c38fe4fda7bd2b261ee0a151656
