### ISSUE TITLE
Dagit - Using --path-prefix serves CSS on the incorrect directory

### ISSUE THREAD

**Issue by joshuataylor** [dagster-io/dagster#3777]
## Summary
When using `--path-prefix /foo`, this works great except for the fonts seemed to be served off the root directory:
```
GET https://example.com/static/media/SourceCodePro-Bold.9efc4535.woff2 net::ERR_ABORTED 503
main.af0c7fcc.chunk.css:1
GET https://example.com/static/media/SourceCodePro-Regular.6b0680a0.woff2 net::ERR_ABORTED 503
````

In the CSS, this looks like:`,url(/static/media/OpenSans-SemiBold.d76f9a5e.woff2) format("woff2")}`, so it's using that it seems.

## Reproduction
1. Run with --path-prefix
2. Open dev console when on the path prefix in your browser
3. Observe results

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bollwyvl** [comment]
Yeah, fonts are notorious. I've ickily worked around this before with `base64-loader`... if it's only one or two fonts (with one or two weights) it's not that bad...

**Comment by hellendag** [comment]
Thanks for flagging this!

**Comment by bollwyvl** [comment]
Sorry, took a sec, but with the 0.11.1 release up, the interactive binder example looks quite good now, and there are no dagster-related errors. Good show!

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/bollwyvl/0fe7a6f89251992ab1a542ac2b4051c4/master?urlpath=lab)

**Comment by schrockn** [comment]
wow that's super cool

**Comment by bollwyvl** [comment]
I was tempted to color-shift the dagster squid (does it have a name) to green-with-red-eyes-and-more-of-them to be dagon, but figured y'all wouldn't like that so much... but yeah, i do still intend to rip apart dagit and get all the pieces to play nice-nice with lab bits. And, of course, if you end up going in-loop with FastAPI or something, the sky's the limit w/r/t a dagster kernel, or at least an in-process dagit, such that more pieces can be integrated. If you go to a node-based process that isn't a single-file, `node dagit.js` or `deno dagit.ts` a la `yarn-legacy.js`, well... it's gonna get harder to integrate. We've been desperately trying to get nodejs/npmjs.com _out_ of the jupyter _runtime_ environment, but some things are hard to replace...
