### ISSUE TITLE
Clarify "Run Steps" in partitions UI

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3782]
## Use Case

I have found myself struggling to understand the meaning of the "Run Steps" box on the partitions page.  Is the idea that users can use it to filter the set of steps that show up in the graphs?  If so, why does it show only "Total Pipeline" in the screenshot below?  Also, if that's the purpose, then it could make sense to rename it to something like "Select Steps to Plot"?

![image](https://user-images.githubusercontent.com/654855/110045113-0eb24180-7cff-11eb-85af-be565687e3ac.png)

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey folks, this will be addressed by https://dagster.phacility.com/D7379
