### ISSUE TITLE
Make default scroll position in "Launch backfill" modal be right-most partition

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3787]
## Use Case

If someone is triggering a backfill over a small subset of partitions, it's likely to be partitions closer to the right, i.e. the more recent partitions.  That's because engineers monitor recent partitions for failures and fix them as they come up.

Also, this would make it consistent with the partitions page and asset page, where we also show partitions left-to-right and start on the right.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by bengotow** [comment]
This will be resolved by https://dagster.phacility.com/D7469
