### ISSUE TITLE
Scrub job language and class names from Schedules/Sensors

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3789]
## Summary

We decided this verbiage was confusing and eliminated it, but there is still some residue.  For example sensor is defined as `Define a sensor that initiates a set of job runs` in the SensorDefinition docblock and it inherits from JobDefinition. We should eliminate all references to Job like this to prevent both internal and external confusion.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Some of the error messages in definitions/decorators/repository.py also refer to jobs.

**Comment by prha** [comment]
This is scrubbed from the user-facing API.

We still refer to "job" as the union of schedules/sensors with regards to storage in the db and access to that stored state in graphql.  We should discuss if we want to scrub that as well.
