### ISSUE TITLE
[Content Gap] Deployment Guide: Using MySQL for Storage

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3793]
## What content is missing
Document what components can be configured using MySQL and how

## Type of the content
Deployment Guide: Using MySQL for Storage

## (Optional) Target Date
by 0.11.0

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by helloworld** [comment]
I think this is a good opportunity to restructure the instance page overall. We should break down each section into its own heading and properly describe the available options. 

I think the structure should look like this:

```
## Instance Configuration YAML (dagster.yaml)

[[Description of instance configuration]]

### Run Storage

[[Description of run storage]]

### SQLite [Default]

<snippet>

### Conslidated SQLite

<snippet>

### MySQL

<snippet>

### Postgres

<snippet>

## Event Log Storage

Repeat same structure
```

**Comment by sidkmenon** [comment]
I think this should be closed w/ the new Instance page: https://docs.dagster.io/deployment/dagster-instance
