### ISSUE TITLE
Make resources available to sensors

### ISSUE THREAD

**Issue by davidz-1** [dagster-io/dagster#3794]
## Use Case
If a certain row appears in our database, a pipeline run should be executed. This needs to be checked every 5 minutes. 
Checking the table requires a authenticated database client, which is already existing and used by the same pipeline, it handles authentication during initialization.

## Ideas of Implementation
Just take the resource which is given to the pipeline (depending on the mode) and make it available with the `required_resource_keys` like it's done with the solids.

## Additional
Thank you and keep up the good work guys, I really like to work with dagster.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
The same out of execution resource init machinery that powers memoization and the context builders could probably be used here as well.

**Comment by VladX09** [comment]
A really good request. Most of sensors watch external resources (APIs, S3 buckets, DBs, queues) to trigger pipeline. It would be nice to configure external resources for solids and sensors in the same way. It will also make unit testing and mocking more consistent

**Comment by bryanchavezkh** [comment]
This would be very useful especially for operations that only need to run on job success.  My use case invovles a resource where I collect metadata from a job across multiple ops including one that has a  DynamicOutput.  When the job finishes, I publish the collected metadata at once to a storage layer which I would like to implement within a @run_status_sensor.

**Comment by dpeng817** [comment]
https://github.com/dagster-io/dagster/pull/6306 adds a top-level API called `build_resources`, which should provide a solution to this issue. `build_resources` allows you to initialize resources outside of the context of execution, meaning you can re-use your resources inside a sensor. 
```python

@sensor
def my_sensor():
    with build_resources({"foo": foo_resource, "bar": bar_resource}) as resources:
        foo = resources.foo
        ...
```

The only downside here is that testing with mock resources gets tricky. But you can use a factory pattern to get around that:
```python

def build_sensor_with_resources(resources):
    @sensor
    def the_sensor():
        with build_resources(resources) as resources:
             ...
    return the_sensor

@resource
def db():
    return connection()
    
mock_db = mock.MagicMock(spec=connection)

prod_sensor = build_sensor_with_resources({"db": db})
sensor_for_test = build_sensor_with_resources({"db": mock_db})
```

Note how you can also directly use values with `build_resources`, instead of just resource definitions. This is to streamline test use cases.

**Comment by dpeng817** [comment]
Going to keep the issue open because this solution might not fully encompass what people are expecting from a solution - given that resources in this scenario work differently than our other decorated functions.

**Comment by johannkm** [comment]
Another request in slack https://dagster.slack.com/archives/C01U954MEER/p1650312986241359

**Comment by sryza** [comment]
@benpankow - should we close this issue given the new functionality here?

Small things I noticed:
- The docstring for SensorEvaluationContext doesn't include `resources`, even though there's a property
- The property isn't marked public

**Comment by benpankow** [comment]
> Small things I noticed:
  The docstring for SensorEvaluationContext doesn't include resources, even though there's a property
  The property isn't marked public

good catch - https://github.com/dagster-io/dagster/pull/13903

marking closed!
