### ISSUE TITLE
in pipeline visualization, connection unnecessarily overlaps solid

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3798]
## Summary

The dependency between the second and fourth solids from the top goes behind the third solid.

![image](https://user-images.githubusercontent.com/654855/110403665-5d7b1680-8032-11eb-90be-b8622ccd4922.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey @sryza!  I upgraded our storybook setup to try to reproduce this but I can't seem to recreate a pipeline that yields this rendering. It could potentially have something to do with the solid names being really long, will try that next.

Is this a pipeline in any of our examples?

<img width="334" alt="image" src="https://user-images.githubusercontent.com/1037212/116293729-cd696b80-a75c-11eb-9287-116cfcc8208e.png">

**Comment by bengotow** [comment]
Hey folks! I wasn't able to track this down back in April but did add a storybook case for this. If we can come up with another example of this I'll re-open.
