### ISSUE TITLE
consider giving solid names more real estate in pipeline visualization

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3799]
## Use Case

There's so much empty space, but the solid names are still getting cut off

![image](https://user-images.githubusercontent.com/654855/110403888-bea2ea00-8032-11eb-8818-42b6a44adf21.png)

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by bengotow** [comment]
I think this has been addressed in the recent redesign but we only gave space for ~30% more characters. We could make these even wider maybe? 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/1037212/156256484-d4e650df-c07d-49a1-9030-c3dd0a12c1c8.png">
