### ISSUE TITLE
Refresh dagit from command line

### ISSUE THREAD

**Issue by NakulK48** [dagster-io/dagster#3803]
## Use Case

It would be useful to be able to reload the repository location in dagit from the command line, so it could happen automatically as part of a release process.

If this already exists, I can't find any documentation for it. The closest thing is restarting the server, but I imagine this could disrupt currently-running jobs.

## Ideas of Implementation

This could just be an HTTP request or something.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi - We don't have a CLI command for this, but it's possible today with a graphql request (you just need to know the location name, which you can see in dagit or customize in your workspace.yaml). Here is some sample code:


```
RELOAD_REPOSITORY_LOCATION_MUTATION = """
mutation ($repositoryLocationName: String!) {
   reloadRepositoryLocation(repositoryLocationName: $repositoryLocationName) {
      __typename
      ... on RepositoryLocation {
        name
        repositories {
            name
        }
        isReloadSupported
      }
      ... on RepositoryLocationLoadFailure {
          name
          error {
              message
          }
      }
   }
}
"""

dagit_host = "your_dagit_host_here"

variables = {
    "repositoryLocationName": "your_location_name_here",
}
reload_res = requests.post(
    "http://{dagit_host}:3000/graphql?query={query_string}&variables={variables}".format(
        dagit_host=dagit_host,
        query_string=RELOAD_REPOSITORY_LOCATION_MUTATION,
        variables=json.dumps(variables),
    )
).json()

did_succeed = reload_res["data"]["reloadRepositoryLocation"]["__typename"] == "RepositoryLocation"

```

Bit cumbersome but would that work for your use case?

**Comment by NakulK48** [comment]
I can give it a try. Does it need to explicitly handle the different return types or can it just check the `__typename` and otherwise ignore them?

**Comment by gibsondan** [comment]
The only reason you'd need to check the response at all is if you care about whether or not it succeeded (and if it failed, the error branch includes more information about why if you want - e.g. a stack trace)

**Comment by NakulK48** [comment]
Should `repositoryLocationName` be the value of the `Repository` column in `/workspace`? I'm trying to enter that and getting:

```json
"__typename": "RepositoryLocationNotFound",
      "message": "Location [the location] does not exist."
```

**Comment by NakulK48** [comment]
Should repositoryLocationName be the value of the Repository column in /workspace? I'm trying to enter that and getting:

```
"__typename": "RepositoryLocationNotFound",
      "message": "Location [the location] does not exist."
```

The location is of the format `repository_function_name@import_location_of_module`
