### ISSUE TITLE
[Content Gap] Deploying Dagster to ECS

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3805]
## What content is missing
how to deploy Dagster to ECS

## Type of the content
 
Deployment Guide: ECS section on the [AWS guide](https://dagster.vercel.app/deployment/guides/aws#hosting-dagit-or-dagster-daemon-on-ec2-or-ecs) 

## (Optional) Target Date
0.11.0

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: [quip](https://elementl.quip.com/cTbTAKapfmV8/Template-Deployment-Guide)
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
We now have a section on deploying to ECS in https://docs.dagster.io/deployment/guides/aws#deploying-in-ecs
