### ISSUE TITLE
Jumping button layout in Partition view

### ISSUE THREAD

**Issue by hellendag** [dagster-io/dagster#3806]
## Summary

Buttons jumping around during the loading state.

## Reproduction

View partitions page in Dagit.

## Dagit UI/UX Issue Screenshots

![image](https://user-images.githubusercontent.com/2823852/110539374-ccb44180-80ea-11eb-9a04-ba00a8afb649.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
This should be resolved by https://dagster.phacility.com/D7378!
