### ISSUE TITLE
Respect indent level in docs sidebar text wrapping

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3807]
## Use Case

![image](https://user-images.githubusercontent.com/654855/110541615-d9319d80-80dc-11eb-9bf2-9bc14e918498.png)

I think the hierarchy would be clearer if the "manager" in "Providing per-output config to an IO manager" were not level with "Examples".

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
maybe we should make the font size there smaller so every heading will be one line

**Comment by helloworld** [comment]
I can fix this
