### ISSUE TITLE
Permalink to compute logs for a particular step

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3809]
Right now this appears as a pop-up but there's no permalink so it's hard to share.

**Comment by sryza** [comment]
@mgasner when you say "this appears as a popup", what exactly do you mean by "this"?

**Comment by bengotow** [comment]
Hey @prha  I think this refers to the stdout / stderr views - think we could encode something in the page URL so that the user could link directly to those screens?

**Comment by prha** [comment]
Yeah, this is already done, landed on master today
