### ISSUE TITLE
[Content Gap] How to create versioned workflows

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3810]
## What content is missing

User asked: If I make a bug fix in commit X and then I check the recent runs in dagit, how do I know whether the runs contain the bug fix?

I recommended tagging docker user code images with the commit hash, but I'm not sure if we have top-level support for exposing the image tag within dagit

## Type of the content
 

Best Practices Guide

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
I think this is currently more of a feature gap than a docs gap. Going to close this.
