### ISSUE TITLE
`dagster-dbt` doesn't yield materializations anymore

### ISSUE THREAD

**Issue by flvndh** [dagster-io/dagster#3815]
Hey Team 👋

The loop right here doesn't yield anymore:
https://github.com/dagster-io/dagster/blob/b6a3e6b34de4275c193419a9617214755e121a79/python_modules/libraries/dagster-dbt/dagster_dbt/cli/solids.py#L197-L201

The DBT team seems to have changed the schema of `run_results.json` from [this](https://schemas.getdbt.com/dbt/run-results/v0.json) in 0.18.1 to [this](https://schemas.getdbt.com/dbt/run-results/v1.json) in 0.19.0.

Thus, this line is always empty:
https://github.com/dagster-io/dagster/blob/b6a3e6b34de4275c193419a9617214755e121a79/python_modules/libraries/dagster-dbt/dagster_dbt/types.py#L102

**Comment by sryza** [comment]
Thanks for reporting this @flvndh and apologies for the delay on responding.  This seems like a serious issue.  It's also a little bit difficult to fix.  We're aiming to address by our 0.12.0 release in a couple months at the latest - hopefully much sooner.
