### ISSUE TITLE
add test for longitudinal pipeline

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3816]
A test that verifies that the toy repo loads without errors would go a long way

**Comment by alangenfeld** [comment]
i think `python_modules/dagster-test/dagster_test_tests/test_toys.py` covers this? unless you mean something different

**Comment by sryza** [comment]
I think the issue that triggered this was a problem in the longitudinal pipeline, which isn't covered in `test_toys` - I'm going to have this issue focus on that.
