### ISSUE TITLE
execution APIs should warn (or throw) if DAGSTER_HOME is set and an instance is not provided

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#3817]
## Summary

If `instance` is not provided, the execution apis (e.g. `execute_pipeline`) construct an ephemeral instance.  This can be unexpected when trying to execute runs against your production instance, and the resulting run is irrecoverable.

We should at minimum warn when there is a `DAGSTER_HOME` environment variable set so that folks are not confused where their run went.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
looking at addressing this by splitting the the python execution apis in to one focused on testing and one focused on legit execution
