### ISSUE TITLE
Helm chart for 0.10.9 unavailable

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#3823]
## Summary

If i try to use the version 0.10.9 of the helm chart I get the following error
```
Error: failed to download "dagster/dagster" at version "0.10.9" (hint: running `helm repo update` may help)
```

`helm repo update` doesn't solve the issue (0.10.8 works but looks like it's a cursed release)

## Reproduction

```
helm repo update && helm template dagster dagster/dagster --values my-values.yaml --version 0.10.9
```

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Sorry about that @amarrella! Uploaded just now.

**Comment by amarrella** [comment]
No problem, thanks a lot 😊
