### ISSUE TITLE
[Content Gap] Document resource scope (spin-up/tear-down behavior)

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3826]
## What content is missing
Right now a user would have to guess about when resources actually get spun up or torn down -- the behavior is confusing.

## Type of the content
Probably belongs in the resource concept doc

#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
Dup of https://github.com/dagster-io/dagster/issues/3825
