### ISSUE TITLE
Dagster Helm Chart initContainers: check-db-ready never progresses

### ISSUE THREAD

**Issue by luander** [dagster-io/dagster#3827]
## Summary
When deploying Dagster using the Helm Chart all deployments get stuck in "PodInitializing" state.
The problem is in the initContainers section called: `check-db-ready` and more specifically in the code section below:
```yaml
          command: ['sh', '-c',
            'until pg_isready -h {{ include "dagster.postgresql.host" $ }} -p {{ $.Values.postgresql.service.port }}; do echo waiting for database; sleep 2; done;',
            ]
          ...
```
The `pg_isready` command seems to require the `-U <user>` parameter to work. A possible fix is to include the missing parameter:
```yaml
          command: ['sh', '-c',
            'until pg_isready -h {{ include "dagster.postgresql.host" $ }} -p {{ $.Values.postgresql.service.port }} -U {{ $.Values.postgresql.postgresqlUsername }}; do echo waiting for database; sleep 2; done;',
            ]
```

## Reproduction
- Deploy the Helm Chart 
- Run `kubectl logs dagster-daemon-<pod id> -c check-db-ready -n <dagster namespace>`
- Expected result: `dagster-postgresql:5432 - accepting connections`
- Observed result: `dagster-postgresql:5432 - no attempt`

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Hey @luander! Thanks for the report and the easy solution, should be resolved in https://dagster.phacility.com/D6896. Had to run some integration tests just to make sure it was all good, so closing #3828.

**Comment by luander** [comment]
No problem @rexledesma. The solution you proposed is the better one as it relieves a chart update if pg_isready changes in the future.
