### ISSUE TITLE
Expose Image Tag In Dagit for Currently Running User Code Deployments

### ISSUE THREAD

**Issue by peter-stratton** [dagster-io/dagster#3830]
## Use Case
Our team is using multiple User Code Deployments and thought it would be super handy to have the currently running image tag exposed in Dagit.

## Ideas of Implementation
Something along the lines of this:

![repo](https://user-images.githubusercontent.com/2140511/110842698-73c4e480-8275-11eb-8ca9-6e6787e46915.jpg)

## Additional Info
I haven't really thought through how this might work for non-containerized deployments, but could see either the version from an `__init__.py` `__version__` or something from `setup.py` being useful (if available).

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
This would be great in the status view as well next to each repository location

**Comment by gibsondan** [comment]
This just landed and will be going out in the 0.11.0 release tomorrow! (It shows the whole image name, not just the tag)
