### ISSUE TITLE
[Content Gap] Deploying to Airflow guide is untested

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#3831]
## What content is missing

https://docs.dagster.io/deployment/custom-infra/airflow is outdated and inaccurate

## Type of the content
Deployment - Executing on Airflow

## Anything in particular you want the docs to cover

1. code snippets aren't tested
2. this example may not need `dagster-graphql` - need to investigate
3. env should use io managers instead of intermediate_storage

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
We now do have tests for the airflow guide, but they are currently disabled because of a dependency issue. That dependency issue is represented [here](https://github.com/dagster-io/dagster/issues/5534).
