### ISSUE TITLE
Guide readers better through tutorial navigation

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3838]
## Use Case

If someone wants to jump in to the tutorial, it's a little unclear how they do so.  They end up here:

![image](https://user-images.githubusercontent.com/654855/110880375-628ad080-8293-11eb-952a-aba245e1fac4.png)

They could click on the "Setup for the Tutorial" link, though it's not particularly emphasized over the other links. If they scroll all the way down, they'll see a tiny link on the bottom right:

![image](https://user-images.githubusercontent.com/654855/110880427-76cecd80-8293-11eb-99fb-253466d4cb0b.png)

When they finish a section and want to move to the next one, they again need to find the tiny link on the bottom right.

## Ideas of Implementation

If it were entirely up to me, I would remove the tutorial overview page entirely and have links to the tutorial send readers to the "Setup for the Tutorial" page.  Others have made reasonable arguments against this, so I won't push on it.  If we're going to keep it, I think it would be helpful to have a prominent click target at the top that takes someone to the first page of the tutorial.

For the rest of the tutorial pages, it would be helpful to have big prominent click targets at the bottom for navigating to the next section.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
pushed https://dagster.phacility.com/D7115 just now which moved the bottom prev/next underneath the main text

@sryza is this good enough or do we also want to update the content to better navigate?

**Comment by sryza** [comment]
Apologies for the delay here @yuhan. I think this is a big improvement and we can close this issue.
