### ISSUE TITLE
link to filtered step logs instead of run logs from asset page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3872]
## Use Case

When someone wants to find out how an asset was materialized, that usually means understanding the step that materialized it.  The asset catalog page should link to the particular step, not just the run, which might have a ton of steps.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
@bengotow says this merged yesterday. :)
