### ISSUE TITLE
visual representation of the asset graph, centered on a single asset

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3873]
## Use Case

Maybe something like this:
![image](https://user-images.githubusercontent.com/654855/111337767-966b4a80-8633-11eb-8ce1-10df4d6d746b.png)

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Marking as "Needs details" because we don't exactly have a "larger project coming soon" tag.

**Comment by bengotow** [comment]
I think this has largely been addressed by the 0.14.0 release with view upstream / view downstream graphs
