### ISSUE TITLE
Make executor configurations able to overwrite the configured image in user deployments

### ISSUE THREAD

**Issue by szalai1** [dagster-io/dagster#3882]
## Use Case
Different pipelines in the same user deployments should be able to run in different containers. 

Example: 
* Data science pipelines sometimes require GPU-enabled resources and to run those we need containers with the required drivers.  
This used to possible by setting the image on the executor config during run time. If we enable user deployments, this is not possible anymore as it returns with the following error:
```
You have specified a job_image
 {job_image_from_executor_config} in your executor configuration, but also {job_image} in your user-code deployment. 
 You cannot specify a job_image
```

## Ideas of Implementation
Executor specified in code overrides the user deployments one and the run jobs and solids runs using the one coming from code.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Resolved with fac4b234c243.
