### ISSUE TITLE
[Content Gap] Document how to call GraphQL API from Python

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3887]
## What content is missing

We have decent documentation for the most important GraphQL queries and mutations, but we should document best practices for how to make these queries in python. 

## Type of the content
 

It belongs on the https://docs.dagster.io/concepts/dagit/graphql page. 

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Should we consider this done now that we have a documented Python GraphQL API?

**Comment by yuhan** [comment]
https://dagster.phacility.com/D7504
