### ISSUE TITLE
[Content Gap] Add documentation for "Airflow Inject"

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3891]
## What content is missing

This is actually our most well-supported codepath in the airflow and not mentioned at all in airflow.mdx. We should also be clear that the "ingest" is pretty experimental

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
cc: @catherinewu do you know where this content lives right now? I assume it exists

**Comment by catherinewu** [comment]
I dont think we have docs for inject. closest i could find are the tests here: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_factory

**Comment by yuhan** [comment]
the closest content is https://docs.dagster.io/deployment/guides/airflow - we could make changes on top of that guide, e.g. update the content, link inject and ingest, have better narratives.
