### ISSUE TITLE
(ver 0.11.0) base_dir config setting in dagster.yaml for local_artifact_storage not working

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#3898]
Hello!  On Windows 10 machine and Python version 3.8.  I am running the dagstermill example and trying to have the output notebook be saved at a certain location.  Here's my dagster.yaml config for the local_artifact_storage:
```
local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: "D:/outputs"
```

When running my pipeline, it defaults to where I executed the dagit command and not the location as specified above.

But I can configure the `base_dir` in my @pipeline decorator like below and it works fine:
```
@pipeline(
    mode_defs=[
        ModeDefinition(
            resource_defs={
                "io_manager": fs_io_manager,
                "file_manager": local_file_manager.configured(
                    {"base_dir": "D:\outputs"}
                )
            },
        )
    ]
)
def my_pipeline():
    my_solid()
```

So it appears the `base_dir` config setting in my dagster.yaml file isn't being recognized or being taken into account.

I was having the same problem with 0.10.9 so I've upgraded to version 0.11.0 as I thought it would address this issue per the release notes:
![image](https://user-images.githubusercontent.com/3989299/111786309-0972fc00-8894-11eb-888d-6116ecca6e4f.png)

With the `base_dir` config set in the dagster.yaml file, I then altered my pipeline decorator above where I removed the `base_dir` config option:
```
@pipeline(
    mode_defs=[
        ModeDefinition(
            resource_defs={
                "io_manager": fs_io_manager,
                "file_manager": local_file_manager
            },
        )
    ]
)
def my_pipeline():
    my_solid()
```

But the notebook output did not get saved to the correct location, but was instead saved where the dagit command was issued.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by pybokeh** [comment]
Just wanted to report that using an environment variable to set the `base_dir` in the dagster.yaml file did not work also:

```
local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir:
      env: DAGSTER_LOCAL_ARTIFACT_STORAGE_DIR
```

So far, on my Windows 10 machine, using the `local_file_manager.configured()` method to set the desired `base_dir` location in the @pipeline decorator appears to be the only way that works.

Furthermore, not sure if this is expected, but if I specify a `run_coordinator` in my `dagster.yaml` file, then the `base_dir` seems to default to where I launch the `dagster-daemon run` command.  If I don't have `run_coordinator` specified in the `dagster.yaml` file, then the base_dir defaults to where the `dagit` command was executed from.  FWIW, thought that was interesting and unexpected.

This is with dagster version 0.11.10 now.

**Comment by alangenfeld** [comment]
> So far, on my Windows 10 machine, using the local_file_manager.configured() method to set the desired base_dir location in the @pipeline decorator appears to be the only way that works.

Yes this is expected given the code as it stands. The `local file manager` has not been updated in the same way the `fs io manager` was to use the instance by default. The file manager uses the current working directory by default https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/storage/file_manager.py#L161-L162
leading to the behavior observed. 

This behavior is pretty confusing so I believe we should likely change it.

**Comment by pybokeh** [comment]
Hi @yuhan  Thanks for the fix!  Now, I have a question.  Is there a way to pass in a custom name for the output notebook?

**Comment by yuhan** [comment]
@pybokeh Not yet. I'm working on an improvement to the output notebook: https://github.com/dagster-io/dagster/pull/4490 -  once it gets merged, it will allow so.
