### ISSUE TITLE
Docs search does not yield definitions/api matches even on exact matches

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3899]
## Summary

For example searching for "solid"

<img width="793" alt="Screen Shot 2021-03-19 at 8 29 21 AM" src="https://user-images.githubusercontent.com/28738937/111795987-53a4af00-888d-11eb-9586-83104c0ce6c4.png">

I would have expected to be able to go to the `@solid` definition

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by kinghuang** [comment]
Lol, it appears we were on the same brainwave! I just wrote a similar issue in #3900.

**Comment by yuhan** [comment]
@helloworld improved the ranking in https://dagster.phacility.com/D7072 and updated the search index. This should be fixed now:
![image](https://user-images.githubusercontent.com/4531914/111833407-5c0de180-88af-11eb-9024-b57a919d2f06.png)
