### ISSUE TITLE
[docs] - Persist recent search term + modal when new tab is opened

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3901]
## Use Case

The quick search on the Dagster Docs site doesn't preserve the last entered search term. Say I do a search, and select the first result. If it doesn't match what I'm looking for, I have to do the search over again to try the second result, and so forth. This makes it very tedious to check each search result, as I have to repeat the same search over and over again.

## Ideas of Implementation

The quick search should remember my last entered search term for the current browser session. If I do a search, pick one of the results, then bring the search modal back up again, it should show me the last search term and set of results so that I can quickly choose another result, or clear the term and make a new search.

Additionally, the search modal should not be dismissed if I open a search result in a new window/tab. For example, in Safari, if I ⌘-click a search result, it opens in a new tab but the search results are also dismissed. This makes it impossible to open multiple search results, or be able to quickly return to the list of search results.

## Additional Info

None.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
Hey @kinghuang - I'm going through some old documentation issues and wanted to know if this could be closed. The docs search now displays recently-clicked results when the modal is opened.

As for your other suggestions, we're working on making additional improvements to search functionality and will keep those in mind!
