### ISSUE TITLE
[Documentation Feedback] Problem on /tutorial/advanced-tutorial/pipelines page

### ISSUE THREAD

**Issue by michaellynton** [dagster-io/dagster#3909]
The line that mentions executing modes.py from the command line, does not work:
`dagster pipeline execute -f modes.py -e resources.yaml -d unittest`

I received a message that said "no such option: -e"

Instead, when using version 0.11.0, I found that this worked instead: 
`dagster pipeline execute -f modes.py -c resources.yaml --mode unittest`

`-e` and `-d` switches did not work. I was able to run this instead with `-c` or-`-config` and `--mode`, respectively.

**Comment by helloworld** [comment]
Hi! Thank you for catching this! Would you be interested in sending a pull request for this? You can click the "Edit on GitHub" button on the same documentation page. 

If not, I can fix this :)

**Comment by michaellynton** [comment]
I don't mind at all. I was actually looking for that, because I thought I remembered y'all mentioning that on a recent community meeting talking about the new docs site. I'll have another look.

**Comment by michaellynton** [comment]
🤦🏻‍♂️ My bad .. I had the page set to half of my screen and the "Edit" button was hidden. I'll get a pull going. Thanks for the direction.
