### ISSUE TITLE
[docs] - Put CLI commands in intro tutorial under test 

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#3911]
## What content is missing

The CLI commands in the tutorial need to be under test. Here's an example of a command that's been broken since 0.9.0 when we removed the `-d` argument: https://github.com/dagster-io/dagster/pull/3910

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
Closing - no longer relevant
