### ISSUE TITLE
Seeing negative numbers for "skip" count in backfill page

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3915]
## Summary

Not sure what is going on, but seeing negative numbers for "skip" on the backfill page on the demo site.

<img width="1526" alt="Screen Shot 2021-03-22 at 5 34 14 AM" src="https://user-images.githubusercontent.com/28738937/111983932-56431680-8ad0-11eb-98e6-55b8b99d1b04.png">

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by prha** [comment]
Negative numbers happen when manual runs (via re-execution) are added with the same backfill tag.

Need to follow-up with a more accurate (but expensive) progress query...
