### ISSUE TITLE
[Documentation Feedback] Add pipeline structures on /concepts/solids-pipelines/pipelines page

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3923]
The original user request was for the pipeline structure below. Would be nice to include that to expand beyond the simple structures

<img width="256" alt="Screen Shot 2021-03-22 at 11 52 07 AM" src="https://user-images.githubusercontent.com/6024687/112042690-092d6780-8b05-11eb-99ee-2cf413438169.png">

code: https://dagster.phacility.com/P150

**Comment by yuhan** [comment]
@catherinewu should the example explain multiprocessing as well?
