### ISSUE TITLE
Execution Timeline does not live update with Azure Database for PostgreSQL server 10

### ISSUE THREAD

**Issue by j-hulbert** [dagster-io/dagster#3927]
## Summary
Execution timeline is not updating in real-time when connected via port forward on k8s (same when connected via Ambassador ingress)

Manually refreshing page updates the timeline.

Chrome network:
```
'ws://localhost:8080/graphql' failed: WebSocket is closed before the connection is established.
```

While it is executing and watching in Chrome network tab it seems there are some payloads coming across websocket but nothing new is getting visualized to page.

There seems to be 4 websocket connections attempted each time pipeline is executed and through multiple attempts to reproduce 3 seem to connect and provide payloads and the 4th never connects.

## Reproduction
Port forward connection from pod
```
kubectl --namespace dagster port-forward $DAGIT_POD_NAME 8080:80
```

Execute a pipeline from Playground

Will switch to execution screen with Engine started and [K8sRunLauncher] Kubernetes run worker job launched

No other timeline updates will occur unless page is reloaded

## Dagit UI/UX Issue Screenshots
![chrome1](https://user-images.githubusercontent.com/78444285/112060052-0c3f4c80-8b33-11eb-94c0-8908c63c8259.png)
![chrome4](https://user-images.githubusercontent.com/78444285/112060155-31cc5600-8b33-11eb-8b71-ddd48159c675.png)
![chrome3](https://user-images.githubusercontent.com/78444285/112060054-0c3f4c80-8b33-11eb-8d0d-e52bf412a36d.png)

Graphql error and different type of payload messages during one run
![chrome5](https://user-images.githubusercontent.com/78444285/112061378-caafa100-8b34-11eb-8b2d-64857adc11b6.png)

## Additional Info about Your Environment
Deployed on AKS (Azure Kubernetes Service) via Helm chart (0.11.0)
External Postgres and user provided code image provided (all other helm chart defaults)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by j-hulbert** [comment]
FYI - this also means no logs show in dagit for the raw step output (compute step) until the step has completed and the logs are persisted to cloud storage

**Comment by j-hulbert** [comment]
Tweaked some settings on ingress controller for authentication and I'm no longer getting any errors related to websockets when connected through ingress (k8s port forward is still an issue) and I can see the websocket messages coming through while the pipeline is running but the dagit doesn't update the screen with the info until I reload the page.
The job does take a little while to spin up (~8 seconds from Kubernetes run worker job launched to Started process for pipeline (pid: 1). - not sure if that is potentially related

**Comment by alangenfeld** [comment]
>  I can see the websocket messages coming through while the pipeline is running

If you inspect the messages, do they appear to contain substantial event payloads?

**Comment by j-hulbert** [comment]
There are payloads of type runGroupOrError, instance, and pipelineRunOrError with data while the pipeline is executing
![payloads](https://user-images.githubusercontent.com/78444285/113225231-211a8f00-925b-11eb-89c0-9df3aed445ae.png)

There is another connection with type PipelineRunLogsSubscriptionSuccess that I see the "Pipeline Starting" and "Kubernetes run worker job launched" messages inside the payload. This must be the one that is the issue but there are no errors in console or in the connection while its running.
![payloads2](https://user-images.githubusercontent.com/78444285/113225247-2677d980-925b-11eb-9769-4c7d5b21291b.png)
![payloads3](https://user-images.githubusercontent.com/78444285/113225255-2aa3f700-925b-11eb-9a94-c4c20e7b445a.png)

When the pipeline finishes the status at the top of the screen updates to success when it completes without having to reload the page

Reloading the page causes a connection with PipelineRunLogsSubscriptionSuccess filled in with all the logs

**Comment by alangenfeld** [comment]
Thanks. Looking at this it seems we have the connection between the client and webserver sorted out, so the issue is in the webserver and its subscription to the postgres database. 

Does the `dagit` pod have anything in its logs?  Can you share some more details about your external postgres database?

For context, we use `LISTEN` / `NOTIFY` to power our subscription to the events flowing in to the databse. https://www.postgresql.org/docs/13/sql-notify.html

**Comment by j-hulbert** [comment]
Nothing in the dagit logs - just "Loading Repository" then a message about Telemetry. Are there more logs I can enable?

Postgres database is Azure Database for PostgreSQL server 10. Any permissions needed to perform LISTEN/NOTIFY?

**Comment by j-hulbert** [comment]
Any chance this timeout could be the culprit? Not sure how to get dagit to give more logs but the pipeline is consistently taking over 5 seconds to start.
https://github.com/dagster-io/dagster/blob/ebdb6e371b961c10da334921cc3858158978ace1/python_modules/libraries/dagster-postgres/dagster_postgres/pynotify.py#L78

**Comment by alangenfeld** [comment]
> Are there more logs I can enable?

Unfortunately not https://github.com/dagster-io/dagster/issues/3704

> Any chance this timeout could be the culprit?

From what I can tell the code is setup to keep spinning in that while loop even if it hits a timeout, so I don't think that is the culprit.

**Comment by j-hulbert** [comment]
FYI ran a test with the default deployment (no external postgres, postgres container in k8s) and the timeline updates normally.

**Comment by j-hulbert** [comment]
Turned on verbose logging in Postgres (this happens after every NOTIFY statement)
2021-04-13 14:11:53 UTC-6075a6a9.db868-LOG:  statement: NOTIFY run_events, 'eb55a21a-20ed-4eef-94d4-95bad310a932_11799'; 
2021-04-13 14:11:53 UTC-6075a6a9.db868-LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.

**Comment by alangenfeld** [comment]
Hmm - a good lead though its not obvious to me what exactly it implies. 
Searching for that error message does pull up other Azure Postgres issues

https://github.com/npgsql/npgsql/issues/2491
https://github.com/brianc/node-postgres/issues/1344

skimming over these, both mention `SSL` settings - but it's not clear that these are actually related.

**Comment by j-hulbert** [comment]
Is there a way to add keep alive settings to the postgres connection? It seems Azure has an aggressive idle connection reset (4 minutes?) that could be to blame.

**Comment by j-hulbert** [comment]
I upgraded to 0.11.6 and when I start the pipeline from the dagit playground now I get a GraphQL error with the following message. Assume this is related to the issue we have already been troubleshooting. The pipeline runs fine and same behavior as before (reloading the screen gives me logs but no logs in realtime)
```
Message: Watcher thread never started

Path: 

Locations: 

Stack Trace:
  File "/usr/local/lib/python3.7/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/usr/local/lib/python3.7/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/usr/local/lib/python3.7/site-packages/dagster_graphql/implementation/pipeline_run_storage.py", line 16, in __call__
    self.instance.watch_event_logs(self.run_id, cursor, self.handle_new_event)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/instance/__init__.py", line 1003, in watch_event_logs
    return self._event_storage.watch(run_id, cursor, cb)
  File "/usr/local/lib/python3.7/site-packages/dagster_postgres/event_log/event_log.py", line 200, in watch
    self._event_watcher.watch_run(run_id, start_cursor, callback)
  File "/usr/local/lib/python3.7/site-packages/dagster_postgres/event_log/event_log.py", line 316, in watch_run
    raise Exception("Watcher thread never started")
```

**Comment by j-hulbert** [comment]
Forgot to add - the new helmchart allows options for postgres so I tried the following but it did not help:
```
  postgresqlParams:
    sslmode: require
    keepalives_idle: 120
    keepalives_interval: 30
    keepalives_count: 5
```

**Comment by j-hulbert** [comment]
I have not been seeing the watcher thread error lately so maybe that was an intermittent or unrelated issue but the timeline issue still exists in latest version (0.11.8)

**Comment by j-hulbert** [comment]
If raw python logs aren't showing up in container logs at all and only in Dagit after the solid completes the same issue as above? Does the AzureBlobComputeLogManager use the same listen/notify subscribe mechanism?

**Comment by alangenfeld** [comment]
> aren't showing up in container logs

This is not intended, but also not the only report we've gotten https://github.com/dagster-io/dagster/issues/4226
The expectation is that the logs are tee-ed to both stdout/stderr and a file that gets uploaded.

cc @prha 

> only in Dagit after the solid completes

This is a current known problem, where the azure/s3 etc compute log managers only upload on completion so you can't view them mid computation. We are in the early phases of solving this problem.

**Comment by j-hulbert** [comment]
Upgraded to Dagster 1.1.9 and the execution timeline
