### ISSUE TITLE
Concurrency limit on each value of a tag

### ISSUE THREAD

**Issue by nawaf-sheikh-qbatch** [dagster-io/dagster#3937]
## Use Case
I'm trying to add a tag on a pipeline with value equal to the user id. Now, this pipeline's run could be multiple but run for each user should be single at any instance. For example, suppose there are 4 users, and a pipeline A. Pipeline A is triggered by a sensor to create 2 task of pipeline A for each user, i.e. 8 tasks of pipeline A. Now from the queue, at any instance,  single task of each user of pipeline A should get started (single is for an example, it could be any limit). 

## Ideas of Implementation
I consider it would be great if this option gets added in the tag_concurrency_limit of queue coordinator. Here is an example of how user could define such thing, consider a tag key 'user'

`
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 25
    tag_concurrency_limits:
      [{ key: 'user', value: '*', limit: 1 }]
`

**Comment by gibsondan** [comment]
Reposting my question here from slack: Could you say more about what the goal would be here? Typically these rules are used to prevent there from being too many runs at once (to prevent the system from using too many resources at once). It doesn't seem like a rule like that would help with resource limits since there could still be an unbounded number of runs happening at once, so I'm curious what problem it would be solving instead.

**Comment by nawaf-sheikh-qbatch** [comment]
Actually in our use case the scheduler is queuing multiple pipeline for multiple users. Now we want to limit that for each user from a queue single pipeline should run at a time. And then there would be another tag on all of those pipeline which would be limiting those concurent runs of the pipeline. So we can say at any instance, lets say 5 concurent pipelines would be running and each pipeline is of different user. The reason we want to run single pipeline per user is because of throttling issue of the api as the burst rate for that api is 1 sec. So for a user if multiple pipelines are running most of the pipeline would return a retry request.

**Comment by szalai1** [comment]
Hey @gibsondan, we have another use case. 

We want to run huge backfills (one per day for 2 years), but only one run at a time per pipeline. 
As we have multiple pipelines we want to group them per pipeline. 

Current workaround: 
```
          - key: "dagster/backfill"
            limit: 10
          - key: "one_at_a_time"
            value: "batch_a"
            limit: 1
          - key: "one_at_a_time"
            value: "batch_b"
            limit: 1
          - key: "one_at_a_time"
            value: "batch_c"
            limit: 1
...
``` 
This way we can the individual backfills with `one_at_a_time: batch_x` so we make sure there is no concurrency issue within pipelines, but different pipelines can run in the same time.

**Comment by johannkm** [comment]
Does anyone have API suggestions for this? We have to differentiate between 

"match this key regardless of value"
```
- key: "dagster/backfill"
  limit: 10
```
and "match this key with a separate limit per value". Thoughts on something like
```
- key: "one_at_a_time_per_value"
  limit: 1
  separateLimitPerValue: true
```

**Comment by alangenfeld** [comment]
to avoid conflicts between the `value` field and these toggles, you can change `value` to a `ScalarUnion` so you could have

```
- key: "one_at_a_time_per_value"
  limit: 1
  value:
    applyLimitPerUniqueValue: true
```

and the `value: str` stuff will continue working

**Comment by sryza** [comment]
Would we ever want to allow someone to someone to set both a key limit and a value limit? I could concoct a situation where that would be useful.  if so, what about:
```
- key: "one_at_a_time_per_value"
  limit: 5
  valueLimit: 1
```

**Comment by johannkm** [comment]
@alangenfeld cool, I'll use that.

@sryza It's a list instead of a dict, so you can have multiple rules for a single key. So the above case could be expressed as 

```
- key: "one_at_a_time_per_value"
  limit: 5
- key: "one_at_a_time_per_value"
  limit: 1
  value:
    applyLimitPerUniqueValue: true
```

Which I think is more clear?

**Comment by sryza** [comment]
I see.  I don't think I have a strong opinion.
