### ISSUE TITLE
[Docs] New Doc Pages don't automatically navigate to top, have to keep scrolling upwards

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#3939]
Hello!  New documentation pages don't scroll or automatically navigate to the top of the page when clicking on a link to a new page unless the page I'm currently on prior to switching to the new page is at the top already.  So it appears, it just carries over  scroll position of the current page to the new page.  So as a result, I have to keep scrolling to the top when the new page loads.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Closed in favor of https://github.com/dagster-io/dagster/issues/4091
