### ISSUE TITLE
in backfill modal, "Re-execute From Failures" is seemingly always gray

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3943]
## Summary

![image](https://user-images.githubusercontent.com/654855/112512763-e5f6f800-8d50-11eb-9529-9bdbca83bdf3.png)

![image](https://user-images.githubusercontent.com/654855/112512804-ed1e0600-8d50-11eb-86af-534755bb9c33.png)

## Reproduction

* Run a backfill for the longitudinal pipeline - some runs will fail
* Open the backfill modal a second time
* "Re-execute From Failures" is gray

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
I think this should no longer be an issue, now that the queries are split. @sryza does this still repro for you?

**Comment by sryza** [comment]
I can't reproduce this.  Closing!
