### ISSUE TITLE
[Content Gap] Specifying a container image to use in a gRPC server

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3949]
The use of the DAGSTER_CURRENT_IMAGE environment variable (particularly outside of k8s where the helm chart sets it automatically for you) could be documented better.

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by nullhack** [comment]
I am struggling with this, trying to set up a helm installation that uses a local grpc server to provide my repositories. How to set up `values.yaml` to make the container read from local grpc server?

I tried to set my values.yaml to:
```yaml
load_from:
  - grpc_server:
      host: localhost
      port: 4266
      location_name: "my_project"
```

After that I up the grpc:
```bash
dagster api grpc --package-name my_project_package_name --host 0.0.0.0 --port 4266
```
And install the helm chart with:
```bash
sudo helm upgrade --install dagster dagster/dagster
```

But instead of my package, the ui shows the default example project. Is the values.yml correct?

**Comment by gibsondan** [comment]
Hi @nullhack - the helm chart values.yaml doesn't have a `load_from` key - what you have there looks like a valid `workspace.yaml` file, but not a valid `values.yaml` file to use as input into the helm chart.

You can see the format of the helm chart here: https://github.com/dagster-io/dagster/blob/master/helm/dagster/values.yaml

and more information about using the helm chart to access gRPC servers here: https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm#configure-your-user-deployment

The helm chart currently operates under the expectation that it will spin up the gRPC servers for you (rather than you running them locally). I'd expect you to be using the `dagsterApiGrpcArgs` from those docs for that.

**Comment by catherinewu** [comment]
Specifically, we want to add info about DAGSTER_CURRENT_IMAGE to https://docs.dagster.io/concepts/repositories-workspaces/workspaces#running-your-own-grpc-server and we can include this in a debugging section in the kubernetes deployment docs https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm
