### ISSUE TITLE
Dagit backfill not showing progress of solids within composite solids

### ISSUE THREAD

**Issue by rubenlopezlozoya** [dagster-io/dagster#3961]
## Summary
When running a backfill over a partition set, the matrix representing whether a solid was executed successfully, failed or was skipped is not updating for solids within composite solids.

## Reproduction
1. Create a pipeline containing a composite solid and a standard solid for reference
2. Create a partition set for that pipeline
3. Execute a backfill over the partition set using Dagit UI
4. The matrix for the execution results of each solid will only update for the standard solid

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/23010951/112893097-0f848c00-908f-11eb-95bd-cad93daadd15.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @rubenlopezlozoya .

@prha - do you have a guess at what's going on?

**Comment by prha** [comment]
This should be fixed with 31729f5 and will get pushed out in next week's release: `0.11.5`
