### ISSUE TITLE
dagit ver 0.11.2 - When activating schedule, have to perform browser refresh for green dot to appear

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#3965]
In dagit, bottom left, where the schedules or sensors are listed, when I activate or turn on a schedule, the green dot does not appear or renders to the right of the schedule's name.  I did wait at least 15 seconds before manually refreshing.  Not positive, but thought for sure in previous versions the green dot would appear after turning on the schedule eventually without manually refreshing the browser.

Browser: Chrome version 89

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
fixed in latest release
