### ISSUE TITLE
on asset page, show children of the asset

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3973]
## Use Case

Right now we show the assets that are parents of the asset.  It would be helpful to show children as well.

This helps answer the question "if I make changes to this table, who and what will I affect?"

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by bengotow** [comment]
I think this ticket was talking about the old "Asset Lineage" that was computed from runtime data. Now that we have SDAs, the asset details page shows proper upstream and downstream assets and I think we can close this.
