### ISSUE TITLE
code snippets in docs should include imports

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3975]
## Use Case

Most code snippets in our docs do not include imports.  This leaves readers guessing and requires them to do more typing when they want to copy/paste.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Duplicate of https://github.com/dagster-io/dagster/issues/4125
