### ISSUE TITLE
Dagit incorrectly caches two pipelines with the same name (and the same repo name) but in different repo locations

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#3979]
Repro:
Two pipelines with the same pipeline name and repository name (but in different repo locations) get cached incorrectly - if dagit starts with both repo locations active, the snapshots are they same for both pipelines (even if they should be different - e.g. if they have different solids). Appears to just be an issue in a client-side cache, since actually launching a run in the pipeline shows the correct execution plan and solids

## Reproduction
See https://dagster.phacility.com/D7247 for a relatively small repro

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment]
fixed in https://dagster.phacility.com/R1:8b8e92f9c26162e1b624d439773b677006dcc6b7
