### ISSUE TITLE
[Documentation Feedback] Problem on /concepts/assets/asset-catalog page

### ISSUE THREAD

**Issue by WesRoach** [dagster-io/dagster#3981]
[dagster.io](https://dagster.io/) front page section: "Link data to computations" contains a link that leads to a 404.

The link: [https://docs.dagster.io/overview/asset-materializations](https://docs.dagster.io/overview/asset-materializations)

![image](https://user-images.githubusercontent.com/8878926/113246410-9cda0300-927e-11eb-9c0c-7768ec438818.png)

**Comment by helloworld** [comment]
Thank you for catching this! This has been fixed on dagster.io
