### ISSUE TITLE
in "Asset Materializations" concept page, motivate the asset catalog

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3990]
We explain what the asset catalog is, but not why someone should care.

**Comment by clairelin135** [comment]
@shalabhc Would be nice to add a screenshot of the asset catalog page to this doc: https://docs.dagster.io/concepts/assets/asset-materializations and to explain that from the asset catalog page you can view all of your defined assets and do certain actions (view in a global asset graph or wipe materializations)

**Comment by shalabhc** [comment]
Couple of questions:

1. The asset-materializations page uses the term `Asset Catalog` but the page it links to just calls it the `Assets` page. We should probably make this consistent.
![image](https://user-images.githubusercontent.com/7066873/170151432-0ab7ce34-b0e9-4314-b9e4-a211ff61ee81.png)

2. Can we reuse the screenshot of the assets catalog from the linked page? (https://docs.dagster.io/concepts/dagit/dagit#assets)

**Comment by shalabhc** [comment]
Created the draft PR anyway reusing the screenshot above: #8049

**Comment by erinkcochran87** [comment]
1. Update intro in Asset Materializations page
2. Beef up section about Assets page in Dagit UI docs

**Comment by sryza** [comment]
We now motivate assets at a bunch of places in our docs, so going to close this
