### ISSUE TITLE
[Content Gap] document DagsterInstance APIs that we expect sensors to use

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3992]
We recommend asset sensors as a pattern, but our API docs don't include the API that users need to implement them (`DagsterInstance.events_for_asset_key`).

If we think it's legitimate for users to build sensors off of other kinds of events that are accessible from the instance (e.g. pipeline run completions), then we should include those in the API docs as well.

**Comment by yuhan** [comment]
https://docs.dagster.io/_apidocs/internals#dagster.DagsterInstance.get_event_records
