### ISSUE TITLE
would be nice if the side nav for runs/status had some quick indication of state

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3997]
rn you need to click through to find out, e.g., if there are any currently executing runs or if the status is green

![Screen Shot 2021-04-05 at 10 13 40 AM](https://user-images.githubusercontent.com/427016/113602551-9b4e6900-95f7-11eb-868f-6518733d6d84.png)

**Comment by yuhan** [comment]
not applicable since the revamp
