### ISSUE TITLE
Be able to view git hash and deployed time of an instance

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3998]
## Use Case

I am running into this during a time-sensitive debugging of one of our internal instances. I would like to know more precisely the state of the instance in terms of what code is deployed and when.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Do you meant the git hash of the instance itself or the git hash of each user code repository?

**Comment by schrockn** [comment]
Both would be useful, but in this case I think the user code repo would be the most useful.

**Comment by rexledesma** [comment]
This is now visible in our internal instances, using https://github.com/dagster-io/dagster-cloud-cicd-action.
