### ISSUE TITLE
Search drops results on multiple tokens

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#4002]
## Summary

Easiest way is to show this video:

https://user-images.githubusercontent.com/28738937/113637124-1c762200-9631-11eb-8de2-17a689d22b09.mov

You'll see that it filters down correct when you match the prefix but then filters out the search at a strange time. It will be very useful to match on multiple substrings.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Probably something we can tweak in the Fuse settings.
