### ISSUE TITLE
more useful dagit home page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4005]
## Use Case

Right now, when you navigate to dagit, it takes you to the first pipeline in your workspace.  This is only useful if that happens to be the pipeline you're interested in.

## Ideas of Implementation

A list of all pipelines?  A search box?  A list of all pipelines, schedules, and definitions?  An instance status page?

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
On the practitioner side, we can track the last viewed pipeline and try to land the user on that. And if it's not present in the loaded workspace, then go to pipeline `[0]`.

On the platform side, I'm not sure we currently have a better solution than the Instance Status page. A richer homepage experience would be a larger project worth discussing further.

**Comment by sryza** [comment]
IMO tracking the last viewed pipeline would be an unambiguous win over what we have now.  Would this be our first foray into local storage though, and would that be unexpected?

**Comment by hellendag** [comment]
Nah, we already use localstorage for other user state too, like left nav repo filter state and playground configs.

**Comment by hellendag** [comment]
We now have something for this! Closing in favor of more granular tasks and error reports.
