### ISSUE TITLE
Dependency package versions aren't pinned and lead to incompatibilities after dependency resolution.

### ISSUE THREAD

**Issue by KDMichaelis** [dagster-io/dagster#4009]
## Summary

Dagster only works correctly if all installed Dagster packages in an environment are of the same version. However, when using package management tools such as [poetry](https://python-poetry.org/) two problems occur:

- Dependency resolution will be successful even if different versions for different Dagster packages are specified as requirements.
- If an older version of a Dagster package is specified as a requirement which itself depends on other Dagster packages which are not explicitly included in the requirements this can result in the installation of the older version of the specified package and the latest version (or an even older) version of unspecified packages.

Both cases result in incompatible combinations of Dagster packages installed in the environment.

Expected behavior: In the first example dependency resolution shouldn't be successful, and in the second case the installed version of all dependency Dagster packages should be the same as the specified version of the Dagster package explicitly stated in the requirements.

## Reproduction

The following pyproject.toml file will reveal both stated cases:

```
[tool.poetry]
name = "example-name"
version = "0.1.0"
description = ""
authors = ["example-author"]

[tool.poetry.dependencies]
python = "^3.8"
dagster-celery-k8s = "==0.10.9"
dagster-pyspark = "==0.10.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Running `poetry update` is successful. Activate the environment and run `pip list | grep dag`. This is an exemplary result:

```
dagster                0.10.2
dagster-celery         0.11.3
dagster-celery-k8s     0.10.9
dagster-graphql        0.11.3
dagster-k8s            0.11.3
dagster-pyspark        0.10.8
dagster-spark          0.11.3
```

**Comment by rexledesma** [comment]
This should be resolved with https://github.com/dagster-io/dagster/commit/5fcfd7bdce3b4e97bbf57d048f5c4cb171f1cc1d.
