### ISSUE TITLE
runs viewer typeahead has no STARTED status

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4017]
![image](https://user-images.githubusercontent.com/654855/114099831-4f5e2700-9878-11eb-9252-56682a7d7647.png)

**Comment by hellendag** [comment]
Yeah, I think we truncate to six results per filter type, but I'm not sure why. `STARTED` is there, it just gets cut off the end of the default list. We could just show more than six.

**Comment by sryza** [comment]
Showing more than six sounds like a good solution to me.

**Comment by bengotow** [comment]
This will be resolved by 4017
