### ISSUE TITLE
Incorrect update_timestamp saved to runs table

### ISSUE THREAD

**Issue by kudryk** [dagster-io/dagster#4022]
## Summary
While looking at entries in the Runs table, I noticed that the `create_timestamp` values are saved in UTC and the `update_timestamp` values are saved in one's local time zone. I'm in Mountain, therefore entries have an update_timestamp value that occur _before_ the create_timestamp values. @prha requested I create a bug for this.

![image](https://user-images.githubusercontent.com/4217975/114230262-2b611b00-9936-11eb-8b96-99e4f6af3096.png)

## Additional Info about Your Environment
I'm running Dagster locally.

Dagster 0.10.7.
MacOSX 10.13.6
Postgres 12.4 in a docker container

**Comment by prha** [comment]
On master as a2189a056, will go out with `0.11.5`.
