### ISSUE TITLE
Parametrize timeout for dagster-celery-k8s

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#4029]
## Use Case

Hi, I have some solids that necessarily need to run for over 24h. The dagster-celery-k8s executor seems to hardcode a timeout of 24h. Would it be possible to parametrize it ?

## Ideas of Implementation

Ideally this should be set per-solid in the executor config, but might be simpler to implement it as a single setting at first (something like `default_solid_timeout_seconds`)

## Additional Info

This is the line that should be changed I believe:
https://github.com/dagster-io/dagster/blob/75fde1e43c9d0d949ef56ea386d9f5bcaadcf8fe/python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/executor.py#L438-L443

That function has a [default argument](https://github.com/dagster-io/dagster/blob/75fde1e43c9d0d949ef56ea386d9f5bcaadcf8fe/python_modules/libraries/dagster-k8s/dagster_k8s/client.py#L211) of [24h](https://github.com/dagster-io/dagster/blob/75fde1e43c9d0d949ef56ea386d9f5bcaadcf8fe/python_modules/libraries/dagster-k8s/dagster_k8s/client.py#L10)

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by jmsanders** [comment]
@amarrella I went ahead and made this configurable: https://github.com/dagster-io/dagster/commit/d64bcf59ccf80ad49618cba1f2e78cf8926a9192

**Comment by amarrella** [comment]
That's amazing, thank you so much @jmsanders !
