### ISSUE TITLE
report long step run times in minutes, not seconds

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4042]
![image](https://user-images.githubusercontent.com/654855/114635518-c11fe180-9c79-11eb-81d9-dd84c3038aa2.png)

I find myself needing to do arithmetic a lot when inspecting pipelines.  For a step that takes 14.45 minutes, it's much easier to reason about it as taking 14.45 minutes than 867 seconds.

**Comment by bengotow** [comment]
This will be addressed in https://dagster.phacility.com/D7609!
