### ISSUE TITLE
dagit ver 0.11.4: Schedules do not get removed from list even though the associated repository was deselected

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#4048]
When I deselect or uncheck a repository in the repository filter feature, the schedules associated with that repository still remain listed in the bottom left of dagit.  I have to deselect every repository, then select the repository for it to list only schedules related to that selected repository.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Thanks for the report, taking a look.
