### ISSUE TITLE
Make pipeline name clickable in runs view

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#4050]
## Use Case

I am looking at a run on the runs page. I want to navigate to the pipeline. The name of the pipeline is there. Clicking on it does nothing.

![Screen Shot 2021-04-14 at 3 36 50 PM](https://user-images.githubusercontent.com/28738937/114783874-98f6b800-9d37-11eb-8cf6-ddbad54d62cb.png)

## Ideas of Implementation

Click on pipeline name and go to pipeline.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Yeah, we removed that a while ago because it was confusing -- people were clicking on the pipeline name when what they really wanted was to navigate to the run itself. I think if we make the pipeline name clickable here, we risk returning to that confusing state. @bengotow and I can discuss.

**Comment by hellendag** [comment]
Added a link icon next to the pipeline name, hopefully that's effective enough without being confusing.
