### ISSUE TITLE
dagit does not execute 2nd + steps in VirtualEnv Created in PyCharm

### ISSUE THREAD

**Issue by ddsmit** [dagster-io/dagster#4051]
## Summary
If use a VirtualEnv created in pycharm, dagit will execute the first step of a pipeline and then stop until it times out. The execution from the command line works without an issue.
On my system, pycharm creates the VirtualEnv in C:\Users\[user]\.virtualenves\[env_name]

## Reproduction
Using pycharm on a Windows 10 machine, create a new project and create a new environment using "VirtualEnv" in the C:\Users\[user]\.virtualenves\[env_name] directory. Install the necessary dependencies and try running the cereal example from the command line (works), then from dagit (didn't work).

If you create a virtual environment in the project folder using python venv venv, activate the environmet .\venv\scripts\activate, and install the dependencies, it will work from both the command line and dagit (my current work-around). 

## Additional Info about Your Environment
Windows 10
Python 3.9.0
Pycharm Community Edition 2019.1
Testing dagit in chrome

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
> dagit will execute the first step of a pipeline and then stop until it times out

Can you share some more details about this? Is there an exception when the timeout occurs you can send the stack trace for? There is a "download debug file" option in the runs page you could send over.

**Comment by alangenfeld** [comment]
Closing since its hard to take an any action without further details. Feel free to reopen with details.
