### ISSUE TITLE
[Content Gap] Run dagster-daemon and dagit as a service in Windows without docker

### ISSUE THREAD

**Issue by nibu147** [dagster-io/dagster#4052]
I'm trying to run dagster-daemon and dagit in Windows 10 without Docker, but I'm having troubles with it.

I've built a .bat which performs the following actions:
- cd \dagster_code_folder
- <dagster_python_env_dir>\activate.bat
- set DAGSTER_HOME=\dagster_code_folder
- START /B dagster-daemon run
- dagit

If I run those command from Command Prompt, it works fine and I'm able to access the Dagit UI.
Instead, if I run that .bat file, nothing happens.

1) which is the error in my procedure?
2) which is the correct way to run dagster-daemon and dagit as background services in Windows without using Docker?

Thanks!

**Comment by alangenfeld** [comment]
> Instead, if I run that .bat file, nothing happens.

are you running the bat file from the command line or desktop? Could you add `echo` statements if running from the prompt to ensure the bat file is proceeding as expected?

**Comment by pybokeh** [comment]
Hi @nibu147 , I'm not an expert on Windows DOS/batch scripting, but this seems to work for me.  I am using the `&& ^` symbols to chain additional commands.  The `&&` means to execute the command if the preceding command was successful and the caret (^) symbol in this case is being used as a line continuation.

Contents of my "start_dagster.bat" file:
```
set DAGSTER_HOME=%USERPROFILE%\.dagster
D:\Python38\envs\dagster_dev\Scripts\activate.bat && ^
REM I have workspace.yaml file saved in the folder below, which is why I have to cd into it:
cd D:\gitprojects\sc-dagster-pipelines\src && ^
start /b D:\Python38\envs\dagster_dev\Scripts\dagster-daemon.exe run && ^
D:\Python38\envs\dagster_dev\Scripts\dagit.exe && ^
pause
```

**Comment by catherinewu** [comment]
Thanks @pybokeh for sharing your .bat file! Going to close this issue, feel free to re-open if the problem persists
