### ISSUE TITLE
Path prefix is not included on View Partition Matrix and View Backfill Runs links

### ISSUE THREAD

**Issue by lamielle** [dagster-io/dagster#4064]
## Summary
On the Dagster instance status page in the Backfills tab, there is a small button that reveals a dropdown with links to View Partition Matrix and View Backfill Runs.  When running Dagit with the --path-prefix flag these two links do not include the configure prefix.  Screenshot of the dropdown I'm referring to:

![Screen Shot 2021-04-20 at 9 16 15 AM](https://user-images.githubusercontent.com/16318/115421772-793d1500-a1b9-11eb-94be-c2e27783f416.png)

## Reproduction

1. Locally run Dagit on `localhost:3000` with `--path-prefix /dagster`
2. Navigate to `http://localhost:3000/dagster/instance/backfills`
3. Ensure at least one backfill has been executed so this tab is not empty
4. Open the dropdown for one of the backfills
5. Click either the View Partition Matrix or View Backfill Runs items
6. Note that the `/dagster` path prefix is missing in the URL after clicking

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by prha** [comment]
well, this is still outstanding, but should be resolved with the next release `0.11.6`

**Comment by lamielle** [comment]
Thanks for the super fast fix @prha!  🎉  ⭐
