### ISSUE TITLE
materialization-level asset lineage

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4067]
When someone is debugging a problem with one of their assets, they want to understand exactly what computation and data went into producing it.

Our current asset lineage UI makes it easy to understand the lineage of an asset at the asset level.  Making it easy to understand the lineage of an asset at the materialization level would make it possible to do this kind of debugging.

**A potential approach**
Materializations have parent asset keys, which are exposed in the asset catalog as links to the parent asset.  Currently, these links take you to the asset page for the parent.  We could have these links instead take you to the most recent materialization of the parent asset that occurred before the child asset materialization that the link is being displayed for.  This would require adding some way to link to a particular materialization.

**Comment by mingfang** [comment]
It would be great if I can see lineage graphically as a dependency diagram.
