### ISSUE TITLE
generated new project is missing default mode in pipeline

### ISSUE THREAD

**Issue by mingfang** [dagster-io/dagster#4069]
https://github.com/dagster-io/dagster/blob/ae921eb6dd66775119f07b3d4a67b5def6957f16/python_modules/dagster/dagster/generate/new_project/new_project/pipelines/my_pipeline.py.tmpl#L8

The `my_sensor.py` fails without a `default` mode.

**Comment by catherinewu** [comment]
thanks @mingfang for the contribution! we just kicked off BK

cc @sryza do you think it's better to add a mode or modify the sensor to use an existing mode

**Comment by sryza** [comment]
IMO it would be best to add a mode called "prod" and have the sensor point at "prod".  It's easy to understand the relationship between "dev" and "prod", but less straightforward to understand the relationship between "dev" and "default".

**Comment by mingfang** [comment]
@sryza 
Conceptually I agrees that `prod` makes more sense than `default`.
I think the bigger problem is on the sensor side in that it's support for modes is too limited.
The problem with sensors that I see relating to this are
1-it assumes the mode is `default` when no modes are setup (the problem in this issue)
2-It needs option to take in the same set of modes as the pipeline so that I can choose the mode using `Dagit`, just like I can do for pipelines.

**Comment by sryza** [comment]
@mingfang - thanks for the feedback.  That makes sense.  We're working on some changes that might make that more straightforward.

**Comment by sryza** [comment]
This is fixed in d774b3ff1ca0d5347e6559e71a8f1355238dced5.
