### ISSUE TITLE
[Content Gap] explain when dynamic orchestration is appropriate to use

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4076]
## What content is missing

Examples of when appropriate to use:
* Hyperparameter search for ML models
* Read a set of files in a directory

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
We can either expand the explanation in https://docs.dagster.io/concepts/solids-pipelines/pipelines#dynamic-mapping--collect or make "Dynamic Orchestration" a top-level concept under Solids&Pipelines.

**Comment by erinkcochran87** [comment]
Thoughts on keeping this open?

**Comment by sryza** [comment]
I think we can close this and reopen it if it comes up again.
