### ISSUE TITLE
Favicon missing when Dagit is run with a path prefix

### ISSUE THREAD

**Issue by lamielle** [dagster-io/dagster#4079]
## Summary
When running Dagit with the path prefix flag the favicon does not load.

## Reproduction
1. Run in an environment like Kubernetes using the `--path-prefix /dagster` flag
2. Ensure that requests to `/` are not routed to Dagit but some other location/service or even return a 404 (as is my case)
3. Note that since Dagit does not insert any explicit location for the favicon, the browser attempts to load "/favicon.ico", which fails:
![Screen Shot 2021-04-22 at 2 47 41 PM](https://user-images.githubusercontent.com/16318/115783242-d97ab500-a379-11eb-9992-4b97ede3a495.png)

## Additional Info about Your Environment
Dagster is deployed in Kubernetes using an ALB for ingress to route requests to the Dagit pod.  Only requests with the `/dagster` prefix will be routed to the Dagit pod, no others.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by lamielle** [comment]
Note, I believe a fix here would be to use the same method for getting the configured path prefix as is used when rendering links and render a `link` tag in `<head>`, something like this:

    <link rel="icon" href="{path prefix}/favicon.ico" />

**Comment by hellendag** [comment]
Thanks for the report, I'll take a look!

**Comment by hellendag** [comment]
Fixed by https://github.com/dagster-io/dagster/commit/6194a99d4cb69b5e00449b7531dc62d12ee23479.

**Comment by lamielle** [comment]
Confirming this is fixed in 0.11.7, we upgraded and the favicon is back!  Nice work @hellendag!
