### ISSUE TITLE
Resuming from failure not finding root serialized output

### ISSUE THREAD

**Issue by hebo-yang** [dagster-io/dagster#4087]
## Summary

I have a pipeline that looks like this with all outputs serialized by fs_io_manager. 
![image](https://user-images.githubusercontent.com/66688603/116005026-2351de00-a5ba-11eb-8308-9f97095656ee.png)

The initial execution (3b367d5f) failed at step "train_markertplace". After I fixed the problems, I re-executed (06e3ff91) from failure and it was able to move further. However, it failed at a new step "post_adjustment_drive". 
![image](https://user-images.githubusercontent.com/66688603/116005066-38c70800-a5ba-11eb-8aab-a581eab11e36.png)

After fixing the issues, now I am not able to re-execute from failure due to this error. 
![image](https://user-images.githubusercontent.com/66688603/116005157-922f3700-a5ba-11eb-9eac-1763691db632.png)

It is looking for output from solid "start_pipeline" in run (06e3ff91). However this solid was only run in root execution (3b367d5f)

I think the right search path for outputs could be defined by searching upwards the execution tree. For "Run 1 -> Run 2 -> Run3", if I re-execute from Run3, it looks for serialized outputs in the order of 3 -> 2 -> 1?

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment]
Thanks for reporting @hebo-yang. It seems a re-execution bug. I'm working on it.

**Comment by yuhan** [comment]
Hi @hebo-yang! a fix was landed just now. it will go out in tomorrow's release. please reopen the issue if you still have trouble with it.

**Comment by hebo-yang** [comment]
Wow! Thanks a lot Yuhan! You are awesome!
