### ISSUE TITLE
[Documentation Feedback] Problem on /tutorial/intro-tutorial/configuring-solids page

### ISSUE THREAD

**Issue by BorePlusPlus** [dagster-io/dagster#4088]
Does this page need to be updated? I'm following the tutorial yet things don't work.

e.g. when trying to configure new run in playground I get:
`Received unexpected config entry "inputs" at path root:solids:read_csv. Expected: "{ config?: Any outputs?: [{ result?: { json: { path: String } pickle: { path: String } } }] }".`

**Comment by sryza** [comment]
Hi @BorePlusPlus - thanks for the report.  It looks like the screenshot is out of date.  If you use the config that's listed here, I believe it should work: https://docs.dagster.io/tutorial/intro-tutorial/configuring-solids#yaml-fragments-and-dagster-cli.

**Comment by sryza** [comment]
The screenshot should be fixed as part of this change: https://dagster.phacility.com/D7516.

**Comment by BorePlusPlus** [comment]
Yep, I ended up doing just what you suggested. Nice to see such a quick turnaround 🚀
