### ISSUE TITLE
Docs site navigation stays in the same place after switching pages

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4091]
## Summary
In the docs site, if you navigate to the end of a long page, and you use the indicator at the end of said page to navigate to the next page, you will end up at the bottom, rather than the top. 

## Reproduction
Navigated to [connecting solids tutorial page](https://docs.dagster.io/tutorial/intro-tutorial/connecting-solids), clicked the link at the bottom taking me to `testing solids and pipelines`, and ended up at the bottom of the next page.

## Additional Info about Your Environment
Using google chrome on a mac. This persists across screen sizes.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by pybokeh** [comment]
I also reported this [problem](https://github.com/dagster-io/dagster/issues/3939) a while back.  I can close my issue and we can consolidate on this one instead.

**Comment by nfx** [comment]
This behaviour is counter-intuitive...

**Comment by rexledesma** [comment]
Fixed with e50f721fd155df59698aa62b4827388865f0367b
