### ISSUE TITLE
Allow Dagit to be compatible with graphql-core 3.*

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#4095]
## Use Case
Currently, `graphql-ws` is pinned to `graphql-core 2.*`. This dependency prevents the user from installing other libraries that depend on `graphql-core 3.*` (e.g. `gql>3`).

## Ideas of Implementation
Remove `graphql-ws` or allow it to be compatible with `graphql-core 3.*`.

## Additional Info
`graphql-ws` is used to create a subscription server for graphql. See https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagit/dagit/subscription_server.py

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
related (if not spiritually the same) https://github.com/dagster-io/dagster/issues/4089
