### ISSUE TITLE
Specify a schedule/sensor in code as 'always on'.

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#4103]
## Use Case
When defining a schedule / sensor, sometimes you might want to specify that the schedule/sensor should always be on as long as it can be loaded in its repository (For example, if a user is programmatically defining a list of schedules based on a DSL, it's cumbersome to need to remember to turn any new ones on and remove any schedules that no longer exist) 

The piece that's not clear here is how the scheduler should know which repositories to consider.

**Comment by GKTheOne** [comment]
I'm still experimenting with dagster and it was very surprising to discover that I had to manually turn on a newly created sensor.
In my mind, schedules/sensors should be on by default.
Only if I'm having problems would I then manually turn them off myself.

**Comment by NavneetSajwan** [comment]
There should be feature that lets you choose whether to turn a schedule on or off at the time of defining the schedule.

**Comment by JonasR** [comment]
In case someone comes here after the introduction of declarative automation and wonders how to enable the sensor for that in code - I'm not sure if it's possible. However, you can easily define your own sensor with the `default_status` to make this work:

```python
from dagster import (
    asset,
    AutomationCondition,
    AutomationConditionSensorDefinition,
    DefaultSensorStatus,
    Definitions,
)


@asset
def asset_a() -> None:
    ...


@asset(deps=[asset_a], automation_condition=AutomationCondition.eager())
def asset_b() -> None:
    ...


defs = Definitions(
    assets=[asset_a, asset_b],
    sensors=[
        AutomationConditionSensorDefinition(
            name="CustomSensor",
            asset_selection=[asset_a, asset_b],
            default_status=DefaultSensorStatus.RUNNING,
        )
    ],
)

```
