### ISSUE TITLE
[Content Gap] in pyspark example, clarify what to do with non-spark outputs

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4107]
## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
@sryza Is this guy still valid? If so, could you add some detail about where you'd expect to see this? Is it here?: https://docs.dagster.io/integrations/spark

**Comment by sryza** [comment]
I think we can close this
