### ISSUE TITLE
Ability to change max_wait_time_sec in DatabricksJobRunner

### ISSUE THREAD

**Issue by andgineer** [dagster-io/dagster#4108]
## Use Case
The default value for the Databricks job runner is pretty small for our jobs.
They can run for a couple of days.

But I do not see how I could change that.
There is const `_DEFAULT_RUN_MAX_WAIT_TIME_SEC` but it is underscored so as I see it I should not change that.
And anyway how I can do that if I run dugster from command line and all his modules already loaded when my pipeline imported.

## Ideas of Implementation
Additional parameter `max_wait_time_sec` in `databricks_pyspark_step_launcher` resources.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
https://dagster.phacility.com/D7747?vs=36876&id=37502 adds a configuration option called `max_completion_wait_time_seconds` that allows configuring the wait time.  It will be included in today's 0.11.9 release.
