### ISSUE TITLE
[Documentation Feedback] Problem on /_apidocs/libraries/dagster_celery page

### ISSUE THREAD

**Issue by shaounak** [dagster-io/dagster#4115]
An unexpected error has occurred.

**Comment by yuhan** [comment]
@shaounak thanks for reporting. We've updated the link to https://docs.dagster.io/_apidocs/libraries/dagster-celery (changed the underscore to hyphen)

**Comment by sryza** [comment]
https://dagster.phacility.com/D8076 should fix

**Comment by rexledesma** [comment]
Closed with c9069c6d0706.
