### ISSUE TITLE
Run a schedule configuration via the playground

### ISSUE THREAD

**Issue by j-hulbert** [dagster-io/dagster#4118]
## Use Case
I would like to be able to run a non-partitioned schedule within the playground for testing or for doing an off-schedule run.
This is similar to capability that already exists to choose a partitioned scheduled in the preset drop down but extends it to schedules of cron_schedule type.
This lets you both test your schedule config within playground but also allows you to use that config as a starting point for a run.

## Ideas of Implementation
List the schedule as one of the preset choices in playground

## Additional Info
For schedules defined like this
```
@schedule(
    cron_schedule="0 2,14 * * *",
    pipeline_name="my_pipeline",
    execution_timezone="America/New_York",
    mode=prod_preset.mode,
)
```

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
@j-hulbert - if you could go to the schedule page, enter a date-time, and click "Launch", would that work for you?  Or do you want the opportunity to edit the full configuration before running the pipeline?

**Comment by j-hulbert** [comment]
I was hoping to be able to edit the configuration - I found that useful for tweaking/testing the schedule. The schedule is usually the best run_config starting point I have.

**Comment by sryza** [comment]
Thanks @j-hulbert .  That makes sense.  We're thinking about changes that would make this possible.

**Comment by sryza** [comment]
I believe it's now possible to achieve this by setting config when you define the job, so going to close.
