### ISSUE TITLE
[Documentation Feedback] Problem on /tutorial/advanced-tutorial/materializations page

### ISSUE THREAD

**Issue by BorePlusPlus** [dagster-io/dagster#4120]
Text in https://docs.dagster.io/tutorial/advanced-tutorial/materializations#custom-materializing-data-types talks about materializing in csv and pickle format, but example provided actually materializes in csv and json.

**Comment by sryza** [comment]
Hi @BorePlusPlus - thanks for reporting this.  We actually recently removed this section from the tutorial, because we no longer believe this is the best way for users to materialize data.  We recommend materializing data within the body of a solid or using an IOManager instead.
