### ISSUE TITLE
[Content Gap] "nothing" example in the tutorial

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4122]
## What content is missing

Many earlier users want to write pipelines where Dagster isn't responsible for passing data between solids.  These users are likely to think Dagster isn't relevant to them if we don't mention how to do so early on.

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
Closing - no longer relevant thanks to Tim's awesome new tutorial sections.
