### ISSUE TITLE
Resources configured to draw settings from env vars expect env vars to be defined even when unused in pipeline

### ISSUE THREAD

**Issue by ThePletch** [dagster-io/dagster#4123]
## Summary
When a resource is preconfigured using `@configured` to draw one of its config settings from an environment variable, a pipeline using a mode containing this resource will fail to execute if that environment variable is not defined, even if it does not use that resource. I would not expect the environment variable to be required unless the resource were being used in the pipeline.

## Reproduction
```python
@resource({
  "some_setting": StringSource
})
def foo(context):
  return {'x': context.resource_config['some_setting']}

@resource
def some_other_resource(_):
  return 'the real resource was the friends we made along the way'

@configured(foo)
def configured_foo(_):
  return {'some_setting': {'env': 'ENVVAR'}}

some_mode = ModeDefinition(
  name="a_mode",
  resource_defs={
    'problem': configured_foo,
    'not_problem': some_other_resource,
  }
)

@solid(required_resource_keys={'not_problem'})
def a_solid(context):
  context.log(context.resources.not_problem)

@pipeline(mode_defs=[some_mode])
def a_pipeline():
  a_solid()

execute_pipeline(a_pipeline, mode='a_mode')
```

Error output:
```
dagster.core.errors.DagsterInvalidConfigError: Error in config for resource problem
    Error 1: Post processing at path root:config:some_setting of original value {'env': 'ENVVAR'} failed:
dagster.config.errors.PostProcessingError: You have attempted to fetch the environment variable "ENVVAR" which is not set. In order for this execution to succeed it must be set in this environment.
```

## Additional Info about Your Environment
Issue is occurring in Dagster version 0.11.6.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
Was not able to reproduce this issue. In the latest version of Dagster, config schema is not applied to a resource if it is not used in the execution. I added a test with [this commit](https://github.com/dagster-io/dagster/commit/1e452e369867734ee20c626e9e1896511b7e9a2e) to confirm that this was the case.
