### ISSUE TITLE
[Docs Infra] include imports in docs code snippets

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4125]
## What content is missing

This will make them easier to copy/paste.

List of all the pages in the "Main Concepts" section that are missing imports:
* https://docs.dagster.io/concepts/solids-pipelines/solids
* https://docs.dagster.io/concepts/solids-pipelines/pipelines
* https://docs.dagster.io/concepts/solids-pipelines/composite-solids
* https://docs.dagster.io/concepts/solids-pipelines/solid-events
* https://docs.dagster.io/concepts/modes-resources
* https://docs.dagster.io/concepts/testing
* https://docs.dagster.io/concepts/types
* https://docs.dagster.io/concepts/io-management/unconnected-inputs
* https://docs.dagster.io/concepts/repositories-workspaces/repositories
* https://docs.dagster.io/concepts/logging/loggers
* https://docs.dagster.io/concepts/partitions-schedules-sensors/schedules
* https://docs.dagster.io/concepts/partitions-schedules-sensors/partitions
* https://docs.dagster.io/concepts/partitions-schedules-sensors/backfills
* https://docs.dagster.io/concepts/assets/asset-materializations

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
https://github.com/dagster-io/dagster/issues/3975

**Comment by yuhan** [comment]
This is more of a docs infra issue since we'll likely need to update snapshot script in order to make the imports show up while passing tests. will investigate options

**Comment by sryza** [comment]
@yuhan do you mind explaining what you mean a little more about needing to update the snapshot script?  In many cases, we do already include imports, e.g. on our Getting Started page: https://docs.dagster.io/getting-started#writing-a-pipeline, and those seem to pass tests fine.

**Comment by erinkcochran87** [comment]
I'm going to close this out in favor of implementing a style standard. As we touch these pages, we can update the code snippets and make sure any new content follows this pattern.
