### ISSUE TITLE
[Content Gap] Revisit how we introduce InputDefinitions on the solids concept page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4126]
## What content is missing

It's a little bit abrupt to introduce them and dagster types at the same time.

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
https://dagster.phacility.com/D7386
