### ISSUE TITLE
[Content Gap] resources concepts page is missing doc on how to reference a resource in a solid

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4135]
## What content is missing

We had this content pre-0.11.0.

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
This content has now been re-added https://github.com/dagster-io/dagster/commit/eb5a8cbab1481e2b1ddc2d920201d66cbb3eb710
