### ISSUE TITLE
[Content Gap] images are missing on the backfills concept page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4136]
## What content is missing

It looks like they got replaced with links.

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
fixed in 0.11.8 https://docs.dagster.io/0.11.8/concepts/partitions-schedules-sensors/backfills
