### ISSUE TITLE
Config nubs appear everywhere now

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#4138]
## Use Case
Now that config defaults to `Any` instead of `None` config nubs are on every solid. This reduces their utility considerably.

See: 
![Screen Shot 2021-05-04 at 9 41 47 AM](https://user-images.githubusercontent.com/28738937/117030688-1ec5ad80-acbd-11eb-99eb-233400eddb38.png)

## Ideas of Implementation

Delete them entirely or hide them when config is Any.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
If I understand correctly, the config nub up until the recent change has expressed "This solid is configurable".

If we were to delete / hide them when config is Any, the nub would now express "This solid has a restricted config schema".  Want to gut check before we make that change: is the nub a reasonable way to express that?  Might we want to alter its appearance in some way to better fit that?  (I don't have any particular opinion there, just wanted to pose the question.)

**Comment by schrockn** [comment]
Yeah this is a good point. I was overly prescriptive with the proposed implementation. I'll retract my proposed implementation, but I think underlying problem remains of it being noisy and not adding much value still exists. Maybe discuss with @bengotow when you meet with him this week?

**Comment by sryza** [comment]
@hellendag and I chatted and came to the conclusion that "hide them when config is Any" is a reasonable direction.  @bengotow let us know if you have other opinions.  Dish is planning to implement it.
