### ISSUE TITLE
Schedules & Sensors list not always updated when changing repository filters

### ISSUE THREAD

**Issue by mhpe** [dagster-io/dagster#4159]
## Summary
The list of schedules and sensors in dagit sometimes shows entries that belong to a previously used repository filter setting.

## Reproduction

- On a dagit instance with at least two repositories
- One of those repositories (A) should have a schedule and/or sensor
- In the repository filter settings, check both repositories A and B to be shown
- Then uncheck the repository A (that has schedules/sensors) in the filter settings, but keep repository B checked
- Schedules and sensors of repository A are still shown in the schedules & sensors list

## Environment
Version 0.11.4

**Comment by hellendag** [comment]
This was fixed in [0.11.5](https://github.com/dagster-io/dagster/releases/tag/0.11.5).
