### ISSUE TITLE
Unpin jinja2 / flask / werkzeug 

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#4167]
See: https://dagster.phacility.com/D7879 which added the pins

And user-reported issue here that demonstrates the symptoms of upgrading to flask2 (dagit unable to serve any requests): https://github.com/dagster-io/dagster/issues/4166

**Comment by ashwin153** [comment]
Any progress on this issue? The pinned Jinja2 version is stalling dependency updates in my monorepo.

**Comment by alangenfeld** [comment]
work is progressing on a starlette replacement for powering dagit, which can be seen here https://github.com/dagster-io/dagster/blob/master/python_modules/dagit/dagit/starlette.py

hoping to be able to cut over 0.14.0

**Comment by iswariyam** [comment]
I see that a PR has been merged for this issue. Would it be possible to change the pin on jinja2 version from "Jinja2<3.0" to "Jinja2>=3.0".
I am also having issues when updating dependencies in my mono-repo setup.
