### ISSUE TITLE
Unpin pendulum in dagster-airflow

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#4176]
## Summary

I saw a discussion in the Airflow slack about someone encountering a dependency conflict caused by our pin to 

"pendulum==1.4.4"

This may be more appropriately framed as making dagster-airflow airflow 2 compatible.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by westonplatter** [comment]
@schrockn I'm interested in using Airflow2 + Dagster, but saw this issue. Is this issue ready be worked on? I'm game to try unpinning and see if things just work. Any direction is appreciated.

**Comment by sryza** [comment]
The pin is now gone in master and will be absent in our next release!
