### ISSUE TITLE
(dagit) SQL preview goes out of the modal when the SQL statement is too long

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#4181]
## Summary

If I create a solid with a very long SQL statement, and try to preview the query in Dagit, the SQL goes out of the box and it's hard to read. Would it be possible to have a scrollbar or make the modal longer (like it is in "view configuration" in the run) to make it easier to read?

## Reproduction

Create a SQL solid with a long query

## Dagit UI/UX Issue Screenshots

Sorry I can't post a screenshot due to the SQL being private

## Additional Info about Your Environment

Dagit 0.11.9

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Will be resolved in https://dagster.phacility.com/D8212
