### ISSUE TITLE
missing run redirects to dagit main page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4187]
https://demo.elementl.dev/instance/runs?cursor=4b7eac20-82a5-4959-9193-541b76df1ec8&q= contains a link to a run that, when clicked, redirects to the dagit main page.

Here's the link that does not work: https://demo.elementl.dev/instance/runs/9075581e-9147-460e-8fbe-f798a1db2ab7.  The run ID is shown in the list as 9075581e.

**Comment by hellendag** [comment]
🤔 This doesn't repro for me. Does it repro reliably for you?

**Comment by sryza** [comment]
I caught up with Dish offline.  Weirdly, it reliably repros for me but never repros for him.

**Comment by hellendag** [comment]
Let's screenshare if you've got some time this week, and see if we can track this down.

**Comment by hellendag** [comment]
Looks like this has gone away.
