### ISSUE TITLE
Completed execution plan nodes look strange visually

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#419]
See how the long ones look half "shiny" for lack of a better term.

![screenshot 2018-12-15 09 51 05](https://user-images.githubusercontent.com/28738937/50045883-4c0f5380-004f-11e9-8d57-a905367aa0e5.png)

**Comment by bengotow** [comment]
Hah! Good catch - looks like the CSS breaks if they're more than 700px wide.

**Comment by mgasner** [comment]
resolved by #433 👏
