### ISSUE TITLE
[Documentation Feedback] Problem on /_apidocs/libraries/dagster_aws page

### ISSUE THREAD

**Issue by shaiamob** [dagster-io/dagster#4201]

**Comment by sryza** [comment]
Hi @shaiamob - what issue are you observing?

**Comment by shaiamob** [comment]
The doc page is not working... https://docs.dagster.io/_apidocs/libraries/dagster_aws
I though it was self explanatory... ;)

**Comment by jmsanders** [comment]
I believe the correct URL is https://docs.dagster.io/_apidocs/libraries/dagster-aws - we should check to see if there's anywhere in our docs that are linking to the wrong URL.

**Comment by sryza** [comment]
Ah - I missed the underscore.  @shaiamob - do you know how you ended up at the page with the underscore?

**Comment by shaiamob** [comment]
your main README.md :)
https://github.com/dagster-io/dagster

**Comment by shaiamob** [comment]
Another example
https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-aws/README.md

**Comment by sryza** [comment]
Thanks @shaiamob - here's a diff that should fix: https://dagster.phacility.com/D8076.

**Comment by rexledesma** [comment]
Closed with c9069c6d0706.
