### ISSUE TITLE
Orphaned runs associated to a backfill cannot be batch canceled 

### ISSUE THREAD

**Issue by MSigno** [dagster-io/dagster#4208]
in status>backfills the relevant backfill appears completed (progress=100%) and cannot be canceled, even though several runs are still in the queue. Incidentally a large (>90%) of runs are flagged as 'skipped' in spite of eventually running to completion. It appears as 'completed' means 'all runs have been spawned' as opposed to 'they have run'. Also that view is in disagreement with the one in the pipeline>partitions tab, which shows the backfill as still running.

**Comment by prha** [comment]
I think this was a UI issue that got resolved with `0.12.5`
