### ISSUE TITLE
Composite Dagster types (e.g. dagster.Optional) don't pass mypy

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#4209]
Steps to reproduce (tested on mypy 0.812):

```
from dagster import Optional

@solid
def exists(_, x: Optional[x]) -> bool:
    return x is not None
```

This fails mypy because `dagster.Optional` is an object, not a Python type.

It's attractive to just export the equivalent members of `typing`, so that `dagster.Optional is typing.Optional` and the internal implementations (`dagster.core.types.dagster_type.Optional` and friends) are just used in our implementation.

Unfortunately, this breaks when you try to use custom instances of `DagsterType` or its subclasses in concert with the `typing` types, e.g.:

```
from typing import Optional

from dagster import DagsterType

MyType = DagsterType(...)

@solid
def exists(_, x: Optional[MyType]) -> bool:
    return x is not None
```

This will fail with an opaque error like ```TypeError: Optional[t] requires a single type. Got <dagster.core.types.dagster_type.DagsterType object at 0x107c91bb0>.```

Note that users will also hit this if they attempt to mix and match the `typing` types (which do work when used to define input and output types with type annotations on solids) with their own custom types.

If we wanted to make this kind of UX possible, we would probably need to move to a metaclass-based implementation of `DagsterType` so that Dagster types were Python types, rather than Python objects.

We should consider what API we actually want to expose for custom types/input & output definition/type annotation. The present situation is pretty confusing.

@sryza lmk if there is anything I should add to this

**Comment by sryza** [comment]
In my opinion, we should accept that this is the case and take no action beyond modifying the API docs for these composite dagster types to discourage usage in type annotations.

It was always the case that usage this was an abuse of PEP 484 type annotations, and it's regrettable that in the past we recommended it.  I would be in favor of deprecating it.

However, I believe that, going forward, Dagster should _never_ encourage users to use DagsterTypes in type annotations, and we should message a clear distinction between DagsterTypes and Python types.  A DagsterType is not a Python type.

I know this is a fairly hardline stance.  If there was an easy way to make the code example above still work with more recent versions of mypy, I'd be in favor of it, but I don't think it's worth going to herculean efforts to support it, especially if it involves further fuzzying the border between DagsterTypes and Python types.

**Comment by mgasner** [comment]
Are you arguing that users shouldn't use type annotations to specify inputs/outputs at all -- they should always use the explicit `InputDefinition` and `OutputDefinition` APIs?

**Comment by sryza** [comment]
I'm arguing that, if a user has a DagsterType and wants to attach it to an input or output, they should use the explicit InputDefinition our OutputDefinition API.

**Comment by mgasner** [comment]
Do you think it's worth fixing the mypy failure on the non-`DagsterType` case:

```
from dagster import Optional

@solid
def exists(_, x: Optional[x]) -> bool:
    return x is not None
```

if this turns the `DagsterType` case into a hard failure?

**Comment by sryza** [comment]
Hmm yeah, that's a tough question. What do you think?

I think the case against would be: if you hold all your dependencies constant except for bumping a patch version on Dagster, you shouldn't encounter any breakages.  I suspect there are users out there who do not run static mypy checks and are happily annotating solid-decorated functions with `Optional[MyDagsterType]`.  While I don't think we should support that usage in the long term, I think it deserves a full deprecation cycle.

**Comment by yuhan** [comment]
Closing as we updated the docs. Please reopen if we need a more invasive/systematic approach
