### ISSUE TITLE
[Content Gap] example of writing a file to a filesystem as an Asset and then using it in the next step

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4211]
Source: https://dagster.slack.com/archives/C01U954MEER/p1621974671127000

## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
Could be an example of "Writing a file to a filesystem as an Asset" with some dagit screenshot on the asset concept page https://docs.dagster.io/concepts/assets/asset-materializations#asset-materializations

**Comment by erinkcochran87** [comment]
I think some of the new tutorial sections (specifically [parts 6](https://docs.dagster.io/tutorial/saving-your-data) and [7](https://docs.dagster.io/tutorial/managing-your-own-io)) address this - thoughts? @sryza

**Comment by sryza** [comment]
I think part 7 addresses this
