### ISSUE TITLE
Have a more coherent story when an IO manager key is specified on composite solid

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4214]
Right now, when an IO manager key is specified on a composite solid, we ignore it, since the output is technically mapped from an underlying solid. This is not well communicated.

We have two options:
1. Better error message around this, to let users know that this io manager key will not be used
2. Actually persist the output again, separately for the composite solid

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
cc @sryza @alangenfeld

**Comment by yuhan** [comment]
https://github.com/dagster-io/dagster/issues/4130

**Comment by yuhan** [comment]
https://github.com/dagster-io/dagster/issues/3656

**Comment by yuhan** [comment]
We are disallowing `io_manager_key` and `root_manager_key` to be set on composite solids' input/output definitions. Instead, we will respect the io managers set on the inner solids of composites.
