### ISSUE TITLE
API reference for loggers is missing content

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4215]
## Summary
https://docs.dagster.io/master/_apidocs/loggers#loggers
![Screen Shot 2021-05-26 at 12 17 38 PM](https://user-images.githubusercontent.com/17576880/119697359-1b39c800-be1e-11eb-97f9-4a5518bea992.png)

These headers should be either filled out, or removed

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
This was addressed - latest version of the docs:

![Screen Shot 2022-05-20 at 12 18 16 PM](https://user-images.githubusercontent.com/16615212/169570299-0dd9bac5-0275-4c26-b445-bf04c8fa0a0e.png)

Closing.
