### ISSUE TITLE
Schedules prominently display UTC and hide timezone-specific times behind click

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#4217]
## Summary

I would call this "something I thought was a bug" rather than a "bug." Curious about the product thinking here.

The issue is that the schedules page doesn't appear to respect timezones at first blush.

![Screen Shot 2021-05-26 at 2 25 57 PM](https://user-images.githubusercontent.com/28738937/119733506-7d022e00-be2e-11eb-8f29-4151e89e0902.png)

Only then did I realize that there was an icon and the timezone-specific time was there.

![Screen Shot 2021-05-26 at 2 26 03 PM](https://user-images.githubusercontent.com/28738937/119733538-8b504a00-be2e-11eb-8472-6bd14e1a44f5.png)

What was the reasoning behind that decision? I might be missing something.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
I'll change this so that it shows the execution timezone alongside the timestamp, which will hopefully alleviate confusion while still including the context of the schedule's relevant timezone. The tooltip will continue to show local time.
