### ISSUE TITLE
Solid selection chooses solids with same prefix

### ISSUE THREAD

**Issue by j-hulbert** [dagster-io/dagster#4219]
## Summary
When using the solid selection in the dagit playground if you have two solids that begin with the same prefix and try to select one of them dagit will try to run them both.

Example:
Pipeline has two solids 
 load_table_contact, load_table_contacthistory
solid selection: load_table_contact

Both solids are selected, even though would like to only run load_table_contact

If trailing comma is used 
solid_selection: load_table_contact,

Both solids are still selected, even though would like to only run load_table_contact

## Reproduction
1. Create a pipeline with two solids (load_contact, load_contacthistory)
2. In Dagit playground enter a solid selection of load_contact,
3. View the solid selected or execute the pipeline and both solids will run

## Additional Info about Your Environment
Dagster 0.11.9

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
@yuhan do you know whether this is the expected behavior?

**Comment by yuhan** [comment]
no i don't think so. @bengotow was looking at this issue in [#dagster-support](https://dagster.slack.com/archives/C01U954MEER/p1620748990048200?thread_ts=1620748393.047300&cid=C01U954MEER) the other day

**Comment by bengotow** [comment]
Hey gang, I think this is currently expected behavior but that is not good.

Given a graph of nodes `node => node_b`, if you type "node" into the search box you get both, and there is no way to just get the first one.

It'd be nice to move the current behavior to an explicit prefix marker, eg: `node*` gets you both, `node` gets you just the first element.  We can't do that though because we made `node*` mean "node and it's downstream graph".

I'm not sure that users ever really asked for the partial matching, so I think we should pick another character like `?` and use it to denote "any suffix" / "any prefix", and make the default behavior exact matching?

@braunjj does that seem ok? You probably have a lot more user context here than me...

**Comment by braunjj** [comment]
I think I prefer the % over the ? in this case. 

Would it be possible to instead allow a user wrap their query in " to signal a strict match? So typing `node` would return both _node_ and _node_b_ but typing `"node"` would only return _node_?

**Comment by yuhan** [comment]
Saw this got moved to In Progress. FYI: I'm making changes to the solid selection as well -- I'm removing solidSelection (the post-resolution version) from Dagit and just sending solidSelectionQuery to let the backend resolve it - as part of https://github.com/dagster-io/dagster/issues/5855 and the op selection backend improvements.

But I suspect this this may happen to the step selection query resolution too, which uses the same `filterByQuery` algorithm and I'm not touching. So guess still worth looking but not a super high priority imo.

**Comment by bengotow** [comment]
Hey Yuhan! Hmm - yeah I think this is used in a lot of places in Dagit just to filter / select things for display and we still want to fix this for those. That seems like a good change though. I guess the alternative would be to re-fetch the graph just before we send the launch run event, but that'd be pretty slow.

I'm not sure about having two implementations of the `items + filter string => filtered items` function but I guess it was only a matter of time before we needed a python one too. I guess we just need to make sure it yields the same results 😬

**Comment by yuhan** [comment]
Right, the alternative would be slower - probably we still need to keep two implementations (one in js, one in python) for perf reason, which I don't love but may be necessary eventually.
