### ISSUE TITLE
[memoization] Missing version error messages are not helpful

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4225]
## Summary
---
If you are missing a version on something, then we just throw CheckErrors. We should more readily point users towards where versions need to be provided.
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by skorski** [comment]
This seems very similar to https://github.com/dagster-io/dagster/issues/4235

**Comment by dpeng817** [comment]
@skorski  I think it's related but not the same - even if we didn't require users to provide versions, in cases where they did opt-in to providing versions we should have better error messaging around that.

**Comment by skorski** [comment]
good point.

**Comment by sryza** [comment]
Closing because these memoization code paths are now deprecated in favor of asset versioning, which has pretty good messaging
