### ISSUE TITLE
Dagster Helm deployment is not coupled with image tag version

### ISSUE THREAD

**Issue by ibegleris** [dagster-io/dagster#4229]
## Summary

In the docs, it's mentioned that by passing `--version` we can install a specific chart version (https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm#versioning).
Also in the Helm installation docs, it's stated that Dagster Python version and Helm Chart version have a 1:1 correspondence.
However, when looking at the `deployment-daggit.yaml` that is created, the latest is always the tag of the Dagster related image unless it is specified in the `values.yaml` file.

## Reproduction
`helm upgrade --install --dry-run dagster dagster/dagster --version 0.11.0`

Will produce `<...>-deployment.yaml` scripts with `latest` tag instead of the specified version. 
For example, `image: "docker.io/dagster/dagster-celery-k8s:latest"`

## Additional Info about Your Environment
To fix this I recommend two ways:
1. the image definition  of Dagster related images would need to be replaced with:
`image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.image.tag }}"`
and to remove `image.tag` from the values.yaml file for all Dagster related images.
2. A helper definition that would calculate the dagster version and then that would be used in the image tags. 

I believe both ways allow the overwrite of `.Chart.Version` or ` .Chart.AppVersion` in the `values.yaml` but this way the default is what is stated in the Chart.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
This should be resolved in the 0.11.13 release of our Helm chart!
