### ISSUE TITLE
Remove intermediate storage in documentation

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#4232]
Good places for documentation that intermediate and system storages are deprecated (with links to io_managers):

- python_modules/dagster/dagster/core/storage/intermediate_storage.py
- python_modules/libraries/dagster-aws/dagster_aws/s3/system_storage.py (and gcs and azure)

**Comment by yuhan** [comment]
#4433 removed most of the mentioning from the docs but the remaining piece requires code changes, so tracking in https://github.com/dagster-io/dagster/issues/4452
