### ISSUE TITLE
[Content Gap] Suggested corrections to Dagster K8s deployment with a working example on Mac

### ISSUE THREAD

**Issue by mcallaway** [dagster-io/dagster#4234]
## What content is missing

Working through the helm deployment here 
https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm I came across some contradictions and lack of clarity. Below I provide the notes of my experience in hopes to flesh out some details in the documentation, leading to a fully working example.

In my case, I was working with kubernetes via Docker for Mac. Enable Kubernetes.

Note the docs refer to `values.yaml`. Once you get set up via the steps below, you can produce a starting file using:

    helm show values dagster/dagster > values.yaml

I thought it was valuable to use a separate context:

    kubectl config set-context dagster --namespace dagster --cluster docker-desktop --user=docker-desktop
    kubectl config use-context dagster

It will also be useful to refer to these commands:

    kubectl get pods
    DAGIT_POD=$( kubectl get pods | awk '/dagster-dagit/{print $1}' )
    # Start a shell in the dagit pod
    kubectl exec --stdin --tty $DAGIT_POD -- /bin/bash
    # Get debug data for $RUN_ID
    kubectl exec $DAGIT_POD -- dagster debug export $RUN_ID debug_info.gzip
    # Get a list of recently failed runs
    kubectl exec $DAGIT_POD -- dagster debug export fakename fakename.gzip
    # Get debug output of a failed run
    kubectl exec $DAGIT_POD -- dagster debug export 360d7882-e631-4ac7-8632-43c75cb4d426 debug.gzip
    # Extract the debug.gzip from the pod
    kubectl cp $DAGIT_POD:debug.gzip debug.gzip
    # List config maps
    kubectl get configmap # Make note of the "user-deployments" configmap
    kubectl get configmap dagster-dagster-user-deployments-$NAME

Note that after the setup, the demo pipeline code lives here:

https://github.com/dagster-io/dagster/blob/master/examples/deploy_k8s/example_project/example_repo/repo.py#L28-L59

It will not have supplied a "run configuration" which you will note in the Dagit UI by the fact that the unconfigured `io_manager` will appear red in color. Following the onscreen prompts will lead you to produce a default configuration that looks like this:

```
resources:
  io_manager:
    config:
      s3_bucket: ""
```

You will Launch Execution with this config probably with "Mode" set to "default". This run will fail, trying to use an unconfigured s3 IO manager.

Changing the Mode to "test" will use the in memory IO manager, and that will work.

You can use `minio` to supply an S3 endpoint such that the default mode will work and S3 functions. There are steps below to install minio and create an test bucket so that the s3 io manager config works.

Note that the Dagster documentation suggests that credentials can be supplied in `env`, but this is not true.  Supplying AWS credentials is done via a K8s Config Map, which has an example below.

Complete setup steps are included below, again only for Mac.

```
brew install minio/stable/minio # server
brew install minio/stable/mc    # client
mkdir $HOME/miniodata           # Prepare a directory for data
minio server $HOME/miniodata    # start a server with default user/pass and no TLS
mc --insecure alias set minio http://localhost:9000 minioadmin minioadmin
# See it work
mc ls minio
date > date1.txt # create a sample file
mc cp date1.txt minio://testbucket/date1.txt

# Prep the AWS environment
cat >> ~/.aws/credentials <<EOF
# Add an AWS_PROFILE for minio
[minio]
aws_access_key_id = minioadmin
aws_secret_access_key = minioadmin
EOF
export AWS_PROFILE=minio
# See the aws cli work
aws --endpoint-url http://localhost:9000 s3 mb s3://test-bucket
aws --endpoint-url http://localhost:9000 s3 cp date1.txt s3://test-bucket/

# Use helm to install dagster into k8s
brew install helm
helm repo add dagster https://dagster-io.github.io/helm
# Make note of the default configuration
helm show values dagster/dagster > values.yaml.orig
# Create local values
cat > values.yaml <<EOF
dagster-user-deployments:
  enabled: true
  deployments:
    # Choose your own "name"
    - name: "k8s-dagster"
      image:
        # This is the Dagster code example repo
        repository: "docker.io/dagster/user-code-example"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "-f"
        - "/example_project/example_repo/repo.py"
      port: 3030
      envConfigMaps:
         # This ConfigMap is made below in extraManifests
         - name: aws-config-map

extraManifests:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: aws-config-map
      # Note the use of the namespace we made by hand
      namespace: dagster
    data:
      # This is insecure, should really use Secrets
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envConfigMaps:
        - name: aws-config-map
EOF

helm upgrade --namespace dagster --install dagster dagster/dagster -f ./values.yaml
export DAGIT_POD_NAME=$(kubectl get pods --namespace dagster -l "app.kubernetes.io/name=dagster,app.kubernetes.io/instance=dagster,component=dagit" -o jsonpath="{.items[0].metadata.name}")
# Watch a few minutes for pods to come online
kubectl get pods --namespace dagster
# When all pods are up, forward the port
kubectl --namespace dagster port-forward $DAGIT_POD_NAME 8080:80
open http://127.0.0.1:8080

# Go to the playground and prepare a configuration
resources:
  io_manager:
    config:
      s3_bucket: test-bucket
  s3:
    config:
      # This use of host.docker.internal is unique to Mac
      endpoint_url: http://host.docker.internal:9000
      region_name: us-east-1
solids:
  multiply_the_word:
    config:
      factor: 0
    inputs:
      word: ''
```

**Comment by sidkmenon** [comment]
Should be solved with https://github.com/dagster-io/dagster/commit/f351585defaeb43d9b6a99098431a3f513f01efd. Thanks so much for raising this issue @mcallaway!
