### ISSUE TITLE
[memoization] make it so that users don't have to provide definition-level versions

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4235]
## Use Case
---

It's super onerous that for someone to get started with memoization, they need to provide definition-level versions for everything. It's very easy to forget something, and the error messages are not intuitive. We should not require this in order for memoization to work properly.

#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
@skorski  I think the main question is whether we want to buy into just utilizing the function code as the definition-level version. Because, technically, imports, changes to other pieces of module, etc, could affect the result as well, and thus should (maybe?) affect the version. It should be noted that the current solution of hashing a file in the memoization docs does not solve this problem either. cc @sryza

**Comment by skorski** [comment]
I agree there are edge cases where the version should be incremented on other things, such as package versions.  This does seem like it would solve the vast majority of use cases and help with the adoption.  This would save a lot of frustration as we iterate over steps in jupyter notebooks.

Is there something else I could add that would make this better?

I would always take the users version over a simple hash.

**Comment by dpeng817** [comment]
@skorski One other possible approach would be to just not require users to provide code versions for their solids/resources. Then, the only buy-in a user would need would be to provide the memoization tag to their pipeline. The inspect/hash approach definitely still has value in that world, perhaps as a replacement for the file hashing scheme currently supplied in the docs example.

**Comment by skorski** [comment]
I do like the version tag.  I'm thinking about how I would use this during development.  I'd likely have a notebook running with solids that I'm iterating over.  Having the system automatically pick up those types of code changes, and thus re-execute a step would be extremely handy.

**Comment by jwebster42** [comment]
Any more decisions on this once?  I'm really struggling with the current solution in the docs regarding the file level hash.  I implemented it so that we could make use of memoization, but because our library is designed so that the solids are basically wrapper functions (easier to test), this only catches changes to the wrapper calls, not the underlying functions.

**Comment by dpeng817** [comment]
Hey @jwebster42 ! We have a pretty big memoization revamp coming up for 0.13.0. We're going to change the solution in the docs away from using the file-level hash, into using a hash of the decorated function. For most cases, this won't work until the revamp, but it actually should already work in your use case (since you're using wrapper calls):

```python
import inspect

def thing_to_be_wrapped():
    pass

source_code = inspect.get_source(thing_to_be_wrapped)

@solid(version=source_code)
def solid_wraps_thing():
    thing_to_be_wrapped()
```

**Comment by jwebster42** [comment]
@dpeng817 That's awesome!  I look forward to that!  I was playing around on my own with something like version = hash_of_solid_wrapper + hash_of_thing_to_be_wrapped. Thanks!

**Comment by sryza** [comment]
> our library is designed so that the solids are basically wrapper functions (easier to test)

@jwebster42 have you had a chance to look at the new direct invocation APIs? You can now invoke a solid like it's a regular function.

**Comment by dpeng817** [comment]
The VersionStrategy APIs resolve this
