### ISSUE TITLE
ModuleNotFoundError: No module named 'dagster_mysql.event_log_storage'

### ISSUE THREAD

**Issue by jragbeer** [dagster-io/dagster#4238]
## Summary

I'm trying to use MySQL as the backend SQL database for my dagster installation. I've installed the extension dagster-mysql but it looks like a module is missing. Taking the event_storage setting out of the yaml makes the `dagster-daemon run` run correctly

My dagster.yaml file looks like:

`scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler
  
run_storage:
  module: dagster_mysql.run_storage
  class: MySQLRunStorage
  config:
      mysql_db:
        username: root
        password: XXX
        hostname: 127.0.0.1
        db_name: run_storage
        port: 3306
    
schedule_storage:
  module: dagster_mysql.schedule_storage
  class: MySQLScheduleStorage
  config:
      mysql_db:
        username: root
        password: XXX
        hostname: 127.0.0.1
        db_name: schedule_storage
        port: 3306

event_log_storage:
  module: dagster_mysql.event_log_storage
  class: MySQLEventLogStorage
  config:
      mysql_db:
        username: root
        password: XXX
        hostname: 127.0.0.1
        db_name: schedule_storage
        port: 3306`

## Reproduction

![image](https://user-images.githubusercontent.com/30732548/120263612-0b7d1200-c26a-11eb-9162-641fad8eb4ae.png)
![image](https://user-images.githubusercontent.com/30732548/120263238-4763a780-c269-11eb-93b1-3c79c7cdc8c8.png)

## Additional Info about Your Environment

ubuntu 20.04
python3.8
dagster 0.11.11

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @jragbeer - the module to use is actually dagster_mysql.event_log, not dagster_mysql.event_log_storage (although that's inconsistent with the other two)

**Comment by jragbeer** [comment]
Thanks for the response! @gibsondan 
Perhaps the documentation can be updated for MySQL?
https://docs.dagster.io/deployment/dagster-instance#event-log-storage

**Comment by gibsondan** [comment]
Ah definitely, will fix right away. Thanks for the report!
