### ISSUE TITLE
long partition names get cut off

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4251]
![image](https://user-images.githubusercontent.com/654855/120724242-3d6bbf80-c488-11eb-97ff-4283047a7e35.png)

**Comment by hellendag** [comment]
I believe that if you hover over partition names that are cut off, it should show a tooltip with the full text: https://dagster.phacility.com/D7628. Is this not working?

**Comment by sryza** [comment]
Didn't notice! Still kind of ugly, but I don't have better ideas, so going to close.
