### ISSUE TITLE
Dagster UI always shows stdout/stderr for the first step in pipeline

### ISSUE THREAD

**Issue by atemmo** [dagster-io/dagster#4254]
## Summary

I am running multistep pipelines where each step produces stdout. Logs are saved correctly (tested using LocalComputeLogManager and S3ComputeLogManager) - separate files are created for each step with full output. When viewing logs in Dagster UI under pipeline runs selecting output for different steps always defaults to the first step (for both local and S3 logs). Logging output fully present.

## Reproduction

from dagster import solid, pipeline

@solid
def step1(context):
    context.log.info('step1 log output')
    print('step1 print output')

@solid
def step2(context):
    context.log.info('step2 log output')
    print('step2 print output')

@pipeline
def test_pipeline():
    step1()
    step2()

dagster.yaml configuration 

compute_logs:
  module: dagster.core.storage.local_compute_log_manager
  class: LocalComputeLogManager
  config:
    base_dir:
      env: DAGSTER_HOME

or

compute_logs:
  module: dagster_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    bucket: "my-bucket"
    prefix: "apps/windstack/compute_logs"

## Dagit UI/UX Issue Screenshots

<img width="848" alt="image" src="https://user-images.githubusercontent.com/43237684/120865824-0a602380-c58f-11eb-9161-357c1fd83fdb.png">

<img width="825" alt="image" src="https://user-images.githubusercontent.com/43237684/120865283-07b0fe80-c58e-11eb-8905-f6f66c54df8f.png">

selecting any step in the dropdown always shows step1 output for both stdout and stderr. Logging output is fully present, clicking on "View stdout / stderr" in logs also always shows step1 output.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/43237684/120865479-68403b80-c58e-11eb-9ff5-0959c04b29f8.png">

## Additional Info about Your Environment

Dagster, dagit, dagster-aws 0.11.11. UI tested in Safari 14.1, Firefox 89.0, Chromium Version 90.0.4430.212 (Official Build, ungoogled-chromium) (x86_64).

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sspaeti** [comment]
I have the same issue. 

To work around, I found a trick if you click above on the graph instead, it seems to work:
![image](https://user-images.githubusercontent.com/689199/121038365-87b6ae80-c7b0-11eb-9b0f-1dbe0fb3c37f.png)

**Comment by sryza** [comment]
Thanks for reporting this @atemmo and @sspaeti.  This seems like a serious bug.  @hellendag is looking into it.
