### ISSUE TITLE
Solid Invocation: Requires values for items in solid_config that contain default values

### ISSUE THREAD

**Issue by Jiafi** [dagster-io/dagster#4259]
## Summary

When using invocation of a solid, it fails to get the key of the `context.solid_config[{key}]`.  In the solid definition, i specify a default value for the key.  The invocation should use the default value and not require the key/value pair to be specified.  

## Reproduction

```
@solid(config_schema={"foo":Field(int, default_value=1)})
def foo_bar(context):
    foo = context.solid_config["foo"]
context = build_solid_context()
foo_bar(context)

```

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
This has been fixed with the suite of changes to direct solid invocation.
