### ISSUE TITLE
Allow users of `dagster run delete` to programatically delete runs via --no-interactive flag

### ISSUE THREAD

**Issue by abelsonlive** [dagster-io/dagster#4268]
## Use Case

I run dagster in a single container with a small Postgres store (< 8 GB). In order to ensure that my database doesn't get too large, I'd like to run a scheduled dagster pipeline to delete any runs older than one week. My initial approach was to query the run database and return a list of run ids and pass those to `dagster run delete` However, the `dagster run delete` command enforces requires input: https://github.com/dagster-io/dagster/blob/7757caf977eb5bb7668f95a7bdb3d050d83c5e32/python_modules/dagster/dagster/cli/run.py#L31 

It would be great if there were an optional `--no-interactive` or `--yes` flag  which would to allow me to script the execution of `dagster run delete`.

## Ideas of Implementation

Add a `click.argument`.

## Additional Info

Happy to try this myself!

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
If you are doing this in a dagster pipeline from python, does invoking the instance method that the cli uses `     instance.delete_run(run_id)` not work better for your specific use case?

**Comment by rexledesma** [comment]
We added functionality for this `--force` flag on the cli, but like @alangenfeld said, since you have access to the instance in a solid, we can do this without the cli.

Something of the flavor of the code snippet. See https://docs.dagster.io/concepts/solids-pipelines/solids for more details on the solid context!
```python
@solid
def delete_runs(context: SolidExecutionContext):
    runs = context.instance.get_runs(...)

    for run in runs:
        context.instance.delete_run(run.run_id)   
```
