### ISSUE TITLE
MultiprocessingExecutionManager chokes on some pipelines

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#428]
Steps to reproduce:

1. Clone the repo at https://github.com/superconductive/sun_basket_forecasting
2. Install the dependencies (`pip install -r sun_basket_forecasting/pipeline_v2/requirements.txt`)
3. Run dagit from the pipeline_v2 directory
4. From the execution pane, run the `create_wine_training_data` pipeline with the config yaml at pipeline_v2/wine_local_create_training_data.yml
5. Execution will reliably choke at `generate_momentum_plots.transform` with an error like  `Exception: Pipeline execution process for 1427d8f2-2026-475f-a56a-a9fa76e3cba9 unexpectedly exited`

**Comment by freiksenet** [comment]
Is that windows only? It works for me on Linux.

**Comment by freiksenet** [comment]
Also I guess it wouldn't work at all on Windows, cause I tried 'spawn' multiprocessing. I wonder what's the failure.

**Comment by schrockn** [comment]
just repro'ed this on mac

**Comment by schrockn** [comment]
It's some matplotlib bullshit.

I pushed a branch that shows the fix

https://github.com/superconductive/sun_basket_forecasting/commit/3472a22eb81b35d7619d5d4b456f773330681e74

magical incantation was found here

https://stackoverflow.com/questions/44030430/pyplot-crashing-on-plt-figure-in-macos

**Comment by mgasner** [comment]
ok, moving the broader issue to #441

**Comment by mgasner** [comment]
Moved the Windows issue to #442
