### ISSUE TITLE
Dagster on EC2 is getting out of memory

### ISSUE THREAD

**Issue by KIRNESH** [dagster-io/dagster#4280]
I am trying to run dagit with workspace.yaml file.
Something like this : `dagit -f workspace.yaml -h 0.0.0.0`

Trying to run dagster as a service. Also set DAFSTER_HOME

But after some time and execution, the instance is getting out of memory or should i say server just gets hanged. I am assuming it is due to out of memory issues.

I am running on 2vcpus with 4 GB RAM.

Is there something I am doing wrong.
Also it would be helpful, if you can specify if there is any memory requirements for running dagit along with dagster-daemon.

**Comment by mgasner** [comment]
Do you have any logs from the server that might help debug this / alternatively, do you have any metrics from EC2 that show the memory getting exhausted? Does upping the amount of memory provided to the instance change anything?

**Comment by KIRNESH** [comment]
Hey sorry guys, Just saw, it is increasing the memory because dagster is creating log files in a directory which is open in vscode and hence on server vscode is taking too much memory to process the log files at real time. It is getting heavy with those heavy files. 

Thanks for responding quickly. Closing the issue for now. 

However, I do think dagster should run on atleast 8 GB ram for efficient usage. Let me know your suggestiong

Btw dagster is a great tool. It will be helpful if you can write more blogs for solving the intricacies in it.
