### ISSUE TITLE
[Documentation Feedback] Problem on /concepts/io-management/io-managers page

### ISSUE THREAD

**Issue by nfx** [dagster-io/dagster#4284]
scroll to bottom of any page. Click on menu in the left - find yourself scrolled to bottom on that page as well. Confusing. people expect scroll to top :)

**Comment by pybokeh** [comment]
Perhaps duplicate to this issue https://github.com/dagster-io/dagster/issues/4091

**Comment by nfx** [comment]
@pybokeh it is!
