### ISSUE TITLE
[Content Gap] schedule should_execute examples should use context.scheduled_execution_time, not current time

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#4291]
Example https://docs.dagster.io/tutorial/advanced-tutorial/scheduling#schedule-filters

**Comment by erinkcochran87** [comment]
It looks like this has already been addressed - all examples in the Schedules docs use `context.scheduled_execution_time`: https://docs.dagster.io/concepts/partitions-schedules-sensors/schedules

@gibsondan Can this be closed? Or are there other places where this should be addressed?
