### ISSUE TITLE
Non-functional "Refresh Config" button on hackernews repo, I think because I didn't have a partition selected

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#4296]
See screenshot - The "Refresh Config" button did nothing. Selecting a partition refreshed the playground and made the button go away.

<img width="957" alt="refreshconfig" src="https://user-images.githubusercontent.com/8451211/122251132-dd194c80-ce8f-11eb-97ca-de2d821987ae.png">

**Comment by sryza** [comment]
Do you recall how you got into a state with the config filled out but no partition selected?
