### ISSUE TITLE
User configurable TTL

### ISSUE THREAD

**Issue by Oliver-Sellwood** [dagster-io/dagster#4310]
## Summary

Currently the job TTL is hardcoded to 24h. With a high volume of pipeline runs this can result in a large build up of completed job pods. This activates [this k8s bug](https://github.com/kubernetes/kubernetes/issues/95492) causing a total system failure as Dagster can no longer schedule new job pods.

## Reproduction

1. Launch a large number of Dagster runs (~50k) (probably best to use the queued run coordinator)
2. Observe tail off in pod creation rate when the k8s control plane is overloaded.

One potential solution to this is to specify ttl in the pipline tags i.e

```
tags = {
    'dagster-k8s/config': {
        "job_spec_config": {
            "ttl_seconds_after_finished": 5
        }
    }
}
```

Currently applying this setting results in 

```
Caught an error for run 7f8e316c-75ff-4164-9f66-8d6646de5bbd while removing it from the queue. Marking the run as failed and dropping it from the queue: TypeError: kubernetes.client.models.v1_job_spec.V1JobSpec() got multiple values for keyword argument 'ttl_seconds_after_finished'

```

## Images
This graph shows number of jobs in the system over time. As can be seen, when the number of jobs hits 12k the rate of pod creation drops dramatically.

The exact number of pods will depend on your environment, 12k seems to be the limit on an EKS cluster.

![image](https://user-images.githubusercontent.com/82496461/123181625-014cdd00-d4d1-11eb-9e92-71108f13f1b0.png)
x-axis time
y-axis number of dagster jobs in the cluster

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
This has been resolved by https://github.com/dagster-io/dagster/commit/3ae6cfd90b23e6d81d4d05e3740d9a15622c5083. Docs are found here: https://docs.dagster.io/deployment/guides/kubernetes/customizing-your-deployment#kubernetes-job-and-pod-ttl-management.
