### ISSUE TITLE
[Content Gap] example of IOManager that uses resource_config

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4313]
## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
will belong to https://docs.dagster.io/concepts/io-management/io-managers#examples

**Comment by erinkcochran87** [comment]
Is this still relevant, given the move to Pythonic resources/config?

**Comment by yuhan** [comment]
This should have been addressed by pythonic resources docs
