### ISSUE TITLE
dagit version 0.11.14: "Copy URL" button is not working

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#4315]
In dagit, at the gantt chart page, the "Copy URL" button doesn't seem to do anything.

Chrome browser version 91

Here's what outputs to the Chrome developer tools console when I click on the button:
```
react-dom.production.min.js:101 Uncaught TypeError: Cannot read property 'writeText' of undefined
    at onClick (LogsToolbar.tsx:347)
    at Object.je (react-dom.production.min.js:52)
    at Qe (react-dom.production.min.js:52)
    at react-dom.production.min.js:53
    at Er (react-dom.production.min.js:100)
    at Tr (react-dom.production.min.js:101)
    at react-dom.production.min.js:113
    at Ie (react-dom.production.min.js:292)
    at react-dom.production.min.js:50
    at kr (react-dom.production.min.js:105)
```

**Comment by hellendag** [comment]
HI @pybokeh, are you serving dagit over http, https, or localhost?

The [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) is used for this button, but is unavailable outside of a secure context (https or localhost). I'll make a change to disable or remove the button in this circumstance, but it'd be helpful to narrow down whether this is the reason you're seeing the issue. Thanks!

**Comment by hellendag** [comment]
I added fallback behavior to enable copy-to-clipboard in cases where the Clipboard API is unavailable.

**Comment by pybokeh** [comment]
@hellendag Sorry I was away on vacation.  It was served with http.

**Comment by hellendag** [comment]
@pybokeh Thanks, that's helpful to know! 0.11.16 will have a fix.
