### ISSUE TITLE
[Content Gap] api doc for create_databricks_job_solid should describe configuration options

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4322]
## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Resolved with https://github.com/dagster-io/dagster/issues/12492.
