### ISSUE TITLE
run_tags table is not created by instace migrate MySQL

### ISSUE THREAD

**Issue by jmaclachlanCapture** [dagster-io/dagster#4324]
## Summary

With a blank MySQL database, running `dagster instance migrate` creates all tables except run_tags.

## Reproduction

Create a blank setup with version 0.11.14, run `dagster instance migrate`, run_tags table is not created.

## Additional Info about Your Environment

Debian Buster x86_64 docker container with Python 3.7.
alembic                1.6.5
dagit                  0.11.14
dagster                0.11.14
dagster-aws            0.11.14
dagster-cron           0.11.14
dagster-docker         0.11.14
dagster-github         0.11.14
dagster-graphql        0.11.14
dagster-mysql          0.11.14
dagster-pandas         0.11.14
dagster-shell          0.11.14
dagster-ssh            0.11.14
mysql-connector-python 8.0.25
PyMySQL                1.0.2
SQLAlchemy             1.4.19

## Workaround

By dropping the the runs table and rerunning the instance migrate command the run_tags table is created.  Potentially related to the _init_ and _init_db function changes, the original thought was, runs was created first for the fk, but the test was for that table, blocking creation of the child table.

The run_tags table is created in v0.10.9.

Relevant diff between the versions that lead to the workaround:

```
$git branch
* (HEAD detached at 0.11.14)

$git diff -u 0.10.9 sql_run_storage.py

diff --git a/python_modules/libraries/dagster-mysql/dagster_mysql/run_storage/run_storage.py b/python_modules/libraries/dagster-mysql/dagster_mysql/run_storage/run_storage.py
index e7adad996..b1cf1bff8 100644
--- a/python_modules/libraries/dagster-mysql/dagster_mysql/run_storage/run_storage.py
+++ b/python_modules/libraries/dagster-mysql/dagster_mysql/run_storage/run_storage.py
@@ -5,9 +5,10 @@
 from dagster.core.storage.sql import create_engine, run_alembic_upgrade
 from dagster.serdes import ConfigurableClass, ConfigurableClassData, serialize_dagster_namedtuple
 from dagster.utils import utc_datetime_from_timestamp
-from dagster.utils.backcompat import experimental
+from dagster.utils.backcompat import experimental_class_warning
 
 from ..utils import (
+    MYSQL_POOL_RECYCLE,
     create_mysql_connection,
     mysql_alembic_config,
     mysql_config,
@@ -24,20 +25,19 @@ class MySQLRunStorage(SqlRunStorage, ConfigurableClass):
     ``dagit`` and ``dagster-graphql`` load, based on the values in the ``dagster.yaml`` file in
     ``$DAGSTER_HOME``. Configuration of this class should be done by setting values in that file.
 
-    To use MySQL for run storage, you can add a block such as the following to your
-    ``dagster.yaml``:
 
-    .. literalinclude:: ../../../../../examples/docs_snippets/docs_snippets/deploying/dagster-mysql.yaml
+    .. literalinclude:: ../../../../../../examples/docs_snippets/docs_snippets/deploying/dagster-mysql.yaml
        :caption: dagster.yaml
-       :lines: 1-10
+       :start-after: start_marker_runs
+       :end-before: end_marker_runs
        :language: YAML
 
     Note that the fields in this config are :py:class:`~dagster.StringSource` and
     :py:class:`~dagster.IntSource` and can be configured from environment variables.
     """
 
-    @experimental
     def __init__(self, mysql_url, inst_data=None):
+        experimental_class_warning("MySQLRunStorage")
         self._inst_data = check.opt_inst_param(inst_data, "inst_data", ConfigurableClassData)
         self.mysql_url = mysql_url
 
@@ -51,17 +51,29 @@ def __init__(self, mysql_url, inst_data=None):
         self._index_migration_cache = {}
         table_names = retry_mysql_connection_fn(db.inspect(self._engine).get_table_names)
 
+        # Stamp and create tables if the main table does not exist (we can't check alembic
+        # revision because alembic config may be shared with other storage classes)
         if "runs" not in table_names:
-            with self.connect() as conn:
-                alembic_config = mysql_alembic_config(__file__)
-                retry_mysql_creation_fn(lambda: RunStorageSqlMetadata.create_all(conn))
-                stamp_alembic_rev(alembic_config, conn)
+            retry_mysql_creation_fn(self._init_db)
             self.build_missing_indexes()
 
+        super().__init__()
+
+    def _init_db(self):
+        with self.connect() as conn:
+            with conn.begin():
+                RunStorageSqlMetadata.create_all(conn)
+                stamp_alembic_rev(mysql_alembic_config(__file__), conn)
+
     def optimize_for_dagit(self, statement_timeout):
         # When running in dagit, hold 1 open connection
         # https://github.com/dagster-io/dagster/issues/3719
-        self._engine = create_engine(self.mysql_url, isolation_level="AUTOCOMMIT", pool_size=1)
+        self._engine = create_engine(
+            self.mysql_url,
+            isolation_level="AUTOCOMMIT",
+            pool_size=1,
+            pool_recycle=MYSQL_POOL_RECYCLE,
+        )
 
     @property
     def inst_data(self):
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by jmaclachlanCapture** [comment]
Unfortunately there are no errors output during the dagster instance migrate command, you are correct there is no need to run the migrate manually, dagit does so at init and fails to create the run_tags table.

`mysql> show tables;
+-------------------+
| Tables_in_dagster |
+-------------------+
| alembic_version   |
| asset_keys        |
| bulk_actions      |
| daemon_heartbeats |
| event_logs        |
| job_ticks         |
| jobs              |
| run_tags          |
| runs              |
| secondary_indexes |
| snapshots         |
+-------------------+
11 rows in set (0.00 sec)
mysql> drop database dagster; create database dagster; use dagster;
mysql> show tables;
+-------------------+
| Tables_in_dagster |
+-------------------+
| alembic_version   |
| asset_keys        |
| bulk_actions      |
| daemon_heartbeats |
| event_logs        |
| job_ticks         |
| jobs              |
| runs              |
| secondary_indexes |
| snapshots         |
+-------------------+
10 rows in set (0.00 sec)
`


Output:
` dagster instance migrate                                                                                                                                                                           
$DAGSTER_HOME: /opt/dagster/dagster_home/

/usr/local/lib/python3.7/site-packages/dagster_mysql/run_storage/run_storage.py:88: ExperimentalWarning: "MySQLRunStorage" is an experimental class. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.
filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  return MySQLRunStorage(inst_data=inst_data, mysql_url=mysql_url_from_config(config_value))
/usr/local/lib/python3.7/site-packages/dagster_mysql/event_log/event_log.py:105: ExperimentalWarning: "MySQLEventLogStorage" is an experimental class. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warning
s.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  inst_data=inst_data, mysql_url=mysql_url_from_config(config_value)
/usr/local/lib/python3.7/site-packages/dagster_mysql/schedule_storage/schedule_storage.py:83: ExperimentalWarning: "MySQLScheduleStorage" is an experimental class. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, i
nvoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  inst_data=inst_data, mysql_url=mysql_url_from_config(config_value)
Updating run storage...
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Starting data migration: run_partitions
Querying run storage.
0it [00:00, ?it/s]
Finished data migration: run_partitions
Updating event storage...
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Updating schedule storage...
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: /opt/dagster/local/
run_storage:
  module: dagster_mysql.run_storage
  class: MySQLRunStorage
  config:
    mysql_db:
      db_name:
        env: DAGSTER_MYSQL_DB
      hostname:
        env: DAGSTER_MYSQL_HOSTNAME
      password:
        env: DAGSTER_MYSQL_PASSWORD
      port: 3306
      username:
        env: DAGSTER_MYSQL_USERNAME
event_log_storage:
  module: dagster_mysql.event_log
  class: MySQLEventLogStorage
  config:
    mysql_db:
      db_name:
        env: DAGSTER_MYSQL_DB
      hostname:
        env: DAGSTER_MYSQL_HOSTNAME
      password:
        env: DAGSTER_MYSQL_PASSWORD
      port: 3306
      username:
        env: DAGSTER_MYSQL_USERNAME
compute_logs:
  module: dagster_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    bucket: log-bucket
    prefix: dagster-test/
schedule_storage:
  module: dagster_mysql.schedule_storage
  class: MySQLScheduleStorage
  config:
    mysql_db:
      db_name:
        env: DAGSTER_MYSQL_DB
      hostname:
        env: DAGSTER_MYSQL_HOSTNAME
      password:
        env: DAGSTER_MYSQL_PASSWORD
      port: 3306
      username:
        env: DAGSTER_MYSQL_USERNAME
scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler
  config: {}
run_coordinator:
  module: dagster.core.run_coordinator
  class: DefaultRunCoordinator
  config: {}
run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher
  config: {}
telemetry: NoneType
`


I am a sysadmin my experience with Dagster is about a week, I was hesitant to post this but was able to reproduce it easily and had been following the documentation, it is 100% possible I'm doing something incorrectly.

Thanks for you time.

**Comment by paralyzah** [comment]
I didn't spoke this case on 0.12.7. Probably this is due to fixes in https://github.com/dagster-io/dagster/pull/4511
Before this PR migration fails on indexes build.

**Comment by gibsondan** [comment]
Hi @paralyzah - agree that that PR likely fixed your issues. Sorry for the delay in response here, but you should be able to get up and running with MySQL in 0.12.7.
