### ISSUE TITLE
Ctrl-/ keyboard shortcut in Dagit's playground YAML editor is double-bound

### ISSUE THREAD

**Issue by afparsons** [dagster-io/dagster#4326]
## Summary
Pressing `Ctrl-/` performs the following two actions:
- comments-out / uncomments a line
- displays search overlay

## Reproduction

Press `Ctrl-/` whilst editing a file in Dagit's playground.

## Suggested Solution
1. Set `Ctrl-/` as the commenting key, akin to PyCharm or VS Code's default keybindings.
2. Map the search pop-up to `Ctrl-k` so as to match the documentation.
3. Alternatively, map the search pop-up to `Ctrl-Shift-/` (`Ctrl-?`); the question mark conveys an interogative sense ("where is ... ?")

## Additional Info about Your Environment
- Dagster stack (dagit, daemon, etc:) 0.11.15
- Dagster host: Ubuntu 20.04 on AWS
- Local system: Ubuntu 18.04
- Local Firefox: 89.0.1 (64-bit)
- Local Chromium: Version 91.0.4472.101 (Official Build) Built on Ubuntu, running on Ubuntu 18.04 (64-bit)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Fixed by https://github.com/dagster-io/dagster/pull/5727.
