### ISSUE TITLE
Adding Asset Materialization to fs_io_manager

### ISSUE THREAD

**Issue by davidtam** [dagster-io/dagster#4342]
## Use Case

Hello I am using [fs_io_manager](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/storage/fs_io_manager.py) and it fits some of my use case but currently dagit doesnt show the files as asset.  Would it be nice to have them shown as asset in dagit by default?

## Ideas of Implementation

Similar to the documentation, but adding the yielding of AssetMaterialization in handle_output
I am happy to do this feature myself (with some  minimal help from you guys)

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Closing because the recommended way to do this is now with SDAs and we added a metadata entry for the path that the FS IO manager writes to
