### ISSUE TITLE
build_hook_context does not support ctx.solid, ctx.solid_config and other properties.

### ISSUE THREAD

**Issue by satyanash** [dagster-io/dagster#4350]
## Use Case
Currently, if a `HookContext` is created using `build_hook_context`, it will not have a bunch of properties and will instead raise a `DagsterInvalidPropertyError` as implemented in https://github.com/dagster-io/dagster/blob/b0c430857c1d772be76216164858ddc7babe376d/python_modules/dagster/dagster/core/execution/context/hook.py#L182

Currently, there is no way to provide a `Solid` instance or any of the other properties.
**This makes it impossible to test hooks** that need access to `context.solid` and other properties.

## Ideas of Implementation

One way would be to change `build_hook_context` to support more kwargs so that the other properties may be specified.

**Comment by sryza** [comment]
@dpeng817

**Comment by dpeng817** [comment]
Hey @satyanash ! Thanks for raising this issue. We consider the class `Solid` an internal API (not to be confused with `SolidDefinition`), and are thus hesitant to encourage its direct creation. What properties of `ctx.solid` have you been making use of in your tests? Maybe there's a more direct way of providing these that doesn't require munging through `Solid` directly.

Regarding `ctx.solid_config`, that one is definitely supportable. It might get tricky regarding validating that config against an actual solid definition, but I think it's reasonable to support that use case.

**Comment by satyanash** [comment]
@dpeng817 Off the top of my head:
- `ctx.solid.name` as it may be used for reporting, identifying which solid broke/succeeded.
- `ctx.run_id` is another one, which is also used for reporting and the like.

I'm sure there are more, but the minute I use `ctx.solid.name` in my hook code, I must disable my tests.

**Comment by satyanash** [comment]
Here are some more that are commonly used:

* `ctx.solid_exception`
* `ctx.mode_def`
* `ctx.pipeline_name`

**Comment by satyanash** [comment]
> We consider the class `Solid` an internal API (not to be confused with SolidDefinition), and are thus hesitant to encourage its direct creation.

An instance of `Solid` is already available to users through `ctx.solid`.
Isn't it already being exposed to users?
Otherwise, we should consider changing the official docs to not use `ctx.solid.name` in the examples.

**Comment by dpeng817** [comment]
I didn't realize that `ctx.solid.name` is used in the examples. I think this should definitely be changed.

You are correct that an instance of `ctx.solid` is available, but `Solid` is not documented anywhere, and I don't think we want to push people towards using it. That property probably shouldn't be there, and we should be pushing people towards things that are more easily communicable and similarly valuable, like `step_key`.

As far as those other properties, I think it's totally reasonable that you would want to construct those. Will put up a PR to address some of the changes we're talking about here.

**Comment by sryza** [comment]
@dpeng817 was this completed? Want to close it out if so?

**Comment by dpeng817** [comment]
not quite completed yet. While `solid` is now supported, there are a few other top level args we should support, namely `solid_config`, `pipeline_name`, `run_id`, and `solid_exception`.

I can get to that this week.

**Comment by satyajeet-sundial** [comment]
> there are a few other top level args we should support, namely solid_config, pipeline_name, run_id, ...

Raised #4501 to resolve the above bits @dpeng817

**Comment by satyanash** [comment]
> there are a few other top level args we should support, namely solid_config, pipeline_name, run_id, ...

Raised #4501 to resolve the above bits @dpeng817

**Comment by LouisAuneau** [comment]
Hello! Is there any release planned for this ? It must be a blocker for a lot of people. On my side I couldn't figure out how to unit test a hook that is using `run_id` and `pipeline_name`.

**Comment by dpeng817** [comment]
Hello @LouisAuneau ! There's a PR up to resolve this now.

**Comment by LouisAuneau** [comment]
@dpeng817  Thanks a lot 🙌 ! I've seen that the PR as been merged to master, will it be part of `0.13.9` ? And is there any release date planned ?

**Comment by dpeng817** [comment]
Hey @LouisAuneau : It will be a part of `0.13.10`, which will be released within the next few weeks.

**Comment by LouisAuneau** [comment]
@dpeng817 Just tested it and it works like a charm. Thanks ! I guess you can close the issue as well ✅
