### ISSUE TITLE
Nested Dynamic Mapping & Collect Not Working

### ISSUE THREAD

**Issue by lgblkb** [dagster-io/dagster#4359]
## Summary

My pipeline (`double_for_loop`) contains two iterators (`first_loop_task` & `second_loop_task`). Both are implemented using "[Dynamic Mapping & Collect](https://docs.dagster.io/_apidocs/dynamic#dynamic-mapping-collect)" feature. The second iterator part (`second_loop_task`) is located inside a composite solid (`subgraph`). 

Expectation: The pipeline should work.
Reality: It doesn't).

P.S. Experimental graph based pipeline definition produces the same behavior.

## Reproduction

```
from dagster import DynamicOutput, Output, repository, solid, pipeline, composite_solid, DynamicOutputDefinition


@solid(output_defs=[DynamicOutputDefinition()])
def first_loop_task():
    data = [
        [1, 2, 3, 4],
        [4, 6, 7, 8],
        [9, 10, 11, 12]
    ]
    for idx, row_items in enumerate(data):
        yield DynamicOutput(row_items, f"row_items_{idx}")


@solid(output_defs=[DynamicOutputDefinition()])
def second_loop_task(context, row_items):
    for single_item in row_items:
        yield DynamicOutput(single_item, f"single_item_{single_item}")


@solid()
def pass_through(v):
    return v + 1


@solid()
def list_to_dict(context, obj):
    context.log.debug(f"obj: {obj}")
    yield Output({str(k): k for k in obj})


@composite_solid()
def subgraph(row_items):
    collected = second_loop_task(row_items).map(pass_through).collect()

    # another_pass_through = pass_through.alias('another_pass_through')
    # return another_pass_through(collected)
    return collected
    # return list_to_dict(collected)


@pipeline()
def double_for_loop():
    collected = first_loop_task().map(subgraph).collect()
    # final_pass_through = pass_through.alias('final_pass_through')
    # result = final_pass_through(collected)


@repository
def double_for_loop_repo():
    return [double_for_loop]
```

## Dagit UI/UX Issue Screenshots

**`dagster.core.errors.DagsterInvalidDefinitionError: @composite_solid subgraph returned problematic value of type <class 'dagster.core.definitions.composition.DynamicFanIn'>. Expected return value from invoked solid or dict mapping output name to return values from invoked solids`**

![image](https://user-images.githubusercontent.com/9667983/125654250-ff6709d5-86ed-4328-9778-7c437182b1fb.png)

## Additional Info about Your Environment

In `pyproject.toml`:
```
dagster = "^0.12.1"
dagit = "^0.12.1"
dagster-graphql = "^0.12.1"
dagster-postgres = "^0.12.1"
dagster-docker = "^0.12.1"
dagster-celery = "^0.12.1"
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
You have `.collect()` in both the composite and the pipeline. We do not currently support mapping the `collect()` from `composite_solid` so we have to drop it there. Once thats dropped, the composite def needs to declare that its output is dynamic. 

With those changes we have:
```
@composite_solid(output_defs=[DynamicOutputDefinition()])
def subgraph(row_items):
    collected = second_loop_task(row_items).map(pass_through)
```
which should work

**Comment by lgblkb** [comment]
Dear @alangenfeld,
Thank you for your help!!! 

I'm not sure if I should create a new issue. Dropping `.collect()` solved the issue, but now I'm facing another problem. 


Updated code:
```
from dagster import DynamicOutput, Output, repository, solid, pipeline, composite_solid, DynamicOutputDefinition


@solid(output_defs=[DynamicOutputDefinition()])
def first_loop_task():
    data = [
        [1, 2, 3, 4],
        [4, 6, 7, 8],
        [9, 10, 11, 12]
    ]
    for idx, row_items in enumerate(data):
        yield DynamicOutput(row_items, f"row_items_{idx}")


@solid(output_defs=[DynamicOutputDefinition()])
def second_loop_task(context, row_items):
    context.log.debug(f"row_items: {row_items}")
    for single_item in row_items:
        context.log.debug(f"single_item: {single_item}")
        yield DynamicOutput(single_item, f"single_item_{single_item}")


@solid()
def pass_through(v):
    return v


@solid()
def list_to_dict(context, obj):
    context.log.debug(f"obj: {obj}")
    yield Output({str(k): k for k in obj})


@composite_solid(output_defs=[DynamicOutputDefinition()])
def subgraph(row_items):
    return second_loop_task(row_items).map(pass_through)


@pipeline()
def double_for_loop():
    collected = first_loop_task().map(subgraph).collect()


@repository
def double_for_loop_repo():
    return [double_for_loop]
```
results in all `pass_through` tasks having `Skipping step due to skipped dependencies: [].`:
![image](https://user-images.githubusercontent.com/9667983/125731257-377aa3b9-4cd5-4fc0-a0c7-e32dfae97d6d.png)

but `second_loop_task` seems to be working fine:
![image](https://user-images.githubusercontent.com/9667983/125731803-4b705c8d-8a4a-43e0-8345-32caacf80835.png)

Am I missing something?

**Comment by alangenfeld** [comment]
Ah I should have caught this when first looking at it - but we do not yet support multiple levels of dynamic mapping. 

You found a case where we don't error out due to the indirection of the `@composite_solid`, leading to unexpected execution behavior. If you remove the composite solid, you will see the expected error message.

**Comment by alangenfeld** [comment]
Heres an issue for tracking proper support https://github.com/dagster-io/dagster/issues/4364
