### ISSUE TITLE
[Content Gap] solid retry policies

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4363]
## Writer's Guide
- [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)
- Templates to follow: <fill by the docs team>
- Examples for reference: <fill by the docs team>

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
could belong to https://docs.dagster.io/concepts/solids-pipelines/pipelines or create a separate failure handling page

**Comment by rexledesma** [comment]
Resolved with https://docs.dagster.io/concepts/ops-jobs-graphs/op-retries
