### ISSUE TITLE
When a pipeline goes for > 1 minute counts should still timer should still update at second granularity

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#437]
Right now if a solid takes more than a minute it appears "dead" in the UI. It also immediately rounds up to "2 mins" in the display.

**Comment by bengotow** [comment]
This is what I thought originally as well - do you know what the threshold should be? 300 seconds switches to 5 minutes maybe?

**Comment by schrockn** [comment]
I kind of think second granularity forever so the user knows that stuff is
happening

**Comment by mgasner** [comment]
per discussion, 00:59 -> 01:00, etc.

**Comment by bengotow** [comment]
This is addressed in #449 which merged this morning. Going to go ahead and close this!
