### ISSUE TITLE
divider sits on top of "Launch Execution" button in Playground

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4370]
## Summary

![image](https://user-images.githubusercontent.com/654855/125981749-a10bee8d-cfb4-40f6-a07f-ae488eecca7f.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
This will be fixed by https://dagster.phacility.com/D9099
