### ISSUE TITLE
Can the docstring-parser dependency be relaxed?

### ISSUE THREAD

**Issue by KyleKing** [dagster-io/dagster#4374]
## Summary

Can the docstring-parser dependency be relaxed? Maybe `"docstring-parser>=0.71"` or unversioned (`"docstring-parser"`)?

https://github.com/dagster-io/dagster/blob/332561414f25164eafd21d58b58881b3db73fd8a/python_modules/dagster/setup.py#L86

`docstring-parser` appears to be implemented in a way that it could be optional and there doesn't seem to be anything special that would require pinning to 0.7.1:

https://github.com/dagster-io/dagster/blob/c9080d04e93aa95bcee12290d77742f97dad8f0b/python_modules/dagster/dagster/core/definitions/inference.py#L25-L50

## Reproduction

1. Currently, this is an issue for me because I need to use a newer version of `pdocs` that requires docstring-parser `>=0.7.2`, so both dagster and pdocs can't be installed in the same environment
2. Keeping docstring-parser pinned is also preventing dagster from benefitting from fixes. For example, #3306 is an issue with docstring-parser that was fixed in `docstring-parser==0.8` ([docstring_parser/issues/37](https://github.com/rr-/docstring_parser/issues/37)). (Dagster should probably still ignore errors from incorrectly formatted docstrings, but with the try/catch there shouldn't be a reason to not allow updated versions of docstring-parser)

---

#### Message from the maintainers:

Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
yep looks like an oversight - sending a change out now
