### ISSUE TITLE
Expose undefined arguments in config

### ISSUE THREAD

**Issue by ricardo-re-azevedo** [dagster-io/dagster#4375]
## Use Case

Currently, unless I missed something in the docs (I am new), it is not easy to allow solid arguments to be exposed as config variables if no input is provided. This is handy if reusing a single solid in various pipelines with different user inputs. In my case I often have solids where in some cases I want a parameter to be determined from some other function output but in other cases I want to have the user define the variable at runtime. 

For example, I have a solid I would like to use in various pipelines such as:
```python
@solid
def add(x: int, y: int) ->int:
    return x + y
```
In one pipeline both inputs are fed from another step:
```python
@pipeline
def work():
   a = some_step()
   b = some_step()
   add(a, b)
```
In another pipeline I would like to expose one of the args in the solid config:
```python
def work():
   a = some_step()
   add(a) # get b from user input
```
Currently this isn't easily doable without copying the solid and modifying it to accept 'y' in the config rather than args . I may be missing something though. 

This seems like it would be a pretty common pattern. It would also be useful in making solids more 'portable'.

## Ideas of Implementation

I think there could be several options here. One would be to allow unused config variables and use kwargs with some logic:
```python
@solid(config_schema={"y": {'type':int, 'optional':True}) # or some other extended syntax
def add(x: int, y=0: int) ->int:
  if 'y' in context.solid_config:
     y = context.solid_config["y"]
  return x + y
``` 
but this seems verbose and fragile. I think a better option would be to have some logic in the definition to expose the arg within the config if it is not explicitly defined:
```python
@solid(input_defs=[InputDefinition(name="x"), InputDefinition(name="y", configurable=True)],
def add(x: int, y: int) ->int:
    return x + y
```

I am using `y` as an arg here but I think it should work the same with kwargs: Expose the kwarg under config if it is using the default value.

## Additional Info

Is this feasible? I am willing to take a deeper look into this if someone has suggestions where in the codebase to look. 

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @ricardo-re-azevedo - I believe Dagster already provides a version of what you're asking for.  Take a look at https://docs.dagster.io/concepts/io-management/unconnected-inputs#loading-a-built-in-dagster-type-from-config.  Let me know if I'm misunderstanding your request.

**Comment by ricardo-re-azevedo** [comment]
Ah, beautiful! Thanks for help. I had misunderstood that section of the doc. 

As an aside, It would be nice if these unconnected inputs were highlighted in the dagit pipeline overview. Perhaps in a different color like red.

**Comment by sryza** [comment]
Glad to hear that this works for you. Going to close this out.

**Comment by yuhan** [comment]
@ricardo-re-azevedo Thanks for the feedback. Filed a separate issue https://github.com/dagster-io/dagster/issues/4407 for tracking
