### ISSUE TITLE
TestDBTRunAndWaitSolid.test_run_all flakey

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#4378]
seems to effect 3.6 more than others
https://buildkite.com/dagster/dagster/builds/18378#4176f87d-18e7-4a46-8f5c-4d6b7a5abc7b

We should move it to the integration suite if we think its valuable to hit live dbt from a test

**Comment by yuhan** [comment]
cc @OwenKephart

**Comment by alangenfeld** [comment]
https://buildkite.com/dagster/dagster/builds/18406#59592e9f-4a44-4390-91ba-d5f02d26d300
