### ISSUE TITLE
Make log viewer scroll along with new messages

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#438]
It would be nice if the log viewer scrolled along with new messages as they come in. Would make the experience feel more alive.

**Comment by bengotow** [comment]
Hey hey - this should already be done in #393. It's only enabled if you have the log window scrolled to the top and it starts scrolling, or if it's scrolled all the way to the bottom. Are you seeing it not work? It's possible the log debouncing changed the behavior somehow.

**Comment by bengotow** [comment]
Ahh finally figured this out—it looks like if the UI transitions from the empty state directly to a state where there are more than N logs and a scrollbar is shown, it doesn't start tracking the bottom. Will get this fixed.
