### ISSUE TITLE
UI Bug: Search box covers solid display 

### ISSUE THREAD

**Issue by mociarain** [dagster-io/dagster#4389]
## Summary

I have a very large fan out that is collected by a single final concatenation solid. To see the logs for this concatenation solid I want to click on the solid in the display but it's covered by the search box. 

## Reproduction
Any pipeline with enough solids or a large enough fan out to cause scrolling on the display.

## Dagit UI/UX Issue Screenshots

![Lots of solids UI Bug](https://user-images.githubusercontent.com/20353159/126669308-738b6042-f114-4cc6-a3d7-efd49e764370.png)

---
#### Message from the maintainers:
Minimal impact. I can work around this by remembering what the solid is called and using the search box. It just looks a bit weird.

**Comment by bengotow** [comment]
Turns out we were just missing some padding. will be resolved in https://dagster.phacility.com/D9100

**Comment by mociarain** [comment]
Nice. Thanks for the quick resolution :)
