### ISSUE TITLE
Need to capture stderr when a forked execution process segfaults or dies in some other way

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#441]
This is the more general issue behind #428, which exposed the issue thanks to matplotlib nonsense.

If we fork an execution process and that process dies -- for whatever reason -- in such a way that error output and logs are not available to the parent process, we need to capture stderr/stdout from the dead process and expose that in the logs.

Otherwise, we are setting ourselves up for a thousand corner cases like this, where pipelines die thanks to peculiarities of the scientific python landscape, or whatever other tools, DSLs, FFIs, etc., people invoke, and users have no feedback about how or why they died.

**Comment by alangenfeld** [comment]
I believe the compute logs setup handles this now
