### ISSUE TITLE
greenlet.greenlet size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by JBrVJxsc** [dagster-io/dagster#4413]
## Summary

guys, im seeing the same `greenlet.greenlet size changed, may indicate binary incompatibility` warnings mentioned in this issue: https://github.com/gevent/gevent/issues/1260
it seems it was resolved with the latest gevent and greenlet, I'm thinking if Dagster can bump the version of these libraries and skip the problematic versions.

With those warnings, the Dagit server will exit when I use Dagit as a library to boot the Dagit UI. I had to pin the 
greenlet version to `"greenlet": "pypi:greenlet:0.4.16",` in order to make it work.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
@alangenfeld - is this something you know anything about?

**Comment by alangenfeld** [comment]
Yea the current gevent/Flask/graphql-ws set up we have is problematic and hard to upgrade incrementally, some details here https://github.com/dagster-io/dagster/issues/4089.

I am working on migrating us to a modern ASGI framework, starlette to replace this problematic set up. 
You can see progress here https://github.com/dagster-io/dagster/blob/master/python_modules/dagit/dagit/starlette.py
