### ISSUE TITLE
Dagit playground auto-populates the default config for a job

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4424]
## Summary
Given the following job:
```python
from dagster import op, graph, repository


@op(config_schema={"foo": str})
def my_op(_):
    pass


@graph
def my_graph():
    my_op()


@repository()
def my_repo():
    my_job = my_graph.to_job(config={"ops": {"my_op": {"config": {"foo": "bar"}}}})
    return [my_job]
```
 `my_job` has its config fully satisfied internally, so there should not be any config populated in the playground. However, when you open the playground, the default config populates a second time:
 
<img width="1440" alt="Screen Shot 2021-07-30 at 9 27 40 AM" src="https://user-images.githubusercontent.com/17576880/127702741-37b8a3d0-3eee-4004-aba5-607c69c080b8.png">

The config in the playground should ideally be empty, to reflect that no additional config is required.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
This is actually the expected behavior, at least as we've currently envisioned it.  The way this works is that the "config" argument is not fully internal - it's used as the default configuration when the job is launched, but can also be overridden.  Is that behavior causing problems?

**Comment by dpeng817** [comment]
I see. Something definitely wrong with default config mapping then on `to_job`.
