### ISSUE TITLE
Dagster getting started code raises immediate issues with PyRight type checker

### ISSUE THREAD

**Issue by smackesey** [dagster-io/dagster#4439]
## Summary
This is not exactly a "bug", but it is something that isn't working correctly in concert with commonly used dev tools.

Dagster's type annotations are (preventably) incompatible with the popular PyRight language server, and the problem manifests itself in the first code block of the tutorial. AFAICT there are two problems:

1. `dagster.core.definitions` both has `from .decorators import solid` and `from .solid import ...`. This introduces ambiguity into the value assigned to `solid` in `dagster.core.definitions`. It is difficult for static analyzers to determine the type of `solid` under these circumstances, and different ones make different assumptions. PyRight's assumption is incorrect-- it thinks `solid` is the `dagster.core.definitions.solid` submodule, when the runtime value is the imported decorator function. This problem is discussed with PyRight's maintainer [here](https://github.com/microsoft/pyright/issues/2140) and in a Slack thread with a Dagster dev [here](https://dagster.slack.com/archives/C01U954MEER/p1627923215076700).

One can work around the above problem by importing `solid` directly from `dagster.core.definitions.decorators` instead of `dagster`. However, the result causes another problem.

2. The `solid` decorator can either function as a "direct" decorator (with no args) or take args. Thus the return value of `solid` is of type `_Solid | SolidDefinition`. When used directly (no args), the result is a `SolidDefinition`, when it gets args the result is a `_Solid`. But PyRight does not understand the conditions that will lead to the return of either type:

```python
@solid
def get_name():  # get_name is a `SolidDefinition` but PyRight thinks it's `SolidDefinition | _Solid`
    return 'dagster'
```

This leads PyRight to complain when you try to call `get_name` in another solid, because you are calling it as a `SolidDefinition` but PyRight thinks maybe it is a `_Solid`:

```python
@pipeline
def hello_pipeline():
    hello(get_name())  # Error: Argument missing for parameter "fn"
```

There are two possible workarounds.

A. You can always invoke the decorator as `@solid()` instead of `@solid`. This gets rid of the error, but for reasons I don't understand this makes the type of the decorated function `SolidDefinition | Any`. Not sure exactly what effect the extra `Any` has or why it's there.

B. You can explicitly cast each decorated solid to a `SolidDefinition`, but this is a PITA/extra complexity/highly undesireable.

## Reproduction

Just load the code-block in Dagster [Getting Started](https://docs.dagster.io/getting-started) into an editor running PyRight and observe the errors:

```python
from dagster import pipeline, solid


@solid
def get_name():
    return "dagster"


@solid
def hello(context, name: str):
    context.log.info(f"Hello, {name}!")


@pipeline
def hello_pipeline():
    hello(get_name())
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
@smackesey thanks for this detailed report.  If we were to change `from .solid import ...` to an absolute import (`from dagster.core.definitions.solid import ...`), would you expect that to help?

**Comment by smackesey** [comment]
Unfortunately the answer is "kind-of-sort-of".

I just tested this and, yes, this does fix the immediate problem for PyRight. However, this is by luck more than by anything systematic, and it makes me wonder whether it might break similar functionality in some *other* typing system.

IMO the solution is ultimately to avoid exporting any names that match the name of a submodule. So, in the case of `dagster.core.definitions`, that means not simultaneously having a defined value (for the decorator) `solid` *and* the submodule (`dagster.core.definitions.solid`).

The reason for this is that the value of the exported name is inherently unstable. That is because, the first time (and *only* the first time) the submodule is loaded (and this does not matter *where* it's loaded, it can be in some arbitrary other file), it adds itself to the module namespace. If it happens to be loaded before whatever you're trying to export, then there's no problem. But if it get's loaded afterwards, then it overwrites the thing you're trying to export. So, this situation is liable to break in the future if an import for the submodule is added or removed elsewhere.

This is described [here](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-submodules-are-added-to-the-package-namespace-trap).

And here's a toy example you can use to verify:

```python
### x/__init__.py
y = 'foo'
import a.z

### x/y.py
# BLANK MODULE

### x/z.py
import x.y

### test.py
import x
print(x.y)
```

You'll see that a string rep of the submodule `x.y` is counterintuitively printed, instead of `foo`.
