### ISSUE TITLE
Rendering is wrong for very fast execution steps

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#445]
![screenshot 2018-12-19 10 28 09](https://user-images.githubusercontent.com/28738937/50240181-f7cee100-0378-11e9-83c8-a998f4a83122.png)

Truncates down to zero and then appends it directly to the step name

**Comment by bengotow** [comment]
Oof! Good catch—I fixed this for the "seconds elapsed" state but it looks like the total time can also be zero if the log messages for start and end have the same timestamp.

**Comment by bengotow** [comment]
This is addressed in #449 which merged this morning. Going to go ahead and close this!
