### ISSUE TITLE
"ins" and "out" arguments for @graph

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4453]
`@op` has the `ins` and `out` arguments for specifying inputs and outputs, which accept `In`s and `Out`s, but `@graph` still has `input_defs` and `output_defs` arguments that accept `InputDefinition`s and `OutputDefinition`s.

We should make these consistent.  Also, we've discussed eliminating the `default_value` and `dagster_type` attrs of graph input/output defs, because they're hard to reason about and provide questionable value.

Could look something like:
```
@graph(ins={"arg1": GraphIn(description="abc")}, out=GraphOut(description="xyz"))
def my_graph(arg1):
    ...
```

**Comment by schrockn** [comment]
Why have GraphIn rather than just reuse In?

**Comment by sryza** [comment]
> Why have GraphIn rather than just reuse In?

`In` and `Out` support `default_value`, `dagster_type`, `io_manager_key`, and `root_manager_key`, which I'm proposing be unsupported for graph inputs and outputs.  Here's a slack thread with more discussion: https://dagster.slack.com/archives/C021JUYU0DN/p1628094583002700.

**Comment by alangenfeld** [comment]
`Graph__` feels off naming wise to me. These are ultimately input & output mappings when they exist on graphs, so maybe something like:
* `MappedIn`
* `MapIn`
* `Mapped`  / `Mapping` (if theres no arg difference between in and out)

**Comment by sryza** [comment]
I have no attachment to `GraphIn`/`Out`, but the map-based named make me a little uneasy.

The way I understand it, an `InputMapping` defines a mapping between an input to a graph and an input to a node inside that graph.  It's inaccurate to say that the input to the graph is a "mapping" - it's included in themapping.  It's also not always accurate to say that the input to the graph is "mapped" - only if, in the body of the decorated function, it's passed as an input to a node invocation, then it will be mapped.

Could maybe go with `MappableIn` or similar?

"Map" is also a term we use in dynamic outputs, which could cause some confusion.

**Comment by alangenfeld** [comment]
> only if, in the body of the decorated function, it's passed as an input to a node invocation, then it will be mapped

For what its worth, I'm fairly sure we error if it doesn't get mapped.

That said, I still find your reasoning compelling. 
Not really happy with these, but throwing them around to help brain storm: `Spec`,  `Props`, `Expose`
