### ISSUE TITLE
Dagstermill notebook previews do not work with remote user code deployment

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#4469]
## Summary
Dagit looks for `.ipynb` files on the local file server, which means that notebooks on the grpc server generate errors.

## Reproduction

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment]
related: https://github.com/dagster-io/dagster/issues/1469
