### ISSUE TITLE
Add configuration which limits the run time of a solid/pipeline

### ISSUE THREAD

**Issue by yasinzaehringer-paradime** [dagster-io/dagster#4492]
## Use Case

For unknown reasons - which I still have to investigate - some pipelines stop working mid-way and the max concurrency limit kicks in and blocks all further schedules. If I can specify a max runtime the solids will fail which is preferable to the scheduling system getting stuck and requiring manual intervention.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
@yasinzaehringer-paradime would you prefer to set this at the solid level, or at the instance level to apply uniformly to all solids?

Here's an issue we have for tracking solid-level timeouts: https://github.com/dagster-io/dagster/issues/3666

**Comment by yasinzaehringer-paradime** [comment]
Yeah, I am indeed thinking about solid level timeouts. I'll close this PR in favour of https://github.com/dagster-io/dagster/issues/3666. Thanks!
