### ISSUE TITLE
MLFlow `end_mlflow_run_on_pipeline_finished` decorator doesn't return `HookExecutionResult`

### ISSUE THREAD

**Issue by JJMinton** [dagster-io/dagster#4506]
## Summary

I get the following error when using `@end_mlflow_run_on_pipeline_finished` with pipeline:
```
dagster.check.CheckError: Invariant failed. Description: Error in hook end_mlflow_run_on_pipeline_finished: hook unexpectedly returned result None of type <class 'NoneType'>. Should be a HookExecutionResult
Stack Trace:
  File "/usr/local/lib/python3.6/site-packages/dagster/core/execution/api.py", line 748, in pipeline_execution_iterator
    for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
  File "/usr/local/lib/python3.6/site-packages/dagster/core/executor/in_process.py", line 50, in execute
    output_capture=pipeline_context.output_capture,
  File "/usr/local/lib/python3.6/site-packages/dagster/core/execution/api.py", line 829, in __iter__
    pipeline_context=self.pipeline_context,
  File "/usr/local/lib/python3.6/site-packages/dagster/core/execution/plan/execute_plan.py", line 83, in inner_plan_execution_iterator
    for hook_event in _trigger_hook(step_context, step_event_list):
  File "/usr/local/lib/python3.6/site-packages/dagster/core/execution/plan/execute_plan.py", line 122, in _trigger_hook
    type_=type(hook_execution_result),
  File "/usr/local/lib/python3.6/site-packages/dagster/check/__init__.py", line 170, in invariant
    raise CheckError(f"Invariant failed. Description: {desc}")
```

## Reproduction
Replace the pipeline of the docker example with
```
@end_mlflow_run_on_pipeline_finished
@pipeline(mode_defs=[ModeDefinition(name="test", resource_defs={"mlflow": mlflow_tracking})])
def my_pipeline():
    hello()
```
(and add `dagster-mlflow` installation to the Dockerfile) then run the pipeline as usual. 

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/6495794/129248442-71c7ad0b-2ce4-422d-96f7-afd98dc7ada2.png)

## Additional Info about Your Environment
```
pip freeze
...
dagit==0.12.5
dagster==0.12.5
dagster-mlflow==0.12.5
...
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for the bug report @JJMinton .  Here's a fix: https://dagster.phacility.com/D9227.

**Comment by JJMinton** [comment]
Thanks @sryza. I put together a fix [here](https://github.com/JJMinton/dagster/tree/bugfix/dagster-mlflow-returns-none) but i guess you beat me to the punch.

Looking at your fix, why return a `skipped` flag, even when the run has been ended?

**Comment by sryza** [comment]
@JJMinton I'm happy to review your fix if you want to make a pull request.  It looks like your version has more tests than mine and uses `skipped` more correctly.
