### ISSUE TITLE
Confusing favicon display strategy 

### ISSUE THREAD

**Issue by JBrVJxsc** [dagster-io/dagster#4532]
## Summary

The favicon is kind of confusing, and as a user, it's hard for me to understand what's going wrong. See attached example:

1. when page just loaded from a route that doesn't have a failure state, the favicon color will be blue, which makes sense;
2. if I switch to a failed run, the favicon became red, which also makes sense;
3. what makes it does not make sense is, if I go back to the route that should have a `blue` state, it still shows `red`. Until I refresh the page, it will become `blue` again.

I think the logic to check which favicon color to show needs some revision.

![confusing favicon logic](https://user-images.githubusercontent.com/3367239/129463463-21a4efcc-ac3c-410a-93be-08d25a8bab31.gif)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Thanks for the details and the screen capture! Taking a look.
