### ISSUE TITLE
objects.inv under dagster docs for intersphinx

### ISSUE THREAD

**Issue by Jiafi** [dagster-io/dagster#4538]
## Use Case

Be able to automatically generate hyperlinks when generating sphinx documentation.  

## Ideas of Implementation

How I would add it in the `conf.py` 
``` python
intersphinx_mapping = {
    "dagster": ("https://docs.dagster.io/docs/", (None, "intersphinx/dagster.inv")),
}
```

Not totally sure how to publish `objects.inv`.  Example of existing `objects.inv` https://numpy.org/doc/stable/objects.inv

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
#4602 made it available at `https://docs.dagster.io/objects.inv`
