### ISSUE TITLE
Migrate dagster-celery away from using intermediate storage.

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4541]
Currently, `dagster-celery` uses intermediate storage. In addition to being a deprecated API, it's also not possible to use memoization with intermediate storage at this time. Switching dagster-celery away from using intermediate storage will enable memoization while using the dagster-celery executor.

**Comment by sryza** [comment]
@dpeng817 - this is a P0 for removing intermediate storage - is that right?  Otherwise we'd break dagster-celery when we remove it?

**Comment by dpeng817** [comment]
@sryza - that's correct
