### ISSUE TITLE
dagit long markdown formatted code blocks require manual resizing

### ISSUE THREAD

**Issue by Aylr** [dagster-io/dagster#456]
I often put sql in markdown formatted code blocks, which do not flow. I wonder if a horizontal scrollbar could appear when non-wrapping text is larger than the viewable area. That saves lots of finicky resizing that causes me to lose context of the entire dag by consuming most of the browser.

<img width="1040" alt="dagit" src="https://user-images.githubusercontent.com/928247/50311753-8ae44580-0463-11e9-8df0-8504e7888aef.png">

**Comment by bengotow** [comment]
I think this is a great idea, should be a quick fix. 👍
