### ISSUE TITLE
Issues with GraphQL, gevent etc

### ISSUE THREAD

**Issue by freiksenet** [dagster-io/dagster#460]
Here is the summary of the issues I've encountered adapting GraphQL/Gevent executor.

* GeventSubscriptionServer actually uses SynchronousExecutor internally. Should be changed to use GeventExecutor.
* SubscriptionServer doesn't support using non-subscribe operations through it. Missing is not only basic support, but also lifecycle operations like outputting COMPLETE at the end of operation. This has been changed in my subclass of SubcriptionServer. 
* GeventExecutor outputs Promise objects. graphql-core subscription core fails on any type but Observable. graphql-core should be changed to allow Promises as base subscribe call results (like graphql-js). This means one can't use GeventExecutor with subscriptions and SubscriptionServer only works because it's not really using GeventExecutor.

Issues with graphene schema:

* Internal Graphene code breaks Union/ObjectType encapsulation. Ideally they should both use methods like getType and getInterfaces to get the list of objects, allowing user to pass lambdas to those fields. Currently they directly inspect ._types and ._interfaces.If this is changed Dauphine won't need to override Schema and TypeMap implementations so much.
* Union metaclass could be somehow less strict about requiring types in Meta. prolly could be solved if lambda as types would be allowed.

**Comment by mgasner** [comment]
I'm going to close this as it's just a reference for outstanding upstream infelicities.
