### ISSUE TITLE
graphql-ws upgraded to 0.4.x making breaking changes

### ISSUE THREAD

**Issue by johncrash64** [dagster-io/dagster#4628]
## Summary

When try to deploy on docker containers I see that dagit and daemon fails.

The import of `SubscriptionObserver` was changed for v0.4.x and is not present anymore.
The change is a side effect of the upgrade of graphql library.

## Reproduction

Use the next Dockerfile_dagster as example

```
# Dagster libraries to run both dagit and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.7-slim

RUN pip install \
    dagster \
    dagster-graphql \
    # graphql-ws==0.3.1 --force-reinstall \ # THIS IS THE WORKAROUND
    dagit \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
```

## Additional Info about Your Environment

Ubuntu server 20.04
Docker version 20.10.8, build 3967b7d
docker-compose version 1.25.0 

#### Docker_dagster version
https://github.com/dagster-io/dagster/tree/0.12.7/examples/deploy_docker

---
#### Message from the maintainers:
The workaround to solve is adding the next line to the `pip install`
```
    graphql-ws==0.3.1 --force-reinstal
```
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
We have the pin landed https://github.com/dagster-io/dagster/commit/2bea17cac86bac738208a741f40208681b0d4980 and it will go out in the `0.12.8` release currently scheduled for tomorrow `8/26` .

**Comment by mgasner** [comment]
Adding the traceback to make this more discoverable on Google:

```Traceback (most recent call last):
File "/usr/local/bin/dagit", line 5, in <module>
from dagit.cli import main
File "/usr/local/lib/python3.7/site-packages/dagit/cli.py", line 22, in <module>
from .app import create_app_from_workspace_process_context
File "/usr/local/lib/python3.7/site-packages/dagit/app.py", line 23, in <module>
from .subscription_server import DagsterSubscriptionServer
File "/usr/local/lib/python3.7/site-packages/dagit/subscription_server.py", line 4, in <module>
from graphql_ws.gevent import GeventSubscriptionServer, SubscriptionObserver
ImportError: cannot import name 'SubscriptionObserver' from 'graphql_ws.gevent' (/usr/local/lib/python3.7/site-packages/graphql_ws/gevent.py)```
