### ISSUE TITLE
dagit silent failure bug

### ISSUE THREAD

**Issue by Aylr** [dagster-io/dagster#468]
## Behavior

- A user working through tutorials runs dagit and sees no output on the terminal for a long time.
- All pipelines etc were determined valid and runnable with the cli and graphviz.

## STR

1. make a new dir `mkdir foo`
2. within `foo` make a virtuanenv
3. activate virturalenv
2. make `foo/foo.py`:
```
from dagster import RepositoryDefinition

from dagster import (
    PipelineDefinition,
    lambda_solid,
)

@lambda_solid
def hello_world():
    print('hello')

def define_pipeline():
    return PipelineDefinition(
        name='hello_world_pipeline',
        solids=[hello_world],
    )

def define_repository():
    return RepositoryDefinition(
        name='my_repository',
        pipeline_dict={
            'hello_world_pipeline': define_pipeline,
        },
    )
```
4. make a `foo/repository.yml`:
```
repository:
  file: foo.py
  fn: define_repository
```
5. `pip install dagit dagster` to get 0.2.8.post0
6. from `foo` run `dagit`. Note dagit works.
7. Now kill dagit and move the two files `foo.py` and `repository.yml` up a single dir
8. `cd ../`
9. `dagit` and watch it hang silently.
10. Also note that `dagit -f foo.py -n define_repository` also hangs silently
11. Also note that cli commands still work: `dagster pipeline list` `dagster pipeline graphviz hello_world_pipeline`

## Also Note, Pyenv is strange

After this STR was discovered, we noted the original hanging behavior was observed with someone using pyenv. Despite multiple iterations using different methods (dagit -f/-n, module/file keys in repository.yml` dagit was only seen to work in this environment using the module key,

**Comment by schrockn** [comment]
Unfortunately I cannot repro this, even with virtualenv.

Some additional ideas/things to include in this issue:

1) Delete all .pyc and __pycache__ files

2) Note *exact* python version number (output python --version)

3) `pip freeze` and copy-paste contents into here

4) See if bug replicates off of dagster master

5) Note exact repro steps using pyenv. (I've never set up an environment using pyenv)

6) Curse the python Gods for having so many permutations of virtual environments.

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by eugmandel** [comment]
Running dagit with --no-watch flag does the trick.

**Comment by schrockn** [comment]
Yeah and this is why ascending up a folder in the repro triggers it. If the watcher is trying to watch too many files it just doesn't work. @bengotow and I have chatted about substantially changing this feature or just relying on something like watchman. I think it is time to do so. I will open up a task to track this.
