### ISSUE TITLE
Reference to solid in subset selection when in job & graph view

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#4690]
## Summary
In the job & graph view, the subset selector should probably read `Type of subset of ops (ex: start*)`

## Reproduction
Switch to the job & graph view, load a repository location, inspect a job.

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/16431325/131726091-dae14858-7336-4bbc-9c90-20eba06019f8.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Yep, there are a bunch of these that will be taken care of with https://github.com/dagster-io/dagster/pull/4698, so I'll go ahead and close this. Thanks for the report!
