### ISSUE TITLE
execute_job and re-execute_job

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4711]
For the short term, we need to have these APIs exist for jobs as they currently do for pipelines. This could mean a simple reskin, but it's important to have these top level APIs for 0.13.0.

**Comment by prha** [comment]
Ran into this with with https://github.com/dagster-io/dagster/pull/6787, where I wish there were a `reexecute_in_process` method on the job that takes a parent run id.

**Comment by sryza** [comment]
Closing because we now have execute_job
