### ISSUE TITLE
revisit how GraphDefinition.execute_in_process works with config

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4719]
Discussion started here: https://github.com/dagster-io/dagster/pull/4685#discussion_r701274757.

A couple things that might be considered weird about the current approach:
* Accepts a `config` argument, which is different than the `run_config` argument accepted by other `execute` methods.
* Can't supply resource config.

Not having known about the underlying implementation of `GraphDefinition.execute_in_process`, I would have expected it to look something like `self.to_job(run_config=config, resources=resources).execute_in_process()`.

If someone wants to supply config only to the graph, they could do `my_graph.configured(config).execute_in_process()`.

**Comment by sryza** [comment]
Thoughts @alangenfeld @dpeng817 ?

**Comment by dpeng817** [comment]
I personally find it a bit weird that the config argument wouldn't refer directly to the thing that we are calling the method on, but maybe it needs to be that way usability purposes. The resources part is definitely a usability concern (and, for that matter, a usability concern of invocation as well).

If we did want to go that route, we should re-name the config argument run_config.

**Comment by sryza** [comment]
I think we should go that route.  In addition to the usability concern, there's also a consistency benefit: the resources argument to `execute_in_process` corresponds to the resources argument to `to_job`.  We'll likely want to add `tags`, `hooks`, and `version_strategy` arguments, each of which will also correspond to a `to_job` argument.  If the config argument corresponds to a `to_job` argument as well, then that would be consistent.

**Comment by dpeng817** [comment]
Fixed on master
