### ISSUE TITLE
Display top-level field description in config

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#473]
This bug is a holdover from when Config was a separate concept. This is no longer true in internal dagster land (it is just a bare Field). However this is not reflected in the graphql schema; there still exists a totally pointless ConfigType. This should be replaced with a Field and then descriptions flow up as appropriate.

**Comment by bengotow** [comment]
Looks like it'll make sense to handle this one and #476 at the same time (currently the pretty-printing field display component is called `Config` which further adds to the confusion.)
