### ISSUE TITLE
Allow access to context in VersionStrategy

### ISSUE THREAD

**Issue by RBrossard** [dagster-io/dagster#4744]
First of all, I'd like to thank you for that amazing work. Given all the great features, we plan on using dagster as our main orchestration lib soon. 

I have been testing the new versioning and memoization recently, and have stumbled on how to use it in nodes designed as factories (more details below). Notice that I am a recent user, and as such I am not entirely sure if this requires a new feature or if this results of me not using the lib correctly.

## Use Case
We are mainly implementing nodes as factories. For example, we have a node make_dataset, which takes a string in config to return either dataset_A of dataset_B. In pseudo_code:

```
@solid(version=???)
def make_dataset(context):
    name = context.solid_config["name"]
    return get_dataset(name)

run_config = {
    "solids": {
        "make_dataset": {
            "config": {"name": "dataset_A"}
        }
    }
}
```

Now, I want to implement versioning of this node, in order to use the memoization feature. 

- I can implement a function like `get_dataset_version(dataset_name:str)->str` (for example using DVC) but I don't know how to use it as the dataset name will be known only at runtime. 

- The other option would be to have only one global version (like the agglomeration the DVC versions of all the datasets). However, this seems awkard to me, as it would change the signature of the whole node if we add or update a dataset.

Currently, the `version` field of the solid decorator expects just a string, and VersionStrategy only has access to the solid definition, which does not have access to the run time context. I am not aware of other ways to add version informations in a solid.

Of course, I could have a different (versionned) node for each dataset and produce the graph dynamically. However, this will break dagit, (and possibly a bunch of other features?).

## Ideas of Implementation
The signatures of [ `VersionStrategy.get_solid_version`](https://github.com/dagster-io/dagster/blob/2880ac198dbd9b5ed0e81e83d8c91508ac8e77ba/python_modules/dagster/dagster/core/definitions/version_strategy.py#L9) and  [`VersionStrategy.get_resource_version`](https://github.com/dagster-io/dagster/blob/2880ac198dbd9b5ed0e81e83d8c91508ac8e77ba/python_modules/dagster/dagster/core/definitions/version_strategy.py#L9) could be modified to have access to a solid context, and the code in [`resolve_versions.py`(l. 100+)](https://github.com/dagster-io/dagster/blob/56805e316e7a9f9d0e90426b84a1d863cae752d7/python_modules/dagster/dagster/core/execution/resolve_versions.py) would have to be adapted. This seems like a small modification, but I am not aware of what it could break.

## Additional Info

An alternative would be to have dagster manage pipeline templates, with placeholder nodes. Although it could be a big step toward managing fully dynamical DAG, this certainely seems like a way bigger change. What do you think ?

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
FYI @dpeng817

**Comment by RBrossard** [comment]
Hello and thank you for your quick answer !

I was aware that the config is also part of the final solid signature. However I was trying to point out a different issue: in order to get a relevant version, we might need to _execute_ something using some config as _argument_. Only putting the config in the version could not be enough.

Maybe an example would be better: Let's say I have two datasets: dataset_A and dataset_B. I store them, for simplicity, on two different  git-lfs repo: repo_A and repo_B. Finally, I have a dagster pipeline with memoization, starting with a factory solid `make_dataset` which takes the dataset name in the config (`'dataset_A'` or `'dataset_B'`) in the config and returns the actual dataset object. Now consider the following succession of events:
- I run the pipeline on both datasets A and B.
- I modify dataset_A on repo_A, for example adding some images.
- I run again the pipeline on both datasets.
Notice that I used the exact same config during the second run.

Ideally, during the second run with dataset_B, nothing should be recomputed as dataset_B is the same. However, the pipeline should run again when using dataset_A, as I modified the dataset. However, the config is the same (it just contains 'dataset_name': 'dataset_A', nothing about the status of repo_A), so how could dagster detect the change ?

My solution would be to use the sha1 of repo_A/master as the version of dataset_A and the sha1 of repo_B/master as the version of dataset_B. _I do not want to put that version in the config as it is not very handy_. Instead, in order to get that sha1 and put it in the version of the solid, I need to add something like `get_dataset_sha1(context.solid_config['dataset_name'])` in a piece of code that defines the version of the solid `make_dataset`. I don't think we can do that now. That's why I was suggesting to give access to the context in VersionStrategy.

What do you think ?

**Comment by dpeng817** [comment]
Ah, I see. I could definitely imagine that type of context object being useful. I think it would probably have to be a different context object than the one available to a solid during execution (because memoization resolution happens earlier in the chain), but it should definitely be possible to get validated config and initialized resources.

**Comment by RBrossard** [comment]
I am not familiar with the inner machinery of the project. But I have seen that get_solid_version is called in [resolve_version.py line 103](https://github.com/dagster-io/dagster/blob/56805e316e7a9f9d0e90426b84a1d863cae752d7/python_modules/dagster/dagster/core/execution/resolve_versions.py):
`solid_def_version = pipeline_def.version_strategy.get_solid_version(solid_def)`

Maybe we could just feed it a context argument there ? There is something looking like getting the solid context only a few lines later in the config resolution. Line 114:
`solid_config_version = resolve_config_version(resolved_run_config.solids[solid_name].config)`

Isn't `resolved_run_config.solids[solid_name].config` the config we are looking for ? I have no idea where the same happens for resources though.

**Comment by dpeng817** [comment]
That's correct, we definitely know config at version-resolution time. I think it would just be a matter of scoping a new context object (ie `SolidVersioningContext`) with the information ([SolidExecutionContext](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/execution/context/compute.py#L67) expects a bunch of stuff we won't have yet.

**Comment by RBrossard** [comment]
I see. Sadly, this is above the limit of my current understanding of dagster inner mechanics. I can still try to help if you point me in the right direction ? Not sure how relevant I would be though.

**Comment by sryza** [comment]
@RBrossard - if you'd be open to submitting a PR, we'd be happy to review and help get it in.  By "scoping a new context object", @dpeng817 just means defining a class called `SolidVersioningContext` with the relevant attributes (i.e. the config you mentioned, along with the solid def) and passing that to `get_solid_version` instead of just the `SolidDefinition`.

**Comment by RBrossard** [comment]
OK then, I'll have a look at the definition of context object and try to do a PR soon.

**Comment by RBrossard** [comment]
Sorry for the delay, I finally made that PR. I am waiting for your feedbacks.
