### ISSUE TITLE
dagit wrong type conversion

### ISSUE THREAD

**Issue by vmarunov** [dagster-io/dagster#4766]
## Summary
Unexpected type conversion in presets when using Dagit.

## Reproduction

Test solid and pipeline:

```python
from dagster import pipeline, solid, PresetDefinition


@solid(config_schema={'data': [str]})
def test_solid(context):
    ...
    return 0


@pipeline(
    name="test_pipeline",
    preset_defs=[
        PresetDefinition(
            name='dev',
            run_config={
                'solids': {
                    'test_solid': {
                        'config': {
                            'data': ['1234', '0148', '1418', '0183', '4567']}
                    }
                }
            },
            solid_selection=None,
            mode='default',
            tags={}
        )
    ]
)
def test_pipeline():
    test_solid()
```

This behavior reproduce for values, that starts with `0` and contains `8`.
This behavior is only in Dagit. Without dagit, the config is read without errors.

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/10268800/132641475-31e98077-c5dc-4d99-8244-d208d1c2ab98.png)

dagit version == 0.12.9

**Comment by yuhan** [comment]
Closing it as it's less related to Dagster but more related to the third party libs we depend on. Reopen if there's anything we can do.
