### ISSUE TITLE
[Content Gap] Document that Nothing inputs can be used with composite solids/graphs

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4780]
The [nothing dependencies documentation](https://docs.dagster.io/concepts/solids-pipelines/pipelines#order-based-dependencies-nothing-dependencies) doesn't reference that they can be used with composites.

**Comment by sryza** [comment]
When graph inputs no longer have dagster types, will this still be relevant?

**Comment by dpeng817** [comment]
> When graph inputs no longer have dagster types, will this still be relevant?

Hm. We'll probably need a separate way of specifying nothing deps on graphs then wont we

**Comment by sryza** [comment]
> Hm. We'll probably need a separate way of specifying nothing deps on graphs once that's the case I guess

What's an example of a scenario where we would need that?

**Comment by dpeng817** [comment]
Same places that nothing deps would currently be useful I'd imagine. I want all the steps in my graph to be dependent upon upstream step, without having to specify an additional input arg in my underlying fxn, right?

**Comment by sryza** [comment]
You can do something like this:

```
@op(ins={"a": In(Nothing)})
def op1():
    pass

@op
def op3():
    pass

@op(ins={"a": In(Nothing)})
def op2():
    pass

@graph
def subgraph(in1):
    op1(in1)
    op2(in2)

@graph
def outergraph():
    subgraph(op3())
```

**Comment by sryza** [comment]
What would the user code look like, ideally, to implement the scenario you're describing?

**Comment by dpeng817** [comment]
```python
@op(ins={"a": In(Nothing)})
def op1():
    pass

@op
def op3():
    pass

@op(ins={"a": In(Nothing)})
def op2():
    pass

@graph(ins={"a": NothingIn()}
def subgraph():
    op1()
    op2()

@graph
def outergraph():
    subgraph(op3())
```

Something like this. Not sure which is better or worse.

**Comment by sryza** [comment]
I don't think it's possible to do an equivalent of that with the pre-CRAG APIs.  I.e. there's no difference between:
* A composite solid input that isn't mapped to any solids inside the composite solid.
* Having no composite solid input.

I.e. there's no way to say "have every solid inside composite solid 1 execute after every solid inside composite solid 2", without wiring outputs to the inputs of the solids in composite solid 2.

**Comment by sryza** [comment]
Going to close this, because I don't think it's relevant once graphs don't have dagster types.
