### ISSUE TITLE
Logger doesn't insert arguments into message template

### ISSUE THREAD

**Issue by VladX09** [dagster-io/dagster#4787]
## Summary
`context.log` doesn't insert arguments into message template.
This doesn't look like expected behaviour because as `DagsterLogManager` inherits from `logging.Logger`

## Reproduction
**Example**
```python
# inside solid
bucket = "MY-BUCKET"
key = "MY_KEY"
context.log.info("Downloading %s:%s", bucket, key)
```
**Expected Result**
`Downloading MY-BUCKET:MY_KEY` in Dagit UI

**Actual Result**
`Downloading %s:%s` in Dagit UI

## Dagit UI/UX Issue Screenshots
<img width="1509" alt="Screenshot" src="https://user-images.githubusercontent.com/6130692/132876262-e2d72488-d6d7-4785-a182-45915c0b72b0.png">

## Additional Info about Your Environment
Dagster version: 0.12.10

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
@OwenKephart

**Comment by OwenKephart** [comment]
thanks for the report! this should be an easy fix and will get into this Thursday's release

**Comment by VladX09** [comment]
Thank you for such a fast fix!
