### ISSUE TITLE
Add terminate pipeline method

### ISSUE THREAD

**Issue by esztermarton** [dagster-io/dagster#4800]
## Use Case
Would like to call terminate pipeline request: https://docs.dagster.io/concepts/dagit/graphql#terminate-a-running-pipeline from a python client - makes sense to add this to the experimental python client https://docs.dagster.io/_apidocs/libraries/dagster-graphql#python-client

## Ideas of Implementation
Similar to other calls except with the appropriate graphql query

Suggested function signature:
def terminate_run(self, run_id: str) -> PipelineRunStatus:

## Additional Info
If this is of interest, happy to implement this.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
@esztermarton - this is definitely of interest.  We'd be happy to review a contribution if you're able to make one.

**Comment by dbatten5** [comment]
i'd be happy to try and take this one on

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/7443.
