### ISSUE TITLE
New Python logging functionality doesn't format messages

### ISSUE THREAD

**Issue by davidhyman** [dagster-io/dagster#4853]
## Summary
```python
LOG.debug("going to upload %s", path)
```
should render as:
```
DEBUG | going to upload /some/path/to/file.txt
```

but instead appears on dagit as:
```
DEBUG | going to upload %s
```
At a guess the handler is directly using `record.msg` instead of calling `record.getMessage()`, or something?

## Reproduction
```
python -m dagit --version
dagit, version 0.12.10
```

log from a solid
```python
import logging
import pathlib
LOG = _logging.getLogger()
path = pathlib.Path("/some/path/to/file.txt")
LOG.debug("going to upload %s", path)
```
with the python logging enabled in `dagster.yaml`
```yaml
python_logs:
  python_log_level: DEBUG
  managed_python_loggers:
    - root
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for the report @davidhyman .  We fixed this bug, and the fix will be included in the 0.12.11 release that goes out today.
