### ISSUE TITLE
[Content Gap] [InvokedSolidDynamicOutputWrapper].collect() not explained, in-order or not?

### ISSUE THREAD

**Issue by sebtrack** [dagster-io/dagster#4895]
## What content is missing

While the title says "Dynamic Mapping & Collect" the collect part is missing in the [API Reference](https://docs.dagster.io/_apidocs/dynamic).

I miss the information if one can be sure that the returned list is in order?

**Comment by erinkcochran87** [comment]
This has since been addressed - new/updated content is available here: https://docs.dagster.io/concepts/ops-jobs-graphs/dynamic-graphs#advanced-mapping-examples
