### ISSUE TITLE
dev loop / error discovery is difficult if "dagit -f" file fails to load file

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4902]
Right now, we just show a warning, but there's no reason to proceed if the repository doesn't load

**Comment by gibsondan** [comment]
This is actually different than how I think about it - I thought 'dagit -f' was just a shortcut for creating a workspace of size 1, not something with different failure semantics than 'dagit -w'.

If you go into the Status page in dagit, you can reload after fixing the problem and you'd be able to proceed without needing to restart Dagit. I do recognize how its confusing though, particularly since the default landing page doesn't give any indication that there was an error.

**Comment by yuhan** [comment]
How about pointing users to Dagit's Status page for resolving issues specified there? could maybe attach a link to the Dagit status page in the warning.

**Comment by sryza** [comment]
That makes sense how we got here, but I think it's still a pretty difficult first experience for users to have with Dagster.    The fact that we proceed to start the webserver makes it seem to the user that whatever error happened can't be that critical.  And it's an even worse experience if users have turned off warnings.

If all your repositories fail to load when you run "dagit -w", it could make sense for us to fail instead of proceeding that case as well?

**Comment by sryza** [comment]
In addition, perhaps, if all repositories fail to load, Dagit should re-direct you to a screen that says so and prompts you to address the problem?

**Comment by gibsondan** [comment]
I like the re-direct to the page with the error idea, that seems uncontroversial. (The workspace page could play that role)

Failing dagit if all repos fail to load makes sense to me in the local dev context, but does not make sense to me in the 'deployed in production' context, where it uses that same command.

**Comment by gibsondan** [comment]
(for example, if you are running gRPC servers and dagit separately in production, as we do in the helm chart, and dagit spins up before the gRPC servers do, I don't think dagit should crash - it can poll for the servers once they are ready and reload them)

**Comment by yuhan** [comment]
Falling Dagit if all repos fails to load sounds a bit too harsh to me. My hypothesis is that in many organizations the person deploying dagit (running `dagit` cli) is different from the person who can fix the repo code, so crashing dagit in the deployment phase seems too much and may harm the prod deployment experience.

**Comment by sryza** [comment]
Cool - sounds like the redirect solution is acceptable to everyone.  Moving this to Dagit for thoughts from @hellendag and @bengotow .
