### ISSUE TITLE
[Content Gap] Talk through recommended project folder structure

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4940]
Quote from a user about trying to come up with a folder structure for a Dagster project: "Puts me in that uncomfortable situation where I’m doing an engineering thing without knowing it’s the right thing.  I don’t want to create something that would be viewed by someone else as messy."

They cited these recommendations as really helpful for dbt: https://discourse.getdbt.com/t/how-we-structure-our-dbt-projects/355. It would be useful to provide something similar.

**Comment by erinkcochran87** [comment]
We now have this! 🎉  https://docs.dagster.io/guides/dagster/recommended-project-structure
