### ISSUE TITLE
Run worker fault tolerance

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#4993]
The run worker is the process dagster spins up to manage pipeline runs.

The faults

* If the run worker dies gracefully (receives an interrupt signal, has a grace period to clean up), it marks the pipeline as failed and exits. An example of this occurs when a K8s cluster is scaling down and the worker’s node is shutting down. 
* If the run worker dies ungracefully (no grace period), the run can be left hanging in an in progress state. An example is running out of memory and crashing. In more detail: https://github.com/dagster-io/dagster/issues/3705

Possible approaches

* Currently runs are managed by the ActiveExecution machinery which keeps state in memory. We need to be able to rebuild that state from the event log, so that a new run worker can pick up where an old one left off
* We need a mechanism for a new run worker to start when the previous failed. Some options are:
    * Monitoring daemon that checks on run workers and spins up replacements. Is this the run coordinator?
    * K8s-specific job retries (probably not, since we want to be cross platform?)

**Comment by rexledesma** [comment]
Addressed by https://docs.dagster.io/deployment/run-monitoring and https://docs.dagster.io/deployment/run-retries.
