### ISSUE TITLE
in asset graph, show assets that are materialized, but not defined

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5004]

**Comment by bengotow** [comment]
We might have to talk through how we want to do this one - we could show them as orphaned/ disconnected boxes, or we could try to use the runtime asset lineage, but the latter would take a lot of new performance work on the backend to fetch for all materializations efficiently.

**Comment by sryza** [comment]
@hellendag this issue refers to including nodes in the asset graph for assets that have no definition, just materializations. I believe we still don't do that, so reopening.

**Comment by sryza** [comment]
@bengotow I think closing this for now is fine. Longer term, I think there's the user story "help me find my orphaned assets" that I think something like this could help with.
