### ISSUE TITLE
Celery & Docker: `docker.errors.DockerException: Command 'dagster api execute_step {...}  returned non-zero exit status 1`

### ISSUE THREAD

**Issue by VladX09** [dagster-io/dagster#5008]
## Summary
I've tried to run a Dagster pipeline with the following configuration:
- Separate gRPC server for pipelines
- Docker run launcher
- Celery-Docker executor

And got an error without any useful logs. It just says that process failed with en exit code and I can't find any additional information anywhere.
So I can't even understand whether my configuration is wrong or it's a bug inside Dagster

```
celery-worker_1  | Traceback (most recent call last):
celery-worker_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
celery-worker_1  |     R = retval = fun(*args, **kwargs)
celery-worker_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
celery-worker_1  |     return self.run(*args, **kwargs)
celery-worker_1  |   File "/usr/local/lib/python3.8/site-packages/dagster_celery_docker/executor.py", line 282, in _execute_step_docker
celery-worker_1  |     docker_response = client.containers.run(
celery-worker_1  |   File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 848, in run
celery-worker_1  |     raise ContainerError(
celery-worker_1  | docker.errors.DockerException: Command 'dagster api execute_step "{\"__class__\": \"ExecuteStepArgs\",
 \"instance_ref\": {\"__class__\": \"InstanceRef\", \"compute_logs_data\": {\"__class__\": \"ConfigurableClassData\", 
\"class_name\": \"LocalComputeLogManager\", \"config_yaml\": \"base_dir: /opt/dagster/dagster_home/storage\\n\", 
\"module_name\": \"dagster.core.storage.local_compute_log_manager\"}, \"custom_instance_class_data\": null, 
\"event_storage_data\": {\"__class__\": \"ConfigurableClassData\", \"class_name\": \"PostgresEventLogStorage\", 
\"config_yaml\": \"postgres_db:\\n  db_name:\\n    env: DAGSTER_POSTGRES_DB\\n  hostname: postgresql\\n  password:\\n 
   env: DAGSTER_POSTGRES_PASSWORD\\n  port: 5432\\n  username:\\n    env: DAGSTER_POSTGRES_USER\\n\", 
\"module_name\": \"dagster_postgres.event_log\"}, \"local_artifact_storage_data\": {\"__class__\": \"ConfigurableClassData\",
 \"class_name\": \"LocalArtifactStorage\", \"config_yaml\": \"base_dir: /opt/dagster/dagster_home/\\n\", \"module_name\": 
\"dagster.core.storage.root\"}, \"run_coordinator_data\": {\"__class__\": \"ConfigurableClassData\", \"class_name\": 
\"QueuedRunCoordinator\", \"config_yaml\": \"{}\\n\", \"module_name\": \"dagster.core.run_coordinator\"}, 
\"run_launcher_data\": {\"__class__\": \"ConfigurableClassData\", \"class_name\": \"DockerRunLauncher\", \"config_yaml\": 
\"env_vars:\\n- DAGSTER_POSTGRES_USER\\n- DAGSTER_POSTGRES_PASSWORD\\n- 
DAGSTER_POSTGRES_DB\\nnetworks:\\n- dagster-celery-docker-bug_default\\n\", \"module_name\": \"dagster_docker\"},
 \"run_storage_data\": {\"__class__\": \"ConfigurableClassData\", \"class_name\": \"PostgresRunStorage\", \"config_yaml\": 
\"postgres_db:\\n  db_name:\\n    env: DAGSTER_POSTGRES_DB\\n  hostname: postgresql\\n  password:\\n    env: 
DAGSTER_POSTGRES_PASSWORD\\n  port: 5432\\n  username:\\n    env: DAGSTER_POSTGRES_USER\\n\", 
\"module_name\": \"dagster_postgres.run_storage\"}, \"schedule_storage_data\": {\"__class__\": \"ConfigurableClassData\", 
\"class_name\": \"PostgresScheduleStorage\", \"config_yaml\": \"postgres_db:\\n  db_name:\\n    env: 
DAGSTER_POSTGRES_DB\\n  hostname: postgresql\\n  password:\\n    env: DAGSTER_POSTGRES_PASSWORD\\n  port: 
5432\\n  username:\\n    env: DAGSTER_POSTGRES_USER\\n\", \"module_name\": \"dagster_postgres.schedule_storage\"}, 
\"scheduler_data\": {\"__class__\": \"ConfigurableClassData\", \"class_name\": \"DagsterDaemonScheduler\", \"config_yaml\": 
\"{}\\n\", \"module_name\": \"dagster.core.scheduler\"}, \"settings\": {}}, \"known_state\": {\"__class__\": 
\"KnownExecutionState\", \"dynamic_mappings\": {}, \"previous_retry_attempts\": {}}, \"pipeline_origin\": {\"__class__\": 
\"PipelinePythonOrigin\", \"pipeline_name\": \"demo_pipeline\", \"repository_origin\": {\"__class__\": 
\"RepositoryPythonOrigin\", \"code_pointer\": {\"__class__\": \"FileCodePointer\", \"fn_name\": \"demo_pipeline\", 
\"python_file\": \"/pipelines/demo.py\", \"working_directory\": \"/opt/dagster/dagster_home\"}, \"container_image\": 
\"pipelines-image\", \"executable_path\": \"/usr/local/bin/python\"}}, \"pipeline_run_id\": \"be551732-9fb6-4faf-b0cb-
3d4c44b3ce72\", \"retry_mode\": {\"__enum__\": \"RetryMode.DEFERRED\"}, \"should_verify_step\": false, 
\"step_keys_to_execute\": [\"hello\"]}"' in image 'pipelines-image' returned non-zero exit status 1
```

## Reproduction
I've prepared full environment for reproduction: https://github.com/VladX09/dagster-celery-docker-bug/tree/non-zero-exit-example
Just run follow the README.md
You will see this error in executor logs and Dagit UI.

## Additional Info about Your Environment
MacOS 11.4
Docker 3.0.1 (engine 20.10.0)

Also reproduces in production environment.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @VladX09, thanks for including a repro environment, that's really useful for us to figure out the problem.

However I see this when I run the pipeline:
bug-daemon-1         | 2021-10-02 16:41:23 - QueuedRunCoordinatorDaemon - ERROR - Caught an error for run 7116ce69-7d07-4291-bfa2-6fb9f8fbe0cf while removing it from the queue. Marking the run as failed and dropping it from the queue: docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/9876c368c277ae502a9dd6e036b4c42bea5f34c55f1f2433df8e6e1bf9f7ac05/start: Not Found ("network dagster-celery-docker-bug_default not found")

Is there a missing step to set up that network / networks entry in the docker-compose file? (could be a docker version compatibility issue too potentially)

**Comment by VladX09** [comment]
Hi @gibsondan, sorry thats my fault, i hardcoded network using docker-compose naming rules (which uses project directory). but I've mistaken naming my GitHub repo.

Please, rename your pulled directory as `dagster-celery-docker-bug` (without `-demo`).
I've also renamed my repo for future pullings/

**Comment by gibsondan** [comment]
Ok, there are a couple of things going on here.

- The celery docker executor calls auto_remove=True when launching steps in containers, making it hard to pull logs when teh container fails. We'll change it to be configurable on the executor, so that you can set it to False when you want to pull logs from failed step containers.
- The most likely reason for a step container to fail immediately like that without anything useful in the event log is that it can't load the instance to write errors to the event log in postgres, usually because it's missing environment variables and/or is using the wrong network. In this case, that's what was happening - the executor needs to configure the list of env_vars to pass in, just like the run launcher (this is a bit inelegant - we'd like to make this better, maybe by automatically passing config from the run launcher through to the steps). But for now the executor needs to set the env_vars and network config options too in order for the step containers to load.

That was enough to get the instance to load and the step container to stop failing without giving any useful information. To get the steps to actually complete, we also needed to pass in the AWS creds, which meant making them accessible on the celery worker container and adding them to the executor config as well.

Overall this set of changes should be enough to get the pipeline to run:
```
diff --git a/docker-compose.yml b/docker-compose.yml
index c583df5..6464931 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,6 +6,8 @@ x-common-env: &common-env
   DAGSTER_POSTGRES_USER: "postgres_user"
   DAGSTER_POSTGRES_PASSWORD: "postgres_password"
   DAGSTER_POSTGRES_DB: "postgres_db"
+  AWS_ACCESS_KEY_ID: "minioAdmin"
+  AWS_SECRET_ACCESS_KEY: "minioAdmin"
 
 x-image: &image
   build:
@@ -108,8 +110,6 @@ services:
     environment: 
       <<: *common-env
       DAGSTER_CURRENT_IMAGE: pipelines-image
-      AWS_ACCESS_KEY_ID: "minioAdmin"
-      AWS_SECRET_ACCESS_KEY: "minioAdmin"
 
     volumes: 
       - ./pipelines:/pipelines
diff --git a/pipelines/demo.py b/pipelines/demo.py
index 883809f..25d0bd5 100644
--- a/pipelines/demo.py
+++ b/pipelines/demo.py
@@ -40,6 +40,14 @@ default_preset = dg.PresetDefinition(
                 "config": {
                     "docker": {
                         "image": "pipelines-image",
+                        "env_vars": [
+                            "DAGSTER_POSTGRES_USER",
+                            "DAGSTER_POSTGRES_PASSWORD",
+                            "DAGSTER_POSTGRES_DB",
+                            "AWS_ACCESS_KEY_ID",
+                            "AWS_SECRET_ACCESS_KEY"
+                        ],
+                        "network": "dagster-celery-docker-bug_default",
                     },
                     "broker": "pyamqp://rabbitmq:rabbitmq@rabbitmq:5672/dagster",
                 },
```

**Comment by VladX09** [comment]
Hmm. I understand what was wrong. Thank you very much for such a fast answer =)

One thing I don't clearly understand is who "sends" environment variables to executors on Celery worker.
I mean:
- Everything is clear for gRPC server. Variables are set directly to the server's container (in this case in `docker-compose.yml`
- Variables for container, created by `DockerRunLauncher`, are taken from daemon's env according to the corresponding section of `dagster.yml`, aren't they?
- So what is the source for variables listed in pipelines runtime config?

**Comment by VladX09** [comment]
OK, I've understood, variables for solid's container are forwarded from Celery worker node.
Anyway it will be nice to have an option to disable `auto_remove`

**Comment by johannkm** [comment]
Closing since it looks like this is resolved (plenty of docs works to do though). Please reopen if that's not the case
