### ISSUE TITLE
dagster.serdes.errors.DeserializationError: Attempted to deserialize class "ExternalTargetData" which is not in the whitelist. This error can occur due to version skew, verify processes are running expected versions.

### ISSUE THREAD

**Issue by Minivolk02** [dagster-io/dagster#5012]
## Summary

This error enabled when i execute senors in kubernetes.
When i execute sensors just as service in docker, sensors is working in same code.

## Dagit UI/UX Issue Screenshots

![image](https://user-images.githubusercontent.com/27731703/135836754-df2d42e5-262d-4f24-8b5a-5fccb5fe3fef.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
This error usually occurs when your dagster versions between your user code/dagit server/daemon are not in sync, as the error message says.
