### ISSUE TITLE
Material icons update broke icon loading

### ISSUE THREAD

**Issue by NicolasPA** [dagster-io/dagster#5026]
## Summary

https://github.com/dagster-io/dagster/pull/4867 in 0.12.12 broke icon loading on Dagit on my PC without internet.
![image](https://user-images.githubusercontent.com/22459427/136045611-36c5c221-8da5-4b10-b9c8-560c83072f6e.png)

Does this update require an internet connection to download the icons while it wasn't the case before?

It's happening on Chrome 79 (company managed) or Edge 85 on a PC without internet.
Since it's not allowed internet access, the Python dependencies are passed through a network drive.
This wasn't a problem with previous version:
![image](https://user-images.githubusercontent.com/22459427/136048400-0de24eae-b86a-4cde-9de9-06a128683abf.png)

It does load correctly on my other PC with Chrome 93 and access to the internet.
![image](https://user-images.githubusercontent.com/22459427/136048960-cb52d85d-28ff-46d3-a733-3cda9553dc78.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Ahh man, thank you for flagging this - I think that this will be resolved in the next release, we actually switched back to locally sourced SVGs because of some other issues with the new icon font.

**Comment by NicolasPA** [comment]
This issue is not relevant anymore because of the new design in 0.13, but the interface is still broken for similar reasons, I have created a new issue: https://github.com/dagster-io/dagster/issues/5515
