### ISSUE TITLE
`celery_docker_executor`: add `container kwargs` parameter

### ISSUE THREAD

**Issue by VladX09** [dagster-io/dagster#5079]
## Use Case
In our usecase it was necessary to download incoming data somewhere and parse it from different solids on different Celery workers (to avoid downloading overhead but still be able to parse data in parallel). We wanted to mount shared volume to workers but were blocked by the lack of additional container parameters inside `celery_docker_executor`'s config. 

## Ideas of Implementation
It will be very helpfull to have all configuration parameters for Docker container like it's already made in `DockerRunLauncher` via `container_kwargs`.

Thank you!

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by Elselot** [comment]
Any news on this issue?
