### ISSUE TITLE
Better documentation of using config with graphs

### ISSUE THREAD

**Issue by marcosfelt** [dagster-io/dagster#5142]
## What content is missing
Currently, the [ops/graphs migration guide](https://docs.dagster.io/guides/dagster/graph_job_o) is missing the proper explanations for using configuration in `execute_in_process`

## Type of the content
I had to look at the source code to figure out that you pass your configuration as follows.

Taking a modified example from the top of the doc:
```python
from dagster import graph, op

@op(config_schema: {"param": str})
def do_something():
    ...


@graph
def do_it_all():
    do_something()
```

You pass 

```python
do_it_all.execute_in_process(config={"do_something": {"config": {"param": "hello"}}})
```

This is because `execute_in_process` wraps the config in an "ops" dictionary.

## Anything else?
Nope! Let me know if you want me to make the change.

#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
Yes - this behavior has been changed to mirror that which happens for an equivalent job, but it may not have made it into the latest release.

**Comment by dpeng817** [comment]
Closing because the behavior has changed to match the migration guide more closely
