### ISSUE TITLE
Should be able to sort date partitions in reverse in the playground

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#5216]
This is typically more useful. Could specify it when defining the partition set, or toggle in UI.

**Comment by sryza** [comment]
Currently, you can click on the A-Z inside the partition selector to sort in reverse.  However, it's probably sensible for the default to be a reverse sort, given that most partitions are time partitions, and you usually want to run the most recent partition.

**Comment by hellendag** [comment]
The feature already exists, as noted by @sryza -- feel free to reopen if there's more needed here.
