### ISSUE TITLE
Discussion: solid uniqueness

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#523]
Just putting placeholder issue here to discuss issues around solid uniqueness. There are a few tradeoffs to weight here. 
See:
https://github.com/dagster-io/dagster/pull/493

**Comment by Aylr** [comment]
I'm looking forward to a discussion on this

**Comment by schrockn** [comment]
@Aylr after our call yesterday it seems like you are onboard with this. are you ok with us closing this out and then eliminating the uniqueness opt-out once it's utility for your 0.2.8 --> 0.3.x migration is done?

**Comment by Aylr** [comment]
Yes I am! I think that approach makes total sense. No sense dragging along legacy cruft.

**Comment by schrockn** [comment]
@Aylr i'll wait you for you (or someone else fro SC) word to actually delete it so you don't have a to couple a solid name-mangling scheme with getting stuff up and running in new dagit etc.

**Comment by Aylr** [comment]
Sounds great! I'd prefer those to be separate!
