### ISSUE TITLE
can't backfill over a job with nested graphs

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5244]
reported by on slack: https://dagster.slack.com/archives/C01U954MEER/p1634136820190600

error:
```
dagster.core.errors.DagsterExecutionStepNotFoundError: Can not build subset plan from unknown step: create_full_taker_answers_table
```

**Comment by sryza** [comment]
@yuhan - is this addressed by your nested op selection work?

**Comment by prha** [comment]
This was mostly a step selection UI bug, that is now addressed in the new partitions page.
