### ISSUE TITLE
hourly partitions are cut off on the partitions page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5281]
Hourly partitioned jobs are one of the first-class kinds of partitioned jobs we support with our Python APIs.  They should render reasonably in Dagit.

![image](https://user-images.githubusercontent.com/654855/138001861-0d82d7d3-ca3d-4c88-818f-97fd63fcc62f.png)

**Comment by bengotow** [comment]
Sounds good! I think we can improve the rendering of these. Would it be possible to put a space in the partition names so these parse as dates? It's a bit strange that there's a dash in there.

**Comment by bengotow** [comment]
This is resolved by https://github.com/dagster-io/dagster/pull/5536. The header now just expands to fit the text properly.


![Uploading Screen Shot 2021-11-04 at 11.13.57 AM.png…]()

**Comment by sryza** [comment]
@bengotow - awesome. I believe the reason we opted against spaces was that sometimes these need to be typed out on the command line, and spaces would require quoting.

I like your other suggestions, however, unfortunately I think at this point the ship has sailed, because the strings correspond to tags that are stored in the database, so we'd need to force users to do a big database migration if we wanted to change the format.

**Comment by bengotow** [comment]
The fix for this has merged!
