### ISSUE TITLE
default graph/job def zoom is unnecessarily far out

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5325]
The default zoom for a job's graph leaves a lot of whitespace:
![image](https://user-images.githubusercontent.com/654855/138305225-adf584f2-434c-4d85-9eef-fa4ef888af43.png)

This zoom level (which I got to manually) is a lot more informative:

![image](https://user-images.githubusercontent.com/654855/138305161-23afd0bc-20fe-4903-a796-13807683d729.png)

**Comment by bengotow** [comment]
Our playground pipelines are unrealistically small and I think the current default is probably best for most use cases, but I think we can automatically select an appropriate zoom level - will take a look!

**Comment by bengotow** [comment]
The fix for this has merged!

**Comment by sryza** [comment]
FWIW I do think it's fairly common to have small DAGs in real life.

I took a look at the change, and it looks perfect.
