### ISSUE TITLE
 Highlight inputs and outputs when dependency edge is highlighted in dag viewer

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#537]
We've talked about this before, but let's get this done.

![screenshot 2019-01-04 09 41 35](https://user-images.githubusercontent.com/28738937/50702166-f5b98300-1004-11e9-8d9f-4873cf393518.png)

What we really need to do is to highlight the input and output boxes so that we know which one the dep is connected too. Right now it is easy to get in the situation where one does not know which one is being referred to.

cc'ing @Aylr  to get any feedback/thoughts

**Comment by Aylr** [comment]
This is going to be excellent. Will this only occur on clicking the edge? Is there a case for highlighting this when an individual input or output is selected? That could get confusing vs a solid selection though.

**Comment by schrockn** [comment]
I was thinking just the edge but we could play with it

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by bengotow** [comment]
👍  I'll see if we can make hovering over the input and output boxes activate the highlighting as well.

**Comment by schrockn** [comment]
done
