### ISSUE TITLE
Step selector overlaps gantt chart

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5383]
![image](https://user-images.githubusercontent.com/654855/138781471-265879cc-d222-49ca-80e7-d5828b41189f.png)

Zoom in on https://demo.elementl.show/instance/runs/cb122bed-1147-4b1e-b65a-7f3314cfacad?logKey=build_comment_stories

**Comment by bengotow** [comment]
Hmm I think there's margin at the bottom so you can scroll down and resolve this?

**Comment by bengotow** [comment]
cc @braunjj  not sure what we should do about this - the viz flows under the bottom bar so things overlap a bit here. There's a margin at the bottom so you can view the bottom of the visualization without the overlap, but we could also make the bottom bar opaque if that's better?

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1037212/140377875-e97b36b9-3441-42c0-8920-e3dd7224b9bb.png">

<img width="984" alt="image" src="https://user-images.githubusercontent.com/1037212/140377887-9713a688-a479-49cd-8ae8-d6ad4c6431d0.png">

**Comment by braunjj** [comment]
could we had a subtle gradient from solid light gray to transparent white like this?
![image](https://user-images.githubusercontent.com/2798333/140426770-fe38a865-2fa2-4b2b-969b-b6ea55bbc2ae.png)
