### ISSUE TITLE
Interacting with the launch backfill modal is painfully slow when many partitions

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5408]
Things that are slow:
- Opening the launch backfill modal
- Clicking on partitions in the launch backfill modal

**Comment by bengotow** [comment]
I think I can address the latter of the these two pretty easily and the first may be a graphql resolver issue, taking a look.

**Comment by bengotow** [comment]
This should be largely addressed by the PR above! If it's still slow we'll need to investigate some graphql perf improvements.
