### ISSUE TITLE
Bigger click target for reloading repository

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5411]
At times, reloading a repository is part of my core dev loop. With the new UI, I often find myself needing to break flow and carefully aim to hit the click target.

**Comment by bengotow** [comment]
Hey gang, +1 for pushing the shortcuts a bit more but I agree this is very hard to hit. I went through and made reload buttons in the following four places have larger click targets (+8px on all sides) so it's easier to hit them. This makes them about the size of normal buttons in terms of clickability.

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/1037212/140668523-839a65ef-2e5c-454a-95a3-df7f7e8546c4.png">

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/1037212/140668589-39b99db6-758c-428c-9471-2e85370fe8e8.png">

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/1037212/140668848-df07f7e3-fc04-42a9-8398-e6830d803b57.png">

<img width="440" alt="image" src="https://user-images.githubusercontent.com/1037212/140668850-53dbafa0-0926-4a19-a507-ae016231d2e0.png">

**Comment by sryza** [comment]
Thanks @bengotow

**Comment by bengotow** [comment]
This has been addressed
