### ISSUE TITLE
Partition graph titles are not displayed

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#5423]
## Summary
Would expect the title string "Execution Time by Partition" to be displayed somewhere for the react component:
```
        <PartitionGraph
          isJob={isJob}
          title="Execution Time by Partition"
          yLabel="Execution time (secs)"
          runsByPartitionName={runsByPartitionName}
          getPipelineDataForRun={getPipelineDurationForRun}
          getStepDataForRun={getStepDurationsForRun}
          ref={durationGraph}
        />
```

**Comment by bengotow** [comment]
I'm addressing this (at least with a basic quick fix) in https://github.com/dagster-io/dagster/pull/5536. Below all the graphs the X label was just "Partition", so I think it makes sense to show the title of the graph there instead.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/1037212/140378754-751d5b40-ea63-4ff0-915b-c6f2c4b7d688.png">

**Comment by bengotow** [comment]
This has been fixed
