### ISSUE TITLE
[Documentation Feedback] Problem on /concepts/solids-pipelines/solids page

### ISSUE THREAD

**Issue by knowlix** [dagster-io/dagster#5456]
Main Concept page contains this link ("Ops, Jobs and Graphs" section) which goes to 404

**Comment by yuhan** [comment]
Thank you for the report! It's fixed in https://github.com/dagster-io/dagster/pull/5464
Meanwhile the new URL is https://docs.dagster.io/concepts/ops-jobs-graphs/ops
