### ISSUE TITLE
[Documentation Feedback] Problem on /concepts/solids-pipelines/solids page

### ISSUE THREAD

**Issue by KevinHaynesLyn** [dagster-io/dagster#5468]
From the Main Concepts page, I clicked the tile for Ops, Jobs, & Graphs, but it directed me to https://docs.dagster.io/concepts/solids-pipelines/solids which resulted in a 404: Not Found

**Comment by KevinHaynesLyn** [comment]
All of the other tiles on the Main Concepts page work as expected.

**Comment by yuhan** [comment]
Thank you for the report! It's fixed in https://github.com/dagster-io/dagster/pull/5464
Meanwhile the new URL is https://docs.dagster.io/concepts/ops-jobs-graphs/ops
