### ISSUE TITLE
Running op name missing from Gantt Chart

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#5486]
## Summary

> it seems unintentional that the running op name is not shown here? on flat view and waterfall view, but not time view

![image](https://user-images.githubusercontent.com/2798333/139747606-60f455fa-5b44-4759-927d-d1f42804d7d5.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
This is fixed in https://github.com/dagster-io/dagster/pull/5544!

**Comment by bengotow** [comment]
The fix for this has merged!
