### ISSUE TITLE
link in default slack_on_failure message does not render as link

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5511]
![image](https://user-images.githubusercontent.com/654855/139966745-9d99d8de-93be-44ab-8e44-4105690893db.png)

**Comment by sryza** [comment]
@yuhan - mind taking a look?

**Comment by yuhan** [comment]
https://github.com/dagster-io/internal/pull/503 should fix it but it hasn't been deployed yet - internal bk is slow now
