### ISSUE TITLE
Pure local helm installation? kubernetesjsonschema

### ISSUE THREAD

**Issue by RMHogervorst** [dagster-io/dagster#5517]
## Summary

I work on a kubernetes cluster with limited internet access and no helm. I have a small notebook server that can run kubectl commands and where I can upload and download files.
I first tried to build on top of the docker examples but couldn't get it to work.
So I tried a helm approach:

* I installed helm locally on the machine
* I downloaded and transfered a specific version of dagster helm charts to that machine
* I modified the settings in values.yaml
* I ran `helm install dagster --generate-name` but it failed for one specific reason:

```
Get "https://kubernetesjsonschema.dev/v1.15.0/  ...... (you get the idea) _definitions.json  Connection reset by peer.

```
Helm tries to check something on the internet and is not allowed.
I could modify the chart and download these definitions to the project but is there a way to point to a local json file in values.schema.json?

Or is there a simpler approach?

## Additional Info about Your Environment

I am able to build dockerfiles, use those, and install python packages in this environment.
Kubernetes 1.21.5

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by RMHogervorst** [comment]
I found out you can  download the version 15 and 16 jsons and upload them. You can then modify the values.schema.json to point to local files. `"$ref": "./definitions.json#blablablalbal`

**Comment by RMHogervorst** [comment]
Get validation errors though: annotations must be canonical,

**Comment by johannkm** [comment]
Any further updates with this? Another (non-ideal) approach could be to render the templates somewhere with internet access, then just apply them with kubectl.

**Comment by johannkm** [comment]
There's an open helm issue for this
https://github.com/helm/helm/issues/10398

**Comment by johannkm** [comment]
Closing because I think we want to continue to point at https://github.com/instrumenta/kubernetes-json-schema for k8s validation. Hoping that the Helm issue gets resolved (maybe I'll take a look) and that the workarounds are acceptable in the meantime.

**Comment by Khalid-Nowaf** [comment]
I have the same issue with airgapped setup.

**Comment by raayu83** [comment]
Same issue here...
