### ISSUE TITLE
Dagit previous runs ordering

### ISSUE THREAD

**Issue by esselius** [dagster-io/dagster#5579]
## Summary

Dagit ordering of previous runs looks wrong to me, I think I've seen this before but couldn't find a github issue related to it, looks like it's ordered by run id rather than timestamp

## Dagit UI/UX Issue Screenshots

![Screenshot 2021-11-09 at 08 29 28](https://user-images.githubusercontent.com/1178200/140881175-818a09a3-813b-489d-999c-fa35122e4083.png)

## Additional Info about Your Environment

dagster 0.13.4

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for the bug report @esselius - this looks like an issue.
