### ISSUE TITLE
Cryptic error on op.configured

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#5580]
## Summary

When misconfiguring an op via configured, we get a cryptic error like this
<img width="883" alt="Screen Shot 2021-11-08 at 3 54 12 PM" src="https://user-images.githubusercontent.com/1425877/140944689-d1c06655-29e5-4057-a6ae-78e647f52628.png">

I would expect an [DagsterInvalidConfigError](https://docs.dagster.io/_apidocs/errors#dagster.DagsterInvalidConfigError) instead

## Reproduction

```python
import dagster

@dagster.op(config_schema=dagster.Shape(fields={"dummy": str}))
def my_op(context):
    return None

my_op2 = my_op.configured({"dummy_completely_different_string": "foo"}, name="my_op2")

@dagster.job
def my_job():
    my_op2()
```

## Additional Info about Your Environment

dagster 0.13.4

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @amarrella - a fix is in-progress.

**Comment by clairelin135** [comment]
Thanks @amarrella, this bug has been fixed as of https://github.com/dagster-io/dagster/pull/5633.
