### ISSUE TITLE
Dagster daemon polling interval improvements

### ISSUE THREAD

**Issue by NakulK48** [dagster-io/dagster#5581]
## Use Case

As things stand the daemon polls every 30 seconds from (as far as I can tell) when it starts up.

Realistically it seems likely that schedules will be set up to run on the minute (if not the hour) - indeed, cron doesn't really have the functionality to go any more granular than this. If you're unlucky enough to get a daemon poll at 11:59:59, a job scheduled for 12:00 won't start until 12:00:29.

## Ideas of Implementation

I think that either as default behaviour or a configurable option, the daemon should poll on the minute and half past the minute, whenever it started - purely for scheduling; sensors could probably stay as they are.

Additionally it might be useful to allow the configuration of the daemon poll interval in `dagster.yaml`

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
This was improved in https://github.com/dagster-io/dagster/pull/5998 - as of the next release on 1/6/21 the scheduler will poll every 5 seconds instead of every 30 seconds.
