### ISSUE TITLE
[Documentation Feedback] Problem on /deployment/guides/dask page

### ISSUE THREAD

**Issue by bing007** [dagster-io/dagster#5599]
Hi there, I'm new to dagster and trying out the `dask_executor` with this guide but always end up with two invalid config errrors: `Error 1: Received unexpected config entry "in_process" at path root:execution` and `Error 2: Missing required config entry "config" at path root:execution`.
I have tried passing in the config via both the dagit interface and the job attribute directly, but neither works. The dask cluster and the azure storage as IOManager are working fine.
The issue can be reproduced with `local` cluster config.

Additionally, the `dask` config under `execution` is no longer valid anymore.

**Comment by bing007** [comment]
There was a separate discussion in [Slack](https://dagster.slack.com/archives/C01U954MEER/p1636545839087900) with [Daniel](https://dagster.slack.com/team/U016C4E5CP8). In short, it can be reproduced in version 0.13.4 and 0.13.0. It's not reproducible in 0.12.15. The team is aware of the issue. Thanks!

**Comment by yuhan** [comment]
This was fixed in https://github.com/dagster-io/dagster/pull/5622
