### ISSUE TITLE
execute_pipeline migration (dagster 0.13.4)

### ISSUE THREAD

**Issue by bernardocortez** [dagster-io/dagster#5607]
## Summary
The **execute_pipeline** method is not working on Dagster 0.13.2 when trying to run an op on a Databricks cluster.

## Reproduction
Consider the following code sample, defining op "test_op".

```
prod_adls2 = {
    "pyspark_step_launcher": databricks_pyspark_step_launcher,
    "pyspark": pyspark_resource,
    "adls2": adls2_resource,
    'io_manager': adls2_delta_io_manager,
    "adls_csv_loader" : adls_csv_loader,
    "database": adls_delta_resource,
}

@op(required_resource_keys={"pyspark_step_launcher", "pyspark"})
def test_op(context):
    context.log.debug('Op started')
```

On previous Dagster versions (at least until 0.12.2), the way to execute this op (solid) would be to wrap it in a pipeline and use **execute_pipeline**+**reconstructable.**
`execute_job(reconstructable(test_pipeline), mode="prod_adls2", run_config=run_config)`

Nowadays ([dagster 0.13.2](https://docs.dagster.io/_apidocs/execution#reconstructable-jobs)), we can either define a job or a graph and then use the _to_job_ method.

I tried the following approaches, which produced the corresponding errors.

1) 
```
@job(resource_defs=prod_adls2)
def test_job():
    test_op()

test_job.execute_in_process(run_config=config)
```

**Error**:
> dagster.check.ParameterCheckError: Param "recon_pipeline" is not a ReconstructablePipeline. Got <dagster.core.definitions.pipeline_base.InMemoryPipeline object at 0x7f2f43fe10a0> which is type <class 'dagster.core.definitions.pipeline_base.InMemoryPipeline'>

2) 
`reconstructable(test_job).execute_in_process(run_config=config)` or `execute_pipeline(reconstructable(test_job), run_config=config)`

**Error**:
> dagster.core.errors.DagsterInvariantViolationError: Reconstructable target was not a function returning a job definition, or a job definition produced by a decorated function. If your job was constructed using ``GraphDefinition.to_job``, you must wrap the ``to_job`` call in a function at module scope, ie not within any other functions. To learn more, check out the docs on ``reconstructable``: https://docs.dagster.io/_apidocs/execution#dagster.reconstructable

3)
`reconstructable(make_test_job).execute_in_process(run_config=config)`

**Error**:
> AttributeError: 'ReconstructablePipeline' object has no attribute 'execute_in_process'

4) 
`execute_pipeline(reconstructable(make_test_job), run_config=config)`

**Error**:
> dagster.core.errors.DagsterUnmetExecutorRequirementsError: You have attempted to use an executor that uses multiple processes with an ephemeral DagsterInstance. A non-ephemeral instance is needed to coordinate execution between multiple processes. You can configure your default instance via $DAGSTER_HOME or ensure a valid one is passed when invoking the python APIs. You can learn more about setting up a persistent DagsterInstance from the DagsterInstance docs here: https://docs.dagster.io/deployment/dagster-instance#default-local-behavior

## Am I missing the point or was execute_pipeline "mismigrated"?
Thanks!

## Dagit UI/UX 
Oddly enough, dagit does manage to run the job.

## Environment
Python 3.9.5
dagster 0.13.2

**Comment by dpeng817** [comment]
Hey Bernardo! Thanks so much for the comprehensive issue. In general, `execute_in_process` does not work with contexts where `reconstructable` is required. Specifically, this is when using a step launcher, or using dagstermill.

We don't currently have a great answer for python-level execution with dagstermill / step launchers. For now, the solution is to keep using `reconstructable` / `execute_pipeline`, but it seems like you're running into trouble there as well.

For example (2): We would expect `execute_pipeline(reconstructable(test_job), run_config=config)` to work. Could you post a full code snippet for this one? Would be useful for debugging purposes.
For example (1) and (3): We wouldn't expect these to work for the aforementioned reasons.
For example (4): For this one I believe the issue is that `execute_pipeline` defaults to creating an ephemeral dagster instance. If you set `DAGSTER_HOME` and then pass in `DagsterInstance.get()` as the instance value, it should work.

**Comment by bernardocortez** [comment]
Hey Christopher! Thanks for the swift help.

Here is the minimal code snipet to reproduce the situation you asked for.

```
from dagster import job, op
from dagster.core.definitions.reconstructable import reconstructable
from dagster.core.execution.api import execute_pipeline


@op
def test_op(context):
    context.log.debug('Op started')

@job
def test_job():
    test_op()

execute_pipeline(reconstructable(test_job))
```

This results in the following error:

> dagster.core.errors.DagsterInvariantViolationError: Reconstructable target was not a function returning a job definition, or a job definition produced by a decorated function. If your job was constructed using ``GraphDefinition.to_job``, you must wrap the ``to_job`` call in a function at module scope, ie not within any other functions. To learn more, check out the docs on ``reconstructable``: https://docs.dagster.io/_apidocs/execution#dagster.reconstructable

I cannot get this error, because the `reconstructable`'s target is, in fact, a job definition (`test_job`).

Can you help?

**Comment by bernardocortez** [comment]
## UPDATE
After some investigation, I believe the problem is that JobDefintion objects have no __name__attribute, thus failing in condition `seven.is_function_or_decorator_instance_of` the `reconstructable` method.

Plus, everything still works with the @pipeline decorator, making it very likely to be a migration bug.

## Environment
I have upgraded dagster to 0.13.4, with no impact on the issue

**Comment by dpeng817** [comment]
@bernardocortez thanks so much for posting the example. After further examination, this case is indeed a bug. Was able to put up [this](https://github.com/dagster-io/dagster/pull/5671) fix, which should go in by next release. Thanks again for surfacing!

**Comment by bernardocortez** [comment]
> @bernardocortez thanks so much for posting the example. After further examination, this case is indeed a bug. Was able to put up [this](https://github.com/dagster-io/dagster/pull/5671) fix, which should go in by next release. Thanks again for surfacing!

Thanks! Has this release gone out already?

**Comment by dpeng817** [comment]
@bernardocortez yes, this has gone out!
