### ISSUE TITLE
Kubernetes deployment with example-user-code  ImagePullBackoff - tag doesn't default to helm chart version

### ISSUE THREAD

**Issue by jonasdebeukelaer** [dagster-io/dagster#5620]
## Summary

When deploying on Kubernetes with default helm values.yaml, the example-user-code image tag is `0.0.1-dev` which doesn't exist.

In `value.yaml `
Changing from 
```
repository: "docker.io/dagster/user-code-example"
tag: ~
``` 
to 
```
repository: "docker.io/dagster/user-code-example"
tag: 0.13.4
```
fixed the issue for me.

The associated comment suggests that should be the version that gets pulled anyway though:
```
# When a tag is not supplied, it will default as the Helm chart version.
```
(version I'm using is 0.13.4)

## Reproduction

```
kubectl create namespace dagster-sandbox
helm upgrade --install dagster dagster/dagster --namespace dagster-sandbox
kubectl -n dagster-sandbox get pods # shows image pull backoff
```

## Additional Info about Your Environment
helm chart version `0.13.4`

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
This should be resolved in our latest release.
