### ISSUE TITLE
Users often encounter `[Network error] Unexpected token < in JSON at position 0 when trying to load repositories`

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#5625]
## Summary

From Slack:
max:dagster: Today at 11:39 AM
gopuff are seeing this network error intermittently: [Network error] Unexpected token < in JSON at position 0 when trying to load repositories and it's eroding confidence
2 replies

max:dagster:  5 hours ago
would be great if we could recover better from this (it's a very standard thing to see in dagit)

max:dagster:  5 hours ago
also difficult on demos

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
I'll go ahead and close this since @prha's change eliminates the toaster.
