### ISSUE TITLE
Toggle between UTC and localized for timestamps in Dagit

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#5626]
## Summary

Some users are confused when timestamps are shown in local time vs. just displaying UTC by default. Want a way to toggle between utc and local

Some users also had trouble finding the timestamps behind the little i icon

Also – It is a little confusing that some information like the health page shows the timezone, while runs page does not.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Does the toggle in `/settings` solve this issue?

**Comment by braunjj** [comment]
I don't think so. Although – I didn't even realize that it was a toggle on the settings page – which is probably something we should also address here

**Comment by hellendag** [comment]
Where are users seeing UTC? Timestamps should be using their timezone setting from `/settings`, which should automatically use their local time.

![image](https://user-images.githubusercontent.com/2823852/142698844-8fdee9c5-4a2c-43e6-bf10-1b042e01c6bb.png)

The only non-local timezones that I think a user might expect to see are execution times for Schedules, which have their own execution timezones. This week I landed a change that surfaces the execution timezone for these cases, and shows the user's local time in the tooltip.

**Comment by hellendag** [comment]
Let's add the execution timezone to the "Schedule" column.
