### ISSUE TITLE
Switching between the panels is confusing in the run debugger

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#5628]
## Summary

From Max –
"user is having trouble in the new Dagit UI -- there are buttons to show only the top pane or only the bottom pane in Dagit, but it's hard to figure out how to recover from these states"

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Possibly dumb question: do we actually need/want those toggle buttons? It seems like users can pretty easily drag the divider to the height they want. cc @bengotow for context

**Comment by braunjj** [comment]
I actually think it's just missing a third option where a user can reset it to the default split state, like this:

![image](https://user-images.githubusercontent.com/2798333/143064131-4b9e7e39-99d1-4a17-929c-8951655369eb.png)

**Comment by hellendag** [comment]
Works for me!
