### ISSUE TITLE
Dagit outputs undifferentiated for branching ops

### ISSUE THREAD

**Issue by clairelin135** [dagster-io/dagster#5640]
## Summary
- Op yields multiple optional outputs, unclear which output is sent as input to which downstream op.
- Can see which output maps to which input on mouseover but unclear in the UI
- Could have other cases where the same UI issue exist

<img width="980" alt="Screen Shot 2021-11-12 at 2 28 32 PM" src="https://user-images.githubusercontent.com/29110579/141552538-545896bf-8c53-40e6-b6c8-4b7a189f4f16.png">

```
@job
def branching():
    all_articles, nyc_articles = fetch_stories()
    write_to_csv(parse_xml(nyc_articles))
    write_to_csv(parse_xml(all_articles))
    send_slack_msg(nyc_articles)
```

**Comment by hellendag** [comment]
Let's use a nice blue instead of the dark gray for the highlighted connection, dots and line.
