### ISSUE TITLE
search bar on assets page omits some expected results

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5655]
I typed "items", but the asset with key "s3 > hackernews-elementl-prod > items" did not appear in the search results.

**Comment by bengotow** [comment]
I think this may depend on whether you choose to browse assets as a list or as a hierarchical tree? If you use the tree view you won't see matches where the matching string is in a nested part of the tree I think? We should double check though, very possible this is a bug.

**Comment by sryza** [comment]
In this case, I was browsing assets as a list.

**Comment by hellendag** [comment]
Hm, looks like a bug with the search results.

**Comment by hellendag** [comment]
I think we can just bump the search threshold a bit.
