### ISSUE TITLE
Better dagstermill parameter experience

### ISSUE THREAD

**Issue by puma314** [dagster-io/dagster#567]
In papermill, to define parameters you create a parameters cell with the parameters that you might want to programatically feed in later. Then within this cell, you define these parameters to be whatever values you want for local testing of the notebook (meaning not executed via papermill).

Currently the dagstermill scaffolding creates a parameters cell with a blank definition of 
`dm_context = dm.define_context()`. To declare parameters that you might want to feed in programatically later, you have to pass in an argument to define_context as follows:  

`inputs=dict(a=3, b=5)`. 

Then you need to add another cell to manually unpack these arguments as follows: 

`a, b = dm.get_inputs(dm_context, 'a', 'b')`

This seems clunky and ideally all this interfacing with dm would be done in the background. If that's not possible, then ideally it would be codegenned in.

**Comment by puma314** [comment]
papermill PR to make this easier https://github.com/nteract/papermill/pull/280

**Comment by mgasner** [comment]
#655
