### ISSUE TITLE
Dagit Gantt Chart keeps a step running when a run failed, if there was no STEP_FAILURE event received

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#5692]
## Summary
If a run is failed but one of the steps never emits a STEP_FAILURE event, the run shows up in Dagit as failed, but the step continues hanging forever. 

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
@bengotow fixed this!
