### ISSUE TITLE
[TypeError: cannot pickle weakref objects] when using @op/@job vs @solid/@pipeline

### ISSUE THREAD

**Issue by william-episource** [dagster-io/dagster#5767]
## Summary

dagster                   0.13.8

When using @solid/@pipeline, I was able to pass Tensorflow class objects between different solids without error. When I updated the code below to use @op/@job, now I keep getting the error: "[TypeError: cannot pickle weakref objects]". There is a problem passing the Tensorflow objects (model, callbacks) between @op's. 

Did the serialization logic change internally when switching to @op/@job?

As a workaround I have to save the Tensorflow model to a local filepath and then read it back from another @op instead of just passing it directly like my example below

## Reproduction

```
class StateClass:
    def __init__(self):
        pass

@op()
def method1():
  state1 = StateClass()

  model = keras.Sequential()
  model.add(keras.layers.Dense(256, input_dim=NUM_FEATURES, activation='relu', name="dense_1"))
  model.add(keras.layers.Dense(NUM_LABELS, activation='sigmoid', name="dense_3"))
  adam_optimizer = keras.optimizers.Adam(learning_rate=0.002)
  model.compile(loss="binary_crossentropy", optimizer=adam_optimizer, metrics=['accuracy'])
  history = model.fit(......)

  state1.model = model
  state1.history = history
  return state1
  
@op()
def op_model_predict(context, stateObject):
   ...

@job()
def job_1():
   one = method1()
   op_model_predict(one)
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Hi @william-episource, thanks for posting this issue. 

Since 0.13.0 we've defaulted jobs to use the multiprocess executor and `fs_io_manager`. Because `fs_io_manager` uses pickle for serialization, some inputs/outputs may fail.

In order to fix this issue, you can execute jobs instead via `job_1.execute_in_process()` which will use the `in_process_executor` and `mem_io_manager`. Or, you can provide them in the job definition as follows:
```
@job(resource_defs={"io_manager": mem_io_manager}, executor_def=in_process_executor)
def job_1():
     one = method1()
     op_model_predict(one)
```

**Comment by william-episource** [comment]
Thanks @clairelin135! That resolved my issue, was unaware of the defaults, everything works great again
