### ISSUE TITLE
yielding outputs from @graph

### ISSUE THREAD

**Issue by bernardocortez** [dagster-io/dagster#5783]
## Summary
The expected behaviour of a graph with multiple outputs is described in the [documentation](https://docs.dagster.io/guides/dagster/graph_job_op#a-composite-solid-with-multiple-outputs).
However, when trying to yield (instead of returning) the output(s), I get the following error message:

> dagster.core.errors.DagsterInvalidDefinitionError: @graph 'do_two_things' returned problematic value of type <class 'generator'>. Expected return value from invoked solid or dict mapping output name to return values from invoked solids

## Reproduction
```
from dagster import (Out, Output, execute_pipeline, graph, op, pipeline,
                     reconstructable)
from dagster.core.definitions.output import GraphOut


@op
def do_something():
    pass


@op(out={"one": Out(int), "two": Out(int)})
def return_multi():
    yield Output(1, "one")
    yield Output(2, "two")


@graph(out={"one": GraphOut(), "two": GraphOut()})
def do_two_things():
    do_something()
    one, two = return_multi()
    yield one
    yield two


@op
def do_yet_more(arg1, arg2):
    assert arg1 == 1
    assert arg2 == 2


@pipeline
def do_it_all():
    one, two = do_two_things()
    do_yet_more(one, two)

execute_pipeline(reconstructable(do_it_all))

```

## Additional Info about Your Environment
dagster 0.13.4
python 3.9.5

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @bernardocortez, `yield` isn't supported inside `@graph`. This should work:
```
@graph(out={"one": GraphOut(), "two": GraphOut()})
def do_two_things():
    do_something()
    one, two = return_multi()
    return one, two
```
