### ISSUE TITLE
Clicking a dagster-k8s/config tag adds multiple filter bar entries

### ISSUE THREAD

**Issue by esselius** [dagster-io/dagster#5879]
## Summary

If you click a `dagster-k8s/config`-tag, it will end up as multiple entries in the filter list

## Dagit UI/UX Issue Screenshots

![Screenshot 2021-12-06 at 11 06 32](https://user-images.githubusercontent.com/1178200/144827565-d3fc8aec-716f-430a-8ea8-1ce1908861a6.png)

## Additional Info about Your Environment
Dagit 0.13.9

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
These tags are no longer clickable. Other tags that contain commas or colons should no longer break the input. :)

**Comment by esselius** [comment]
Thanks!
