### ISSUE TITLE
Sensors' unit tests

### ISSUE THREAD

**Issue by bernardocortez** [dagster-io/dagster#5891]
## Use Case
There is, currently, no way to run unit tests in any type of sensors, other than file sensors, as far as I can understand from the [documentation](https://docs.dagster.io/concepts/partitions-schedules-sensors/sensors).
This is a major flaw, as sensors are crucial to use Dagster in production environments.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @bernardocortez - I assume you've looked at this already: https://docs.dagster.io/concepts/partitions-schedules-sensors/sensors#testing-sensors. What's missing for you? Is it that you'd like to be able to supply custom resources for testing, similar to what you can do when testing ops?

**Comment by bernardocortez** [comment]
Hi @sryza. Thanks for replying.

Yes I had seen that. I guess my question was not specific enough. Sorry for that...

The problem I am facing concerns testing a chain of jobs that are triggered by the previous one and trigger another one afterwards using asset materializations and multi-asset sensors. I think dagster lacks some resource to test these type of chains, as I see it as common use-case.

Best.

**Comment by sryza** [comment]
@bernardocortez got it, that makes sense. I can definitely see the value in that. Do you have an idea of what an ideal API would look like for you?

I'd also be happy to jump on a call and talk this through with you if that would be easier. Are you in the Dagster Slack?

**Comment by sryza** [comment]
Cool - here's a link: https://dagster-slackin.herokuapp.com/

**Comment by sryza** [comment]
Going to close this. Bernardo and I chatted, and I recommended using `instance_for_test` to mock out events for a sensor. Bernardo, feel free to reopen if you think there are still issues here.
