### ISSUE TITLE
[Documentation Feedback] Problem on /ops#dagster.AssetMaterialization page

### ISSUE THREAD

**Issue by mwlee9** [dagster-io/dagster#5945]
Seems like link has been broken - clicking from the dagstermill docs doesn't show the AssetMaterialization documentation

**Comment by yuhan** [comment]
surprised the broken link test didn't capture this. will investigate!

**Comment by yuhan** [comment]
seems broken since 0.12.14 and blames to https://github.com/dagster-io/internal/pull/360

**Comment by prha** [comment]
Should be fixed in the next release: https://github.com/dagster-io/internal/pull/1208

**Comment by prha** [comment]
Confirmed that this is now fixed on the latest docs.
