### ISSUE TITLE
Schedule tick history in dagit could choose different defaults based on the cron schedule

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#6011]
A daily schedule still defaults to showing ticks from the past 24 hours - 7 days is probably a better default for such a schedule.

**Comment by hellendag** [comment]
Could be another good onboarding issue!

**Comment by salazarm** [comment]
How do I repro this?

I tried making a daily schedule what I see is a daily tick? Am I look at the wrong place?

<img width="1404" alt="Screen Shot 2022-04-07 at 7 57 11 AM" src="https://user-images.githubusercontent.com/2286579/162193344-40e61fbf-1e89-4047-8b13-4787abedd6ec.png">

**Comment by hellendag** [comment]
The tick timeline visualization has been removed from the schedule page, so it seems like this ticket has aged out. :)
