### ISSUE TITLE
Description of job should inherit from graph

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#6027]
If I don't provide a description to my job when calling `to_job`, it should inherit from the base graph.

**Comment by AndreaGiardini** [comment]
It looks like this is on purpose https://github.com/dagster-io/dagster/blob/4776e4ffc84449227a17ec92a34c183fc0cd2810/python_modules/dagster/dagster_tests/core_tests/graph_tests/test_graph.py#L405-L407

Happy to submit a PR if we would like to change this behaviour
