### ISSUE TITLE
Helm Chart Support for Ingress on Kubernetes v1.22+

### ISSUE THREAD

**Issue by wkeifenheim** [dagster-io/dagster#6050]
## Use Case

Update the ingress Helm chart template to support newer versions of Kubernetes.

As of Kubernetes v1.22 the Ingress API no longer supports the `extensions/v1beta1` spec ([k8s deprecation ref](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122)).

Today, if enabling ingress from the Dagster Helm chart, the deploy will fail if you are targeting k8s v1.22+.

## Ideas of Implementation

Not only does the `apiVersion` field need to change to support k8s v1.22+, but the `path` and `service` fields are restructured as well.

Taking queues from other open source software providing helm charts, Airflow and Prometheus being good examples, update the Helm templates to support the different ingress specs.

Currently, the Helm chart for Dagster specifies that it supports k8s 1.15+. If support gets dropped for versions before 1.19, then Helm chart templating for ingress becomes much more simple.

~I have a PR tackling the ingress template here: https://github.com/dagster-io/dagster/pull/5476~

~In that PR I have built support for both the `extensions/v1beta1` and `networking.k8s.io/v1` ingress specs.~ _Taking a different approach based on feedback on that PR. New PR will be coming shortly_

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by wkeifenheim** [comment]
Starting over on how to approach. Rex found a much cleaner path forward, based on work that [JupyterHub has done](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/1f21ccd85b43f68766d846b7758ce853343639ba/jupyterhub/templates/ingress.yaml#L2).

I have a new branch made with both ingress templates. Currently working on the associated `ingress.py subschema` code.

**Comment by solarisa21** [comment]
PLEASE make this happen. our dagster runs on GKE clusters with versions auto-upgraded..right now it's on 1.2 (stable release) but would not want our helm charts (with ingress enabled) breaking
