### ISSUE TITLE
[examples/hacker-news] configure storage location per instance

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#6055]
configure intermediate storage locations so that if you have multiple instances of this running at the same time they will not write to the same location

**Comment by yuhan** [comment]
when you say intermediate storage location, did you mean the instance level storage configuration? i believe io manager defaults to that per instance.

**Comment by OwenKephart** [comment]
oh this got resolved at some point -- we were using a custom io manager that wrote to the same location regardless of instance
