### ISSUE TITLE
TimeWindowedPartitionConfigs should be possible to offset

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#6057]
The documentation for the ..._partitioned_config() functions states that the "start_date" parameter is "start_date (Union[datetime.datetime, str]) – The first date in the set of partitions. Can provide in either a datetime or string format."

For weekly partitioned configs (and monthly) this is not really the case, as we use a `0 0 * * 0` cron schedule, and the start_date is only used to determine when that `0 0 * * 0` iterator will start.

This may be intended behavior, but there should be some functionality for being able to create weekly partition sets that end on different days of the week than Sunday (similar functionality should probably exist for all the other time windowed partition functions).

**Comment by OwenKephart** [comment]
relevant slack discussion: https://dagster.slack.com/archives/C01U954MEER/p1640189546485200

**Comment by cwe5590** [comment]
Consider this a blocker b4 moving to the new partition api.

**Comment by Tiri1992** [comment]
Any updates on this?

**Comment by jamiedemaria** [comment]
PR is merged, will be included in this week's release
