### ISSUE TITLE
Support graph DSL in graphql api

### ISSUE THREAD

**Issue by shuitai** [dagster-io/dagster#6069]
## Use Case
In document, we found dagster could support DSL to create graph.
So we hope it could work in graphql api, when uses submit graph dsl schema to dagit by graphql api and once dagit receives the dsl request could create graph based on the dsl.

**Comment by sryza** [comment]
Hey @shuitai - thanks for the suggestion. In Dagster's current architecture, graph definitions are provided by code repositories. To support graphql-created graphs, we'd need to support database-stored graph definitions as a second source of truth on the graphs that Dagit knows about.  We wouldn't rule out this direction in the long term, but it's unlikely that we would support this functionality in the near future.

**Comment by shuitai** [comment]
@sryza Thanks for your feedback

**Comment by yuhan** [comment]
Closing for now because this isn't something we plan on doing in the near future (see comment above for more details).
