### ISSUE TITLE
Dagit produces an unhelpful error when a schedule uses a crontab that it can't parse

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#6082]
## Summary

We should raise a definition error if a schedule uses a cron_schedule that Dagster won't recognize. Separately, we should consider supporting a broader range of cron strings (like `@daily`).

## Reproduction
Create a schedule with `@daily` as the cron_schedule, view the Schedules tab in Dagit.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by prha** [comment]
This was half addressed in #6083, but will be fully addressed by #6810
