### ISSUE TITLE
dagstermill reloading

### ISSUE THREAD

**Issue by puma314** [dagster-io/dagster#615]
If the user is using the iPython automagic inline `%load_ext autoreload` (or re-importing dagstermill), then we have to be careful that every time they reload dagstermill they also have to re-run 
`dm.declare_as_solid(define_example_repository(), 'solid_name')` to interact with any module-level methods (such as `dm.get_context() or dm.get_info()`) since the NOTEBOOK_MANAGER is a global module-level variable.

**Comment by mgasner** [comment]
Can we hook into the extension or the import to warn them?

**Comment by mgasner** [comment]
This registration step is no longer part of dagstermill usage.
