### ISSUE TITLE
multiple re-execution of failures from Runs page

### ISSUE THREAD

**Issue by peterbaccaroshell** [dagster-io/dagster#6158]
## Use Case

Re-execution of failures is slow and inefficient as it is only possible to re-execute failed executions on an individual basis.

From the Runs page the steps to re-execute are as follows:

1. Navigate to Runs page.
2. Apply Filter of staus:FAILURE.
3. Select Re-excution option for one of the failures; this takes you to the instance runs page.
4. Navigate back to the Runs page and repeat the previous 2 steps for all failures.

The good thing about re-executing from the Runs page is that this re-executes the same job instance so once successful this is reflected on the Runs page.  Furthermore, for back-fills re-execution from the Runs page is also reflected in the back-fill status so when a back-fill failure is re-executed successfully the back-fill Succeeded status is incremented by 1 and the Failed status is decremented by 1.

There is an alternative to re-execute failed execution from the Partitions Run Matrix however the behaviour here is completely different as this launches a new backfill with new job run instances so the original failures still appear on the Runs page and for backfills the original backfill status is not updated.  Furthermore, the partitions page is very slow and only works at an individual job level so for failures across many jobs, the process would need to be repeated for each job.

## Ideas of Implementation

A better solution would be to be able to trigger multiple re-executions at once from the Runs page which would set the selected runs back to NOT_STARTED status so that they get re-queued and re-executed by Dagster.  The only options currently available when multiple run instances are selected are Terminate and Delete so we would need a new Re-execution option.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
Having a solution on the runs page seems potentially tricky, as an arbitrary set of runs could be connected / conflict in arbitrary ways. While in some scenarios filtering by failure and reexecuting all from failure will have a reasonable outcome, I don't think we can be sure that's always the case.

**Comment by dpeng817** [comment]
Perhaps I misunderstood, but let's say I see the same job failing a few times. If these are disconnected runs, do we retry every single one of those failures, or just one? If the config is different, maybe it makes sense to re-execute multiple times, but if we launch those off at once, they may conflict if accessing the same external resources.

**Comment by peterbaccaroshell** [comment]
@dpeng817  So you're suggesting that there could be duplicate failures for the same job/partition and by re-executing these together there could be a conflict depending on the implementation of the job.
This situation could also happen if the jobs are re-executed individually in parallel or if overlapping back-fills are launched.  Therefore I don't see this as a strong reason not to be able to re-execute multiple failures.  The failures that are re-executed will be the failures that the user has selected so the user will need to be aware of any possible conflicts in their system and if they have concerns they still have the ability to re-execute failures individually.
By making the re-execution of failures more streamlined I would say it is less likely that there are multiple failures for the same job/partition as when there are failures the user would simply re-execute these and once successful the jobs would no longer appear on the failure list.  
As it stands, because re-execution from the Runs page is not streamlined the user may end up re-launching a back-fill from the Run Matrix in which case duplicate failures on the Runs page is more likely.
Having a more streamlined way to perform re-executions from the Runs page makes things cleaner as the Run page reflects the health of the system.  Launching new backfills to address failed partitions pollutes the Runs page as the original failed jobs remain.  Identifying failed partitions from the Run Matrix is unreliable as if a job fails due to a framework error this is not shown on the Run Matrix.

**Comment by bengotow** [comment]
Hey folks! Moving this out of the Dagit UI/UX workstream, it sounds like there are a few product questions here and it's also debatable whether we should allow so many jobs to be queued at once (via multi-selection + "Re-execute from failure")  vs. launching a backfill.

**Comment by peterbaccaroshell** [comment]
> Hey folks! Moving this out of the Dagit UI/UX workstream, it sounds like there are a few product questions here and it's also debatable whether we should allow so many jobs to be queued at once (via multi-selection + "Re-execute from failure") vs. launching a backfill.

The behaviour of launching a backfill is completely different and the backfill page is very slow.  
Multi-selection on the run page is only limited to 25 items so it is not excessive and far less than what can be queued via a backfill.

Furthermore, framework errors do not appear on the run matrix so the run matrix is not reliable.

Also, backfills will not remove the historic failures from the run page so without re-execution from the run page is difficult to get a view on the health of the system across multiple interfaces.

**Comment by johannkm** [comment]
Brought this up to the team.

In the meantime- we're working on supporting policies for automatic re-execute from failure. I'm curious if that would solve some of this use case. There's also a revamp of backfills in progress which may resolve some of your concerns with the partition matrix.

**Comment by peterbaccaroshell** [comment]
> Brought this up to the team.
> 
> In the meantime- we're working on supporting policies for automatic re-execute from failure. I'm curious if that would solve some of this use case. There's also a revamp of backfills in progress which may resolve some of your concerns with the partition matrix.

The automatic re-executions do help however they are only a partial solution to the issue.  Backfills launch new run instances which is not what we want to do here.  We want to be able to re-execute multiple failed job run instances from the Runs page so that once the runs are successful they will no longer appear as failed on the Runs page.  Re-executing individually is too slow and cumbersome so we want to select the failed Runs to re-execute in the page (max is 25 I believe) and then queue for re-execution.

The backfills would launch new job run instance and the leave the existing run instances as failed on the Runs page.  Also the partitions page is very slow and both partitions and backfill only operate at the job level whereas the Runs page is a view across all jobs.  Using partitions and backfills is not only slower that individual re-execution it also results in an undesired end state.

**Comment by hellendag** [comment]
Reopening issue in the meantime, just to be certain.

**Comment by peterbaccaroshell** [comment]
> Reopening issue in the meantime, just to be certain.

Hi, which version will this change be part of.

**Comment by hellendag** [comment]
This feature will be in this Thursday's open source release, 0.14.13.

**Comment by hellendag** [comment]
Both re-execution policies are now implemented.
