### ISSUE TITLE
A command to validate the usercode repository

### ISSUE THREAD

**Issue by RMHogervorst** [dagster-io/dagster#6200]
## Use Case

As a data engineer, supporting my team, I want to create a pit of success; I want the users of dagster to feel empowered to try out new things and be independent. 

Loading usercode with `dagit` performs several checks while loading the repository. 
I would like to see those checks without dagit. 

* Usecase 1: I want my users to run that command to check their own work
* Usecase 2: I want to run this command in my CI/CD pipeline to check every new commit. Ideally failing when the repository is configured incorrectly.

I like the `dagster job list --repository` command, but I need to run it for every reposity I create.  I'm also not sure it fails meaningfully.

### Ideal situation
`dagster validate` would execute the runtime checks that dagster does. Preferably without very deep  stacktraces. Maybe output like mypy or flake8, a filename - linenumber , possibly name of the function and what is wrong. 

### other possibilities
Docs explaining how to run `dagster job list` and how to integrate it into CI/CD pipelines. 

Possibility to point dagster job list to a workspace yaml so that multiple repositories are automatically enumerated. 

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by tacastillo** [comment]
[Sharing from this message](https://dagster.slack.com/archives/C01U5LFUZJS/p1712172812490519)
>Hello :wave: I recently onboarded to a pre-existing project, and while working eventually received an error message dagster_graphql.client.utils.DagsterGraphQLClientError: ('JobNotFoundError', 'No jobs with the name <name> exist'). The reason for the error is that in our tests, we are using the GraphQL client to kick off a run, but the repo has been misconfigured such that (in theory) it hasn't initialized fully. Specifically, there was an op with the same name as another, causing a naming conflict for the repo. It seems that there isn't a great way to perform the validation without a deployment, which seems like a shortcoming of the software

**Comment by 0x26res** [comment]
Isn't it what `dagster definitions validate` does?

**Comment by garethbrickman** [comment]
@0x26res That's correct, [dagster definitions validate](https://docs.dagster.io/_apidocs/cli#dagster-definitions-validate) is available from version 1.8.9 onwards!
