### ISSUE TITLE
dagit re-run pipeline 

### ISSUE THREAD

**Issue by puma314** [dagster-io/dagster#621]
![image](https://user-images.githubusercontent.com/5422468/51153190-0e574380-1824-11e9-89bc-621ad8368c3c.png)

Sometimes, when pressing the play button after executing a pipeline, dagit will not do anything and the error in the image will be visible in the javascript console. But this only happens sometimes (have not been able to find a explainable pattern behind when).

**Comment by schrockn** [comment]
I'm closing this for now as I haven't seen that behavior in awhile.
