### ISSUE TITLE
Need more logging information

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#622]
Run this pipeline

```dagit -m dagster.tutorials.intro_tutorial.tutorial_repository -n define_repository```

And you can open a toy pipeline "execution_context_pipeline" that demonstrates logging.

![screenshot 2019-01-15 05 13 32](https://user-images.githubusercontent.com/28738937/51182848-53ab5d80-1884-11e9-9a65-3eae152d4111.png)

You'll notice the "An error occurred" message. We need to print out more context information about what is going on. In particular we need to make it so that if you click on the solid in the execution plan it doesn't get filtered away.

![screenshot 2019-01-15 05 15 00](https://user-images.githubusercontent.com/28738937/51182896-85bcbf80-1884-11e9-8908-23678ec5f53f.png)

**Comment by bengotow** [comment]
My guess is that this error message does not have an associated solid in the graphQL schema? This seems like a log data structure problem and not a display problem - will take a look though 👍

**Comment by schrockn** [comment]
It definitely has it in its semi-structured information. You can see if you print it out on the console

**Comment by schrockn** [comment]
Here is the same message outputted to the console

![screenshot 2019-01-22 11 12 41](https://user-images.githubusercontent.com/28738937/51559412-a6fa4e80-1e36-11e9-98f6-8da216dcfe30.png)

**Comment by schrockn** [comment]
Resolved in https://github.com/dagster-io/dagster/pull/1078
