### ISSUE TITLE
dagster-k8s/config : only one secret_ref gets loaded to pod

### ISSUE THREAD

**Issue by jonasdebeukelaer** [dagster-io/dagster#6239]
## Summary
I'm unable to add multiple `env_from.secret_ref`s using a `job`'s `tags` property. the first secret ref gets overriden by the second in the pod definition (looking at kubectl get pod _ -o yaml)

## Reproduction

* create a kubernetes secret my-secret-1 containing env var 'MY_ENV_VAR_1'
* create a kubernetes secret my-secret-2 containing env var 'MY_ENV_VAR_2'

Then try to run this job in dagster in kubernetes.
```
import os

from dagster import config_from_files, file_relative_path, job, op

@op
def test_op(context):
    context.log.info(f"this list only includes MY_ENV_VAR_2, but is missing MY_ENV_VAR_1")
    context.log.info(os.environ)


@job(
    tags={
        "dagster-k8s/config": {
            "container_config": {
                "env_from": [{
                    "secret_ref": {
                        "name": "my-secret-1"
                    },
                    "secret_ref": {
                        "name": "my-secret-2"
                    }
                }]
            }
        }
    }
)
def test_job():
    test_op()
```

## Additional Info about Your Environment
dagster, dagster-k8s version 1.13.14

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hey @jonasdebeukelaer - this looks like an easy-to-miss python issue to me. you have a list of size 1 with one dict with two duplicate 'secret_ref' keys, but you want a list of size 2, where each element is a dict with a 'secret_ref' key:

```
                "env_from": [{
                    "secret_ref": {
                        "name": "my-secret-1"
                    }
                  }, {
                    "secret_ref": {
                        "name": "my-secret-2"
                    }
                }]
```

**Comment by jonasdebeukelaer** [comment]
🤦  !!! Thanks @gibsondan, apologies for the silly non-bug report.
