### ISSUE TITLE
offer a way for an op to fail and skip retries

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6271]
If an op has a retry policy, a user might want to override it. I.e. fail and tell Dagster not to schedule any retries.

Requested on slack: https://dagster.slack.com/archives/C01U5LFUZJS/p1642637702012000

**Comment by alangenfeld** [comment]
Some options:
* A new exception type `Abort` which always bypasses retry policies 
* A flag on `Failure` to allow it to bypass retry policies
* whitelist/blacklist capabilities on `RetryPolicy` for exception classes. Some unfortunate potential trickiness here if we want to run the policy from a host process where we can't `isinstace` to respect class inheritance.
