### ISSUE TITLE
dagit: changes to run config not picked up correctly

### ISSUE THREAD

**Issue by erinov1** [dagster-io/dagster#6312]
## Summary
There are two instances where dagit picks up changes to a job's python run config (i.e., via the `config` argument in `to_job()`) in undesirable ways:

1. Reloading a workspace is not enough to pick up changes (either in dagit's Launchpad tab or in job's actual run); I have to close and reopen the dagit tab in my browser (tested on Firefox and Safari)
2. Manually deleting the contents of dagit's Launchpad tab fixes this issue in the sense that changes to the run config *are* reflected in the job's output just by reloading the workspace. However, because the Launchpad is now empty, clicking on `View tags and config` shows an empty config, which makes it impossible to associate a run with the config. I am also unable to automatically repopulate the Launchpad tab after I delete its contents (even though the underlying job runs correctly with the config that was defined in python)

Related to the second issue, there is end-user ambiguity between a job's run config defined in python (if there is one), what is reflected in the Launchpad, and the config that is actually used when launching a run.

It would also be useful to allow the user to load (multiple) configs from file directly from the dagit UI (similar to the CLI), with options to either (a) completely replace the python run config or (b) simply override duplicate keys. Exporting a config entered into the Launchpad to yaml could also be useful.

## Reproduction
In `jobs.py` I define the following job:

```
@op()
def hello(context):
    print("Hello {}".format(context.op_config["name"]))

@graph()
def my_graph():
    hello()

my_job = my_graph.to_job(
    config={"ops": {"hello": {"config": {"name": "Anne"}}}}
)
```

Then I launch dagit with `dagit -f jobs.py`. Under the launchpad I correctly see

```
ops:
  hello:
    config:
      name: Anne
```
Launching a run correctly prints `Hello Anne`.

Next, with the dagit tab still open in my browser, I edit `jobs.py`, replacing the name `Anne` with `Steve`:

```
my_job = my_graph.to_job(
    config={"ops": {"hello": {"config": {"name": "Steve"}}}}
)
```
I return to the dagit tab and reload the workspace. The launchpad still lists `name: Anne` instead of `name: Steve`. If I launch a run, it incorrectly prints `Hello Anne`. On the other hand, if I close the dagit tab and then reopen it (with the dagit process still running), the launchpad now correctly lists `name: Steve` and launching a run prints `Hello Steve`.

For the second issue, suppose I now delete the contents of Launchpad. If I change `Steve` back to `Anne`, reload the workspace, and launch a run, it correctly prints `Hello Anne`; this is *without* having to close and reopen the dagit browser tab. However, the Launchpad remains empty, and if I click on `View tags and config` it simply reads `Config {}`. Furthermore, there is no way for me to reload the contents of my job's python config into the Launchpad: it always stays empty. This is true even if I kill the dagit process itself and reload it.

## Additional Info about Your Environment
```
macOS: 10.13.4
python: 3.8.12
dagster: 0.13.16
Firefox: 95.0.2
Safari: 12.0.3
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
We have a feature in place that would prompt you to refresh the config when reloading the repository manually...but it only applies when a preset is used. Looking into a fix.

**Comment by hellendag** [comment]
@sryza Any ideas how we might be able to distinguish when a job might need its config reloaded?

**Comment by hellendag** [comment]
It looks like this was simpler than I thought: we just weren't treating the `default` preset config for jobs the same way as for pipelines.
