### ISSUE TITLE
Migration who added startTime and endTime fields doesn't apply properly for MySQL storage

### ISSUE THREAD

**Issue by paralyzah** [dagster-io/dagster#6330]
## Summary
I tried migrate dagster from 0.13.13 to 0.13.16, and migration fails on attempts migrate data to new columns startTime and endTime.
I guess the reason is https://github.com/dagster-io/dagster/pull/6038
A mysql migration located in dagster-postgres alembic versions, but for mysql storage no need to install dagster-postgres library.
How I can apply migration what I don't have?

**Comment by prha** [comment]
This is fixed in #6331, should go out in the next release

**Comment by prha** [comment]
Addressed in `0.13.17`
