### ISSUE TITLE
Add `build_run_status_sensor_context ` and `build_run_failure_sensor_context `

### ISSUE THREAD

**Issue by LouisAuneau** [dagster-io/dagster#6347]
## Use Case

In order to unit-test sensors built from decorators `@run_status_sensor` and `@run_failure_sensor` we need a simple way to generate a fake context, as it is possible for standard sensors with `build_sensor_context`.

## Ideas of Implementation

```python
context = build_run_status_sensor(
    run_id='<RUN_ID>',
    pipeline_run_status=DagsterRunStatus.SUCCESS,
    instance='<MOCK_INSTANCE>',
    cursor='<MOCK_CURSOR>'
)
```
*Not fully sure on how to provide the instance and cursor, that for sure is used in most sensors to retrieve informations such as failure messages etc.*

## Additional Info
 N/A

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
Repeat of https://github.com/dagster-io/dagster/issues/6332
