### ISSUE TITLE
Clicking in the Runs tab from a job in Dagit shows all runs for any jobs with that name

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#6377]
## Summary
We should add a repository name tag and repository location name tag in dagit, and use those tags when navigating from a job to the runs associated with that job.

## Reproduction
Have two jobs in the same workspace with the same name, click on Runs, see all runs for both of those jobs.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by braunjj** [comment]
Similar to #6725
