### ISSUE TITLE
Info tab for op is too responsive on desktop

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#6384]
## Summary
When expanding the information sidebar after double-clicking into an op, the execution time graph can overfill its container. 

Rather than letting the sidebar be expanded or contracted, maybe it should just exist in two states: open with a fixed width, or closed.

## Reproduction
Inspect this component in the hacker news demo.

## Dagit UI/UX Issue Screenshots

https://user-images.githubusercontent.com/16431325/151462139-5f33580a-6c26-4c01-a26d-733e5bce9f84.mov

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Will be fixed by https://github.com/dagster-io/dagster/pull/6799
