### ISSUE TITLE
Helm Chart should support adding labels to Dagit

### ISSUE THREAD

**Issue by michaeljguarino** [dagster-io/dagster#6414]
## Use Case
We have some mutating webhooks that are triggered off specific labels we'd like to apply to a dagit k8s deployment, but the helm chart currently has no support for manually provided labels.

## Ideas of Implementation
It looks like there's currently support for adding additional annotations which can be copypasta'ed to adding labels.  I'm happy to implement this and submit a PR if it helps unblock on your end as well.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @michaeljguarino - we'd be happy to accept a PR for this if you're willing! I agree it should be a pretty quick one / similar to the annotations case.

**Comment by rexledesma** [comment]
Should be resolved with https://github.com/dagster-io/dagster/pull/6428

**Comment by yuhan** [comment]
sorry thought the pr was landed. reopen now
