### ISSUE TITLE
Clicking on Run ID in asset catalog does not navigate to run

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#6417]
## Summary

For example on this page I want to click to the run for the first materialization. Run "6ea22b5d"

![Screen Shot 2022-01-30 at 8 44 03 PM](https://user-images.githubusercontent.com/28738937/151736002-c5a6c292-9a2a-43ee-99be-6006be2c2879.png)

However when I click it nothing happens except the url changes

![Screen Shot 2022-01-30 at 8 44 18 PM](https://user-images.githubusercontent.com/28738937/151736047-19fd5d99-8a94-4556-931c-015b8f8cf670.png)

Here is a video which is probably more helpful

https://user-images.githubusercontent.com/28738937/151736094-c8d6899a-ba2d-4a96-a396-a150eadcb437.mov

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
This has been addressed!
