### ISSUE TITLE
"Could not load solids" should be renamed

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#6419]
## Summary

In dagster/js_modules/dagit/packages/core/src/pipelines/SidebarOpContainer.tsx there is an error message "Could not load solids". We should rewrite for an op/SDA world. 

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by Sync271** [comment]
I'd like to work on this issue.
I understand this:
> In dagster/js_modules/dagit/packages/core/src/pipelines/SidebarOpContainer.tsx there is an error message "Could not load solids"... 

But not:
> ... We should rewrite for an op/SDA world.

I think for an outsider to contribute, it'd help if it's more descriptive

**Comment by sryza** [comment]
I actually fixed this yesterday. We renamed "solid" to "op".
