### ISSUE TITLE
Deadlock in dagster_shell.execute when using BUFFER output control

### ISSUE THREAD

**Issue by kbd** [dagster-io/dagster#6435]
The following lines in `dagster_shell.execute` are incorrect, and deadlock when there's enough output from the called subprocess:

https://github.com/dagster-io/dagster/blob/a4eab2ab70e2fd4f4f71d66c479d0d83c01acdb4/python_modules/libraries/dagster-shell/dagster_shell/utils.py#L97-L104

From the [Python manual](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait):

> [`Popen.wait`] will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use ['Popen.communicate()'](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) when using pipes to avoid that.

So, that code should be something like:

```python
if output_logging == "BUFFER": 
    output, _ = sub_process.communicate()
    log.info(output.decode("utf-8"))
```

And call `.wait()` afterwards. The "NONE" case is also likely broken since any program that has a lot of output will fill output buffers and won't complete unless you drain them.

While I'm here, I want to mention that:

https://github.com/dagster-io/dagster/blob/a4eab2ab70e2fd4f4f71d66c479d0d83c01acdb4/python_modules/libraries/dagster-shell/dagster_shell/utils.py#L95

Is n^2 behavior because it has to reallocate the string each time. Instead, you should add the lines to a list and join them at the end.

**Comment by sryza** [comment]
Thanks for the reports @kbd . Would you be interested in contributing fixes to either of these issues? We'd be happy to review your code if so.

**Comment by kbd** [comment]
Sure if you'll look at a PR I'll take a look at fixing this and #6357.
