### ISSUE TITLE
dagster-k8s: [K8sRunLauncher] full pod name in dagit

### ISSUE THREAD

**Issue by chapmanjacobd** [dagster-io/dagster#6450]
## Use Case
I would like to see the exact pod name when the pod is created.

currently I see something like this

```
Executing step *** in Kubernetes job dagster-job-1cde046f20f90ef81e01b8f32b80914d
Step key
	***
Kubernetes Job name
	dagster-job-1cde046f20f90ef81e01b8f32b80914d
```

I would like to be able to copy and paste the job pod into something like this

```
kubectl logs --follow -n dagster dagster-job-1cde046f20f90ef81e01b8f32b80914d-2gwds
```

But where does `-2gwds` come from ? What is that??

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
From https://stackoverflow.com/a/63237571, you'll want to use this command:

```
kubectl logs --selector job-name=my-test
```

So in your example, you want

```
kubectl logs --selector job-name=dagster-job-1cde046f20f90ef81e01b8f32b80914d
```

This is because in Kubernetes, a job manages a pod to completion. The job name is separate from the pod name.
