### ISSUE TITLE
Dagit homepage should route to the new instance status page

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#6468]
We should use the following logic to determine the homepage routing:

- I have 0 Agents (in cloud): Route to the Status - Health Page
- I have 0 Jobs: Route to the Workspace tab
- I have 1 Job: Route to the Job Overview page
- I have more than 1 Job: Route to the Status - Overview (Factory Floor) page

**Clicking The Daggy icon in the top left should route to the homepage (Right now it seems to always route to the workspace page)**

**Comment by bengotow** [comment]
We've got this implemented with the exception of the "0 agents in cloud" case specific to Cloud.

There are also two cases beneath these four not documented here: 
- 1+ repos and zero jobs ("No jobs, create one!" landing page)
- 0 repos and zero jobs ("No repos, create one!" landing page)
