### ISSUE TITLE
The repo selection on the Instance status page should be tethered to the left nav repo selection

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#6469]
When a users clicks the repository filter button on the instance status page, it should open the same repo filter modal that appears when you click the filter button from the left nav. A user's selection on either filter should be reflected in both the left nav and the instance status view.

Here's a video walkthrough of what I'm thinking:
https://www.loom.com/share/4535e3bbff0f4f768cf25598ec6a01e0

**Comment by bengotow** [comment]
This is incorporated into https://github.com/dagster-io/dagster/pull/6494!
