### ISSUE TITLE
Allow users to toggle between assets and op graphs in the job overview page

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#6471]
Today for Software Defined Asset Jobs, users don't have a way to view the underlying op graph. We'd like to make the relationship between ops and assets more clear by introducing a toggle in the graph view.

**When viewing the asset graph**, each asset node should be annotated with the op that produced it, (unless the op name and the asset name are identical.)
<img width="316" alt="Screen Shot 2022-02-02 at 3 51 15 PM" src="https://user-images.githubusercontent.com/2798333/152235350-8a86faf6-836d-4bd9-8758-753e2e900802.png">

**When viewing the op graph view,** each op that produces assets should get annotated with the name of the first asset it produces. If there are more than one asset we can append a "+ X assets" to it. A user can click on the op to view a full list of the assets produced by that op in the right sidebar.
<img width="583" alt="Screen Shot 2022-02-02 at 3 53 59 PM" src="https://user-images.githubusercontent.com/2798333/152235792-10220000-a67e-4577-8ff8-bcc028d90b6f.png">

### Here's a full video walkthrough of the desired experience:
https://www.loom.com/share/a8bce582e02941bcab55c6816ed36c70

**Comment by bengotow** [comment]
This is incorporated into https://github.com/dagster-io/dagster/pull/6494!
