### ISSUE TITLE
add a boolean metadata type

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6473]

**Comment by alangenfeld** [comment]
whats the context on the utility of this over using string metadata "True" / "False" ? Aggregations I assume?

**Comment by sryza** [comment]
1. It's nice to be able to type True / False and have the linter detect if you misspelled something.
2. Aggregations.
3. Opens up the ability to render them in creative / useful ways. E.g. could imagine a grid where each column is a materialization date and each row is a metadata key and a checkbox indicates true / false.
