### ISSUE TITLE
[docs] clarify argument usage in op factory example

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#6512]
~"nwe" https://docs.dagster.io/concepts/ops-jobs-graphs/ops#op-factory~

~bonus:~
update section for clarity https://dagster.slack.com/archives/C01U954MEER/p1643843874933099?thread_ts=1643843102.120129&cid=C01U954MEER

**Comment by yuhan** [comment]
typo fixed in https://github.com/dagster-io/dagster/pull/6209

updating this issue to address bonus
