### ISSUE TITLE
return model name in dbt asset

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#6538]
## Use Case

Hi! After yesterday's community meeting I got curious and started playing around with the dagster_dbt asset api.

It seems that dbt assets return "None" making them hard to use them dynamically in downstream assets (e.g. python code that would want to load the table).

Would it be possible to return some metadata about the model instead?

## Ideas of Implementation

Probably involves changing https://github.com/dagster-io/dagster/blob/6781eaadd33ecfb0b48d7c2c7d8e193efbda4209/python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py#L69-L71

## Additional Info

Asset API looks awesome

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
We would expect you to use an IO manager to load the asset in downstream dependencies.
