### ISSUE TITLE
Add ability to schedule a static partition job

### ISSUE THREAD

**Issue by tim-roy-sp** [dagster-io/dagster#6554]
## Use Case

Currently the only schedule decorators and functions that support partitions only support temporal partitions. In addition, a standard (non-partition) schedule fails when attempting to use in conjunction with a static partition job (`dagster.core.errors.DagsterInvalidSubsetError: No qualified ops to execute for op_selection=['']`)

## Ideas of Implementation

Provide functionality to either execute all partitions  or explicitly define a partition to be ran with a cron schedule

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
spawns https://github.com/dagster-io/dagster/issues/6557
