### ISSUE TITLE
Launchpad defaults with invalid subset error

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#6557]
## Summary
`dagster.core.errors.DagsterInvalidSubsetError: No qualified ops to execute found for op_selection=['']` shows by default when opening a launchpad from a historical run.

From a cursory look, https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/js_modules/dagit/packages/core/src/launchpad/LaunchpadSessionContainer.tsx?L386%3A7-387%3A99=, we should probably default to `*` if the solid selection is either null or an empty array.

## Reproduction
go/dev. Navigate to the run tabs, and open the launchpad for a historical run. 

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by tim-roy-sp** [comment]
I am receiving the same error message when attempting to create a scheduled run using a static partition. Please see [this slack thread](https://dagster.slack.com/archives/C01U954MEER/p1644606094959869?thread_ts=1644438429.559749&cid=C01U954MEER) for more context. This error can be recreated using `my_schedule = ScheduleDefinition(job=continent_job, cron_schedule="0 0 * * *")` with the static partition example from the docs. using 0.13.18
