### ISSUE TITLE
Job names longer than 35 characters are being truncated on the jobs page

### ISSUE THREAD

**Issue by peterbaccaroshell** [dagster-io/dagster#6563]
## Summary
The job names have recently started to be displayed in a truncated form when they are longer than 35 characters making it more difficult to identify a specific job.

The job page should display the full job name as it has before.

## Reproduction
View the jobs for a repo that has job names longer than 35 characters.

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/74666079/153588209-a0e50b0f-ae7a-4fca-8678-4235e34ea7e3.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
just landed a fix for this that will go live in the 0.14.0 release.
