### ISSUE TITLE
sqlite version >= 3.25 required for window functions. (sqlite3.OperationalError) near "(": syntax error

### ISSUE THREAD

**Issue by MischaU8** [dagster-io/dagster#6566]
## Summary

In Dagit getting an error in loading the workspace (reported by `Anoop Sharma` on Slack), but I was facing the same problems myself with 0.13.18:

```
Operation name: RepositoryPipelinesListQuery

Message: (sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT anon_1.id, anon_1.run_body, anon_1.create_timestamp, anon_1.update_timestamp, anon_1.start_time, anon_1.end_time, anon_1.rank 
FROM (SELECT runs.id AS id, runs.run_body AS run_body, runs.create_timestamp AS create_timestamp, runs.update_timestamp AS update_timestamp, runs.start_time AS start_time, runs.end_time AS end_time, rank() OVER (PARTITION BY runs.pipeline_name ORDER BY runs.id DESC) AS rank 
FROM runs 
WHERE runs.pipeline_name IN (?)) AS anon_1 
WHERE anon_1.rank <= ? ORDER BY anon_1.rank ASC]
[parameters: ('serial', 5)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Path: ["repositoryOrError","pipelines",0,"runs"]

Locations: [{"line":30,"column":3}]
```

## Reproduction

I could trigger the same / similar issue (all throwing `sqlite3.OperationalError near "(": syntax error` with sql queries containing window functions such as `rank()`) in various way by browsing dagit’s Status > Schedules / Sensors / Backfills views iirc. I don’t think I can reproduce it anymore after upgrading to Ubuntu 20 LTS, except for creating a new Ubuntu 18 LTS installation.

## Additional Info about Your Environment

Dagit requires a newer version of sqlite, window functions such as rank() were [introduced in 3.25](https://www.sqlite.org/releaselog/3_25_0.html), but (as an example) Ubuntu 18 LTS ships with Python 3.6.x / sqlite 3.22.x
As a workaround I fixed it yesterday by upgrading to Ubuntu 20.04.3 LTS, Python 3.810 / sqlite 3.31.1. 

To verify sqlite library version:
```
$ python3
import sqlite3
sqlite3.sqlite_version
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by prha** [comment]
I believe this is fixed in `0.14.0`... we now gate rank queries by the version of sqlite installed.
