### ISSUE TITLE
AssetGroup remaining work post 0.14.0

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#6647]
- Re-materialize API for materializing assets in-process via python
- Repo-level resources
- De-couple asset selection from op selection.

**De-couple asset selection from op selection**
Asset selection has some slightly different requirements from op selection, since asset keys don't correspond 1-1 with ops. We currently don't have a convenient way of selecting all of the asset keys associated with a given software defined asset. We also don't have a way to subselect across source assets, which don't directly correspond to an op.

**Comment by sryza** [comment]
@dpeng817 I think we should break these into separate issues, because they might be on pretty different timeframes
