### ISSUE TITLE
[Content Gap] getting the partition_key from the context

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6682]
## Anything else?

---

Writer's Guide: [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by nvinhphuc** [comment]
The partition key in the context is now currently "start_time" only? How can we get both "start" and "end" time of the partition in the context?

**Comment by sryza** [comment]
@nvinhphuc here's a PR that should add the ability to get both start and end time: https://github.com/dagster-io/dagster/pull/7795
