### ISSUE TITLE
Display cursor information on schedule/sensor ticks in Dagit

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#6683]
## Use Case
Would be nice to see cursor information on tick history.

**Comment by yuhan** [comment]
@prha good to close with the PR linked here?

**Comment by prha** [comment]
No, I think not... I think we still need to extract a richer tick history on this page, instead of just relying on the chart.js tooltips.  For example, for ticks with a large number of error messages or run ids, the tooltip truncates so we might not be able to read the cursor information.
