### ISSUE TITLE
[Documentation Feedback] Foo on /_apidocs/ops page

### ISSUE THREAD

**Issue by nlarusstone** [dagster-io/dagster#6693]
You left a foo in your docs:
`The foo foundational unit of computation in Dagster.`
I'm assuming this slipped through after testing, but if this is intentional, feel free to close!

**Comment by yuhan** [comment]
Hi @nlarusstone thanks for catching it. I've put up a PR to fix it just now.

**Comment by rexledesma** [comment]
Resolved with https://github.com/dagster-io/dagster/issues/6758.
