### ISSUE TITLE
Error using "local_dagster_job_package_path" in databricks_pyspark step launcher

### ISSUE THREAD

**Issue by iswariyam** [dagster-io/dagster#6717]
## Summary

_local_dagster_job_package_path_ can be provided as a resource config to databricks_pyspark_step_launcher resource.
However, when used it throws the following error,
 _"Error in config: Provided both 'local_dagster_job_package_path' and 'local_pipeline_package_path' entries. Need to specify one or the other."_

The error is due to a buggy invariant check happening [here](https://github.com/dagster-io/dagster/blob/05643a1e831a51133b1e001976b1d2f73cef2ed1/python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py#L144).

## Reproduction
A simple way to reproduce this error is to execute the dagster_databricks unit tests in the repository by replacing "_local_pipeline_package_path_" with "_local_dagster_job_package_path_" [here]((https://github.com/dagster-io/dagster/blob/7e727515db4e33c4c22bd529065037957db56cc2/python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pyspark.py#L38)) 

## Additional Info about Your Environment
Execute dagster_databricks unit tests available in the master branch or any dagster version (For e.g. 0.13.19) and following the [contributing doc](https://docs.dagster.io/community/contributing) to setup the dev environment.
Python version: 3.7.4

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
@iswariyam - thanks for catching this bug. Would you be interested in submitting a fix? I'd be happy to review it and help it get through.

**Comment by iswariyam** [comment]
I have already submitted a PR (#6718 ) to fix this issue. Could you please review it?

**Comment by yuhan** [comment]
PR merged
