### ISSUE TITLE
UI mixes runs of similar named jobs from different repositories.

### ISSUE THREAD

**Issue by bhundt** [dagster-io/dagster#6725]
## Summary
I have two repositories (dev, staging) which load jobs which are similarly named, but are located in different folders and are loaded using two different entries in workspaces.yaml. When running a job from one repository, the job with the same name but from the other repository gets the same run information displayed in the UI. So it looks like the two jobs have failed at the same time, succeeded at the same time but this is not the case as I can look at the output of the two jobs (which are written to disk) and see that they run at very different points in time.

## Reproduction
Create two jobs with same job name, put them into different repositories which are loaded from the same workspaces.yaml (with one entry for every repo). Execute one job from one repository. The job from the other repository (which was not executed) shows in the UI as executed.

## Dagit UI/UX Issue Screenshots
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/97769/154812756-1fb022a7-d61e-402a-bd9f-15611e2ee252.png">
These two jobs look exactly similar in UI but actually did not run at the same time (as can be seen when looking at the timestamp of the output files).

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey @sryza  I wonder if we could prioritize a fix for this? The problem here is that Runs don't store the repo / repo location of the job, just the name of the job. Anywhere Dagit shows "runs for job X", it's actually "run for jobs with name X" - there's no matching on repo name or repo location.

**Comment by prha** [comment]
Yeah, this has been something we've known we've needed to address for a while.  We'll want to do a schema migration over runs and in the meantime write some extra data as run tags.  Will also need to figure out what to do for backcompat.

**Comment by bengotow** [comment]
Just found another old ticket about this, merging it in here: https://github.com/dagster-io/dagster/issues/2734.  Nice ancient screenshot in there 😅

**Comment by nico525** [comment]
Is there any idea when this issue will be tackled?

**Comment by prha** [comment]
This was gated on some data migrations we needed.  I think those are all in place now and we can land the appropriate gating logic in the next week or two.

**Comment by prha** [comment]
This was landed with https://github.com/dagster-io/dagster/pull/7820 and will go out in the next release.
