### ISSUE TITLE
when left nav is hidden, no easy way to reload repositories

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6727]

**Comment by bengotow** [comment]
Hey @braunjj curious if you have thoughts on this one - I feel like these little embedded refresh icons should do the trick on the asset details page -- the big place the reload option isn't available is on the asset catalog list / graph views?

![image](https://user-images.githubusercontent.com/1037212/156205953-e5827f24-e65b-4543-bd6f-04737466141f.png)

**Comment by hellendag** [comment]
Possibly something we can work toward solving in @braunjj's IA proposal.
