### ISSUE TITLE
Support -c flag (load config from file) in dagit

### ISSUE THREAD

**Issue by danjampro** [dagster-io/dagster#6738]
## Use Case
I am not aware of any mechanism by which I can load a job config from file into dagit. Currently the only way seems to be to copy and paste the config from a yaml file or to type it manually.

## Ideas of Implementation
Just as `dagster` can be invoked with the `-c` flag, so could / should dagit.

Thanks!

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Hi @danjampro, if you drag and drop your yaml file into the Launchpad editor, it should populate the editor with its contents. Hopefully that's a bit more convenient than copy-paste. :)
