### ISSUE TITLE
Make it so that dagit works with WSL1

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#6739]
From Slack [post](https://app.slack.com/client/TCDGQDUKF/threads/thread/C01U954MEER-1645434283.402689).

Maybe also include in dagster documentation that dagit won't work with WSL1.

**Comment by yuhan** [comment]
@alangenfeld from reading the slack thread, to clarify, will this be fixed in 0.14.2?

**Comment by alangenfeld** [comment]
yea this should be resolved
