### ISSUE TITLE
Graph DSL docs references deprecated DependencyDefinition

### ISSUE THREAD

**Issue by dannysepler** [dagster-io/dagster#6796]
## What content is missing
Hi there! I've been looking at the Graph DSL example (https://docs.dagster.io/concepts/ops-jobs-graphs/jobs-graphs#graph-dsl) and I'm just curious if this is something actively supported by Dagster. If so, I see a reference to [DependencyDefinition](https://docs.dagster.io/_apidocs/pipeline#dagster.DependencyDefinition) which seems deprecated since the whole Pipelines page is deprecated.

(Also, it'd be nice to have a bit more examples of the Graph DSL if it's actively maintained, it seems super helpful for my project!)

## Type of the content
- Best Practices Guide

**Comment by sryza** [comment]
Thanks for reporting this @dannysepler . DependencyDefinition is actually not deprecated. We should move it off of the Pipelines page.

**Comment by sryza** [comment]
Here's a fix: https://github.com/dagster-io/dagster/pull/7673.
