### ISSUE TITLE
Add documentation about backfill schedules

### ISSUE THREAD

**Issue by prha** [dagster-io/dagster#6808]
## What content is missing
Some questions about how to implement auto-backfill schedules.  We could include a section on the backfill page with some examples code.

Reference: https://dagster.slack.com/archives/C01U954MEER/p1645736872907019

**Comment by prha** [comment]
There are some non-crag backfilling schedule toys here: https://github.com/dagster-io/dagster/blob/4dbfa80c8f5b9fd61880b6d2f574c08a9fe0f28d/python_modules/dagster-test/dagster_test/toys/schedules.py#L79

We could translate those ideas to our recommended APIs

**Comment by erinkcochran87** [comment]
@prha Is this guy still relevant?
