### ISSUE TITLE
On asset details page, gracefully handle assets that are sources in one repo and definitions in another

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6819]
Users should be able to define an asset as a source asset in one repository and as a derived asset in another repository.

Right now, if they do that, they get this message on the asset details page:
![image](https://user-images.githubusercontent.com/654855/155813792-260f3715-747b-4598-8464-5234c7e3aa2d.png)

**Comment by bengotow** [comment]
Hey Sandy, do we have a repo that repros this? Seems like it should be straightforward to refine that message 👍

**Comment by sryza** [comment]
@bengotow here's a PR for a toy that repos this: https://github.com/dagster-io/dagster/pull/7210
