### ISSUE TITLE
In asset graph and asset details page, include links to downstream assets in different repositories

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6820]
In the below example, the "comments", "stories", and "comment_stories" assets are defined in one repository, and the "comment_daily_stats" and "story_daily_stats" are defined in a different one: 

![image](https://user-images.githubusercontent.com/654855/155814129-f83f31f9-7730-4b6d-aa9a-93f8569a7fde.png)

If you use the repository selector to filter down to only the former repository, then you can still see links to upstream assets in different repositories, but no links to downstream assets in different repositories:

![image](https://user-images.githubusercontent.com/654855/155814261-4e4f2dd9-d395-4199-b26c-db75f03fa8cb.png)

**Comment by sryza** [comment]
@clairelin135 - is this solved by the PR you merged?

**Comment by clairelin135** [comment]
@sryza Yes, this is solved
