### ISSUE TITLE
[Documentation Feedback] Problem on /tutorial/advanced-tutorial/scheduling page

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#6827]
Sidebar page in the tutorial is 404ing in 0.14.2 (but not 0.14.1 or master)

**Comment by yuhan** [comment]
https://docs.dagster.io/tutorial/advanced-tutorial/scheduling seems fine to me. can you repro it now?

**Comment by gibsondan** [comment]
Looks fixed, yeah. Not sure what happened!
