### ISSUE TITLE
"Hidden" __ASSET_GROUP job shows up on factory floor page 

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6832]
![image](https://user-images.githubusercontent.com/654855/156025362-4682cfb0-e6bb-45a4-9ecc-6e9534120103.png)

**Comment by sryza** [comment]
@bengotow - definitely agree we need to figure out what the factory floor should look like in asset-world. Worth a brainstorm.

**Comment by braunjj** [comment]
I think we should hide it and explore adding more asset-related info to Factory Floor
