### ISSUE TITLE
Change ResourceDefinition to take name rather get name from a dict passed into ModeDefinition

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#687]
old:
```@lambda_solid(
    inputs=[InputDefinition('num', dagster_pd.DataFrame)],
    output=OutputDefinition(dagster_pd.DataFrame),
)
```

new:
```@lambda_solid(
    inputs={'num' : Input(Dataframe)},
    output=OutputDefinition(dagster_pd.DataFrame),
)```

**Comment by schrockn** [comment]
At this point I actually think we should probably standardize on having name be part of the object as that's how most of these work. I think `ResourceDefinition` is the only one that is left that relies on the dictionary method now that ContextDefinition is gone. Objects with the name embedded are certainly much easier to deal with in the implementation of the framework.

**Comment by schrockn** [comment]
So thinking about this I'm not sure this is a good idea. This issue is that the key for the resources should be pipeline-specific rather than resource-specific, given the fact that pipelines might have colliding resource names. Curious about opinions here. @mgasner thoughts?

**Comment by mgasner** [comment]
This is fraught, since the whole required_resources concept sort of implies the opposite -- that keys are resources-specific (?) rather than pipeline-mode -specific

**Comment by schrockn** [comment]
Agree. I think we should close this. Current api is what we want

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )
