### ISSUE TITLE
(014.2) Gantt Chart blocks don't show full op names with mouse hover if block labels end with "_..." suffix

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#6870]
In dagit, when I hover my mouse over the ops with names longer than the green blocks, some will show the full op names, while for others it does not.  I found out it depends on how the block's label ends with.  If it ends with "\_...", the mouse hover will not show the full op name.  See below.  The 2 op blocks with a red X next to them do not show full op name due to their labels ending with "_...":

<img width="448" alt="mouse_hover_labels_bug" src="https://user-images.githubusercontent.com/3989299/156403283-b41ef4f0-60a8-4e4c-bff8-a827626917d8.png">

**Comment by bengotow** [comment]
This will be fixed in the next release!
