### ISSUE TITLE
DagsterInvalidDefinitionError still refers to "the solid function"

### ISSUE THREAD

**Issue by markfickett** [dagster-io/dagster#6874]
## Summary
dagster.core.errors.DagsterInvalidDefinitionError: Input parameter start is annotated with Nothing which is a type that represents passing no data. This type must be used via InputDefinition and no parameter should be included in the solid function.

## Reproduction
Here's a GitHub search showing a few references to "the solid function." https://github.com/dagster-io/dagster/search?q=%22the+solid+function%22

**Comment by dpeng817** [comment]
Solved by #6883
