### ISSUE TITLE
"Reload again" button in repository error modal sometimes doesn't work

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6903]
I've observed that sometimes I hit "Reload again" and nothing happens, but if I leave the modal and his the "Reload" button on the workspace page, the repository location reloads

**Comment by hellendag** [comment]
@sryza Do you have reliable repro steps?

**Comment by sryza** [comment]
I don't. We can close for now and I can reopen if I hit it again.

**Comment by sryza** [comment]
@hellendag This has been happening to me almost every time recently. Maybe I can find some time to show you over a zoom?

**Comment by hellendag** [comment]
Moving into "Needs details" until we've got a repro nailed down.

**Comment by sryza** [comment]
I think we can close it and I'll reopen if I encounter it again
