### ISSUE TITLE
Document nested op selection syntax

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#6915]
As of 0.13.18, nested op selection is now possible, but we don't reflect the additional syntax in our docs.

**Comment by erinkcochran87** [comment]
@dpeng817 Is this still needed? I couldn't immediately find a PR about this to look it up, but I did find this section in the Job execution docs (https://docs.dagster.io/concepts/ops-jobs-graphs/job-execution#op-selection-syntax), specifically the `some_op+++` syntax. Is this what you're referring to, or is it something else?

**Comment by dpeng817** [comment]
that's right! I think this can be closed.
