### ISSUE TITLE
Autoscaffold context config if required

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#692]

**Comment by mgasner** [comment]
this means that context config should also be scaffolded in the dagit config editor?

**Comment by schrockn** [comment]
yes

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by bengotow** [comment]
I did a bit of investigation here. The reason that the context isn't being scaffolded is because the top level context composite field is marked as a `selector` but has all optional fields, whereas other selectors have all required fields and you must chose one.

I think we can make it so that the scaffold includes selector composite fields, even if all their field options are optional, but this might lead to the scaffold being a bit more aggressive...
 
```
      "configTypes": [
        {
          "key": "AirlineDemoIngestPipeline.ContextConfig",
          "isSelector": true,
          "__typename": "CompositeConfigType",
          "fields": [
            {
              "name": "cloud",
              "isOptional": true,
              "configType": {
                "key": "AirlineDemoIngestPipeline.ContextDefinitionConfig.Cloud"
              }
            },
            {
              "name": "local",
              "isOptional": true,
              "configType": {
                "key": "AirlineDemoIngestPipeline.ContextDefinitionConfig.Local"
              }
            },

          ...
}
```

**Comment by natekupp** [comment]
Just throwing a cautionary warning here for whenever we pick this up—I do think we should do this, but having fought this part of the system for an entire weekend a few weeks back, I believe this is extremely hard to do within the current config machinery.

Across the system, we have inconsistent semantics for what to do with optional fields, and `key: {}`, `key: None`, and no key present all have significance. We also apply default values in the middle of config traversal; I tried and could not figure out how to safely extricate the application of defaults without breaking something.

To do this, I think we should start with a few things, in rough sequence below:

(1) Add the capability to log / inspect config schemas to enable easier debugging
(2) Formalize the semantics of config values to make this consistent (e.g. config traversal should continue even if a key isn't present, and we should stop using `key: {}` as a means to signal that traversal should descend).
(3) Move the defaults application for `Field` out of the primary config schema traversal.
(4) Redesign the config traversal system, and separate the traversal implementation and the action at each node (e.g. visitor pattern)

**Comment by mgasner** [comment]
closing this in line with #1139
