### ISSUE TITLE
RegisterTaskDefinition fails on ecs with dagster-aws 0.14.3

### ISSUE THREAD

**Issue by saliaaa** [dagster-io/dagster#6926]
## Summary
After upgrading `dagster-aws` to `0.14.3`, it fails to register run on ecs:
`botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Cannot depend on container + 'Daemon_ResolvConf_InitContainer' because it does not exist
`

Downgrading to `0.14.2` works fine.

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/23005200/156764681-f8ac9f9c-5d1f-4469-a14c-d639a934b66d.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @saliaaa - sorry for the trouble here. Is it possible to share the task definition of the task that's launching the run (either here or over DM to @daniel in Slack)? It looks like there's an issue with how we translate the task definition that's launching the run into the task definition for the run itself, and there were some changes to that in 0.14.3 - hopefully will be a quick fix once we understand the exact nature of the problem.

**Comment by saliaaa** [comment]
Sure, I'll write on slack

**Comment by saliaaa** [comment]
Closing the issue, as it's been resolved with PR mentioned above. 🙏🏼 🙇🏼‍♂️
