### ISSUE TITLE
Find sensible place for execution button

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#693]
Also add keyboard shortcut for execution

Pretty weird. Especially when the scroll bar is there

<img width="838" alt="screenshot 2019-01-19 19 14 19" src="https://user-images.githubusercontent.com/28738937/51434827-7a6bea00-1c1e-11e9-97a8-0fd8f11a56f8.png">

**Comment by bengotow** [comment]
Oh lawd. Yeah I think this should be revisited - when we add single step re-execution it may make sense to shift this around a bit. 👍

**Comment by mgasner** [comment]
is this still an issue with the reworked button?

**Comment by bengotow** [comment]
This will be fixed (more) in #842
