### ISSUE TITLE
Put dagit persistent logging under test and make sure it works

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#694]
We have a feature that allows dagit to run in a mode where its logs are persisted to disk instead held in memory. It likely broke with https://github.com/dagster-io/dagster/pull/676

We should make this a full-fledged supported feature with tests, documentation, etc

**Comment by mgasner** [comment]
#344

**Comment by alangenfeld** [comment]
https://dagster.phacility.com/D468
