### ISSUE TITLE
[dagit] problematic recursion ensureChildrenAfterParentInArray in GanttChartLayout.ts

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#6942]
It seems certain graph structures cause a problem with our gantt layout 

https://dagster.slack.com/archives/C02SDECJAKS/p1646406379787209

**Comment by markfickett** [comment]
Thanks for the fix! However, I'm still finding that dagit won't load for my graph when I start a run for > 3 minutes. Here's the debug download from a run. Using dagit 0.14.5. (I renamed it to a .txt file so GitHub would allow the upload.)

[17d5918c-2ce9-40c2-95d4-312b24263a4c-rundebug.txt](https://github.com/dagster-io/dagster/files/8307362/17d5918c-2ce9-40c2-95d4-312b24263a4c-rundebug.txt)
