### ISSUE TITLE
asset runs from global asset graph and asset details page don't have partitioned config

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6953]
I had a set of partitioned assets. I tried to materialize one of them from the global asset graph, but the config for the partitioned assets was missing. Same with the asset details page. I went to the job page for the asset, and when I materialized from there, the config was present.

The tags were present in all cases.

**Comment by geoHeil** [comment]
launchpad would also include the tags - agreed, this is a bug

**Comment by bengotow** [comment]
Hey folks! I'm working to repro this now and it sounds like these assets are in a job? The partitioned assets in the `graph_job_op_toys.partitioned_assets` example seem to be working fine (config + tags are applied to the run launched from the Global Graph page). Will make an example with a partitioned asset job and see if that does the trick.

**Comment by bengotow** [comment]
Hmm, I've created a trivial example:

```
@asset(partitions_def=daily_partitions_def)
def upstream():
    return [1, 2, 3]


@asset(partitions_def=daily_partitions_def)
def downstream_1(upstream):
    return upstream + [4]


@asset(partitions_def=daily_partitions_def)
def downstream_2(upstream):
    return len(upstream)


partitioned_asset_group = AssetGroup.from_current_module()
asset_job = partitioned_asset_group.build_job(name="partitioned_asset_job")
```

When I rematerialize `upstream` from the global graph or the asset details page, I get a run with the following config (looks ok I think?)

![image](https://user-images.githubusercontent.com/1037212/157754027-d38db04c-afcd-4adb-8108-4e84f45fa079.png)

When I rematerialize `upstream` from the job, it uses the job to rematerialize it, but it seems to pass the same config?

![image](https://user-images.githubusercontent.com/1037212/157754068-0a96093f-cfdd-4b70-be64-754e206a2702.png)

In your case, does the job provide additional config? I don't know that that's a supported use case at the moment (eg: an asset that is in the global graph that can't be rematerialized via the asset_group job)

**Comment by bengotow** [comment]
Talked to Sandy about this offline - it sounds like the bug in #6986 was preventing the config from being scaffolded, and Dagit was missing error handling on the config fetch (#7011) and was launching the run anyway.

**Comment by geoHeil** [comment]
Mabe. Have you tried not to schedule from the UI of the asset detail page but:

- workspace
- select the job on the left side. It must be a job which is partitioned and includes software defined assets
- in the overview tab of the dagit pane click the black re-materialize all button
- the run should fail
- - however when you use the launch tab and specify the correct tags/configuration (partitions) it would work nicely

**Comment by bengotow** [comment]
Hey folks! It looks like both the front-end and backend PRs for this have merged, going to go ahead and close this! I did one final test with your case geoHeil and I think we're set, but feel free to re-open if you see anything in the next release!

**Comment by geoHeil** [comment]
I think this one needs to be reopened for 0.14.4.

```
dagster.check.CheckError: Failure condition: The output has no asset partitions

```

for a dummy job of:

```
from dagster import job

from dagster import op, Out
from dagster import job, daily_partitioned_config
from dagster import AssetKey, AssetMaterialization, EventMetadata, Output
from dagster import SourceAsset, asset
from pandas import DataFrame
import pandas as pd
import random
from dagster import job

from ASSET_DEMO.io.simple_io import LocalFileSystemCSVIOManager, LocalFileSystemParquetIOManager
from dagster import IOManagerDefinition

@op(config_schema={"date": str})
def hello_here(context):
    """
    dummy asset with partitions
    """
    date = context.op_config["date"]
    context.log.info(f"processing data for {date}")

from dagster import daily_partitioned_config, DailyPartitionsDefinition
from datetime import datetime


@daily_partitioned_config(start_date=datetime(2022, 2, 1))
def my_partitioned_config(start: datetime, _end: datetime):
    # TODO how to directly get a date object
    # probably use: https://stackoverflow.com/questions/58168488/type-hint-returns-nameerror-name-datetime-not-defined
    return {"ops": {"hello_here": {"config": {"date": start.strftime("%Y-%m-%d")}}}}

@job(config=my_partitioned_config)
def partitioned_dummy_job():
    """
    https://docs.dagster.io/concepts/partitions-schedules-sensors/schedules
    """
    hello_here()

```
fails with the arror above when:
<img width="1141" alt="Job__partitioned_asset_dummy" src="https://user-images.githubusercontent.com/1694964/158901173-3aada259-d333-45d2-9fe5-cdb214215747.png">

clicking rematerialize

**Comment by geoHeil** [comment]
For the launchpad and assets overview - both partitions are selected / asked from the user. But not from the Overview pane.

There no partitions are set - and the job obviously fails.

**Comment by sryza** [comment]
Hey @geoHeil - outputs only have asset partitions if the job is specified using software-defined assets. If you're using ops and jobs without assets, as in the example code you posted, then the error you posted is expected if your IOManager attempts to access one of the asset partition methods on the context.

If you want to use partitions, but aren't using assets, you can avoid that error by using `context.partition_key` instead of.

**Comment by geoHeil** [comment]
You mean:

instead of:

```
date = context.op_config["date"]
```

using

```
date = context.partition_key
```
?

In any case I realized I pasted the wrong code before:
```

from dagster import job

from dagster import get_dagster_logger, Out
from dagster import job
from dagster import AssetKey, AssetMaterialization, EventMetadata, Output
from dagster import SourceAsset, asset
from pandas import DataFrame
import pandas as pd
import random
from dagster import job

from ASSET_DEMO.io.simple_io import LocalFileSystemCSVIOManager, LocalFileSystemParquetIOManager, PandasCsvIOManagerWithOutputAssetPartitions
from dagster import IOManagerDefinition
from dagster import AssetGroup

from dagster import DailyPartitionsDefinition, ResourceDefinition
from datetime import datetime

@asset(partitions_def=DailyPartitionsDefinition(start_date="2022-02-01"))
def dummy_asset_partitioned(context) -> DataFrame:
    """Creates a mini dummy asset which is partitioned"""
    partition_key = context.output_asset_partition_key()
    # TODO 1: how to get the true partition key value and not its object?
    get_dagster_logger().info(f"Partitioned asset from: {partition_key}")
    df = pd.DataFrame({'foo':[1,3,3], 'bar':['a', 'b', 'c']})
    df['partition_key'] = partition_key

    rand_metric_dummy_value = random.randrange(0, 101, 2)  
    yield Output(df, metadata={
        "path": EventMetadata.path('/path/to/file'),
        "value_counts": 10,
        "random_dummy_metric": rand_metric_dummy_value
    })

partitioned_asset_dummy_ag = AssetGroup(
    #"partitioned_asset_dummy",
    assets=[dummy_asset_partitioned],
    source_assets=[],
    resource_defs={
        "io_manager": IOManagerDefinition.hardcoded_io_manager(PandasCsvIOManagerWithOutputAssetPartitions()),
        "partition_bounds": ResourceDefinition.none_resource()
    },
)
partitioned_asset_dummy_pipeline = partitioned_asset_dummy_ag.build_job("partitioned_asset_dummy")
```

This is definitely an SDA - and the problem still persists here as well.

The non-SDA does not show the button to re-materialize anyways.
