### ISSUE TITLE
Show "kind" tags in global asset graph

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6956]

**Comment by sryza** [comment]
@smackesey would it be easy for you to get the compute kind surfacing on the asset nodes?

**Comment by bengotow** [comment]
Hey gang, ok - I have the basic compute kind showing in Dagit, and I see that I can explicitly set it when I create an asset like this:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/1037212/164507677-7f033f9e-a3ad-405b-961c-38e1d39bf0a3.png">

![image](https://user-images.githubusercontent.com/1037212/164507639-8d6f6522-a5ca-48fb-bbf6-9b0c901512bf.png)

However, in the op version of this feature certain `kinds` like "sql" have additional metadata (eg: the actual sql query). I'm thinking that in the right sidebar, we should fetch the other metadata off the op and show it in a new section? Does that make sense? (cc @sryza )

**Comment by bengotow** [comment]
Hey folks - ok I've put up a PR for this and there are two possible behaviors:

1) If you explicitly specify the `compute_kind` on your @asset, you get just the tag and nothing else.

2) If the compute_kind on the asset is being inherited from an op, and that op is populating other op.metadata, you get the full behavior which includes a "Description" section in the right sidebar with kind-based additions, like the "View SQL" button.
