### ISSUE TITLE
after materializing an asset, don't go to run page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6974]
When I materialize an asset, it's typically part of a larger task that involves whatever page I'm materializing the asset from.  E.g. I  notice that the columns for an asset are stale and want to remedy that by rematerializing it. I'd like to hit the rematerialize button, wait for the materialization run to complete, and then look back at the metadata to see if it's fixed.

I typically only want to see the run page if something failed.

**Comment by bengotow** [comment]
This sounds great, I was kind of torn about this behavior - will get a tiny PR up for this now 👍
