### ISSUE TITLE
Add job_namespace to CeleryK8sRunLauncher and the Helm chart

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#6988]
## Use Case
Instead of requiring you to set the namespace in each celery_k8s_job_executor in the job_namespace field, we could allow you to set a default at the run launcher level, that's only overridden if its set at the executor level.

See https://dagster.slack.com/archives/C014N0PK37E/p1646752568643059 for context

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by AndreaGiardini** [comment]
Hello @gibsondan I think https://github.com/dagster-io/dagster/pull/9235 fixes this issue. 
Can you have a look when you get the chance?

**Comment by gibsondan** [comment]
I dont think that PR is sufficient, but https://github.com/dagster-io/dagster/pull/12911/files should resolve this

**Comment by gibsondan** [comment]
jobNamespace can be set on the CeleryK8sRunLauncher in the Helm chart in the release tomorrow (1.2.2). Starting in 1.3, the default namespace will be set to the Helm chart's release instead of the "default" namespace by default.
