### ISSUE TITLE
Same asset shows up multiple times in "downstream assets" of asset on details page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7001]
![image](https://user-images.githubusercontent.com/654855/157555848-87bd129e-1b23-4d26-bfc1-0bb2e098e91d.png)

My guess is that this is happening because the downstream assets show up both in:
* The hidden asset job corresponding to the asset group
* An asset job built from the asset group, which includes them

**Comment by bengotow** [comment]
Have been able to reproduce this 👍  it seems like the assets are being duplicated when they're attached to the repository and this should be a small python fix? Will investigate!
