### ISSUE TITLE
when repository fails to re-load, re-execute fails silently

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7062]
* do a run
* make a change to the code that makes code no longer load 
* hit the re-execute button
* the run says "failed", but has a blank event log

**Comment by hellendag** [comment]
I wasn't able to repro this.

- If I reload the repository after commenting the job out of the repository, the re-execute button on the completed run is correctly disabled.
- If I attempt the re-execution from the Runs page, the menu item is disabled and the bulk re-execution fails correctly.
- If I comment out the job without reloading the repository in Dagit, then attempt the run, I see this error in the logs table:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/2823852/166325887-050bb346-3875-4d28-9e7a-96e2fd14e40b.png">

Do you have more details about which job this occurred on, or anything else that might help narrow down a repro?

**Comment by hellendag** [comment]
Closing as stale. Please reopen if this is still happening.
