### ISSUE TITLE
sensor disabled by adimistrator

### ISSUE THREAD

**Issue by geoHeil** [dagster-io/dagster#7114]
## Summary
before the upgrade to 0.14.4 from 0.14.3 I had some sensors disabled manually in the UI from dagit.
These can now no longer be enabled manually in dagit.

Instead: I am greeted with a message that the sensor has been disabled by the administrator.
Even setting:

```
default_status=DefaultSensorStatus.RUNNING
```

does not fix it.

I have deleted/changed `DAGSTER_HOME` (dummy SQLITE).  this fixes the problem

**Comment by rexledesma** [comment]
Thanks for the report @geoHeil - this was an oversight with some permissions consolidation that we missed here: https://github.com/dagster-io/dagster/blob/f89db08a21cbd9588fc049e117e3cae30f1ec4df/js_modules/dagit/packages/core/src/app/Permissions.tsx#L34-L35. We'll be landing a fix shortly and pushing another release.

**Comment by rexledesma** [comment]
Resolved with https://github.com/dagster-io/dagster/pull/7115 - pushed out 0.14.5 with this change. https://github.com/dagster-io/dagster/pull/7117 should ensure that permissions mishaps like this don't occur in the future.
