### ISSUE TITLE
Upstream data for asset partition erroneously considered missing before refresh

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7118]
I have a materialization for a partition of an asset
![image](https://user-images.githubusercontent.com/654855/158911136-4a900517-bd51-4e68-94ba-904d20b00759.png)

But when I try to launch a run to materialize the corresponding partition in a downstream asset, I get this error:
![image](https://user-images.githubusercontent.com/654855/158911187-083ac988-edbb-45bc-83ee-ac9ff39d4db7.png)

After manually refreshing the page, the error goes away:
![image](https://user-images.githubusercontent.com/654855/158911240-e0bd48e5-44f0-42aa-ab28-a61a41444ff2.png)

**Comment by bengotow** [comment]
Ahh this is super interesting, I think Dagit must be caching this data now that we use it in more places. Will get this fixed.
