### ISSUE TITLE
Formatting Issue in Software-Defined Assets Guide

### ISSUE THREAD

**Issue by lynma01** [dagster-io/dagster#7138]
## What content is missing
There's a "PyObject" tag that isn't rendering correctly in the documentation. 

" ### Combining the assets into a group
    [...]

It's common to use a utility like <"PyObject object="AssetGroup" method="from_module" /"> or **\<PyObject object="AssetGroup" method='from_package_name" />** to pick up all the assets within a module or package, so you don't need to list them individually."

<img width="723" alt="Screen Shot 2022-03-20 at 12 55 41 PM" src="https://user-images.githubusercontent.com/11153510/159173554-4cf59f33-9e86-4464-be4c-c925ecf7fe73.png">

Browser: Firefox - 98.0.1
Accessed: 3/20/202 - 12:58PM EST

---

Writer's Guide: [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Should be resolved by https://github.com/dagster-io/dagster/pull/7136
