### ISSUE TITLE
[Documentation Feedback] Search for "Dynamic" doesn't surface relevant docs

### ISSUE THREAD

**Issue by markfickett** [dagster-io/dagster#7140]
Steps:
1. Open https://docs.dagster.io/getting-started
2. Click into "Quick search for anything"
3. Enter "Dynamic"

Expected:
Top results would be
* https://docs.dagster.io/concepts/ops-jobs-graphs/dynamic-graphs
* https://docs.dagster.io/concepts/ops-jobs-graphs/jobs-graphs#dynamic-mapping--collect

Observed:
Top results are all API reference pages.

Suggestions:
* Make sure the above linked pages are the top results
* Add links to the above from the API reference pages. For example, the intro paragraph at https://docs.dagster.io/_apidocs/dynamic#dynamic-mapping-collect could link to one of them.
* Merge the two linked pages above.

**Comment by yuhan** [comment]
Hi @markfickett, thanks for reporting!

The search is fixed now:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4531914/159335496-0bb2afe5-c839-4c39-b26b-b345a2d97868.png">

There was a bug in our indexing script and it was fixed just now.
