### ISSUE TITLE
Make the left nav collapsed by default even in the workspace pages

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#7170]
In 0.14 se decided to collapse the nav everywhere except for the workspace pages; a user recently shared some feedback in slack that the left nav is distracting in the Launchpad. I think that's fair feedback and we should just collapse the left nav by default in all pages.

![image](https://user-images.githubusercontent.com/2798333/159766001-8cdfec92-de00-47c2-85b3-36d354870d77.png)

**Comment by bengotow** [comment]
I'm a fan of this! I'll put up a quick PR 🙌

**Comment by sryza** [comment]
This feels like a big enough change that I think we'd want to wait for a major release. It might be a better move overall, but I suspect a lot of users rely on the current behavior.

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/8173
