### ISSUE TITLE
Missing dynamic job example to accompany description

### ISSUE THREAD

**Issue by zyd14** [dagster-io/dagster#7173]
## What content is missing
[Dynamic map and collect docs](https://docs.dagster.io/concepts/ops-jobs-graphs/dynamic-graphs#a-dynamic-job) have a duplicative / erroneous example. An example of an op definition is used twice, where the second example seems like it should be an example of a job using the dynamic map and collect pattern.

## Type of the content
- Main Concept: "What is Dynamic Map in Dagster"

## Anything else?
job example could be something like:
```
@job
def dynamic_job():
    pieces = load_pieces()
    results = pieces.map(analyze_piece).collect()
```

---

Writer's Guide: [Docs README](https://github.com/dagster-io/dagster/tree/master/docs)

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
thanks for the report!
