### ISSUE TITLE
Run date is hard to find on the run page (Hidden under info icon tooltip)

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#7197]
![image](https://user-images.githubusercontent.com/2798333/160171895-f7922822-aee4-45d1-a4fc-f8678db56324.png)

**Comment by braunjj** [comment]
@hellendag @sryza What do you guys think about the following change to the run page. This change should make the run date information more obvious instead of hidden under the info icon tooltip.

### We remove the (i) icon next to the run ID, and replace it with two tags that display the `start time` and `run duration`
![image](https://user-images.githubusercontent.com/2798333/161856968-b2db561a-6948-4aa7-82dd-63107a23927e.png)

### users can hover over either new tag to view the start and end times + duration as a tooltip
![image](https://user-images.githubusercontent.com/2798333/161857221-9da68fc4-7ed2-4599-8e5c-7b0006668c16.png)
This tooltip is exactly the same as the current (i) one.

**Comment by sryza** [comment]
Un-hiding this information behind the tooltip sounds reasonable to me.
