### ISSUE TITLE
Link to another run's dagit url from event logs

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#7230]
Helpful when logging about another run, for example if one run kicks off another. I think this would be some special event metadata that Dagit could interpret?

**Comment by sryza** [comment]
We've got `MetadataValue.dagster_run` (though looks like it's missing from the api docs, because it's missing docstring)

**Comment by sryza** [comment]
Here's a PR to add it to our api docs: https://github.com/dagster-io/dagster/pull/7231/files
