### ISSUE TITLE
Display execution plan *before* execution

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#725]
Now that we have running status, if could be a nice enhancement to display the execution plan prior to execution. If we have a valid config, we can construct an execution plan and display it to the user. I actually think could be a really powerful way to explain what the execution plan intuitively.

**Comment by mgasner** [comment]
The more complex the divergence between logical pipeline structure (we need a name for this) and execution plan becomes, the more important this is.

**Comment by mgasner** [comment]
Closing this in favor of #1043

**Comment by mgasner** [comment]
Ack, reopening until #1043 or successor merges
