### ISSUE TITLE
factory floor page says there are no jobs, but sidebar disagrees

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7275]
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/654855/161577819-3774b439-7fa5-4812-bed5-d4bf960b353c.png">

In this case, pretty sure the sidebar is correct

**Comment by bengotow** [comment]
Ahh yep I see how this could happen - it looks like if you have a single repository with more than one job the "default" page of Dagit isn't specified. Will fix this asap.

**Comment by bengotow** [comment]
This has been fixed!
