### ISSUE TITLE
Surface `SkipReason` in Dagit

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7276]
I thought this would show up on the sensor page, but didn't find it there

**Comment by hellendag** [comment]
It looks like the `skipReason` should show up as a tooltip on the "Skipped" tag. Is that not the case?

**Comment by hellendag** [comment]
Closing because I believe this is surfaced on the tag. Please reopen if it's missing.

**Comment by sryza** [comment]
Ah, I didn't think to look there. FWIW, I'm not in love with the tooltip pattern for this kind of information.  I expect to use tooltips to tell me give me hints about how to use the UI, but not for information that's on the critical path of a task I want to complete. I.e. what's outlined here: https://www.nngroup.com/articles/tooltip-guidelines/.

That said, not something I feel super strongly about on this one. Will leave it up to you on whether it's worth revisiting.
