### ISSUE TITLE
On "View tags and config" modal on run details page, add a button for copying config

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7298]
Request from a user

**Comment by abkfenris** [comment]
In addition to copying, a button to load the config directly into the launchpad. Potentially also an option to open in launchpad directly from the 'Re-execute' menu.

**Comment by hellendag** [comment]
An "Open in Launchpad" button is being added to the Run page. 😄 

I'll add a "Copy" button to the config modal.
