### ISSUE TITLE
Remove sensor toggle on asset details page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7329]
It's a little dangerous, because turning it on/off will affect other assets.

**Comment by hellendag** [comment]
How about if the sensor/schedule tag shows up, but doesn't render a switch? So you'd have to click through to the sensor to change it. Seems like it would still be useful to show information about the sensor, no?

**Comment by sryza** [comment]
@hellendag yeah - that's exactly what I was imagining.
