### ISSUE TITLE
solid_selection within schedule seems not to work

### ISSUE THREAD

**Issue by jganzabal** [dagster-io/dagster#7340]
## Summary
When I want to select a subset of ops from a job to be executed from a schedule, it seems to ignore solid_selection list.
You could reproduce it just selecting one OP from a multiple op job. It still executes all ops in job instead of the one selected in solid_selection. Should it be called op_selection? Is it a legacy?

Using version 0.14.7

## Reproduction
```
@schedule(
    cron_schedule="3 2 * * *",
    job=train_spots_job,
    solid_selection=['get_spots_dataframe'],
    execution_timezone="America/Argentina/Buenos_Aires",

)
def train_spots_job_schedule(_context):
    run_config = {}
    return run_config
```

As an important note, I can run this single OP: "get_spots_dataframe", from dagit lanchpad and ir works without any issue

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment]
Hi @jganzabal `solid_selection` is deprecated. If you are using jobs and ops, `op_selection` should work for selecting ops. Please let me know if you still hit an issue when using `op_selection`. 

Side note: we should have handled the deprecation better and we are working on it!

**Comment by jganzabal** [comment]
@yuhan thanks so much. I will give it a try!

**Comment by yuhan** [comment]
Closing this issue for now. Please leave a comment if it's still a problem so we can reopen.
