### ISSUE TITLE
When the Runs page refreshes any open dialogs dissappear

### ISSUE THREAD

**Issue by salazarm** [dagster-io/dagster#7341]
## Summary

On the runs page, we refresh every 15 seconds, when that refresh happens, any open dialogs get removed. It's a poor user experience. 

## Reproduction

1. Go to /staging/instance/runs
2. Open a dialog using the metadata column
3. Wait for refresh and watch it disappear 

## Dagit UI/UX Issue Screenshots

<img width="364" alt="Screen Shot 2022-04-07 at 7 41 42 AM" src="https://user-images.githubusercontent.com/2286579/162190914-00692f68-efb6-43eb-8cfc-0cc0e96fc132.png">

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Hmm, this doesn't repro for me. Is it reliably reproing for you?

**Comment by bengotow** [comment]
Hmm tried to repro this one as well because it seemed serious. I haven't gotten it to happen, even if I "View Configuration" for the last run on the page and then trigger a new run, causing the row I selected to disappear under the open modal. Maybe there's something else required?

**Comment by salazarm** [comment]
Hmm, let me check again. It was reproing consistently for me when I tried the other day.

**Comment by hellendag** [comment]
Closing for now, let's reopen if it repros!
