### ISSUE TITLE
Selection for partitioned in an AssetGroup

### ISSUE THREAD

**Issue by jburnich** [dagster-io/dagster#7342]
## Summary
Hi everyone,
I want to define multiple asset branches in a single `AssetGroup` and I would like each branch to be partitioned with a different `start_date`. So, I created several jobs using a `selection`. But obviously the asset selection for partitioning is done on the AssetGroup and not on the selection. What generates this exception : `When an assets job contains multiple partitions assets, they must have the same partitions definitions, but asset '["branch_1_upstream"]' and asset '["branch_2_upstream"]' have different partitions definitions`.
Is there a solution to solve this problem? Thank you in advance

## Reproduction

```
def make_asset_group(branch, date):
    daily = DailyPartitionsDefinition(start_date=date)
    
    @asset(
        name = f'{branch}_upstream',
        partitions_def=daily
    )
    def asset_upstream():
        ...

    @asset(
        name = f'{branch}_downstream',
        ins={"upstream": AssetIn(asset_key=AssetKey(f'{branch}_upstream'),
        partitions_def=daily
    )
    def asset_downstream(upstream):
        ...

    return [asset_downstream, asset_upstream]


assets_branch = make_asset_group(branch, date) for branch, date in {branch_1 : date_1, branch_2 : date_2}.items()

asset_group = AssetGroup(
  assets=[asset for assets in assets_branch for asset in assets]
)

job_1 = asset_group.build_job(
    selection = [branch_1_upstream, branch_1_downstream]
)
job_2 = asset_group.build_job(
    selection = [branch_2_upstream, branch_2_downstream]
)


@repository
def repository():
    return [asset_group, job1, job2]
```

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @jburnich. This is a current limitation that we're aiming to get rid of. The current workaround would be to put each of the branches in a separate AssetGroup and repository. Would that work for you?

**Comment by jburnich** [comment]
In our case, we have hundreds of branches where the age of the data varies from branch to branch. This may therefore be complicated to manage from a maintenance point of view.

We can still try this separation solution first. But this would involve creating as many AssetGroup as repository. So, is there a way to generate repositories dynamically?

**Comment by sryza** [comment]
There are ways you could hack it with https://stackoverflow.com/questions/5354676/how-can-i-add-attributes-to-a-module-at-run-time, though it gets a little ugly.

It wouldn't be difficult for us to allow multiple AssetGroups on a repository though - we could likely ship that in our release next Thursday. Would that help?

**Comment by jburnich** [comment]
Thanks for your quick return.
Yes, that’s a good idea. I believe that if a repository can contain multiple AssetGroup where each AssetGroup has its own partitioning and scheduler, this would probably solve our problem.
We look forward to testing this new feature.

**Comment by sryza** [comment]
@jburnich - yesterday's release included a change that enables having assets with different partitions definitions within the same group. That turned out to make more sense than enabling multiple AssetGroups within the same repository.

I believe that should address the issue you raised here, so I'm going to close this. Feel free to reopen if not.
