### ISSUE TITLE
Add a method to terminate in progress runs from the Dagster GraphQL client

### ISSUE THREAD

**Issue by Javier162380** [dagster-io/dagster#7356]
## Use Case

Enable the possibility to terminate Dagster executions from the GraphQL python client.

Currently, the GraphQL client exposes a query to terminate in-progress runs(https://docs.dagster.io/concepts/dagit/graphql#terminate-an-in-progress-run), although the GraphQL python client does not have this method explicitly defined.

## Ideas of Implementation

Add an explicit to the python GraphQL client to stop running executions, this way users of the GraphQL python client do not have to implement this method their selves.

## Additional Info

I can contribute to the solution

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.
👍

**Comment by sryza** [comment]
@Javier162380 - if you'd be open to contributing this, we'd appreciate it and be happy to review a pull request.

**Comment by Javier162380** [comment]
Hi @sryza ,

I already make a first PR with the changes https://github.com/dagster-io/dagster/pull/7443, let me know what do you think 🙏

**Comment by rexledesma** [comment]
Resolved with https://github.com/dagster-io/dagster/pull/7443
