### ISSUE TITLE
Consider adding docstrings to our GraphQL schema

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#7370]
## What content is missing
The Dagster GraphQL is a pretty big surface area - the current docs don't accurately show the extent to what's possible with the API that we expose.

https://docs.dagster.io/concepts/dagit/graphql#graphql-api

This could double as documentation for similar APIs that we expose in Dagster Cloud.

We currently generate the schema in `generateGraphQLTypes.ts`. To expose the existing descriptions, all it takes is enabling them to gathered from the introspection query.

```
const result = execSync(
  `dagster-graphql --ephemeral-instance --empty-workspace -t '${getIntrospectionQuery()}'`,
  {cwd: '../../../../examples/docs_snippets/'},
).toString();
```

## Type of the content
Add docstrings to our GraphQL API. 

## Anything else?

Similar to Linear's GraphQL API here: https://github.com/linear/linear/blob/master/packages/sdk/src/schema.graphql. Their schema is directly linked in their documentation: https://developers.linear.app/docs/.

#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by prha** [comment]
This is great... I wonder if we can use these docstrings to document what part of our graphql API is stable (must be backwards-compatible) and which parts can change across minor releases.

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/8346, https://github.com/dagster-io/dagster/pull/8347, https://github.com/dagster-io/dagster/pull/8348. Could potentially add it to the docs in https://github.com/dagster-io/dagster/pull/8350.
