### ISSUE TITLE
Ability to yield a RunRequest from a run status sensor

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#7383]
User says: "While working with sensors, we came to the conclusion that you cannot yield a RunRequest from a run_status_sensor . This forces us to have a generic sensor which queries  runs and assets with  RunsFilter  and EventRecordsFilter , then yield a run request for a downstream graph. This works well enough, but it would be much simpler to have run_status_sensor  able to yield run requests as it would have the job run and the assets it produced in the sensor context, which means we don’t need to go against the storage API".

**Comment by smackesey** [comment]
Had another user confused by this here: https://dagster.slack.com/archives/C01U954MEER/p1653335204256159

I'll also say that the current docs are really unclear on this, sensors are defined on the sensor's page with:

>Sensors are definitions in Dagster that allow you to instigate runs based on some external state change.

This definition as it stands is simply wrong.

**Comment by sryza** [comment]
Another request for this: https://dagster.slack.com/archives/C01U954MEER/p1655913995296399
