### ISSUE TITLE
way to indicate that an asset or asset partition is already materialized

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7389]
> How can I go about such assets, with corresponding data already existing before I define them in Dagster? As a for instance, say I define a partitioned asset with data persisted on S3; if partitions exist prior to modelling the asset on Dagster, would I have to re-materialize these partitions in order to reflect reality within Dagster? Any other way to sync the two worlds?

https://dagster.slack.com/archives/C01U954MEER/p1649712560720919

The best answer we have right now is to create a dummy job that generates a bunch of materializations.

**Comment by ampx-mg** [comment]
Did this ever get resolved on Slack? I have run into this problem myself and I'm not really sure how to proceed.

**Comment by sryza** [comment]
Duplicate of https://github.com/dagster-io/dagster/issues/7389 - already completed.
