### ISSUE TITLE
Tracking task for intermittent dagstermill test failures

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#739]
Keeping a log of example runs that fail

**Comment by schrockn** [comment]
https://circleci.com/gh/dagster-io/dagster/48335?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mgasner** [comment]
https://circleci.com/gh/dagster-io/dagster/69207?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mgasner** [comment]
It might make sense to just retry once when we see `RuntimeError: Kernel died before replying to kernel_info`

**Comment by schrockn** [comment]
https://github.com/dagster-io/dagster/pull/905
