### ISSUE TITLE
Add setuptools to dagster/setup.py install_requires

### ISSUE THREAD

**Issue by cbini** [dagster-io/dagster#7396]
`setuptools` isn't a part of core Python, so when installing Dagster into an isolated environment by a package manager (e.g. PDM, poetry), it will not get picked up and installed as a dependency.

Here's where it's throwing a `ModuleNotFoundError` when I try to run `dagster-cloud agent run`:
https://github.com/dagster-io/dagster/blob/96a6762095eec173d9ec3a524dd64382d34f5ed7/python_modules/dagster/dagster/core/definitions/utils.py#L7

**Comment by sryza** [comment]
Thanks for reporting the issue @cbini . I'm not an expert on Python packaging, but is there a circularity issue here? I.e. `install_requires` is an argument of `setuptools.setup`, which can only be called if setuptools is already there.

**Comment by cbini** [comment]
It's a dev dependency, so you need it to package and distribute Python software, but it's not a vanilla Python module. It's commonly included with Python installer, but if you're creating a clean Python environment with only core modules, it's not included.

If you have code within the actual package that imports `setuptools` modules (i.e. `pkg_resources` the code I linked), it's good practice to include it in whatever dependency manifest you're using (`requirements.txt`, `setup.py`, `pyproject.toml`, etc). Otherwise, end-users will also need to add it to their project dependencies themselves, which is my current workaround. So while `setuptools` isn't explicitly a dependency of my `dagster` project, I have to list it because it's a dependency of `dagster`.

**Comment by sryza** [comment]
Ahh, got it - makes sense.

**Comment by cbini** [comment]
That's right. The issue is only that it's currently assumed to be in your environment. Adding it as a runtime dep should fix it
