### ISSUE TITLE
asset says "upstream changed" even when materialized after partitioned upstream asset

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7434]
Reported here: https://dagster.slack.com/archives/C01U954MEER/p1649863788378579

![image](https://user-images.githubusercontent.com/654855/163242159-a5e917ab-c7fa-44a5-b6ac-0d45987a7ce9.png)

To reproduce:
* Dagit -f this:
```
from dagster import asset, AssetGroup, repository, DailyPartitionsDefinition


@asset(partitions_def=DailyPartitionsDefinition(start_date="2020-02-02"))
def asset1():
    pass


@asset
def asset2(asset1):
    pass


group = AssetGroup.from_current_module()


@repository
def my_job():
    return [group]
```
* Materialize one of the partitions of `asset1`
* Materialize one of the partitions of `asset2`
* Observe that `asset2` says "Upstream changed"

**Comment by hellendag** [comment]
Let's discuss at the next SDA UI meeting.
