### ISSUE TITLE
DagsterLogHandler is not threadsafe 

### ISSUE THREAD

**Issue by adamwbarr** [dagster-io/dagster#7442]
## Summary

I have an op that produces log output on a thread other than the main thread. If this thread happens to be emitting a log message while the op is also emitting a dagster event (for example an `ASSET_MATERIALIZATION` or a `STEP_SUCCESS`), the dagster events are lost.

This can result in the op appearing to have not terminated (and therefore appear grey in the UI); however subsequent ops _do_ go on to be executed. See screenshot below.

The reason for this is that `DagsterLogHandler` is not threadsafe; the field `_should_capture` may be set to `True` while thread A is emitting a record; if thread B also emits a record while this is the case then thread B's record is dropped (because `DagsterLogHandler.filter(...)` returns `False`).

## Reproduction

```python
import logging
import threading

import time
from dagster import op, job, Output, AssetMaterialization, AssetKey, repository

logger = logging.getLogger(__name__)


def background_thread():
    for i in range(0, 100):
        logger.info(f"Background thread: {i}")


@op
def op1():
    yield AssetMaterialization(asset_key=AssetKey(["asset1"]))
    threading.Thread(name="background_thread", target=background_thread).start()
    time.sleep(0.5) 
    yield AssetMaterialization(asset_key=AssetKey(["asset2"]))
    yield Output(123)


@op
def op2(arg):
    logger.info(f"Result of op1: {arg}")


@job
def dropped_events_job():
    op2(op1())


@repository
def dropped_events_repository():
    return [dropped_events_job]
```

## Dagit UI/UX Issue Screenshots

`op1` apparently still executing, even after `op2` has finished:
![image](https://user-images.githubusercontent.com/3532527/163357079-32539b8c-cbcf-4dd7-a293-57e1a1a846bf.png)

`op1` eventually goes grey.
![image](https://user-images.githubusercontent.com/3532527/163357197-a0100eb9-8882-43d1-9b8e-e979a0bbea26.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @adamwbarr . Your assessment of the situation seems correct.

@OwenKephart - I'm looking at the code and not 100% grokking why `_should_capture` is needed. Does the `isinstance(getattr(record, DAGSTER_META_KEY, None), dict)` check in `filter` not protect against these infinite loop situations?

```
    def filter(self, record: logging.LogRecord) -> bool:
        """If you list multiple levels of a python logging hierarchy as managed loggers, and do not
        set the propagate attribute to False, this will result in that record getting logged
        multiple times, as the DagsterLogHandler will be invoked at each level of the hierarchy as
        the message is propagated. This filter prevents this from happening.
        """
        return self._should_capture and not isinstance(
            getattr(record, DAGSTER_META_KEY, None), dict
        )

    def emit(self, record: logging.LogRecord):
        """For any received record, add Dagster metadata, and have handlers handle it"""

        try:
            # to prevent the potential for infinite loops in which a handler produces log messages
            # which are then captured and then handled by that same handler (etc.), do not capture
            # any log messages while one is currently being emitted
            self._should_capture = False
            dagster_record = self._convert_record(record)
            # built-in handlers
            for handler in self._handlers:
                if dagster_record.levelno >= handler.level:
                    handler.handle(dagster_record)
            # user-defined @loggers
            for logger in self._loggers:
                logger.log(
                    dagster_record.levelno,
                    dagster_record.msg,
                    exc_info=dagster_record.exc_info,
                    extra=self._extract_extra(record),
                )
        finally:
            self._should_capture = True
```

**Comment by OwenKephart** [comment]
@sryza that was put in there as a bit of a bandaid fix to handle a different infinite loop case, where adding a new record to the events database would result in a logging call (which would necessitate adding a new event to the database, and so on). We can/should definitely make this bit thread safe though.

**Comment by adamwbarr** [comment]
Thanks for looking into it!
