### ISSUE TITLE
Sub-hourly partitioned configs

### ISSUE THREAD

**Issue by atemmo** [dagster-io/dagster#7468]
## Use Case

In my usage of Dagster one of the main features I am missing is partitioned configs for sub hourly periods. My current workaround is to have regular schedule for continuous running (every N minutes) and an hourly or daily partitioned config for backfilling. But this means that I must have "backfill mode" in the job where the job needs to process several periods in one run (or 2 jobs, one for current running and one for backfills).

## Ideas of Implementation

I can come up with 2 implementations:
1. a sub_hourly_paritioned_config which would take an argument which determines its granularity (every 5, 10 etc minutes)
2. a separate partitioned_config for each case, this would follow the current API design of having hourly, daily etc

I guess another variant is to have a generic partitioned config to which user can pass a timedelta object which would determine granularity but this would be a big change to existing functionality.

## Additional Info

I have an example implementation for 1. case which I will submit as WIP pull request.

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for filing this @atemmo! I left a comment on the PR.

**Comment by sryza** [comment]
`TimeWindowPartitionsDefinition` now accepts arbitrary cron schedules, so you should be able to build a sub-hourly set of partitions.
