### ISSUE TITLE
Override entrypoint when launching runs with Docker containers

### ISSUE THREAD

**Issue by dgorlier** [dagster-io/dagster#7487]
## Use Case
We are using Pantsbuild to build a PEX file encapsulating dagster and all the needed dependencies for a `repository.py` which is outside of the PEX. We set the entrypoint of the PEX to `dagster` and the Pantsbuild option `execution_mode` to `venv` to be able to launch the RPC server with
`$ /bin/my_pex api grpc -h 0.0.0.0 -p 4321 -f repository.py`
This is the CMD of our docker container and it works fine to serve the `repository.py`.

However, when the daemon runs a job, it launches a new container and overrides the CMD with
`$ dagster api execute_run ...`
Since our dependencies are contained inside the PEX file, the container fails because it can't find the required libraries. Would it be possible to override this entrypoint to use the PEX file when the deamon launches a job?

## Ideas of Implementation
None

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
I believe you are looking for `--use-python-environment-entry-point` on `dagster api grpc` 
context: https://github.com/dagster-io/dagster/pull/6147

**Comment by sryza** [comment]
Closing this based on @alangenfeld 's suggestion. @dgorlier - feel free to reopen if that doesn't work for you.
