### ISSUE TITLE
[helm] allow updating annotations for read only dagit deployment

### ISSUE THREAD

**Issue by arunbalasubramani** [dagster-io/dagster#7495]
## Use Case
We would like to spin up the read-only dagit instance supported by dagster helm. However, we need to register the dagit read-only service to [consul](https://www.consul.io/) internally in order to expose it to the users with Okta authentication. With the internal process, we need to set some specific annotations to the service in order for the consul to pick it up. Currently, the dagster helm chart does not expose the required keys in the values to set different annotations to both the dagit deployments.

## Ideas of Implementation
Expose a separate set of helm keys (type, port annotations,..) to modify the properties to the read-only dagit service.

## Additional Info
Slack conversation: https://dagster.slack.com/archives/C014N0PK37E/p1646046355289549

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by johannkm** [comment]
Hi Arun, our current recommended approach for this is to use a [post render filter](https://helm.sh/docs/topics/advanced/#post-rendering) such as Kustomize to adjust the spec as necessary.
