### ISSUE TITLE
K8sRunLauncher fails when job_image isn't defined

### ISSUE THREAD

**Issue by simonvanderveldt** [dagster-io/dagster#7512]
The [K8sRunLauncher docs](https://docs.dagster.io/_apidocs/libraries/dagster-k8s#dagster_k8s.K8sRunLauncher) state
> job_image (Union[dagster.StringSource, None], optional)
> Docker image to use for launched Jobs. If this field is empty, the image that was used to originally load the Dagster repository will be used. (Ex: “mycompany.com/dagster-k8s-image:latest”).

Yet if I don't define it I get the following error when trying to run a Run
```
dagster.check.CheckError: Value in dict mismatches expected type for key dagster/image. Expected value of type <class 'str'>. Got value None of type <class 'NoneType'>.
  File "/usr/local/lib/python3.7/site-packages/dagster/core/instance/__init__.py", line 1698, in launch_run
    self._run_launcher.launch_run(LaunchRunContext(pipeline_run=run, workspace=workspace))
  File "/usr/local/lib/python3.7/site-packages/dagster_k8s/launcher.py", line 249, in launch_run
    self._launch_k8s_job_with_args(job_name, args, run)
  File "/usr/local/lib/python3.7/site-packages/dagster_k8s/launcher.py", line 201, in _launch_k8s_job_with_args
    {DOCKER_IMAGE_TAG: job_config.job_image},
  File "/usr/local/lib/python3.7/site-packages/dagster/utils/__init__.py", line 611, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/instance/__init__.py", line 1167, in add_run_tags
    return self._run_storage.add_run_tags(run_id, new_tags)
  File "/usr/local/lib/python3.7/site-packages/dagster/core/storage/runs/sql_run_storage.py", line 456, in add_run_tags
    check.dict_param(new_tags, "new_tags", key_type=str, value_type=str)
  File "/usr/local/lib/python3.7/site-packages/dagster/check/__init__.py", line 196, in dict_param
    return _check_mapping_entries(obj, key_type, value_type, mapping_type=dict)
  File "/usr/local/lib/python3.7/site-packages/dagster/check/__init__.py", line 1323, in _check_mapping_entries
    f"Value in {mapping_type.__name__} mismatches expected type for key {key}. Expected value "
```

**Comment by johannkm** [comment]
Are you deploying with the provided helm chart? We use the container image from the repo origin, and default back to the `job_image` field if it's not provided. https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py#L195-L197

That variable gets provided by setting the `DAGSTER_CURRENT_IMAGE` env var:
https://github.com/dagster-io/dagster/blob/master/helm/dagster/charts/dagster-user-deployments/templates/deployment-user.yaml#L47-L48

If you're running your own grpc server, you'll want to include that env var on it. If you're bundling Job code with Dagit, you'll either want to set that env on Dagit and the Daemon or set `job_Image` on the launcher.

**Comment by johannkm** [comment]
Comment if this doesn't resolve and I'll re-open. We could also improve the docs here

**Comment by simonvanderveldt** [comment]
@johannkm Thanks for the reply. I wasn't aware that the `DAGSTER_CURRENT_IMAGE` env var gets used for this. In that case I'd classify this as a documentation "bug", because the docs say that `job_image` is optional, but then it's apparently only really optional if the `DAGSTER_CURRENT_IMAGE` env var is set. Would be good to mention that in the `K8sRunLauncher.job_image` description I think.
