### ISSUE TITLE
When underlying process is killed during dagit execution the button keeps on spinning

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#752]
![screenshot 2019-01-30 13 53 09](https://user-images.githubusercontent.com/28738937/52015322-8ebdab80-2496-11e9-9d79-12682a28d29a.png)

**Comment by mgasner** [comment]
Is this still true @bengotow ?

**Comment by schrockn** [comment]
This still seems to be an issue. This is the state of things when you kill the airline demo while execute is proceeding.

<img width="530" alt="Screenshot 2019-04-01 07 46 34" src="https://user-images.githubusercontent.com/28738937/55336749-4b5dca00-5452-11e9-914b-c6ea891b58b8.png">
