### ISSUE TITLE
[Project] Multiprocessing-based execution engine

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#757]

**Comment by mgasner** [comment]
#857

**Comment by mgasner** [comment]
I believe we are good to close this.

**Comment by mgasner** [comment]
Next step is being able to configure concurrency, e.g. `dagster -n 4`

**Comment by mgasner** [comment]
https://dagster.phacility.com/D11

**Comment by natekupp** [comment]
@mgasner do we still need to keep this issue around?

**Comment by mgasner** [comment]
@alangenfeld can you confirm that we are in fact running using multiproc?

**Comment by mgasner** [comment]
Closing this in favor of #1407
