### ISSUE TITLE
User code deployment subchart does not allow numeric git shas as a docker image tag.

### ISSUE THREAD

**Issue by jrouly** [dagster-io/dagster#7578]
## Summary

* We use the Dagster user code deployment Helm sub-chart to deploy our Dagster repositories to Kubernetes.
* We use short git shas to version our Docker images.
* Sometimes we get a purely numeric short git sha for a Docker image tag (e.g. `5176135`)

When setting a numeric tag for the Dagster user code deployment sub-chart, Helm schema verification rejects it:

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
dagster-user-deployments:
- deployments.0.image.tag: Must validate at least one schema (anyOf)
- deployments.0.image.tag: Invalid type. Expected: string, given: integer
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/7579.
