### ISSUE TITLE
Linkify URLs in log messages

### ISSUE THREAD

**Issue by markfickett** [dagster-io/dagster#7606]
## Use Case
I'd like to add a link to a relevant external dashboard for a given job run, and it's easy to dump that URL in the logs. It'd be nice to click on the link and open it up easily!

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
You can add https://docs.dagster.io/_apidocs/ops#dagster.MetadataValue.url to one your outputs in your job run.
