### ISSUE TITLE
Passing configs to AssetGroups materialize()

### ISSUE THREAD

**Issue by dpad** [dagster-io/dagster#7621]
## Summary

Unless I'm misunderstanding the way AssetGroups are supposed to work, it does not seem possible to pass a configuration to an AssetGroup's `materialize()` method.

(Edit: Ok, so it seems we should probably do it manually, calling `build_job()` first and then `execute_in_process(run_config=...)`. I guess it would be a nice-to-have on the `materialize()` method as well?)

## Reproduction

I don't have a minimal example coded up, but as an example, defining an AssetGroup that contains a `resource_defs` including a `ResourceDefinition.string_resource()`, it does not seem possible to provide a configuration value for that string resource when trying to materialise said AssetGroup.

## Additional Info about Your Environment

dagster 0.14.12

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for raising this @dpad . @smackesey is currently investigating this functionality.

**Comment by sryza** [comment]
This has been added!
