### ISSUE TITLE
K8sRunLauncher should automatically delete the Jobs it creates

### ISSUE THREAD

**Issue by simonvanderveldt** [dagster-io/dagster#7623]
K8sRunLauncher creates a Job, which then creates a Pod (or multiple Pods in case of a failure) for each Run. None of these Jobs and Pods get cleaned up, resulting in our case in 500+ Jobs and Pods being present after 1 day of running:
```
$ kubectl get jobs -n tnt-dp -l app.kubernetes.io/instance=dagster | wc -l
529
```
which just clutters up the cluster.

Jobs that are finished should be deleted, there's no point in keeping them around. I guess in case of a failure one could argue it might be useful to keep them around, although on the other hand IMHO the logging in Dagster should be good enough to provide all the necessary information and it shouldn't be necessary to keep the failed Jobs around for these purposes either.
In any case, definitely for succeeded Jobs they should not be kept.

P.S. I've raised this as a bug because it's unexpected behavior for me, but someone could argue it's a feature request I guess.

**Comment by rexledesma** [comment]
We have documentation on this: https://docs.dagster.io/deployment/guides/kubernetes/customizing-your-deployment#kubernetes-job-and-pod-ttl-management

We recommend that you let your cluster handle the cleanup of these jobs and pods.

**Comment by simonvanderveldt** [comment]
@rexledesma I'm aware, we already autoremoving everything after a while, but what Dagster leaves behind is entirely unworkable for us. We're scaling to about 500 dags, and really don't want 500 Jobs and Pods staying around cluttering our cluster views. There's also no reason at all to keep them around, so if this is a decision that was made in the past it would be a good idea to revisit that.

**Comment by johannkm** [comment]
Hi @simonvanderveldt, could you expand on what would be missing with the [native K8s TTL](https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs) set to 0? Is the latency high for it deleting them? The solutions I can think of from the Dagster side would essentially be re-implementing that

**Comment by simonvanderveldt** [comment]
@johannkm AFAIK that allows no way to distinguish between Succeeded/Completed and Failed Jobs. We've generally found it useful to keep Failed Jobs around to be able to inspect them as part of the troubleshooting process.

**Comment by johannkm** [comment]
The recommendation in the [docs](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) is

> Use a [mutating admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#admission-webhooks) to set this field dynamically after the job has finished, and choose different TTL values based on job status, labels, etc.

So it seems like that's an option, though a bit of a pain. I also haven't immediately been able to find an example of someone doing that. Another approach would be one of the cron jobs running the `kubectl delete job <filters>` on a tighter loop.
