### ISSUE TITLE
Handle failures of Pods created for Runs by K8sRunLauncher

### ISSUE THREAD

**Issue by simonvanderveldt** [dagster-io/dagster#7641]
## Use Case
When using K8sRunLauncher failures outside of the scope of the Run Pod (things like the node where the Pod is running on scaling down or a replacement of this node because of maintenance) should not cause a failure of the Run.
There's already something like this in place [when using K8sRunLauncher with the k8s_job_executor](https://github.com/dagster-io/dagster/blob/43cf8660d23c92e7b0b80b838836e6736f4f38da/docs/content/deployment/run-monitoring.mdx#detecting-run-worker-crashes) but not for other cases like K8sRunLauncher with the multiprocess_executor.

Currently when using K8sRunLauncher with the multiprocess_executor if the Run Pod dies the Run is failed, irrespective of what caused this failure. After that a new Pod is started which also fails (because according to Dagster there’s already a Run running) and then the Kubernetes Job is marked as succeeded.

## Implementation ideas
If the Pod created for the Run fails because of something outside of the scope of the Pod like the node going down the K8sRunLauncher should take care of creating a new Pod. This new Pod should continue where the previous one stopped. Since the last Op run in the previous Pod probably failed, retry that.

## Additional Info
Two things I'm not sure about:
- Should this only apply to failures caused by things outside of the Pod? And if so, how can be determined if this is the case? I'm not sure the Kubernetes API is descriptive enough to be able to distinguish a failed process within the Pod from a Pod that gets killed because the node went away.
- Should Ops be somehow informed that they are being retried? I can imaging there might be cases where someone might want different behavior when an Op is restarted/tried again vs starting fresh.

**Comment by simonvanderveldt** [comment]
copied from Slack
> Next week we’ll ship automatic re-execute from failure. This retries a Job in a whole new Dagster run (the same experience as manually re-executing in Dagit). We still think that resuming the run in place is the optimal experience for K8s failures, but this will at least be a kind of brute force solution

@johannkm did this happen? I checked the recent changelogs but didn't see any mention of a change like this.

**Comment by johannkm** [comment]
It shipped on Dagster Cloud, but we ended up having to add a new table for performance. We should be able to release it in 0.15.0 when we can ask users to run a DB migration.

**Comment by simonvanderveldt** [comment]
OK, thanks for the info. Will keep an eye on the releases and test it out once 0.15.0 hits :)

**Comment by johannkm** [comment]
I neglected to update this issue, but run retries shipped: https://docs.dagster.io/deployment/run-retries. The only caveat for this use case is that retries will apply to both system failures and user code failures. Created a tracking issue for that here: https://github.com/dagster-io/dagster/issues/9738
