### ISSUE TITLE
default IO asset manager doesn't handle op outputs inside graph-backed assets

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#7713]

**Comment by sryza** [comment]
@OwenKephart @clairelin135 - is this something you're working on? If not, I might be able to take it on.

**Comment by clairelin135** [comment]
I think this may be related to @OwenKephart 's root input manager work, tagging him to clarify

**Comment by OwenKephart** [comment]
Ah yeah this problem -- forgot to include that fix. The simple fix is just checking if you have an asset key or not (and if not, falling back to a run-scoped key)
