### ISSUE TITLE
In run_config 'int' becomes 'None' while using a graphql client to trigger the job.

### ISSUE THREAD

**Issue by Jaikant** [dagster-io/dagster#7762]
## Summary

Using graphql to launch a job. The run_config data is pretty big, but to summarize it is something like below.

```
{
  resources: {
    ...
  },
  ops: {
    query_get_cart_order_detail: {
      config: {
        data: {
          id: 4764400517342
        }
      }
    }
  }
}
```

The `data` above is a dictionary which contains a lot more.
What I observed was the value of `id` in the config, is becoming `None`
I was not sure if it was because of the type of id being an `int`. So I changed it into a `str` and then the value is retained.

## Additional Info about Your Environment
I am using a graphql client, to trigger the jobs.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by prha** [comment]
Hi Jaikant!

I can't repro this bug... can you share a little more information on your op config and your dagster version?

Here's what I'm finding on `0.14.14`:
```
# in example.py
from dagster import op, job, repository, get_dagster_logger

@op(config_schema={"num": int})
def my_op(context):
    num = context.op_config["num"]
    get_dagster_logger().info(f"num is {num} {type(num)}.")

@job
def my_job():
    my_op()
```

When invoking the python graphql client:
```
>>> from dagster_graphql import DagsterGraphQLClient
>>> client = DagsterGraphQLClient("localhost", port_number=3333)
>>> client.submit_job_execution("my_job", run_config={"ops": {"my_op": {"config": {"num": 4764400517342}}}})
'61eba854-c42e-4263-b4b4-59b34740228c'
```

Log output:
```
2022-05-06 11:41:57 -0700 - dagster - INFO - my_job - 61eba854-c42e-4263-b4b4-59b34740228c - my_op - num is 4764400517342 <class 'int'>.
```

**Comment by Jaikant** [comment]
@prha I am on 
```
dagster, version 0.13.12
```

I ran your code on 0.13.2, inside a repo, with the int having a much higher value on the graphql interface using the below query

```
{
  isPipelineConfigValid(
    pipeline: {
      pipelineName: "my_job"
      repositoryName: "my_repository"
      repositoryLocationName: "example.py"
    }
    runConfigData: {
      ops: {
        my_op: {config: {num: 111111111111}}
      }
    },
    mode: "default"
  ) {
    __typename
    ... on PythonError {
      message
      className
      stack
      cause {
        message
      }
    }
    ...on RunConfigValidationInvalid {
      errors {
        message
      }
    }
    ...on Error {
      message 
    }
  }
}

```

I get the response of an invalid config,  like below:
```
{
  "data": {
    "isPipelineConfigValid": {
      "__typename": "RunConfigValidationInvalid",
      "errors": [
        {
          "message": "Value at path root:ops:my_op:config:num must not be None. Expected \"Int\""
        }
      ]
    }
  }
}
```

I am using the [prisma graphql client](https://github.com/prisma-labs/python-graphql-client) and in my case, the query `isPipelineConfigValid` was successful. But on executing the pipeline the `ints` turned into `None`. 

In my case it was an id with a value of `4764400517344`

**Comment by prha** [comment]
Hi Jaikant.

I was able to repro the error you were getting.  Unfortunately, GraphQL has the limitation around supporting ints larger than 32 bits.  (See https://stackoverflow.com/questions/44982279/graphql-large-integer-error-int-cannot-represent-non-32-bit-signed-integer-valu)

However, we do support json strings for the `runConfigData`, so you might be able to work around this limitation by first json serializing the whole payload, and passing the value in as a string.

```
client.execute(query, {"runConfigData": json.serialize({ "ops": {"my_op": {"config": {"num": 111111111111}}}})})
```

**Comment by Jaikant** [comment]
@prha thanks for your help. Serializing works okay.
