### ISSUE TITLE
dagstermill intro tutorial

### ISSUE THREAD

**Issue by puma314** [dagster-io/dagster#783]
An actual dagstermill intro tutorial that is simultaneously accessible but also shows off more complexity than the hello world (or add two numbers) but less complicated than the airline demo.

**Comment by mgasner** [comment]
#781

**Comment by puma314** [comment]
Break into chunks

https://github.com/dagster-io/dagster/pull/781#pullrequestreview-205897289
https://github.com/dagster-io/dagster/pull/781#pullrequestreview-205942168
