### ISSUE TITLE
Dagit GraphQL playground should work offline/behind a firewall

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#785]
Right now we get an error like:

```
Loading failed for the <script> with source “http://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js”.
```

We should vendor this dependency and any others being fetched from CDN

**Comment by bengotow** [comment]
Wow the playground is just a python template... I think that we may have gone this route because there's not a great way to pull in node modules without adding dependencies on node. Will see if there's anything we can do here.

**Comment by mgasner** [comment]
By vendor, I think I mean check into source control 🙈

**Comment by alangenfeld** [comment]
just hit this 🤡

**Comment by mgasner** [comment]
https://dagster.phacility.com/D613
