### ISSUE TITLE
asset display : compute_kind

### ISSUE THREAD

**Issue by jburnich** [dagster-io/dagster#7928]
## Summary

Hi Dagster Team, 
It's not a major issue but I'll point out anyway. I just noticed that in some cases where the asset height is large, the `compute_kind` display spills over to the downstream asset.

## Dagit UI/UX Issue Screenshots

<img width="233" alt="Capture" src="https://user-images.githubusercontent.com/99728876/168819736-030ace3e-ce70-47ce-a2d3-83bda10f500b.PNG">

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
Thanks for pointing this out! it will get triaged and put in our backlog!

**Comment by sryza** [comment]
@bengotow did this get addressed?

**Comment by bengotow** [comment]
Hey @sryza - I tried to repro this one but wasn't able to get the assets to be that close together in the graph, need to figure out how that happened.

**Comment by jburnich** [comment]
I hadn't made the capture big enough, I think this happens when the asset name is too long.
<img width="168" alt="Capture" src="https://user-images.githubusercontent.com/99728876/174118150-a2285e52-4026-4694-af1d-1f9d3ccaedad.PNG">

**Comment by bengotow** [comment]
Hey folks! This has been fixed, it was actually an issue with our layout engine not computing the height of the asset correctly.
