### ISSUE TITLE
Contexts and resources with cleanup requirements will not work in dagstermill

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#796]
```
        # BUG: If the context cleans up after itself (e.g. closes a db connection or similar)
        # This will instigate that process *before* return. We are going to have to
        # manage this manually (without an with block) in order to make this work.
        with yield_context(pipeline_def, typed_environment, execution_metadata) as context:
            self.info = DagstermillInNotebookExecutionInfo(context, pipeline_def)
```

**Comment by mgasner** [comment]
note that in dagster-airflow, the semantics of contexts are also different -- they are execution-step-scoped, rather than execution-plan-scoped. This is going to be an issue for, e.g., ephemeral EMR clusters.

**Comment by schrockn** [comment]
Ya. I’m really focusing on the execution engine this week. Let’s discuss tmrw

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by puma314** [comment]
I think I get the gist of the problem but not exactly what "manage this manually (without an if block)" means? Would be nice to discuss some time either over slack or zoom.

**Comment by schrockn** [comment]
I meant "without a with block"! whoops

**Comment by mgasner** [comment]
https://dagster.phacility.com/D263
