### ISSUE TITLE
Asset CLI

### ISSUE THREAD

**Issue by clairelin135** [dagster-io/dagster#7994]
Operations:
- Materialize a selection of assets
- Show status of a selection of assets (last time materialized, etc.)

Options:
- Partition

What we've heard:
- https://dagster.slack.com/archives/C01U5LFUZJS/p1666357154963809
- https://www.reddit.com/r/dataengineering/comments/1152wow/comment/j937ise/?utm_source=share&utm_medium=web2x&context=3
- Chris Histe - https://dagster.slack.com/archives/C01U954MEER/p1677706795517989
  - Hello, we can execute jobs in the CLI using dagster job execute -f my_job.py, that’s great. Is there a way to do the same for an @asset or @op? Thanks. I couldn’t find anything in the [reference](https://docs.dagster.io/_apidocs/cli)

**Comment by slopp** [comment]
Dagster now has support via

```
dagster asset materialize 
```

**Comment by sryza** [comment]
In light what @slopp brought up, I'm going to close this. We can open up followup issues for additional CLI functionality.
