### ISSUE TITLE
is_required on @asset

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8011]

**Comment by sryza** [comment]
So the main question here is what to name this argument.

`is_required` is a very sensible name for an argument on `Out`, because it's like "is the op required to yield this output", but can the same be said for asset? "is the asset required to yield itself" doesn't make quite as much sense.

**Comment by jamiedemaria** [comment]
I agree that `is_required` is a confusing name without the context of what the param does in op-land. fwiw, I was unclear as to what this issue fully meant until the linked issue (#9220) was opened.

I assume that if asset A is a table in snowflake and we've successfully materialized the asset before, then if we re-materialize and return None, the snowflake table remains as it was after the first materialization. Then any downstream assets would not execute (and asset sensors wouldn't trigger). Let me know if any of that is incorrect. 

Given all of that, the new param seems less about "this asset is required to exist" or "this asset is required to produce itself" and more like "this asset is updated conditionally" and "this asset can halt execution". 

spitballing some names here: `is_noneable`, `optional`... ? not sure i like any of those, but i'll keep thinking on it

`is_required` might not be so bad with a good doc string and explanation in the concepts pages,

**Comment by sryza** [comment]
> I assume that if asset A is a table in snowflake and we've successfully materialized the asset before, then if we re-materialize and return None, the snowflake table remains as it was after the first materialization. Then any downstream assets would not execute (and asset sensors wouldn't trigger). Let me know if any of that is incorrect.

Exactly.

is_optional sounds better to me than is_required.

Throwing out some more ideas:
- is_conditional
- always_materialize
- always_output
- Dispense with a definition-level argument and allow the user to raise a some sort of `SkipMaterialization`.  Though this wouldn't work in situations where one asset of a multi-asset gets updated but another does not.

**Comment by jamiedemaria** [comment]
I like `always_materialize`, it's specific to what's happening
