### ISSUE TITLE
[tracking] asset-resources

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#8022]
1. Add resource defs to assets https://github.com/dagster-io/dagster/pull/7918
2. Add io manager defs to assets https://github.com/dagster-io/dagster/pull/7920
3. Pending job definitions https://github.com/dagster-io/dagster/pull/7921
4. Resource requirement refactor https://github.com/dagster-io/dagster/pull/7947
5. Add io manager defs to source assets https://github.com/dagster-io/dagster/pull/8105
6. with_resources method https://github.com/dagster-io/dagster/pull/8019

**Comment by sryza** [comment]
@dpeng817 do you think we can close this?
