### ISSUE TITLE
[Dagster docker] Missing dagster-mysql

### ISSUE THREAD

**Issue by phuongdinh1411** [dagster-io/dagster#8024]
## Summary

Dagster-mysql is missed in dagster-celery-k8s docker image.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Duplicate of https://github.com/dagster-io/dagster/issues/4610. Currently in the helm chart, we assume postgres as your storage backend.
