### ISSUE TITLE
Allow .map to accept arguments to the OP it's mapping to

### ISSUE THREAD

**Issue by AlejandroUPC** [dagster-io/dagster#8026]
## Use Case

I have a static file I load from another OP with two columns I use to map some id's to their descriptions.

I want to be able to handle my data dynamically and using the .map function to chain ops but passing arguments between.

## Ideas of Implementation
To me it would look like
```
first_op.map(second_op,args=(a,b))
```

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by alangenfeld** [comment]
Just for reference, how to solve the problem with the current API is documented here https://docs.dagster.io/concepts/ops-jobs-graphs/dynamic-graphs#additional-arguments

**Comment by smackesey** [comment]
Hi Alejandro, could you clarify what `first_op` and `second_op` look like? What are `a` and `b` here? Are they dynamic outputs of `first_op`?

**Comment by AlejandroUPC** [comment]
> Just for reference, how to solve the problem with the current API is documented here https://docs.dagster.io/concepts/ops-jobs-graphs/dynamic-graphs#additional-arguments

@alangenfeld  sorry I missed it, thanks!
