### ISSUE TITLE
dagstermill CLI: add top metadata cell retroactively

### ISSUE THREAD

**Issue by puma314** [dagster-io/dagster#804]
add a dagstermill CLI to add the top metadata cell if someone needs it. 

Ideal workflow: 
--Someone works on notebook
--Once they need the context for some reason (e.g. a config-driven Spark context or DB connection or whatever), have the CLI consume the existing notebook and inject the top cell with the repo name and information

**Comment by mgasner** [comment]
https://dagster.phacility.com/D446
