### ISSUE TITLE
Airflow tests not picking up changes in circleci?

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#805]
This failure was quite suspect:

https://circleci.com/gh/dagster-io/dagster/62526?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This looks like it was doing logic in a version of dagster not in that repo, but maybe from public? Or maybe docker caching bug?

**Comment by mgasner** [comment]
Yeah, I think this is because of installing from requirements.txt in the Dockerfile

**Comment by mgasner** [comment]
Resolved in #803
