### ISSUE TITLE
More efficiently use memory by garbage collecting results in iterate_step_events_for_execution_plan

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#811]

**Comment by schrockn** [comment]
Assigning to you alex to assess this. This was created before the notion of the intermediates manager. In the parlance of today, this is asking whether or not we should garbage collect intermediate results as execution unfolds. This could be an issue for long running executions where you don't want to keep around all results for forever.

**Comment by mgasner** [comment]
These internals have changed, I think we should close this task or rename it.

**Comment by schrockn** [comment]
the core issue is still relevant. for a multi-step computational all intermediate values held in memory

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
consider doing this with a weakref dict

**Comment by natekupp** [comment]
@schrockn - is this still important? This is only a problem for in-memory intermediates, correct?

**Comment by schrockn** [comment]
not really a concern until we execute many steps in one process in production. feel free to close for now

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
