### ISSUE TITLE
Jobs and graphs docs page is returning 404

### ISSUE THREAD

**Issue by edumucelli** [dagster-io/dagster#8118]
## What content is missing
Hey, the [jobs and graphs](https://docs.dagster.io/concepts/ops-jobs-graphs/jobs-graphs) page is returning 404, but it only happens when you click on the left side menu (highlighted). It will work when you go through the link I just let, but once there when you click on the menu it will 404

![jobs-graphs](https://user-images.githubusercontent.com/959623/171201446-fd3a0e84-643e-40c9-866f-b4141a26607d.png)

---
#### Message from the maintainers:
Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by yuhan** [comment]
Hi @edumucelli thanks for flagging! However, I can't repro it on my end - is it still an issue?

**Comment by edumucelli** [comment]
Hey @yuhan, thanks for the prompt response. Interestingly it is not happening anymore! I am closing it.
