### ISSUE TITLE
We should emit an event before we init resources so that the dagit UI doesn't appear unresponsive

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#816]
Steps to reproduce:

In a fresh environment, run dagit from the root of the airline demo repository. Bring up the postgres (docker-compose up). Run the download pipeline (http://127.0.0.1:3000/airline_demo_download_pipeline/execute) using the config fragments in environments/local_base.yml and environments/local_fast_download.yml

Nothing will appear to change in the dagit UI, but there will be a bunch of log spew in the terminal window running dagit as the spark resource resolves dependencies. We should emit an event before this resource is created so that the spinner, etc., provides the user some indication that the system is working.

**Comment by schrockn** [comment]
Oh this is interesting. I think the right thing to do here is to actually model resource init as an execution step itself. This will be indeed for stuff like an EMR cluster spin-up

**Comment by mgasner** [comment]
Yep, that works too

**Comment by mgasner** [comment]
The spew / hang is on this line: https://github.com/dagster-io/dagster/blob/master/python_modules/airline-demo/airline_demo/resources.py#L31

**Comment by bengotow** [comment]
Based on the discussion yesterday, we decided to handle this by having the app display some affordance that the graphQL mutation to start the pipeline is in progress, since we can't subscribe to logs until the run has started. 086d67c92f991d6f0dc2f5da9ea144335fcc4da4
