### ISSUE TITLE
Assets graph doesn't load in Safari

### ISSUE THREAD

**Issue by creativedutchmen** [dagster-io/dagster#8194]
## Summary
When visiting the assets graph view, the page is stuck at "Rendering a large number of assets, please wait". Looking at the console, it's because the page is not allowed to load some js: `Refused to load https://*****/static/js/616.530fc15b.chunk.js because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.`

The page works in Firefox.

## Additional Info about Your Environment
Dagster 0.14.17 running in k8s using the helm chart, behind an Nginx ingress. There are a few hundred assets in the graph (mostly dbt)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
@creativedutchmen Unfortunately, I'm not able to repro this in Safari 15.5. What version of Safari are you using?

**Comment by hellendag** [comment]
Closing in the meantime, please reopen if you have a reliable repro. Thanks!

**Comment by creativedutchmen** [comment]
I'm on safari 15.2 (17612.3.6.1.6) - unfortunately getting a minimal repro is quite a pain because it only really happens with a large graph. I'll try to update to 15.5 and see if that fixes things
