### ISSUE TITLE
Apparent autoscaffold regression on airline demo download pipeline

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#820]
Steps to reproduce:

Run dagit from the airline demo repository. Navigate to http://127.0.0.1:3000/airline_demo_download_pipeline/execute and add a new config pane. No config is scaffolded.
<img width="637" alt="screen shot 2019-02-12 at 1 29 34 pm" src="https://user-images.githubusercontent.com/427016/52669272-a3ad2c80-2ee3-11e9-9fb9-19ac4e33d81c.png">

**Comment by schrockn** [comment]
I dug into this a bit. Pretty sure it is client side. GraphQL looks like.
![screenshot 2019-02-12 17 34 03](https://user-images.githubusercontent.com/28738937/52680204-7d3fbf00-2eec-11e9-85ae-da099499f714.png)
![screenshot 2019-02-12 17 33 54](https://user-images.githubusercontent.com/28738937/52680206-803aaf80-2eec-11e9-8b5e-b8c5c0c95256.png)
