### ISSUE TITLE
TypeError: issubclass() - when using DynamicOutputDefinition/DynamicOutput/DynamicOut - Dagster 0.14.19 

### ISSUE THREAD

**Issue by orelalonn** [dagster-io/dagster#8201]
## Summary

After updating to Dagster 0.14.19, I get an error `TypeError: issubclass() arg 1 must be a class` caused by lines 843 & 915, in `resolve_dagster_type` & `is_dynamic_output_annotation` respectively, in `dagster/core/types/dagster_type.py`.

The line is:
`not (isinstance(dagster_type, type) and issubclass(dagster_type, DagsterType))`
It can be seen that the argument `dagster_type` is used as first argument in both `isinstance` and `issubclass`. But the first function receives an instance as first argument, while second function receives a class as first argument.
The second call should be `issubclass(type(dagster_type), DagsterType)`

## Reproduction

Using `DynamicOutput` should reproduce the problem.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by fahadkh** [comment]
I'm seeing a [similar issue as well](https://dagster.slack.com/archives/C01U954MEER/p1654658027690449?thread_ts=1654547814.036109&cid=C01U954MEER) - adding a code sample that I used to reproduce the issue.

Note that this only happens on Dagster 0.14.19, but not 0.14.17:

```python
@op(
    out=DynamicOut(str),
)
def generate_names():
    for num in range(100):
        yield DynamicOutput(str(num), f"name_{num}")


@op
def name_to_path(_: OpExecutionContext, name: str) -> Path:
    return Path("/tmp", name)


@op
def concat_paths(_: OpExecutionContext, paths: list[Path]) -> str:
    names = [str(path) for path in paths]
    return "".join(names)


@graph
def path_graph():
    names = generate_names()
    paths = names.map(name_to_path)
    return concat_paths(paths.collect())

jobs = path_graph.to_job(resource_defs=resources)
```

**Comment by Proteusiq** [comment]
I got similar issue with `-> list[DataFrame]` on v0.14.19 but not in v0.14.17`
