### ISSUE TITLE
DockerRunLauncher tasks stuck in "starting" when container crashes

### ISSUE THREAD

**Issue by PascalStehling** [dagster-io/dagster#8312]
## Summary

When using an DockerRunLauncher and the Container, in which the tasks should run, Crashs immediately when starting up, the Dagit UI will stay in Starting and it needs to be manually terminated. Ideally the DockerRunLauncher should check if the container is running and if not, mark the run as failed and also add the Container Logs in the Event screen in the bottom, to see why the container crashed.

## Reproduction

To reproduce, just take the ["deploy_docker"](https://github.com/dagster-io/dagster/tree/master/examples/deploy_docker) example from dagster and remove the "DAGSTER_POSTGRES_PASSWORD" in the run_launcher env_vars in the dagster.yaml. Then start the the docker-compose file with `docker compose up --build`.

When now launching the "my_job" it will start the container in which the tasks should run, but the container will immediately crash, as the "DAGSTER_POSTGRES_PASSWORD" Environment Variable is missing. But the Job will stay in starting forever, as it did not recognize it.

## Dagit UI/UX Issue Screenshots

![image](https://user-images.githubusercontent.com/33455644/173003898-169c3e95-fde4-43a8-8d55-18083f840f4b.png)

## Additional Info about Your Environment

Dagster Version: 0.14.17

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
This is solved by enabling [Run Monitoring](https://docs.dagster.io/deployment/run-monitoring#run-monitoring).
