### ISSUE TITLE
Long config error descriptions are truncated in dagit UI

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#832]
<img width="795" alt="screen shot 2019-02-13 at 3 09 08 pm" src="https://user-images.githubusercontent.com/427016/52750549-8eef9800-2fba-11e9-97cd-7195d0c25485.png">

**Comment by bengotow** [comment]
Man that's a bummer. Right now this is using the default browser alert dialog and we'll need to roll our own to get a scrollbar in there. I'll take a look - although I wonder if we could also shorten this somehow?
