### ISSUE TITLE
In dagit, should users be able to expand long log messages inline?

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#835]
Right now, you have to copy the message into another buffer.

<img width="630" alt="screen shot 2019-02-13 at 3 22 42 pm" src="https://user-images.githubusercontent.com/427016/52751149-72ecf600-2fbc-11e9-98dc-cc65b0f1be2a.png">

**Comment by bengotow** [comment]
Yep for sure. Can't remember why I implemented this in this way, but at the very least we can pop them out in to a big text block.

**Comment by bengotow** [comment]
This is fixed now by #906.
