### ISSUE TITLE
Dagit should warn users on type mismatches between solids

### ISSUE THREAD

**Issue by Aylr** [dagster-io/dagster#836]
Yes, runtime errors are good, but the more I use dagit, the more I think of it as compile-like step. I had assumed that types were checked, and I have apparently never run into this yet.

<img width="505" alt="screen shot 2019-02-14 at 9 59 04 am" src="https://user-images.githubusercontent.com/928247/52803418-429a6b80-303f-11e9-9075-3b801f6d7c2d.png">

## STR

1. Make a solid with a typed input (not Any)
2. Make a solid with a different typed output
3. Wire together with a mismatch
4. Observe dagit.

**Comment by schrockn** [comment]
👍🏻 great idea

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by schrockn** [comment]
I think what we do is have a strict mode that enforced strict type matches that you opt into

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by Aylr** [comment]
I like the idea of a strict mode!

**Comment by mgasner** [comment]
+1 for this

**Comment by mgasner** [comment]
Closing this in favor of #1840
