### ISSUE TITLE
`No module named 'docs_snippets'`

### ISSUE THREAD

**Issue by LucasMassucci** [dagster-io/dagster#8366]
## Summary

load_python_module
    raise DagsterImportError(
dagster.core.errors.DagsterImportError: Encountered ImportError: `No module named 'docs_snippets'` while importing module docs_snippets.docs_snippets.intro_tutorial.airflow

## Reproduction

dagster-airflow scaffold \
     --module-name docs_snippets.docs_snippets.intro_tutorial.airflow \
     --pipeline-name hello_cereal_pipeline \
     --output-path  ...

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Hi @LucasMassucci. I think that you can fix this issue by installing the docs snippets package via `pip install -e docs_snippets`.
