### ISSUE TITLE
[testing] - Testing docs automation [CON-321]

### ISSUE THREAD

**Issue by erinkcochran87** [dagster-io/dagster#8394]
## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
@erinkcochran87 mind adding some detail here?

**Comment by erinkcochran87** [comment]
@sryza Just testing something out for tracking - I'll close this when I'm finished.

**Comment by sryza** [comment]
Ah oops great
