### ISSUE TITLE
Airflow vs Dagster - What the diffrence ?

### ISSUE THREAD

**Issue by alefbt** [dagster-io/dagster#840]
Hi, 

What the motivation of this tool? what the difference between using pipelines in Airflow ?

**Comment by schrockn** [comment]
Hey thanks for asking! We're still in the midst of building this and working towards a public(-ish) release so we don't have a full motivations and design section yet. We'll be expanding more on its purpose and its relationship (it's complementary) to Airflow soon. Thanks for your interest!
