### ISSUE TITLE
can't re-execute from failure when downstream of the failure is dynamic

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#8411]
## Summary
When a failed step which is dynamic and has dynamically generated downstream steps,  "re-execute from failure" will error as:
<img width="1707" alt="image" src="https://user-images.githubusercontent.com/4531914/173891919-d3044c0c-d8ca-4a08-8ec8-5407384f68bb.png">

I believe this is because the downstream is unresolved in the step selection, so the backend thinks users are trying to execute an unresolved op without providing its upstream, which isn't the case here.

A fix could be to either
- When re-execute from failure or resolving the step selection, we pass the resolved steps, because selecting this works:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/4531914/173893692-abcbf050-bacf-4b0b-af96-46f166c0a510.png">
- When checking unresolved vs resolved, we look up its parent state, if the upstream is present in the current run, we let it pass.

## Reproduction
```python
from dagster import op, job, DynamicOut, DynamicOutput


@op(config_schema=list, out=DynamicOut(int))
def generate_subtasks(context):
    for num in context.op_config:
        yield DynamicOutput(num, mapping_key=str(num))


@op
def subtask(input_number: int):
    print(f"Found {input_number} cereals")
    raise Exception
    return input_number


@op
def echo(input_number: int):
    print(input_number)


@job
def real_dynamic_job():
    generate_subtasks().map(lambda i: echo(subtask(i)))
```
This failed because `echo[?]` which is a downstream of the failed step is unresolved:
https://user-images.githubusercontent.com/4531914/173892468-0baa17b0-2052-4020-84e7-4dea4c5dd81e.mov

However, if the failed step `subtack[?]` doesn't have a downstream, re-execute from failure would work:
https://user-images.githubusercontent.com/4531914/173892707-3b0a895a-f6d0-4406-883e-f205e4622ef4.mov

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment]
A workaround is to select `generate_subtasks` and click `re-execute from selected steps`.
or specify `generate_subtasks*` in the step subset as: 
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/4531914/173894721-bf84a423-3ea7-4c18-b931-05fc6169c0b0.png">

**Comment by yuhan** [comment]
related: https://github.com/dagster-io/dagster/issues/6044

**Comment by cbini** [comment]
@yuhan would I be able to plug in on resolving this? It's become a big headache for dynamic jobs deployed on k8s. I see you identified a couple potential fixes above. 

I think I traced where the parent job lookup needs to happen to here: https://github.com/dagster-io/dagster/blob/b99e488efe66edd3b927f7fa5fc33d00436c1e1a/python_modules/dagster/dagster/_core/execution/plan/plan.py#L795
