### ISSUE TITLE
Dagster errors do not appear in dagit UI

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#843]
Steps to reproduce:
1. Check out 3815ce2e4eadf2d2cd922e5e0fd8799a3c5736d8
2. Start dagit from the root of the airline demo
3. Navigate to http://127.0.0.1:3000/airline_demo_warehouse_pipeline/execute
4. Console and dagit logs will both display `dagster.core.errors.DagsterInvalidDefinitionError: Solid delays_by_geo in dependency dictionary not found in solid list`, but nothing will appear in the UI

**Comment by mgasner** [comment]
Possible dupe of #815 (?) -- @schrockn can you elaborate on #815/is it resolved?

**Comment by schrockn** [comment]
not a dupe. those were errors by users, not our own errors

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
