### ISSUE TITLE
Typo in dagster-postgres schedule storage documentation

### ISSUE THREAD

**Issue by eavonius** [dagster-io/dagster#8430]
## What content is missing

On [the page for setting up dagster postgres](https://docs.dagster.io/_apidocs/libraries/dagster-postgres), the example schedule storage config at the bottom of the page lists:

```yaml
schedule_storage:
  module: dagster_postgres.event_log
```

This should be

```yaml
schedule_storage:
  module: dagster_postgres.schedule_storage
```

## Type of the content
Integration Guide: "How to use postgresql in Dagster"

**Comment by clairelin135** [comment]
Thanks @eavonius for raising this typo. We'll address this shortly
