### ISSUE TITLE
[docs] - sugariest_cereal should be renamed to nabisco_cereals

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#8472]
Reference to sugariest_cereal should be changed to nabisco_cereals at this [page](https://docs.dagster.io/tutorial/assets/asset-graph#lets-get-serial).

**Comment by clairelin135** [comment]
Thanks @pybokeh for raising this typo! We will fix this soon

**Comment by erinkcochran87** [comment]
Thanks @pybokeh! I had a PR already open (https://github.com/dagster-io/dagster/pull/8494) that addressed some other issues with this page, so I've added it to that.

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/8494.
