### ISSUE TITLE
Make it possible to specify config when materializing assets with optional config

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8524]
And when resources that the assets depend on have optional config

https://dagster.slack.com/archives/C01U954MEER/p1655801664267859

**Comment by sryza** [comment]
@smackesey @braunjj - thoughts on what would be required for this? We had talked about possibly having some sort of dropdown that allows you to force the config modal when materializing an asset?

**Comment by braunjj** [comment]
Should the materialize button just always open up the config dialog? It might be annoying in cases when no config is needed but it would make the experience more consistent across all cases

**Comment by sryza** [comment]
@braunjj IMO that makes life significantly more annoying in the majority of cases, so would lean away from it. I suspect that config will only be used in like 1/3 materializations.
