### ISSUE TITLE
Inconsistencies when dagit follows long-running job logs

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#854]
I don't have reliable steps to reproduce a *particular* problem, but executing the airline demo ingest pipeline on the full dataset pretty reliably produces *some* problem, where for instance the logs displayed in dagit will stop streaming and the pipeline will appear to be hanging on some intermediate step, while the logs in the terminal continue to stream and the pipeline continues to execute.
<img width="630" alt="screen shot 2019-02-20 at 1 50 29 pm" src="https://user-images.githubusercontent.com/427016/53127490-6ebe5c80-3517-11e9-9228-b46b8ab5fb42.png">

**Comment by mgasner** [comment]
Reloading the dagit UI seems to resolve the issue

**Comment by bengotow** [comment]
We were able to fix this yesterday - it turned out that our implementation of a debouncing log queue on the python side was locking, essentially freezing the client out of the log stream. Fixed in 94e37458f0502a1453fb6b8f3b2c4b70efde6956
