### ISSUE TITLE
dagster_dbt requires a default target that cannot be changed in software defined assets

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#8558]
## Summary

When using `load_assets_from_dbt_project` dagster_dbt runs a CLI command that ignores the resource settings for the target, essentially not specifying the `--target` CLI flag (note: the target dir is working, I'm talking about the target in the [dbt_profile](https://docs.getdbt.com/dbt-cli/configure-your-profile)). 

This makes loading assets fail if a "default" target is not specified in the project.

Also resource-level configuration using `with_resources` is ignored, both if specified by overriding the resource with a "configured" one, and if you try to specify it in the resource config using `resource_config_by_key` that doesn't get passed either.

I think the core of the problem is that this function here is not using the dbt resource but running a custom cli command (I guess because this is running at repository load time):
https://github.com/dagster-io/dagster/blob/71b6d4fe5d74e8c6584cc898a410a287c58dd109/python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py#L33-L55

I think a simple solution would be to add a "target" parameter to the function but not sure if it's the best one.

## Reproduction

Try not having a `default` resource in the profiles.yaml file in dbt and load the dbt project using `load_assets_from_dbt_project`

## Additional Info about Your Environment

dagster 0.15.0

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @amarrella . We'll see if we can get this fixed for next week's release.

**Comment by OwenKephart** [comment]
Hi @amarrella, looked into this a bit, and I think the heart of the issue (the fact that you need to specify some configuration options on the load_assets_from... method, and others on the dbt_cli_resource) is definitely something we want to improve upon, although that's a bit of a larger effort.

For your usecase, is there a downside to specifying a default profile in your dbt project? this would essentially just be a line underneath your project name in profiles.yaml:

```
my_dbt_project:
    target: prod
    prod:
        ... lots of config
    dev:
        ... lots of config
``` 

Just from browsing the dbt docs, I actually thought that this was something that was required to set, but it seems like that's not the case.

If that's a breaking change, it would also be possible to switch from using load_assets_from_dbt_project to load_assets_from_dbt_manifest (as you could just compile a manifest with whichever target you want). If this also doesn't work, happy to chat more on other potential workarounds.

The basic idea here is that, in theory, the assets that are loaded should be independent of the target to some extent, so it should be possible to load assets from your project that can be run with `--target dev` or `--target prod`, without having to load different assets for each.

**Comment by amarrella** [comment]
Hey @OwenKephart, thanks for looking into this!

Using a default target is not a problem for our use case and that's probably what we will do. 

What you said makes complete sense and in fact assets are identical across targets.

Thanks,
Alessandro

**Comment by j-hulbert** [comment]
For our project the target changes between local/test/prod and would not always match the default. While the targets would have the same assets, the profiles use different credentials and local developers would not have the credentials used for the prod profile.
Would the dagster team accept a PR to have load_assets_from_dbt_project use the target from the dbt resource (if provided)? or alternatively allow an optional target parameter?

**Comment by sryza** [comment]
Thoughts @rexledesma ?

**Comment by j-hulbert** [comment]
One interesting thing that I learned while working around this is that "dbt ls" doesn't connect to the database so theoretically you could set the environment variable used by that profile target to anything to workaround this a bit.
from dbt docs https://docs.getdbt.com/reference/commands/list:

> While dbt ls will read your connection profile to resolve target-specific logic, this command will not connect to your database or run any queries.

We have target specific logic to determine schemas but don't think that info gets used by dagster

**Comment by Bonnevie** [comment]
@sryza is this still in the pipeline? 
I was using `runtime_metadata_fn` to store database and schema of my models, but was surprised to see my development schemas show up in production, as I follow the standard and use different schemas for each! If I'm reading the code correctly, this is due to the manifest.json being generated by the above command which uses the default "dev" profile I set up for development rather than the provided target profile "prod", and this "dev"-manifest is used to provide all the `node_info` dictionaries.

**Comment by sryza** [comment]
Glad you got this working. @OwenKephart is the expert here, so best to direct any further questions towards him.

**Comment by rexledesma** [comment]
With `DbtCli`, a default global target can be specified using Dagster configuration. If you'd like to have a dynamic target, you can provide `--target` when `DbtCli.cli` is invoked.

See https://github.com/dagster-io/dagster/discussions/14477#discussioncomment-6092054 for a relevant discussion.
