### ISSUE TITLE
No way to specify an executor for an asset

### ISSUE THREAD

**Issue by Nintorac** [dagster-io/dagster#8573]
## Summary

There doesn't seem to be any way to define an executor for an asset that I can find. 

It's possible to pass an `executor_def` to `@jobs` and `graph.to_job` but not `define_asset_job`

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Hey @Nintorac - the current recommended way to do this is to supply a `default_executor_def` on your repository definition, and it will apply to all the assets. E.g.:

```
@repository(default_executor_def=multiprocess_executor)
def repo():
    return [asset1, asset2]
```

Does this work for you, or do you intend to have different executors on different asset jobs?

**Comment by Nintorac** [comment]
yup that works for me... I also found `from dagster.core.definitions.asset_layer import build_asset_selection_job` before I saw your super speedy response. Thanks :D
