### ISSUE TITLE
dagster_databricks 0.15.0- deprecated prior_attempts_count field is still referenced

### ISSUE THREAD

**Issue by Phazure** [dagster-io/dagster#8583]
## Summary

I am attempting to run an op which leverages the databricks pyspark step launcher. After migrating from dagster* 0.14.5 -> 0.15.0 however, I now receive the following error:
```
AttributeError: 'StepRunRef' object has no attribute 'prior_attempts_count'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
    145 
    146 if __name__ == "__main__":
--> 147     main(sys.argv[1], sys.argv[2], sys.argv[3])

/tmp/tmpaj5b8gso.py in main(step_run_ref_filepath, setup_filepath, dagster_job_zip)
     95         events_filepath = os.path.join(
     96             step_run_dir,
---> 97             f"{step_run_ref.prior_attempts_count}_{PICKLED_EVENTS_FILE_NAME}",
     98         )
     99         stdout_filepath = os.path.join(step_run_dir, "stdout")

AttributeError: 'StepRunRef' object has no attribute 'prior_attempts_count'
```

Per https://github.com/dagster-io/dagster/blob/e7d5c2c47093cb24c0c1c4f564ae93fbf46fb578/MIGRATION.md, my understanding is that `prior_attempts_count` should be deprecated (the field is no longer part of StepRunRef - https://github.com/dagster-io/dagster/blob/cca45616bbc99372a21a0f1394f90fdb49a9fa06/python_modules/dagster/dagster/core/definitions/step_launcher.py#L14), but it is still referenced in the dagster_databricks codebase: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-databricks/dagster_databricks/databricks_step_main.py#L97.  Is this expected?

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @Phazure . We're actually already tracking this here: https://github.com/dagster-io/dagster/issues/8576. We're aiming to have this fixed in next week's release.
