### ISSUE TITLE
Cannot provide 'resource_defs' with 'define_asset_job'

### ISSUE THREAD

**Issue by zareami10** [dagster-io/dagster#8612]
## Summary

Add the title mentions, 'define_asset_job' doesn't provide any way to define 'resource_defs' for the job that will be created. This is needed if you for example want to provide resources to the OPs of a graph based asset.

I would also appreciate any workaround in the meantime.

**Comment by sryza** [comment]
hey @zareami10 - the intended way to supply resources in this case is to put them on the assets themselves, instead of the jobs.  e.g.
```
@repository
def repo():
    return [with_resources(assets, resource_defs=MY_RESOURCES), define_asset_job("fdshjk")]
```

would this work for you?

**Comment by zareami10** [comment]
> hey @zareami10 - the intended way to supply resources in this case is to put them on the assets themselves, instead of the jobs. e.g.
> 
> ```
> @repository
> def repo():
>     return [with_resources(assets, resource_defs=MY_RESOURCES), define_asset_job("fdshjk")]
> ```
> 
> would this work for you?

Thank you for your quick response, this works as expected!
