### ISSUE TITLE
Backfill history not populating

### ISSUE THREAD

**Issue by adam-bloom** [dagster-io/dagster#8619]
## Summary
Backfills are shown under the status screen, some as completed. If you click the link on a completed backfill, you are brought to the screen for partitions for the job. This page has a "Backfill History", that shows "No backfills for <job>". I'd expect to see the backfills launched from this job displayed there.

## Reproduction
Create a partitioned job and launch a small backfill.

## Additional Info about Your Environment
Using dagster-postgres and an external postgresql database.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
@prha - ideas about what's going on here?

**Comment by prha** [comment]
What version are you running?  I think this was a bug in `0.15.0` that was fixed in `0.15.1`...

**Comment by adam-bloom** [comment]
Ah, I see the changelog now. I must have missed the original issue/PR for that while searching. We're on `0.15.0`. Let me upgrade to `0.15.2` and confirm that this is resolved.
