### ISSUE TITLE
node_info_to_asset_key arg for dbt sources

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8627]

**Comment by sryza** [comment]
@OwenKephart thoughts on what this should look like?

**Comment by OwenKephart** [comment]
node_info_to_asset_key assigns keys to sources as well as models, although that's potentially not an ideal name (as I don't think dbt technically calls sources "nodes").

**Comment by sryza** [comment]
Ah ok - mind documenting this if this is the direction we want to stick with?

**Comment by sryza** [comment]
Looks like this is now reflected in docs. Closing.
