### ISSUE TITLE
Memoization for assets

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#8632]
Memoization is currently not implemented for assets. The main questions for implementation are:
- how does version strategy get set?
- how do you deal with changes to external resources?

Requests:
- https://dagster.slack.com/archives/C01U954MEER/p1657793659979589

**Comment by sryza** [comment]
> how does version strategy get set?

Curious if you have thoughts on this one.

> how do you deal with changes to external resources?

Mind elaborating on this one?

**Comment by dpeng817** [comment]
> how does version strategy get set?

version strategy could be set on the job or the repo.

> how do you deal with changes to external resources?

this isn't a problem unique to assets, but I think assets make it more acute. Right now, if I'm using memoization with SourceHashVersionStrategy, and I don't change my source code or config, then it will never re-run. But let's say that my job is pulling down from some external data source; I would always want to re-run if there is new data. I need some way to tell the memoization machinery that the current "versions" of computations have been rendered moot, and we don't currently have a great way to do that without manually encoding it into a version strategy.

**Comment by sryza** [comment]
> version strategy could be set on the job or the repo.

Setting it on the repo makes sense to me. Setting it on the job would mean that different assets could have different versions in different jobs, which seems dangerous.

**Comment by sryza** [comment]
> But let's say that my job is pulling down from some external data source; I would always want to re-run if there is new data. I need some way to tell the memoization machinery that the current "versions" of computations have been rendered moot, and we don't currently have a great way to do that without manually encoding it into a version strategy.

Ah, so, if I understand correctly, we're talking about external data sources / assets that our versioned assets might depend on? One way to handle that could be to model those external data sources / assets with SourceAssets and allow source assets to have some function that determines their version, potentially by reaching out to some external service.

**Comment by sryza** [comment]
Something to think about for the implementation here: what happens when an asset depends on upstream assets that are defined inside a different job? The workhorse function of memoization, `resolve_step_output_versions`, currently only operates within a job.

**Comment by sryza** [comment]
Those who upvoted this issue – e.g. @zareami10 @nvinhphuc @frsann @programermus @alessandrofacchin – we're doing some research on improving memoization and would love to hear from you.

If you'd be open to a conversation, DM me on Slack (@ sandy) or email me at my first name @elementl.com. Or if you don't have time for an in-depth chat but have briefer thoughts, anything you write down on this issue is helpful as well.

cc @smackesey
