### ISSUE TITLE
Yield AssetMaterializations/AssetObservations from schedule/sensor evaluations

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#8672]
In prod use cases where you just want to observe a particular event occurred without going through the set up of launching a job.

Would be non-trivial to implement because structured events are tied to a run.

**Comment by samuelstuetz** [comment]
As the use case is primarily linked to mapping of outside events to the internal structured events a potentially cleaner solution would be to allow, an External Event Subscriber/Publisher to integrate with choreography tools.

e.g. 
```python
@external_subscriber # executes like a run (in process) but with a state and yields Events or RunRequests
def get_pubsub_exents(context):
    pubsub = context.resources.pubsub
    cursor = context.state.subcription_id
    for external_event in pubsub.read(subscrption_id):
        yield map( external_event_mapper, AssetMaterialization(...., .... )) # under a run of type external with state as the config, really the run could even execute it is mostly for speed that it should be in process.
        # or yield RunRequest(....,...)
    return { subscription_id : subscription_id } # just return the state where this is needed, for pub/sub the state is anyway externally managed but the subscription_id is always needed, maybe on first run the sensor would have to create its subscription.
```
And similarly there should be a @external_publisher which is nothing more than a mapper from internal events to external publishing system. Ideally without the overhead of starting a pod every 30s or have one running continously.

If I am not mistaken all of this could be achieved with a standard sensor and an inprocess runs for the event magic.

**Comment by sryza** [comment]
This will be possible in this week's release, with the new `asset_events` property on `SensorResult`.
