### ISSUE TITLE
Incorrect resources being used when clicking materialise selected in a job

### ISSUE THREAD

**Issue by Nintorac** [dagster-io/dagster#8700]
### Dagster version

0.15.2

### What's the issue?

When multiple repositories are loaded using the same set of assets and different resources it is not determined which resources will be used when materialising specific assets in a specific repo.

### What did you expect to happen?

I expected the resources defined for the specific repository in which the job resides to be used.

### How to reproduce?

```
from dagster import AssetSelection, asset, define_asset_job, repository, with_resources, resource

@resource
def test_dev(context):
    raise Exception('dev')

@resource
def test_prod(context):
    raise Exception('prod')

@asset(
    required_resource_keys={'test'}
)
def the_asset():
    pass

all_assets = {"asset1": the_asset}


@repository()
def dev():
    resource_defs = {
        'test': test_dev
    }
    resourced_assets = with_resources(
            all_assets.values(), 
            resource_defs
        )

    return [
        define_asset_job("build_and_train", AssetSelection.assets(*resourced_assets))
    ] + list(resourced_assets)


@repository()
def production():
    resource_defs = {
        'test': test_prod
    }
    resourced_assets = with_resources(
            all_assets.values(), 
            resource_defs
        )

    return [
        define_asset_job("build_and_train", AssetSelection.assets(*resourced_assets))
    ] + list(resourced_assets)
```

With these repos loaded navigate to the job overview tab, click on the asset and then materialize selected.

It is expected that the exception raised has text of the same name as the repository, instead it could be either.

### Deployment type

Dagster Helm chart

### Deployment details

n/a

### Additional information

https://dagster.slack.com/archives/C01U954MEER/p1656631444998219?thread_ts=1656571918.851609&cid=C01U954MEER

some discussion in this thread

### Message from the maintainers

This form field should be ignored.

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
I think this isn't an issue with incorrect resources, but rather an issue with the job being pointed to when using the materialize button. Seems to not be respecting which repo is being called from.

**Comment by sryza** [comment]
Hey @Nintorac - we generally advise against loading multiple repositories into the same Dagit, if those repositories have definitions for the same assets. That's because, in this case any many others, it can be confusing which version you're dealing with.

Is there a particular reason that you want both loaded at the same time?

**Comment by sryza** [comment]
I'm going to close this issue in favor of a new one that errors when multiple repositories have definitions for the same asset: https://github.com/dagster-io/dagster/issues/8748.

Please let me know if this doesn't work for you.
