### ISSUE TITLE
Cross-repo asset dependencies surface SourceAssets, confuse Dagit

### ISSUE THREAD

**Issue by bengotow** [dagster-io/dagster#8705]
### Dagster version

015.3

### What's the issue?

hey gang! I’m seeing some undesirable behavior in our root workspace where there are cross-repo asset graphs and I’d be interested thoughts about a potential fix. The problem is that calls to asset_node.dependencies { } in graphQL still return the source asset (in the repo) and not the real asset (in a different repo)

https://www.loom.com/share/004a470fad734fe79e73ced950eeb11a

This breaks some GraphQL assumptions because the real asset node and the source asset node both have the same “id” field value and overwrite each other in the Apollo cache (but one has op_names, job_names, etc and the other doesn’t.)

### What did you expect to happen?

I think we could:

- Change the dependencies / dependedBy resolvers to fully resolve source asset nodes (so source asset nodes would not reach Dagit unless the defining repository was not loaded)
- Change the asset_node.id so that it includes the repo + repo location, avoiding cache collisions between two copies of the same asset node

### How to reproduce?

This is reproducible in our root workspace, see attached video!

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Thanks for sharing this @bengotow! I think that I'd prefer to change the python implementation to fully resolve source asset nodes rather than changing asset_node.id because `GrapheneAsset`s also contain an ID but may not be defined in a repo. To keep things consistent between `GrapheneAssetNode` and `GrapheneAsset` it's probably easiest to fully resolve the asset.

I'll put out a diff to fix this!

**Comment by clairelin135** [comment]
Actually, on second thought, fully resolving source assets would force unnecessarily loading all repository locations on cloud upon page load. It's probably best to avoid this--I'll put out a diff to modify the IDs instead.
