### ISSUE TITLE
enable backfilling multiple asset partitions within a single step (coalesced backfills)

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8706]
Here's a How-to guide to how to do this using Dagster's current somewhat-limited functionality: https://github.com/dagster-io/dagster/discussions/11653.

---
Requests:
* https://dagster.slack.com/archives/C01U954MEER/p1656662232023999?thread_ts=1656596814.202879&cid=C01U954MEER
* https://dagster.slack.com/archives/C01U954MEER/p1658781926863839
* https://dagster.slack.com/archives/C01U954MEER/p1660634859297209
* https://dagster.slack.com/archives/C01U954MEER/p1667932777213229?thread_ts=1667922601.771249&cid=C01U954MEER

Implementing this requires some way of allowing users to specify how to break up the partitions in a backfill into steps. This could be a function that accepts a list of partition keys and returns a list of PartitionKeyRanges. The default implementation of that function would return a PartitionKeyRange per partition key:
```
def step_partitions(context: LaunchBackfillContext) -> Sequence[PartitionKeyRange]:
    return [PartitionKeyRange(partition_key, partition_key) for partition_key in context.partition_keys]
```

but a custom implementation could return a single PartitionKeyRange:

```
def step_partitions(context: LaunchBackfillContext) -> Sequence[PartitionKeyRange]:
    return [context.partition_key_range]
```

There's the question of where this function gets specified:
* Is it on a `PartitionsDefinition`?
* Is it a separate attribute on each asset?
* Is it on the job?

There's also the question of PartitionKeyRanges vs. partition lists. In the case where you just want to fire off a SQL query that operates over a range, Dagster shouldn't have to do O(# partitions) work or pass around O(# partitions) data, but it might be too restrictive to require that steps always handle continuous sets of partitions.

**Comment by zczhuohuo** [comment]
Any update or any workaround? Currently，It will be very slow when backfills a large set of partitions

**Comment by Nintorac** [comment]
Just throwing in a usecase I've run into.

I have a large archive sitting on the net somewhere that contains many files named by their hash in a subfolders named for the initial char of the hash. eg `e/e990ff1.file` or `f/f556439485.file`. 

A single partition is pushing it for memory and it's not possible to seek a single partition efficiently.

For now my sol'n is to skip the IOManager for this asset, partition within the asset code itself and then on the consuming asset load the correct partition manually. 

It might be cool to be able to specify the partition key of a particular materialization  with something like
```
@asset(partition_def=StaticPartitionDefintion(list('abcdef012345689')))
def multi_partition_archive(context):
    for partition in load_data():
        yield Output(partition.data, partition_key=partition.key)
```

**Comment by mjclarke94** [comment]
On flagging use cases, we might eventually need to run a backfill on a multidimensional partition (TimePartition X categorical with 10k values). If we have hourly assets in there, it's approaching 100M distinct jobs to backfill a years worth of data, which just isn't viable. Being able to chunk that (say, 100 jobs, each spanning the entire time dimension and a subset of the categoricals) would be a lot more practical in our case.

**Comment by sryza** [comment]
From Zach Bluhm:
> So the usual scenario is: we have 2 assets, A and B, both at the hourly grain where B depends on A
> B's underlying SQL is changed which requires a rebuild of all partitions
> A now needs to "reconcile" all of the modified partitions, but preferably this is done in chunks of partitions instead of individual partitions. Reason being is that it takes a very very very long time to run 1000s of partitions with all of the overhead (also assuming that A depends on previous partitions).
> How might this work? Naively each asset has a config that specifies whether or not it can be reconciled in "chunks"... as far as how that might be utilized I can't say, as I'm not familiar with how the asset reconciliation sensor is currently implemented

**Comment by sryza** [comment]
From Philippe Laflamme:
>  Hello! I’m completely new to dagster and have mostly only read documentation. So I’m sorry if this is mentioned anywhere that I missed. I have a question regarding backfilling. Say I have a daily partitioned asset defined that requests the data using a http request and produces a file to disk, say using parquet. I’d like to backfill this for a whole year. From my understanding, that would make one HTTP request per partition. But the API I’m using supports larger batches, say per month. How would I go about backfilling a daily partitioned asset, for a full year, using monthly requests (12 HTTP calls for 365 files)?

https://dagster.slack.com/archives/C01U954MEER/p1673466648059209

**Comment by sryza** [comment]
Closing this, because it's now supported in a first-class way in Dagit. Instructions here: https://github.com/dagster-io/dagster/discussions/11653.
