### ISSUE TITLE
Run tag "dagster/retry_strategy:" is not being used 

### ISSUE THREAD

**Issue by george-chamoun** [dagster-io/dagster#8710]
### Dagster version

0.15.2

### What's the issue?

Using the auto run re-execution feature we set tags in the job configuration. For example:

```
@job(
    tags={
        "dagster/max_retries": 2,
        "dagster/retry_strategy": "ALL_STEPS"
    }
)
```

The max retries tag is considered.  https://github.com/dagster-io/dagster/blob/0d6530413349a7d85efa977afbeda696e7b9e3f7/python_modules/dagster/dagster/daemon/auto_run_reexecution/auto_run_reexecution.py#L25

The retry strategy tag is not:  https://github.com/dagster-io/dagster/blob/0d6530413349a7d85efa977afbeda696e7b9e3f7/python_modules/dagster/dagster/daemon/auto_run_reexecution/auto_run_reexecution.py#L109.

As a result... We can specify the number of retries, but the ability to re run all steps is not available. As noted in the documentation, FROM_FAILURE requires an IOManager that can access outputs from other runs. Given that we do not have this, all retry runs fail. 

### What did you expect to happen?

We expected all steps from run root to be re-run. 

### How to reproduce?

Add these tags to a job that you know will fail on step > 1. 

```
@job(
    tags={
        "dagster/max_retries": 2,
        "dagster/retry_strategy": "ALL_STEPS"
    }
)
```

You will see that it does not retry all steps and only starts from where it failed. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
Thanks for the report, fixing
