### ISSUE TITLE
dagit not honoring or reflecting my use of alias() method

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#8722]
### Dagster version

0.15.3

### What's the issue?

I have a job defined like so:
```
@job
def d1_safety_features_job():
    mapping_dict = fetch_mapping()
    template_standard = fetch_standard_generic_equipment_template()
    template_optional = fetch_optional_generic_equipment_template()
    template_merge = fetch_merge_generic_equipment_template()
    sql_standard = generate_query.alias("std_generic_equip_sql")(template_standard, mapping_dict)
    sql_optional = generate_query.alias("opt_generic_equip_sql")(template_optional, mapping_dict)
    sql_merge = generate_query.alias("merge_std_opt_sql")(template_merge, mapping_dict)
    create_d1_snowflake_tables(sql_standard, sql_optional, sql_merge)
```
I am reusing the generate_query op 3 times and so in dagit, it shows them as "generate_query_1", "generate_query_2", and "generate_query_3".  To prevent dagit from using these "_1", "_2", "_3" suffixes, I am using the alias() method.  After doing so, dagit still shows those suffixes.

### What did you expect to happen?

After using alias() method, I expect dagit to use my aliases, but instead, it continues to use the "_1", "_2", and "_3" suffixes.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
I tried to recreate this using the following dummy code:
```python
from dagster import job, op


@op
def fetch_mapping():
    return "foo"


@op
def fetch_standard_generic_equipment_template():
    return "foo"


@op
def fetch_optional_generic_equipment_template():
    return "foo"


@op
def fetch_merge_generic_equipment_template():
    return "bar"


@op
def generate_query(template, mapping):
    return "foo"


@op
def create_d1_snowflake_tables(sql, sql2, sql3):
    pass


@job
def d1_safety_features_job():
    mapping_dict = fetch_mapping()
    template_standard = fetch_standard_generic_equipment_template()
    template_optional = fetch_optional_generic_equipment_template()
    template_merge = fetch_merge_generic_equipment_template()
    sql_standard = generate_query.alias("std_generic_equip_sql")(template_standard, mapping_dict)
    sql_optional = generate_query.alias("opt_generic_equip_sql")(template_optional, mapping_dict)
    sql_merge = generate_query.alias("merge_std_opt_sql")(template_merge, mapping_dict)
    create_d1_snowflake_tables(sql_standard, sql_optional, sql_merge)
```
however, I received the expected aliases in dagit:
![Screen Shot 2022-07-01 at 4 35 46 PM](https://user-images.githubusercontent.com/17576880/176977735-b8b2fa6b-acb6-4c89-8660-145e8b80f457.png)

Is there anything unique about the structure of your ops that the above example is not reflecting?

**Comment by pybokeh** [comment]
Hmmm, after clearing browser cache and restarting, I have not been able to reproduce my problem.
