### ISSUE TITLE
[docs] - Self-documenting run configuration and exposure in Dagit

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#8743]
### What's the issue or suggestion?

A user gave feedback that it should be possible to add descriptions to config schema so that scaffolding missing config is documented: https://dagster.slack.com/archives/C01U5LFUZJS/p1657010390346369.

You can do this in the API, but it is not explicit in the documentation on https://docs.dagster.io/concepts/configuration/config-schema.

We should add a section in the documentation about how to self-document your run configuration, and show how it is exposed in Dagit. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
We now show config schema documentation for our default fields (e.g. `resources`, `execution`, `loggers`, `op`) in run configuration to naturally show off this feature. https://github.com/dagster-io/dagster/pull/8757

**Comment by erinkcochran87** [comment]
Sounds like there are some config improvements planned post GA. Let's wait to tackle this guy after those improvements take a bit more shape.
