### ISSUE TITLE
sklearn not in dependencies anywhere

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#875]
This means in order for tests to pass you must manually install sklearn. This should be added to a test requirements file or something.

**Comment by puma314** [comment]
It's in here: https://github.com/dagster-io/dagster/blob/master/python_modules/dagstermill/setup.py#L49
so it's required when you install dagstermill (maybe that's too much to ask since it's a pretty big package).

**Comment by schrockn** [comment]
whoops!

**Comment by schrockn** [comment]
oh duh! I didn't find it with grep for some reason. 

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
