### ISSUE TITLE
Tutorial - Incorrect `AssetGroup` method named in documentation

### ISSUE THREAD

**Issue by jackapbutler** [dagster-io/dagster#8759]
### What's the issue or suggestion?

On the [testing page](https://docs.dagster.io/0.14.20/tutorial/assets/testing-assets) for the tutorial documentation version 0.14.20 it mentions "invoke AssetGroup.materialize_in_process". 

However, in the code and documentation I believe the correct method is just `AssetGroup.materialize()`.

### Additional information

Thanks for making this! 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by prha** [comment]
Thanks for the report @jackapbutler!  I believe this has been fixed in subsequent releases, so will close out.
