### ISSUE TITLE
[dagster-dbt] Support snapshots and seeds as dagster assets

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#8770]
### What's the use case?

When you use the dbt build command, snapshots and seeds are executed by dagster, and produce persistent artifacts, and so should be represented as software-defined assets. However, we currently only surface models as assets.

### Ideas of implementation

Right now, we filter out any non-model nodes, so we could just... not do that. There will also need to be a bit of extra logic to turn that behavior on or off depending on if the dbt run or dbt build command is being used.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by blackdigitaldotnet** [comment]
Any ETA on the resolution of this issue?

**Comment by blackdigitaldotnet** [comment]
Hi @sryza , @OwenKephart  can you confirm if this fix is part of dagster-1.1.17, dagster-dbt-0.17.17?
When i inspect the assets loaded from my dbt project, i can only see models. I dont see snaphsots and seeds. Or maybe i'm doing something wrong?

**Comment by OwenKephart** [comment]
hi @blackdigitaldotnet! in order for snapshots/seeds to show up, you'll need to set `use_build_command=True` inside of your `load_assets_from...` call

**Comment by blackdigitaldotnet** [comment]
Thanks @OwenKephart , your a life saver. I had been grappling with this issue for about 2 days. Might be worthwhile adding to the documentation for the 'use_build_command' argument and being more explicit about the implications of not setting this to true. 
Also is there a forum to post general Dagster DBT related questions?

**Comment by OwenKephart** [comment]
Our Slack is the most active/easiest place for these questions! (dagster.io/slack)
