### ISSUE TITLE
dbt assets should support runs via dbt Cloud

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#8773]
### What's the use case?

Right now, you can only use dbt + SDAs if you are using the dbt_cli_resource to execute them, but in some cases you would prefer to run dbt via dbt Cloud rather than the CLI.

### Ideas of implementation

There are a few different ways to go on this one. The simplest option would be to just require users to manually download a relevant manifest.json file from dbt Cloud, and then use `load_assets_from_dbt_manifest`. Then, we could update the dbt_cloud_resource to support the necessary methods to work with the existing dbt operation.

I think this approach might be a bit annoying in practice, so a better solution would likely be to create a new `load_assets_from_dbt_cloud_manifest` function, which would allow some more flexibility for these functions to differ. This would still require the user to have a local copy of the dbt cloud manifest available.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Corresponding guide: https://docs.dagster.io/master/integrations/dbt-cloud
