### ISSUE TITLE
[Doc] Image link broken

### ISSUE THREAD

**Issue by sayantikabanik** [dagster-io/dagster#8782]
### Dagster version

 0.15.4

### What's the issue?

The image link seems to be broken for the document section:  [A more Complex Asser Graph](https://docs.dagster.io/tutorial/assets/asset-graph#a-more-complex-asset-graph)

Documentation version - `0.15.4`

<img width="708" alt="Broken image link" src="https://user-images.githubusercontent.com/17350312/177696989-277c66f8-cbc0-4f3c-a8a3-7e82ef7414d4.png">

**Comment by prha** [comment]
Thanks for the report!  We'll push out a fix today: https://github.com/dagster-io/dagster/pull/8702/
