### ISSUE TITLE
after clicking Materialize button, config modal shows up even when there's no required config

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8810]
And the partition selector does not show up

To reproduce:
* go here: https://demo.elementl.show/workspace/hacker_news_assets_prod@hacker-news-assets/asset-groups/core
* click "Materialize All"

Perhaps relevant: these assets are partitioned

**Comment by sryza** [comment]
@bengotow @smackesey

**Comment by geoHeil** [comment]
great - seems that I have the same issue.
But the missing partition selector is missing config which should show up
