### ISSUE TITLE
Add metadata to AssetsDefinition.from_graph

### ISSUE THREAD

**Issue by zareami10** [dagster-io/dagster#8819]
### Dagster version

15.3

### What's the issue?

Unless I'm missing something, there currently doesn't seem to be an easy way to set meatada for graph-backed assets (with different input/outputs).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
hi @zzztimbo ! Currently, the metadata shown for each asset is sourced from the underlying OutputDefinition associated with that asset. This doesn't quite qualify as an "easy way" to set metadata, but if you add metadata to the relevant outputs of the op that produces the asset, then this will be reflected in Dagit, i.e.

```python
@asset(
    out=Out(metadata={"something": 1, "foo": "bar"})
)
def my_asset_producing_op(foo):
    # ...

@graph
def my_gba():
    return my_asset_producing_op(some_op())
```

In an ideal world, are you imagining setting the metadata when doing the `AssetsDefinition.from_graph()` call? Something like:

```python
my_assets = AssetsDefinition.from_graph(
    my_gba,
    metadata_by_key={
        AssetKey("foo"): {"metadata": 1, "other_metadata": "bar"}
    }
)
```

**Comment by zareami10** [comment]
> hi @zzztimbo ! Currently, the metadata shown for each asset is sourced from the underlying OutputDefinition associated with that asset. This doesn't quite qualify as an "easy way" to set metadata, but if you add metadata to the relevant outputs of the op that produces the asset, then this will be reflected in Dagit, i.e.
> 
> ```python
> @asset(
>     out=Out(metadata={"something": 1, "foo": "bar"})
> )
> def my_asset_producing_op(foo):
>     # ...
> 
> @graph
> def my_gba():
>     return my_asset_producing_op(some_op())
> ```
> 
> In an ideal world, are you imagining setting the metadata when doing the `AssetsDefinition.from_graph()` call? Something like:
> 
> ```python
> my_assets = AssetsDefinition.from_graph(
>     my_gba,
>     metadata_by_key={
>         AssetKey("foo"): {"metadata": 1, "other_metadata": "bar"}
>     }
> )
> ```

Not sure if the mention was mistaken, but anyways.

First of all thanks for your response and pointing out a solution. Although in my workflow, I usually end up making many assets based on the same underlying graph with different inputs and outputs, and would like to assign metadata to individual assets generated by `AssetsDefinition.from_graph()`. But unless I'm mistaken again, that doesn't seem to be possible with the approach you mentioned? (e.g. all assets created by multiple `AssetsDefinition.from_graph()` calls would end up with the same metadata)

**Comment by OwenKephart** [comment]
ah yep autocomplete got me on that mention 🤦.

That totally makes sense, and you're exactly right that this wouldn't allow you to assign different metadata per invocation of `AssetsDefinition.from_graph()`. I'll investigate the metadata_by_key solution as that seems to be more aligned with what you need in this case.
