### ISSUE TITLE
from Launchpad, it's too easy to kick off a non-partitioned run of a partitioned job

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8925]
A partitioned job will usually fail if not launched with a partition.  However, if you go to the Launchpad and launch a run and forget to select a partition, this failure will often not occur until runtime.  We should force you or heavily encourage you to select a partition before launching a run.

It's possible that there are some edge cases, with non-asset jobs, where this is a desirable thing to do - e.g. if you want to manually provide all the config that you'd otherwise provide through the partition, and you don't use `context.partition_key` or similar anywhere. So I'm not sure we should 100% outlaw it in all cases.  In the asset case, we should 100% outlaw it.

**Comment by bengotow** [comment]
It looks like this is still the case and can be repro'd with the `many_events` job, which runs (and succeeds) without a partition specified but maybe shouldn't.

I'll add a warning of some kind that you have to click through to start the job without the partition filled in if a partition set is present.
