### ISSUE TITLE
same type is shown for all outs of same multi-asset in Dagit

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8926]
Here's a multi-asset with a different type on each of its Outs:
```
from dagster import multi_asset, AssetOut
from typing import Tuple


@multi_asset(outs={"a": AssetOut(), "c": AssetOut()})
def multi() -> Tuple[int, str]:
    ...

```

But the type for out "c" is erroneously shown as Int, instead of String in Dagit:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/654855/179580787-954cc7d5-edc0-4fd5-85aa-bf5519df7626.png">

The types on the object seem correct, which implies that the issue be at the web app layer.

```
assert [out.dagster_type.typing_type for out in multi.op.output_defs] == [int, str]
```

Thanks @danielgafni for reporting this.

**Comment by bengotow** [comment]
Hmm, it looks like the `multi.op.output_defs` are correct, but there isn't a formal mapping from the two generated assets to the two outputs? @sryza could you weigh in on this one real quick?

eg: Given asset "C", with "asset.op" = "multi" is there a way to know which of `multi`'s outputs is the one bound to C? Maybe there's a hack where we could load all the assets of multi and all the outputs of multi and know that asset index 1 maps to output index 1?

If the asset's outputs are in-use, I think we can get this off the AssetDependency record, but if it's detatched as shown in the picture we might not have the info attached to the Asset?

**Comment by sryza** [comment]
@clairelin135 - do you know whether there's a way via graphql to find out which op output definitions are associated with each asset of a multi-asset?

**Comment by clairelin135** [comment]
We'd need to get the output name off of the external asset node object and use it to match to the output definition that is yielding the asset. It's probably easiest if I add a resolver that fetches the asset type--will put out a diff
