### ISSUE TITLE
With K8S, Dagit UI is not fully updating after the run finishes (with fail or success)

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#8937]
### Dagster version

0.15.6

### What's the issue?

Here is a screenshot:

![image](https://user-images.githubusercontent.com/49863538/179694600-140d5dae-c639-40a7-883a-8de3eb3c60f7.png)

You can see how the run is marked as "failure" in the very top of the image, but the logs don't have this information yet. In the op view the current op is shown as executed. 

This behavior doesn't change unless I refresh the page.

The same is true for "success" marked runs.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by danielgafni** [comment]
Generally, things don't appear online for me (including structured / non-structured logs). The only thing that updates online is the run status.

**Comment by hellendag** [comment]
@danielgafni So do you never see logs streaming in as the run continues to execute?

**Comment by ChrisJFarr** [comment]
Experiencing same issue, in order to view the logs you have to manually refresh the browser.

**Comment by danielgafni** [comment]
Sorry, I forgot to reply to the question above. Unfortunately, I'm not able to try again, because I don't have my old Dagster K8s setup anymore.

**Comment by hellendag** [comment]
Closing as stale.
