### ISSUE TITLE
Dagstermill notebook error 

### ISSUE THREAD

**Issue by puma314** [dagster-io/dagster#894]
Currently when there is an error when executing a notebook, a dagstermill error is thrown and execution stops--but the output notebook path is never shown (at least in the log messages). But papermill still generates the output notebook (and it would be nice to have the path to the notebook spat out so that the user can debug the error in the notebook).

**Comment by mgasner** [comment]
see #1261

**Comment by mgasner** [comment]
Closing in favor of #1261
