### ISSUE TITLE
[docs] - Missing docs for getting reasonable logs out of the DbtRpcSyncResource

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#8957]
### What's the issue or suggestion?

[Slack convo](https://dagster.slack.com/archives/C01U954MEER/p1658264254265819)

In order for logs in dagit to be displayed nicely when using this resource, you need to specify `DBT_ENABLE_LEGACY_LOGGER=True` and the `--no-use-colors` flag when launching your rpc server. This should be surfaced somewhere (at least in the API docs for the resource).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Our `dbt-rpc` integration will be deprecated in 0.20.0.
