### ISSUE TITLE
Dagit UI is completely broken when accessing certain asset metadata 

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#8959]
### Dagster version

0.15.6

### What's the issue?

When clicking on a certain asset, the Dagit UI turns completely blank. This error appears in the js console:

```
react-dom.production.min.js:216 SyntaxError: Unexpected token N in JSON at position 317
    at JSON.parse (<anonymous>)
    at Object.content (MetadataEntry.tsx:106:36)
...
```

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by danielgafni** [comment]
The error disappeared after this asset was rematerialized (I used an old run to do this). Seems like something was broken for the latest partition metadata.

**Comment by hellendag** [comment]
@danielgafni Is it possible that you have an `NaN` value in the metadata object being parsed here?

Do you have some more details on reproducing the issue? Is this occurring on the Run view only, or elsewhere for this asset as well?

**Comment by danielgafni** [comment]
Hey! I can't reproduce it since it happened a long time ago.

Nan values are possible.

It happened both in the Run view and in the Asset Catalog when selecting the corrupted asset.
