### ISSUE TITLE
Allow IntSource for dagster_ssh remote_port

### ISSUE THREAD

**Issue by cbini** [dagster-io/dagster#8968]
Currently only allows explicit `int` set in the config YAML. The rest of my SFTP configs are provided via envvars, so it would be nice to allow IntSource for consistency

https://github.com/dagster-io/dagster/blob/65caf7986b8d0a168c6943622ba55894c4a81055/python_modules/libraries/dagster-ssh/dagster_ssh/resources.py#L216

**Comment by yuhan** [comment]
Hi @cbini, thanks for opening this issue! This sounds reasonable. We can get the change in during our next bug bash.

In the meantime, we'd definitely welcome a contribution if this is something you'd like to open a PR for.
