### ISSUE TITLE
[K8S] The example k8s-example-user-code template not ready because exceeded readiness probe checking

### ISSUE THREAD

**Issue by leehuwuj** [dagster-io/dagster#9014]
### Dagster version

0.15.6

### What's the issue?

The example template for user deployment: k8s-example-user-code always not ready because exceeded deadline in readiness probe checking.
```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  31s               default-scheduler  Successfully assigned dagster/dagster-dagster-user-deployments-k8s-example-user-code-1-5blhx2 to docker-desktop
  Normal   Pulling    30s               kubelet            Pulling image "docker.io/dagster/user-code-example:0.15.6"
  Normal   Pulled     27s               kubelet            Successfully pulled image "docker.io/dagster/user-code-example:0.15.6" in 3.637367626s
  Normal   Created    26s               kubelet            Created container dagster-user-deployments
  Normal   Started    26s               kubelet            Started container dagster-user-deployments
  Warning  Unhealthy  8s (x2 over 17s)  kubelet            Readiness probe errored: rpc error: code = Unknown desc = deadline exceeded ("DeadlineExceeded"): context deadline exceeded
```

### What did you expect to happen?

I think the readinessProbe default config in deployment-user.yaml is set too strict:
```
readinessProbe:
  exec:
    command: ["dagster", "api", "grpc-health-check", "-p", "3030"]
  periodSeconds:
    20
  timeoutSeconds:
    3
  successThreshold:
    1
  failureThreshold:
    3
```

When i run command manually in the pod, it's always return after 5-8 seconds with my local machine (Macbook Pro M1 Pro) so i think the timeoutSeconds was set too strict (only 3 seconds) which always returns failed.

I think this issue will make new users confuse when try Dagster k8s deployment for the fist time and it would be better if we increase the `timeoutSeconds` to `10` seconds.

### How to reproduce?

I render the k8s template from Helm chart by this command, my values.yaml almost the same with the default one!
```
helm template dagster ./dagster --version 0.15.6 --values ./dagster/values.yaml --output-dir ./rendered
```

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
Sounds reasonable to me, there's not too high a cost of having a higher timeout I think

**Comment by wannesghielens** [comment]
Stumbled upon this issue as we are experiencing the same timeout. It seems odd to me that a health check should even take longer than 3s, or is there a lot of checking going on behind the scenes that makes this a very latent operation? (trying to enlighten myself a bit on the behind the scenes of dagster here instead of just changing the timeout and moving on)

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/9073.
