### ISSUE TITLE
SourceAssets + define_asset_job  result in  not found asset key

### ISSUE THREAD

**Issue by TimoFriedri** [dagster-io/dagster#9017]
### Dagster version

dagster, version 0.15.7

### What's the issue?

The simple SourceAsset example in the docs works fine. BUT a minimal extension with explicit assets jobs breaks it.

### What did you expect to happen?

Even with jobs, It should work as without.

### How to reproduce?

``` python
from dagster import AssetKey, SourceAsset, asset, define_asset_job, repository


@asset
def repository_a_asset():
    return 5


job_a = define_asset_job(
    name="JOBA", selection=[repository_a_asset.key.to_user_string()]
)


@repository
def repository_a():
    return [job_a, repository_a_asset]


repository_a_source_asset = SourceAsset(key=repository_a_asset.key)


@asset
def repository_b_asset(repository_a_asset):
    return repository_a_asset + 6


job_b = define_asset_job(
    name="JOBB",
    selection=[repository_b_asset.key.to_user_string()]
    + [repository_a_source_asset.key.to_user_string()],
)


@repository
def repository_b():
    return [job_b, repository_b_asset, repository_a_source_asset]
```

Error:
`UserWarning: Error loading repository location tmp_dagster.py:dagster.core.errors.DagsterInvalidSubsetError: AssetKey(s) {'repository_a_asset'} were selected, but no AssetDefinition objects supply these keys. Make sure all keys are spelled correctly, and all AssetsDefinitions are correctly added to the repository.`

### Deployment type

Local

### Deployment details

dagit -f tmp_dagster.py

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
I'll try to improve the error messages to make this more clear

**Comment by TimoFriedri** [comment]
@sryza 
I originally intended the latter option. 

Actually, I realized I shouldn't need 2 repos at all, but I was facing the same bug as decribed in #9020 which forced me to try this.

Could you run the above example in "latter option" and see if the cross repo asset links in the job's view in Dagit work for you? I get the message `
Pipeline not found
Could not find Pipeline tmp_dagster.py.repository_a.JOBB`

**Comment by sryza** [comment]
I tried launching this:
```
from dagster import AssetSelection, SourceAsset, asset, define_asset_job, repository


@asset
def repository_a_asset():
    return 5


job_a = define_asset_job(name="JOBA", selection=AssetSelection.assets(repository_a_asset))


@repository
def repository_a():
    return [job_a, repository_a_asset]


repository_a_source_asset = SourceAsset(key=repository_a_asset.key)


@asset
def repository_b_asset(repository_a_asset):
    return repository_a_asset + 6


job_b = define_asset_job(name="JOBB", selection=[repository_b_asset.key.to_user_string()])


@repository
def repository_b():
    return [job_b, repository_b_asset, repository_a_source_asset]
```

 and JOBB appeared to render correctly in Dagit:
![Uploading image.png…]()

**Comment by sryza** [comment]
I'm going to close this for now, but feel free to reopen if there's still an issue

**Comment by TimoFriedri** [comment]
@sryza 
Try to click on the link for repository_a_asset, the cross job Asset Link. There I get an error.

**Comment by sryza** [comment]
@TimoFriedri ah yes- I'm seeing that as well. I filed https://github.com/dagster-io/dagster/issues/9029 to track it.
