### ISSUE TITLE
define_asset_job breaks for asset selection and set config

### ISSUE THREAD

**Issue by daviskirk** [dagster-io/dagster#9020]
### Dagster version

dagster, version 0.15.7

### What's the issue?

As discussed in the slack thread here: https://dagster.slack.com/archives/C01U954MEER/p1658751578283169

I'm trying to figure out how to start jobs that use assets without having to rematerialize all previous assets. My main focus is exactly to run a "piece" of the dag, without re-materializing everything.

I can define a "partial" job (one that just materializes "saved_data" and not of the previous steps like this:

```
save_only = define_asset_job(
    "save_only_job",
    selection=["saved_data"]
)
```

however, as soon as I add any sort of configuration to the job (note the "config" key), like this:

```
save_only = define_asset_job(
    "save_only_job",
    selection=["saved_data"],
    config={}
)
```

Results in (the repository can no longer be created):

```
dagster.core.errors.DagsterInvalidDefinitionError: Input 'files' of op 'save_data_op' has no way of being resolved. Must provide a resolution to this input via another op/graph, or via a direct input value mapped from the top-level graph. To learn more, see the docs for unconnected inputs: https://docs.dagster.io/concepts/io-management/unconnected-inputs#unconnected-inputs.
```

### What did you expect to happen?

To obtain a job definition that assumes that the asset already exists (thus not forcing me to rematerialize it).

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by TimoFriedri** [comment]
I can confirm this bug. Facing the same behaviour also with 0.15.7

**Comment by sryza** [comment]
Thanks for reporting this @TimoFriedri and @daviskirk . @OwenKephart - mind taking a look? This looks possibly related to the `FromSourceAsset` stuff you worked on.
