### ISSUE TITLE
link to cross-repository upstream asset doesn't work

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#9029]
I tried clicking on "repository_a_asset" here and nothing happened:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/654855/180866949-785bf9b9-6b18-4bc1-9361-984946d0d034.png">

I would have expected it to take me to the group with "repository_a_asset". The other direction _does_ work.  I.e. if I'm looking at a group in the upstream repository, I can navigate to the group in the downstream repository by clicking on the asset link.

Here's the code:
```
from dagster import AssetSelection, SourceAsset, asset, define_asset_job, repository


@asset
def repository_a_asset():
    return 5


job_a = define_asset_job(name="JOBA", selection=AssetSelection.assets(repository_a_asset))


@repository
def repository_a():
    return [job_a, repository_a_asset]


repository_a_source_asset = SourceAsset(key=repository_a_asset.key)


@asset
def repository_b_asset(repository_a_asset):
    return repository_a_asset + 6


job_b = define_asset_job(name="JOBB", selection=[repository_b_asset.key.to_user_string()])


@repository
def repository_b():
    return [job_b, repository_b_asset, repository_a_source_asset]
```

If you go to the job page for JOBB and click the upstream link, you get this error:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/654855/180867479-8586d0ca-c26b-49df-a70f-614e6c39edc6.png">

**Comment by bengotow** [comment]
Was able to reproduce this and can confirm it's still busted... will get a PR up for this :-/
