### ISSUE TITLE
Can NOT specify K8sLauncher cpu/gpu resources configuration for different pipelines

### ISSUE THREAD

**Issue by abdulvirta** [dagster-io/dagster#9035]
### Dagster version

0.15.5

### What's the issue?

There is no way to specify different cpu/gpu resources in K8sLauncher for different code deployments repo? I have many repo with pipelines with significant differences in terms of requirements. Some needs cpu only, some needs t4 GPU, some need a-100 GPU and so on... Am I understanding this correctly that the K8sLauncher is configured once in the Dagster installation and will be used by all different pipelines repos?
In which case this seems to be a very weird architecture decision and something that is very limiting. It means if I have one pipeline that requires 4 a-100 GPU machines, that means all other pipelines have to use that much resources.

Please let me know if what is the recommended way in this case?

### What did you expect to happen?

K8s Resources configuration should be really at the pipeline level, or at least the repo level. But not at the dagster cluster level forcing every pipeline running in the cluster to use the same resources 

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @abdulvirta - you can control this at the user code deployment level. As of dagster 0.15.0, setting a resource limit in the helm chart config for a deployment will automatically apply that same resource limit to any runs launched for that deployment. See some examples here: https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm#configure-your-user-deployment

**Comment by abdulvirta** [comment]
Thanks @gibsondan. yeah I was looking at this approach. My problem with this is that this will also mean that the deployment pod (running the grpc) will also use the same resources, correct? So if I want to specify GPU a-100, it means that I will have a pod running a-100 GPU 24/7 just for hosting the user code deployment, which is very expensive. Rather than only used by pods spun up for the duration of running the pipeline.

**Comment by abdulvirta** [comment]
The other approach I'm looking at is tagging individual jobs as documented here: https://docs.dagster.io/deployment/guides/kubernetes/customizing-your-deployment

I think this should work, right? it will only apply the resources for this specific job when it launched

**Comment by gibsondan** [comment]
Yes that should also work!
