### ISSUE TITLE
dagster_databricks - crashes before logging initialisation

### ISSUE THREAD

**Issue by jmccartin** [dagster-io/dagster#9039]
### Dagster version

0.15.5

### What's the issue?

After submitting work to a databricks cluster via the step launcher, dagster polls for logs via the databricks API on a pre-defined resource (the stdout file). If this file is not present on the cluster, then a step failure will occur with a `RESOUCE_DOES_NOT_EXIST` error in the dagit logs. 

The specific error message will be of the form:
```
 { 'error_code': 'RESOURCE_DOES_NOT_EXIST',
  'message': 'No file or directory exists on path '
   '/dagster_staging/<RUN_ID>/<OP_NAME>/stdout.'}
```

### What did you expect to happen?

If there is any error in the project files being deployed, one would expect to see the detailed error message rather than the API complaining that the stdout file is not present.

### How to reproduce?

Reproduction of this error can be done in a number of ways, as it involves a number of fail modes in the `databricks_step_main.py` file before the stdout file is created and events are written to it.

1. First, two pickle files (`step_run_ref.pkl` and `config.pkl`) are is [loaded](https://github.com/dagster-io/dagster/blob/9b0f58cf1adfb83e4e4893ef375aeeb7d02624d0/python_modules/libraries/dagster-databricks/dagster_databricks/databricks_step_main.py#L85), where a failure could occur due to a different Python version (note: I think I saw this behaviour but I have not had time to reproduce).
2. When the dbutils are [configured](https://github.com/dagster-io/dagster/blob/9b0f58cf1adfb83e4e4893ef375aeeb7d02624d0/python_modules/libraries/dagster-databricks/dagster_databricks/databricks_step_main.py#L88), any path issues in the packaged zip file uploaded to DBFS will halt the code here. This can happen when using absolute imports from the repository root in your project files, while supplying the folder one level lower in the `local_pipeline_package_path` variable in `databricks_pyspark_step_launcher`.
3. The dbutils load can also fail when incorrect or inaccessible storage credentials are passed to the `databricks_pyspark_step_launcher`. In my case it was due to the databricks secret scope being unavailable.

All of these failures will halt the code before the stdout file is created, resulting in the missing resource error.

### Deployment details

Tested with local submission to a databricks cluster and from a kubernetes helm chart.

### Additional information

This may also affect other pyspark step launchers, such as EMR (there is nothing inherent to databricks' architecture that would generate this behaviour).

The fix for this might simply be to immediately set up the stdout and stderr files and log all errors when attempting to load the project files in a try/except clause - this helped me debug the problem initially with console access to the databricks cluster. In addition, I think the documentation on the `databricks_pyspark_step_launcher` function needs to be improved, so that it is clear that pointing `local_pipeline_package_path` to anything other than the source root will result in import errors when the spark application is started.

@OwenKephart As discussed in Slack.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi jmccartin! Thanks for digging into this -- I think your suggested fix would work, and this would definitely be valuable, as it can be quite tricky to debug these issues, especially around point number 2 (I've hit that in the past myself). I'll take a look and see if we can get a fix for this in soon.

**Comment by jmccartin** [comment]
Regarding the path issues in point 2, either the documentation could be improved (so that it's clear that all of your imports will need to be relative from the `local_pipeline_package_path`), or perhaps another argument could be added so that only specific folders under that level are included in the zip. 

For example, when I set it to my repository root, everything will be included in that zip, including Dockerfiles and virtual envs - which balloons the size and isn't optimal. If there was another argument for whitelisted folders under that, then I could still have my folder structure and imports as usual. I hope I'm making sense here.
