### ISSUE TITLE
grpcio 1.48.0 causing dead locks

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#9099]
pinned to avoid, should remove pin once fixed in future

The observed behavior is test processes getting wedged. 

Seems to be a timing issue as stepping in the debugger avoids the wedge.

**Comment by alangenfeld** [comment]
I was not able to determine the root cause, the debugger loses the python process where ever its getting wedged, i assume in a native extension. 

I was also not able to reproduce in normal dagit usage, in my limited testing.

**Comment by NominalTrajectory** [comment]
Hi. Since this morning, I'm not able to load multiple repositories using through workspace.yaml, is this issue related?

**Comment by alangenfeld** [comment]
@NominalTrajectory do you have grpcio 1.48.0 installed? If so can you downgrade `grpcio` and see if that fixes your issue?

**Comment by NominalTrajectory** [comment]
@alangenfeld I had grpcio 1.48.0 installed. I downgraded to 1.47.0 and the issue was resolved, and repositories load normally again. Thanks, I've been bashing my head all day.

**Comment by alangenfeld** [comment]
Hmm, I was able to load multiple repositories on `1.48.0` at least in the way I tried. 

@NominalTrajectory  if you could send over any stack traces or useful pieces of information from your head bashing session this morning that would be greatly appreciated.

**Comment by NominalTrajectory** [comment]
@alangenfeld Sure, I should provide some context. 

1. I'm running `0.15.8` Dagster-daemon and Dagit as Docker containers
2. I use docker compose to start the containers
3. I have three repositories listed in the `workspace.yaml` file, as follows

```yaml
load_from:
  - python_file: repository_scraping.py
  - python_file: repository_matching.py
  - python_file: repository_sync.py

```

The same configuration was running fine until today. This morning our images were rebuilt and Dagit became unavailable. I didn't see any errors, just couldn't open the Dagit UI. Then, I tried loading only 1 repository by commenting out the rest in the `workspace.yaml` and it worked. However, trying to load all three (or even two) wasn’t working, all I saw in the logs was 

Started Dagster code server for file ... (for one of the repositories) and no further logs, and Dagit UI not accessible.


Downgrading grpcio to `1.47.0` solved my issue (I double checked it now).

**Comment by alangenfeld** [comment]
py-spy dump of what the wedge, we seem to get stuck waiting for grpc server subprocess to start

https://gist.github.com/alangenfeld/f0233707c00ba15d8255ef7afebf89b3

os sample of the wedge - seems like it might be dead lock involving `grpc_core::Fork::AwaitThreads()` 

https://gist.github.com/alangenfeld/cefd72da60fe01d92c18dee602d845c5

**Comment by gibsondan** [comment]
https://github.com/grpc/grpc/issues/30446

**Comment by FAKERINHEART** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/13352188/182165077-8d1ddc06-2101-4edf-93e7-91611a5cf7df.png">
