### ISSUE TITLE
incorrect dagit display if both `key_prefix` and `group_name` are set using AssetsDefinition.from_graph()

### ISSUE THREAD

**Issue by erinov1** [dagster-io/dagster#9114]
### Dagster version

0.15.7

### What's the issue?

Suppose an asset is defined using `AssetsDefinition.from_graph()` (or `AssetsDefinition.from_op()`). 
- If `key_prefix` is specified, then the asset appears in the "default" group in dagit, and the key prefix is displayed correctly.
- If `group_name` is specified, then the asset appears in the specified group in dagit, and there is no key prefix.
- If both `key_prefix` and `group_name` are specified, then the asset appears in the "default" group (instead of the specified group), and the key prefix is displayed correctly.

### What did you expect to happen?

If both `key_prefix` and `group_name` are specified, then the asset should appear in the specified group (instead of the "default" group), and the key prefix should be displayed correctly.

### How to reproduce?

Define the following three assets and place each one in a repo:
```
@op()
def my_op():
    return True

@graph
def my_graph():
    return my_op()

# displays correctly
asset_with_group = AssetsDefinition.from_graph(graph_def=my_graph, group_name="my_group")

# displays correctly
asset_with_prefix = AssetsDefinition.from_graph(graph_def=my_graph, key_prefix="my_prefix")

# is placed in the "default" group instead of "my_group"
asset_with_group_and_prefix = AssetsDefinition.from_graph(
    graph_def=my_graph, 
    key_prefix="my_prefix",
    group_name="my_group"
)
```

Incidentally, if all three are placed in the same repo, e.g.,
```
@repository
def my_repo():
    return [asset_with_group, asset_with_prefix, asset_with_group_and_prefix]
```
then dagit spits out GraphQL error like

```
Operation name: SidebarAssetQuery

Message: 'my_graph_3'

Path: ["assetNodeOrError","op"]

Locations: [{"line":25,"column":3},{"line":113,"column":3}]
```
when trying to click on the assets in the "default" group.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @erinov1. Here's a fix: https://github.com/dagster-io/dagster/pull/9138.
