### ISSUE TITLE
Cannot use `from_op` when `op_def` is the output of `configured`

### ISSUE THREAD

**Issue by erinov1** [dagster-io/dagster#9118]
### Dagster version

0.15.7

### What's the issue?

First I create a configurable op which I configure using `configured`, and then attempt to create an asset:
```python
from dagster import AssetsDefinition, configured, op

@op()
def configurable_op():
    pass

configured_op = configured(configurable_op, name="configured_op")(
    {"key": "value"}
)

configured_asset = AssetsDefinition.from_op(op_def=configured_op)
```
This yields the following (informative!) error:

```
dagster._check.ParameterCheckError: Param "node_def" is not one of ['GraphDefinition', 'OpDefinition']. Got <dagster.core.definitions.solid_definition.SolidDefinition object at 0x113488760> which is type <class 'dagster.core.definitions.solid_definition.SolidDefinition'>. 
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by erinov1** [comment]
Explicitly setting
```python
configured_op.__class__ = OpDefinition
```
in the above example fixes the issue, so I'm guessing there is a simple fix.

**Comment by sryza** [comment]
Thanks for reporting this @erinov1. Here's a fix: https://github.com/dagster-io/dagster/pull/9136
