### ISSUE TITLE
Update dagster-cron version.

### ISSUE THREAD

**Issue by rasulkireev** [dagster-io/dagster#9133]
### What's the use case?

I'm creating a dagster repo that will be deployed on k8s. I want to use poetry for dependency management. When I run `poetry add dagster` the following line is added to my `pyproject.toml`:

```
dagster = "^0.15.8"
```

When I run `poetry add dagster-cron` I get the following error:
```
  SolverProblemError

  Because no versions of dagster-cron match >0.11.16,<0.12.0
   and dagster-cron (0.11.16) depends on dagster (0.11.16), dagster-cron (>=0.11.16,<0.12.0) requires dagster (0.11.16).
  So, because gc-ds-orchestration depends on both dagster (^0.15.8) and dagster-cron (^0.11.16), version solving failed.
```

Here are the things I'm now considering, but neither is perfect:
- not use poetry and just opt for requirements.txt
- downgrade dagster version to 0.11.16

The reason I want to use Poetry is that right now we will be using dagster repo to host all the code, which will require more dependency. Poetry is the preferred way of doing things at the company that I work for.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
`dagster-cron` is legacy, and was removed a few major releases ago. You should not need that package to run your dagster code.

**Comment by rasulkireev** [comment]
Thanks so much @rexledesma!
