### ISSUE TITLE
Error in Dagit when the op name of an asset does not match the alias

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#9134]
### Dagster version

0.15.8

### What's the issue?

Slack: https://dagster.slack.com/archives/C01U954MEER/p1659346736965669

I believe we've seen this bug before, and it's managed to resurface.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
@bengotow to talk to @OwenKephart about what "alias" means in this context

**Comment by bengotow** [comment]
Per the original slack thread it looks like @OwenKephart  fixed this one in 0.15.8 and we can close this!
