### ISSUE TITLE
Unexpected error while fetching data from Dagster

### ISSUE THREAD

**Issue by akcx** [dagster-io/dagster#9164]
### Dagster version

0.15.5

### What's the issue?

While looking at the instance overview screen in Dagster cloud, I got the following error message in a popup.

```
You hit an unexpected error while fetching data from Dagster.

If you have a minute, consider reporting this error either by filing a Github issue or by messaging in the Dagster slack. Use the "Copy" button below to include error information that is helpful for the core development team to diagnose what is happening and to improve Dagster in recovering from unexpected errors.
```

```
Operation name: StepSummaryForRunQuery

Message: Internal Server Error (Trace ID: 7654489063520913138)

Path: ["pipelineRunOrError","stepStats"]

Locations: [{"line":6,"column":7}]
```

### Deployment type

Dagster Cloud

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @akcx , thanks for the report! Did you encounter this error message more than once, or did it go away after a reload?

**Comment by akcx** [comment]
Hi @OwenKephart, I encountered this only once and the error went away after the reload. I filed this as recommended in the error message to keep track.

**Comment by sryza** [comment]
I'm going to close this because it seems like potentially a transient issue. Please reopen if this starts to come back.
