### ISSUE TITLE
Use offline mirror for yarn to avoid ci/ci failures

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#917]
Right now we are failing ci/cd because of an infra error with yarn. We should cut our dependency on this.

https://twitter.com/yarnpkg/status/1088371531988811776
https://yarnpkg.com/blog/2016/11/24/offline-mirror/

**Comment by mgasner** [comment]
@alangenfeld are we good to close this?

**Comment by schrockn** [comment]
yup

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )
