### ISSUE TITLE
add retry policy to @asset

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#9193]

**Comment by alexanrf** [comment]
Seconded, however RetryRequested works. https://docs.dagster.io/_apidocs/ops#dagster.RetryRequested.

**Comment by yuhan** [comment]
Workaround: create [AssetsDefinition.from_op](https://docs.dagster.io/_apidocs/assets#dagster.AssetsDefinition.from_op) on an op that has a retry policy defined on it

**Comment by jayhale** [comment]
Would be great to have this.  If I'm understanding, SDAs are a wrapper around ops, so I would have expected the full op interface to be implemented.
