### ISSUE TITLE
Display relative time in event logs

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#9209]
**User reported in slack:**

> Just want to suggest that it would be a nice feature if the user could switch from timestamp to relative time in structured event logs in run view, so here in the screenshot below first event time would be 00:00:00.000 and other will be related to it.
It would simplify estimating time delta between some events

>  often look to the timestamp to check where are slow parts of a job (relative time use case) and sometimes when some event occurs to match some other events in external services (timestamp use case) so timestamp on hover is looking more preferable option for me

![image](https://user-images.githubusercontent.com/2798333/182871468-cf8afe13-4b4c-416b-b01d-32b0513d6902.png)

**Comment by hellendag** [comment]
Let's see what @sryza thinks

**Comment by sryza** [comment]
I think there's definitely value in showing the relative timestamp - I usually care about that more than the absolute timestamp. I often care about the timestamp relative to the start of a step vs. the timestamp relative to the start of a run.  However:
- I think we'd need to make sure it doesn't risk being misinterpreted as an absolute timestamp.
- It could be a disruptive change to users who are reliant on the current behavior?

**Comment by hellendag** [comment]
Let's go with a tooltip on the timestamp string.
