### ISSUE TITLE
Support `is_required` for the @asset decorator

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#9220]
### What's the use case?

AssetOut supports this argument, but we don't expose it in the decorator.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
This is a dupe of https://github.com/dagster-io/dagster/issues/8011. We should do this soon though because it's come up a couple times and is straightforward! Only tough part is to figure out whether `is_required` is the right name.
