### ISSUE TITLE
IOManager handle_output in streaming

### ISSUE THREAD

**Issue by xavier-balesi** [dagster-io/dagster#9243]
### What's the use case?

I have a huge file to process.
I need to process it chunk by chunk to preserve the RAM.
Then I want to write the output as stream through the IO Manager.

### Ideas of implementation

An idea of usage (the op return an iterable) :

```python3
class StreamIOManager(IOManager):
    def load_input(self, _: InputContext) -> Any:
        with open("my_output.csv", "r") as f:
            yield from csv.DictReader(f)


    def handle_output(self, _: OutputContext, chunks: Iterable) -> None:
        with open("my_output.csv", "wb") as f:
            for chunk in chunks:
                f.write(chunk)


@io_manager
def stream_io_manager():
    return StreamIOManager()


@asset(io_manager_key="stream_io_manager")
def download_huge_file(_: SolidExecutionContext):
    with requests.get(
        "https://files.data.gouv.fr/annuaire-entreprises/sitemap-name.csv",
        stream=True,
    ) as s:
        yield from s.iter_content(chunk_size=CHUNK_SIZE)


@asset(ins={"huge_file": AssetIn("download_huge_file")})
def filter_huge_file(_: SolidExecutionContext, huge_file):
    for entry in huge_file:
        if entry["toto"] == "tata":
            print(entry)
```

### Additional information

I think it's an essential feature for a data orchestrator ^^

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
This is a cool idea. I think the code you've written should actually work here, even if it's a bit of a pain to have to have to return a generator from your asset (instead of just directly yielding the chunks).

I haven't tried this myself, but does anything break when you do this?

**Comment by xavier-balesi** [comment]
Ok after some retries and fixes my sample of implementation works with input and output. (I had an error but miserderstood and now fixed).

**Comment by OwenKephart** [comment]
https://github.com/dagster-io/dagster/discussions/9772
