### ISSUE TITLE
Poetry cannot resolve dagster-dbt with databricks-dbt

### ISSUE THREAD

**Issue by mv1742** [dagster-io/dagster#9258]
### Dagster version

0.15.8

### What's the issue?

I have looked at other issues and none seems to address my current problem.

I am using the following versions:
- [x] latest dagster 0.15.8
- [x] latest dbt-databricks 1.1.1 
- [x] latest poetry version 1.1.14

Poetry cannot resolve dependencies from the following:

[tool.poetry.dependencies]
python = "^3.7.2"
dagster = "^0.15.7"
dagit = "^0.15.7"
dagster-dbt = "^0.15.7"
dbt-databricks = "^1.1.1"

### What did you expect to happen?

Install all packages successfully and create lock file

### How to reproduce?

Poetry cannot build environment

run the following commands in a new directory:
```
poetry init
```
add the following to the .toml
```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Manrique"]

[tool.poetry.dependencies]
python = "^3.7.2"
dagster = "^0.15.7"
dagit = "^0.15.7"
dagster-dbt = "^0.15.7"
dbt-databricks = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
run install
```
poetry install
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @mv1742 -- I was able to replicate this issue, but setting `python = "^3.8.0"` resolved the issue. Is that an option for you? I imagine some transitive dependency somewhere doesn't support 3.7 or something like that (root cause would likely be pretty tricky to track down)

**Comment by mv1742** [comment]
that works, thank you!
