### ISSUE TITLE
Dagit crashes with large dagster-dbt repo (databricks-dbt)

### ISSUE THREAD

**Issue by mv1742** [dagster-io/dagster#9261]
### Dagster version

0.15.8

### What's the issue?

dagster-dbt setup running fine on local dagit (command `dagit`) but when deploying to kubernetes dagit starts to fail.

**Kubernetes setup works fine on a small dbt repo**

It also works fine before adding dagster-dbt assets from existing debt repo.

`dagit Kubernetes pod` fails on a loop with the errors:

Status: "CrashLoopBackOff
27"

```Readiness probe failed: Get (...) dial tcp 172.17.0.9:80: connect: connection refusedBack-off restarting failed container
```

I tried increasing Dagit resources by using the following values (see deployment section for more details)
```
resources:
    limits:
      cpu: 1100m
      memory: 1128Mi
    requests:
      cpu: 1100m
      memory: 1128Mi
```

I installed the following dependencies with `pip install -r requirements.txt`

```
dagit==0.15.8
dagster-aws==0.15.8
dagster-celery-k8s==0.15.8
dagster-celery==0.15.8
dagster-dbt==0.15.8
dagster-graphql==0.15.8
dagster-k8s==0.15.8
dagster-pandas==0.15.8
dagster-postgres==0.15.8
dagster==0.15.8
dbt-databricks==1.1.1
```

Thankful if you can share other ideas.

### What did you expect to happen?

Dagit should load our dbt project  successfully.

### How to reproduce?

Use Dagster API grip args  package option for dagster-user-deployments.

The package contains the dbt project as a subfolder inside the package, e.g. `dagster/dbt/`

### Deployment type

Dagster Helm chart

### Deployment details

During deployment initially the user-deployment-code shows some issues. See error:
```
The above exception was caused by the following exception:
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "failed to connect to all addresses" debug_error_string = "
```
After a few minutes `user-deployment-code` pod stabilizes and `dagit pod` starts to fail on a loop with the errors:
```Readiness probe failed: Get (...) connect: connection refusedBack-off restarting failed container
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by johannkm** [comment]
@alangenfeld this is probably hitting the grpc timeout? Iirc we made this configurable?

**Comment by alangenfeld** [comment]
> @alangenfeld this is probably hitting the grpc timeout? Iirc we made this configurable?

i did add `DAGSTER_GRPC_TIMEOUT_SECONDS` as an env var that can be set, its not clear to me thats the solution here.

What were the logs in the `dagit` pod ? you can set `logLevel` in helm values to trigger more verbose logging. 

How much memory does the `dagit` process take when it loads the repo locally successfully?

**Comment by mv1742** [comment]
it turns out the issue was one dbt model not being compatible with dagster
