### ISSUE TITLE
dbt creating duplicated schema name

### ISSUE THREAD

**Issue by pwachira** [dagster-io/dagster#9265]
### Dagster version

1.0.1

### What's the issue?

For a local setup with dbt and duckdb (see [example fully_featured](https://github.com/dagster-io/dagster/tree/1.0.1/examples/project_fully_featured))
[Dbt model](https://github.com/dagster-io/dagster/tree/1.0.1/examples/project_fully_featured/dbt_project) is creating tables under schema " activity_analytics_activity_analytics" instead of "activity_analytics"
But the downstream  asset   [activity_analytics](https://github.com/dagster-io/dagster/tree/1.0.1/examples/project_fully_featured/project_fully_featured/assets/activity_analytics) is trying to read from "activity_analytics" and failing

```
The above exception was caused by the following exception:
RuntimeError: Catalog Error: Table with name activity_daily_stats does not exist!
Did you mean "activity_analytics_activity_analytics.activity_daily_stats"?
LINE 1: SELECT * FROM activity_analytics.activity_daily_stats
```

```
In [30]: con.execute("select * from information_schema.tables").fetch_df()
Out[30]: 
   table_catalog                           table_schema                    table_name  ... is_insertable_into  is_typed  commit_action
0            NaN  activity_analytics_activity_analytics             story_daily_stats  ...                YES        NO            NaN
1            NaN  activity_analytics_activity_analytics           comment_daily_stats  ...                YES        NO            NaN
2            NaN  activity_analytics_activity_analytics          activity_daily_stats  ...                YES        NO            NaN
3            NaN                                   core                      comments  ...                 NO        NO            NaN
4            NaN                                   core                       stories  ...                 NO        NO            NaN
5            NaN                            recommender         component_top_stories  ...                 NO        NO            NaN
6            NaN                            recommender               comment_stories  ...                 NO        NO            NaN
7            NaN                            recommender  user_top_recommended_stories  ... 
```
[](url)

### What did you expect to happen?

schema name created by dbt should be just activity_analytics

### How to reproduce?

Rune the example [example fully_featured](https://github.com/dagster-io/dagster/tree/1.0.1/examples/project_fully_featured) locally
Last asset activity_forecast will fail

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @pwachira . I just merged a change that should fix the issue by just naming the schema "activity_analytics".
