### ISSUE TITLE
PartitionedParquetIOManager is unable to load partitioned input in `project_fully_featured` example project

### ISSUE THREAD

**Issue by kien-truong** [dagster-io/dagster#9277]
In the example project `project_fully_featured`, we have 2 core assets `items`, `stories`. 

If you materialize `items` and `stories` in the same run, everything run correctly. 

However, if they are materialized in 2 separate runs, the first run to materialize `items` will finish but the second run to materialize `stories` will fail. It will be unable to load the `items` assets, because the upstream partition info is no longer available.

I'm testing with Dagster `1.0.1`

**Comment by sryza** [comment]
Thanks for reporting this @kien-truong . I was able to reproduce this and am working on a fix.
