### ISSUE TITLE
Unused DBT seed assets aren't displayed

### ISSUE THREAD

**Issue by Nintorac** [dagster-io/dagster#9338]
### Dagster version

0.15.8

### What's the issue?

Seed assets defined in DBT project that aren't used by any of the models in the project don't get picked up as assets by dagster-dbt

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
cc @OwenKephart

**Comment by OwenKephart** [comment]
hi @Nintorac ! Thanks for the report. However, I was not able to replicate this behavior. To confirm, are you calling `load_assets_from_dbt_manifest` / `load_assets_from_dbt_project` with `use_build_command=True`? If you don't set this flag, then no dbt nodes other than models will be represented as assets.

However, from your report it sounds like you are seeing some seeds represented as assets, just not the ones which are unconnected to any models. If that's the case, do you mind sharing a bit more about your dbt project structure? i.e. where these seed files are, and maybe the output of `dbt ls`?

**Comment by Nintorac** [comment]
oh nvm, an errant select that I forgot about :?

Thanks!
