### ISSUE TITLE
Nested op does not receive context

### ISSUE THREAD

**Issue by j-chmielewski** [dagster-io/dagster#9390]
### Dagster version

dagster, version 1.0.3

### What's the issue?

Nested op compute function does not receive context object, code:

```python
@op
def nested_test_op(context: OpExecutionContext) -> None:
    context.log.info("Nested test op started")


@op
def test_op(context: OpExecutionContext) -> None:
    context.log.info("Test op started")
    nested_test_op()


@job
def test_job() -> None:
    test_op()
```

The error:
```
Thread stopped due to exception of type DagsterInvalidInvocationError (unhandled)
Description: Compute function of op 'nested_test_op' has context argument, but no context was provided when invoking.
Stack trace:
  File "/home/jck/workspace/work/teonite/booste/data-warehouse/etl/dagster_scheduler.py", line 357, in test_op
    nested_test_op()
  File "/home/jck/workspace/work/teonite/booste/data-warehouse/etl/import_dbg.py", line 23, in <module>
    test_job.execute_in_process()
```

### What did you expect to happen?

Expected `nested_test_op` to run just as `test_op` did and `context` variable to be set appropriately.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
hey @j-chmielewski - nesting ops is not really an endorsed pattern in Dagster.  If you want to do nesting, we recommend using graphs.  If you do want to invoke an op from inside another op, you're invoking it as if it's a regular Python function, and you can pass the context directly as an argument.

**Comment by j-chmielewski** [comment]
Ok, I guessed this may be the case, thanks for clearing that up.
