### ISSUE TITLE
Show cumulative run failed and success count in Deployment Overview

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#9393]
it would be nice if the Deployment status page showed counts of numbers failed and succeeded in a timeframe

[Slack Link](https://dagster.slack.com/archives/C01U5LFUZJS/p1660601024976499)

**Comment by hellendag** [comment]
I'm not sure I entirely understand the request -- @braunjj let's talk about it when you're back.

**Comment by hellendag** [comment]
Resolved by #9540, at least when behind the flag.
