### ISSUE TITLE
1.0.3: project_fully_featured: Attempting to access partitions def for asset AssetKey(['snowflake', 'recommender', 'comment_stories']), but it is not partitioned

### ISSUE THREAD

**Issue by bitsofinfo** [dagster-io/dagster#9418]
### Dagster version

1.0.3

### What's the issue?

 trying to run the `project_fully_featured` - i've successfully materialized the `core` asset group. I next tried materializing the `recommender.comment_stories` (which works) but when I try the `user_story_matrix` that fails with the errors below

```
dagster._core.errors.DagsterInvariantViolationError: Attempting to access partitions def for asset AssetKey(['snowflake', 'recommender', 'comment_stories']), but it is not partitioned
```

```
Dependencies for step snowflake__recommender__component_top_stories failed: ['s3__recommender__user_story_matrix'] were not executed: ['s3__recommender__recommender_model']. Not executing.
```

```
Dependencies for step snowflake__recommender__user_top_recommended_stories failed: ['s3__recommender__user_story_matrix'] were not executed: ['s3__recommender__recommender_model']. Not executing.
```

### What did you expect to happen?

the example project to work

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for catching this @bitsofinfo - here's a fix: https://github.com/dagster-io/dagster/pull/9422
