### ISSUE TITLE
DBT Uninformative error when DBT CLI crashes in repository load

### ISSUE THREAD

**Issue by Nintorac** [dagster-io/dagster#9425]
### Dagster version

0.15.8

### What's the issue?

No informative output when DBT is misconfigured when loading in dagster

![image](https://user-images.githubusercontent.com/24326299/185291688-914f380a-e045-408b-86be-ee5abf9cd2e6.png)

### What did you expect to happen?

Output the CLI output as part of the exception to help guide debugging

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@OwenKephart

**Comment by OwenKephart** [comment]
Hi @Nintorac ! Thanks for the report -- this behavior was improved on a bit in dagster-dbt 0.16.0 (the error message will include the dbt error logs alongside that message), so I'll close this issue.
