### ISSUE TITLE
Be able to specify asset config when materializing a partitioned asset from Dagit

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#9467]
Currently, launching a materialization of an asset from dagit allows you to specify the partition key, but there's no option to edit/set the config that the materialization launches with. In the global asset view case, since there is no partitioned config for a given asset, this makes it basically impossible to use asset config with the materialize button, but we fail silently right now.

**Comment by adam-bloom** [comment]
Are there any viable workarounds for this in the meantime? I looked at the discussion on the linked PR above, and doesn't seem like there are any?

**Comment by sryza** [comment]
Hey @adam-bloom - I believe that we actually fixed this in the latest release. I.e. you can shift-click the Materialize button when materializing a partitioned asset, and you'll get a dialog where you can enter config. This still doesn't work when backfilling multiple assets.

**Comment by adam-bloom** [comment]
@sryza ahh, must have missed that in the changelog. Just updated our test environment to 1.0.14 from 1.0.13 and confirmed that this is resolved for single materializations. Thanks for letting me know!

**Comment by bengotow** [comment]
Glad the update did the trick! I'm going to go ahead and close this issue - feel free to re-open if you have any trouble after updating to 1.0.14.
