### ISSUE TITLE
Log Level parameter for dagster-daemon

### ISSUE THREAD

**Issue by TimoFriedri** [dagster-io/dagster#9487]
### What's the use case?

Currently the dagster-daemon process can't be debugged since the log level is hardcoded to INFO.

This makes it difficult to e.g. see if something odd is going on between the daemon and the postgres server.

### Ideas of implementation

Pipe the log level to the process arguments, down to eventually the value.yaml of the helm chart.

Start here: `.../_daemon/controller.py` line 155

### Additional information

More info here:
[](https://dagster.slack.com/archives/C01U954MEER/p1661330571555969)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
Hi! thanks for bringing this up! we have an issue tracking this request at #4299
