### ISSUE TITLE
Docker executor doesn’t support retries

### ISSUE THREAD

**Issue by LBolte29** [dagster-io/dagster#9536]
### Dagster version

1.0.4

### What's the issue?

If you attach a retry policy with a partitioned job that runs with the Docker executor, the retries throws the following error 

docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=dagster-step-17d2413766f9852e61c997d7424274919771f51a: Conflict ("Conflict. The container name "/dagster-step-17d2413766f9852e61c997d7424274919771f51a" is already in use by container "92cc63ef1fd49963c6d96f8edc8c40fcc75307783d17c4f7d9ba63d96004396c". You have to remove (or rename) that container to be able to reuse that name."

### What did you expect to happen?

The retry to start normally

### How to reproduce?

You can use the docker_example https://github.com/dagster-io/dagster/tree/master/examples/deploy_docker and then replace the repo.py with the following code:

`
from dagster import RetryPolicy, op, repository, fs_io_manager, job
from dagster_docker import docker_executor

retryPolicy = RetryPolicy(max_retries=1, delay=1)

@op
def an_op(context):
    context.log.info("starting op to fail")
    assert 1 == 2, "1 != 2"
    context.log.info("This must not be printed")

@job(executor_def=docker_executor,
    resource_defs={"io_manager": fs_io_manager.configured({"base_dir": "/tmp/io_manager_storage"})},
    op_retry_policy=retryPolicy)
def a_job():
    an_op()

@repository
def a_repository():
    return [a_job]
`

### Deployment type

Docker Compose

### Deployment details

https://github.com/dagster-io/dagster/tree/master/examples/deploy_docker

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by LBolte29** [comment]
Code to reproduce:

`import os

from dagster import RetryPolicy, static_partitioned_config, op, HookContext, graph, failure_hook, success_hook, repository, fs_io_manager
from dagster_slack import slack_resource
from dagster_docker import docker_executor

retryPolicy = RetryPolicy(max_retries=1, delay=10)

@op(config_schema={"a_config": str}, retry_policy=retryPolicy)
def an_op(context):
    context.log.info("starting op to fail")
    assert 1 == 2, "1 != 2"
    context.log.info("This must not be printed")


@op(config_schema={"another_config": str}, retry_policy=retryPolicy)
def another_op(context):
    context.log.info("No error here")

@static_partitioned_config(partition_keys=["ha", "ho"])
def configs(partition_key: str) -> dict:
    return {
        "ops": {
            "an_op": {
                "config": {
                    "a_config": partition_key,
                }
            },
            "another_op": {
                "config": {"another_config": partition_key}
            },
        },
    }

@graph
def a_graph():
    an_op()
    another_op()

a_job = a_graph.to_job(
    config=configs,
    executor_def=docker_executor,
    resource_defs={"io_manager": fs_io_manager.configured({"base_dir": "/tmp/io_manager_storage"})},
)

@repository
def a_repository():
    return [a_job]
`

**Comment by johannkm** [comment]
Thanks for the report! This is fixed in 1.0.9 (core) / 0.16.9 (libraries)
