### ISSUE TITLE
Partitions incorrectly shown as missing in the UI

### ISSUE THREAD

**Issue by xaniasd** [dagster-io/dagster#9557]
### Dagster version

0.15.8

### What's the issue?

Experiencing this bug with a job materializing a group of SDAs. When running backfills, succesfully completed runs are shown as missing in the UI, both on the job's partition overview page and on the dialog selecting partitions for the backfill.
The corresponding partitions of the related assets are shown correctly.

The attached screenshot hopefully demonstrates the issue. The partition for 2022-08-27 is shown as missing in both bars, while there is a data point in the execution time graph below (the corresponding run was triggered in a backfill and completed successfully). 
<img width="1347" alt="Screenshot 2022-08-31 at 09 31 18" src="https://user-images.githubusercontent.com/6271065/187621832-7d3d70bf-e67c-4bdf-a659-cdf5531ef5fb.png">

Successfully completed scheduled runs are correctly shown on the bar. 

### What did you expect to happen?

The partition bar should correctly show partitions when the corresponding runs finish.

### How to reproduce?

1. Define an asset job materializing a group of assets, with daily partitions
2. Allow a scheduled run to materialize a partition
3. Run a backfill materializing that partition
4. The partition is shown as missing in the partition overview, while partitions of individual assets are shown correctly as present.

I haven't tested other setups so I'm sure exactly what triggers this behavior. 

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
@hellendag i vaguely remember there were some bugs in the partition UI a while ago, do you remember if they were fixed prior to 0.15.8?

**Comment by xaniasd** [comment]
Backfilling an already missing partition (i.e. one that has never been materialized) seems to work correctly, the partition is shown afterwards as completed. This bug occurs only when backfilling a failed partition (didn't try backfilling a successful one)

**Comment by Nintorac** [comment]
Same on 1.0.2

**Comment by panzelva** [comment]
same problem here (on Dagster Cloud) - first correct state is displayed but after few seconds, its replaced with incorrect state - almost looks like some kind of cache problem - see screens below.

Correct state:
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/28455278/189176843-a758523e-e317-4b18-98f4-efb28b1a9224.png">

Incorrect state:
![image](https://user-images.githubusercontent.com/28455278/189176897-ba86f463-bafd-44dc-95a9-2b4ba544a640.png)

Detail:
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/28455278/189176923-682088e7-53aa-4929-addb-261af88218a0.png">

**Comment by prha** [comment]
I think this is a caching issue where the backfill runs are interfering with the overall status when they load in.  Working on a fix right now.
