### ISSUE TITLE
[CRITICAL] DAEMON NOT WORKING PROPERLY SINCE 1.0.7

### ISSUE THREAD

**Issue by IsmaelRDeMelo** [dagster-io/dagster#9586]
Hi, the daemon it's stopping all the time for no reason since release 1.0.7, I already tried rollback to previous 1.0.6, but still, so I think it's a problem related to the way Dagster storage its data using SQLite because I tested using MySQL as storage, and nothing happened at the firsts 30 minutes, but when I'm using SQLite the thing just stops work at with 10 to 15 minutes, sometimes more than an hour, but isn't working all the time anymore.
It says Sensors and Schedules stopped, so the daemon also will stop this does not make sense to me, it should run all the time or try at least restart the daemon instead of deactivating it.

Can someone help me? It's a great pain when the most critical feature of an orchestrator just doesn't work anymore. I don't know what to do anymore, please, someone help.
Maybe it's something related to MB of storage.
![image](https://user-images.githubusercontent.com/54531312/188374960-758a3334-a5d9-4638-9823-a68c935404fe.png)

I also started to have this issue when starting my application
![image](https://user-images.githubusercontent.com/54531312/188384108-9e46c233-6406-446b-b951-7ac8ccae5fc8.png)

**Comment by yuhan** [comment]
closing this issue as discussion is continuing in [dagster slack](https://dagster.slack.com/archives/C01U954MEER/p1662254951865759).
