### ISSUE TITLE
[docs] - Partitioned I/O managers

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#9597]
### What's the issue or suggestion?

Partitioned I/O managers are I/O managers that pull partition information off of the context to make decisions about where to store data.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jayhale** [comment]
Would be very helpful to have better documentation of the IOManager interface, especially what features need to be present to handle partitioning.

**Comment by sryza** [comment]
hey @jayhale - any particular details that you think are missing? e.g. things that you learned that took a while or open questions that you still have?

**Comment by jayhale** [comment]
@sryza a couple of things that took digging through the code:
- The IO manager must infer whether or not the output is partitioned from `context` in both the `handle_output` and `load_input`: https://github.com/dagster-io/dagster/blob/cf8d61152c50c350489ac312ee209e57085dc441/python_modules/libraries/dagster-snowflake/dagster_snowflake/db_io_manager.py#L153
- There is no way to create an `OuputManager` only, `IOManager` is the only ABC that is exposed, and must implement both input handling and output handling even if they are only performing one function (e.g., with an `raise NotImplementedError`)

I was expecting to find a set of ABCs like below:
```
          ┌────────────────┐   ┌─────────────────┐    *Base classes are ABCs that scaffold
          │InputManagerBase│   │OutputManagerBase│    the expected interface (e.g.,
          └───────────────┬┘   └─┬───────────────┘    `handle_output()` for `OutputManagerBase`
                          │      │
                          │      │
                          │      │
┌─────────────────────┐ ┌─▼──────▼┐ ┌──────────────────────┐
│PartitionedInputMixin│ │IOManager│ │PartitionedOutputMixin│
└───────────────────┬─┘ └────┬────┘ └─┬────────────────────┘
                    │        │        │
                    │        │        │        Partitioning is handled in an entirely separate
                    │        │        │        flow (e.g., something like
                  ┌─▼────────▼────────▼┐       `handle_partitioned_output(obj, partition_key)`
                  │PartitionedIOManager│       that prepares the output before calling
                  └────────────────────┘       `handle_output()`)
```

**Comment by sryza** [comment]
Here's a PR that aims to make the docs somewhat clearer: https://github.com/dagster-io/dagster/pull/9987.

I filed an issue to track exposing OutputManagers: https://github.com/dagster-io/dagster/issues/9991.

and another issue to track potentially adding a PartitionedIOManager: https://github.com/dagster-io/dagster/issues/9997

**Comment by erinkcochran87** [comment]
@sryza It looks like doc updates related to this issue have since been merged - does this need to stay open?
