### ISSUE TITLE
Managing code locations doc does not apply to serverless

### ISSUE THREAD

**Issue by petehunt** [dagster-io/dagster#9612]
### What's the issue or suggestion?

I was helping someone understand how code locations interact with Serverless and sent him the docs: https://docs.dagster.io/dagster-cloud/developing-testing/code-locations#managing-code-locations-in-dagster-cloud-1

However, the docs mention things that aren't available in serverless, like `container_context` and `image`. Do we want to update the docs to make it clearer which configuration options are available for which agent types?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by erinkcochran87** [comment]
This is being addressed by #9643. Do you want this to stay open until that PR is merged, or can I go ahead and close this @petehunt?

**Comment by erinkcochran87** [comment]
I'm going to close this guy out, as it'll be addressed in the PR I referenced in my last comment.
