### ISSUE TITLE
Ephemeral EMR cluster resource example in airline demo

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#966]

**Comment by mgasner** [comment]
@natekupp

**Comment by natekupp** [comment]
@sryza we're not too far from this, right? just would need to finish up work on streaming back EMR logs, and make the airline demo example launch an ephemeral cluster vs. running on an existing cluster

**Comment by sryza** [comment]
Yeah, exactly

**Comment by natekupp** [comment]
FYI @sryza bumping this to 0.10.0

**Comment by catherinewu** [comment]
closing this since we intend to deprecate airline demo cc @yuhan
