### ISSUE TITLE
Nothing happens when user clicks on a backfill ID on the partitions page under Backfill History

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#9662]
Reported in [slack](https://elementl-workspace.slack.com/archives/C03CCE471E0/p1663002595649759)

**Comment by hellendag** [comment]
I think maybe this filtered view was removed when the new partition page was shipped. I believe the dialogs available in the table row menus should provide the relevant context. I'll go ahead and remove the link to alleviate confusion, and I'm going to do some visual cleanup while I'm in there.
