### ISSUE TITLE
Spurious failure on airline-demo tests

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#975]
https://circleci.com/gh/dagster-io/dagster/94589?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by schrockn** [comment]
another:

https://circleci.com/gh/dagster-io/dagster/96852?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mgasner** [comment]
We're not seeing these on Buildkite
