### ISSUE TITLE
run_config does not override a graph config

### ISSUE THREAD

**Issue by scott-arne** [dagster-io/dagster#9767]
### Dagster version

dagster, version 1.0.9

### What's the issue?

When executing a job with ```execute_in_process```, I am unable to use ```run_config``` to override previously defined ```config``` values on a graph.

The following is the minimum example that still executes, please see below for what I would have expected to work.

### Minimally Reproducible Example

This does the following:
1. Defines an op called ```print_value``` that just prints a number it is configured with.
2. Defines a graph where ```print_value``` is the only op. **The graph is configured with a default value to print.**
3. Defines a job from the graph generated in the previous step.

```python
from dagster import op, graph


@op(config_schema={"value": int})
def print_value(context):
    context.log.info(f'The value is {context.op_config["value"]}')


@graph(config={"print_value": {"config": {"value": 8675309}}})
def print_value_graph():
    print_value()


# Create a job from the graph
print_value_job = print_value_graph.to_job()


if __name__ == "__main__":
    print_value_job.execute_in_process(
        run_config={
            # Try to configure a new value to print...
            "ops": {
                # This extra config key required here for the code to run looks fishy? 
                # But it won't run without it! See below.
                "config": {"print_value": {"config": {"value": 42}}}
            }
        }
    )
```

### Output

Note that it is printing the default value defined on the graph, not within ```run_config```.

```text
2022-09-21 16:54:26 -0700 - dagster - INFO - print_value_graph - a3c8555a-9e28-497c-bac5-0e7d34ff90d3 - print_value - The value is 8675309
```

### How I would have expected it to work

I would have expected this to work based on the [documentation here on configuring graphs](https://docs.dagster.io/concepts/ops-jobs-graphs/graphs#directly-inside-jobs):

```python
    math_job.execute_in_process(
        run_config={
            # Note: I've removed the extra "config" here, you'll see why I had it above in the MRE
            "ops": {
                "print_value": {"config": {"number": 42}}
            }
        }
    )
```

This fails with the following:

```text
Traceback (most recent call last):
  File "/Users/johnss51/Desktop/dagster_error.py", line 21, in <module>
    print_value_job.execute_in_process(
  File "/Users/johnss51/local/miniconda3/envs/dagit/lib/python3.9/site-packages/dagster/_core/definitions/job_definition.py", line 393, in execute_in_process
    return core_execute_in_process(
  File "/Users/johnss51/local/miniconda3/envs/dagit/lib/python3.9/site-packages/dagster/_core/execution/execute_in_process.py", line 40, in core_execute_in_process
    execution_plan = create_execution_plan(
  File "/Users/johnss51/local/miniconda3/envs/dagit/lib/python3.9/site-packages/dagster/_core/execution/api.py", line 1003, in create_execution_plan
    resolved_run_config = ResolvedRunConfig.build(pipeline_def, run_config, mode=mode)
  File "/Users/johnss51/local/miniconda3/envs/dagit/lib/python3.9/site-packages/dagster/_core/system_config/objects.py", line 174, in build
    raise DagsterInvalidConfigError(
dagster._core.errors.DagsterInvalidConfigError: Error in config for job
    Error 1: Received unexpected config entry "print_value" at path root:ops. Expected: "{ config?: Any }".
```

### Why I would have expected that to work?

I'd have expected it to work using the configuration above, because if I remove the default config from the ```@graph``` decorator, the above code works. Here is an example of that:

```python
from dagster import op, graph


@op(config_schema={"value": int})
def print_value(context):
    context.log.info(f'The value is {context.op_config["value"]}')


# Note: Default config removed from graph decorator - this is not what I want!
@graph
def print_value_graph():
    print_value()


# Create a job from the graph
print_value_job = print_value_graph.to_job()


if __name__ == "__main__":
    # Say we don't want to do default math...
    # Overwriting default config here breaks
    print_value_job.execute_in_process(
        run_config={
            # Try to overwrite the default add_n value
            "ops": {
                # This works now
                "print_value": {"config": {"value": 42}}
            }
        }
    )
```

And the output is as expected, we are now using the value provided to ```run_config```:

```text
2022-09-21 17:01:31 -0700 - dagster - INFO - print_value_graph - 00f7e3cc-a56d-4591-9abd-3f2c42cda84b - print_value - The value is 42
```

Note that this is **not** what I want though, I'd like to have sensible defaults on the ```@graph``` decorator that can be overridden at runtime with ```run_config```.

### How to reproduce?

Please see MRE and "What did you expect to happen above".

### Deployment type

Local

### Deployment details

Mac OS X 12.6
Python 3.9.7
dagster, version 1.0.9

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @scott-arne ! This is actually expected behavior, albeit a bit confusing.

The `config` argument to a graph is one of two things:

1. static, non-overridable dictionary of config
2. a ConfigMapping function, which is a function which takes in some dictionary config (with an arbitrary config schema), and produces a new dictionary of config matching the config schema of the graph itself.

In your case, two things are happening. First, when you define a static dictionary of config on your graph, you get a hardcoded set of config that will always be passed to subsidiary ops. Second, a defauly config schema is placed on top of that default config, which is permissive, meaning it allows any config to be applied to your graph (just with no effect, as regardless of the config given to your graph, the output config will be that same dictionary).

Default values are generally easiest to define on the config schema where that value is used, so in this example I'd recommend `@op(config_schema={"value": Field(int, default_value=8675309)})`

You can also define a config mapping function to override the default value for a graph that uses this op. In this case this would look something like:

```
from dagster import op, graph, config_mapping, Field

@op(config_schema={"value": Field(int, default_value=8675309)})
def print_value(context):
    context.log.info(f'The value is {context.op_config["value"]}')

@config_mapping(config_schema={"value": Field(int, default_value=42)})
def my_config_mapping(val):
    return {
        "print_value": {"config": {"value": val["value"]}}
    }

@graph(config=my_config_mapping)
def print_value_graph():
    print_value()

# Create a job from the graph
print_value_job = print_value_graph.to_job()


if __name__ == "__main__":
    print_value_job.execute_in_process(
        # "ops" is the key under which all graph/op configuration lives in this schema
        # our top level graph now has a simplified config schema, thanks to our config mapping, so
        # we just need to provide the value directly
        run_config={"ops": {"config": {"value": 20}}} 
    )
```
