### ISSUE TITLE
execute_in_process raises RetryRequested instead of actual exception

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#9790]
From https://dagster.slack.com/archives/C01U954MEER/p1661343110296189 
If the underlying op raises RetryRequested, execute_in_process will raise that back out to the system instead of raising the underlying exception post-retries.
code snippet: 
```python
from dagster import graph, op, RetryRequested

RETRY = 0

def always_fail() -> None:
    """Fail."""
    exception = Exception("I have failed.")
    if RETRY:
        raise RetryRequested(max_retries=2) from exception
    raise exception


@op
def fail_op() -> None:
    """Op that fails."""
    always_fail()


@graph
def fail_pipeline() -> None:
    """Fail pipeline."""
    fail_op()
```
Causes the following test to fail if retries are set to >1:
```python
def test_fail() -> None:
    """Ensure that a failing pipeline causes an exception."""
    with pytest.raises(Exception, match="I have failed."):
        fail_pipeline.execute_in_process()
```

**Comment by yuhan** [comment]
https://github.com/dagster-io/dagster/pull/9884 seems like this got reverted? any blockers? @dpeng817

**Comment by dpeng817** [comment]
It got put back out as https://app.graphite.dev/github/pr/dagster-io/dagster/9934 - this is resolved.
