### ISSUE TITLE
Custom logger works with Dagster CLI but not with Dagit UI or Schedules

### ISSUE THREAD

**Issue by ScottRWood** [dagster-io/dagster#9829]
### Dagster version

0.13.9

### What's the issue?

I've written a custom logger which outputs to a log file, and then applied two of them to a job. 

**Job**

```
@op
def hello_logs(context):
    context.log.info("Hello, world!")
    x = 1/0


@job(logger_defs={"datadog_error_logger": datadog_file_logger, "datadog_info_logger": datadog_file_logger})
def demo_job():
    hello_logs()
```

**Logger**

```
@logger(
    {
        "log_level": Field(str, is_required=False, default_value="INFO"),
        "name": Field(str, is_required=False, default_value="dagster"),
        "outfile": Field(str, is_required=False, default_value="logs/log.log"),
    },
    description="A JSON-formatted console logger",
)
def datadog_file_logger(init_context):
    level = init_context.logger_config["log_level"]
    name = init_context.logger_config["name"]

    klass = logging.getLoggerClass()
    logger_ = klass(name, level=level)

    handler = logging.FileHandler(init_context.logger_config["outfile"], mode="w")

    class JsonFormatter(logging.Formatter):
        def format(self, record):
            return json.dumps(record.__dict__)

    handler.setFormatter(JsonFormatter())
    logger_.addHandler(handler)

    return logger_
```

**Logger Config**

```
loggers:
  datadog_error_logger:
    config:
      log_level: ERROR
      outfile: logs/error.log
  datadog_info_logger:
    config:
      log_level: INFO
      outfile: logs/general.log
```

Now this log works when the job is run with dagster CLI. But it doesn't work when the job is run in the Dagit UI or with a schedule. It is deployed in a docker container currently.

### What did you expect to happen?

I expect the error logs to go to `logs/error.log` and the info logs to go to `logs/general.log` when the job is run in the dagit UI or when the job is run on a schedule.

### How to reproduce?

Code given above. Run `dagster job execute -f test_job.py -c custom_logger_config.yml` to run in CLI. Run on Dagit UI or with a schedule to test failing scenarios.

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ConnorWhelanHDAI** [comment]
+1

**Comment by ScottRWood** [comment]
Hi, I have copied the config into the UI for it, as well as having it read in and applied to the execution context by the schedule

**Comment by sryza** [comment]
I just tried this locally (no Docker) was able to get the logs to show up when I launched a run from Dagit. Maybe it has something to do with the Docker setup? If you use absolute paths instead of relative, does that help?

**Comment by hellendag** [comment]
Closing as stale.
