### ISSUE TITLE
TimeWindow has misleading type annotations

### ISSUE THREAD

**Issue by ltowarek** [dagster-io/dagster#9862]
### Dagster version

dagster, version 1.0.11

### What's the issue?

[TimeWindow](https://github.com/dagster-io/dagster/blob/aa8b753c709c55ee7c1ea9c39b4fc4898012ddc1/python_modules/dagster/dagster/_core/definitions/time_window_partitions.py#L23) is defined in terms of [datetime.datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime) objects. However that's not the case, as [time_window_for_partition_key](https://github.com/dagster-io/dagster/blob/aa8b753c709c55ee7c1ea9c39b4fc4898012ddc1/python_modules/dagster/dagster/_core/definitions/time_window_partitions.py#L150) returns [pendulum.DateTime](https://github.com/sdispater/pendulum/blob/7f6d069d8eee0b022dac276e7d6ef7545e78220e/pendulum/datetime.py#L47) objects.

It is quite misleading as pendulum is not a 1:1 replacement for datetime as you can see below:
```python
>>> import datetime
>>> x = datetime.datetime(2022, 10, 23, 8, 30)
>>> str(x)
'2022-10-23 08:30:00'
>>> import pendulum
>>> y = pendulum.instance(x)
>>> str(y)
'2022-10-23T08:30:00+00:00'
>>> str(x) == str(y)
False
```

### What did you expect to happen?

Please fix type annotations for TimeWindow to use pendulum objects or change time_window_partitions to return datetime objects.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @ltowarek - I believe the reason that we do this is that the type will be `pendulum.Pendulum` in Pendulum 1 and `pendulum.DateTime` in Pendulum 2. We can't pin Pendulum, because different users depend on different versions.

From your example - `isinstance(y, datetime)` returns `True`.

**Comment by ltowarek** [comment]
I see, thanks! In this case I have submitted an issue for pendulum to better understand differences in string representations - https://github.com/sdispater/pendulum/issues/662.
