### ISSUE TITLE
Duplicate type error message is questionable

### ISSUE THREAD

**Issue by bengotow** [dagster-io/dagster#988]
```
Type names must be unique. You have construct two instances of types with the same key {key} but have different instances. Instance one {inst_one}. Instance two {inst_two}.
```

- printing inst_one and inst_two prints exactly the same thing (that's part of the problem)
- "You have construct two instances of types" => "You have defined two concrete types", maybe? "two instances of type but with different instances" makes no sense.

**Comment by mgasner** [comment]
![ayb](https://user-images.githubusercontent.com/427016/54844996-75b2c900-4c95-11e9-835c-4ada883312a8.jpg)
