### ISSUE TITLE
Odd error message when an unexpected config field is present

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#991]
`E               Error 1: Undefined field "archive_member" on type "None" at path root:solids:unzip_q2_coupon_data:config`

What is `type "None"` doing here?

**Comment by schrockn** [comment]
![Screenshot 2019-03-26 14 31 12](https://user-images.githubusercontent.com/28738937/55034912-d747a000-4fd3-11e9-9da7-1c3f4d885fae.png)

@mgasner  this is error message that I'm seeing. Bouncing back to you so that we can nail down repro or say that this is resolved.

**Comment by schrockn** [comment]
Closing in favor of https://github.com/dagster-io/dagster/issues/1090
