### ISSUE TITLE
Unable to install Dagster via HELM

### ISSUE THREAD

**Issue by dangal95** [dagster-io/dagster#9927]
I am trying to install Dagster via HELM on AWS EKS by following this documentation: https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm

I am using EKS version 1.23 and the Dagster HELM chart version 1.0.12

I install dagster and then get the following errors, but I'm not sure why this is happening. 

![image](https://user-images.githubusercontent.com/24626518/194555687-bf258d51-19df-443b-98c1-9df6732b649e.png)

All three pods have one failed container:
Daemon -
![image](https://user-images.githubusercontent.com/24626518/194557288-3e4e93e2-55bc-4ab3-8e1d-00c731293639.png)

Dagit - 
![image](https://user-images.githubusercontent.com/24626518/194557390-e7cd34e7-17de-4be7-ba6e-5a32d868be80.png)

Dagster user deployments - 
![image](https://user-images.githubusercontent.com/24626518/194557465-b4217087-7452-4363-8117-9561b6118d13.png)

The error log in all the Daemon and Dagit failed containers is:
`exec /bin/bash: exec format error`

The error log in the user deployment container is:
`exec /usr/local/bin/dagster: exec format error 
`
I am not sure as to what the problem could be given that I am following the tutorial. Is it an EKS / HELM incompatibility issue?

**Comment by Yatagani** [comment]
Hi, I had the same issue. Were you able to solve it?

**Comment by dangal95** [comment]
@Yatagani I haven't been able to resolve this yet either.  Are you also trying to run it on EKS? If so, which version are you using?

**Comment by Yatagani** [comment]
I am running on GKE. Try downgrade to 1.0.11.

**Comment by dangal95** [comment]
Did it work when downgrading to 1.0.11? I tried downgrading even further, to 0.15.10 but I got the same issue.

**Comment by johannkm** [comment]
Are you using the provided images? Or have you built your own?

**Comment by dangal95** [comment]
@johannkm I am using the provided images available in the values.yaml available here https://github.com/dagster-io/dagster/blob/master/helm/dagster/values.yaml

**Comment by Yatagani** [comment]
> Are you using the provided images? Or have you built your own?

When using their Docker Image (user-example-code) everything works fine. For me the problem arises when providing my own image. Here is my Dockerfile
```
FROM python:3.7.13-slim

ARG DAGSTER_VERSION=1.0.11

RUN pip install \
    dagster==${DAGSTER_VERSION} \
    dagster-postgres \
    dagster-k8s \
    dagster-celery[flower,redis,kubernetes] \
    dagster-celery-k8s \
    pandas \
    pyyaml \
    pandas-datareader \
    google-cloud \
    # Cleanup
    &&  rm -rf /var \
    &&  rm -rf /root/.cache  \
    &&  rm -rf /usr/lib/python2.7 \
    &&  rm -rf /usr/lib/x86_64-linux-gnu/guile


COPY pipelines/ /
```

Pipelines repository contains the workspace.yaml and repo.py file

**Comment by madhur-tandon** [comment]
It's probably because you guys are building the docker image on an M1 Mac i.e. ARM architecture while the EC2 machines on the EKS cluster are Linux machines with the x86 or perhaps amd64 architecture. You should probably use the `--platform` while building your image with docker.

**Comment by dangal95** [comment]
@madhur-tandon You are right :) My EC2 instances were of type "g" which are ARM based, and the official Dagster images are built on AMD architectures. Switching to type "a" EC2 solved it for me. I am closing this issue.
