### ISSUE TITLE
Ops and assets with required config break when config is provided to job definitions

### ISSUE THREAD

**Issue by archiekennedy** [dagster-io/dagster#9943]
### Dagster version

dagster, version 1.0.12

### What's the issue?

Providing config to job definitions causes missing config errors at build time if any related ops/assets have `config_schema`.

### What did you expect to happen?

Jobs need to accept software-defined config, for example when using the s3_pickle_io_manager:

```py
@job(
  ...
  config={
    "resources": {
      "io_manager": {
        "config": {"s3_bucket": "my-bucket"}
      }
    }
  }
)
```

This pattern is incompatible with ops & assets with `config_schema` because they fail the config schema check.

### How to reproduce?

This code shows the problem, removing the `config={}` stops the error.

```py
"""Using ops"""

from dagster import repository, job, op, Field


@op(config_schema={"thing": Field(str)})
def hello():
    return "Hello, Dagster!"


@job(
    # Providing config to the job causes an error at build time
    config={}
)
def say_hello_job():
    hello()


@repository
def my_project():
    jobs = [say_hello_job]
    return jobs
```

```py
"""Using assets"""

from dagster import repository, Field, asset, define_asset_job


@asset(config_schema={"thing": Field(str)})
def hello():
    return "Hello, Dagster!"


say_hello_job = define_asset_job(
    "say_hello_job",
    selection="hello",
    # Providing config to the job causes an error at build time
    config={}
)


@repository
def my_project():
    jobs = [say_hello_job]
    assets = [hello]
    return jobs + assets
```

### Additional information

Error output when running `dagit`:
```
Error 1: Missing required config entry "ops" at the root. Sample config for missing entry: {'ops': {'hello': {'config': {'thing': '...'}}}}
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@alangenfeld @dpeng817 I think you know more about the config system than me.  This looks like a bug to me - is it?

**Comment by archiekennedy** [comment]
Update:
* Isolated the bug further
* Confirmed it also affects software-defined assets

**Comment by archiekennedy** [comment]
Thanks for the info, I'll check out configured.

Just for reference, my current workaround is to provide a "fallback" value for required fields. Example:

```py
@job(
    resource_defs={
        "io_manager": s3_pickle_io_manager,
        "s3": s3_client,
    },
    config={
        "resources": {
            "io_manager": {
                "config": {"s3_bucket": "my_bucket"}
            }
        },
        # Workaround for https://github.com/dagster-io/dagster/issues/9943
        "ops": {"ingestion": {"ops": {"my_op": {"config": {"payload": {"thing": ""}}}}}}},
)
```

**Comment by sryza** [comment]
Because we have the issue that @alangenfeld mentioned for tracking this, I'm going to close this issue. Feel free to reopen if you think that's a mistake.

**Comment by resulyrt93** [comment]
Also, if you re execute from the UI, partial executions work in this way. or if you send a `LaunchPipelineExecution` graphql request like below. 
```
{
  "executionParams": {
    "mode": "default", 
    "stepKeys": ["my_last_op"],
    "selector": {
        "repositoryLocationName": "...",
        "repositoryName": "...",
        "pipelineName": "...",
        "solidSelection": ["my_last_op"]
    }}
}
``` 
so I don't think there is a technical obstacle to partial execution.
