### ISSUE TITLE
Experimental dependency resolution results in unexpected asset selections

### ISSUE THREAD

**Issue by jayhale** [dagster-io/dagster#9944]
### Dagster version

dagster, version 1.0.12

### What's the issue?

When an asset dependency is resolved with same-group inference, selecting that asset (e.g, for a job) results in an `AssetSelection` of all assets.

E.g.:

With two assets
```python
@asset(
    name="cdrs_search_start_time",
    key_prefix=PREFIX,
    required_resource_keys={"atscall_snowflake"},
)
def get_recent_cdrs_start_time(context):
    # ...

@asset(
    name="cdrs",
    key_prefix=PREFIX,
    required_resource_keys={"atscall"},
    io_manager_key="atscall_snowflake_io_manager",
)
def get_recent_cdrs(context, cdrs_search_start_time):
    # ...
```

This `AssetSelection` behaves strangely and resolves to all assets in the repository.
```python
extract_cdrs_job = define_asset_job(
    name="extract_cdrs_job",
    selection=AssetSelection.assets(
        get_recent_cdrs_start_time,
        get_recent_cdrs
    )
)
```

However, directly specifying the dependency resolves the issue:
```python
@asset(
    name="cdrs",
    key_prefix=PREFIX,
    required_resource_keys={"atscall"},
    io_manager_key="atscall_snowflake_io_manager",
    ins={"cdrs_search_start_time": AssetIn(key=get_recent_cdrs_start_time.key)}
)
def get_recent_cdrs(context, cdrs_search_start_time):
    # ...
```

Relevant line for dependency resolution: https://github.com/dagster-io/dagster/blob/e1adadd33cecf01474ec1c232b5b52b68ab1210a/python_modules/dagster/dagster/_core/definitions/resolved_asset_deps.py#L94

### What did you expect to happen?

The experimental same-group asset dependency resolution should not impact `AssetSelection`s.

### How to reproduce?

See above for an example.

### Deployment details

Dagster Cloud

### Additional information

Slack conversation: https://dagster.slack.com/archives/C01U954MEER/p1665411262280519

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for filing this @jayhale. I wouldn't expect dependency resolution logic to have an impact on what assets a selection is resolved to (unless you're using the `upstream` or `downstream` methods on `AssetSelection`).

Any chance you have an example that I'd be able to try this out on?

**Comment by jayhale** [comment]
@sryza I spent a little time trying to replicate the problem in a smaller project and haven't been able to.

This is impacting a pure-python SDA that is named as a source for a dbt asset handled by dagster-dbt, so I'm thinking it may be an issue with dagster-dbt, but haven't had the time to track it down.

**Comment by sryza** [comment]
Got it - I'm going to close this in that case. Please reopen if you the issue again!
