### ISSUE TITLE
Asset Key column in the asset group list view is unnecessarily squished

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#9986]
![image](https://user-images.githubusercontent.com/654855/195398427-bd085e40-6d6a-4f03-a450-99fae41f4c94.png)

The Asset Key column in the asset group list view feels squished. I think it's more important than "Defined In".

**Comment by hellendag** [comment]
I think we'll change this view to use the virtualized tables that we're now using elsewhere, which should give us quite a bit more space for rendering asset keys, and should solve some other issues at the same time.
