### ISSUE TITLE
make build_asset_reconciliation_sensor work with partitions

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#9988]

**Comment by yeachan153** [comment]
@sryza will this also support cases where the partition definition of the downstream asset is more granular than the upstream asset? For example, we have use cases where the upstream asset is daily, but the downstream asset is hourly.

I didn't find any documentation about such usecases in the [partition dependencies documentation](https://docs.dagster.io/concepts/partitions-schedules-sensors/partitions#partition-dependencies)

**Comment by sryza** [comment]
@yeachan153 - yes, it will. The current time window partition mapping models that case, and the partitioned reconciliation sensor will use it to kick off runs in the right order.

**Comment by yeachan153** [comment]
OK, I guess that will work slightly differently then? From what I've seen advancing the cursor prevents the same materialisation from being used to trigger a downstream asset from kicking off. In this case, since the upstream asset would have a daily partition and the downstream asset would have an hourly one, we'd be expecting 24 materialisations of the downstream asset based on a single upstream materialisation.

**Comment by sryza** [comment]
@yeachan153 exactly - here's the test case for this: https://github.com/dagster-io/dagster/pull/10410/files#diff-bb28a0abbe6fd8d9dcdc646a29409c07020f46a8a6c855ee818c3262d5c18478R506.

**Comment by yeachan153** [comment]
@sryza I tried testing this on a graph backed asset, seems to trip up at https://github.com/dagster-io/dagster/blob/7019df523976202219380d56643125b3e877191a/python_modules/dagster/dagster/_core/definitions/sensor_definition.py#L624

Seems like no basejob was found:

```bash
docker_example_daemon        |   File "/usr/local/lib/python3.7/site-packages/dagster/_grpc/impl.py", line 323, in get_external_sensor_execution
docker_example_daemon        |     return sensor_def.evaluate_tick(sensor_context)
docker_example_daemon        |   File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/sensor_definition.py", line 420, in evaluate_tick
docker_example_daemon        |     run_requests, context, self._asset_selection
docker_example_daemon        |   File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/sensor_definition.py", line 622, in _run_requests_with_base_asset_jobs
docker_example_daemon        |     job_name=base_job.name, asset_selection=list(asset_keys)
```

**Comment by sryza** [comment]
@yeachan153 any chance you've got some code you could share that reproduces the issue?

**Comment by yeachan153** [comment]
@sryza sorry, that may have been my mistake.

I do get another error now, here's the code snippet:
```python
@op(ins={"arg": In(Nothing)}, out={"result": Out(Nothing)})
def foo(context):
    pass

@graph()
def upstream() -> Nothing:
    return foo()

upstream_asset = AssetsDefinition.from_graph(upstream, partitions_def=DailyPartitionsDefinition("2022-11-10"))

@op(ins={"arg": In(Nothing)}, out={"result": Out(Nothing)})
def bar(context):
    pass

@graph(ins={"upstream": GraphIn()})
def downstream(upstream: Nothing) -> Nothing:
    return bar(arg=upstream)

downstream_asset = AssetsDefinition.from_graph(downstream, partitions_def=DailyPartitionsDefinition("2022-11-10"))

reconcile = build_asset_reconciliation_sensor(
    asset_selection=AssetSelection.assets(upstream_asset, downstream_asset),
    name="asset_reconciliation_sensor",
)

@repository
def test_repo():
    return [
        upstream_asset, downstream_asset, reconcile
    ]
```

and the trace:

```bash
dagster._check.CheckError: Failure condition: Tried to access partition_key_range for a non-partitioned run
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_plan.py", line 251, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_step.py", line 370, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event, input_lineage):
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_step.py", line 427, in _type_check_and_store_output
    for evt in _store_output(step_context, step_output_handle, output, input_lineage):
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_step.py", line 636, in _store_output
    output_context, output_def, output_manager
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/execution/plan/execute_step.py", line 458, in _asset_key_and_partitions_for_output
    output_asset_info.partitions_fn(output_context) or set(),
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/asset_layer.py", line 625, in partitions_fn
    ).get_partition_keys_in_range(context.asset_partition_key_range)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/execution/context/output.py", line 441, in asset_partition_key_range
    return self.step_context.asset_partition_key_range_for_output(self.name)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/execution/context/system.py", line 846, in asset_partition_key_range_for_output
    return self.asset_partition_key_range
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/execution/context/system.py", line 370, in asset_partition_key_range
    check.failed("Tried to access partition_key_range for a non-partitioned run")
  File "/usr/local/lib/python3.7/site-packages/dagster/_check/__init__.py", line 1485, in failed
    raise CheckError(f"Failure condition: {desc}")
```

**Comment by sryza** [comment]
@yeachan153 - I think I saw your deleted message, and the error you included corresponds to a bug that should be fixed in today's release.

**Comment by yeachan153** [comment]
> @yeachan153 any chance you've got some code you could share that reproduces the issue?

Sorry, that was probably user error on my part.

> @yeachan153 - I think I saw your deleted message, and the error you included corresponds to a bug that should be fixed in today's upcoming release.

That was quick! Wanted to double check something before posting, but good to know. I'll try it again in a few days :-)

**Comment by yeachan153** [comment]
@sryza tried this again, it now successfully materialises both assets in my test with the first sensor tick. On subsequent ticks I receive a type error about the partition keys:

```bash
dagster._check.CheckError: Member of list mismatches type. Expected <class 'dagster._core.definitions.partition_key_range.PartitionKeyRange'>. Got ['2022-11-18', '2022-11-20'] of type <class 'list'>.
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/errors.py", line 188, in user_code_error_boundary
    yield
  File "/usr/local/lib/python3.7/site-packages/dagster/_grpc/impl.py", line 321, in get_external_sensor_execution
    return sensor_def.evaluate_tick(sensor_context)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/sensor_definition.py", line 376, in evaluate_tick
    result = list(self._evaluation_fn(context))
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/sensor_definition.py", line 535, in _wrapped_fn
    result = fn(context)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/asset_reconciliation_sensor.py", line 842, in sensor_fn
    if context.cursor
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/asset_reconciliation_sensor.py", line 154, in from_serialized
    ).deserialize_subset(serialized_subset)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/time_window_partitions.py", line 431, in deserialize_subset
    return TimeWindowPartitionsSubset.from_serialized(self, serialized)
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/time_window_partitions.py", line 1043, in from_serialized
    return TimeWindowPartitionsSubset(partitions_def, json.loads(serialized))
  File "/usr/local/lib/python3.7/site-packages/dagster/_core/definitions/time_window_partitions.py", line 954, in __init__
    check.list_param(key_ranges, "key_ranges", of_type=PartitionKeyRange)
  File "/usr/local/lib/python3.7/site-packages/dagster/_check/__init__.py", line 747, in list_param
    return _check_iterable_items(obj, of_type, "list")
  File "/usr/local/lib/python3.7/site-packages/dagster/_check/__init__.py", line 1648, in _check_iterable_items
    f"Member of {collection_name} mismatches type. Expected {of_type}. Got {repr(obj)} of type "
```

My sample code for reference:

```python
@op(ins={"arg": In(Nothing)}, out={"result": Out(Nothing)})
def foo(context):
    pass

@graph()
def upstream() -> Nothing:
    return foo()

upstream_asset = AssetsDefinition.from_graph(upstream, partitions_def=DailyPartitionsDefinition("2022-11-"))

@op(ins={"arg": In(Nothing)}, out={"result": Out(Nothing)})
def bar(context):
    pass

@graph(ins={"upstream": GraphIn()})
def downstream(upstream: Nothing) -> Nothing:
    return bar(arg=upstream)

downstream_asset = AssetsDefinition.from_graph(downstream, partitions_def=DailyPartitionsDefinition("2022-11-10"))

reconcile = build_asset_reconciliation_sensor(
    asset_selection=AssetSelection.assets(upstream_asset, downstream_asset),
    name="asset_reconciliation_sensor",
)

@repository
def test_repo():
    return [
        upstream_asset, downstream_asset, reconcile
    ]
```

**Comment by yeachan153** [comment]
Thanks for the working on this @sryza! Some nice improvements indeed. I had a couple of other issues / potential discussions. I'll list the issues here and put the discussion points here: https://github.com/dagster-io/dagster/discussions/10689

**Downstream partitions not materialising**
Reconciling worked perfectly when the partitioning scheme was the same. However, when I added different starting dates, for upstream/downstream assets, I had issues getting all the expected downstream assets to materialise. I just changed the partitioning scheme from the sample code above, so it should be replicable as well.

In my test, I set the upstream asset start date set to `2022-11-18` and downstream asset start date to `2022-11-20`. All upstream asset partitions were first materialised (`2022-11-18` - `2022-11-21`) on the first sensor tick. However, only one downstream asset was materialised on the second sensor tick, and no other partitions downstream were materialised:
![image](https://user-images.githubusercontent.com/30076090/203319435-b03b9709-8c8a-4169-bcb4-003c43d0f354.png)

This behaviour wasn't consistent though, so maybe there's a race condition somewhere going on?

This was the case for different partitioning schemes like hourly-on-hourly as well.

For the case when I had a daily partitioned upstream asset and hourly downstream partitions, I couldn't get the 24 downstream partitions to trigger at all. I assume the correct behaviour is for the downstream hourly partitions to kick off once the upstream daily partition materialises?

**Upstream assets are materialised from the start date**
I am not sure if this is intended behaviour, but the sensor triggers/backfills all partitions from the start date for upstream assets. I was a little surprised since this is technically triggering behaviour rather than sensor behaviour, and seems a bit inconsistent with scheduled jobs, where the backfill has to be triggered manually.

**Comment by sryza** [comment]
@yeachan153 - regarding those bugs, would you mind trying it out again using the latest version? We shipped some bugfixes yesterday that might be relevant.

> I am not sure if this is intended behaviour, but the sensor triggers/backfills all partitions from the start date for upstream assets. I was a little surprised since this is technically triggering behaviour rather than sensor behaviour, and seems a bit inconsistent with scheduled jobs, where the backfill has to be triggered manually.

This is the intended behavior. We should probably provide some way of making it optional. Your preference would be for it not to fill these in?
