### ISSUE TITLE
Support authentication and self-signed TLS for Airbyte resource client

### ISSUE THREAD

**Issue by blarghmatey** [dagster-io/dagster#9995]
### What's the use case?

I would like to be able to have an interface to specify authentication details for an Airbyte client (e.g. self-hosted with basic-auth or Airbyte cloud). For the self-hosted situation, it would be useful to be able to optionally disable TLS validation in the case that a self-signed certificate is being used.

### Ideas of implementation

It should be fairly straightforward to add some parameters to the Airbyte resource initialization that passes through to the underlying `requests` library.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by benpankow** [comment]
Hi @blarghmatey, this should hopefully be enabled by #10000, which is releasing with `1.0.13` today:

```python
airbyte_instance = airbyte_resource.configured(
    {
        "host": "localhost",
        "port": "8000",
	"request_additional_params": {
	    "headers": {
	        "my_cool_header": "foobarbaz",
            },
	    "verify": False,
	},
    }
)
```

I'm going to mark as closed, but feel free to reopen if this doesn't end up addressing your use-case.

**Comment by blarghmatey** [comment]
Thanks @benpankow! This is great. Do you have any sense of when the `1.0.13` release will be cut so that I can pull this in?

**Comment by blarghmatey** [comment]
Also, another question here is whether this implementation allows for the `"env": "MY_ENV_VAR"` approach for the values in that dict, for instance to allow for fetching values from the env for the `auth` parameter.

**Comment by benpankow** [comment]
Hi @blarghmatey - the release was intended to ship yesterday but got delayed, it should release today.

You can pass in env vars in your python code, e.g.

```python
airbyte_instance = airbyte_resource.configured(
    {
        "host": "localhost",
        "port": "8000",
	"request_additional_params": {
	    "headers": {
	        "my_cool_header": os.getenv("MY_SUPER_SECRET_HEADER_VALUE),
            },
	    "verify": False,
	},
    }
)
```

Does that suffice for your use-case? If the env var needs to be dynamically specified in the launchpad for example, a [`ConfigMapping`](https://docs.dagster.io/_apidocs/config#dagster.ConfigMapping) might work.

**Comment by blarghmatey** [comment]
Thanks! That will definitely work for my use case, and I'll also take a look at the ConfigMapping approach for any other work we do going forward.
